### ISSUE TITLE
Convert Message in .eml format

### ISSUE THREAD

**Issue by snowiow** [jstedfast/MailKit#100]
Hi,
we're currently trieing to switch from the limilabs mail.dll to mailkit. We already got some stuff converted, but currently we're stuck. We want to to convert all the messages from the inbox to eml(rfc-822) formatted strings, which we need to save in our database. Is such a conversion supported in mailkit?

**Comment by cyroul82** [comment]
Thanks a lot @jstedfast  for your great work and your support on almost every topics 
Your library is so great and very powerful.
