### ISSUE TITLE
Retrieve email link into MimeMessage

### ISSUE THREAD

**Issue by franva** [jstedfast/MailKit#1003]
**Describe the solution you'd like**
When using Gmail API, I was able to have an url in its Thread object which allows me to open that specific email in a browser window. I would like to request Mailkit to include this url into its MimeMessage class so that we can provide this url to customers as a "FYI" link if they would like to see a specific email in Gmail online.

**Describe alternatives you've considered**
I also observed that each email has an ID which looks like this:
https://mail.google.com/mail/u/0/#inbox/FMfcgxwHAZOFGHxBgcpDrsNLvkDgPzDz
(this url is not the same url I mentioned above, the aforementioned url is longer, I will try to find an example url later. I do not have that URL as I have moved from Gmail API to Mailkit completely.)

But I was not able to find it in the current MimeMessage object.

**Comment by jstedfast** [comment]
MimeMessage is meant to be strictly the MIME message object, so this wouldn't fit as a MimeMessage property.

Not sure how I'd get that link anyway, to be honest.

Sorry.

**Comment by jstedfast** [comment]
Also, MailKit depends on MimeKit (which is where MimeMessage lives), so MimeMessage wouldn't be able to use anything that lives in MailKit.

That would require a circular library dependency.

**Comment by franva** [comment]
okie, so it doesn't have to be in MimeMessage, can be in any class which you think relevant.

I will bring back the Gmail Api code to find out where I got the email url and add to this question.

**Comment by franva** [comment]
Here is the screenshot:
![image](https://user-images.githubusercontent.com/5151146/77810076-b0d8ab00-70e6-11ea-8eaa-ce71e0327bf4.png)

You can see the Thread.Id from here.

So how to construct an email link:

"https://mail.google.com/mail/u/0/#inbox/" + thread.Id

then copy and paste the url into your browser it will open that email.
I would like to have this Id in some place where it fits its content.

In essence, I just need the Thread Id from Mailkit or MimeKit.

Is it possible to implement this? Or I think Thread.Id probably has already been included as it's pretty core property. I might just have not found it.

Could you please help from here? 

Appreciated,

Winston

**Comment by jstedfast** [comment]
Try:

```csharp
var threads = client.Inbox.Fetch (0, -1, MessageSummaryItems.GMailThreadId);
threads[0].GMailThreadId.Value;
```

These are all of the properties you can request: http://www.mimekit.net/docs/html/T_MailKit_IMessageSummary.htm

And the associated enums to get each of them can be found here: http://www.mimekit.net/docs/html/T_MailKit_MessageSummaryItems.htm

Each enum value corresponds (mor-or-less) with the equivalent IMessageSummary property.

**Comment by franva** [comment]
Thanks :)

Just wondering why don't we use the ThreadId as the UniqueId when we are doing:
`imapClient.Inbox.Search(bSearch);`

We only need 1 ID for each of the email, why do we need so many different kinds of IDs for a same thing?

**Comment by jstedfast** [comment]
`ThreadId` is an IMAP extension that very few IMAP servers implement and is not unique per message, it is unique per *thread* (aka conversation).

`UniqueId` is the only unique identifier that the core IMAP protocol supports and is unique per-folder, but not globally unique for the account.

The `GMailMessageId` and `GMailThreadId` are IMAP extensions that are only supported by GMail.

**Comment by franva** [comment]
Thanks for your explanation, it makes sense.

Just one thought, in order to retrieve an email, I need to make a call:
`await imapClient.Inbox.GetMessageAsync(emailId);`

But in order to get the GmailThreadId which is just a simple string, I have to make another API call:
`imapClient.Inbox.Fetch(0, -1, MessageSummaryItems.GMailThreadId);`

I would like to save the one API call to optimize the code, 
otherwise if I have 1000 emails to retrieve, the number of API calls will soar from 1000 to 2000!

Could you please help to optimize it?

Thanks

**Comment by jstedfast** [comment]
`imapClient.Inbox.Fetch(0, -1, MessageSummaryItems.GMailThreadId);` gets the value for *all* messages in a single request.

That means you only need to make 1001 calls if you have 1000 messages.

**Comment by franva** [comment]
I tried all Thread IDs, none of them able to get an email.
![image](https://user-images.githubusercontent.com/5151146/77813059-b1c70800-70f9-11ea-9411-7f45ec97d148.png)

Google throws an error:
![image](https://user-images.githubusercontent.com/5151146/77813085-f357b300-70f9-11ea-8645-dfedb1ccfbdd.png)

**Comment by jstedfast** [comment]
Then I guess GMailThreadId is not the same thing as the thread Id from the web API. In that case, I have no idea how to get the information you are looking for.

**Comment by franva** [comment]
okie, thanks for letting know. 

Cheers
