### ISSUE TITLE
[ask] what's the maximum length

### ISSUE THREAD

**Issue by fakhrulhilal** [jstedfast/MailKit#1004]
**Describe the bug**
This's a question rather than a bug. We use our mail client before, which was developed internally. There was a bug when connecting to IMAP having nested subfolder which total character for the path longer than 500 characters. It turns out be issue when reading response (for `a1 LIST "" "*"` command). So we increase the buffer length for that.
Now we use MailKit. The old issue doesn't occur without any change. But we would like to know, what's the maximum depth that's supported by MailKit?

**Platform (please complete the following information):**
 - OS: Windows
 - .NET Runtime: CoreCLR
 - .NET Framework: .NET 4.7
 - MailKit Version: 2.5.1

**To Reproduce**
1. Create IMAP account
2. Under INBOX folder, created nested subfolder as long as the mail server supports
3. Use [`ImapClient.GetFolder(string)`](http://www.mimekit.net/docs/html/M_MailKit_Net_Imap_ImapClient_GetFolder_2.htm)

Example of nested sub folder
```
\---INBOX
|---\---A1234567890123456789
|---|---\---B1234567890123456789
|---|---|---\---C1234567890123456789
|---|---|---|---\---D1234567890123456789
|---|---|---|---|---\---E1234567890123456789
|---|---|---|---|---|---...
```
Perhaps we can test until `INBOX.A1234567890123456789.B1234567890123456789...Z1234567890123456789`?

**Expected behavior**
It produces expected results. We just want to know what's the maximum supported length?

**Comment by jstedfast** [comment]
The limit should be infinite, but I haven’t tested it, so maybe there is a bug.

**Comment by jstedfast** [comment]
Just to expand on this a bit, I think you are more likely to hit a server limit than a MailKit limit.

**Comment by fakhrulhilal** [comment]
> Just to expand on this a bit, I think you are more likely to hit a server limit than a MailKit limit.

Perhaps. Each mail server has its own limitation. We tested with with [hMailServer](https://www.hmailserver.com/) with 989 total characters and MailKit passes the test. I think we need to define the limitation by our own for safeness. Thank you for your answer.
