### ISSUE TITLE
Access to sharedmailbox

### ISSUE THREAD

**Issue by jerpic** [jstedfast/MailKit#1006]
Hello,

I try to access to the folders of a sharedmailboxes, to do that at the connection step, the login is built like that : user@domaine.com/nameofthesharedmailbox.

The authentication step is Ok, I'm able to read the messages of the main boxe, but unable to find any folder from the sharedmailbox. The variable "SharedNamespaces" is always empty...

The box is an Office365 mailbox.

Is there any specific things to do for Office365?

Regards.

**Comment by jstedfast** [comment]
Are you sure you need to use the shared namespace? If you have to login with the shared mailbox name in the username, most likely you do not.

What is under the PersonalNamespaces?

Do you have a [ProtocolLog](https://github.com/jstedfast/MailKit/blob/master/FAQ.md#q-how-can-i-get-a-protocol-log-for-imap-pop3-or-smtp-to-see-what-is-going-wrong) to take a look at?

**Comment by jerpic** [comment]
Thanks for your quick answer.

Unfortunately, I got 0 in the PersonalNamespaces as well.

SharedNamespaces : 0
PersonalNamespaces : 0

**Comment by jerpic** [comment]
Hi again,

Sorry, It was my bad. I didn't have the right user of the shared mailbox.

Everything works fine now.

Thanks!
