### ISSUE TITLE
An error occurred while attempting to establish an SSL or TLS connection

### ISSUE THREAD

**Issue by harshendra181** [jstedfast/MailKit#1007]
**Is your feature request related to a problem? Please describe.**
An error occurred while attempting to establish an SSL or TLS connection.
This usually means that the SSL certificate presented by the server is not trusted by the system for one or more of
the following reasons:
1. The server is using a self-signed certificate which cannot be verified.
2. The local system is missing a Root or Intermediate certificate needed to verify the server's certificate.
3. A Certificate Authority CRL server for one or more of the certificates in the chain is temporarily unavailable.
4. The certificate presented by the server is expired or invalid

**Describe the solution you'd like**
below is the sample code where we are trying to connect gmail account but while on connect we are getting error explained above.

```csharp
using (var client = new ImapClient())
{
    client.SslProtocols = System.Security.Authentication.SslProtocols.Tls;
    client.Connect(emailHost, emailPort, SecureSocketOptions.SslOnConnect);
}
```

**Describe alternatives you've considered**
OS Versions        : Microsoft Windows NT 6.2.9200.0
runtime Vertion : 4.7

**Additional context**

**Comment by jstedfast** [comment]
What port are you connecting to? Have you read the [FAQ](https://github.com/jstedfast/MailKit/blob/master/FAQ.md#SslHandshakeException)?

**Comment by harshendra181** [comment]
Secure port 993, also configuration is working on local and different server

**Comment by jstedfast** [comment]
Are you sure that this IMAP server supports TLS 1.0 as opposed to 1.1 or 1.2 or 1.3?

TLS 1.0 is no longer considered secure if you weren’t aware and so many servers have phased it out.

Thirdly, have you tried writing your own ServerCertificateValidationCallbacj to see what errors it is getting?

**Comment by harshendra181** [comment]
Thank you for your response.  But have tried all the suggested points and
even we have not recieved any certificate error also during server
certificate validation call back

**Comment by jstedfast** [comment]
Did you try setting [CheckCertificateRevocation](http://www.mimekit.net/docs/html/P_MailKit_IMailService_CheckCertificateRevocation.htm) to `false`?

If you've really tried everything from the FAQ, then your only option left is to file a bug report against .NET's SslStream.

I can't help you any further.
