### ISSUE TITLE
Forwarded flag

### ISSUE THREAD

**Issue by atiyka** [jstedfast/MailKit#1009]
I'd like to ask, what is recommended to set the forwarded flag?

I checked what other platforms use, and they sets the 7. bit (int 64), in the MailKit's `MessageFlags` enum that value is the `UserDefined`. So I tried to pass that value to `AddFlags()` method and it throw an exception: 

> No flags were specified. Parameter name: flags

Then I checked what happens when I set the forwarded flag on other platforms (Android - Mailcore). It sets the int 64 (7. bit to 1), but when I sync the flags with MailKit, in the MessageFlags 
 that bit is not set. Instead it returns among `Keywords` field an entry named `$Forwarded`.

Okay, I tried to pass this keyword, when I set the flags, like:

> imapFolder.AddFlags(uids, MessageFlags.UserDefined, new HashSet<string> { "$Forwarded" }, false);

The problem with this is that, when I sync with Mailcore (in my Android app), it doesn't gets that the forwarded flag is set.

Did I miss something? If not, than this could be an improvement request to be able to set the forwarded flag as a simple flag, like answered.

Thanks!

**Comment by jstedfast** [comment]
The fact that both MailKit and MailCore use bit-wise flags for the core IMAP flags is a coincidence, so I would not expect them to use the same bits to represent the same flags. If they do, that's just another coincidence of random luck ;-)

In MailKit, `MessageFlags.UserDefined` is a special flag that is ONLY used in `ImapFolder.AcceptedFlags` and/or `ImapFolder.PermanentFlags`.

This flag maps to cases where IMAP uses `\*` as aa wild-card for user-defined flags (aka keywords).

`$Forwarded` is not a flag that comes built-in to IMAP.

IMAP only supports the following flags:

```
\Answered
\Deleted
\Draft
\Flagged
\Recent
\Seen
```

Anything other than those is user (or, more likely, mail-client) defined.

The correct way to add a custom keyword to a message (or group of messages) is like this:

```csharp
imapFolder.AddFlags(uids, MessageFlags.None, new HashSet<string> { "$Forwarded" }, false);
```

Note that `MessageFlags.UserDefined` is not used.

That said, your code should still work afaik.

Can you get a protocol log to verify that the $Forwarded flag is being set by MailKit?

**Comment by atiyka** [comment]
Thank you for your quick response! It is very useful.

Here is the protocol log, but as I see, the flag is set correctly.
[imap_log.log](https://github.com/jstedfast/MailKit/files/4461879/imap_log.log)

Adding the flag works fine, I can get it as well. Probably I have to modify something on the Android project to get the forwarded flag based on custom user flags, or check the mailcore, how it sets exactly that flag.

**Comment by jstedfast** [comment]
Glad it's being set correctly by MailKit :-)

I've been considering adding `MessageFlags` for `$Forwarded`, `$Junk` and `$NotJunk` which, while not official IETF-defined standard flags, are fairly commonly used by mail client software.

The reason I haven't (yet), is because not all clients agree on these flag names (I.O.W. I've seen some clients use different names) and I want to avoid the nightmare of trying to map different names to the same bits depending on which ones are currently being used on the server (and then, of course, you get to deal with the fun where the user has used multiple clients that each used different flag names for forwarded/junk/notjunk).
