### ISSUE TITLE
Ssl2, Ssl3, Tls1 Not implemented as SSL Algorithm

### ISSUE THREAD

**Issue by nemocrk** [jstedfast/MailKit#1012]
Trying to connect to a SMTPS Server i have the following error:

>An error occurred while attempting to establish an SSL or TLS connection.
>
>This usually means that the SSL certificate presented by the server is not trusted by the system for one or more of
>the following reasons:
>
>1. The server is using a self-signed certificate which cannot be verified.
>2. The local system is missing a Root or Intermediate certificate needed to verify the server's certificate.
>3. A Certificate Authority CRL server for one or more of the certificates in the chain is temporarily unavailable.
>4. The certificate presented by the server is expired or invalid.
>
>Another possibility is that you are trying to connect to a port which does not support SSL/TLS.
>
>It is also possible that the set of SSL/TLS protocols supported by the client and server do not match.
>
>See https://github.com/jstedfast/MailKit/blob/master/FAQ.md#SslHandshakeException for possible solutions.

even if using an online certificate tester the certifacte seems to be valid [https://www.sslshopper.com/ssl-checker.html#hostname=smtps.aruba.it:465](test).

digging around i found that the outer exception was wrong and the real exception talk about "no common algorithm avilable" (i'm using an italian version of VS so i see translated messages) and is thrown by 
`await ssl.AuthenticateAsClientAsync (host, ClientCertificates, SslProtocols, CheckCertificateRevocation).ConfigureAwait (false);` in SMTPClient.cs Line 1014

digging deeper i found that the only SslProtocols valid are Tls11 and Tls22.

now the question, is there any reason why you are using only that 2 protocols?
trying to add other protocols the error seems resolved.

So 2 issues:
1. Why is not declared:
`SslProtocols.Ssl2 | SslProtocols.Ssl3 | SslProtocols.Tls` in MailService.cs Line 53 and 55

 - OS: Windows 10
 - .NET Framework: .NET 4.6.1
 - MailKit Version: 2.6.0

`
            SmtpClient client = new SmtpClient();
            await client.ConnectAsync("smtps.aruba.it, 465, true);`

**Comment by jstedfast** [comment]
That just means the only protocols supported by the server are TLS 1.1 and TLS 1.2.

This makes sense because TLS 1.0 is deemed insecure these days.

**Comment by nemocrk** [comment]
maybe it's a my mistake, 
the original line is:
>const SslProtocols DefaultSslProtocols = SslProtocols.Tls11 | SslProtocols.Tls12 | SslProtocols.Tls13;

editing it with

>const SslProtocols DefaultSslProtocols = SslProtocols.Tls11 | SslProtocols.Tls12 | SslProtocols.Ssl2 | SslProtocols.Ssl3 | SslProtocols.Tls;

let the connection work safely, 
so the client only support TLS 1.1 and TLS 1.2 and the server has worse feature.

so 2 more questions:
- so it's safe for me fork your code to get that capabilities?
 - what about the misleading exception?

Maybe could be a feature to let the user choose what encryption is supported

**Comment by jstedfast** [comment]
Oh, thanks for the explanation - I clearly misunderstood your earlier comment. Sorry about that!

MailKit doesn't include SSL v2, SSL v3, or TOLS 1.0 because those protocols are obsolete and have been deemed "insecure".

> so it's safe for me fork your code to get that capabilities?

Sure, you can fork it to change the default, but why bother? Just do:

```csharp
using (var client = new SmtpClient ()) {
    client.SslProtocols = SslProtocols.Tls11 | SslProtocols.Tls12 | SslProtocols.Ssl2 | SslProtocols.Ssl3 | SslProtocols.Tls;
    // now use the SmtpClient as normal
}
```

> what about the misleading exception?

Meh. The number of possible explanations for an SSL handshake exception are numerous, but I suppose I can add that the the growing list of reasons in the exception message...

Ideally people wouldn't actually hit that issue since servers shouldn't be using old obsolete SSL/TLS protocols, but oh well.
