### ISSUE TITLE
smtp timeout/can't connect with italian provider

### ISSUE THREAD

**Issue by luca7766** [jstedfast/MailKit#1014]
**Describe the bug**

Not sure if it's a bug, I'm using mailkit on visual studio 2019 (visual basic .net) and windows form project, I successfully used mailkit to send email using various smtp servers of major italian providers (and Gmail smtp too), but after many tries I'm unable to send with a specific one, Privately I can provide you a temporary account to test with, this smtp server works good with common mail clients (thunderbird, outlook, etc.).

This is the configuration of the smtp:
(SMTP): smtps.aruba.it
account: your mail
Password: your password
Use SSL: ON
Authentication: Password
Port: 465

When doing this (the same code works OK for all the others smtp servers)
smtp.Connect(SMTPserver, SMTPport, SecureSocketOptions.Auto)

I get this error (the smtp log created by mailkit is empty):

---------
MailKit.Security.SslHandshakeException: 'An error occurred while attempting to establish an SSL or TLS connection.

This usually means that the SSL certificate presented by the server is not trusted by the system for one or more of
the following reasons:

1. The server is using a self-signed certificate which cannot be verified.
2. The local system is missing a Root or Intermediate certificate needed to verify the server's certificate.
3. A Certificate Authority CRL server for one or more of the certificates in the chain is temporarily unavailable.
4. The certificate presented by the server is expired or invalid.

Another possibility is that you are trying to connect to a port which does not support SSL/TLS.

It is also possible that the set of SSL/TLS protocols supported by the client and server do not match.

See https://github.com/jstedfast/MailKit/blob/master/FAQ.md#SslHandshakeException for possible solutions.
---------

I wanted to try this:
client.ServerCertificateValidationCallback = (s,c,h,e) => true;
but I don't know how to use it in vb, i'm not an expert programmer, thanks in advance, it's not urgent. best regards

**Platform (please complete the following information):**
 - OS: [e.g. Windows, Linux, MacOS, iOS, Android, Windows Phone, etc.]
 - .NET Runtime: [e.g. CoreCLR, Mono]
 - .NET Framework: [e.g. .Net Core, .NET 4.5, UWP, etc.]
 - MailKit Version: 

- Windows 10 1903, latest .net framework, latest mailkit version

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by jstedfast** [comment]
What you need to do is this:

```csharp
smtp.SslProtocols = SslProtocols.Tls1 | SslProtocols.Tls11 | SslProtocols.Tls12;
smtp.Connect(SMTPserver, SMTPport, SecureSocketOptions.Auto)
```

By default, MailKit does not support TLS 1.0 because it is no longer secure. Your SMTP server, unfortunately, *only* supports TLS 1.0 and does not support the newer versions (1.1 or 1.2).

**Comment by luca7766** [comment]
wow, thanks a lot, with this
smtp.SslProtocols = SslProtocols.Tls
or this
smtp.SslProtocols = SslProtocols.Default
it works like a charm, is was almost sure they uses tls 1.2, but maybe it's just for the certified mail
