### ISSUE TITLE
I am using IMAP mailkit to read email. I want to show only reply email text without original email content. 

### ISSUE THREAD

**Issue by amitmanekar19** [jstedfast/MailKit#1017]
I am using IMAP mailkit to read email. I want to show only reply email text without original email content. 
How would I remove original mail content from mail reply?
OR
How Would I just read reply text rather than complete email?

Here is my code:

using (var client = new ImapClient())
{
client.Connect("-----------------", 993, SecureSocketOptions.SslOnConnect);client.Authenticate("-----------", "------------");

            client.Inbox.Open(FolderAccess.ReadOnly);

            // search for messages where the Subject header contains either "MimeKit" or "MailKit"
            var query = SearchQuery.SubjectContains("008").Or(SearchQuery.SubjectContains("008"));
            var uids = client.Inbox.Search(query);
            foreach (var uid in uids)
            {
                var message = client.Inbox.GetMessage(uid);
                
                // write the message to a file
                Console.WriteLine(message.HtmlBody);
                Console.WriteLine("-------------------------");
            }
            Console.Read();
client.Disconnect(true);
        }

Need urgent help..

**Comment by jstedfast** [comment]
You asked this yesterday and I answered.

**Comment by jstedfast** [comment]
Duplicate of https://github.com/jstedfast/MailKit/issues/1016
