### ISSUE TITLE
MailKit.Security.AuthenticationException for gmail

### ISSUE THREAD

**Issue by Amitloh** [jstedfast/MailKit#1018]
**Describe the bug**
MailKit.Security.AuthenticationException for gmail imap- This was working 100 times may be and then suddenly it stopped working. Is there any daily limit?
**Platform (please complete the following information):**
 - OS: [e.g. Windows, Linux, MacOS, iOS, Android, Windows Phone, etc.]
windows
 - .NET Runtime: [e.g. CoreCLR, Mono]
 - .NET Framework: [e.g. .Net Core, .NET 4.5, UWP, etc.]
.net 4.6
 - MailKit Version: 
latest

**To Reproduce**

**Expected behavior**
The gmail login via imap should work but it stopped working after working fine for 2 days with
auth exception.

```csharp
client.Connect("imap.gmail.com", 993, true);
client.Authenticate("ouremail@gmail.com", "ourpwd");
```

**Screenshots**

**Additional context**

**Comment by jstedfast** [comment]
> This was working 100 times may be and then suddenly it stopped working. Is there any daily limit?

You'd have to ask the GMail developers and/or admins (which I'm not sure how you would do that).

100 times is a lot, but it's probably not "excessive".

My recommendation would be to start with getting a [protocol log](https://github.com/jstedfast/MailKit/blob/master/FAQ.md#q-how-can-i-get-a-protocol-log-for-imap-pop3-or-smtp-to-see-what-is-going-wrong).

My next step would probably be to check your Gmail settings to make sure that it is configured to allow "Less secure apps".

Then, if you are working on trying to write an app that is meant for more than just you and your Gmail account, I would probably recommend switching to OAuth2 authentication by following my [guide](https://github.com/jstedfast/MailKit/blob/master/GMailOAuth2.md).

Moving to OAuth2 *may* solve your issue (hard to know for sure).

**Comment by Amitloh** [comment]
Thank you!!
