### ISSUE TITLE
Filter Undeliverable and Delay Delivery Emails

### ISSUE THREAD

**Issue by sumanrajpura** [jstedfast/MailKit#1020]
**Is your feature request related to a problem? Please describe.**
I am parsing emails from outlook account. In that I am receiving many emails that of Delivery Failure or Delay Delivery from postmaster account of that email domain. 

**Describe the solution you'd like**
Is there any way that I can detect such emails based on its status or email type?

**Describe alternatives you've considered**
As off now I am filtering such emails based on Subject like "Undeliverable:" or "Mail delivery failed : " or based on the from email address like "postamaster@domain.com"

**Additional context**

**Comment by jstedfast** [comment]
I would probably need to see an example of a raw message that you are processing, but my guess is that it would have a top-level Content-Type of `multipart/report` with a `report` parameter of `deliver-status`:

```
Content-Type: multipart/report; report-type=delivery-status; boundary=...
```
