### ISSUE TITLE
When adding MailKit 2.6.0.0 Visual Studio keeps showing it as version 2.5.0.0

### ISSUE THREAD

**Issue by Sicos1977** [jstedfast/MailKit#1021]
I thought this was a bug in one om my projects but I have the same problem in another VS project. For some reason VS keeps showing it as version 2.5.0.0

I use the NET46 version.

![image](https://user-images.githubusercontent.com/6692947/81648580-37dfa980-942f-11ea-93a9-3c604916600e.png)

![image](https://user-images.githubusercontent.com/6692947/81648697-652c5780-942f-11ea-9f5f-cff15a84e972.png)

**Comment by Sicos1977** [comment]
Ah that explains it, I had some problems getting the code compiled (resolved now) and that version number was driving me nuts... because visual studio kept complaining that it could not find version 2.5.0.0 :-) ... I already readded the nuget packages a few times.

**Comment by jstedfast** [comment]
haha, sorry about that ;-)
