### ISSUE TITLE
How get Threads with correct reference count 

### ISSUE THREAD

**Issue by SmbatChilingaryan** [jstedfast/MailKit#1028]
**How can I get message list like in Gmail under 6 sec**
now I do like this

```csharp
var gmailMessages = currentFolder.Fetch(0, -1, MessageSummaryItems.UniqueId |
                                                             MessageSummaryItems.GMailMessageId |
                                                             MessageSummaryItems.GMailThreadId)
                                                            .OrderByDescending(o => o.UniqueId)
                                                            .ToList();
```
**12 sec**

```csharp
// apply group to get threads
var groupedList = gmailMessages.GroupBy(g => g.GMailThreadId)
    .Select(s => s.Key.Value)
    .ToList();
//apply paging to reduce ids
var finalListForMerge = groupedList.Skip(paging.skip).Take(pageSize).ToList();

//then open all folder to find references as message in Inbox can have referenc in otheer folders
var allMail = imap.GetFolder(SpecialFolder.All);
allMail.Open(FolderAccess.ReadOnly);

var uIds = allMail.Fetch(0, -1, MessageSummaryItems.UniqueId |
    MessageSummaryItems.GMailThreadId)
    .Where(w=> finalListForMerge.Contains(w.GMailThreadId.Value))
    .Select(s => s.UniqueId).ToList();
```

**14sec***

```csharp
//get messages by Uis with correct references
var messageSummary = allMail.Fetch(uIds, MessageSummaryItems.All |
     MessageSummaryItems.References |
     MessageSummaryItems.PreviewText |
     MessageSummaryItems.UniqueId |
     MessageSummaryItems.Flags |
     MessageSummaryItems.GMailLabels |
     MessageSummaryItems.GMailMessageId |
     MessageSummaryItems.GMailThreadId)
     .OrderByDescending(o => o.UniqueId)
     .ToList();
```

**All takes more then 30 sec in case 40.000 messages in inbox.
What is the optimal code to get messages more faster?
Thanks**

**Comment by jstedfast** [comment]
The first rule in making something faster is to not fetch the same information over and over again.

Why keep fetching stuff from the server instead of fetching stuff once and then filtering what you have locally?

**Comment by SmbatChilingaryan** [comment]
I'm doing like you say. 
1. Fetch (0, -1) then  (get ids takes about 12-16 sec)
2. Group by GmailThreadIds (local)
3. Apply paging (local)
now I have GmailThreadIds for one page from Inbox folder but with incorrect referenc count right? I need to find all relations for above id's and should search in SpecialFolder.All. SO
4. SpecialFolder.All.Fetch (0, -1) then  (get ids takes about 16-18sec)
5. find All needed uIds from
6.Fetch (uIds, MessageSummaryItems.All |
                         MessageSummaryItems.References ........)

**my vulnerable point 1 and 4.**
Is it possible to get GmailThreads with correct ref count with another way?

if yes Please provide an exaple.

Note* I get this problem when user have more then 40.000 messages.

Thanks.

**Comment by jstedfast** [comment]
Are you writing an email client? If so, why aren't you caching message summaries locally?

**Comment by jstedfast** [comment]
My next suggestion would be to do away with trying to treat folders individually and instead just use the `All` folder. You can filter out messages with labels that don't include the label for your particular folder, thereby drastically reducing useless IMAP query traffic.
