### ISSUE TITLE
An error occurred while attempting to establish an SSL or TLS connection

### ISSUE THREAD

**Issue by xiaobaxiang** [jstedfast/MailKit#1029]
**Describe the bug**
An error occurred while attempting to establish an SSL or TLS connection.\n\nThis usually means that the SSL certificate presented by the server is not trusted by the system for one or more of\nthe following reasons:\n\n1. The server is using a self-signed certificate which cannot be verified.\n2. The local system is missing a Root or Intermediate certificate needed to verify the server's certificate.\n3. A Certificate Authority CRL server for one or more of the certificates in the chain is temporarily unavailable.\n4. The certificate presented by the server is expired or invalid.\n\nIt is also possible that the set of SSL/TLS protocols supported by the client and server do not match.\n\nSee https://github.com/jstedfast/MailKit/blob/master/FAQ.md#SslHandshakeException for possible solutions.\n

**Platform (please complete the following information):**
 - OS: [e.g. Windows, Linux, MacOS, iOS, Android, Windows Phone, etc.]
Linux
 - .NET Runtime: [e.g. CoreCLR, Mono]
CoreCLR
 - .NET Framework: [e.g. .Net Core, .NET 4.5, UWP, etc.]
NetCore2.2
 - MailKit Version: 

**To Reproduce**
1.On winserver is ok.On Linux get an error
**Expected behavior**

**Screenshots**

**Additional context**

**Comment by xiaobaxiang** [comment]
> Did you read the link provided for possible solutions?
yes,all the SecureSocketOptions I have test,but fail.I use two aliyun linux server test.they all have the same error.

**Comment by jstedfast** [comment]
The documentation that the link points to has more than just "try these different SecureSocketOptions".

The Linux servers have this problem because they do not have SSL certificate stores that contain the Root CA certificate that your mail server was signed with and so the authenticity of the mail server's certificate cannot be established.

**Comment by xiaobaxiang** [comment]
> The documentation that the link points to has more than just "try these different SecureSocketOptions".
> 
> The Linux servers have this problem because they do not have SSL certificate stores that contain the Root CA certificate that your mail server was signed with and so the authenticity of the mail server's certificate cannot be established.

So,How to solve this problem?

**Comment by jstedfast** [comment]
Read what I wrote at https://github.com/jstedfast/MailKit/blob/master/FAQ.md#SslHandshakeException

This is the link from the exception - it explains how to fix the issue.

**Comment by xiaobaxiang** [comment]
ok,I have solved this problem 
 by setting SecureSocketOptions.StartTls 
client.SslProtocols = SslProtocols.Tls | SslProtocols.Tls11 | SslProtocols.Tls12;
client.ServerCertificateValidationCallback = (s,c,h,e) => true; 

thans a lot

**Comment by 0xced** [comment]
I solved this issue by installing the `ca-certificates` package (using the `debian:buster` docker image):

```sh
apt update && apt install -y ca-certificates
```

This option might be worth mentioning in the FAQ.
