### ISSUE TITLE
MailKit encoding issue

### ISSUE THREAD

**Issue by IvanBarbaric992** [jstedfast/MailKit#1030]
Hello @jstedfast, I am using nuget Mailkit and everything works perfectly except French language encoding where I get an email with bad encoding of é and similar letters, this is the result: 
_Quelqu'un vient de r�pondre � votre commentaire,_ 
What do you suggest how to solve this? English and Italian works perfectly.  Thank you in advance.

_Originally posted by @IvanBarbaric992 in https://github.com/jstedfast/MailKit/issues/497#issuecomment-636498289_

**Comment by jstedfast** [comment]
Show me your code and I'll take a look.

**Comment by IvanBarbaric992** [comment]
` public class MailRepositoryManagementService : IMailRepositoryManagementService
    {
        private string _smtpServer;
        private int _port;
        private string _userName;
        private string _password;
        private bool _ssl;

        public MailRepositoryManagementService(string smtpServer, int port, string userName, string password, bool ssl)
        {
            _smtpServer = smtpServer;
            _port = port;
            _userName = userName;
            _password = password;
            _ssl = ssl;
        }
        public async Task<Message.Response> SendMailAsync(Message.Request message)
        {
            var messageSent = new Message.Response();
            var mailMessage = CreateEmailMessage(message);
            messageSent.Success = await SendAsync(mailMessage);
            return messageSent;
        }
        public async Task<Message.Response> SendMailAsync(Message.Request message, Template template)
        {
            var messageSent = new Message.Response();
            var mailMessage = CreateEmailMessage(message, template);
            messageSent.Success = await SendAsync(mailMessage);
            return messageSent;
        }

        private MimeEntity GenerateEmailBodyWithOrWithoutTemplate(Message.Request message, Template template)
        {
            var builder = new BodyBuilder();
            string body = string.Empty;
            if (template != null)
            {
                using (StreamReader reader = new StreamReader(template.Path))
                {
                    body = reader.ReadToEnd();
                }

            
                foreach (KeyValuePair<string, string> entry in template.LocalizedStrings)
                {
                    body = body.Replace($"{{{entry.Key.ToLower()}}}", entry.Value);
                }
                if(message.LinkToWebPage != null)
                {
                    body = body.Replace("{actionlink}", message.LinkToWebPage);
                }
            }
            else
            {
                if (message.Content != null)
                {
                    body = message.Content;
                }
            }

            builder.HtmlBody = body;

            return builder.ToMessageBody();
        }

        private MimeMessage CreateEmailMessage(Message.Request message, Template template = null)
        {
            var emailMessage = new MimeMessage();

            if (message.CC.Count > 0)
            {
                emailMessage.Cc.AddRange(message.CC);
            }
            if (message.BCC.Count > 0)
            {
                emailMessage.Bcc.AddRange(message.BCC);
            }
            emailMessage.From.Add(new MailboxAddress(message.From));
            emailMessage.To.AddRange(message.To);
            emailMessage.ReplyTo.Add(new MailboxAddress(message.ReplyTo));
            emailMessage.Subject = message.Subject;

            emailMessage.Body = GenerateEmailBodyWithOrWithoutTemplate(message, template);

            return emailMessage;
        }
        private async Task<bool> SendAsync(MimeMessage mailMessage)
        {
            var isSent = false;
            using (var client = new SmtpClient())
            {
                try
                {
                    await client.ConnectAsync(_smtpServer, _port, SecureSocketOptions.Auto).ConfigureAwait(false);
                    client.AuthenticationMechanisms.Remove("XOAUTH2");
                    client.Authenticate(_userName, _password);

                    await client.SendAsync(mailMessage).ConfigureAwait(false);
                    isSent = true;
                }
                catch
                {
                    isSent = false;
                }
                finally
                {
                    await client.DisconnectAsync(true).ConfigureAwait(false);
                    client.Dispose();
                }
            }
            return isSent;
        }
    }`

Everything works as expected except when you get French language, then I get wrong character enc/dec... Subject, body, preheader everything(gmail, outlook, yahoo, ...) Thank you in advance

**Comment by jstedfast** [comment]
Try calling `mailMessage.Prepare (EncodingConstraint.SevenBit);` right before calling `client.SendAsync(mailMessage)`.

**Comment by IvanBarbaric992** [comment]
I have already tried that, somewhere on github I have seen your suggestion to do that but no success.

**Comment by jstedfast** [comment]
Are you sure that the text you are loading isn't already "corrupted"? Your code will only work if those template files were saved in UTF-8 format but they might not be. They might be in iso-8859-1 or iso-8859-15 or perhaps a windows-cp1251 (or is it 1252? I can never keep them straight) charset.

**Comment by IvanBarbaric992** [comment]
True, I have checked now, they are already corrupted, but not the template, strings that are comming from json file to mailkit html body have something wrong with encoding, sorry and thank you a lot.
