### ISSUE TITLE
What is the correct Google scope to authenticate using GMail OAuth2.0 in MailKit (To just send email) ?

### ISSUE THREAD

**Issue by marcelcamargo** [jstedfast/MailKit#1032]
Hello, how are you?

I will use Google OAuth authentication only to send emails, which scope should I use to obtain authorization in the authentication process? (https://developers.google.com/gmail/api/auth/scopes)

I did a test using the specific scope for sending (https://www.googleapis.com/auth/gmail.send), but it didn't work.

Note: I did a test using the full scope of gmail (https://mail.google.com/) and it worked. However, I would not like to use it because the application verification process for this scope is very bureaucratic, as it is a restricted scope. In addition, in my application I do not use all functions that the scope allows me, such as exclusion.

Thank you.

**Comment by jstedfast** [comment]
The only one you can use if you want to send mail via SMTP is the `https://mail.google.com/` scope.

The `gmail.send` scope (and all of the other scopes) are limited to their HTTP API.
