### ISSUE TITLE
Suddenly  'The IMAP server has unexpectedly disconnected.' constantly appears

### ISSUE THREAD

**Issue by dpinart-uxland** [jstedfast/MailKit#1034]
Hi,

Suddenly, today, I started receviing the  'The IMAP server has unexpectedly disconnected.' error. I'm connecting to a GMail account using OAuth2. It has been working fine for last 2 months but today I have no chance to authenticate.
Credentials are fine because I can use GMail Api to check for a label

**Comment by dpinart-uxland** [comment]
That's weird.
If I change the gmail account, is working properly. Can't see why a gmail account is not working

**Comment by jstedfast** [comment]
The error you are seeing just means that the TCP/IP connection is being lost. That could mean a network problem or it could mean that the server is dropping the connection for some reason.

GMail and other public mail servers will sometimes drop connections if the account is making too many requests in an attempt to throttle that account.

What "too many requests" is, as a number, is not something that I have had the time to figure out.

If you can use a different account just fine, then that is the likely case.

Hope that answers your question.
