### ISSUE TITLE
Provide DKIM and ARC compiler options

### ISSUE THREAD

**Issue by hlsantos** [jstedfast/MailKit#1037]
In issue https://github.com/jstedfast/MailKit/issues/1036, I noted I am was getting compiler errors related to DKIM ARC protocol components.

Let me add this major point,.  ARC is experimental and due to its complexity to implement and extremely high mail overhead, and more importantly there is no established purpose on what good it will do, I do not envision it will be widely supported.  It is my technical opinon, I follow the Working Groups, have been involved with DKIM, SSP, ADSP and DMARC since the begining and ARC is not something I am looking forward to.  Santronics's Wildcat SMTP will not support it anytime soon.  It will take a number of years before it has any payoff whatsoever.  Currently it does not have value other to trace who broke the DKIM signature.  It doesn't resolve what the #1 problem people are having with DKIM, namely indirect mail 3rd party signature problems mostly seen with list systems.

Nonetheless, in addition to the idea that any SMTP client should not be reliant on experiment protocols which, without any doubt, will be a moving target,   I highly suggest that compiler options are provided to avoid ARC compilation.  Although DKIM is more stable, I would also suggest to add a compiler option for DKIM as well    But ARC?   Its getting in your MailKits way. I would probably make it a separate assembly.  

Keep in mind,  MSDN is recommending not to use .Net SmtpClient and to consider using MailKit instead.  In the case of win-acme, it really just needs a simple SMTP client without the massive overhead of ARC.  DKIM is fine but there are going to be many small smtp client needs where DKIM is not required, and especially the ARC junk --- no I am not a fan of ARC and the Google folks behind it are very aware of my position on ARC.

Thanks for the consideration to make MailKit simpler to compile and without an ARC requirement.

**Comment by jstedfast** [comment]
For what it's worth, MailKit's SmtpClient doesn't actually use DKIM -or- ARC. You have to manually sign messages before sending via SmtpClient in order for them to be signed. It's not something that is automatic.

Both features are also such tiny amounts of additional code that it doesn't seem worthwhile to make them compile options. People mostly just use the nugets anyway.

**Comment by hlsantos** [comment]
Yes, but by the same token of it only adding a small amount of code, it should not be a (compiler of choice) show  stopper for a much larger WASC need than having it incorporate ARC.  

It is important to note, ARC it is a experimental protocol.  It could be abandoned for lack of utility.  Just this morning, someone just pointed this out in the DMARC working group:

"ARC is not going to solve the mailing list problem any time soon."

- https://mailarchive.ietf.org/arch/msg/dmarc/td5afnWgTb49g6hYqnFzW7e4Zz0/

Let me spend sometime today with build pragmas:

#define USE_ARC
...
#if USE_ARC 
arc code
#endiif 

Thanks

**Comment by hlsantos** [comment]
Closing this issue.  No need to add the compiler option.
