### ISSUE TITLE
Send mail with envelope

### ISSUE THREAD

**Issue by biancapop** [jstedfast/MailKit#1039]
Hello,
I am writing a c# program to relay mails from one server to Internet and I use MailKit to send the mail to its destiny or to local postfix depending on the domain.

I have a problem with duplicated mail, let me explain:
Let's say I try to send an email to a@a.com and b@b.com from a plesk webmail to the internet. I saw that plesk creates 2 calls with different envelopes: one for a@a.com and other for b@b.com. So when I get the mail in the relay I parse it with MIMEKit and I send it with MailKit but MailKit (as I read in another issue here on github) makes a RCPT TO call for each mail in to, cc and bcc. So in the end a@a.com and b@b.com get the same mail twice:
 - envelope rcpt to a@a.com - message to: a@a.com and b@b.com - two mails are sent: one to a@a.com and another to b@b.com
 - envelope rcpt to b@b.com - message to: a@a.com and b@b.com - two mails are sent: one to a@a.com and another to b@b.com

I can remove the mails from the to, cc and bcc message header but I don't think this is a good solution because then the reciver won't know it the emails was send only to him or not.

Is there something that I am missing? 
Thank you very much!!!

**Comment by jstedfast** [comment]
There are multiple Send() methods: http://www.mimekit.net/docs/html/Overload_MailKit_MailTransport_Send.htm

Some of them take a list of addresses that you want to relay the message to. When these methods are used, the SmtpClient does not use the To/Cc/Bcc headers.

**Comment by biancapop** [comment]
Great!!! This solved my problem in 1 sec!! Thank you very much!
