### ISSUE TITLE
IMailFolder.Search() does not correctly match the exact pattern of SearchQuery.BodyContains([...])

### ISSUE THREAD

**Issue by ole1986** [jstedfast/MailKit#1043]
**Describe the bug**

When using `IMailFolder.Search()` with `SearchQuery.BodyContains("--- BEGIN DATA ---")` it also seam to match the following pattern

```
[...]
BEGIN DATA ---
[...]
```

**Platform (please complete the following information):**
 - OS: Windows
 - .NET Runtime: CoreCLR
 - .NET Framework: .Net Core
 - MailKit Version: 2.7.0 (from nuget)

**To Reproduce**
1. Create a SearchQuery E.g. `SearchQuery.NotSeen.And(SearchQuery.NotDeleted).And(SearchQuery.BodyContains("--- BEGIN DATA ---"));`
2. Apply the Search to `ImapClient.Inbox.Search([...])`
3. Send email with content `BEGIN DATA ---`
4. 

**Expected behavior**
Should not match "BEGIN DATA ---" but only "--- BEGIN DATA ---"

**Comment by jstedfast** [comment]
Nothing I can do about that. This is a "feature" of the IMAP server you are using.
