### ISSUE TITLE
Apparent security issue when sending via gmail smtp server using oauth2

### ISSUE THREAD

**Issue by solutionj** [jstedfast/MailKit#1044]
Hi,

I'm using Visual Studio 2019 to send emails via smtp using the oauth2 security standard. Coding is in c#.

I have Mimekit v2.8 installed (and Mailkit v2.7).

When I test the program it gets to this connect statement 

 client.Connect(MyHost, 587, SecureSocketOptions.None);

where MyHost is "smtp.gmail.com"

and errors as follows:

Exception thrown: 'System.NotSupportedException' in MailKit.dll
Exception thrown: 'System.NotSupportedException' in mscorlib.dll
System.NotSupportedException: The SMTP server does not support authentication.
   at MailKit.Net.Smtp.SmtpClient.<AuthenticateAsync>d__67.MoveNext() in D:\src\MailKit\MailKit\Net\Smtp\SmtpClient.cs:line 612

I don't know if this is part of the same problem, but if I put a breakpoint into the code then as soon as I step to any statement using Mailkit or Mimekit references I get a screen come up ...

![image](https://user-images.githubusercontent.com/33104886/86392980-3d6da900-bc94-11ea-9dcd-b695fef898f5.png)

**Platform (please complete the following information):**
 - OS: Windows 10
 - .NET Runtime: [e.g. CoreCLR, Mono]
 - .NET Framework: [e.g. .Net Core, .NET 4.5, UWP, etc.]

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by jstedfast** [comment]
That's because smtp.gmail.com does not support any authentication mechanisms when not in TLS mode.

You need to connect using `SecureSocketOptions.StartTls`.

**Comment by solutionj** [comment]
Thanks for getting back to me. Having made that change there's still a problem:

Exception thrown: 'MailKit.Security.AuthenticationException' in MailKit.dll
Exception thrown: 'MailKit.Security.AuthenticationException' in mscorlib.dll
MailKit.Security.AuthenticationException: 334: eyJzdGF0dXMiOiI0MDAiLCJzY2hlbWVzIjoiQmVhcmVyIiwic2NvcGUiOiJodHRwczovL21haWwuZ29vZ2xlLmNvbS8ifQ==
   at MailKit.Net.Smtp.SmtpClient.<AuthenticateAsync>d__67.MoveNext() in D:\src\MailKit\MailKit\Net\Smtp\SmtpClient.cs:line 666

Also, can you please briefly say if these screens I get popping up when using breakpoints are to be expected?

![image](https://user-images.githubusercontent.com/33104886/86394496-98080480-bc96-11ea-9599-e85969727d99.png)

Many thanks for your help.

Cheers
Reg Jackson

**Comment by jstedfast** [comment]
Have you read through and followed the instructions that I outlined in https://github.com/jstedfast/MailKit/blob/master/GMailOAuth2.md ?

> Also, can you please briefly say if these screens I get popping up when using breakpoints are to be expected?

You mean the "MimeMessage.cs not found" window? That's expected because you do not have the source code on your machine - or at least not in the expected location. You have to show Visual Studio where to find the code if you do have it.

**Comment by solutionj** [comment]
Good Morning

Thanks again for coming back to me. Although I’m a “seasoned” programmer I’m very new to c#, and I apologise for asking such a naïve question about the screens popping up!

I have read the information you refer to, but am planning to have another go at this today sometime.

Many thanks for your help and patience.

Kind Regards
Reg

Reg Jackson
• Mobile            +44(0)7900 985343
• Email               reg@solutionj.co.uk<mailto:reg@solutionj.co.uk>
ü Web                http://www.tradabase.co.uk
[SOLUTION J VECTOR LOGO]

[TradaBase22Small]

**Comment by solutionj** [comment]
Success! Thanks for all the help :)
