### ISSUE TITLE
Outlook: Unicode problems in header

### ISSUE THREAD

**Issue by Nielsbishere** [jstedfast/MailKit#1045]
**Describe the bug**
If a message is sent with a UTF8 or unicode encoding in the subject or in the from/to, outlook will display it as garbage characters. I do use the Encoding.UTF8 as the first parameter of MailboxAddress. GMail also displays it correctly.
Is this an outlook bug or is there something else I can do to ensure that they display it correctly?
```cs
                var msg = new MimeMessage();

                msg.From.Add(new MailboxAddress(Encoding.UTF8, sender.Name, sender.MailAddress));
                msg.To.Add(new MailboxAddress(Encoding.UTF8, receiver.Name, receiver.MailAddress));
                msg.Subject = subject;

                var builder = new BodyBuilder() { TextBody = content };

                if (attachments != null)
                    foreach (var attachment in attachments)
                        builder.Attachments.Add(attachment.Name, attachment.Data);

                msg.Body = builder.ToMessageBody();

                var options = FormatOptions.Default.Clone();

                options.International = true;
                options.AllowMixedHeaderCharsets = true;

                client.Send(options, msg);
```

**Platform (please complete the following information):**
 - OS: Windows 10 1909 18363.900 and Outlook on Android 10 (possibly elsewhere)
 - .NET Runtime: No clue.
 - .NET Framework: .NET Core 3.1
 - MailKit Version: 2.7.0

**To Reproduce**
Send mail with the example above where the name is unicode and open Outlook.

**Expected behavior**
Outlook should display it the same as GMail (which does work on both firefox and GMail app).

**Screenshots**
N.A. Just the general character mess you get if unicode isn't read properly.

**Additional context**
-

**Comment by jstedfast** [comment]
Don't use the following code snippet:

```csharp
options.International = true;
options.AllowMixedHeaderCharsets = true;
```

options.International tells MimeKit/MailKit not to encode the headers (i.e. it sends raw UTF-8 which probably breaks Outlook) and options.AllowMixedHeaderCharsets tells MimeKit/MailKit to mix-and-match UTF-8, US-ASCII and ISO-8859-1 in the same header. In other words, if the Subject (for example) is really long and needs to be broken up into multiple encoded-word tokens, this option allows MimeKit/MailKit to choose US-ASCII and/or ISO-8859-1 for each individual encoded-word even if you've specified UTF-8, thereby making it *possible* that you end up with a Subject like this:

```
Subject: =?us-ascii?q?This_is_ascii_?= =?iso-8859-1?q?and_this_is_fran=CAes?= =?utf-8?b?<base64>?=
```

Some clients do not deal well with this scenario even though the specification requires support for that.

**Comment by Nielsbishere** [comment]
You are right, thank you. I saw a if(...) options.International = true; mentioned somewhere. I guess that introduced this and then I tried fixing it by adding the mixed charsets.
Thank you!
