### ISSUE TITLE
Profile Picture

### ISSUE THREAD

**Issue by SmbatChilingaryan** [jstedfast/MailKit#1046]
Please share some information if you have.
I'm using MailKit about 5 month, but cant find answers to this 2 questions.
**1. Is there any way to get profile picture of sender or receiver in mail list ?**
For example when I do .Fetch(0,-1)...... or .GetMessage(id).... I wont to receive  profile picture too.

**2. Is there any way to get an result like in attachment ?**
https://drive.google.com/file/d/1beAmF2K2YVy9Ga5lqKiFt2glfi1MvbCQ/view?usp=sharing

it means :  
profile picture, name and email.

Thanks.

**Comment by jstedfast** [comment]
1. You have to write that code yourself. The IMAP protocol does not support profile pictures, so you'll have to get that profile picture another way. Maybe through [gravatar](https://en.gravatar.com/)?
2. Yes:

```csharp
var mailbox = message.From.Mailboxes.FirstOrDefault();
var name = mailbox.Name;
var email = mailbox.Address;
```
