### ISSUE TITLE
Am not able to reterieve message information like From Email, CC Email etc.

### ISSUE THREAD

**Issue by techportsolutions** [jstedfast/MailKit#1047]
**Describe the bug**
Am not able to reterieve message information like From Email, CC Email etc. Please let me know which object property I can get this.

**Platform (please complete the following information):**
 - OS:  Windows
 - .NET Framework: 4.6
 - MailKit Version: latest

**Comment by jstedfast** [comment]
Did you try the message object? http://www.mimekit.net/docs/html/T_MimeKit_MimeMessage.htm

**Comment by techportsolutions** [comment]
Hi ,

Thanks for your quick response. I am iterating the IListMessageSummary Object, which I am got by calling imap.Inbox.Fetch. I have sorted out the issue by getting the Envelope object from the IListMessageSummary. Below is the code for your reference:

`var items = imap.Inbox.Fetch(uids, MessageSummaryItems.UniqueId | MessageSummaryItems.BodyStructure | MessageSummaryItems.Envelope);
                foreach (var item in items)
                {
                    var bodyPart = item.TextBody; 

                    // download the 'text/plain' body part
                    var body = (TextPart)imap.Inbox.GetBodyPart(item.UniqueId, bodyPart);
                    Console.WriteLine("From:" + item.Envelope.From);
                    Console.WriteLine("Unique ID:" + item.UniqueId + "\nHTML Body:" + item.HtmlBody);
                    Console.WriteLine("Item Body" + item.TextBody + " Body Text:" + body.Text);

                }`

 Let me know if there is a better way of doing that.

**Comment by jstedfast** [comment]
Your way of getting the information you want is perfectly fine as well.
