### ISSUE TITLE
ImapFolder.CreateAsync doesn't allow mailbox names that contain the hierarchy separator

### ISSUE THREAD

**Issue by Moosemorals** [jstedfast/MailKit#1048]
**Describe the bug**
ImapFolder.CreateAsync throws an ArgumentException when the mailbox name includes the hierarchy separator character. However, this behaviour is permitted by rfc3501:

> 6.3.3.  CREATE Command
> [...]
> If the server's hierarchy separator character appears elsewhere in
> the name, the server SHOULD create any superior hierarchical names
> that are needed for the CREATE command to be successfully
> completed.

It looks like ImapEngine.IsValidMailboxName checks for the hierarchy separator as well as invalid unicode.

**Platform (please complete the following information):**
 - OS: Windows 10
 - .NET Runtime: CoreCLR
 - .NET Framework: .net core 3.1.301
 - MailKit Version: 2.7.0

**To Reproduce**
```
IMailFolder root = await client.GetFolderAsync(imap.PersonalNamespaces.First().Path);
string name = string.Join(root.DirectorySeparator, "level1", "level2");
await root.CreateAsync(name, true);
```

**Expected behavior**
One (or two, depending on which folders already exist) new folders to be created.

**Additional context**
An obvious workaround would be something like:
```
IMailFolder current = root;
foreach (string part in name.Split(root.DirectorySeparator)) {
    current = await current.CreateAsync(part, true);
}
```
but that's going to do a bunch extra round trips.

**Comment by jstedfast** [comment]
IMailFolder.CreateAsync() is designed to only allow creating of *immediate* subfolders, not folders anywhere on the system.

*Maybe* an ImapClient.CreateAsync() method would make sense for your particular use-case scenario.

**Comment by Moosemorals** [comment]
Fair enough, and I've checked the docs (should have done that before I reached for the code :smile:) and they're fairly clear:
> Create a new subfolder with the given name.

I can happily live with the workaround (my server is on localhost), but ImapClient.CreateAsync gets a +1 from me.

Thanks for the reply.
