### ISSUE TITLE
Mimekit | Getting exception when trying to add from email address | Unexpected token at offset 33

### ISSUE THREAD

**Issue by RajuKankipati** [jstedfast/MailKit#1050]
**Describe the bug**
 Getting exception when trying to add from email address, Unexpected token at offset 33

**Platform :**
 - OS: . Windows
 - .NET Framework: [e.g. .Net Corec 3.1,
 - MailKit Version: 2.0.3

![image](https://user-images.githubusercontent.com/68748180/88413040-1c622900-cdf8-11ea-8f61-50e510eb65f5.png)

Could someone please suggest the solutions, thanks in Advance

**Comment by jstedfast** [comment]
That's a pretty old version of MailKit. You could try upgrading.

What are the strings that are failing? Specifically the `x.Address` value.

**Comment by RajuKankipati** [comment]
> That's a pretty old version of MailKit. You could try upgrading.
> 
> What are the strings that are failing? Specifically the `x.Address` value.

Hi Jeffrey,

I believe i am using the latest even too, I am getting the issues. Please find the below image for your reference.

![image](https://user-images.githubusercontent.com/68748180/88421192-c09e9c80-ce05-11ea-8630-553c22023e13.png)

Thanks..

**Comment by jstedfast** [comment]
NETCore.MailKit is not my package.

Use the MailKit package. I don't know what NETCore.MailKit is.

**Comment by RajuKankipati** [comment]
> NETCore.MailKit is not my package.
> 
> Use the MailKit package. I don't know what NETCore.MailKit is.

Hi Jeffrey,

Thanks for the suggestion both are Working the same (NETCore.Mailkit and MailKit).

The fix for this offset 33 issue is, I am copying the email from another source there is adding some other extra character that causes the problem.

Thanks for your time Jeffrey.

**Comment by jstedfast** [comment]
If you are copying MailboxAddresses, try using `Clone()` instead of `new MailboxAddress (x.Name, x.Address)`
