### ISSUE TITLE
Office 365 OAuth2 - Non interactive

### ISSUE THREAD

**Issue by PrzemyslawKlys** [jstedfast/MailKit#1054]
Hi,

Do you know if it's possible to SMTP/IMAP/pop3 in O365 in a non-interactive way? Or at least in a way that doesn't prompt me all the time to login?

![image](https://user-images.githubusercontent.com/15063294/88474597-6cd8a400-cf28-11ea-8871-c945d109ab18.png)

Your example shows an interactive acquiring of a token, and I can see it has other ways, just not sure how to use them. 

On Google example, you showed how to do this with the cached credentials folder, and it would be cool having a similar things for O365.

Przemek

**Comment by jstedfast** [comment]
The first time you authenticate the user, you'll need to do something like this:

```csharp
var authToken = await publicClientApplication.AcquireTokenInteractive(scopes).WithLoginHint (userName).ExecuteAsync(cancellationToken);
```

Then, once you have that information, you can cache the `authToken.Account` values so that you can then use the following method in the future:

```csharp
await publicClientApplication.AcquireTokenSilent(scopes, authToken.Account).ExecuteAsync(cancellationToken);
```

**Comment by PrzemyslawKlys** [comment]
Would you be able to show that on example like you did with google code? I don't know how would I cache safely the auth token? Would it only last till application runtime? 

Sorry for asking silly questions but I'm translating this to PowerShell and it's not so straightforward for me.

**Comment by jstedfast** [comment]
Well, the `authToken.Account` is just a class that implements the `IAccount` interface which has a 2 strings (`Username` and `Environment`) as well as a `HomeAccountId` which is of type `AccountId` which contains 3 strings: `Identifier`, `ObjectId` and `TenantId`. You'll need to save all of these strings so that you can reconstruct this data structure later.

I'm not able to find a public class in Microsoft.Identity.Client that implements `IAccount`, so you'll probably need your own class that implements that interface. Then just load the strings and set them appropriately.

**Comment by PrzemyslawKlys** [comment]
Ok :-) Thought this would be a bit easier. Tried to convert to XML and load it back up but no luck. I guess I need to brush up my C# skills a bit to create such class. Thank you.

**Comment by PrzemyslawKlys** [comment]
I also see that there is ability to use LoginHint for AcquiteTokenSilent - but the hard part is actually getting token cache. 

Exception calling "GetResult" with "0" argument(s): "You are trying to acquire a token silently using a login hint. No account was found in the token cache having this login hint."

**Comment by jstedfast** [comment]
Using a LoginHint doesn't make sense for obtaining a token from a cache because the LoginHint just pre-populates the UI with the specified username.

**Comment by PrzemyslawKlys** [comment]
Actually I think I totally took a wrong approach. I was too focused on the `AcquireTokenInteractive` part while not focusing on what I need it for. Since I've acquired the token all that MailKit needs is UserName and AccessToken which both are strings. So I can just save those strings and skip requesting token altogether. 

```powershell
[MailKit.Security.SaslMechanismOAuth2]::new($Username, $AccessToken)
```

Thanks again for your help

**Comment by jstedfast** [comment]
Sure, you could also do that - but eventually you'll need to refresh the token (which is what I thought you meant).

**Comment by PrzemyslawKlys** [comment]
There is PowerShell implementation for that library https://github.com/AzureAD/MSAL.PS/tree/master/src and it seems to cover a bunch of options there, including some caching. 

It seems the Access Token Time is 1h - https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-configurable-token-lifetimes - so I would need to find a way to refresh it based on that. Eh, shit.

**Comment by jstedfast** [comment]
You won't have to re-authenticate every hour (not sure if you're worried about that or not), but if you get disconnected (either because the connection drops or because the app logs out on purpose), the next time you connect, you will need to refresh the token.

**Comment by PrzemyslawKlys** [comment]
I'm creating PowerShell module (https://github.com/EvotecIT/Mailozaurr) that uses your libraries beneath it. As PowerShell is often non-interactive to send reports or do all kinds of stuff it basically can't prompt if not asked. I was thinking it can query once, and then it has to work forever.

**Comment by rajessnit** [comment]
@jstedfast :  As per your suggestion I have implemented IAccount class and storing these strings(Username
Environment,HomeAccountId) and setting up appropriately but it is not working , it is giving me an error of {"No Refresh Token found in the cache"}.
Here is my steps : first I use this 
 var options = new PublicClientApplicationOptions
                    {
                        ClientId = "clientID",
                        TenantId = "TenandID",
                        RedirectUri = "https://login.microsoftonline.com/common/oauth2/nativeclient"
                };

                    var publicClientApplication = PublicClientApplicationBuilder
                        .CreateWithApplicationOptions(options)
                        .Build();

                      var scopes = new string[] {
                                "email",
                                "user.read",
                                "offline_access",
                                "https://outlook.office.com/SMTP.Send" // Only needed for SMTP
                                };
authToken = await publicClientApplication.AcquireTokenInteractive(scopes).ExecuteAsync();
I get information from  authToken and store  Username,Environment,HomeAccountId in my database.

In next call I would like not to open pop up window for authentication hence I use this 
  myIAccount= new EmailAccount("rajesh@abc.com", "login.windows.net","identifier","objectId","tenantID");
 var authToken1 = await publicClientApplication.AcquireTokenSilent(scopes, myIAccount).ExecuteAsync(CancellationToken.None);  

but it throws error of "No Refresh Token found in the cache".

Am I missing something , can you please help.

Implemented Class code:
==========

    class EmailAccount:IAccount
    {
        private string _userid;
        private string _env;
		private string _identifier;
        private string _objectId;
	    private string _tenantID;
        public EmailAccount(string userid, string env, string identifier, string objectId, string tenantID)
        {
            _userid = userid;
            _env = env;
	   _identifier=identifier;
	  _objectId=objectId;
	  _tenantID=tenantID;
        }
     
     
       AccountId obj = new AccountId(_identifier, _objectId, _tenantID);
       public AccountId HomeAccountId
        { 
                get => obj;
                set => obj = value;
            
        }

        public string Username  // read-write instance property
        {
            get => _userid;
            set => _userid = value;
        }
        public string Environment  // read-write instance property
        {
            get => _env;
            set => _env = value;
        }

    }
=========

**Comment by jstedfast** [comment]
@rajessnit in order for the refresh token to be in the cache, you'll have to have at least authenticated once via a browser control with user interaction.

If you did do that, then keep in mind that refresh tokens likely have an expiration date and once that expires, the cache probably gets rid of it.

I wish I knew more about how this stuff works to be more helpful, but unfortunately OAUTH is not something I know a ton about. I banged my head against the wall enough to figure out what I wrote in the [GMailOAuth2.md](https://github.com/jstedfast/MailKit/blob/master/GMailOAuth2.md) and [ExchangeOAuth2.md](https://github.com/jstedfast/MailKit/blob/master/ExchangeOAuth2.md) and that's as far as I've gotten.

**Comment by PrzemyslawKlys** [comment]
When you read on the internet refreshing tokens is connected with what they call "offline_access" requests. For weeks I was under impression that I would need this offline_access to get this up and running, but it turns out that "offline_access" is used for delegation only.

So for application access - you just can request token once and use it for 3600 seconds before it expires. You basically have an app/key for your application, and once the token is about to expire (3600 seconds) you request it again, and again and again. Since you have an app/key that's all the time valid - you just need to handle the authorization process.

For delegation access - you need to request token, but since this is delegation it's a bit more complicated. You need request token with offline_access if you want to continue using it without constant user interaction. But once you have the offline_access - you can refresh it the same way as for the application. 

You basically need to build your own logic around the expiration - kind of internal cache. In PowerShell I did it so during a first request I would save the time minus 10 seconds and save both the token and expiration time. Then every time during authentication I would check if the cache for my app/key is still valid and use that, if it's about to expire or expired already - I went thru the authentication process. 

I think MSAL.NET (or in the case of PowerShell MSAL.PS - https://www.powershellgallery.com/packages/MSAL.PS/4.2.1.3) solves this for you to some degree.

**Comment by rajessnit** [comment]
Thanks @jstedfast and @PrzemyslawKlys  for your inputs, it seems more complicated. My requirement is simple , generate a token once in interactive mode, save it and use it for somedays in silent mode.
Initially my plan was to save access token with user name  and use it , it works for a single day approx 6 hours , very next day it gets expired. Then I thought of second solution to refresh token which is not working out here.
I am integrating this solution in a third party application where user will send an email with attachments in interactive as well as non-interactive mode,  non-integrative mode means I will create a schedule job and job will send an email with attachments without any interference from user, so if the silent mode of authentication does not work then job will not be able to send an email.
Any help will be highly appreciated! thanks again for providing your inputs.

**Comment by ARFFI-26** [comment]
https://github.com/MicrosoftDocs/azure-docs/blob/main/articles/active-directory/develop/msal-net-token-cache-serialization.md#desktop-apps

**Comment by fredoche1810** [comment]
Hello @PrzemyslawKlys, @rajessnit 
did you finally find a solution to generate a token once in interactive mode, save it and use it for some days in silent mode ?
Thanks in advance,

**Comment by jonferreira** [comment]
@jstedfast  @PrzemyslawKlys did you guys ever got to the bottom of this?

I need to make a windows service that will connect to Exchange and continuously read new emails and download certain attachments, if exist.

I have no problem in having an interactive login when deploying the service but from there on it needs to be non-interactive for as long as possible

**Comment by jstedfast** [comment]
@jonferreira yes, it's solved. What you want is service-to-service OAuth.

Read the ExchangeOAuth2.md file in MailKit's root project directory.

**Comment by jonferreira** [comment]
Yes that's what I've done but sounds like you're saying that for non-interactive auth I must follow the web service section only? - https://github.com/jstedfast/MailKit/blob/master/ExchangeOAuth2.md#web-services

**Comment by jstedfast** [comment]
Yes, that is correct.

**Comment by jonferreira** [comment]
In that case shouldn't the WIKI be updated and this section removed then?

`Note: Once you've acquired an auth token using the interactive method above, you can avoid prompting the user if you cache the authToken.Account information and then silently reacquire auth tokens in the future using the following code:`

**Comment by jstedfast** [comment]
Yes, sorry, that probably shouldn't have been there.
