### ISSUE TITLE
Fetch error on Header Search and can't find with subject on Yahoo

### ISSUE THREAD

**Issue by navaddins** [jstedfast/MailKit#1055]
I'm fetching some mail from yahoo base on some condition (1 is base on the header and another is the subject). I got an error if I use header search with "References" or "In-Reply-To". I don't get any error if I search with SubjectContains but not a result. Actually, there has a message in yahoo mailbox, that I search from MailKit.

I would like to get a suggestion from you, what is a best way to get a delivery failure message for all servers(yahoo, Gmail, and outlook). Eg. fetch with Message-Id or Subject?

**Platform (please complete the following information):**
 - OS: [Windows 10 Ent. 2004]
 - .NET Framework: .NET 4.5
 - MailKit Version: 2.8.0.0

**To Reproduce**

**Header Search**

`HeaderSearchQuery _binarySearchQuery = SearchQuery.HeaderContains("References", "1BNX4NKI9BU4.72GSHLUJJJ0B1@WIN10");`

**Exception
{"The IMAP server replied to the 'SEARCH' command with a 'NO' response: UID SEARCH Server error - Please try again later"}.**

**StackTrace

   at MailKit.Net.Imap.ImapFolder.<SearchAsync>d__383.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MailKit.Net.Imap.ImapFolder.Search(SearchQuery query, CancellationToken cancellationToken)
   at GoogleOAuth2.Main(String[] args) in C:\Users\xxx\Documents\Visual Studio 2015\Projects\GoogleAPIs\GoogleAPIs\Program.cs:line 201
   at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
   at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
   at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

**Can't find with subject** 

```
TextSearchQuery _binarySearchQuery = SearchQuery.SubjectContains("Failure `Notice");
                IList <UniqueId> _uniqueId = _iMailFolder.Search(_binarySearchQuery);
                IList<IMessageSummary> _imessageSummaries = _iMailFolder.Fetch(_uniqueId, MessageSummaryItems.UniqueId | MessageSummaryItems.BodyStructure);
                foreach (IMessageSummary _imessageSummary in _imessageSummaries)
                {
                                // Never come to here
                                console.writeline("comehere");
                }
```

**Screenshots**
This screenshot is taking with below code

`MimeMessage` _mimeMessage = _iMailFolder.GetMessage(0); // I have only one message

![Error](https://user-images.githubusercontent.com/33715070/88666327-83425380-d112-11ea-8b23-8b11584228cf.png)

**ProtocolLog**
**HEADER** References

Connected to imaps://imap.mail.yahoo.com:993/
S: * OK [CAPABILITY IMAP4rev1 SASL-IR AUTH=PLAIN AUTH=XOAUTH2 AUTH=OAUTHBEARER ID MOVE NAMESPACE XYMHIGHESTMODSEQ UIDPLUS LITERAL+ CHILDREN X-MSG-EXT OBJECTID] IMAP4rev1 Hello
C: A00000000 AUTHENTICATE PLAIN
S: A00000000 OK AUTHENTICATE completed
C: A00000001 CAPABILITY
S: * CAPABILITY IMAP4rev1 ID MOVE NAMESPACE XYMHIGHESTMODSEQ UIDPLUS LITERAL+ CHILDREN X-MSG-EXT UNSELECT OBJECTID
S: A00000001 OK CAPABILITY completed
C: A00000002 NAMESPACE
S: * NAMESPACE (("" "/")) NIL NIL
S: A00000002 OK NAMESPACE completed
C: A00000003 LIST "" "INBOX"
S: * LIST (\HasNoChildren) "/" "Inbox"
S: A00000003 OK LIST completed
C: A00000004 LIST "" "MailKit/Delivery Failed"
S: * LIST (\HasNoChildren) "/" "MailKit/Delivery Failed"
S: A00000004 OK LIST completed
C: A00000005 LIST "" MailKit
S: * LIST (\HasChildren) "/" "MailKit"
S: A00000005 OK LIST completed
C: A00000006 EXAMINE "MailKit/Delivery Failed"
S: * 1 EXISTS
S: * 0 RECENT
S: * OK [UIDVALIDITY 1595903349] UIDs valid
S: * OK [UIDNEXT 3] Predicted next UID
S: * FLAGS (\Answered \Deleted \Draft \Flagged \Seen $Forwarded $Junk $NotJunk)
S: * OK [PERMANENTFLAGS ()] No permanent flags permitted
S: * OK [HIGHESTMODSEQ 7]
S: * OK [MAILBOXID (27)] Ok
S: A00000006 OK [READ-ONLY] EXAMINE completed; now in selected state
C: A00000007 UID SEARCH HEADER References 1BNX4NKI9BU4.72GSHLUJJJ0B1@WIN10
S: A00000007 NO [SERVERBUG] UID SEARCH Server error - Please try again later

**SEARCH TEXT**
Connected to imaps://imap.mail.yahoo.com:993/
S: * OK [CAPABILITY IMAP4rev1 SASL-IR AUTH=PLAIN AUTH=XOAUTH2 AUTH=OAUTHBEARER ID MOVE NAMESPACE XYMHIGHESTMODSEQ UIDPLUS LITERAL+ CHILDREN X-MSG-EXT OBJECTID] IMAP4rev1 Hello
C: A00000000 AUTHENTICATE 
S: A00000000 OK AUTHENTICATE completed
C: A00000001 CAPABILITY
S: * CAPABILITY IMAP4rev1 ID MOVE NAMESPACE XYMHIGHESTMODSEQ UIDPLUS LITERAL+ CHILDREN X-MSG-EXT UNSELECT OBJECTID
S: A00000001 OK CAPABILITY completed
C: A00000002 NAMESPACE
S: * NAMESPACE (("" "/")) NIL NIL
S: A00000002 OK NAMESPACE completed
C: A00000003 LIST "" "INBOX"
S: * LIST (\HasNoChildren) "/" "Inbox"
S: A00000003 OK LIST completed
C: A00000004 LIST "" "MailKit/Delivery Failed"
S: * LIST (\HasNoChildren) "/" "MailKit/Delivery Failed"
S: A00000004 OK LIST completed
C: A00000005 LIST "" MailKit
S: * LIST (\HasChildren) "/" "MailKit"
S: A00000005 OK LIST completed
C: A00000006 EXAMINE "MailKit/Delivery Failed"
S: * 1 EXISTS
S: * 0 RECENT
S: * OK [UIDVALIDITY 1595903349] UIDs valid
S: * OK [UIDNEXT 3] Predicted next UID
S: * FLAGS (\Answered \Deleted \Draft \Flagged \Seen $Forwarded $Junk $NotJunk)
S: * OK [PERMANENTFLAGS ()] No permanent flags permitted
S: * OK [HIGHESTMODSEQ 7]
S: * OK [MAILBOXID (27)] Ok
S: A00000006 OK [READ-ONLY] EXAMINE completed; now in selected state
C: A00000007 UID SEARCH SUBJECT Failure `Notice
S: * SEARCH 
S: A00000007 OK UID SEARCH completed

**Comment by jstedfast** [comment]
Well, in your first example, the server replied with `A00000007 NO [SERVERBUG] UID SEARCH Server error - Please try again later` which is a bug in the server :-(

In your second example, you code fails because you queried for the wrong subject string:

```csharp
SearchQuery.SubjectContains("Failure `Notice");
```

Notice the back-tick character in there? I suspect that's a typo.

That said, the logs do reveal what looks like it could be a bug but I can't seem to reproduce it locally which is:

```
C: A00000007 UID SEARCH SUBJECT Failure `Notice
```

The subject string should be quoted there because it contains a space. Did you edit the log?

I just added a unit test based on your logs and MailKit is correctly quoting the search string, so I don't know what is going on unless that quotes were removed from the log for some reason.

**Comment by navaddins** [comment]
@jstedfast ,

I removed auth part only. I think it was my typo or format issue. Here is code screenshot and new log

![Annotation 2020-07-28 222753](https://user-images.githubusercontent.com/33715070/88679027-9f99bc80-d121-11ea-95fb-c73292569f16.png)

Connected to imaps://imap.mail.yahoo.com:993/
S: * OK [CAPABILITY IMAP4rev1 SASL-IR AUTH=PLAIN AUTH=XOAUTH2 AUTH=OAUTHBEARER ID MOVE NAMESPACE XYMHIGHESTMODSEQ UIDPLUS LITERAL+ CHILDREN X-MSG-EXT OBJECTID] IMAP4rev1 Hello
C: A00000000 AUTHENTICATE PLAIN
S: A00000000 OK AUTHENTICATE completed
C: A00000001 CAPABILITY
S: * CAPABILITY IMAP4rev1 ID MOVE NAMESPACE XYMHIGHESTMODSEQ UIDPLUS LITERAL+ CHILDREN X-MSG-EXT UNSELECT OBJECTID
S: A00000001 OK CAPABILITY completed
C: A00000002 NAMESPACE
S: * NAMESPACE (("" "/")) NIL NIL
S: A00000002 OK NAMESPACE completed
C: A00000003 LIST "" "INBOX"
S: * LIST (\HasNoChildren) "/" "Inbox"
S: A00000003 OK LIST completed
C: A00000004 LIST "" "MailKit/Delivery Failed"
S: * LIST (\HasNoChildren) "/" "MailKit/Delivery Failed"
S: A00000004 OK LIST completed
C: A00000005 LIST "" MailKit
S: * LIST (\HasChildren) "/" "MailKit"
S: A00000005 OK LIST completed
C: A00000006 EXAMINE "MailKit/Delivery Failed"
S: * 1 EXISTS
S: * 0 RECENT
S: * OK [UIDVALIDITY 1595903349] UIDs valid
S: * OK [UIDNEXT 3] Predicted next UID
S: * FLAGS (\Answered \Deleted \Draft \Flagged \Seen $Forwarded $Junk $NotJunk)
S: * OK [PERMANENTFLAGS ()] No permanent flags permitted
S: * OK [HIGHESTMODSEQ 7]
S: * OK [MAILBOXID (27)] Ok
S: A00000006 OK [READ-ONLY] EXAMINE completed; now in selected state
C: A00000007 UID SEARCH SUBJECT "Failure Notice"
S: * SEARCH 
S: A00000007 OK UID SEARCH completed

**Comment by jstedfast** [comment]
What if you try:

```csharp
SearchQuery.SubjectContains ("Failure").And (SearchQuery.SubjectContains ("Notice"))
```

I don't really have any good advice to give you for search queries that will work across all IMAP servers.

**Comment by navaddins** [comment]
FYI,
I tested with many emails for the search methods. This is what I found on yahoo mail.

SearchQuery with SubjectContains,BodyContains,MessageContains (**working on**)

Html body **with/without image**, Plain Text body (**Receive or Delivery successful**)

Html body **without image**, Plain Text body (Receive or Delivery successful or **Delivery failed**)

SearchQuery with SubjectContains,BodyContains,MessageContains (**not working**)

Html body **with an image** (**Delivery failed**)

Look like yahoo mail has an issue.

thank you for your support
