### ISSUE TITLE
GetFolder returns empty folder despite the XList compatibility

### ISSUE THREAD

**Issue by hahyes** [jstedfast/MailKit#1056]
**Describe the bug**
Hi there,

I'm trying to get access to Sent folder from my test email on some local provider service. Problem is, I can't get access to any folder using GetFolder method. Getting access to the Inbox by `client.Inbox` works just fine. For what I read earlier, problem appeared, when IMAP server hadn't XList or SPECIAL-USE compability, but used server has XList support.

**Platform (please complete the following information):**
 - OS: Windows 10
 - .NET Runtime: 3.1.6
 - .NET Framework: .NET Core
 - MailKit Version: v2.8.0

What I tried:
`var inbox = client.GetFolder(SpecialFolder.Sent)`
`var inbox = client.GetFolder(nameOfInboxFromXLIST)`
`var inbox = client.GetFolder(client.personalNamespaces[0]);
var sent = inbox.GetSubFolder(nameOfInboxFromXLIST)`

Logs from ImapClient:
https://pastebin.com/sZwq9Trm

**Comment by jstedfast** [comment]
This works for me:

```csharp
var inbox = client.GetFolder (SpecialFolders.Sent);
```

Your other attempts will fail if you use the string `"Wys&AUI-ane"` because that is the *encoded* name of the folder, but the GetFolder methods expect the decoded name (i.e. it'll be in UTF-8 with accents and all that fun stuff).

**Comment by jstedfast** [comment]
Any update on this? Did you figure out the issue?
