### ISSUE TITLE
Search query does not return messages

### ISSUE THREAD

**Issue by FishTailTea6** [jstedfast/MailKit#1057]
We have recently get update on our IceWarp server. I use MailKit to read incoming and outgoing messages (they are placed in specific folders). Since the update I'm not able to get messages through the search option using the query (I have tried also SearchQuery.All etc.).

```
var query = SearchQuery.DeliveredOn(DateTime.Parse("2020-07-01"))
        .And(SearchQuery.NotSeen).And(SearchQuery.NotDeleted);

foreach (var uid in mailFolder.Search(query))
{
    var message = mailFolder.GetMessage(uid);
    Console.WriteLine("[match] {0}: {1}", uid, message.Subject);
}
```
But I'm able to get messages in:

```
for (int i = 0; i < mailFolder.Count; i++)
{
    var message = mailFolder.GetMessage(i);
    Console.WriteLine("Subject: {0}", message.Subject);   
}
```
Do you have any idea why this could be happening? Thanks in advance.

**Comment by jstedfast** [comment]
The only reason that could be true is if the messages don't match your search query.

I can't help but notice that your search query doesn't have anything to do with subjects but your loop later on just prints the subject. How do you know, based on only the subject, that the messages matched or didn't match your search query?

**Comment by FishTailTea6** [comment]
In the first case it doesn't go inside the foreach loop at all.
I used this query before the update for some years, so I know it worked. And as I have stated if I use SearchQuery.All, I get the same result: Count=0.

**Comment by jstedfast** [comment]
Okay, then it sounds like a bug in your IMAP server (MailKit only sends the search query to the server which does all the matching logic and returns the results).

You can try getting a log (`new ImapClient (new ProtocolLogger ("imap.log"))`) to see what the search query looks like and what the server sends back.

**Comment by jstedfast** [comment]
Any update on this?

Looking at the IceWarp [release notes](http://dl.icewarp.com/patchinfo/12.3.0.txt), looks like they made changes to IMAP SEARCH by "fixing" a bug in caching search results back at the end of May.

If you have that update, then it probably means their fix broke things or else you don't have that update and maybe that update will solve your bug.

**Comment by FishTailTea6** [comment]
Not really, I have escalated the issue to my colleagues who are in touch with  the company that has done the update and waiting for response. Will keep you posted. Thank you for the comment, maybe it helps...
