### ISSUE TITLE
ImapFolder.Search Method is assigning a value of 0 to UniqueId.Validity property on returning UniqueId list

### ISSUE THREAD

**Issue by JuanDavidPaez** [jstedfast/MailKit#1060]
I am running MailKit 2.8.0
When I make a query using ImapFolder.Search Method, and check the UniqueIds list, all of them has a value of 0 in the  UniqueId.Validity property. I dont know if this is the intentent functionallity or it is a bug.

`
IList<UniqueId> uids = inbox.Search(searchQuery);
`

I have checked and this bug does not happen when using Fetch method.

**Comment by jstedfast** [comment]
Just an oversight. Should be fixed now. Thanks!
