### ISSUE TITLE
SmtpClient.SendAsync() should return the response string, not just void (non-generic Task)

### ISSUE THREAD

**Issue by springy76** [jstedfast/MailKit#1064]
MailKit claims to be truly async, but hooking into events (to get MessageSentEventArgs) feels so 1990 in an async world.

(not to forget the problems which can occur when not de-registering events)

**Comment by jstedfast** [comment]
What are you trying to use the string for? In the majority of SMTP implementations, it doesn't contain anything of value.

Anything you do with it is a hack and I'm not thrilled about designing MailKit's APIs around hacks.

**Comment by springy76** [comment]
I'm logging it (to database) since it nearly always contains human readable data in any way. There is no machine interpreting of that data, its just there for the purpose to be read by humans when searching for problems - far from being a hack.

**Comment by jstedfast** [comment]
IMHO, if the public API returns a string, it will be expected that it is machine usable for something other than logging to a database or log file for human diagnostics.

**Comment by jstedfast** [comment]
Also keep in mind that the IMailTransport interface that the Send/SendAsync methods implement is general purpose and not SMTP-specific, so it's impossible to be consistent with what that string contains. Never mind the fact that every SMTP server will use a different syntax and/or provide different diagnostics info. It's completely worthless from an API perspective.

FWIW, if you don't want to have to worry about event hooks, you can subclass SmtpClient and override OnMessageSent().

**Comment by springy76** [comment]
I did not notice the generic/common `IMailTransport` "base" so you're right that it won't fit nicely.

From an API perspective: If it would be machine usable I would expect the component to return an according object and not just a string.
But calling essential data worthless is disrespectful. Someone might only ever use the very same SMTP server and have a regex for parsing the well known result format (but not my case).
