### ISSUE TITLE
Encoding with  builder.ToMessageBody 

### ISSUE THREAD

**Issue by rvandeweyer** [jstedfast/MailKit#1065]
Hello
I try to send email with text in attachment. That works well only right now i have an encoding in the builder.ToMessageBody statement that screws up my communication with the customer. In the code example below i try to send an email with text "my text = my subject and Version=1.0" as attachment , but when you open the email the text has been altered to "my text =3D my subject and Version=3D1.0".  Is there a way to change the encoding? 
Thanks

var message = new MimeMessage();
var builder = new BodyBuilder();

builder.TextBody = "";
var xmltext ="my text = my subject and Version=1.0" ; 

builder.Attachments.Add("12345.txt", Encoding.ASCII.GetBytes(xmltext), new ContentType("text", "plain"));
 
message.Body = builder.ToMessageBody();

**Comment by jstedfast** [comment]
You can set any encoding you want.

```csharp
var attachment = (MimePart) builder.Attachments.Add("12345.txt", Encoding.ASCII.GetBytes(xmltext), new ContentType("text", "plain"));
attachment.ContentTransferEncoding = ContentEncoding.Base64;
```

Right now, based on your description, MimeKit is defaulting to QuotedPrintable. Probably because you have 8bit text or one of the lines in your attachment content starts with `"From "`.

**Comment by jstedfast** [comment]
FWIW, there's no reason to worry about the =3D stuff. The receiving mail software should be able to decode it just fine.
