### ISSUE TITLE
MailKit Pop3Client.Count retrieves all emails, not just the number of emails.

### ISSUE THREAD

**Issue by johnmackerras** [jstedfast/MailKit#1066]
**Describe the bug**
MailKit Pop3Client.Count retrieves all emails, not just the number of emails.

My code is as follows

```
using (var client = new Pop3Client(new ProtocolLogger("d:\\pop3.txt") ))
            {
                client.Connect(emailSettings.PopServer, emailSettings.PopPort, SecureSocketOptions.SslOnConnect);
                client.Authenticate(emailSettings.Username, emailSettings.Password);

                EmailCount = client.Count();
            }
```

The mailbox I am issung this command against has over 1000 emails in it. When examining the created Pop3.txt file I see that the client has correctly issued the ```STAT``` command and recieves the reply ```+OK 1122 50068335```.

However the Client then goes on to retrieves all email, issuing ```RETR``` until all have been downloaded.

When calling the ```client.Count()``` command, all the client needs to do is issue STAT and return the number from the server. Anything further is not necessary and a waste of bandwidth.

**Platform (please complete the following information):**
 - OS: Windows 10
 - .NET: Net Core 3.1
-  Microsoft Visual Studio Community 2019 Version 16.7.2
 - MailKit Version: 2.8.0

**Comment by jstedfast** [comment]
The `Count()` method that you are using is a LINQ extension method that iterates over an IEnumerable.

What you want is the `Count` *property* which will not download all messages.

I can't change the behavior of the LINQ `Count()` method because it exists in System.Linq, not MailKit.

**Comment by johnmackerras** [comment]
Damn those paretheses - thanks. Much faster now.
