### ISSUE TITLE
Performance test

### ISSUE THREAD

**Issue by biapopescu** [jstedfast/MailKit#1067]
Hello,
I am trying to do a stress test of an smtp relay server app that I made based on MimeKit and MailKit but I am not able to perform it correctly. I need to do it so I can establish a plan to scale up the server.
The most connections that I managed to perform are 70 connections per second on a VM with 1 virtual cpu and 3.75 Gb of RAM in Google cloud engine. I am sending mails from another linux VM with the same capacity using a parallel for loop. The sent messages are logged on another vm (identical to the others) where I use an async task with MessageStore just to write to the logs.
I was wondering if you have any performance data that I can rely on or maybe you could give me some advice on how to do this properly.
Thank you very much!

**Comment by jstedfast** [comment]
You're going to be limited by the number of socket connections you can make from your VM, I would imagine. I'm not sure it's possible to really push a server to the max to find out how many connections it can accept by only using a single client VM. You'd need a bunch of them if the server scales well at all.
