### ISSUE TITLE
Sorry, It's just a question

### ISSUE THREAD

**Issue by lyhoangnam** [jstedfast/MailKit#1068]
**I wonder if we had to flaged a message as seen in code?**
I gonna to find out an package to get unread mail, how to check it without update flag in code

**Comment by jstedfast** [comment]
To flag a message as seen, you can use the following code:

```csharp
folder.AddFlags (uids, MessageFlags.Seen, true);
```

No flags are ever changed automatically, you need to explicitly set them. You don't have to worry about GetMessage(), for example, setting the message as `\Seen`.

**Comment by lyhoangnam** [comment]
So thank @jstedfast
