### ISSUE TITLE
Is it possible to receive all emails in a domain through mailkit

### ISSUE THREAD

**Issue by KhalilMohammad** [jstedfast/MailKit#1069]
I need to create an IDLE IMAP for all wild card email addresses in a domain.

So for example, I have a domain foo.com
I create these email addresses
- sales@foo.com
- hr@foo.com

Can I receive all emails for all domains in *@foo.com

https://stackoverflow.com/questions/63712717/is-there-a-way-to-receive-all-wild-card-emails-programatically

Is this possible with MailKit?

**Comment by jstedfast** [comment]
Yes, but you'll have to create a new ImapClient for each email address.
