### ISSUE TITLE
Making impersonation possible

### ISSUE THREAD

**Issue by lukalule** [jstedfast/MailKit#1070]
Hey Jerry,

What I'm trying to do is access the mailboxes from the designated group of e-Mail addresses on our Exchange server. 
Addresses in that address group receive messages from our business partners.
After sifting through some Exchange docs, I found out that I should probably be looking at ["Impersonation"].(https://docs.microsoft.com/en-us/exchange/client-developer/exchange-web-services/impersonation-and-ews-in-exchange).

In short, are there steps in MailKit, coupled with Exchange settings, I can take to implement impersonation?

Exchange admin gave me the supposed "imperosnated user", which for testing purposes, has access to only my mailbox.
However, after trying to authenticate with that user's credentials (the same way I did with my original account), 
I get **MailKit.Security.AuthenticationException**: 'LOGIN failed.'
Unfortunately, admin said that beyond setting up that user, he doesn't know neither the code implementation details nor the traits or structure of that user. 

1. I'm wondering is the AuthenticationException something on MailKit side, or the user is perhaps wrongly setup by the admin, or can such user be used by Mailkit analog to my regular account.
2. What would be the structure of mailbox _if_ I had successfully authenticated? For multiple addresses in address group, would I have multiple mailboxes, or would all mail coalesce in one common mailbox?

[Using this guide](https://docs.microsoft.com/en-us/previous-versions/office/developer/exchange-server-2010/dd633680(v%3Dexchg.80)) I managed to create a "TestFolder1" under my inbox. Next up I'll try reading mail (using EWS) and I'll probably suggest that admin adds an additional address to this impersonation account, for testing purposes.

I'd like to achieve this with MailKit if possible (if there's an easy and straightforward way), as my code is already leveraging MailKit and pulling mail over IMAP.

Thanks.

EDIT: See my [updated question on SO](https://stackoverflow.com/questions/63740916/exchange-impersonation-using-imap). Doesn't change anything fundamentally but still it's updated.

**Comment by jstedfast** [comment]
> I'm wondering is the AuthenticationException something on MailKit side, or the user is perhaps wrongly setup by the admin, or can such user be used by Mailkit analog to my regular account.

The AuthenticationException is thrown by MailKit only when the server rejects your username/password combo.

To be honest, I'm not even sure what you are trying to do is even supported by Exchange via the IMAP protocol. It might only be supported via the Exchange protocol which MailKit does not support.

> What would be the structure of mailbox if I had successfully authenticated? For multiple addresses in address group, would I have multiple mailboxes, or would all mail coalesce in one common mailbox?

You would have to ask someone who is knowledgeable about this particular Exchange feature. This is the first time I'm even hearing about it.

Sorry, wish I could be more helpful but I'm just not knowledgeable about these Exchange features.

**Comment by lukalule** [comment]
After some research, I guess I'll be sticking with EWS. The [impersonation](https://docs.microsoft.com/en-us/exchange/client-developer/exchange-web-services/impersonation-and-ews-in-exchange) feature is what I needed, as there are dozens of people in our company who work as commercialists and communicate with our business partners. I will be needing access to their mailboxes, so I could redirect incoming mail to our CRM. 
BTW this is .Net Core 3.1 with Microsoft.Exchange.WebService.NETStandard nuget package. Same applies to framework with its respective nuget package.
Here's a code snippet for doing so, if someone in need stumbles onto this:


```
ExchangeService service = new ExchangeService(ExchangeVersion.Exchange2016);
service.Credentials = new WebCredentials("ImpersonationAccName", "impersonationAccPass");
service.Url = new Uri("https://path.to.your/service/definition.asmx");
```
Alternatively, if you don't know the service.Url, I found out you can just insert any e-mail address in your 
domain as a part of service.AutodiscoverUrl("john.doe@yourDomain.com", RedirectionUrlValidationCallback);
where RedirectionUrlValidationCallback is:
```
private static bool RedirectionUrlValidationCallback(string redirectionUrl)
{
    bool result = false;
    Uri redirectionUri = new Uri(redirectionUrl);
    if (redirectionUri.Scheme == "https")
    {
        result = true;
    }
    return result;
}

```
This is the important part, **ImpersonatedUserId** . The part where you introduce yourself as someone else,
the person you wish to impersonate.
Note that you CANNOT fetch messages directly with your impersonation account provided to you by admin.
Next line is mandatory. And for each person whose mailbox you want to access, you would have to loop and do this.
```
service.ImpersonatedUserId = new ImpersonatedUserId(ConnectingIdType.SmtpAddress, "someone.else@yourDomain.com");
SearchFilter searchFilter = new SearchFilter.IsGreaterThan(ItemSchema.DateTimeSent, DateTime.Now.AddDays(-1));
FindItemsResults<Item> result = await service.FindItems(WellKnownFolderName.Inbox, searchFilter, new ItemView(100000));

foreach (Item item in result)
{
    EmailMessage message = await EmailMessage.Bind(service, item.Id);
    //... do what must be done 
}
```

And of course, each e-mail address you wish to impersonate has to be manually added to impersonation 
account by Exchange admin.
