### ISSUE TITLE
Accentuation in attachment filename with Outlook 2019

### ISSUE THREAD

**Issue by leodinei** [jstedfast/MailKit#1071]
I am not sure if the bug is with MailKit or Outlook.
When is send an attachment with accentuation in filename, the attachment shows with a random number and extension dat.
GMail shows the same email correctly.

**Platform (please complete the following information):**
 - OS: Windows
 - .NET Runtime: .NET 4.5
 - .NET Framework: .NET 4.5
 - MailKit Version: 2.8.0

Sample:
            BodyBuilder builder = new BodyBuilder();

            foreach (Anexo AnexoEnviar in Enviar.Anexos)
            {
                MimePart anexo = new MimePart();
                anexo.FileName = "Relatório.pdf";
                anexo.Content = new MimeContent(File.OpenRead(AnexoEnviar.Arquivo));
                anexo.ContentDisposition = new ContentDisposition(ContentDisposition.Attachment);
                anexo.ContentTransferEncoding = ContentEncoding.Base64;
                builder.Attachments.Add(anexo);
            }

**Comment by jstedfast** [comment]
Remove `anexo.ContentDisposition = new ContentDisposition(ContentDisposition.Attachment);`

When you set the FileName, it creates a ContentDisposition for you.
