### ISSUE TITLE
Unexpected Token error after IceWarp security updates.

### ISSUE THREAD

**Issue by spavolko** [jstedfast/MailKit#1073]
Mailkit throws the following error when attempting to authenticate to an IceWarp email server used by a client:

"Syntax error in IMAP server greeting. Unexpected token: [atom: NO]"

**Platform (please complete the following information):**
 - OS: Windows 10 / Server 2012 R2
 - .NET Runtime: .NET Framework
 - .NET Framework:  .NET 4.5
 - MailKit Version: 2.5.0.0

**To Reproduce**
The issue is happening on a specific client's email server, and I cannot give specific credentials for that account due to security concerns, however general steps to reproduce should be:
1.)Set up a Mailkit IMAP project
2.)Plug in server address, username, and password info for a valid account on an IceWarp email server.
3.)Try to authenticate/create an IMAP client
4.)See error

**Expected behavior**
Move past the message given in the IMAP log, if possible, to continue the authentication process. If not possible, show a more descriptive error

**Additional context**
IMAP Log contents (actual hosts/IPs redacted):

Connected to imaps://mail.******************.com:993/
S:  NO LOGOUT Intrusion prevention active for 50.***.***.***

**Comment by jstedfast** [comment]
Looks like a server bug. "NO" is not a valid response to connecting to the IMAP server. Only "OK", "PREAUTH", or "BYE" are valid.

**Comment by spavolko** [comment]
> Looks like a server bug. "NO" is not a valid response to connecting to the IMAP server. Only "OK", "PREAUTH", or "BYE" are valid.

Thanks for the quick response!
