### ISSUE TITLE
MailKit SMTP message never arrives

### ISSUE THREAD

**Issue by NDCTechSupport** [jstedfast/MailKit#1074]
**Describe the bug**
On one particular SMTP server, email sent using MailKit never arrives but same email sent via same SMTP server using .NET’s System.Net.Mail.SmtpClient does arrive.

**Platform (please complete the following information):**
 - OS: Windows
 - .NET Runtime: Microsoft .NET Framework 4.5 Full Package
 - .NET Framework: .NET 4.5
 - MailKit Version: 2.8.0.0

**To Reproduce**
1. See transcript and screenshot below.

**Expected behavior**
Email should arrive at destination.

**Screenshots**

Below is the redacted e.Response from the MailKit.MessageSentEventArgs.

The redacted info is not the same value as the message ID in the transcript.

![Annotation 2020-09-09](https://user-images.githubusercontent.com/71021842/92608679-acaedd00-f283-11ea-9397-c57506040101.png)

**Additional context**

Below is the redacted SMTP transcript. 

MailKit works with every other SMTP server I've tried, but I do notice that all other SMTP servers say: "S: 250-8BITMIME" in uppercase whereas this particular SMTP server says: "S: 250-8bitmime" in lowercase. And MailKit is using "C: Content-Transfer-Encoding: binary" instead of the usual "C: Content-Transfer-Encoding: base64".

The transcript seems to end abruptly when it tries to send the content as binary.

Could it be as simple as MailKit needing to do a case-insensitive compare on "8bitmime"?

From: noreply@xxxxxxxx.org
Host: xx.xx.xx.2
Port: 25
SmtpOptions: Auto
User: 
Pwd: (none)
To: support@xxxxxxxx.com
Subject: Test MailKit Message
Message: Test MailKit Message
Use XOAUTH2: False
Authenticate: False
Connected to smtp://xx.xx.xx.2:25/?starttls=when-available
S: 220 xxxxxx.xxxxxxxxxxxxxx.gov Microsoft ESMTP MAIL Service, Version: 10.0.17763.1 ready at  Wed, 9 Sep 2020 08:41:51 -0400 
C: EHLO [xx.xx.x.3]
S: 250-xxxxxx.xxxxxxxxxxxxxx.gov Hello [xx.xx.x.3]
S: 250-TURN
S: 250-SIZE 102400000
S: 250-ETRN
S: 250-PIPELINING
S: 250-DSN
S: 250-ENHANCEDSTATUSCODES
S: 250-8bitmime
S: 250-BINARYMIME
S: 250-CHUNKING
S: 250-VRFY
S: 250 OK
C: MAIL FROM:<noreply@xxxxxxxxx.org> SIZE=376 BODY=BINARYMIME
C: RCPT TO:<support@xxxxxxxx.com>
S: 250 2.1.0 noreply@xxxxxxxxx.org....Sender OK
S: 250 2.1.5 support@xxxxxxxx.com 
C: BDAT 376 LAST
C: From: noreply@xxxxxxxxx.org
C: Date: Wed, 09 Sep 2020 08:41:53 -0400
C: Subject: Test MailKit Message
C: Message-Id: <SMCMSY7KMBU4.EALKEOS43AZF1@xxxxxx>
C: To: support@xxxxxxxx.com
C: MIME-Version: 1.0
C: Content-Type: text/plain; charset=utf-16
C: Content-Transfer-Encoding: binary
C: 
C: A

I could make the entire Visual Studio 2013 Windows Forms "MailKitTest" project available if needed but the particular SMTP server exhibiting this problem is not available for any off-site testing.

**Comment by jstedfast** [comment]
Your log is missing the end response from the server and no, it has nothing to do with lowercase "8bitmime" - MailKit already matches that case insensitively.

**Comment by jstedfast** [comment]
Exchange has a bug with BINARYMIME which MailKit opts into using because it is more efficient when sending mail to not need to encode using base64.

Do this in your code before calling Send/SendAsync():

```csharp
client.Capabilities &= ~(SmtpCapabilities.BinaryMime | SmtpCapabilities.Chunking);
```

**Comment by jstedfast** [comment]
Note: if you disable BINARYMIME and CHUNKING (as shown above), you will get the same behavior as System.Net.Mail.

**Comment by NDCTechSupport** [comment]
Dear Jeffrey,

 

Thanks for the quick responses!

 

I’m implementing the change you suggest and will test on that (and other) SMTP servers.

 

This application is sending very-short plaintext emails, so I imagine disabling BINARYMIME and CHUNKING will have no ill effects. And if it gives greater compatibility with the SMTP servers that are out there that I may need to connect with, I’m all for that.

 

MailKit has already greatly increased the successful delivery of emails compared to System.Net.Mail. Only this one SMTP server has given any trouble.

 

 

Sincerely, 

 

Don Strom for

NDC Tech Support
