### ISSUE TITLE
Is that possiable to send Email locally without a Email Server like outlook.com ?

### ISSUE THREAD

**Issue by John0King** [jstedfast/MailKit#1079]
**Is your feature request related to a problem? Please describe.**
it's not stable  when send email via outlook.com , because it has some human verification tech, to prevent us send lots of email to many email receiver. Can I send a email without a email server (ps: I own a domain , so technically I can build a email server with my domain )

**Describe the solution you'd like**

send email without to connect some server

**Describe alternatives you've considered**

a alternative cross-platform email server that I can use to build a (simple or not ) email server by myself

**Comment by jstedfast** [comment]
No. You don't need to use outlook.com, though. You can use your own mail server.

**Comment by John0King** [comment]
@jstedfast   any recommendation software that I can use to build my mail server ?

**Comment by jstedfast** [comment]
I work for Microsoft, so I think I'm supposed to tell you to use Exchange ;-)

Honestly, I don't know - there are plenty of free mail server options.
