### ISSUE TITLE
MailKit.Net.Imap.ImapCommandException: "The IMAP server replied to the 'SEARCH' command with a 'NO' response: Internal error occurred. Refer to server log for more information. [2020-09-23 19:48:51] (0.001 + 0.000 secs)."

### ISSUE THREAD

**Issue by Vain-soft** [jstedfast/MailKit#1082]
MailKit.Net.Imap.ImapCommandException: "The IMAP server replied to the 'SEARCH' command with a 'NO' response: Internal error occurred. Refer to server log for more information. [2020-09-23 19:48:51] (0.001 + 0.000 secs)."

**Comment by jstedfast** [comment]
I'll need a [protocol log](https://github.com/jstedfast/MailKit/blob/master/FAQ.md#ProtocolLog) to see what happened here, but based on the response, it seems like a server bug (that's generally what "internal error" means).
