### ISSUE TITLE
Support PRDR (Per-recipient Data Response)

### ISSUE THREAD

**Issue by ygoe** [jstedfast/MailKit#1083]
**Is your feature request related to a problem? Please describe.**
SMTP has the PRDR (Per-recipient Data Response) feature that lets the server accept or deny individual recipients after the message data has been received. This allows for per-user content filtering.

**Describe the solution you'd like**
The `SmtpClient` class should support PRDR and negotiate it with the SMTP server. This should be optional so that it can be turned on and off in the code.

**Describe alternatives you've considered**
None available.

**Additional context**
I'm testing my mail server setup with MailKit. Exim supports this, probably also other MTAs. [This is all I could find for a specification.](https://tools.ietf.org/html/draft-hall-prdr-00)

**Comment by jstedfast** [comment]
As a general rule, I find that it's not worth implementing draft specifications. This particular one hit a dead-end back in 2007, so it's likely to have a 0% chance of ever being accepted at this point.

**Comment by ygoe** [comment]
I did it myself now. It wasn't hard and it works fine with Exim. Would you be willing to accept a pull request for this?

**Comment by jstedfast** [comment]
Probably not, but I'm willing to take a look.
