### ISSUE TITLE
Not able to send mail to numeric digit in email address while using mailkit library .

### ISSUE THREAD

**Issue by Anooppandey3** [jstedfast/MailKit#1084]
To help me debug your issue, please explain:
- What were you trying to do?
 I am sending mail using mailkit library. I am using a mail address which have numeric value eg. anooppandey3@gmail.com
- What happened?
It is giving error -
System.InvalidOperationException: No recipients have been specified.
at MailKit.Net.Smtp.SmtpClient.Send(FormatOptions options, MimeMessage message, CancellationToken cancellationToken, ITransferProgress progress)
at MailKit.MailTransport.Send(MimeMessage message, CancellationToken cancellationToken, ITransferProgress progress)

- What did you expect to happen?
- MAil should be sent with numeric id using mailkit library.
 

code Snippt:

![image](https://user-images.githubusercontent.com/71870756/94536010-ddb97680-025f-11eb-93b0-e9965fbb6d6d.png)

**Comment by jstedfast** [comment]
I can't reproduce the problem with your exact code snippet. Maybe try upgrading to the latest MailKit release?
