### ISSUE TITLE
Add IsTransient property to SmtpCommand exceptions

### ISSUE THREAD

**Issue by jjxtra** [jstedfast/MailKit#1086]
When sending email over smtp, it is helpful to know if an exception is transient (i.e. greylist, please try again in 180 seconds or this ip is not yet authorized to send mail...) vs. the recipient does not exist (permanent error) and other type of exceptions. Hopefully the smtp status codes returned by the email server could be used to do this in a consistant way without parsing actual text of responses.

Having an IsTransient bool property on the SmtpCommandException would be helpful to instruct the caller to retry again later vs giving up and reporting a fatal error.

**Comment by jstedfast** [comment]
This information is already available on the SmtpCommandException - check the StatusCode property.
