### ISSUE TITLE
The last version supporting Windows Phone 8.1

### ISSUE THREAD

**Issue by zipswich** [jstedfast/MailKit#1089]
**Describe the bug**
The current version (2.9) does not support Windows Phone 8.1. 

**Platform (please complete the following information):**
 - OS: Windows Phone 8.1
 - MailKit Version: 2.9.0 

**To Reproduce**
Try to use NuGet Manager to install MailKit and get the following error:
Could not install package 'MailKit 2.9.0'. You are trying to install this package into a project that targets 'WindowsPhoneApp,Version=v8.1', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Expected behavior**
Installed.

What is the last version compatible with Windows Phone 8.1?

**Comment by jstedfast** [comment]
According to the [ReleaseNotes](https://github.com/jstedfast/MailKit/blob/master/ReleaseNotes.md#mailkit-240-2019-11-02), it was dropped in v2.4.0 which means that the last version to support it was v2.3.2. The MimeKit version that you will need will also be v2.3.2.

**Comment by zipswich** [comment]
Thanks a lot.
