### ISSUE TITLE
The SMTP server has unexpectedly disconnected.

### ISSUE THREAD

**Issue by Cereal-Killa** [jstedfast/MailKit#1090]
**Describe the bug**
Since this morning, I've been unable to send out simple emails,
I've been getting "The SMTP server has unexpectedly disconnected."
from any machine that I try it on, even on different locations.
The code hasn't changed nor any the account(s) settings.

**Platform (please complete the following information):**
 - OS: Windows 10, Windows Server 2016
 - .NET Runtime: CoreCLR
 - .NET Framework: [.NET 4.8
 - MailKit Version: 2.9.0

**To Reproduce**
1. Copy the sample code from the repository or write a simple smtp code to send an email.
2. Fire up the code
3. Wait for the response
4. An exception is thrown and the message doesn't get sent

**Expected behavior**
The very same piece of code used to work until this morning

**Screenshots**
None

**Additional context**
I'm not sure what kind of change there was on Google's end but
my code to send out emails using MailKit started failing this morning.
Initially I thought it was network related, since the code runs on my
server which is in another state, then running the very same code on
my machine gave me the same message, so far I have not been
able to send emails using MailKit, and I've tried quite a few combinations
of gmail smtp settings without any luck.

* Less secure apps is turned on the account, just like it has always been.
* It's happening with other email accounts from Google as well that we have,
not password related.

![kbH2KMgfC7](https://user-images.githubusercontent.com/25939765/97043565-0d029100-1549-11eb-942c-ac8969f56f6d.png)

**Comment by jstedfast** [comment]
In all likelyhood, Google's SMTP servers are dropping the connection for some reason. Maybe they rolled out a buggy version this morning.
