### ISSUE TITLE
[Documentation] Typo in SslCertificateValidation sample

### ISSUE THREAD

**Issue by RichardD2** [jstedfast/MailKit#1094]
There is a typo in the [SslCertificateValidation sample](https://github.com/jstedfast/MailKit/blob/master/Documentation/Examples/SslCertificateValidation.cs):
```cs
if (element.ChainStatus.Length == 0)
    continue;
...
foreach (var error in element.ChainStatus) {
```
The [X509ChainElement](https://docs.microsoft.com/en-gb/dotnet/api/system.security.cryptography.x509certificates.x509chainelement) class does not contain a `ChainStatus` property. I suspect this should be `ChainElementStatus` instead.

**Comment by jstedfast** [comment]
Thanks for reporting this!
