### ISSUE TITLE
.NET 5 support

### ISSUE THREAD

**Issue by atotalnoob** [jstedfast/MailKit#1098]
**Is your feature request related to a problem? Please describe.**
I am trying to build and deploy my application on .NET 5. Mailkit is currently not compatible. 

```
error NU1202: Package NETCore.MailKit 2.0.3 is not compatible with net50 (.NETFramework,Version=v5.0). Package NETCore.MailKit 2.0.3 supports: netstandard2.1 (.NETStandard,Version=v2.1) 
```

**Describe the solution you'd like**
Supports .NET 5

**Describe alternatives you've considered**
I would have to migrate to a different library

**Additional context**

N/A

**Comment by jstedfast** [comment]
The NETCore.MailKit package is not mine. Try the official MailKit nuget package.
