### ISSUE TITLE
{"5.1.0 Sender is not allowed to send from gmail.com (R2)"}

### ISSUE THREAD

**Issue by SDG01** [jstedfast/MailKit#1101]
Seeking some assistance into a new exception message I just started receiving randomly.  I have been using MailKit for 3-4 months with an email forwarder without any issues, then started getting this message on `smtpClient.Send(message);` execution.

Sanitized stack trace?
MailKit.Net.Smtp.SmtpCommandException: **5.1.0 Sender is not allowed to send from gmail.com (R2)**
   at MailKit.Net.Smtp.SmtpClient.DataAsync(FormatOptions options, MimeMessage message, Int64 size, Boolean doAsync, CancellationToken cancellationToken, ITransferProgress progress)
   at MailKit.Net.Smtp.SmtpClient.SendAsync(FormatOptions options, MimeMessage message, MailboxAddress sender, IList 1 recipients, Boolean doAsync, CancellationToken cancellationToken, ITransferProgress progress)
   at MailKit.Net.Smtp.SmtpClient.SendAsync(FormatOptions options, MimeMessage message, MailboxAddress sender, IList 1 recipients, Boolean doAsync, CancellationToken cancellationToken, ITransferProgress progress)
   at MailKit.Net.Smtp.SmtpClient.Send(FormatOptions options, MimeMessage message, CancellationToken cancellationToken, ITransferProgress progress)
   at MailKit.MailTransport.Send(MimeMessage message, CancellationToken cancellationToken, ITransferProgress progress)
   at XXXXXXXX.processMail() in XXXXXX.cs:line 202

This small desktop app I wrote retrieves email, checks email for certain strings, rebuilds email body with builder and sends it to a round-robin list.  The sender's domain shown above (gmail.com) can be different and this exception is not triggered with every email the app handles.  I suspected the original message's 'FROM' being the culprit and bypassed it with the authenticated smtp's user and then the original sender as the REPLY-TO but still fails with certain emails, like the above.  I'm not a developer, just a hobbyist.  Seeking some advice on where to look to resolve this exception.

Line 202 I don't believe is related to the above exception and is a TO string comparison check and with it commented out still run into this exception message.  I also commented out changing the FROM to REPLY-TO email (noted above)  with a full replace as message.from.clear() and an add and still get the exception.

Sending code:
```
var smtpClient = new SmtpClient();
smtpClient.Connect(mailServer, _port, SecureSocketOptions.None);
smtpClient.Authenticate(userName, passWord);
smtpClient.Send(message); //fails here
smtpClient.Dispose();
```
Again, this exception does not happen with every email, but started happening all of a sudden with some emails.  Any helps is appreciated!

**Comment by jstedfast** [comment]
Can you attach a [protocol log](https://github.com/jstedfast/MailKit/blob/master/FAQ.md#ProtocolLog) and a little more context about how you are modifying the message (with regards to From/ReplyTo)?

Does the From address match the GMail account address you are using to send?

**Comment by SDG01** [comment]
Will send as soon as possible.

**Comment by jstedfast** [comment]
What are the differences between the From addresses that work and the ones that don't? That will be important info.

Generally, GMail wants your account address to match the From address.

You *might* be able to get around that restriction by using the `Resent-*` headers (e.g. `Resent-From`, `Resent-Reply-To`, `Resent-To`, `Resent-Cc`, `Resent-Bcc`, `Resent-Message-Id`, and `Resent-Date`).

**Comment by SDG01** [comment]
Hello again Here's a smtp blurb from the protocol log (I have full log if needed):

```
Connected to -
S: 220 -
C: EHLO [127.0.0.1]
S: 250--
S: 250-PIPELINING
S: 250-SIZE 75000000
S: 250-ETRN
S: 250-STARTTLS
S: 250-AUTH PLAIN LOGIN
S: 250-AUTH=PLAIN LOGIN
S: 250-ENHANCEDSTATUSCODES
S: 250 8BITMIME
C: AUTH PLAIN -
S: 235 2.7.0 Authentication successful
C: MAIL FROM:<@gmail.com> SIZE=112229
C: RCPT TO:<@privatedomain.com>
S: 250 2.1.0 Ok
S: 250 2.1.5 Ok
C: DATA
S: 550 5.1.0 Sender is not allowed to send from gmail.com (R2)
C: RSET
S: 250 2.0.0 Ok
```

The FROM in this case indicates gmail.com and the privatedomain.com is the sending smtp (if that makes sense).

I was thinking it may have to do with mailbox.name versus mailbox.address due to similarities between this particular email that returned this message and other emails that returned the same message from different domains (not gmail.com), but I did change the code to follow the MailboxAddress(name, address) and didn't help.

The forwarder does handle other emails from different originating domains and that's where I'm confused because they are received, parsed thru subject/body, rebuilt with original attachments to the builder and resent to a round-robin list where that same email can be replied to and have the originating sender's email address in the reply-to.

I did a test removing the originating FROM and REPLY-TO and replacing it with the sending smtp and still rec'd this message, altho I'm not convinced they were cleared and replaced.

Thanks for replying so quick!  I don't want to take up too much of your time and my apologies if this post is in the wrong place to try and resolve this exception.  I'll look into the resent headers too.

**Comment by jstedfast** [comment]
> The FROM in this case indicates gmail.com and the privatedomain.com is the sending smtp (if that makes sense).

So the message came from user@privatedomain.com and was sent *to* user@gmail.com, but now you swapped the From and To, and are sending it back?

> Not sure what may have changed recently to cause this

Most likely, if anything changed, it was that GMail's SMTP server got stricter in what it will allow.

Was the body of the message sent after the DATA command? Or is that 550 error in response to the DATA command before the message body was sent?

Does the username you are using to authenticate with GMail the same as you are using in the From header? If not, that's the problem.

**Comment by SDG01** [comment]
> > The FROM in this case indicates gmail.com and the privatedomain.com is the sending smtp (if that makes sense).
> 
> So the message came from [user@privatedomain.com](mailto:user@privatedomain.com) and was sent _to_ [user@gmail.com](mailto:user@gmail.com), but now you swapped the From and To, and are sending it back?
> 

So this particular email is from 1@gmail.com to 1@privatedomain.com, the forwarder retrieves the email, conditionally rebuilds the subject and body and modifies the TO to send to a different email address 2@privatedomain.com in that when the new TO receives the email they can reply to the original sender at 1@gmail.com.

I had some luck with a test email by taking the original FROM and converting it to the REPLY-TO (which I've done before), but this time adding a Resent-*.Clear(); and making the new FROM the sending privatedomain.com email address.  

```
foreach (var mailbox in message.From.Mailboxes)
       message.ReplyTo.Add(new MailboxAddress(mailbox.Name, mailbox.Address));
message.From.Clear();
message.ResentFrom.Clear();
message.ResentReplyTo.Clear();
message.ResentTo.Clear();
message.ResentBcc.Clear();
message.ResentCc.Clear();
message.From.Add(new MailboxAddress("name", "address"));
```


The email forwarder historically has worked with other gmail.com emails as well as other domains that this new exception starting popping up with (but not all).  Will continue to test with different originating senders.

**Comment by SDG01** [comment]
Please feel free to close or delete this posting.  I believe I have resolved this by using the suggested Resent Headers.  This wasn't a bug or inherent issue with MailKit, which is a great resource/library for handling email with code!

This seems to work well with some of the exception emails so far:
```
foreach (var mailbox in message.From.Mailboxes)
     message.ResentReplyTo.Add(new MailboxAddress(mailbox.Name, mailbox.Address));
message.ResentSender = null;
message.ResentFrom.Clear();
message.ResentReplyTo.Clear();
message.ResentTo.Clear();
message.ResentCc.Clear();
message.ResentBcc.Clear();
message.ResentFrom.Add(new MailboxAddress(name, address));
message.To.Add(new MailboxAddress(name, address));
message.ResentTo.Add(new MailboxAddress(name, address));
```
