### ISSUE TITLE
Best practice for creating a Client

### ISSUE THREAD

**Issue by Bchir** [jstedfast/MailKit#1103]
Hello, 
What is the best practice for creating a Client? 
As it is disposable am trying to figure out if maybe it should have something similar to HTTP Client.
Am not sure if creating and disposing of a client for each request is an optimal choice. Maybe it should have some sort of life cycle managing Factory for client creation and just inject the client in the service

**Comment by jstedfast** [comment]
> What is the best practice for creating a Client?

I'm not really sure what you are asking...

> As it is disposable am trying to figure out if maybe it should have something similar to HTTP Client.

What do you mean?

> Am not sure if creating and disposing of a client for each request is an optimal choice.

You would be correct - that would not be optimal at all!

> Maybe it should have some sort of life cycle managing Factory for client creation and just inject the client in the service

This is too vague for me to understand what you are asking.

Keep in mind, too, that how you use any of the MailKit client classes all depends on what you intend to do with your application.

**Comment by Bchir** [comment]
My intent is to create a using some message broker, and I will be sending any message sent to the queue. 
I will be pulling multiple messages in parallel and each message handler has its own service scope.

What I mean by the Factory that controls the lifecycle is a factory will be responsible for the choice between creating a new client or pulling a cached one from a pool of cached clients for example.

**Comment by jstedfast** [comment]
The only way it makes sense to keep a pool of ImapClients alive (for example), would be if you intended to re-use the same connection w/ the same account info.

If that is the road you decide to take, my recommendation would be that you also periodically invoke NoOp() or NoOpAsync() on the client to keep the connection alive. Otherwise keeping the client object in a cache will be a waste.
