### ISSUE TITLE
Question related to concurrent IMAP connections

### ISSUE THREAD

**Issue by kislovs** [jstedfast/MailKit#1109]
Hey! It's not an issue and my question not straightforward related to `MailKit` (even if I use it). I ask this question because you might got an exclusive experience while developing this library. Hope, you don't mind 🙂 

---

I have two thread:
1. Incoming - this thread search `NotDeleted` messages, keep track of what were readed and enqueue new messages next to pipeline. Use: `await ImapClient.Inbox.SearchAsync(SearchQuery.NotDeleted, cancellationToken)`.
2. Outgoing - this thread (after some processing) mark one message per iteration as `Deleted`. Use: `await ImapClient.Inbox.SetFlagsAsync(messageId, MessageFlags.Deleted | MessageFlags.Seen, false, cancellationToken)`.

I have an issue that second thread works only short period of time right after connection. If second thread had pause for several seconds, `SetFlags` command didn't applied to messages (or it applied and reverted some way, I'm not sure), even if `MailKit` and `dovecot` logs success result:
```
C: B00000006 UID STORE 21 FLAGS (\Deleted \Seen)
S: B00000006 OK Store completed (0.001 + 0.000 secs).
C: B00000007 UID STORE 22 FLAGS (\Deleted \Seen)
S: * 1 EXPUNGE
S: * 1 EXIST
S: B00000007 OK Store completed (0.001 + 0.000 secs).
```
Message UID 21 - was processed after initial connect - flag was setted.
Message UID 22 - was processed after ~5 seconds pause after message UID 21 - didn't get any flags.

After that log both on client and server I see (through `doveadm`) that message with UID 22 doesn't have any flags.. And it breaks my program in some way.

**BUT**! If I add a call of `await ImapClient.NoOpAsync(cancellationToken)` before `SetFlags` - it immediately got fixed.

Also I tested one instance with locking on `SyncRoot` - works perfectly, but locks are banned 😅

---

So, do you know some reasons of such behavior? Or is it IMAP thing that couldn't be fixed without such "smell" NoOp call? Or maybe I just use `MailKit` wrong and there is an ability to do it more correct? As I said I have readonly job and writeonly job, both independant and connected through one way task queue.

**Comment by jstedfast** [comment]
Odd.

Based on the logs, it seems thread 2 successfully set the flags but you are saying that the flags aren't actually set on the server? That might be a server bug (kinda surprised, though, because Dovecot is top-notch as far as IMAP servers go).

One thing to keep in mind is that the NOOP command is to keep the connection alive. If a long enough period of idleness passes, the server will drop your connection. According to the IMAP specifications, this time limit is supposed to be >= 30 minutes, but my experience with some servers like GMail is that it's closer to ~10 minutes.

That said, the `UID STORE 22 FLAGS (...)` command is succeeding (according to the log) and as you said, it was only ~5 seconds after connecting, so that shouldn't require a NOOP.

**Comment by kislovs** [comment]
> Based on the logs, it seems thread 2 successfully set the flags but you are saying that the flags aren't actually set on the server?

Yeah, it is. We temporarily turn off log of IMAP sessions and dovecot got same logs, byte-to-byte. 

> That might be a server bug (kinda surprised, though, because Dovecot is top-notch as far as IMAP servers go).

I don't actually think that it's dovecot's bug, more likely some race conditions maybe.. (as I said "maybe reverted somehow")

> One thing to keep in mind is that the NOOP command is to keep the connection alive. If a long enough period of idleness passes, the server will drop your connection. According to the IMAP specifications, this time limit is supposed to be >= 30 minutes, but my experience with some servers like GMail is that it's closer to ~10 minutes.
That said, the UID STORE 22 FLAGS (...) command is succeeding (according to the log) and as you said, it was only ~5 seconds after connecting, so that shouldn't require a NOOP.

Yeah, read in the RFC and XML comments in MailKit 🙂 I think it's not required to be `NoOp`, any read / fetch request to server is  okay maybe (didn't test). 

Both of my threads work in `while (true)` loop with 1 second (at least for now) delay. And if first is always request to server to check any updates, second does it only when it has work to do (when first enqueue something). So second could have pretty big delay (even minutes). If I add `NoOp` call at the start of iteration in second thread - always works fine. If I track `LastConnectedAt` time and reconnect after 5 minutes of inactivity - it doesn't work. If I do `NoOp` call - it does work. Mystery...

**Comment by jstedfast** [comment]
Let's assume for the moment that the reason that the `doveadm` command didn't see the flag change to UID 22 is that the dovecot server hadn't (yet) synced the flags to disk (it's not uncommon for IMAP servers to not immediately sync flags).

It *might* be necessary for client connection 1 to send a CHECK command to force dovecot to sync flag changes made by connection 2 in order for connection 1 to see those changes (and for the SEARCH command to return the expected results).

I'm talking with the dovecot devs right now to try and figure this out.

**Comment by kislovs** [comment]
> Let's assume for the moment that the reason that the doveadm command didn't see the flag change to UID 22 is that the dovecot server hadn't (yet) synced the flags to disk

Unfortunately, flags didn't appear even in minutes after successful logs, so I don't think it relates to some `not-synced to disk` issues.

> It might be necessary for client connection 1 to send a CHECK command to force dovecot to sync flag changes made by connection 2 in order for connection 1 to see those changes (and for the SEARCH command to return the expected results).

It's okay for connection 1 to see changes in some short period of time, but it is likely stuck with those messages. I could try to add some `Check` (or whatever) requests, because I could easy reproduce on staging `dovecot` instance. So, I could check any guesses tomorrow 🙂 

> I'm talking with the dovecot devs right now to try and figure this out.

Amazing, thanks. Hope it could be solved without some "smell" `NoOp` call for only opened connection 🙂

**Comment by jstedfast** [comment]
It looks like the NOOP command is necessary and causes dovecot to sync flag changes.

Hope that helps, or at least explains why that works...

I guess I learned something new today as well ;-)
