### ISSUE TITLE
Create interaction with IMAP folders

### ISSUE THREAD

**Issue by 70076541** [jstedfast/MailKit#1110]
Hi Jeffrey,

I would need your help again. This time I would like to be able to create an interaction between the IMAP folders but I have not the faintest idea how to move and I was wondering if this request is possible to deepen it with you through the use of the MimeKit function or if you need to create code from scratch. In case the solution is the latter, would you have some documentation to understand where to start?

Best regards,
Andrea

**Comment by jstedfast** [comment]
I'm not sure what you mean by:

>  create an interaction between the IMAP folders

but it sounds like you just want to move messages from folder A to folder B?

If so, use the ImapFolder.MoveTo() method:

```csharp
client.Inbox.Open (FolderAccess.ReadWrite);
client.Inbox.MoveTo (UniqueIdRange.All, targetFolder);
```

http://www.mimekit.net/docs/html/M_MailKit_Net_Imap_ImapFolder_MoveTo.htm

**Comment by 70076541** [comment]
I'm sorry I was not very detailed. I created a mail "Client" using the potential of MimeKit so I can classically download in pop3 or Imap and send mail via SMTP. Now let's imagine the classic situation in which you have an e-mail box and you want to consult it on various devices such as smartphones, tablets and PCs. All of us would like that if read by one party it is already read on the other devices or if I reply or send a new email we would like this reply to be visible in the mail section sent on all devices. For this we rely on the IMAP protocol but, then the various mail programs I have to know how to manage the folders in such a way that they are always aligned / synchronized. I have read that this type of work is called interaction so my question is this: Is it possible to do this if so where should I start from?

________________________________
Da: Jeffrey Stedfast <notifications@github.com>
Inviato: mercoledì 2 dicembre 2020 03:19
A: jstedfast/MailKit <MailKit@noreply.github.com>
Cc: 70076541 <andrea--hp@hotmail.com>; Author <author@noreply.github.com>
Oggetto: Re: [jstedfast/MailKit] Create interaction with IMAP folders (#1110)


I'm not sure what you mean by:

create an interaction between the IMAP folders

but it sounds like you just want to move messages from folder A to folder B?

If so, use the ImapFolder.MoveTo() method:

client.Inbox.Open (FolderAccess.ReadWrite);
client.Inbox.MoveTo (UniqueIdRange.All, targetFolder);

http://www.mimekit.net/docs/html/M_MailKit_Net_Imap_ImapFolder_MoveTo.htm

**Comment by jstedfast** [comment]
> All of us would like that if read by one party it is already read on the other devices or if I reply or send a new email we would like this reply to be visible in the mail section sent on all devices. For this we rely on the IMAP protocol but, then the various mail programs I have to know how to manage the folders in such a way that they are always aligned / synchronized. I have read that this type of work is called interaction so my question is this: Is it possible to do this if so where should I start from?

I've never heard the term "interaction" before.

Yes, it's possible to do that... all you have to do is listen to all of the events on the `ImapFolder` class and handle them.

For example, when you get a `MessageFlagsChanged` event, you'll want to handle that by displaying the new set of message flags instead of what you were showing before the event fired.

When you get a `MessageExpunged` event (or `MessageVanished` if you enable `QRESYNC`), you'll want to handle that by removing the message from the list of messages.

When you get a `CountChanbed`, you'll want to handle that by queueing up a FETCH request for new messages (assuming the count didn't change due to messages being expunged).

**Comment by 70076541** [comment]
Hi,

sorry but, I want to write iteration and not interaction. In any case, I thank you for the guideline that I will try to follow step by step

Andrea

________________________________
Da: Jeffrey Stedfast <notifications@github.com>
Inviato: venerdì 4 dicembre 2020 16:10
A: jstedfast/MailKit <MailKit@noreply.github.com>
Cc: 70076541 <andrea--hp@hotmail.com>; Author <author@noreply.github.com>
Oggetto: Re: [jstedfast/MailKit] Create interaction with IMAP folders (#1110)


All of us would like that if read by one party it is already read on the other devices or if I reply or send a new email we would like this reply to be visible in the mail section sent on all devices. For this we rely on the IMAP protocol but, then the various mail programs I have to know how to manage the folders in such a way that they are always aligned / synchronized. I have read that this type of work is called interaction so my question is this: Is it possible to do this if so where should I start from?

I've never heard the term "interaction" before.

Yes, it's possible to do that... all you have to do is listen to all of the events on the ImapFolder class and handle them.

For example, when you get a MessageFlagsChanged event, you'll want to handle that by displaying the new set of message flags instead of what you were showing before the event fired.

When you get a MessageExpunged event (or MessageVanished if you enable QRESYNC), you'll want to handle that by removing the message from the list of messages.

When you get a CountChanbed, you'll want to handle that by queueing up a FETCH request for new messages (assuming the count didn't change due to messages being expunged).
