### ISSUE TITLE
**The client and server cannot communicate, because they do not possess a common algorithm** error connecting to Exchange  / OWA server over POP3 and SMTP 

### ISSUE THREAD

**Issue by lafar6502** [jstedfast/MailKit#1111]
I can confirm there is an error connecting to Exchange  / OWA server over POP3 and SMTP with Ssl or Tls enabled. Tried any combinations listed and not listed here, to no avail. the message is always 
**The client and server cannot communicate, because they do not possess a common algorithm**

.Net Framework v4.6.1

Solution was found by going back with MailKit versions.
The last version where the connection works is **MailKit v 2.3.1.6**
and the same exactly code breaks on next version **2.3.2** and all subsequent versions 

Can you please verify what was changed and where the problem could come from? 
PS im not a bot.
test code:
```
using (Pop3Client cli = new Pop3Client())
            {
                cli.CheckCertificateRevocation = false;
                cli.ServerCertificateValidationCallback = (s, c, ch, e) => true;
                //cli.SslProtocols = SslProtocols.Tls | SslProtocols.Tls11 | SslProtocols.Tls12  | SslProtocols.Ssl2;
                //cli.SslProtocols = SslProtocols.Ssl2;
                //cli.Timeout = NetworkTimeoutMs;
                cli.Connect(server, popPort);
                cli.Authenticate(user, pass);
                var uids = cli.GetMessageUids();
            }
```

_Originally posted by @lafar6502 in https://github.com/jstedfast/MailKit/issues/934#issuecomment-737861307_

**Comment by jstedfast** [comment]
This is what was changed in 2.3.2:

* Dropped SslProtocols.Tls (aka TLSv1.0) from the default SslProtocols used by IMAP, POP3
  and SMTP clients. To override this behavior, use the client.SslProtocols property
  to set the preferred SslProtocol(s).

And 2.10.0 dropped `SslProtocols.Tls11`.

What you can try doing is:

```csharp
cli.CheckCertificateRevocation = false;
cli.ServerCertificateValidationCallback = (s, c, ch, e) => true;
cli.SslProtocols |= SslProtocols.Tls | SslProtocols.Tls11;

cli.Connect (host, port, SecureSocketOptions.SslOnConnect);
```

Just to confirm, what port are you connecting to? 995?

**Comment by lafar6502** [comment]
smtp port 587
pop3 port 995
the error happened the same way both for SMTP and POP3 (so either both worked, or both didnt).
Unfortunately i dont have any details about the Exchange server configuration, but the problem only happens when communicating with Exchange, all other email servers i'm using worked fine with all Mailkit versions.
The lines in my code where i set SslProtocols were commented out because i experimented with this a lot, but no matter what combination was chosen it didnt work for versions above 2.3.1. 

Ok, now did some tests with 2.3.2
and 
your suggestion
```cli.SslProtocols |= SslProtocols.Tls | SslProtocols.Tls11;  ``` works OK
this
```cli.SslProtocols = SslProtocols.Default``` - doesn work
this
```cli.SslProtocols = SslProtocols.Tls | SslProtocols.Tls11 | SslProtocols.Tls12  | SslProtocols.Ssl2;``` - also doesnt work, which is quite strange as it allows more versions than the first one
and finally, if we dont specify any cli.SslProtocols (just dont set this property) the connection doesnt work either (but works prior to 2.3.2)

so all in all, maybe its some quirk of the Exchange and we can find the correct setting of SslProtocols but it's quite difficult to guess. But with this knowledge i think i will be able to upgrade to newer versions soon, thanks.

**Comment by jstedfast** [comment]
FWIW, the following line of code *adds* TLS v1.0 and TLSv1.1 to MailKit's default set of supported SSL/TLS protocol versions:

```csharp
cli.SslProtocols |= SslProtocols.Tls | SslProtocols.Tls11;
```

While the following code sets a list of supported protocols:

```csharp
cli.SslProtocols = SslProtocols.Tls | SslProtocols.Tls11 | SslProtocols.Tls12 | SslProtocols.Ssl2;
```

What *might* be breaking the above line is Ssl2. You *never* want SSLv2 - that's been dead since the mid-90's, replaced by SSLv3.

`SslProtocols.Default` is not quite what you probably think it is. According to the Microsoft docs for this value:

> Use None instead of Default. Default permits only the Secure Sockets Layer (SSL) 3.0 or Transport Layer Security (TLS) 1.0 protocols to be negotiated, and those options are now considered obsolete. Consequently, Default is not allowed in many organizations. Despite the name of this field, SslStream does not use it as a default except under special circumstances.

Hope that helps.
