### ISSUE TITLE
From is Empty

### ISSUE THREAD

**Issue by icemansven** [jstedfast/MailKit#1115]
**Describe the bug**
I have a old Telephone system with IMAP deamon. It is poorly implementet. I can fetch mails from the system, but MailKit returns no value in the from field. But Thunderbird does.
I can see in Thunderbird, the from has no domain, only a phone number.

**Platform (please complete the following information):**
 - OS: Windows Server 2016
 - .NET Runtime: CoreCLR
 - .NET Framework: .NET 4.8
 - MailKit Version: 2.10.0

**To Reproduce**
Not shure it is posible
Fetch a mail with has no domain
**Expected behavior**
Get the value

**Screenshots**
<img width="935" alt="MailKit" src="https://user-images.githubusercontent.com/62931183/101980812-6e510180-3c68-11eb-92ca-adfee7749895.png">

**Additional context**
N/T

**Comment by icemansven** [comment]
Found a work-a-round

```
message.WriteTo("readout.eml");

using (var sr = new System.IO.StreamReader("readout.eml"))
						{
							while (sr.Peek() >= 0)
							{
								strline = sr.ReadLine();
								if (strline.StartsWith("X-MessageSenderID:", System.StringComparison.CurrentCultureIgnoreCase))
								{
									strfrom = strline.Replace("X-MessageSenderID: ", "");
									Console.WriteLine("From:{0}", strfrom);
									break;

								}
							}
						}
```

**Comment by jstedfast** [comment]
Hi @icemansven 

Sorry for the delay, I've just been so busy due to the holidays.

Looks like you've figured out a decent work-around but this little trick might help reduce the amount of processing that you have to do:

```csharp
int index = message.Headers.IndexOf ("X-MessageSenderID");
if (index != -1) {
    var header = message.Headers[index];
    InternetAddressList.TryParse (header.RawValue, out var from);

    // now you can use `from` as if it were the message.From property
}
```
