### ISSUE TITLE
Save message with attachment as eml file

### ISSUE THREAD

**Issue by ghendo** [jstedfast/MailKit#1123]
To help me debug your issue, please explain:
- What were you trying to do?
     save a message as eml file
     using WriteTo()
- What happened?
    All ok except attachment which is a stream is not written.
- What did you expect to happen?
    I expected the full message to be written including the attachments streams
- Step-by-step reproduction instructions and/or a simple test case.
    CREATE THE ATTACHMENT
                var attachment = new MimePart()
                {
                    Content = new MimeContent(streamOut),
                    ContentDisposition = new ContentDisposition(ContentDisposition.Attachment),
                    FileName = item.Key,
                    IsAttachment = true
                };
    AFTER ADDING THE ATTACHMENT TO THE MESSAGE
                using (var ms = new MemoryStream())
                {
                    await message.WriteToAsync(ms, false).ConfigureAwait(false);
                    var buffer = ms.ToArray();
                    var str = Encoding.UTF8.GetString(buffer);
                }

**Comment by jstedfast** [comment]
Make sure that you set the `Position` of `streamOut` back to 0.
