### ISSUE TITLE
Authenticate dosnt work if password contains % character 

### ISSUE THREAD

**Issue by Skr1pt** [jstedfast/MailKit#1125]
If i try login to mail with password that  contains % character and catch {"The IMAP server has unexpectedly disconnected." exception

**Comment by jstedfast** [comment]
I just tested this and MailKit properly quotes passwords with % in them for the LOGIN command.

What does the [protocol log](https://github.com/jstedfast/MailKit/blob/master/FAQ.md#ProtocolLog) show?
