### ISSUE TITLE
[help] how can i do fetch while idling ?

### ISSUE THREAD

**Issue by lyling** [jstedfast/MailKit#1127]
My client is idling.  And i want to use fetch or search action. 
When i do fetching while idling, i get and get error about synchronize

**Comment by jstedfast** [comment]
Have you checked out the IDLE sample? https://github.com/jstedfast/MailKit/blob/master/samples/ImapIdle/ImapIdle/IdleClient.cs

What you need to do is to "cancel" the `doneToken` in the event handler so that the IDLE command ends and then you can send a FETCH command.
