### ISSUE TITLE
MailKit - ImapClient() .search() does not read EVERY emails C#

### ISSUE THREAD

**Issue by VicoLeChips49** [jstedfast/MailKit#1128]
I'm using the MailKit client library to use the IMAP protocol in order to read my mails and search in it for a specific mail. It does work well for recent mail (less than a month and a half). But when I'm trying to search for an email that contains "myWordToSearch" from a long time (6 months old or stuff like that) it tells me that it does not exist, because it does not go that deep into the mails. Is there a way to retrieve/read ALL emails in order to filter them (like the search bar on gmail or stuff like that) ?

Here is my code :

`
               using (var client = new ImapClient())
               {
                        using (var cancel = new CancellationTokenSource())
                        {

                            client.Connect("imap." + provider , 993, true, cancel.Token);
                            client.Authenticate(myMail, myPassword, cancel.Token);
                            var inbox = client.Inbox;
                            inbox.Open(FolderAccess.ReadOnly, cancel.Token);

                            var mail = (SearchQuery.SubjectContains(myWordToSearch)); 
                            foreach (var uid in inbox.Search(mail, cancel.Token))
                            {
                                  var message = inbox.GetMessage(uid, cancel.Token);
                            }
                         }
                }
`

**Comment by jstedfast** [comment]
You could try getting a [protocol log](https://github.com/jstedfast/MailKit/blob/master/FAQ.md#ProtocolLog) to see what is happening, but it sounds like a bug in the IMAP server since sending a subject search query is really trivial.

**Comment by VicoLeChips49** [comment]
Thanks a lot for the answer.
Should i search headers only ?

**Comment by jstedfast** [comment]
@VicoLeChips49 hard to know because it's impossible to know what other bugs/limitations the IMAP server might have.

I guess I would recommend fetching the ENVELOPE for all messages and doing your own subject matching.

```csharp
var summaries = folder.Fetch (0, -1, MessageSummaryItems.UniqueId | MessageSummaryItems.Envelope);
foreach (var summary in summaries) {
    if (summary.Envelope.Subject.Contains (myWordToSearch)) {
        var message = inbox.GetMessage(uid, cancel.Token);
        // ...
    }
}
```
