### ISSUE TITLE
Search Subject doesn`t work for any character.

### ISSUE THREAD

**Issue by lyling** [jstedfast/MailKit#1130]
C: A00000007 UID SEARCH CHARSET UTF-8 SUBJECT {3}
S: * SEARCH 1474 1475 1476 1477 1478 1479 1480 1499 1500 1501 1502 1503 1504 1505 1506 1507 1508 1509 1510 1511 1512 1513 1514 1515 1516 1517 1518 1519 1520 1521 1522 1523 1524 1525 1526 1527 1528 1529 1530 1532
S: A00000007 OK UID SEARCH completed

I think it is lack of one line about "C: XXX" after the first line.

**Comment by jstedfast** [comment]
What string are you searching for?

**Comment by lyling** [comment]
> What string are you searching for?

any. 
中文 at this case.

**Comment by lyling** [comment]
outlook server

**Comment by jstedfast** [comment]
The server is supposed to send back a `S: +` response which is when MailKit would send the `C: XXX` part of the request.

Apparently the server is doing a search thinking that `{3}` is the text to search for.

This is a bug in the server because the `{###}` syntax tells the server that there is more to the search command and that the client is waiting for the server to give it the OK to send the rest of it.

**Comment by lyling** [comment]
> The server is supposed to send back a `S: +` response which is when MailKit would send the `C: XXX` part of the request.
> 
> Apparently the server is doing a search thinking that `{3}` is the text to search for.
> 
> This is a bug in the server because the `{###}` syntax tells the server that there is more to the search command and that the client is waiting for the server to give it the OK to send the rest of it.

C: A00000007 UID SEARCH CHARSET UTF-8 SUBJECT {6+}
C: 电子
S: A00000007 NO [BADCHARSET (US-ASCII)] The specified charset is not supported.
C: A00000008 UID SEARCH SUBJECT {2+}
C: 5P
S: * SEARCH 1415
S: A00000008 OK SEARCH completed.

another server.  Why BADCHARSET? i searched some solution about using Search("CHARSET UTF-8 XXXX") , but the method of string parameter is not supported now. 
how to solve it?

**Comment by jstedfast** [comment]
Not all IMAP servers support UTF-8 search. Some only support US-ASCII (which is apparently what your server supports).

Search (string) still exists, but you need to cast:

```csharp
var results = ((ImapFolder) folder).Search ("CHARSET UTF-8 SUBJECT XXX");
```
