### ISSUE TITLE
pop3Client: A connection attempt failed because the connected party...

### ISSUE THREAD

**Issue by skdutta-ga** [jstedfast/MailKit#1131]
I am having this issue in a local machine...

```
try{
pop3Client.ServerCertificateValidationCallback = (s, c, h, e) => true;
pop3Client.Connect("pop.gmail.com", 995, SecureSocketOptions.SslOnConnect);
pop3Client.Authenticate(logonName, logonPassword);
}
catch(Exception e){
}
```

I am getting the exception:
"A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond"

The log is:
Connected to pops://pop.gmail.com:995/
S: +OK Gpop ready for requests from 71.59.xx.xxx l13mb529002861qtp
C: CAPA
S: +OK Capability list follows
S: USER
S: RESP-CODES
S: EXPIRE 0
S: LOGIN-DELAY 300
S: TOP
S: UIDL
S: X-GOOGLE-RICO
S: SASL PLAIN XOAUTH2 OAUTHBEARER
S: .
C: AUTH PLAIN
S: + 
C: ....base64string.... (decodes to: recent:xxx@domain.com,My-password)

**Comment by jstedfast** [comment]
Looks like the TCP connection timed out. What you need to do is catch exceptions like this one and re-connect and try again.

This is a fairly common network error that happens to all network software.

**Comment by skdutta-ga** [comment]
Tried this and still it is not working. Is there a way to find out what is happening or google just shut off the pop3 access? I already enabled pop3 in settings and enabled the less secure apps.

**Comment by jstedfast** [comment]
You could try setting the client.Timeout property to something larger...

The default timeout should be plenty, though.

You don't actually need to enable POP3 access in your gmail settings to be able to connect to pop.gmail.com - that server is always up regardless. The setting only enables authentication to work for your account.
