### ISSUE TITLE
An error occurred while attempting to establish an SSL or TLS connection.

### ISSUE THREAD

**Issue by prafula** [jstedfast/MailKit#1132]
**Describe the bug**
We are getting the following exception -

Exception Details :-

The server's SSL certificate could not be validated for the following reasons:
• The server certificate has the following errors:
• The revocation function was unable to check revocation for the certificate.
• The revocation function was unable to check revocation because the revocation server was offline.
• An intermediate certificate has the following errors:
• The revocation function was unable to check revocation for the certificate.
• The revocation function was unable to check revocation because the revocation server was offline.

Code -

```
using (var client = new SmtpClient())
                {
                    client.Connect(_smtpServer);
                    client.AuthenticationMechanisms.Remove("XOAUTH2");
                    client.Send(message);
                    client.Disconnect(true);
                }

```

**Platform (please complete the following information):**
 - OS: [e.g. Windows, Linux, MacOS, iOS, Android, Windows Phone, etc.] - Windows server
 - .NET Runtime: [e.g. CoreCLR, Mono] 
 - .NET Framework: [e.g. .Net Core, .NET 4.5, UWP, etc.] .NET 4.7
 - MailKit Version: 2.7/2.10

**Comment by prafula** [comment]
This seems to be broken ~ 24 hours before the issue is reported.

**Comment by jstedfast** [comment]
What you can do in this situation is:

```csharp
using (var client = new SmtpClient())
{
    client.CheckCertificateRevocation = false;
    client.Connect(_smtpServer);
    client.AuthenticationMechanisms.Remove("XOAUTH2");
    client.Send(message);
    client.Disconnect(true);
}
```

http://www.mimekit.net/docs/html/P_MailKit_IMailService_CheckCertificateRevocation.htm
