### ISSUE TITLE
IMAP Client emails are not flagged properly

### ISSUE THREAD

**Issue by Tr1KzZ** [jstedfast/MailKit#1133]
**Describe the bug**
I'm connecting to a outlook (O365) mailbox via imap client and retrieving mail summaries including flags, internalDate and uniqueId. The program processes the emails and flags emails that cannot be processed. If the flagged email is now processed in Outlook, for example, and the flag is removed, then the email will still be listed as flagged when it is fetched by the imap client again.

**Platform (please complete the following information):**
 - OS: Windows 10
 - .NET Runtime: .NET 5 project inside linux docker container, 5.0-buster-slim
 - .NET Framework: Mailkit inside a .NET Standard 2.0 custom nuget package loaded inside a .NET 5 project
 - MailKit Version:  2.10.1

**To Reproduce**
Create a basic imap client, authenticate via credentials and request mails from a folder

```csharp
var client = new ImapClient();
await client.ConnectAsync(host, port, true);
await client.AuthenticateAsync(credential);
var folder = await client.GetFolderAsync(folderPath); // e.g. INBOX/Produktiv
await folder.OpenAsync(ReadOption.ReadOnly);
var summaries = await folder.FetchAsync(0, -1, MessageSummaryItems.Flags | MessageSummaryItems.InternalDate | MessageSummaryItems.UniqueId);
var flags = summaries.First().Flags; // returns "seen | flagged" although the mail inside outlook was manually unflagged
await client.DisconnectAsync(true);
```

**Expected behavior**
1. Imap client returns 2 mails (both for example unseen | recent)
2. one mail moved to different folder and the other was flagged (via mailkit)
3. Imap client returns 1 seen | flagged mail
4. the flagged mail was unflagged (via outlook)
5. Imap client returns 1 seen | unflagged mail

**Screenshots**
1. First run (Debug Code, Outlook):
    ![image](https://user-images.githubusercontent.com/67892761/104326145-abb7e180-54e9-11eb-8821-8ad74418ba7f.png) ![image](https://user-images.githubusercontent.com/67892761/104326198-becab180-54e9-11eb-8e20-138540c4f4eb.png)

2. Second run, after unflagging mail inside outlook (Debug code, Outlook):
    ![image](https://user-images.githubusercontent.com/67892761/104326338-ef125000-54e9-11eb-9ff1-b967a65cce2d.png) ![image](https://user-images.githubusercontent.com/67892761/104326267-d6a23580-54e9-11eb-8b1a-89e118f9827d.png)

Addition: Found out, that moving the mail outside the folder and again in, fixes the problem because it generates a new ID, is there some kind of Caching while reading mails via imap client? 
![image](https://user-images.githubusercontent.com/67892761/104327051-ad35d980-54ea-11eb-8002-4e44d888c3e4.png)

**Comment by jstedfast** [comment]
The issue you are facing is that the server (not MailKit) is caching state of the message(s).

It's odd that the cache lives between reconnecting/opening the folder. That sounds like a bug in the server (or maybe Outlook hasn't synced the flag to the server yet??).

The best idea I can come up with is to try calling `await folder.CheckAsync ();` and seeing if that causes the IMAP server to flush its cache and reread state.

**Comment by Tr1KzZ** [comment]
Thanks for the suggested CheckAsync function, but that does not change anything, mails are still not updated.

After some further research, it seems that this might be an Outlook bug, as many other users post about flagged mails not syncing with ToDo/Task Lists or the Outlook OWA. Changing the state between seen and unseen is updating immediately when fetched by the imap client, so sync works as aspected, but strangely not for (un)flagged mails.

Sadly I couldn't find a way to manually clear that local cache and force sync the flagged mails, might try other approaches to differ between those mails.

**Comment by jstedfast** [comment]
@Tr1KzZ That's interesting... thanks for the update on that.

If the issue is that Outlook isn't syncing the state of the "Flagged" flag, then yea, the `Check` command won't help unfortunately since that just forces the server to re-sync state and doesn't have any effect on what Outlook does :-(
