### ISSUE TITLE
Mail not received when sent from some devices but not others

### ISSUE THREAD

**Issue by Alexios-Sam** [jstedfast/MailKit#1134]
I have an app, made in unity, where I send an image as an attachment through SMTP using one.com's webmail, port 587 to a gmail, and it works fine on some devices, but on two of the six devices I have tested it on, the mail does not get received.
I am sending it from the same one.com mail to the same gmail on every device, and on every device, it gets send without any errors, but even with consecutive tests, the mail is not received when sent from the same two devices.

It works on my desktop computer, Samsung Galaxy S9 (android phone), Samsung Galaxy Tab A 10.1 (android tablet),  and Xiaomi Pocophone F1 (android phone), but does not work on Samsung Galaxy A50 (android phone) and Sony Xperia XA (android phone). I tested the Samsung Galaxy S9 and the phones that didn't work using Unity's Android Logcat to check for errors, but the only error I get is "unable to find libc", which occurs on every one of the devices and shouldn't be the problem.

The confusing part is that it used to work on the Sony Xperia XA two months ago (14/11/2020), but even when I installed the previous version of the app that it used to work on, on both the Sony and the Samsung A50, it doesn't work now.

This is a simplified version of the code, everything important should be here:
```
private void SendMailUsingSMTP(string password)
{
    var message = new MimeMessage();
    message.From.Add(new MailboxAddress(user.Email));
    foreach (var mail in emailGroupData.RecipientMails)
    {
        if(mail.Length > 0)
        {
            message.Bcc.Add(new MailboxAddress(mail));
        }
    }
    message.Subject = MailSubject;
    var builder = new BodyBuilder();
    builder.TextBody = @"E-mail sent gennem regnskabsskolen's app";
    string imagePath = GetImageScript.GetImagePath();
    builder.Attachments.Add(@imagePath);
    message.Body = builder.ToMessageBody();
    using (var client = new SmtpClient())
    {
        client.ServerCertificateValidationCallback = (s, c, h, e) => true;
        client.Connect("send.one.com", 587, false);
        client.Authenticate(user.Email, password);
        client.Send(message);
        client.Disconnect(true);
     }
 }
```

**Comment by jstedfast** [comment]
I would recommend getting a [protocol log](https://github.com/jstedfast/MailKit/blob/master/FAQ.md#ProtocolLog) to see if that provides any clues. You are welcome to share it with me if you don't see anything obvious (just be sure to munge the "AUTHENTICATE" command before posting it in a GitHub comment).

**Comment by Alexios-Sam** [comment]
I did a protocol log for the devices that didn't work and compared it to a device that worked, and the data was almost identical, the only data that changed was the data that is expected to change. I would have added the log here but I wasn't sure if the only data I had to manipulate was the emails or if I had to manipulate the long number after the auth plain and remove the raw transfer data of what I expect to be a more than a thousand lines.

An even more confusing thing happened, randomly the Sony Xperia XA started working again, but not the Samsung Galaxy A50, that one still does still not work. 

If I can't figure out why this happens, is it possible to set up something to give me feedback if the email was received successfully? Like a listener on the one.com server-side of the specific email to send a ping when the email is received. Kind of like what you get when you get an email on your phone, because the user won't have access to the mail that the message is being sent to.

**Comment by jstedfast** [comment]
The most important piece to check is the response from the server after the contents of the message get posted.

For example:

```
...
C: DATA
<contents of message>
C: .
S: 250 Message sent
```

**Comment by Alexios-Sam** [comment]
I will post the server response below, I changed the email address, email subject, and email body as well as removing data indicated by |(removed data)| - just so we're on the same page. The first log is from a device that works and the second is from the one that doesn't.
Working device log:
```
C: DATA
S: 354 End data with <CR><LF>.<CR><LF>
C: From: censored-mail@one.com
C: Date: Tue, 12 Jan 2021 22:17:34 +0100
C: Subject: email subject (changed)
C: Message-Id: <IK27DBN0PCU4.EK1YGFS6DT2@localhost>
C: MIME-Version: 1.0
C: Content-Type: multipart/mixed; boundary="=-ZGBWyF7IN7bSvVGgQsWtgw=="
C: 
C: --=-ZGBWyF7IN7bSvVGgQsWtgw==
C: Content-Type: text/plain; charset=utf-8
C: 
C: email body (changed): 
C: --=-ZGBWyF7IN7bSvVGgQsWtgw==
C: Content-Type: image/jpeg; name=IMG_camera.jpg
C: Content-Disposition: attachment; filename=IMG_camera.jpg
C: Content-Transfer-Encoding: base64
 |(removed data)|
C: --=-ZGBWyF7IN7bSvVGgQsWtgw==--
C: .
S: 250 2.0.0 Ok: queued as 97120da8-551b-11eb-8cbd-d0431ea8bb03
C: QUIT
S: 221 2.0.0 Bye
```
Non-working device log:
```
C: DATA
S: 354 End data with <CR><LF>.<CR><LF>
C: From: censored-mail@one.com
C: Date: Tue, 12 Jan 2021 22:35:21 +0100
C: Subject: email subject (changed)
C: Message-Id: <IP7EP7S0PCU4.KDR38OD5SQ032@localhost>
C: MIME-Version: 1.0
C: Content-Type: multipart/mixed; boundary="=-W8oOyw32fG3FON7lIH+n8w=="
C: 
C: --=-W8oOyw32fG3FON7lIH+n8w==
C: Content-Type: text/plain; charset=utf-8
C: 
C: email body (changed): 
C: --=-W8oOyw32fG3FON7lIH+n8w==
C: Content-Type: image/jpeg; name=IMG_camera.jpg
C: Content-Disposition: attachment; filename=IMG_camera.jpg
C: Content-Transfer-Encoding: base64
 |(removed data)|
C: --=-W8oOyw32fG3FON7lIH+n8w==--
C: .
S: 250 2.0.0 Ok: queued as 12d13e6c-551e-11eb-923f-d0431ea8a283
C: QUIT
S: 221 2.0.0 Bye
```
I can see the message gets queued which I guess might be the reason why I can't get info if it fails.

**Comment by jstedfast** [comment]
Yea, the 250 response code tells MailKit that the message has been successfully "sent" (or, in this case, queued to be sent) and it's out of MailKit's hands at that point.

Have you checked spam folders or anything? Maybe the messages ended up there?
