### ISSUE TITLE
MailFaulted event

### ISSUE THREAD

**Issue by Taldrit** [jstedfast/MailKit#1138]
**Is your feature request related to a problem? Please describe.**
If you send a mail by SendAsync and don't want to await the return (you use async so you don't have to), you have to use handlers like ContinueWith Action<Task> and so on. That is uncomfortable for a programmer to use. If it sends, everything is fine, but if the sending does not work, possible exceptions are lost and there is no further handling.

**Describe the solution you'd like**
It would be really cool if there was some event handler like the MailSent event, where I can handle my exceptions and so on.

**Describe alternatives you've considered**
Using a ContinueWith, but as already written, that is not really nice to use.

**Additional context**
-

**Comment by jstedfast** [comment]
This sounds like what you want to do is `await`. You can make your own async wrapper method that awaits MailKit's SendAsync() method, catches the exceptions, and does whatever you need to do.
