### ISSUE TITLE
I'm getting "BAD Command Argument Error. 11" when set \Seen flag

### ISSUE THREAD

**Issue by odabas** [jstedfast/MailKit#1139]
I'm trying to mark as read a mail in my inbox.And I'm getting BAD Command Argument Error. 11 error when i set the flag.

CAPABILITY from my ProtocolLogger :
**S: * CAPABILITY IMAP4 IMAP4rev1 AUTH=NTLM AUTH=GSSAPI AUTH=PLAIN  STARTTLS UIDPLUS CHILDREN IDLE NAMESPACE LITERAL+**

Error part from my ProtocolLogger :

**S: A00000013 OK FETCH completed.
C: A00000014 UID STORE 108 FLAGS.SILENT (\Seen)
S: A00000014 BAD Command Argument Error. 11**

Actually i can run this command with  Exchange server 2015 but we have another server version is 2010.
I need to run this with Exchange Server 2010 too.

I'm getting uid's like below
`var client = new ImapClient(new ProtocolLogger("imap.log"))`
*
*
*

```
var uids = client.Inbox.Search(searchQuery);
                foreach (var uid in uids)
                {
                    var message = client.Inbox.GetMessage(uid);
```

It's thrown exception at this line:
`client.Inbox.SetFlags(uid, MessageFlags.Seen, true);
`
Also i have a same problem with  MessageFlags.Deleted flag too.

`client.Inbox.SetFlags(uid, MessageFlags.Deleted, true);
`
How can i fix this problem ?

**Comment by jstedfast** [comment]
That appears to be a server bug.

You might be able to work around it by using the index-based SetFlags method (i.e. using an int index rather than a UID).

The BAD response is supposed to only be used by the server if the command is malformed (which in this case, it is not).
