### ISSUE TITLE
Can not send emails after updating from .NET Core 3.1 to .NET 5

### ISSUE THREAD

**Issue by Mihail1996** [jstedfast/MailKit#1140]
Hello, 
I recently updated a mailing microservice from .net core 3.1 to .net 5, which runs in a linux docker image, and I keep getting the exception "An error occurred while attempting to establish an SSL or TLS connection."

First I've tried every solution from your FAQ and it still did not work. When I downgrade the service from .NET 5 to .NET core 3.1 it works fine. So it is not the code, and furthermore I am able to connect to google's smtp server with the .NET 5 version.

Having said that, the only options left for me is this breaking change from microsoft [Default TLS cipher suites for .NET on Linux](https://docs.microsoft.com/en-us/dotnet/core/compatibility/cryptography/5.0/default-cipher-suites-for-tls-on-linux). 
The server I'm trying to connect to is using TLS1.2 with the cipher AES256-GCM-SHA384, which is not in the list for .NET 5 for Linux from the link above.
 
I've tried to add the cipher to openssl.cnf in the docker image but without success. 

Also, I've tried to set the CipherSuitePolicy for Kestrel and it still did not work.

This is the Smtp.log with .NET 5

Connected to smtp://smtp.mngt.local:587/?starttls=when-available
S: 220 smtp.company-name.pt ESMTP Haraka/2.8.23 ready
C: EHLO [10.42.20.59]
S: 250-smtp.company-name.pt Hello [10.172.16.38]Haraka is at your service.
S: 250-PIPELINING
S: 250-8BITMIME
S: 250-SMTPUTF8
S: 250-SIZE 0
S: 250 STARTTLS
C: STARTTLS
S: 220 Go ahead.

So I'd like to know where is MailKit getting the available ciphers from? Is it something internal? system defaults?

Thank you very much!

**Comment by Mihail1996** [comment]
Thank you for your answer!

From my research  `AES256-GCM-SHA384` and `TLS_AES_256_GCM_SHA384` are different ciphers, their authentication is different.

When I use OpenSsl to connect to the server I get this:

```
openssl s_client -connect smtp.mngt.local:465
CONNECTED(00000003)
depth=0 C = PT, ST = Campo Grande, L = Lisboa, O = NOS DC, CN = smtp.mngt.local, emailAddress = admin@dc.nos.pt
verify error:num=18:self signed certificate
verify return:1
depth=0 C = PT, ST = Campo Grande, L = Lisboa, O = NOS DC, CN = smtp.mngt.local, emailAddress = admin@dc.nos.pt
verify return:1
---
Certificate chain
 0 s:C = PT, ST = Campo Grande, L = Lisboa, O = NOS DC, CN = smtp.mngt.local, emailAddress = admin@dc.nos.pt
   i:C = PT, ST = Campo Grande, L = Lisboa, O = NOS DC, CN = smtp.mngt.local, emailAddress = admin@dc.nos.pt
---
Server certificate
-----BEGIN CERTIFICATE-----
MIID1TCCAr2gAwIBAgIJANUClQo1V4djMA0GCSqGSIb3DQEBCwUAMIGAMQswCQYD
VQQGEwJQVDEVMBMGA1UECAwMQ2FtcG8gR3JhbmRlMQ8wDQYDVQQHDAZMaXNib2Ex
DzANBgNVBAoMBk5PUyBEQzEYMBYGA1UEAwwPc210cC5tbmd0LmxvY2FsMR4wHAYJ
KoZIhvcNAQkBFg9hZG1pbkBkYy5ub3MucHQwHhcNMTkwMTIxMTQ0ODA3WhcNMjUw
MTE5MTQ0ODA3WjCBgDELMAkGA1UEBhMCUFQxFTATBgNVBAgMDENhbXBvIEdyYW5k
ZTEPMA0GA1UEBwwGTGlzYm9hMQ8wDQYDVQQKDAZOT1MgREMxGDAWBgNVBAMMD3Nt
dHAubW5ndC5sb2NhbDEeMBwGCSqGSIb3DQEJARYPYWRtaW5AZGMubm9zLnB0MIIB
IjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAshe3Pne/fegAfT7KSNgeFh9Z
3eOLnSCQ5x/U/vRNygsdH5Zhx35rzX7ru5UaobzAwC80FQksK1GVnUaOBMEqGmQ6
srs6zsy/1a7jC4tjNZh/LMWprS8BX/UMf+70gVRsyW5iLTzBVuPxo/UDmp1Hs/Er
Msva5UkHjBvdRsjze+KXQ5SBupAZ0g/5u5+j/FqeUpckpNjPSri7ITj4FRJzCsFj
PuJ0zHHrhpIfoPWtUc13sECquFukPs5Sp3pyp2sa/zDfRWaBgCqnNx9rI4DiOczO
wUWEJcFz9oGaRkM7vO8lra3UM6PmV72ItD95I9z79Zcty8zhBEHp4SGmgQxfLQID
AQABo1AwTjAdBgNVHQ4EFgQUrKzpacIm6baoxQoPnDqQpSMAD9kwHwYDVR0jBBgw
FoAUrKzpacIm6baoxQoPnDqQpSMAD9kwDAYDVR0TBAUwAwEB/zANBgkqhkiG9w0B
AQsFAAOCAQEAUrQZa0TQRpcOoR3AnY/nkNPTCuiOh24MqE+0l11e2TxhTDhwcwHK
EpWdL+f9MQMI5ncn3d9gyYYtj1yuQNQEv25o9R7DEmF1tMw4qximOZHkm91Gvwny
sktf1fCEd1J0LGoE0BxTjx67lyY+nTNP0kV1gbjY//iEkbTZ1pMuQrjHe+y+uPEe
05KW3UNKPOQ0pWWaWTvVKxWTnvLhGUqypcT+Jv0yXpgS1m04eAO0DRBPMuZz3UER
Ea1JB2SPJnYznCsx1aCkj5w4EcT4w1umNWopx1IioTEbT/SaHO4FNS40yx+S7Gsv
Zlr7sP3MdkANkn9F5qKFXbAQhvwu1tyF7Q==
-----END CERTIFICATE-----
subject=C = PT, ST = Campo Grande, L = Lisboa, O = NOS DC, CN = smtp.mngt.local, emailAddress = admin@dc.nos.pt

issuer=C = PT, ST = Campo Grande, L = Lisboa, O = NOS DC, CN = smtp.mngt.local, emailAddress = admin@dc.nos.pt

---
No client certificate CA names sent
Client Certificate Types: RSA sign, DSA sign, ECDSA sign
Requested Signature Algorithms: RSA+SHA512:DSA+SHA512:ECDSA+SHA512:RSA+SHA384:DSA+SHA384:ECDSA+SHA384:RSA+SHA256:DSA+SHA256:ECDSA+SHA256:RSA+SHA224:DSA+SHA224:ECDSA+SHA224:RSA+SHA1:DSA+SHA1:ECDSA+SHA1
Shared Requested Signature Algorithms: RSA+SHA512:DSA+SHA512:ECDSA+SHA512:RSA+SHA384:DSA+SHA384:ECDSA+SHA384:RSA+SHA256:DSA+SHA256:ECDSA+SHA256:RSA+SHA224:DSA+SHA224:ECDSA+SHA224
---
SSL handshake has read 1351 bytes and written 637 bytes
Verification error: self signed certificate
---
New, TLSv1.2, Cipher is AES256-GCM-SHA384
Server public key is 2048 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : AES256-GCM-SHA384
    Session-ID: 13951D0A92FFF79CD904858A2948B8B43CF50E6ABC518370DD9AE66DC8ED4D5C
    Session-ID-ctx: 
    Master-Key: C484F7ADC846A31F7268AE9D150489D2136496377BD3257FC48ADF8CE60F4ABCE45E497CD6B441A145F14A38B3142E0A
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    TLS session ticket lifetime hint: 300 (seconds)
    TLS session ticket:
    0000 - 6c 5c a0 30 f1 a3 e0 09-31 2e 0b 32 69 1b 21 56   l\.0....1..2i.!V
    0010 - 57 81 ae 71 18 90 8c 11-fa 9d 4e 4e a4 00 da 48   W..q......NN...H
    0020 - 2f d7 ed 73 05 6e 93 08-35 c3 89 b1 d5 9f f6 e8   /..s.n..5.......
    0030 - 23 8a 8a 49 0d 99 e7 d9-13 0b 64 c2 22 96 f5 e3   #..I......d."...
    0040 - 6e a7 2b 47 e3 24 a0 b8-3a 9f a5 4b 6c d4 b7 ff   n.+G.$..:..Kl...
    0050 - f7 bc 2d 9f f1 a1 14 53-c0 99 01 b2 98 4d e6 ef   ..-....S.....M..
    0060 - e3 61 af d8 6f 9a a8 c1-ad e4 ce e3 2b 74 ef 9c   .a..o.......+t..
    0070 - 39 81 9c 26 4a 76 9d f6-32 01 b8 93 1f 25 9b 0e   9..&Jv..2....%..
    0080 - da ca cb c2 3c ab 9b 71-dd ff 7a b4 d6 23 99 9b   ....<..q..z..#..
    0090 - a8 80 b2 96 6d ac 49 8c-1c fd cf c9 7e c1 4c 06   ....m.I.....~.L.
    00a0 - 74 9c c6 79 fb 14 3d cb-71 ab 5a 01 9f 26 85 55   t..y..=.q.Z..&.U

    Start Time: 1611247663
    Timeout   : 7200 (sec)
    Verify return code: 18 (self signed certificate)
    Extended master secret: no
---
220 smtp.dc.nos.pt ESMTP Haraka/2.8.23 ready

```

From this we can see that it is using a self signed certificate, however I am using 
```csharp
client.ServerCertificateValidationCallback = (s,c,h,e) => true;
client.CheckCertificateRevocation = false;
```
And furthermore, it doesn't make sense to work perfectly on .NET Core 3.1 and not in .NET 5

I have tried with Ubuntu and Alpine ditros, and I appended these lines to `/etc/ssl/openssl.cnf`
```
openssl_conf = default_conf

[default_conf]
ssl_conf = ssl_sect

[ssl_sect]
system_default = system_default_sect

[system_default_sect]
CipherString = AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES128-SHA256
```

**Comment by jstedfast** [comment]
> From my research AES256-GCM-SHA384 and TLS_AES_256_GCM_SHA384 are different ciphers, their authentication is different.

Ah, good to know! Looks like, based on your openssl output, that the algorithm name that you used in the config file would be correct.

I'm curious, what if you set `client.ServerCertificateValidationCallback` to a method with the proper signature that returns true but also prints something to the console so that you can see if it even gets called?

That might at least tell us if it's getting that far or if it's failing before that check.

**Comment by Mihail1996** [comment]
> I'm curious, what if you set `client.ServerCertificateValidationCallback` to a method with the proper signature that returns true but also prints something to the console so that you can see if it even gets called?

I did that and I can not see the log! It must fail before that

**Comment by jstedfast** [comment]
That suggests that the SslStream hasn't gotten around to validating certificates, yet, then, which supports your theory that it has something to do with negotiating the supported algorithms.

**Comment by jstedfast** [comment]
Looks like .NET 5.0 added [AuthenticateAsClientAsync(SslClientAuthenticationOptions, CancellationToken)](https://docs.microsoft.com/en-us/dotnet/api/system.net.security.sslstream.authenticateasclientasync?view=net-5.0#System_Net_Security_SslStream_AuthenticateAsClientAsync_System_Net_Security_SslClientAuthenticationOptions_System_Threading_CancellationToken_) and [SslClientAuthenticationOptions](https://docs.microsoft.com/en-us/dotnet/api/system.net.security.sslclientauthenticationoptions?view=net-5.0) has a [CipherSuitesPolicy](https://docs.microsoft.com/en-us/dotnet/api/system.net.security.sslclientauthenticationoptions.ciphersuitespolicy?view=net-5.0#System_Net_Security_SslClientAuthenticationOptions_CipherSuitesPolicy) property that allows setting which cipher algorithms to allow.

Maybe I can extend MailKit's IMailService API to allow setting a CipherSuitePolicy as well for NET50.

**Comment by Mihail1996** [comment]
Yes that is what I was going to suggest, a way of setting the CipherSuitesPolicy. Setting it at "system default" does not seem to be easy, and also, a developer may want to only allow weak ciphers to a specific mail server, and not to the whole system.
I can even help with the code if you need me to :)

Thank you for your time!

**Comment by jstedfast** [comment]
The above patch *should* fix this issue. I've got to get back to work, but hopefully some myget packages will be pushed by the automated build system to https://www.myget.org/feed/mimekit/package/nuget/MailKit

It'll be v2.10.1.8, I think.

There's a new property on each of the Smtp/Pop3/ImapClients called `SslCipherSuitesPolicy` that you can set.

**Comment by Mihail1996** [comment]
Thank you! I will test again when this change is out and I will let you know if it worked.

**Comment by Mihail1996** [comment]
Hi, 
I tried to test this but I don't seem to find the property `SslCipherSuitesPolicy` . I'm using .NET 5.0 and Mailkit 2.11.1

I was looking at your [commit](https://github.com/jstedfast/MailKit/commit/1168bd75e9b4e206cd887482515f1e637f3782af) and I noticed you have `#if NET50`, and I looked up the documentation and it says that we should use `NET5_0` instead, so this could be the problem.

Thank you

**Comment by Mihail1996** [comment]
I can confirm that this change fixed the issue.
