### ISSUE TITLE
Can't search emails by `FormContains` or `SubjectContains` in QQ email.

### ISSUE THREAD

**Issue by BeGemini** [jstedfast/MailKit#1143]
**Describe the bug**
Here's my code.
```csharp
            IList<IMailFolder> folders = client.GetFolders(client.PersonalNamespaces[0]);
            foreach (var folder in folders)
            {
                if(((FolderAttributes)folder.Attributes).ToString().Contains("NoSelect"))
                    continue;
                foler.Open(MailKit.FolderAccess.ReadOnly);
                var uidss = folder.Search(SearchQuery.FromContains("sth@sth.com"));
                var uis = folder.Search(SearchQuery.SubjectContains("sth"));
             }
```
The mails in `uidss` are all the mails in the folder `folder` without any filter. It means `SearchQuery.FromContains` and  `SearchQuery.SubjectContains` doesn't work. And I just found it in QQ mail, outlook is ok.
**Platform (please complete the following information):**
 - OS: MACOS
 - .NET Runtime: CoreCLR
 - .NET Framework: .Net Core
 - MailKit Version: 2.9.0

**Comment by BeGemini** [comment]
And I use Imap protocol.

**Comment by jstedfast** [comment]
Unfortunately, if it doesn't work, then it means that it's a bug in the IMAP server's SEARCH implementation.

Outlook does not use IMAP SEARCH queries as far as I'm aware, they do a search through the locally cached data.

I'm not familiar with QQ mail, but my guess is that they do the same.

If you get a [protocol log](https://github.com/jstedfast/MailKit/blob/master/FAQ.md#ProtocolLog), I would be happy to take a look at what is happening just in case there's any hints (like maybe the server is sending a confusing response or something that MailKit could still extract a valid result from), but based on past reports of SEARCH not working, they were always with broken IMAP servers that sent a completely empty response.

**Comment by jstedfast** [comment]
That's returning a list of UIDs correctly. Are you sure the returned list is empty??

**Comment by BeGemini** [comment]
The returned list is not empty. But it's all the mails in the folder `INBOX`. I'm trying to search the mails from  `12306@rails.com.cn`, but the result is not what I expected.

**Comment by jstedfast** [comment]
Your expectations for the search query seem good to me and the SEARCH command sent to the server by MailKit looks correct.

You might need to search manually by doing something like this:

```csharp
var messages = folder.Fetch (0, -1, MessageSummaryItems.Envelope | MessageSUmmaryItems.UniqueId);
var uids = new UniqueIdSet ();
foreach (var message in messages) {
    if (message.Envelope?.From.Mailboxes.Any (x => x.Address.Contains ("12306")))
        uids.Add (message.UniqueId);
}
```

**Comment by BeGemini** [comment]
Thanks a lot! it does work.
