### ISSUE TITLE
Is there support for geolocation of a message through IMessageSummary?

### ISSUE THREAD

**Issue by AdamCharron** [jstedfast/MailKit#1144]
After fetching messages through ImapClient.Fetch(), I want to see if there is any way to see where geographically it came from.

Is there support for this?
Will there be support for this?

My email host is outlook.

**Comment by jstedfast** [comment]
Is this a feature that the outlook.com IMAP server has? I wasn't aware that this data was available.

**Comment by jstedfast** [comment]
FWIW, this is the link I've been using to check for the latest IMAP extensions: https://www.imapwiki.org/Specs

I'm not seeing anything there for geolocation.

If outlook.com has geolocation metadata for messages, it's probably a proprietary extension (which I could possibly still implement, I just need to know more about it).
