### ISSUE TITLE
Can't send email using https://www.googleapis.com/auth/gmail.send

### ISSUE THREAD

**Issue by joao7yt** [jstedfast/MailKit#1147]
See if you can help me.

Using "https://mail.google.com/" it works all fine, but using "https://www.googleapis.com/auth/gmail.send" (because I only need to send emails and it's recommended by google [here](https://developers.google.com/gmail/imap/xoauth2-protocol): "If your app doesn’t require https://mail.google.com/, migrate to the Gmail API and use more granular restricted scopes.") it shows the webpage for authorizing my app and everything... After authorizing it, the .Authenticate() method gives the exception "535: 5.7.8 Username and Password not accepted".

```
using (var clientGoogle = new SmtpClient())
{
    var secrets = new ClientSecrets
    {
        ClientId = clientId,
        ClientSecret = clientSecret
    };

    var credential = GoogleWebAuthorizationBroker.AuthorizeAsync(
        secrets,
        new[] { "https://www.googleapis.com/auth/gmail.send" }, credencial.Email, CancellationToken.None).Result;

    clientGoogle.Connect("smtp.gmail.com", 587, SecureSocketOptions.StartTls);

    var oauth2 = new SaslMechanismOAuth2(senderEmail, credential.Token.AccessToken);
    clientGoogle.Authenticate(oauth2);

    clientGoogle.Send(MimeMessage.CreateFromMailMessage(message));

    clientGoogle.Disconnect(true);
}
```

**Comment by jstedfast** [comment]
"https://www.googleapis.com/auth/gmail.send" is only usable for the Gmail API, not SMTP.

The Gmail API is an HTTP REST API that you can use via the [Google.Apis](https://www.nuget.org/packages/Google.Apis/) nuget
