### ISSUE TITLE
Unexpected token in IMAP response: '['

### ISSUE THREAD

**Issue by marspd** [jstedfast/MailKit#115]
Hi there
I'm using Mailkit (from nuget) with an Office365 account and when I try to use the MoveTo method I get the error above. The mail item does get moved successfully.

I'm getting around this at the moment with the copy/delete option.

Excellent code by the way, saved me a whole heap of bother.  :-)

![capture](https://cloud.githubusercontent.com/assets/7964927/4769577/0bd10aec-5b7c-11e4-98da-7ebd663f09f7.JPG)

**Comment by gluszczek** [comment]
Uexpected COPYUID in IMAP response using folder.MoveTo()

I've also got a similar problem. I'am using MailKit 1.16.0.0.
Trying to move a message from Inbox to another folder with home.pl account.
I've tested with gmail.com account and there is no problem.

In reslut: ImapProtocolException: 'Syntax error in response. Unexpected token: [atom: COPYUID]'.
Here is my code and logs from gmail.com and home.pl:

`IList<IMessageSummary> messages = new List<IMessageSummary>();
      messages = _client.Inbox.Fetch(0, -1, MessageSummaryItems.Full | MessageSummaryItems.UniqueId).ToList();
      var destinationFolder = _client.GetFolder("Processed");
      foreach (var message in messages)
      {
        var uid = message.UniqueId;
        _client.Inbox.MoveTo(uid, destinationFolder);
      }`
![moveerror](https://user-images.githubusercontent.com/18527635/27960324-2fcd66b6-632b-11e7-9497-1e6c87b575fc.png)

**Comment by jstedfast** [comment]
Hi @gluszczek

The problem is that the COPYUID response code needs to appear in the OK response line like it does in gmail. It looks like home.pl has a bug in its implementation.

**Comment by gluszczek** [comment]
Thanks for your reply. Is there any walk around this bug?

**Comment by jstedfast** [comment]
I think the work-around that I just committed should work.

**Comment by gluszczek** [comment]
I just tested it and your commit fixed this issue. Thanks!

**Comment by jstedfast** [comment]
you're welcome!
