### ISSUE TITLE
How to update the subject of a message using IMAP

### ISSUE THREAD

**Issue by abid76** [jstedfast/MailKit#1155]
Hello,

in Outlook it's possible to update the subject of any mail received via IMAP. The message is not only updated locally but also on the mailserver.

I didn't find any method in `IMailFolder` resp. `ImapFolder` which seems to provide the needed functionality.

Is there any way to achieve this using MailKit?

Regards,

Abid

**Comment by jstedfast** [comment]
What you seem to be looking for is the [IMailFolder.Store/Async](http://www.mimekit.net/docs/html/M_MailKit_IMailFolder_StoreAsync.htm) methods and you'll want to use the [AltSubject](http://www.mimekit.net/docs/html/F_MailKit_AnnotationEntry_AltSubject.htm) annotation entry.

Be aware, however, that very few IMAP servers actually support this as it is an experimental feature that is only available if the server advertises that it supports the ANNOTATE-EXPERIMENT-1 extension (which can be checked for using ImapCapabilities.Annotate).

You can read up more about this extension and how it works at https://tools.ietf.org/html/rfc5257

**Comment by abid76** [comment]
👍
