### ISSUE TITLE
How to 'track' many folders?

### ISSUE THREAD

**Issue by DierkDroth** [jstedfast/MailKit#1156]
I wonder what's the best/most efficient way to track changes on *all* folders of an ImapClient/IMAP connection?

The .NoOp logic only would be triggered on a folder which is open. So I had to do this:
- get all folders on startup (including subfolders)
- after every X seconds/minutes: iterate through the list of all folders
-- .Open the folder + subscribe to .CountChanged and .MessageExpunged
-- .NoOp + track incoming events as per above
-- pull the 'right' messages
-- .Close the folder + unsubscribe from .CountChanged and .MessageExpunged

Is this really what I should do for *all* folders? Or is there a more efficient way? I could not find any answer on that "all folders" scenario neither here on GitHub nor on stackoverflow ... hence my inquiry.

Any hint/pointer is appreciated.

**Comment by jstedfast** [comment]
Do you really need to fetch the message summary info when new mail arrives in folders that the user doesn't currently have open?

If all you need are message counts, it would be cheaper for you to use the [Status/Async](http://www.mimekit.net/docs/html/M_MailKit_IMailFolder_StatusAsync.htm) methods.

If your server supports LIST-STATUS, then you could use the [GetSubfolders/Async](http://www.mimekit.net/docs/html/M_MailKit_IMailFolder_GetSubfoldersAsync.htm) methods which will combine the LIST and STATUS commands to speed up the process.

I think ImapFolder.GetSubfolders(StatusItems, bool, CancellationToken) method will actually fall back to issuing a LIST and then STATUS commands if the server doesn't support LIST-STATUS for your convenience.

**Comment by DierkDroth** [comment]
>> Do you really need to fetch the message summary info when new mail arrives in folders that the user doesn't currently have open?

Yes, this is similar to the outlook (Windows) client where I could have (and actually do have) many folders open the same time.

**Comment by jstedfast** [comment]
Do you have a screenshot of what this looks like? I use Outlook and have never seen multiple folders open at one time...

Are you doing "Open in new Window..." ?

My guess would be that if Outlook is using IMAP, then it is probably doing exactly what you are already doing or else they have the equivalent of multiple ImapClient connections open - 1 per folder that is currently open.

**Comment by DierkDroth** [comment]
I mean I have expanded pretty much the whole tree of (sub) folders. Of course in the list UI of outlook there only is displayed the list of mails for the currently selected folder. 

Are you referring to that scenario? Meaning I should open .Open + .FetchAsync + subscribe to events whenever I selected a new folder?

**Comment by jstedfast** [comment]
I mean that, unless the user is actively *looking at* the contents of multiple folders, then it doesn't really make sense to constantly populate your local caches for every folder.

Most clients that I've ever seen the code for have only bothered to update their local caches for the folder that is actively being viewed by the user when new mail arrives (usually using the IDLE command to be notified or NOOP every few minutes if IDLE isn't available). They then use a combination of LIST and STATUS commands to update the folder-list view to embolden (and/or provide unread counts) any other folder(s) that contain unread messages. They don't generally SELECT every folder on the IMAP server and issue FETCH requests. That's just way too expensive and usually a bit of a waste of effort.

Does that make sense?

**Comment by DierkDroth** [comment]
Thanks for clarification. 

I'll work along those lines and will see where it will take me...

**Comment by DierkDroth** [comment]
@jstedfast I'm still struggling...

How would you handle that scenario?
- many clients connect to one server
- the server manages IMAP (and SMTP) access and mirrors the IMAP folder structure
- the IMAP folder structure could be manipulated (concurrently) by unrelated 3rd-party IMAP clients (e.g. outlook)
- hence, the server needed to monitor INBOX as well as any IMAP (sub) folder for changes/updates

The problem here is that having one IMAP connection (at the server) per client easily could run into limitations and there rather needed to be only one IMAP connection - managed by the server - which monitors all (sub) folders for changes/updates.

What am I missing?

**Comment by jstedfast** [comment]
I'm not 100% sure I follow your requirements...

It sounds like you are not implementing a client (e.g. Outlook). You are implementing some sort of middle-man server that mirrors an IMAP server?

Or are you implementing a web-based IMAP client (e.g. [Imp](https://www.horde.org/apps/imp/#:~:text=IMP%20is%20the%20Internet%20Messaging%20Program.%20It%20is,fast%2C%20robust%20connections%20to%20the%20remote%20IMAP%2FPOP3%20server.))?

**Comment by DierkDroth** [comment]
> You are implementing some sort of middle-man server that mirrors an IMAP server?

Yes, it mirrors the IMAP folder structure

**Comment by jstedfast** [comment]
If you have control over which IMAP server(s) you connect to, you could pick IMAP servers that support the NOTIFY extension and configure the client to be notified of new mail arriving in any folder.

Short of that, I guess you'll need to do what you are doing.

**Comment by DierkDroth** [comment]
Thanks for clarification. Unfortunately I don't have any control over the IMAP servers, since those are the domain of the customer(s) and out of our control.
