### ISSUE TITLE
IMailFolder.Search with UIDs range [x:*] keeps retrieving UID x-1

### ISSUE THREAD

**Issue by barbaraacsilva** [jstedfast/MailKit#1158]
Hi,

I'm developing a method where I connect to an IMAP client and search for new messages using the overload for `Search` that accepts an `IList<UniqueId>` parameter; I need to search for messages with UID greater than the last one I read because the method will be executed in a shared mailbox that is already verified by another application, so I can't change any of the messages I find.

When I run the `Search` method looking for messages with UID greater than the last one I read (let's say `x`), the result keeps retrieving the message with UID `x`, and nothing else, falling in an infinite loop.

Here is my code:

```
public async Task ReadMailBox()
{
    using var client = new ImapClient();

    try
    {
        await client.ConnectAsync("outlook.office365.com", 993, true);
        await client.AuthenticateAsync("username", "password");
        
        var inboxFolder = client.GetFolder("Inbox");
        inboxFolder.Open(FolderAccess.ReadOnly);

        var query = SearchQuery.SubjectContains("MyId")
            .And(SearchQuery.Seen);

        uint lastReadId = 0; // will be retrieved from database afterwards

        var listOfMessageId = SearchMailMessages(inboxFolder, lastReadId, query);

        while (listOfMessageId.Any())
        {
            foreach (var messageId in listOfMessageId)
            {
                // some code
            }

            lastReadId = listOfMessageId.Max(x => x.Id);
            // getting 72 here

            listOfMessageId = SearchMailMessages(inboxFolder, lastReadId, query);
            // getting one-item list, with UID 72 again
        }
    }
    catch (Exception)
    {
        // some log here
        throw;
    }
    finally
    {
        if (client.IsConnected)
        {
            await client.DisconnectAsync(true);
        }
    }
}

private IList<UniqueId> SearchMailMessages(IMailFolder mailFolder, uint? lastMessageId = null, SearchQuery query = null)
{
    var rangeStart = lastMessageId.HasValue ? new UniqueId(lastMessageId.Value + 1) : UniqueId.MinValue;
    
    var range = new UniqueIdRange(rangeStart, UniqueId.MaxValue);

    if (query == null)
    {
        query = SearchQuery.All;
    }

    var listOfMessageId = mailFolder.Search(range, query);

    return listOfMessageId;
}
```

For some reason, this seems to happen only when the code is executed and there's no message in the search with UID greater than the last one read.

Thanks in advance!

**Platform:**
 - OS: Windows
 - .NET Framework: .NET 5.0
 - MailKit Version: 2.10.1 (latest as of this post)

**Comment by jstedfast** [comment]
According to the spec:

           Also note that a UID range of 559:* always includes the
           UID of the last message in the mailbox, even if 559 is
           higher than any assigned UID value.  This is because the
           contents of a range are independent of the order of the
           range endpoints.  Thus, any UID range with * as one of
           the endpoints indicates at least one message (the
           message with the highest numbered UID), unless the
           mailbox is empty.

You'll probably just have to check if the first value is the lastMessageId value, and if so, ignore it.
