### ISSUE TITLE
CONDSTORE extension: IMailFolder.ModSeqChanged not fired?!?

### ISSUE THREAD

**Issue by DierkDroth** [jstedfast/MailKit#1162]
I'm working with an IMAP server which has CONDSTORE supported
`client.Capabilities.HasFlag(ImapCapabilities.CondStore) == true`

Here is my code:
Opening the INBOX folder
`await client.Inbox.OpenAsync(FolderAccess.ReadWrite, cts.Token)`

Fetching the initial set of mails
`await client.Inbox.FetchAsync(0, -1, <highestModSeq>, MessageSummaryItems.UniqueId, cts.Token)`

Subscribing to .ModSeqChanged
`client.Inbox.ModSeqChanged += (s, e) => messagesArrived = true;`
However, that handler is not triggered, even as I'm waiting a couple of minutes after a new mail made it to the INBOX

I even tried calling
`await client.NoOpAsync(cts.Token);`
... but that didn't help neither

Any idea what I'm doing wrong?

**Comment by jstedfast** [comment]
I'm not sure if mod-seq changes when new mail arrives, it may only change when the flags of a message are changed.

If you get a protocol log, does the log contain mod-seq changes that MailKit isn't emitting?

**Comment by DierkDroth** [comment]
Ah, I see what you're saying. Let me work on that... thanks

**Comment by DierkDroth** [comment]
OK, I got it working by just using the .CountChanged and .MessageExpunged events.

Basically the CONDSTORE extension then 'only' makes a difference on system restart to avoid pulling mails again which the system already has seen..

Thanks again for your help
