### ISSUE TITLE
Not check email as seen

### ISSUE THREAD

**Issue by ngomezleal** [jstedfast/MailKit#1164]
Hello I hope your very well.

I want that my email check as seen in gmail, but this not working.
This is my code.

```csharp
var uidsDemo = client.Inbox.Search(SearchQuery.GMailRawSearch("Category:Primary").And(SearchQuery.DeliveredAfter(dt).And(SearchQuery.NotSeen)));

foreach (var uid in uidsDemo) 
{
  **client.Inbox.AddFlags((int)uid.Id, MessageFlags.Seen, true);**
  var message = client.Inbox.GetMessage(uid);
}
```

I observe that client.Inbox.id is null always, but I don't know why.
Can they help me please?
Regards.
![Exception](https://user-images.githubusercontent.com/10334284/109813968-01f8f500-7bfc-11eb-8513-0d96f55c89db.png)
![Exception2](https://user-images.githubusercontent.com/10334284/109814247-47b5bd80-7bfc-11eb-8e3b-e3dd430086cb.png)

**Comment by jstedfast** [comment]
The following code is wrong:

```csharp
client.Inbox.AddFlags((int)uid.Id, MessageFlags.Seen, true);
```

You are using the AddFlags() method that takes an *index* and you are giving it the *UID*.

IMAP has 2 ways of referencing messages in a folder:
1. by index
2. by UID

Indexes and UIDs are not interchangeable.

You need to use:

```csharp
client.Inbox.AddFlags(uid, MessageFlags.Seen, true);
```

**Comment by ngomezleal** [comment]
Thanks so much, that was the error.
Now run very good.
