### ISSUE TITLE
MailKit implements the following IETF specifications

### ISSUE THREAD

**Issue by webdev3301** [jstedfast/MailKit#1166]
**Is your feature request related to a problem? Please describe.**
MimeKit has an excellent and usefull history of implemented RFCs related to MIME in a signle markdown file however the same is not true for MailKit. It would be nice to revisit it from time to time to see RFC progression, obsolescence, updates, etc for MailKit as well.

**Describe the solution you'd like**
I've took the time to polish the RFCs MailKit has in the /rfc directory to match the one from MimeKit hosted here MimeKit [RFCs.md](https://github.com/jstedfast/MimeKit/blob/master/RFCs.md)

Below is the Result:

### Specifications

MailKit implements the following IETF specifications:

* [821](https://tools.ietf.org/pdf/rfc821.pdf): SIMPLE MAIL TRANSFER PROTOCOL
* [822](https://tools.ietf.org/pdf/rfc822.pdf): STANDARD FOR THE FORMAT OF ARPA INTERNET TEXT MESSAGES
* [974](https://tools.ietf.org/pdf/rfc974.pdf): MAIL ROUTING AND THE DOMAIN SYSTEM
* [1081](https://tools.ietf.org/pdf/rfc1081.pdf): Post Office Protocol - Version 3
* [1123](https://tools.ietf.org/pdf/rfc1123.pdf): Requirements for Internet Hosts -- Application and Support
* [1225](https://tools.ietf.org/pdf/rfc1225.pdf): Post Office Protocol - Version 3 (Obsoletes rfc1081)
* [1425](https://tools.ietf.org/pdf/rfc1425.pdf): SMTP Service Extensions
* [1426](https://tools.ietf.org/pdf/rfc1426.pdf): SMTP Service Extension for 8bit-MIMEtransport
* [1460](https://tools.ietf.org/pdf/rfc1460.pdf): Post Office Protocol - Version 3 (Obsoletes rfc1225)
* [1651](https://tools.ietf.org/pdf/rfc1651.pdf): SMTP Service Extensions (Obsoletes rfc1425)
* [1652](https://tools.ietf.org/pdf/rfc1652.pdf): SMTP Service Extension for 8bit-MIMEtransport (Obsoletes rfc1426)
* [1653](https://tools.ietf.org/pdf/rfc1653.pdf): SMTP Service Extension for Message Size Declaration
* [1725](https://tools.ietf.org/pdf/rfc1725.pdf): Post Office Protocol - Version 3 (Obsoletes rfc1460)
* [1730](https://tools.ietf.org/pdf/rfc1730.pdf): INTERNET MESSAGE ACCESS PROTOCOL - VERSION 4
* [1731](https://tools.ietf.org/pdf/rfc1731.pdf): IMAP4 Authentication Mechanisms
* [1734](https://tools.ietf.org/pdf/rfc1734.pdf): POP3 AUTHentication command
* [1830](https://tools.ietf.org/pdf/rfc1830.pdf): SMTP Service Extensions for Transmission of Large and Binary MIME Messages
* [1854](https://tools.ietf.org/pdf/rfc1854.pdf): SMTP Service Extension for Command Pipelining
* [1870](https://tools.ietf.org/pdf/rfc1870.pdf): SMTP Service Extension for Message Size Declaration (Obsoletes rfc1653)
* [1869](https://tools.ietf.org/pdf/rfc1869.pdf): SMTP Service Extensions
* [1891](https://tools.ietf.org/pdf/rfc1891.pdf): SMTP Service Extension for Delivery Status Notifications
* [1928](https://tools.ietf.org/pdf/rfc1928.pdf): SOCKS Protocol Version 5
* [1929](https://tools.ietf.org/pdf/rfc1929.pdf): Username/Password Authentication for SOCKS V5
* [1939](https://tools.ietf.org/pdf/rfc1939.pdf): Post Office Protocol - Version 3 (Obsoletes rfc1725)
* [1961](https://tools.ietf.org/pdf/rfc1961.pdf): GSS-API Authentication Method for SOCKS Version 5
* [2034](https://tools.ietf.org/pdf/rfc2034.pdf): SMTP Service Extension for Returning Enhanced Error Codes
* [2060](https://tools.ietf.org/pdf/rfc2060.pdf): INTERNET MESSAGE ACCESS PROTOCOL - VERSION 4rev1 (Obsoletes rfc1730)
* [2086](https://tools.ietf.org/pdf/rfc2086.pdf): IMAP4 ACL extension
* [2087](https://tools.ietf.org/pdf/rfc2087.pdf): IMAP4 QUOTA extension
* [2088](https://tools.ietf.org/pdf/rfc2088.pdf): IMAP4 non-synchronizing literals
* [2095](https://tools.ietf.org/pdf/rfc2095.pdf): IMAP/POP AUTHorize Extension for Simple Challenge/Response
* [2177](https://tools.ietf.org/pdf/rfc2177.pdf): IMAP4 IDLE command
* [2193](https://tools.ietf.org/pdf/rfc2193.pdf): IMAP4 Mailbox Referrals
* [2195](https://tools.ietf.org/pdf/rfc2195.pdf): IMAP/POP AUTHorize Extension for Simple Challenge/Response (Obsoletes rfc2095)
* [2197](https://tools.ietf.org/pdf/rfc2197.pdf): SMTP Service Extension for Command Pipelining (Obsoletes rfc1854)
* [2221](https://tools.ietf.org/pdf/rfc2221.pdf): IMAP4 Login Referrals
* [2222](https://tools.ietf.org/pdf/rfc2222.pdf): Simple Authentication and Security Layer (SASL)
* [2245](https://tools.ietf.org/pdf/rfc2245.pdf): Anonymous SASL Mechanism
* [2342](https://tools.ietf.org/pdf/rfc2342.pdf): IMAP4 Namespace
* [2359](https://tools.ietf.org/pdf/rfc2359.pdf): IMAP4 UIDPLUS extension
* [2449](https://tools.ietf.org/pdf/rfc2449.pdf): POP3 Extension Mechanism (Updates rfc1939)
* [2487](https://tools.ietf.org/pdf/rfc2487.pdf): SMTP Service Extension for Secure SMTP over TLS
* [2554](https://tools.ietf.org/pdf/rfc2554.pdf): SMTP Service Extension for Authentication
* [2595](https://tools.ietf.org/pdf/rfc2595.pdf): Using TLS with IMAP, POP3 and ACAP
* [2683](https://tools.ietf.org/pdf/rfc2683.pdf): IMAP4 Implementation Recommendations
* [2821](https://tools.ietf.org/pdf/rfc2821.pdf): Simple Mail Transfer Protocol (Obsoletes rfc0821, rfc0974, rfc1869) (Updates rfc1123)
* [2822](https://tools.ietf.org/pdf/rfc2822.pdf): Internet Message Format (Obsoletes rfc0822)
* [2831](https://tools.ietf.org/pdf/rfc2831.pdf): Using Digest Authentication as a SASL Mechanism
* [2920](https://tools.ietf.org/pdf/rfc2920.pdf): SMTP Service Extension for Command Pipelining (Obsoletes rfc2197)
* [2971](https://tools.ietf.org/pdf/rfc2971.pdf): IMAP4 ID extension
* [3030](https://tools.ietf.org/pdf/rfc3030.pdf): SMTP Service Extensions for Transmission of Large and Binary MIME Messages (Obsoletes rfc1830)
* [3207](https://tools.ietf.org/pdf/rfc3207.pdf): SMTP Service Extension for Secure SMTP over Transport Layer Security (Obsoletes rfc2487)
* [3348](https://tools.ietf.org/pdf/rfc3348.pdf): The Internet Message Action Protocol (IMAP4) Child Mailbox Extension
* [3461](https://tools.ietf.org/pdf/rfc3461.pdf): Simple Mail Transfer Protocol (SMTP) Service Extension for Delivery Status Notifications (DSNs) (Obsoletes rfc1891)
* [3501](https://tools.ietf.org/pdf/rfc3501.pdf): INTERNET MESSAGE ACCESS PROTOCOL - VERSION 4rev1 (Obsoletes rfc2060)
* [3502](https://tools.ietf.org/pdf/rfc3502.pdf): Internet Message Access Protocol (IMAP) - MULTIAPPEND Extension
* [3516](https://tools.ietf.org/pdf/rfc3516.pdf): IMAP4 Binary Content Extension
* [3691](https://tools.ietf.org/pdf/rfc3691.pdf): Handle System Namespace and Service Definition
* [4013](https://tools.ietf.org/pdf/rfc4013.pdf): SASLprep: Stringprep Profile for User Names and Passwords
* [4314](https://tools.ietf.org/pdf/rfc4314.pdf): IMAP4 Access Control List (ACL) Extension (Obsoletes rfc2086)
* [4315](https://tools.ietf.org/pdf/rfc4315.pdf): Internet Message Access Protocol (IMAP) - UIDPLUS extension (Obsoletes rfc2359)
* [4466](https://tools.ietf.org/pdf/rfc4466.pdf): Collected Extensions to IMAP4 ABNF (Updates rfc2088, rfc2342, rfc3501, rfc3502, rfc3516)
* [4469](https://tools.ietf.org/pdf/rfc4469.pdf): Internet Message Access Protocol (IMAP) CATENATE Extension (Updates rfc3501, rfc3502)
* [4551](https://tools.ietf.org/pdf/rfc4551.pdf): IMAP Extension for Conditional STORE Operation or Quick Flag Changes Resynchronization (Updates rfc3501)
* [4616](https://tools.ietf.org/pdf/rfc4616.pdf): The PLAIN Simple Authentication and Security Layer (SASL) Mechanism (Updates rfc2595)
* [4731](https://tools.ietf.org/pdf/rfc4731.pdf): IMAP4 Extension to SEARCH Command for Controlling What Kind of Information Is Returned
* [4952](https://tools.ietf.org/pdf/rfc4952.pdf): Overview and Framework for Internationalized Email
* [4959](https://tools.ietf.org/pdf/rfc4959.pdf): IMAP Extension for Simple Authentication and Security Layer (SASL) Initial Client Response
* [4978](https://tools.ietf.org/pdf/rfc4978.pdf): The IMAP COMPRESS Extension
* [5032](https://tools.ietf.org/pdf/rfc5032.pdf): WITHIN Search Extension to the IMAP Protocol (Updates rfc3501)
* [5161](https://tools.ietf.org/pdf/rfc5161.pdf): The IMAP ENABLE Extension
* [5162](https://tools.ietf.org/pdf/rfc5162.pdf): IMAP4 Extensions for Quick Mailbox Resynchronization
* [5182](https://tools.ietf.org/pdf/rfc5182.pdf): IMAP Extension for Referencing the Last SEARCH Result (Updates rfc3501)
* [5255](https://tools.ietf.org/pdf/rfc5255.pdf): Internet Message Access Protocol Internationalization
* [5256](https://tools.ietf.org/pdf/rfc5256.pdf): Internet Message Access Protocol - SORT and THREAD Extensions
* [5257](https://tools.ietf.org/pdf/rfc5257.pdf): Internet Message Access Protocol - ANNOTATE Extension
* [5258](https://tools.ietf.org/pdf/rfc5258.pdf): Internet Message Access Protocol version 4 - LIST Command Extensions (Obsoletes rfc3348) (Updates rfc2193)
* [5259](https://tools.ietf.org/pdf/rfc5259.pdf): Internet Message Access Protocol - CONVERT Extension
* [5267](https://tools.ietf.org/pdf/rfc5267.pdf): Contexts for IMAP4
* [5321](https://tools.ietf.org/pdf/rfc5321.pdf): Simple Mail Transfer Protocol (Obsoletes rfc2821) (Updates rfc1123)
* [5336](https://tools.ietf.org/pdf/rfc5336.pdf): SMTP Extension for Internationalized Email Addresses (Updates rfc2821, rfc2822, rfc4952)
* [5464](https://tools.ietf.org/pdf/rfc5464.pdf): The IMAP METADATA Extension
* [5465](https://tools.ietf.org/pdf/rfc5465.pdf): The IMAP NOTIFY Extension (Updates rfc5267)
* [5466](https://tools.ietf.org/pdf/rfc5466.pdf): IMAP4 Extension for Named Searches (Filters)
* [5530](https://tools.ietf.org/pdf/rfc5530.pdf): IMAP Response Codes
* [5721](https://tools.ietf.org/pdf/rfc5721.pdf): POP3 Support for UTF-8
* [5738](https://tools.ietf.org/pdf/rfc5738.pdf): IMAP Support for UTF-8 (Updates rfc3501)
* [5788](https://tools.ietf.org/pdf/rfc5788.pdf): IMAP4 Keyword Registry
* [5801](https://tools.ietf.org/pdf/rfc5801.pdf): Using Generic Security Service Application Program Interface (GSS-API) Mechanisms in Simple Authentication and Security Layer (SASL): The GS2 Mechanism Family
* [5802](https://tools.ietf.org/pdf/rfc5802.pdf): Salted Challenge Response Authentication Mechanism (SCRAM) SASL and GSS-API Mechanisms
* [5819](https://tools.ietf.org/pdf/rfc5819.pdf): IMAP4 Extension for Returning STATUS Information in Extended LIST
* [5957](https://tools.ietf.org/pdf/rfc5957.pdf): Display-Based Address Sorting for the IMAP4 SORT Extension (Updates rfc5256)
* [6154](https://tools.ietf.org/pdf/rfc6154.pdf): IMAP LIST Extension for Special-Use Mailboxes
* [6203](https://tools.ietf.org/pdf/rfc6203.pdf): IMAP4 Extension for Fuzzy Search
* [6237](https://tools.ietf.org/pdf/rfc6237.pdf): IMAP4 Multimailbox SEARCH Extension (Obsoletes rfc4466)
* [6531](https://tools.ietf.org/pdf/rfc6531.pdf): SMTP Extension for Internationalized Email (Obsoletes rfc5336)
* [6851](https://tools.ietf.org/pdf/rfc6851.pdf): Internet Message Access Protocol (IMAP) - MOVE Extension
* [6855](https://tools.ietf.org/pdf/rfc6855.pdf): IMAP Support for UTF-8 (Obsoletes rfc5738)
* [6856](https://tools.ietf.org/pdf/rfc6856.pdf): Post Office Protocol Version 3 (POP3) Support for UTF-8 (Obsoletes rfc5721)
* [7162](https://tools.ietf.org/pdf/rfc7162.pdf): IMAP Extensions: Quick Flag Changes Resynchronization (CONDSTORE) and Quick Mailbox Resynchronization (QRESYNC) (Obsoletes rfc4551, rfc5162) (Updates rfc2683)
* [7377](https://tools.ietf.org/pdf/rfc7377.pdf): IMAP4 Multimailbox SEARCH Extension (Obsoletes rfc6237) (Updates rfc4466)
* [7628](https://tools.ietf.org/pdf/rfc7628.pdf): A Set of Simple Authentication and Security Layer (SASL) Mechanisms for OAuth
* [7677](https://tools.ietf.org/pdf/rfc7677.pdf): SCRAM-SHA-256 and SCRAM-SHA-256-PLUS Simple Authentication and Security Layer (SASL) Mechanisms (Updates rfc5802)
* [7888](https://tools.ietf.org/pdf/rfc7888.pdf): IMAP4 Non-synchronizing Literals (Obsoletes rfc2088)
* [7889](https://tools.ietf.org/pdf/rfc7889.pdf): The IMAP APPENDLIMIT Extension
* [8437](https://tools.ietf.org/pdf/rfc8437.pdf): IMAP UNAUTHENTICATE Extension for Connection Reuse (Updates rfc3501)
* [8438](https://tools.ietf.org/pdf/rfc8438.pdf): IMAP Extension for STATUS=SIZE
* [8440](https://tools.ietf.org/pdf/rfc8440.pdf): IMAP4 Extension for Returning MYRIGHTS Information in Extended LIST
* [8457](https://tools.ietf.org/pdf/rfc8457.pdf): IMAP "$Important" Keyword and "\Important" Special-Use Attribute
* [8474](https://tools.ietf.org/pdf/rfc8474.pdf): IMAP Extension for Object Identifiers
* [8508](https://tools.ietf.org/pdf/rfc8508.pdf): IMAP REPLACE Extension (Updates rfc3501)
* [8514](https://tools.ietf.org/pdf/rfc8514.pdf): Internet Message Access Protocol (IMAP) - SAVEDATE Extension
* [8689](https://tools.ietf.org/pdf/rfc8689.pdf): SMTP Require TLS Option

**Comment by jstedfast** [comment]
Thanks!

**Comment by webdev3301** [comment]
Thank you! I've learned so much from the MimeKit RFC.md one you've created I just had to give something back.

If anyone on stackoverflow who asks a question about mime/email even knew the ocean of RFC docs you have to navigate to really have a grasp on it... Ha.
