### ISSUE TITLE
connect to IMAP using proxy

### ISSUE THREAD

**Issue by hossein0939** [jstedfast/MailKit#1168]
Hello,

I want to connect to IMAP using proxy but it's not work!
code I'm using:

`using (var client = new ImapClient())
                {
                        client.ProxyClient = new HttpProxyClient(proxyAd, proxyPort);
                        client.Connect(hostName, port , true);
                        client.Authenticate(login, pass);
                      }
                        `
                        
Help me please

**Comment by webdev3301** [comment]
If this was stackoverflow, I would feel inclined to ask that you **post your error console logs**.

**Comment by jstedfast** [comment]
@hossein0939 I need more information.

For example: what, exactly, is the error you are getting?
