### ISSUE TITLE
IMAP: custom folder not showing

### ISSUE THREAD

**Issue by DierkDroth** [jstedfast/MailKit#1172]
Hi,

Here is how I create a custom folder:
`archiveFolder = await client.Inbox.GetSubfolderAsync("Archive", cts.Token);`
`if (archiveFolder == null)`
`    archiveFolder = await client.GetFolder(client.PersonalNamespaces[0]).CreateAsync("Archive", true, cts.Token);`
`await archiveFolder.SubscribeAsync(cts.Token);`

Creation appears to be successful since "Archive" is reported by `client.GetFolders`.

However, it does not show e.g. in my Outlook client which is connected to the IMAP account. Restarting Outlook makes no difference.

Any idea what I'm doing wrong?

**Comment by jstedfast** [comment]
I was going to recommend subscribing to the Archive folder, but then I noticed you were already doing that...

I'm not sure :-\

**Comment by jstedfast** [comment]
You are doing everything correctly. The problem is with Outlook.
