### ISSUE TITLE
SMTP: Get UniqueID on sent mail?

### ISSUE THREAD

**Issue by DierkDroth** [jstedfast/MailKit#1173]
What's the correct way to get the UniqueID of an email which I just have sent?

When sending a mail it would make it to the SENT folder. Hence, I assume it would have a UniqueID?!?

**Comment by jstedfast** [comment]
SmtpClient doesn't append it to the Sent folder (it's completely separate and independent from IMAP: and knows nothing about folders).

What you need to do is to use the ImapClient to append the message to the Sent folder. The `IMailFolder.Append (...)` methods will return a UID (if the server supports it).

**Comment by DierkDroth** [comment]
Thanks @jstedfast. That helps
