### ISSUE TITLE
Mute logging of credentials

### ISSUE THREAD

**Issue by AdamCharron** [jstedfast/MailKit#1174]
Hi,

I was wondering if there was any plan to create functionality for muting the ProtocolLogger's logging of credentials during authentication.
If PLAIN or LOGIN are used, the protocol logger logs the base64 credentials directly to the protocol log. 
There currently is no functionality in place for omitting this information, which is not ideal for any potential collaborative efforts where debugging of ProtocolLogs is needed, but you don't want to share your login information with those debugging it. 

I know ProtocolLog can be extended and fed into IMAP or SMTP clients as parameters, but handling this information from the logger can be tricky. Namely in ImapClient, where there are multiple client-server interactions in Authenticate() after the authentication mechanism that shouldn't be muted (Capabilities, Namespace, Special Folders, etc).

Would it be possible to implement something like:
- Add a public flag to IProtocolLogger, something like AuthenticationInProgress
- This flag is enabled in Imap/SmtpClient.AuthenticateAsync before the authentication happens, and disabled once it completes.
- Anyone creating their own implementation of Protocol logger could have access to this parameter and simply skip any LogClient operations they so chose while this was in progress.

i.e. In ImapClient.AuthenticateAsync, lines ~954-970

```
ProtocolLogger.AuthenticationInProgress = true;
try {
    ic = engine.QueueCommand (cancellationToken, null, command);
    ic.ContinuationHandler = async (imap, cmd, text, xdoAsync) => {
        var challenge = sasl.Challenge (text);
        var buf = Encoding.ASCII.GetBytes (challenge + "\r\n");

        if (xdoAsync) {
            await imap.Stream.WriteAsync (buf, 0, buf.Length, cmd.CancellationToken).ConfigureAwait (false);
	    await imap.Stream.FlushAsync (cmd.CancellationToken).ConfigureAwait (false);
        } else {
            imap.Stream.Write (buf, 0, buf.Length, cmd.CancellationToken);
    	    imap.Stream.Flush (cmd.CancellationToken);
        }
    };

    await engine.RunAsync (ic, doAsync).ConfigureAwait (false);

    ProtocolLogger.AuthenticationInProgress = false;
}
catch {
    ProtocolLogger.AuthenticationInProgress = false;
    throw;
}
```

**Comment by jstedfast** [comment]
I'll think about it.

**Comment by jstedfast** [comment]
I've considered adding this feature for quite a few years at this point. The problem is that I haven't found a clean way of doing it that only hides the secret strings (e.g. the user name and the password).

In my opinion, what is needed is the following:

1. The IProtocolLogger should be modified to have a LogClientSecret() method or else LogClient() should take additional arguments that specify a "secret range" (or, actually, it would probably need to be a list of secret ranges).
2. Not all SaslMechanisms should log their base64 challenges as "secrets". Only PLAIN and LOGIN likely need this (in addition to the POP3 USER/PASS commands and IMAP's LOGIN command).

I don't like the AuthenticationInProgress idea because it's not very clean and it still means each logger implementation would have to be able to parse SMTP, POP3 or IMAP commands in order to hide secrets properly. Otherwise it would just blot out the entire command which sucks.

**Comment by AdamCharron** [comment]
Yeah this above case isn't a great solution, it was just a top-of-mind idea to get my point across.
As for your second point, the reason I asked instead of just doing it in my own code (add a simple string replace to an extended protocol logger's LogClient method) is that even though other mechanisms don't store the password in plaintext, some such as NTML or DIGEST-MD5 store them using a broken hash like MD4/5. This is probably nitpicky, and it all depends where you're comfortable drawing the line, but for those more paranoid/security-sensitive users (hello!) it is still less than ideal and a possible point of compromise if those protocol logs ever get shared.

**Comment by jstedfast** [comment]
I have an idea for how this could work fairly cleanly... stay tuned.

**Comment by jstedfast** [comment]
Not 100% convinced the AuthSecret struct name is the best choice or the name of the interface, but the API seems decent otherwise.

Comments welcome.

**Comment by jstedfast** [comment]
At this point I have unit test coverage for all of the authentication secret detection backends (SMTP, POP3 and IMAP) and test coverage for SmtpClient and Pop3Client but not ImapClient (yet). I'll try to get ImapClient unit tests written tonight if I have free time.

Feeling pretty confident that it works well now after some fixes I added last night.

Try giving it a whirl and let me know if it'll work for you.
