### ISSUE TITLE
TLS success not checked for

### ISSUE THREAD

**Issue by AdamCharron** [jstedfast/MailKit#1175]
In Imap/SmtpClient.Connect, when creating an SSL/TLS wrapped stream, the handshake is performed using the AuthenticateAsClient method. Success seems to be defined by this method not having thrown an exception. 

According to Microsoft docs for this method (https://docs.microsoft.com/en-us/dotnet/api/system.net.security.sslstream.authenticateasclient?view=netframework-4.8), Microsoft says:
`When authentication succeeds, you must check the IsEncrypted and IsSigned properties to determine what security services are used by the SslStream`

Documentation for SslStream (https://docs.microsoft.com/en-us/dotnet/api/system.net.security.sslstream?view=netframework-4.8) suggests the same, as well as a suggestion to check the protocols, algorithms, and strength. This is partially done by allowing the user to specify the TLS protocol, but not the algorithms within it or their strength.

The STARTTLS standard also makes mention of this (section 7 of https://tools.ietf.org/html/rfc2487):
`Both the STMP client and server must check the result of the TLS negotiation to see whether acceptable authentication or privacy was achieved. Ignoring this step completely invalidates using TLS for security. `

For these two things:
- sslStream.IsEncrypted and sslStream.IsSigned
- algorithms and strength

Is there any plan of adding any functionality to either automatically check these, or to expose them to the user and allow them to check it themselves?

**Comment by jstedfast** [comment]
I've already added support for specifying algorithms via a new SslCipherSuitesPolicy property (only supported in .NET 5.0).

**Comment by AdamCharron** [comment]
Thanks for the commit!

**Comment by AdamCharron** [comment]
For those who aren't on .Net 5.0 yet, would it be possible to expose the SSL/TLS protocol used, ie
CipherAlgorithm, CipherStrength, KeyExchangeAlgorithm, KeyExchangeStrength,, HashAlgorithm, HashStrength ?

It would be helpful to get confirmation of exactly what was agreed upon in the TLS handshake.

**Comment by jstedfast** [comment]
Other than for diagnostic purposes, what do you plan to do with that info? It seems like a lot of property accessors to add that < 0.00001% of users would actually use.

TBH, I'm not even sure it was valuable to add the SslCipherSuitesPolicy property in .NET 5.0 to allow selection of algorithms, etc.

Adding 6 more properties for various SSL statistical info seems minimally useful and would pollute the API.

Even the IsEncrypted/IsSIgned properties are not things the average user is going to care about (you've probably noticed that none of the commonly used mail clients out there show any of this info).

**Comment by AdamCharron** [comment]
If I'm sending any sensitive info, I'd like to know that the algorithms being used are secure. 
From my understanding (and please correct me if I'm wrong), there is flexibility as to what TLS suite the client sends, and that the server accepts. If they agree on a suite that contains weak algorithms that could jeopardize my data, I'd like to know and reject connection. Right now there is little insight as to what is going on in the handshake (IsEncrypted and IsSigned are a nice step though, thanks!).

I know this probably applies to very few users, but for those who do have a higher interest in the security side of things, it's a welcome addition.

**Comment by jstedfast** [comment]
My understanding is that the way that SSL cipher negotiation works, the stronger ciphers (AES, etc) take priority over the weaker ciphers (e.g. 3DES) which means that if the client & server settle on 3DES, it means that they have no stronger ciphers in common.

Starting with TLS v1.2, 3DES isn't even supported anymore, leaving the weakest ciphers being built on AES128 afaik.

It also means that if you abort the connection, you can't read your mail and you aren't likely to be able to read your mail with any other client, either (.NET's SSL stream implements all of the ciphers). You can find the list supported by .NET's TLS implementation here: https://docs.microsoft.com/en-us/dotnet/api/system.net.security.tlsciphersuite?view=net-5.0

FYI: A big warning that the docs have for specifying TLS cipher suites reads:

https://docs.microsoft.com/en-us/dotnet/api/system.net.security.ciphersuitespolicy.allowedciphersuites?view=net-5.0#System_Net_Security_CipherSuitesPolicy_AllowedCipherSuites
> Defining a cipher suite policy on SslStream authentication will prevent the OS from deciding which are the best cipher suites to negotiate with and requires that you manually check and update this code. We strongly recommend that you avoid using this feature and rely on your constantly updated OS policy.

**Comment by jstedfast** [comment]
Decided to add them after all.
