### ISSUE TITLE
SMTP: Random failure using Microsoft 365

### ISSUE THREAD

**Issue by DierkDroth** [jstedfast/MailKit#1176]
Hi,

I'm trying to send an email to Microsoft/Office 365 using [SMTP Auth](https://docs.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/authenticated-client-smtp-submission) (legacy authentication, *not* OAuth2). This may not work (see exception below) but as I tried a few seconds later it does work no problem.

Any idea why those random exceptions occur?

MailKit.Net.Smtp.SmtpCommandException
  HResult=0x80131500
  Message=5.2.0 STOREDRV.Submission.Exception:SendAsDeniedException.MapiExceptionSendAsDenied; Failed to process message due to a permanent exception with message Cannot submit message. 0.35250:D8360000, 1.36674:0A000000, 1.61250:00000000, 1.45378:02000000, 1.44866:441B0000, 1.36674:0E000000, 1.61250:00000000, 1.45378:491B0000, 1.44866:2C010000, 16.55847:950D0000, 17.43559:0000000024020000000000000000000000000000, 20.52176:140F738F0B00F01F00000000, 20.50032:140F738F7B17F01F00000000, 0.35180:140F738F, 255.23226:F6360000, 255.27962:0A000000, 255.27962:0E000000, 255.31418:FB360000, 0.35250:0A000E32, 1.36674:0A000000, 1.61250:00000000, 1.45378:02000000, 1.44866:18000000, 1.36674:32000000, 1.61250:00000000, 1.45378:1D000000, 1.44866:01000000, 16.55847:84000000, 17.43559:0000000078030000000000000000000000000000, 20.52176:140F738F0B0010104D000000, 20.50032:140F738F7B1700002F0A0000, 0.35180:52000000, 255.23226:4800D13D, 255.27962:0A000000, 255.27962:32000000, 255.17082:DC040000, 0.27745:4B0A0000, 4.21921:DC040000, 255.27962:FA000000, 255.1494:500A0000, 0.38698:00000000, 0.37692:01000000, 0.37948:00000000, 5.33852:00000000534D545000000000, 7.36354:01000000000001090B000000, 4.56248:DC040000, 7.40748:010000000000010B00000000, 7.57132:000000000000000000000000, 1.63016:32000000, 4.39640:DC040000, 8.45434:2D76BE8F20BC32468E937736B8BEB8B208000000, 1.46798:04000000, 5.10786:0000000031352E32302E333935352E3031313A465232503238314D42303034313A63626134316238372D313261622D346463302D393939652D3533386365653034393433343A323938303400, 7.51330:A4993BD37AE5D80800000000, 0.39570:00000000, 1.55954:0A000000, 0.49266:A4000000, 1.33010:0A000000, 2.54258:00000000, 0.40002:18000000, 1.56562:00000000, 1.64146:32000000, 1.33010:32000000, 2.54258:DC040000, 255.1750:0A005D36, 255.31418:A2080000, 0.22753:AE000000, 255.21817:DC040000, 0.64418:A7080000, 4.39842:DC040000, 0.41586:0A005636, 4.60547:DC040000, 0.21966:B8000000, 4.30158:DC040000 [Hostname=FR2P281MB0041.DEUP281.PROD.OUTLOOK.COM]
  Source=MailKit
  StackTrace:
   at MailKit.Net.Smtp.SmtpClient.<DataAsync>d__107.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MailKit.Net.Smtp.SmtpClient.<SendAsync>d__113.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at MailKit.Net.Smtp.SmtpClient.<SendAsync>d__113.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MailKit.Net.Smtp.SmtpClient.Send(FormatOptions options, MimeMessage message, CancellationToken cancellationToken, ITransferProgress progress)
   at Unusual.Mail.MailClient.<SendMailAsync>d__31.MoveNext() in C:\Users\ddroth\Documents\Unusual.CRM\Unusual.Common\Mail\MailClient.cs:line 685

  This exception was originally thrown at this call stack:
    [External Code]
    Unusual.Mail.MailClient.SendMailAsync(Unusual.Model.IMailAccount, MimeKit.MimeMessage) in MailClient.cs

**Comment by jstedfast** [comment]
Since they are occurring in the Send method (as opposed to Authenticate) and because of the string "MapiExceptionSendAsDenied", it's probably related to the address in the From header not matching the address used for authenticating.

In other words, if you authenticate using "bob@example.com" and the From header contains "alice@example.com", it is rejecting the message because you are not alice.

**Comment by DierkDroth** [comment]
Excellent! Thanks again for your help @jstedfast
