### ISSUE TITLE
how to add inline image to  ReplyVisitor

### ISSUE THREAD

**Issue by billpeace** [jstedfast/MailKit#1182]
Use the ReplyVisitor below

the inlined image will missing，how to solve？

thanks

===============================================

https://github.com/jstedfast/MailKit/blob/984a55b773a3b9db2a1a6a8e41037a8800f6fc80/FAQ.md

The first thing we'd need to do is implement our own MimeVisitor to handle this:

public static MimeMessage Reply (MimeMessage message, MailboxAddress from, bool replyToAll)
{
    var visitor = new ReplyVisitor (from, replyToAll);

    visitor.Visit (message);

    return visitor.Reply;
}

**Comment by jstedfast** [comment]
I've updated the FAQ.

**Comment by billpeace** [comment]
Thanks very much
