### ISSUE TITLE
how to add attachment to ReplyVisitor #1182

### ISSUE THREAD

**Issue by billpeace** [jstedfast/MailKit#1185]
Use the ReplyVisitor below

I want to add  attachment ，how to solve？

Can you give me a better code， reply message， no attachment  or  with all attachment  

thanks jstedfast 

============================================

The following code
     The attachment is vnd.ms-tnef part， use  tnefPart.ExtractAttachments()， get sublist
     when sublist have vnd.ms-tnef part， The attachment will untitled attachment.dat

foreach (var attachment in message.Attachments)
            {
                //builder.Attachments.Add(attachment);
                if (attachment.GetType() == typeof(MimeKit.Tnef.TnefPart))
                {
                    var tnefPart = attachment as TnefPart;
                    var lists = tnefPart.ExtractAttachments();
                    foreach (var item in lists)
                    {
                        if (item.IsAttachment)
                        {
                            if (item.GetType() == typeof(MimeKit.Tnef.TnefPart))
                            {
                                builder.Attachments.Add(item);   // 
                            }
                            else
                            {
                                  builder.Attachments.Add(item);
                            }
                        }
                    }
                }
                else
                {
                    builder.Attachments.Add(attachment);
                }
            }

===============================================

https://github.com/jstedfast/MailKit/blob/984a55b773a3b9db2a1a6a8e41037a8800f6fc80/FAQ.md

The first thing we'd need to do is implement our own MimeVisitor to handle this:

**Comment by jstedfast** [comment]
I'm confused by what you are asking.

If you want to attach all of the original message's attachments, just modify the ReplyVisitor.VisitMimePart method to attach everything rather than just inline attachments.
