### ISSUE TITLE
Unable to authenticate with XOAUTH2 for GMail and Office365 IMAP servers on .NET framework 4.7.2

### ISSUE THREAD

**Issue by pete-lewis** [jstedfast/MailKit#1190]
**Describe the bug**
Apologies if I am doing something wrong (I'm new to the IMAP protocol and MailKit), but it appears that GMail and Office365 IMAP servers support various authentication mechanisms, but MailKit appears to be trying to use LOGIN by default, which causes authentication failure.  

**Platform (please complete the following information):**
 - OS: Windows 10
 - .NET Framework: 4.7.2
 - MailKit Version:  2.11.0.0

**Exception**
```
MailKit.Security.AuthenticationException: Authentication failed.
   at MailKit.Net.Imap.ImapClient.<AuthenticateAsync>d__85.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MailKit.Net.Imap.ImapClient.Authenticate(SaslMechanism mechanism, CancellationToken cancellationToken)
```

**To Reproduce**
1. Create Google/Office365 test app, with the appropriate scopes for reading mail
2. Obtain OAuth2 authorization code & token
3. Attempt to authenticate with MailKit using an instance of SaslMechanismLogin

Example code:
```
Dim logger As New ProtocolLogger("C:\temp\imap.log", True)
Dim client As New ImapClient(logger)

client.Connect("imap.gmail.com", 993, True)

Dim mechanism As New SaslMechanismLogin("example@gmail.com", "accessToken")
client.Authenticate(mechanism)

```

**Expected behavior**
Use the XOAUTH2 authentication mechanism.  Even if I clear the IMAP client AuthenticationMechanisms HashSet, and manually re-add only XOAUTH2, it seems to continue to try LOGIN.

**Protocol Logs**
```
Connected to imaps://imap.gmail.com:993/
S: * OK Gimap ready for requests from XXX.XXX.XXX.XXX 
C: A00000000 CAPABILITY
S: * CAPABILITY IMAP4rev1 UNSELECT IDLE NAMESPACE QUOTA ID XLIST CHILDREN X-GM-EXT-1 XYZZY SASL-IR AUTH=XOAUTH2 AUTH=PLAIN AUTH=PLAIN-CLIENTTOKEN AUTH=OAUTHBEARER AUTH=XOAUTH
S: A00000000 OK Thats all she wrote! 
C: A00000001 AUTHENTICATE LOGIN
S: A00000001 NO Unsupported AUTHENTICATE mechanism. 


Connected to imaps://outlook.office365.com:993/
S: * OK The Microsoft Exchange IMAP4 service is ready. 
C: A00000000 CAPABILITY
S: * CAPABILITY IMAP4 IMAP4rev1 AUTH=PLAIN AUTH=XOAUTH2 SASL-IR UIDPLUS MOVE ID UNSELECT CHILDREN IDLE NAMESPACE LITERAL+
S: A00000000 OK CAPABILITY completed.
C: A00000001 AUTHENTICATE LOGIN
S: A00000001 NO AUTHENTICATE failed. Provided authentication mechanism is not supported.
```

**Additional context**
I'm certain I have the correct scopes configured for my applications.  Am I missing something?  All example code I can find online appears to do little differently than mine.

**Comment by jstedfast** [comment]
The problem is that you are using `SaslMechanismLogin` which is the `LOGIN` SASL mechanism, but you want OAuth2 which is `SaslMechanismOAuth2` or `SaslMechanismOAuthBearer` (Gmail works with both, but Exchange (aka Office365) only works with `SaslMechanismOAuth2`).

The [GMailOAuth2.md](https://github.com/jstedfast/MailKit/blob/master/GMailOAuth2.md) docs and the [ExchangeOAuth2.md](https://github.com/jstedfast/MailKit/blob/master/ExchangeOAuth2.md) docs show how to authenticate via OAuth2 with those services (Office365 is Exchange).

**Comment by pete-lewis** [comment]
Oh what a horrible goof.  Thank you.
