### ISSUE TITLE
Will Maintain email conversation on email server as well as local Is it possible? 

### ISSUE THREAD

**Issue by ysunil702** [jstedfast/MailKit#1192]
(1)I want it to be updated in the sent folder of the mail server while  i reply to someone or created new email.

(2)How do I know if I have spammed an email on email server and want it from the imap in local?

**Comment by jstedfast** [comment]
I don't understand what you are asking in either question.

1) What do you want updated on the mail server? I don't understand. Do you want the reply message to be appended to the Sent folder when you send the reply? If so, you need to send the message via SmtpCLient and then append the message to the sent folder using an ImapClient (see the ImapFolder.Append method).

2) What...??? Are you asking how to tell if you've received a message marked as spam? Or are you asking if it's possible to tell if a message you've sent got marked as spam in the recipient's mailbox?

**Comment by ysunil702** [comment]
Thank you for prompt reply @jstedfast . You understand the first question right. and my second question is 
When I retrieved  the email from server using IMAP, how will I know if there is a mail with spam?

**Comment by jstedfast** [comment]
The same way you'd determine if the message was seen/deleted/etc. except that you'd use the IMessageSummary.Keywords property instead of IMessageSummary.Flags and you'd check for a keyword like `"$Junk"`.

```csharp
if (summary.Keywords.Contains ("$Junk")) {
    // the message is marked as spam
}
```

**Comment by ysunil702** [comment]
Thank you very much @jstedfast
