### ISSUE TITLE
How does google and outlook append mail in SENT automatically?

### ISSUE THREAD

**Issue by ysunil702** [jstedfast/MailKit#1193]
When I send mail using smtp of Gmail or Outlook, it becomes an append automatically in the Sent folder on the server.
but If other smtp server like justhost ,then justhost does not append email in the sent folder.
What is the reason behind this? Would they use imap internally?

**Comment by jstedfast** [comment]
You have to append the message yourself because the SMTP protocol does not support doing that for you.

This doesn't really have anything to do with MailKit.

**Comment by ysunil702** [comment]
Thank you very much @jstedfast
