### ISSUE TITLE
Question about forwarded messages and use of visitor pattern

### ISSUE THREAD

**Issue by szmalec** [jstedfast/MailKit#1194]
[On the FAQ page](https://github.com/jstedfast/MailKit/blob/2.11.1/FAQ.md#Reply) we can find information, that in the case of HTML formatting, the `ReplyVisitor` class should be used to generate the `MimeMessage` object (thanks to which the original text or HTML body of the message will be quoted and `"Re:"` prefix is added).

Shouldn't we do the same in the case of generating a `MimeMessage` for **forwarded message** - at least in the case of inlining the original message's content?

The [FAQ shows](https://github.com/jstedfast/MailKit/blob/2.11.1/FAQ.md#q-how-can-i-forward-a-message) an example of a simple code that only supports text body (and NOT HTML body)...
Shouldn't the FAQ include another example of e.g. `ForwardVisitor` class in which the case with inlining **text body** and the case with inlining **HTML body** will be handled?

Maybe `ForwardVisitor` could also process attachments from the original message (which I don't see in these two simple existing FAQ examples)?

Does the lack of such comprehensive example is due to the lack of maintainers' time to prepare the proper code or is it not appropriate to use the visitor pattern for the messages being forwarded?

**Comment by jstedfast** [comment]
> Shouldn't we do the same in the case of generating a MimeMessage for forwarded message - at least in the case of inlining the original message's content?

You could.

There's no definitive rules for this stuff, so you can do whatever you want.

> Shouldn't the FAQ include another example of e.g. ForwardVisitor class in which the case with inlining text body and the case with inlining HTML body will be handled?

It's just an example.

> Does the lack of such comprehensive example is due to the lack of maintainers' time to prepare the proper code or is it not appropriate to use the visitor pattern for the messages being forwarded?

Mostly because writing a simple example that deals with text only makes the code a lot simpler to read and understand.

You can 100% use the visitor pattern for generating forwarded messages as well.
