### ISSUE TITLE
How to get mail with utf-8 format

### ISSUE THREAD

**Issue by burakergun394** [jstedfast/MailKit#1200]
How can I receive emails with utf-8 support. I am using the Turkish alphabet. There are characters that support utf-8 in the incoming mails and I cannot view them. How can I do that ?

`
I will share the my code on the below.
           
                  var client = new ImapClient()
                   client.ServerCertificateValidationCallback = (s, c, h, e) => true;
                   client.Connect(hostName, 993, ssl);
                   client.Authenticate(userName, password);
                   // The Inbox folder is always available on all IMAP servers...
                   var inbox = client.Inbox;
                   inbox.Open(FolderAccess.ReadOnly);
  
                   Console.WriteLine("Total messages: {0}", inbox.Count);
                   Console.WriteLine("Recent messages: {0}", inbox.Recent);
  
                   for (int i = 0; i < 2; i++)
                   {
                       
                       var message = inbox.GetMessage(i);
                       Console.WriteLine("Subject: {0}", message.Subject);
                       Console.WriteLine("Body: {0}", message.TextBody);
                       
                   }
  
                  client.Disconnect(true);
     
`

**Comment by jstedfast** [comment]
Did you still need help with this question or did you manage to figure it out?

**Comment by burakergun394** [comment]
If I receive mail via Gmail, it comes with utf-8 support, but if I send it with an e-mail belonging to my private domain via the outlook application, then it comes without utf-8 support. The reason for this is that the e-mails I sent through the outlook application were sent in Turkish format instead of the utf-8 format. By changing this to the utf-8 format the problem was solved.

**Comment by burakergun394** [comment]
Assuming I got an error, what solution would you recommend for this?

**Comment by jstedfast** [comment]
I would have to see a sample message so that I could take a look at it and figure out how MimeKit might be mishandling it (if it is).

Sometimes, some clients will send raw 8bit bytes instead of properly declaring the content to be using iso-8859-5 (for example) and so MimeKit might have (wrongly) assumed that the bytes were in UTF-8 format.

If this is the case, it's *possible* to use a custom `ParserOptions` where the `UserCharset` is set to `Encoding.GetEncoding ("iso-8859-5")`.

**Comment by burakergun394** [comment]
I send the output result as a screenshot on the below

![resim_2021-05-19_214403](https://user-images.githubusercontent.com/47159921/118867046-53f01380-b8eb-11eb-94ae-84d9abe737d0.png)

**Comment by jstedfast** [comment]
I need to see the raw message content (aka MimeMessage.WriteTo(stream))

**Comment by burakergun394** [comment]
I can't take characters like "ı,ğ,ş". That characters has in turkish alphabet. I write the response on the txt file and take the screenshot. You can find the on the below 

![image](https://user-images.githubusercontent.com/47159921/118881671-0039f600-b8fc-11eb-8e9c-f82aa5cb3ba9.png)

[test.txt](https://github.com/jstedfast/MailKit/files/6511430/test.txt)

**Comment by jstedfast** [comment]
This is what I get:

```
Pijamalı hasta yağız şoföre çabucak güvendi.
```

What version of MimeKit are you using?

**Comment by burakergun394** [comment]
I am using version 2.12.0 of MailKit and Mimekit. I can't get the result like you got

**Comment by burakergun394** [comment]
In the below. I am giving you my outlook mail settings. (Encoding for outgoing messages -> turkish ISO)

![Screenshot_1](https://user-images.githubusercontent.com/47159921/118928114-6e59d980-b94b-11eb-99d1-635e66b51527.png)

**Comment by burakergun394** [comment]
How can I convert unknow charset to utf8 charset.

**Comment by jstedfast** [comment]
Try downloading the test.txt file you attached above and then doing the following:

```csharp
var message = MimeMessage.Load (@"c:\Users\<username>\Downloads\test.txt");
Console.WriteLine (message.TextBody);
```

Does that show the characters correctly?

That's how I tested your sample message. Maybe when you attached the message, something got modified making it work for me?

**Comment by burakergun394** [comment]
I can't take the characters right. Did you change anything other than the codes you shared. Whenever you're available, can you meet up on discord and help me?

**Comment by jstedfast** [comment]
The only thing I can think of at this point is that maybe your system doesn't have the "windows-1254" text encoding?

What happens if you do:

```csharp
var encoding = Encoding.GetEncoding ("windows-1254");
var text = encoding.GetString (new byte[] { 80, 105, 106, 97, 109, 97, 108, 196, 177, 32, 104, 97, 115, 116, 97, 32, 121, 97, 196, 159, 196, 177, 122, 32, 197, 159, 111, 102, 195, 182, 114, 101, 32, 195, 167, 97, 98, 117, 99, 97, 107, 32, 103, 195, 188, 118, 101, 110, 100, 105, 46, 13, 10, 13, 10 });
Console.WriteLine (text);
```

**Comment by burakergun394** [comment]
That's true. My system doesn't have "windows-1254"
