### ISSUE TITLE
Mime header showing internal IP address

### ISSUE THREAD

**Issue by dazinator** [jstedfast/MailKit#1201]
**Is your feature request related to a problem? Please describe.**
We had a penetration test conducted recently and one of the "low" risk items was that a pen tester was able to glean knowledge of an internal IP address, by looking at the headers on an email that was sent by our application using this library.

The mime header on the email that was sent looks a bit like this:

```
Received: from [10.0.2.4] (XX.XXX.XX.XX) by // etc
```

The value in square brackets is the internal IP address of the machine hosting the application that is using this library to send the email via smtp. The value in parenthesis is the public IP address of the same server - it's a web server.

Is this something that we can control in application code when formulating the mail message? We would rather not reveal the internal IP address if possible.

**Describe the solution you'd like**
If this is controllable on the Mailkit side, we'd like not to reveal the internal IP address.

**Describe alternatives you've considered**
Currently looking at what we can do on office 365 to potentially remove these headers.. haven't ironed that out yet!

**Additional context**

**Comment by dazinator** [comment]
Closing - [i think this](https://github.com/jstedfast/MailKit/issues/885) is what I need, will give it a go

**Comment by jstedfast** [comment]
I suspect you are on the right track with the SmtpClient.LocalEndPoint and/or LocalDomain properties.

As you have probably already figured out, MimeKit/MailKit do not set the Received header directly, but it's possible that either of those values *could* potentially be used by the SMTP server to construct that Received header.

Hope you find a solution!

**Comment by dazinator** [comment]
Yep `SmtpClient.LocalEndPoint` solved the problem. We just set that to "localhost" now. It doesn't appear that this needs to be an actual valid ip address or host name. Thank you!
