### ISSUE TITLE
Gmail - An error occurred while attempting to establish an SSL or TLS connection

### ISSUE THREAD

**Issue by kaddrison** [jstedfast/MailKit#1203]
Has anything changed on gmail - reopened an old program that was all working and getting this error on a .Connect( smtp.gmail.com,587)

Have check that less secure is still on on gmail

Any ideas before I start looking at it

**Comment by jstedfast** [comment]
Depending on how old your program was, it might be because GMail changed their SSL certificates.

They changed them, I think, in January or February this year.
