### ISSUE TITLE
POP3/IMAP client connection get stuck at Socket.Receive()

### ISSUE THREAD

**Issue by Just1n** [jstedfast/MailKit#1204]
**Describe the bug**
We have a service task to download emails from the server, some days ago we found our service kept in running status without any errors thrown, we then went into the computer, and dumped the process, after analyzed the dump file, we found that the process was stuck at Socket.Receive(). See call stack:
![image](https://user-images.githubusercontent.com/517376/119753621-a4f69d80-bed1-11eb-9819-6f0bfb1960aa.png)
And the code in TryHardConnectAndAuthenticate() is pretty straight, it just calls `MailService.Connect(....)` with a timeout 30s.

After restarted our service task, everything went normal now. So to me it looks like a one-off issue, but the weird thing is, why it got stuck at Socket.Receive()? Why the Timeout didn't work?

**Platform (please complete the following information):**
 - OS: Windows
 - .NET Runtime: .NET CLR
 - .NET Framework: .NET 4.8
 - MailKit Version: 2.8.0.0

**Exception**
No exception

**To Reproduce**
It's unreproducible now, more like an one-off issue.

**Protocol Logs**
No protocol logs.

**Additional context**
Is this a bug of MailKit? Or any suggestion that you can give to make it not happen in the future? (e.g. forcibly abandon the connection after a certain time limit)

**Comment by Just1n** [comment]
Looks similar to another [issue](https://github.com/jstedfast/MailKit/issues/1186).

**Comment by Just1n** [comment]
Looks like it's been fixed since 2.9.0.0
https://github.com/jstedfast/MailKit/commit/a26b1d1090397df514c19e298031342cfe1a395d 
Closing this ticket.

**Comment by jstedfast** [comment]
Ah, yes, that would make sense. Good find! :)
