### ISSUE TITLE
Unable to connect to Gmail via IMAP using MailKit 2.12.0

### ISSUE THREAD

**Issue by MahmoudElias** [jstedfast/MailKit#1205]
I used MailKit v2.12.0 to connect my gmail account through IMAP with the following code:

```
using (var client = new ImapClient(new ProtocolLogger("imap.log")))
{
  client.Connect("imap.gmail.com", 993, SecureSocketOptions.SslOnConnect);
  client.AuthenticationMechanisms.Remove("XOAUTH2");	// with this line or without it
  client.Authenticate(userName, pwd); 
  ..
}

```
Many trials are made by:
- including/excluding "@gmail.com" at the end of userName
- Keeping/Removing XOAUTH2
but without a positive result. Always I have the following log:

**Connected to imaps://imap.gmail.com:993/
S: * OK Gimap ready for requests from 82.137.255.68 u15mb117714195wmj
C: A00000000 CAPABILITY
S: * CAPABILITY IMAP4rev1 UNSELECT IDLE NAMESPACE QUOTA ID XLIST CHILDREN X-GM-EXT-1 XYZZY SASL-IR AUTH=XOAUTH2 AUTH=PLAIN AUTH=PLAIN-CLIENTTOKEN AUTH=OAUTHBEARER AUTH=XOAUTH
S: A00000000 OK Thats all she wrote! u15mb117714195wmj
C: A00000001 AUTHENTICATE PLAIN xxxx
S: A00000001 NO [AUTHENTICATIONFAILED] Invalid credentials (Failure)
C: A00000002 LOGIN xxxx xxxx
S: A00000002 NO [AUTHENTICATIONFAILED] Invalid credentials (Failure)**

Are there any solutions please?

**Comment by jstedfast** [comment]
Try this: https://github.com/jstedfast/MailKit/blob/master/FAQ.md#GMailAccess

**Comment by MahmoudElias** [comment]
> Try this: https://github.com/jstedfast/MailKit/blob/master/FAQ.md#GMailAccess

I really appreciate your fast reply.
The solution of my problem was enabling "Less secure app access" for non-google apps, which enabled the access to gmail.

Thank you, and best regards,
Mahmoud
