### ISSUE TITLE
Google IMAP SSL error

### ISSUE THREAD

**Issue by Mobiusimmortal301** [jstedfast/MailKit#1206]
From my local machine, I have no issues, but when I push my code to Azure all I receive is MailKit.Security.SslHandshakeException

I have tried all the suggestions here: https://github.com/jstedfast/MailKit/blob/master/FAQ.md#SslHandshakeException

I also ran across this issue: https://github.com/jstedfast/MailKit/issues/735 but I can't apply the same fix they did because my code is in an Azure App Service.

**Comment by jstedfast** [comment]
You'll have to share more info about the error you are getting like the stack trace, the inner exception, what exactly you tried from the FAQ, what version of MailKit you are using, etc.

Have you tried writing a TcpClient to connect to GMail using System.Security's SslStream? Does that work?
