### ISSUE TITLE
How to I reply message with image

### ISSUE THREAD

**Issue by burakergun394** [jstedfast/MailKit#1211]
Hi sir,
Firstly sorry my english.
I want to reply to the person who sent your mail and I did but
If there is a picture in the e-mail I reply, I want to show it to the user. But as an attachment, I want to send the picture that the user sent me while replying to the user, not the picture I sent. I tried several ways. I want to send the picture without saving it to the file. For this, I wanted to convert the incoming image to base64 and send it with an img tag, but mail companies(google, yahoo etc..) do not support this. How can I make this happen?

**Comment by jstedfast** [comment]
Read the second part of the answer here: https://github.com/jstedfast/MailKit/blob/master/FAQ.md#Reply
