### ISSUE TITLE
Can't resolve the reference System.Security.Cryptography.DSACng::.ctor( System.Security.Cryptography.CngKey )

### ISSUE THREAD

**Issue by Jakar510** [jstedfast/MailKit#1212]
**Describe the bug**

After upgrading Visual Studio to v16.10.0, I got this build error in iOS. After some tracing, I discovered the build error doesn't occur once I remove **MailKit**. 

	Can't resolve the reference 'System.Void System.Security.Cryptography.DSACng::.ctor(System.Security.Cryptography.CngKey)', 
	referenced from the method 'T Internal.Cryptography.Pal.Windows.PkcsPalWindows::GetPrivateKey(System.Security.Cryptography.X509Certificates.X509Certificate2,System.Boolean,System.Boolean)'
	in 'System.Security.Cryptography.Cng, Version=4.3.3.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
		

I don't know if this library is the issue or it's in the `System.Security.Cryptography.Cng`. See this  [issue for more details](https://github.com/xamarin/xamarin-macios/issues/8772). 

this issue also seems to have occurred in the past. See [previous issue](https://github.com/jstedfast/MimeKit/issues/579).

**Platform (please complete the following information):**
 - OS: iOS
 - .NET Runtime: Xamarin.Forms v4.8.0.1821
 - .NET Framework: 2.1
 - MailKit Version: 2.12.0

**Comment by jstedfast** [comment]
Yea, this is a known issue - I just don't think I can resolve it from the MimeKit side of things. I think the Xamarin.iOS team needs to resolve this somehow.

Unless... what if you add a nuget reference to [System.Security.Cryptography.Cng](https://www.nuget.org/packages/System.Security.Cryptography.Cng)?

**Comment by Jakar510** [comment]
> Yea, this is a known issue - I just don't think I can resolve it from the MimeKit side of things. I think the Xamarin.iOS team needs to resolve this somehow.
> 
> Unless... what if you add a nuget reference to [System.Security.Cryptography.Cng](https://www.nuget.org/packages/System.Security.Cryptography.Cng)?

@jstedfast I tried adding it, but no change.

**Comment by jstedfast** [comment]
Okay, thanks for trying...

None of the MimeKit code explicitly calls the System.Security.Cryptography.DSACng..ctor() (other than the unit tests which are in a separate assembly), so I don't know why this is happening.

**Comment by Jakar510** [comment]
@jstedfast I don't know either. Even odder is that I can't get any meaningful stack trace during the build.

**Comment by jstedfast** [comment]
Something clearly changed in the IDE or the .NET libraries or something because this also broke recently for VSMac when it used to work fine.

This is unfixable on my side so I'm not sure keeping this open in MimeKit/MailKit makes any sense.
