### ISSUE TITLE
[Question] Get notification when new mail arrives

### ISSUE THREAD

**Issue by workgroupengineering** [jstedfast/MailKit#1213]
Hi, 
Thanks for the great library. I'm in the design phase of a new application. I would like to understand if it is possible to receive a notification when a new mail arrives or to use polling.

**Comment by jstedfast** [comment]
Yes, that's possible.

Not all IMAP servers support the IDLE extension, so if it doesn't support IDLE, you'll have to adopt a "polling" approach.

If you take a look at the [ImapIdle](https://github.com/jstedfast/MailKit/tree/master/samples/ImapIdle) sample, it should give you a good starting place to figure out how to do what you want to do.
