### ISSUE TITLE
Add support for Gmail’s [WEBALERT …] response code

### ISSUE THREAD

**Issue by MrYossu** [jstedfast/MailKit#1214]
**Is your feature request related to a problem? Please describe.**
When you try and access Gmail using a user name and password from a new device, you sometimes get a security alert email (which allows you to trust the device), but often don't.

On the [package author's request](https://stackoverflow.com/a/67822372/706346), I'd like to ask for Mailkit to add support for Gmail’s [WEBALERT …] response code.

**Comment by jstedfast** [comment]
MailKit 2.13.0 has been released with this fix.
