### ISSUE TITLE
AuthenticationException when the OAuth token has expired, but not asked to confirm again

### ISSUE THREAD

**Issue by MrYossu** [jstedfast/MailKit#1215]
Pardon me if this is a dumb question, but I'm really new at OAuth, and finding it hard to get my head around it.

I copied the [sample OAuth code shown in the FAQ](https://github.com/jstedfast/MailKit/blob/master/FAQ.md#GMailOAuth2) into a console app, and all worked fine. The first time I ran it, I got a pop-up asking me to confirm it was me, and then I could run again and again without any interruption.

However, I just tried it again, and got the following exception...

>MailKit.Security.AuthenticationException: 'Authentication failed.'

...on the following line of code...

    await client.AuthenticateAsync(oauth2);

Looking at the file that was created when I first ran, I can see that it contains an `"Issued"` property, with the time it was created, and an `"expires_in"` property that has a value of `3599`. Presuming this is milliseconds, then this means the token expired an hour after being issued, which I guess is why the auth failed just now. However, what I don't get is why it didn't ask me to confirm it was me again.

If I delete the token file and try again, I get the pop-up, and once I've confirmed it's me, it works fine.

How do I get around this? I can understand that the token expires, but don't know how to handle this to enable my code to continue.

Anyone able to advise? Thanks

**Comment by jstedfast** [comment]
Oh, looks like maybe I need to update the FAQ with the code snippet from my [GMailOAuth2.md](https://github.com/jstedfast/MailKit/blob/master/GMailOAuth2.md) docs.

Try this:

```csharp
var credential = await authCode.AuthorizeAsync (GMailAccount, CancellationToken.None);

if (credential.Token.IsExpired (SystemClock.Default))
	await credential.RefreshTokenAsync (CancellationToken.None);
```

I think when I originally wrote the FAQ (before writing the standalone doc), I wrongly assumed that the following if-statement would check expiration but it doesn't:

```csharp
if (authCode.ShouldRequestAuthorizationCode (credential.Token))
```

Can you let me know if that does/doesn't work for you?

If it works out, I'll update the FAQ... if not, I'll try to find time to look into it more.
```

**Comment by MrYossu** [comment]
That seems to work fine, thanks
