### ISSUE TITLE
Rename attachment file before sending

### ISSUE THREAD

**Issue by dheoxic** [jstedfast/MailKit#1217]
How do I rename an attachment before sending?

I am currently using the code below but is not working. I think I'm missing something after the rename.

                var msg = new MimeMessage();
                var username = "username";
                var password = "password";
                var displayname = "displayname";

                var from = new MailboxAddress(displayname, username);
                var to = new MailboxAddress("User", emailto);

                msg.From.Add(from);
                msg.To.Add(to);

                msg.Subject = emailsubject;
                var msgbody = new BodyBuilder
                {
                    HtmlBody = string.Format(@"Message"),
                    TextBody = "Message"
                };
                msgbody.Attachments.Add(Path.Combine(file.directory, "original name.zip"));
                foreach(var file in msg.Attachments)
                {
                    file.ContentDisposition.FileName = "new name.zip";
                }
                msg.Body = msgbody.ToMessageBody();

**Comment by jstedfast** [comment]
Try `file.FileName = "new name.zip";`

Technically, what you are doing is "correct", but some mailers use the `name` property on the Content-Type header instead of the `filename` parameter on the Content-Disposition header. The `MimePart.FileName` property sets both.
