### ISSUE TITLE
"Error 400: redirect_uri_mismatch" trying to connect to Gmail

### ISSUE THREAD

**Issue by MrYossu** [jstedfast/MailKit#1219]
I'm trying to use the [example code to connect to Gmail](https://github.com/jstedfast/MailKit/blob/master/FAQ.md#GMailOAuth2), but am running into the above error.

I'm running in Visual Studio, and copied the URI of the page that initiates the call to Gmail as the redirect URI...

![RedirectUri](https://user-images.githubusercontent.com/10185332/121916123-c659e500-cd2b-11eb-8346-000ce94c4227.png)

However, when I run my code, I get the a browser window pop up with the following error...

![GoogleAuthError](https://user-images.githubusercontent.com/10185332/121916323-f0aba280-cd2b-11eb-8a51-fed63cee2e15.png)

As you can see, the URI shown does not match the one I added in the Google console.

I've spent hours searching for an answer to this, but have failed to work out what is going on. Can anyone help me?

In case it makes a difference, my use case is that the code will be part of a web site, and there will be a background task that downloads emails. I realise that there will need to be some interaction with Google to authorise the access initially, so will provide a button on the admin user details page where they can connect to Gmail, which should pop up the authorisation window, then store the token on the server for future use. I don't know if that is the best (or even a practical) way to do this, so if anyone has any comments, I would be grateful.

**Comment by jstedfast** [comment]
Have you tried adding the http://127.0.0.1:64102/authorize URI to the list of authorized URIs?

I've never seen this error so I don't how to solve it.

**Comment by jstedfast** [comment]
FYI, not sure if you've seen these docs, but they may have useful info in them: https://developers.google.com/identity/protocols/oauth2/web-server

**Comment by MrYossu** [comment]
Hello again,

Thanks for the reply, but it didn't help. I tried adding the URL, but got the same error. I've been over that document several times, tried everything in there (including code from all sorts of other places), but nothing helps. I just keep getting the same error whatever I do.

Any idea how I can solve this? I can't believe its so hard to access a Gmail inbox. 

Thanks again.

**Comment by jstedfast** [comment]
I don't really have any experience in writing ASP.NET apps, unfortunately, so this question is out of my realm of expertise.

There is another way of authenticating using OAuth2 with Google/GMail. For service-to-service apps (which sounds like what you are doing?), there is a way to register your app that gives you a certificate that you can use instead of needing to pop up a browser window.

I suspect that the problem you are having stems from the way you are presenting this browser window to the user, so maybe the certificate route is what you need.

**Comment by jstedfast** [comment]
https://developers.google.com/api-client-library/dotnet/guide/aaa_oauth#serviceaccountcredential

**Comment by MrYossu** [comment]
@jstedfast Thanks for that. I did look at that, but like everything else with Google, it's soooo complex that you need a Phd in maths to understand it! As it happens, I do have a Phd in maths, but I still couldn't work it out!

For the moment, I'm using a plain user name and password, and will have to live with that until I've got the application working. Once the pressure is off, I can think about coming back to this.

Thanks again.
