### ISSUE TITLE
Catch exception "Invalid domain name"

### ISSUE THREAD

**Issue by Prazdnik** [jstedfast/MailKit#1220]
Recently I found such an error in the logs NewRelic.
![image](https://user-images.githubusercontent.com/10244929/122013603-8ad12080-cde8-11eb-8321-d450fdb25612.png)

The send method is wrapped in a try-catch design. How can I catch exactly the "nvalid domain name" error? Since I want to make a separate processing logic for it.

The address that caused this error looked like this "andrew@10.66".

`try
{
    _smtpClient.Send(mail);
}
    catch (Exception ex)
{
    // TODO: Invalid domain name
}`

**Comment by jstedfast** [comment]
You might be able to use the SmtpCommandException ErrorCode and/or StatusCode properties to help narrow it down. After that, you'll have to use something like `ex.Message.StartsWith ("Transaction failed: Invalid domain name:")`
