### ISSUE TITLE
SmtpClient.Send throwing an error “502 5.5.2 Error: command not recognized"

### ISSUE THREAD

**Issue by JahangirSheikh** [jstedfast/MailKit#1221]
Hi,

We are using MailKit SmtpClient (ver: 2.11.1) from NuGet package manager. Mail delivery works fine but in certain cases we do receive an error "5.5.2 Error: command not recognized". 

When we try sending the same mail to the same recipients using **System.Net.Mail.SmtpClient**, it works fine at both the application and postfix smtp server end. 

We have also ensured that all the email ids which are being used are valid email ids (Have masked these email ids while sharing below for data security reasons). 

Error Info:
```
Error Message: 5.5.2 Error: command not recognized
Stack Trace: at ExporterBAL.SmtpClientManager.SendMail(MimeMessage message) in E:\ExporterNew_V3\ExporterBAL\SmtpClientManager.cs:line 232
   at ExporterBAL.MailSender.sendMailSMTP(String fromAddr, String toAddr, String ccAddr, String bccAddr, String attachment, String subject, String strMessage, String SMTPServerName, Int32 RequestID, String SendMailType) in E:\ExporterNew_V3\ExporterBAL\MailSender.cs:line 389
Inner Exception: 
```

Protocol Log:
```
C: MAIL FROM:<xxxxxxxxxxx@xxxxxx.com> SIZE=14836
C: RCPT TO:<xxxxxxxxxxx@xxxxxx.com>
C: RCPT TO:<xxxxxxxxxxx@xxxxxx.com>
C: RCPT TO:<xxxxxxxxxxx@xxxxxx.com>
C: RCPT TO:<xxxxxxxxxxx@xxxxxx.com>
C: RCPT TO:<xxxxxxxxxxx@xxxxxx.com>
C: RCPT TO:<xxxxxxxxxxx@xxxxxx.com>
C: RCPT TO:<xxxxxxxxxxx@xxxxxx.com>
C: RCPT TO:<xxxxxxxxxxx@xxxxxx.com>
C: RCPT TO:<xxxxxxxxxxx@xxxxxx.com>
C: RCPT TO:<xxxxxxxxxxx@xxxxxx.com>
C: RCPT TO:<xxxxxxxxxxx@xxxxxx.com>
C: RCPT TO:<xxxxxxxxxxx@xxxxxx.com>
C: RCPT TO:<xxxxxxxxxxx@xxxxxx.com>
C: RCPT TO:<xxxxxxxxxxx@xxxxxx.com>
C: RCPT TO:<xxxxxxxxxxx@xxxxxx.com>
C: RCPT TO:<xxxxxxxxxxx@xxxxxx.com>
C: RCPT TO:<xxxxxxxxxxx@xxxxxx.com>
C: RCPT TO:<xxxxxxxxxxx@xxxxxx.com>
C: RCPT TO:<xxxxxxxxxxx@xxxxxx.com>
C: RCPT TO:<xxxxxxxxxxx@xxxxxx.com>
C: RCPT TO:<xxxxxxxxxxx@xxxxxx.com>
C: RCPT TO:<xxxxxxxxxxx@xxxxxx.com>
C: RCPT TO:<xxxxxxxxxxx@xxxxxx.com>
C: RCPT TO:<xxxxxxxxxxx@xxxxxx.com>
C: RCPT TO:<xxxxxxxxxxx@xxxxxx.com>
C: RCPT TO:<xxxxxxxxxxx@xxxxxx.com>
C: RCPT TO:<xxxxxxxxxxx@xxxxxx.com>
C: RCPT TO:<xxxxxxxxxxx@xxxxxx.com>
C: RCPT TO:<xxxxxxxxxxx@xxxxxx.com>
C: RCPT TO:<xxxxxxxxxxx@xxxxxx.com>
C: RCPT TO:<xxxxxxxxxxx@xxxxxx.com>
C: RCPT TO:<xxxxxxxxxxx@xxxxxx.com>
C: RCPT TO:<xxxxxxxxxxx@xxxxxx.com>
C: RCPT TO:<xxxxxxxxxxx@xxxxxx.com>
C: RCPT TO:<xxxxxxxxxxx@xxxxxx.com>
C: RCPT TO:<xxxxxxxxxxx@xxxxxx.com>
C: RCPT TO:<xxxxxxxxxxx@xxxxxx.com>
C: RCPT TO:<xxxxxxxxxxx@xxxxxx.com>
C: RCPT TO:<xxxxxxxxxxx@xxxxxx.com>
C: RCPT TO:<xxxxxxxxxxx@xxxxxx.com>  
S: 250 2.1.0 Ok
S: 250 2.1.5 Ok
S: 250 2.1.5 Ok
S: 250 2.1.5 Ok
S: 250 2.1.5 Ok
S: 250 2.1.5 Ok
S: 250 2.1.5 Ok
S: 250 2.1.5 Ok
S: 250 2.1.5 Ok
S: 250 2.1.5 Ok
S: 250 2.1.5 Ok
S: 250 2.1.5 Ok
S: 250 2.1.5 Ok
S: 250 2.1.5 Ok
S: 250 2.1.5 Ok
S: 250 2.1.5 Ok
S: 250 2.1.5 Ok
S: 250 2.1.5 Ok
S: 250 2.1.5 Ok
S: 250 2.1.5 Ok
S: 250 2.1.5 Ok
S: 250 2.1.5 Ok
S: 250 2.1.5 Ok
S: 250 2.1.5 Ok
S: 250 2.1.5 Ok
S: 250 2.1.5 Ok
S: 250 2.1.5 Ok
S: 250 2.1.5 Ok
S: 250 2.1.5 Ok
S: 502 5.5.2 Error: command not recognized
S: 250 2.1.5 Ok
S: 250 2.1.5 Ok
S: 250 2.1.5 Ok
S: 250 2.1.5 Ok
S: 250 2.1.5 Ok
S: 250 2.1.5 Ok
S: 250 2.1.5 Ok
S: 250 2.1.5 Ok
S: 250 2.1.5 Ok
S: 250 2.1.5 Ok
S: 250 2.1.5 Ok
C: RSET
S: 250 2.0.0 Ok 
```

We tried addressing the issue but couldn't find the apparent reason for the same. It would be helpful if you could help us to understand the issue.

**Comment by jstedfast** [comment]
Each of those responses maps to the corresponding `MAIL FROM` or `RCPT TO` commands that precede it.

In other words, the error message is for the 29th `RCPT TO` command.

Normally, the way SMTP works is that the client sends 1 command and then receives 1 response, but MailKit supports pipelining commands which essentially it means that MailKit will, if the server claims to support it, send a slew of commands and then read all of the responses after it has blitted those commands to the server.

In the scenario that you provided logs for, it's *possible* that the 29th `RCPT TO` command cross buffer boundaries - in other words, when MailKit flushed its internal 4K output buffer, only a partial `RCPT TO` command was included at the end of that 4K TCP/IP packet and the server wrongly did not await the next packet before checking to see if the next packet completed a partial command string.

This would technically be a bug in the server, but you can work around it in the client by disabling Pipelining support like this:

```csharp
client.Connect ("some.server.com", 587, SecureSocketOptions.StartTls);
client.Authenticate ("username", "password");

// Note: The following line will disable the SMTP PIPELINING extension
client.Capabilities &= ~SmtpCapabilities.Pipelining;

client.Send (message);
```

**Comment by JahangirSheikh** [comment]
Thanks a lot for the prompt and detailed response.

As you suggested, we tried disabling pipelining for this case and it worked, however if we still want to keep pipelining enabled as there will be advantages in doing so, is there any config change that we need to do at the SMTP server level which can allow us to use pipelining; or is there any known bug that you can highlight or share any reference with respect to Postfix v3.1 SMTP server;

**Comment by jstedfast** [comment]
That's all something you'd have to ask the Postfix developers.
