### ISSUE TITLE
Authentication error codes

### ISSUE THREAD

**Issue by fairking** [jstedfast/MailKit#1223]
**Describe the bug**
It is an question not a bug.
After few days of normally working IMAP connection suddenly I started to receive errors.
I receive `Authentication error - 0402`. The question is what does `0402` mean and where I can find a list of all error codes. I looked at the documentation and only found this: http://www.mimekit.net/docs/html/T_MailKit_Security_AuthenticationException.htm
Or maybe that error code belongs to IMAP server rather than to MailKit.
Thanks.

**Platform (please complete the following information):**
 - OS: Windows
 - .NET Runtime: CoreCLR
 - .NET Framework: .Net Core
 - MailKit Version: 2.12.0

**Exception**
```
Hangfire.Server.JobPerformanceException: An exception occurred during performance of the job.
 ---> MailKit.Security.AuthenticationException: Authentication error - 0402
   at MailKit.Net.Imap.ImapClient.AuthenticateAsync(Encoding encoding, ICredentials credentials, Boolean doAsync, CancellationToken cancellationToken)
```

**To Reproduce**
Steps to reproduce the behavior not required.

**Comment by jstedfast** [comment]
Unfortunately, the 0402 error code comes from the server and is not a standardized error code for the IMAP protocol.

**Comment by fairking** [comment]
Ah, ok. Sorry. I thought there is a meaning of the code somewhere.
I very appreciate you reply. Thanks.

**Comment by jstedfast** [comment]
No problem, hope you manage to figure out the issue.
