### ISSUE TITLE
Chinese gibberish

### ISSUE THREAD

**Issue by myall200** [jstedfast/MailKit#1225]
**Describe the bug**

**Platform (please complete the following information):**
 - OS: Windows, MacOS
 - .NET Runtime:  CoreCLR,
 - .NET Framework: .NET5
 - MailKit Version: 2.12.0

In. Net5, receive mail, Chinese gibberish, in. Net 3.1 under normal

**Comment by myall200** [comment]
Attach file name and mail Title is random code in Net5, but in .Net 3.1 is normal.

**Comment by myall200** [comment]
![12271624348697_ pic_hd](https://user-images.githubusercontent.com/10205986/122886661-bcab2f80-d372-11eb-85cd-db0720726a2e.jpg)
![12281624348697_ pic_hd](https://user-images.githubusercontent.com/10205986/122886684-c03eb680-d372-11eb-9f15-79d7e08bd206.jpg)

**Comment by jstedfast** [comment]
You are likely missing text encodings in your .NET 5 - you might need to reference System.Text.Encodings.CodePages or something.

**Comment by myall200** [comment]
Add System.Text.Encoding.CodePages and 
System.Text.Encoding.RegisterProvider(System.Text.CodePagesEncodingProvider.Instance);
It worked!
Thank you, and best regards,
