### ISSUE TITLE
DeliveryNotificationOptions in MimeMessage model

### ISSUE THREAD

**Issue by Laser42** [jstedfast/MailKit#1226]
**Is your feature request related to a problem? Please describe.**
I need to set DeliveryNotificationOptions for a message. When using built-in MailMessage class from System.Net.Mail, there is a property named DeliveryNotificationOptions which represents enum DeliveryNotificationOptions. So, when I create MailMessage instance, I can easily set up this property. In MailKit I found no such property

**Describe the solution you'd like**
I'd like to have an ability to get and set a property DeliveryNotificationOptions in my MimeMessage

**Describe alternatives you've considered**
The only workaround I found was to inherit from SmtpClient and overrride GetDeliveryStatusNotifications method (and do this every time I send a message!)

**Additional context**
I also wonder which DeliveryStatusNotification is default for SmtpClient (receive nothing / all or what?)

**Comment by jstedfast** [comment]
MimeMessage's properties are all serializable as message headers (or, of course, the message body).

The DeliveryStatusNotification property on MailMessage is not a header. It's a hint to their SmtpClient as to what it should do.

This is why you need to inherit from SmtpClient to do the same thing in MailKit, because that value really has nothing to do with MIME, it is SMTP-only.

**Comment by Laser42** [comment]
Ok, so SmtpClient (or child) must be injected as transient to guarantee that every sending should use its own instanse of client

**Comment by jstedfast** [comment]
You don't need a new instance of an SmtpClient for each message to be sent, you just need your override of the [GetDeliveryStatusNotifications()](http://www.mimekit.net/docs/html/M_MailKit_Net_Smtp_SmtpClient_GetDeliveryStatusNotifications.htm) method to decide which notifications are wanted based on the MimeMessage being sent which is made possible by the fact that that method takes a MimeMessage argument (which is the same MimeMessage passed to the Send() method).
