### ISSUE TITLE
Certificate Revocation Check using proxy

### ISSUE THREAD

**Issue by PrzemyslawKlys** [jstedfast/MailKit#1228]
If the user is behind proxy I believe checking certificate revocation may not work correctly. I know you can SkipCertificateRevocation, but maybe it would be better, more secure to actually allow proxy definition?

**Comment by jstedfast** [comment]
It's not really clear to me what the issue is...

It seems his SSL certificate validation is failing because SslStream is failing to retrieve the certificate from the CA/OCSP server.

Other than setting CheckCertificateRevocation to false, I'm not sure what else can be done.

**Comment by PrzemyslawKlys** [comment]
Well, his internet is restricted - meaning any Internet access requires a proxy server. To retrieve certificate from CA/OCSP you need to use internet right? So the logical thing to do would be to use proxy to connect? 

For example: https://www.digicert.com/kb/util/utility-test-ocsp-and-crl-access-from-a-server.htm

![image](https://user-images.githubusercontent.com/15063294/123555762-05eeeb00-d788-11eb-8130-4741b86c6cc9.png)

It would seem - this is a standard practice? Or am I wrong here?

**Comment by jstedfast** [comment]
No, you are not wrong, I just mean that there's no way for MailKit to make SslStream use the same proxy specified by the ImapClient.Proxy property.

**Comment by PrzemyslawKlys** [comment]
I see. Thought it would be possible to set a proxy. Thank you anyways.
