### ISSUE TITLE
IMAP Message Flags Deleted problem

### ISSUE THREAD

**Issue by Tonay** [jstedfast/MailKit#1230]
Hello everyone,

I don't know this is bug or something else that when i marked email as a deleted ( `client.Inbox.AddFlags(uid, MessageFlags.Deleted, true`  or `client.Inbox.SetFlags(uid, MessageFlags.Deleted, true` ) in Gmail, the message deleting permanently without any `Expunge()`. 

I just want to marked as a deleted ( and move trash folder directly after marked complete).

**Comment by jstedfast** [comment]
This is a feature of GMail. You can go into your GMail settings in the IMAP/POP3 section and change the behavior of what GMail will do when you mark a message as deleted.
