### ISSUE TITLE
How do I fix OAuth 2 Client.Authenticate errorMessage=AuthenticationInvalidCredentials: 5.7.8 

### ISSUE THREAD

**Issue by victoryplayerumer** [jstedfast/MailKit#1231]
I'm trying to support "secure" OAUTH2.0 access to Gmail so that our users don't need to "allow less secure apps" nor get an app password. The problem is Message=AuthenticationInvalidCredentials: 5.7.8 Username and Password not accepted. Learn more at
5.7.8 https://support.google.com/mail/?p=BadCredentials b84sm4142328ljf.60 - gsmtp. I dont know y is this happening here is my code :-

```csharp
var secrets = new ClientSecrets
{
    ClientId = ClientId,//i made them secret
    ClientSecret = ClientSecret
};
var codeFlow = new GoogleAuthorizationCodeFlow(new GoogleAuthorizationCodeFlow.Initializer
{
    DataStore = new FileDataStore("CredentialCacheFolder", false),
    Scopes = new[] { "https://mail.google.com/" },
    ClientSecrets = secrets
});

// Note: For a web app, you'll want to use AuthorizationCodeWebApp instead.
var codeReceiver = new LocalServerCodeReceiver();
var authCode = new AuthorizationCodeInstalledApp(codeFlow, codeReceiver);

var credential = await authCode.AuthorizeAsync(senderaddress.Text, CancellationToken.None);

if (credential.Token.IsExpired(SystemClock.Default))
    await credential.RefreshTokenAsync(CancellationToken.None);

var oauth2 = new SaslMechanismOAuth2(credential.UserId, credential.Token.AccessToken);

using (var client = new SmtpClient())
{
    await client.ConnectAsync(smtpaddress, port, SecureSocketOptions.StartTls);
    await client.AuthenticateAsync(oauth2);
    await client.SendAsync(message);
    await client.DisconnectAsync(true);
}
```

@jstedfast Help me Master

**Comment by jstedfast** [comment]
-[ ] Did you register your app with Google?
-[ ] Does it pop up a Google login window?
-[ ] You might have to submit a support ticket to Google - maybe they can help diagnose what is going wrong with your credential request (MailKit just sends the token, so it's not likely to be a MailKit bug).

You could try the `SaslMechanismOAuthBearer` mechanism (that's the replacement for XOAUTH2 that Google seems to be trying to switch to).

Maybe XOAUTH2 doesn't work any more?

**Comment by victoryplayerumer** [comment]
> - [ ] Did you register your app with Google?
> - [ ] Does it pop up a Google login window?
> - [ ] You might have to submit a support ticket to Google - maybe they can help diagnose what is going wrong with your credential request (MailKit just sends the token, so it's not likely to be a MailKit bug).
> 
> You could try the `SaslMechanismOAuthBearer` mechanism (that's the replacement for XOAUTH2 that Google seems to be trying to switch to).
> 
> Maybe XOAUTH2 doesn't work any more?

1 I have registered my app
2 Sometimes it does popup but sometimes it doesn't
3 if SaslMechanismOAuthBearer doesn't work then i will
4 ok i will try it
5 maybe

**Comment by jstedfast** [comment]
Did you manage to find a solution?

**Comment by chikien276** [comment]
Hi @jstedfast I have this issue too. But my code is a bit different 
```
Credential = new ServiceAccountCredential(
   new ServiceAccountCredential.Initializer(EmailConfig.Email)
   {
       Scopes = new[] { "https://mail.google.com/" }
   }.FromCertificate(certificate));
   
using var client = new SmtpClient();
string token = await Credential.GetAccessTokenForRequestAsync("https://mail.google.com/");

//token = token.Substring(0, token.IndexOf("..."));
var oauth2 = new SaslMechanismOAuthBearer(EmailConfig.FromEmail, token);
client.Connect("smtp.gmail.com", 587, SecureSocketOptions.StartTls);
await client.AuthenticateAsync(oauth2);
client.Send(msg);
client.Disconnect(true);
```
If I use this code, I will get error `AuthenticationException: 555: 5.5.2 Syntax error, goodbye`
I notice that the token generated have a lot of trailing `...` I tried to trim it. Then I got the error `Username and Password not accepted`
Could you please help to investigate ?

**Comment by jstedfast** [comment]
I can't help you. You'll need to ask Google for help with their libraries because I do not know them very well.

**Comment by chikien276** [comment]
Thank you for your response. I read somewhere that `ServiceAccountRedential` cannot use for sending email :(. Just want to post here so everyone else wont fall into this rabbit hole.
