### ISSUE TITLE
Imap at mail.ru

### ISSUE THREAD

**Issue by Babico1** [jstedfast/MailKit#1234]
**Describe the bug**
When i want to use imap at mail.ru mailbox i get that error "2factor Exception The IMAP server replied to the 'SEARCH' command with a 'NO' response: Unsupported search criterion: FROM "

**Platform (please complete the following information):**
 - OS: Windows
 -

**Comment by jstedfast** [comment]
If mail.ru doesn't support the FROM search criteria, I don't know what I can do about that...

The FROM search criteria is a standard part of the IMAP protocol and is required to be implemented in order for a server to claim that they support IMAP.

https://datatracker.ietf.org/doc/html/rfc3501#section-6.4.4

**Comment by jstedfast** [comment]
If you want to continue to use mail.ru, I would recommend not using SearchQuery.FromContains()

**Comment by jstedfast** [comment]
FYI: https://ru.stackoverflow.com/questions/289544/mail-ru-imap-unsupported-search-criterion

mail.ru doesn't implement (any?) SEARCH criteria
