### ISSUE TITLE
The IMAP server replied to the 'FETCH' command with a 'BAD' response: Error in IMAP command FETCH: Invalid messageset

### ISSUE THREAD

**Issue by DierkDroth** [jstedfast/MailKit#1235]
**Describe the bug**
IMailFolder.FetchAsync throws error above on one of my customer's mail servers. The code works perfectly on other mail servers
`await MailFolder.FetchAsync(0, -1, (ulong) MailAccount.HighestModSeq, MessageSummaryItems.UniqueId, cts.Token)`

**Platform (please complete the following information):**
 - OS: Windows
 - MailKit Version: latest

**Exception**
MailKit.Net.Imap.ImapCommandException
  HResult=0x80131500
  Message=The IMAP server replied to the 'FETCH' command with a 'BAD' response: Error in IMAP command FETCH: Invalid messageset (0.001 + 0.000 secs).
  Source=MailKit
  StackTrace:
   at MailKit.Net.Imap.ImapFolder.<FetchAsync>d__233.MoveNext()

Here is an snippet of the log:
S: A00000006 OK Subscribe completed (0.001 + 0.000 secs).
C: A00000007 LIST "" "INBOX.%" RETURN (SUBSCRIBED CHILDREN)
S: * LIST (\Subscribed \HasNoChildren) "." INBOX.Done
S: * LIST (\Subscribed \HasNoChildren) "." INBOX.spam
S: * LIST (\Subscribed \HasNoChildren) "." INBOX.Trash
S: * LIST (\Subscribed \HasNoChildren) "." INBOX.Sent
S: * LIST (\HasNoChildren) "." INBOX.Junk
S: * LIST (\Subscribed \HasNoChildren) "." INBOX.Drafts
S: * LIST (\HasNoChildren) "." INBOX.Archive
S: A00000007 OK List completed (0.001 + 0.000 secs).
C: A00000008 FETCH 1:* UID (CHANGEDSINCE 0)
S: A00000008 BAD Error in IMAP command FETCH: Invalid messageset (0.001 + 0.000 secs).
C: A00000009 LOGOUT

Any idea what's going on? 

Thanks in advance

**Comment by jstedfast** [comment]
Seems like a bug in the IMAP server. The `seq-range` of `1:*` should ALWAYS be valid even if there are no messages in the folder, but I suspect that this IMAP server breaks in this condition.

A work-around might be to only issue a FETCH request if `folder.Count > 0`.

**Comment by jstedfast** [comment]
It might also be that the server's error message is misleading and perhaps it is failing due to the modseq value being `0`.

You could try something like this:

```csharp
if ((ulong) MailAccount.HighestModSeq > 0)
    await MailFolder.FetchAsync(0, -1, (ulong) MailAccount.HighestModSeq, MessageSummaryItems.UniqueId, cts.Token);
else
    await MailFolder.FetchAsync(0, -1, MessageSummaryItems.UniqueId, cts.Token);
```

**Comment by jstedfast** [comment]
Let me know if neither of those solutions works. It's also *possible* that the server expects the `UID` token to be within parens (it shouldn't, but GMail, for example, expected macos like `ALL` and `FULL` to be within parens even tho that is not required by the spec).

The spec allows singleton fetch items to be sent w/o being in parens. E.g. parens are only needed if multiple FETCH items are specified:

```
fetch           = "FETCH" SP sequence-set SP ("ALL" / "FULL" / "FAST" /
                  fetch-att / "(" fetch-att *(SP fetch-att) ")")
```

**Comment by DierkDroth** [comment]
> It might also be that the server's error message is misleading and perhaps it is failing due to the modseq value being `0`.
> 
> You could try something like this:
> 
> ```cs
> if ((ulong) MailAccount.HighestModSeq > 0)
>     await MailFolder.FetchAsync(0, -1, (ulong) MailAccount.HighestModSeq, MessageSummaryItems.UniqueId, cts.Token);
> else
>     await MailFolder.FetchAsync(0, -1, MessageSummaryItems.UniqueId, cts.Token);
> ```

Interesting. This appeared to work. I'll get back to you as the customer reports further issues.

Thanks

**Comment by DierkDroth** [comment]
Ahh .. this drives me nuts: on very next try it appeared to work. Here are the logs:
C: A00000008 FETCH 1:* UID (CHANGEDSINCE 1)
S: * 1 FETCH (UID 1 MODSEQ (2))
A00000008 OK Fetch completed (0.001 + 0.000 secs).

Not sure what's going on here. Any idea?!?

**Comment by jstedfast** [comment]
You've just verified that your IMAP server doesn't handle FETCH requests when there are 0 messages in a folder.

You can work around this by doing the following:

```csharp
if (folder.Count > 0) {
    if ((ulong) MailAccount.HighestModSeq > 0)
        return await MailFolder.FetchAsync(0, -1, (ulong) MailAccount.HighestModSeq, MessageSummaryItems.UniqueId, cts.Token);
    else
        return await MailFolder.FetchAsync(0, -1, MessageSummaryItems.UniqueId, cts.Token);
} else {
    return Array.Empty<IMessageSummary>();
}
```

**Comment by DierkDroth** [comment]
Hmm ... are you sure? This capp
C: A00000008 FETCH 1:* UID (CHANGEDSINCE 1)

... did work as I had an email in the account and did not work right before as I had the same email in the account.

What am I missing?

**Comment by jstedfast** [comment]
If it's not that the folder was empty, then it's just that the server is broken. There's no other explanation I can think of.

**Comment by DierkDroth** [comment]
Hmm ... ok thanks. I'll keep and eye and will get back to you as I had more input on the case.
