### ISSUE TITLE
System.FormatException: Invalid INTERNALDATE format: 00-Jan-0000 00:00:00 +0000

### ISSUE THREAD

**Issue by zmarkusdev** [jstedfast/MailKit#1236]
**Describe the bug**
When fetching from a Domino IMAP4 Server with the version 10.0.1 i occasionaly get the exception documented below.

**Platform (please complete the following information):**
 - OS: Windows
 - .NET Framework: 4.6.1
 - MailKit Version: 2.9.0

**Exception**
If you got an exception, please include the exception Message *and* StackTrace.

> System.FormatException: Invalid INTERNALDATE format: 00-Jan-0000 00:00:00 +0000
bei MailKit.Net.Imap.ImapUtils.ParseInternalDate(String text)
bei MailKit.Net.Imap.ImapFolder.<ReadDateTimeOffsetTokenAsync>d__188.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
bei MailKit.Net.Imap.ImapFolder.<FetchSummaryItemsAsync>d__189.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
bei MailKit.Net.Imap.ImapFolder.<FetchSummaryItemsAsync>d__190.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
bei MailKit.Net.Imap.ImapEngine.<ProcessUntaggedResponseAsync>d__173.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
bei MailKit.Net.Imap.ImapCommand.<StepAsync>d__83.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
bei MailKit.Net.Imap.ImapEngine.<IterateAsync>d__174.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
bei MailKit.Net.Imap.ImapEngine.<RunAsync>d__175.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
bei MailKit.Net.Imap.ImapFolder.<FetchAsync>d__230.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
bei MailKit.Net.Imap.ImapFolder.Fetch(Int32 min, Int32 max, MessageSummaryItems items, CancellationToken cancellationToken)

**Protocol Logs**
Please include a protocol log (scrubbed of any authentication data), especially
if you got an exception such as `Syntax error in XYZ. Unexpected token: ...`.

> S: * OK Domino IMAP4 Server Release 10.0.1FP3 ready Mon, 26 Jul 2021 13:56:27 +0200
C: L00000000 CAPABILITY
S: * CAPABILITY IMAP4rev1 AUTH=PLAIN LITERAL+ QUOTA UIDPLUS
S: L00000000 OK CAPABILITY completed
C: L00000001 AUTHENTICATE PLAIN
S: +
C: ************************************
S: L00000001 OK AUTHENTICATE completed
C: L00000002 CAPABILITY
S: * CAPABILITY IMAP4rev1 AUTH=PLAIN LITERAL+ QUOTA UIDPLUS
S: L00000002 OK CAPABILITY completed
C: L00000003 LIST "" ""
S: * LIST (\Noselect) "\\" ""
S: L00000003 OK LIST completed
C: L00000004 LIST "" "INBOX"
S: * LIST (\Noinferiors \HasNoChildren) "\\" Inbox
S: L00000004 OK LIST completed
C: L00000005 EXAMINE Inbox
S: * 277 EXISTS
S: * 0 RECENT
S: * OK [UNSEEN 263] Message 263 is first unseen
S: * OK [UIDVALIDITY 36] UIDs valid
S: * OK [UIDNEXT 21234] Predicted next UID
S: * FLAGS (\Flagged \Seen \Answered \Deleted \Draft)
S: * OK [PERMANENTFLAGS ()] No permanent flags permitted
S: L00000005 OK [READ-ONLY] EXAMINE completed
C: L00000006 FETCH 253:277 (UID INTERNALDATE)
S: * 253 FETCH (UID 21093 INTERNALDATE "21-Jul-2021 06:11:32 +0000")
S: * 254 FETCH (UID 21111 INTERNALDATE "21-Jul-2021 12:18:36 +0000")
S: * 255 FETCH (UID 21123 INTERNALDATE "22-Jul-2021 05:03:43 +0000")
S: * 256 FETCH (UID 21124 INTERNALDATE "22-Jul-2021 05:03:53 +0000")
S: * 257 FETCH (UID 21141 INTERNALDATE "22-Jul-2021 08:28:30 +0000")
S: * 258 FETCH (UID 21145 INTERNALDATE "22-Jul-2021 07:15:18 +0000")
S: * 259 FETCH (UID 21149 INTERNALDATE "22-Jul-2021 08:28:36 +0000")
S: * 260 FETCH (UID 21153 INTERNALDATE "22-Jul-2021 11:58:25 +0000")
S: * 261 FETCH (UID 21164 INTERNALDATE "07-Jul-2021 15:35:49 +0000")
S: * 262 FETCH (UID 21173 INTERNALDATE "22-Jul-2021 15:34:32 +0000")
S: * 263 FETCH (UID 21184 INTERNALDATE "23-Jul-2021 08:06:18 +0000")
S: * 264 FETCH (UID 21185 INTERNALDATE "23-Jul-2021 05:02:07 +0000")
S: * 267 FETCH (UID 21197 INTERNALDATE "00-Jan-0000 00:00:00 +0000")
S: * 269 FETCH (UID 21211 INTERNALDATE "26-Jul-2021 06:55:19 +0000")
S: * 270 FETCH (UID 21212 INTERNALDATE "26-Jul-2021 06:05:56 +0000")
S: * 271 FETCH (UID 21213 INTERNALDATE "26-Jul-2021 07:28:01 +0000")
S: * 272 FETCH (UID 21217 INTERNALDATE "26-Jul-2021 08:13:11 +0000")
S: * 273 FETCH (UID 21220 INTERNALDATE "26-Jul-2021 06:15:51 +0000")
S: * 274 FETCH (UID 21225 INTERNALDATE "22-Jul-2021 12:02:32 +0000")
S: * 265 FETCH (UID 21195 INTERNALDATE "00-Jan-0000 00:00:00 +0000")
S: * 268 FETCH (UID 21198 INTERNALDATE "00-Jan-0000 00:00:00 +0000")
S: * 266 FETCH (UID 21196 INTERNALDATE "00-Jan-0000 00:00:00 +0000")
S: * 275 FETCH (UID 21229 INTERNALDATE "26-Jul-2021 09:24:43 +0000")
S: * 276 FETCH (UID 21231 INTERNALDATE "26-Jul-2021 07:40:51 +0000")
S: * 277 FETCH (UID 21233 INTERNALDATE "26-Jul-2021 11:50:25 +0000")
S: L00000006 OK FETCH completed

**Additional context**

**Comment by jstedfast** [comment]
Yikes, yea, "00-Jan-0000 00:00:00 +0000" is an invalid date. Not sure how Domino ended up having that internal date for the message, but I can look into handling this edge case better and not throwing an exception so that you can still get mail.

Thanks for reporting this.

**Comment by jstedfast** [comment]
I plan to make a new release this week which will contain this fix. Keep an eye out for 2.14.0.
