### ISSUE TITLE
MailKit.Security.SslHandshakeException with client on Windows 2019

### ISSUE THREAD

**Issue by ckePriv** [jstedfast/MailKit#1238]
Hi @jstedfast,
sorry to come up with this exception (again), but currently I'm struggeling with the following scenario:
I try to connect to an internal imap server, using SSL on port 993. That works, as long as I run my testclient on a Windows Server 2016. Using the same code and the same credentials from a Windows Server 2019 I'm blocked with that exception. I'm pretty sure that this might be an issue on the Win 2019 I'm testing with but currently I have no clue where to look. The callback even 
seems not to work in this case ... Are you aware of any known issues/circumstances with WinServer 2019?
`ServicePointManager.SecurityProtocol` states `SystemDefault`
Imap protocol file is created empty but does not contain any content.
Any hints are welcome ...

** Platform (please complete the following information): **
 - OS: Win2016 vs. Win2019 (see description)
 - .NET Framework: 4.8
 - MailKit Version: 2.11.1

** Used code snippet **
```
        public void InitIMapClient(string[] args)
        {
            // args:
            // 0 - Hostname
            // 1 - Port
            // 2 - UserId
            // 3 - Password
            try
            {
                Console.WriteLine(ServicePointManager.SecurityProtocol);
                Console.WriteLine("Host:" + args[0]);
                Console.WriteLine("Port:" + args[1]);
                Console.WriteLine("User:" + args[2]);
                Console.WriteLine("Pwd: " + args[3]);

                string logPath = System.IO.Path.Combine(System.IO.Path.GetTempPath(), "Imap.log");
                client = new ImapClient(new ProtocolLogger(logPath));

                client.ServerCertificateValidationCallback = (object sender,
                                                      X509Certificate certificate,
                                                      X509Chain chain,
                                                      SslPolicyErrors sslPolicyErrors) => true;
                
                client.Connect(args[0], int.Parse(args[1]), useSsl: true);
                client.Authenticate(args[2], args[3]);
                inbox = client.Inbox;
                ImapFolder fldr = (ImapFolder)inbox;
                inbox.Open(FolderAccess.ReadWrite);
                Console.WriteLine("Success!");

            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.ToString());
            }
        }
```

 **Exception** 
```
MailKit.Security.SslHandshakeException: An error occurred while attempting to establish an SSL or TLS connection.

This usually means that the SSL certificate presented by the server is not trusted by the system for one or more of
the following reasons:

1. The server is using a self-signed certificate which cannot be verified.
2. The local system is missing a Root or Intermediate certificate needed to verify the server's certificate.
3. A Certificate Authority CRL server for one or more of the certificates in the chain is temporarily unavailable.
4. The certificate presented by the server is expired or invalid.
5. The set of SSL/TLS protocols supported by the client and server do not match.
6. You are trying to connect to a port which does not support SSL/TLS.

See https://github.com/jstedfast/MailKit/blob/master/FAQ.md#SslHandshakeException for possible solutions.
 ---> System.Security.Authentication.AuthenticationException: A call to SSPI failed, see inner exception. ---> System.ComponentModel.Win32Exception: The message received was unexpected or badly formatted
   --- End of inner exception stack trace ---
   at System.Net.Security.SslState.StartSendAuthResetSignal(ProtocolToken message, AsyncProtocolRequest asyncRequest, Exception exception)
   at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ForceAuthentication(Boolean receiveFirst, Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.Security.SslStream.AuthenticateAsClient(String targetHost, X509CertificateCollection clientCertificates, SslProtocols enabledSslProtocols, Boolean checkCertificateRevocation)
   at MailKit.Net.Imap.ImapClient.<ConnectAsync>d__92.MoveNext()
   --- End of inner exception stack trace ---
   at MailKit.Net.Imap.ImapClient.<ConnectAsync>d__92.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MailKit.Net.Imap.ImapClient.Connect(String host, Int32 port, SecureSocketOptions options, CancellationToken cancellationToken)
   at MailKit.MailService.Connect(String host, Int32 port, Boolean useSsl, CancellationToken cancellationToken)
   at IMAP_Test.IMAP.InitIMapClient(String[] args)
```

**Comment by ckePriv** [comment]
Took me half a day now to figure out that something was missing in the Win 2019 installation / configuration. I was not abel to figure it out in detail, but some hints in various groups, so here if someone might struggle with the same:
The tool used to fix is [IICrypto](https://www.nartac.com/Products/IISCrypto), and it showed the initial state for the schannels like this:
![image](https://user-images.githubusercontent.com/83004590/127147310-a58f1208-55ac-48ff-acfd-72962a70dbbb.png)

After using the recommended button "Best Practices" followed up by a reboot the connection starts working. What I'm wondering about is, that this tool activated the other tls1.x protocols as well. After deactivating them again it still keeps working. So in conclusion I guess, that there was something broken within the protocol activation configuration on that machine.

![image](https://user-images.githubusercontent.com/83004590/127147876-67f36857-3bda-4ef0-900c-04f5a3363110.png)

**Comment by jstedfast** [comment]
I hope I can provide some additional insight to your update...

Was the 2019 server acting as the IMAP server? Or was your IMAP *client* code running on it? (It sounds like it is the *client* running on the Windows Server 2016 and 2019, right?)

Note that there are 2 sections with TLS in your screenshots - **Server Protocols** and **Client Protocols**.

In your initial screenshot, the **Client Protocols** had TLS 1.0, 1.1, and 1.2 enabled but the **Server Protocols** only had TLS 1.2 enabled.

Also of note are the **Ciphers** and **Key Exchanges**. The SSL/TLS *protocol* versions are only half of the issue - SSL/TLS make use of ciphers, hashes, and key exchange algorithms.

Initially, the enabled **Ciphers** only included AES (strong crypto) and in the second screenshot, Triple-DES was added. Triple-DES was/is the only required cipher in older SSL/TLS versions (I think TLS 1.2 now makes it AES and has dropped Triple-DES because it is no longer considered "secure").

Why is this important?

It's *possible*, depending on how the IMAP server is configured, that it only supports Triple-DES and not AES and so MailKit's IMAP client (which uses System.Security's SslStream) would only have AES as a supported cipher and so the client & server would be unable to negotiate a cipher that they both supported.

The other possibility is that the SslStream and the IMAP server could not agree on a key-exchange algorithm (note that Diffie-Hellman was added in the second screenshot).

**Comment by ckePriv** [comment]
Thanks for your comments. The Imap server itself runs on a linux VM. The tests were performed on unattended server VMs - on Win2016 and Win2019 as well. Some more debugging facilities on what exactly goes wrong would be appreciated - only if possible.

**Comment by jstedfast** [comment]
Most of this happens below the surface in SslStream, but I'll look into seeing if there are any helpful properties that are exposed that MailKit could poke at to provide more helpful diagnostics.
