### ISSUE TITLE
Error: Symbol indexes could not be retrieved.

### ISSUE THREAD

**Issue by Saurbaum** [jstedfast/MailKit#1239]
Nightly builds using MailKit are generating an error

  | Indexed source information could not be retrieved from D:\Dev\ClearSCADA_Project\ClearSCADA\Binaries\Win32\Release\MailKit.pdb. Error: Symbol indexes could not be retrieved.
MailKit.pdb. Error: Symbol indexes could not be retrieved.

Windows using mailkit 2.13.0 targeting .net 4.8

MSBuild error produced running under VS2019 msbuild

I saw a similar issue in another project where the pdbs were in some kind of hybrid PDB format that Visual Studio didn't know how to handle correctly.

**Comment by Saurbaum** [comment]
https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/1098 this is the other project I found them in.

**Comment by jstedfast** [comment]
Thanks, I'll try to look into this.

**Comment by jstedfast** [comment]
What I read seems to suggest that the `<DebugType>portable</DebugType>` pdb format isn't loadable by .NET Framework <= 4.7.0 but is for versions after that. Oddly, you are having issues with .NET Framework v4.8.

Maybe I can use `<DebugType>full</DebugType>` for .NET Framework versions of MimeKit/MailKit?

**Comment by jstedfast** [comment]
https://stackoverflow.com/questions/46902377/what-is-the-difference-between-using-debugtypefull-debugtype-and-debugtype

This same explanation is echoed in the link you sent me (or maybe it was a link to another discussion from the link you provided, I'm not sure).

**Comment by jstedfast** [comment]
More confirmation of what was said above: https://github.com/dotnet/sdk/issues/1238

**Comment by Saurbaum** [comment]
Much appreciated.
