### ISSUE TITLE
Is it possible to avoid logging message content?

### ISSUE THREAD

**Issue by CristinaHP** [jstedfast/MailKit#1246]
Hi, this is just a question. Sorry if it's something obvious but I'm new to Mailkit and I can´t find a way to do it. I'm creating a SmtpClient with a ProtocolLogger and I'm seeing that the full message content that I sent appears in the log.

Is it possible in some way to avoid the logging of the message and its headers? Not sure but I think its called the DATA command.

**Comment by jstedfast** [comment]
The only way to avoid this right now is if you subclass the ProtocolLogger (or implement your own IProtocolLogger) and filter it out .
When I implemented the ProtocolLogger, I saw it as more of a debugging tool than anything else, so I wanted everything.

**Comment by CristinaHP** [comment]
And is it possible to know which command is being sent, so that I can skip DATA command? Or the only way to do that is to read the stream/file in which the ProtocolLogger is writing?

**Comment by jstedfast** [comment]
You have to read the data :(
