### ISSUE TITLE
Cyrillic in Subject field of Envelope is not displayed correctly in iOS project

### ISSUE THREAD

**Issue by vzhusel** [jstedfast/MailKit#125]
When mailkit project is used in iOS project, subject field is not displaying correctly cyrillic symbols, after Fetch command.

Methods GetMessage or GetBodyParts are working fine with cyrillic.

Also I have ran unit tests with cyrillic in VS and they all working fine, problem only exists for iOS project and appears in simulator and on device.

Example of the message:
- 3 FETCH (UID 3 FLAGS (\Seen \Flagged) INTERNALDATE "28-Jan-2014 15:35:34 +0000" RFC822.SIZE 209654 ENVELOPE ("28-Jan-2014 19:35:34 +0400" "=?koi8-r?B?8NLJ18XU09TX1cXNINcg8sHNwszF0i3wz97UxSE=?=" (("=?koi8-r?B?68/Nwc7EwSDywc3CzMXSLfDP3tTZ?=" NIL "mail-news" "rambler-co.ru")) (("=?koi8-r?B?68/Nwc7EwSDywc3CzMXSLfDP3tTZ?=" NIL "mail-news" "rambler-co.ru")) (("=?koi8-r?B?68/Nwc7EwSDywc3CzMXSLfDP3tTZ?=" NIL "mail-news" "rambler-co.ru")) (("alyona testing" NIL "alyona.testing" "rambler.ru")) NIL NIL NIL "e2406527-a1c1-40c4-96a6-02f27680fdd2@mail.rambler.ru") BODYSTRUCTURE (("text" "html" ("charset" "utf-8") NIL NIL "quoted-printable" 15477 261 NIL ("inline" NIL) NIL NIL)("image" "png" ("name" "welcome-startpage.png") "4f117460-bd97-45fc-ad44-ffd5a43dacbe@mail.rambler.ru" NIL "base64" 21994 NIL ("inline" ("filename" "welcome-startpage.png")) NIL NIL)("image" "png" ("name" "welcome-section1.png") "42479f52-d842-4473-87a8-609277af1582@mail.rambler.ru" NIL "base64" 56008 NIL ("inline" ("filename" "welcome-section1.png")) NIL NIL)("image" "png" ("name" "welcome-section2.png") "cc9a35f9-0799-4095-a24c-8479bce1804e@mail.rambler.ru" NIL "base64" 48344 NIL ("inline" ("filename" "welcome-section2.png")) NIL NIL)("image" "png" ("name" "welcome-header.png") "87e4c910-5a80-434a-b19c-7e112cf21927@mail.rambler.ru" NIL "base64" 8958 NIL ("inline" ("filename" "welcome-header.png")) NIL NIL)("image" "png" ("name" "welcome-section3.png") "22d366b0-16c4-4a39-88d5-c8e68f05209b@mail.rambler.ru" NIL "base64" 56864 NIL ("inline" ("filename" "welcome-section3.png")) NIL NIL) "related" ("boundary" "_----------=_1378312441231490") NIL NIL NIL))

*Screenshot is from another email account.

![screen shot 2014-12-02 at 3 05 21 pm](https://cloud.githubusercontent.com/assets/1458920/5262987/c37860ce-7a34-11e4-89d4-65f142cb55b3.png)

**Comment by vzhusel** [comment]
I have this problem again with ISO-8859-13 encoding, which is used for Latvian language (email from gmail). I am using latest MailKit version and internalization options all turned on.

C: A00000041 UID FETCH 2455 (UID FLAGS INTERNALDATE RFC822.SIZE ENVELOPE BODYSTRUCTURE)
S: * 1943 FETCH (UID 2455 RFC822.SIZE 724 MODSEQ (393258) INTERNALDATE "27-Feb-2015 08:59:11 +0000" FLAGS (\Seen) ENVELOPE ("Fri, 27 Feb 2015 10:59:11 +0200" "=?ISO-8859-13?Q?jaut=E2jums_=EE=EE=EE=FB=FB=EC=F0?=" (("Shurik Afonin" NIL "kyleidocscabinet" "gmail.com")) (("Shurik Afonin" NIL "kyleidocscabinet" "gmail.com")) (("Shurik Afonin" NIL "kyleidocscabinet" "gmail.com")) (("Shurik Afonin" NIL "kyleidocscabinet" "gmail.com")) NIL NIL NIL "<CAPNaYUNJGXJT27NfS+qRhQKX1gNa4ZaVthYdGo_V8WDdX6zVdg@mail.gmail.com>") BODYSTRUCTURE (("TEXT" "PLAIN" ("CHARSET" "UTF-8") NIL NIL "7BIT" 12 1 NIL NIL NIL)("TEXT" "HTML" ("CHARSET" "UTF-8") NIL NIL "7BIT" 33 1 NIL NIL NIL) "ALTERNATIVE" ("BOUNDARY" "001a11c30880fe6eab05100e14c1") NIL NIL))
![screen shot 2015-02-27 at 11 33 53 am](https://cloud.githubusercontent.com/assets/1458920/6410128/d48d9ff8-be74-11e4-86e4-d44e5dd6f2fd.png)

**Comment by jstedfast** [comment]
Can you link me to the raw email message?

**Comment by jstedfast** [comment]
Are you using the MimeMessage.Subject to display the subject in your screenshot? Or are you using the MessageSummary.Envelope.Subject?

**Comment by jstedfast** [comment]
The problem is that Mono does not support ISO-8859-13 and so MimeKit tries its best to convert it anyway.

You can check this for yourself by running this program under Mono:

https://gist.github.com/jstedfast/a819e0cce183d7055204

**Comment by vzhusel** [comment]
Thank you, Jeffrey. I was using MessageSummary.Envelope.Subject
