### ISSUE TITLE
HTTPS proxy support

### ISSUE THREAD

**Issue by MaheshBGajera** [jstedfast/MailKit#1251]
I am using this library for one of my project where in I fetch emails using IMAP client and I use proxy there.
I use HttpProxyClient and it seems to be working fine but now I realise that I need my proxy to work on HTTPS not HTTP for some security reasons(my proxy credentials are not encrypted over wire).

Is there any possibility that you can support HTTPS proxy here?

OR does Socks5ProxyClient supports TLS?

Thanks

**Comment by jstedfast** [comment]
I will put this on the radar for 3.0.

The problem with trying to add this to 2.x is that the proxy needs to return a Socket rather than a Stream.

I will need to modify it to return a Stream for this to be possible.

**Comment by MaheshBGajera** [comment]
Thank a lot. Do you have any expected release date for 3.0?

**Comment by jstedfast** [comment]
I do not have an expected release date, but I've already been working toward a 3.0 release in my `vnext` branch.

**Comment by jstedfast** [comment]
I've created a GitHub Project board. Assuming you can at least view it, it should give you an idea of the progress I'm making toward v3.0.

There's also a [MimeKit 3.0](https://github.com/jstedfast/MimeKit/projects/1) board.

**Comment by jstedfast** [comment]
This is now implemented in the `vnext` branch

**Comment by MaheshBGajera** [comment]
thank you.

**Comment by jstedfast** [comment]
If you can, please test to make sure it works.

**Comment by jstedfast** [comment]
Have you tested this at all?

I'd like to make a 3.0 release but I need this tested first.

**Comment by MaheshBGajera** [comment]
I tested https proxy on nuget 3.0.0-preview1 and I am getting following exception.

> MailKit.Security.SslHandshakeException: An error occurred while attempting to establish an SSL or TLS connection.
> 
> The host name did not match the name given in the server's SSL certificate.
> 
>  ---> System.Security.Authentication.AuthenticationException: The remote certificate was rejected by the provided RemoteCertificateValidationCallback.
>    at System.Net.Security.SslStream.SendAuthResetSignal(ProtocolToken message, ExceptionDispatchInfo exception)
>    at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
>    at MailKit.Net.Proxy.HttpsProxyClient.ConnectAsync(String host, Int32 port, Boolean doAsync, CancellationToken cancellationToken)
>    --- End of inner exception stack trace ---
>    at MailKit.Net.Proxy.HttpsProxyClient.ConnectAsync(String host, Int32 port, Boolean doAsync, CancellationToken cancellationToken)
>    at MailKit.Net.Proxy.ProxyClient.ConnectAsync(String host, Int32 port, Int32 timeout, CancellationToken cancellationToken)
>    at MailKit.MailService.ConnectNetwork(String host, Int32 port, Boolean doAsync, CancellationToken cancellationToken)

**Comment by jstedfast** [comment]
MailKit v3.0.0 has been released with this feature.
