### ISSUE TITLE
Is support for bitwised-or DeliveryStatusNotification provider dependant?

### ISSUE THREAD

**Issue by papaja** [jstedfast/MailKit#1252]
This is just a question, not a bug report.

When I use bitwise or to request DeliveryStatusNotification for Success and Failure I get only Success notification but never failure. If I request only Failure I do get it.

Is this caused by my provider's server configuration related or is there something that I could configure differently.

```c#
protected override DeliveryStatusNotification? GetDeliveryStatusNotifications(MimeMessage message, MailboxAddress mailbox)
{
    return DeliveryStatusNotification.Failure | DeliveryStatusNotification.Success;
}

**Comment by jstedfast** [comment]
As far as I can tell from my reading of the spec, that's supposed to give you a delivery status notification no matter what.

https://datatracker.ietf.org/doc/html/rfc1891

**Comment by papaja** [comment]
You are right. That part of the spec seems pretty straightforward.

Just for test I used Thunderbird mail client and enabled `mail.dsn.always_request_on`. I receive both success and failure report on the same host. I hoped I could take a look at their implementation but their online Mercurial repo does not offer code search :(

**Comment by jstedfast** [comment]
Maybe Thunderbird is using `Success | Delay` ?

**Comment by papaja** [comment]
I really don't know how they do it, but this is very weird as it seems that reports depend not on my host (alone) but on receiving end.

For instance sending to Gmail from Thunderbird with `mail.dsn.always_request_on` does not return any report. This is very similar to MailKit:

- `Failure | anything` does not return any report.
- `Failure` alone returns Failure
- `Success` alone or with `Delay` returns Success report.

On the other hand sending to local provider with `Success | Delay` returns both Success and Failure report.

If someone could confirm this behavior with Gmail it would mark this question as not resolvable but closed :)

**Comment by jstedfast** [comment]
smtp.gmail.com doesn't support DNS, that's why it doesn't work.

**Comment by papaja** [comment]
I am not sending through smtp.gmail.com. I am sending from *me*@*myisp*.net through smtp.*myisp*.net to *me*@gmail.com.
- `return DeliveryStatusNotification.Failure;` works
- `return DeliveryStatusNotification.Success;` works
- Combinations do not work.

I am totally puzzled after your last reply :)

**Comment by jstedfast** [comment]
Oh, I misunderstood - sorry.

**Comment by jstedfast** [comment]
Can you try using the latest CI build? (or building from master)

I wonder if the issue is lack of an `ORCPT` parameter in the `RCPT TO` command(s)?

**Comment by papaja** [comment]
I have just tried 2.15.0.190. Is that the last one?

Same behavior. `DeliveryStatusNotification.Failure` works when alone. 

In any combination no Failure report is returned when sending from local provider, which supports DSN, to gmail and outlook addresses. Thunderbird works the same.

**Comment by jstedfast** [comment]
This is sounding more like a server bug then.

If you look at the smtp protocol logs, it sets the NOTIFY= parameters that you are specifying, right? I'm pretty sure it must be because there are unit tests for that.

**Comment by papaja** [comment]
Maybe it is server bug. I am willing to try on another server. Do you know of free email provider which supports DSN?

From log:
`C: RCPT TO:<somewrongaddress@outlook.com> NOTIFY=SUCCESS,FAILURE ORCPT=rfc822;somewrongaddress@outlook.com`

**Comment by jstedfast** [comment]
That looks correct.

Unfortunately I haven't kept tabs on what email servers support which features, so I don't have that information handy.
