### ISSUE TITLE
Mailkit freezes sometimes at ImapClient.Disconnect(...)

### ISSUE THREAD

**Issue by hansmelin** [jstedfast/MailKit#1253]
**Describe the bug**
I use mailkit to connect to various imap accounts, poll them once a minute 24/7, download the messages, delete them, then purge and at last I disconnect.

I have had this problem a long time through many versions of Mailkit and right now I use **v2.11.1**

This works 99.99% of the times, but once in a while The code freezes at `ImapClient.Disconnect(bool quit, CancellationToken cancellationToken = default(CancellationToken))`

I call the method with:

``` 
  // client.Timeout = 3 * 60 * 1000;
  // cancellationToken.IsCancellationRequested == false
  imapClient.Disconnect(true, cancellationToken);
```

I have taken a dump file when my program has hanged and what I see is the code has freezed at 
`System.Net.Sockets.Socket:3072` in method `public bool Poll(int microSeconds, SelectMode mode)`

```
3072   if (socketCount == -1)
3073   {
3074        SocketException socketException = new SocketException();
```

If I backtrace the calls stack I come to `Mailkit.Net.NetworkStream:248` in method `Poll` => `cancellationToken.ThrowIfCancellationRequested();`

```
public void Poll(SelectMode mode, CancellationToken cancellationToken)
{
	if (cancellationToken.CanBeCanceled)
	{
		do
		{
			cancellationToken.ThrowIfCancellationRequested();
		}
		while (!Socket.Poll(250000, mode));
		cancellationToken.ThrowIfCancellationRequested();
	}
}
```

And at last at`ImapClient:861` and method `Disconnect` and when I 

```
public override void Disconnect(bool quit, CancellationToken cancellationToken = default(CancellationToken))
{
	DisconnectAsync(quit, doAsync: false, cancellationToken).GetAwaiter().GetResult();
}
```

**Platform (please complete the following information):**
 - OS: Windows 2016
 - .NET Framework: .NET 4.8
 - MailKit Version: v2.11.1

**Exception**
No exception. The program freezes.

**To Reproduce**
Not reproducible in test code.

**Screenshots**
Call stack:
![image](https://user-images.githubusercontent.com/856263/132186262-486b367e-d2da-40e3-89c0-42ea8a09c57c.png)

**Protocol Logs**
Not possible. Not reproducible in test code.

**Comment by jstedfast** [comment]
It's waiting for a response from the server, which I'm guessing the server never sends?

This is what the cancellationToken is for :)

Are you saying that it spins in that loop for longer than 3 minutes (3 * 60 * 1000)?

**Comment by hansmelin** [comment]
Yes, that is how I thought it would work. But it spins in that loop forever and does not respect the timeout setting. But as I said this only happens very, very seldom. But I experience the problem against various IMAP server implementations. But it is impossible to reproduce this in a test.

I host the code in a Windows service powered by Topshelf. The Mailkit code runs in a separate thread instantiated with `System.Threading.Tasks.Task` to which I pass the `CancellationToken`. 

In the main thread I listen to the Stop event of the service and cancel the `CancellationTokenSource`. This works without any problems, except in these rare occasions. Then the Windows services UI times out when trying to stop the service.  All I can do then is to kill the process.

**Comment by jstedfast** [comment]
Note that a hang in Socket.Poll() (which is used by my NetworkStream.Poll method) is supposed to timeout after 1/4 second which should return to the do-while loop in NetworkStream.Poll() which will check the cancellationToken for a cancel event. If the cancellationToken is cancelled, then it should immediately throw and exit the NetworkStream.Poll().

You say that isn't happening, though, which suggests that it's actually hanging in Socket.Poll() which is in .NET's libraries, so the following fix probably won't work, but maybe it's worth a try?

```csharp
public void Poll (SelectMode mode, CancellationToken cancellationToken)
{
	const int oneQuarterSecond = 250000;

	if (!cancellationToken.CanBeCanceled)
		return;

	int timeout = mode == SelectMode.SelectWrite ? WriteTimeout : ReadTimeout;
	int elapsed = 0;

	do {
		cancellationToken.ThrowIfCancellationRequested ();

		// wait 1/4 second and then re-check for cancellation
		if (Socket.Poll (oneQuarterSecond, mode))
			break;

		cancellationToken.ThrowIfCancellationRequested ();

		if (timeout != Timeout.Infinite) {
			int remainder = int.MaxValue - elapsed;

			if (remainder < oneQuarterSecond || (elapsed += oneQuarterSecond) >= timeout)
				throw new TimeoutException ();
		}
	} while (true);

	cancellationToken.ThrowIfCancellationRequested ();
}
```

Please add logging to that to verify that the TimeoutException gets hit (it might not bubble up to your application as a TimeoutException, in fact, I think Disconnect() swallows exceptions so you likely won't get an exception at all).

Before I merge that code to MailKit, I'd like confirmation that it's working.

If it's actually hanging in the Socket.Poll(), then a different solution will be needed...

**Comment by hansmelin** [comment]
Thanks!

I will test your suggested implementation side by side with the current and see if it works.

Note that it might take weeks until the problem occurs and I have some clue if the fix will help.

**Comment by jstedfast** [comment]
that's fine

**Comment by jstedfast** [comment]
Any new updates? If not, I'm going to close this for the time being. You (or I) can reopen it if/when you get the needed information.

**Comment by hansmelin** [comment]
Sorry, I did not see your comment. I have continued to run both versions side by side and have not had this issue at all.

What I will try from now is to on only run the production code (MailKit 2.15.1) to see if I the problem occurs.

Or do you recommend me to try 3.0.0 instead?

**Comment by jstedfast** [comment]
3.0.0 would not fix this issue (all that code has not changed), so it's not worth trying 3.0.0 in that sense.
