### ISSUE TITLE
Add support for getting the custom keywords listed in the [FLAGS] and [PERMANENTFLAGS] response-codes

### ISSUE THREAD

**Issue by Danyfirex** [jstedfast/MailKit#1256]
My question may be simple, but I read documentation and also google it too much and I don't find a solution. 

I'm needing to have get  FLAGS   and PERMANENTFLAGS. 

This is my actual code.

```powershell
$client = New-Object MailKit.Net.Imap.ImapClient([mailkit.protocollogger]::new($PSScriptRoot+"\imap.log"))
#$client = New-Object MailKit.Net.Imap.ImapClient
$client.Connect($mailserver,143,[MailKit.Security.SecureSocketOptions]::StartTls)
$client.Authenticate($username, $password)
$inbox = $client.Inbox
$inbox.Open([MailKit.FolderAccess]::ReadWrite)
$client.Disconnect($true);
```

What I need:
```
S: * FLAGS (\Answered \Flagged \Deleted \Seen \Draft NonJunk 1._test 1._test 2._test 3._test 5._test Junk $label1 $label2)
S: * OK [PERMANENTFLAGS (\Answered \Flagged \Deleted \Seen \Draft NonJunk 1._test 1._test 2._test 3._test 5._test Junk $label1 $label2 \*)] Flags permitted.
```

I've notice that the protocollogger has the keywords/strings I need. but I have not found a property or method that return that list to me.  is it available? or at least an string where I can parse them later.

Thank you.
Regards

**Comment by jstedfast** [comment]
You want the [AcceptedFlags](http://www.mimekit.net/docs/html/P_MailKit_MailFolder_AcceptedFlags.htm) and [PermanentFlags](http://www.mimekit.net/docs/html/P_MailKit_MailFolder_PermanentFlags.htm) properties of the folder.

So:

```pwsh
$Flags = $inbox.AcceptedFlags
$PermanentFlags = $inbox.PermanentFlags
```

**Comment by Danyfirex** [comment]
I already tried that two properties, but they don't show all keywords it seems to return some default ones. 

```powershell
$client = New-Object MailKit.Net.Imap.ImapClient([mailkit.protocollogger]::new($PSScriptRoot+"\imap.log"))
#$client = New-Object MailKit.Net.Imap.ImapClient
$client.Connect($mailserver,143,[MailKit.Security.SecureSocketOptions]::StartTls)
$client.Authenticate($username, $password)
$inbox = $client.Inbox
$inbox.Open([MailKit.FolderAccess]::ReadWrite)
$Flags = $inbox.AcceptedFlags
$PermanentFlags = $inbox.PermanentFlags
Write-Host $Flags
Write-Host $PermanentFlags
$client.Disconnect($true);
```

Output:
```
Seen, Answered, Flagged, Deleted, Draft
Seen, Answered, Flagged, Deleted, Draft, UserDefined
```

**Comment by Danyfirex** [comment]
is there an alternative? or a way to get the base stream like logger does to parse it myself.

**Comment by jstedfast** [comment]
Can I ask why you need them? Knowing what custom keywords have been used in the folder isn't generally useful because unless you created the keyword, you wouldn't know how to interpret them.

All that is really needed is to know that user-defined keywords can (or can't) be stored in the folder.

**Comment by Danyfirex** [comment]
I actually have many keywords. (My account is shared with some coworkers) so it may be possible that they add new keywords etc. So I want to get the list of keywords to count mails within the keywords.

So I would have something like this at the end.

```powershell
$client = New-Object MailKit.Net.Imap.ImapClient([mailkit.protocollogger]::new($PSScriptRoot+"\imap.log"))
#$client = New-Object MailKit.Net.Imap.ImapClient
$client.Connect($mailserver,143,[MailKit.Security.SecureSocketOptions]::StartTls)
$client.Authenticate($username, $password)
$inbox = $client.Inbox
$inbox.Open([MailKit.FolderAccess]::ReadWrite)
$keywords=$inbox.PermanentFlags

foreach($keyword in $keywords){
	$uids = $Inbox.Search([MailKit.Search.SearchQuery]::HasKeyword($keyword));
	Write-Host "Mails with keyword " $keyword $uids.Count	
}

```

**Comment by jstedfast** [comment]
It's not a bug, but it is a feature request.

Your use-case is very non-typical.

> shouldn't $inbox.PermanentFlags return the string list I want?

It can't because it's an enum.

**Comment by Danyfirex** [comment]
In the meanwhile can I get the main stream returned from the Inbox without using the protocollogger?

**Comment by jstedfast** [comment]
The only way to do that would be to supply your own ProtocolLogger - then you'd have full access to all of the data

**Comment by Danyfirex** [comment]
Thank you very much. here is my alternative solution by now.

```powershell
$Stream = New-Object System.IO.MemoryStream
$client = New-Object MailKit.Net.Imap.ImapClient([mailkit.protocollogger]::new($Stream))
$client.Connect($mailserver, 143, [MailKit.Security.SecureSocketOptions]::StartTls)
$client.Authenticate($username, $password)
$inbox = $client.Inbox
$inbox.Open([MailKit.FolderAccess]::ReadWrite)
$sStream = [System.Text.Encoding]::UTF8.GetString($logStream.ToArray())
$AcceptedKeywords = [regex]::match($sStream, "\* FLAGS \((.*)\)").Groups[1].Value.Split(' ')
$PermanentKeywords = [regex]::match($sStream, "\* OK \[PERMANENTFLAGS \((.*)\\\*\)").Groups[1].Value.Split(' ')
Write-Host $AcceptedKeywords
Write-Host $PermanentKeywords
$client.Disconnect($true);

```

thank you again. You rock

**Comment by jstedfast** [comment]
I took a quick look at the code and it was already parsing those values and saving them into a HashSet<string>, I just needed properties to set them on.

Quick fix.

**Comment by jstedfast** [comment]
MailKit v3.0.0 has been released with this feature.
