### ISSUE TITLE
Add a MailKitLite package to avoid dependency on BouncyCastle

### ISSUE THREAD

**Issue by DierkDroth** [jstedfast/MailKit#1257]
I found that the BouncyCastly assembly adds significant size to my distribution package. This could become a serious issue as I'm using MimeKit/MailKit with the [Platform UNO](https://platform.uno/) technology, where basically .NET code is 'transformed' to WebAssembly, Droid/Java, iOS ... code which includes not only my application code but any assembly referenced. Download size, startup time etc. needed to be considered...

That's why I'm trying to keep my 'app package' lean as possible.

- Is there any way I could exclude BouncyCastle from my package?
- If so, what would be implications?

Thanks in advance

**Comment by DierkDroth** [comment]
Sounds good. Thx @jstedfast

**Comment by jstedfast** [comment]
Fixed with commit 2c8fca1efd8f9d0f44108171484db604e1c819ce

v3.0 will have a MailKitLite build.
