### ISSUE TITLE
Any way to retrieve the response string from an SMTP Send command?

### ISSUE THREAD

**Issue by ebekker** [jstedfast/MailKit#126]
I appears all the Send method variations on [SmtpClient](http://jstedfast.github.io/MailKit/docs/MailKit.Net.Smtp/SmtpClient.html) don't return anything, so I was wondering if there was any way to retrieve the response details for a Send operation.  Specifically, I'm working one particular SMTP provider (AWS SES) that send back a Message ID in the SMTP 250 response string so that you use that ID in future operations (like status checks, message tracking, etc.).

Is there any way to extract the response string in the Send command to get at this info?  I found other libraries in other platforms, provide this functionality out of the box, but it seems abstracted away or intentionally hidden in both MailKit and the native .NET SMTP client.

**Comment by kevinneufeld** [comment]
ebekker,  

I in the same situation, I would like to get a response back from the server ESP.  I am wondering if you could share how you implemented this.

**Comment by ebekker** [comment]
@jstedfast added the `OnMessageSent()` which you can override in a subclass, and it will pass you back the data received.

**Comment by krylor** [comment]
ebekker,

Is it possible to get an working example of  handling the MessageSent event?.

http://www.mimekit.net/docs/html/E_MailKit_MailTransport_MessageSent.htm

**Comment by Silly-V** [comment]
I want to know how to 'listen' to the MessageSent event.

**Comment by jstedfast** [comment]
You'd use it the same way you'd use any other event in .NET...

```csharp
void OnMessageSent (object sender, MessageSentEventArgs e)
{
    Console.WriteLine ("The message was sent!");
}

void SendMessage (MimeMessage message, string host, int port, string username, string password)
{
    using (var client = new SmtpClient ()) {
        client.Connect (hostname, port, SecureSocketOptions.Auto);
        client.Authenticate (username, password);

        client.MessageSent += OnMessageSent;
        client.Send (message);

        client.Disconnect (true);
    }
}
```

**Comment by Silly-V** [comment]
Oh, okay- thank you so much! So, I was wondering, is an exception thrown in case the message is sent to an address that does not exist ?

**Comment by jstedfast** [comment]
Yes. Read the documentation.

**Comment by Silly-V** [comment]
Will do. Thanks!

**Comment by mehardik** [comment]
Hi...I have a project requirement where I need to prepare some kind of dashboard which shows how many recipients have read the email. Till now I was able to display Read Receipt dialog in Outlook and receive a mail which shows all the details that who have read our email. But in order to show all these details on a separate page, I need to store them in a database. Do we have any event where I can call a method to insert the record in the database.

**Comment by jstedfast** [comment]
@mehardik I don't understand the question. Are you hoping to have an event on SmtpClient during the `Send` process that you can hook into in order to save something to your database?

**Comment by hefhem** [comment]
I'm using a multi tenant database and I would like to log mail not sent in a table so as to retry. OnMessageSent would have work for me but I need a way to send additional parameter into the method.

**Comment by Samra10** [comment]
I tried another solution to get the ID of the message sent with SMTP Client, to trace any replied messages.

Before you send your message add a hidden ID property to the message headers,
`               `Guid objGuid = new Guid();
                objGuid = Guid.NewGuid();
                // save the generated ID on a local var to later use
                String messageIdentity = objGuid.ToString();
                Console.WriteLine(messageIdentity);
                message.Headers.Add("Identity", `messageIdentity);`

Now continue and send your message,
Wait about 10 Seconds, Then you will use the **IMAP** Client to get your Sent folder and for each message in your folder,
loop over the message headers and check if anyone of them is ==`messageIdentity `, now you catch your 
sent message successfully and get any information about it you wand like ID etc...

**Comment by jstedfast** [comment]
@hefhem I would recommend subclassing SmtpClient so that you can have access to whatever parameters you need inside of the OnMessageSent method.

@Samra10 You seem to be more-or-less just duplicating the functionality of the Message-Id header?
