### ISSUE TITLE
Getting MailKit.Net.Imap.ImapProtocolException at client.Authentication in all other consumers except one.

### ISSUE THREAD

**Issue by AksharGanatra** [jstedfast/MailKit#1262]
MailKit.Net.Imap.ImapProtocolException is throwed by consumers
I have a producer-consumer setup, in which there can be more than one consumers. All consumers should connect and authenticate and then perform operations.
But the problem I am facing is while my project runs with AOL server, consumers throw this error, but one consumer run without any error. I am not sure if this is a mailkit problem or AOL .

**Platform (please complete the following information):**
 - OS:  Windows
 - .NET Framework: NET 4.5
 - MailKit Version: 2.15

**Exception**
--MailKit.Net.Imap.ImapProtocolException: IMAP4rev1 Server logging out
   at MailKit.Net.Imap.ImapEngine.<IterateAsync>d__175.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at MailKit.Net.Imap.ImapEngine.<RunAsync>d__176.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MailKit.Net.Imap.ImapEngine.<QueryCapabilitiesAsync>d__182.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at MailKit.Net.Imap.ImapClient.<AuthenticateAsync>d__102.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MailKit.Net.Imap.ImapClient.Authenticate(Encoding encoding, ICredentials credentials, CancellationToken cancellationToken)
   at MailKit.MailService.Authenticate(Encoding encoding, String userName, String password, CancellationToken cancellationToken)
   at MailKit.MailService.Authenticate(String userName, String password, CancellationToken cancellationToken)
   at InfinniumIMAPConsumer.Business.MailkitWorker.Connect(). ,(:0)--.

1. You need a producer, consumer setup
2. All consumers should connect and authenticate with same credentials and at same time.
3. say if there are 3 consumers 1 will run smooth others will throw above exception.

All consumers should be able to authenticate at the same time and fetch folders and mails at the same time.

Code written in each cosnumer for conenction and authentication.
```csharp
                  try
                    {
                        iMapClient.Connect(hostName, (port == 0) ? 993 : port, securityOptions);
                    }
                    catch (Exception ex)
                    {
                        ProcessLogger.Error($"Error While Connecting to server .{ex} ");
                        throw ex;
                    }
                    if (!iMapClient.IsAuthenticated)
                    {
                        try
                        {
                            iMapClient.Authenticate(userName, password);
                        }
                        catch (Exception ex)
                        {
                            ProcessLogger.Error($"Error While Authenticating to server {ex}. ");
                            //throw ex;
                        }
                    }
```

**Comment by jstedfast** [comment]
The server is closing the connect with the following message: `"IMAP4rev1 Server logging out"`

AOL obviously doesn't want you to open more than 1 connection.

**Comment by AksharGanatra** [comment]
Is there any way other way I can make this work, because it works fine with Gmail, Yahoo, Outlook.
And making AOL work in same fashion is important to me.

**Comment by AksharGanatra** [comment]
Okayy, Thanks for Your reply.

**Comment by AksharGanatra** [comment]
@jstedfast this is working with aspose.dll.

**Comment by jstedfast** [comment]
Can you get some protocol logs from MailKit and some protocol logs from Aspose so we can inspect the differences?

I mean, if the server is closing the connection, I'm not sure how Aspose could possibly be working unless you are just mistaken.

**Comment by AksharGanatra** [comment]
in this setup, when there are more than one program which will access same file, it is throwing error something like this : compiler is unable to open the file as it is shared with other consumer.

**Comment by jstedfast** [comment]
You can just log to different files.

**Comment by jstedfast** [comment]
Did you manage to get any logs that can be looked at to see what is happening?
