### ISSUE TITLE
SearchQuery.SentSince not working as expected

### ISSUE THREAD

**Issue by AksharGanatra** [jstedfast/MailKit#1263]
I am passing SearchQuery.SentSince(Date format till seconds precision) but it does not give me a proper result, it is giveing me messages after that date - (dd) but it is not considering minutes and seconds (mm:ss)

 - OS: . Windows

 - .NET Framework: NET 4.5
 - MailKit Version: 2.15

No exception

Use SearchQuery.SentSince

I want to fetch mails after say 9/24/2021 3:53:12 PM, When I pass this date, it is currently giving me all the mails after 24 th sept 00:00:00 but I strictly want mails after 9/24/2021 3:53:12 PM.

Can anyone Please Help me ?
if this is the way how it works, please give me an alternative to achieve minutes and seconds precision.

**Comment by jstedfast** [comment]
That's just how the IMAP protocol works, unfortunately.

From [rfc3501, section 6.4.4](https://datatracker.ietf.org/doc/html/rfc3501#section-6.4.4):
```
      SENTSINCE <date>
         Messages whose [RFC-2822] Date: header (disregarding time and
         timezone) is within or later than the specified date.
```

The simplest solution is to use the search to get close, and then do client-side filtering of the results.

For example:

```csharp
var uids = folder.Search (SearchQuery.SentSince (dateTime));
var summaries = folder.Fetch (uids, MessageSummaryItems.Envelope | ...).Where (x => x.Envelope.Date >= dateTime);
```

**Comment by AksharGanatra** [comment]
Ohh thank you so much, it worked. However SearchQuery was not fully utilized but obviously it filters other mails. 
Thanks for your Quick reply. You people are doing fabulous job.

**Comment by jstedfast** [comment]
It's only me, but thanks :)

**Comment by AksharGanatra** [comment]
I had one more question does using iMesasgeSummary item.internaldate gives minute and seconds precision ?

**Comment by jstedfast** [comment]
yes

**Comment by AksharGanatra** [comment]
Thanks bro! You are one man army.
