### ISSUE TITLE
Is there a point in using DecodeToAsync() or WriteToAsync() for MimeMessage?

### ISSUE THREAD

**Issue by SpiritBob** [jstedfast/MailKit#1264]
The underlying streams that are being used are either a good old `MemoryStream`, or a `MemoryBlockStream` for the contents of a `MimeMessage`..

If I've correctly understood that, both of those variants do sync-over-async for their `async` methods, which the rest of the `MimeKit` library ends up using by wrapping those streams in other kinds of streams, like a `FilteredStream`?

**Comment by jstedfast** [comment]
Async IO methods don't just apply to the MemoryStream/MemoryBlockStream input data, it *also* applies to the output stream.

So if you do a WriteAsync() to a NetworkStream or an SslStream, that immediately has value even if the message body parts are all using MemoryStreams or MemoryBlockStreams.

Same for DecodeToAsync().

Obviously if you are writing the message or decoding the content of a MimePart to a memory stream, then Async is likely overhead that doesn't gain you anything.
