### ISSUE TITLE
5.7.1 Client was not authenticated error using Mailkit when connecting on port 25

### ISSUE THREAD

**Issue by saurabhb-optimus** [jstedfast/MailKit#1265]
Below is the telnet session information:

![image](https://user-images.githubusercontent.com/37896739/136194042-a4d037fc-dc4c-4199-b59f-c053c81a8ac0.png)
This means that the Exchange receive connectors are configured correctly; Also this relay is used by dozens of other applications

But When I try to send email using below code:

`SmtpHost.Connect(Server, Port, SecureSocketOptions.None)`
 `Dim msg As New MailMessage()`
    `Try`
      `  msg.From = New MailAddress(Me.from)`
       ` msg.Subject = Subject`
      `  RecipientList = RecipientList.Replace(",", ";")`
        `Dim recipients As String() = RecipientList.Split(";")`
      `  For Each recipient As String In recipients`
           ` msg.To.Add(recipient)`
        `Next`
      `  msg.Body = Body`
      `  Me.SmtpHost.Send(Message)`
   ` Catch ex As Exception`
        // Exception Handling code 
   ` Finally`
     `   msg.Dispose()`
     `   msg = Nothing`
 `   End Try`

I get the below error:

`5.7.1 Client was not authenticated `

I also verified that Anonymous was enabled here: Exchange Management Console > Server Configuration > Hub Transport > Default Receive Connector > Properties as several articles online pointed to that as being the issue.

**Platform (please complete the following information):**
 - OS: Windows
 - MailKit Version: 2.8.0.0

**Comment by jstedfast** [comment]
I'm on a phone right now so I can't easily provide you with any detailed explanation. Luckily I already wrote a detailed explanation in the FAQ, so I would recommend reading that.

**Comment by saurabhb-optimus** [comment]
> I'm on a phone right now so I can't easily provide you with any detailed explanation. Luckily I already wrote a detailed explanation in the FAQ, so I would recommend reading that.

@jstedfast Thanks for the response. I was able to get pass through that error by going through the FAQ response from you.

However, I am still getting the same error with the StartTls and now I am again at my original error.

Below are the SMTP logs:

Connected to smtp://Server:25/
S: 220 SCSMX10P.Server Microsoft ESMTP MAIL Service ready at Wed, 20 Oct 2021 10:43:52 -0400
C: EHLO [172.16.33.62]
S: 250-SCSMX10P.Server Hello [172.16.33.62]
S: 250-SIZE 10485760
S: 250-PIPELINING
S: 250-DSN
S: 250-ENHANCEDSTATUSCODES
S: 250-STARTTLS
S: 250-X-ANONYMOUSTLS
S: 250-AUTH NTLM
S: 250-X-EXPS GSSAPI NTLM
S: 250-8BITMIME
S: 250-BINARYMIME
S: 250-CHUNKING
S: 250-XEXCH50
S: 250-XRDST
S: 250 XSHADOW
C: MAIL FROM:<FromEmail> SIZE=106374
C: RCPT TO:<ToEmail>
S: 530 5.7.1 Client was not authenticated
Connected to smtp://Server:25/
S: 220 SCSMX10P.Server Microsoft ESMTP MAIL Service ready at Wed, 20 Oct 2021 10:45:01 -0400
C: EHLO [172.16.33.62]
S: 250-SCSMX10P.Server Hello [172.16.33.62]
S: 250-SIZE 10485760
S: 250-PIPELINING
S: 250-DSN
S: 250-ENHANCEDSTATUSCODES
S: 250-STARTTLS
S: 250-X-ANONYMOUSTLS
S: 250-AUTH NTLM
S: 250-X-EXPS GSSAPI NTLM
S: 250-8BITMIME
S: 250-BINARYMIME
S: 250-CHUNKING
S: 250-XEXCH50
S: 250-XRDST
S: 250 XSHADOW
C: MAIL FROM:<MailFrom> SIZE=106374
C: RCPT TO:<Mail To>
S: 530 5.7.1 Client was not authenticated
Connected to smtp://Server:25/
S: 220 SCSMX10P.Server Microsoft ESMTP MAIL Service ready at Wed, 20 Oct 2021 10:47:25 -0400
C: EHLO [172.16.33.62]
S: 250-SCSMX10P.Server Hello [172.16.33.62]
S: 250-SIZE 10485760
S: 250-PIPELINING
S: 250-DSN
S: 250-ENHANCEDSTATUSCODES
S: 250-STARTTLS
S: 250-X-ANONYMOUSTLS
S: 250-AUTH NTLM
S: 250-X-EXPS GSSAPI NTLM
S: 250-8BITMIME
S: 250-BINARYMIME
S: 250-CHUNKING
S: 250-XEXCH50
S: 250-XRDST
S: 250 XSHADOW
C: MAIL FROM:<Mail From> SIZE=106374
C: RCPT TO:<Mail To>
S: 530 5.7.1 Client was not authenticated


Its hard for me to understand the reason for this as dozens of other applications are using the same server to send emails anonymously.

@jstedfast Can you please assist me and let me know what might be the possible reason for this ` 5.7.1 Client was not authenticated` error?

What can be done to pass this error?

**Comment by jstedfast** [comment]
The only way to get past that is to authenticate.

If the server says you need to authenticate, then there's no way to bypass it.

**Comment by saurabhb-optimus** [comment]
> The only way to get past that is to authenticate.
> 
> If the server says you need to authenticate, then there's no way to bypass it.

@jstedfast Based on your previous responses, I did the library upgrade and updated the code to something like below:

`SmtpHost.Connect(Server, 25, SecureSocketOptions.StartTls)`
`SmtpHost.Authenticate(New SaslMechanismNtlm (New Net.NetworkCredential(txtUser.Text, txtPassword.Text)))`

but still we were not able to send email successfully. Below are the smtp.log


Connected to smtp://Server:25/?starttls=always
S: 220 SCSMX10P.Server Microsoft ESMTP MAIL Service ready at Thu, 9 Dec 2021 13:38:43 -0500
C: EHLO [172.16.33.187]
S: 250-SCSMX10P.Server Hello [172.16.33.187]
S: 250-SIZE 10485760
S: 250-PIPELINING
S: 250-DSN
S: 250-ENHANCEDSTATUSCODES
S: 250-STARTTLS
S: 250-X-ANONYMOUSTLS
S: 250-AUTH NTLM
S: 250-X-EXPS GSSAPI NTLM
S: 250-8BITMIME
S: 250-BINARYMIME
S: 250-CHUNKING
S: 250-XEXCH50
S: 250-XRDST
S: 250 XSHADOW
C: STARTTLS
S: 220 2.0.0 SMTP server ready
C: EHLO [172.16.33.187]
S: 250-SCSMX10P.Server Hello [172.16.33.187]
S: 250-SIZE 10485760
S: 250-PIPELINING
S: 250-DSN
S: 250-ENHANCEDSTATUSCODES
S: 250-AUTH NTLM LOGIN
S: 250-X-EXPS GSSAPI NTLM
S: 250-8BITMIME
S: 250-BINARYMIME
S: 250-CHUNKING
S: 250-XEXCH50
S: 250-XRDST
S: 250 XSHADOW
C: AUTH NTLM TlRMTVNTUAABAAAAB4IIogAAAAAoAAAAAAAAACgAAAAGAvAjAAAADw==
S: 334 TlRMTVNTUAACAAAADAAMADgAAAAFgomi+HYRer5cKVoAAAAAAAAAAMQAxABEAAAABgGxHQAAAA9QAFUAQgBMAEkAQwACAAwAUABVAEIATABJAEMAAQAQAFMAQwBTAE0AWAAxADAAUAAEACYAYwBpAHQAeQAuAGsAaQBuAGcAcwB0AG8AbgAuAG8AbgAuAGMAYQADADgAcwBjAHMAbQB4ADEAMABwAC4AYwBpAHQAeQAuAGsAaQBuAGcAcwB0AG8AbgAuAG8AbgAuAGMAYQAFACYAYwBpAHQAeQAuAGsAaQBuAGcAcwB0AG8AbgAuAG8AbgAuAGMAYQAHAAgAdo8H/yvt1wEAAAAA

I am not able to understand what is causing this issue with MailKit library and why we are not able to send emails. This issue is getting us in trouble now. Can you please help me and let me know in case I am missing anything here?

I also tried below code but then it resulted in exception as shown in the screenshot below:

`SmtpHost.Connect(Server, port, SecureSocketOptions.StartTls)`
`SmtpHost.Authenticate (New SaslMechanismNtlm (New Net.NetworkCredential))`

<img width="227" alt="image" src="https://user-images.githubusercontent.com/37896739/145562312-71383844-3948-49f0-b292-11475c285a29.png">

It would be great if you could even let me know the direction that I should approach this problem?

Looking forward for your response

Thanks in advance.

**Comment by jstedfast** [comment]
Try this:

```csharp
SmtpHost.Connect(Server, 25, SecureSocketOptions.StartTls)
SmtpHost.Authenticate(New SaslMechanismLogin (txtUser.Text, txtPassword.Text))
```
