### ISSUE TITLE
Exchange 2010 and MailKit

### ISSUE THREAD

**Issue by Saurbaum** [jstedfast/MailKit#1268]
I had a report of someone trying to use my application to send an email to an Exchange 2010 server.

Apparently all security is disabled and I can't connect to the server myself because it's hidden from external access.

They did provide a couple of wireshark logs

Here's my application which appears to stop communicating after receiving Sender OK

![Geo SCADA wireshark](https://user-images.githubusercontent.com/7288848/136520523-6f0e1c15-c2d7-42dc-8e38-7feef7a39d0e.png)

And here's some other mail client that they connected

![Other app wireshark](https://user-images.githubusercontent.com/7288848/136520691-8cdec63d-4826-4b3e-b51c-c9cb53348fea.png)

The only difference I can see if that mailkit includes the size in the MAIL FROM but I'm not sure why that would cause an issue.

**Comment by jstedfast** [comment]
I don't think the SIZE=... caused a problem either since the server responded with `250` (which means "OK").

My first suspicion is a timeout since I can't think of a reason that the RCPT TO command would not send other than a timeout.

I can't think of any reason it would just stop after sending MAIL FROM.

What version of MailKit is this?

**Comment by Saurbaum** [comment]
I believe it's 2.14.0

**Comment by jstedfast** [comment]
Try disabling PIPELINING and maybe SIZE:

```csharp
client.Capabilities &= ~(SmtpCapabilities.Pipelining | SmtpCapabilities.Size);
```

**Comment by jstedfast** [comment]
I'm going to close this for now, but if you get more information, please reopen with the new info and I will look into this more.

**Comment by Saurbaum** [comment]
I finally got some time to investigate this some more.

Here's the protocol log which doesn't show me an awful lot but at first glance appears that the last communication on it was done by the server.
[smtp_protocol.log](https://github.com/jstedfast/MailKit/files/8552667/smtp_protocol.log)

I also did a log to capture the exceptions 

`2022-04-22 09:23:29.8184|INFO|MailKitTest.MailSender|System.IO.IOException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond ---> System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
   at System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   at MailKit.Net.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   --- End of inner exception stack trace ---
   at MailKit.Net.Smtp.SmtpClient.<FlushCommandQueueAsync>d__80.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at MailKit.Net.Smtp.SmtpClient.<SendAsync>d__131.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MailKit.Net.Smtp.SmtpClient.Send(FormatOptions options, MimeMessage message, CancellationToken cancellationToken, ITransferProgress progress)
   at MailKit.MailTransport.Send(MimeMessage message, CancellationToken cancellationToken, ITransferProgress progress)
   at MailKitTest.MailSender.SendEmail()`

The server named in the logs is annoyingly inaccessible from the outside world so any tests I'm doing have to round trip through a support team into the customer and then I get the logs back.

I've been assured that they can send emails using other mail clients. Connection is unencrypted and does not require authentication. I tried with an internal smtp server and it works fine here.

The apparently have also updated to a slightly less out of date version of Exchange (2016).

I gave them a test application where I turned off the Pipelining and Size capability and it didn't make a difference.

I'm going to move the test client up to the latest version of MailKit today and I'll see if somthing in there solves all my problems. Otherwise do you have anything more to suggest I try or more logging to enable?

**Comment by jstedfast** [comment]
Here's the relevant bit in the log:

```
C: MAIL FROM:<xxx@yyy.com> SIZE=264
C: RCPT TO:<zzz@abc.com>
S: 250 2.1.0 Sender OK
```

MailKit hangs waiting for the response to the `RCPT TO` command and eventually times out (hence the IOException).

The `250 2.1.0 Sender OK` is the response to the `MAIL FROM` command.

**Comment by Saurbaum** [comment]
Any suggestion on what to try next?

**Comment by jstedfast** [comment]
Disabling PIPELINING is the only thing I can suggest, but you said that didn't work either?

```csharp
client.Connect (...);
client.Authenticate (...);
client.Capabilities &= ~SmtpCapabilities.Pipelining;
client.Send (message);

**Comment by Saurbaum** [comment]
Correct this test was done without PIPELINING and SIZE

**Comment by jstedfast** [comment]
The logs definitely show MailKit using PIPELINING, so maybe you didn't disable it correctly?

**Comment by Saurbaum** [comment]
I see a difference in that I am setting the capabilities before connection and you are after. While I wait for timezones to bring you online to comment I'll send off a test version and see if that's why it wasn't working.

**Comment by jstedfast** [comment]
Yea, PIPELINING needs to be disabled after connecting.

**Comment by Saurbaum** [comment]
That's done it thanks. I'll see if they can turn it off server side as well which might get it working quicker than they will accept a new build from me.
