### ISSUE TITLE
In case of timeout, NetworkStream should probably throw "TimeoutException" not "TaskCanceledException"?

### ISSUE THREAD

**Issue by alex-jitbit** [jstedfast/MailKit#1269]
**Describe the bug**

This is thrown in case of timeout. Looking at the code, it just rethrows the exception, thrown by the `timeout` cancellation token.

```
System.IO.IOException: The read operation failed, see inner exception.
 ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at MailKit.Net.NetworkStream.ReadAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
```

I spent a couple of hours trying to understand, where do I cancel the operation?! 😂 Then realized it's probably the timeout maybe? And yes, it is.

**I will send a PR later today**

**Comment by jstedfast** [comment]
MailKit v3.0.0 has been released with this feature.
