### ISSUE TITLE
Can we download the images in a Gmail message?

### ISSUE THREAD

**Issue by MrYossu** [jstedfast/MailKit#1272]
I'm using MailKit to download emails from a Gmail account. I get the inbox, then loop through all new messages as follows...

```c#
foreach (IMessageSummary msg in inboxMessages) {
  MimeMessage fullMsg = await inbox.GetMessageAsync(msg.UniqueId);
  // Save the message in the database
}
```

The messages are saved into a database as part of a bigger application, and displayed in an inbox within that application.

This all works fine, except when the message body contains an inline image (common when it was sent by another Gmail user). These are included in the message HTML as `<img>` tags, with the source for the image being something like...

```
https://mail.google.com/mail/u/0?ui=2&ik=22232ec565&attid=0.1&permmsgid=msg-f:1713343029673224947&th=17c7046866106af3&view=fimg&sz=s0-l75-ft&attbid=ANGjdJ9mdsSwaLCpvkzs_a6kV6Pbj63CIaiWN2tzikW7p4uDXdrrTqkREi3OMdaIaSMFnqCrmEYT_fw3R7wXxqMZj2o4lB_UJ2HnrAv27Hw0n4Z779TOSw78gcznsDw&disp=emb&realattid=ii_kumwa31x0
```

If you are logged in to Google, and enter that URL in your browser, the image displays fine. If you aren't, you are prompted to log in. When the user views their inbox from within our application, they are not logged in to Google, so the images don't load.

Given that when downloading, we have access to their inbox, is there a way of downloading these images as well? That way we can store them locally, and the user will be able to see them.

Thanks for any help you can give.

**Comment by jstedfast** [comment]
You could scan the message HTML for `img` tags, look at the `src` attribute and if it starts with "https://mail.google.com/mail/", for example, use an HttpClient to download the image and cache it somehow so that when you render the message, you can retrieve the images from the cache.
