### ISSUE TITLE
YaaniMail Auth Error

### ISSUE THREAD

**Issue by suleymanakilli** [jstedfast/MailKit#1274]
Hi,
I get invalid username or password error when I try to authenticate with a password that has special characters. However, I can authanticate by using simple password. 
The password I use that gives error: RhCz<y4+.*8+ua-;

Mailkit version : 2.15.0

**Comment by jstedfast** [comment]
Which type of client are you using? What authentication mechanism is being used? You will likely need to use a ProtocolLogger with the client ctor to see what is happening.
