### ISSUE TITLE
email is not sent if subject contains digits inside brackets

### ISSUE THREAD

**Issue by Umer-Mahmood** [jstedfast/MailKit#1280]
**Description**
If MimeMessage.Subject contain a string like "Email Subject (123)", the email does not go through. 

**Platform**
 - OS: Windows
 - .NET Framework: AspNetCore 5.0.0
 - MailKit Version: 2.15.0

**Exception**
No exception thrown, but email is not received on the receiver's address. 

**To Reproduce**
generate email using : 
`MimeMessage message = new MimeMessage();`
set its subject :
`message.Subject="subject (123);`
call `client.Send(message)`
**Expected behavior**
Email should arrive on receiver's address.

**Comment by jstedfast** [comment]
Not a MimeKit or MailKit bug.

You need to set a sender and recipient.

If it's still not arriving, then it's a server-side filter.
