### ISSUE TITLE
FETCH 1:6 UID -> BAD FETCH Invalid Fetch argument

### ISSUE THREAD

**Issue by ckePriv** [jstedfast/MailKit#1286]
Hi @jstedfast,

I have an issue with using the following code snippet:

`IList<IMessageSummary> itemSummaries = folder.Fetch(0, 5, MessageSummaryItems.UniqueId);`
Purpose is to get a list of UniqueIds for the first 5 messages ...
this results a "BAD FETCH Invalid Fetch argument"!

IMAP Log:
C: A00000017 SELECT Importfolder
S: * 5 EXISTS
S: * 0 RECENT
S: * OK [UNSEEN 1] Message 1 is first unseen
S: * OK [UIDVALIDITY 27] UIDs valid
S: * OK [UIDNEXT 6] Predicted next UID
S: * FLAGS (\Flagged \Seen \Answered \Deleted \Draft)
S: * OK [PERMANENTFLAGS (\Flagged \Seen \Answered \Deleted \Draft \*)] Permanent flags
S: A00000017 OK [READ-WRITE] SELECT completed
C: A00000018 **FETCH 1:6 UID**
S: A00000018 **BAD FETCH Invalid Fetch argument** 
C: A00000019 LOGOUT

Any idea how to come around this issue?

Used IMAP server:
S: * OK Domino IMAP4 Server Release 10.0.1FP6 ready Wed, 10 Nov 2021 08:58:15 +0100
C: A00000000 CAPABILITY
S: * CAPABILITY IMAP4rev1 AUTH=PLAIN LITERAL+ NAMESPACE QUOTA UIDPLUS
S: A00000000 OK CAPABILITY completed

**Comment by jstedfast** [comment]
Seems like a bug in Domino IMAP.

**Comment by ckePriv** [comment]
@jstedfast Thanks for the reply, I made some additional tests:
`IList<IMessageSummary> itemSummaries = folder.Fetch(0, 5, MessageSummaryItems.UniqueId);`
sends FETCH 1:**6** UID and not as expected FETCH 1:**5** UID
In the current folder on the Domino server exists exactly 5 (index 1 to 5) messages, the command requests index 6 as upper and not 5 as expected, the server returns with a BAD FETCH (see above).

Reducing the requested max index 4 
`folder.Fetch(0, 4, MessageSummaryItems.UniqueId);`
shows sends **FETCH 1:5 UID** ... server responds then correctly with 5 message UIDs and _surprisingly_ the lib returns 5 and not 4 UIDs as requested by the function call. So looks like the IMAP implementation of the Domino server rejects that call.

So the question is:
Why does the library fetch one more message than requested by the function call?

**Comment by jstedfast** [comment]
Why do you expect `FETCH 1:5 UID`? You provided index 0 through 5 which equates to IMAP index 1 to 6. Remember: C# uses indexes starting at 0, but IMAP uses indexes starting at 1, so once you map C# indexes to IMAP indexes, you have to add 1.

**Comment by jstedfast** [comment]
If this is the entire problem, then this bug is in your code and not MailKit.

**Comment by ckePriv** [comment]
May you're right and I'm wrong, but documentation states:
`public abstract IList<IMessageSummary> Fetch( int min,int max,MessageSummaryItems items,CancellationToken cancellationToken = default)`
min = The minimum index.
max = The maximum index, or -1 to specify no upper bound.

Just to get sure I understood correctly:
_index_ in this case doesn't mean the IMAP message index, right?

**Comment by jstedfast** [comment]
> Just to get sure I understood correctly:
> index in this case doesn't mean the IMAP message index, right?

Correct. It means the "array index", Index 0 means "the first message" (aka IMAP index 1). Index 1 means "the second message" (aka IMAP index 2).
