### ISSUE TITLE
Mailfolder.Count() initiates a FETCH x (BODY.PEEK[]) for all contained messages

### ISSUE THREAD

**Issue by ckePriv** [jstedfast/MailKit#1287]
I assume it works as designed, but I encounter the following behavior which lasts in a high traffic and I'm wondering if this couldn't be optimized:

Selecting an existing folder (containing 5 messages in this example) results in the following:
`myMailFolder.Open(FolderAccess.ReadWrite)`
C: A00000012 SELECT Import (CONDSTORE)
S: * FLAGS (\Answered \Flagged \Deleted \Seen \Draft \Forwarded)
S: * OK [PERMANENTFLAGS (\Answered \Flagged \Deleted \Seen \Draft \Forwarded \*)]
S: * OK [URLMECH INTERNAL]
**S: * 5 EXISTS**
S: * 0 RECENT
S: * OK [UIDVALIDITY 1636533206]
S: * OK [UIDNEXT 21]
S: * OK [HIGHESTMODSEQ 45]
S: A00000012 OK [READ-WRITE] SELECT completed

Now trying to determine the number of messages using:
`myMailFolder.Count()`
This immediately results in a FETCH sequence for all containing messages:

C: A00000012 FETCH 1 (BODY.PEEK[])
...
S: A00000012 OK FETCH completed
C: A00000013 FETCH 2 (BODY.PEEK[])
...
S: A00000013 OK FETCH completed
C: A00000014 FETCH 3 (BODY.PEEK[])
...
S: A00000014 OK FETCH completed
C: A00000015 FETCH 4 (BODY.PEEK[])
...
S: A00000015 OK FETCH completed
C: A00000016 FETCH 5 (BODY.PEEK[])
...
S: A00000016 OK FETCH completed

I expected the lib to use the number retrieved from the initial open call for the folder (5 EXISTS). I know that value will be outdated at some point, but shouldn't there be a more efficient way to determine the number of messages instead of retrieving all messages?

**Comment by jstedfast** [comment]
The Count() method that you are calling is from System.Linq, MailKit does not have any control over how that method is implemented.

If you just want to get the number of messages in the folder, don't use the Count() method. Use the Count *property*.

**Comment by jstedfast** [comment]
No worries.
