### ISSUE TITLE
Incorrect context extraction from Attachment

### ISSUE THREAD

**Issue by Budsy** [jstedfast/MailKit#1290]
**Describe the bug**
Xml text from a MimePart.Content stream is corrupted.

**Platform (please complete the following information):**
 - OS:  Windows 10
 - .NET Runtime:  Core
 - .NET Framework:  .NET 6
 - MailKit Version:  2.15.0

**Exception**
If you got an exception, please include the exception Message *and* StackTrace.

**To Reproduce**

**Expected behavior**
// This works to save a valid Xml from same attachment:
xmlEntity.WriteToAsync(string fileName);
produces XML that is clean:
<NOT_protest_hearing_begin_date>2021-05-20</NOT_protest_hearing_begin_date>
	<PRP_geo_account_id>68035</PRP_geo_account_id>
// ... but code snippet (below ) writing to a stream seems to leave MIME line enders scattered between Xml tags

<NOT_protest_hearing_begin_date>2021-05-20     FOR </NOT_protest_hearing_begin_date>
        ==
	<PRP_geo_account_id>68035</PRP_geo_account_id>

**Code Snippets**
If applicable, add code snippets to help explain your problem.

```csharp
// Add your code snippet here.
```
    // code snippet returns malformed Xml string, where xmlEntity is from Attachment
    using (Stream stream = ((MimePart) xmlEntity).Content.Stream)
    {
        byte[] buffer = new byte[stream.Length];
        stream.Position = 0;
        _ = await stream.ReadAsync(buffer, 0, (int)stream.Length);
        return System.Text.Encoding.UTF8.GetString(buffer);
    }

**Additional context**

**Comment by jstedfast** [comment]
Change your code to this:

// code snippet returns malformed Xml string, where xmlEntity is from Attachment
using (Stream stream = ((MimePart) xmlEntity).Content.Open ())
{
    byte[] buffer = new byte[stream.Length];
    stream.Position = 0;
    _ = await stream.ReadAsync(buffer, 0, (int)stream.Length);
    return System.Text.Encoding.UTF8.GetString(buffer);
}
