### ISSUE TITLE
how-to Save Attachments

### ISSUE THREAD

**Issue by felixZmn** [jstedfast/MailKit#1293]
**Describe the bug**
I tried to save E-Mail-Attatchments as described there: 
http://www.mimekit.net/docs/html/Frequently-Asked-Questions.htm#SaveAttachments

This Documentation seems to be outdated, because there are serval errors highlited by Visual Studio:
* A attachment always is a BodyPartBasic, so the "if" is practically useless
* BodyPartBasic can not be casted to MimePart

Am I missing something? Is the FAQ wrong? 

Currently I am using MailKit 2.15.0 on a Windows 10 Machine
Thanks in advance for your help

**Comment by jstedfast** [comment]
Those directions assume you used:

```csharp
MimeMessage message = folder.GetMessage (uid);
```
