### ISSUE TITLE
Not able to send email in RELEASE mode

### ISSUE THREAD

**Issue by NirajW-Infogain** [jstedfast/MailKit#1294]
**Issue**
The code below works as expected in debug mode, however, it fails in release mode. Type initializer exception is thrown at line  
var message = new MimeMessage();

Any solution, I would highly appreciate. 

**Platform (please complete the following information):**
 - OS: Windows 10
 - .NET Framework: UWP
 - MailKit Version: 2.15

**Code Snippets**
**var message = new MimeMessage();_**
message.From.Add(new MailboxAddress("Niraj Wadikar", "xxxxxx@gmail.com"));
message.To.Add(new MailboxAddress("my name", myemail@gamil.com));
message.Subject = "Driving Directions For Route" + " - " + RouteName;
message.Body = new TextPart("plain")
  {
         Text = @"Please use this url for driving direction" + " : " + RouteNavigationUrl
  };

using (var client = new SmtpClient())
                    {
                        client.Connect("smtp.gmail.com", 465, true);
                        client.Authenticate("mymail@gmail.com", "password");

                        client.Send(message);
                        client.Disconnect(true);
                    }

**Comment by jstedfast** [comment]
Am I supposed to guess what the exception is? What framework does UWP target? I don't ship a UWP assembly.

**Comment by jstedfast** [comment]
Most likely the issue is with text encoding initialization which means you are probably not including System.Text.Encoding.CodePages nuget or the assemblies included in that package are not being copied over to your bin directory.
