### ISSUE TITLE
Catch failed message delivery

### ISSUE THREAD

**Issue by dheoxic** [jstedfast/MailKit#1296]
Is it possible to determine/wait if a message fails to send for some reason without having to check the sender inbox for failed delivery email notification?

Below is a mock of what I am trying to accomplish.

```
Remote Server returned '550 5.1.2 <testemail@outlook.com>: Recipient address rejected: Domain not found' //

void SendMail(){
    try{
        //send e-mail
        if(failedToSend){
            //log failed delivery
            //reason: email doesn't exist
        }
    }
    catch (failedDeliveryException e){
        //log failed delivery
        //reason: other reasons
    }

}

**Comment by jstedfast** [comment]
```csharp
try {
    client.Send (message);
} catch (Exception ex) {
    // Failed to send message
}
```

**Comment by dheoxic** [comment]
Doesn't seem to catch failure of delivery in catch block if an email address doesn't exist. All I get is an email notification from outlook that the email was not sent because of non-existing email address. `Recipient address rejected: Domain not found`

**Comment by jstedfast** [comment]
Then your only option is to write code that will check your IMAP or POP3 Inbox for bounce messages.

**Comment by dctremblay** [comment]
> Doesn't seem to catch failure of delivery in catch block if an email address doesn't exist. All I get is an email notification from outlook that the email was not sent because of non-existing email address. `Recipient address rejected: Domain not found`

Have you found a library that does this since then ?

**Comment by dheoxic** [comment]
The only way is to check for bounce messages, as what's written in the mimekit docs.

**Comment by dctremblay** [comment]
Yup looks like it, I was wondering if there's some mediator/facade library that does it.
