### ISSUE TITLE
Can't set connection. System.Net.Sockets.SocketException

### ISSUE THREAD

**Issue by NiceAhah** [jstedfast/MailKit#1300]
A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

This error happens when code execution reach client.Connect method

Here Some Code 

 public void SendEmail(string email, string subject, string message)
        {
            var emailMessage = new MimeMessage();

            emailMessage.From.Add(new MailboxAddress("administration", "SomeEmail"));
            emailMessage.To.Add(new MailboxAddress("", email));
            emailMessage.Subject = subject;
            emailMessage.Body = new TextPart(MimeKit.Text.TextFormat.Html)
            {
                Text = message
            };

            using (var client = new SmtpClient())
            {
                client.Connect("smtp.gmail.com", 587, true);
                client.Authenticate("some@gmail.com", "pass");
                client.Send(emailMessage);

                client.Disconnect(true);
            }
        }

**Comment by NiceAhah** [comment]
smtp host doesn't matter in my case. I just want to send email, but can't

**Comment by jstedfast** [comment]
This is a networking problem that I can't really help you with.

Best I can do is provide you some possible things to try looking into:

1. check whether you have a firewall blocking outbound connections (antivirus software often puts up a firewall too)
2. check whether your network cable is plugged in and/or your wifi has a solid connection
3. make sure that your network routing tables are correct

FWIW, this is an error that comes from the .NET networking APIs, not MailKit itself.
