### ISSUE TITLE
How to receive messages that do not match IList<UniqueId>

### ISSUE THREAD

**Issue by eugenestepanyuk** [jstedfast/MailKit#1302]
I found in the documentation that can find messages by their uid
`SearchQuery.Uids(IList<UniqueId>);`

I have a question:
For example, I will transfer a string from the outside with one or more id and parse it by filling in IList <UniqueId>. And I will only need to receive messages that do not match this list.
Maybe I did not notice such a solution in the documentation, if there is one, I will be grateful for the help

**Comment by jstedfast** [comment]
Try this:

```csharp
SearchQuery.Not(SearchQuery.Uids(IList<UniqueId>));
```
