### ISSUE TITLE
Attempt to parse invalid content-type headers

### ISSUE THREAD

**Issue by patrick-bfs** [jstedfast/MailKit#1304]
Hello,

First off, thank you for MimeKit! It works fantastically well.

I recently ran into some emails that are sending invalid Content-Type headers, of the form `Content-Type: multipart/multipart/mixed; boundary="-boundary123-"`. MimeKit (quite reasonably) parses this as a `multpart/multpart` content-type without any boundary information, and so the content of the email is treated as the preamble.

It seems that some email clients are able to handle that content-type, presumably by discarding the first piece and treating it as a proper multipart/mixed header, or by checking for the presence of the boundary marker in that header and soldiering on.
A quick test of the first option in `ContentType.TryParse` allows MimeKit to parse those emails with no problem, is that something that would be appropriate to add?

I realize trying to fix bad headers may be out of the scope of the project, so thanks either way!

**Comment by patrick-bfs** [comment]
My apologies, this was meant for the MimeKit repo!

**Comment by jstedfast** [comment]
FWIW, GitHub allows me to move issues between my repos, so it's not a huge deal if you file in the wrong place.
