### ISSUE TITLE
NET6.0 Support

### ISSUE THREAD

**Issue by tpetzold-ts** [jstedfast/MailKit#1306]
Is there paned a NET6.0 support in the future?

**Comment by jstedfast** [comment]
Your .NET 6.0 apps/libraries should be able to use the .NET 5.0 builds of MimeKit/MailKit. It shouldn't be necessary for me to push .NET 6.0 builds for things to work afaik.

That said, it would be trivial to add build targets for net6.0 in the .csproj files.
