### ISSUE TITLE
Donation link broken on mimekit.net

### ISSUE THREAD

**Issue by user8446** [jstedfast/MailKit#1309]
Hi,

The PayPal donation link on mimekit.net --> https://paypal.me/pools/c/857bnxBTXg returns "We can't find that fundraiser 
It looks like that fundraiser is no longer available."
For some reason I couldn't donate via GitHub sponsors as well, but that may be a GitHub issue as it was failing for others as well tonight.
I did finally dig up https://github.com/jstedfast/MimeKit/issues/378 in which I found a working [Liberapay](https://liberapay.com/MimeKit/donate), but that is not advertised anywhere else.

**Comment by jstedfast** [comment]
Thanks, I forgot to update the website after PayPal stopped offering the ability to donate.
