### ISSUE TITLE
Invalid documentation for CodePagesEncodingProvider for .NET 6

### ISSUE THREAD

**Issue by kobruleht** [jstedfast/MailKit#1310]
Documentation at

https://github.com/jstedfast/MailKit/blob/master/FAQ.md#SaveAttachments

recommends to use

`System.Text.Encoding.RegisterProvider(System.Text.Encoding.CodePagesEncodingProvider.Instance);`

to suppport encodings.

This causes compile error in .NET 6:

> error CS0117: 'Encoding' does not contain a definition for 'CodePagesEncodingProvider'

It is not possible to support encodings in .NET 6

**Comment by jstedfast** [comment]
You need to grab the System.Text.Encoding.CodePages nuget from nuget.org

**Comment by kobruleht** [comment]
This package is included. Documentation is wrong. Encoding member should removed. Correct statement is

>             System.Text.Encoding.RegisterProvider(System.Text.CodePagesEncodingProvider.Instance);

**Comment by wilbertom** [comment]
Also ran into this issue

```
 error CS0117: 'Encoding' does not contain a definition for 'CodePages'
 ```
 
The docs are wrong.
