### ISSUE TITLE
Version mismatch

### ISSUE THREAD

**Issue by McTristan** [jstedfast/MailKit#1313]
I might be mistaken here but it seems the MailKit version posted at nuget.org is an older version than the myget.org one? Is there a particular reason for that?

It seems some bugs were closed in the latest release but as our build system uses nuget.org as primary nuget source and we would have to put quite a lot of effort into supporting another nuget source I would kindly ask you to publish it also to nuget.org if possible.

**Comment by jstedfast** [comment]
myget.org builds are rolling builds. nuget.org has official releases.

This is the only fix in the myget.org builds compared to the official release of 3.0.0: https://github.com/jstedfast/MailKit/commit/6f294cd7d5f80188679215ca5736e61616454fba

**Comment by McTristan** [comment]
Thank you for the clarification, I wasn't aware there was a myget feed at all. Seems like the mentioned commit isn't the course for our problem. So we have to invest more time to find the root course. We are running into some random authentication issues with the new 3.0 version.
