### ISSUE TITLE
Question about AccessRights and mocking

### ISSUE THREAD

**Issue by rogatec** [jstedfast/MailKit#1317]
Hi @jstedfast,

this is neither a bug nor a feature request, more of a question - hope you can label that.
I am currently using MailKit Version 3.0.0 on a .net standard 2.1 project.

When trying to get the access rights from an imap folder, I am calling the `GetMyAccessRightsAsync()` function - you mentioned that for me in another issue #1241.
As a result I'll get an object of `AccessRights` where there is a property with a private setter called `IsReadOnly`.

In my unit tests I am mocking the folder and the `GetMyAccessRightsAsync` function, but I'm having trouble to set the `IsReadOnly` to true, because with a private setter it gives me a `Non-overridable members` error. (_I am using Moq and NUnit_).

Maybe I am completely wrong, when checking this property, but I thought this is the obvious one to check.

Additionally on the imap client object, there is also a object property called `Rights` with the same AccessRights type.

How is it possible to mock/check wether the imap folder is read and/or writable?

Maybe you have a hint for me, or do the AccessRights (if the mailbox supports it) differs between different mail servers?

Best regards

**Comment by jstedfast** [comment]
> As a result I'll get an object of AccessRights where there is a property with a private setter called IsReadOnly.

The `AccessRights` collection class doesn't have a way to set `IsReadOnly` to true. Essentially, `AccessRights` is just `List<AccessRight>`.

> Maybe I am completely wrong, when checking this property, but I thought this is the obvious one to check.

Adding or removing access rights on the value returned by `GetMyAccessRightsAsync()` won't update any server settings or any state in the ImapClient/ImapFolder. Ideally, the IMAP implementation should probably set `IsReadOnly` to true, but I haven't found it important enough to worry about (yet).

> Additionally on the imap client object, there is also a object property called Rights with the same AccessRights type.

This property is set only when the IMAP server supports the ACL extension and you can verify this with the following check:

```csharp
if (client.Capabilities.HasFlag (ImapCapabilities.Acl))
```

The value contained within the ImapClient.AccessRights property are the full list of supported ACL access rights. Not all IMAP servers support every ACL access right, some only support a subset. This property can be used to figure out which ones the server supports.

It's not a reflection of what rights you have.

> How is it possible to mock/check wether the imap folder is read and/or writable?

You would mock the ImapFolder.GetMyAccessRights/Async() method(s) and have them return an `AccessRights` collection with the appropriate `AccessRight` values.

For the full list, see: http://www.mimekit.net/docs/html/T_MailKit_AccessRight.htm

For read-only, I think that would be `LookupFolder` and `OpenFolder`.

For read-write, you'd add all of the `AccessRight` values other than `Administer`.

> Maybe you have a hint for me, or do the AccessRights (if the mailbox supports it) differs between different mail servers?

They can differ in the sense that each IMAP server that supports ACLs may return a different subset.
