### ISSUE TITLE
Migrate to Mimekit 3.0 on Net 6.0 Application. SendAsync throws MethodNotFoundException

### ISSUE THREAD

**Issue by ThatBlokeCalledJay** [jstedfast/MailKit#1318]
**Describe the bug**
Migrating to MimeKit 3.0 on Net6.0 application introduces a MethodNotFoundException when trying to call SendAsync, specifically 

Method not found: 'System.Threading.Tasks.Task MailKit.MailTransport.SendAsync(MimeKit.MimeMessage, System.Threading.CancellationToken, MailKit.ITransferProgress)'

**Platform (please complete the following information):**
 - OS: Windows and Linux
 - .NET Runtime: CoreCLR
 - .NET Framework: Net 6.0
 - MimeKit Version: 3.0

**To Reproduce**
1. Using a Net6 application
2. Using service extensions, AddFluentEmail, AddMailkitSender and AddRazorRenderer.
2. attempt to call implementation of IFluentEmail  Task<SendResponse> SendAsync(CancellationToken? token = null);

**Expected behavior**
An email is dispatched

**Additional context**
Mimecast has been in use for quite some time now and works as expected. MimeKit 2.15.1 works as expected in our Net 6.0 application. We are using the razor renderer.

Interestingly we have been receiving other issues where razorlight has been used under the hood. Again, just putting that out there. :)

**Interesting note**
Pulling your source and referencing your solution directly from our application no longer produces an exception.

I understand that Mimekit doesn't explicitly support Net 6, and we can always revert to the previous version. Just wanted to put this out there. Will you be tackling Net 6 any time soon?

**Comment by jstedfast** [comment]
I think the issue might be that FluentEmail references MailKit 2.x instead of 3.0.

The Send methods in 2.x returned `void` but in 3.0, they return `string` (and the SendAsync 2.x methods returned `Task` while the 3.0 versions return `Task<string>`).

**Comment by ThatBlokeCalledJay** [comment]
Yeah, this seems to have been my realisation as I've been digging a bit deeper too. This would explain why, when I remove all reference to MailKit, the problem disappears as it will be using the  package version referenced by FluentEmail. 

I hope I haven't ruined your day/evening with this. I think it's probably best we close this guy for now, what say you?

**Comment by jstedfast** [comment]
No worries and yea, we can close this for now.

**Comment by msavara** [comment]
> No worries and yea, we can close this for now.

Sorry. I don't understand. Why this can be closed? That bug was resolved? I don't think so. Because it's still doesn't work...
