### ISSUE TITLE
POP3Client GetMessage throw Download Exceed

### ISSUE THREAD

**Issue by ROMYIM** [jstedfast/MailKit#1320]
**Describe the bug**
I turned on a cron task that runs every 5 minutes.
Every time I do a scheduled task, I reconnect to the pop3 mail service and do the authentication.
Then get the number of emails, and use the index to get the uid and message of each email according to the number of emails. When I call _**GetMessage(int index)**_ it throws an exception

**Platform (please complete the following information):**
 - OS: Windows 10,   Windows Server 2016
 - .NET Runtime: [e.g. CoreCLR, Mono]
 - .NET Framework: .net  framework 4.8
 - MailKit Version: 3.0.0

**Exception**
MailKit.Net.Pop3.Pop3CommandException: POP3 server did not respond with a +OK response to the RETR command.
   在 MailKit.Net.Pop3.Pop3Client.DownloadContext`1.<DownloadItemAsync>d__13.MoveNext() 位置 D:\src\MailKit\MailKit\Net\Pop3\Pop3Client.cs:行号 2507
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   在 MailKit.Net.Pop3.Pop3Client.DownloadContext`1.<DownloadAsync>d__14.MoveNext() 位置 D:\src\MailKit\MailKit\Net\Pop3\Pop3Client.cs:行号 2518
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   在 MailKit.Net.Pop3.Pop3Client.GetMessage(Int32 index, CancellationToken cancellationToken, ITransferProgress progress) 位置 D:\src\MailKit\MailKit\Net\Pop3\Pop3Client.cs:行号 2905
   在 iPlatform.MailService.controls.uBaseCtrol.DownloadEmail(Boolean filterToday) 位置 D:\ACIP\Documents\Repositories\iPlatform\iPlatform.MailService\controls\uBaseCtrol.cs:行号 12

**Code Snippets**
If applicable, add code snippets to help explain your problem.

```csharp
                messageCount = pop3Client.GetMessageCount(); 
                var guid = string.Empty;
                for (int i = messageCount - 1; i >= 0; i--)
                {
                    try
                    {
                        guid = pop3Client.GetMessageUid(i);
                        LogWorker.Log($"message guid: {guid}");
                        if (guids.ContainsKey(guid)) continue;
                
                        var messageModel = new MailBodyModel();

                        //  throw  exception  by this step
                        var message = pop3Client.GetMessage(i);

                        .....
                    }
                 }
```

**Protocol Logs**
C: LIST 3715
S: +OK 3715 79471
C: UIDL 3714
S: +OK 3714 AGoAQQAjE3Rj83HljEAskKoS
C: RETR 3714
S: -ERR Download exceed. msg=3714

**Comment by jstedfast** [comment]
That error comes from the POP3 server, not from MailKit. You need to contact the admin of your POP3 server and ask him/her what the issue is.

I suspect that you have exceeded some limit of the number of times you are allowed to connect and download messages from the POP3 server in a short span of time.

Try changing your timer to 10 minutes instead of 5 minutes.

**Comment by ROMYIM** [comment]
Thanks for your reply.It is the server limit
