### ISSUE TITLE
When will you upgrade MailKit package to .net 6?

### ISSUE THREAD

**Issue by vahitbayri** [jstedfast/MailKit#1321]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by jstedfast** [comment]
Is there a real need? A .NET 6.0 app should be able to reference MailKit's .NET 5.0 assemblies.

**Comment by vahitbayri** [comment]
Yes. TFS build pipeline wants MailKit .net 6 package for .net 6 projects to restore package. It is critical for our projects.

**Comment by jstedfast** [comment]
I've just updated MimeKit to build for net6.0 and will update MailKit to do the same after work.

**Comment by vahitbayri** [comment]
We both use MailKit and MimeKit. We need two. Can you please upgrade mailkit ?

**Comment by jstedfast** [comment]
I develop MimeKit and MailKit in my spare personal time (I wish Microsoft would pay me to work on these, but they don't).

Like I said in my previous comment, when I finish with work today, I'll update MailKit to build for net6.0 as well (for a quick hack, you can just add `net6.0` to the `<TargetFrameworks>` XML node in the MimeKit.csproj file).

**Comment by vahitbayri** [comment]
When I clone your repo, l got many errors so I couldnt build it.

**Comment by jstedfast** [comment]
Donations are appreciated :-)
