### ISSUE TITLE
README has obsolete API in it

### ISSUE THREAD

**Issue by alex-jitbit** [jstedfast/MailKit#1324]
**Describe the bug**
You've removed `AddFlags` API from `IMailFolder` but the README still has an old example

Please provide an updated example if possible

**Comment by alex-jitbit** [comment]
I assume that this code:

```csharp
imap.Inbox.AddFlags(uids, MailKit.MessageFlags.Deleted, true);
```

Should new be

```csharp
imap.Inbox.Store(uids, new MailKit.StoreFlagsRequest(MailKit.StoreAction.Add, MailKit.MessageFlags.Deleted));
```

**Comment by alex-jitbit** [comment]
Sorry for the false alarm

**Comment by jstedfast** [comment]
I think it would actually be closer to this (but your assumption is 99% correct):

```csharp
imap.Inbox.Store(uids, new MailKit.StoreFlagsRequest(MailKit.StoreAction.Add, MailKit.MessageFlags.Deleted) { Silent = true });
```

**Comment by jstedfast** [comment]
No worries, the docs should be updated for sure.

**Comment by jstedfast** [comment]
I've updated the README.md for this particular API change, but I need to still audit the rest of the docs
