### ISSUE TITLE
Custom DefaultLocalDomain for SmtpClient

### ISSUE THREAD

**Issue by waldo2188** [jstedfast/MailKit#1328]
**Is your feature request related to a problem? Please describe.**
I use MailKit in a docker container to send email through SMTP.
I was debugging some issue with an SMTP provider, and I notice that the hostname of the container is present in the raw email 
```text
Received: from container-hostname (unknown [42.42.42.42])
```

**Describe the solution you'd like**
I would like to know if there is a way to customize the `DefaultLocalDomain` with a personal value without changing the container hostname ?

In advance, thank you.

**Comment by jstedfast** [comment]
You can set SmtpClient.LocalDomain to whatever string you want and that is the (full) string that will be used in the EHLO command (which, presumably, is the string used by the SMTP server to generate the Received header).

**Comment by waldo2188** [comment]
I didn't see this possibility, you made my day!
