### ISSUE TITLE
Unable to Authenticate when using OAuth 2.0 access token gmail

### ISSUE THREAD

**Issue by sunandaVarma** [jstedfast/MailKit#1329]
**Describe the bug**
Hi,

I'am tryign to authenticate using mailKit providing the user name and OAuth access token.
Getting the below error when trying to Authenticate. I have the valid oAuth access token  token. 
535: 5.7.8 Username and Password not accepted. Learn more at 5.7.8  https://support.google.com/mail/?p=BadCredentials c7sm19648018pfp.164 - gsmtp

**Platform (please complete the following information):**
 - OS: Windows
 - .NET Runtime: [e.g. CoreCLR, Mono]
 - .NET Framework: [e.g. .Net Core, .NET 4.5, UWP, etc.]
 - MailKit Version: 3.1.1

**Exception**
535: 5.7.8 Username and Password not accepted. Learn more at 5.7.8  https://support.google.com/mail/?p=BadCredentials c7sm19648018pfp.164 - gsmtp

stack trace:
   at MailKit.Net.Smtp.SmtpClient.<AuthenticateAsync>d__93.MoveNext() in D:\src\MailKit\MailKit\Net\Smtp\SmtpClient.cs:line 962
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MailKit.Net.Smtp.SmtpClient.Authenticate(SaslMechanism mechanism, CancellationToken cancellationToken) in D:\src\MailKit\MailKit\Net\Smtp\SmtpClient.cs:line 1008
   at emailComponent123.Class1.sendMail(String accessToken) in E:\TstProjects\TestProjectsSol\WindowsFormsApp1\emailComponent123\Class1.cs:line 65

**Expected behavior**
To be able to Authenticate successfully

**Code Snippets**
```csharp
using (var client = new SmtpClient())
{
    client.Connect("Smtp.gmail.com", 587, SecureSocketOptions.StartTls);
    var oauth2 = new SaslMechanismOAuth2("myemail@gmail.com", "OauthToken");
    try
    {
        client.Authenticate(oauth2); // Authenticate throws the error
    } catch(Exception ex)
    {

    }
    client.Send(message);
    client.Disconnect(true);

}
```

```csharp
// Add your code snippet here.
```

**Protocol Logs**
Please include a protocol log (scrubbed of any authentication data), especially
if you got an exception such as `Syntax error in XYZ. Unexpected token: ...`.

To get a protocol log, follow one of the following code snippets:

```csharp
// log to a file called 'imap.log'
var client = new ImapClient (new ProtocolLogger ("imap.log"));
```

```csharp
// log to a file called 'pop3.log'
var client = new Pop3Client (new ProtocolLogger ("pop3.log"));
```

```csharp
// log to a file called 'smtp.log'
var client = new SmtpClient (new ProtocolLogger ("smtp.log"));
```

Note: if the protocol log contains sensitive information, feel free to email it to me at
jestedfa@microsoft.com instead of including it in the GitHub issue.

**Additional context**

**Comment by jstedfast** [comment]
Did you follow the directions in the [GMailOAuth2.md](https://github.com/jstedfast/MailKit/blob/master/GMailOAuth2.md) file?

**Comment by jstedfast** [comment]
Yes, the scope ALWAYS needs to be https://mail.google.com/. THe other 2 scopes you mentioned are ONLY for using Google's HTTP REST API, they do NOT work for SMTP.
