### ISSUE TITLE
LOGIN failed when connecting to office365 exchange account in outlook(.net core 5.0)

### ISSUE THREAD

**Issue by Prashant-Y-Girase** [jstedfast/MailKit#1332]
Hi,

I have one offce365 email account. Using that account I am login in Outlook application using (Exchange). So whenever I am trying to get all emails using IMAP, the "Login Failed"  exception is thrown. I am able to fetch all emails from my Gmail account using the below code after "ON" 'Less security Option' with IMAP enabled.

I haven't idea how to check IMAP setting enabled/disabled for Office365(Exchange account connect in Outlook) as well as need any security less for that account.
NOTE: two-way auth (Multifactor authentication) is off.

Please help me, if something missing from my side.

![image](https://user-images.githubusercontent.com/22464695/154003007-26aab85c-6d67-4f8d-96d7-30c680ad49da.png)

![image](https://user-images.githubusercontent.com/22464695/154003121-149b2e42-dadd-488f-89bd-a613ccfa3102.png)

**Comment by jstedfast** [comment]
Office365 stopped allowing normal authentication a year or 2 ago.

Your only option is to follow the instructions in [ExchangeOAuth2.md](https://github.com/jstedfast/MailKit/blob/master/ExchangeOAuth2.md) and to register your app with Microsoft and then use OAuth2 authentication.

**Comment by Prashant-Y-Girase** [comment]
Thank you @jstedfast

**Comment by Prashant-Y-Girase** [comment]
Hi @jstedfast ,

I have followed the above instructions and registered my application with all 3 steps which is mentioned in [ExchangeOAuth2.md](https://github.com/jstedfast/MailKit/blob/master/ExchangeOAuth2.md)
But still, I am not able to get the access token and throw an error using the below code which is provided by you in the link
Please help me, if something went wrong from my side.

![image](https://user-images.githubusercontent.com/22464695/154627430-92965fb2-6db3-462e-ab92-6941a92b7c2f.png)

**Error:**
One or more errors occurred. (Only loopback redirect uri is supported, but https://login.microsoftonline.com/common/oauth2/nativeclient was found. Configure http://localhost or http://localhost:port both during app registration and when you create the PublicClientApplication object. See https://aka.ms/msal-net-os-browser for details)

I am also using below code and getting different error 
![image](https://user-images.githubusercontent.com/22464695/154627856-3d7e751b-9309-40fe-b3dc-14c0956945ae.png)

Error:
One or more errors occurred. (A configuration issue is preventing authentication - check the error message from the server for details. You can modify the configuration in the application registration portal. See https://aka.ms/msal-net-invalid-client for details.  Original exception: AADSTS7000218: The request body must contain the following parameter: 'client_assertion' or 'client_secret'.
Trace ID: c74c9671-2f0d-47ea-8d50-a65038907900
Correlation ID: 093553c6-5d3d-4400-a562-143d7ff24ccb
Timestamp: 2022-02-17 09:06:57Z)

**Comment by jstedfast** [comment]
Have you tried following the instructions in the error message that you got?

That's the best advice I can give you.
