### ISSUE TITLE
Unable to use MailKit for email reporting in Arq Backup for Windows using Fastmail

### ISSUE THREAD

**Issue by pro-sumer** [jstedfast/MailKit#1333]
**Describe the bug**
Although I am a coder, I am submitting this issue as a user, where someone else is using MailKit, but unable to help me. I hope it's still OK to submit this. Maybe we can solve this all together?

I'm trying to set up email reporting in [Arq Backup](https://www.arqbackup.com) for Windows, using [Fastmail](https://fastmail.com) (with an application specific password). Email reporting works fine on macOS (where Arq does not use MailKit, I have been told). It also works fine for [Macrium Reflect (Home Edition)](https://www.macrium.com/products/home) on Windows, so I don't think the issue is with Fastmail.

When trying to test my setup, a dialog appears that only shows a very small part of the error returned by MailKit, but it seems to contain this link:

https://github.com/jstedfast/MailKit/blob/master/FAQ.md#SslHandshakeException

Additionally it shows this error log:

```
Connected to smtp://smtp.fastmail.com:587/?starttls=when-available
S: 220 smtp.fastmail.com ESMTP ready
C: EHLO [192.168.1.100]
S: 250-smtp.fastmail.com
S: 250-PIPELINING
S: 250-SIZE 71000000
S: 250-ENHANCEDSTATUSCODES
S: 250-8BITMIME
S: 250 STARTTLS
C: STARTTLS
S: 220 2.0.0 Start TLS
```

**Platform**
 - OS: Windows 10
 - MailKit Version: unknown (we would need to ask the Arq Backup author)

**Exception**
Since the dialog only shows a very small part of the error, I don't know...

**To Reproduce**
1. Configure a Fastmail account (with an application specific password) in Arq Backup for Windows
2. Click on the "Test" button

**Expected behavior**
Email setup works without issues.

**Code Snippets**
n/a

**Protocol Logs**
n/a

**Additional context**
n/a

**Comment by pro-sumer** [comment]
Thank you for responding.

Yes, I have read the FAQ before submitting this issue, but I unfortunately lack some knowledge, because I don't understand which of the four mentioned scenario's is mine and what I should do to fix it.

If anyone is willing to help me with that I would appreciate it.

**Comment by jstedfast** [comment]
I wouldn't know either :)
