### ISSUE TITLE
Is there any way to receive emails(webstite contact form) with MailKit ?

### ISSUE THREAD

**Issue by Haykaz-tech** [jstedfast/MailKit#1336]

**Comment by Haykaz-tech** [comment]
Dear Jeffrey Stedfast, thank you for your quick response. I have asp.net core project. And made email confirmation for registration using MailKit and it is OK.
But now I am trying to make contact form for the website customers. I don't know how to write the code for asp.net core using MailKit.
Do you have any code examples for that. I am new in programming.
Regards Haykaz.

**Comment by jstedfast** [comment]
You could look at the README to see how to do the basics.
