### ISSUE TITLE
NTLM: Incorrect MIC offset calculation

### ISSUE THREAD

**Issue by filipnavara** [jstedfast/MailKit#1340]
**Describe the bug**

The NTLM implementation suffers from the same bug as [gss-ntlmssp](https://github.com/gssapi/gss-ntlmssp/issues/62) and [Heimdal](https://github.com/heimdal/heimdal/issues/961). It incorrectly assumes that the presence, or lack thereof, of the `NtlmFlags.NegotiateVersion` affects the location of the MIC field in the `AUTHENTICATE_MESSAGE` packet. That disagrees both with the [official specification](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-nlmp/b38c36ed-2804-4868-a9ff-8dd3182128e4) and the the [Wireshark traces when testing against Windows Server 2022](https://github.com/gssapi/gss-ntlmssp/issues/62#issuecomment-1048726862).

The code in question:
https://github.com/jstedfast/MailKit/blob/a5b78170e1d994b30dfdd2644ff690e922585ae4/MailKit/Security/Ntlm/NtlmAuthenticateMessage.cs#L235

Notably, I am working on a unit test [here](https://github.com/dotnet/runtime/pull/65611) and in some subsequent PRs to dotnet/runtime that emulate the server behaviour to unit test the whole authentication exchange. Once the code stabilises a bit it would likely make sense to adapt it in MailKit too.

**Comment by filipnavara** [comment]
Side notes:
- `SaslMechanismNtlm` seems to specify OSVersion on Windows, this propagates into the NTLM `NegotiateMessage` and upon successful exchange all the way into `AuthenticationMessage`. As a result it masks the bug on Windows.
- Unlike gss-ntlmssp if the server unilaterally sets the `NegotiateVersion` bit in `ChallengeMessage` without the client asking for it in `NegotiateMessage` the version is not propagated into `AuthenticationMessage`. This is in line with the Microsoft specification but it also means that it can actually result in fail authentication in practical scenarios.

**Comment by filipnavara** [comment]
> Ah, thanks. I would love to adopt any unit tests you have into MailKit for NTLM.

We were in the same boat. Last week I snapped and implemented a fake server-side part in C# to test against. It's not perfect but it already uncovered bugs in every major NTLM implementation [outside Windows] including buffer overruns. So I started filing bugs...

> It was one of the bigger challenges and I never managed to get access to a server that supported NTLM, so I pretty much implemented it blind 😅

We run two test servers in Azure that I would be happy to share access to. The problem is that it doesn't cover all scenarios (domain vs. server authentication) and one of the servers routinely crashes (and needs manual restart). Moreover, at the moment they only serve HTTP requests and not the full Exchange installation. The Exchange machines bit rot way too easily and we didn't have anyone to maintain them.  I cannot promise anything at the moment but I will try to get the infrastructure more reliable so it can be used for testing by external projects. Ideally, we should figure out a way to share the credentials for private use or use in GitHub Actions CI (through the GitHub Secrets).                                                                                                      

> Oh, you work for eM Client? That's awesome!
> Do you guys use MimeKit or MailKit at all?
> I'm guessing you have your own MIME parser/IMAP/POP3/SMTP implementations, but figured I'd ask.

We use our own libraries, mostly because the original code predates MimeKit and MailKit by a couple of years. That said, we do use MimeKit/MailKit in some ancillary tools and we run some compatibility tests to ensure we don't break on emails produced by MimeKit or vice-versa.

**Comment by filipnavara** [comment]
> Getting NTLM correct was not trivial (and it looks like I still got stuff wrong!).

I got it wrong too, twice. 😅 First in one implementation that I wrote years ago and now again in a one that I based on someone else's code.

The MIC offset calculation seems to be broken in every implementation I checked so far (5 of them + Wireshark analyzer). I am even starting to doubt myself whether I performed the check correctly. However, I did Wireshark trace against real Windows installation and double-checked the specification (+ errata). In most cases that bug is masked by some other implementation detail though.

Given the fact that I could have possibly missed something, I recommend proceeding with extra scrutiny. The safe way to fix the problem is to always start with negotiating with the `NtlmFlags.NegotiateVersion` flag. Servers that support MIC also support this flag and will reply with appropriate challenge. The authenticate message will then contain the version field as well and the MIC field will be at the correct offset [per the specification] regardless of calculation used.

**Comment by jstedfast** [comment]
I re-read the spec the other night and it does look like you are correct about always including the block of 8 bytes for the version field (even if not populated).

I've made a commit to do that, but I'm going to keep this open for a bit longer to remind me to check up on the dotnet/runtime link unit test discussion here: https://github.com/dotnet/runtime/pull/65611

Looks like there's now discussion of setting up a SMTP server for testing purposes - whether I try to hop onto that train or take your unit tests and modify them for inclusion in MailKit, I'm not sure yet - but either way, I want better tests for MailKit's NTLM support.

**Comment by filipnavara** [comment]
Thanks, as of today gss-ntlmssp and Wireshark were also fixed.

I'll notify you when we move forward with the testing infrastructure.
