### ISSUE TITLE
Send multiple Emails at once

### ISSUE THREAD

**Issue by JanTrichter** [jstedfast/MailKit#1341]
Hey guys, 
I've  found a few issues related to this ticket already but they don't seem to fix my problem.

I have a `List<MimeMessage>` which I want to send to the GMail API. 

I already tried it but my current approach is not working:

Firstly I authenticated using OAuth2.0 (which works fine when sending only one email).

I thought that I could try to send multiple emails like this but it is not working:
```cs
emails.ForEach(async (email) =>
{
    using (var client = new SmtpClient())
    {
        await client.ConnectAsync(smtp.Host, smtp.Port, SecureSocketOptions.SslOnConnect);

        // Note: only needed if the SMTP server requires authentication
        await client.AuthenticateAsync(oauth2);

        await client.SendAsync(email);

        await client.DisconnectAsync(true);
    }
});
```

I get the Error:
`MailKit.Security.AuthenticationException: '501: 5.5.2 Cannot Decode response [...]`

How can I send multiple messages like this (or is this even possible)?

**Comment by jstedfast** [comment]
Have you considered doing this instead?

```csharp
using (var client = new SmtpClient())
{
    await client.ConnectAsync(smtp.Host, smtp.Port, SecureSocketOptions.SslOnConnect);

    // Note: only needed if the SMTP server requires authentication
    await client.AuthenticateAsync(oauth2);

    foreach (var email in emails)
        await client.SendAsync(email);

    await client.DisconnectAsync(true);
}
```

**Comment by JanTrichter** [comment]
Thank you for the great explanation 💯 .

I will look into this a bit more when I find the time to do so but you already gave me an idea what is happening.

Thanks a lot 👍🏽
