### ISSUE TITLE
Possible Bug with OAuth2 authentication

### ISSUE THREAD

**Issue by sophisma** [jstedfast/MailKit#1343]
**Describe the bug**
Hi I'm trying to implement a small email service using MailKit with a google service account, gmail and oauth2 and I think I ran into a bug.
I can get an access token just fine but when I try to authenticate with it I get an error "555: 5.5.2 Syntax error, goodbye.".
The access token has a size of 1024 bytes, after a bit of digging I found out is that if I pass only a substring of the token with a maximum size of 697 that error disappears and I get an error "535: 5.7.8 Username and Password not accepted.", which is expected. Anything with a length above 697 will give the first error.

The issue happens on the last line of the following code, but I dont know if it's an issue with the SaslMechanismOAuth2 or the client.AuthenticateAsync method.
I'm substringing the AccessToken just for debuging purposes.

```
var oauth2 = new SaslMechanismOAuth2(emailSettings.ClientEmailAddress, token.AccessToken.Substring(0, 697));
await client.ConnectAsync(emailSettings.PrimaryDomain, emailSettings.PrimaryPort, SecureSocketOptions.Auto);
await client.AuthenticateAsync(oauth2);
```

Just for context, in the code you'll se an undeclared "token" variable, that's actually a static variable so that it doesn't et deleted after each call.
Here is how I'm getting the access token:

```
private static void GetAccessToken()
{
    var credential = new ServiceAccountCredential(new ServiceAccountCredential
        .Initializer("id")
    {
        Scopes = new[] { GmailService.Scope.MailGoogleCom },
        User = "id"
    }.FromPrivateKey("Private_Key"));

    try
    {
        bool accessTokenRequestIsSuccessful = credential.RequestAccessTokenAsync(CancellationToken.None).Result;

        if (!accessTokenRequestIsSuccessful)
        {
            LogHelper.Error("Error acquiring access token from Google Services");
            throw new Exception("Error acquiring access token from Google Services");
        }
        else
        {
            Console.WriteLine(credential.Token.AccessToken);
            token = credential.Token;
        }
    }
    catch (Exception e)
    {
        LogHelper.Error(e, "Error acquiring access token from Google Services");
        throw e;
    }
}
```
And here is how I'm attempting to send an email, with the block of code that's not working:
        
```
public async Task SendEmail(string email, string subject, string message)
{
    try
    {
        using (var client = new SmtpClient())
        {
            if (token.IsExpired(SystemClock.Default))
            {
                GetAccessToken();
            }
            var oauth2 = new SaslMechanismOAuth2(emailSettings.ClientEmailAddress, token.AccessToken);
            await client.ConnectAsync(emailSettings.PrimaryDomain, emailSettings.PrimaryPort, SecureSocketOptions.Auto);
            await client.AuthenticateAsync(oauth2);

            var emailMessage = new MimeMessage();

            emailMessage.From.Add(new MailboxAddress(emailSettings.FromEmail, emailSettings.ClientEmailAddress));
            emailMessage.To.Add(new MailboxAddress("", email));
            emailMessage.Subject = subject;
            emailMessage.Body = new TextPart("html") { Text = message };
                 
            await client.SendAsync(emailMessage);
            await client.DisconnectAsync(true);
        }
    }
    catch (Exception e)
    {
        LogHelper.Error(e, "Error executing sending email");
        throw e;
    }
}

```
Finally, here are a couple of tokens that gave me the error:

"ya29.c.b0AXv0zTMJzAmgyY58SmHozsErq62XlEMNC6dLzTLct2czy-ERyOwrymdqkJ8xQjQMH0LwPnOwqdEqE68PUXs48NRnnPVCxQigZCRGNFEGcanHv0BuEUHOKwMc97snf8l3uMdx4G15_62SHrsf9QDmo83kDBul8AKdbD6GqTBG_3JyhLnPwa2TMxFcA8b3kkFq-pTgY-hdPj56FsfUlMEUWrFExw9j3g........................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................."

"ya29.c.b0AXv0zTP_KCbq8ewxpkZF9zR1pFGbN9fx-CeeUTgIgM70JfAiu5pC-w8Z_oQU2p8CJ_jl_HKR-L4tjTiEi0gTG1TNSEfR-uNAcD0AllHjdnBaIkLcADnlUkwhWE_CtesOUfOY4zV7OHt_MtIFRimZYrGpZPeN4yaogu1acabCoscCoLBfPtrLKj9FqL5VQw5Kd6vwpgvjeMwvx4iE7vgEAcekQm5Lsw........................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................."

**Platform (please complete the following information):**
 - OS: Windows 10
 - .NET Runtime: [e.g. CoreCLR, Mono]
 - .NET Framework: .NET 5
 - MailKit Version: 3.1.1

**Exception**
555: 5.5.2 Syntax error, goodbye. v124-20020a1cac82000000b0037c3d08e0e7sm15738372wme.29 - gsmtp

   at MailKit.Net.Smtp.SmtpClient.<AuthenticateAsync>d__95.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at EmailService.Data.Gateway.EmailsGateway.<Execute>d__4.MoveNext() in C:\VSProjects\EmailService\Data.Gateway\EmailsGateway.cs:line 71

**Comment by jstedfast** [comment]
Here's the only docs I've ever found on Google's X-OAUTH2 implementation: https://developers.google.com/gmail/imap/xoauth2-protocol

There's nothing that says to trim the access token after 697 characters.

Here's the X-OAUTH2 implementation: https://github.com/jstedfast/MailKit/blob/master/MailKit/Security/SaslMechanismOAuth2.cs#L132

**Comment by sophisma** [comment]
I know it doesn't, It's supposed to work with 1024, but I'm getting that initial error if the length of the token is above 697.

**Comment by jstedfast** [comment]
The only thing I can think of is that the base64 encoded blob in the `AUTH XOAUTH2 ...` command is so long that it is too long for Google's command buffer (often 1000 bytes in many SMTP servers).

If that's the case, then it's an unfixable problem and not a bug in MailKit.

**Comment by jstedfast** [comment]
You could try changing this line: https://github.com/jstedfast/MailKit/blob/master/MailKit/Net/Smtp/SmtpClient.cs#L916

If the length is > 1000, try injecting a `"\r\n" at position 998.

I doubt it'll work, but maybe it's worth a shot?

**Comment by jstedfast** [comment]
FWIW, are you *sure* you need to be using the service-to-service OAUTH2 mechanism as opposed to the normal OAUTH2 tokens? See these docs: https://github.com/jstedfast/MailKit/blob/master/GMailOAuth2.md

**Comment by sophisma** [comment]
Yes, I'm sure.
This is going to be used to send order update information to clients.
Since it's going to be deployed to a IIS server it won't work that way, I tried it yesterday all day. 
It works when you're debugging on visual studio but when you deploy it to a webserver it blocks on this line:

`var credential = await authCode.AuthorizeAsync (GMailAccount, CancellationToken.None);`

The reason for it is because when that line runs it asks the user to grant permission to access his gmail account. This works fine when you're running in Visual Studio on your local machine, but when you deploy it to IIS it tries to open de webserver's browser, the thing is that the user never sees it and can't grant permission.

**Comment by sophisma** [comment]
Yesterday I was following another tutorial but I just noticed you have something slightly different in your version:

```
// Note: For a web app, you'll want to use AuthorizationCodeWebApp instead.
var codeReceiver = new LocalServerCodeReceiver ();
var authCode = new AuthorizationCodeInstalledApp (codeFlow, codeReceiver);
```

I might give it a shot.
I'll keep the current code just in case.

**Comment by jstedfast** [comment]
That will still require user interaction, it just presents it in a web UI instead of opening a browser window (sorta like websites often allow you to "login" via Google).

**Comment by sophisma** [comment]
Just tried it, still doesn't work when deployed to a webserver.

**Comment by iPilot** [comment]
I'm experiencing the same issue moving to OAuth2 + service accounts authorization. According to RCF 5321:
> The maximum total length of a text line including the <CRLF> is 1000 octets (not counting the leading dot duplicated for transparency). This number may be increased by the use of SMTP Service Extensions.

Auth tokens returned by Google have 1024 characters length themselves, and they must be combined with service account id which is very long comparing to common email addresses and with fields names. Converting to Base64 increases the total length to almost 1500 bytes in my case.

**Comment by jstedfast** [comment]
@iPilot OAUTH2 is an SMTP service extension so it allows more.
