### ISSUE TITLE
The requested folder could not be found. Exception

### ISSUE THREAD

**Issue by revis45** [jstedfast/MailKit#1347]
**Can't Get folders for some emails**

i'm trying to make a simple E-Mail client...
when i'm trying to get all folders
i get this weird exception

the issue is , it's not happening on all emails 
some emails works , some doesn't even if it's from the same service
i own two @t-online.de emails
only one works , the other one gives an exception
i've tried to search and check my code and did alot of modifcations ... still getting same exception 
doesn't get folders..

is it a bug or  issue from my code ? if so i would really appreciate helping me , even if it's in C# i can understand that

**

The requested folder could not be found.
   at MailKit.Net.Imap.ImapEngine.<GetFoldersAsync>d__194.MoveNext() in D:\src\MailKit\MailKit\Net\Imap\ImapEngine.cs:line 2703
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MailKit.Net.Imap.ImapClient.<GetFoldersAsync>d__136.MoveNext() in D:\src\MailKit\MailKit\Net\Imap\ImapClient.cs:line 2429
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MailKit.Net.Imap.ImapClient.GetFolders(FolderNamespace namespace, StatusItems items, Boolean subscribedOnly, CancellationToken cancellationToken) in D:\src\MailKit\MailKit\Net\Imap\ImapClient.cs:line 2478
   at Form1.clientlogins() in C:\form1.vb:line 545
----------

**
line 545 is  Dim inbox = Await client.GetFoldersAsync(New FolderNamespace(".", ""))

**Expected behavior**
Getting folders
** 

                   Using client = New ImapClient()

                    If ProxyCheckbox.Checked Then

                        client.ProxyClient = New HttpProxyClient(PrxIP, PrxPrt, New NetworkCredential(PrxLogin, PrxPass))

                    End If

                    client.CheckCertificateRevocation = False
                    client.Connect(imp, 993, SecureSocketOptions.Auto)
                    client.Authenticate(login, pass)
                  'exception 
                    Dim inbox = Await client.GetFoldersAsync(New FolderNamespace(".", ""))

                    For Each item In inbox
                     Dim folder = client.GetFolder(item.FullName)
                     Await folder.OpenAsync(FolderAccess.[ReadOnly])
                     etc.....
**

**Comment by revis45** [comment]
> It would be helpful if you could get a [protocol log](https://github.com/jstedfast/MailKit/blob/master/FAQ.md#ProtocolLog)

Connected to imaps://secureimap.t-online.de:993/
S: * OK [CAPABILITY IMAP4 IMAP4rev1 QUOTA LITERAL+ NAMESPACE UIDPLUS IDLE SORT] IMAP Proxy ready (secureimap.t-online.de)
C: F00000000 LOGIN ******** ********
S: F00000000 OK [CAPABILITY IMAP4rev1 SASL-IR LOGIN-REFERRALS ID ENABLE IDLE SORT SORT=DISPLAY THREAD=REFERENCES THREAD=REFS THREAD=ORDEREDSUBJECT MULTIAPPEND URL-PARTIAL CATENATE UNSELECT CHILDREN NAMESPACE UIDPLUS LIST-EXTENDED I18NLEVEL=1 CONDSTORE QRESYNC ESEARCH ESORT SEARCHRES WITHIN CONTEXT=SEARCH LIST-STATUS BINARY MOVE SNIPPET=FUZZY PREVIEW=FUZZY PREVIEW STATUS=SIZE SAVEDATE LITERAL+ NOTIFY METADATA SPECIAL-USE XEXPIRE QUOTA] Logged in
C: F00000001 NAMESPACE
S: * NAMESPACE (("INBOX." ".")) NIL NIL
S: F00000001 OK Namespace completed (0.001 + 0.000 secs).
C: F00000002 LIST "" "INBOX" RETURN (SUBSCRIBED CHILDREN)
S: * LIST (\HasChildren) "." INBOX
S: F00000002 OK List completed (0.006 + 0.000 + 0.005 secs).
C: F00000003 LIST (SPECIAL-USE) "" "*" RETURN (SUBSCRIBED CHILDREN)
S: * LIST (\Subscribed \HasNoChildren \UnMarked \Junk) "." INBOX.Spam
S: * LIST (\Subscribed \HasNoChildren \UnMarked \Trash) "." INBOX.Trash
S: * LIST (\Subscribed \HasNoChildren \UnMarked \Sent) "." INBOX.Sent
S: * LIST (\Subscribed \HasNoChildren \UnMarked \Drafts) "." INBOX.Drafts
S: F00000003 OK List completed (0.001 + 0.000 secs).
Connected to imaps://secureimap.t-online.de:993/
S: * OK [CAPABILITY IMAP4 IMAP4rev1 QUOTA LITERAL+ NAMESPACE UIDPLUS IDLE SORT] IMAP Proxy ready (secureimap.t-online.de)
C: G00000000 LOGIN ******** ********
S: G00000000 OK [CAPABILITY IMAP4rev1 SASL-IR LOGIN-REFERRALS ID ENABLE IDLE SORT SORT=DISPLAY THREAD=REFERENCES THREAD=REFS THREAD=ORDEREDSUBJECT MULTIAPPEND URL-PARTIAL CATENATE UNSELECT CHILDREN NAMESPACE UIDPLUS LIST-EXTENDED I18NLEVEL=1 CONDSTORE QRESYNC ESEARCH ESORT SEARCHRES WITHIN CONTEXT=SEARCH LIST-STATUS BINARY MOVE SNIPPET=FUZZY PREVIEW=FUZZY PREVIEW STATUS=SIZE SAVEDATE LITERAL+ NOTIFY METADATA SPECIAL-USE XEXPIRE QUOTA] Logged in
C: G00000001 NAMESPACE
S: * NAMESPACE (("INBOX." ".")) NIL NIL
S: G00000001 OK Namespace completed (0.001 + 0.000 secs).
C: G00000002 LIST "" "INBOX" RETURN (SUBSCRIBED CHILDREN)
S: * LIST (\HasChildren) "." INBOX
S: G00000002 OK List completed (0.003 + 0.000 + 0.003 secs).
C: G00000003 LIST (SPECIAL-USE) "" "*" RETURN (SUBSCRIBED CHILDREN)
S: * LIST (\Subscribed \HasNoChildren \UnMarked \Junk) "." INBOX.Spam
S: * LIST (\Subscribed \HasNoChildren \UnMarked \Trash) "." INBOX.Trash
S: * LIST (\Subscribed \HasNoChildren \UnMarked \Sent) "." INBOX.Sent
S: * LIST (\Subscribed \HasNoChildren \UnMarked \Drafts) "." INBOX.Drafts
S: G00000003 OK List completed (0.001 + 0.000 secs).
Connected to imaps://secureimap.t-online.de:993/
S: * OK [CAPABILITY IMAP4 IMAP4rev1 QUOTA LITERAL+ NAMESPACE UIDPLUS IDLE SORT] IMAP Proxy ready (secureimap.t-online.de)
C: H00000000 LOGIN ******** ********
S: H00000000 OK [CAPABILITY IMAP4rev1 SASL-IR LOGIN-REFERRALS ID ENABLE IDLE SORT SORT=DISPLAY THREAD=REFERENCES THREAD=REFS THREAD=ORDEREDSUBJECT MULTIAPPEND URL-PARTIAL CATENATE UNSELECT CHILDREN NAMESPACE UIDPLUS LIST-EXTENDED I18NLEVEL=1 CONDSTORE QRESYNC ESEARCH ESORT SEARCHRES WITHIN CONTEXT=SEARCH LIST-STATUS BINARY MOVE SNIPPET=FUZZY PREVIEW=FUZZY PREVIEW STATUS=SIZE SAVEDATE LITERAL+ NOTIFY METADATA SPECIAL-USE XEXPIRE QUOTA] Logged in
C: H00000001 NAMESPACE
S: * NAMESPACE (("INBOX." ".")) NIL NIL
S: H00000001 OK Namespace completed (0.001 + 0.000 secs).
C: H00000002 LIST "" "INBOX" RETURN (SUBSCRIBED CHILDREN)
S: * LIST (\HasChildren) "." INBOX
S: H00000002 OK List completed (0.011 + 0.000 + 0.011 secs).
C: H00000003 LIST (SPECIAL-USE) "" "*" RETURN (SUBSCRIBED CHILDREN)
S: * LIST (\Subscribed \HasNoChildren \UnMarked \Junk) "." INBOX.Spam
S: * LIST (\Subscribed \HasNoChildren \UnMarked \Trash) "." INBOX.Trash
S: * LIST (\Subscribed \HasNoChildren \UnMarked \Sent) "." INBOX.Sent
S: * LIST (\Subscribed \HasNoChildren \UnMarked \Drafts) "." INBOX.Drafts
S: H00000003 OK List completed (0.001 + 0.000 secs).

**Comment by jstedfast** [comment]
Okay, so the FolderNotFoundException was being thrown because there is no namespace for `("", ".")`, as you can see in the log, it's `("INBOX.", ".")`.

I'm not seeing the unexpected disconnect, though.

**Comment by revis45** [comment]
> Okay, so the FolderNotFoundException was being thrown because there is no namespace for `("", ".")`, as you can see in the log, it's `("INBOX.", ".")`.
> 
> I'm not seeing the unexpected disconnect, though.

when i add Namespaces[0]
i get unexpected disconnect....

**Comment by jstedfast** [comment]
I need a protocol log of that

**Comment by revis45** [comment]
thank you so much , i'm so stupid it was a vpn problem
vpn in background gave me headache for hours lol

**Comment by jstedfast** [comment]
No problem, it happens :)
