### ISSUE TITLE
Sending Mailkit Uniqueid value from razor

### ISSUE THREAD

**Issue by cgtytpl** [jstedfast/MailKit#1348]
Hi, thanks for library.
I am using the library in asp.net mvc project.
I created an imap client and listed the mails. 
I use this to select one of these messages and see its detail. 
`public ActionResult GetMailDetails(UniqueId id, string foldername = "INBOX")`

how can i send uniqueid value via razor page?

**Comment by jstedfast** [comment]
I've never written an ASP.NET app or a razor page, so I don't know, but I imagine you would do it the same as you would a regular int.
