### ISSUE TITLE
Inbox opens in ReadOnly mode even though ReadWrite specified.

### ISSUE THREAD

**Issue by rgelb** [jstedfast/MailKit#1349]
**Describe the bug**
Inbox opens in ReadOnly mode even though ReadWrite specified.

**Platform (please complete the following information):**
 - OS: Windows
 - .NET Runtime: CLR
 - .NET Framework: .NET 4.6.1
 - MailKit Version: 3.3.1

**To Reproduce**
```csharp
var imapClient = new ImapClient(new ProtocolLogger("imap.log"));
imapClient.Connect('mybox', 143, false);
imapClient.Authenticate("uid", "pwd");
var inbox = imapClient.Inbox;
var openedWith = inbox.Open(FolderAccess.ReadWrite);
Console.WriteLine(openedWith);
if (!inbox.IsOpen) throw new Exception("boom");
```

The `.Open` method always returns `FolderAccess.ReadOnly` even though I specified `FolderAccess.ReadWrite`.

**Protocol Logs**
The protocol logger reports the following:

```
Connected to imap://mybox:143/?starttls=when-available
S: * OK [CAPABILITY IMAP4rev1 SASL-IR LOGIN-REFERRALS ID ENABLE IDLE LITERAL+ AUTH=PLAIN AUTH=LOGIN] Dovecot ready.
C: A00000000 AUTHENTICATE PLAIN ********
S: A00000000 OK [CAPABILITY IMAP4rev1 SASL-IR LOGIN-REFERRALS ID ENABLE IDLE SORT SORT=DISPLAY THREAD=REFERENCES THREAD=REFS THREAD=ORDEREDSUBJECT MULTIAPPEND URL-PARTIAL CATENATE UNSELECT CHILDREN NAMESPACE UIDPLUS LIST-EXTENDED I18NLEVEL=1 CONDSTORE QRESYNC ESEARCH ESORT SEARCHRES WITHIN CONTEXT=SEARCH LIST-STATUS BINARY MOVE SNIPPET=FUZZY PREVIEW=FUZZY LITERAL+ NOTIFY SPECIAL-USE] Logged in
C: A00000001 NAMESPACE
S: * NAMESPACE (("" ".")) NIL NIL
S: A00000001 OK Namespace completed (0.001 + 0.000 secs).
C: A00000002 LIST "" "INBOX" RETURN (SUBSCRIBED CHILDREN)
S: * LIST (\HasNoChildren) "." INBOX
S: A00000002 OK List completed (0.001 + 0.000 secs).
C: A00000003 LIST (SPECIAL-USE) "" "*" RETURN (SUBSCRIBED CHILDREN)
S: * LIST (\Subscribed \HasNoChildren \Trash) "." Trash
S: A00000003 OK List completed (0.001 + 0.000 secs).
C: A00000004 SELECT INBOX (CONDSTORE)
S: * FLAGS (\Answered \Flagged \Deleted \Seen \Draft)
S: * OK [PERMANENTFLAGS ()] Read-only mailbox.
S: * 5061 EXISTS
S: * 0 RECENT
S: * OK [UNSEEN 1] First unseen.
S: * OK [UIDVALIDITY 1646954935] UIDs valid
S: * OK [UIDNEXT 39151] Predicted next UID
S: * OK [HIGHESTMODSEQ 712] Highest
S: A00000004 OK [READ-ONLY] Select completed (0.007 + 0.000 + 0.006 secs).
```

As you can see it does say `OK [PERMANENTFLAGS ()] Read-only mailbox`, but I am not sure what it means.  I am connected to the same IMAP mailbox via Thunderbird and I am able to do destructive things to the Inbox like Delete messages, etc...

**Expected behavior**
Inbox should open in ReadWrite mode

**Additional information**
I am able to do read-only things like read messages, etc...

**Comment by jstedfast** [comment]
There are 2 IMAP commands to open a folder. These commands are SELECT which *requests* that the server open the folder in read-write mode and EXAMINE which tells the server to explicitly open in read-only mode.

MailKit correctly used the SELECT command in your logs, so this isn't a bug.

Most likely, your IMAP server only allows 1 client to have a folder open in read-write mode at a time because it doesn't implement proper synchronization. Therefor, when a second client (in this case, your program using MailKit) attempts to open the folder, it forces read-only mode.

Close Thunderbird and I bet it will allow you to open in read-write mode.

**Comment by jstedfast** [comment]
Fwiw, "OK [READ-ONLY]" is where the actual mode is parsed from. The other text you noticed is just free-form human readable junk that can be anything.

**Comment by rgelb** [comment]
@jstedfast I killed Thunderbird and I am still getting ReadOnly.  I tried a different library and also got a ReadOnly.  It's probably a server side problem.

As far as Thunderbird goes, I looked at the IMAP [trace ](https://pastebin.com/YbjLzTz8)and it also gets `OK [READ-ONLY]` and `OK [PERMANENTFLAGS ()] Read-only mailbox` messages back.  It just doesn't seem to care.  It plows ahead and lets me delete things and move them around.

**Comment by jstedfast** [comment]
Try asking on Dovecot's forums (or their irc channel). They have been helpful when I've asked questions.

**Comment by rgelb** [comment]
@jstedfast Thanks for the suggestion.  They were helpful. 

In case someone else runs into this problem.  That email account I was using is a system (on Linux) account, but lacked write permissions to the folder where the mail was stored.  Postfix/Dovecot seems to eat that error and do not report it either via IMAP or POP3 protocols.  I am unclear how this process kept failing for a decade and no one noticed.
