### ISSUE TITLE
Question: keeping connection around

### ISSUE THREAD

**Issue by dkekesi** [jstedfast/MailKit#135]
Hi Jason,

This is rather a theoretical question. We send out approx. 2000 mails/day using MailKit from a multi-threaded application. We currently send by connecting to the company SMTP server, authenticating, sending the mail, then finally disconnecting. This works fine, but a bit slow. Each mail takes about 6-7 seconds to send and most time is used for establishing connection. Mail bodies are always less than 1 KB in size (plain text notification messages). We want to make sending faster, but would like an advice first.
Is it possible - or rather a good practice - using MailKit to connect once the application starts, and keep the connection open for sending subsequent mails? Is it possible for multiple threads to use the same connection with MailKit?

Thanks,
Daniel

**Comment by senj** [comment]
Is there an example which methods need to be synchronized?

**Comment by jstedfast** [comment]
@senj 

```csharp
lock (folder.SyncRoot) {
    folder.DoSomething ();
}
```
