### ISSUE TITLE
Where do I go if I have a question about MailKit 2_15 that DotNetNuke uses.

### ISSUE THREAD

**Issue by cunnke** [jstedfast/MailKit#1354]
We are trying to get an answer on an older version of MailKit version 2_15 that DNN 09.10.02 (0) is using. The issue we are having is that DNN is sending emails in TXT format and our paperless office solution likes HTML format. The older version of DNN 09.10.01 (0) with MailKit 2_13 sends emails in HTML format. 

Is there a file that we can update in MailKit to have forms emailed out as an HTML format?

**Comment by jstedfast** [comment]
That doesn't sound like a MailKit issue - MailKit doesn't have any control over whether the message body is in text or html format. That's up to the software that constructs the message *using* MimeKit/MailKit.

In other words, MimeKit/MailKit just do what you tell it to do :-)
