### ISSUE TITLE
header tag: Return-Path dont appear in email AWS SES

### ISSUE THREAD

**Issue by Eugene-Lytvynov** [jstedfast/MailKit#1355]
**Describe the bug**
During sending Email, we added header "Return-Path" with value "ReturnPath@mail.com". As result tag did not appear in result Email. What is wrong? Did we do something wrong or AWS remove it. pls, help us to understand your part.

**Platform (please complete the following information):**
 - OS: Windows
 - .NET Runtime: ASP.NET 4.6.1 
 - MailKit Version: 3.1.1

**Expected behavior**
Header should consist this attr

**Code Snippets**
If applicable, add code snippets to help explain your problem.

```csharp
            MimeMessage mailMessage = new MimeMessage();
            mailMessage.From.Clear();
            mailMessage.From.Add(new MailboxAddress("Test from", "From@mail.com"));

            mailMessage.To.Add(new MailboxAddress("Test To", "To@mail.com"));

            mailMessage.Headers.Add("Return-Path", MailboxAddress.Parse("ReturnPath@mail.com").ToString());

            mailMessage.Subject = "test Message";

            var sender = new MailboxAddress("Sender@mail.com");
            mailMessage.Body = ....

            await _client.SendAsync(mailMessage, sender, cancellationToken).ConfigureAwait(false);
```

**Comment by jstedfast** [comment]
AWS is removing it, but maybe it's removing it because it's not at the top of the headers.

Try this:

```csharp
mailMessage.Headers.Insert(0, "Return-Path", "ReturnPath@mail.com");
```

**Comment by Eugene-Lytvynov** [comment]
Ok, thanks

**Comment by Eugene-Lytvynov** [comment]
So, you do not overwrite it, isnt it? I mean the tag

**Comment by jstedfast** [comment]
MimeKit/MailKit will not overwrite any headers.
