### ISSUE TITLE
What's the recommended/performant way to use the getStreams method?

### ISSUE THREAD

**Issue by cuuupid** [jstedfast/MailKit#1356]
Hi, I found `getStreams` when looking through past issues regarding bulk processing. I'd like to consume around ~30k emails from a folder and am looking for the most performant way to do so!

Currently I'm using this pattern:
``` csharp
// using an exact path for the type below as it was the only way to get it to resolve getStreams
MailKit.Net.Imap.IImapFolder all = (IImapFolder)client.GetFolder(SpecialFolder.All);
UniqueIdRange range = new UniqueIdRange(uidMin, uidNext); // predefined range for last 30k
var refs = all.Search(range, SearchQuery.All);

IList<Task<MimeMessage>> tasks = new List<Task<MimeMessage>>();
void getMessageFromStream(ImapFolder _, int __, UniqueId ___, Stream stream) {
    tasks.Add(MimeMessage.LoadAsync(stream));
}
all.GetStreams(refs, getMessageFromStream);
MimeMessage[] messages = await Task.WhenAll(tasks);
```

I'm looking to possibly parallelize this; as the callback doesn't require a full IMAP connection since it just parses the message, I figured it shouldn't be an issue to have that be done in large batches of threads. However, I read that the stream is closed when the callback returns, so I'm not sure what the best way to go about this is. Would love some insight here as to how to accomplish this or whether there's a better way to go about this!

**Comment by jstedfast** [comment]
> However, I read that the stream is closed when the callback returns

Correct. The Stream argument is Dispose()'d once the callback returns, so it's important to process it in the callback itself and not defer processing.

You probably don't want to have 30,000 messages loaded in RAM anyway because that could be a ton of memory.

**Comment by jstedfast** [comment]
FWIW, the API was designed with the expectation that developers would save the stream to disk and process them later.

**Comment by cuuupid** [comment]
Thanks! We need to serve it up to another process pretty much immediately, so in this case I'll go with the synchronous route.
