### ISSUE TITLE
Add support for setting dsn per email in smpt client

### ISSUE THREAD

**Issue by jagtyp** [jstedfast/MailKit#136]
I would want to be able to set per email which delivery notifications should be sent back to the return-path in the smtp client.

They describe in below rfc's how this should be implemented:
https://www.ietf.org/rfc/rfc3461.txt
https://www.ietf.org/rfc/rfc1891.txt
It's possible to do quite alot here, but for me simply setting per email (per send) would be just fine.

Thanks
/David

**Comment by jstedfast** [comment]
I just released MailKit 1.0.5 to NuGet this morning with this fix.
