### ISSUE TITLE
Switched to MailKit's SmtpClient - Authentication Failures

### ISSUE THREAD

**Issue by AlexanderMorou** [jstedfast/MailKit#1360]
I've been having an issue transitioning from the .NET `SmtpClient` to MailKit's `SmtpClient`.

Our connection process is dirt simple:
```C#
public SmtpClient CreateSmtpClient()
{
  var result = new SmtpClient();
  result.Connect
    ( this.Host
    , this.Port
    , this.EnableSsl
      ? SecureSocketOptions.Auto
      : SecureSocketOptions.None);
  /* https://stackoverflow.com/a/66711098/557100 */
  if (!this.UserName.IsNullOrWhiteSpace()
      && !this.Password.IsNullOrWhiteSpace()
      && result.Capabilities.HasFlag(SmtpCapabilities.Authentication))
    result.Authenticate(this.UserName, this.Password);
  return result;
}
```

The issue I'm having is some customers are reporting the following exception:
`MailKit.Net.Smtp.SmtpCommandException: 5.7.3 Authentication unsuccessful`

The problem with this is that nothing other than the `SmtpClient` changed.

Our original approach, with the .NET `SmtpClient` was simpler still:
```C#

    public SmtpClient CreateSmtpClient()
    {
      return new SmtpClient
      {
        Host = this.Host,
        Port = this.Port,
        EnableSsl = this.EnableSsl,
        DeliveryMethod = SmtpDeliveryMethod.Network,
        UseDefaultCredentials = false,
        Credentials = new NetworkCredential(UserName, Password)
      };
    }
```
We've had mild success with some customers resetting their password, but that logic doesn't seem sequitur to me. Legacy `SmtpClient` didn't retry without credentials if the credentialed path didn't work, did it?

**Comment by AlexanderMorou** [comment]
It was a bit baffling to me because the only thing that changed was the `SmtpClient`. It seemed odd to ask them to check their username and password, because it'd been working fine for sometimes years.

**Comment by jstedfast** [comment]
FWIW, you will likely find this helpful in debugging stuff like this: https://github.com/jstedfast/MailKit/blob/master/FAQ.md#ProtocolLog

Note that http://mimekit.net/docs/html/P_MailKit_ProtocolLogger_RedactSecrets.htm can also be helpful if you need to disable redaction of secrets.

**Comment by jstedfast** [comment]
> It seemed odd to ask them to check their username and password, because it'd been working fine for sometimes years.

Ah, yea, that makes sense.

**Comment by AlexanderMorou** [comment]
We're on 3.1.1. We weren't anticipating any issues moving to the new `SmtpClient`, but it happens sometimes. We'll just gather information (more with the link you provided) and go from there.

There is a lot of variety in our customer environments, and we've of yet been unable to replicate their issues. So that makes it fun to track down.
