### ISSUE TITLE
NON-ASCII CHARACTERS NOT SUPPORTED - Trash Library

### ISSUE THREAD

**Issue by Castellano213** [jstedfast/MailKit#1364]
I cannot authenticate because of this trashbrary not parsing passwords correctly.
The worst library in the galaxy.

Connected to imaps://imap.rambler.ru:993/
S: * OK IMAP4 ready
C: A00000000 CAPABILITY
S: * CAPABILITY IMAP4rev1 UNSELECT LITERAL+ IDLE QUOTA AUTH=PLAIN
S: A00000000 OK completed
C: A00000001 AUTHENTICATE PLAIN
S: + 
C: ********
S: A00000001 NO Invalid login or password
C: A00000002 LOGIN ******** "********"

I can manually authenticate (through rambler site) correctly, They also have IMAP activated so, trash library!!
This library is a waste of time.
The Earth doesn't deserve this library, TrashKit. (or better, WasteKit)

**Comment by jstedfast** [comment]
😢

**Comment by ekalchev** [comment]
@Castellano213 Mailkit is one of the best .net codebase I've seen in my 15 years career.

**Comment by 0xivaan** [comment]
@Castellano213 Have you perhaps considered the slight possibility that the issue is on the server’s side before deciding to base your unsuccessful invasion of the issue section of the library on false accusations? 🤔
