### ISSUE TITLE
[MessageExpunged]: How to sync the local DB?

### ISSUE THREAD

**Issue by DierkDroth** [jstedfast/MailKit#1366]
Hi,

I'm storing emails in a local DB (keyed by their .UniqueId) and liked to keep that DB in sync as an email is deleted on the IMAP server -> the record in my DB needed to be deleted as well.

.MessageExpunged provides an e.Index and an optional e.UniqueId property. Unfortunately the latter is not set on my customer's email account (this is a CONDSTORE=false account). The e.Index reference does not help, since AFAIK there is no way to get the .UniqueId from it.

Also: I'm aware of the sample code where a 'messages' dictionary in memory mirrors the IMAP folder. However, that does not help, since in my approach the emails can't be kept in memory but are saved to the DB -> .MessageExpunged needed to provide a non-volatile reference to the email record in the DB.

What could be done to solve the problem? Thanks in advance

**Comment by jstedfast** [comment]
Have you considered something like this?

```csharp
public bool TryGetUniqueId (int index, out UniqueId uid)
{
	using (var command = dbConnection.CreateCommand ()) {
		command.Parameters.AddWithValue ("@INDEX", (long) index);
		command.CommandText = $"SELECT UID FROM {MessageTable.TableName} ORDER BY UID LIMIT 1 OFFSET @INDEX";
		command.CommandType = CommandType.Text;

		using (var reader = command.ExecuteReader (CommandBehavior.SingleRow)) {
			if (reader.Read ()) {
				int column = reader.GetOrdinal ("UID");

				if (column != -1) {
					uid = new UniqueId ((uint) reader.GetInt64 (column));
					return true;
				}
			}

			uid = UniqueId.Invalid;

			return false;
		}
	}
}
```

**Comment by DierkDroth** [comment]
@jstedfast thanks for follow up.

If I understand your approach correctly, then it would fail if the MailKit client would miss a single .MessageExpunged event since from that point forward the wrong email would be deleted from the DB, no? This would be an unacceptable risk since there is no guarantee the MailKit client would be up 100% of the time and there would not be deleted any email on the IAMP server if the MailKit client is down...

Is my understand correct or am I missing something?

**Comment by jstedfast** [comment]
> then it would fail if the MailKit client would miss a single .MessageExpunged event

Not if you re-synchronized your database immediately after opening the folder.

See this code snippet: https://github.com/jstedfast/MailKit/issues/1363#issuecomment-1108729056

The approach I'm giving you is the way every mail client does it.

It's important to always keep an index-to-UID mapping, even if you haven't yet requested data for all of the messages yet.

You can use folder.Search(SearchQuery.All) to get the server's mapping.

**Comment by DierkDroth** [comment]
@jstedfast to clarify (to make sure I'm on the right track): basically you're suggesting a full map of local cache/DB to the remote IMAP folder every time the MailKit client connects, correct?

If so, then I don't think this is a viable approach, since the resource consumption on startup could be massive (think of a server managing thousands of IMAP accounts).

Back to the real problem: is there no other info available than e.Index on .MessageExpunged?

**Comment by jstedfast** [comment]
> basically you're suggesting a full map of local cache/DB to the remote IMAP folder every time the MailKit client connects, correct?

Correct. There's no other way to do it.

> If so, then I don't think this is a viable approach, since the resource consumption on startup could be massive (think of a server managing thousands of IMAP accounts).

Not really. All you need is to do folder.Search(SearchQuery.all) to get the server's list of UIDs and use that to purge cached items that no longer make sense, and then add db records for the UIDs that you don't already know about.

You don't have to fetch all of the metadata for all of those messages.

> Back to the real problem: is there no other info available than e.Index on .MessageExpunged?

There is not. All you get from an IMAP server's EXPUNGE notification is the index.

https://www.rfc-editor.org/rfc/rfc3501.html#section-7.4.1

**Comment by DierkDroth** [comment]
@jstedfast I'm still trying to understand the full scope of the problem...

- What happens as an email is moved on the IMAP server from one folder to the next? Would I get .MessageExpunged on the source folder (provided I'm subscribed to that folder)?
- What's the optional e.UniqueId property for if it's not populated at all?

**Comment by jstedfast** [comment]
* You'll get a MessageExpunged event
* MessageEventArgs is a general-purpose EventArgs. I probably should have used a MessageExpungedEventArgs that only had an Index.

**Comment by DierkDroth** [comment]
Thanks for clarification @jstedfast

**Comment by DierkDroth** [comment]
@jstedfast I'm thinking through this case for a potential code change

I feel there is some confusion between UID and UniqueId. In [this code reference](https://github.com/jstedfast/MailKit/issues/1363#issuecomment-1108729056) you're using 'uid' in name where is it rather should be 'UniqueId', no? E.g. I'm looking at the `var uids`

I would appreciate it you could provide some clarification. Thanks in advance

**Comment by jstedfast** [comment]
Sure.

1. Uid and UniqueId are the same thing. UID is the IMAP nomenclature and in MailKit, the type used to denote a UID is a UniqueId.
2. That is correct. UIDs are assigned sequentially and never change once the message is added to the folder.

Every message has an index and a UID. The index of a message can change if an older message gets deleted, but the UID will not.

Let me walk you through an easy scenario:

You've just created a new folder (so UID sequencing will start fresh at `1`) and then immediately copy 10 messages into the folder. You'll now have the following indexes and UIDs (I'll use the numeric list feature to indicate indexes):

1. 1
2. 2
3. 3
4. 4
5. 5
6. 6
7. 7
8. 8
9. 9
10. 10

If you then delete messages 4, 5 and 6, the IMAP server will give you a MessageExpunged event for each message and, depending on which order they are deleted in, will be something like:

OnMessageExpunged(Index = 4)
OnMessageExpunged(Index = 4)
OnMessageExpunged(Index = 4)

or

OnMessageExpunged(Index = 6)
OnMessageExpunged(Index = 5)
OnMessageExpunged(Index = 4)

(Note: Actually, since MailKit indexes are 0-based, the indexes will be 3, 3, 3 or 5, 4, 3)

The end result will be:

1. 1
2. 2
3. 3
4. 7
5. 8
6. 9
7. 10

If you then receive a new message, it will have an index of 8 and a UID of 11.

IMAP will never re-use the same UID in the folder, so if you delete message #8 (UID=11) and then a new message arrives, it will have an index of 8 and a UID of 12.

**Comment by DierkDroth** [comment]
Excellent! Thanks @jstedfast. I appreciate your patience...

**Comment by DierkDroth** [comment]
@jstedfast I'm trying to minimize the DB load impact imposed by the approch you suggested [here ](https://github.com/jstedfast/MailKit/issues/1366#issuecomment-1108694485) ... and wanted to maintain a cache (a key dictionary of my DB records, sorted by UniqueId) which basically works like this:
- populate cache on startup as per [here](https://github.com/jstedfast/MailKit/issues/1363#issuecomment-1108729056)
- add items on every FetchAsync
- remove items on .MessageExpunged (and use the DB key to efficiently remove any DB record)

Is this a viable approach or would you see any conceptual holes?

**Comment by jstedfast** [comment]
Seems reasonable to me

**Comment by DierkDroth** [comment]
Thanks again for your feedback @jstedfast. FYI initial tests did not exhibit any issue with the approach above
