### ISSUE TITLE
How do I avoid sent emails go to spam?

### ISSUE THREAD

**Issue by BrandonStudio** [jstedfast/MailKit#1368]
**Describe the bug**
Use an existing smtp server to send email.
Use `GenerateMessageId(string domain)` method to generate messageId ending with domain name.

**Platform (please complete the following information):**
 - OS: Windows
 - .NET Runtime: CoreCLR
 - .NET Framework: ASP.NET Core 6.0
 - MailKit Version: 3.2.0

**Exception**

**To Reproduce**

**Expected behavior**
Sent emails go to target inbox.

**Code Snippets**

```csharp
public async Task SendEmailAsync(string email, string subject, string htmlMessage)
{
Begin:
	if (!_smtpClient.IsConnected)
		Connect();
	if (!_smtpClient.IsAuthenticated)
		Authenticate();
	var message = new MimeMessage()
	{
		Subject = subject,
		Body = new TextPart("html") { Text = htmlMessage }
	};
	message.From.Add(new MailboxAddress(_sender.DisplayName ?? _sender.UserName, _sender.Email));
	message.To.Add(new MailboxAddress(email, email));
	message.MessageId = MimeUtils.GenerateMessageId(_sender.Email[(_sender.Email.IndexOf('@') + 1)..]);
	try
	{
		await _smtpClient.SendAsync(message);
	}
	catch (SmtpCommandException ex)
	{
		goto Begin;
	}
}
```

**Protocol Logs**

**Additional context**

**Comment by jstedfast** [comment]
If the messages you are sending end up in the recipient's spam folder, then you need to tweak your messages to not trigger the spam software logic.

I can't help you with that.
