### ISSUE TITLE
Are links in MimeMessage.Subject supported at all?

### ISSUE THREAD

**Issue by DierkDroth** [jstedfast/MailKit#1371]
Hi,

A customer just came across an valid/interesting request. He's used to have links in the subjects of his mails. This works nicely e.g. in Outlook where he then could click on that link.

However, MimeMessage.Subject is a plain string. Is there some support for links other than me just parsing the .Subject string and visualize the link by whatever UI means?

Thanks in advance

**Comment by jstedfast** [comment]
MIME messages don't have a concept of links in any header or even message bodies.

You could put a link there if you wanted to, though. It's just not guaranteed to be supported by any (or all) mail clients that receive the message.

If you are implementing the receiving client, then you could just parse the subject looking for http or https URLS or something and linkify them.

**Comment by DierkDroth** [comment]
Thanks for your feedback @jstedfast
