### ISSUE TITLE
problem in oauth2 in android application

### ISSUE THREAD

**Issue by moshemc1** [jstedfast/MailKit#1374]
Hello,
I am trying to authenticate with gmail using the code:
```csharp
var clientSecrets = new ClientSecrets {
    ClientId = "xxx.apps.googleusercontent.com",
    ClientSecret = "xx"
};
var codeFlow = new GoogleAuthorizationCodeFlow(
    new GoogleAuthorizationCodeFlow.Initializer {
        DataStore = new FileDataStore("CredentialCacheFolder", false), 
        Scopes = new[] { "https://mail.google.com/" }, 
        ClientSecrets = clientSecrets
    });
var codeReceiver = new LocalServerCodeReceiver();
var authCode = new AuthorizationCodeInstalledApp(codeFlow, codeReceiver); 
var credential = await authCode.AuthorizeAsync(Chatting.Setings.CSetings.email, CancellationToken.None);
```
I get exception:
Failed to launch browser with "https://accounts.google.com/o/oauth2/v2/auth?access_type=offline&response_type=code&client_id=235430671536-lv1hu1mpqq4868ui7akghha90sbq6prk.apps.googleusercontent.com&redirect_uri=http%3A%2F%2F127.0.0.1%3A41743%2Fauthorize%2F&scope=https%3A%2F%2Fmail.google.com%2F" for authorization. See inner exception for details.
Cannot find the specified file
What's the problem
Please help
Thank you
Moshe

**Comment by jstedfast** [comment]
This is a question you'll need to ask the Google.Apis.Auth library experts.

Google.Apis.Auth is not part of (nor a dependency of) MailKit. You could try using a different OAuth library like DotNetOpenAuth or some such.
