### ISSUE TITLE
Imap envelope messageId truncated

### ISSUE THREAD

**Issue by Webmarco** [jstedfast/MailKit#138]
ImapUtil.ParseEnvelope has the following line to set the messageId:

if ((nstring = ReadNStringToken (engine, false, cancellationToken)) != null)
envelope.MessageId = MimeUtils.EnumerateReferences (nstring).FirstOrDefault ();

the actual envelope from exchangeserver has "&lt;020c01d044d4$c33d0f80$47a72eb0$@aName@online.com&gt;" as messageId

when applied to MimeUtils.EnumerateReferences this returns "020c01d044d4$c33d0f80$47a72eb0$@aName" where I would expect "020c01d044d4$c33d0f80$47a72eb0$@aName@oneline.com".

Is this an issue in MimeKit or should someother method be used by MailKit to parse messageId from the exchange envelope?

From the emailheader:
x-mailer: Microsoft Office Outlook 12.0

Log from protocollogger (altered original identifiers):

S: \* 624 FETCH (ENVELOPE ("Wed, 17 Dec 2014 09:37:54 +0000" "RE: Your Reference ID: 1000  - (DSM , DSM -  - 0737) Service  - FF-00055560" (("name" NIL "name.aName" "online.com")) NIL NIL (("'C'" NIL "c" "dom.com")) ((NIL NIL "support" "online.com") ("'VS]'" NIL "v" "online.com") ("'C'" NIL "c "dom.com")) NIL "7b777fe4-05a7-43a2-ae1d-7077731d04cc" "&lt;020c01d044d4$c33d0f80$47a72eb0$@aName@online.com&gt;") UID 79999)

**Comment by jstedfast** [comment]
I just released MimeKit 1.0.4 to NuGet this morning with this fix.

**Comment by Webmarco** [comment]
Thank you!
