### ISSUE TITLE
System.Net.NetworkInformation is not supported on this platform

### ISSUE THREAD

**Issue by zonggang** [jstedfast/MailKit#1381]
**Describe the bug**
got System.Net.NetworkInformation is not supported on this platform when new SMTP client.

**Platform (please complete the following information):**
 - OS: Windows
 - .NET Runtime: [e.g. CoreCLR, Mono]
 - .NET Framework: .NET 6
 - MailKit Version: 3.2

**Exception**
Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
Unhandled exception rendering component: The type initializer for 'MailKit.Net.Smtp.SmtpClient' threw an exception.
System.TypeInitializationException: The type initializer for 'MailKit.Net.Smtp.SmtpClient' threw an exception.
---> System.PlatformNotSupportedException: System.Net.NetworkInformation is not supported on this platform.

**To Reproduce**
new SmtpClient()

**Expected behavior**
new instance created.

**Comment by jstedfast** [comment]
Which platform are you on?
