### ISSUE TITLE
Does Exchange OAuth2 Account ever expire?

### ISSUE THREAD

**Issue by aleksvujic** [jstedfast/MailKit#1383]
Documentation about [Using OAuth2 With Exchange](https://github.com/jstedfast/MailKit/blob/master/ExchangeOAuth2.md) states that we can use the following code snippet once we successfully obtained `authToken.Account` (with `AcquireTokenInteractive(scopes)`):

`var authToken = await publicClientApplication.AcquireTokenSilent(scopes, account).ExecuteAsync(cancellationToken);`

We obtained account information on `localhost` during development. We plan to save it to `appsettings.json` file and deploy the application to the server. It is supposed to send the email **without any human interaction from now on**. Will `account` information ever expire?

**Comment by jstedfast** [comment]
Yes, unfortunately, it expires after a period of time. IIRC, there should be a "expires_in" json property on the token response that will tell you.

**Comment by aleksvujic** [comment]
We would like to implement a common email service which would serve as a central mail-sending service for all company applications. It would expose a REST API endpoint (ex. `POST /SendMail`) which would receive all the required data (to, cc, from, email content, …) and then send the message to the recipients using Microsoft account (`no-reply@company.com`). Obviously mail service is a deamon background running process without human interaction involved.

How can we implement common email service given the fact that `Account` expires? We don’t want to update its configuration on monthly-basis just because `Account` expires every now and then.

**Comment by jstedfast** [comment]
My best suggestions are:

1. Setup your own company SMTP server so that you can configure it to use whatever authentication method you want (obviously stay away from OAuth)
2. Use a public SMTP server that doesn't require OAuth
3. Use the REST API that Office365 is moving to: https://docs.microsoft.com/en-us/graph/outlook-send-mime-message
4. Use [SendGrid](https://sendgrid.com/)
