### ISSUE TITLE
Question: Checking for client still connected

### ISSUE THREAD

**Issue by lukos** [jstedfast/MailKit#1385]
Obviously, connecting on the SmtpClient is relatively expensive so I am attempting to cache the clients so they can be reused. However, when a client is next used, I want to check for it being connected since if not, I can simply discard it and create a new one.

However, I tried this by shutting down a remote mail host on a pod and when my code called `client.IsConnected`, it returned true, attempting to carry on and then, of course, crashed on `Send()`.

Is there a proper way to check that a client is *still* connected, as opposed to it was connected when I first created it? I saw `NoOp()` but that looks like it would need a try catch and might not be the most efficient way to check the life of the client?

Thanks

**Comment by ekalchev** [comment]
When you have TCP/IP connection, the only reliable way to check if it is still connected is to send something (or receive but that cannot be forced). NoOp() is the proper way to do it.

**Comment by jstedfast** [comment]
The SmtpClient.IsConnected property only tells you what it thinks the state is w/o doing any I/O to verify (in this way, it behaves much like Socket.IsConnected).

The only way to know for sure is to send a command and see if that works and the NOOP command is perfect for that purpose. It's basically just a ping to see if the server is still there and to let the server know that the client is still there.
