### ISSUE TITLE
Question: Enhanced SMTP status codes

### ISSUE THREAD

**Issue by lukos** [jstedfast/MailKit#1386]
Currently, if we send an email that fails asynchronously, the bounce email that is sent back usually includes an enhanced status code of the format x.x.x, which we are currently using to apply specific metadata for our users e.g. "Conversion failed".

However, if we send an email that throws an exception due to a synchronous error, it appears that MailKit only returns a basic status code e.g. `UserNotLocalTryAlternatePath = 551`

I found a non-exhaustive map between them here: https://datatracker.ietf.org/doc/html/rfc5248 but since a single basic code could map to multiple enhanced codes, I was wondering if MailKit has access to these enhanced codes and is not returning them in the exception or whether there is any other way that I can get the enhanced code from the exception or request?

**Comment by jstedfast** [comment]
They would be in the error message string if they are there.
