### ISSUE TITLE
DisconnectAsync(true, token) throws System.NullReferenceException

### ISSUE THREAD

**Issue by giterdonebubba** [jstedfast/MailKit#1389]
I'm getting the NullReferenceException when calling the DisconnectAsync(true, token).  The email gets send successfully otherwise.   

.NET 6 console app
MailKit 3.2.0

> System.NullReferenceException
> 
>   HResult=0x80004003
>   Message=Object reference not set to an instance of an object.
> 
>   Source=MailKit
> 
>   StackTrace:
>    at MailKit.Net.Smtp.SmtpClient.<DisconnectAsync>d__108.MoveNext()
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
>    at SmtpClientAdapter.<>c__DisplayClass0_1.<<SendMessageAsync>b__0>d.MoveNext() in
>    C:\SmtpClientAdapter.cs:line 36
> 
>   This exception was originally thrown at this call stack:
>     [External Code]
>     SmtpClientAdapter.SendMessageAsync.AnonymousMethod__0(object, MailKit.MessageSentEventArgs) in SmtpClientAdapter.cs

Here is my code:

	using (var smtpClient = new SmtpClient())
	{
	    smtpClient.MessageSent += async (o, e) => await smtpClient.DisconnectAsync(true, cancellationToken);

	    await smtpClient.ConnectAsync(smtpServerOptions.Host, smtpServerOptions.Port, smtpServerOptions.UseSsl, cancellationToken);

        if (!string.IsNullOrWhiteSpace(smtpServerOptions.UserName) && !string.IsNullOrWhiteSpace(smtpServerOptions.Password))
        {
		await smtpClient.AuthenticateAsync(smtpServerOptions.UserName, smtpServerOptions.Password, cancellationToken);
	    }

	    await smtpClient.SendAsync(mimeMessage, cancellationToken);
	}

I also tried the DisconnectAsync() right after the SendAsync() with the same result.  When the `MessageSent` event is triggered, I can see the IsConnected is true and right after calling DisconnectAsync() it is set to false.  So the connection is disconnected gracefully or otherwise.  I wrapped the try-catch around but the exception wasn't caught by the catch block.  Also, this seems to happen only in the Visual Studio debugger.  Does the exception mean the `using` block disposed a resource that DisconnectAsync() need?

**Comment by jstedfast** [comment]
Ugh, don't call DisconnectAsync in the event handler. You are corrupting state when you do that.

**Comment by giterdonebubba** [comment]
Thanks for the response.  Exception is still is thrown even if I have the DisconnectAsync() right after the SendAsync(). 
   
      using(var client = new SmtpClient())
      {
         .
         .
         await smtpClient.SendAsync(mimeMessage, cancellationToken); 
         await smtpClient.DisconnectAsync(true, cancellationToken);
      }

**Comment by jstedfast** [comment]
Can you get me a protocol log? I don't know what would be causing your NRE if you call DIsconnectAsync() after SendAsync.

All my code does that and it never fails with an NRE...
