### ISSUE TITLE
Headers with multiple encoding fail to be decoded by major email clients

### ISSUE THREAD

**Issue by ThomasCadiou** [jstedfast/MailKit#139]
I am trying to send emails using MailKit but some subjects fail to be encoded properly, and some accented characters appear corrupted (question mark). This may be random, but it happens for all accented characters after the 60th in my test subject.
I am simply using MimeMessage and setting the subject like that.
`message.Subject = "Retrouvez-nous à la Chaux-Neuve à l’occasion de la Coupe du Monde de Combiné Nordique";`
I am not setting any encoding in the headers, as the body is sent properly with all its accented characters.

Here are my samples, encoded using Mailkit, to show where the problem occurs:
`Retrouvez-nous à la Chaux-Neuve à l’occasion de la Coupe dué Monde de Combiné Nordique`
The first 'é' (60th character) works, the last one doesn't.
`=?utf-8?B?UmV0cm91dmV6LW5vdXMgw6AgbGEgQ2hhdXgtTmV1dmUgw6AgbOKAmW9jY2Fz?=
=?utf-8?B?aW9uIGRlIGxhIENvdXBlIGR1IE1vbmRlIGRlIENvbWJpbu+/vSBOb3JkaXE=?=
=?utf-8?B?dWU=?=`

`Retrouvez-nous à la Chaux-Neuve à l’occasion de la Coupe du éMonde de Combiné Nordique`
The first (61st character) and last 'é' don't work
`=?utf-8?B?UmV0cm91dmV6LW5vdXMgw6AgbGEgQ2hhdXgtTmV1dmUgw6AgbOKAmW9jY2Fz?=
=?utf-8?B?aW9uIGRlIGxhIENvdXBlIGR1IO+/vU1vbmRlIGRlIENvbWJpbu+/vSBOb3Jk?=
=?utf-8?B?aXF1ZQ==?=`

The initial subject is
`Retrouvez-nous à la Chaux-Neuve à l’occasion de la Coupe du Monde de Combiné Nordique`
Encoded using MailKit (with error):
`=?utf-8?B?UmV0cm91dmV6LW5vdXMgw6AgbGEgQ2hhdXgtTmV1dmUgw6AgbOKAmW9jY2Fz?=
=?utf-8?B?aW9uIGRlIGxhIENvdXBlIGR1IE1vbmRlIGRlIENvbWJpbu+/vSBOb3JkaXE=?=
=?utf-8?B?dWU=?=`

Encoded using System.Web.Mail (properly encoded):
`=?utf-8?B?UmV0cm91dmV6LW5vdXMgw6AgbGEgQ2hhdXgtTmV1dmUgw6AgbOKAmW9jY2Fz?=
=?utf-8?B?aW9uIGRlIGxhIENvdXBlIGR1IE1vbmRlIGRlIENvbWJpbsOpIE5vcmRpcXU=?=
=?utf-8?B?ZQ==?=`

**Comment by jstedfast** [comment]
I just released MimeKit 1.0.4 to NuGet this morning with this fix.

**Comment by ThomasCadiou** [comment]
Thank you!

**Comment by krylor** [comment]
This issue has not been resolved as yet, I had to go to the FormatOptions.cs and set the default value as false. Am I missing something here?.

**Comment by jstedfast** [comment]
The fix was to add the option in the first place. That said, I've just changed the default value to false.
