### ISSUE TITLE
GMail Oauth Example does not work

### ISSUE THREAD

**Issue by dolphinsd** [jstedfast/MailKit#1390]
Google removed support for Other type of Oauth clients as described
https://github.com/jstedfast/MailKit/blob/master/GMailOAuth2.md
![screenshot-console cloud google com-2022 06 07-13_17_26](https://user-images.githubusercontent.com/3460517/172474856-ab02ed97-4bd0-4429-8f65-d1a39e8c1b15.png)

When using TV app as a client it fails, and if using web application, LocalServerCodeReceiver would use random port and Error 400: invalid_request
Localhost URI is not allowed for 'NATIVE_DEVICE' client type.

How would someone use MailKit with Gmail in netcore background process for example check gmail inbox every 5 min.

**Comment by jstedfast** [comment]
Did you choose "TVs and Limited Input devices"? Or Desktop app?

The instructions I provided are for Desktop apps (altho that wasn't an option when I wrote the docs).

**Comment by jstedfast** [comment]
You need to read [Google's OAuth documentation](https://developers.google.com/api-client-library/dotnet/guide/aaa_oauth).

The very top of that page lists 3 options:
1. Web application
2. Installed application (this is you)
3. Service account

If you click the "Installed application" link, it takes you to [OAuth 2.0 for Mobile & Desktop Apps](https://developers.google.com/identity/protocols/oauth2/native-app) where it states:

> For apps running on devices that do not support a system browser or that have limited input capabilities, such as TVs, game consoles, cameras, or printers, see [OAuth 2.0 for TVs & Devices](https://developers.google.com/identity/protocols/oauth2/limited-input-device) or [Sign-In on TVs and Limited Input Devices](https://developers.google.com/identity/gsi/web/guides/devices).

I recommend reading those guides :)

**Comment by dolphinsd** [comment]
@jstedfast while you close the issue, using TV and Limited Input Device does not work!

**Comment by jstedfast** [comment]
If you get the correct OAuth2 access token from the Google library, then it will work correctly.

But you need to follow the Google docs to implement getting the OAuth2 access token properly.
