### ISSUE TITLE
Question - how to connect to gmail after May 30, 2022

### ISSUE THREAD

**Issue by BieleckiLtd** [jstedfast/MailKit#1391]
As of May 30, 2022 Google no longer supports the use of third-party apps or devices which ask you to sign in to your Google Account using only your username and password.

How to configure imap client now? Below method fails at `AuthenticateAsync`

```
public async Task<IEnumerable<MimeMessage>> GetMessagesAsync()
{
    using var imapClient = new MailKit.Net.Imap.ImapClient();
    var secureSocketOptions = SecureSocketOptions.Auto;
    if (useSsl) secureSocketOptions = SecureSocketOptions.SslOnConnect;
    await imapClient.ConnectAsync(host, port, secureSocketOptions);

    await imapClient.AuthenticateAsync(login, password);

    await imapClient.Inbox.OpenAsync(FolderAccess.ReadOnly);

    var uids = await imapClient.Inbox.SearchAsync(SearchQuery.All);

    var messages = new List<MimeMessage>();
    foreach (var uid in uids)
    {
        messages.Add(await imapClient.Inbox.GetMessageAsync(uid));
    }

    imapClient.Disconnect(true);

    return messages;
}
```

**Comment by BieleckiLtd** [comment]
Also http://www.mimekit.net/docs/html/Frequently-Asked-Questions.htm#GMailAccess needs updating as it is no longer valid (Google does not allow enabling less secure apps any more)

**Comment by Sueetan** [comment]
For my side, it worked the next section with the OAuth 2, but if the app is still in development, remember to add the account to the test users in the consent screen.

**Comment by jstedfast** [comment]
Sounds like App-specific passwords also works.

**Comment by BieleckiLtd** [comment]
> Sounds like App-specific passwords also works.

Correct, and that's more straightforward solution. More info here: https://stackoverflow.com/a/72551015/3934322

**Comment by jstedfast** [comment]
FWIW, I updated the FAQ.md file last night to suggest App passwords. I haven't updated the website but that's because it's a whole bug-a-boo to regenerate the docs and FTP them up to the hosting service.

I miss the days when I used a web hosting service that hooked into github commits and auto-fetched the updates to the website. Oh well.
