### ISSUE TITLE
Mailkit.dll and Mimekit.dll fail to load in PowerShell 5.1

### ISSUE THREAD

**Issue by ytfj** [jstedfast/MailKit#1392]
Versions 3.2.0 of Mailkit.dll and Mimekit.dll are not supported in Windows PowerShell 5.1? PowerShell 7 can load them, but PowerShell 5.1 will generate the following error.

--- here ---
PS C:\> Add-Type -Path "C:\Program Files\PackageManagement\NuGet\Packages\MimeKit.3.2.0\lib\net48\MimeKit.dll"
Add-Type : Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more
information.
At line:1 char:1
+ Add-Type -Path "C:\Program Files\PackageManagement\NuGet\Packages\Mim ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Add-Type], ReflectionTypeLoadException
    + FullyQualifiedErrorId : System.Reflection.ReflectionTypeLoadException,Microsoft.PowerShell.Commands.AddTypeComma
   nd

PS C:\> Add-Type -Path "C:\Program Files\PackageManagement\NuGet\Packages\MailKit.3.2.0\lib\net48\MailKit.dll"
Add-Type : Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more
information.
At line:1 char:1
+ Add-Type -Path "C:\Program Files\PackageManagement\NuGet\Packages\Mai ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Add-Type], ReflectionTypeLoadException
    + FullyQualifiedErrorId : System.Reflection.ReflectionTypeLoadException,Microsoft.PowerShell.Commands.AddTypeComma
   nd

**Comment by jstedfast** [comment]
Probably because they reference System.Text.Encoding.CodePages.dll and you haven't loaded that or something.

Have you seen https://github.com/EvotecIT/Mailozaurr? That's a MimeKit/MailKit powershell project.
