### ISSUE TITLE
Fix errors on `ImapExamples` in `MailKit.Documentation` solution

### ISSUE THREAD

**Issue by mohabbati** [jstedfast/MailKit#1395]
There are some errors in `ImapExamples` class as follows:

- `quota.StorageLimit.Value` and `quota.MessageLimit.Value` in `if` statements in `Capabilities` method are redundant.
- `baseDirectory` in `DownloadBodyParts` method is not defined and set.
- In the `ProtocolLogger` section the example method name has an error and needs to rename the method.

**Comment by jstedfast** [comment]
I fixed the first 2 issues, but are you trying to compile ImapExamples.cs?

It's not meant to be compiled. It's just a source for extracting regions to put into the documentation.

**Comment by mohabbati** [comment]
I pulled again and the problems have been solved. About the last one as you said is ok.
