### ISSUE TITLE
Gmail IMAP Client Folder related commands are currently super slow?

### ISSUE THREAD

**Issue by GameHackerPM** [jstedfast/MailKit#1396]
Previously, it was working great and very fast like retrieving the emails in like 3-5 seconds max with authenticating and opening folder/label as well. Recently I noticed after Gmail decided to stop "Less Secure Apps" and now I'm using the password app from Gmail after activating my 2-step verification code feature. It's really super slow now to authenticate or opening the folder! It takes like 2-3 minutes now instead of 3-5 seconds. It's really huge difference! I'm not sure from where exactly is the issue, if it's from Gmail or miss coding it. Or from MailKit itself. Idk need help!

**Platform (please complete the following information):**
 - OS: Windows
 - .NET Runtime: CoreCLR
 - .NET Framework: .NET Core 6.0
 - MailKit Version: 3.3.0
 - Project: ASP.NET MVC Core

**Exception**
It happened one time only which got this exception randomly after some time: 
`Error The IMAP server has unexpectedly disconnected.    at MailKit.Net.Imap.ImapStream.ReadAheadAsync(Int32 atleast, CancellationToken cancellationToken)\r\n   at MailKit.Net.Imap.ImapStream.ReadTokenAsync(String specials, CancellationToken cancellationToken)\r\n   at MailKit.Net.Imap.ImapCommand.StepAsync(Boolean doAsync)\r\n   at MailKit.Net.Imap.ImapEngine.IterateAsync(Boolean doAsync)\r\n   at MailKit.Net.Imap.ImapEngine.RunAsync(ImapCommand ic, Boolean doAsync)\r\n   at MailKit.Net.Imap.ImapFolder.OpenAsync(ImapCommand ic, FolderAccess access, Boolean doAsync, CancellationToken cancellationToken)\r\n   at RichardToolsCore.Controllers.EmailGrabberController.<>c.<<EmailGrabber>b__1_0>d.MoveNext()`

**To Reproduce**
1. Just try to connect to Gmail Account via IMAP.
2. Open Folder/Label.
3. Search for emails inside.

Each step from above will take a lot of time. Event *Disconnecting* from IMAPClient took like 5-10 seconds.

**Expected behavior**
It should be way faster than that like usually take 3-5 seconds instead of 2-3 minutes.

**Code Snippets**
If applicable, add code snippets to help explain your problem.

```csharp
                                await GlobalVariables.MailClient.ConnectAsync("imap.gmail.com", 993, true);
                                GlobalVariables.MailClient.AuthenticationMechanisms.Remove("XOAUTH2");
                                await GlobalVariables.MailClient.AuthenticateAsync("email@gmail.com", "pw");
                                var aFolder = await GlobalVariables.MailClient.GetFolderAsync("LabelX1");
                                var aFolder2 = await GlobalVariables.MailClient.GetFolderAsync("LabelX2");
                                var LastUniqueId = aFolder.UidNext;
                                await aFolder.OpenAsync(FolderAccess.ReadOnly);
                                await aFolder.CheckAsync();
                                 var range = new UniqueIdRange((UniqueId)LastUniqueId, UniqueId.MaxValue);
                                 foreach (var uid in await aFolder.SearchAsync(range, SearchQuery.NotSeen))
                                {
                                       var message = await aFolder.GetMessageAsync(uid);
                                       //Doing some stuff with the message
                                       await aFolder.AddFlagsAsync(uid, MessageFlags.Seen, true);
                                 }
                                 LastUniqueId = aFolder.UidNext;
                                 
                                  await aFolder2.OpenAsync(FolderAccess.ReadOnly);
                                  var LastUniqueId2 = aFolder2.UidNext;
                                await aFolder2.CheckAsync();
                                 var range = new UniqueIdRange((UniqueId)LastUniqueId2, UniqueId.MaxValue);
                                 foreach (var uid in await aFolder2.SearchAsync(range, SearchQuery.NotSeen))
                                {
                                       var message = await aFolder2.GetMessageAsync(uid);
                                       //Doing some stuff with the message
                                       await aFolder2.AddFlagsAsync(uid, MessageFlags.Seen, true);
                                 }
                                 LastUniqueId2 = aFolder2.UidNext;
```
Looping that code every 3 seconds for some period of time.

**Protocol Logs**

> Connected to imaps://imap.gmail.com:993/
> S: * OK Gimap ready for requests from 197.49.123.47 x2mb241876667wmk
> C: A00000000 CAPABILITY
> S: * CAPABILITY IMAP4rev1 UNSELECT IDLE NAMESPACE QUOTA ID XLIST CHILDREN X-GM-EXT-1 XYZZY SASL-IR AUTH=XOAUTH2 AUTH=PLAIN AUTH=PLAIN-CLIENTTOKEN AUTH=OAUTHBEARER AUTH=XOAUTH
> S: A00000000 OK Thats all she wrote! x2mb241876667wmk
> C: A00000001 AUTHENTICATE PLAIN ********
> S: * CAPABILITY IMAP4rev1 UNSELECT IDLE NAMESPACE QUOTA ID XLIST CHILDREN X-GM-EXT-1 UIDPLUS COMPRESS=DEFLATE ENABLE MOVE CONDSTORE ESEARCH UTF8=ACCEPT LIST-EXTENDED LIST-STATUS LITERAL- SPECIAL-USE APPENDLIMIT=35651584
> S: A00000001 OK xyz@gmail.com authenticated (Success)
> C: A00000002 NAMESPACE
> S: * NAMESPACE (("" "/")) NIL NIL
> S: A00000002 OK Success [THROTTLED]
> C: A00000003 LIST "" "INBOX" RETURN (SUBSCRIBED CHILDREN)
> S: * LIST (\HasNoChildren \Subscribed) "/" "INBOX"
> S: A00000003 OK Success [THROTTLED]
> C: A00000004 LIST (SPECIAL-USE) "" "*" RETURN (SUBSCRIBED CHILDREN)
> S: * LIST (\All \HasNoChildren \Subscribed) "/" "[Gmail]/All Mail"
> S: * LIST (\Drafts \HasNoChildren \Subscribed) "/" "[Gmail]/Drafts"
> S: * LIST (\HasNoChildren \Sent \Subscribed) "/" "[Gmail]/Sent Mail"
> S: * LIST (\HasNoChildren \Junk \Subscribed) "/" "[Gmail]/Spam"
> S: * LIST (\Flagged \HasNoChildren \Subscribed) "/" "[Gmail]/Starred"
> S: * LIST (\HasNoChildren \Subscribed \Trash) "/" "[Gmail]/Trash"
> S: A00000004 OK Success [THROTTLED]
> C: A00000005 LIST "" "[Gmail]" RETURN (SUBSCRIBED CHILDREN)
> S: * LIST (\HasChildren \NonExistent \Subscribed) "/" "[Gmail]"
> S: A00000005 OK Success [THROTTLED]
> C: A00000006 LIST "" LabelX1 RETURN (SUBSCRIBED CHILDREN)
> S: * LIST (\HasNoChildren \Subscribed) "/" "LabelX1"
> S: A00000006 OK Success [THROTTLED]
> C: A00000007 LIST "" LabelX2 RETURN (SUBSCRIBED CHILDREN)
> S: * LIST (\HasNoChildren \Subscribed) "/" "LabelX2"
> S: A00000007 OK Success [THROTTLED]
> C: A00000008 EXAMINE LabelX1 (CONDSTORE)
> S: * FLAGS (\Answered \Flagged \Draft \Deleted \Seen $NotPhishing $Phishing)
> S: * OK [PERMANENTFLAGS ()] Flags permitted.
> S: * OK [UIDVALIDITY 16] UIDs valid.
> S: * 997 EXISTS
> S: * 0 RECENT
> S: * OK [UIDNEXT 39502] Predicted next UID.
> S: * OK [HIGHESTMODSEQ 30710793]
> S: A00000008 OK [READ-ONLY] LabelX1 selected. (Success) [THROTTLED]
> C: A00000009 EXAMINE LabelX2 (CONDSTORE)
> S: * FLAGS (\Answered \Flagged \Draft \Deleted \Seen $NotPhishing $Phishing)
> S: * OK [PERMANENTFLAGS ()] Flags permitted.
> S: * OK [UIDVALIDITY 18] UIDs valid.
> S: * 2 EXISTS
> S: * 0 RECENT
> S: * OK [UIDNEXT 3] Predicted next UID.
> S: * OK [HIGHESTMODSEQ 30710793]
> S: A00000009 OK [READ-ONLY] LabelX2 selected. (Success) [THROTTLED]
> C: A00000010 SELECT LabelX1 (CONDSTORE)
> S: * FLAGS (\Answered \Flagged \Draft \Deleted \Seen $NotPhishing $Phishing)
> S: * OK [PERMANENTFLAGS (\Answered \Flagged \Draft \Deleted \Seen $NotPhishing $Phishing \*)] Flags permitted.
> S: * OK [UIDVALIDITY 16] UIDs valid.
> S: * 997 EXISTS
> S: * 0 RECENT
> S: * OK [UIDNEXT 39502] Predicted next UID.
> S: * OK [HIGHESTMODSEQ 30710793]
> S: A00000010 OK [READ-WRITE] LabelX1 selected. (Success) [THROTTLED]
> C: A00000011 CHECK
> S: A00000011 OK Success [THROTTLED]
> C: A00000012 UID SEARCH RETURN (ALL) UID 39502:* UNSEEN
> S: * ESEARCH (TAG "A00000012") UID
> S: A00000012 OK SEARCH completed (Success) [THROTTLED]
> C: A00000013 SELECT LabelX2 (CONDSTORE)
> S: * FLAGS (\Answered \Flagged \Draft \Deleted \Seen $NotPhishing $Phishing)
> S: * OK [PERMANENTFLAGS (\Answered \Flagged \Draft \Deleted \Seen $NotPhishing $Phishing \*)] Flags permitted.
> S: * OK [UIDVALIDITY 18] UIDs valid.
> S: * 2 EXISTS
> S: * 0 RECENT
> S: * OK [UIDNEXT 3] Predicted next UID.
> S: * OK [HIGHESTMODSEQ 30710793]
> S: A00000013 OK [READ-WRITE] LabelX2 selected. (Success) [THROTTLED]
> C: A00000014 CHECK
> S: A00000014 OK Success [THROTTLED]
> C: A00000015 UID SEARCH RETURN (ALL) UID 3:* UNSEEN
> S: * ESEARCH (TAG "A00000015") UID
> S: A00000015 OK SEARCH completed (Success) [THROTTLED]
> C: A00000016 LOGOUT
> S: * BYE LOGOUT Requested
> S: A00000016 OK 73 good day (Success) [THROTTLED]

Thanks for your time.

**Comment by ekalchev** [comment]
Nothing to do with Mailkit. GMail is throttling you connections. This happens when you send too many imap commands in 24 hours or receive too much data. You can google it and find more information.

**Comment by GameHackerPM** [comment]
> Nothing to do with Mailkit. GMail is throttling you connections. This happens when you send too many imap commands in 24 hours or receive too much data. You can google it and find more information.

Thanks for the info, I was doing a lot of researches in the wrong path, but I found it after I just submit the issue! I understood now it's because I'm doing a lot of requests and receiving a lot of emails in 24hrs! I also found @jstedfast submitted an IdleClient which is very good in my situation, but I was wondering with one thing about it. If I have more than 1 folder (Not inbox) I need to open each folder before I try to fetch them in IdleClient, which I think may occur some other issues so far. I tried to do get multiple folders but I see it require a namespace, tbh I don't know what is it yet, but will do more searches about it.

Is there a way to see my current usage of Google APIs so I can monitor how much I use and with which step exactly do I spam it?!

**Comment by jstedfast** [comment]
I'm not aware of anywhere to monitor usage, unfortunately and I haven't seen an IMAP protocol extension for it (but new ones come out all the time).

As you were hinting at in your question, the IDLE command is really only good for 1 folder at a time.

The namespaces are client.PersonalNamespaces, SharedNamespaces, and OtherNamespaces.

In most cases, all you ever really see is 1 PersonalNamespace and the others are typically empty. This is the way it is with GMail.

```csharp
var root = client.GetFolder (client.PersonalNamespaces[0]);
var subfolders = root.GetSubfolders ();
```
