### ISSUE TITLE
Can I use the repo to delete all emails in inbox folder?

### ISSUE THREAD

**Issue by zydjohnHotmail** [jstedfast/MailKit#1399]
Hello:
I can use the repo to retrieve all emails from inbox by IMAP, which seems to be easy.
But I can't find any simple way to delete all the email in the inbox folder.  For most of the email servers, the inbox is the only folder.
I have quite a number of emails on different email servers.  So I want to write a simple program I can run every week or every month, it just simply deletes all the emails from inbox folder without reading contents or titles of any emails.
Can you show me some simple code to do this without complicated query statement.
Thanks,

**Comment by jstedfast** [comment]
```csharp
var uids = new UniqueIdRange (UniqueId.MinValue, UniqueId.MaxValue);
inbox.AddFlags (uids, MessageFlags.Deleted, true);
inbox.Expunge ();
```

**Comment by jstedfast** [comment]
```csharp
inbox.Open(FolderAccess.ReadWrite);
var uids = new UniqueIdRange (UniqueId.MinValue, UniqueId.MaxValue);
inbox.AddFlags (uids, MessageFlags.Deleted, true);
inbox.Expunge ();
```
