### ISSUE TITLE
SmtpClient.Timeout seems to be ignored by ConnectAsync

### ISSUE THREAD

**Issue by fschmied** [jstedfast/MailKit#1402]
**Describe the bug**
Since switching from .NET's own `System.Net.Mail.SmtpClient` to MailKit, we've been getting intermittent `SslHandshakeExceptions` that (indirectly) contain a `SocketException` which in turn indicates a timeout (_"A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."_) when calling `SmtpClient.ConnectAsync`. This probably indicates some network issue or the server being down (retrying resolves the problem), although it's strange that it didn't show with the old SmtpClient. Anyway, the issue I want to report is that this exception is thrown after about 21 seconds even though the `SmtpClient.Timeout` property is at its default value of 120000 ms.

**Platform (please complete the following information):**
 - OS: Windows
 - .NET Runtime: CoreCLR (.NET 6.0.6)
 - .NET Framework: .NET 6
 - MailKit Version: 3.2.0 (similar repro in 3.3.0, see below)

**Exception**
```
MailKit.Security.SslHandshakeException: An error occurred while attempting to establish an SSL or TLS connection.

This usually means that the SSL certificate presented by the server is not trusted by the system for one or more of
the following reasons:

1. The server is using a self-signed certificate which cannot be verified.
2. The local system is missing a Root or Intermediate certificate needed to verify the server's certificate.
3. A Certificate Authority CRL server for one or more of the certificates in the chain is temporarily unavailable.
4. The certificate presented by the server is expired or invalid.
5. The set of SSL/TLS protocols supported by the client and server do not match.
6. You are trying to connect to a port which does not support SSL/TLS.

See https://github.com/jstedfast/MailKit/blob/master/FAQ.md#SslHandshakeException for possible solutions.

 ---> System.IO.IOException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
 ---> System.Net.Sockets.SocketException (10060): A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
   at MailKit.Net.NetworkStream.ReadAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken) in D:\src\MailKit\MailKit\Net\NetworkStream.cs:line 206
   --- End of inner exception stack trace ---
   at MailKit.Net.NetworkStream.ReadAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken) in D:\src\MailKit\MailKit\Net\NetworkStream.cs:line 206
   at System.Net.Security.SslStream.<FillHandshakeBufferAsync>g__InternalFillHandshakeBufferAsync|187_0[TIOAdapter](TIOAdapter adap, ValueTask`1 task, Int32 minSize)
   at System.Net.Security.SslStream.ReceiveBlobAsync[TIOAdapter](TIOAdapter adapter)
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
   at MailKit.Net.Smtp.SmtpClient.ConnectAsync(String host, Int32 port, SecureSocketOptions options, Boolean doAsync, CancellationToken cancellationToken) in D:\src\MailKit\MailKit\Net\Smtp\SmtpClient.cs:line 1418
   --- End of inner exception stack trace ---
   at MailKit.Net.Smtp.SmtpClient.ConnectAsync(String host, Int32 port, SecureSocketOptions options, Boolean doAsync, CancellationToken cancellationToken) in D:\src\MailKit\MailKit\Net\Smtp\SmtpClient.cs:line 1418
   ...
```

**To Reproduce**
Unfortunately, I can't provide an easy repro for exactly this exception, but I can reproduce a similar behavior by running this snippet in either 3.2.0 or 3.3.0:
```
using var smtpClient = new SmtpClient();
await smtpClient.ConnectAsync("google.com", 5000, MailKit.Security.SecureSocketOptions.SslOnConnect, CancellationToken.None);
```

As Google won't respond on port 5000, this will produce a `SocketException` with the same message (_"A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."_) after roughly 21 seconds (on my machine). So, it probably occurs a bit earlier in `ConnectAsync` than my original problem, but it demonstrates the short timeout.

**Expected behavior**
Ideally, the `SmtpClient.Timeout` would apply here, or the `SmtpClient` would somehow be more resilient to this kind of error so the timeout wouldn't be needed.

**Protocol Logs**
The log file produced by `ProtocolLogger` is empty.

**Comment by jstedfast** [comment]
The stacktrace indicates that the client connected just fine but that the SslStream's handshake timed out.

**Comment by jstedfast** [comment]
Here's how this code works:

* SmtpClient calls [SocketUtils.ConnectAsync](https://github.com/jstedfast/MailKit/blob/master/MailKit/Net/SocketUtils.cs#L95) with the SmtpClient.Timeout value which creates an artificial timeout-based CancellationTokenSource because the ReceiveTimeout and SendTimeout properties on the Socket do not change Socket.Connect* behavior.
* Once that connects, the SendTimeout and ReceiveTimeout properties on the socket are set.
* If SslOnConnect is specified, SmtpClient will then wrap the NetworkStream in an SslStream and call AuthenticateAsClient() (or the Async equiv).

This is the part that is failing for you.

**Comment by fschmied** [comment]
@jstedfast Sure; I raised this as a bug in Mailkit because I thought that the `SmtpClient.Timeout` property was meant to affect `Connect(Async)`, too. However, if I understand correctly, as it is implemented using a `CancellationToken`, the timeout can only _reduce_  the connection timeout, not _increase_ it?

**Comment by fschmied** [comment]
@jstedfast  Let me ask just one more follow-up question regarding the analysis of my original stack trace you posted above (thanks a lot!):

> * SmtpClient calls [SocketUtils.ConnectAsync](https://github.com/jstedfast/MailKit/blob/master/MailKit/Net/SocketUtils.cs#L95) with the SmtpClient.Timeout value which creates an artificial timeout-based CancellationTokenSource because the ReceiveTimeout and SendTimeout properties on the Socket do not change Socket.Connect* behavior.
> * Once that connects, the SendTimeout and ReceiveTimeout properties on the socket are set.
> * If SslOnConnect is specified, SmtpClient will then wrap the NetworkStream in an SslStream and call AuthenticateAsClient() (or the Async equiv).

So, in my original case, `SocktUtils.ConnectAsync` is able to successfully create a socket connection, but `AuthenticateAsClient` then times out on the socket, right? This seems interesting (especially as this wasn't a one-time fluke, but happens every two weeks or so in our specific setup). With your experience and knowledge of the things happening there, have you any quick idea why that might be the case?

**Comment by fschmied** [comment]
> A Socket.Connect() timing out in 21s seems ridiculously short to me, so I can't understand why that is happening.

This seems to be some Windows default for the initial TCP handshake: https://github.com/dotnet/runtime/issues/28909#issuecomment-470951041 . So MailKit probably can't do much about it, apart from maybe documenting that the `Timeout` property will only _shorten_ the initial TCP connection's timeout, not extend it.

I still don't know exactly why we'd be getting a TCP handshake error while reading from the already established connection - if I understand correctly, the MailKit's NetworkStream should have finished establishing its TCP connection during `AuthenticateAsClient`.

> I think there must be a bug in the Socket class or something.

I see that `NetworkStream` is reusing the `SocketAsyncEventArgs recv` object; maybe the error isn't from that current `ReadAsync` call at all, but from a previous operation? But I don't know the MailKit code well enough.

Anyway, we'll deal with this issue by manually retrying.

Thanks a lot for the analysis!

**Comment by jstedfast** [comment]
FWIW, I think the timeout still makes a difference on Linux/MacOS, but yea, it looks like on Windows, it's 21s no matter what we do.

> I still don't know exactly why we'd be getting a TCP handshake error while reading from the already established connection - if I understand correctly, the MailKit's NetworkStream should have finished establishing its TCP connection during AuthenticateAsClient.

Correct - NetworkStream.ReadAsync() is not happening during the Connect phase - it happens *after*.

Maybe the 21s is hard-coded on Windows there, too?

> I see that NetworkStream is reusing the SocketAsyncEventArgs recv object; maybe the error isn't from that current ReadAsync call at all, but from a previous operation? But I don't know the MailKit code well enough.

No, I'm pretty confident that's not the case.
