### ISSUE TITLE
set_InReplyTo not accepting Message-Id from a real message

### ISSUE THREAD

**Issue by ipostanogov** [jstedfast/MailKit#1407]
**Describe the bug**
Passing a `MessageId` which was extracted from a real message to `set_InReplyTo` leads to ArgumentException.

**Platform (please complete the following information):**
 - OS: Linux
 - .NET Runtime: CoreCLR
 - .NET Framework: .Net Core 3.1
 - MailKit Version: 3.3.0
 - Email provider: Yandex

**Exception**
```
      [ErrorMsg System.ArgumentException: Invalid Message-Id format. (Parameter 'value')
         at MimeKit.MimeMessage.set_InReplyTo(String value)
```

**To Reproduce**
```csharp
            var emailMessageToSend = new MimeMessage();
            emailMessageToSend.InReplyTo = "20220720005922.0000000004E@";
```

**Expected behavior**
No error.

**Additional context**
The constant from the sample was extracted via `originalMessage.MessageId`. I've checked the source of the message from which the `MessageId` was extracted:

![image](https://user-images.githubusercontent.com/2305983/179908923-dd0f1f10-2e91-421b-8500-9667ea39916e.png)

The code constructing in-reply-to works for years with the same email provider and we've never seen this error before.

**Comment by jstedfast** [comment]
That message-id is invalid.

Bypass the InReplyTo property and set the header directly:

```csharp
message.Headers.Add ("In-Reply-To", "<20220720005922.0000000004E@>");
```

The purpose of the MimeMessage properties is to validate the inputs to make sure they are valid. This value is not syntactically valid.
