### ISSUE TITLE
Performance issue

### ISSUE THREAD

**Issue by M1z23R** [jstedfast/MailKit#1410]
When working with older Gmail accounts, and with it, using search after query, it seems like it's working in following way:
Initially it's gathering message id's of entire folder, then filtering out message id's in regard to it's date.

Correct me if I am wrong, but downloading for example 100 emails for today for a new account takes way less time then picking out 100 emails from today with inbox having 3000 emails + over all time.

If I am not clear feel free to ask me for some more details.

**Comment by jstedfast** [comment]
That will all depend on the SEARCH implementation of the server.

Or am I misunderstanding your question?

**Comment by M1z23R** [comment]
Well, looking at the code now (Sorry I didn't do it before posting), it's working as it should - asking the server to return messages  SINCE xxx, I believed it was due to something else. But now I am even more confused as to why does it seem to work slower on older (bigger folders) accounts.

**Comment by M1z23R** [comment]
How would I search for messages newer then certain unique ID message ?
Since Uids query requires a list of Uids.

All and all, I would like to setup search query to return the same as following: "SEARCH UID 1000:*"

**Comment by jstedfast** [comment]
you can use a UniqueIdRange to represent a list of UIDs:

```csharp
var range = new UniqueIdRange (new UniqueId (1000), UniqueId.MaxValue);
```

**Comment by M1z23R** [comment]
Works like a charm, thank you very much.
