### ISSUE TITLE
Question: Shared Mailbox XOAUTH2 Access

### ISSUE THREAD

**Issue by raphaelfrei** [jstedfast/MailKit#1412]
### Hi team!
I have some questions regarding the following article from [Microsoft Documentation](https://docs.microsoft.com/en-us/exchange/client-developer/legacy-protocols/how-to-authenticate-an-imap-pop-smtp-application-by-using-oauth):

> In case of shared mailbox access using OAuth, application needs to obtain the access token on behalf of a user but replace the userName field in the SASL XOAUTH2 encoded string with the email address of the shared mailbox.

And I'm curious about what should I do...
My currently possition is with this error:

> ERROR - While logging in: MailKit.Security.AuthenticationException: Authentication failed. 
> at MailKit.Net.Imap.ImapClient.d__101.MoveNext() 
> --- End of stack trace from previous location where exception was thrown --- 
> at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) 
> at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) 
> at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task) 
> at PCControl.EMLRC.d__3.MoveNext()

What should I do to obtain the token in my user and then replace to my shared mailbox?

```csharp
            try {
                    
                var options = new ConfidentialClientApplicationOptions {
                    ClientId = "my_client_id",
                    TenantId = "my_ten_id",
                    RedirectUri = "https://login.microsoftonline.com/common/oauth2/nativeclient",
                    ClientSecret = secret //obtained through .txt file
                };


                var scopes = new string[] {
                "https://graph.microsoft.com/.default",
                };

                var confidentialClientApplication = ConfidentialClientApplicationBuilder
                    .Create(options.ClientId)
                    .WithClientSecret(options.ClientSecret)
                    .WithAuthority(new Uri($"https://login.microsoftonline.com/{options.TenantId}/"))
                .Build();
  
                string userName = "sharedmailbox@company.com";
                //tried with myuser@company.com as well

                var authToken = await confidentialClientApplication.AcquireTokenForClient(scopes).ExecuteAsync();

                var oauth2 = new SaslMechanismOAuth2(userName, authToken.AccessToken);

                using (var client = new ImapClient(new ProtocolLogger(@"imap.log"))) {
                    //server is mail.mycompany.com and port I'm using 993
                    client.Connect(server, port, SecureSocketOptions.SslOnConnect);

                    //client.AuthenticationMechanisms.Remove("XOAUTH2");

                    await client.AuthenticateAsync(oauth2);

                    client.Inbox.Open(FolderAccess.ReadWrite);

                    var inbox = client.Inbox;

                    var uids = client.Inbox.Search(SearchQuery.NotSeen);

                    foreach (var uid in uids) {
                        var message = client.Inbox.GetMessage(uid);           

                        var subject = message.Subject;
                        message.WriteTo($"{save}\\{subject}.eml");

                        num++;
                        str2 = str2 + subject.ToString() + (char)13;
                        str1 = $"SUCCESS - Saved {num} email{(num == 1 ? '\0' : 's')}: {(char)13}{(char)13}{str2}";

                    }

                    inbox.AddFlags(uids, MessageFlags.Seen, true);
                    client.Disconnect(true);
                }

            } catch (System.Exception ex) {
                str1 = $"ERROR - While logging in: {ex}";

            }
```

My IMAP.log:

```
Connected to imaps://outlook.office365.com:993/
S: * OK The Microsoft Exchange IMAP4 service is ready. [QgBOADkAUABSADAXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX]
C: A00000000 CAPABILITY
S: * CAPABILITY IMAP4 IMAP4rev1 AUTH=PLAIN AUTH=XOAUTH2 SASL-IR UIDPLUS MOVE ID UNSELECT CHILDREN IDLE NAMESPACE LITERAL+
S: A00000000 OK CAPABILITY completed.
C: A00000001 AUTHENTICATE XOAUTH2 ********
S: A00000001 NO AUTHENTICATE failed.
Connected to imaps://outlook.office365.com:993/
S: * OK The Microsoft Exchange IMAP4 service is ready. [QgBOADAAUABSADAANXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX]
C: A00000000 CAPABILITY
S: * CAPABILITY IMAP4 IMAP4rev1 AUTH=PLAIN AUTH=XOAUTH2 SASL-IR UIDPLUS MOVE ID UNSELECT CHILDREN IDLE NAMESPACE LITERAL+
S: A00000000 OK CAPABILITY completed.
C: A00000001 AUTHENTICATE XOAUTH2 ********
S: A00000001 NO AUTHENTICATE failed.
Connected to imap://outlook.office365.com:993/?starttls=when-available
Connected to imap://outlook.office365.com:993/?starttls=when-available
Connected to imap://outlook.office365.com:993/?starttls=when-available
Connected to imap://outlook.office365.com:993/?starttls=when-available
Connected to imap://outlook.office365.com:993/?starttls=when-available
Connected to imap://outlook.office365.com:993/?starttls=when-available
Connected to imap://outlook.office365.com:993/?starttls=when-available
Connected to imap://outlook.office365.com:993/?starttls=when-available
Connected to imap://outlook.office365.com:993/?starttls=when-available
Connected to imap://outlook.office365.com:993/?starttls=when-available
Connected to imap://outlook.office365.com:993/?starttls=when-available
Connected to imap://outlook.office365.com:993/?starttls=when-available
Connected to imap://outlook.office365.com:993/?starttls=when-available
Connected to imap://outlook.office365.com:993/?starttls=when-available
Connected to imap://outlook.office365.com:993/?starttls=when-available
Connected to imap://outlook.office365.com:993/?starttls=when-available
Connected to imap://outlook.office365.com:993/?starttls=when-available
Connected to imap://outlook.office365.com:993/?starttls=when-available
Connected to imap://outlook.office365.com:993/?starttls=when-available
Connected to imaps://mail.company.com:993/
S: * OK The Microsoft Exchange IMAP4 service is ready. [RABNADUAUAAxADEANgBDAXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX]
C: A00000000 CAPABILITY
S: * CAPABILITY IMAP4 IMAP4rev1 AUTH=PLAIN AUTH=XOAUTH2 SASL-IR UIDPLUS ID UNSELECT CHILDREN IDLE NAMESPACE LITERAL+
S: A00000000 OK CAPABILITY completed.
C: A00000001 AUTHENTICATE XOAUTH2 ********
S: A00000001 NO AUTHENTICATE failed.

```

**Comment by jstedfast** [comment]
You need to use `myuser@company.com\sharedmailbox` where `sharedmailbox` is the alias of the shared mailbox, so if the shared mailbox is `user-feedback@company.com`, then you'd use `myuser@company.com\user-feedback`

**Comment by raphaelfrei** [comment]
Hi jstedfast! I've managed to fix this issue, but I'm stuck on another error... All accounts inside the company has 2FA, can this be the issue here?

I'm having this error when I tried to login with the security key:

> MSAL.Desktop.4.45.0.0.MsalClientException: 
> ErrorCode: parsing_wstrust_response_failed
> Microsoft.Identity.Client.MsalClientException: There was an error parsing WS-Trust response from the endpoint. This may occur if there is an issue with your ADFS configuration. See https://aka.ms/msal-net-iwa-troubleshooting for more details. Error Message: Federated service at https://mycompany.com/adfs/services/trust/2005/usernamemixed returned error: ID3242: The security token could not be authenticated or authorized. ---> Microsoft.Identity.Client.MsalServiceException: Federated service at https://mycompany.com/adfs/services/trust/2005/usernamemixed returned error: ID3242: The security token could not be authenticated or authorized. 
> at Microsoft.Identity.Client.WsTrust.WsTrustWebRequestManager.d__3.MoveNext() 
> --- End of stack trace from previous location where exception was thrown --- 
> at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) 
> at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) 
> at Microsoft.Identity.Client.WsTrust.CommonNonInteractiveHandler.d__6.MoveNext() 
> --- End of inner exception stack trace --- 
> at Microsoft.Identity.Client.WsTrust.CommonNonInteractiveHandler.d__6.MoveNext() 
> --- End of stack trace from previous location where exception was thrown --- 
> at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) 
> at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) 
> at Microsoft.Identity.Client.WsTrust.CommonNonInteractiveHandler.d__5.MoveNext() 
> --- End of stack trace from previous location where exception was thrown --- 
> at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) 
> at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) 
> at Microsoft.Identity.Client.Internal.Requests.UsernamePasswordRequest.d__4.MoveNext() 
> --- End of stack trace from previous location where exception was thrown --- 
> at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) 
> at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) 
> at Microsoft.Identity.Client.Internal.Requests.UsernamePasswordRequest.d__3.MoveNext() 
> --- End of stack trace from previous location where exception was thrown --- 
> at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) 
> at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) 
> at Microsoft.Identity.Client.Internal.Requests.RequestBase.d__12.MoveNext() 
> --- End of stack trace from previous location where exception was thrown --- 
> at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) 
> at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) 
> at Microsoft.Identity.Client.ApiConfig.Executors.PublicClientExecutor.d__5.MoveNext() 
> --- End of stack trace from previous location where exception was thrown --- 
> at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) 
> at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) 
> at PCControl.EMLRC.d__4.MoveNext() 
> --- End of stack trace from previous location where exception was thrown --- 
> at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) 
> at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) 
> at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task) 
> at PCControl.EMLRC.d__3.MoveNext()
> Inner Exception: MSAL.Desktop.4.45.0.0.MsalServiceException: 
> ErrorCode: federated_service_returned_error
> Microsoft.Identity.Client.MsalServiceException: Federated service at https://mycompany.com/adfs/services/trust/2005/usernamemixed returned error: ID3242: The security token could not be authenticated or authorized. 
> at Microsoft.Identity.Client.WsTrust.WsTrustWebRequestManager.d__3.MoveNext() 
> --- End of stack trace from previous location where exception was thrown --- 
> at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) 
> at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) 
> at Microsoft.Identity.Client.WsTrust.CommonNonInteractiveHandler.d__6.MoveNext()
> StatusCode: 500 
> ResponseBody: http://www.w3.org/2005/08/addressing/soap/faulturn:uuid:33c7a0a0-f946-49a5-8565-d86388ddd5442022-07-28T11:44:09.988Z2022-07-28T11:49:09.988Zs:Sendera:FailedAuthenticationID3242: The security token could not be authenticated or authorized. 
> Headers: Date: Thu, 28 Jul 2022 11:44:09 GMT 
> Server: Microsoft-HTTPAPI/2.0 

I've tried to use my personal password without the Shared Mailbox and it raises the AUTHENTICATION FAILED ERROR

This are the changes I made in the code:

```csharp
private static async Task<string> ReadEmailAsync(string? save, string? server, int port, string? key, string? globalId, string? mailBox) {

            try {

                var options = new PublicClientApplicationOptions {
                    ClientId = "...",
                    TenantId = "...",
                    RedirectUri = "https://login.microsoftonline.com/common/oauth2/nativeclient",
                };

                var scopes = new string[] {
                    "https://outlook.office365.com/.default",
                };

                var pca = PublicClientApplicationBuilder
                    .Create(options.ClientId)
                    .WithAuthority($"https://login.microsoftonline.com/{options.TenantId}/")
                    //.WithRedirectUri("http://localhost")
                    .WithRedirectUri(options.RedirectUri)
                .Build();

                using (var client = new ImapClient(new ProtocolLogger(@"imap.log"))) {

                    client.Connect(server, port, SecureSocketOptions.SslOnConnect);

                    AuthenticationResult authToken = await AzureToken(globalId, key);
                    client.Authenticate(new SaslMechanismOAuth2($"{globalId}@company.com\\{mailBox}", authToken.AccessToken));
                    client.Inbox.Open(FolderAccess.ReadWrite);

                    client.AuthenticationMechanisms.Remove("XOAUTH2");

                    var inbox = client.Inbox;

                    var uids = client.Inbox.Search(SearchQuery.NotSeen);

                    foreach (var uid in uids) {
                        var message = client.Inbox.GetMessage(uid);

                        var subject = message.Subject;
                        message.WriteTo($"{save}\\{subject}.eml");

                        num++;
                        str2 = str2 + subject.ToString() + (char)13;
                        str1 = $"SUCCESS - Saved {num} email{(num == 1 ? '\0' : 's')}: {(char)13}{(char)13}{str2}";

                    }

                    inbox.AddFlags(uids, MessageFlags.Seen, true);
                    client.Disconnect(true);
                }

            } catch (System.Exception ex) {
                str1 = $"ERROR - While logging in: {ex}";

            }

            return str1;

        }

        private static async Task<AuthenticationResult> AzureToken(string globalId, string key) {

            var options = new PublicClientApplicationOptions {
                ClientId = "...",
                TenantId = "...",
                RedirectUri = "https://login.microsoftonline.com/common/oauth2/nativeclient"
            };

            var username = $"{globalId}@company.com";
            var pass = new System.Net.NetworkCredential(username, key).SecurePassword;
            var clients = PublicClientApplicationBuilder.CreateWithApplicationOptions(options).Build();

            var scopes = new string[] {
                "email",
                "offline_access",
                "https://outlook.office365.com/.default",
            };

            return await clients.AcquireTokenByUsernamePassword(scopes, username, pass).ExecuteAsync();
        }
```

**Comment by raphaelfrei** [comment]
On my IMAP.log I have the following status:

> Connected to imaps://mail.company.com:993/
> S: * OK The Microsoft Exchange IMAP4 service is ready. [QgBOADYAUAXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX]
> C: A00000000 CAPABILITY
> S: * CAPABILITY IMAP4 IMAP4rev1 AUTH=PLAIN AUTH=XOAUTH2 SASL-IR UIDPLUS ID UNSELECT CHILDREN IDLE NAMESPACE LITERAL+
> S: A00000000 OK CAPABILITY completed.

**Comment by jstedfast** [comment]
Microsoft.Identity.Client isn't part of MailKit so I'm not sure why you'd expect me to have any idea what the problem could be?

Ask the Microsoft.Identity.Client developers.
