### ISSUE TITLE
Failed to convert the object type "MimeKit.MimePart" to the type "MimeKit.TextPart"

### ISSUE THREAD

**Issue by asdqwe227** [jstedfast/MailKit#1417]
Failed to cast the object type "MimeKit.MimePart" to the type "MimeKit.TextPart".

```
        client.GetFolder("FOLDER").Open(FolderAccess.ReadOnly);

        var uids = client.GetFolder("FOLDER").Search(SearchQuery.DeliveredAfter(parseDateTime));

        var messages = client.GetFolder("FOLDER").Fetch(uids, MessageSummaryItems.Envelope | MessageSummaryItems.BodyStructure);

        if (messages != null && messages.Count > 0)
        {
            foreach (var msg in messages)
            {
                var body = (TextPart)client.GetFolder("FOLDER").GetBodyPart(msg.UniqueId, msg.BodyParts.First());
```

On the last line of the code an error is called (topic name). The catch is that the code works! But for some reason an error popped up when parsing mail for a certain day. How can it be related? Maybe you know another way to get the message body out of the folder?

**Comment by jstedfast** [comment]
Well, the first BodyPart is not always the text body and you are casting whatever it finds to a TextPart which is why you are getting a cast exception.

There are 2 convenience properties: TextBody and HtmlBody that, when non-null, use heuristics to get the text/plain and text/html body parts.

**Comment by asdqwe227** [comment]
Thanks!
