### ISSUE TITLE
Add Xamarin Unified support to nugget package

### ISSUE THREAD

**Issue by vzhusel** [jstedfast/MailKit#142]
Hello,
Is it possible to add Xamarin Unified target to nuget package?

**Comment by jstedfast** [comment]
Yea, now that Unified is in the stable channel I should do this.

**Comment by vzhusel** [comment]
Thanks, do you have ETA?

**Comment by jstedfast** [comment]
Not at the moment, but I can *probably* do it this weekend.

**Comment by jstedfast** [comment]
The 1.0.6.1 nuget packages have been updated to support the Unified API.

**Comment by vzhusel** [comment]
Thank you!
