### ISSUE TITLE
Problem using ImapFolder.GetBodyPart because the documentation maybe is wrong

### ISSUE THREAD

**Issue by NilsHoyer** [jstedfast/MailKit#1426]
I'm trying to get bodyparts with `ImapFolder.GetBodyPart`, documented here:
http://www.mimekit.net/docs/html/M_MailKit_Net_Imap_ImapFolder_GetBodyPart.htm

The first parameter, described on that page, is `UniqueId uid` and as the description is mentioned "The UID of the message."

I can't find a further hint, what "UID" is.

Before of it, I use `ImapClient.Inbox.Fetch` to get information about that message. In the result of the type "ReadOnlyCollection\`1" (I wonder about the backtick in that name...) I have multiple items of the type `MessageSummary`. And inside of it, I have a `UniqueId`.

Is this the `UID` for the `GetBodyPart`?

Or do I have to use `Index`?

If I decompile MailKit.IMailFolder to get the definition of `GetBodyPart`, I see this:

` MimeEntity GetBodyPart(int index, BodyPart part, CancellationToken cancellationToken = default(CancellationToken), ITransferProgress progress = null);
`
Here is the parameter called `index` and not like in the documentation `udi`.

IMHO, there is a bug inside the documentation, because it's not clear what the `UID` is.

**Comment by jstedfast** [comment]
> Is this the UID for the GetBodyPart?

Yes.

> Or do I have to use Index?

No. APIs that want you to use the Index will take an `int index` parameter.

> If I decompile MailKit.IMailFolder to get the definition of GetBodyPart, I see this:
> MimeEntity GetBodyPart(int index, BodyPart part, CancellationToken cancellationToken = default(CancellationToken), ITransferProgress progress = null);
> Here is the parameter called index and not like in the documentation udi.

There are typically at least 2 versions of every API in MailKit's IMAP classes. One that takes a UniqueId (aka UID) and one that takes an index.

You can use either.

Keep in mind that IMAP allows multiple clients to all be accessing the messages at the same time and if 1 client deletes message 9 and your client wants message 10, once message 9 is deleted by the other client, your new index is 9 and not 10 anymore.

Using Index-based APIs is generally a bad idea.

I highly recommend using the UniqueId instead. There are multiple ways to get this value:

1. ImapFolder.Search() returns a list of UniqueIds.
2. ImapFolder.Fetch() will populate the MessageSummary.UniqueId value if (and ONLY if) you specify MessageSummaryItems.UniqueId in the request. e.g.:

```csharp
var items = folder.Fetch (0, -1, MessageSummaryItems.UniqueId | MessageSummaryItems.Envelope | ...);
```

**Comment by jstedfast** [comment]
Uhm...

Probably because you specified an invalid list of indexes?

What, exactly, did your code do?

**Comment by NilsHoyer** [comment]
Sorry to bother you. You are right, it was my problem.

... but I still believe, the word `UID` is wrong inside the documentation...

**Comment by jstedfast** [comment]
I disagree.

**Comment by NilsHoyer** [comment]
Ok, you are igorant.
