### ISSUE TITLE
ImapFolder.GetBodyPart is not implemented with PartSpecifier

### ISSUE THREAD

**Issue by NilsHoyer** [jstedfast/MailKit#1427]
**Platform:**
 - OS: Windows 10
 - .NET Framework: .NET 4.8
 - MailKit Version: 3.4.0, installed via NuGet

I would like to use `ImapFolder.GetBodyPart` with **`partSpecifier`**:

`ImapFolder.GetBodyPart(
	UniqueId uid,
	string partSpecifier,
	CancellationToken cancellationToken = default,
	ITransferProgress progress = null
)`

... like described [here](http://www.mimekit.net/docs/html/M_MailKit_Net_Imap_ImapFolder_GetBodyPart_1.htm)

But it's not implemented, if I'm right. I can only access it with **`BodyPart`**.

**Comment by jstedfast** [comment]
The documentation is generated from the code. It is there.

You need to cast to an ImapFolder.

**Comment by NilsHoyer** [comment]
Until now, I worked with `ImapClient.Inbox`. And there I still can't find a way to use a `partSpecifier`.

But for me, it looks like, you are not interested to fix bugs on your end. Am I right?

**Comment by NilsHoyer** [comment]
Ahh…

I can't use `ImapClient.Inbox.GetBodyPart`, I have to use `(ImapClient.Inbox as ImapFolder).GetBodyPart`.
