### ISSUE TITLE
The size (Octets) of BodyPartBasic does not show the final file size

### ISSUE THREAD

**Issue by NilsHoyer** [jstedfast/MailKit#1428]
**Platform:**
 - OS: Windows 10
 - .NET Framework: .NET 4.8
 - MailKit Version: 3.4.0, installed via NuGet

I'm using `ImapClient.Inbox.Fetch(myUniqueIds, MessageSummaryItems.Headers | MessageSummaryItems.Size | MessageSummaryItems.BodyStructure);` to get a list of attachments in a mail.

As the response, I get a [`MessageSummary`](http://www.mimekit.net/docs/html/T_MailKit_MessageSummary.htm) for each mail with a [`BodyPartBasic`](http://www.mimekit.net/docs/html/T_MailKit_BodyPartBasic.htm) for each attachment.

Inside of it, I have `Octets`, which are described with _"Gets the size of the body part, in bytes."_, but in my case, I get for a (text) attachment a value of `Octets` with **1584** by a file with **1,156** Bytes.

Inside the source code of the mail, I have the following header of this attachment:
`Content-Type: text/plain; name="MyFile.txt"`
`Content-Transfer-Encoding: base64`
`Content-Disposition: attachment; filename="MyFile.txt"`

I would like to have the **final file size** of that attachment.

**Comment by jstedfast** [comment]
Please stop wasting my time.

The Octet count comes from the IMAP server.

MailKit cannot get the "final byte count" that you want without downloading the message.

Instead of using Fetch(), just use GetMessage() for each message and calculate the size yourself.

**Comment by NilsHoyer** [comment]
I waste your time?

I'm sorry, but if your documentation is wrong (and it is!!!), you are wasting my time!!!

**Comment by NilsHoyer** [comment]
You are fighting against me, do you recognize this?
