### ISSUE TITLE
MailFolder.Search(SearchQuery.All) does not show new mails

### ISSUE THREAD

**Issue by NilsHoyer** [jstedfast/MailKit#1431]
I'm trying to use IDLE.

First, I read the available message with `MailFolder.Search(SearchQuery.All)`. After this, I receive a new message.

If I'm right, the only way to be informed about a new mail is using `MailFolder.CountChanged`. Right?

I can get these events, but if I run `MailFolder.Search(SearchQuery.All)` after this, I do not get the new mail.

What is my mistake?

**Comment by jstedfast** [comment]
It sounds like a bug in the IMAP server.

But let me make sure that I am understanding the situation correctly:

You do:

```csharp
var matches = folder.Search (SearchQuery.All);
```

This is returning all of the current messages for you correctly so far.

Afterward you received a CountChanged event signifying a new message has arrived?

And then you do another `folder.Search (SearchQuery.All);` and it returns the exact same results as before?

**Comment by NilsHoyer** [comment]
Yes, you understood me well.

I deleted all mails from that mailbox and started my app new with a IDLE, running in separate thread.

Then I sent a mail to that mailbox, my app detected it and started a new search.

This is the protocol of it:

```
Connected to imap://mail.my-server.xyz:143/?starttls=always
S: * OK [CAPABILITY IMAP4 IMAP4rev1 STARTTLS UIDPLUS CHILDREN NAMESPACE THREAD=ORDEREDSUBJECT THREAD=REFERENCES SORT QUOTA IDLE ACL ACL2=UNION] perdition ready on fd00:dead:beef:1234::10 00041cfa
C: A00000000 STARTTLS
S: A00000000 OK Begin TLS negotiation now
C: A00000001 CAPABILITY
S: * CAPABILITY IMAP4 IMAP4rev1 UIDPLUS CHILDREN NAMESPACE THREAD=ORDEREDSUBJECT THREAD=REFERENCES SORT QUOTA IDLE ACL ACL2=UNION
S: A00000001 OK CAPABILITY
C: A00000002 LOGIN ******** ********
S: * CAPABILITY IMAP4rev1 SASL-IR LOGIN-REFERRALS ID ENABLE IDLE SORT SORT=DISPLAY THREAD=REFERENCES THREAD=REFS THREAD=ORDEREDSUBJECT MULTIAPPEND URL-PARTIAL CATENATE UNSELECT CHILDREN NAMESPACE UIDPLUS LIST-EXTENDED I18NLEVEL=1 CONDSTORE QRESYNC ESEARCH ESORT SEARCHRES WITHIN CONTEXT=SEARCH LIST-STATUS BINARY MOVE SNIPPET=FUZZY PREVIEW=FUZZY STATUS=SIZE SAVEDATE LITERAL+ NOTIFY SPECIAL-USE QUOTA
S: A00000002 OK You are so in
C: A00000003 NAMESPACE
S: * NAMESPACE (("INBOX." ".")) NIL NIL
S: A00000003 OK Namespace completed (0.001 + 0.000 secs).
C: A00000004 LIST "" "INBOX" RETURN (SUBSCRIBED CHILDREN)
S: * LIST (\HasChildren) "." INBOX
S: A00000004 OK List completed (0.001 + 0.000 secs).
C: A00000005 LIST (SPECIAL-USE) "" "*" RETURN (SUBSCRIBED CHILDREN)
S: * LIST (\Subscribed \HasNoChildren \Trash) "." INBOX.Trash
S: * LIST (\Subscribed \HasNoChildren \Junk) "." INBOX.spambucket
S: * LIST (\Subscribed \HasNoChildren \Sent) "." INBOX.Sent
S: * LIST (\Subscribed \HasNoChildren \Drafts) "." INBOX.Drafts
S: A00000005 OK List completed (0.001 + 0.000 secs).
C: A00000006 SELECT INBOX (CONDSTORE)
S: * FLAGS (\Answered \Flagged \Deleted \Seen \Draft)
S: * OK [PERMANENTFLAGS (\Answered \Flagged \Deleted \Seen \Draft \*)] Flags permitted.
S: * 0 EXISTS
S: * 0 RECENT
S: * OK [UIDVALIDITY 1662400074] UIDs valid
S: * OK [UIDNEXT 16] Predicted next UID
S: * OK [HIGHESTMODSEQ 51] Highest
S: A00000006 OK [READ-WRITE] Select completed (0.001 + 0.000 secs).
C: A00000007 UID SEARCH RETURN (ALL) ALL
S: * ESEARCH (TAG "A00000007") UID
S: A00000007 OK Search completed (0.001 + 0.000 secs).
C: A00000008 UID SEARCH RETURN (ALL) ALL
S: * ESEARCH (TAG "A00000008") UID
S: A00000008 OK Search completed (0.001 + 0.000 secs).

```

If I understand the protocol right, my app started the second search as well and didn't get the new received message.

Then, I terminated my app and started it again.

I received nearly the same protocol as before, but with this line at the end:

```
S: A00000006 OK [READ-WRITE] Select completed (0.001 + 0.000 secs).
C: A00000007 UID SEARCH RETURN (ALL) ALL
S: * ESEARCH (TAG "A00000007") UID ALL 16
S: A00000007 OK Search completed (0.001 + 0.000 secs).
C: A00000008 UID FETCH 16 (FLAGS BODY.PEEK[HEADER])
S: * 1 FETCH (UID 16 FLAGS () BODY[HEADER] {3671}

```
… followed by my new mail.

If I understood the protocol right, the difference is this line:
`ESEARCH (TAG "A00000007") UID ALL 16`

... the **`16`**

So, I believe, you are right: It could be a problem on the server. Do you still believe this too?

**Comment by jstedfast** [comment]
Yes, it's a server problem.

**Comment by NilsHoyer** [comment]
... I find bug everywhere in my life. :-)

**Comment by jstedfast** [comment]
> ... I find bug everywhere in my life. :-)

Apparently. Yikes. Looks like Perdition IMAP is a POP3/IMAP proxy server.

My guess is that:

1. the server redirecting IMAP commands incorrectly and turning BODY.PEEK requests into BODY requests (hence your messages being auto-marked as `\\Seen`)
2. It is caching SEARCH request/results, hence follow-up SEARCH requests not seeing new messages.

**Comment by NilsHoyer** [comment]
For me, it's not important to work with this server. It's just the first server, I tested with MailKit.

So for the moment, I will no longer take time for this issue
