### ISSUE TITLE
Does mark MailKit mark received messages automatically as "seen" (read)?

### ISSUE THREAD

**Issue by NilsHoyer** [jstedfast/MailKit#1432]
I'm receiving messages with Imap and this works so far. But after I'm receiving it with `ImapClient.Inbox.Fetch(uniqueIds, MessageSummaryItems.Headers | MessageSummaryItems.Size | MessageSummaryItems.Flags | MessageSummaryItems.BodyStructure);`, they are marked as "seen" / "read" on the server.

Does MailKit sends this flag?

Is there a way for me, not to send this flag?

**Comment by jstedfast** [comment]
MailKit does not automatically mark any messages as read/seen on the server. If the server is doing that, then the server is buggy.

The IMAP protocol *does* automatically mark the message as `\\Seen` if-and-only-if the client sends a `FETCH BODY[]` request and the way around that is to send `FETCH BODY.PEEK[]` (which is what MailKit does).

That said, MailKit's ImapFolder.Fetch() methods never send `FETCH BODY[]` -or- `FETCH BODY.PEEK[]`. Only the `GetMessage(int index)` and `GetMessage(UniqueId uid)` methods send that request.

**Comment by NilsHoyer** [comment]
Yes, I'm using `ImapFolder.Fetch(uniqueIds, messageSummaryItem)` to receive message.

Inside the protocol, I found this lines:

```
C: A00000010 UID FETCH 17 (BODY.PEEK[HEADER] BODY.PEEK[TEXT])
S: * 1 FETCH (UID 17 BODY[HEADER] {3675}
```

Do you believe, this is a server bug?

**Comment by jstedfast** [comment]
Yes, this is a server bug.

**Comment by NilsHoyer** [comment]
I'm sorry, but there is no server information.

**Comment by jstedfast** [comment]
Ok, so based on one of your other bug reports, looks like you are connecting to a Perdition IMAP proxy which is probably the source of these bugs.

**Comment by NilsHoyer** [comment]
If you believe, there is no bug in MailKit, we should not spend more time about this server.

**Comment by NilsHoyer** [comment]
... by the way: The provider of this server don't like my bug reports like you. ;-)
