### ISSUE TITLE
ImapClient.Idle does not cancel

### ISSUE THREAD

**Issue by NilsHoyer** [jstedfast/MailKit#1434]
In a separate thread, I call this code:

`imapClient.Idle(new CancellationTokenSource(new TimeSpan(0, 29, 0)).Token, _idleCancellationSource.Token);`

After this, in the main thread, I call `_idleCancellationSource.Cancel();`

The `imapClient.Idle` does not stop executing within 15 seconds.

Why? (How can I stop it?)

**Comment by NilsHoyer** [comment]
Sorry to bother you: My mistake, I have to cancel the doneToken.

**Comment by NilsHoyer** [comment]
Hm... now I call ImapClient.IdleAsync and cancel the done before the cancel source.

After this, I wait until the task finished. But it doesn't finish...

**Comment by NilsHoyer** [comment]
Inside the log, I have this:

```
C: B00000007 IDLE
S: + idling
S: * 1 FETCH (MODSEQ (88) FLAGS (\Seen))
C: DONE
```

So the IDLE has stopped, but the task doesn't finish.

**Comment by jstedfast** [comment]
It looks like the server isn't responding to the `DONE` command...

That said (and confirm if I am wrong), but you also cancelled the cancelationToken which should have dropped your connection to the IMAP server which would throw a OperationCanceledException.

I assume it did not?

**Comment by jstedfast** [comment]
Based on a comment in another bug report, I gather this is resolved?

**Comment by NilsHoyer** [comment]
Shame on me: It was a deadlock. :-(

(I tried to stop the `ImapClient.Idle` inside the `mailFolder.MessageFlagsChanged` event. And indeed, this can't work.)

**Comment by jstedfast** [comment]
ah, ok

**Comment by ibrahimabtula** [comment]
Hello, I have the same problem. Could you please give bit more info what was the issue and how you fixed it ?
