### ISSUE TITLE
MimeMessage.Envelope would be helpful

### ISSUE THREAD

**Issue by NilsHoyer** [jstedfast/MailKit#1435]
I'm using `MimeMessage.Load` to create a mime message from a file.

Maybe you can implement the `MimeMessage.Envelope` like you have implemented `MessageSummary.Envelope`?

**Comment by jstedfast** [comment]
MimeMessage already has all of the pre-parsed header values as properties so I'm not sure what the point would be?

**Comment by NilsHoyer** [comment]
Yes, I can access to `MimeMessage.Headers[HeaderId.MessageId]`. But this gives me the message id enclosed in &lt; and &gt;. So I have to remove it by myself.

Additionally, I have to call `DateUtils.TryParse` for `HeaderId.Date`.

For the header lists like `HeaderId.To` and `HeaderId.Bcc` I have more work too.

I can live with the current solution. But the `Envelope` is the better way. ;-)

**Comment by jstedfast** [comment]
I recommend taking a look at `MimeMessage.MessageId`, `MimeMessage.Date`, `MimeMessage.To`, etc :-)

Basically, Envelope's API mimics the subset of the `MimeMessage` API dealing with the commonly accessed headers.

**Comment by NilsHoyer** [comment]
GREAT! Thank you.
