### ISSUE TITLE
How to get refresh token oauth2 for web application using C#?

### ISSUE THREAD

**Issue by Prashant-Y-Girase** [jstedfast/MailKit#1440]
I am able to get a refresh token for the Desktop app using "AuthorizationCodeInstalledApp" as per the below attachment.
But not able to get a refresh token for the Web app using "AuthorizationCodeWebApp" as per the below code.

`const string GMailAccount = "username@gmail.com";

var clientSecrets = new ClientSecrets {
      ClientId = "XXX.apps.googleusercontent.com",
      ClientSecret = "XXX"
};

var codeFlow = new GoogleAuthorizationCodeFlow (new GoogleAuthorizationCodeFlow.Initializer {
	DataStore = new FileDataStore ("CredentialCacheFolder", false),
	Scopes = new [] { "https://mail.google.com/" },
	ClientSecrets = clientSecrets
});

var uri = ConfigurationReader.Instance.Configuration.GetSection("GoogleAuth:RedirectUri").Value;
var authCode = new AuthorizationCodeWebApp(codeFlow, uri, uri).AuthorizeAsync(GMailAccount, CancellationToken.None).Result;

**//authCode.Credential is getting null**
if (authCode.Credential != null && authCode.Credential.Token.IsExpired(SystemClock.Default))
{	
	authCode.Credential.RefreshTokenAsync(CancellationToken.None).GetAwaiter().GetResult();
}`
![image](https://user-images.githubusercontent.com/22464695/191426939-94425c8a-8252-475d-9396-94562ee19bdb.png)

**Comment by jstedfast** [comment]
Isn't this a question for the authors of the OAuth library you are using?

If you can't find it in their documentation, how would I fare any better?
