### ISSUE TITLE
Mailkit cannot read autogenerated mails from mailbox

### ISSUE THREAD

**Issue by DomV-cloud** [jstedfast/MailKit#1441]
**Describe the bug**
Hi, 
I hope I'm not bothering you with my question. I ran into a weird bug. I develop an application that extracts information from the client's mailbox. My problem is that once an autogenerated mail arrives in the mailbox, if the Server crashes, Mailkit will not read the mail, it is empty. But if the email comes from a different email address (I tried from my personal and school email address), it reads the email fine.  

**Platform (please complete the following information):**
 - OS: Windows
 - .NET Framework: [.NET 4.0, WPF]
 - MailKit Version: 3.3.0

```csharp
 using (var client = new ImapClient())
                {
                    using (var cancel = new System.Threading.CancellationTokenSource())
                    {

                        client.Connect(emailParser.ServerName, emailParser.Port, emailParser.IsSSLuse,
                            cancel.Token);

                        client.Authenticate(emailParser.Username, emailParser.Password, cancel.Token);

                        var inbox = client.Inbox;
                        inbox.Open(FolderAccess.ReadOnly, cancel.Token);

                        for (int i = 0; i < inbox.Count; i++)
                        {
                            var message = inbox.GetMessage(i, cancel.Token); 
                            MessageBox.Show(message.TextBody);                                                                                
                            
                                }

                            }

                        }

                        client.Disconnect(true, cancel.Token);
```

**Comment by jstedfast** [comment]
I'll need more information:

* What is the exception you get?
* Change your code to use `using (var client = new ImapClient (new ProtocolLogger ("imap.log")))` and then share the log (feel free to anonymize the data)

**Comment by DomV-cloud** [comment]
Hi,

Exception:NullPointerException

ProtocolLogger:

Connected to imaps://imap.seznam.cz:993/
S: * OK Seznam IMAP server ready
C: A00000000 CAPABILITY
S: * CAPABILITY XLIST IMAP4rev1 STARTTLS CHILDREN SORT I18NLEVEL=1 UIDPLUS ID
S: A00000000 OK CAPABILITY completed
C: A00000001 LOGIN ******** ********
S: A00000001 OK LOGIN Authentication succeeded
C: A00000002 CAPABILITY
S: * CAPABILITY XLIST IMAP4rev1 STARTTLS CHILDREN SORT I18NLEVEL=1 UIDPLUS ID
S: A00000002 OK CAPABILITY completed
C: A00000003 LIST "" ""
S: * LIST (\Noselect) NIL ""
S: A00000003 OK LIST complete
C: A00000004 LIST "" "INBOX"
S: * LIST (\HasNoChildren) NIL "INBOX"
S: A00000004 OK LIST complete
C: A00000005 XLIST "" "*"
S: * XLIST (\HasNoChildren) NIL "INBOX"
S: * XLIST (\HasNoChildren \Sent) NIL "sent"
S: * XLIST (\HasNoChildren \Drafts) NIL "drafts"
S: * XLIST (\HasNoChildren) NIL "newsletters"
S: * XLIST (\HasNoChildren \Archive) NIL "archive"
S: * XLIST (\HasNoChildren \Spam) NIL "spam"
S: * XLIST (\HasNoChildren \Trash) NIL "trash"
S: A00000005 OK XLIST complete
C: A00000006 EXAMINE INBOX
S: * 1 EXISTS
S: * 0 RECENT
S: * FLAGS (\Seen \Answered \Flagged \Deleted \Draft \Recent)
S: * OK [PERMANENTFLAGS (\Seen \Answered \Flagged \Deleted \Draft)] Can bee changed permanently
S: * OK [UIDVALIDITY 1] UIDs validity number
S: * OK [UIDNEXT 1174] Predicted next UID
S: * OK [UNSEEN 1] The first unseen message MSN.
S: A00000006 OK [READ-ONLY] EXAMINE completed
Total messages: 1
Recent messages: 0
C: A00000007 FETCH 1 (BODY.PEEK[])
S: * 1 FETCH (BODY[] {1515}
S: Received: from a43-89.smtp-out.amazonses.com (a43-89.smtp-out.amazonses.com [54.240.43.89])
S:      by email-smtpd9.ko.seznam.cz (Seznam SMTPD 1.3.137) with ESMTP;
S:      Wed, 28 Sep 2022 07:13:26 +0200 (CEST)
S: DKIM-Signature: v=1; a=rsa-sha256; q=dns/txt; c=relaxed/simple;
S:      s=6gbrjpgwjskckoa6a5zn6fwqkn67xbtw; d=amazonses.com; t=1664342004;
S:      h=MIME-Version:From:To:Date:Subject:Content-Type:Content-Transfer-Encoding:Message-ID:Feedback-ID;
S:      bh=Tf3522dYaPsTT9jF2cD86TCuEtQz5qF452+xNRMN+NQ=;
S:      b=I5Ct+FxJVSh8Ycnnc1iZoMjyRRmvD2v/qPcazMWhdixHlZX+fF/mboARjx3fS0SU
S:      2j2N20NQOYC5FRjV5mbRXgHZiKCU78szIcmkL7LBVNM0Zpj0OwK3+JCTBWn46oynDMZ
S:      RO7cDdJWOrdjBWxjC47y7V6orSaH8X5DpbrHJccM=
S: MIME-Version: 1.0
S: From: "Smart One s.r.o. Monitoring" <support@smart1.hostedrmm.com>
S: To: reportssmo@seznam.cz
S: X-Priority: 1
S: Priority: urgent
S: Importance: high
S: Date: Wed, 28 Sep 2022 05:13:24 +0000
S: Subject: Dostupnost serveru!
S: Content-Type: text/html; charset=utf-8
S: Content-Transfer-Encoding: base64
S: Message-ID: <0100018382839396-333e4874-3fe3-4ef8-a494-3337fc7cd7ed-000000@email.amazonses.com>
S: Feedback-ID: 1.us-east-1.ryKZb8SVjogJP0qpNnSWHxlkLJ4dmTjOGGDhWsI1zhM=:AmazonSES
S: X-SES-Outgoing: 2022.09.28-54.240.43.89
S:
S: U1JWLVRFU1QtU21hcnQgT25lIFNVQ0NFU1Mgb24gU21hcnQgT25lIHMuci5vLlxTUlYt
S: VEVTVCBhdCBNYWluIGZvciAgcmVzdWx0IFBJTkcgT0sgMTkyLjE2OC4xLjggLSBQYWNr
S: ZXQgbG9zcyA9IDAlLCBSVEEgPSAwbXMgLi4gU2VydmVyIGplIE9ubGluZTxCUj48QlI+
S: UmVwbHkgdG8gdGhpcyBlbWFpbCB0byBjcmVhdGUgYSBuZXcgdGlja2V0LjxCUj4gQ2xp
S: ZW50SUQ6MSBDb21wdXRlcklEOjg5MQ==
S:
S: )
S: A00000007 OK FETCH completed

C: A00000008 LOGOUT
S: * BYE Thanks for your visit, have a nice day.
S: A00000008 OK LOGOUT Completed.

**Comment by jstedfast** [comment]
Oh, the problem is that the message doesn't have a `TextBody`, it only has an `HtmlBody`.

This line is the problem:
```csharp
MessageBox.Show(message.TextBody);
```

You should change that to:

```csharp
MessageBox.Show(message.TextBody ?? message.HtmlBody ?? string.Empty);
```

**Comment by DomV-cloud** [comment]
Hi,
Thank you so much, it works.
