### ISSUE TITLE
Attachment only txt ad html files

### ISSUE THREAD

**Issue by bugaoleg** [jstedfast/MailKit#1443]
Hello! Have a bug and cant figure it out ... what I am doing wrong. When I send zip docx or pdf file in attachments, the file that I recivied is corrupt. Cannot open, or it give me error that file is corrupt. Even jpg, png files wont open. Only txt files comes without a problem.
Maybe someone know what is the problem ?

       `public async Task<ResponseData> SendEmail(VictimData victimData, SmtpData senderData, LetterData letter)
        {
            ResponseData response = new ResponseData();
            BodyBuilder bodyBuilder = new BodyBuilder();
            string newAttachment = "";
            try
            {
                MimeMessage message = new MimeMessage();
                message.From.Add(new MailboxAddress(senderData.senderName, senderData.senderEmail));
                message.To.Add(new MailboxAddress("", victimData.email));
                
                message.ReplyTo.Add(new MailboxAddress(senderData.senderName, senderData.senderEmail));
                message.Subject = letter.subject;
                if (letter.isHtml)
                {
                    bodyBuilder.HtmlBody = letter.body;
                }
                else
                {
                    bodyBuilder.TextBody = letter.body;
                }

                foreach (var attachment in letter.attachment)
                {
                    newAttachment = ReadAndReplaceAttachment(attachment.filePath, victimData.email, attachment.fileName);
                    bodyBuilder.Attachments.Add(newAttachment);
                    File.Delete(newAttachment);
                    Console.WriteLine(newAttachment);
                }
                message.Body = bodyBuilder.ToMessageBody();
                await client.SendAsync(message);
                response.status = true;
                response.messages = "";
                return response;
            }
            catch (Exception ex)
            {
                response.messages = ex.Message;
                response.status = false;
                return response;
            }
        }
        private string ReadAndReplaceAttachment(string filePath, string email, string newFileName)
        {
            Replacer replacer = new Replacer();
            string tempFile = Path.Combine(Helpers.tempPath, replacer.DoReplace(newFileName, email));//Path.GetTempPath() + Guid.NewGuid().ToString() + Path.GetExtension(filePath);
            string contentResult = "";

            using (StreamReader sr = File.OpenText(filePath))
            {
                contentResult = sr.ReadToEnd();
                contentResult = replacer.DoReplace(contentResult, email);
                sr.Close();
            }

            using (var tw = new StreamWriter(tempFile, true))
            {
                tw.Write(contentResult);
            }

            return tempFile;
        }`

**Comment by nikola1234-hash** [comment]
If the file you are attaching is malicious, many factors can occur that you get a corrupted file, for example, Windows Defender quarantines the malicious file or smtp server has some kind of antivirus.

**Comment by bugaoleg** [comment]
> If the file you are attaching is malicious, many factors can occur that you get a corrupted file, for example, Windows Defender quarantines the malicious file or smtp server has some kind of antivirus.

No, it is not a virus. A simple pdf with one word writet in it ... There is a problem with all binaries files. Jpg,png,zip,docx,pdf and so on ... With txt file all is ok.

**Comment by jstedfast** [comment]
Your code is opening binary files in text mode (`File.OpenText(filePath)`) which is corrupting your jpegs, pdfs, etc (because they aren't text files).
