### ISSUE TITLE
How to encode mail subject and body using UTF-8 encoding in Mailkit?

### ISSUE THREAD

**Issue by 0xNinjaCoder** [jstedfast/MailKit#1447]
In System.Net.Mail.MailMessage library, SubjectEncoding and BodyEncoding options can be used to set encoding for subject and body of the mail.
_System.Net.Mail.MailMessage psuedo code:_
```
var mailMessage = new MailMessage(new MailAddress(From), recipient)
{
    SubjectEncoding = Encoding.UTF8,
    BodyEncoding = Encoding.UTF8
};
```
Are there similar options to SubjectEncoding and BodyEncoding available in MimeKit.MimeMessage library to encode subject and body?
_Mimekit psuedo code:_
```
var message = new MimeMessage();
message.Subject = "Howdie";
message.Body = "Test";
```

**Comment by jstedfast** [comment]
Yes

To set the "body encoding", you would construct the message body like this:

```csharp
var body = new TextPart ("plain");
body.SetText (Encoding.UTF8, "This is the message body.");

message.Body = body;
```

Note that by default, for message bodies, UTF-8 is used. So if you want UTF-8, then you can even do this:

```csharp
message.Body = new TextPart ("plain") {
    Text = "This is the message body."
};
```

For headers, you'll need to bypass MimeMessage.Subject:

```csharp
message.Headers.Replace ("Subject", Encoding.UTF8, "This is my subject.");
```

You can also specify an encoding to use for each MailboxAddress:

```csharp
message.To.Add (new MailboxAddress (Encoding.UTF8, "Name", "recipient@example.com"));
```

**Comment by 0xNinjaCoder** [comment]
Thanks for detailed answer. I appreciate it.
