### ISSUE TITLE
Application breaks with ContextSwitchDeadlock while sending the large attachments using Mailkit.

### ISSUE THREAD

**Issue by 0xNinjaCoder** [jstedfast/MailKit#1448]
I'm trying to send large attachment (3MB) over email using Mailkit SMTP but my WPF application breaks while sending the email.

The exception:

_Managed Debugging Assistant 'ContextSwitchDeadlock' : 'The CLR has been unable to transition from COM context 0x1639550 to COM context 0x1639498 for 60 seconds. The thread that owns the destination context/apartment is most likely either doing a non pumping wait or processing a very long running operation without pumping Windows messages. This situation generally has a negative performance impact and may even lead to the application becoming non responsive or memory usage accumulating continually over time. To avoid this problem, all single threaded apartment (STA) threads should use pumping wait primitives (such as CoWaitForMultipleHandles) and routinely pump messages during long running operations.'_

**While I can send the same attachment in a jiffy using the System.Net.Mail library.**

MailKit code:

                ```
                var smtpClient = new SmtpClient();
                 smtpClient.Connect("smtp.office365.com", 587, SecureSocketOptions.StartTls);
                 smtpClient.Authenticate(UserName, RealPassword);
                smtpClient.Timeout = 5 * 60 * 1000; //5 minutes default

                // add from and to mailaddresses
                var mailMessage = new MimeMessage();
                mailMessage.From.Add(new MailboxAddress(Encoding.UTF8, From, From));
                mailMessage.To.Add(new MailboxAddress(Encoding.UTF8, recipient, recipient));

                mailMessage.Headers.Replace("Subject", Encoding.UTF8, Subject);

                BodyBuilder builder = new BodyBuilder();
                builder.HtmlBody = Body;
                builder.Attachments.Add(@"C:\Users\John\Downloads\Brandon.pdf"); // 1MB
                builder.Attachments.Add(@"C:\Users\John\Desktop\MyDocs\dp.jpg");  // 2MB
                mailMessage.Body = builder.ToMessageBody();
                
                smtpClient.Send(mailMessage);
                smtpClient.Disconnect(true);
```

If I do not add the attachments, the mail works fine.

**Comment by jstedfast** [comment]
This doesn't make any sense. There's no way that this is a problem with MailKit itself because it doesn't do any thread locking.

Try to repro this with a console app and I bet you won't be able to.

**Comment by jstedfast** [comment]
See this: https://stackoverflow.com/questions/578357/visual-studio-contextswitchdeadlock

**Comment by jstedfast** [comment]
It sounds like the problem is that you are sending mail in your GUI thread which blocks until the message is sent.
