### ISSUE TITLE
Message flag 'seen' does not persist on Exchange server

### ISSUE THREAD

**Issue by Olby2000** [jstedfast/MailKit#1449]
Hi, I was tasked with downloading messages from an old Exchange server 2010 (yes you read correctly).
I am able to set the flag to seen and the server seems to acknowledge the request. However next time around this same message (based on uid) has no flags set.

Code which opens the folder in question and sets the flag:
```
var folder = await Client.GetFolderAsync(folderPath, CancellationToken);
await folder.OpenAsync(FolderAccess.ReadWrite, CancellationToken);
try
{
	await folder.RemoveFlagsAsync(uniqueId, MessageFlags.Seen, true);
}
finally
{
	await folder.CloseAsync();
}
```

Protocol log acknowledging the update:
```
C: A00000009 SELECT INBOX
S: * 4 EXISTS
S: * 0 RECENT
S: * FLAGS (\Seen \Answered \Flagged \Deleted \Draft $MDNSent)
S: * OK [PERMANENTFLAGS (\Seen \Answered \Flagged \Deleted \Draft $MDNSent)] Permanent flags
S: * OK [UNSEEN 1] Is the first unseen message
S: * OK [UIDVALIDITY 7937] UIDVALIDITY value
S: * OK [UIDNEXT 67167] The next unique identifier value
S: A00000009 OK [READ-WRITE] SELECT completed.
C: A00000010 UID STORE 67162 -FLAGS.SILENT (\Seen)
S: A00000010 OK STORE completed.
C: A00000011 LOGOUT
S: * BYE Microsoft Exchange Server 2010 IMAP4 server signing off.
S: A00000011 OK LOGOUT completed.
```

Is there something I am doing wrong?

Thank you.

**Comment by jstedfast** [comment]
You're removing the Seen flag, but it sounds like you want to *add* it.

If you remove the \Seen flag, there won't be any flags set on it in the next session (which is what you are seeing, right?)

**Comment by Olby2000** [comment]
Well, that's embarrassing. That's exactly what I was trying to do lol. I guess I got hung up on the semantics because I thought you need to remove "something" rather than add to make it read. Appreciate your help. Sorry to bother the mail guru!

**Comment by jstedfast** [comment]
No problem :-)
