### ISSUE TITLE
Outlook OAuth2 SMTP is not authenticating with mailkit

### ISSUE THREAD

**Issue by m1adow** [jstedfast/MailKit#1450]
Hi! I'm currently working on one specific app that should send e-mail via outlook and using mailkit. App is logging in via oauth2 and imap authentication is OK, but not smtp.  

I'm getting this exception:

**535: 5.7.3 Authentication unsuccessful   
[AM6P192CA0023.EURP192.PROD.OUTLOOK.COM]**

Code sample:

    var publicClientApplication = PublicClientApplicationBuilder.Create(ClientId)
                        .WithRedirectUri(RedirectUri)
                        .Build();
    
    var scopes = new string[]
    {
        "email",
        "offline_access",
        "https://outlook.office.com/IMAP.AccessAsUser.All",
        "https://outlook.office.com/SMTP.Send"
    };
    
    var authToken = await publicClientApplication.AcquireTokenInteractive(scopes).ExecuteAsync();
  
    var oauth2 = new SaslMechanismOAuth2(authToken.Account.Username, authToken.AccessToken);
    
    await SmtpClient.ConnectAsync(smtp.office365.com, 587, SecureSocketOptions.StartTls);
    await SmtpClient.AuthenticateAsync(oauth2);
    
API permissions in app registration:
![api](https://user-images.githubusercontent.com/84251113/196470346-34437982-8cb8-408b-a99b-5dbdc8c7d117.png)

Any ideas?

**Comment by jstedfast** [comment]
Why are you checking the ImapClient's AuthenticationMechanisms instead of the SmtpClient's?

```csharp
if (account.ImapClient.AuthenticationMechanisms.Contains("OAUTHBEARER"))
```

Not sure if that's the issue or not, but that seems sketchy.

Secondly, you aren't specifying a TenantID and I'm pretty sure you need that.

**Comment by m1adow** [comment]
Ok thank you i will try it tomorrow 😸

**Comment by m1adow** [comment]
To all who can ran into this problem. Idk why but I've changed my code like this

                await smtpClient.ConnectAsync(smtpLink, 587, SecureSocketOptions.StartTls);

                if (smtpClient.AuthenticationMechanisms.Contains("OAUTHBEARER"))
                    oauth2 = new SaslMechanismOAuthBearer(authToken.Account.Username, authToken.AccessToken);
                else
                    oauth2 = new SaslMechanismOAuth2(authToken.Account.Username, authToken.AccessToken);

                await smtpClient.AuthenticateAsync(oauth2);
