### ISSUE TITLE
ToMailboxAddress fails too often with Exceptions when parsing response from Microsoft Exchange Server Imap

### ISSUE THREAD

**Issue by ekalchev** [jstedfast/MailKit#1451]
I see that when fetching data from mailbox hosted on outlook.com, hotmail.com and etc (Microsoft Exchange Server Imap)
MailKit throws thousand of exceptions. I see a lot of these lines coming from microsoft servers

`S: * 2 FETCH (UID 3 FLAGS (\Seen) INTERNALDATE "27-Jan-2021 11:56:15 +0200" RFC822.SIZE 12006 ENVELOPE (NIL "Retrieval using the IMAP4 protocol failed for the following message: 3" (("Microsoft Exchange Server" NIL NIL ".MISSING-HOST-NAME.")) NIL NIL (("username@testdomain.com" NIL "username" "testdomain.com")) NIL NIL NIL NIL) BODYSTRUCTURE ("text" "plain" ("charset" "us-ascii") NIL NIL "quoted-printable" 1 1 NIL NIL NIL NIL) BODY[HEADER.FIELDS (IMPORTANCE RECEIVED X-PRIORITY REFERENCES)] {2}`

It seems that is common scenario for these popular servers and may be it is not good idea to throw exceptions for those. This will improve MailKit integration with Microsoft Exchange Imap.

**Comment by jstedfast** [comment]
Would it be possible to find out what the actual Sender/From addresses are when you get:

```
("Microsoft Exchange Server" NIL NIL ".MISSING-HOST-NAME.")
```

Hoping to reconstruct this the way it is in the actual message.

**Comment by ekalchev** [comment]
I am not aware of any way to do that

**Comment by jstedfast** [comment]
Don't worry about it. It is probably something like `Microsoft Exchange Server <>`
