### ISSUE TITLE
Move emails between two mailboxes

### ISSUE THREAD

**Issue by umbertoB67** [jstedfast/MailKit#1453]
**Describe the solution you'd like**
I would like to be able to copy/move messages from one IMAP mailbox to another IMAP mailbox, while keeping the date/time of the original message (for example to backup or to free up space from mailbox A).

**Describe alternatives you've considered**
At the moment I download the message from the INBOX of mailbox A and save it in the INBOX of mailbox B, but the new message has the current date and not that of the original message.

**Comment by jstedfast** [comment]
You have a couple of options:

1. Use ImapFolder.CopyTo/MoveTo().
2. Make use of the INTERNALDATE of the message in the source folder:

```csharp
var summaries = sourceFolder.Fetch (0, -1, MessageSummaryItems.UniqueId | MessageSummaryItems.InternalDate | MessageSummaryItems.Flags);
foreach (var summary in summaries) {
    var message = sourceFolder.GetMessage (summary.UniqueId);
    destinationFolder.Append (message, summary.Flags.Value, summary.Keywords, summary.InternalDate.Value);
}
```

**Comment by umbertoB67** [comment]
Thank you for your quick answer.
Could I also use this mode to move messages between two different mailboxes or just between folders of the same mailbox?

**Comment by jstedfast** [comment]
> between two different mailboxes or just between folders of the same mailbox?

Do you mean 2 different accounts? If you mean 2 different IMAP accounts, then you'll need to use one of the Append() methods (CopyTo/MoveTo only work within the same account).

**Comment by umbertoB67** [comment]
Yes, I mean two different IMAP accounts (example: from INBOX of userX@domain.com to INBOX of userY@otherdomain.com), but keeping the same date/time of the message in the source mailbox.
