### ISSUE TITLE
Unable to use certain charaters on imap outlook connection

### ISSUE THREAD

**Issue by fghjkgcfxx56u** [jstedfast/MailKit#1455]
**Describe the bug**
i am having trouble logging in to the imap server "outlook.office365.com:993", basically sometimes the passwords i use contain special characters (-"_?$%& and such) that make the login fail with error: imaplib.IMAP4.error: b'LOGIN failed.' i know that this is a problem with the characters, because it appears only when the password contains some of them, while when the password is only numbers/letters it works fine. I am also unable to change the password, so i have to connect with that i've got

**Platform (please complete the following information):**
 - OS: Windows
 - .NET Runtime: Mono
 - .NET Framework: .NET 6.0
 - MailKit Version: 3.4.2

**Exception**
Unhandled exception. MailKit.Security.AuthenticationException: LOGIN failed.
   at MailKit.Net.Imap.ImapClient.AuthenticateAsync(Encoding encoding, ICredentials credentials, Boolean doAsync, CancellationToken cancellationToken)
   at MailKit.Net.Imap.ImapClient.Authenticate(Encoding encoding, ICredentials credentials, CancellationToken cancellationToken)
   at MailKit.MailService.Authenticate(Encoding encoding, String userName, String password, CancellationToken cancellationToken)
   at Get_Email.Program.Main(String[] args) in T:\Projects\C#\Get Email\Program.cs:line 18

**To Reproduce**
1. try to authenticate to Outlook IMAP server with a password that uses special characters

**Expected behavior**
All is normal and nothing happens

**Code Snippets**
```
using (var client = new ImapClient())
            {
                client.Connect("imap-mail.outlook.com", 993, true);
                Console.WriteLine(client.Capabilities);
                //client.EnableUTF8();
                client.Authenticate(System.Text.Encoding.UTF8, "email@outlook.com", "mozz@-rella9?torey");
```

**Protocol Logs**
Connected to imaps://imap-mail.outlook.com:993/
S: * OK The Microsoft Exchange IMAP4 service is ready. [WgBSADAAUAAyADcAOABDAEEAMAAxADgAOQAuAEMASABFAFAAMgA3ADgALgBQAFIATwBEAC4ATwBVAFQATABPAE8ASwAuAEMATwBNAA==]
C: A00000000 CAPABILITY
S: * CAPABILITY IMAP4 IMAP4rev1 AUTH=PLAIN AUTH=XOAUTH2 SASL-IR UIDPLUS ID UNSELECT CHILDREN IDLE NAMESPACE LITERAL+
S: A00000000 OK CAPABILITY completed.
C: A00000001 AUTHENTICATE PLAIN ********
S: A00000001 NO AUTHENTICATE failed.
C: A00000002 LOGIN ******** ********
S: A00000002 NO LOGIN failed.

**Comment by jstedfast** [comment]
Can you identify what MailKit is doing wrong?

You could try comparing to another IMAP library to see if any other library works and then check the IMAP logs for that library to see what it does different.

BTW, I suspect the real problem is just that imap-mail.outlook.com requires XOAUTH2 now and will not accept "less secure" authentication.

Also, if you want to see what MailKit is sending for the authentication data, you'll need to do this:

```csharp
using (var client = new ImapClient(new ProtocolLogger ("imap.log") { RedactSecrets = false }))
```

**Comment by fghjkgcfxx56u** [comment]
so, i made a script that tests a bunch of the emails in succession and you can indeed login without XOAUTH2, but it seems to error when there are certain characters in the password, so far i isolated the characters: dash (-), underscore (_) and dot (.). It seems to be an error with the server, but i found a workaround by generating passwords that don't contain those characters, thanks for your help
