### ISSUE TITLE
Strange Behaviour

### ISSUE THREAD

**Issue by gsantosgo** [jstedfast/MailKit#1456]
**Describe the bug**
I have a main program which access through IMAP Protocol to IMAP Exchange Server. This program is really simple, that is, it gets connect on IMAP Server and return the number of items of Inbox. 

The first try to run the program, everything goes OK since it returns number of items. But if I try to execute the same program for second time, it returns an exception (SSL issue). I don't undertand why sometimes it works fine and sometimes it works wrong. If I try to execute for third time, everything is OK, but the fourth time, it returns a exception,.., so forth 

**Platform (please complete the following information):**
 - OS: Windows
 - .NET Runtime: .NET Core 6.0 
 - .NET Framework: .NET Core 6.0 
 - MailKit Version: 3.4.2 

**Exception**
Unhandled exception. MailKit.Security.SslHandshakeException: An error occurred while attempting to establish an SSL or TLS connection.

This usually means that the SSL certificate presented by the server is not trusted by the system for one or more of
the following reasons:

1. The server is using a self-signed certificate which cannot be verified.
2. The local system is missing a Root or Intermediate certificate needed to verify the server's certificate.
3. A Certificate Authority CRL server for one or more of the certificates in the chain is temporarily unavailable.
4. The certificate presented by the server is expired or invalid.
5. The set of SSL/TLS protocols supported by the client and server do not match.
6. You are trying to connect to a port which does not support SSL/TLS.

See https://github.com/jstedfast/MailKit/blob/master/FAQ.md#SslHandshakeException for possible solutions.

 ---> System.IO.IOException: Se ha anulado una conexión establecida por el software en su equipo host..
 ---> System.Net.Sockets.SocketException (10053): Se ha anulado una conexión establecida por el software en su equipo host..
   at MailKit.Net.NetworkStream.ReadAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at MailKit.Net.NetworkStream.ReadAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
   at System.Net.Security.SslStream.<FillHandshakeBufferAsync>g__InternalFillHandshakeBufferAsync|189_0[TIOAdapter](TIOAdapter adap, ValueTask`1 task, Int32 minSize)
   at System.Net.Security.SslStream.ReceiveBlobAsync[TIOAdapter](TIOAdapter adapter)
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
   at MailKit.Net.Imap.ImapClient.ConnectAsync(String host, Int32 port, SecureSocketOptions options, Boolean doAsync, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at MailKit.Net.Imap.ImapClient.ConnectAsync(String host, Int32 port, SecureSocketOptions options, Boolean doAsync, CancellationToken cancellationToken)
   at GPG.MediatRRecolector.App.Program.Main() in C:\sources\GPGMediatRRecolectorApp\src\GPG.MediatRRecolector.App\Program.cs:line 121
   at GPG.MediatRRecolector.App.Program.<Main>()

C:\sources\GPGMediatRRecolectorApp\src\GPG.MediatRRecolector.App\bin\Debug\net6.0\GPG.MediatRRecolector.App.exe (process 17932) exited with code -532462766.
Press any key to close this window . . .

**To Reproduce**
1. Run application console program. The result is OK.  (Result: Items:8)
2. Run application console program. Exception
3. Run application console program. The result is OK.  (Result: Items:8)
4. Run application console program. Exception
5. Run application console program. The result is OK.  (Result: Items:8)
6. Run application console program. Exception

**Expected behavior**
The program should always return Items:8

**Code Snippets**
```csharp
private async static Task Main()
        {
            using (var client = new ImapClient(new ProtocolLogger("imap.log")))
            {               
                client.SslProtocols = SslProtocols.Tls | SslProtocols.Tls11 | SslProtocols.Tls12 | SslProtocols.Tls13;

                await client.ConnectAsync("outlook.domain", 993, true);
                await client.AuthenticateAsync("userName", "password");
                await client.Inbox.OpenAsync(FolderAccess.ReadOnly);

                var uids = await client.Inbox.SearchAsync(SearchQuery.All);

                Console.WriteLine("Items:" + uids.Count);
                await client.DisconnectAsync(true);
            }
        }
```

Thank you

**Comment by jstedfast** [comment]
The following article explains what is going wrong for you (see the inner SocketException error code that you pasted - code 10053)

https://wiki.pscs.co.uk/how_to:10053

**Comment by jstedfast** [comment]
Here are some more possibilities: https://appuals.com/asynchronous-socket-error-10053-on-windows-operating-system/
