### ISSUE TITLE
How to store authToken.AccessToken Oauth 2.0 in windows app ?

### ISSUE THREAD

**Issue by fredoche1810** [jstedfast/MailKit#1457]
Hello,

As explained in the documention, we first need to acquire a token : 
`authToken = await publicClientApplication.AcquireTokenInteractive(scopes).WithLoginHint(myemail).ExecuteAsync(cancellationToken);`
That works for me.

After that, I can use this command to refresh token or connect with exisiting token :
`authToken = await publicClientApplication.AcquireTokenSilent(scopes, authToken.Account).ExecuteAsync(cancellationToken);`
That works also.

But when I close my software and restart it, I always need to put my password again.
I suppose that if I could save "authToken.Account" values and read the value at the startup of my software it will solve the problem but it's not a simple string so I don't know how to store it.

As it's for an internal use, i don't use encryption and so on.

Could someone give me a sample code ?

Thanks in advance,

**Comment by ekalchev** [comment]
Here you go
https://stackoverflow.com/questions/6219938/c-sharp-store-a-string-variable-to-a-text-file-txt

**Comment by jstedfast** [comment]
I think what he's looking for is this: https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/AcquireTokenSilentAsync-using-a-cached-token

**Comment by fredoche1810** [comment]
Hello @ekalchev,
Thanks for your proposition but "authToken" is an AuthenticationResult object so it's a little bit more complicated than a simple string. I think I've to serialize the object into a file but I don't find how to do that.

@jstedfast : Acquiring silent works perfectly when the object AuthenticationResult authToken is initialized. At the startup of my software, I have to recreate the object from something stored in a file, database or something else. 

So is there a way to serialize the AuthenticationResult object ?
Does someone have a sample ?
Thanks in advance,

**Comment by jstedfast** [comment]
I imagine you would store this as JSON. Take a look at Newtonsoft.Json documentation. https://www.newtonsoft.com/json/help/html/SerializingJSON.htm

**Comment by fredoche1810** [comment]
@jstedfast 
Yes that could be a solution but I can't use it without error.
Here is my code :

```
try
    {
        string json = JsonConvert.SerializeObject(authToken, Newtonsoft.Json.Formatting.Indented, new JsonSerializerSettings { PreserveReferencesHandling = PreserveReferencesHandling.Objects, ReferenceLoopHandling = ReferenceLoopHandling.Serialize });
        Api.Stop(json);
    }
    catch (Exception ex)
    {
        Api.Stop(ex.Message + System.Environment.NewLine + ex.StackTrace + System.Environment.NewLine + ex.InnerException + System.Environment.NewLine + ex.HResult);
    }
```

And I have the following error

Error getting value from 'User' on 'Microsoft.Identity.Client.AuthenticationResult'.
   à Newtonsoft.Json.Serialization.DynamicValueProvider.GetValue(Object target)
   à Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.CalculatePropertyValues(JsonWriter writer, Object value, JsonContainerContract contract, JsonProperty member, JsonProperty property, JsonContract& memberContract, Object& memberValue)
   à Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   à Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
   à Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value, Type objectType)
   à Newtonsoft.Json.JsonConvert.SerializeObjectInternal(Object value, Type type, JsonSerializer jsonSerializer)
   à Newtonsoft.Json.JsonConvert.SerializeObject(Object value, Formatting formatting, JsonSerializerSettings settings)
   à MercaPlanner.Class_functions.<QtyMailsUnreaded>d__21.MoveNext() dans C:\Users\fdepu\OneDrive - BEL-ART S.A\Visual Studio 2019\Projets\MercaPlanner\MercaPlanner\Class_functions.cs:ligne 470
System.NotImplementedException: La méthode ou l'opération n'est pas implémentée.
   à Microsoft.Identity.Client.AuthenticationResult.get_User()
   à GetUser(Object )
   à Newtonsoft.Json.Serialization.DynamicValueProvider.GetValue(Object target)
-2146233088

Do you have a sample that's working fine for you ?

**Comment by jstedfast** [comment]
> Do you have a sample that's working fine for you ?

No, that's why I keep pointing you to documentation for the libraries you are trying to work with :-)

If I were to try and find an answer for you, I'd have to go through all of the trial & error and documentation reading that you would have to go through to figure this out.

My understanding from my quick skimming of the Microsoft.Identity.Client documentation that I pointed you to last week seemed to indicate that it would do the caching for you. If that's not the case, then I don't have an answer for you.

**Comment by fredoche1810** [comment]
Hello @jstedfast 
Thanks for your help but unfortunately I couldn't get it working. 
I tested a lot of thinks but nothing work until now.
I think the right method is to serialize the object to a file for example and to deserialize it to use it again later.
When I check my file after I serialize it I only have this inside :
```
<?xml version="1.0"?>
<AuthenticationResult xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" />
```

I suppose that someone else use also that in a windows application. 
I'm sure there is a solution to store the result of the interactive authentication to be able to acquire a new token silently but I can't find it.

I hope someone could help me.
