### ISSUE TITLE
Mailkit is not sending proper html body

### ISSUE THREAD

**Issue by abid7437** [jstedfast/MailKit#1458]
I am trying to send a simple `<ul><li> something </l></ul>` html but any reciept is not showing proper html 
![image](https://user-images.githubusercontent.com/26162059/200520932-30eced79-b301-40b4-90cd-77d68718a15c.png)

here is my code

```csharp
  string  MainMailTo = "";
            //************
            MimeMessage message = new MimeMessage();
            //************
            var SMTP = Configuration.GetSection("EmailConfiguration:SMTPServer");
            var Port = Configuration.GetSection("EmailConfiguration:SMTPPort");
            var MailSender = Configuration.GetSection("EmailConfiguration:FromEmail");
            var MailPass = Configuration.GetSection("EmailConfiguration:Password");
            var SSlEnabled = Configuration.GetSection("EmailConfiguration:IsSSL");
            var MailUser = Configuration.GetSection("EmailConfiguration:MailUser");

            //************
            var MailTo = param.ToEmail;

            //************
            MailboxAddress from = new MailboxAddress("noreply", MailSender.Value);
            message.From.Add(from);
            //************
            string[] mailToList = MainMailTo.Split(new String[] { ";" }, StringSplitOptions.RemoveEmptyEntries);
            foreach (var item in MailTo.Split(new String[] { ";" }, StringSplitOptions.RemoveEmptyEntries))
            {
                mailToList.Append(item);
            }
           
            MailboxAddress to = new MailboxAddress("User", MailTo);
            message.To.Add(to);
            //************
            message.Subject = param.Subject;
            //************
            BodyBuilder bodyBuilder = new BodyBuilder();
            bodyBuilder.HtmlBody = param.BodyHTML;
            bodyBuilder.TextBody = "-";

          

            if (param.FileIds?.Count > 0)
            {
                foreach (int id in param.FileIds)
                {
                    var fileObj = dBContext.Documents.Where(x => x.DocumentId == id).FirstOrDefault();
                    if (fileObj != null)
                    {
                        var pathCombine = System.IO.Path.Combine(this.environment.WebRootPath, fileObj.Path);
                      
                        bodyBuilder.Attachments.Add(pathCombine);
                    }
                }
            }

            try
            {
                message.Body = bodyBuilder.ToMessageBody();
               
                SmtpClient client = new SmtpClient();
                
                client.Connect(SMTP.Value, Convert.ToInt32(Port.Value), Convert.ToBoolean(SSlEnabled.Value));
                client.Authenticate(MailUser.Value, MailPass.Value);
                //************
                client.Send(message);
                client.Disconnect(true);
                client.Dispose();
                return "true";
            }
            catch (Exception exp)
            {
                return exp.Message;
            }
```

**Comment by jstedfast** [comment]
What is the value of `param.BodyHTML`?

**Comment by abid7437** [comment]
> What is the value of `param.BodyHTML`?

same as picture in email

<ul> <li><b>Id : </b>2</li> <li><b>FullName : </b>fullname</li> <li><b>Gender : </b>Male</li> <li><b>SSN : </b></li> <li><b>Mobile : </b>32131</li> <li><b>Email : </b></li> <li><b>City : </b> test</li> <li><b>Language : </b> Marwan test</li> <li><b>JobTitle : </b>test</li> <li><b>Degree : </b> test</li> <li><b>DateOfBirth : </b>10/31/2022 12:00:00 AM</li> <li><b>RecordStatus : </b>Active</li> <li><b>CreatedDate : </b>11/1/2022 10:50:28 AM</li> <li><b>CreatedBy : </b>1</li> <li><b>ModifiedDate : </b></li> <li><b>ModifiedBy : </b></li> <li><b>TwitterUrl : </b></li> <li><b>TwitterFollowers : </b></li> <li><b>InstagramUrl : </b></li> <li><b>InstagramFollowers : </b></li> <li><b>SnapChatUrl : </b></li> <li><b>SnapChatFollowers : </b></li> <li><b>YouTubeUrl : </b></li> <li><b>YouTubeFollowers : </b></li> <li><b>FacebookUrl : </b></li> <li><b>FacebookFollowers : </b></li> <li><b>TikTokUrl : </b></li> <li><b>TikTokFollowers : </b></li> <li><b>Category : </b> category more</li> <li><b>Specialized : </b>test</li> </ul>

**Comment by jstedfast** [comment]
So what do you think MimeKit is doing wrong?

Can you attach the raw MIME message data?

**Comment by abid7437** [comment]
> So what do you think MimeKit is doing wrong?
> 
> Can you attach the raw MIME message data?

By mistake i created an "issue", it should be a question, May be i am doing wrong, i have attached the picture of Raw html ?

**Comment by abid7437** [comment]
> I need to know what the raw message looks like so I can see the MIME and MIME headers.
> 
> You can use `message.WriteTo("raw-mime.txt")` to see what it looks like


From: noreply <noreply@kacnd.org>
Date: Tue, 08 Nov 2022 23:26:58 +0500
Subject: fullname
Message-Id: <ESGPRN3PCIU4.GTT557F0UK3T2@DESKTOP-UPERP58>
To: User <ah6442@gmail.com>
MIME-Version: 1.0
Content-Type: multipart/alternative; boundary="=-r4uvd8VnK/R7PepsRDxFgA=="

--=-r4uvd8VnK/R7PepsRDxFgA==
Content-Type: text/plain; charset=utf-8

-
--=-r4uvd8VnK/R7PepsRDxFgA==
Content-Type: text/html; charset=utf-8

                                    &lt;ul&gt;



                                    &lt;li&gt;&lt;b&gt;Id : &lt;/b&gt;2&lt;/li&gt;
                                    &lt;li&gt;&lt;b&gt;FullName : &lt;/b&gt;fullname&lt;/li&gt;
                                    &lt;li&gt;&lt;b&gt;Gender : &lt;/b&gt;Male&lt;/li&gt;
                                    &lt;li&gt;&lt;b&gt;SSN : &lt;/b&gt;&lt;/li&gt;
                                    &lt;li&gt;&lt;b&gt;Mobile : &lt;/b&gt;32131&lt;/li&gt;
                                    &lt;li&gt;&lt;b&gt;Email : &lt;/b&gt;&lt;/li&gt;
                                    &lt;li&gt;&lt;b&gt;City : &lt;/b&gt; test&lt;/li&gt;
                                    &lt;li&gt;&lt;b&gt;Language : &lt;/b&gt; Marwan test&lt;/li&gt;
                                    &lt;li&gt;&lt;b&gt;JobTitle : &lt;/b&gt;test&lt;/li&gt;
                                    &lt;li&gt;&lt;b&gt;Degree : &lt;/b&gt; test&lt;/li&gt;
                                    &lt;li&gt;&lt;b&gt;DateOfBirth : &lt;/b&gt;10/31/2022 12:00:00 AM&lt;/li&gt;
                                    &lt;li&gt;&lt;b&gt;RecordStatus : &lt;/b&gt;Active&lt;/li&gt;
                                    &lt;li&gt;&lt;b&gt;CreatedDate : &lt;/b&gt;11/1/2022 10:50:28 AM&lt;/li&gt;
                                    &lt;li&gt;&lt;b&gt;CreatedBy : &lt;/b&gt;1&lt;/li&gt;
                                    &lt;li&gt;&lt;b&gt;ModifiedDate : &lt;/b&gt;&lt;/li&gt;
                                    &lt;li&gt;&lt;b&gt;ModifiedBy : &lt;/b&gt;&lt;/li&gt;
                                    &lt;li&gt;&lt;b&gt;TwitterUrl : &lt;/b&gt;&lt;/li&gt;
                                    &lt;li&gt;&lt;b&gt;TwitterFollowers : &lt;/b&gt;&lt;/li&gt;
                                    &lt;li&gt;&lt;b&gt;InstagramUrl : &lt;/b&gt;&lt;/li&gt;
                                    &lt;li&gt;&lt;b&gt;InstagramFollowers : &lt;/b&gt;&lt;/li&gt;
                                    &lt;li&gt;&lt;b&gt;SnapChatUrl : &lt;/b&gt;&lt;/li&gt;
                                    &lt;li&gt;&lt;b&gt;SnapChatFollowers : &lt;/b&gt;&lt;/li&gt;
                                    &lt;li&gt;&lt;b&gt;YouTubeUrl : &lt;/b&gt;&lt;/li&gt;
                                    &lt;li&gt;&lt;b&gt;YouTubeFollowers : &lt;/b&gt;&lt;/li&gt;
                                    &lt;li&gt;&lt;b&gt;FacebookUrl : &lt;/b&gt;&lt;/li&gt;
                                    &lt;li&gt;&lt;b&gt;FacebookFollowers : &lt;/b&gt;&lt;/li&gt;
                                    &lt;li&gt;&lt;b&gt;TikTokUrl : &lt;/b&gt;&lt;/li&gt;
                                    &lt;li&gt;&lt;b&gt;TikTokFollowers : &lt;/b&gt;&lt;/li&gt;
                                    &lt;li&gt;&lt;b&gt;Category : &lt;/b&gt; category more&lt;/li&gt;
                                    &lt;li&gt;&lt;b&gt;Specialized : &lt;/b&gt;test&lt;/li&gt;


                                            &lt;/ul&gt;
                                 
                    
--=-r4uvd8VnK/R7PepsRDxFgA==--

**Comment by abid7437** [comment]
> The problem appears to be that your code is html-encoding the text that you are setting as the HtmlBody.
> 
> MimeKit doesn't do that, so the problem has to be in your code somewhere.

I added the code in main question area, i tried hard then i decided to create a question here, please look at code only a second may be you got an issue ? otherwise thank i will try to resolve

**Comment by jstedfast** [comment]
If you print `param.BodyHTML` to a text file (or to the Console), you'll notice that the value already encodes `<` as `&lt;` and `>` as `&gt;` which is what is causing your problem.

In other words, the `param.BodyHTML` string is already broken before you give it to MimeKit/MailKit.
