### ISSUE TITLE
Push a message

### ISSUE THREAD

**Issue by rk1984** [jstedfast/MailKit#146]
Hi there, 

I'm trying to fetch all messages from  IMAP and push them to a destination server that could be IMAP or Exchange Server.
I was able to fetch all emails, but wondering if MailKit supports pushing emails to destination IMAP? If it supports, how should I implement it?

Thank you for your time!

**Comment by jstedfast** [comment]
I assume by "Push" you mean that you want to Append them to a folder on another IMAP server?

If so, look at the `Append()` method on `ImapFolder` :-)

**Comment by rk1984** [comment]
@jstedfast yep. 
Thanks a lot!

**Comment by rk1984** [comment]
@jstedfast is there any easy way to map MimeMessage to an EWS Message. As I mentioned I'm fetching emails using your library and pushing then to exchange using EWS. An Automapper method will make help me a lot.

**Comment by jstedfast** [comment]
Nope, you'll have to figure that out on your own. You might be able to write the MimeMessage to a stream and then parse it into an EWS Message object.

**Comment by rk1984** [comment]
That was very quick! :)
Thanks a lot!
Will post my Automapper config method if I'll be able to handle it.
