### ISSUE TITLE
Problem with renaming folder on the Outlook imap

### ISSUE THREAD

**Issue by m1adow** [jstedfast/MailKit#1465]
**Describe the bug**
Im trying to rename sub folder in outlook via mailkit and UWP. But when I call mailFolder.RenameAsync(newName) it will not end but on the server folder will be renamed.

**Platform (please complete the following information):**
 - OS: Windows
 - UWP Target version 19041
 - MailKit Version: last

**To Reproduce**
1. Connect to outlook imap and authenticate there
2. Get any sub folder
3. Rename with asynchronous method
4. Method will not end 

**Expected behavior**
Method will end normally

**Code snippets**!

```csharp
// Add your code snippet here.
protected async Task(ImapClient client, Folder folder, string newName)
{
    folder.ToMailFolder().RenameAsync(newName);
}
```

**Comment by jstedfast** [comment]
I'll need a [ProtocolLog](https://github.com/jstedfast/MailKit/blob/master/FAQ.md#ProtocolLog) to diagnose this.

**Comment by m1adow** [comment]
Here is image of my test machine. And how could u seen last console writing was not called after renaming
![image](https://user-images.githubusercontent.com/84251113/202574434-27a58bf5-c1ec-4d4d-bcb2-690efb56d657.png)

Code snippet that I have wrote

`using MailKit;
using MailKit.Net.Imap;
using MailKit.Security;
using System.Net;

var logger = new ProtocolLogger(Console.OpenStandardOutput());

using (var client = new ImapClient(logger))
{
    var credentials = new NetworkCredential("somethinggreat3@outlook.com", "BRxeX_rrr82.kUp");

    await client.ConnectAsync("outlook.office365.com", 993, SecureSocketOptions.SslOnConnect);
    await client.AuthenticateAsync(credentials);

    var folder = client.GetFolder(client.PersonalNamespaces.FirstOrDefault());
    folder = folder.GetSubfolder("Drafts");
    folder = folder.GetSubfolder("Sub draft");

    await folder.RenameAsync(folder, "DRAFTED");

    Console.WriteLine("123");
}`

ProtocolLog

`Connected to imaps://outlook.office365.com:993/
S: * OK The Microsoft Exchange IMAP4 service is ready. [QgBFADEAUAAyADgAMQBDAEEAMAAwADYAMgAuAEQARQBVAFAAMgA4ADEALgBQAFIATwBEAC4ATwBVAFQATABPAE8ASwAuAEMATwBNAA==]
C: A00000000 CAPABILITY
S: * CAPABILITY IMAP4 IMAP4rev1 AUTH=PLAIN AUTH=XOAUTH2 SASL-IR UIDPLUS ID UNSELECT CHILDREN IDLE NAMESPACE LITERAL+
S: A00000000 OK CAPABILITY completed.
C: A00000001 AUTHENTICATE PLAIN ********
S: A00000001 OK AUTHENTICATE completed.
C: A00000002 CAPABILITY
S: * CAPABILITY IMAP4 IMAP4rev1 AUTH=PLAIN AUTH=XOAUTH2 SASL-IR UIDPLUS MOVE ID UNSELECT CLIENTACCESSRULES CLIENTNETWORKPRESENCELOCATION BACKENDAUTHENTICATE CHILDREN IDLE NAMESPACE LITERAL+
S: A00000002 OK CAPABILITY completed.
C: A00000003 NAMESPACE
S: * NAMESPACE (("" "/")) NIL NIL
S: A00000003 OK NAMESPACE completed.
C: A00000004 LIST "" "INBOX"
S: * LIST (\Marked \HasChildren) "/" Inbox
S: A00000004 OK LIST completed.
C: A00000005 LIST "" Drafts
S: * LIST (\HasChildren \Drafts) "/" Drafts
S: A00000005 OK LIST completed.
C: A00000006 LIST "" "Drafts/Sub draft"
S: * LIST (\HasNoChildren) "/" "Drafts/Sub draft"
S: A00000006 OK LIST completed.
C: A00000007 RENAME "Drafts/Sub draft" "Drafts/Sub draft/DRAFTED"
S: A00000007 OK RENAME completed.`

**Comment by jstedfast** [comment]
That's because you are renaming it into a subfolder of itself which causes a recursive problem.

**Comment by m1adow** [comment]
Ok, thank you. Will try it tomorrow 😸
