### ISSUE TITLE
How to send email using "kakao.com" and "daum.net" email accounts using Mailkit?

### ISSUE THREAD

**Issue by Prashant-Y-Girase** [jstedfast/MailKit#1470]
**Is your feature request related to a problem? Please describe.**
Yes, I am able to send emails using the "Gmail/Office365/Outlook/Yahoo/AOL/Naver" accounts. But not able to send emails using the "kakao.com/daum.net" email accounts. I used below SMTP setting for sending emails.

**Kakao.com:** [https://mail.kakao.com/](url)
SMTP server: smtp.kakao.com
SMTP port: 465, SSL Required
ID: (Your ID for KakaoMail)
Password: Your password for KakaoMail

**Daum.net:** [https://mail.daum.net/](url)
SMTP server: smtp.daum.net
SMTP port: 465, Secure connection (SSL) required
ID: (Your ID for DaumMail)
Password: Password to access Daum Mail

![Daum](https://user-images.githubusercontent.com/22464695/202976023-0183ca0d-e2a4-4c9f-b53c-5626cf87c94b.png)

![Kakao](https://user-images.githubusercontent.com/22464695/202976026-e1f11017-e118-4dfd-b797-f1b1b437917f.png)

**Describe the solution you'd like**
```
public async Task Send()
{
	try
	{
		using (var client = new SmtpClient())
		{
			var email = new MimeMessage();
			email.From.Add(MailboxAddress.Parse(userName));
			email.To.Add(MailboxAddress.Parse("receiver@gmail.com"));
			email.Subject = "Test Email Subject";
			email.Body = new TextPart(TextFormat.Html) { Text = "<h1>Example HTML Message Body</h1>" };

			//await client.ConnectAsync("smtp.kakao.com", 465, SecureSocketOptions.StartTls);
			await client.ConnectAsync("smtp.daum.net", 465, SecureSocketOptions.StartTls);
			client.AuthenticationMechanisms.Remove("XOAUTH2");
			await client.AuthenticateAsync(userName, password);
			client.Send(email);
			client.Disconnect(true);
		}
	}
	catch (Exception ex)
	{
		throw ex;
	}
}
```

**Describe alternatives you've considered**
SMTP port 587 also not working for "kakao.com" and "daum.net". But this port number works for "Gmail, Office365, Outlook, Yahoo, AOL, and Naver" accounts.

**Comment by Prashant-Y-Girase** [comment]
I changed the SecureSocketOptions option "SecureSocketOptions.StartTls" to "SecureSocketOptions.Auto" and working fine.

```
public async Task Send()
{
	try
	{
		using (var client = new SmtpClient())
		{
			var email = new MimeMessage();
			email.From.Add(MailboxAddress.Parse(userName));
			email.To.Add(MailboxAddress.Parse("receiver@gmail.com"));
			email.Subject = "Test Email Subject";
			email.Body = new TextPart(TextFormat.Html) { Text = "<h1>Example HTML Message Body</h1>" };

			//await client.ConnectAsync("smtp.kakao.com", 465, SecureSocketOptions.Auto);
			await client.ConnectAsync("smtp.daum.net", 465, SecureSocketOptions.Auto);
			client.AuthenticationMechanisms.Remove("XOAUTH2");
			await client.AuthenticateAsync(userName, password);
			client.Send(email);
			client.Disconnect(true);
		}
	}
	catch (Exception ex)
	{
		throw ex;
	}
}
```

**Comment by jstedfast** [comment]
For future reference, port 465 is the SSL port and does not use StartTLS (hence why SecureSocketOptions.StartTls did not work).

What you wanted was SecureSocketOptions.SslOnConnect.
