### ISSUE TITLE
Invalid local-part at offset 0

### ISSUE THREAD

**Issue by mantasaudickas** [jstedfast/MailKit#1471]
Hello, 

I am getting just another error with "Invalid local-part at offset 0"
Using the code:
```
public class EnvelopeShould
{
    [Fact]
    public void Parse()
    {
        var rawEnvelope =
            "(\"Tue, 23 Dec 2014 17:03:26 +0100\" \" Merry Christmas!\" ((\"Firstname LastName\" NIL \"f.lastname\" \"ex.com\")) ((\"Firstname LastName\" NIL \"f.lastname\" \"ex.com\")) ((\"Firstname LastName\" NIL \"f.lastname\" \"ex.com\")) ((NIL NIL \"\" \"localhost\")) NIL NIL NIL \"<D1329FAF41FC457FA57F0427E6AEB5E0@example.com>\")";

        var parsed = Envelope.TryParse(rawEnvelope, out var envelope);
        Assert.True(parsed);
    }
}
```

Seems like this part is making issue: 
((NIL NIL \"\" \"localhost\"))

if I change it to 
((NIL NIL \"localhost\" \"localhost\"))

it works fine.. however have no idea about details here.
Envelope is received from IMAP server.
Any advice?

**Comment by jstedfast** [comment]
The problem is that `((NIL NIL "" "localhost"))` maps to an email address like `@localhost` which is invalid.

If you look at the raw message data, what is in the To header?

**Comment by jstedfast** [comment]
Wait, are you trying to use MailKit's `Envelope` class to parse real-world IMAP responses?

**Comment by jstedfast** [comment]
I guess at one point there must have been a bug in MailKit that allowed it to successfully parse `@localhost` or perhaps `\u0000@localhost` which resulted in the serialization of `(NIL NIL "" "localhost")`.

Question now is how do we deal with that?

**Comment by mantasaudickas** [comment]
We can of course resynchronize that user account, however not sure if that would change situation?

**Comment by jstedfast** [comment]
Question: Is the example `(NIL NIL "" "localhost")` the exact serialized string? Or did you use the `localhost` string to anonymize some other string value?

**Comment by mantasaudickas** [comment]
This part did not changed. I removed some other user related fields, but this place remained untouched.

**Comment by mantasaudickas** [comment]
Actually we have the same error from 2 clients:

```
("Wed, 04 Nov 2015 03:44:46 +0000" "Daily Digest | Nov 3, 2015" (("SumAll" NIL "noreply" "sumall.com")) (("SumAll" NIL "noreply" "sumall.com")) (("SumAll" NIL "noreply" "sumall.com")) ((NIL NIL "f.lastname" "userdomain.com")) ((NIL NIL "" "localhost")) ((NIL NIL "" "localhost")) NIL "<hashcode@anotherhashcode.sendgrid.net>")
```

and
```
("Thu, 14 Apr 2016 12:04:00 +0000" "The new season is coming..." (("RAF News" NIL "" "localhost")) NIL NIL NIL NIL NIL NIL "<DB3PR05MB077871F726AB0A00C107D8F3857D0@DB3PR05MB0778.example.com>")
```

**Comment by jstedfast** [comment]
okay, thanks, I see what is happening...
