### ISSUE TITLE
MailKit fro NuGet

### ISSUE THREAD

**Issue by kPlusPlus** [jstedfast/MailKit#1472]
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0246	The type or namespace name 'Pop3Client' could not be found (are you missing a using directive or an assembly reference?)	ReadMail	P:\AKDAMAR\ReadMail\Form1.cs	59	Active

Cannot connect to SMTP server 52.97.176.102 (52.97.176.102:587), connect error 10060'

{"Cannot connect to SMTP server 195.29.178.8 (195.29.178.8:587), connect error 10060"}

What is point, where is error/Bug ?

**Comment by jstedfast** [comment]
That doesn't look like an error message from MailKit. Are you sure you're using MailKit?

**Comment by kPlusPlus** [comment]
Yes use.

**Comment by kPlusPlus** [comment]
OK when use super class, ALL WORKING

https://stackoverflow.com/questions/70142852/mailkit-security-sslhandshakeexception-when-running-as-windows-service

  static bool MySslCertificateValidationCallback (object sender, X509Certificate certificate, X509Chain chain, SslPolicyErrors sslPolicyErrors)
        {
            return true;
        }
