### ISSUE TITLE
How can auto sync Gmail/Office365 account using mailkit

### ISSUE THREAD

**Issue by Prashant-Y-Girase** [jstedfast/MailKit#1477]
I stored all folders and emails in our database (cache) for performance improvement which is getting from Gmail/Office365 accounts using IMAP Mailkit. 

If I delete emails from our database (cache) then also deleted those emails from my Gmail/Office365 accounts (working fine for me).
Manually I can get new emails from my Gmail/Office365 accounts and store those emails in the database (cache).

What can I do for the below scenarios?
1. If I delete emails from my Gmail/Office365 accounts then How can I remove those emails from our database (cache)?
2. If I received any new emails in the "Inbox" of my Gmail/Office365 accounts then How can I store those emails in my database (cache) using **auto sync**?

Please help me to solve these problems.

**Comment by jstedfast** [comment]
Best I can offer is the advice I provided for similar questions:

* https://github.com/jstedfast/MailKit/issues/1159
* https://github.com/jstedfast/MailKit/issues/805

Also of value:
* https://www.rfc-editor.org/rfc/rfc5162
* https://www.rfc-editor.org/rfc/rfc7162

**Comment by Prashant-Y-Girase** [comment]
@jstedfast  Thanks for the quick response. I check the above tickets and link.
