### ISSUE TITLE
Folder structure getting in multiple languages from IMAP server

### ISSUE THREAD

**Issue by Prashant-Y-Girase** [jstedfast/MailKit#1478]
We are fetching folder tree structure from the IMAP server and storing it in our cache database. When I draft/delete an email for different email accounts that time I saw the draft/delete folder name are different based on the below email providers.
 
**Draft folder name:**
- Gmail draft folder name is "[Gmail]/Drafts"
- Office365/Outlook/Kakao.com/Daum.Net draft folder name is "Drafts"				
- Yahoo/AOL draft folder name is "Draft"

**Delete folder name:**
- Gmail shows some accounts have a "Trash" folder and some accounts have a "Bin"
- Outlook shows some accounts have a "Deleted Items" folder and some accounts have a "Deleted"

So when I draft/delete an email at that time I pass the draft/delete folder name in the "English" language based on the above email providers.[working fine]

-----------------------------------------------------------------------------------------------------------
**Problems 1:**
I have a Korean Gmail account. When I fetched the folder tree structure from the IMAP server at that time I can't see the default folder name (ex: "Draft/Sent/Trash")  in the English language under the [Gmail] folder but I see the folder name in the Korean language.
Please find out the attachment file which has the Korean Gmail folder structure in .json format

How can I identify which folder is used to store deleted/draft/sent emails for multiple languages?

-----------------------------------------------------------------------------------------------------------
**Problems 2:**
ImapClient.GetFolder(SpecialFolder.Drafts) throws an exception while saving emails in the draft folder for Office365/Outlook accounts.

Note: SpecialFolder is working fine in some accounts and not working for some accounts.

[GmailFolderStructure.txt](https://github.com/jstedfast/MailKit/files/10121759/GmailFolderStructure.txt)

**Comment by jstedfast** [comment]
> Note: SpecialFolder is working fine in some accounts and not working for some accounts.

The `ImapClient.GetFolder(SpecialFolder)` method will ONLY work if the IMAP server supports the `SPECIAL-USE` extension. To check if the IMAP server supports this extension, you can use the following check in C#:

```csharp
if (client.Capabilities.HasFlag (ImapCapabilities.SpecialUse)) {
    var drafts = client.GetFolder (SpecialFolder.Drafts);
}
```

Keep in mind that even if the server supports `SPECIAL-USE`, there may not be an assigned Drafts (or Deleted or whatever else) folder and so the GetFolder() method *may* return `null`.

If the server does not support SPECIAL-USE or if you get a `null` from GetFolder(), then you will probably need to ask the user to select his/her Drafts/Deleted/etc folder(s) -or- just create your own Drafts/Deleted/etc folders on the server and use those.
