### ISSUE TITLE
You are trying to install this package into a project that targets '.NETFramework,Version=v4.5', but the package does not contain any assembly references or content files that are compatible with that framework

### ISSUE THREAD

**Issue by raeldor** [jstedfast/MailKit#1479]
Trying to Install using NuGet and keep getting the error...

Install-Package : Could not install package 'MailKit 3.4.3'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

I seem to have .NET 4.5 frameworks under my 'References', so I'm not sure what's going on here.

**Comment by jstedfast** [comment]
Your project is targeting .NET v4.5 but MailKit no longer supports .NET v4.5 because it is so old that even Microsoft has stopped supporting it.

The minimum version of .NET Framework that Microsoft (and MailKit) support right now is v4.6.2 but I would highly recommend updating to .NET 4.8 or better yet, .NET Core 6.0

**Comment by raeldor** [comment]
Yikes, I guess that's what happens when I let my app fester for a few years.  Appreciate the prompt reply, thank you!

**Comment by jstedfast** [comment]
Yea, Microsoft dropped support for .NET v4.5.2 back in April (MailKit stopped supporting it in, I think, May).

At this point, I would consider .NET Framework <= 4.8.x to be "Legacy" and would recommend avoiding it unless you specifically need to for some reason.

The .NET Core 6.0 platform is long-term supported (as opposed to .NET 5.0 which has already been dropped).

**Comment by raeldor** [comment]
Good info, thank you.  I've updated to VS2022, so I'll look at moving to 6.0 then.  Really appreciate the pointers to get me up to speed, thank you.
