### ISSUE TITLE
SmtpCommandException throws a null reference exception when GetObjectData is called

### ISSUE THREAD

**Issue by jamezor** [jstedfast/MailKit#148]
SmtpCommandException.cs, line 155, does `Mailbox.ToString ()` during `GetObjectData` but the `Mailbox` property is not always assigned.

**Comment by jstedfast** [comment]
Ah, good catch, thanks! I'll fix this momentarily

**Comment by jstedfast** [comment]
Fixed :-)

**Comment by jamezor** [comment]
Excellent, thank you very much! :)
