### ISSUE TITLE
Access Shared mailbox with SaslMechanismOAuth2

### ISSUE THREAD

**Issue by tejaspatel4u** [jstedfast/MailKit#1486]
I am implementing email parser console app in asp.net core application from MS Office 365. I am able to access and parse all emails using SaslMechanismOAuth2. But if I am trying to authenticate my shared email id as **SaslMechanismOAuth2(<sharedmailboxid>, <token>)**, it gives error as "Authaticated but not connected" exception.

I would like to know how can I authenticate and access emails from shared mailbox of MS Office 365.

Earlier I was connecting shared email account using emailid\sharedemailalias and password. I now wanted to access shared email using SaslMechanismOAuth2(<sharedmailboxid>, <token>)

**Comment by jstedfast** [comment]
As far as I know, you would still use `emailid\sharedemailalias` as the username, the only difference is that you would use the SaslMechanismOAuth2.

This question is very specific to the IMAP server you are using and there is no standard mechanism for what you want to do.

If that doesn't work, then I can't help you. You'll have to contact customer support for Microsoft Office365.

**Comment by tejaspatel4u** [comment]
Thanks Jeffrey for your time & efforts. We need to give shared mailbox permissions to OAuth app as well and shared mailbox will be accessible.
