### ISSUE TITLE
How To Delete Multiple Emails From Gmail Using Mailkit?

### ISSUE THREAD

**Issue by Prashant-Y-Girase** [jstedfast/MailKit#1487]
I am able to delete a single email using Mailkit. But when I am trying to delete multiple emails at a time then I get the error "cannot convert from 'System.Collections.Generic.List' to 'MailKit.UniqueId'". Actually, I have all emails UniqueId which I have stored in List. 
ex: List<<long>long> uniqueIdList = new List<<long>long>() { 45901, 45902, 45903 };

```
public async Task BulkDeleteEmailAsync()
{
    try
    {
        List<long> uniqueIdList = new List<long>() { 45901, 45902, 45903 };
        SaslMechanismOAuth2 oauth2 = await Authentication();
        using (var client = new ImapClient())
        {
            await client.ConnectAsync("imap.gmail.com", 993, SecureSocketOptions.SslOnConnect);
            await client.AuthenticateAsync(oauth2);
            IMailFolder folder = client.GetFolder("INBOX");
            folder.Open(FolderAccess.ReadWrite);

            if (!folder.IsOpen == true)
                throw new Exception($"{folder.FullName} is not open.");

            folder.AddFlags(uniqueIdList, MessageFlags.Deleted, false); //here is Error
            folder.Expunge(uniqueIdList, CancellationToken.None); //here is Error
            
            folder.Close();
            await client.DisconnectAsync(true);
        }
    }
    catch (Exception ex)
    {
        throw ex;
    }
}
```

How can I convert or stored List<<long>long> into IList<<UniqueId>UniqueId>?

**Comment by jstedfast** [comment]
The `folder.AddFlags()` method and the `folder.Expunge()` methods take `IList<UniqueId>`, not `IList<long>`.

None of the MailKit IMAP APIs take a `long` to signify a UID.

**Comment by Prashant-Y-Girase** [comment]
@jstedfast @m1adow Thanks for the response. I got it solution on the below link. Which is working fine for me.
[https://stackoverflow.com/questions/74794286/how-to-delete-multiple-emails-from-gmail-using-mailkit/74800775](url)
