### ISSUE TITLE
Email is not sent to the CC and BCC addresses

### ISSUE THREAD

**Issue by jkiller295** [jstedfast/MailKit#1491]
**Describe the bug**
I've been using `System.Net.Mail` Namespace and just moved to MimeKit so please pardon my ignorance.

I use `MailKit.Net.Smtp.SmtpClient` to send emails with `smtp.office365.com` as the host. It sends to the "To" address without problem, but the addresses I add to "CC" or "BCC" do not receive the email. 

**Platform (please complete the following information):**
 - OS: Windows
 - .NET Framework: 4.7
 - MimeKit Version: 3.4
 - Language: C#

**Code Snippets**
```csharp
try
{
	using (SmtpClient client = new SmtpClient())
	{
		await client.ConnectAsync("smtp.office365.com", 587, SecureSocketOptions.StartTlsWhenAvailable);
		AuthenticationResult ar = await GetSmtpToken();
		SaslMechanismOAuth2 oauth2 = new SaslMechanismOAuth2(ar.Account.Username, ar.AccessToken);
		await client.AuthenticateAsync(oauth2);
		MimeMessage message = new MimeMessage();
		message.From.Add(new MailboxAddress("JK", "jk@contoso.com"));
		message.To.Add(new MailboxAddress("JK", "jk@contoso.com"));
		message.Cc.Add(new MailboxAddress("Test", "test@contoso.com"));
                message.Bcc.Add(new MailboxAddress("Test", "test@contoso.com"));
		message.Subject = "How you doin'?";
		message.Body = new TextPart("html")
		{
			Text = @"Hey Jk,

			Testing the new SMTP client

			-- Jk"
		};
		{

			await client.SendAsync(message);
			await client.DisconnectAsync(true);

		}
	}
}
catch (Exception ex)
{
	Console.WriteLine(ex.Message);
}
```
**Expected behaviour**
The CC or BCC mailbox should receive the email but they don't

**Comment by jstedfast** [comment]
Change this line:

```csharp
using (SmtpClient client = new SmtpClient())
```

to:

```csharp
using (SmtpClient client = new SmtpClient(new ProtocolLogger("smtp.log")))
```

Do you see `RCPT TO` commands for the CC/BCC addresses?

**Comment by jkiller295** [comment]
> Change this line:
> 
> ```cs
> using (SmtpClient client = new SmtpClient())
> ```
> 
> to:
> 
> ```cs
> using (SmtpClient client = new SmtpClient(new ProtocolLogger("smtp.log")))
> ```
> 
> Do you see `RCPT TO` commands for the CC/BCC addresses?

Yes, there is. Does that mean it send but the server fail to deliver?

**Comment by jstedfast** [comment]
> Yes, there is. Does that mean it send but the server fail to deliver?

Yes.
