### ISSUE TITLE
OAuth problem

### ISSUE THREAD

**Issue by Praetorian11** [jstedfast/MailKit#1496]
Hello,
I have problem to connect to Azure exchange using both IMAP and POP3. Protocols a listed bellow (some long items are truncated).
In IMAP, property IsConnected and Is Authenticated are both true. Azure configuration is ok, I used it one week ago without problem.

.NET Framework 4.8,  the latest MailKit.

Thank you

=== IMAP ===
Connected to imaps://outlook.office365.com:993/
S: * OK The Microsoft Exchange IMAP4 service is ready. [RgBSADAAUAAyADgAMQBDAEEAMAAwADQAMQAuAEQARQBVAFAAMgA4ADEALgBQAFIATwBEAC4ATwBVAFQATABPAE8ASwAuAEMATwBNAA==]
C: C00000000 CAPABILITY
S: * CAPABILITY IMAP4 IMAP4rev1 AUTH=PLAIN AUTH=XOAUTH2 SASL-IR UIDPLUS ID UNSELECT CHILDREN IDLE NAMESPACE LITERAL+
S: C00000000 OK CAPABILITY completed.
C: C00000001 AUTHENTICATE XOAUTH2 dXNlcj1tYWd...
pTS: C00000001 OK AUTHENTICATE completed.
C: C00000002 CAPABILITY
S: * CAPABILITY IMAP4 IMAP4rev1 AUTH=PLAIN AUTH=XOAUTH2 SASL-IR UIDPLUS MOVE ID UNSELECT CLIENTACCESSRULES CLIENTNETWORKPRESENCELOCATION BACKENDAUTHENTICATE CHILDREN IDLE NAMESPACE LITERAL+
S: C00000002 OK CAPABILITY completed.
C: C00000003 NAMESPACE
S: C00000003 BAD User is authenticated but not connected.
C: C00000004 LIST "" "INBOX"
S: C00000004 BAD User is authenticated but not connected.
S: * BYE Connection closed. 14
C: C00000005 LOGOUT

=== POP3 ===
Connected to pops://outlook.office365.com:995/
S: +OK The Microsoft Exchange POP3 service is ready. [RgBSADAAUAAyADgAMQBDAEEAMAAwADUANQAuAEQARQBVAFAAMgB1ADEALgBQAFIATwBEAC4ATwBVAFQATABPAE8ASwAuAEMATwBNAA==]
C: CAPA
S: +OK
S: TOP
S: UIDL
S: SASL PLAIN XOAUTH2
S: USER
S: .
C: AUTH XOAUTH2
S: + 
C: dXNlcj1tYWdpa2luZm9...
S: -ERR Authentication failure: unknown user name or bad password.
C: QUIT
S: +OK Microsoft Exchange Server POP3 server signing off.

**Comment by jstedfast** [comment]
Looks like Microsoft broke their servers: https://learn.microsoft.com/en-us/answers/questions/1144723/office365-email-imap-user-is-authenticated-but-not.html
