### ISSUE TITLE
Loop Through Individual Threads of a Single Mail

### ISSUE THREAD

**Issue by Reejesh-PK** [jstedfast/MailKit#1497]
Is there a way to loop through individual threads inside the same mail ?

**Comment by jstedfast** [comment]
You'll want to take a look at the [MessageThreader](http://www.mimekit.net/docs/html/M_MailKit_MessageThreader_Thread.htm) class and the [MessageThread](http://www.mimekit.net/docs/html/T_MailKit_MessageThread.htm) class which represents a message node in the thread.
