### ISSUE TITLE
MimeMessage.Load() for MSG files throws "Failed to parse message headers."

### ISSUE THREAD

**Issue by kostelis** [jstedfast/MailKit#1503]
I am trying to extract the attachments from a .msg file. The code works fine for .eml files with attachments, however when I try to load the .msg file using ```MimeMessage.Load ()``` I receive an error message saying ```Failed to parse message headers.```. The .msg file is exported using Outlook: [sample.zip](https://github.com/jstedfast/MailKit/files/10409788/sample.zip). I tried with multiple different .msg files. Some .msg files that do not contain any attachments load fine, but others don't.

**Platform (please complete the following information):**
 - OS: Windows 10
 - .NET Framework: net6.0
 - MailKit Version: 3.4.3

**Exception**
System.FormatException: **Failed to parse message headers.**
   at MimeKit.MimeParser.ParseMessage(Byte* inbuf, CancellationToken cancellationToken)
   at MimeKit.MimeParser.ParseMessage(CancellationToken cancellationToken)
   at MimeKit.MimeMessage.Load(ParserOptions options, Stream stream, Boolean persistent, CancellationToken cancellationToken)
   at MimeKit.MimeMessage.Load(ParserOptions options, Stream stream, CancellationToken cancellationToken)
   at MimeKit.MimeMessage.Load(ParserOptions options, String fileName, CancellationToken cancellationToken)
   at MimeKit.MimeMessage.Load(String fileName, CancellationToken cancellationToken)
   at Program.

**To Reproduce**
Run the code snippet below with the file sample attached above.

**Expected behavior**
It should load the .msg file with attachments.

**Code Snippets**

```csharp
var message = MimeMessage.Load ("/path/to/mail.msg");
var attachments = message.Attachments;

foreach (var attachment in attachments)
{
    var fileName = attachment.ContentDisposition?.FileName ?? attachment.ContentType.Name;
    using (var fs = new FileStream(Path.Combine(resultDir, fileName), FileMode.Create))
    { 
        if (attachment is MessagePart rfc822) {
            rfc822.Message.WriteTo(fs);
        } else {
            var part = (MimePart) attachment;
            part.Content.DecodeTo(fs);
        }
    }
}
```

**Comment by jstedfast** [comment]
The Outlook binary message file format is not supported. MimeKit only supports the MIME format.

You might be able to use another library such as [MsgReader](https://github.com/Sicos1977/MSGReader).
