### ISSUE TITLE
Can the ProtocolLogger class include an ILogger constructor please?

### ISSUE THREAD

**Issue by danzuep** [jstedfast/MailKit#1504]
**Is your feature request related to a problem? Please describe.**
It's frustrating that IProtocolLogger doesn't implement Microsoft.Extensions.Logging.ILogger as it makes dependency injection much harder.

**Describe the solution you'd like**
Please implement Microsoft.Extensions.Logging.ILogger in IProtocolLogger.

**Describe alternatives you've considered**
I've made a [partial implementation](https://github.com/danzuep/MailKitSimplified/blob/main/source/MailKitSimplified.Receiver/Services/MailKitProtocolLogger.cs) of this myself that I'm happy for you to use, but it'd be much better as part of the core MailKit package.

**Additional context**
I'm happy to help with writing this, just let me know what you want the new IProtocolLogger interface to be.

**Comment by danzuep** [comment]
Also, thanks for making such an awesome open source project!

**Comment by jstedfast** [comment]
I'm not sure this makes sense.

**Comment by danzuep** [comment]
What I meant was can you add an ILogger overload to the ProtocolLogger constructor please. This would enable to class to be used with dependency injection and NLog/Serilog file loggers. `public ProtocolLogger(ILogger<ProtocolLogger> logger)`

**Comment by jstedfast** [comment]
If I already needed to depend on Microsoft.DependencyInjection, then it would make more sense to do, but as it stands right now, I'd just be adding a huge dependency to MimeKit for a micro feature that (as far as I know), there is very little interest in having.

**Comment by danzuep** [comment]
The only external library requirement for ILogger is Microsoft.Extensions.Logging.Abstractions which is very lightweight.

**Comment by jstedfast** [comment]
There are a few problems:

1. Messages can contain binary data, so they aren't really appropriate to log via strings.
2. Should message data even be logged at all via the ILogger? If not, things get complicated.
