### ISSUE TITLE
I don't access the mail hosted in outlook.office365.com neither by POP3 nor by IMAP

### ISSUE THREAD

**Issue by ebenito** [jstedfast/MailKit#1506]
I have an account created in office 365 that I need to access, just for reading emails (I don't need SMTP). But I can't connect, although all the connection data is correct, if I put it in an email management program, it accesses without problem.

 - OS: Windows 10
 - .NET Framework: tested with framework 4.8 and NET6
 - MailKit Version: 3.4.3

The **exception message** I get is "**LOGIN failed**", just by calling the Authenticate method.

In StackTrace: 
`   at MailKit.Net.Imap.ImapClient.<AuthenticateAsync>d__103.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MailKit.Net.Imap.ImapClient.Authenticate(Encoding encoding, ICredentials credentials, CancellationToken cancellationToken)
   at MailKit.MailService.Authenticate(Encoding encoding, String userName, String password, CancellationToken cancellationToken)
   at MailKit.MailService.Authenticate(String userName, String password, CancellationToken cancellationToken)
   at EXE_ImportarLeadsCorreos_IMAP.Program.Main(String[] args) in _[my app]_\Program.cs:line 22`

```csharp
 using (var client = new ImapClient(new ProtocolLogger("imap.log")))
            {
                try
                {
                    client.Connect("outlook.office365.com", 993, MailKit.Security.SecureSocketOptions.Auto);
                    client.Authenticate("[here my email]", "[here my pass]");

                    var inbox = client.Inbox;
                    inbox.Open(FolderAccess.ReadOnly);

                    Console.WriteLine("Total messages: {0}", inbox.Count);
                    Console.WriteLine("Recent messages: {0}", inbox.Recent);

                    for (int i = 0; i < inbox.Count; i++)
                    {
                        var message = inbox.GetMessage(i);
                        Console.WriteLine("Subject: {0}", message.Subject);
                    }

                    client.Disconnect(true);
                
                }
                catch (Exception ex)
                {
                    Console.WriteLine("ERROR en acceso IMAP: " + ex.Message);                    
                }
            }
```

**Protocol Logs**
Connected to imaps://outlook.office365.com:993/
S: * OK The Microsoft Exchange IMAP4 service is ready. [TABPADIAUAAyADYANQBDAEEAMAAxADkAMAAuAEcAQgBSAFAAMgA2ADUALgBQAFIATwBEAC4ATwBVAFQATABPAE8ASwAuAEMATwBNAA==]
C: A00000000 CAPABILITY
S: * CAPABILITY IMAP4 IMAP4rev1 AUTH=PLAIN AUTH=XOAUTH2 SASL-IR UIDPLUS ID UNSELECT CHILDREN IDLE NAMESPACE LITERAL+
S: A00000000 OK CAPABILITY completed.
C: A00000001 AUTHENTICATE PLAIN ********
S: A00000001 NO AUTHENTICATE failed.
C: A00000002 LOGIN ******** "********"
S: A00000002 NO LOGIN failed.

If I try **with POP3** the result is similar:
Connected to pops://outlook.office365.com:995/
S: +OK The Microsoft Exchange POP3 service is ready. [TABPADQAUAAxADIAMwBDAEEAMAA0ADMANgAuAEcAQgBSAFAAMQAyADMALgBQAFIATwBEAC4ATwBVAFQATABPAE8ASwAuAEMATwBNAA==]
C: CAPA
S: +OK
S: TOP
S: UIDL
S: SASL PLAIN XOAUTH2
S: USER
S: .
C: AUTH PLAIN
S: + 
C: ********
S: -ERR Authentication failure: unknown user name or bad password.
C: USER ********
S: +OK
C: PASS ********
S: -ERR Logon failure: unknown user name or bad password.

I don't understand why this error is due, when the credentials are fine.
I think I've read that one solution is to enable OAuth2 and create an application in Azure that later references it in my .NET application; But is it the only way? I don't manage the mail, and it wouldn't be easy to get it.

Thank you

**Comment by jstedfast** [comment]
Microsoft disabled the use of usernames and passwords for logging into Office365. Your only option is to use OAuth2.

You can read up on how to set that up here: https://github.com/jstedfast/MailKit/blob/master/ExchangeOAuth2.md
