### ISSUE TITLE
Add .NET global tool

### ISSUE THREAD

**Issue by kapsiR** [jstedfast/MailKit#1508]
**Is your feature request related to a problem? Please describe.**
Many of the "old ways" of sending emails on different platforms and tools are deprecated, e.g. taskschd, PowerShell, legacy .NET implementation, ...  
There are no direct replacements available, MailKit can solve this 

**Describe the solution you'd like**
A simple tool for sending emails in scenarios like scripting, quick tests or simple system alerts

**Describe alternatives you've considered**
An alternative would be to load the MailKit dlls directly in e.g. PowerShell, but it would be very convenient to have simple CLI options too

**Additional context**
Where this could he helpful:
- Any scripting related email log, alert
- Sending emails with task scheduler, cron, ...
- Quick email via CLI
- ...

**Comment by kapsiR** [comment]
Would this be in scope of this repo or should anyone build a .NET tool on top of MailKit in another project?  
I recently though this would be very helpful to get rid of some boilerplate in the CLI.

**Comment by jstedfast** [comment]
I'm not really sure that MailKit is the appropriate project for this.

Likely the tool you'd like would be based on MimeKit/MailKit, but my focus is on a library and not a tool.

**Comment by kapsiR** [comment]
Thanks for clarifying this! I appreciate your time!
