### ISSUE TITLE
The IMAP server has unexpectedly disconnected.  Microsoft Exchange Server 2003

### ISSUE THREAD

**Issue by xiongjx** [jstedfast/MailKit#1512]
**Describe the bug**
Authenticate Exception

**Platform (please complete the following information):**
 - OS: Windows
 - .NET Framework: .Net Core 6
 - MailKit Version: 3.5.0

**Exception**
Connected to imap://*.*.*.*:143/?starttls=when-available
S: * OK Microsoft Exchange Server 2003 IMAP4rev1 服务器版本 6.5.7638.1 (*.*.com) 已就绪。
C: A00000000 CAPABILITY
S: * CAPABILITY IMAP4 IMAP4rev1 IDLE LOGIN-REFERRALS MAILBOX-REFERRALS NAMESPACE LITERAL+ UIDPLUS CHILDREN
S: A00000000 OK CAPABILITY completed.
IMAP Connected
C: A00000001 LOGIN ******** ********
S: A00000001 OK LOGIN completed.
C: A00000002 CAPABILITY
S: * CAPABILITY IMAP4 IMAP4rev1 IDLE LOGIN-REFERRALS MAILBOX-REFERRALS NAMESPACE LITERAL+ UIDPLUS CHILDREN
S: A00000002 OK CAPABILITY completed.
C: A00000003 NAMESPACE
IMAPMailKit.Net.Imap.ImapProtocolException: The IMAP server has unexpectedly disconnected.
   at MailKit.Net.Imap.ImapStream.ReadAhead(Int32 atleast, CancellationToken cancellationToken)
   at MailKit.Net.Imap.ImapStream.ReadToken(String specials, CancellationToken cancellationToken)
   at MailKit.Net.Imap.ImapEngine.ReadTokenAsync(Boolean doAsync, CancellationToken cancellationToken)
   at MailKit.Net.Imap.ImapCommand.StepAsync(Boolean doAsync)
   at MailKit.Net.Imap.ImapEngine.IterateAsync(Boolean doAsync)
   at MailKit.Net.Imap.ImapEngine.RunAsync(ImapCommand ic, Boolean doAsync)
   at MailKit.Net.Imap.ImapEngine.QueryNamespacesAsync(Boolean doAsync, CancellationToken cancellationToken)
   at MailKit.Net.Imap.ImapClient.OnAuthenticatedAsync(String message, Boolean doAsync, CancellationToken cancellationToken)
   at MailKit.Net.Imap.ImapClient.AuthenticateAsync(Encoding encoding, ICredentials credentials, Boolean doAsync, CancellationToken cancellationToken)
   at MailKit.Net.Imap.ImapClient.Authenticate(Encoding encoding, ICredentials credentials, CancellationToken cancellationToken)
   at MailKit.MailService.Authenticate(Encoding encoding, String userName, String password, CancellationToken cancellationToken)
   at MailKit.MailService.Authenticate(String userName, String password, CancellationToken cancellationToken)
   at ConsoleApp1.Program.Main(String[] args) in D:\ConsoleApp1\ConsoleApp1\Program.cs:line 77

**Code Snippets**
using(var client=new ImapClient(new ProtocolLogger(Console.OpenStandardOutput())))
{                   
try
   {
      client.Connect("*.*.*.*", 143);
      Console.WriteLine("IMAP Connected");
  //    client.ServerCertificateValidationCallback += (s, c, ch, e) => { return true; };           
  //    client.AuthenticationMechanisms.Clear();
      client.Authenticate(userName, password);
      Console.WriteLine("IMAP Authenticate Success");  
   }
  catch(Exception e)
    {
    }
}

**Comment by TechGuyAlabama** [comment]
I'm having a similar issue. I am trying to connect to Yahoo.

.Net Framework 4.7.2 (c#)
Mimekit 3.5
Mailkit 3.5

I placed my code in Pastebin since it was long:

https://pastebin.com/P6wq2YNR

The settings I tried:

      var es = new EmailSetting();
      var em = new EmailMessage();
      es.AuthType = SecureSocketOptions.Auto; // tried various settings here
      es.EnableSmtpLog = true;
      em.EmailBody = "This is a test";
      var r = new Random();
      em.EmailSubject = $"Test!";
      em.FromEmail = "myacct@yahoo.com";
      es.IsAuthenticationRequired = true;
      es.IsSslEnabled = true;
      es.SmtpPassword = "SomeCrazyLongPassword";
      es.SmtpPort = 995;   // tried various ports here
      es.SmtpServer = "smtp.mail.yahoo.com";
      es.SmtpUsername= "myacct@yahoo.com";
      var to = new List<string>();
      to.Add("me@gmail.com");
      em.ToEmail = to;
      var res = PublicClass.SendMail(es,em);

My Error:

MailKit.Net.Smtp.SmtpProtocolException: 'The SMTP server has unexpectedly disconnected.'

"   at MailKit.Net.Smtp.SmtpStream.ReadAhead(CancellationToken cancellationToken)\r\n   at MailKit.Net.Smtp.SmtpStream.ReadResponse(CancellationToken cancellationToken)\r\n   at MailKit.Net.Smtp.SmtpStream.SendCommand(String command, CancellationToken cancellationToken)\r\n   at MailKit.Net.Smtp.SmtpClient.Authenticate(Encoding encoding, ICredentials credentials, CancellationToken cancellationToken)\r\n   at MailKit.MailService.Authenticate(Encoding encoding, String userName, String password, CancellationToken cancellationToken)\r\n   at MailKit.MailService.Authenticate(String userName, String password, CancellationToken cancellationToken)\r\n   at SSS.SuburbanEmail.Email.SendEmail.Send(EmailSetting emailSetting, EmailMessage emailMessage) in D:\\Source\\Suburban\\Miscellaneous\\SuburbanMail\\Email\\SendEmail.cs:line 156"

Any suggestions?

**Comment by jstedfast** [comment]
@TechGuyAlabama 

Port 995 is POP3, not SMTP.

The SMTP ports are: 25, 465 (SslOnConnect), or 587.

@xiongjx 

There's nothing MailKit can do in your situation. Your network connection was lost, either because the server disconnected your or because your router went down or something.

**Comment by TechGuyAlabama** [comment]
@jstedfast Sorry, that was a typo but as I said in the comment, I tried various port. Not sure why 995 was there for that.

I've tried various physical locations attempting to connect. I'm getting the same message regardless where I connect. I do not believe this is a network issue as I can send and receive with any other account but Yahoo.

Thanks for your input!

**Comment by xiongjx** [comment]
Thanks@jstedfast
I can receive the email use imap protocol with lumisoft.net lib

**Comment by xiongjx** [comment]
lumisoft.net 2 from nuget

**Comment by jstedfast** [comment]
I'm not sure how that is supposed to help, but ok.

If Socket.Receive() returns 0 bytes, then it means the server has disconnected. Just because it doesn't disconnect lumisoft.net 1 time doesn't mean it's a bug in MailKit code anywhere.

It just means you got lucky.

**Comment by xiongjx** [comment]
I just want to give more information to help you, thanks for your great job!
Lumisoft.net doesn't disconnect every time.

**Comment by jstedfast** [comment]
1. Download MailKit source code
2. Open https://github.com/jstedfast/MailKit/blob/master/MailKit/Net/NetworkStream.cs
3. Go to the Read() method on line 162
4. Modify the code to look like this:

```csharp
try {
	int result = return Socket.Receive (buffer, offset, count, SocketFlags.None);
	return result;
} catch (SocketException ex) {
	throw new IOException (ex.Message, ex);
}
```

5. Put a breakpoint on `return result;` and change the Condition in your breakpoint so it only hits when `result == 0`
6. Put a breakpoint on `throw new IOException (ex.Message, ex);`
7. Run your code

Does it hit the breakpoint? What is the value of the `count` variable?

**Comment by xiongjx** [comment]
Thanks!
I'll try 4 hours later in work time

**Comment by xiongjx** [comment]
> * Does it hit the breakpoint?       Yes
> * What is the value of the `count` variable? 4096
> * What is the value of the `Socket.Blocking` property?  true

Thanks

**Comment by xiongjx** [comment]
![mailkit](https://user-images.githubusercontent.com/11856131/218641556-b5befc57-b8be-43a9-991c-68b9358844f3.png)

**Comment by jstedfast** [comment]
The Socket is set to use Blocking IO with a ReadTimeout of 120000 milliseconds (2 minutes).

What this means is that the Receive() method will not return until it has received data *or* until it has waited 2 minutes and still no data has been received.

In the latter case, it would throw a SocketException with a SocketError value of TimedOut.

What happened instead is that Receive() returned saying 0 bytes were read which means that the server closed the connection.

**Comment by jstedfast** [comment]
Does the lumisoft.net IMAP client send the `NAMESPACE` command?

Can you get me a log from lumisoft's IMAP session that works?

**Comment by jstedfast** [comment]
For reference, the code that calls NetworkStream.Read() (which is the method I had you set a breakpoint in) is [ImapStream.ReadAhead()](https://github.com/jstedfast/MailKit/blob/master/MailKit/Net/Imap/ImapStream.cs#LL306C62-L306C62).

If you look in that method (which is also very simple), you can see that it attempts to read into an input buffer. If any data is read, it immediately logs the received data (which is how I know that the Exchange server is not sending a response to the `NAMESPACE` command from your protocol log).

The line above the Stream.Read() call is:

```csharp
network?.Poll (SelectMode.SelectRead, cancellationToken);
```

In your case, `network` will be non-null which means it will call the Poll() method to wait for data to become available for reading.

You can find the Poll() method toward the bottom of [NetworkStream.cs](https://github.com/jstedfast/MailKit/blob/master/MailKit/Net/NetworkStream.cs#L285) on line 285.

Since your code does not pass a `CancellationToken` to the Authenticate() method, the Poll() method will no-op because, by default, every ImapClient/ImapFolder method that takes an optional CancellationToken will use `CancellationToken.None` which is non-cancellable.

You could try creating a `new CancellationTokenSource()` and then passing `cancellationTokenSource.Token` to the Authenticate() method to see if that changes anything ( don't expect it will, but you could try):

```csharp
using var cts = new CancellationTokenSource();
client.Authenticate(userName, password, cts.Token);
```

**Comment by TechGuyAlabama** [comment]
Just to throw it out there, my issue ended up being that the user setup extra security on the account which required an App password on Yahoo.  

For reference:  https://help.yahoo.com/kb/SLN15241.html

Thanks for the help!

**Comment by jstedfast** [comment]
@TechGuyAlabama I completely forgot that Yahoo has done that now, too.

Just about all of the major free mail servers out there are now requiring OAuth and/or App-Specific Passwords for added security and will no longer accept the user's normal password.

**Comment by xiongjx** [comment]
09:17:14:Connecting to *.*.*.*:143.
09:17:14:Connected, localEP=' *.*.*.*:65162'; remoteEP=' *.*.*.*:143'.
09:17:14:* OK Microsoft Exchange Server 2003 IMAP4rev1 ???????汾 6.5.7638.1 (*.*.com) ???????
09:17:14:00001 LOGIN "zhang***" <PASSWORD-REMOVED>
09:17:14:00001 OK LOGIN completed.
09:17:14:00002 SELECT "INBOX"
09:17:14:* 3 EXISTS
09:17:14:* 0 RECENT
09:17:14:* FLAGS (\Seen \Answered \Flagged \Deleted \Draft $MDNSent)
09:17:14:* OK [PERMANENTFLAGS (\Seen \Answered \Flagged \Deleted \Draft $MDNSent)] Permanent flags
09:17:14:* OK [UIDVALIDITY 263937] UIDVALIDITY value
09:17:14:00002 OK [READ-WRITE] SELECT completed.
09:17:14:00003 FETCH 1:* (ENVELOPE UID FLAGS INTERNALDATE RFC822)
09:17:15:* 1 FETCH (ENVELOPE ("Sat, 11 Feb 2023 16:06:48 +0800" "=?gb2312?B?1tjS****z+suLK1A==?=" (("=?gb2312?B?MDU2Me/ySDI7bz+0d**osrS?=" NIL "dai**" "*.*.com")) (("=?gb2312?B?MDU2MDk2tPe/ySDI7bz+0dC3osrS?=" NIL "dai**" "*.*.com")) (("=?gb2312?B?MDU2MDk2tPe/ySDI7bz+0dC3osrS?=" NIL "dai**" "*.*.com")) (("=?gb2312?B?MDU2MTA31cXX07rAIMjtvP7R0LeiytI=?=" NIL "zhang**" "*.*.com")) NIL NIL NIL "<52F46C41B17B97**BEB3A5F1C0D2478F0044@*.*.*.com>") UID 129 FLAGS (\Seen) INTERNALDATE "11-Feb-2023 16:06:48 +0800" RFC822 {1557}
09:17:15:Readed string-literal 1557 bytes.
09:17:15:)
09:17:15:* 2 FETCH (ENVELOPE ("Sat, 11 Feb 2023 16:09:22 +0800" "=?gb2312?B?1tj****tc3Tyrz+suLK1A==?=" (("=?gb2312?B?MD**2tPe/ySDI7bz+0d**osrS?=" NIL "dai**" "*.*.com")) (("=?gb2312?B?MDU2MDk2tPe/ySDI7bz+0dC3osrS?=" NIL "dai**" "*.*.com")) (("=?gb2312?B?MDU2MDk2tPe/ySDI7bz+0dC3osrS?=" NIL "dai**" "*.*.com")) (("=?gb2312?B?MDU2MTA31cXX07rAIMjtvP7R0LeiytI=?=" NIL "zhang**" "*.*.com")) NIL NIL NIL "<52F46C41B17B97**BEB3A5F1C0D2478F0044@*.*.*.com>") UID 130 FLAGS (\Seen) INTERNALDATE "11-Feb-2023 16:09:22 +0800" RFC822 {1506}
09:17:15:Readed string-literal 1506 bytes.
09:17:15:)
09:17:15:00003 OK FETCH completed.
09:17:15:00004 LOGOUT
09:17:15:Disconnected.

**Comment by jstedfast** [comment]
Seems that your other IMAP library doesn't send a NAMESPACE command.

Maybe the Exchange server breaks when it receives that command?

You'll have to edit ImapEngine.cs to make it ignore the NAMESPACE capability to work around that.

**Comment by jstedfast** [comment]
It also doesn't seem to send the CAPABILITY command (before or after logging in) to find out what commands the IMAP server supports.

**Comment by jstedfast** [comment]
Try editing [ImapEngine.cs](https://github.com/jstedfast/MailKit/blob/master/MailKit/Net/Imap/ImapEngine.cs#L2589) on line 2589 and changing the line:

```csharp
if ((Capabilities & ImapCapabilities.Namespace) != 0) {
```

to:

```csharp
if (false && (Capabilities & ImapCapabilities.Namespace) != 0) {
```

**Comment by xiongjx** [comment]
> Try editing [ImapEngine.cs](https://github.com/jstedfast/MailKit/blob/master/MailKit/Net/Imap/ImapEngine.cs#L2589) on line 2589 and changing the line:
> 
> ```cs
> if ((Capabilities & ImapCapabilities.Namespace) != 0) {
> ```
> 
> to:
> 
> ```cs
> if (false && (Capabilities & ImapCapabilities.Namespace) != 0) {
> ```
> 
> If this fixes the issue, I'll add a QuirksMode for Exchange 2003 to avoid using the NAMESPACE command.

Fixed the issue!
Thank you very much!

**Comment by jstedfast** [comment]
Ok, I'll add a work-around for Exchange 2003.

**Comment by chenzuo** [comment]
> @TechGuyAlabama
> 
> Port 995 is POP3, not SMTP.
> 
> The SMTP ports are: 25, 465 (SslOnConnect), or 587.
> 
> @xiongjx
> 
> There's nothing MailKit can do in your situation. Your network connection was lost, either because the server disconnected your or because your router went down or something.

https://help.aliyun.com/document_detail/36576.html

SMTP
smtp.mxhichina.com
465

using var smtp = new SmtpClient();
smtp.Connect(_mailSettings.Host, _mailSettings.Port, **### SecureSocketOptions.SslOnConnect**);
 smtp.Authenticate(_mailSettings.Mail, _mailSettings.Password);
 await smtp.SendAsync(mimeMessage);
smtp.Disconnect(true,cancellationToken);

thanks, it has been resolved my issue and successfully sent mail.
