### ISSUE TITLE
Mailkit: email showing only in english language. How to showing email for another languages (Korean, Japanese, Chinese, etc...)?

### ISSUE THREAD

**Issue by Prashant-Y-Girase** [jstedfast/MailKit#1514]
**Describe the bug**
I received/sent emails in Korean, Japanese, Chinese, etc languages except for English into Gmail, Office365, Outlook, etc accounts than was able to see the correct email details in respective languages. 
But when I am fetching emails from the IMAP server using Mailkit at that time getting unreadable emails.

**Platform (please complete the following information):**
 - OS: Windows 10, Linux
 - .NET Framework: .Net Core 3.1
 - MailKit Version: 3.5.0

**Code Snippets**
Fetch email from IMAP server using Mailkit

![image](https://user-images.githubusercontent.com/22464695/218955581-6f2b0396-9557-4dde-afa4-d151f8fb8501.png)

Below email properly showing in Outlook

![image](https://user-images.githubusercontent.com/22464695/218955875-e57aa6f7-8a57-46f5-b428-f5b021f3b5eb.png)

![image](https://user-images.githubusercontent.com/22464695/218955736-539a1d70-6ec4-4790-a39f-c1a8b300dd92.png)

```
using MailKit;
using MailKit.Net.Imap;
using MailKit.Net.Smtp;
using MailKit.Security;

SaslMechanismOAuth2 oauth2 = await UserAuthenticate();
using (var client = new ImapClient())
{
	await client.ConnectAsync("outlook.office365.com", 993, SecureSocketOptions.SslOnConnect);
	await client.AuthenticateAsync(oauth2);
	IMailFolder folder = client.GetFolder(folderName);
	folder.Open(FolderAccess.ReadOnly);
	var results = folder.Search(MailKit.Search.SearchQuery.All).Reverse();
	if (results?.Count() > 0)
	{
		foreach (var uniqueId in results)
		{
			var message = folder.GetMessage(uniqueId);
		}
	}
}
```

If something missing from my side. Please help me for fix the above issue

**Comment by jstedfast** [comment]
https://github.com/jstedfast/MailKit/blob/master/FAQ.md#q-why-does-text-show-up-garbled-in-my-aspnet-core--net-core--net-5-app

**Comment by Prashant-Y-Girase** [comment]
@jstedfast Awesome!! Thank you so much, your solution is working fine for me.
