### ISSUE TITLE
Question: Does it support .eml parsing ?

### ISSUE THREAD

**Issue by Legends** [jstedfast/MailKit#1517]
Does it support parsing of .eml files?
If not is there a library which only does .eml parsing?

**Comment by jstedfast** [comment]
[MimeKit](https://github.com/jstedfast/MimeKit) parses MIME message files (*.eml) which MailKit depends on, so yes.

But if all you need is to parse .eml files, then you can just add the MimeKit nuget instead of MailKit.

**Comment by Legends** [comment]
Great, thanks for the quick response.

**Comment by Legends** [comment]
Ok, MimeKitLight is enough. Perfect!
