### ISSUE TITLE
Accessing IMAP calendar, contacts, notes, tasks etc

### ISSUE THREAD

**Issue by rk1984** [jstedfast/MailKit#152]
Is there any way how can I fetch items like calendar appointment, contacts, notes, tasks and other items in folders? 
I'm aware there is not parser for those items, but I just need to be able to fetch them and save locally.

Thanks a lot!

**Comment by jstedfast** [comment]
Assuming you mean that these items are stored on an IMAP server, they must be in the rfc5322 message format and so you can already fetch them like you'd fetch any message in a folder.

**Comment by unnatRevo** [comment]
How to identify such messages like are they of Contacts (.vcf format) or Calendar (.ics format) or regular email (.eml/.msg format file)?

**Comment by jstedfast** [comment]
I don't know, I've never seen them.

**Comment by unnatRevo** [comment]
> I don't know, I've never seen them.

Can you please help me with, how to save such messages into the storage drive and open with Microsoft Outlook client and open it successfully !?

Below is the output of the file which I've got from the Calendar folder.

```
MIME-Version: 1.0
Content-Type: text/plain; charset="us-ascii"
From: Microsoft Exchange Server 2010
To: Unnat <my_id@my_domain.com>
Subject: Retrieval using the IMAP4 protocol failed for the following message:
 81
Content-Transfer-Encoding: quoted-printable

The server couldn't retrieve the following message:

Subject: "Mail subject"
From: "Steve" ("/o=3DCAPTAIN/ou=3DExchange Administrative Group (F=
YDIBOHF23SUIKD)/cn=3DRecipients/cn=3Dd4ac10b72ca2446eb0cb65bcc110d4eb-Steve=
Koh")
Sent date: 9/12/2019 2:56:56 PM

The message hasn't been deleted. You might be able to view it using either =
Outlook or Outlook Web App. You can also contact the sender to find out wha=
t the message says.=
```
With this output, Calendar application cannot open this file.

**Comment by jstedfast** [comment]
Looks like a fake message that the server auto-generated specially for your FETCH request.

This means that you can't get calendar data using MailKit. Sorry. There's just no way to get it because your server doesn't support downloading calendar data via the IMAP protocol.

**Comment by unnatRevo** [comment]
Fair enough. can I download calendar or other folder messages via IMAP protocol by any mean?

**Comment by unnatRevo** [comment]
Fair enough. can I download calendar or other folder messages via IMAP protocol by any mean?

**Comment by jstedfast** [comment]
Nope. You need to use the Exchange Protocol which MailKit does not support.
