### ISSUE TITLE
Auto delete of debug log files

### ISSUE THREAD

**Issue by ZenwalkerD** [jstedfast/MailKit#1521]
**Is your feature request related to a problem? Please describe.**
We log all SMTP related debug data to a log file onto a local storage via ProtocolLogger interface/class

**Describe the solution you'd like**
Can there be an auto delete option like Serilog provides https://github.com/serilog/serilog-sinks-file#limits refer: retainedFileCountLimit property

**Describe alternatives you've considered**
To write a script to do the job; but this is very expensive as our application runs in many instances in cloud. Also cost-effort wise not suitable.

**Comment by jstedfast** [comment]
Since your application is what decides on what to name the log files, how would MailKit be able to clean them up?
