### ISSUE TITLE
Autogenerating filenames for attached emails when Filename=null

### ISSUE THREAD

**Issue by enediel2017** [jstedfast/MailKit#1522]
Hello
While downloading emails from Microsoft Exchange I came across examples where the attached file was an email and the filename returned is null.
Is it possible to include in the library to produce generic names for these cases and make the solution more transparent for the application using the library?

Thank you for your attention

**Comment by jstedfast** [comment]
I don't think this makes sense for MimeKit or MailKit to do.

It needs to be able to tell you that an "attachment" doesn't have a specified FileName just like it does now.

If I make it auto-generate a filename if one doesn't already exist when you access the MimePart.FileName property, then it would provide false information.
