### ISSUE TITLE
body builder htmlbody rendering on local but when deployed on linux it is sending html tags

### ISSUE THREAD

**Issue by Raahulkanhaiya** [jstedfast/MailKit#1525]
body builder htmlbody rendering on local but when deployed on linux it is sending html tags

**Comment by jstedfast** [comment]
What are you using to 'render' it on 'local'? What OS is 'local'? What are you using to 'render' the message on Linux?

Are you generating the message on 'local' and then rendering that?

And are you generating the message on Linux and then rendering that on Linux?

Or are you generating the message and sending it to your 'local' machine and also the Linux machine?

Have you compared the raw message? What do they look like?
