### ISSUE TITLE
Notifications (delivery, reading)

### ISSUE THREAD

**Issue by Rialzarre** [jstedfast/MailKit#1527]
Hello!
Can you please tell me how i can send email with the "notify of delivery" and "notify of read" flags?

**Comment by jstedfast** [comment]
### Q: How can I request a notification when the message is read by the user?

The first thing I need to make clear is that requesting a notification does not guarantee that you'll actually
get one. In order for you to receive a notification that the message was read by its recipient, the recipient's
mail client needs to know how to send such a notification *and* that the user has enabled it to do so.

That said, here's how you can request a notification when the recipient reads the message that has been sent:

```csharp
// Add the following header to tell the recipient's client that you want to receive a
// notification when the message has been read by the user.
message.Headers[HeaderId.DispositionNotificationTo] = new MailboxAddress ("My Name", "me@example.com").ToString (true);
```

For more information on this topic, read [rfc3798](https://tools.ietf.org/html/rfc3798).

### Q: How can I process a read receipt notification?

A read receipt notification comes in the form of a MIME message with a top-level MIME part with a MIME-type
of `multipart/report` that has a `report-type` parameter with a value of `disposition-notification`.

You could check for this in code like this:

```csharp
var report = message.Body as MultipartReport;
if (report != null && report.ReportType.Equals ("disposition-notification", StringComparison.OrdinalIgnoreCase)) {
    // This is a read receipt notification.
}
```

The first part of the `multipart/report` will be a human-readable explanation of the notification.

The second part will have a MIME-type of `message/disposition-notification` and be represented by
a [MessageDispositionNotification](http://www.mimekit.net/docs/html/T_MimeKit_MessageDispositionNotification.htm).

This notification part will contain a list of header-like fields containing information about the
message that this notification is for such as the `Original-Message-Id`, `Original-Recipient`, etc.

```csharp
var notification = report[1] as MessageDispositionNotification;
if (notification != null) {
    // Get the Message-Id of the message this notification is for...
    var messageId = notification.Fields["Original-Message-Id"];
}
```
For more information on this topic, read [rfc3798](https://tools.ietf.org/html/rfc3798).

### Q: How can I request a notification when the message I am sending is delivered?

For this, you will need to subclass SmtpClient to override a few methods.

```csharp
public class DSNSmtpClient : SmtpClient
{
    public DSNSmtpClient ()
    {
    }

    /// <summary>
    /// Get the envelope identifier to be used with delivery status notifications.
    /// </summary>
    /// <remarks>
    /// <para>The envelope identifier, if non-empty, is useful in determining which message
    /// a delivery status notification was issued for.</para>
    /// <para>The envelope identifier should be unique and may be up to 100 characters in
    /// length, but must consist only of printable ASCII characters and no white space.</para>
    /// <para>For more information, see rfc3461, section 4.4.</para>
    /// </remarks>
    /// <returns>The envelope identifier.</returns>
    /// <param name="message">The message.</param>
    protected override string GetEnvelopeId (MimeMessage message)
    {
        // Since you will want to be able to map whatever identifier you return here to the
        // message, the obvious identifier to use is probably the Message-Id value -or-
        // whatever value you want to use to look up the message in your database.
        return message.MessageId;
    }

    /// <summary>
    /// Get the types of delivery status notification desired for the specified recipient mailbox.
    /// </summary>
    /// <remarks>
    /// Gets the types of delivery status notification desired for the specified recipient mailbox.
    /// </remarks>
    /// <returns>The desired delivery status notification type.</returns>
    /// <param name="message">The message being sent.</param>
    /// <param name="mailbox">The mailbox.</param>
    protected override DeliveryStatusNotification? GetDeliveryStatusNotifications (MimeMessage message, MailboxAddress mailbox)
    {
        // In this example, we want to be notified of successful deliveries, failures to deliver, and delays.
        return DeliveryStatusNotification.Success | DeliveryStatusNotification.Failure | DeliveryStatusNotification.Delay;
    }
}
```

Now that you have a custom DSNSmtpClient, you can use it more-or-less as normal except that you'll also want to set the `DeliveryStatusNotificationType`.

```csharp
using (var client = new DSNSmtpClient ()) {
    client.Connect (host, port, sslOptions);
    client.Authenticate (username, password);

    // We can either have the delivery-status-notification email that the server sends us contain only the message headers
    // -or- have it include the full message. In general, we probably just want the headers.
    client.DeliveryStatusNotificationType = DeliveryStatusNotificationType.HeadersOnly;

    client.Send (message);

    client.Disconnect (true);
}
```

**Comment by Rialzarre** [comment]
Hello again =)

I took your advice, I successfully receive and use the delivery notification. However, there were difficulties with the read receipt. I received an email, but when I try to cast to a MultipartReport, I get null.
I tried to cast message to different types, and found some information that is in the body of the letter:
![image](https://github.com/jstedfast/MailKit/assets/26819342/15bffbb2-b259-4b70-bea5-6b9ff8b6b58f)

The letter itself looks like this:
![image](https://github.com/jstedfast/MailKit/assets/26819342/2668b3fe-6ff9-459b-b45c-2ae343252286)

However, I'm not sure that this option is unified, and in what I found - it is possible to understand that this message is a read report only from the Subject, which is not very reliable.

How else can you process such letters in other ways? 
Thanks!

**Comment by Rialzarre** [comment]
You are correct, 
`report3.ContentType.MimeType`  is  `"multipart/mixed"`
![image](https://github.com/jstedfast/MailKit/assets/26819342/20822ed8-5f4f-4a1a-8792-72110ee51a53)

How can it be processed?
