### ISSUE TITLE
How to download attachments when whole mail is attachment

### ISSUE THREAD

**Issue by loopdude** [jstedfast/MailKit#1531]
Hi,

I have everything working fine. I can download EMail attachments from subfolders in c#. I have one problem though.

When a whole Email is sent (forwarded) as an attachment, and the attachment I want to download is in the forwarded Email, I don't know how to grab the attachments. (The users rightclick the EMail and select "send Email as attachment") 

Can Mailkit handle this?

Thanks!

**Comment by jstedfast** [comment]
> Can Mailkit handle this?

Yes.

You'll have to descend into the `IMessageSummary.Body` yourself and locate the [BodyPartMessage](http://www.mimekit.net/docs/html/T_MailKit_BodyPartMessage.htm) and then descend into that part's `Body` property to locate the attachment(s) that you desire.
