### ISSUE TITLE
Second call to GetMessageHeaders fails

### ISSUE THREAD

**Issue by AndreyVDenisov** [jstedfast/MailKit#1533]
Hello!

The version of MailKit is 3.6.0. It happens on one certain email server and it seems that it returns bad headers. When I call GetMessageHeaders or GetMessageHeadersAsync for certain email index for the first time it works well, but all subsequent calls to GetMessageHeaders or GetMessage (and async versions also) fail with 

MailKit.Net.Pop3.Pop3ProtocolException: 'Failed to parse data.'
Inner Exception
FormatException: Failed to parse message headers.

Also GetMessageHeaders for a set of messages fails on the first call.
Calls to GetMessage without previous calling to GetMessageHeaders  works well.

I wonder why the first call works well, but all later fails, even GetMessage?

Here are the logs for two calls, the first is ok, the second with an exception:

Connected to pop://pop.km.ru:110/?starttls=when-available
S: +OK POP3 server ready  b23b3b99-b568-4970-b899-1bca79864581
C: CAPA
S: +OK Capability list follows
S: USER
S: LOGIN-DELAY 60
S: PIPELINING
S: EXPIRE NEVER
S: RESP-CODE
S: UIDL
S: IMPLEMENTATION fast_pop
S: STLS
S: .
C: STLS
S: +OK Begin TLS negotiation
C: CAPA
S: +OK Capability list follows
S: USER
S: LOGIN-DELAY 60
S: PIPELINING
S: EXPIRE NEVER
S: RESP-CODE
S: UIDL
S: IMPLEMENTATION fast_pop
S: .
C: USER ********
S: +OK password required
C: PASS ********
S: +OK
C: CAPA
S: +OK Capability list follows
S: USER
S: LOGIN-DELAY 60
S: PIPELINING
S: EXPIRE NEVER
S: RESP-CODE
S: UIDL
S: IMPLEMENTATION fast_pop
S: .
C: STAT
S: +OK 360 25632208
C: TOP 11 0
S: +OK 1510 octets
S: Received: from mainserver.main-hosting.eu(31-170-164-250.main-hosting.eu
S: 	[31.170.164.250]) by m10.mx.km.ru with ESMTP; Sat, 19 Oct 2013 04:23:56
S: 	+0400 
S: Received: from youhost by mainserver.main-hosting.eu with local (Exim
S: 	4.80.1) (envelope-from <youhost@mainserver.main-hosting.eu>) id
S: 	1VXJHC-0004RL-MH for andreyru@km.ru; Sat, 19 Oct 2013 00:16:14 +0100
S: To: =?UTF-8?Q?=D0=90=D0=BD=D0=B4=D1=80=D0=B5=D0=B9=20=D0=94=D0=B5=D0=BD=D0=B8=D1=81=D0=BE=D0=B2?=
S: 	<andreyru@km.ru>
S: Subject: =?UTF-8?Q??= 
S: 	=?UTF-8?Q?=D0=A3=D0=B2=D0=B5=D0=B4=D0=BE=D0=BC=D0=BB=D0=B5=D0=BD=D0=B8=D0=B5=20?=
S: 	 =?UTF-8?Q?=D0=BE=20?= 
S: 	=?UTF-8?Q?=D0=BF=D1=80=D0=BE=D0=B4=D0=BB=D0=B5=D0=BD=D0=B8=D0=B8=20=D0=B4=D0=BE=D0=BC=D0=B5=D0=BD=D0=B0?=
S: From: =?UTF-8?Q?Hostinger=20=D0=A0=D0=BE=D1=81=D1=81=D0=B8=D1=8F?=
S: 	<ru@hostinger.com>
S: Date: Sat, 19 Oct 2013 00:16:14 +0100
S: Content-Type: multipart/alternative;
S: 	boundary="=_06a4cdd6b6a28bbdb7c0b974ce8a5740"
S: MIME-Version: 1.0
S: Message-Id: <E1VXJHC-0004RL-MH@mainserver.main-hosting.eu>
S: X-AntiAbuse: This header was added to track abuse, please include it with
S: 	any abuse report
S: X-AntiAbuse: Primary Hostname - mainserver.main-hosting.eu
S: X-AntiAbuse: Original Domain - km.ru
S: X-AntiAbuse: Originator/Caller UID/GID - [500 500] / [47 12]
S: X-AntiAbuse: Sender Address Domain - mainserver.main-hosting.eu
S: X-Get-Message-Sender-Via: mainserver.main-hosting.eu: authenticated_id:
S: 	youhost/only user confirmed/virtual account not confirmed
S: 
S: --=_06a4cdd6b6a28bbdb7c0b974ce8a5740
S: 
S: .
C: TOP 11 0
S: +OK
S: +OK 1510 octets
S: Received: from mainserver.main-hosting.eu(31-170-164-250.main-hosting.eu
S: 	[31.170.164.250]) by m10.mx.km.ru with ESMTP; Sat, 19 Oct 2013 04:23:56
S: 	+0400 
S: Received: from youhost by mainserver.main-hosting.eu with local (Exim
S: 	4.80.1) (envelope-from <youhost@mainserver.main-hosting.eu>) id
S: 	1VXJHC-0004RL-MH for andreyru@km.ru; Sat, 19 Oct 2013 00:16:14 +0100
S: To: =?UTF-8?Q?=D0=90=D0=BD=D0=B4=D1=80=D0=B5=D0=B9=20=D0=94=D0=B5=D0=BD=D0=B8=D1=81=D0=BE=D0=B2?=
S: 	<andreyru@km.ru>
S: Subject: =?UTF-8?Q??= 
S: 	=?UTF-8?Q?=D0=A3=D0=B2=D0=B5=D0=B4=D0=BE=D0=BC=D0=BB=D0=B5=D0=BD=D0=B8=D0=B5=20?=
S: 	 =?UTF-8?Q?=D0=BE=20?= 
S: 	=?UTF-8?Q?=D0=BF=D1=80=D0=BE=D0=B4=D0=BB=D0=B5=D0=BD=D0=B8=D0=B8=20=D0=B4=D0=BE=D0=BC=D0=B5=D0=BD=D0=B0?=
S: From: =?UTF-8?Q?Hostinger=20=D0=A0=D0=BE=D1=81=D1=81=D0=B8=D1=8F?=
S: 	<ru@hostinger.com>
S: Date: Sat, 19 Oct 2013 00:16:14 +0100
S: Content-Type: multipart/alternative;
S: 	boundary="=_06a4cdd6b6a28bbdb7c0b974ce8a5740"
S: MIME-Version: 1.0
S: Message-Id: <E1VXJHC-0004RL-MH@mainserver.main-hosting.eu>
S: X-AntiAbuse: This header was added to track abuse, please include it with
S: 	any abuse report
S: X-AntiAbuse: Primary Hostname - mainserver.main-hosting.eu
S: X-AntiAbuse: Original Domain - km.ru
S: X-AntiAbuse: Originator/Caller UID/GID - [500 500] / [47 12]
S: X-AntiAbuse: Sender Address Domain - mainserver.main-hosting.eu
S: X-Get-Message-Sender-Via: mainserver.main-hosting.eu: authenticated_id:
S: 	youhost/only user confirmed/virtual account not confirmed
S: 
S: --=_06a4cdd6b6a28bbdb7c0b974ce8a5740
S: 
S: .

**Comment by jstedfast** [comment]
This is why:

C: TOP 11 0
S: +OK
S: +OK 1510 octets

Your server is replying with an extra +OK response which is breaking the header parser because it's not a header.

You should file a bug against your server.

**Comment by jstedfast** [comment]
As a work-around, what you *could* do is to use the [GetStream()](http://www.mimekit.net/docs/html/M_MailKit_Net_Pop3_Pop3Client_GetStream.htm) method to get the raw header stream instead of GetMessageHeader().

By getting the raw header stream, you bypass the header parser and can try parsing the raw header stream later (or in a try/catch) so that it doesn't break your POP3 connection.

e.g.

```csharp
using (var client = new Pop3Client()) {
    client.Connect("pop.km.ru", 110, SecureSocketOptions.StartTlsWhenAvailable);
    client.Authenticate("username", "password");

    for (int index = 0; index < client.Count; index++) {
        var stream = client.GetStream(index, headersOnly: true);
        try {
            var headers = HeaderList.Load(stream);
        } catch (Exception ex) {
        }
    }

    client.Disconnect(true);
}
```

The above code snippet will still fail on any response that returns 2 (or more) +OK responses, but at least you'd still have the raw header stream that you can save to disk or whatever.

As a more sophisticated work-around, you could do something like this:

```csharp
using (var client = new Pop3Client()) {
    client.Connect("pop.km.ru", 110, SecureSocketOptions.StartTlsWhenAvailable);
    client.Authenticate("username", "password");

    // allocate a temp buffer that is long enough to contain a "+OK" response including a message count and total byte count of the mailbox
    var buffer = new byte[$"+OK {uint.MaxValue} {ulong.MaxValue}\r\n".Length];

    for (int index = 0; index < client.Count; index++) {
        var stream = client.GetStream(index, headersOnly: true);
        int nread = stream.Read(buffer, 0, buffer.Length);
        var text = Encoding.ASCII.GetString(buffer, 0, nread);

        if (text.StartsWith("+OK ", StringComparison.Ordinal)) {
            int position = 0;

            while (position < nread && buffer[position] != (byte) '\n')
                position++;

            // skip over the '\n'
            position++;

            // reset the stream to the position immediately after the buggy "+OK" line ends
            stream.Position = position;
        } else {
            // rewind back to the beginning of the stream before parsing
            stream.Position = 0;
        }

        try {
            var headers = HeaderList.Load(stream);
        } catch (Exception ex) {
        }
    }

    client.Disconnect(true);
}
```

**Comment by AndreyVDenisov** [comment]
Thank you so much for the answer! Still don't understand why the subsequent calls to GetMessage fails...
