### ISSUE TITLE
Unexpected atom token: BYE (server-bug)?

### ISSUE THREAD

**Issue by get-flat** [jstedfast/MailKit#1536]
On ImapClient.Disconnect()

Exception thrown: 'MailKit.Net.Imap.ImapProtocolException' 
Syntax error in tagged response. Unexpected atom token: BYE

(imaps://imap.wp.pl:993/)
C: A00000006 LOGOUT
S: A00000006 BYE IMAP4rev1 Server logging out

Just to confirm a server-bug: BYE should be untagged message?

**Comment by jstedfast** [comment]
Yes, the response should look like this instead:

```
C: A00000006 LOGOUT
S: * BYE
S: A00000006 OK IMAP4rev1 Server logging out
```

**Comment by jstedfast** [comment]
I can look into how difficult it would be to special-case trap this exception as a work-around, but technically you are right, it is a server bug.

**Comment by jstedfast** [comment]
I wrote some unit tests to test this but they already pass without any code changes.

What version are you using? It must be an old version?

**Comment by get-flat** [comment]
MailKit (3.6.0)

**Comment by jstedfast** [comment]
I can't reproduce any exception being thrown. Can you give me a test case?
