### ISSUE TITLE
Cannot use AddFlags on ImapClient.Inbox to delete message

### ISSUE THREAD

**Issue by glebourg76** [jstedfast/MailKit#1537]
Hi.

i just want do read an delete messages with an ImapClient so

MailKit.Net.Imap.ImapClient clientIMAP = new MailKit.Net.Imap.ImapClient();
AuthenticateAsync(clientIMAP).GetAwaiter().GetResult();  //OAT2 on office
clientIMAP.Inbox.Open(MailKit.FolderAccess.ReadWrite);
var uids = clientIMAP.Inbox.Search(SearchQuery.All);  // ok access message no pb
...
...
...

//want to delete
clientIMAP .Inbox.AddFlags   // but AddFlags   not exist on Inbox

what i miss ?

Thanks a lot

**Comment by jstedfast** [comment]
AddFlags is an extension method in 3.x for compatibility and for simpler use.

**Comment by jstedfast** [comment]
Add a using MailKit; statement at the top of your source code

**Comment by glebourg76** [comment]
Ha .. great!!!
thx Jeff
