### ISSUE TITLE
Password issue 

### ISSUE THREAD

**Issue by IanDStone** [jstedfast/MailKit#1539]
Send message Fails: 
535 5.7.8 Error: authentication failed: Authentication failed self68_911524ef40022 
This occurs when there is a full quote (") character in the password which is valid.

OS:  Windows 10 Pro
.NET 6 Core
Visual studio 2022
MailKit Version: 3.6.0

**Code Snippets**
```csharp
smtp.Authenticate(".......@..........co.uk", "(Pq?7jNmA5_\"34.*");
```

NB the username and password are loaded from a database.  Hard coding here just demonstrates the problem.  A password without a full quote (") works fine.

System.Net.Mail works fine in a similar setup.

Error message, Visual Studio in Debug mode:
System.IO.IOException: 'The decryption operation failed, see inner exception.'
Inner Exception:
WIN32Exception: The specified data could not be decrypted.

[smtp.log](https://github.com/jstedfast/MailKit/files/11114053/smtp.log)

**Comment by jstedfast** [comment]
It seems unlikely that this is a bug in MailKit's SaslMechanismPlain implementation seeing as how the PLAIN mechanism is dead simple and requires no interpretation or escaping of quotes in usernames -or- passwords.

You can read the specification here: https://www.rfc-editor.org/rfc/rfc4616

And the implementation is here: https://github.com/jstedfast/MailKit/blob/master/MailKit/Security/SaslMechanismPlain.cs#L178-L205

I don't see what the issue could possibly be.

**Comment by jstedfast** [comment]
I don't think System.Net.Mail supports the PLAIN mechanism, I think it only supports `LOGIN` (your server supports both).

Try this:

```csharp
client.AuthenticationMechanisms.Remove("PLAIN");
smtp.Authenticate(".......@..........co.uk", "(Pq?7jNmA5_\"34.*");
```

**Comment by jstedfast** [comment]
Just confirmed that System.Net.Mail does not support the `PLAIN` mechanism.

**Comment by IanDStone** [comment]
Hi Jeffrey,

 

Afraid it did not work.  Here is my test run:

 

using (var smtp = new MailKit.Net.Smtp.SmtpClient(new ProtocolLogger("smtp.log")))

               // using (var smtp = new MailKit.Net.Smtp.SmtpClient())

                    try

                    {

                        var client = new ImapClient(new ProtocolLogger("imap.log"));

                        smtp.ServerCertificateValidationCallback = (s, c, h, e) => true;

                        smtp.Connect(emailOutgoingMailServerTextBox.Text.Trim(), (int)outgoingServerPortNumericUpDown.Value, SecureSocketOptions.Auto);

                        //smtp.Authenticate(emailUserNameTextBox.Text.Trim(), emailPasswordTextBox.Text.Trim());

                        client.AuthenticationMechanisms.Remove("PLAIN");

                        ***@***.*** ***@***.***> , "(Pq?7jNmA5_\"34.*");

                        // ***@***.*** ***@***.***> , "7Zu^VZSl*M22");

                        smtp.Send(email);

                    }

 

I’ve attached the log.

 

Regards

Ian

 

Ian Stone

Pykefield House

Greete

Ludlow SY8 3BS

t: 01584 777493

m: 07773 419645

 ***@***.***> ***@***.***

**Comment by jstedfast** [comment]
You need to use the website to post attachments. GitHub does not handle replies via email very well.

**Comment by IanDStone** [comment]
Yes I now realise that.  My first time out.  

 

Ian Stone

Pykefield House

Greete

Ludlow SY8 3BS

t: 01584 777493

m: 07773 419645

 ***@***.***> ***@***.***

**Comment by jstedfast** [comment]
@asorcinelli Your issue is most likely an encoding issue. Some POP3 servers expect passwords in UTF-8 and some expect the password to be encoded in their locale encoding (which could be iso-8859-1 or any other encoding).

MailKit provides a way to specify which encoding should be used for the password, you just need to use one of those APIs.

E.g.: http://www.mimekit.net/docs/html/M_MailKit_MailService_Authenticate_4.htm

**Comment by IanDStone** [comment]
Been digging deeper to get to the bottom of this issue.  The account in question, the one with a “ in the password was set up 15-20 years ago and has worked ever since.  
I attempted to change the password on this account to one containing a “ character which was rejected as was passwords containing £, %, ^, &, * characters.  No doubt the same applies to other shorthand characters.    
In conclusion this appears to be a historical issue.  My apologies for introducing a red herring.

**Comment by jstedfast** [comment]
A double-quote character isn't an encoding issue and it doesn't really matter how the character was set in the password.

What matters is whether MailKit is doing something wrong with the password when sending it.

**Comment by asorcinelli** [comment]
@jstedfast you're right, it was an encoding problem. If I specify the econding all works fine. Thanks.
