### ISSUE TITLE
Gmail returns 'BAD response' when trying to remove a label from a message using the RemoveLabels() method

### ISSUE THREAD

**Issue by gldmelo** [jstedfast/MailKit#154]
Hello, I'm getting a "The IMAP server replied to the 'STORE' command with a 'BAD' response." from the following code, while trying to remove a gmail label from a message:

var username = ""; // not provided
var password = ""; // not provided
var credentials = new NetworkCredential(username, password);
var uri = new Uri("imaps://imap.gmail.com");

using (var cancel = new CancellationTokenSource()) 
{
  client.Connect(uri, cancel.Token);
  client.AuthenticationMechanisms.Remove("XOAUTH");
  client.Authenticate(credentials, cancel.Token);
  var inbox = client.Inbox;
  inbox.Open(FolderAccess.ReadWrite, cancel.Token);

  var query = SearchQuery.DeliveredAfter(DateTime.Parse("2015-02-22"))
                        .And(SearchQuery.HasGMailLabel("Não Processado"))
                        .And(SearchQuery.HasGMailLabel("unread"));

   var mailList = inbox.Search(query, cancel.Token);
   foreach (var uid in mailList)
   {
      var labels = new List<string> {"Não Processado"};
      inbox.RemoveLabels(uid, labels, true, cancel.Token);
   }
   client.Disconnect(true, cancel.Token);
}

I took code from examples and added the inbox.RemoveLabels statement.

I do believe that it's a bug since the syntax is correct. Is that the proper command to remove a label from gmail message?

**Comment by jstedfast** [comment]
Try changing your `var client = new ImapClient (...)` line to:

```csharp
var client = new ImapClient (new ProtocolLogger ("imap.log"));
```

Then copy & pasting the log here so that I can see what is happening (I really only need the command that attempts to remove the label and the server response to that command). Thanks.

**Comment by gldmelo** [comment]
Hello jstedfast, thanks for the fast reply!

I figured out the issue, I think it's a bug indeed related to accents.

My folder had the name of Não Processado, after renaming it to Nao Processado (accent removed), it worked as expected.

I tried your suggestion to generate the imap log and I got this:

S: * LIST (\HasNoChildren) "/" "INBOX"
S: A00000004 OK Success
C: A00000005 XLIST "" "*"
S: * XLIST (\HasNoChildren) "/" "Antispam"
S: * XLIST (\HasNoChildren) "/" "Ausente"
S: * XLIST (\HasNoChildren) "/" "Bloq Spam"
S: * XLIST (\HasNoChildren) "/" "Caixa cheia"
S: * XLIST (\HasNoChildren \Inbox) "/" "Caixa de entrada"
S: * XLIST (\HasNoChildren) "/" "Ignorada"
S: * XLIST (\HasNoChildren) "/" "Indefinido"
S: * XLIST (\HasNoChildren) "/" "Invalidos"
S: * XLIST (\HasNoChildren) "/" "N&AOM-o Processado"
S: * XLIST (\HasNoChildren) "/" "Provedor"
S: * XLIST (\HasNoChildren) "/" "Resposta Email Marketing"
S: * XLIST (\Noselect \HasChildren) "/" "[Gmail]"
S: * XLIST (\HasNoChildren \Starred) "/" "[Gmail]/Com estrela"
S: * XLIST (\HasNoChildren \Sent) "/" "[Gmail]/E-mails enviados"
S: * XLIST (\HasNoChildren \Important) "/" "[Gmail]/Importante"
S: * XLIST (\Trash \HasNoChildren) "/" "[Gmail]/Lixeira"
S: * XLIST (\Drafts \HasNoChildren) "/" "[Gmail]/Rascunhos"
S: * XLIST (\HasNoChildren \Spam) "/" "[Gmail]/Spam"
S: * XLIST (\HasNoChildren \AllMail) "/" "[Gmail]/Todos os e-mails"
S: A00000005 OK Success
C: A00000006 SELECT INBOX (CONDSTORE)
S: * FLAGS (\Answered \Flagged \Draft \Deleted \Seen $Phishing $NotPhishing)
S: * OK [PERMANENTFLAGS (\Answered \Flagged \Draft \Deleted \Seen $Phishing $NotPhishing \*)] Flags permitted.
S: * OK [UIDVALIDITY 600951206] UIDs valid.
S: * 32184 EXISTS
S: * 0 RECENT
S: * OK [UIDNEXT 5829504] Predicted next UID.
S: * OK [HIGHESTMODSEQ 147412434]
S: A00000006 OK [READ-WRITE] INBOX selected. (Success)
C: A00000007 UID SEARCH RETURN () CHARSET UTF-8 SINCE 22-FEB-2015 X-GM-LABELS {15+}
C: Não Processado
S: * ESEARCH (TAG "A00000007") UID ALL 5824523:5824531,5824533,5824535:5824553,5824555:5824624,5824626:5825191,5825193:5826721,5826723:5827541,5827543:5828708,5828710:5828873,5828875:5829398,5829400:5829503
S: A00000007 OK SEARCH completed (Success)
C: A00000008 UID STORE 5824523 -X-GM-LABELS ({15+}
C: Não Processado)
S: A00000008 BAD Could not parse command
C: A00000009 UID STORE 5824523 -X-GM-LABELS ({15+}
C: Não Processado)
S: A00000009 BAD Could not parse command
C: A00000010 LOGOUT
S: * BYE LOGOUT Requested
S: A00000010 OK 73 good day (Success)
---------------------------------
Please note this line: 
S: * XLIST (\HasNoChildren) "/" "N&AOM-o Processado"

It's spelled different: the string should be NÃO but it's spelled N&AOM-o. I guess this is related to RFC telling us how to encode special characters?

For now I'll be using the folders without the accents, but I think it's a bug anyway. Others may have come across this issue and/or will be in the future.

MailKit is a great library. I just found it recently. Thanks a lot for taking time to write it. much appreciated!

**Comment by jstedfast** [comment]
Correct, the N&AOM-o spelling is a modified UTF-7 encoding that the IMAP specification uses to encode folder names.

Strangely, GMail accepts the unencoded name when searching for the label:

```
C: A00000007 UID SEARCH RETURN () CHARSET UTF-8 SINCE 22-FEB-2015 X-GM-LABELS {15+}
C: Não Processado
S: * ESEARCH (TAG "A00000007") UID ALL 5824523:5824531,5824533,5824535:5824553,5824555:5824624,5824626:5825191,5825193:5826721,5826723:5827541,5827543:5828708,5828710:5828873,5828875:5829398,5829400:5829503
```

but not when trying to remove the label (and presumably not when adding the label either?):

```
A00000008 UID STORE 5824523 -X-GM-LABELS ({15+}
C: Não Processado)
S: A00000008 BAD Could not parse command
```

Should be fairly easy to fix, just strange that GMail's extension syntax would work this way.

**Comment by jstedfast** [comment]
Should be fixed now.
