### ISSUE TITLE
Timeouts for `SmtpClient`

### ISSUE THREAD

**Issue by CollinAlpert** [jstedfast/MailKit#1540]
I am seeing occasional timeouts when sending emails via the `SmtpClient`. Here's basically my code:
```csharp
var smtpClient = new SmtpClient();
await smtpClient.ConnectAsync("alfa3031.alfahosting-server.de", 465, true, cancellationToken);
await smtpClient.AuthenticateAsync("user", "password", cancellationToken);
var message = …
await smtpClient.SendAsync(message, cancellationToken);
```
Sometimes it works, but most of the time I get the following exception:
```
MailKit.Net.Smtp.SmtpCommandException: 4.4.2 alfa3031.alfahosting-server.de Error: timeout exceeded
   at MailKit.Net.Smtp.SmtpClient.SendAsync(FormatOptions options, MimeMessage message, MailboxAddress sender, IList`1 recipients, CancellationToken cancellationToken, ITransferProgress progress)
```

I know this is likely an issue with the mail server, but wanted to see if I was maybe doing anything wrong with my connection or if you were aware of any issues concerning Alfahosting. Thanks in advance!

**Comment by jstedfast** [comment]
it's most likely an issue with the mail server. MailKit uses the default socket timeout values which is about 2 minutes, I think. That should be a pretty reasonable timeout such that if the server doesn't respond in that amount of time, it probably isn't going to respond.

**Comment by jstedfast** [comment]
FWIW, you can increase the timeout by modifying the Timeout property: http://www.mimekit.net/docs/html/P_MailKit_Net_Smtp_SmtpClient_Timeout.htm

**Comment by CollinAlpert** [comment]
Yeah, I tried increasing the timeout, but that didn't change anything. Thanks anyway!
