### ISSUE TITLE
Unable to Send Mail to Office 365 from Windows Service

### ISSUE THREAD

**Issue by mjanulaitis** [jstedfast/MailKit#1542]
**Describe the solution you'd like**
I have a customer in law enforcement that wants to send emails for automated alerts. Their CJIS implementation requires they send email through Office 365 using either OAuth2 or optionally a Client Secret.  Since OAuth2 is a user interface implementation, OAuth2 is not a viable solution.  I would like to be able to send email through MailKit rather than the Microsoft Graph API.  Currently there is no way to use a client secret with an ConfidentialClientApplicationBuilder, authenticate then send an email.

**Describe alternatives you've considered**
The alternative is to bail on Mailkit and use Graph.

**Comment by jstedfast** [comment]
There's a discussion on how to do what you want here: https://github.com/jstedfast/MailKit/issues/1126
