### ISSUE TITLE
Invalid anchor links

### ISSUE THREAD

**Issue by artur-intech** [jstedfast/MailKit#1549]
None of the links under "Question Index" on the "FAQ" document seem to work Their IDs do not match IDs used on the corresponding elements.

https://github.com/jstedfast/MailKit/blob/master/FAQ.md

**Comment by jstedfast** [comment]
Seems that with GitHub's new UI, the old anchor markdown syntax no longer works.

**Comment by artur-intech** [comment]
[Those IDs](https://github.com/jstedfast/MailKit/commit/81e9a411f50ef8a45f4af5cfff24e45798ccec02) should be in lowercase in order to work. It is also considered a good practice in the front-end world.

[An example](https://github.com/jstedfast/MailKit/pull/1550).
