### ISSUE TITLE
UniqueId of a message after moving

### ISSUE THREAD

**Issue by sboldt** [jstedfast/MailKit#155]
Hello.

I am trying to move all messages from inbox into a subfolder of inbox. My need is to get the new UniqueId in this folder for later use.

But the return value of the MoveTo-Function is always null.

Code i am using
```
using (var client = new ImapClient())
{ 
   // connect
   //authenticate

   client.Inbox.Open(FolderAccess.ReadWrite, ct);

   var mappingFolders = client.Inbox.GetSubfolders(false, ct);

   var mappingFolder = mappingFolders.FirstOrDefault(f => f.Name == "in_mapping") ?? client.Inbox.Create("in_mapping", true, ct);
   
   foreach (var mail in client.Inbox.Fetch(0, -1, MessageSummaryItems.Full | MessageSummaryItems.UniqueId))
   { 
      // move the mail to the folder
      var newMessageId = client.Inbox.MoveTo(mail.UniqueId.Value, mappingFolder);
   
      // code that uses the returned UniqueId here
   }

   client.Disconnect(true);
}
```

After running the code with a protocoll logger:

C: A00000008 UID COPY 159 INBOX/in_mapping
S: A00000008 OK [COPYUID 1424785378 159 57] UID command completed
C: A00000009 UID STORE 159 +FLAGS.SILENT (\Deleted)
S: A00000009 OK UID command completed
C: A00000010 UID EXPUNGE 159
S: * 1 EXPUNGE
S: A00000010 OK UID command completed

I far as i can see the server return the new UniquieId (57) of the moved mail here:

S: A00000008 OK [COPYUID 1424785378 159 57] UID command completed

I have tested this by fetching the mail from the new folder after move and it is the new UniqueId.
Howewer it is never returned by the MoveTo-Function.

I am doing something wrong?

Thanks.

**Comment by jstedfast** [comment]
The way the code works right now (and maybe it shouldn't work this way), is that it uses the following logic inside of CopyTo():

```csharp
if (destination.UidValidity.HasValue) {
    var copy = ic.RespCodes.OfType<CopyUidResponseCode> ().FirstOrDefault ();

    if (copy != null && copy.UidValidity == destination.UidValidity.Value)
        return copy.DestUidSet;
}
```

This means that it will only work as you are expecting if the destination folder has been previously opened during the current session (that's the only way it will have a UidValidity value assigned to it).

**Comment by jstedfast** [comment]
The *reason* it works that way is because it's possible for the UIDVALIDITY value for the destination folder to change some time after issuing the UID COPY command and whenever you next decide to open the folder.

**Comment by sboldt** [comment]
Ok. I modified my code.

```
client.Inbox.Open(FolderAccess.ReadWrite, ct);
var mappingFolders = client.Inbox.GetSubfolders(false, ct);
var mappingFolder = mappingFolders.FirstOrDefault(f => f.Name == "in_mapping") ?? client.Inbox.Create("in_mapping", true, ct);

// open the mapping folder
 mappingFolder.Open(FolderAccess.ReadWrite, ct);
//open inbox again because its get closed by opening the mapping folder
client.Inbox.Open(FolderAccess.ReadWrite, ct);
foreach (var mail in client.Inbox.Fetch(0, -1, MessageSummaryItems.Full | MessageSummaryItems.UniqueId))
{
   // move the mail to the folder
   var newMessageId = client.Inbox.MoveTo(mail.UniqueId.Value, mappingFolder);
}
```
Now the MoveTo-Function returns the UniqueId in new folder.

Thanks for help !!

**Comment by jstedfast** [comment]
You're welcome.

**Comment by jstedfast** [comment]
I've modified the code to ALWAYS return the UniqueId values now. By modifying UniqueId to have a Validity property, it is no longer necessary for IMailFolder.Append(), CopyTo() and MoveTo() to make sure that the UidValidities match and can now safely leave it up to the caller to do this validity checking.
