### ISSUE TITLE
Add an Example for MailStore.MetadataChanged Event

### ISSUE THREAD

**Issue by vivekshankarbs** [jstedfast/MailKit#1556]
Please add an example for MailStore.MetadataChanged Event.

TODO (optional): Describe a specific scenario you would like to see addressed.

Help Topic: http://www.mimekit.net/docs/html/E_MailKit_MailStore_MetadataChanged.htm

**Comment by jstedfast** [comment]
Is there something specific you'd like to know? I can't think of a good example for this because it's not something a typical app would use.
