### ISSUE TITLE
Unexpected token in IMAP greeting: '+'

### ISSUE THREAD

**Issue by ciapa1998** [jstedfast/MailKit#156]
Hi,
I'm using Mailkit 1.0.9 from NuGet with an Cyrus Server. The problem is that I get the following ImapProtocolException when I try to connect:
```
Unexpected token in IMAP greeting: '+'
```
Logging the whole connection process with the ProtocolLogger gives me this Output:
```
Connected to imaps://yxz.yxz.yxz:995/
S: +OK yxz.yxz.yxz Cyrus POP3 v2.4.16-Debian-2.4.16-4+deb7u2 server ready <11461268568888226136.1425393580@yxz.yxz.yxz>
```
(original Domain replaced by yxz.yxz.yxz)
However, when I try to connect to another Server, powered by hMailserver, everything works flawlessly. 
It would be really great if you can help me with getting rid of this bug.
Thanks in advance and greetings from Germany

**Comment by jstedfast** [comment]
Take a closer look at the greeting... :-)

`S: +OK yxz.yxz.yxz Cyrus POP3 ...`

What kind of server are you connecting to? Are you connecting to an IMAP server? Or are you really connecting to a POP3 server? :-)

Try port 993 instead. 995 is for POP3, not IMAP.

**Comment by ruffin--** [comment]
Probably worth mentioning that the IMAP sample code in the readme contains...

    using (var client = new ImapClient ()) {
                client.Connect ("imap.friends.com", 995, true);

So that might have contributed to ciapa1998's confusion. Want me to open a new issue? Probably not worth a pull.

**Comment by Ciapa** [comment]
Well, it was also caused by the Frontend of my Scholl(they use IServ AS web Portal) which showed Port 995.
But anyway, thanks for the help

**Comment by jstedfast** [comment]
Thanks @ruffin--, I've just fixed the sample code to use 993 (must have been a copy-pasta from some sample POP3 code).

**Comment by ruffin--** [comment]
Awesome. Thanks for keeping the updates fast and furious. It's appreciated!

**Comment by jstedfast** [comment]
I try :-)
