### ISSUE TITLE
Using VB.NET to authenticate IMAP with XOAUTH2

### ISSUE THREAD

**Issue by FrankCastle666** [jstedfast/MailKit#1561]
Will it be possible to include an additional sample to your link:

[https://github.com/jstedfast/MailKit/blob/master/ExchangeOAuth2.md](https://github.com/jstedfast/MailKit/blob/master/ExchangeOAuth2.md)

this time in  VB.NET?

I tested this feature in C# and it works well, however I’m battling to implement it in VB.NET
Any help on this matter will be greatly appreciated.

Many thanks

**Comment by jstedfast** [comment]
I don't know VB.NET at all, so unfortunately if you can't translate from c# to VB, I won't be able to help you.

**Comment by FrankCastle666** [comment]
Many thanks anyway, Jeffrey
