### ISSUE TITLE
Add an Example for IProtocolLogger.AuthenticationSecretDetector Property

### ISSUE THREAD

**Issue by jindrichmatous** [jstedfast/MailKit#1567]
Please add an example for IProtocolLogger.AuthenticationSecretDetector Property.

TODO (optional): Describe a specific scenario you would like to see addressed.

Help Topic: http://mimekit.net/docs/html/P_MailKit_IProtocolLogger_AuthenticationSecretDetector.htm

**Comment by jstedfast** [comment]
Unless you are implementing a custom client for a protocol that isn't already supported by MailKit, you won't have any need to ever set or implement this.
