### ISSUE TITLE
SmtpStream.QueueCommand goes to endless loop in TryQueueCommand

### ISSUE THREAD

**Issue by alexander-kucherov** [jstedfast/MailKit#1568]
**Describe the bug**
SmtpStream.QueueCommand goes to endless loop in TryQueueCommand if command length is greater than output buffer size (4096).
It was broken by [commit](https://github.com/jstedfast/MailKit/commit/6990619200aa7999977893275f9e6af767c86867)
In my case **needed** bytes always greater than 4096 and it always return false. Callsite has while loop
```csharp
			while (!TryQueueCommand (encoder, command, ref index))
				Flush (cancellationToken);
```
In this case it's endless.

**Platform (please complete the following information):**
 - OS: Windows
 - .NET Runtime: net7.0
 - MailKit Version: All versions >3.4.3

**Exception**
No exception. Endless loop

**To Reproduce**
I've prepared a unit test to reproduce bug
```csharp
		[Test]
		public void EndlessLoopOnQueueCommand ()
		{
			using var stream = new SmtpStream (new DummyNetworkStream (), new NullProtocolLogger ());
			var memory = (MemoryStream) stream.Stream;
			var command = "AUTH GSSAPI YIIkMgYGK"+ new string ('X', 4096);
			stream.QueueCommand (command, default);
		}
```

**Additional context**
I've implemented a custom SaslMechanism for GSSAPI Kerberos. So my outgoing blob is greater than 4096 and i have problems which  described above.

**Comment by jstedfast** [comment]
Thanks, I'll try to look into this soon

**Comment by alexander-kucherov** [comment]
Thanks a lot for your quick fix.
I'm looking forward for a new release.
