### ISSUE TITLE
Add an Example for MimeMessage(IEnumerable<InternetAddress>, IEnumerable<InternetAddress>, String, MimeEntity) Constructor

### ISSUE THREAD

**Issue by PaKrop079** [jstedfast/MailKit#1569]

**Comment by jstedfast** [comment]
Which part are you struggling with? The `MimeEntity body` argument?

Take a look at the README.md file for examples of how to create a message body, keeping in mind that `MimeEntity` is an abstract base class for other classes like `Multipart`, `MimePart`, `TextPart`, and `MessagePart`.
