### ISSUE TITLE
Add an Example for FormatOptions Class

### ISSUE THREAD

**Issue by AnkitaDBathia** [jstedfast/MailKit#1570]
Please add an example for FormatOptions Class.

TODO (optional): Describe a specific scenario you would like to see addressed.

Help Topic: http://www.mimekit.net/docs/html/T_MimeKit_FormatOptions.htm

**Comment by jstedfast** [comment]
Is there a specific scenario you need help with? FormatOptions is just a collection of formatting options that can be used when writing a message to disk. I would imagine that most of these are self-explanatory.

**Comment by AnkitaDBathia** [comment]
I want to store exception info stored as json file in attachment to sql server. how can i use this ?

**Comment by jstedfast** [comment]
I don't really understand what you are asking, but FormatOptions is definitely not the right place to look.
