### ISSUE TITLE
MailKit Return-Path is not respected by mail clients

### ISSUE THREAD

**Issue by setoy** [jstedfast/MailKit#1572]
**Describe the bug**
When specifying a custom `Return-Path` in the header list, it is not respected by mail clients.

**Platform (please complete the following information):**
 - OS: Windows
 - Mail server: hMailServer
 - .NET Runtime: .NET 6
 - MailKit Version: 4.0.0

**Exception**
None.

**To Reproduce**
1. Send an e-mail with a custom `Return-Path` header
2. Open e-mail in Outlook
3. "Internet headers" does not display the provided `Return-Path` in the first line (it is, however, displayed in the middle of the internet headers), but rather the `From` address as the `Return-Path`

**Expected behavior**
The `Return-Path` header should be respected.

**Code Snippets**
```csharp
var sender = new EmailSender();
await sender.SendAsync("senderuser@senderdomain.com",
                       "Sender User",
                       "<p>test</p>",
                       true,
                       "recipientuser@recipientdomain.com",
                       "Recipient User",
                       "bounces@senderdomain.com");
```
```csharp
public class EmailSender
{
    private string _host = "mail.senderdomain.com";
    private int _port = 25;
    private string _username = "senderuser@senderdomain.com";
    private string _password = "pass";
    private bool _enableSsl = false;

    public async Task SendAsync(string fromAddress,
                                string fromName,
                                string body,
                                bool isBodyHtml, 
                                string toAddress,
                                string toName,
                                string bounceEmailAddress = null)
    {
        var message = new MimeMessage();

        // From
        var fromMailboxAddress = new MailboxAddress(fromName, fromAddress);
        message.From.Add(fromMailboxAddress);

        // Return path
        string returnPathEmail = bounceEmailAddress;
        if (!string.IsNullOrEmpty(returnPathEmail))
        {
            SetReturnPath(message, returnPathEmail);
        }

        // To
        var to = SetTo(message, toAddress, toName);

        // Subject
        message.Subject = "Subject";

        // Body
        var bodyBuilder = new BodyBuilder();
        if (isBodyHtml)
        {
            bodyBuilder.HtmlBody = body;
        }
        else
        {
            bodyBuilder.TextBody = body;
        }

        message.Body = bodyBuilder.ToMessageBody();

        // Send email
        using (var smtpClient = await BuildClientAsync(_host, _port, _enableSsl, _username, _password))
        {
            await smtpClient.SendAsync(message, fromMailboxAddress, to);

            await smtpClient.DisconnectAsync(true);
        }
    }

    private async Task<SmtpClient> BuildClientAsync(string host, int port, bool enableSsl, string username, string password)
    {
        var client = new SmtpClient(new ProtocolLogger("smtp.log"))
        {
            ServerCertificateValidationCallback = ValidateServerCertificate
        };

        try
        {
            await client.ConnectAsync(host,
                                      port,
                                      enableSsl ? SecureSocketOptions.SslOnConnect : SecureSocketOptions.StartTlsWhenAvailable);

            await client.AuthenticateAsync(new NetworkCredential(username, password));

            return client;
        }
        catch (Exception ex)
        {
            client.Dispose();
            throw new Exception(ex.Message, ex);
        }
    }

    private bool ValidateServerCertificate(object sender, X509Certificate certificate, X509Chain chain, SslPolicyErrors sslPolicyErrors)
    {
        // By default, server certificate verification is disabled.
        return true;
    }

    private MailboxAddress[] SetTo(MimeMessage message, string toEmailAddress, string toName)
    {
        var toMailboxAddress = new MailboxAddress(toName, toEmailAddress);
        message.To.Add(toMailboxAddress);

        return new[] { toMailboxAddress };
    }

    private static void SetReturnPath(MimeMessage message, string address)
    {
        if (!message.Headers.Contains(HeaderId.ReturnPath))
        {
            message.Headers.Insert(0, HeaderId.ReturnPath, address);
        }
        else
        {
            message.Headers.Replace(HeaderId.ReturnPath, address);
        }
		
        message.Sender = new MailboxAddress("", address);
    }
}
```

**Protocol Logs**

**Additional context**
I can see that MailKit successfully passes the e-mail header to the mail server via the log:
```
S: 235 authenticated.
C: MAIL FROM:<senderuser@senderdomain.com> SIZE=322
S: 250 OK
C: RCPT TO:<recipientuser@recipientdomain.com>
S: 250 OK
C: DATA
S: 354 OK, send.
C: Return-Path: testbounce@senderdomain.com
C: From: Sender User <senderuser@senderdomain.com>
C: Date: Sat, 20 May 2023 14:26:27 +0200
C: Subject: Subject
C: Message-Id: <XD5XSEYNZJU4.WD1YA1HS3G4K1@hostname>
C: To: recipientuser test <recipientuser@recipientdomain.com>
C: MIME-Version: 1.0
C: Content-Type: text/html; charset=utf-8
C: 
C: <p>test</p>
C: .
S: 250 Queued (0.032 seconds)
C: QUIT
S: 221 goodbye
```

However, Outlook does not display it. When using the default .NET mail library, the `Return-Path` is successfully shown when also specifying the `MailMessage.Sender` property - although the e-mail client then displays `sent on behalf of`. I've tried using the solution in #917 (by using a different `SendAsync` overload), however it still displays the `on behalf of`.

Since it (kinda) works when using the default .NET library (the header is successfully passed through, although it displays `on behalf of` which I cannot seem to get rid of), I might be inclined to say that the Mail Server is **not** the culprit. Also, because doing the exact same thing using PHP and the Laminas library also works.

**Comment by jstedfast** [comment]
As you can see from your log, the Return-Path header is the very first header of the message when sent via MailKit.

Most likely, the problem is your mail server is inserting Received headers *above* the Return-Path header by the time it is received by the recipient's mail server/client.

This is not a MimeKit/MailKit issue.

**Comment by jstedfast** [comment]
BTW, generally speaking, the client isn't supposed to set the Return-Path header. The server is supposed to do that.

**Comment by setoy** [comment]
> Most likely, the problem is your mail server is inserting Received headers above the Return-Path header by the time it is received by the recipient's mail server/client.

Why does it work with other libraries when using the same mail server, then? This is what I tried to make clear with the last two paragraphs.

> BTW, generally speaking, the client isn't supposed to set the Return-Path header. The server is supposed to do that.

It's an ASP.NET application, so technically it's the server. Or are you talking about the **mail**server?

**Comment by jstedfast** [comment]
> Why does it work with other libraries when using the same mail server, then? This is what I tried to make clear with the last two paragraphs.

Probably because they don't set a Return-Path and allow the mail server to do it.

> It's an ASP.NET application, so technically it's the server. Or are you talking about the mailserver?

I'm talking about the mail server.

**Comment by setoy** [comment]
> Probably because they don't set a Return-Path and allow the mail server to do it.

[They're not](https://docs.laminas.dev/laminas-mail/intro/). Also: How else would you go about implementing VERP for automated bounce handling (like in the the mentioned #917) in an ASP.NET web application?

**Comment by jstedfast** [comment]
In both of the links you provided, the Return-Path header only does what you expect when you use the Sendmail transport backends, not SMTP.

> Also: How else would you go about implementing VERP for automated bounce handling (like in the the mentioned https://github.com/jstedfast/MailKit/issues/917) in an ASP.NET web application?

The same way you'd have to do it for any other type of client? Not sure why ASP.NET would be any different.

**Comment by kubilay-dev** [comment]
> > Probably because they don't set a Return-Path and allow the mail server to do it.
> 
> [They're](https://swiftmailer.symfony.com/docs/messages.html#setting-the-return-path-bounce-address) [not](https://docs.laminas.dev/laminas-mail/intro/). Also: How else would you go about implementing VERP for automated bounce handling (like in the the mentioned #917) in an ASP.NET web application?

Could you maybe send me your discord name?
