### ISSUE TITLE
.AddFlags does not exisit in powershell

### ISSUE THREAD

**Issue by HomeOfSourceCode** [jstedfast/MailKit#1577]
I'm using powershell and the latest version von Mailkit 4.0.0

I use this code:
`
 // client.Connect("pop.qq.com", 995, true);
client.Connect("imap.qq.com", 993, true);
// Note: since we don't have an OAuth2 token, disable
// the XOAUTH2 authentication mechanism.  
client.AuthenticationMechanisms.Remove("XOAUTH2");

client.Authenticate("113729396@qq.com", "nathan2013");
List<UniqueId> Uids = new List<UniqueId> { };
request.Uids.ForEach(e=> {
Uids.Add(new UniqueId(e));
});

var inbox = client.Inbox;
inbox.Open(FolderAccess.ReadWrite);
inbox.AddFlags(Uids,MessageFlags.Deleted, false);
`
I can read all mail from the mailbox, but I cnnot delet any email.

Powershell tells me, that inbox.AddFlags method does not exist.

**Comment by jstedfast** [comment]
AddFlags is an extension method. You might need to use `inbox.Store(new StoreFlagsRequest (StoreAction.Add, MessageFlags.Deleted));`
