### ISSUE TITLE
MailKit, Linux and Interop+Crypto+OpenSslCryptographicException: tls_process_ske_dhe:dh key too small	

### ISSUE THREAD

**Issue by SerhiyBalan** [jstedfast/MailKit#1578]
Hello

**Describe the bug**
I have to communicate with a custom remote email server
The email server uses an SSL certificate (SHA256, 2048 bits) and 1024 bits DH key  
When I used the Windows environment, everything was fine. Windows doesn't care about too weak DH key.
I switched to Linux, and now I receive a 'Interop+Crypto+OpenSslCryptographicException: error:141A318A:SSL routines:tls_process_ske_dhe:dh key too small' exception

It is clear that the remote email server has issues with their configuration, it is not secure enough (they should use DH key 2048 bits instead of 1024). _But it still valid._ Unfortunately they are not able to do that because they have no access to it (or they simply do not want to bother with it). So I have to deal with it on my side.

So here is a question - is it possible to ignore this issue at my side in MailKit at Linux?

I have tried to follow https://github.com/jstedfast/MailKit/blob/master/FAQ.md
but unfortunately nothing helped.

**Platform (please complete the following information):**
 - OS: Linux (Azure Functions). On Windows everything is fine
 - .NET Runtime: CoreCLR
 - .NET Framework: .NET 6
 - MailKit Version: 4.0.0

**Exception**
Exception Message:
```
An error occurred while attempting to establish an SSL or TLS connection.This usually means that the SSL certificate presented by the server is not trusted by the system for one or more ofthe following reasons:1. The server is using a self-signed certificate which cannot be verified.2. The local system is missing a Root or Intermediate certificate needed to verify the server's certificate.3. A Certificate Authority CRL server for one or more of the certificates in the chain is temporarily unavailable.4. The certificate presented by the server is expired or invalid.5. The set of SSL/TLS protocols supported by the client and server do not match.6. You are trying to connect to a port which does not support SSL/TLS.See https://github.com/jstedfast/MailKit/blob/master/FAQ.md#SslHandshakeException for possible solutions.
```

Stack trace:	
```  
 at MailKit.Net.Imap.ImapClient.ConnectAsync(String host, Int32 port, SecureSocketOptions options, Boolean doAsync, CancellationToken cancellationToken)
   at MyApp.Functions.Testing2.Triggers.TestTrigger(HttpRequestData httpRequest, DurableTaskClient client, FunctionContext context) in D:\a\1\s\Source\MyApp.Functions.Testing2\Triggers.cs:line 47
```

Inner exception:
```
System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception. ---> Interop+OpenSsl+SslException: SSL Handshake failed with OpenSSL error - SSL_ERROR_SSL. ---> Interop+Crypto+OpenSslCryptographicException: error:141A318A:SSL routines:tls_process_ske_dhe:dh key too small   --- End of inner exception stack trace ---   at Interop.OpenSsl.DoSslHandshake(SafeSslHandle context, ReadOnlySpan`1 input, Byte[]& sendBuf, Int32& sendCount)   at System.Net.Security.SslStreamPal.HandshakeInternal(SafeFreeCredentials credential, SafeDeleteSslContext& context, ReadOnlySpan`1 inputBuffer, Byte[]& outputBuffer, SslAuthenticationOptions sslAuthenticationOptions)   --- End of inner exception stack trace ---   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)   at MailKit.Net.Imap.ImapClient.ConnectAsync(String host, Int32 port, SecureSocketOptions options, Boolean doAsync, CancellationToken cancellationToken)
```

Inner exception stack trace:
```
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)   at MailKit.Net.Imap.ImapClient.ConnectAsync(String host, Int32 port, SecureSocketOptions options, Boolean doAsync, CancellationToken cancellationToken)
```
  

**To Reproduce**
Sorry, I can't share the address of that server here in public

**Expected behavior**
I would like to force MailKit somehow to ignore that exception and still connect to the remote server even if they have non-critical issues.

**Code Snippets**
If applicable, add code snippets to help explain your problem.

```csharp
using var imap = new ImapClient();

// I've tried to set according to FAQ, but no success
imap.ServerCertificateValidationCallback = (_, _, _, _) => true;
imap.CheckCertificateRevocation = false;
imap.SslProtocols = SslProtocols.Tls | SslProtocols.Tls11 | SslProtocols.Tls12 | SslProtocols.Tls13;

await imap.ConnectAsync("serverUrl", 993, true); // or SecureSocketOptions.Auto - the same
await imap.AuthenticateAsync("login", "password");

var inbox = imap.Inbox;
await inbox.OpenAsync(FolderAccess.ReadOnly);

await inbox.CloseAsync();
await imap.DisconnectAsync(true);
```

**Protocol Logs**
No logs for now
I will send them to your email on request

**Additional context**
-

**Comment by jstedfast** [comment]
Sorry to hear about your situation. Unfortunately, this exception is not something that MailKit has any control over.

The exception is a native OpenSSL error that .NET's SslStream gets when trying to connect.

You'll need to submit this issue to the dotnet team to fix.
