### ISSUE TITLE
Add an Example for MimeUtils.GenerateMessageId(String) Method

### ISSUE THREAD

**Issue by sanwadhw** [jstedfast/MailKit#1579]
Please add an example for MimeUtils.GenerateMessageId(String) Method.

TODO (optional): Describe a specific scenario you would like to see addressed.

Help Topic: http://www.mimekit.net/docs/html/M_MimeKit_Utils_MimeUtils_GenerateMessageId_1.htm

**Comment by jstedfast** [comment]
Is there a specific scenario you need help with?
