### ISSUE TITLE
Is it possible to know if a message has attachment before downloading them?

### ISSUE THREAD

**Issue by xavier-rigau** [jstedfast/MailKit#158]
We have a limit in terms of attachment size and number our program can process. I would rather skip messages that are too big. Last time I tried I couldn't figure out a way to know how many attachment a message has by looking at the Message Summary.

**Comment by jstedfast** [comment]
Yes, this is possible.

What you need to do is make sure to include the `MessageSummaryItems.BodyStructure` flag in the bitmask of items you want from `folder.Fetch (...)`. The `MessageSummary` items returned will have their `Body` properties set. The `Body` property is similar to a `MimeMessage.Body` in that it is a hierarchical tree structure of MIME parts. The base `BodyPart` class has very few usable properties on it (it's similar to the base `MimeEntity` class in MimeKit) and so you must check if the BodyPart is a `BodyPartBasic` (`BodyPartText` is a subclass of `BodyPartBasic` which has additional properties such as the number of lines of text), `BodyPartMultipart`, or `BodyPartMessage`. A `BodyPartMultipart` will contain a collection of child `BodyPart` objects, etc.

**Comment by jstedfast** [comment]
I've just added a number of convenience properties to `MessageSummary`:

1. `BodyParts` returns `IEnumerable<BodyPartBasic>`, essentially flattening the MIME hierarchy for easier iteration.
2. `Attachments` filters the list of `BodyParts` to only include parts that are attachments.
3. `TextBody` returns the `BodyPartText` object that represents the `text/plain` message body, if it exists, using the same heuristics as `MimeMessage.TextBody`.
4. `HtmlBody` returns the `BodyPartText` object that represents the `text/html` message body, if it exists, using the same heuristics as `MimeMessage.HtmlBody`.

**Comment by jstedfast** [comment]
I should also note that each `BodyPartBasic` has an `Octets` property which is the size (in bytes) of the MIME part.
