### ISSUE TITLE
50% of Emails have Broken Attachments/Attachments that can't be opened

### ISSUE THREAD

**Issue by sanfordn** [jstedfast/MailKit#1586]
**Describe the bug**
We are downloading some files from Azure Blob storage into a `MemoryStream` and using the `BodyBuilder` to add these files as attachments to emails. The files are getting attached to emails, but about 50% of the time, the emails have attachments that are broken/can't be opened. 

I have tested sending 10 emails within a short time-frame, and 5 of them will have working attachments, while the other 5 have broken attachments. Below is an example of broken attachments (1st image), and working attachments (2nd image). These emails were sent within 5 seconds of each other. The broken ones have a smaller attachment size.

![broken](https://github.com/jstedfast/MailKit/assets/43021738/87b128ed-2235-47c3-a2a7-ad76996dae2a)

![working](https://github.com/jstedfast/MailKit/assets/43021738/ea8c051b-20f0-4de4-ab89-d90c95b97120)

This is very strange functionality to us, and we have tried a lot of things with our implementation before submitting this issue including refactoring our system to control the [service lifetime](https://learn.microsoft.com/en-us/dotnet/core/extensions/dependency-injection#service-lifetimes) of the class that this code lives in because we were concerned one of the dependencies might not have been disposed of properly prior to the next run of this class.

Any suggestions you may have related to handling attachments would be greatly appreciated as we are unsure of how to get around this issue. Could we use a FileStream? MemoryStream? ByteArray's? What are all of our options?

**Platform (please complete the following information):**
 - OS: Windows
 - .NET Runtime: .NET
 - .NET Framework: net6.0
 - MailKit Version: 4.0.0

**To Reproduce**
1. Put the code snippet below somewhere into a system that can run asyncronously.
2. Add attachments to a `BodyBuilder` using `BodyBuilder.Attachments.Add()` (multiple attachments can be used per email)
4. Connect to the SMTP Server using TLS Connection
5. Send multiple emails, using this code, to your own email in rapid succession (I used postman and clicked "Send" 10 times in a row)
6. Review your emails in your inbox. 5 of the emails should have broken attachments, 5 emails should have working attachments.

**Expected behavior**
I would expect that all attachments that are sent through our SMTP server have all of the content that they were originally sent with, and they can be opened using a supported application (.xlsx opens with Excel; .pdf opens with chrome, adobe, etc).

**Code Snippets**
Here's our code we are using. This part of our system runs asynchronously as well if that provides any information. I have seen some other past issues related to attachments, and I've tried setting the memory stream position to 0, converting the memory stream to byte array, and this is just the current state of the code after this. I understand I don't need to set the memory position if I am converting it to a byte array.

```csharp
var emailBody = new BodyBuilder();
if (isHTML)
{
    emailBody.HtmlBody = message.Body;
}
else
{
    emailBody.TextBody = message.Body;
}

BlobContainerClient containerClient = _blobServiceClient.GetBlobContainerClient(containerName);

foreach (string item in directoryName)
{
    await foreach (BlobItem blob in containerClient.GetBlobsAsync(prefix: item, cancellationToken: cancellationToken))
    {
        BlobClient blobClient = containerClient.GetBlobClient(blob.Name);
        using var memStream = new MemoryStream(10485760);
        await blobClient.DownloadToAsync(memStream, cancellationToken: cancellationToken);
        memStream.Position = 0;
        emailBody.Attachments.Add(blobClient.Name.Split("/")[1], memStream.ToArray());
    }
}

email.Body = emailBody.ToMessageBody();

// send email
using var smtp = new SmtpClient(new ProtocolLogger("smtp.log"));
smtp.Connect(smtpServer, smtpPort, SecureSocketOptions.StartTls, cancellationToken: cancellationToken);
smtp.Authenticate(emailID, emailSecret, cancellationToken: cancellationToken);
await smtp.SendAsync(email, cancellationToken: cancellationToken);
smtp.Disconnect(true, cancellationToken: cancellationToken);
```

**Protocol Logs**
Due to security purposes, I am unable to share any protocol logs as they contain some information that is not to be shared external to our company.

**Additional context**
We are using an smtp server internal to our company, and other methods of sending emails (non-MailKit/MimeKit implementations) with attachments have never had an issue like this (50% of emails with attachments have broken attachments)

**Comment by jstedfast** [comment]
When you examine the smtp.log file for each of the broken vs non-broken transactions, does the DATA command payload look different?

I have never heard of any such problem and my unit tests have never detected any such issue either.

Just out of curiosity - why are you using the synchronous APIs for Connect/Authenticate/Disconnect but the Async version of Send? That seems very odd to me (not that it should cause a problem, but it's just a weird thing to do).

**Comment by jstedfast** [comment]
Honestly, my guess is that you are failing to download the full content of the attachment files from blob storage.

I would suggest adding some logging to that to see how large those files are after downloading them to see if they are coming up short ~50% of the time.

**Comment by sanfordn** [comment]
> When you examine the smtp.log file for each of the broken vs non-broken transactions, does the DATA command payload look different?
> 
> I have never heard of any such problem and my unit tests have never detected any such issue either.
> 
> Just out of curiosity - why are you using the synchronous APIs for Connect/Authenticate/Disconnect but the Async version of Send? That seems very odd to me (not that it should cause a problem, but it's just a weird thing to do).

I am looking into this right now, and a lot of this actually looks like we may not be getting a new instance of this class each time a request comes through. For the ones that don't work, we aren't getting an smtp.log file at all. I just added a guid to the file name and I'm only getting a new log file for half of the requests I send. I'm thinking I need to look deeper into our system rather than mailkit/mimekit. 

In regards to your question around the synchronous methods, I think we just didn't know there were options. I will likely change those up to use all async or all synchronous, depending on what makes most sense for us.

Thanks for your prompt response. I'll plan to respond here if I find anything.
