### ISSUE TITLE
Add an Example for MimeMessage.To Property

### ISSUE THREAD

**Issue by rish0512** [jstedfast/MailKit#1588]
Please add an example for MimeMessage.To Property.

TODO (optional): Describe a specific scenario you would like to see addressed.

Help Topic: https://www.mimekit.net/docs/html/P_MimeKit_MimeMessage_To.htm

**Comment by jstedfast** [comment]
What is it, exactly, that you need to see an example of? Is there something specific about the To property that you don't understand how to use?
