### ISSUE TITLE
S/MIME Signature Incorrect using ECDSA Certificate

### ISSUE THREAD

**Issue by tmccal2** [jstedfast/MailKit#1591]
**Describe the bug**
I have attempted to send a signed email message, but various clients have said that the signature is incorrect or the message has been tampered with.

**Platform (please complete the following information):**
 - OS: MacOS
 - .NET Runtime: .NET 7
 - .NET Framework: .NET Core 7
 - MailKit Version: 4.0.0

**Exception**
No exceptions thrown

**To Reproduce**
1. Run the code snippet below
2. Receive the email in another address
3. See that the signature is somehow incorrect.

**Expected behavior**
I expected the email, once received, to have a correct signature and validate successfully.

**Code Snippets**

```csharp
var newmsg = new MimeMessage();
        newmsg.To.Add(new MailboxAddress("Taylor", "<Destination>"));
        newmsg.From.Add(new SecureMailboxAddress("Taylor McCall", "<Email>", "<Certificate>"));
        newmsg.Subject = "Test message Here";
        var sender = newmsg.From.Mailboxes.FirstOrDefault();
        newmsg.Body = new TextPart(MimeKit.Text.TextFormat.Text);

        using (var ctx = new WindowsSecureMimeContext())
        {
            newmsg.Body = MultipartSigned.Create(ctx, sender, DigestAlgorithm.Sha256, newmsg.Body);
        }

        var client = new SmtpClient();
        client.Connect("mail.privateemail.com", 465, MailKit.Security.SecureSocketOptions.SslOnConnect);
        client.Authenticate("<Email>", "<Password>");
        client.Send(newmsg);
        client.Disconnect(true);
        client.Dispose();
```

**Protocol Logs**
No logs available

**Additional context**
I have attempted to correct this with a self-signed RSA certificate, but the email client also says that the email has been tampered with or the signature is incorrect.

Public certificate and signed emails are available upon request.

**Comment by tmccal2** [comment]
It doesn't seem to immediately correct the problem.

Where should the prepare method be placed?

**Comment by jstedfast** [comment]
Before signing the message

**Comment by tmccal2** [comment]
Setting it after creating the body and before signing the message does not seem to correct the problem.

**Comment by jstedfast** [comment]
Can you verify the message with MimeKit (before sending the message)?

**Comment by tmccal2** [comment]
Verification returns true.

Should the Prepare method set headers? I sent a signed message from my email client and the message returns a valid signature.

**Comment by tmccal2** [comment]
It may be because I set an empty message body. Having a body in the message seems to solve the problem.

Of all the face palm moments.

**Comment by tmccal2** [comment]
I should note, however, the the Gmail client still says the message has been tampered with.

**Comment by tmccal2** [comment]
I think it's safe to close. The problem of most clients rejecting signatures is resolved. The remainder appears to be a Gmail or a transport issue.
