### ISSUE TITLE
Folder not showing when created in Namecheap hosting for domain

### ISSUE THREAD

**Issue by vladtreny** [jstedfast/MailKit#1598]
**Describe the bug**
Namecheap email hosting for domain. 
When creating a folder, it is not displayed in the web interface (https://privateemail.com/) and via IMAP in email clients like Thunderbird or Apple Mail. However, it is visible in GetFolders.

On other email providers, it works as expected.

**Platform (please complete the following information):**
 - OS: All
 - .NET Framework: .Net 7
 - MailKit Version: 4.1.0

```csharp
using var client = new ImapClient();
client.Connect("mail.privateemail.com", 993, true); 
client.Authenticate("Namecheap login and password");
var toplevel = client.GetFolder(client.PersonalNamespaces[0]);
toplevel.Create("test", true);

// Here it is visible
client.GetFolders(client.PersonalNamespaces[0]).ToList().ForEach(i => Console.WriteLine(i.FullName));

```

**Comment by vladtreny** [comment]
Solved

**Comment by rodrigonsilva** [comment]
how?

> Resolvido

**Comment by jstedfast** [comment]
You probably need to subscribe the folder
