### ISSUE TITLE
CLR/System.ArgumentNullException

### ISSUE THREAD

**Issue by TomaszMyszak** [jstedfast/MailKit#1601]
I'm trying to use your extension for program to copy email, but have a problem. 

 w MailKit.Net.Imap.ImapFolder.<SearchAsync>d__304.MoveNext()
   w MailKit.Net.Imap.ImapFolder.Search(SearchOptions options, SearchQuery query, CancellationToken cancellationToken)

in this code

```
var uids = sourceInbox.Search(SearchOptions.All, null).UniqueIds;

            foreach (var uid in uids)
            {
                var sourceMessage = await sourceInbox.GetMessageAsync(uid);
                await destinationInbox.AppendAsync(sourceMessage);
            }
```

all method

`public async Task CopyEmails()
    {
        using (var sourceClient = new ImapClient())
        using (var destinationClient = new ImapClient())
        {
            await sourceClient.ConnectAsync(sourceServer, sourcePort, SecureSocketOptions.Auto);
            await sourceClient.AuthenticateAsync(sourceUsername, sourcePassword);

            await destinationClient.ConnectAsync(destinationServer, destinationPort, SecureSocketOptions.Auto);
            await destinationClient.AuthenticateAsync(destinationUsername, destinationPassword);

            var sourceInbox = sourceClient.Inbox;
            await sourceInbox.OpenAsync(FolderAccess.ReadOnly);

            var destinationInbox = destinationClient.Inbox;
            await destinationInbox.OpenAsync(FolderAccess.ReadWrite);

            Console.WriteLine("Znaleziono folder INBOX na serwerze źródłowym.");
            Console.WriteLine("Znaleziono folder INBOX na serwerze docelowym.");

            var uids = sourceInbox.Search(SearchOptions.All, null).UniqueIds;

            foreach (var uid in uids)
            {
                var sourceMessage = await sourceInbox.GetMessageAsync(uid);
                await destinationInbox.AppendAsync(sourceMessage);
            }

            Console.WriteLine("Skopiowano wiadomości z folderu INBOX.");

            await sourceClient.DisconnectAsync(true);
            await destinationClient.DisconnectAsync(true);
        }
    }

**Comment by jstedfast** [comment]
Hi Thomasz,

The problem is that you are passing null as the query argument to the Search() method.

You probably want to use SearchQuery.All instead of null.
