### ISSUE TITLE
ImapProtocolException: Syntax error in untagged QUOTA response

### ISSUE THREAD

**Issue by Glaerferyn** [jstedfast/MailKit#1602]
**Describe the bug**
When getting the Inbox Quota from a Gmail IMAP server, the response from the server is not expected and cannot be parsed (value is too long for an `uint`).

**Exception**
```ImapProtocolException: Syntax error in untagged QUOTA response. Unexpected atom token: 7881299347898368```

**Code Snippets**

```csharp
if (_client.SupportsQuotas)
{
    try
    {
        _currentQuota = await _client.Inbox.GetQuotaAsync(tt.Token);
    }
    finally
    {
        // Logging
    }
}
```

The `GetQuotaAsync` method throws and the client gets disconnected.

**Protocol Logs**

```
Connected to imaps://imap.gmail.com:993/
S: * OK Gimap ready for requests from XYZ
C: A00000000 CAPABILITY
S: * CAPABILITY IMAP4rev1 UNSELECT IDLE NAMESPACE QUOTA ID XLIST CHILDREN X-GM-EXT-1 XYZZY SASL-IR AUTH=XOAUTH2 AUTH=PLAIN AUTH=PLAIN-CLIENTTOKEN AUTH=OAUTHBEARER
S: A00000000 OK Thats all she wrote!
C: A00000001 AUTHENTICATE PLAIN ********
S: * CAPABILITY IMAP4rev1 UNSELECT IDLE NAMESPACE QUOTA ID XLIST CHILDREN X-GM-EXT-1 UIDPLUS COMPRESS=DEFLATE ENABLE MOVE CONDSTORE ESEARCH UTF8=ACCEPT LIST-EXTENDED LIST-STATUS LITERAL- SPECIAL-USE APPENDLIMIT=35651584
S: A00000001 OK abc@efg.com authenticated (Success)
C: A00000002 NAMESPACE
S: * NAMESPACE (("" "/")) NIL NIL
S: A00000002 OK Success
C: A00000003 LIST "" "INBOX" RETURN (SUBSCRIBED CHILDREN)
S: * LIST (\HasNoChildren \Subscribed) "/" "INBOX"
S: A00000003 OK Success
C: A00000004 LIST (SPECIAL-USE) "" "*" RETURN (SUBSCRIBED CHILDREN)
S: * LIST (\Drafts \HasNoChildren \Subscribed) "/" "[Gmail]/Brouillons"
S: * LIST (\HasNoChildren \Subscribed \Trash) "/" "[Gmail]/Corbeille"
S: * LIST (\HasNoChildren \Sent \Subscribed) "/" "[Gmail]/Messages envoy&AOk-s"
S: * LIST (\HasNoChildren \Junk \Subscribed) "/" "[Gmail]/Spam"
S: * LIST (\Flagged \HasNoChildren \Subscribed) "/" "[Gmail]/Suivis"
S: * LIST (\All \HasNoChildren \Subscribed) "/" "[Gmail]/Tous les messages"
S: A00000004 OK Success
C: A00000005 LIST "" "[Gmail]" RETURN (SUBSCRIBED CHILDREN)
S: * LIST (\HasChildren \NonExistent \Subscribed) "/" "[Gmail]"
S: A00000005 OK Success
C: A00000006 GETQUOTAROOT INBOX
S: * QUOTAROOT "INBOX" ""
S: * QUOTA "" (STORAGE 17417480 7881299347898368)
S: A00000006 OK Success
```

**Platform (please complete the following information):**
 - OS: [e.g. Windows, Linux, MacOS, iOS, Android, Windows Phone, etc.]
 - .NET Runtime: CoreCLR
 - .NET Framework: .NET 6
 - MailKit Version: 2.15 / 4.1

**Additional context**
The Gmail IMAP server is returning an absurdly long integer value for the QUOTA STORAGE available value 7881299347898368, though this value is supposed to be within the bound of an `uint` by RFC.

Supposedly we happen to have a quota on this account, but for some reason Gmail's IMAP server returns the highest possible value for the storage capacity. The Gmail interface itself is displaying the storage usage (17417480 kB) but considers we do not have a limit anymore. 

This maximum capacity is 7881299347898368, and converts as 0x1C000000000000 (a special flag on Gmail side ?).

Whether this is intended or not is unclear, I found only a couple other ressources regarding that error, as illustrated by this bug report for the Thunderbird product : https://bugzilla.mozilla.org/show_bug.cgi?id=1636665
They took the party to handle the storage values as `ulong` instead of `uint`.

Would you consider parsing those value as an `UInt64` rather than `UInt32` ?
Cheers :)

**Comment by jstedfast** [comment]
Thanks. I will consider using `ulong` instead of `uint`. It *probably* makes sense to do. I need to re-familiarize myself with the code there to be sure about what can be done. I also, unfortunately, need to weigh the consequences of breaking the API and ABI to make such a change.

**Comment by jstedfast** [comment]
The above patch reads the value from the IMAP response as a `ulong`, but converts it to a `uint` when storing it on the FolderQuota data structure in order to avoid API/ABI breakage.

Does that work for you?
