### ISSUE TITLE
SMTP Client Send Result

### ISSUE THREAD

**Issue by r-work** [jstedfast/MailKit#1604]
How do you determine if sending the email was successful?

The Send/SendAsync methods return a string, which at the moment for me it returns something like:
`XXXXXXXXXX mail accepted for delivery`.

And I'm pretty sure I've had results like `OK` in the past.

Is there way to simply know if the message was sent (i.e `true`/`false`) rather than trying to see if result contains 'OK', 'Accepted' etc..

**Comment by jstedfast** [comment]
If the method throws an exception, then it failed. If it doesn't throw an exception, then it succeeded.

**Comment by r-work** [comment]
Thanks for the quick reply.
That should probably be mentioned in the method documentation.
