### ISSUE TITLE
Inbox folder is null

### ISSUE THREAD

**Issue by xavier-rigau** [jstedfast/MailKit#161]
Symptom: 

```csharp
var inbox = _imapClient.Inbox;
```

inbox is null after this call.

This is a stress test that involves calling this sequence in fast succession:

```csharp
await _imapClient.ConnectAsync(_currEmailAccountInfoAcct.Servername, 993, true, _emailCancellationTokenSource.Token);

await inbox.OpenAsync(FolderAccess.ReadOnly);

_imapClient.AuthenticationMechanisms.Remove("XOAUTH2");

await  _imapClient.AuthenticateAsync(_currEmailAccountInfoAcct.UserName, _currEmailAccountInfoAcct.Password);

const MessageSummaryItems summaryItems =  MessageSummaryItems.Envelope | 
          MessageSummaryItems.Flags | MessageSummaryItems.InternalDate |
          MessageSummaryItems.MessageSize | MessageSummaryItems.BodyStructure;

var summaries = await inbox.FetchAsync(minIndex, maxIndex, summaryItems);

// This is called from the UI thread while some of the calls above are going on.
await _imapClient.DisconnectAsync(true);
```

I also observed that sometimes the exception sequence is 

```
A first chance exception of type 'System.OperationCanceledException' occurred in mscorlib.ni.dll
A first chance exception of type 'System.OperationCanceledException' occurred in MailKit.ni.DLL
A first chance exception of type 'System.OperationCanceledException' occurred in MailKit.ni.DLL
```

and sometimes is:

```
A first chance exception of type 'System.Threading.Tasks.TaskCanceledException' occurred in mscorlib.ni.dll
A first chance exception of type 'System.Threading.Tasks.TaskCanceledException' occurred in MailKit.ni.DLL
A first chance exception of type 'System.Threading.Tasks.TaskCanceledException' occurred in mscorlib.ni.dll
```

Here is a log of a case where the inbox was null.

```
A first chance exception of type 'System.Threading.Tasks.TaskCanceledException' occurred in mscorlib.ni.dll
A first chance exception of type 'System.Threading.Tasks.TaskCanceledException' occurred in MailKit.ni.DLL
A first chance exception of type 'System.Threading.Tasks.TaskCanceledException' occurred in mscorlib.ni.dll
The thread 0x1768 has exited with code 0 (0x0).
A first chance exception of type 'System.Threading.Tasks.TaskCanceledException' occurred in mscorlib.ni.dll
A first chance exception of type 'System.Threading.Tasks.TaskCanceledException' occurred in MailKit.ni.DLL
A first chance exception of type 'System.Threading.Tasks.TaskCanceledException' occurred in mscorlib.ni.dll
A first chance exception of type 'System.Threading.Tasks.TaskCanceledException' occurred in mscorlib.ni.dll
A first chance exception of type 'System.Threading.Tasks.TaskCanceledException' occurred in MailKit.ni.DLL
A first chance exception of type 'System.Threading.Tasks.TaskCanceledException' occurred in mscorlib.ni.dll
A first chance exception of type 'System.Threading.Tasks.TaskCanceledException' occurred in mscorlib.ni.dll
A first chance exception of type 'System.Threading.Tasks.TaskCanceledException' occurred in MailKit.ni.DLL
A first chance exception of type 'System.Threading.Tasks.TaskCanceledException' occurred in mscorlib.ni.dll
'ePEMobile.WindowsPhone.exe' (CoreCLR: .): Loaded 'C:\data\ProgramData\Microsoft\Windows\AppRepository\Packages\AD2F1837.HPePrintEnterprise_1.0.0.7_neutral__v10z8vjag6ke6\NI\Portable.Text.Encoding.ni.DLL'. Cannot find or open the PDB file.
'ePEMobile.WindowsPhone.exe' (CoreCLR: .): Loaded 'C:\windows\system32\SYSTEM.TEXT.ENCODING.NI.DLL'. Symbols loaded.
'ePEMobile.WindowsPhone.exe' (CoreCLR: .): Loaded 'C:\windows\system32\System.Net.ni.DLL'. Cannot find or open the PDB file.
The thread 0x1704 has exited with code 0 (0x0).
The thread 0x175c has exited with code 259 (0x103).
A first chance exception of type 'System.OperationCanceledException' occurred in mscorlib.ni.dll
A first chance exception of type 'System.OperationCanceledException' occurred in MailKit.ni.DLL
A first chance exception of type 'System.OperationCanceledException' occurred in MailKit.ni.DLL
The thread 0x1718 has exited with code 259 (0x103).
The thread 0x1710 has exited with code 259 (0x103).
A first chance exception of type 'System.OperationCanceledException' occurred in mscorlib.ni.dll
```

**Comment by jstedfast** [comment]
The `client.Inbox` will *always* be null until you `Connect()` and `Authenticate()`.

But you are getting the value of `client.Inbox` *before* you authenticate.

**Comment by xavier-rigau** [comment]
Doh. Inherited code makes me lazy. Appreciated.

Sent from my Windows Phone 8.1
Excuse dictation errors coma tpyos and brevity.
________________________________

**Comment by xavier-rigau** [comment]
How about putting some guard or throwing and exception if somebody uses the bad order? Just a thought.

**Comment by jstedfast** [comment]
Already added it as part of MailKit 1.0.11 that I just released to NuGet :-)

**Comment by xavier-rigau** [comment]
Original developer pointed out the order was correct. I added those missing lines in the original post.

///////////////////////////////////////////
// I forgot to add those lines //
///////////////////////////////////////////

var inbox = _imapClient.Inbox;
await inbox.OpenAsync(FolderAccess.ReadOnly);

///////////////////////////////////////////

**Comment by jstedfast** [comment]
It doesn't matter because you are still trying to open the Inbox before you've authenticated.

**Comment by xavier-rigau** [comment]
I might be missing something because the code is clear.
_imapClient = new LoggingImapClient();

                if (_imapClient != null)
                {

                    if (_currEmailAccountInfoAcct.UsesSsl)
                        await
                            _imapClient.ConnectAsync(_currEmailAccountInfoAcct.Servername, 993, true,
                                _emailCancellationTokenSource.Token);
                    else
                    {
                        await
                            _imapClient.ConnectAsync(_currEmailAccountInfoAcct.Servername, 143, false,
                                _emailCancellationTokenSource.Token);
                    }

                    // Note: since we don't have an OAuth2 token, disable
                    // the XOAUTH2 authentication mechanism.
                    _imapClient.AuthenticationMechanisms.Remove("XOAUTH2");

                    await
                        _imapClient.AuthenticateAsync(_currEmailAccountInfoAcct.UserName,
                            _currEmailAccountInfoAcct.Password);

                    Debug.Assert(_numMessagesDownloadedSoFar == 0);
                    _numMessagesDownloadedSoFar = 0;

                    // Set a timer that will be calling the email server to perform a No Operation to 
                    // keep it from disconnecting.
                    _idleTimer = new DispatcherTimer { Interval = TimeSpan.FromMilliseconds(ServerConstants.EMAIL_SERVER_NO_OP_PERIOD) };
                    _idleTimer.Tick += NoOpCallBack;

                    LoadMoreMessages = await FetchMessagesAsync();

**Comment by jstedfast** [comment]
In your original bug report, you pasted the following code snippet:

```csharp
await _imapClient.ConnectAsync(_currEmailAccountInfoAcct.Servername, 993, true, _emailCancellationTokenSource.Token);

await inbox.OpenAsync(FolderAccess.ReadOnly);

_imapClient.AuthenticationMechanisms.Remove("XOAUTH2");

await  _imapClient.AuthenticateAsync(_currEmailAccountInfoAcct.UserName, _currEmailAccountInfoAcct.Password);
```

Notice how you connect, then open the folder, and *then* authenticate.

**Comment by xavier-rigau** [comment]
Which proves why I should always cut and paste and not try write a loop from memory. Sorry about this. The issue, I guess, should be reopened after my brain fr@7$ have been clarified.

**Comment by jstedfast** [comment]
if you can get me a test case that still returns null after connecting and then authenticating, I'll look into why, but currently I don't see how that would be possible.

**Comment by xavier-rigau** [comment]
Fair enough. It is a corner case very hard to reproduce.
