### ISSUE TITLE
Handle Envelope-to header

### ISSUE THREAD

**Issue by vladtreny** [jstedfast/MailKit#1611]
Does this lib include Envelope-to header in message.To array?
Return-path: <>
Envelope-to: email@exmaple.com
Delivery-date:

**Comment by jstedfast** [comment]
No, the MimeMessage.To property only includes the `To` header.

You can get the list of addresses in the `Envelope-To` header this way:

```csharp
int index = message.Headers.IndexOf(HeaderId.EnvelopeTo);
if (index >= 0) {
    var addrList = InternetAddressList.Parse(message.Headers[index].RawValue);
}
```
