### ISSUE TITLE
Setting up email configuration in .net core 6

### ISSUE THREAD

**Issue by Softkonnectdev** [jstedfast/MailKit#1612]
Please how can I set up my email configuration using my domain name mailbox e.g info@webhost.com?

**Comment by jstedfast** [comment]
MailKit doesn't use any configuration, so this question doesn't make sense.

What you will need to do is when you call the `Connect(string hostName, int port, SecureSocketOptions sslOptions)` method with your "configured" values, but you'll have to write your own logic for getting those values. Maybe you want to save those values in json or xml or maybe you want to hard-code them or maybe you want to prompt a user.
