### ISSUE TITLE
Occasional Problems Downloading IMAP from Office365

### ISSUE THREAD

**Issue by James-Treacy** [jstedfast/MailKit#1615]
Hi Jeffrey,

At our business in Sydney, Dataline, we have been using Mimekit/Mailkit for several years and I really like it.  I sent you a donation a few years ago.  We use email for invoice delivery to our processing bureau and CANNOT lose emails or suppliers don't get paid and we lose customers.  I have used Mimekit and Mailkit to build a fairly robust mail gateway in C# .net 4.7.2.

We are finding that for some (not all) high volume Office365 email accounts (> 1000/day) we are not able to fetch all the message content.    I have raised a case with Microsoft - you are aware that O365 FETCH commands sometimes return nothing even though the UID was returned in a search.  Worse still, the message is visible in Outlook Web App and can be opened, its attachments downloaded.  Groan, I can't do this via Mailkit (yet).

Thinking the mailbox might be corrupt I have twice done a Powershell Move-Request, took ages but didn't improve anything.

I am stuck, MS is not being particularly helpful yet and I can't even fetch message headers or the Unique ID for some messages but Outlook can do it every time.  I have lots of logs but they are basically saying a search returns UID x (e.g. 5721 below) but the FETCH just returns nothing ..., like this:

C: A00000008 UID SEARCH UNDELETED
S: * SEARCH 5721 5722 5723 5724
S: A00000008 OK SEARCH completed.
C: A00000009 UID FETCH 5721 (BODY.PEEK[])
S: A00000009 OK FETCH completed.

Ugh.  Any suggestions on how I can patch up what seems to be dud MIME content, I really need to get to the attachment(s) but FETCH just fails on me.  I am hopeful for a solution - Microsoft has it licked in Outlook and OWA but of course I don't have that source code.  The current feedback from MS is use the Graph API but I much prefer Mailkit and don't have a .net core 2.0 environment to work in.

Any suggestions on how to collect messages with corrupt headers?  I'm happy to hack away towards a solution if there is one.  Asking customers to re-send is pretty lame in our business.

Cheers
James Treacy
Senior Applications Development Manager
The Dataline Group
Sydney AUSTRALIA
Email james.treacy@dataline.com.au

**Comment by James-Treacy** [comment]
[imaplogAug042023.txt](https://github.com/jstedfast/MailKit/files/12258092/imaplogAug042023.txt)
[MailLogAug42023.txt
[OWAMessage1141am.txt](https://github.com/jstedfast/MailKit/files/12258105/OWAMessage1141am.txt)
[OWAMessage1143am.txt](https://github.com/jstedfast/MailKit/files/12258106/OWAMessage1143am.txt)
[OWAMessage248pm-OK.txt](https://github.com/jstedfast/MailKit/files/12258108/OWAMessage248pm-OK.txt)
](https://github.com/jstedfast/MailKit/files/12258093/MailLogAug42023.txt)

**Comment by James-Treacy** [comment]
Thanks for a prompt reply.  Repeated GetMesasage or Fetch calls on these ones generally fail, however if I manually move the message to another folder in Outlook then move it back to the Inbox, it succeeds perhaps 40% of the time.  I have had varied success with Fetch-Envelope and even Fetch-UID's fail, but will try AddFlags and respond with some results.  

As context our many customers are hurriedly forwarding us dozens of mail messages first thing in the morning, each with one or often twenty attachments - many attachments are messages containing PDF attachments.  These are never a problem once we get past GetMessage. or Fetch.  As it is a busy cross-O365-Tenant mailbox that we need to process regularly, I might now create another mailbox and have Office365 forward to that for a production band aid.  Hopefully Office365 will fix up content deformities while forwarding like it does in Outlook.

Thanks for the suggestions I will try and let you know the outcome.

**Comment by James-Treacy** [comment]
I can manipulate the message flags and this is shown in Outlook straight away, but still can't fetch any content:
C: A00000005 SELECT INBOX
S: * 1 EXISTS
S: * 0 RECENT
S: * FLAGS (\Seen \Answered \Flagged \Deleted \Draft $MDNSent)
S: * OK [PERMANENTFLAGS (\Seen \Answered \Flagged \Deleted \Draft $MDNSent)] Permanent flags
S: * OK [UNSEEN 1] Is the first unseen message
S: * OK [UIDVALIDITY 14] UIDVALIDITY value
S: * OK [UIDNEXT 1529866] The next unique identifier value
S: A00000005 OK [READ-WRITE] SELECT completed.
C: A00000006 UID SEARCH UNDELETED
S: * SEARCH 1529863
S: A00000006 OK SEARCH completed.
C: A00000007 UID STORE 1529863 +FLAGS.SILENT (\Flagged)
S: A00000007 OK STORE completed.
C: A00000008 UID STORE 1529863 +FLAGS (\Answered)
S: * 1 FETCH (FLAGS (\Answered \Flagged))
S: A00000008 OK STORE completed.
C: A00000009 UID FETCH 1529863 (BODY.PEEK[])
S: A00000009 OK FETCH completed.

**Comment by jstedfast** [comment]
Office365 IMAP guys are asking me how to reproduce this. Any suggestions? Is it just the blank line in the middle of the headers?

**Comment by James-Treacy** [comment]
If I forward one of these emails anywhere, then O365 will often, but not always, fix up the problem, so that's not going to work.  I can schedule an exact time to run the code, or better still make this production email account available for direct examination by the Office365 team.  We can reproduce the error easily like this:

When GetMessage fails I move the message to the Error folder and it stays there broken.  We get about 30 a day out of 700 to 1000 good ones for this account.  So right now I have 30 good test cases ready for examination sitting in the Error folder.  Just issue a Search Undeleted then GetMessage - or even simpler, fetch(0,1) to one of these and it will fail.

I will leave at least one in that Error folder.  We could make an exact time for me to exec the GetMessage call against this (and my log records at milliseconds - we are GMT+10), or they could have a look at one of these dud messages with their tools anytime.  Having the O365 team examine a specific message would be great and to enable that I can send you credentials for access.  

If you think this is a good idea I would prefer to send credentials a bit more privately that Github allows.  Do you have a suitable email address that I can send two messages to.  The first will be the O365 account email and the password will come after you confirm the first has been received.  The caveat is that no messages in the Inbox should be touched, but they can have free reign of the Error folder.

I'm very grateful for your interest in this issue and especially getting the O365 heavies involved.  I am confident my code and my implementation of your code is sound, there is something I just am not getting and an expert's help would be really appreciated.   My reputation at work has suffered from this.

Cheers James Treacy

**Comment by jstedfast** [comment]
James,

Let's hold off on sending me any passwords quite yet.

Send me an email at jestedfa@microsoft.com and I'll loop in someone from the Office365 IMAP team and then we'll figure out how to proceed from there.
