### ISSUE TITLE
EHLO after AUTH causes send failure with 5.7.0 even though authentication succeeded

### ISSUE THREAD

**Issue by fubar-coder** [jstedfast/MailKit#162]
I've found a problem with an E-Mail provider (Strato) that causes a 5.7.0 error after a successful authentication (2.7.0) due to the sent EHLO after the authentication.

```
Connected to smtp://smtp.strato.de:587/
S: 220 smtp.strato.de ESMTP RZmta 37.4 ready (mo11)
C: EHLO [192.168.1.70]
S: 250-smtp.strato.de greets 79.194.205.58
S: 250-ENHANCEDSTATUSCODES
S: 250-8BITMIME
S: 250-PIPELINING
S: 250-DELIVERBY
S: 250-SIZE 104857600
S: 250-AUTH SCRAM-SHA-1 DIGEST-MD5 CRAM-MD5 LOGIN PLAIN
S: 250-STARTTLS
S: 250 HELP
C: STARTTLS
S: 220 Ready to start TLS
C: EHLO [192.168.1.70]
S: 250-smtp.strato.de greets 79.194.205.58
S: 250-ENHANCEDSTATUSCODES
S: 250-8BITMIME
S: 250-PIPELINING
S: 250-DELIVERBY
S: 250-SIZE 104857600
S: 250-AUTH SCRAM-SHA-1 DIGEST-MD5 CRAM-MD5 LOGIN PLAIN
S: 250 HELP
C: AUTH SCRAM-SHA-1 XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
S: 334 XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
C: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
S: 334 XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
C: 
S: 235 2.7.0 OK Authenticated
C: EHLO [192.168.1.70]
S: 250-smtp.strato.de greets 79.194.205.58
S: 250-ENHANCEDSTATUSCODES
S: 250-8BITMIME
S: 250-PIPELINING
S: 250-DELIVERBY
S: 250-SIZE 104857600
S: 250-AUTH SCRAM-SHA-1 DIGEST-MD5 CRAM-MD5 LOGIN PLAIN
S: 250 HELP
C: MAIL FROM:<XXXXXXXX@XXXXXXX.de>
C: RCPT TO:<XXXXXXXX@XXXXXXX.de>
S: 530 5.7.0 Bitte konfigurieren Sie ihr E-Mailprogramm fuer Authentifizierung am SMTP Server, wie auf www.strato.de/email-hilfe beschrieben. - Please configure your mail client for using SMTP Server Authentication
S: 503 5.5.1 need MAIL FROM first
C: QUIT
S: 221 2.0.0 closing connection
```

**Comment by jstedfast** [comment]
Can you please report this bug to Strato? Clients are supposed to send EHLO after authenticating.

The reason the RFC says SHOULD and not MUST is because it depends on whether or not the client uses extensions. If the client doesn't use extensions, then obviously it doesn't need to re-fetch them. Otherwise it needs to.

**Comment by fubar-coder** [comment]
I tried, but they don't give a **** about standard compliance and they're big enough to get away with it :disappointed: . They don't even provide E-Mail support for non-customers...

**Comment by jstedfast** [comment]
I've committed a different workaround. I'd rather not introduce public APIs to work around broken servers.

**Comment by fubar-coder** [comment]
Thank you :+1:

**Comment by cnblogs-dudu** [comment]
smtp.dm.aliyun.com has the same problem.

**Comment by jstedfast** [comment]
I've released MailKit 1.4.1 with a fix for this to nuget.org

**Comment by analogic** [comment]
@jstedfast Can you please point me to RFC? I have found only https://tools.ietf.org/html/rfc4954 which states that there should be additional EHLO only after TLS negotiation.

(ref https://bitbucket.org/analogic/mailserver/issues/183/mailkit-cant-authenticate-in-posteio)

**Comment by jstedfast** [comment]
It doesn't say anything about TLS negotiation, it says after any security layer has been obtained. SASL stands for Simple Authentication and Security Layer.

**Comment by jstedfast** [comment]
That said, rfc4616 does state: `The PLAIN SASL mechanism does not provide a security layer.`.

**Comment by analogic** [comment]
Thanks!

**Comment by SonicGD** [comment]
Thank you

**Comment by jstedfast** [comment]
FWIW, MailKit 1.14.1 fixes this.
