### ISSUE TITLE
MDaemon server: errors while using MailKit

### ISSUE THREAD

**Issue by Bykiev** [jstedfast/MailKit#1622]
Hello,

thank you for you hard work, I really love you library!

Unfortunately I'm facing some errors while reading/sending mails with MailKit. I believe these errors caused by server, but I need to use MDaemon mail server (MDaemon 8.1.1). What do you think about it? Is anything can be done on client side?

Here is some logs from MDaemon:

```
Error reading from socket!
Unexpected socket closure
SMTP session terminated (Bytes in/out: 0/76)
----------
Error reading from socket!
Winsock Error 10053 Software caused a connection abort.
SMTP session terminated (Bytes in/out: 0/76)
----------
Error reading from socket!
Winsock Error 10054 Connection was reset by the other side!
SMTP session terminated (Bytes in/out: 0/76)
----------
Error reading from socket!
Unexpected socket closure
SMTP session terminated (Bytes in/out: 0/76)

IMAP:
Socket connection closed by the other side (how rude!)
Winsock Error 10053 Software caused a connection abort.
Unexpected socket closure
IMAP session terminated, (54 bytes)
----------
```

This warning is always in MDaemon's log on successful read:

```
Socket connection closed by the other side (how rude!)
IMAP session terminated, (45945 bytes)
```

Typically, other client's IMAP log looking like this:
```
<-- pnkl LOGOUT
--> * BYE IMAP engine signing off (no errors)
IMAP session complete, (XXX bytes)
```

**Comment by Bykiev** [comment]
> 
> This warning is always in MDaemon's log on successful read:
> 
> ```
> Socket connection closed by the other side (how rude!)
> IMAP session terminated, (45945 bytes)
> ```
> 
> Typically, other client's IMAP log looking like this:
> 
> ```
> <-- pnkl LOGOUT
> --> * BYE IMAP engine signing off (no errors)
> IMAP session complete, (XXX bytes)
> ```

I think I need to call `Disconnect` method with `true` to send `LOGOUT ` command

**Comment by Bykiev** [comment]
> > I think I need to call Disconnect method with true to send LOGOUT command
> 
> That is the solution to your problems, yes.

Sorry, but what about IMAP errors?

**Comment by jstedfast** [comment]
Same thing.
