### ISSUE TITLE
Get mailbox Size using pop3

### ISSUE THREAD

**Issue by usamasarfraz** [jstedfast/MailKit#1623]
How can we get mailbox size (in bytes) using mailkit pop3 just like we get using STAT command.
In logs we are getting mailbox size but in mailkit we didn't found any method or property to get this.
******************
C: STAT
S: +OK 3376 5720744
******************

**Comment by jstedfast** [comment]
Looks like Pop3Client caches the data but doesn't provide a property. I can add one.

**Comment by usamasarfraz** [comment]
How long it will take to add this property ?

**Comment by jstedfast** [comment]
The biggest hurdle to adding this is deciding on the name to use for the property. It should be quick & easy to add because there is already a member variable that contains the value.

**Comment by usamasarfraz** [comment]
The STAT command displays the number of messages currently in the mailbox and the size in bytes.
So you can name this property as size.
