### ISSUE TITLE
Example how to use GetStreamAsync method for ImapFolder

### ISSUE THREAD

**Issue by aldayneko** [jstedfast/MailKit#1627]
Hello,

Is there any example how to use GetStreamAsync on ImapFolder properly ?
`Task<Stream> GetStreamAsync(UniqueId uid, BodyPart part, int offset, int count, CancellationToken cancellationToken = default(CancellationToken), ITransferProgress progress = null);
`
What I'm trying to achieve with this method is to get attachment as a stream and return this stream as a part of FileStreamResult from web api endpoint.

At this moment there are two unclear things for me:
1. Method requires count parameter. Is it attachment size ? How to get it correctly from message ?
2. Is it necessary to call Close method on ImapFolder ? If so, how to do it correctly ? Does Close method dispose all opened streams ? I'm asking because if I simple call Close method my endpoint still continues to read data from stream when returning FileStreamResult 

Thanks in advance

**Comment by aldayneko** [comment]
Thanks a lot for the response
But how to get attachment as a stream if I need decoded content ?
As I can see there is an option to call MimeContent.DecodeTo() method, but it means all data will be buffered into memory stream which is not good from resources management perspective.
Are there any options not to write decoded data to stream but to read decoded data as a stream ?

**Comment by aldayneko** [comment]
Thanks a lot for the response
But how to get attachment as a stream if I need decoded content ?
As I can see there is an option to call MimeContent.DecodeTo() method, but it means all data will be buffered into memory stream which is not good from resources management perspective.
Are there any options not to write decoded data to stream but to read decoded data as a stream ?

**Comment by jstedfast** [comment]
> But how to get attachment as a stream if I need decoded content ?

foreach (var attachment in item.Attachments) {
    // Figure out a filename to use to save the part.
    string fileName = attachment.FileName;

    if (string.IsNullOrEmpty (fileName)) {
        if (!MimeTypes.TryGetExtension (attachment.ContentType.MimeType, out string extension))
            extension = ".dat";

        fileName = Guid.NewGuid ().ToString () + extension;
    }

    // If all we want is the content (rather than the entire MIME part including the headers), then
    // we want the ".TEXT" section of the part.
    using (var content = client.Inbox.GetStream (item.UniqueId, attachment.PartSpecifier + ".TEXT")) {
#if USE_MIME_CONTENT
        ContentEncoding encoding;

        if (string.IsNullOrEmpty (attachment.ContentTransferENcoding) || !MimeUtils.TryParse (attachment.ContentTransferEncoding, out encoding))
            encoding = ContentEncoding.Default;

        using (var mimeContent = new (content, encoding)) {
            using (var stream = File.Create (fileName))
                mimeContent.DecodeTo (stream);
        }
#else
        using (var stream = File.Create (fileName)) {
            using (var filtered = new FilteredStream (stream)) {
                if (!string.IsNullOrEmpty (attachment.ContentTransferEncoding)) {
                    var decoder = DecoderFilter.Create (attachment.ContentTransferEncoding);
                    filtered.Add (filter);
                }

                content.CopyTo (filtered);
                filtered.Flush ();
            }
        }
#endif
    }
}
```

> As I can see there is an option to call MimeContent.DecodeTo() method, but it means all data will be buffered into memory stream which is not good from resources management perspective.

MimeContent.DecodeTo() doesn't load everything into memory, it incrementally decodes the stream as it reads it and writes each chunk to the output stream.

In the above example, the difference between the USE_MIME_CONTENT option and the low-level FilteredStream option is just that MimeContent is a lot simpler to deal with.

> Are there any options not to write decoded data to stream but to read decoded data as a stream ?

No. MailKit doesn't have the context to know what the content transfer encoding is.
