### ISSUE TITLE
UniqueIdRange.ToList() doesn't work for large arrays.

### ISSUE THREAD

**Issue by danzuep** [jstedfast/MailKit#1631]
The following code throws an Overflow exception:
`new UniqueIdRange(UniqueId.MinValue, UniqueId.MaxValue).ToList();`
System.OverflowException: 'Arithmetic operation resulted in an overflow.'

The following code throws an OutOfMemory exception on my laptop:
`new UniqueIdRange(UniqueId.MinValue, new UniqueId(int.MaxValue - 1)).ToList();`
`System.OutOfMemoryException: 'Array dimensions exceeded supported range.'`

MailKit Version: 4.1.0

If `ToList` shouldn't be used then perhaps some other exception would be more appropriate.

**Comment by jstedfast** [comment]
Why are you using ToList() in the first place??

UniqueIdRange already implements the IList<UniqueId> interface and uses way less memory to represent that UID range than a List<UniqueId> would, which is why you are getting a OutOfMemory exception. You just tried to allocate 4 gigabytes of memory!!!

**Comment by danzuep** [comment]
I have a method that does an IList pattern match on an IEnumerable<UniqueId> for an IMailFolder query which takes very little memory, but someone using that method tried to use a UniqueIdRange.ToList() so I thought you might want to improve the handling of that instead of just consuming so many resources. UniqueIdRange has this issue, not IList<UniqueId>.

**Comment by jstedfast** [comment]
Unfortunately, I do not have any control over the ToList() method because it is a LINQ extension method.
