### ISSUE TITLE
GMail - remove label from mailbox

### ISSUE THREAD

**Issue by Kegelcizer** [jstedfast/MailKit#1637]
I'm trying to stamp emails with processing and processed labels that contain datetime.
While this works fine, I'm unable to remove all the processing labels that remain unused.

I would like to programmatically remove these labels, for this I need to enumerate and delete them, if possible.
For enumerating them I've found client.GetFolders(client.PersonalNamespaces[0], false) but nothing on deleting them.

Thank you!

**Comment by jstedfast** [comment]
IMailFolder has a Delete method.

http://www.mimekit.net/docs/html/M_MailKit_Net_Imap_ImapFolder_Delete.htm

**Comment by Kegelcizer** [comment]
I got stuck on thinking folders and labels are different things and GMail labels can only be used with the appropriate prefixed methods like HasGMailLabel. Thank you again!
