### ISSUE TITLE
`Sender` from a gmail group alias doesn't work?

### ISSUE THREAD

**Issue by khteh** [jstedfast/MailKit#1638]
**Describe the bug**
I am trying to fix the Sender to a GMAIL group alias but the email is always received from the email alias used in `AuthenticateAsync`
```
                    MimeMessage msg = new MimeMessage() {
                        Sender = MailboxAddress.Parse("group@email.com"),
                        Subject = subject
                    };
```
How to correctly set up the `Sender` or `From` so that emails received is from my GMAIL group alias?

**Platform (please complete the following information):**
 - OS: [e.g. Windows, Linux, MacOS, iOS, Android, Windows Phone, etc.] Ubuntu 23.04
 - .NET Runtime: [e.g. CoreCLR, Mono] CoreCLR
 - .NET Framework: [e.g. .Net Core, .NET 4.5, UWP, etc.] .Net Core
 - MailKit Version: 4.1.0

**Exception**
If you got an exception, please include the exception Message *and* StackTrace.

**To Reproduce**

**Expected behavior**

**Code Snippets**
If applicable, add code snippets to help explain your problem.

```csharp
// Add your code snippet here.
```

**Protocol Logs**
Please include a protocol log (scrubbed of any authentication data), especially
if you got an exception such as `Syntax error in XYZ. Unexpected token: ...`.

To get a protocol log, follow one of the following code snippets:

```csharp
// log to a file called 'imap.log'
var client = new ImapClient (new ProtocolLogger ("imap.log"));
```

```csharp
// log to a file called 'pop3.log'
var client = new Pop3Client (new ProtocolLogger ("pop3.log"));
```

```csharp
// log to a file called 'smtp.log'
var client = new SmtpClient (new ProtocolLogger ("smtp.log"));
```

Note: if the protocol log contains sensitive information, feel free to email it to me at
jestedfa@microsoft.com instead of including it in the GitHub issue.

**Additional context**

**Comment by jstedfast** [comment]
The simple answer is that you can't because GMail won't let you. It is overriding the Sender and From headers to stop email spoofing.

**Comment by khteh** [comment]
Does AWS SES support this?

**Comment by jstedfast** [comment]
The hosting service will have nothing to do with this.

The fact that you are trying to use GMail is why you can't spoof another address.

**Comment by jstedfast** [comment]
Maybe, you'll have to try it.

**Comment by khteh** [comment]
Yes, it works with AWS SES + SNS!
