### ISSUE TITLE
I need help regarding IMAP (Stopping, filtering messages etc.)

### ISSUE THREAD

**Issue by MyInviteacc** [jstedfast/MailKit#1643]
As title describes, I can't quite understand how to use this library to control messages sent to my IMAP server?
I'm a .NET Developer and a client requested to control an IMAP server (with credentials for sure like name, ip, port, etc..) through a desktop application.
I can't really understand where to start on each topic needed for something like this.
Thank you.

**Comment by MyInviteacc** [comment]
@jstedfast Thanks for replying, But as stated I did read the readme already .......
All I can see is fetching/traversing folders etc..
There is nothing about the cases mentioned in my issue.
To be more specific one more time:
1. Control the time messages reaches my IMAP server
2. Filter messages that hass specific keywords, allow messages that have specific keywords etc.
3. Documentation for later controlling (so I can search and try myself).
Thank you.

**Comment by jstedfast** [comment]
I'm not sure what your definition of specific is, but it's clearly not the same as mine.

Your first question is completely nonsensical.

Your second question is so vague that I'm not sure where to begin. I would recommend getting some clarity about what you actually want to do here. What do you mean by "filter"? What do you mean by "allow messages"? What do you mean by "keywords"? IMAP has a concept of keywords, but based on your lack of clarity into what you actually hope to accomplish, I have a sneaking suspicion that IMAP's keywords are not what you are looking for.

Your third question, is again, vague and nonsensical and if such an answer exists to your question, then it would be http://www.mimekit.net/docs which is linked directly from the README.md file that I told you to look at before (and which you assure me you did).

For even more in-depth knowledge of the IMAP protocol, I provide a [RFCs.md](https://github.com/jstedfast/MailKit/blob/master/RFCs.md) file that acts as an index to all of the specification documents outlining the features of IMAP and how to do all of the various tasks that it supports.

My documentation website also provides a search feature so you can search for keywords in the documentation.

**Comment by jstedfast** [comment]
Let's ask ChatGPT for some answers...

If you want to control when messages reach your IMAP server, there are a few strategies you can employ. However, remember that controlling incoming emails to your IMAP server might require advanced configurations or interventions at different points in the email delivery process. Here are some methods:

	1.	Server-Level Configuration:
	•	Some mail server software allows you to set up rules or filters that can delay the delivery of incoming messages. For instance, you could set up a rule to hold all incoming emails for a specified period before delivering them to the mailbox.
	•	This approach requires admin-level access to the mail server software.
	2.	SMTP Gateway or Intermediate SMTP Server:
	•	You could set up an SMTP gateway or an intermediate SMTP server that first receives emails. This server can be configured to delay forwarding emails to the actual IMAP server.
	•	This is an advanced method and requires a deep understanding of mail server configurations.
	3.	Custom Application:
	•	If you’re creating an application that reads messages from an IMAP server, you can control when your application fetches or displays these emails, even if they’ve already reached the server.
	•	This doesn’t delay the email’s arrival to the IMAP server, but it can delay when the email is presented or made visible to the end-user.
	4.	MX Record Configuration:
	•	If you have control over your domain’s DNS settings, you can adjust the MX (Mail Exchange) records. By pointing your MX records to an intermediary mail server or service, you can control or delay the forwarding of emails to your primary IMAP server.
	•	This is a more advanced method and might be overkill for most scenarios.
	5.	Third-party Services:
	•	There are third-party email services or tools that might offer features to delay or schedule email deliveries. These would act as a middle-man, holding onto emails until the specified delivery time.
	6.	Email Client Level:
	•	Some email clients allow rules or plugins that can delay the fetching of emails from the server. While the emails would still be on the IMAP server, the client wouldn’t display them until a certain time.
	•	This doesn’t control when messages reach the server, but it controls when they’re displayed to the user.
	7.	Legal and Ethical Considerations:
	•	If you’re thinking of delaying emails for users, ensure that you’re transparent about this and that you have valid reasons for doing so. Delays in email delivery can impact businesses and personal communications significantly.

It’s essential to clarify the exact reasons and needs for controlling the timing of emails. If you’re trying to manage workloads, ensure timely responses, or similar objectives, there might be other strategies or tools more suited to the task. If you’re thinking of implementing this for a business, consider getting input from stakeholders, IT personnel, and possibly legal counsel to ensure there are no unintended consequences or issues.

**Comment by MyInviteacc** [comment]
Thanks for such a thorough answer. Maybe I wasn't clear enough so I will - hopefully - make it clear this time.
1. Actually there IS a program that does this - but in some other programming language and with different control menus etc - so I want to recreate this in .NET C# (since i'm a .net developer). What does delay means is for example i want emails that contain word "dog" to reach the email account under my IMAP server after 50 minutes from the "send message" event, and emails containing word "Cat" reach email only after 15 minutes etc.
2. Filter, filter is to allow passage of something or disallow passage of something, So I want to make filtering capababilities through IMAP by manipulating some configuration from the .NET client I'm seeking to develop (like adding the keywords, specify which keywords gets allowed, which keywords doesn't and etc).
3. 
![image](https://github.com/jstedfast/MailKit/assets/138369501/35b60f33-1a9f-4341-9986-ba71df0c57af)
I don't see anything related to IMAP

**Comment by MyInviteacc** [comment]
![image](https://github.com/jstedfast/MailKit/assets/138369501/56d3f1e8-3ba2-46bb-a06b-c375f9115c56)
The configuration from the old program that i'm willing to recreate.

**Comment by jstedfast** [comment]
> Actually there IS a program that does this - but in some other programming language and with different control menus etc - so I want to recreate this in .NET C# (since i'm a .net developer). What does delay means is for example i want emails that contain word "dog" to reach the email account under my IMAP server after 50 minutes from the "send message" event, and emails containing word "Cat" reach email only after 15 minutes etc.

None of the protocols that MailKit supports have the ability to do this, so you won't find this functionality in MailKit.

> Filter, filter is to allow passage of something or disallow passage of something, So I want to make filtering capababilities through IMAP by manipulating some configuration from the .NET client I'm seeking to develop (like adding the keywords, specify which keywords gets allowed, which keywords doesn't and etc).

Again, IMAP doesn't really have a filtering feature to "allow" or "disallow" messages that match any particular rule-set. This is something you'll have to implement yourself by taking advantage of IMAP's SEARCH commands and/or by fetching summary information about messages and doing your own "search" locally in your code.

Examples:

```csharp
using (var client = new ImapClient ()) {
    client.Connect ("imap.server.com", 993, SecureSOcketOptions.SslOnConnect);
    client.Authenticate ("username", "password");

    // In order to list the folders in the personal namespace, we first must get
    // the personal namespace folder:
    var personalNamespace = client.PersonalNamespaces[0];
    var personalNamespaceFolder = client.GetFolder (personalNamespace);

    // Get the Archived folder, which we are pretending (for this example) exists inside the personal namespace folder:
    var archived = personalNamespaceFolder.GetFolder ("Archived");

    // Open the INBOX folder
    client.Inbox.Open (FolderAccess.ReadWrite);

    IList<UniqueId> uids;

    if (useServerSideSearch) {
        // Search for messages with a Subject header containing the word "google", or "friends" or "godaddy"
        // using the IMAP SEARCH command:
        var query = SearchQuery.Or (SearchQuery.SubjectContains ("google"), SearchQuery.SubjectContains ("friends"), SearchQuery.SubjectContains ("godaddy"));
        uids = client.Inbox.Search (query);
    } else {
        // Notes:
        // 1. We query for UniqueId because UIDs won't change out from under us while we're doing this operation.
        // 2. We query for Envelope data because that will provide us with the IMessageSummary.Envelope properties which
        //     contain the basic headers such as Sender, From, Reply-To, To, Cc, Bcc, Subject, Date, Message-ID, and In-Reply-To
        //     headers.
        var request = new FetchRequest (MessageSummaryItems.UniqueId | MessageSummaryItems.Envelope);
        var summaries = client.Inbox.Fetch (0, -1, request);

        // create a new UID list (could also use new List<UniqueId> () but UniqueIdSet is more memory efficient)
        uids = new UniqueIdSet (SortOrder.Ascending);

        foreach (var summary in summaries) {
            var subject = summary.Envelope.Subject;
            if (subject.Contains ("google") || subject.Contains ("friends") || subject.Contains ("godaddy"))
                uids.Add (summary.UniqueId);
        }
    }

    // If you want, you can now download each of the messages that match the search criteria:
    foreach (var uid in uids) {
        var message = client.Inbox.GetMessage (uid);
    }

    // ...Or you can move the messages to an Archived folder:
    client.Inbox.MoveTo (uids, archived);
    
    // Disconnect
    client.Disconnect (true);
}
```

**Comment by jstedfast** [comment]
BTW, I am willing to offer consultation services for my going rate of $500/hr.

I suspect you'll need help.

**Comment by MyInviteacc** [comment]
Thanks once more for your thorough answer my freind.
So for most part, This library doesn't have what i'm looking for. Does this mean what I'm looking for is not possible through an application built with C# or in general with IMAP ?
Also I saw the IMAP part on the API reference, but I was talking about the guides 😂
Thanks for the offer, I will look into it and hopefully use it.

**Comment by jstedfast** [comment]
> So for most part, This library doesn't have what i'm looking for. Does this mean what I'm looking for is not possible through an application built with C# or in general with IMAP ?

Depends on which part you are asking about.

If you are asking if it's even possible to implement a general-purpose program to slow down the transmission of an email message not sent by you in order to block it from arriving at a random IMAP server, then probably not.

If this is for a very specific IMAP server that either has this feature (which would be non-standard if it did) or a very specific server that you have full control over, then yes, I suppose that it's possible...? Whether you could do it in C# or not would depend on how you were able to implement this. If you have to write a plugin for a specific IMAP server, you'll likely be limited to whatever language(s) it supports for its plugins.

"Filtering" itself could be done via C# by building on top of MailKit, but like I said, it'll be a non-trivial task because you'll have to develop your own filtering language, a parser for that language, an evaluator for that language and then map expressions in that language to the appropriate IMAP SEARCH function and/or some sort of client-side search (which may involve downloading summary information like in my example code snippet or possibly even downloading the main body of the message or perhaps even downloading the whole message to do a fully controlled search).

As I showed you, I've implemented this kind of thing before ~20+ years ago back when I was a relative newbie software developer (hadn't even finished college). And I wrote it in C of all languages. C# would be a lot easier, especially given something like MailKit be available to build on top of rather than having to implement my own IMAP client code from the ground up.

My co-worker and I even implemented a "Stop Processing" filter action which you can find in camel-filter-driver.c.

**Comment by MyInviteacc** [comment]
Hello, Sorry for taking long time to response but I have been searching more and also grabbing better information from the client..
Currently, I will try to explain in brief but with detaisl:
- The client has IMAP server (with his login access etc.)
- He wants to control the messages that gets delivered to emails under his IMAP (by the ways I mentioned above)
- So it is not like viewing the emails on a C# client, no. He wants a GUI - like the one i showed above - to control the IMAP which in turn will control the messages downloaded by any client (gmail,hotmail,outlook, etc...) to his needs.
I know it may sound a bit complicated but unfortunately the PHP solution that we had (the GUI in picture) doesn't work 100%
@jstedfast  thanks in advance.

**Comment by MyInviteacc** [comment]
> ![image](https://user-images.githubusercontent.com/138369501/268355169-56d3f1e8-3ba2-46bb-a06b-c375f9115c56.png) The configuration from the old program that i'm willing to recreate.

[ven.php.txt](https://github.com/jstedfast/MailKit/files/12701987/ven.php.txt)
Please if you can give any help/guidance about what is going on here, it would be super awesome.
Note: the file is a php code but converted into .txt file because github doesn't allow uploading php files (due to security i guess)

**Comment by jstedfast** [comment]
This is far outside the scope of MailKit so I really feel like I should be getting a consulting fee, here.

**Comment by xx7Ahmed7xx** [comment]
I'm also looking for same solution for issue that is similar to this one, Which I'm trying to solve.
If you can help me or just guide me as little as possible (like a stepping stone) It would be really great, I'm a just starting developer.
