### ISSUE TITLE
Is this the correct way to combine 4 SearchQuery in AND?

### ISSUE THREAD

**Issue by pralinoid** [jstedfast/MailKit#1644]
Is this the correct way to combine 4 SearchQuery in AND?

`SearchQuery.FromContains("sender").And(SearchQuery.SubjectContains("subject")).And(SearchQuery.SentSince(dateFrom)).And(SearchQuery.SentBefore(dateTo))`

Or is this other way the correct one?

```
SearchQuery.And
(
    SearchQuery.FromContains("sender"),
    SearchQuery.And
    (
        SearchQuery.SubjectContains("subject"),
        SearchQuery.And
        (
            SearchQuery.SentSince(dateFrom),
            SearchQuery.SentBefore(dateTo)
        )
    )
);
```

**Comment by jstedfast** [comment]
They both do the same thing. Both are correct. They will both produce exactly the same tree structure.
