### ISSUE TITLE
Receiving SSL Errors after connecting 100's ImapClients at the same time imap.gmail.com

### ISSUE THREAD

**Issue by GameHackerPM** [jstedfast/MailKit#1645]
**Describe the bug**

We have been using it for so long like couple of years was working fine, but over the time we are adding more gmail accounts to be connected and monitored for emails, recently we reached 153 ImapClients, we figured that it connect only to the first 100, then the rest gets error like this: **(Please check below "Exception" title).**

The reason we are connecting to 153 ImapClients, they are all only 53 accounts, but for each folder we need to monitor we have created a ImapClient for it in IdleClient so we monitor any emails comes out in that folder/label only.

**Platform**
 - OS: Windows
 - .NET Runtime: 6.0
 - .NET Framework: ASP.Net Core
 - MailKit Version: 4.2.0

**Exception**
```text
Error An error occurred while attempting to establish an SSL or TLS connection.

This usually means that the SSL certificate presented by the server is not trusted by the system for one or more of the following reasons:
1. The server is using a self-signed certificate which cannot be verified.
2. The local system is missing a Root or Intermediate certificate needed to verify the server's certificate.
3. A Certificate Authority CRL server for one or more of the certificates in the chain is temporarily unavailable.
4. The certificate presented by the server is expired or invalid.
5. The set of SSL/TLS protocols supported by the client and server do not match.
6. You are trying to connect to a port which does not support SSL/TLS.
See https://github.com/jstedfast/MailKit/blob/master/FAQ.md#ssl-handshake-exception for possible solutions.

at MailKit.Net.Imap.ImapClient.ConnectAsync(String host, Int32 port, SecureSocketOptions options, CancellationToken cancellationToken)\r\n   at BusinessLayer.IdleClient.ReconnectAsync() in WebSiteCore\\BusinessLayer\\IdleClient.cs:line 68
  at BusinessLayer.IdleClient.RunAsync() in WebSiteCore\\BusinessLayer\\IdleClient.cs:line 345
   at BusinessLayer.GlobalVariables.<>c__DisplayClass26_0.<<EmailGrabberControl>b__0>d.MoveNext() in WebSiteCore\\BusinessLayer\\GlobalVariables.cs:line 405
```

**To Reproduce**
1. Create 150+ ImapClient and connect to them.
2. I don't think you need to auth the accounts, just creating 150+ ImapClient and try to connect to imap.gmail.com port 993 SSL Enabled.

**Expected behavior**
It should work fine, but it gets ssl error above.

**Code Snippets**

Using "IdleClient"..
```csharp
 async Task ReconnectAsync()
 {
     client.CheckCertificateRevocation = false;
     if (!client.IsConnected)
         await client.ConnectAsync("imap.gmail.com", 993, SecureSocketOptions.Auto, cancel.Token);
     

     if (!client.IsAuthenticated)
     {
         await client.AuthenticateAsync(userName, password, cancel.Token); 

         mailFolder = await client.GetFolderAsync(folderName);
         await mailFolder.OpenAsync(FolderAccess.ReadWrite, cancel.Token);
         if (LastUniqueId == null)
             LastUniqueId = mailFolder.UidNext;
     }
 }
```

**Protocol Logs**
We tried to capture the logs using this code:
```csharp
// log to a file called 'imap.log'
var client = new ImapClient (new ProtocolLogger ("imap.log"));
```
But it always create the file only doesn't write anything into it.

**Additional context**
Please feel free to ask for any missing info or if you can advice us for a better way to monitor these folders/labels over a huge amount of accounts like 50-100 accounts.

**Comment by GameHackerPM** [comment]
Ok I just tested what you say with this code: 

```csharp

```

On my local machine, it works fine and connected with more than 150+ connections, but on the server I can see it gets this exception:

```text
Error Unable to read data from the transport connection: An established connection was aborted by the software in your host machine..    at System.Net.Security.SslStream.<FillHandshakeBufferAsync>g__InternalFillHandshakeBufferAsync|189_0[TIOAdapter](TIOAdapter adap, ValueTask`1 task, Int32 minSize)
  at System.Net.Security.SslStream.ReceiveBlobAsync[TIOAdapter](TIOAdapter adapter)
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)\r\n   at BusinessLayer.GlobalVariables.<>c__DisplayClass26_0.<<EmailGrabberControl>b__0>d.MoveNext() in G:\\TFS\\RichardToolsWebSiteCore\\BusinessLayer\\GlobalVariables.cs:line 491
```
So I think it's something from the host capping my connections to 100 or something like that as it's being aborted from their side anyway! Please correct me if I'm wrong..

Also is there a better way not to create a new ImapClient for each Folder/Label and combine these folders monitoring in one Client so we will need to create only 1 Client per account? That would be helpful I believe.

Thanks again.

**Comment by jstedfast** [comment]
If GMail supports the LIST-STATUS extension (`client.Capabilities.HasFlag(ImapCapabilities.ListStatus)`), then you can call `GetSubfolders(StatusItems.Unread | StatusItems.Count)` on the "[Gmail]" folder, for example, and it will update the Count and Unread count for each folder.

Even if it doesn't support that feature, you can still call GetSubfolders() and MailKit will issue the appropriate STATUS commands for each subfolder for you as a work-around.

Just do that every few minutes or whatever and most users won't notice that things aren't updated "instantly".
