### ISSUE TITLE
IsAttachment ContentDisposition always null

### ISSUE THREAD

**Issue by silaing** [jstedfast/MailKit#165]
Hi
I'm using the following code to ascertain if messages contain an attachment:

...
if (bodyMultiPart != null) {
   foreach (var bodyPart in bodyMultiPart.BodyParts.Where(x => x is BodyPartBasic)) {
      BodyPartBasic basicPart = bodyPart as BodyPartBasic;
      if (basicPart.ContentDisposition != null && basicPart.ContentDisposition.IsAttachment) {
         return true;
      }
   }
}

The ContentDisposition always seems to equate to null with or without attachments and the IsAttachment property is always false. However, referencing a message with a pdf attachment produces:

-		ContentDisposition	null	MimeKit.ContentDisposition
-		Static members		
		Attachment	"attachment"	string
		FormData	"form-data"	string
+		icase	null	System.StringComparer
		Inline	"inline"	string

+		[1]	{("APPLICATION" "PDF" ("NAME" "PP-15-03.pdf") NIL NIL "BASE64" 6037170 NIL NIL NIL NIL)}	MailKit.BodyPart {MailKit.BodyPartBasic}

It may be my Server, however, I've queried it using a different IMAP client, which picked up the presence of the attachments accurately. Any idea what's happening?

thank you

**Comment by jstedfast** [comment]
In our query, are you using MessageSummaryItem.Body or MessageSummaryItem.BodyStructure? You need the second one to get the ContentDisposition field.

**Comment by silaing** [comment]
That was quick, thanks.

Yes, I think that's solved my problem. I had MessageSummaryItems.All in my Fetch command, but adding MessageSummaryItems.BodyStructure makes it work.

**Comment by jstedfast** [comment]
Yea, MessageSummaryItem.All only has Body and not BodyStructure. The All alias is the same as the ALL alias in IMAP, but it's not very appropriately named :-(

**Comment by patbush** [comment]
Hi, 
I'm using below code to fetch messages:
```
inbox.Fetch(uids, MessageSummaryItems.UniqueId | MessageSummaryItems.Full | MessageSummaryItems.BodyStructure);
```
when message consist of text and attachment, then:
```
var multipart = message.Body as BodyPartMultipart;
foreach (var attachment in multipart.BodyParts.OfType<BodyPartBasic>().Where(x => x.IsAttachment)
{
// attachment.ContentDisposition is not null
}
```
but when message consist of only attachment, then:
```
var basicpart = message.Body as BodyPartBasic;
if (basicpart != null && basicpart.IsAttachment)
{
// basicpart.ContentDisposition always is null
}
```

Any idea why basicpart contains null for ContentDisposition?

**Comment by jstedfast** [comment]
@patbrush are you sure? This is the IsAttachment logic: https://github.com/jstedfast/MailKit/blob/master/MailKit/BodyPartBasic.cs#L160

There's no way that ContentDisposition can be null if IsAttachment is true.

**Comment by patbush** [comment]
Sorry, I made mistake in example, correct example looks like that:
```
var basicpart = message.Body as BodyPartBasic;
if (basicpart != null && basicpart.IsAttachment)
{
// this part never execute because basicpart.ContentDisposition always is null
}
```

**Comment by jstedfast** [comment]
@patbush Ah, okay, that makes more sense. Well, what that means is that there is no Content-Disposition header which means that the IsAttachment property will be false.
