### ISSUE TITLE
Questions to Pop3Client.DeleteMessage

### ISSUE THREAD

**Issue by AdvancedNotifier** [jstedfast/MailKit#1650]
If I delete a message with `Pop3Client.DeleteMessage`, the message should be marked for deletion, if I'm right.

After this, `Pop3Client.GetMessageCount` still counts this message furthermore. But if I try to receive them again with `Pop3Client.GetMessageHeaders` (with `IList<int>), I can't receive them.

My questions:

- Why will the message be countered furthermore, but I can't get it?
- Is there a way to delete the message completely (immediately) without disconnecting?

PS
Thanks a lot for your great support.

**Comment by jstedfast** [comment]
> Why will the message be countered furthermore, but I can't get it?

That's just the way the POP3 protocol was designed.

> Is there a way to delete the message completely (immediately) without disconnecting?

Unfortunately, no. Again, this is just how the POP3 protocol was designed.
