### ISSUE TITLE
Disposing of resources

### ISSUE THREAD

**Issue by Bykiev** [jstedfast/MailKit#1659]
Hi, in Imap [sample](https://github.com/jstedfast/MailKit#using-imap) you're not disposing `GetMessage` result, is it ok? Also do I need to manually dispose the message parts, like body and attachments or it will be disposed automatically?

**Comment by jstedfast** [comment]
Yes, the sample should probably dispose of the message when it is done with it.

MimeMessage.Dispose() disposes of *all* streams, etc. You do not need to recursively dispose the attachments and other MIME parts contained within the message.

**Comment by Bykiev** [comment]
Thank you!
