### ISSUE TITLE
Unexpected token in IMAP response: '('

### ISSUE THREAD

**Issue by jacargentina** [jstedfast/MailKit#166]
Doing this on a given folder with latest 1.0.13.0

    var changes = folder.Search(MailKit.Search.SearchQuery.ChangedSince(this.HighestModSeq));

Logs this:

    S: M00000006 OK Completed
    C: M00000007 UID SEARCH RETURN () MODSEQ 46538
    S: * SEARCH 56753 (MODSEQ 46539)
    S: M00000007 OK Completed (1 msgs in 0.004 secs)

And i get an exception like this:

    MailKit.Net.Imap.ImapProtocolException: Unexpected token in IMAP response: '('
    en MailKit.Net.Imap.ImapFolder.SearchMatches(ImapEngine engine, ImapCommand ic, Int32 index)
    en MailKit.Net.Imap.ImapEngine.ProcessUntaggedResponse(CancellationToken cancellationToken)
    en MailKit.Net.Imap.ImapCommand.Step()
    en MailKit.Net.Imap.ImapEngine.Iterate()
    en MailKit.Net.Imap.ImapEngine.Wait(ImapCommand ic)
    en MailKit.Net.Imap.ImapFolder.Search(SearchQuery query, CancellationToken cancellationToken)

I think the parser is not expecting the **(MODSEQ 46539)** part.

Using cyrus-imapd-2.4.17-8.fc21.x86_64

**Comment by jacargentina** [comment]
Maybe mailkit is not implementing the protocol as it should?

https://tools.ietf.org/html/rfc4551#section-3.5

> If a client specifies a MODSEQ criterion in a SEARCH (or UID SEARCH)
> command and the server returns a non-empty SEARCH result, the server
> MUST also append (to the end of the untagged SEARCH response) the
> highest mod-sequence for all messages being returned.  See Section
> 3.4 for examples.

**Comment by jstedfast** [comment]
Thanks, I've just committed a fix for this.

**Comment by jstedfast** [comment]
@jacargentina would you be willing to get me the initial few lines of a log when connecting to Cyrus IMAP? I mostly care about the greeting, but if you could include the CAPABILITIES as well, that would be awesome. Thanks!
