### ISSUE TITLE
how to get the index of message with unique id of imap

### ISSUE THREAD

**Issue by AlexGeller** [jstedfast/MailKit#1663]
**Is your feature request related to a problem? Please describe.**
first of all, i want to fetch all message by paging use imap, so i can get a unique id from first page, but when i want to read the second page, there maybe some message deleted, so i have to turn the unique id to message index, so that i can fetch the second page from this index.

**Describe the solution you'd like**
now i have use this code to get the index of message with unique id.

IList<IMessageSummary> lastMsg = inbox.Fetch(new List<UniqueId> { new UniqueId(lastUID) }, MessageSummaryItems.UniqueId);

and get the index like this.

lastMsg[0].Index

**Describe alternatives you've considered**
i just want to want that if there have a method to get index directly.

**Additional context**

**Comment by jstedfast** [comment]
That's the only way
