### ISSUE TITLE
bc-sharp repo is not public

### ISSUE THREAD

**Issue by jacargentina** [jstedfast/MailKit#167]
The building instructions from Mailkit README.md says

git clone https://github.com/jstedfast/bc-csharp.git

When i try to do that, i'm asked User & Password.

**Comment by jstedfast** [comment]
I don't have any private repositories, so it has to be public.

You probably just need to give it your own login/password. How did you clone MimeKit and MailKit? Just use the same technique for bc-csharp.

**Comment by jacargentina** [comment]
Mmmmm, now it worked.... strange

**Comment by jstedfast** [comment]
GitHub is being DoS'd, so maybe that was the problem?
