### ISSUE TITLE
Problem with saving edited message using IMAP

### ISSUE THREAD

**Issue by xx7Ahmed7xx** [jstedfast/MailKit#1677]
I have successfully edited my message body, created a new message object and append it to the ImapClient.Inbox folder.
However, if I just delete the message without using the ImapClient.Inbox.Append() method, the message will disappear from the inbox and get deleted permanentally.
But, when I execute the append command, the message appear back to the inbox as a thread (or related message) and the edited message appear as a new message under it.
![image](https://github.com/jstedfast/MailKit/assets/36636484/dd49657e-9638-4d9a-a6ba-502d25104375)
Here is the code to do so:
```
client.Connect("server", 993, true);
client.Authenticate("email", "pass");
client.Inbox.Open(FolderAccess.ReadWrite);

var message = client.Inbox.GetMessage(UniqueId);
ReplaceTextPart(message.Body, "New Text here");

client.Inbox.AddFlags(UniqueId,MessageFlags.Deleted, true);
client.Inbox.Expunge();
if (client.Capabilities.HasFlag(ImapCapabilities.UidPlus))
{
    client.Inbox.Expunge(
        new UniqueId[] { UniqueId });
}
client.Disconnect(true);

client.Connect("server", 993, true);
client.Authenticate("email", "pass");
client.Inbox.Open(FolderAccess.ReadWrite);

var newMessage = new MimeMessage();
newMessage.Subject = message.Subject;
newMessage.Body = message.Body;
newMessage.Sender = message.Sender;
newMessage.Date = message.Date - TimeSpan.FromSeconds(1);
newMessage.From.AddRange(message.From);
newMessage.To.AddRange(message.To);
newMessage.Cc.AddRange(message.Cc);
newMessage.MessageId = MimeUtils.GenerateMessageId();
newMessage.InReplyTo = null;
foreach (var attachment in message.Attachments)
{
    newMessage.Attachments.Append(attachment);
}


client.Inbox.Append(newMessage);
client.Disconnect(true);
```

You can see I made it disconnect and reconnecct so while debugging i could see the behavior described.
@jstedfast please help with this one or anyone who have done something similar before..

**Comment by jstedfast** [comment]
Is this GMail? If so, once you add the Deleted flag, GMail moves the message to the Trash folder so `client.Inbox.Expunge(...)` won't do anything.

(Note: unless you change GMail's user Settings to make it behave like a normal IMAP server).

**Comment by xx7Ahmed7xx** [comment]
Yes this is gmail, the client i'm developing will be used for alot of IMAPs
What are your suggestions?

**Comment by jstedfast** [comment]
I don't know what can be done. You'll have to experiment. Maybe you can expunge the Trash folder.

**Comment by jstedfast** [comment]
Does GMail support `ImapCapabilities.Replace`? If so, you can use client.Inbox.Replace() methods.

**Comment by xx7Ahmed7xx** [comment]
What is `IReplaceRequest` ? How to use this inside this method?

**Comment by xx7Ahmed7xx** [comment]
I tried it and it does nothing, either with a MimeMessage or a ReplaceRequest..
Maybe if you know an existing solution or someone who have done this before so I could investigate further?

**Comment by jstedfast** [comment]
I don't know if anyone trying to do what you are trying to do.

**Comment by jstedfast** [comment]
Instead of deleting the message on GMail, move it to the Trash folder (which will return the uid of the message as it will be in the Trash folder). Then open the Trash folder and expunge that uid.

In other words:

```csharp
var trash = client.GetFolder (SpecialFolder.Trash);
var trashUid = client.Inbox.MoveTo(uid, trash);
trash.Open(FolderAccess.ReadWrite);
trash.Expunge(new UniqueId[] { trashUid });
```

**Comment by jstedfast** [comment]
Sounds like it's just a feature of GMail then.

What you are trying to do is very non-standard behavior outside of Draft messages saved in the Drafts folder.

**Comment by xx7Ahmed7xx** [comment]
So other IMAPs will work as expected using the whole code discussed here?

**Comment by jstedfast** [comment]
Yes
