### ISSUE TITLE
Consider removing BouncyCastle in latest versions of .net and use .net native libraries for crypto

### ISSUE THREAD

**Issue by nlionis-eg** [jstedfast/MailKit#1689]
There is always a problem with different libraries using different versions of BouncyCastle that ends in versions mismatches.

Consider removing BouncyCastle in latest versions of .net (.net6 .net8 etc) and use .net native libraries for crypto

**Comment by jstedfast** [comment]
Even the latest versions of dotnet don't have all of the crypto needed.
