### ISSUE TITLE
ServerCertificateValidationCallback called with SslStream as sender

### ISSUE THREAD

**Issue by jeff7091** [jstedfast/MailKit#169]
This code ends up passing a SslStream object as the sender. 
```
static bool ValidateRemoteCertificate (object sender, X509Certificate certificate, X509Chain chain, SslPolicyErrors errors)
		{
			if (ServicePointManager.ServerCertificateValidationCallback != null)
				return ServicePointManager.ServerCertificateValidationCallback (sender, certificate, chain, errors);

			return true;
		}
```
However RemoteCertificateValidationCallback is not the same animal as ServerCertificateValidationCallback. From https://msdn.microsoft.com/en-us/library/system.net.servicepointmanager.servercertificatevalidationcallback%28v=vs.110%29.aspx

"When doing custom validation, the sender parameter passed to the RemoteCertificateValidationCallback can be a host string name or an object derived from WebRequest (HttpWebRequest, for example) depending on the CertificatePolicy property."

**Comment by jstedfast** [comment]
Thanks. I've also taken the liberty to add a callback property to each *Client class to allow non-global overrides.

**Comment by jeff7091** [comment]
Hey Jeff - I'm happy to fix what I find, but I just want your take on it
1st. Do feel like *you* have to fix it if you don't want to - Jeff

**Comment by jstedfast** [comment]
I'll accept pull requests or I can fix these issues, it doesn't really matter either way. Bugs like this one are pretty trivial to fix :-)
