### ISSUE TITLE
Strange memory problem after calling IMailFolder.Open

### ISSUE THREAD

**Issue by Segelpapa** [jstedfast/MailKit#1692]
**Describe the bug**
I have a strange memory problems.

I have this code:

    var mailItem5 = new MailItem(0, "")
    {
        Nils = "Hallo",
        Test = "Test",
    };
    if (folder.IsOpen)
    {
        var mailItem6 = new MailItem(0, "")
        {
            Nils = "Hallo",
            Test = "Test",
        };

After calling it, mailItem5.Nils is `null`, but mailItem6.Nils is `Hallo`.

If I rename `Nils` to `A`, I don't have this problem.

I call `new MailItem` a lot of times in my project, but I have no problem anywhere else, than after calling `folder.IsOpen`.

Indeed, these are very little information for you to, I know.

But at the moment, I don't have an idea, now I can hunt this problem furthermore. Do have an idea?
 
**Platform (please complete the following information):**
 - OS: Microsoft Windows NT 10.0.19045.0
 - .NET Runtime: .NET 8.0.1
 - .NET Framework: .NET Framework 4.8.09037
 - MailKit Version: Nuget Package 4.3.0

**Exception**
No exception

**To Reproduce**
... running my app.

If you want, I can send it to you, but it has about 60,000 lines of code.

**Protocol Logs**
I don't believe, this these last lines are interested for you:
    C: A00000007 FETCH 1:101 (UID FLAGS BODYSTRUCTURE X-GM-MSGID)
    S: * 1 FETCH (X-GM-MSGID 1788879945269525946 UID 3533 MODSEQ (568225) FLAGS (\Seen) BODYSTRUCTURE ("TEXT" "HTML" ("CHARSET" "utf-8") NIL NIL "BASE64" 23880 478 NIL NIL NIL))
    S: * 2 FETCH (X-GM-MSGID 1788881413359928556 UID 3534 MODSEQ (568676) FLAGS (\Flagged \Seen) BODYSTRUCTURE ("TEXT" "HTML" ("CHARSET" "utf-8") NIL NIL "BASE64" 12128 243 NIL NIL NIL))
    S: * 3 FETCH (X-GM-MSGID 1788881414021207184 UID 3535 MODSEQ (568628) FLAGS (\Seen) BODYSTRUCTURE ("TEXT" "HTML" ("CHARSET" "utf-8") NIL NIL "BASE64" 20392 408 NIL NIL NIL))
    S: * 4 FETCH (X-GM-MSGID 1788881472065481562 UID 3536 MODSEQ (568895) FLAGS (\Flagged \Seen) BODYSTRUCTURE ("TEXT" "HTML" ("CHARSET" "utf-8") NIL NIL "BASE64" 12128 243 NIL NIL NIL))
    S: * 5 FETCH (X-GM-MSGID 1788881472441851301 UID 3537 MODSEQ (568731) FLAGS (\Seen) BODYSTRUCTURE ("TEXT" "HTML" ("CHARSET" "utf-8") NIL NIL "BASE64" 20392 408 NIL NIL NIL))
    S: * 6 FETCH (X-GM-MSGID 1788888487919972441 UID 3538 MODSEQ (568838) FLAGS (\Seen) BODYSTRUCTURE ("TEXT" "HTML" ("CHARSET" "utf-8") NIL NIL "BASE64" 23368 468 NIL NIL NIL))
    S: * 7 FETCH (X-GM-MSGID 1788990424369813442 UID 3558 MODSEQ (571799) FLAGS (\Seen) BODYSTRUCTURE ("TEXT" "HTML" ("CHARSET" "utf-8") NIL NIL "BASE64" 26020 521 NIL NIL NIL))
    S: A00000007 OK Success

**Comment by jstedfast** [comment]
MailItem isn't even a MailKit type.

Make sure you are debugging unoptimized code, or it can have odd behavior.

If that's not the problem, then this is 100% a bug in the dotnet runtime or whatever library MailItem is from.
