### ISSUE TITLE
Done token won't cancel IMap IdleAsync

### ISSUE THREAD

**Issue by szguoxz** [jstedfast/MailKit#1697]
When donetoken is expired,  the idleasync won't exit for my Gmail IMap connection.
I monitored the protocol log, 
S: + idling
C: DONE

I can see DONE is written.

I looked into the source code, found the stream handling is weird. Maybe I don't understand the code, why is it not async stream code?
public void Write (byte[] buffer, int offset, int count, CancellationToken cancellationToken)
This function seems way tom complicated for a normal async stream, but again, maybe there is a reason.

Anyway, This happens to me all the time. It worked for a while, then happens again.
By the way, I am monitoring a couple gmail accounts at the same time, not sure if that  means anything.

I've also noticed, I set the done token to cancel in 5 minutes, it actually got canceled after 21 minutes.

Anyway, this is way too weird. And it works if I cancel the done token myself. But it won't work if the done token cancels itself.

**Comment by jstedfast** [comment]
If the `C: DONE\r\n` text is in the log, it *should* mean that the DONE command was flushed through the socket layer.

That would suggest that the ImapClient is stuck waiting for a response from the server.

The way to check this would be to download a program such as [wireshark](https://www.wireshark.org/) to sniff the TCP/IP packets between your machine and the server to see what has been sent/received.

**Comment by szguoxz** [comment]
I think I know what is going on now. It's GMAIL pulling the shit.
Basically GMAIL decide not to comply with the protocol. DONE command will or will not cancel the idle will depend on how GMAIL feels.

My observation is : When my done token cancels and send the DONE command, GMAIL ignores it (sometimes hornor it).  Then if a new message arrives, it will honor the DONE command.

I guess GMAIL thinks I cancel too early, which is a waste of its resource, force me to stay up to the last minute. Either reaches the maximum waiting period, or something happened with the inbox.

It works for me, actually better, as I am tired to guess when GMAIL will disconnect me. Now I just wait for it to disconnect me, or if a new email comes in, I can cancel the idle and start to process it right away.

By the way, I never touch the cancellation token, as that means I want to stop the operation.

**Comment by szguoxz** [comment]
> I'm guessing you were looking at ImapStream.Write (byte[] buffer, int offset, int count, CancellationToken cancellationToken) and yes, it's a little complicated, but not too bad.

When code gets this complicated, there tends to be a bug. When  I see the code, I was surprised. As CancellationToken usually only used in Async Task system. And your code is a sync stream.

You said it might hang some time. Is it possible that the code is way too old, and dotnet has changed its way of handling things? I am just saying! :-) I just feel the code does not comply with the latest best practice of DOTNET async idiom.

**Comment by szguoxz** [comment]
Now I believe it's a bug, it hangs. I need to find out a way to fix this. This is ODD.

**Comment by jstedfast** [comment]
When it hangs, what are the values of the Send/ReceiveTimeout properties of the underlying Socket?

And is it hanging in ImapStream.ReadAhead?

Are you using ImapClient.Idle()? Or ImapClient.IdleAsync()?

2 minutes is the default timeout for network sockets on most systems, so it sounds suspicious.

In ImapCommand.Step/Async(), there is code that sets the timeout to infinity when idling.

I suspect that might not be working for you for some reason.

**Comment by szguoxz** [comment]
I didn't go into that deep. But here are some information:
1. I use IdleAsync
2. It works for 2 minutes, 3 minutes, 4 minutes, but not 5 minutes.
3. When I set it to 4 or less minutes, I can see that we send the done command when the token expires, and it exits, every works as expected.
4. when it hangs, it eventually will be disconnected after 20, 30 or 40 minutes.
Right now, I set it to 4 minutes, the longest time possible. And it works beautifully.

on a side note:
I have this event attahced to inbox:
client.Inbox.CountChanged += (x, y) => { hasnewmessage = true; doneidle.cancel(); }

My question is: if I detect the client got disconnected, and I reconnect it immediately. Now, do I need to reattach the event? I mean, will the inbox folder got reinitialized?

My code is quite simple, I will paste it here:
<code>
	CancellationTokenSource doneidle = new();
		bool hasnewmessage = false;
		await ReconnectAsync();
		client.Inbox.CountChanged += (x, y) => {
			hasnewmessage = true;
			doneidle.Cancel();
			logger.Info($"new email arrived for {email}");
		};

		while (!cts.IsCancellationRequested)
			try
			{
				await ReconnectAsync();
				if (hasnewmessage && await ProcessMessageAsync() > 0) continue;
				logger.Info($"start idle now {email}");
				doneidle = new CancellationTokenSource(TimeSpan.FromMinutes(4));
				hasnewmessage = false;
				await client.IdleAsync(doneidle.Token, cts.Token);
				logger.Info($"done idle {email}");
			}
			catch (ImapProtocolException ex) {}
			catch (IOException ex) {}
			catch (OperationCanceledException ex)
			{
				break;
			}
			catch (Exception e)
			{
				logger.Error($"something went wrong {email}", e);
				break;
			}
</code>

Thanks,

**Comment by jstedfast** [comment]
You will not need to reattach event handlers unless you connect to a different server.

**Comment by jstedfast** [comment]
Oh, I see the problem.

```csharp
client.Inbox.CountChanged += (x, y) => { hasnewmessage = true; doneidle.cancel(); }
```

The problem is that that code only captures the `doneidle` instance that is live when that delegate is created. Once it gets cancelled, it's done.

You shouldn't use a delegate like this. You should provide an actual method handler.

**Comment by szguoxz** [comment]
That's not the case. I recreated the instance every time when I started to idleasync.
It captures the reference to  doneidle. I have been using .net for over 20 years, I was careful. :-)

**Comment by szguoxz** [comment]
Besides, I works fine when I set it to 4 minutes.
