### ISSUE TITLE
Sending MimeMessage using Mircosoft Graph

### ISSUE THREAD

**Issue by dgxhubbard** [jstedfast/MailKit#1702]
Does MailKit have a supported way of converting MimeMessage to the JSON expected
by Microsoft Graph?

SmtpClient used to work on outlook 365, but now fails. So with this [article](https://www.linkedin.com/pulse/sending-smtp-email-microsoft-graph-oauth-using-vbnet-elie-karkafy/)
we can send a simple json formatted message. We use MailKit and MimeMessage in a lot of places in our code but I don't see a simple way to convert MimeMessage to the JSON expected by graph.

Does this feature exist now or can it be added?

**Comment by jstedfast** [comment]
It looks to me like you can [send in MIME format](https://learn.microsoft.com/en-us/graph/outlook-send-mime-message) and that's what I'd recommend doing.

The problem with trying to serialize MIME to JSON is that the Outlook JSON message format is not likely to be the same as the JMAP JSON message format (JMAP is a newer standard that is more-or-less a replacement for IMAP based on JSON & HTTP REST).

And then there's Google's JSON message format as well for GMail.

And I'd bet my life on them all being different.
