### ISSUE TITLE
Recommendations for fatching and processing large amounts of emails

### ISSUE THREAD

**Issue by vinaykarora** [jstedfast/MailKit#1705]
To read 31,000 emails from Gmail efficiently using C# concurrency programming, we can leverage asynchronous programming along with parallel processing to improve performance. Here's how I can achieve this using async/await and parallel processing:

 - OS: Windows
 - .NET Runtime: CoreCLR
 - .NET Framework: .Net 8
 - MailKit Version: 4.3.0

**Exception**
System.InvalidOperationException
  HResult=0x80131509
  Message=The ImapClient is currently busy processing a command in another thread. Lock the SyncRoot property to properly synchronize your threads.

If I use lock on SyncRoot of client and folder, I'm still facing this issue.

`
lock (client.SyncRoot)
{
    return folder.GetMessageAsync(uid);
}
`

```
`using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using MailKit;
using MailKit.Net.Imap;
using MimeKit;

public class Program
{
    public static async Task<List<MimeMessage>> ReadEmailsConcurrentlyAsync(string host, int port, string username, string password, int batchSize)
    {
        var allMessages = new List<MimeMessage>();

        using (var client = new ImapClient())
        {
            await client.ConnectAsync(host, port, true);
            await client.AuthenticateAsync(username, password);

            var inbox = client.Inbox;
            inbox.Open(FolderAccess.ReadOnly);

            var totalMessages = inbox.Count;
            var batchCount = (totalMessages + batchSize - 1) / batchSize;

            var options = new ParallelOptions
            {
                MaxDegreeOfParallelism = Environment.ProcessorCount // Adjust as needed
            };

            await Task.Run(() => Parallel.For(0, batchCount, options, async i =>
            {
                var start = i * batchSize;
                var end = Math.Min(start + batchSize - 1, totalMessages - 1);

                var uids = inbox.Search(SearchQuery.All, start, end);

                var messages = await Task.WhenAll(uids.Select(uid => inbox.GetMessageAsync(uid)));

                lock (allMessages)
                {
                    allMessages.AddRange(messages);
                }
            }));
        }

        return allMessages;
    }

    public static async Task Main(string[] args)
    {
        string host = "imap.gmail.com";
        int port = 993;
        string username = "your_email@gmail.com"; // Enter your email address
        string password = "your_password"; // Enter your email password
        int batchSize = 1000; // Adjust batch size as needed

        var allMessages = await ReadEmailsConcurrentlyAsync(host, port, username, password, batchSize);

        Console.WriteLine($"Total emails retrieved: {allMessages.Count}");

        // Process the retrieved messages
    }
}
```

**Comment by jstedfast** [comment]
You are spawning so many threads in your code to fetch messages. Your Parallel.For() spawns a new thread per batch and each of those threads spawns a thread per GetMessageAsync(). Yikes.

I suppose the ParallelOptions will limit that somewhat, but you still will get a thread per GetMessageAsync() and probably at least 2-8 threads for ParallelFor depending on what processor you have.

The issue you are having is that ImapClient is not (nor can it be) designed for concurrent access on multiple threads. Have you ever tried to use multiple threads to read/write to a System.IO.Stream? Doesn't end well, does it? That's what you are trying to do.

Each ImapClient only has 1 TCP/IP connection to the server, so if you want to parallel process this kind of operation, you'll need multiple connections (which means multiple ImapClient instances).

I'm not sure you really need that.

It should be plenty feasible to fetch the first thousand messages to quickly display to the user (and maybe that 1000 is 100 or whatever depending on some trial & error testing to see what you think is a suitable delay) and then fetching the rest incrementally in the background.

I believe that my ImapClientDemo does this. You can read the [MessageList.cs](https://github.com/jstedfast/MailKit/blob/master/samples/ImapClientDemo/ImapClientDemo/MessageList.cs) code and see how I did it for the demo.

Keep in mind I'm not a UI developer and so I'm not super proud of this code, but it works.

I'm sure you'd be able to find a better way to do it. I just hate writing Windows.Forms code and I hate writing demos, so I just wanted to get things done and working as quickly as possible.
