### ISSUE TITLE
Authentication on SMTP to Microsoft Outlook using OAuth

### ISSUE THREAD

**Issue by eitanbehar** [jstedfast/MailKit#1712]
**Describe the bug**
Getting error "Error: MailKit.Security.AuthenticationException: 535: 5.7.3 Authentication unsuccessful " when using SMTP client with OAuth credentials for Office 365
It might be a configuration issue on my side, but I wanted to confirm that this is supposed to work, and maybe there is a hint in the logs of what I am missing.

**Platform (please complete the following information):**
 - OS: MacOS
 - .NET Runtime: .NET Interactive
 - .NET Framework: .NET Interactive
 - IDE: VS Code with Polyglot Extension
 - MailKit Version: MailKit, 4.3.0,
  HttpToSocks5Proxy, 1.4.0
Microsoft.Identity.Client, 4.59.0

**Exception**
Error: MailKit.Security.AuthenticationException: 535: 5.7.3 Authentication unsuccessful [AM0PR06CA0126.eurprd06.prod.outlook.com 2024-02-14T14:50:26.590Z 08DC2D372B4C3DED]
at MailKit.Net.Smtp.SmtpClient.AuthenticateAsync(SaslMechanism mechanism, CancellationToken cancellationToken) in D:\src\MailKit\MailKit\Net\Smtp\AsyncSmtpClient.cs:line 254
at Submission#13.<SendUsingMailKitProxy>d__13.MoveNext()
--- End of stack trace from previous location ---
at Submission#13.<<Initialize>>d__0.MoveNext()
--- End of stack trace from previous location ---
at Microsoft.CodeAnalysis.Scripting.ScriptExecutionState.RunSubmissionsAsync[TResult](ImmutableArray`1 precedingExecutors, Func`2 currentExecutor, StrongBox`1 exceptionHolderOpt, Func`2 catchExceptionOpt, CancellationToken cancellationToken)

**To Reproduce**
1. Use example snippet
2. Change credentials
3. Send email

**Expected behavior**
Email sent sucessfully

**Code Snippets**
If applicable, add code snippets to help explain your problem.

```csharp
#r "nuget:MailKit"
#r "nuget:HttpToSocks5Proxy"
#r "nuget:Microsoft.Identity.Client"

// reference: https://github.com/jstedfast/MailKit/blob/master/ExchangeOAuth2.md

using MailKit.Net.Proxy;
using MailKit.Net.Smtp;
using MailKit.Security;
using System.Net.Mail;
using MimeKit;
using Microsoft.Identity.Client;  // version 4.59.0

const string proxyUrl = "squid.proxy.local";
const int squidPort = 8080;

const string toEmailAddress = "info@baconao.net";
const string fromEmailAddress =  "noreply@shr.gs"; 

const string clientId = "6825244d-384c-44f1-97a4-a0a6e284a47d";
 string clientSecret = "---removed---";
const string tenantId = "0d64f7d0-5034-49f8-9743-14b169707750";
        
string[] scopes = new string[] {
  "https://outlook.office365.com/.default",
};
        
var confidentialClientApplication = ConfidentialClientApplicationBuilder
                                    .Create(clientId)
                                    .WithClientSecret(clientSecret)
                                    .WithAuthority($"https://login.microsoftonline.com/{tenantId}/v2.0")
                                    .Build();
        
var authToken = await confidentialClientApplication
                                       .AcquireTokenForClient(scopes)
                                       .ExecuteAsync();
var oauth2 = new SaslMechanismOAuth2(fromEmailAddress, authToken.AccessToken);
        
var message = GetMimeMessage();
await SendUsingMailKitProxy();

async Task SendUsingMailKitProxy()
{
	
    var proxy = new HttpProxyClient(proxyUrl, squidPort);

    // Connect to the SMTP server via a HTTP or SOCKS proxy
    using (var client = new MailKit.Net.Smtp.SmtpClient())
    {

        client.ProxyClient = proxy;

        await client.ConnectAsync("outlook.office365.com", 587, SecureSocketOptions.Auto);
        await client.AuthenticateAsync(oauth2);
        await client.DisconnectAsync(true);

        client.Send(message);
        client.Disconnect(true);
        Console.WriteLine("Email message sent successfully.");
        Console.WriteLine("******");
          
    }
}

MimeMessage GetMimeMessage()
{
	var message = new MimeMessage();
	message.From.Add(new MailboxAddress("no-reply", fromEmailAddress));
	message.To.Add(new MailboxAddress("", toEmailAddress));
	message.Subject = $"Hello!";

	message.Body = new TextPart("plain")
	{
		Text = $"Hello, {toEmailAddress}"
	};

	return message;
}
```

**Protocol Logs**
Please include a protocol log (scrubbed of any authentication data), especially
if you got an exception such as `Syntax error in XYZ. Unexpected token: ...`.

```
Connected to smtp://outlook.office365.com:587/?starttls=when-available
S: 220 AS4P190CA0051.outlook.office365.com Microsoft ESMTP MAIL Service ready at Wed, 14 Feb 2024 15:09:53 +0000
C: EHLO VQLJ414V0M
S: 250-AS4P190CA0051.outlook.office365.com Hello [20.56.173.64]
S: 250-SIZE 157286400
S: 250-PIPELINING
S: 250-DSN
S: 250-ENHANCEDSTATUSCODES
S: 250-STARTTLS
S: 250-8BITMIME
S: 250-BINARYMIME
S: 250-CHUNKING
S: 250 SMTPUTF8
C: STARTTLS
S: 220 2.0.0 SMTP server ready
C: EHLO VQLJ414V0M
S: 250-AS4P190CA0051.outlook.office365.com Hello [20.56.173.64]
S: 250-SIZE 157286400
S: 250-PIPELINING
S: 250-DSN
S: 250-ENHANCEDSTATUSCODES
S: 250-AUTH LOGIN XOAUTH2
S: 250-8BITMIME
S: 250-BINARYMIME
S: 250-CHUNKING
S: 250 SMTPUTF8
C: AUTH XOAUTH2 ********
S: 535 5.7.3 Authentication unsuccessful [AS4P190CA0051.EURP190.PROD.OUTLOOK.COM 2024-02-14T15:10:00.397Z 08DC2D0CACA19782]
```

**Additional context**
**Configuration screenshot** 
<img width="708" alt="image" src="https://github.com/jstedfast/MailKit/assets/4739474/b4f07257-09c5-4225-a1bb-e216cd3f103f">

**Comment by jstedfast** [comment]
Yes, it is supposed to work but you aren't the first (and won't be the last) person to struggle with this.

OAUTH2 is a nightmare to get working and Office365, for whatever reason, seems to take the cake especially for the confidential-client flow. I get multiple emails, bug reports, and/or StackOverflow questions per week on this topic and I honestly have no idea how to provide a solution for people so that I can finally end the nightmare.

From a quick glance at your code, it looks like you at least followed the directions in my [ExchangeOAuth2.md](https://github.com/jstedfast/MailKit/blob/master/ExchangeOAuth2.md) documentation.

All I can suggest is reading and rereading the documentation I wrote up (which tries to simplify the process) and Microsoft's own dizzyingly (is that a word? it should be) confusing documentation to try and figure out what step you missed.

If you've got access to Microsoft Support, I'd recommend cashing in on that support contract and getting help from someone on the Office365 support team and making them earn their keep.
