### ISSUE TITLE
Way to correctly build a folder tree on cyrus & also on gmail

### ISSUE THREAD

**Issue by jacargentina** [jstedfast/MailKit#172]
I've built my email client on mailkit, developing first with cyrus imapd as the imap server.
Now i'm trying to get it working also with gmail. AFAIK my understanding of IMAP structures is my problem.

On cyrus i simply build a tree on the UI where the root of any IMAP account is:

    var root = client.Inbox;

And then it has the subfolders below with:

    var nodes_cyrus = root.GetSubfolders(...);

Now with gmail, that doesnt work. I've learn that i have to fetch all the folders available with:

    var root = client.GetFolder(client.PersonalNamespaces[0]);
    var nodes_gmail = root.GetSubfolders(...);

But here starts my confusion: this nodes_gmail CONTAINS the Inbox ??? So, any little help would be great. How can i write 1 code to rule them all (cyrus & gmail?)

**Comment by jstedfast** [comment]
Every IMAP server structures their folders differently, unfortunately.

The way to do it with every IMAP server is to use the namespace approach:

```csharp
var root = client.GetFolder (client.PersonalNamespaces[0]);
var toplevel_folders = root.GetSubfolders (...);
```

I believe that INBOX will always be included in that list. If not, you'll just have to pretend that it is there (the Inbox folder is *always* at the top-level).

Hope that helps.
