### ISSUE TITLE
Regression: Nested signed mail showed as nameless.eml

### ISSUE THREAD

**Issue by minimalisticMe** [jstedfast/MailKit#1726]
**Describe the bug**
When extracting a mail with multiple nested mails (mail attachments) I can extract all mails correctly, but one mail is named incorrectly.
One of the attached mails is a singed mail and the name of this mail is "Nameless.eml" instead of the correct name.
This was working correctly on a prior version (I am not sure which one, maybe `3.6.0`?).

**Platform (please complete the following information):**
 - OS: Windows 11
 - .NET Framework: .NET 8
 - MailKit Version: 4.4.0

**Exception**
No exception, just incorrect parsing.

**To Reproduce**
Is there a way to share the mail securely? It contains personal data of me.

**Expected behavior**
The name of the attached signed mail is read correctly.

**Code Snippets**
```csharp
var eml = MsgReader.Mime.Message.Load(stream);
foreach (var item in eml.Attachments)
{
     if (item.IsAttachment)
     {
         var originalFilename = item.FileName; // wrong in one of the attachments
     }
}
```

**Comment by jstedfast** [comment]
You can zip it up and email it to me:

jestedfa@microsoft.com

**Comment by minimalisticMe** [comment]
I just sent the mail.

**Comment by jstedfast** [comment]
Looks like this isn't a MimeKit or MailKit bug.
