### ISSUE TITLE
XLIST IMAP command being sent automatically on AuthenticateAsync

### ISSUE THREAD

**Issue by thecodrr** [jstedfast/MailKit#1728]
Here's what I am doing:

```cs
await _imapClient.ConnectAsync("imappro.zoho.com", 993, true);
await _imapClient.AuthenticateAsync("email", "password")
```

Here are the Protocol Logs:

```
Connected to imaps://imappro.zoho.com:993/
S: * OK svwall.zoho.com IMAP4 Server (Zoho Mail IMAP4rev1 Server version 1.0)
C: A00000000 CAPABILITY
S: * CAPABILITY IMAP4rev1 UNSELECT CHILDREN XLIST NAMESPACE IDLE MOVE ID AUTH=PLAIN SASL-IR UIDPLUS ESEARCH LIST-EXTENDED LIST-STATUS WITHIN LITERAL- ACL CONDSTORE
S: A00000000 OK CAPABILITY completed
C: A00000001 AUTHENTICATE PLAIN ********
S: * CAPABILITY IMAP4rev1 UNSELECT CHILDREN XLIST NAMESPACE IDLE MOVE ID AUTH=PLAIN SASL-IR UIDPLUS ESEARCH LIST-EXTENDED LIST-STATUS WITHIN LITERAL- ACL CONDSTORE
S: A00000001 OK Success
C: A00000002 NAMESPACE
S: * NAMESPACE (("" "/")) NIL NIL
S: A00000002 OK NAMESPACE completed
C: A00000003 LIST "" "INBOX" RETURN (SUBSCRIBED CHILDREN)
S: * LIST (\HasNoChildren \Subscribed) "/" "INBOX"
S: A00000003 OK Success
C: A00000004 XLIST "" "*"
S: * XLIST (\HasNoChildren \Inbox) "/" "Inbox"
S: * XLIST (\Noinferiors \Drafts) "/" "Drafts"
S: * XLIST (\Noinferiors \Templates) "/" "Templates"
S: * XLIST (\Noinferiors \Sent) "/" "Sent"
S: * XLIST (\Noinferiors \Spam) "/" "Spam"
(bunch of other XLIST commands)
S: A00000004 OK Success
```

Why is this happening? The other thing is even though the Zoho IMAP Server supports `LIST-STATUS` extension, MailKit still sends seperate `LIST` and `STATUS` commands for each folder in the namespace when I call `GetFoldersAsync`.  I have 18 folders so it sends 36 commands one after the other. Is that how its supposed to work?

**Comment by jstedfast** [comment]
The XLIST command is sent once the client is authenticated because it needs to know which folders are the Sent/Trash/Drafts/etc.

> (bunch of other XLIST commands)

Those aren't commands, those are responses. MailKit only sends 1 XLIST command in total, no matter how many folders you might have.

>  I have 18 folders so it sends 36 commands one after the other.

I suspect you are mistaking responses for commands just like you did above, but I can confirm it if you can provide the relevant portion of the protocol log for me to examine.

> Is that how its supposed to work?

Based on what I've seen so far, yes.

**Comment by thecodrr** [comment]
@jstedfast

But why does it need to know special folders when I haven't explicitly requested any folders yet? If it really is necessary, is there a way to use the XLIST response to get the list of folders directly? So far I can only access the folders after doing a GetFolders call. If MailKit already sent an XLIST command, shouldn't it use it to populate the folders too?

I am afk right now but as soon as I am back, I'll send over the relevant protocol logs for LIST & STATUS commands. They definitely were separate but I could be wrong.

**Comment by jstedfast** [comment]
> If MailKit already sent an XLIST command, shouldn't it use it to populate the folders too?

It does. This is why ImapClient.GetFolder(SpecialFolder.Drafts) doesn't take a CancellationToken because it does not require a command to be sent to the IMAP server.
