### ISSUE TITLE
UTF-8 not supported ?!

### ISSUE THREAD

**Issue by MarkoShenodaa** [jstedfast/MailKit#1729]
Hello,

I'm try to use this project in my app however most of the emails is in Arabic languish.

![Screenshot 2024-03-13 011049](https://github.com/jstedfast/MailKit/assets/137176976/2a305102-0e9d-445a-9688-8f3e24664797)

as you see here it didn't display the words 

Note: i tried use client.EnableUTF8 method and i get error "System.NotSupportedException: 'The IMAP server does not support the UTF8=ACCEPT extension.'"

thank you

**Comment by jstedfast** [comment]
Have you tried the solution in the [FAQ](https://github.com/jstedfast/MailKit/blob/master/FAQ.md#q-why-does-text-show-up-garbled-in-my-aspnet-core--net-core--net-5-app)?
