### ISSUE TITLE
GMail: Unexpected token in IMAP response: [atom: 1028614]

### ISSUE THREAD

**Issue by jacargentina** [jstedfast/MailKit#173]
````
MailKit.Net.Imap.ImapProtocolException: Unexpected token in IMAP response: [atom: 1028614]
   en MailKit.Net.Imap.ImapFolder.ESearchMatches(ImapEngine engine, ImapCommand ic, Int32 index)
   en MailKit.Net.Imap.ImapEngine.ProcessUntaggedResponse(CancellationToken cancellationToken)
   en MailKit.Net.Imap.ImapCommand.Step()
   en MailKit.Net.Imap.ImapEngine.Iterate()
   en MailKit.Net.Imap.ImapEngine.Wait(ImapCommand ic)
   en MailKit.Net.Imap.ImapFolder.Search(SearchQuery query, CancellationToken cancellationToken)
````

The code is simply:

    var changes = folder.Search(MailKit.Search.SearchQuery.ChangedSince(this.HighestModSeq));

Using latest version btw.

**Comment by jacargentina** [comment]
Using a debug version i could see this. On ImapFolder.cs:7187, the switch is not handling a "MODSEQ" atom. Does it help to fix this?

**Comment by jacargentina** [comment]
@jstedfast May be b9c087f14d223118d2da37634d75c024c5bc623e is similar to this? Should something similar be applied to the ESearchMatches(...) handler ?

**Comment by jstedfast** [comment]
Should be fixed now.
