### ISSUE TITLE
Special Character on Password

### ISSUE THREAD

**Issue by RichardKBR** [jstedfast/MailKit#1734]
**Describe the bug**
Using a special character ¨ (umlaut) in password cause authentication error.

**Platform:**
 - OS: Windows 11 Pro
 - .NET Framework: 4.6.1
 - MailKit Version: 2.15.0

**Exception**
Authentication Exception (535 5.7.3 Authentication unsuccessful)

**To Reproduce**
1. Put in youre test account password a character ¨ (umlaut)
2. Try to send email

**Comment by jstedfast** [comment]
Please upgrade. 2.15 is years out of date and there won't be any updates to 2.x

**Comment by RichardKBR** [comment]
Thx ill test!

**Comment by jstedfast** [comment]
Make sure to add this line of code to your program's startup logic:

```csharp
System.Text.Encoding.RegisterProvider (System.Text.CodePagesEncodingProvider.Instance);
```

Then, when authenticating to your SMTP server, use the AUthenticate() method that allows you to pass a System.Text.Encoding parameter to tell MailKit which encoding to use when encoding your password.
