### ISSUE TITLE
The POP3 server has unexpectedly disconnected

### ISSUE THREAD

**Issue by mrjozo** [jstedfast/MailKit#174]
Hi,

tried new version from github with fixed \r\n and got next problem:

    The POP3 server has unexpectedly disconnected.

     at MailKit.Net.Pop3.Pop3Stream.ReadAhead(CancellationToken cancellationToken)

```     
            
client.Connect(ConfigStorage.Instance.ProjectData.GetElementValueAsString("emailServer"),
                    int.Parse(ConfigStorage.Instance.ProjectData.GetElementValueAsString("emailPort")),
                    Convert.ToBoolean(ConfigStorage.Instance.ProjectData.GetElementValueAsString("emailUseSSL")),
                    ConfigStorage.Instance.CTS.Token);
              client.Authenticate(ConfigStorage.Instance.ProjectData.GetElementValueAsString("emailUser"),
                    ConfigStorage.Instance.ProjectData.GetElementValueAsString("emailPassword"),
                    ConfigStorage.Instance.CTS.Token);

              var saChunk = new List<int>();

              for (var j = 0; j < 10; j++)
              {
                 saChunk.Add(j);
              }
              var b = client.GetMessages(saChunk);
```

Log
```
Connected to pop://poczta.o2.pl:110/?starttls=when-available
S: +OK POP3 ready
C: CAPA
S: +OK Capability list follows
S: LAST
S: TOP
S: USER
S: PIPELINING
S: UIDL
S: SASL LOGIN PLAIN
S: STLS
S: .
C: STLS
S: +OK
C: CAPA
S: +OK Capability list follows
S: LAST
S: TOP
S: USER
S: PIPELINING
S: UIDL
S: SASL LOGIN PLAIN
S: .
C: AUTH PLAIN
S: + 
C: AGdhY2VrLndlbG9uZQB6eGN6eGMxMg==
S: +OK
C: CAPA
S: -ERR
C: STAT
S: +OK 12338 2153983759
C: RETR 2
C: RETR 3
C: RETR 4
C: RETR 5
C: RETR 6
C: RETR 7
C: RETR 8
C: RETR 9
C: RETR 10
C: RETR 11
S: +OK
S: Received: by o2.pl (o2.pl mailsystem) with LMTP;
S: 	Thu, 12 Jun 2014 19:46:03 +0200
more lines with S
S: /></body>
S: </html>
S: 
S: 
S: 
S: --b1_412ecde77cc960066f69e099e0527507--
S: 
S: 
S: .

```

**Comment by jstedfast** [comment]
Try downloading 1 message at a time

**Comment by mrjozo** [comment]
It is ok when downloading one at time

**Comment by jstedfast** [comment]
The problem, I suspect, is that your server advertises that it supports PIPELINING, but doesn't actually support it.

You'll notice above in the log that MailKit requests a bunch of messages (all those RETR commands) in a pipelined fashion, but the server only replies with a single message.

Or did you cut out more than just the content of a single message?

**Comment by mrjozo** [comment]
I cut out messages content and replace it with "more lines with S"

**Comment by jstedfast** [comment]
Did you cut out any "S: +OK"'s? That's what I was asking.

**Comment by mrjozo** [comment]
Sorry for my misunderstood, here are 2 full  logs:

http://pastebin.com/e9qV76XH
http://pastebin.com/qbi439YU

**Comment by jstedfast** [comment]
Okay, so, I think that the problem is that the server is only responding with a single message even though you asked for ~10 or so in each session.

**Comment by jstedfast** [comment]
Looking at your log again, I saw this after authenticating:

```
C: CAPA
S: -ERR
```

This should probably clear our list of capabilities which would cause us to not even try to take advantage of PIPELINING.

I also confirmed that your server is broken with PIPELINING. As I suspected, it only responds to a single RETR command and ignores the rest which is what causes MailKit to sit there waiting forever until the TCP connection times out and throws an exception.

**Comment by jstedfast** [comment]
BTW, you may want to change your password since you forgot to X-out your base64'd user/password string both in your original bug report and in those pastebin links.

I've X'd it out in your original bug report, but I can't change the pastebin entries.
