### ISSUE TITLE
Virtual-mta value information 

### ISSUE THREAD

**Issue by Bhupendersinghbisht** [jstedfast/MailKit#1766]
While using Mailkit to send mail, we are using X-virtual-mta as header now.

But not sure about how to get it's value.
Do we need to check with MTA or how to figure out MTA of Mailkit.net.smtp.

mail message.Headers.Add("X-virtual-mta","**VALUE**");

Any help on this will be appreciated.

**Comment by jstedfast** [comment]
I've never even heard of X-Virtual-MTA but it sounds more likely that it's the SMTP server that should be setting that header, not any client.
