### ISSUE TITLE
Invalid subject parsing from iso-8859-2

### ISSUE THREAD

**Issue by dvmbro** [jstedfast/MailKit#1767]
**Describe the bug**
Message sent with subject "ĄĘĆÓŁŚŹŻŃ" is parsed to "¡ÊÆÓ£¦¬¯Ñ"

**Platform (please complete the following information):**
 - OS: Windows
 - .NET Runtime: CoreCLR, Mono
 - .NET Framework: .Net Core 8.0
 - MailKit Version: 4.7.0 (Bug also occurs in MailKit 3.5.0, it works in 3.3.0 though)
 
**To Reproduce**
Send an e-mail with subject written in iso-8859-2 format (example mail attached)
[example_email.eml.txt](https://github.com/user-attachments/files/16107637/example_email.eml.txt)

**Expected behavior**
Proper parsing like one in version 3.3.0

**Additional context**

**Comment by jstedfast** [comment]
I should probably update the FAQ to say "NET Core 8.0" instead of stopping at "NET Core 5.0", but the issue is the same.

https://github.com/jstedfast/MailKit/blob/master/FAQ.md#garbled-text
