### ISSUE TITLE
Great Work!!

### ISSUE THREAD

**Issue by stony69** [jstedfast/MailKit#177]
Hi 

Just wanted to say Awesome job on this.. Super fast.. 

Looking for some help.. doing a search SearchQuery.FromContains("joe@yahoo.com"), I get no results.. I know that there is joe@yahoo.com..  

Searching for  SearchQuery.FromContains("joe"), I get results.. 

Is there anyway of searching for the From email Address

Cheers,

**Comment by jstedfast** [comment]
Unfortunately, FromContains() is server implementation dependent. However, what you can try is to use the `SearchQuery.Header ("From", "joe@yahoo.com")` query instead.

Hmmm, I should probably rename this to HeaderContains so it makes more sense and is more consistent with the others...
