### ISSUE TITLE
`System.Formats.Asn1` version clash with framework/netstandard2

### ISSUE THREAD

**Issue by elachlan** [jstedfast/MailKit#1772]
**Describe the bug**
Looks like nuspec is referencing 8.0.0 and csproj is referencing 8.0.1?

**Platform (please complete the following information):**
 - OS: Windows
 - .NET Runtime: [e.g. CoreCLR, Mono]
 - .NET Framework: 4.8
 - MailKit Version: 4.7.1

https://github.com/jstedfast/MailKit/blob/ee5156657a0002dabba1334d0b4691c10b41880d/nuget/MailKit.nuspec#L54-L84

**Comment by jstedfast** [comment]
Fixed

**Comment by elachlan** [comment]
I think the deploy failed:
```
Attempting to build package from 'MailKit.nuspec'.
Error NU5010: Version string specified for package reference '4.7.1.1.1124' is invalid.
```

**Comment by jstedfast** [comment]
I goofed on my commit, but the 4.7.1.1 release build is good
