### ISSUE TITLE
New version scheme

### ISSUE THREAD

**Issue by georg-eckert-zeiss** [jstedfast/MailKit#1775]
Hi there, I noticed that the version changed from 4.7.1 to 4.7.1.1 - is this intentional? May I ask what's the reason to introduce a new digit?

Best regards,
Georg

**Comment by jstedfast** [comment]
It's a nuget package fix for MailKit 4.7.1 and I didn't want to make a new release of MimeKit (e.g. bumping both versions to 4.7.2), so I just released a fixed nuget package of MailKit and added a digit.

**Comment by georg-eckert-zeiss** [comment]
Ugly but fair enough ;)

**Comment by jstedfast** [comment]
I tend to stick with 3 digits, if/when you see a fourth digit, it's a packaging fix.
