### ISSUE TITLE
Gmail won't accept duplicate mails.

### ISSUE THREAD

**Issue by bradykelly** [jstedfast/MailKit#181]
Sorry, I didn't know how else to contact you, and this actually has nothing to do with MailKit, but I wanted to share this in case anyone else has the same grief I did, you will be able to advise them. I'll close this as soon as possible. 

Turns out it was more than the lack of a 'from' address that caused me not to see mails sent via MailKit Smtp. When I delete a new mail in gmail, and it goes to the bin, subsequent sends of the same mail seem to be ignored by the gmail inbox. I have to clear the bing folder before I can send and receive that message again.

**Comment by jstedfast** [comment]
It might be due to an identical Message-Id header? If you are downloading the message from GMail and then re-sending it back to your GMail account, it may decide that the message is looping by reading existing Received headers as well.

**Comment by bradykelly** [comment]
Thanks, that's nice to know. Such a looping check is a good thing - imagine I accidentally put my test code in a loop and bomb someone's mailbox.

I'll try removing that before re-sending the test mail.
