### ISSUE TITLE
ImapClient: IMessageSummary.Envelope is null on Fetch

### ISSUE THREAD

**Issue by FlorianRainer** [jstedfast/MailKit#182]
I have a Problem with the Result of Fetch with MessageSummaryItems.Envelope.
Sometimes ~1 of 200 Fetchs i get a null value for Envelope. If i Retry the Fetch i get Envelope again.
(Same MailId)

There are multiple Imap Clients processing on the same Inbox, but no deletes are made!

What is the problem for this Envelope == null? Bug or by Design?

Example Code:
```C#
using (var client = new ImapClient())
{
	client.Connect("%server address%", 143, false);

	// Note: since we don't have an OAuth2 token, disable the XOAUTH2 authentication mechanism.
	client.AuthenticationMechanisms.Remove("XOAUTH");
	client.Authenticate("username", "password");

	var inbox = client.Inbox;
	inbox.Open(FolderAccess.ReadWrite);

	var query = SearchQuery.DeliveredAfter(DateTime.UtcNow.AddDays(-7)).And(SearchQuery.NotSeen);
	var unseenMailIds = inbox.Search(query);

	if (!unseenMailIds.Any())
		return;
	
	Console.WriteLine("Got {0} unseen Mails not older than a week", unseenMailIds.Count());

	foreach (var mailId in unseenMailIds)
	{
		Console.WriteLine("Start processing MailId {0}", mailId);
		
		var mailSummary = inbox.Fetch(new[] { mailId }, MessageSummaryItems.Envelope).FirstOrDefault();
		
		//server / network error condition?
		if (mailSummary == null)
			throw new Exception(string.Format("MailHeader of MailId {0} is null (unexpected)", mailId));
		
		//server / network error condition?
		if (mailSummary.Envelope == null)
			throw new Exception(string.Format("MailHeader of MailId {0} has no Envelope (unexpected)", mailId));
	}
}
```

Debug Dump if Envelope is null
```
Errormessage: MailHeader of MailId 47554 has no Envelope (unexpected)
Dump: {MailKit.MessageSummary}
  Body: null
  TextBody: null
  HtmlBody: null
  BodyParts: ...
  Attachments: ...
  Envelope: null
  Flags: Seen
  UserFlags: ...
  Headers: null
  InternalDate: null
  MessageSize: null
  ModSeq: 132564
  References: null
  UniqueId: null
  Index: 11
  GMailMessageId: null
  GMailThreadId: null
  GMailLabels: null
```

I use Version 1.0.13.0 via NuGet but this Problem was already at my first used Version 1.0.10.0

**Comment by jstedfast** [comment]
Try getting a [protocol log](https://github.com/jstedfast/MailKit/blob/master/FAQ.md#ProtocolLog) to see what is happening in that case.

My guess is that the IMAP server is not returning the ENVELOPE.

**Comment by FlorianRainer** [comment]
Ok, i have added the ProtocolLogger, now i have to wait until the Problem occurs (in Production only)
I will give Feedback as soon as i get the Logs.

Thanks

**Comment by jstedfast** [comment]
Any updates?

**Comment by FlorianRainer** [comment]
No, unfortunately the Error was not occurring since i have published the Application.
But i keep you up to date if i get Logs

**Comment by FlorianRainer** [comment]
The following Log was Dumped: (changed domain names)

C: N00000007 UID FETCH 49720 ENVELOPE
S: * 9 FETCH (UID 49720 ENVELOPE ("Mon, 18 May 2015 21:56:56 +0200" "Delivery Status Notification (Failure)" ((NIL NIL "postmaster" "xyz")) ((NIL NIL "postmaster" "xyz")) ((NIL NIL "postmaster" "xyz")) ((NIL NIL "customer" "domin.com")) NIL NIL NIL "<HZgzDgtZK00002ef6@smtp.provider.net>"))
S: * 7 FETCH (MODSEQ (139170) FLAGS (\Seen))
S: N00000007 OK Fetch completed.

**Comment by jstedfast** [comment]
I'm guessing that you didn't get an envelope for message 7?

**Comment by jstedfast** [comment]
The problem you are hitting is that another client is marking a message as seen and the IMAP server is choosing to notify you of that change in the response to an ENVELOPE request for another message.

You need to be ready to handle that case.

**Comment by FlorianRainer** [comment]
but strange, the data i see upon in the logs are fields i try to access via Envelope, like Subject, fron Address, To Address, and more. the Subject for example is "Delivery Status Notification (Failure)", and To is customer@domin.com From is postmaster@xyz.

ok, should i handle this with a simple retry mechanism, or is there a proper way to handle this?

**Comment by jstedfast** [comment]
No. You are receiving multiple IMessageSummary's back from your Fetch() request and you are only handling the first one (MailKit returns them in sorted order... you asked for message 9 but got message 7 and 9 back). Message 7 only has MODSEQ and FLAGS, not the ENVELOPE.

**Comment by FlorianRainer** [comment]
ok got it, thanks!

**Comment by jstedfast** [comment]
No problem. I'm updating the docs to explain this.

**Comment by FlorianRainer** [comment]
Changing the Code like this could do the job?

```C#
inbox.Fetch(new[] { mailId }, MessageSummaryItems.Envelope).FirstOrDefault(x => x.UniqueId == mailId)
```

It was not intuitive for me that i can get items on Fetch, i was thinking i get only the one summary specified by mailId

**Comment by jstedfast** [comment]
Well, if you want to ignore summary info for other messages, yes, that will work.

**Comment by FlorianRainer** [comment]
Perfect, Thanks
