### ISSUE TITLE
No exception thrown when connection fails due to unreachable SMTP server

### ISSUE THREAD

**Issue by Malechus** [jstedfast/MailKit#1823]
I am getting a 504 Gateway Timeout Error when attempting to send an automated email via webform. This error is only occurring when code is deployed to the webserver, either in dev or prod environments, and is not reproducible when debugging locally. Investigation currently indicates this is caused by a firewall issue between the webserver and the SMTP server preventing completion of the SmtpClient.Connect() method, **however,** I would expect an exception to be thrown here, so that the error can be handled by code, rather than an uncontrolled 504 error. With an exception here, logic could be added to iterate over alternate servers/ports, for example. Investigation would be easier due to exception logging. **I understand that the root cause of the failure to connect is not with MailKit.**

**Platform (please complete the following information):**
 - OS: Windows and Linux (Ubuntu)
 - .NET Framework: .NET Core
 - MailKit Version: 4.8.0

**Expected behavior**
Some exception to be thrown.

**Code Snippets**
```csharp
try
{
    using (SmtpClient client = new SmtpClient())
    {
        //Debugging indicates this is where the problem lies. Additional investigation shows issue is with connection to SMTP server.
        client.Connect("smtp.forwardemail.net", 587, false);
        client.Authenticate(_config["Credentials:Mailbot:Username"], _config["Credentials:Mailbot:Password"]);
        client.Send(mimeMessage);
        client.Disconnect(true);
    }
}
catch (Exception ex)
{
    _logger.Log(ex);
    throw ex;
}
```

**Comment by jstedfast** [comment]
Are you saying the Connect() method successfully returns?

**Comment by Malechus** [comment]
No. It seems that it is just hanging until the proxy server returns a timeout HTTP code.

**Comment by jstedfast** [comment]
Okay, but the Connect() method provides you with multiple ways to prevent that socket connect timeout situation.

1. Set a client.Timeout value
2. Pass a CancellationToken into the Connect() method and cancel it.

The timeout is the same timeout that you would get if you called System.Net.Sockets.Socket.Connect().
