### ISSUE TITLE
Are you able to authorize without providing a password?

### ISSUE THREAD

**Issue by kikaragyozov** [jstedfast/MailKit#1826]
If you've made your own SMTP inhouse server, and made an account without a password - are you able to use `SmtpClient` to successfully authorize within it? Or does the library make assumptions that a password must always be present?

**Comment by jstedfast** [comment]
The SmtpClient can be used with or without calling the Authenticate() method. In your scenario, you would not want to call the Authenticate() method because you have no username or password.

**Comment by kikaragyozov** [comment]
@jstedfast I did not mention that there's no username. I mentioned that there's a username with no password setup.

**Comment by jstedfast** [comment]
Then I guess you would use an empty string as your password.

SMTP servers usually either require username/password or no authentication at all. It is abnormal to require a username without a password.
