### ISSUE TITLE
ImapClient Inbox: SearchQuery.FromContains, SearchQuery.SubjectContains invalid

### ISSUE THREAD

**Issue by zyz** [jstedfast/MailKit#1843]
**Describe the bug**

**Platform (please complete the following information):**
 - OS: [Windows 11]
 - .NET Runtime: [.NET]
 - .NET Framework: [.NET 9.0, .NET 4.8]
 - MailKit Version: [4.8.0]

**Expected behavior**
Receive messages contained by a specified sender or subject.

```csharp
using (var client = new ImapClient())
{
    await client.ConnectAsync(host, port, useSsl);
    await client.AuthenticateAsync(email, password);
    var inbox = client.Inbox;
    await inbox.OpenAsync(FolderAccess.ReadOnly);
    var uids = await inbox.SearchAsync(SearchQuery.FromContains(sender));
    await client.DisconnectAsync(true); 
}
```

Note: if the protocol log contains sensitive information, feel free to email it to me at
jestedfa@microsoft.com instead of including it in the GitHub issue.

**Additional context**

**Comment by jstedfast** [comment]
What's the issue?

**Comment by zyz** [comment]
SearchQuery.FromContains: Invalid search criteria for messages from specified senders.

**Comment by jstedfast** [comment]
Can you provide a protocol log? Sounds like a server bug based on what you've told me so far.
