### ISSUE TITLE
Thread freezes calling some asynchronous method using await 

### ISSUE THREAD

**Issue by gabrielforneck** [jstedfast/MailKit#1850]
**Describe the bug**
When I try to use an asynchronous method from `MailKit.Net.Smtp.SmtpClient` with `await`, the thread freezes indefinitely. However, calling the method with `GetAwaiter().GetResult()` does not cause this issue.
No exception is thrown even if the parameters make no sense.
Please tell me if I am doing something wrong!!

**Platform (please complete the following information):**
 - OS: Windows 11
 - .NET Runtime: WPF .NET 8
 - .NET Framework: WPF .NET 8
 - MailKit Version: 4.8.0

**Exception**
No exception is thrown, the thread just still stuck forever.

**To Reproduce**
1. Open Visual Studio and create a WPF .NET 8 project;
2. Import the Mailkit Nuget package;
3. Try to call a asynchronous method from SmtpClient using await (e.g.: `await new SmtpClient().ConnectAsync(/* parameters */);`)

**Expected behavior**
The SmtpClient unfreezes the thread when it is done doing whatever int need to do or throw a exception.

**Code Snippets**
```csharp
using MailKit;
using MailKit.Net.Smtp;
using MailKit.Security;
using System.Windows;

namespace WpfApp1;

/// <summary>
/// Interaction logic for App.xaml
/// </summary>
public partial class App : Application
{

    protected void OnStartup(object sender, StartupEventArgs e)
    {
        SendEmail().GetAwaiter().GetResult();
        new MainWindow().Show();
    }

    public async Task SendEmail()
    {
        var client = new SmtpClient(new ProtocolLogger("smtp.log"))
        {
            Timeout = 10000
        };
        
        await client.ConnectAsync("smtp.gmail.com", 465, options: SecureSocketOptions.Auto, cancellationToken: CancellationToken.None);

        MessageBox.Show("This message will never be shown!", "Hello!", MessageBoxButton.OK, MessageBoxImage.Information);
    }
}
```
Download the project: [WpfApp1.zip](https://github.com/user-attachments/files/17909658/WpfApp1.zip)

**Protocol Logs**
[smtp.log](https://github.com/user-attachments/files/17909841/smtp.log)

**Additional context**
Windows build: Windows 11 23H2 22631.4541
Visual Studio version: Visual Studio 2022 Community 17.12.0

**Comment by jstedfast** [comment]
Add `.ConfigureAwait (false)` to your await call:

```csharp
await client.ConnectAsync("smtp.gmail.com", 465, options: SecureSocketOptions.Auto, cancellationToken: CancellationToken.None).ConfigureAwait (false);
```

For more info, see: https://learn.microsoft.com/en-us/dotnet/api/system.threading.tasks.task.configureawait?view=net-8.0
