### ISSUE TITLE
Sending failure

### ISSUE THREAD

**Issue by jonande** [jstedfast/MailKit#1855]
When doing a SMTP mail send I get an exception: `6.6.0 Error sending message for delivery` 
I'm using yahoo mail and when I log into the yahoo UI I do see the emails in the drafts folder. I'm not clear how to go about debugging what might be wrong here. Note: this same mailing code used to be used with a hotmail address successfully so think the code is ok?

Any help/pointers to look into here would be greatly appreciated.

```
            private readonly string _host = "smtp.mail.yahoo.com";
            private readonly int _port = 587;

            var email = new MimeMessage();
            email.Sender = MailboxAddress.Parse(_user); 
            foreach (string to in mailRequest.To)
                email.To.Add(MailboxAddress.Parse(to));
            email.Subject = mailRequest.Subject;
            var builder = new BodyBuilder();
            builder.HtmlBody = mailRequest.HtmlBody;
            builder.TextBody = mailRequest.TextBody;
            email.Body = builder.ToMessageBody();
            using (var smtp = new SmtpClient())
            {
                smtp.Connect(_host, _port, SecureSocketOptions.StartTls);
                smtp.Authenticate(_user, _pw);
                await smtp.SendAsync(email);
                smtp.Disconnect(true);
            }

```

**Comment by jstedfast** [comment]
You should set the From header rather than Sender.

Only set Sender if it is different from the From address or if the From header contains multiple addresses.

**Comment by jonande** [comment]
Thank you for the assistance!
