### ISSUE TITLE
Some folders are missing

### ISSUE THREAD

**Issue by m1adow** [jstedfast/MailKit#1858]
**Describe the bug**
Hello! I am getting all folders via IMAP client, but some are missing me. Particularly all with '/' are missing. Is this fixable? I have only one personal namespace and the other + shared namespace are empty.

**Platform (please complete the following information):**
 - OS: Windows 11
 - .NET Runtime: CoreClr
  - .NET Framework: WinUI3, .NET 8.0
 - MailKit Version: 4.9.0

**To Reproduce**
1. Create a folder at outlook.com with '/' in the name
2. Get folders from imap client
3. See error

**Expected behavior**
Folders count are equal between Outlook and IMAP client

**Code Snippets**
``` C#
var mailFolders = (await client.GetFoldersAsync(client.PersonalNamespaces.FirstOrDefault()))
                               .Where(f => !f.Attributes.HasFlag(FolderAttributes.NonExistent));
```

**Protocol Logs**
```
Connected to imaps://outlook.office365.com:993/
S: * OK The Microsoft Exchange IMAP4 service is ready. [VwBBADEAUAAyADkAMQBDAEEAMAAwADAAOQAuAFAATwBMAFAAMgA5ADEALgBQAFIATwBEAC4ATwBVAFQATABPAE8ASwAuAEMATwBNAA==]
C: A00000000 CAPABILITY
S: * CAPABILITY IMAP4 IMAP4rev1 AUTH=PLAIN AUTH=XOAUTH2 SASL-IR UIDPLUS ID UNSELECT CHILDREN IDLE NAMESPACE LITERAL+
S: A00000000 OK CAPABILITY completed.
C: A00000001 AUTHENTICATE XOAUTH2 ********
S: A00000001 OK AUTHENTICATE completed.
C: A00000002 CAPABILITY
S: * CAPABILITY IMAP4 IMAP4rev1 AUTH=PLAIN AUTH=XOAUTH2 SASL-IR UIDPLUS MOVE ID UNSELECT CLIENTACCESSRULES CLIENTNETWORKPRESENCELOCATION BACKENDAUTHENTICATE CHILDREN IDLE NAMESPACE LITERAL+
S: A00000002 OK CAPABILITY completed.
C: A00000003 NAMESPACE
S: * NAMESPACE (("" "/")) NIL NIL
S: A00000003 OK NAMESPACE completed.
C: A00000004 LIST "" "INBOX"
S: * LIST (\Marked \HasChildren) "/" Inbox
S: A00000004 OK LIST completed.
C: A00000005 LIST "" "*"
S: * LIST (\HasNoChildren) "/" Archive
S: * LIST (\HasNoChildren) "/" best
S: * LIST (\HasNoChildren) "/" Collection
S: * LIST (\HasNoChildren \Trash) "/" Deleted
S: * LIST (\HasChildren \Drafts) "/" Drafts
S: * LIST (\HasNoChildren) "/" "Drafts/Sub drafts"
S: * LIST (\Marked \HasChildren) "/" Inbox
S: * LIST (\HasNoChildren) "/" "Inbox/Sub Inbox"
S: * LIST (\HasNoChildren \Junk) "/" Junk
S: * LIST (\HasNoChildren) "/" Notes
S: * LIST (\HasNoChildren) "/" Outbox
S: * LIST (\HasChildren \Sent) "/" Sent
S: * LIST (\HasChildren) "/" "Sent/Sub sent"
S: * LIST (\HasNoChildren) "/" "Sent/Sub sent/Sub sent sent"
S: A00000005 OK LIST completed.
```

**Screenshots**
![image](https://github.com/user-attachments/assets/6bc1be28-6f6b-4dd6-aa78-a11fb4ed358a)
![image](https://github.com/user-attachments/assets/99789788-f534-49e6-9c49-fd4642d8d7c7)

**Comment by jstedfast** [comment]
Most likely the issue is that you are creating a folder with /'s in the name when / is the directory separator on the IMAP server.

You generally can't do that. It results in all kinds of problems.

You'll notice that the IMAP server is not returning that folder in the query for *all* folders. It probably only shows up in Outlook because Outlook isn't using IMAP.

**Comment by m1adow** [comment]
Thank you for getting back to me. What is Outlook using?

**Comment by jstedfast** [comment]
Outlook uses the Graph API to talk to the Exchange server.
