### ISSUE TITLE
SmtpProtocolException with a new SmtpClient connection.

### ISSUE THREAD

**Issue by Didacuss** [jstedfast/MailKit#187]
Hi, I have an exception in the version  1.0.15.0 and 1.0.16.0, when I try to use a new SmtpClient connection. I have no exception with 1.0.14.0 version.

Here there is the code:

using (var smtp = new MailKit.Net.Smtp.SmtpClient()) {
                smtp.Connect("sendm.intra.cciaa.net", 25, false);
           }

... and here there is the exception:

SmtpProtocolException: {"Unable to parse status code returned by the server."}

   in MailKit.Net.Smtp.SmtpStream.ReadResponse(CancellationToken cancellationToken)
   in MailKit.Net.Smtp.SmtpClient.SendCommand(String command, CancellationToken cancellationToken)
   in MailKit.Net.Smtp.SmtpClient.SendEhlo(Boolean ehlo, CancellationToken cancellationToken)
   in MailKit.Net.Smtp.SmtpClient.Ehlo(CancellationToken cancellationToken)
   in MailKit.Net.Smtp.SmtpClient.Connect(String host, Int32 port, SecureSocketOptions options, CancellationToken cancellationToken)
   in MailKit.MailService.Connect(String host, Int32 port, Boolean useSsl, CancellationToken cancellationToken)
   in ConsoleApplication3.Program.Main(String[] args) in f:\Devstudio\Download\Dal Papa\ConsoleApplication3\ConsoleApplication3\Program.cs:riga 56
   in System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
   in System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
   in Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
   in System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   in System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   in System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   in System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   in System.Threading.ThreadHelper.ThreadStart()

Have you any idea about this?
Thanks in advance.
Regards.

Diego Paroiln.

**Comment by amellini** [comment]
Same error there .... I've rolled back to previous version and all worked fine.

**Comment by jstedfast** [comment]
Can you guys get me a protocol log? Without it, this will be impossible to debug.

**Comment by jstedfast** [comment]
nevermind, I can reproduce with gmail

**Comment by fenzad** [comment]
This work: smtp.Connect("sendm.intra.cciaa.net", 25, MailKit.Security.SecureSocketOptions.None);

**Comment by jstedfast** [comment]
Just released 1.0.17 with the fix

**Comment by JCCabili** [comment]
I am having this issue on 2.0

SmtpProtocolException: Unable to parse status code returned by the server.

MailKit.Net.Smtp.SmtpStream+<ReadResponseAsync>d__54.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
MailKit.Net.Smtp.SmtpStream.ReadResponse(CancellationToken cancellationToken)
MailKit.Net.Smtp.SmtpClient+<ConnectAsync>d__69.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
MailKit.Net.Smtp.SmtpClient.Connect(string host, int port, SecureSocketOptions options, CancellationToken cancellationToken)
TechnicalSupportService.Pages.Troubleshoots.CloseTicketModel+<OnPostCloseTicketAsync>d__28.MoveNext() in CloseTicket.cshtml.cs
+
                        client.Connect("mail.sistemaxtech.com", 110, MailKit.Security.SecureSocketOptions.Auto);
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
System.Runtime.CompilerServices.TaskAwaiter.GetResult()
Microsoft.AspNetCore.Mvc.RazorPages.Internal.ExecutorFactory+GenericTaskHandlerMethod+<Convert>d__4.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
System.Runtime.CompilerServices.TaskAwaiter.GetResult()
Microsoft.AspNetCore.Mvc.RazorPages.Internal.ExecutorFactory+GenericTaskHandlerMethod+<Execute>d__3.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
System.Runtime.CompilerServices.TaskAwaiter.GetResult()
Microsoft.AspNetCore.Mvc.RazorPages.Internal.PageActionInvoker+<InvokeHandlerMethodAsync>d__29.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.Mvc.RazorPages.Internal.PageActionInvoker+<InvokeNextPageFilterAsync>d__31.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
Microsoft.AspNetCore.Mvc.RazorPages.Internal.PageActionInvoker.Rethrow(PageHandlerExecutedContext context)
Microsoft.AspNetCore.Mvc.RazorPages.Internal.PageActionInvoker.Next(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
Microsoft.AspNetCore.Mvc.RazorPages.Internal.PageActionInvoker+<InvokeInnerFilterAsync>d__22.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+<InvokeNextResourceFilter>d__22.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+<InvokeFilterPipelineAsync>d__17.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+<InvokeAsync>d__15.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.Builder.RouterMiddleware+<Invoke>d__4.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.Authentication.AuthenticationMiddleware+<Invoke>d__6.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.VisualStudio.Web.BrowserLink.BrowserLinkMiddleware+<ExecuteWithFilter>d__7.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware+<Invoke>d__7.MoveNext()

**Comment by jstedfast** [comment]
Can't solve the problem without a protocol log.

**Comment by jstedfast** [comment]
This is the problem: client.Connect("mail.sistemaxtech.com", 110, MailKit.Security.SecureSocketOptions.Auto);

You are connecting to a POP3 server using the SMTP client. That won't work.

**Comment by JCCabili** [comment]
I am very sorry but I'm new on Mail Services so what should I do ?

**Comment by jstedfast** [comment]
Try connecting to port 25 or 587... or 465 (SSL port)

**Comment by JCCabili** [comment]
Thank you jstedfast I already fix it. Thanks!
