### ISSUE TITLE
ParseBody results in empty PartSpecifier

### ISSUE THREAD

**Issue by jvilhuber** [jstedfast/MailKit#188]
I'm not sure if this is expected or not, but if I do a BODYSTRUCTURE fetch, ParseBody() is called with string.EMPTY. The summary.Body therefore doesn't have a PartSpecifier. Is the intent of the string.Empty to auto-discover the Part (TEXT in my case, but could be anything, I assume).

```
				case "BODYSTRUCTURE":
					summary.Body = ImapUtils.ParseBody (engine, string.Empty, ic.CancellationToken);
					summary.FetchedItems |= MessageSummaryItems.BodyStructure;
					break;
```

then

```
			body.ContentTransferEncoding = enc;
			body.ContentDescription = desc;
			body.PartSpecifier = path;
```

**Comment by jvilhuber** [comment]
If there's a better way to ask these kinds of questions than opening an issue, please let me know.

**Comment by jvilhuber** [comment]
I ask because I'm trying to make sure I can read a stream instead of reading the body into memory like this:

```
    var message = folder.GetStream (summary.UniqueId.Value, text, (int)(summary.MessageSize.Value-text.Octets), (int)text.Octets);
```

and underneath, GetStream() uses part.PartSpecifier to select the BODY.PEEK[XXX] value, and since the PartSpecifier here is the empty string, I don't think it's doing what I thought it would. Perhaps I'm misusing the API?

**Comment by jstedfast** [comment]
> The summary.Body therefore doesn't have a PartSpecifier.

If the message has only 1 part, then there's no need for a part specifier.

> Is the intent of the string.Empty to auto-discover the Part (TEXT in my case, but could be anything, I assume).

Sort of, but not really. The top-level MIME part does not have a part specifier (hence string.Empty). If that part is a multipart, then it's children will have part specifiers.

TEXT is not a part specifier, it's just a string that gets *appended to* the part specifier.

> and since the PartSpecifier here is the empty string, I don't think it's doing what I thought it would.

What do you expect it to return? FWIW, I'm pretty sure you want to pass `0` as the offset.

**Comment by jvilhuber** [comment]
Offset: Yea, I was playing with some stuff. Fixed :)
Expecting: I was expecting the resulting IMAP command to get  `UID FETCH 8622 (BODY.PEEK[TEXT]<0.6>)`, instead of `UID FETCH 8622 (BODY.PEEK[]<0.6>)`, which gets me the first 6 bytes of the headers (I think).

**Comment by jstedfast** [comment]
it's intended to start with the headers fwiw.

**Comment by jvilhuber** [comment]
Ok, thanks. Will play (and learn) more.

**Comment by jstedfast** [comment]
I was thinking of adding an API to allow specifying TEXT, but I think that would be awkward because the only Octets value there is assumes that you start with the headers.

**Comment by jstedfast** [comment]
I have added new GetStream() overloads which take a bool contentOnly parameter allowing you to fetch only the TEXT section.

Are you by chance just trying to get the TEXT section in order to show a preview of the message in a message-list (like some mobile mail clients (such as the iOS mail app) do?).

**Comment by jvilhuber** [comment]
Yes, precisely. Perhaps a GetPreview() api could be useful, though that could turn into a quagmire with html and other not-easily-previewable messages..
