### ISSUE TITLE
Broken imap capabilities

### ISSUE THREAD

**Issue by radiy** [jstedfast/MailKit#19]
My mail server reports StartTLS capability, but in fact do not support it.
So when mailkit try to make handshake it fails.
It would be helpfull if I can disable some capabilities similar to the way I can disable 
authentication methods.

**Comment by jstedfast** [comment]
FWIW, there's a newer Connect() API that takes a SecureSocketOptions enum that specifies whether or not to use SslOnConnect, StartTls, or StartTlsWhenAvailable.

The StartTls option will throw an exception and abort if StartTLS is not available.
