### ISSUE TITLE
New contentOnly fails sometimes

### ISSUE THREAD

**Issue by jvilhuber** [jstedfast/MailKit#190]
Ran into this with the new contentOnly GetStream method. Not sure the patch is the right one, but it'll hopefully give you an idea:

```
diff --git a/MailKit/Net/Imap/ImapFolder.cs b/MailKit/Net/Imap/ImapFolder.cs
index c0fc6a9..820e503 100644
--- a/MailKit/Net/Imap/ImapFolder.cs
+++ b/MailKit/Net/Imap/ImapFolder.cs
@@ -5216,7 +5216,7 @@ namespace MailKit.Net.Imap {
                        if (ic.Result != ImapCommandResult.Ok)
                                throw ImapCommandException.Create ("FETCH", ic);

-                       if (!streams.TryGetValue (part.PartSpecifier, out stream))
+            if (!streams.TryGetValue (partSpecifier, out stream))
                                throw new ImapCommandException ("The IMAP server did not return the requested stream.");

                        return stream;
```

In my case I was getting the stream for "TEXT" (no part.PartSpecifier, i.e. it is ""). The TryGetValue failed because part.PartSpecifier is empty. We previously created a local partSpecifier, which I suspect we need to use here.

**Comment by jvilhuber** [comment]
This seemed a smallish patch, and I'm not entirely comfortable (yet) making a pull request, so forgive me about just pasting the patch here...

**Comment by jstedfast** [comment]
Thanks. Fixed in git master.

**Comment by jvilhuber** [comment]
Thanks. I figured there'd be other places to fix.
