### ISSUE TITLE
engine.Uri = null in IMAP Authenticate method under NETFX_CORE

### ISSUE THREAD

**Issue by limefrogyank** [jstedfast/MailKit#192]
In the Authenticate method for ImapClient, on my system (Windows 10 universal app) an exception is thrown on line 855:

`var uri = new Uri ("imap://" + engine.Uri.Host);`

Under the Connect method, you've got a compiler conditional where !NETFX_CORE has the engine.Uri initialized with the local uri variable.  However, for the ELSE condition (my condition), engine.Uri is never initialized.  I'm not sure if you actually need it in this case, but simply adding the line:

`engine.Uri = uri;` 

after the #else statement seems to fix my error.

**Comment by jstedfast** [comment]
Thanks!
