### ISSUE TITLE
SmtpClient missing SmtpCommandException

### ISSUE THREAD

**Issue by stopak** [jstedfast/MailKit#194]
I'm trying to write simple smtp outgoing queue that can handle status codes.

I was trying to send email to hotmail.com, but my ip address is on their block list. Unfortunately after issuing RCPT TO: command their response is 550 and immediate connection close. Currently SmtpClient is throwing SmtpProtocolException and I have no way of finding what has happend. In this particular case email should be marked as impossible to deliver. Would it be possible to change connection handling in a way that in such situation SmtpCommandException is thrown with status code ? Currently I'm parsing ProtocolLogger output in search of 550, but it's really slow and terrible solution.

**Comment by jstedfast** [comment]
The code seems to already throw an SmtpCommandException() when RCPT TO fails with a 550.

I need a stack trace of where you are getting this SmtpProtocolException.

**Comment by stopak** [comment]
Unfortunately I'm running this on mono and can't find a way to get full stack trace.

Exception message: The SMTP server has unexpectedly disconnected.

Stack Trace:  at MailKit.Net.Smtp.SmtpStream.ReadAhead (CancellationToken cancellationToken) [0x00000] in <filename unknown>:0 

SMTP Dump: 
Connected to smtp://mx4.hotmail.com:25/?starttls=when-available
S: 220 COL004-MC1F33.hotmail.com Sending unsolicited commercial or bulk e-mail to Microsoft's computer network is prohibited. Other restrictions are found at http://privacy.microsoft.com/en-us/anti-spam.mspx. Tue, 19 May 2015 05:39:09 -0700 
C: EHLO [0.0.0.0]
S: 250-COL004-MC1F33.hotmail.com (3.21.0.184) Hello [0.0.0.0]
S: 250-SIZE 36909875
S: 250-PIPELINING
S: 250-8bitmime
S: 250-BINARYMIME
S: 250-CHUNKING
S: 250-STARTTLS
S: 250-AUTH LOGIN
S: 250-AUTH=LOGIN
S: 250 OK
C: STARTTLS
S: 220 SMTP server ready
C: EHLO [0.0.0.0]
S: 250-COL004-MC1F33.hotmail.com (3.21.0.184) Hello [0.0.0.0]
S: 250-SIZE 36909875
S: 250-PIPELINING
S: 250-8bitmime
S: 250-BINARYMIME
S: 250-CHUNKING
S: 250-AUTH LOGIN
S: 250-AUTH=LOGIN
S: 250 OK
C: MAIL FROM:<petycja@petycja.ekorozwoj.pl>
C: RCPT TO:<some_email@hotmail.com>
S: 550 OU-002 (COL004-MC1F33) Unfortunately, messages from 0.0.0.0 weren't sent. Please contact your Internet service provider since part of their network is on our block list. You can also refer your provider to http://mail.live.com/mail/troubleshooting.aspx#errors.

and connection close.

I will try to reproduce this situation on windows machine. However all IP I have access to passed without a problem.

**Comment by jstedfast** [comment]
Okay, so the reason you weren't getting the SmtpCommandException is because the commands were PIPELINED and in that code-path, all responses are read from the server before they are processed for errors. Since the SMTP server broke the connection and did not send a response to the RCPT TO command, the SmtpProtocolException was thrown due to a failure to read the RCPT TO response.

**Comment by stopak** [comment]
Thanks for such fast resolution
