### ISSUE TITLE
Client connect bug

### ISSUE THREAD

**Issue by asenval** [jstedfast/MailKit#196]
Hello, in .NET URI class when you create an URI without port or port=0, it set port property to -1, than your connect method for IMAP and so on throw exception that port couldn't be negative. I think that default value for port must be -1 too, so users of your library could use .NET URI class to the client.Connect method.

**Comment by jstedfast** [comment]
This was fixed in MailKit 1.0.14 which was released on April 11th.

**Comment by asenval** [comment]
OK I am sorry for this report but I look code in Client classes but it was fixed in MailService class. Thank you.
