### ISSUE TITLE
Bad encoding with gmail

### ISSUE THREAD

**Issue by Mxater** [jstedfast/MailKit#199]
I download email from gmail services, but receive the body content with bad encoding, this show "DirecciÃ³n" insted of "dirección"

The header of email :
<code>
--b1_3db63c5f18eb64d14c37d6765fae0566
</code>
<code>
Content-Type: text/html; charset=iso-8859-1
</code>
<code>
Content-Transfer-Encoding: 8bit
</code>

**Comment by jstedfast** [comment]
That suggests that the HTML is actually in UTF-8 and not in iso-8859-1 like the headers say.

You can use `TextPart.GetText (Encoding.UTF8)` to work around that.
