### ISSUE TITLE
ImapClient.Idle causes (a little) CPU usage

### ISSUE THREAD

**Issue by Sune1337** [jstedfast/MailKit#200]
First of all, thanks for a great Imap client :)

I noticed my application is using a little CPU when i use the Idle command.
This is because the following line is executed 1000 times/second.
https://github.com/jstedfast/MailKit/blob/master/MailKit/Net/Imap/ImapStream.cs#L282

Was the intent perhaps to poll it 1 time per second? Or could it perhaps become configurable?

**Comment by jstedfast** [comment]
Oops, yes, it was meant to be more like once per second, although it should probably be a bit more fine-grained than once-per-second - but certainly not 1000 times-per-second.

Ideally I'd find a way to wait on either the CancellationToken being cancelled or the stream having data, whichever comes first.

**Comment by jstedfast** [comment]
I changed it to 1/4 second for now. I don't think we need any finer-grained precision than that for cancellation.

I'd like for cancellation to be nearly instantaneous in the user's perspective, or as close as we can reasonably get. I think anything finer-grained than 1/10 is not going to be perceptible to a user and 1/4 second is probably a reasonable delay for users.

**Comment by Sune1337** [comment]
nice, thanks for the fix.

**Comment by jstedfast** [comment]
no prob!
