### ISSUE TITLE
Unable to authenticate when password contains £ 

### ISSUE THREAD

**Issue by truane** [jstedfast/MailKit#204]
Hi 

I am using the code below with a simple password like This1sA£Test to content to a Exchange server with Active Directory user

<code>
_credentials = new NetworkCredential(_emailClientWatcher.Username,_emailClientWatcher.Password);
_client = new ImapClient();
_client.AuthenticationMechanisms.Remove("XOAUTH2");
_client.Connect(_emailClientWatcher.Server, _emailClientWatcher.Port, _emailClientWatcher.SocketOption); 
_client.Authenticate(_credentials);

Any password that contains a password with £ in it is failing. 

Can you confirm that mailkit supports the standard password symbols 

Lowercase letters
a, b, c, ...

Uppercase letters
A, B, C, ...

Numerals
0, 1, 2, 3, 4, 5, 6, 7, 8, 9

Non-alphanumeric (symbols)
( ) ` ~ ! @ # $ % ^ & * - + = | \ { } [ ] : ; " ' < > , . ? /

Unicode characters
€, Γ, and λ

If not which so I can document them

Thanks for any help

**Comment by jstedfast** [comment]
It should work with everything unless the server doesn't support the UTF-8 encoding, in which case... good luck :-)

If the server doesn't support UTF-8, there's:

1. no way to know it doesn't support it
2. no way to know what encoding it expects the password to be in

If you can get me a protocol log, perhaps the problem is in the particular SASL mechanism being used.

**Comment by truane** [comment]
here is the protocol log i will take to the exchange guys

<code>
Connected to imaps://mail.server.com:993/
S: * OK The Microsoft Exchange IMAP4 service is ready.
C: B00000000 CAPABILITY
S: * CAPABILITY IMAP4 IMAP4rev1 AUTH=PLAIN UIDPLUS MOVE ID CHILDREN IDLE NAMESPACE LITERAL+
S: B00000000 OK CAPABILITY completed.
C: B00000001 AUTHENTICATE PLAIN
S: +
C: AGFkc2Vuc2ExXFZpc2lvbkxvYWRlckRldjIAVGhlMklzVGVzdMKjMTMy
S: B00000001 NO AUTHENTICATE failed.
C: B00000002 LOGIN "domain\\Username" {15+}
C: Th1sIs£Test
S: B00000002 NO LOGIN failed.
<\code>

**Comment by jstedfast** [comment]
Googling around seems to suggest that this is a common problem with Exchange and non-ASCII passwords dating all the way back to at least 2002.

The suggested workarounds have been:

1. Use `LOGIN "username" {#}\r\npassword\r\n" (which you see from the log did not work)
2. Use `AUTHENTICATE PLAIN ...` which defines the charset to always be UTF-8, but as you can see - that also did not work.

**Comment by truane** [comment]
Thanks for the quick response. All I can do now is thrown the issue to our exchange guys and see what they say. I think it is there issue anyway so will let you know.
