### ISSUE TITLE
Wrong event raised when Gmail labels are added/removed

### ISSUE THREAD

**Issue by quentez** [jstedfast/MailKit#208]
When I register for both `MessageFlagsChanged` and `MessageLabelsChanged` on a folder, I never get any calls on the later. When I add/remove a label to an email on Gmail, it's `MessageFlagsChanged` that gets raised.

**Comment by jstedfast** [comment]
I think you'll find that the code is correct.

If the IMAP server sends:

    * 1 FETCH (FLAGS (...))

then it will emit MessageFlagsChanged. However, if the server sends:

    * 1 FETCH (X-GM-LABELS (...))

then it will emit MessageLabelsChanged.

You can find the code here: https://github.com/jstedfast/MailKit/blob/master/MailKit/Net/Imap/ImapFolder.cs#L9132

**Comment by jstedfast** [comment]
Some of GMail's labels also double as flags, so when it's the same as a flag, the server will send FLAGS instead of X-GM-LABELS.

**Comment by jstedfast** [comment]
If you could post a protocol log, that would be helpful in verifying this.

**Comment by quentez** [comment]
Oh ok I see. I'll make sure to check with the logs to validate that. Thanks for the quick response. 

We just deployed a new system in production using Mailkit and we're now keeping about 10k IMAP connections open at all time using it. It has worked very well so far, so thank you for that!

**Comment by jstedfast** [comment]
Wow, that's awesome :-)
