### ISSUE TITLE
Headers are always empty on Fetch

### ISSUE THREAD

**Issue by bitdisaster** [jstedfast/MailKit#210]
I'm trying to get read the HeaderId.Importance when I fetch messages. However the Headers property is always null. On the other side the Headers property is never null when I use GetMessage for the same set of messages.

**Comment by jstedfast** [comment]
Can you get a [protocol log](https://github.com/jstedfast/MailKit/blob/master/FAQ.md#ProtocolLog) so I can take a look at what command is being sent and what the server is sending back?

**Comment by jstedfast** [comment]
FWIW, I just tested this and it works for me.

```csharp
var headers = new HashSet<HeaderId> (new [] { HeaderId.Importance });
var summaries = client.Inbox.Fetch (0, -1, MessageSummaryItems.UniqueId, headers);
foreach (var summary in summaries) {
    foreach (var header in summary.Headers)
        Console.WriteLine (header);
}
```

Is this how you are doing it?

**Comment by jstedfast** [comment]
This is what the protocol log should look like (more-or-less):

```
C: A00000008 FETCH 1:* (UID BODY.PEEK[HEADER.FIELDS (IMPORTANCE)])
S: * 1 FETCH (UID 343 MODSEQ (38846) BODY[HEADER.FIELDS (IMPORTANCE)] {22}
S: Importance: Normal
S: 
S: )
```

**Comment by jstedfast** [comment]
Is the issue that if the Importance header doesn't exist, the summary.Headers property is null?

If so, I've just fixed that.

**Comment by bitdisaster** [comment]
Ah, sorry. My bad. I wasn't aware that I have to explicitly request the headers on the fetch. The not null on the summary.Headers property is still a welcomed change.
Thanks for the fast reply.

**Comment by jstedfast** [comment]
The `MessageSummaryItems` flags tell the ImapFolder which fields of the `IMessageSummary` object to request and fill-in.

It's a lot like reading just a subset of the columns from a database record.

**Comment by bitdisaster** [comment]
I was aware of  MessageSummaryItems . But it has no impact on headers except for References. The clue was to define var headers = new HashSet<HeaderId> (new [] { HeaderId.Importance }); and pass it to fetch.

**Comment by jstedfast** [comment]
oh, gotcha.
