### ISSUE TITLE
Support for CoreCLR

### ISSUE THREAD

**Issue by niemyjski** [jstedfast/MailKit#212]
Will there be any support for the new core clr?
https://aspnet.uservoice.com/forums/252111-asp-net-vnext/suggestions/7648077-corefx-should-include-system-net-mail

Also, it would be sweet if we could configure this library with smtp defaults via environmental variables as this is a part of vnext.

**Comment by jstedfast** [comment]
I'll happily accept a csproj file to build for Core CLR but I don't want to add support for loading default settings from environment variables - it just would not fit nicely with the API.

**Comment by jstedfast** [comment]
if you could send me an empty Library Project .csproj file for CoreCLR, I can probably commit them in a few minutes (I'm betting it compiles without any (or very few) changes).

**Comment by jstedfast** [comment]
Actually, can't you just reference a .NET4.5 assembly and be done?

**Comment by niemyjski** [comment]
There are two different run times, the core clr can't reference .net 4.5/4.6 assemblies

**Comment by niemyjski** [comment]
Vnext won't support web.config/ will have generic configuration that runs off anything (environment variables, json, ini, etc)

**Comment by jstedfast** [comment]
Okay, well, if you can get me a blank Library Project template, I can probably copy/paste the `&lt;Compile Include="..." /&gt;` lines into it and it'll probably more-or-less work. Looks like serialization isn't supported, so I'll probably have to add a DEFINE for that, but no big deal.

**Comment by jstedfast** [comment]
Do you mean you want a DNX project?

**Comment by niemyjski** [comment]
Yes, DNX which uses a new project format too.

**Comment by jstedfast** [comment]
You can already reference MimeKit and MailKit from DNX projects in VS2015 (I just tested this).

**Comment by akoeplinger** [comment]
@jstedfast it only works for the Desktop .NET target, but not for the .NET Core based one, which is what this issue was about:

![image](https://cloud.githubusercontent.com/assets/1376924/8889665/4747607c-32e4-11e5-935b-bb859891fdf3.png)

**Comment by jstedfast** [comment]
Ah, thanks. What's the correct way to create a .NET Core project in VS2015? The NewProject templates I see don't make it obvious (to me, at least).

**Comment by akoeplinger** [comment]
@jstedfast If you create a new "Visual C# > Web > Class Library (Package)" project, that should give you the refactored BCL packages in project.json with the new `dotnet` TFM (read more about that [here](http://oren.codes/2015/06/16/demystifying-pcls-net-core-dnx-and-uwp-redux/)).

**Comment by jstedfast** [comment]
Thanks, I'll give that a go

**Comment by jstedfast** [comment]
Hmmm, having trouble getting this to work because it wants to slurp up every file in the directory whether I want to include it or not.

The only solution I can think of is using symlinks...

**Comment by akoeplinger** [comment]
@jstedfast you can include/exclude patterns of files in `compile` or just list each file separately in `compileFiles`: https://github.com/aspnet/Home/wiki/Project.json-file#sources

**Comment by jstedfast** [comment]
oooooohhhhh, thanks. I'll give that a try.

**Comment by jstedfast** [comment]
Okay, so I've almost got MimeKit ported, but I've got the following build errors that I have no idea what they mean or how to solve them:

![screenshot](http://content.screencast.com/users/jeff.xamarin/folders/Jing/media/174e189d-64c6-4bb6-8da9-69ce846a12e2/2015-07-28_1020.png)

**Comment by akoeplinger** [comment]
@jstedfast that looks like the incompatibility with the Xamarin Tools: https://github.com/dotnet/corefx/issues/449. Uninstall them and it should work (builds fine here).

**Comment by jstedfast** [comment]
Ah, hmmm, how am I going to create a nuget with all these? if I have to uninstall the Xamarin stuff? :(

**Comment by akoeplinger** [comment]
I think that's just a point in time thing until the incompatibility is fixed? btw. you can turn on producing a .nupkg from "Properties > Build > Produce outputs on build".

**Comment by akoeplinger** [comment]
@jstedfast Here's an interesting blogpost about how to target .NET Core without DNX: http://oren.codes/2015/07/29/targeting-net-core/

**Comment by joeaudette** [comment]
I just came across this while researching how to send mail in dnxcore50. It seems that getting mailkit/mimekit to work would be the best hope since there is no system.net.mail in the current corefx and it won't be there at the 1.0 release and no timeline has been given for when they will port that.

It seems like very important functionality for any web app to send email so I'm kind of surprised MS hasn't given it higher priority. MailKit/MimeKit looks far superior to system.net.mail anyway.  I guess the only 3rd option is to use REST apis from 3rd party email services, but I think it will be a big disappointment to many people trying to port their web apps to dnxcore50 when they find there is nothing available to easily send email.

I would be glad to help in any way that I can to assist in getting these projects ported. Looking at the code I don't feel like I'm qualified to solve it or send a pull request. But I do know about the new project system and how to resolve errors like the ones in the screenshot you posted so maybe I could help a little.

There is a new .xproj file and a project.json file that are the main new things.

The project.json file has all the nuget dependencies, framework targets and dependencies and meta data about the project. VS 2015 will automatically restore the dependencies if you edit project.json to add dependencies. you can also use 

    dnu restore 

from the command line in the project directory to restore nuget dependencies.

The build output in the new system is a nuget package per project. VS 2015 will create the nuget package for you based on the project.json file. I'm sure there is also a command line way to do it and vs is just automating that stuff.

Those errors you had in the screenshot look likely related to some problem in the project.json file.

If there is anything I could do to assist you in any way please let me know. If there was a kickstarter to raise money to make it worthwhile for you to work on this as a priority to get it done I would be willing to make a small donation and I'm sure others would too.

**Comment by jstedfast** [comment]
I actually plan to look into this again soon. Hoping the incompat between Xamarin and DNX is gone now.

**Comment by joeaudette** [comment]
That is great news! If you run into unexpected errors please post them and maybe I can help.

**Comment by jstedfast** [comment]
If you can figure out why this is failing, that'd be helpful:

https://ci.appveyor.com/project/jstedfast/mimekit/build/1.2.16.191

Also, how do I restore nuget packages in VS2015?

**Comment by jstedfast** [comment]
The commit that breaks the build just moved the MimeKit.CoreFX.xproj, project.json and project.lock.json back into the MimeKit directory next to all of the other .csproj files.

Before that, the build worked fine.

**Comment by jstedfast** [comment]
BTW, if I open the VS2015 terminal and cd into the project directory and type `dnu restore`, it says `dnu not recognized...`

**Comment by joeaudette** [comment]
The appveyor error seems about .csproj and is happening right after it adds the package for Sqlite.
I'm not entirely sure what is going on there but I do know that in dnxcore50 there is a new package for Sqlite, I'm using it in one of my projects and my project.json reference looks like this:

    "Microsoft.Data.Sqlite": "1.0.0-rc1-final"

as opposed to System.Data.Sqlite

There is also [an update to VS 2015 that just came out Nov 30](https://www.visualstudio.com/en-us/news/vs2015-update1-vs.aspx) that you probably need to install.

After doing that I would follow the install steps [starting at step 2 here](https://docs.asp.net/en/latest/getting-started/installing-on-windows.html) to make sure you install the latest RC1-update1 bits of .NET Core/ASP.NET 5

That should get the command line experience working.

I know that NUnit is not supported with dnxcore50 but there is xunit that is compatible, not sure if that is at all related to the errors.

One thing with the new xproj type is that it does not keep a list of files that are project members like.csproj, instead every file in the project folder is part of the project and there may be potential issues with files that are from other project types and not intended to be part of the .xproj project.

There are some new ways of [sharing files across projects in vs](http://stackoverflow.com/questions/30634753/what-is-the-difference-between-a-shared-project-and-a-class-library-in-visual-st) that may be useful.

**Comment by joeaudette** [comment]
I just looked at the [project.json file in the mimekit folder](https://github.com/jstedfast/MimeKit/blob/master/MimeKit/project.json), I would not have expected to see any targets there for older platforms, I would only expect net451 and dnxcore50 but maybe I'm misunderstanding something if that file is also used for other platforms.

**Comment by joeaudette** [comment]
also looking in the project.json foe mimekit I see a dependency:

    "System.Security.Cryptography.Algorithms": "4.0.0-beta-23225",

as far as I know dependencies like that are only for dnxcore50 and should be in a dependency section for dnxcore50, and it is also an older version and not up to date for rc1. For example in my classlibrary projects I have:

    "frameworks": {
      "net451": { },
      "dnxcore50": {
        "dependencies": {
          "System.Collections": "4.0.11-beta-23516",
          "System.Linq": "4.0.1-beta-23516",
          "System.Runtime": "4.0.21-beta-23516",
          "System.Collections.Concurrent": "4.0.11-beta-23516",
          "Microsoft.CSharp": "4.0.1-beta-23516",
          "System.Security.Cryptography.Algorithms": "4.0.0-beta-23516"
        }
      }

I just added that bottom reference in my project to verify that the correct version for rc1 should be 23516 not 23225 as you have it, that is a very old beta package.

**Comment by joeaudette** [comment]
I think the dotnet moniker is not yet ready for prime time and should be dnxcore50 for now. dotnet will work later but not everything is in place for that yet.  Just yesterday I watched [this video](https://channel9.msdn.com/Events/ASPNET-Events/ASPNET-Fall-Sessions/Class-Libraries) which explains their plans for making it much easier to target multiple platforms and even target platforms that don't exist yet, that will be great when it is ready but I think it is not ready now. I think the dotnet moniker is for those future plans.

**Comment by joeaudette** [comment]
probably a good reference project to study is https://github.com/JamesNK/Newtonsoft.Json since it supports lots of platforms just as you do with mailkit/mimekit and they support dnxcore50

**Comment by jstedfast** [comment]
I've been copying the Newtonsoft.Json project.json file and they use "dotnet" :)

Anyway, I've gotten it to work locally for me, but appveyor is still breaking on nuget restore for the .Net45 solution.

Note that appveyor is being asked to build MimeKit.Net45.sln which only contains the .NET 4.5 project and the unit tests. It does not contain the .xproj.

**Comment by jstedfast** [comment]
Also, I came to the same conclusion about removing all of the other "net45", "net40", etc framework targets.

I can try switching over to "dnxcore50" instead of "dotnet", but the problem seems to actually be with "nuget restore MimeKit.Net45.sln", but *only* when the .xproj and the project.json file are in the MimeKit directory (if I remove them, appveyor works again).

**Comment by joeaudette** [comment]
I still think some of the dependencies like:

   "System.Security.Cryptography.Algorithms": "4.0.0-beta-23225"

should be updated either as 4.0.0-beta-23516 or 4.0.0-*

I noticed that newtonsoft has a separate [Newtonsoft.Json.project.json](https://github.com/JamesNK/Newtonsoft.Json/blob/master/Src/Newtonsoft.Json/Newtonsoft.Json.project.json) which appears to target 4.5 but then their main project.json also seems to target 4.5 and other platforms much as your did.

**Comment by jstedfast** [comment]
Yea, that's why I did things that way as well, but that caused errors in the build for me ("The build host had an error..." or some such, but no error was ever listed after it and/or it just had a OutOfMemoryException)

**Comment by joeaudette** [comment]
I noticed newtonsoft has a global.json and a nuget.config, not sure if that matters.

There are ways in the xml for .csproj files to exclude specific files so maybe there is a way to explicitly tell it to ignore the .xproj and project.json file, though I don't see anything like that in the newtonsoft .csproj file

**Comment by jstedfast** [comment]
Strangely, `nuget restore MimeKit.Net45.sln` worked perfectly fine on my Windows 10 machine. Maybe it was because I already had the nuget packages installed, though? I'll try with a fresh checkout tonight when I get home.

**Comment by jstedfast** [comment]
Looks like a bug in nuget or something. The problem is that `MimeKit.csproj` uses `AnyCPU` but the error is that there is no `OutputPath` defined for `Any CPU`. From what I understand, the sln is supposed to remap `Any CPU` to `AnyCPU`, but for whatever reason, when nuget encounters a project.json file, it doesn't do the remapping.

Worked around it by adding some logic to the .csproj to manually remap.

**Comment by jstedfast** [comment]
Possibly some bad news. One of the latest comments on https://github.com/dotnet/corefx/issues/1006 suggests that System.Net.Sockets has not been ported to CoreCLR yet, and I'll need those for MailKit :(

**Comment by joeaudette** [comment]
that issue is about SmtpClient. I can see that System.Net.Sockets does exist in the source code https://github.com/dotnet/corefx/tree/master/src/System.Net.WebSockets and there exists a nuget you can add to dnxcore50 dependencies

    "System.Net.Sockets": "4.1.0-beta-23516"

**Comment by jstedfast** [comment]
I am very close to having a port completed. I'm just missing an HMACMD5 implementation now.

**Comment by jstedfast** [comment]
Okay, this is now implemented.

**Comment by joeaudette** [comment]
That is fantastic! Is there a nuget for dnxcore50?

I tried adding this in my dependencies but it says it doesn't support dnxcore50:

    "MailKit": "1.2.15"

so I'm guessing you haven't published a nuget yet.

**Comment by jstedfast** [comment]
I have not published a nuget yet

**Comment by joeaudette** [comment]
any idea when you might do that? I'm eager to test it in my project.

**Comment by jstedfast** [comment]
well, I can't figure out where the dnxcore50 build ends up

**Comment by joeaudette** [comment]
in VS if you go into the project properties under build there is a checkbox to tick for "Produce Outputs on build" it should then build a nuget package on build and I believe it will land under solutionfolder/artifacts/bin
typically I think we add the artifacts folder to gitignore

**Comment by jstedfast** [comment]
okay, now I can't publish the packages because they depend on pre-release versions of the coreclr packages

**Comment by joeaudette** [comment]
that is strange, there are plenty of things published already, I have a pagination library here for dnxcore50 https://www.nuget.org/packages/cloudscribe.Web.Pagination/1.0.0-beta4

but then my packages are also pre-release beta versions. Maybe they only let you publish your own package as pre-release if it depends on other pre-release things.

I'm guessing you are trying to publish a single package for all your supported platforms and you don't want that package to be marked as pre-release. It looks like the way netwonsoft handled it was to mark their latest release as beta but they also have a stable release that maybe does not support dnxcore50

**Comment by jstedfast** [comment]
how do I make a beta package? just put -beta in the version string?

**Comment by joeaudette** [comment]
yes, like in my pagination library the project.json has

    "version": "1.0.0-beta4"

you can increment like -beta1 , -beta2 etc if you need to update the release later. I guess it will have to be beta until dotnetcore is in final release

**Comment by jstedfast** [comment]
ok, try this package: https://www.nuget.org/packages/MailKit/1.2.16-beta1

**Comment by joeaudette** [comment]
when I add a reference to the package I get an error that it could not resolve

 "System.Net.Sockets": "4.0.10-beta-23123",

I'm pretty sure that needs to be 23516 and similar with 

    "System.Net.Primitives": "4.0.11-beta-23409",

that you have in your project.json, it needs to be:

     "System.Net.Primitives": "4.0.11-beta-23516"

**Comment by jstedfast** [comment]
try beta2

**Comment by jstedfast** [comment]
The problem was that I named System.Net.Sockets as System.Security.Sockets

**Comment by joeaudette** [comment]
for some reason it is failing to get the package:

    
C:\_joe\__projects\__cloudscribe\_code\cloudscribe\src\cloudscribe.Messaging>dnu restore
Microsoft .NET Development Utility CoreClr-x86-1.0.0-rc1-16231

  CACHE https://api.nuget.org/v3/index.json
  CACHE https://api.nuget.org/v3/index.json
Restoring packages for C:\_joe\__projects\__cloudscribe\_code\cloudscribe\src\cloudscribe.Messaging\project.json
  CACHE https://api.nuget.org/v3-flatcontainer/mailkit/index.json
  CACHE https://api.nuget.org/v3-flatcontainer/mailkit/index.json
Unable to locate Dependency MailKit >= 1.2.16-beta2
Writing lock file C:\_joe\__projects\__cloudscribe\_code\cloudscribe\src\cloudscribe.Messaging\project.lock.json
Restore complete, 291ms elapsed

Errors in C:\_joe\__projects\__cloudscribe\_code\cloudscribe\src\cloudscribe.Messaging\project.json
    Unable to locate Dependency MailKit >= 1.2.16-beta2

NuGet Config files used:
    C:\Users\Joe\AppData\Roaming\NuGet\nuget.config
    C:\_joe\__projects\__cloudscribe\_code\cloudscribe\nuget.config

Feeds used:
    https://api.nuget.org/v3-flatcontainer/
    C:\_joe\__projects\__cloudscribe\nugetfeed

C:\_joe\__projects\__cloudscribe\_code\cloudscribe\src\cloudscribe.Messaging>

though I can see the package on the nuget site.

Though probably unrelated, I still contend that you have some version mistakes in your project.json as noted in my previous posts. Those version numbers are for older betas, all the System.* ones for rc1 should end with 23516

**Comment by jstedfast** [comment]
I already fixed those.

**Comment by joeaudette** [comment]
I'm just going by what I see here https://github.com/jstedfast/MailKit/blob/master/MailKit/project.json maybe you are working in a different branch or something.

I also notice that your project.json has only dnxcore50 as a target. My projects target both net451 and dnxcore50 which are the default targets if you create a new asp.net 5 webapp in vs 2015 so it would be good if we could use the same package for both of those targets.

I'm not sure if the problem I'm having now is some kind of feed cache issue. I'm a little scared to try

    dnu restore --no-cache

due to https://github.com/aspnet/dnx/issues/1835

**Comment by jstedfast** [comment]
I just hadn't committed my changes yet.

**Comment by jstedfast** [comment]
Can you install MimeKit? Maybe it's the minClientVersion="3.0"?

**Comment by joeaudette** [comment]
found how to clear the cache with

    dnu clear-http-cache

then it found the package, but when I try to build with some sample code I get:

C:\_joe\__projects\__cloudscribe\_code\cloudscribe\src\cloudscribe.Messaging\AuthMessageSender.cs(38,17,38,36): DNX Core 5.0 error CS1705: Assembly 'MailKit' with identity 'MailKit, Version=1.2.0.0, Culture=neutral, PublicKeyToken=null' uses 'System.Net.Primitives, Version=4.0.11.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' which has a higher version than referenced assembly 'System.Net.Primitives' with identity 'System.Net.Primitives, Version=4.0.10.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'

**Comment by joeaudette** [comment]
do you still want me to add MimeKit? What version should I reference?

**Comment by jstedfast** [comment]
1.2.17.2

**Comment by joeaudette** [comment]
I added MimeKit:

    "dependencies": {
    "MimeKit": "1.2.17.2",
    "MailKit": "1.2.16-beta2"
  },

still get the same error about System.Primitive on build

so you managed to publish a dnxcore50 package of mimekit without making it beta?

**Comment by joeaudette** [comment]
don't know if this is related but in your project.json I see

    "System.Runtime.Serialization.Primitives": "4.0.10",

but I can see that the latest version is really

    "System.Runtime.Serialization.Primitives": "4.1.0-beta-23516"

maybe there is some relation with that package and

    "System.Net.Primitives": "4.0.11-beta-23516",

**Comment by joeaudette** [comment]
for some reason if I add this to my own project dependencies:

    "System.Net.Primitives": "4.0.11-beta-23516"

the build error goes away, if I remove it it comes back

**Comment by jstedfast** [comment]
try now, I've created new MimeKit and MailKit packages with version 1.3.0-beta1

**Comment by joeaudette** [comment]
that is building fine now with those new versions, I was able to remove System.Net.Primitives from my own dependencies.
This is really fantastic! I will test actually sending email either later today or tomorrow and post to let you know all is good as I'm confident it will be.

Though I'm essentially unemployed at the moment and relatively broke, I just went and made a small donation on your pledgie page http://www.pledgie.com/campaigns/29300
because I am really grateful for what you've just done.

I think Microsoft should give you a generous donation since MailKit will solve what would otherwise be a major problem for developers porting their web apps to dnxcore50. They may never need to get around to implementing System.Net.Mail, MailKit will likely be the defacto way to send email for ASP.NET 5. I will help spread the word to others that they can use MailKit now on dnxcore50!

**Comment by jstedfast** [comment]
Thanks! Let me know if you run into any issues.

**Comment by joeaudette** [comment]
I have to apologize because I promised to test this back in December but I'm just getting around to it now because I got sidetracked on another project. 

I just now tried to send a message and I got an error:

    IOException: The handshake failed due to an unexpected packet format.
    System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes,    AsyncProtocolRequest asyncRequest)
    System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
    System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
    System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
    System.Net.Security.SslState.ForceAuthentication(Boolean receiveFirst, Byte[] buffer, AsyncProtocolRequest asyncRequest)
    System.Net.Security.SslState.ProcessAuthentication(LazyAsyncResult lazyResult)
    System.Net.Security.SslStream.AuthenticateAsClient(String targetHost, X509CertificateCollection clientCertificates, SslProtocols enabledSslProtocols, Boolean checkCertificateRevocation)
    MailKit.Net.Smtp.SmtpClient.Connect(String host, Int32 port, SecureSocketOptions options, CancellationToken cancellationToken)
    MailKit.MailService.<>c__DisplayClass38_0.<ConnectAsync>b__0()
    System.Threading.Tasks.Task.InnerInvoke()

I'm using:

    "MimeKit": "1.3.0-beta5",
    "MailKit": "1.3.0-beta5"

**Comment by jstedfast** [comment]
I just got a report last night that SslStream.AuthenticateAsClient() is missing in nightly builds of RC2, so I might need to use some other solution for SSL/TLS. Hopefully that's just a bug, though.

**Comment by joeaudette** [comment]
I'm still on RC1 here. Seems like the error would be missingmethodexception if that were the problem.
Based on some googling of the error I tried adding a ServerCertificateValidationCallback that returns true but the error did not change, my code is like this:

    public async Task SendEmailAsync(
            SmtpOptions smtpOptions,
            string to,
            string from,
            string subject,
            string message)
        {
            var m = new MimeMessage();
           
            m.From.Add(new MailboxAddress("", from));
            m.To.Add(new MailboxAddress("", to));
            m.Subject = subject;
            m.Body = new TextPart("plain") { Text = message };

            using (var client = new SmtpClient())
            {
                client.ServerCertificateValidationCallback = delegate (
                    Object obj, X509Certificate certificate, X509Chain chain,
                    SslPolicyErrors errors)
                {
                    return (true);
                };

                await client.ConnectAsync(smtpOptions.Server, smtpOptions.Port, smtpOptions.UseSsl);
                
                // Note: since we don't have an OAuth2 token, disable
                // the XOAUTH2 authentication mechanism.
                client.AuthenticationMechanisms.Remove("XOAUTH2");

                // Note: only needed if the SMTP server requires authentication
                if(smtpOptions.RequiresAuthentication)
                {
                    client.Authenticate(smtpOptions.User, smtpOptions.Password);
                }
                

                client.Send(m);
                client.Disconnect(true);
            }

        }

**Comment by akoeplinger** [comment]
@jstedfast the sync versions were removed (https://github.com/dotnet/corefx/pull/4868), only the async versions like AuthenticateAsClientAsync remain.

**Comment by jstedfast** [comment]
@joeaudette Sorry, I didn't meant to say that the reason for the failure in your case was a missing method, just that there seems to be development going on around AuthenticateAsClient and thus the disappearance of that method from RC2 might be related.

@akoeplinger ah, thanks.

**Comment by joeaudette** [comment]
so, what should I do at this point, just wait for coreclr RC2 to be released and try again?

**Comment by jstedfast** [comment]
So one place where that error can be thrown from what I can tell is if you connect to a plain-text port and then try to send an SSL handshake (which is what AuthenticateAsClient does).

Is it possible that you are connecting to a non-SSL port?

**Comment by joeaudette** [comment]
I'm testing against [elastic email smtp relay](https://elasticemail.com/support/smtp-cms/smtp-relay) using port 2525 which they say is a TLS port, but it looks like there are a few supported ports so I could try one of the others, though in my account settings there they indicate 2525 specifically. It appears they have alternate non ssl settings I can try on port 25. I'll report back after trying a few things.

**Comment by jstedfast** [comment]
Sometimes when someone claims a port is a "TLS" port, what they mean is that the client should send a STARTTLS request to toggle into TLS mode, but until then, it is a plain-text port.

I don't know if that's the case here or not.

**Comment by joeaudette** [comment]
is there a way I can try that?

**Comment by jstedfast** [comment]
yea, just change your `client.Connect(...)` logic to `client.Connect(smtpOptions.Server, smtpOptions.Port, SecureSocketOptions.StartTLS)`

**Comment by joeaudette** [comment]
I got the same error trying with SecureSocketOptions.StartTLS

It did work when I changed to use the non ssl settings though that is not ideal. I will experiment with the other ssl ports they provide.

**Comment by jstedfast** [comment]
Okay, so it sounds like 2525 might really be an SSL-wrapped port (e.g. you need SSL/TLS immediately when you connect after all).

Sadly I'm not sure how to work around this issue unless I can just make the code use AuthenticateAsClientAsync() and it'll magically work.

**Comment by joeaudette** [comment]
Good news, when I switched to port 465 it worked with ssl!

**Comment by joeaudette** [comment]
Thanks for your great support!

**Comment by mogarick** [comment]
Hi @joeaudette and @jstedfast!
Could you please share example code about using the MailKit to send email with .Net core CLR? I'm newbie with .Net platform (started with .Net 5/core just a week ago. I come from Java, PHP & JS world) and developing in Mac OSX with VS Code.

Thank you in advance!!

**Comment by joeaudette** [comment]
I have some example code here that works https://github.com/joeaudette/cloudscribe/blob/master/src/cloudscribe.Messaging.Email/EmailSender.cs

**Comment by mogarick** [comment]
Thank you @joeaudette .

I'll check it out. I the mean time, I opened an issue (#293) because I'm having a `System.Net.Security` assembly not found or something like that. Do you have any idea why this could be happening? 

Thank you!

**Comment by michielpost** [comment]
I can't install MailKit in a ASP.Net 5 Class Library that targets the framework dotnet5.4.
I can install it in a ASP.net 5 website, because webapps target dnx451 and dnxcore50 framework. But class libraries have the frameworks net451 and dotnet5.4.

`The dependency MailKit 1.3.0-beta6 in project MyProject.Services does not support framework .NETPlatform,Version=v5.4.`

Can you add support for that?

**Comment by Maxwe11** [comment]
>I can't install MailKit in a ASP.Net 5 Class Library that targets the framework dotnet5.4.

#298

**Comment by jstedfast** [comment]
@michielpost Unfortunately, dotnet54 is missing System.Net.Sockets (and I think a few other APIs) that would make it impossible to support MailKit on.

Perhaps I can try adding support for net451, though.

**Comment by jstedfast** [comment]
FWIW, if you bump your class library to dotnet5.5, you can install MailKit.

**Comment by michielpost** [comment]
Thanks. I thought dnxcore50 supported exactly the same as dotnet5.4. Using dotnet5.5 now and that works. Didn't know that, thanks!

**Comment by PabloZaiden** [comment]
Hi! With the new dotnet cli (dnx + dnu + dnvm is now deprecated) the package is not working
When trying to restore packages I'm getting:

```
Package MailKit 1.3.0-beta7 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). Package MailKit 1.3.0-beta7 supports:
      - dotnet5.5 (.NETPlatform,Version=v5.5)
      - monoandroid10 (MonoAndroid,Version=v1.0)
      - net40 (.NETFramework,Version=v4.0)
      - net45 (.NETFramework,Version=v4.5)
      - net451 (.NETFramework,Version=v4.5.1)
      - win81 (Windows,Version=v8.1)
      - wpa81 (WindowsPhoneApp,Version=v8.1)
      - xamarinios10 (Xamarin.iOS,Version=v1.0)
    One or more packages are incompatible with .NETCoreApp,Version=v1.0.
```

The repo with the official sample projects is: dotnet cli samples

**Comment by Ciantic** [comment]
I think the project needs to update for RC2 to "netstandard", old name was "dotnet". Is there beta release somewhere with RC2 support?

**Comment by joeaudette** [comment]
rc2 has not been released yet

**Comment by ssg** [comment]
It got released yesterday.

**Comment by jstedfast** [comment]
Yep, I know. I'll make a new release this weekend when I have enough time to sit down and install all of the updates :)

**Comment by joeaudette** [comment]
I've already updated my projects to ASP.NET Core RTM, and MailKit/MimeKit seem to be working fine for me, I'm able to send email.

**Comment by jstedfast** [comment]
Hey guys, I ended up installing the Core updates last night and was able to make updated releases of MimeKit and MailKit 1.4.0 this morning to nuget.org. Enjoy! :)

**Comment by joeaudette** [comment]
Awesome! Thank you!
