### ISSUE TITLE
SMPP?

### ISSUE THREAD

**Issue by di48l069** [jstedfast/MailKit#217]
Hi, Is there any chance MailKit supports SMPP?

**Comment by jstedfast** [comment]
Sorry, it does not support SMPP. I'm not sure it would even be the right fit? I don't know much about SMS, but I thought it was completely different from email?

**Comment by di48l069** [comment]
It is completely different but was just asking because i'm looking SMPP library just thought MailKit would support it, but thanks @jstedfast

**Comment by jstedfast** [comment]
No problem. Hope you find something that does SMS/SMPP.
