### ISSUE TITLE
How to download the attachments from a specified mail?

### ISSUE THREAD

**Issue by githubxiaowen** [jstedfast/MailKit#219]
Thank you for your MailKit ! I've been developing a mail cliient and imported the two libraries.The problem is that I couldn't get the attachments from a email.Can you help me with that? A simple code will do great help.
PS.I am using ImapClient.

**Comment by jstedfast** [comment]
If you have the full `MimeMessage` object, you can do:

```csharp
foreach (var attachment in message.Attachments) {
    // do stuff
}
```

Or if you have not downloaded the full message, you can do:

```csharp
var items = client.Inbox.Fetch (0, -1, MessageSummaryItems.UniqueId | MessageSummaryItems.BodyStructure);
foreach (var item in items) {
    foreach (var attachment in item.Attachments) {
        // do stuff
    }
}
```
