### ISSUE TITLE
Unexpected token in IMAP response: '\n'

### ISSUE THREAD

**Issue by githubxiaowen** [jstedfast/MailKit#225]
Sometimes I got this exception:
Unexpected token in IMAP response: '\n'
MailKit.Net.Imap.ImapProtocolException”Exception occurs in MailKit.dll

**Comment by jstedfast** [comment]
Can you get a [protocol log](https://github.com/jstedfast/MailKit/blob/master/FAQ.md#ProtocolLog) to figure out when this happens?

Odds are that your IMAP server is broken.

**Comment by jstedfast** [comment]
any luck getting a protocol log and figuring out the cause? Was it a bug in the server?

**Comment by githubxiaowen** [comment]
Thanks for your help ! I don't know if this is the part you need.

S: A00000001 OK Success
C: A00000002 LIST "" "INBOX"
S: * LIST (\HasNoChildren) "/" "INBOX"
S: A00000002 OK LIST completed
C: A00000003 EXAMINE INBOX
S: * 101 EXISTS
S: * 0 RECENT
S: * OK [UNSEEN 27]
S: * OK [UIDVALIDITY 1316352875] UID validity status
S: * OK [UIDNEXT 5765] Predicted next UID
S: * FLAGS (\Answered \Flagged \Deleted \Draft \Seen)
S: * OK [PERMANENTFLAGS ()] No permanent flags permitted
S: A00000003 OK [READ-ONLY] EXAMINE complete
C: A00000004 UID SEARCH ALL
S: * SEARCH 5660 5661 5662 5663 5664 5665 5666 5667 5668 5669 5670 5671 5672 5673 5674 5675 5676 5677 5678 5679 5680 5681 5682 5683 5684 5685 5686 5687 5688 5689 5690 5691 5692 5693 5694 5695 5696 5697 5698 5699 5700 5701 5702 5703 5704 5705 5706 5707 5708 5709 5710 5711 5712 5713 5714 5715 5716 5717 5718 5719 5720 5721 5722 5723 5724 5725 5726 5727 5728 5729 5730 5733 5734 5736 5737 5739 5740 5741 5742 5743 5744 5745 5746 5747 5748 5749 5750 5751 5752 5753 5754 5755 5756 5757 5758 5759 5760 5761 5762 5763 5764
..
...
....
S: A00000071 OK UID FETCH completed
C: A00000072 UID FETCH 5727 (BODY.PEEK[])
S: 
S: )
S: A00000072 OK UID FETCH completed
What should I do with this?

**Comment by jstedfast** [comment]
This is the problem:

```
C: A00000072 UID FETCH 5727 (BODY.PEEK[])
S: 
S: )
S: A00000072 OK UID FETCH completed
```

This tells me that MailKit is requesting the message for UID 5727 and the server is returning:

```
S: 
S: )
S: A00000072 OK UID FETCH completed
```

which makes no sense.

The server *SHOULD* respond with something more like this (assuming the message is just a blank line):

```
S: * <message index> FETCH (BODY {2}
S: 
S: )
S: A00000072 OK UID FETCH completed
```

What server is this? I'd recommend reporting a bug to them.
