### ISSUE TITLE
Control SSL/TLS supported protocols

### ISSUE THREAD

**Issue by Saurbaum** [jstedfast/MailKit#229]
Something we have been doing for security recently is restricting the protocol that we will accept to a minimum from SSL 3.0, TLS 1.0 or TLS 1.1

Is there a way to reject connections based on the protocol in MailKit?

**Comment by jstedfast** [comment]
MailKit currently restricts SSL/TLS connections to TLSv1.0 or higher (i.e. it does not allow SSLv3 or older).

I've just added a public accessor to override the defaults.

**Comment by Saurbaum** [comment]
Thanks for the fast turn around.  Did you realise your builds on windows aren't running according to your front page widget?

**Comment by jstedfast** [comment]
There's some sort of NuGet breakage on AppVeyor wrt them installing Visual Studio 2015 that I have no idea how to fix or work around.

It builds completely fine for me, though, and I also have Visual Studio 2015 installed.
