### ISSUE TITLE
Incorrect decoding when receiving email with UTF-8 (Japanese) Subject

### ISSUE THREAD

**Issue by nallar** [jstedfast/MailKit#234]
When receiving the email with the following headers from an IMAP server: https://gist.github.com/nallar/7ade79a76297edc908e1

Subject from header is `Subject: =?UTF-8?B?RndkOiDjgI7jg53jgrHjg6Ljg7Mgzqnjg6vjg5Pjg7zjg7vOseOCteODleOCoeOCpOOCog==?=
	=?UTF-8?B?44CP44KS44OX44Os44Kk44GV44KM44Gf55qG44GV44G+44G4IDcyMOeorumhnuOBruODneOCseODog==?=
	=?UTF-8?B?44Oz44GM5Yui44Ge44KN44GE77yBM0RT5pyA5paw44K944OV44OI44Gu44GK44GX44KJ44Gb44Gn44GZ?=`

The Subject is decoded as `Fwd: ????? O???�a????????????????? 720????????????!3DS????????????` (from MimeMessage.Subject)

The expected result is `Fwd: 『ポケモン Ωルビー・αサファイア』をプレイされた皆さまへ 720種類のポケモンが勢ぞろい！3DS最新ソフトのおしらせです`

The subject is retrieved from msg.Subject, and the body is retrieved from msg.HtmlBody. The same issue happens with all non-ASCII text in the email body. Connecting to the same IMAP server with thunderbird results in the expected subject and body.

I've sent the full .eml of the broken email to your email address from your github profile in case that helps with testing.

PS: I'm not sure if this is a MimeKit issue or a MailKit issue, sorry if I reported this in the wrong place :(

**Comment by jstedfast** [comment]
I added a unit test to MimeKit to test this and it decodes just fine.

Perhaps you are using an old version of MimeKit?

**Comment by nallar** [comment]
I'm using Mimekit `1.2.10` from Nuget. Have there been header encoding related changes since the last release there?

I'll try to make a minimum reproducible test-case on Monday  - going home for the weekend in a few minutes.

Thanks for the speedy response.

**Comment by jstedfast** [comment]
MimeKit 1.2.10 is the latest version and there have been no changes to header parsing since then.

I suspect the problem is that whatever you are using to display the decoded text is not using the Japanese fonts to render the text and that's why you are getting a bunch of ?'s.

I just tested printing the body text and that decoded and rendered correctly for me as well.

Here was my test program:

```csharp
using System;
using System.IO;
using System.Diagnostics;

using MimeKit;

namespace MboxParser {
	class Program
	{
		public static void Main (string[] args)
		{
			using (var stream = File.OpenRead (args[0])) {
				var message = MimeMessage.Load (stream);
				Console.WriteLine ("Subject: {0}", message.Subject);
				Console.WriteLine ("Body: {0}", message.TextBody);
			}
		}
	}
}
```

I've replied to your email with the output I am getting from this test program.

**Comment by nallar** [comment]
I hadn't configured log4net to use UTF8 for the UDP appender - just the file appender. Sorry for wasting your time :(

At least you got a new unit test?

**Comment by jstedfast** [comment]
No worries, I figured something like that must have been the case.

More unit tests never hurt. I'd like to get to 80+% coverage (currently sitting at around 75%)
