### ISSUE TITLE
Possible bug?

### ISSUE THREAD

**Issue by Sicos1977** [jstedfast/MailKit#235]
Hi,

A question about the authentication mechanisms to an Exchange 2013 server.
See the log below... 

What happens, I see that the first authentication fails, Exchange then sends back the response
 S: P00000001 NO AUTHENTICATE failed. 
C: P00000002 AUTHENTICATE PLAIN

After that a base64 encoded account and password is sent to the Exchange server. This also fails... When I take the base64 string from the logging and decode it then I see that the account name and password are concatenated together like this

eurtld\[accountname][password] ... so how does Exchange know what the account name is and what the password is?

Greetings,
Kees van Spelde

Connected to imap://mail.a3cd.local:143/ 
S: * OK The Microsoft Exchange IMAP4 service is ready. 
C: P00000000 CAPABILITY 
S: * CAPABILITY IMAP4 IMAP4rev1 AUTH=PLAIN AUTH=NTLM AUTH=GSSAPI STARTTLS UIDPLUS MOVE ID CHILDREN IDLE NAMESPACE LITERAL+
 S: P00000000 OK CAPABILITY completed. 
C: P00000001 AUTHENTICATE NTLM 
S: + 
... 
S: + TlRMTVNTUAACAAAACAAIADgAAAAFAokCnwWs9dU4eOIAAAAAAAAAAJ4AngBAAAAABgLwIwAAAA9BADMAQwBEAAIACABBADMAQwBEAAEAGgBBAEMASABXAEIAUwBUAEUAWABDADAAMAA3AAQAFABhADMAYwBkAC4AbABvAGMAYQBsAAMAMABBAEMASABXAEIAUwBUAEUAWABDADAAMAA3AC4AYQAzAGMAZAAuAGwAbwBjAGEAbAAFABQAYQAzAGMAZAAuAGwAbwBjAGEAbAAHAAgApi8TqhPh0AEAAAAA
 C: TlRMTVNTUAADAAAAGAAYAGwAAAAYABgAhAAAAAwADABAAAAAIAAgAEwAAAAAAAAAbAAAAAAAAACcAAAAAZIIAGUAdQByAHQAbABkAGEAYQBfAGcAaQB0AHMAXwBkAGQAXwB6AGsAXwBoAGMAMTgtzHD6zLsAAAAAAAAAAAAAAAAAAAAAkS7gf+93nTx7lF/BjMi6EKFbmsce+eWh
 S: P00000001 NO AUTHENTICATE failed. 
C: P00000002 AUTHENTICATE PLAIN 
S: + 
C: BASE 64 encoded account and password
S: P00000002 NO AUTHENTICATE failed. 
... 
S: P00000003 NO Server Unavailable. 15 
S: * BYE Connection closed. 14

**Comment by jstedfast** [comment]
There should be a nul byte between the username and password strings.

You can see the code here:

https://github.com/jstedfast/MailKit/blob/master/MailKit/Security/SaslMechanismPlain.cs#L104

**Comment by Sicos1977** [comment]
Hi jstedfast,

 If possible can you then please remove this complete thread? Someone in the company where I work complained that I was leaking a password in the base 64 encoded data that was in the originally post that I did post .... which was not the case. .. because I removed it before posting the log.  They also did not even decido the base 64 string to see them self. But to make them happy if possible please remove this thread. 

Greetings, 

Kees can Spelde

**Comment by jstedfast** [comment]
I don't think I can delete the thread, I can only delete the comments replying to the original issue reported.

**Comment by mwpowellhtx** [comment]
Sounds like a case of poor judgment. Once it's out there, it's out there.

**Comment by Sicos1977** [comment]
Thanks


Verzonden vanaf mijn Samsung-apparaat

-------- Oorspronkelijk bericht --------
Van: Jeffrey Stedfast <notifications@github.com> 
Datum: 04-02-2016  19:16  (GMT+01:00) 
Aan: jstedfast/MailKit <MailKit@noreply.github.com> 
Cc: Kees <magic-sessions@home.nl> 
Onderwerp: Re: [MailKit] Possible bug? (#235) 

I don't think I can delete the thread, I can only delete the comments replying to the original issue reported.
