### ISSUE TITLE
Self Signed certificates

### ISSUE THREAD

**Issue by Saurbaum** [jstedfast/MailKit#236]
I had a trawl through the documentation but didn't spot anything so apologies if the answer is in there.

Is it possible to support a Self Signed SSL certificate in MailKit?  I couldn't tell if I'd properly set up my server with one or not but I couldn't connect and couldn't find a way to make MailKit accept them.

**Comment by jstedfast** [comment]
Yes, it's possible. What you'll need to do is set the [ServerCertificateValidationCallback](http://www.mimekit.net/docs/html/P_MailKit_MailService_ServerCertificateValidationCallback.htm) property on the SmtpClient, Pop3Client, or ImapClient that you are using.
