### ISSUE TITLE
Read / Convert from .msg to .eml format

### ISSUE THREAD

**Issue by matt2003** [jstedfast/MailKit#238]
This program seems really full featured, there was one thing that would be great. Reading / loading a outlook .msg file and converting it to .eml format!

Thank you in advance

**Comment by jstedfast** [comment]
There is no format specification that I know of for Outlook .eml format, so I will not be implementing support for it (MimeKit and MailKit are designed for the standards-compliant formats, not Outlook-specific compatibility).

Sorry.

**Comment by jstedfast** [comment]
Here's what the web says about the Outlook .msg format:

```
MSG files are outlook messages saved as files.
They are saved as "COM stuctured storage OLE2 compound documents" or "DocFile", which is the
same technique used by Word, Excel and many many more.
```

That does not sound at all exciting to implement.

MimeKit and MailKit are meant to be cross-platform which means anything COM or OLE2 are unfeasible because there's no way to support them in a cross-platform way without implementing millions of lines of compatibility code.

**Comment by matt2003** [comment]
Hi, I understand. msg was the outlook format eml being the mime type. The only reason I asked was that some paid packages and msg reader on GitHub do convert between the two formats but only on the desktop windows and Mac but not on xamarin.ios which uses a subset of he .net framework. So I was curious if you had this converter as well since your package was actually compatible with xamarin.ios but I can certainly understand that this might be quite painful to implement from scratch and potentially without the interop classes and p invokes that some of these packages use to do it since that is not available on .net compact framework.ThanksMatt

Sent from Outlook




On Wed, Sep 2, 2015 at 7:09 AM -0700, "Jeffrey Stedfast" <notifications@github.com> wrote:












There is no format specification that I know of for Outlook .eml format, so I will not be implementing support for it (MimeKit and MailKit are designed for the standards-compliant formats, not Outlook-specific compatibility).



Sorry.

**Comment by jstedfast** [comment]
I suspect the other libraries that do it only actually work on Windows since it probably requires native COM and OLE2 support. I could be wrong, though.
