### ISSUE TITLE
Copying message throws Protocol Exception

### ISSUE THREAD

**Issue by neolution-ch** [jstedfast/MailKit#240]
Calling `CopyTo()` actually copies the message successfully on the server but throws this Exception afterwards
`[MailKit.Net.Imap.ImapProtocolException] {"Unexpected token in IMAP response: [atom: 0]"}`

Previously I have used `MoveTo()` but ended with the same exception (and even the same log).

Code:
```
inbox.Open(FolderAccess.ReadWrite);

var trash = client.GetFolder("Deleted Items");
foreach (var uniqueId in uniqueIds)
{
    inbox.CopyTo(uniqueId, trash);
    inbox.AddFlags(uniqueId, MessageFlags.Deleted, true);
}
```

Protocol Logger:
```
C: B00000004 XLIST "" "*"
S: * XLIST (\Unmarked \Trash) "/" "Deleted Items"
S: * XLIST (\Unmarked \Inbox) "/" "Inbox"
S: * XLIST (\Unmarked \Spam) "/" "Junk E-Mail"
S: * XLIST (\Unmarked \Sent) "/" "Sent Items"
S: * XLIST (\Unmarked) "/" "Trash"
S: B00000004 OK XLIST completed
C: B00000005 SELECT Inbox
S: * 1 EXISTS
S: * 0 RECENT
S: * OK [UIDVALIDITY 0] UIDs valid
S: * OK [UIDNEXT 36] Predicted next UID
S: * FLAGS (\Answered \Flagged \Deleted \Seen \Draft)
S: * OK [PERMANENTFLAGS (\Answered \Flagged \Deleted \Seen \Draft)]
S: B00000005 OK [READ-WRITE] SELECT completed
C: B00000006 UID COPY 35 "Deleted Items"
S: B00000006 OK [COPYUID 0 35 41] UID COPY completed
```

**Comment by jstedfast** [comment]
The exception is being thrown because this value is 0:

```
S: B00000006 OK [COPYUID 0 35 41] UID COPY completed
-------------------------^
```

That value is supposed to be the UIDVALIDITY of the destination folder which is not allowed to be `0`.

Syntax from the IMAP specifications:

```
resp_code_copy ::= "COPYUID" SPACE nz_number SPACE set SPACE set
nz-number       = digit-nz *DIGIT
                    ; Non-zero unsigned 32-bit integer
                    ; (0 < n < 4,294,967,296)
```

**Comment by jstedfast** [comment]
Your IMAP server is broken, please submit a bug report to the appropriate party.

**Comment by jstedfast** [comment]
FWIW, this is another bug in your IMAP server:

```
S: * OK [UIDVALIDITY 0] UIDs valid
```

Once again, it has declared the UIDVALIDITY of a folder to be 0.

This is NOT ALLOWED.

I would strongly advise you to use a different IMAP server as referring to messages based on UID for your IMAP server will be unreliable since the UIDVALIDITY value cannot be trusted.

**Comment by jstedfast** [comment]
Hint: You can make your code more efficient by doing this:

```csharp
inbox.Open(FolderAccess.ReadWrite);

var trash = client.GetFolder("Deleted Items");
inbox.CopyTo(uniqueIds, trash);
inbox.AddFlags(uniqueIds, MessageFlags.Deleted, true);
```

**Comment by neolution-ch** [comment]
Thanks for your fast reply! 

It's a test mail server ([SmarterMail](http://www.smartertools.com/smartermail/mail-server-software.aspx) fyi). I created the loop just for debugging purposes. Before that I had the code just like in your last comment, but with `MoveTo()` instead of `CopyTo()`.

**Comment by tomwell** [comment]
I'm having the same problem mentioned above, but I still can not fix it.
This is my code:

 if (flag != MessageFlags.None)
          sourceFolder.SetFlags(uidsList, flag, true);

 sourceFolder.MoveTo(uidsList, targetFolder);


Below is the log:

Connected to imaps://outlook.office365.com:993/
S: * OK The Microsoft Exchange IMAP4 service is ready. [RgBSADEAUABSADgAMABDAEEAMAAwADMAMAAuAGwAYQBtAHAAcgBkADgAMAAuAHAAcgBvAGQALgBvAHUAdABsAG8AbwBrAC4AYwBvAG0A]
C: G00000000 CAPABILITY
S: * CAPABILITY IMAP4 IMAP4rev1 AUTH=PLAIN AUTH=XOAUTH2 SASL-IR UIDPLUS MOVE ID UNSELECT CHILDREN IDLE NAMESPACE LITERAL+
S: G00000000 OK CAPABILITY completed.
C: G00000001 AUTHENTICATE XOAUTH2 dXNlcj1teWludm9pY2VzQHN1cHBseXRpLmNvbS5icgFhdXRoPUJlYXJlciBKdW5vMjYyNQEB
S: G00000001 NO AUTHENTICATE failed.
C: G00000002 AUTHENTICATE PLAIN AG15aW52b2ljZXNAc3VwcGx5dGkuY29tLmJyAEp1bm8yNjI1
S: G00000002 OK AUTHENTICATE completed.
C: G00000003 CAPABILITY
S: * CAPABILITY IMAP4 IMAP4rev1 AUTH=PLAIN AUTH=XOAUTH2 SASL-IR UIDPLUS MOVE ID UNSELECT CLIENTACCESSRULES CLIENTNETWORKPRESENCELOCATION BACKENDAUTHENTICATE CHILDREN IDLE NAMESPACE LITERAL+
S: G00000003 OK CAPABILITY completed.
C: G00000004 NAMESPACE
S: * NAMESPACE (("" "/")) NIL NIL
S: G00000004 OK NAMESPACE completed.
C: G00000005 LIST "" "INBOX"
S: * LIST (\Marked \HasChildren) "/" INBOX
S: G00000005 OK LIST completed.
C: G00000006 LIST "" "INBOX/Email N&AOM-o Importado"
S: * LIST (\Marked \HasNoChildren) "/" "INBOX/Email N&AOM-o Importado"
S: G00000006 OK LIST completed.
C: G00000007 SELECT INBOX
S: * 4239 EXISTS
S: * 0 RECENT
S: * FLAGS (\Seen \Answered \Flagged \Deleted \Draft $MDNSent)
S: * OK [PERMANENTFLAGS (\Seen \Answered \Flagged \Deleted \Draft $MDNSent)] Permanent flags
S: * OK [UNSEEN 1940] Is the first unseen message
S: * OK [UIDVALIDITY 14] UIDVALIDITY value
S: * OK [UIDNEXT 27157] The next unique identifier value
S: G00000007 OK [READ-WRITE] SELECT completed.
C: G00000008 UID STORE 10761,17473:17474,21129,21132,22962,23414,23416,26030,31957 FLAGS.SILENT (\Seen)
S: G00000008 OK STORE completed.
C: G00000009 UID MOVE 10761,17473:17474,21129,21132,22962,23414,23416,26030,31957 "INBOX/Email N&AOM-o Importado"
S: * OK [COPYUID 240  ]
S: G00000009 OK MOVE completed.

Need help!

**Comment by jstedfast** [comment]
Looks like your IMAP server is broken. The COPYUID response code does not contain all of the fields that it is supposed to have.

Here's the syntax specification:

```
resp_code_copy ::= "COPYUID" SPACE nz_number SPACE set SPACE set
nz-number       = digit-nz *DIGIT
                    ; Non-zero unsigned 32-bit integer
                    ; (0 < n < 4,294,967,296)
```

**Comment by jstedfast** [comment]
Has your destination folder ever been opened? If not, maybe try opening it. Maybe that will work around the server bug. You'll need to make sure to open the source folder before moving messages out of it, though.

**Comment by tomwell** [comment]
Regarding the code that passed me, I do not know how to apply, because I am, use a version for .NET and this code is formed internally. Is there any other way to implement this code via .NET?

Regarding opening a target folder, it is not possible, since ImapClient allows only one folder open at a time. Only the source folder is required to be open.

**Comment by tomwell** [comment]
This is the message:
MailKit.Net.Imap.ImapProtocolException
Syntax error in COPYUID response code. Unexpected token: ']'

**Comment by jstedfast** [comment]
I know only 1 folder can be opened at a time. I'm saying try opening the destination folder to make sure that the server has fully initialized it, then open the source folder and move messages from the source folder to the destination folder.

And yes, I figured what the exception would be - the COPYUID response code has too few arguments. Read the syntax definition I provided above. You'll see that you need *at least* 3 arguments to the COPYUID response code but your server only replied with 1.

**Comment by tomwell** [comment]
Eu entendi isso, só não sei como aplicar em .NET para corrigir o problema. Peço desculpas se pareci arrogante na mensagem anterior, não foi minha intenção.

**Comment by jstedfast** [comment]
You can't solve it with .NET, you have to file a bug report against your server to get them to fix it.

**Comment by tomwell** [comment]
I understood the previous message and forced the opening of the destination folder and then opened the source, but it still did not solve.

**Comment by tomwell** [comment]
Here is the code changed:

      OperFolder(ref targetFolder);
      OperFolder(ref sourceFolder);
      sourceFolder.SetFlags(uids, flag, true);
      sourceFolder.CopyTo(uids, targetFolder);

      sourceFolder.SetFlags(uids, MessageFlags.Deleted, true);
      sourceFolder.Expunge();


Unfortunately has not resolved yet

**Comment by tomwell** [comment]
Is there any differential setting for email from Outlook 365?

**Comment by jstedfast** [comment]
There's no special property in MailKit for Outlook 365

**Comment by tomwell** [comment]
Good afternoon!
I was able to solve the problem. It was a mistake in the programming itself. I search e-mails in 3 different folders and at the moment I tried to use "MoveTo" to the wrong source folder, this way it could not transfer messages from one folder to another.

Intership error.
