### ISSUE TITLE
deliveryMethod="specifiedPickupDirectory"?

### ISSUE THREAD

**Issue by KevinAndrewLipscomb** [jstedfast/MailKit#241]
I could very well be doing something stupid.  For eons I've built my web apps to use System.Net.Mail.SmtpClient to connect to localhost.  In my production environment there is an actual SMTP server running (IIS 6 SMTPSVC).  On my development environments, there is not.  Instead, the mail messages just got dropped into C:\inetpub\mailroot\Queue as .eml files, which I could open with a text editor or Thunderbird to inspect.

When I migrated from .NET 3.5 to 4.5.1, the arrangement I had in my development environments would no longer work until I added this to the Web.config:

`<system.net>`
`  <mailSettings>`
`    <smtp deliveryMethod="specifiedPickupDirectory">`
`      <specifiedPickupDirectory pickupDirectoryLocation="C:\inetpub\mailroot\Queue"/>`
`    </smtp>`
`  </mailSettings>`
`</system.net>`

Now I need DKIM.  But on the second line of this snippet...

  var mailkit_smtp_client = new MailKit.Net.Smtp.SmtpClient();
  mailkit_smtp_client.Connect(host:"localhost");

I get this exception:

  System.Net.Sockets.SocketException: A system call has failed 127.0.0.1:25

Could Connect() be revised to support this scenario?

**Comment by jstedfast** [comment]
Why not just use `message.WriteTo (@"C:\inetpub\mailroot\Queue\something.eml");`?

SmtpClient is for connecting to an SMTP server, not for saving files to disk.
