### ISSUE TITLE
IMAP Yahoo Mail: No 'Inbox' folder listed even in ImapClientDemo.iOS app

### ISSUE THREAD

**Issue by okertanov** [jstedfast/MailKit#242]
Connected to imaps://imap.mail.yahoo.com:993/
S: * OK [CAPABILITY IMAP4rev1 ID NAMESPACE X-ID-ACLID UIDPLUS LITERAL+ CHILDREN XAPPLEPUSHSERVICE XYMHIGHESTMODSEQ AUTH=PLAIN AUTH=LOGIN AUTH=XOAUTH2 AUTH=XYMCOOKIE AUTH=XYMECOOKIE AUTH=XYMCOOKIEB64 AUTH=XYMPKI] IMAP4rev1 imapgate-1.8.1_01.20166 imap1015.mail.ir2.yahoo.com
C: A00000000 AUTHENTICATE PLAIN
S: + 
C: AGFseW9uYS50ZXN0aW5nQHlhaG9vLmNvbQBxYXpxYXoxMg==
S: A00000000 OK AUTHENTICATE completed - Mailbox size in bytes is 34943485
C: A00000001 CAPABILITY
S: * CAPABILITY IMAP4rev1 ID NAMESPACE X-ID-ACLID UIDPLUS LITERAL+ XAPPLEPUSHSERVICE XYMHIGHESTMODSEQ
S: A00000001 OK CAPABILITY completed
C: A00000002 NAMESPACE
S: * NAMESPACE (("" "/")) NIL NIL
S: A00000002 OK NAMESPACE completed
C: A00000003 LIST "" "INBOX"
S: * LIST (\HasNoChildren) "/" "Inbox"
S: A00000003 OK LIST completed
C: A00000004 LIST "" "%"
S: * LIST (\HasNoChildren) "/" "Bulk Mail"
S: * LIST (\HasNoChildren) "/" "Draft"
S: * LIST (\HasNoChildren) "/" "Empty folder"
S: * LIST (\HasNoChildren) "/" "Inbox"
S: * LIST (\HasNoChildren) "/" "Manny Mailstest rename"
S: * LIST (\HasNoChildren) "/" "Notes"
S: * LIST (\HasNoChildren) "/" "Sent"
S: * LIST (\HasNoChildren) "/" "Test folder renamed"
S: * LIST (\HasNoChildren) "/" "TestFolderRenamedGG"
S: * LIST (\HasNoChildren) "/" "Top Layer"
S: * LIST (\HasNoChildren) "/" "Trash"
S: * LIST (\HasNoChildren) "/" "VladZ"
S: * LIST (\HasNoChildren) "/" "VladZ1"
S: * LIST (\HasNoChildren) "/" "folder name111"
S: A00000004 OK LIST completed
C: A00000005 LIST "" "Bulk Mail/%"
S: A00000005 OK LIST completed
C: A00000006 LIST "" "Draft/%"
S: A00000006 OK LIST completed
C: A00000007 LIST "" "Empty folder/%"
S: A00000007 OK LIST completed
C: A00000008 LIST "" "Manny Mailstest rename/%"
S: A00000008 OK LIST completed
C: A00000009 LIST "" "Notes/%"
S: A00000009 OK LIST completed
C: A00000010 LIST "" "Sent/%"
S: A00000010 OK LIST completed
C: A00000011 LIST "" "Test folder renamed/%"
S: A00000011 OK LIST completed
C: A00000012 LIST "" "TestFolderRenamedGG/%"
S: A00000012 OK LIST completed
C: A00000013 LIST "" "Top Layer/%"
S: A00000013 OK LIST completed
C: A00000014 LIST "" "Trash/%"
S: A00000014 OK LIST completed
C: A00000015 LIST "" "VladZ/%"
S: A00000015 OK LIST completed
C: A00000016 LIST "" "VladZ1/%"
S: A00000016 OK LIST completed
C: A00000017 LIST "" "folder name111/%"
S: A00000017 OK LIST completed

**Comment by jstedfast** [comment]
Should be fixed now.

**Comment by jstedfast** [comment]
Since this was a particularly inconvenient bug, I've released 1.2.11.1 to NuGet.

**Comment by okertanov** [comment]
Thanks!
