### ISSUE TITLE
Port keeps changing for IMAP

### ISSUE THREAD

**Issue by macupryk** [jstedfast/MailKit#243]
I have the following that works on my machine then when I connect to the network at work
the IP changes for IMAP

Error
{"A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 132.245.58.130:993"}

A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 132.245.36.34:993}

    <add key="SmtpServerName" value="smtp.office365.com" />
    <add key="SmtpPort" value="587" />
    <add key="ImapServerName" value="outlook.office365.com" />
    <add key="ImapPort" value="993" />

Code

```csharp
public static void ConnectImap()
{
    //if (ImapClient != null && !ImapClient.IsConnected)
    //{
        using (var client = new ImapClient())
        {
            client.Connect(AppSettings.ImapServerName, AppSettings.ImapPort, true);

            // Note: since we don't have an OAuth2 token, disable
            // the XOAUTH2 authentication mechanism.
            client.AuthenticationMechanisms.Remove("XOAUTH2");

            client.Authenticate(AppSettings.MailboxUserName, AppSettings.MailboxPassword);

            //// The Inbox folder is always available on all IMAP servers...
            Inbox = client.Inbox;
            SentItems = client.GetFolder("Sent Items");
            Inbox.Open(FolderAccess.ReadOnly);

            Console.WriteLine("Total messages: {0}", Inbox.Count);
            Console.WriteLine("Recent messages: {0}", Inbox.Recent);

            for (int i = 0; i < Inbox.Count; i++)
            {
                var message = Inbox.GetMessage(i);
                Console.WriteLine("Subject: {0}", message.Subject);
            }
        }
}
```

**Comment by jstedfast** [comment]
I don't see the port changing at all. In both error messages and in your configuration, it says port 993.

Where do you see it changing?

**Comment by macupryk** [comment]
Hi guys, I mean the IP.

**Comment by jstedfast** [comment]
That's up to your DNS server - when MailKit asks the DNS server to get the IP for "outlook.office365.com", the DNS server returns a different IP.

This is actually not at all surprising since outlook.office365.com uses a round-robin scheme (they couldn't handle the load of everyone in the world connecting to a single mail server)

**Comment by macupryk** [comment]
Yes, now that we know this is there a way to resolve this ? A work around.

**Comment by jstedfast** [comment]
Get a faster network? I dunno, the problem is that the TCP connection timed out - there's no code you can write to work around that.

**Comment by jstedfast** [comment]
You might also be behind a firewall that won't let packets out... talk to your network admin.

**Comment by macupryk** [comment]
But they will have to open every IP on that specific port?

**Comment by macupryk** [comment]
Our network is fast. So what else do I do?

**Comment by macupryk** [comment]
Can I send you the application? It is a small console.

**Comment by macupryk** [comment]
132.245.47.130:993

{"A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 157.56.239.18:993"}

Error
{"A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 132.245.58.130:993"}


A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 132.245.36.34:993}

**Comment by jstedfast** [comment]
It looks like the code you're using is the same code in my demo app, so I can already test that that code works locally :-)

Talk to your network administrator and ask him to look into whether there is a firewall blocking your app from connecting to outlook.office365.com on port 993.

There's nothing I can do.

**Comment by ps2goat** [comment]
Mine was blocked when on one of my VPNs.  :(
