### ISSUE TITLE
Can't open created msg file in Outlook

### ISSUE THREAD

**Issue by TNTGav** [jstedfast/MailKit#246]
Hello,

First of all, fantastic library - there has clearly been a lot of effort put into this, and I've been looking for something like this for what feels like an eternity.

I've just started playing about with MailKit - I have some basic code (based on the samples in this library) to download some messages from an IMAP Server:

```csharp
using (var client = new ImapClient(new ProtocolLogger("c:\\temp\\imap.log")))
{
     client.Connect("outlook.office365.com", 993, SecureSocketOptions.SslOnConnect);
     client.Authenticate("notmyreal@emailaddress.com", "hunter2");
     client.Inbox.Open(FolderAccess.ReadOnly);

     var uids = client.Inbox.Search(SearchQuery.All);

     foreach (var uid in uids)
     {
        var message = client.Inbox.GetMessage(uid);
        // write the message to a file
        message.WriteTo(string.Format("c:\\temp\\{0}.msg", uid));
     }
     client.Disconnect(true);
}
```

This works successfully and generates the IMAP log and creates the MSG files in said directory. The file will not open in Outlook, I've tried two different machines with Outlook 2013 installed, and tried to open all of them in a test machine with Outlook 2003 and 2007 installed.

In all instances I get this warning from Outlook:

"We can't open pathtomsg. It's possible the file is already open, or you don't have permission to open it. To check your permissions, right-click the file folder, then click properties."

If I open the MSG in notepad, it does seem to have the headers at the top followed by the content.

Any insight at all would be most appreciated, I've kind of fallen at the first hurdle here :)

**Comment by jstedfast** [comment]
Outlook's .msg format is not in the MIME format, for that I think you might need to use the .eml extension.

Beyond that, I don't know what the problem could be. The WriteTo() method disposes the stream, so that can't be the problem.
