### ISSUE TITLE
Xamarin Forms Profile support

### ISSUE THREAD

**Issue by AshD** [jstedfast/MailKit#249]
Tested out MailKit in a console app and it looks awesome. 

Trying to install this into my Xamarin Forms app and ran into a profile mis-match. Using the latest stable version of Xamarin Forms. 

Thanks,
Ash

PM> Install-Package MailKit

Install-Package : Could not install package 'MailKit 1.2.12'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile78', but the 
package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.
At line:1 char:1
+ Install-Package MailKit
+ ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand

**Comment by jstedfast** [comment]
MailKit can never support Xamarin.Forms because Xamarin.Forms has to support WindowsPhone 8.0 which does not have networking API's that are needed by MailKit. Nor does WindowsPhone 8 support unsafe code which is used quite a bit in Portable.Text.Encoding, MimeKit and MailKit.

I'm sorry, but what you are asking is not possible.

**Comment by AshD** [comment]
Thanks for the quick reply Jeff. 

I care about only the iOS and Android platforms. What would be the best way to get MailKit to work?

Is it possible to tweak my Xamarin Forms portable library profile to support only Xamarin iOS and Android and still get nuget to install it. 

Thanks,
Ash

**Comment by jstedfast** [comment]
You could probably edit the Project Options for your project and change which PCL profile they are to something that does not include Windows Phone 8
