### ISSUE TITLE
Connecting to inmotionhosting IMAP server fails wit an excpetion

### ISSUE THREAD

**Issue by bitdisaster** [jstedfast/MailKit#250]
We connect to a wide variety of IMAP server but with this particular one we have a problem. 
We see the exception below  when calling imapClient.ConnectAsync()

{"Unexpected token in IMAP greeting: [atom: 220-ld138.inmotionhosting.com]"}

**Comment by jstedfast** [comment]
Can you get me the first line of text that the IMAP server responds with?

MailKit expects "* OK" conditionally followed by either a newline or a list of capabilities within square brackets. It will also handle arbitrary text after the OK.

You can see the logic for parsing the connection response here: https://github.com/jstedfast/MailKit/blob/master/MailKit/Net/Imap/ImapEngine.cs#L553

My *guess* is that your IMAP server is responding with:

```
220-ld138.inmotionhosting.com OK
```

(or something like that)

My first suggestion would be to make sure you're not connecting to the POP3 port or something (they have different responses that they send when the client connects).

**Comment by jstedfast** [comment]
Actually, on closer inspection of the response... the leading "220-" suggests that you are connecting on the SMTP port and not the IMAP port.
