### ISSUE TITLE
Load message info from .imap file

### ISSUE THREAD

**Issue by FishTailTea6** [jstedfast/MailKit#253]
Could you please let me know if it is possible to load saved mail message (xyz.imap) that has been already saved to a local folder, e.g. C:\Users\xxx\DOcuments\SavedMessages to the MimeMessage object?

**Comment by jstedfast** [comment]
Yes.

Use one of the [MimeMessage.Load()](http://www.mimekit.net/docs/html/Overload_MimeKit_MimeMessage_Load.htm) methods.
