### ISSUE TITLE
Subfolder 'INBOX/Inbox' not returned

### ISSUE THREAD

**Issue by bardisco** [jstedfast/MailKit#255]
If the INBOX of a mailbox contains a subfolder with the name 'Inbox', the folder is not returned when retrieving the subfolders for the INBOX.

Folder structure in the mailbox:

	INBOX
	- Inbox
	- subfolder1
	- Subfolder2

Code to retrieve the folders:

	var inbox = imapClient.Inbox;
	var folders = inbox.GetSubfolders();
	foreach (var folder in folders)
	{
		Console.WriteLine(folder.FullName);
	}

	imapClient.Disconnect(true);

Output written by the testcode:

	INBOX/subfolder1
	INBOX/subfolder2
	
	
Protocollogging:
C: A00000003 NAMESPACE
S: * NAMESPACE (("" "/")) NIL NIL
S: A00000003 OK NAMESPACE completed
C: A00000004 LIST "" "INBOX"
S: * LIST (\HasChildren) "/" INBOX
S: A00000004 OK LIST completed
C: A00000005 LIST "" "INBOX/%"
S: * LIST (\HasNoChildren) "/" INBOX/Inbox
S: * LIST (\HasNoChildren) "/" INBOX/subfolder1
S: * LIST (\HasNoChildren) "/" INBOX/subfolder2
S: A00000005 OK LIST completed

**Comment by jstedfast** [comment]
I don't have a server that I can test this on, but I think my above patch will fix this.

If you could test it, that would be fantastic.

**Comment by bardisco** [comment]
The patch works great. The expected result is now returned

    INBOX/Inbox
    INBOX/subfolder1
    INBOX/subfolder2

**Comment by jstedfast** [comment]
great!
