### ISSUE TITLE
Sending mail via SMTP aborts if a user is unknown

### ISSUE THREAD

**Issue by TimTheTinker** [jstedfast/MailKit#256]
It would be really great if there was an option to specifically ignore `550 [...] User unknown`.

Thanks for this great utility!

**Comment by jstedfast** [comment]
I'm honestly having trouble understanding the use-case for this. Normally, if an address doesn't exist, you need to abort sending the message and notify the user that one of the addresses does not exist and allow the user to fix it/remove it and then send again.

Allowing the message to go through is just awkward unless you are writing a mass mailer that doesn't care if addresses are invalid/unavailable.

I'm also not really keen on adding awkward bool properties to SmtpClient to specify corner-case behaviors.

**Comment by TimTheTinker** [comment]
I'm using MimeKit/MailKit to send automated notification emails internally from an intranet application. From time to time, I receive a "Hey! So and so did not get notified of XYZ" email, and it's always been a problem outside of my control -- either an alias isn't configured correctly or they accidentally added someone to a form who doesn't work here anymore, etc.

Manually checking each email against the internal LDAP database could solve _some_ of the problem, but even then there are issues that would only show up in the SMTP session with a `550` error, like aliases that aren't configured correctly.

In my opinion, the best solution would be for the app to send the emails anyway and notify the responsible devs of the problem.

**Comment by TimTheTinker** [comment]
I'd be happy if you only marked SmtpClient#ProcessMailFromResponse and SmtpClient#ProcessRcptToResponse `protected` so I could provide different behavior in a subclass.

**Comment by jstedfast** [comment]
if MAIL FROM fails, there's no way to recover, so I left that one private for now.

**Comment by TimTheTinker** [comment]
Thanks Jeffrey, much appreciated.

**Comment by TimTheTinker** [comment]
Hey, also, before I go --- thanks so much for the quick turnaround and the really great libraries.

**Comment by jstedfast** [comment]
Hey @TimTheTinker, another user in issue #309 has a similar problem and the current `ProcessRcptToCommand()` method does not provide enough context for their use case.

I am proposing to modify that method to also take the `MimeMessage` object that is currently being sent as a possible solution and both wanted to keep you updated on the potential API breakage but also to solicit feedback from you to see if that would be useful to you (perhaps you might run into the same situation he brought up (which is "what to do if all recipients are rejected?").
