### ISSUE TITLE
SSL v3.0 appears to not work correctly

### ISSUE THREAD

**Issue by Saurbaum** [jstedfast/MailKit#259]
It's been noted during test that if SSL v3.0 is the only supported Version for SSL/TLS on the mail server then MailKit can't connect and gives {"The client and server cannot communicate, because they do not possess a common algorithm"} as the inner exception.

As soon as I enable TLS v1.0 or later it connects without complaint.

I've made sure that I set the clients SslProtocols to SslProtocols.Ssl3 | SslProtocols.Tls | SslProtocols.Tls11 | SslProtocols.Tls12;

**Comment by Saurbaum** [comment]
If I set it to only use SSL3 it works but I would have expected allowing all the SslProtocols it should accept the server.

**Comment by jstedfast** [comment]
I explicitly disabled SSLv3 because SSLv3 is known to be not secure since about a year and a half ago.

No one should be using SSLv3 anymore unless they have been living under a rock :-)

**Comment by Saurbaum** [comment]
So if it's disabled why does it work when only SSL3 is set?

Either there is a bug that there is a way to trick MailKit into using SSL3 (by removing the TLS protocols from the supported list) or there is a bug that it doesn't fall back to SSL3 even when it's explicitly set as a supported type.

**Comment by jstedfast** [comment]
I dunno, probably a bug in Microsoft's SslStream implementation.

BTW, you can override which SSL/TLS protocols the client is allowed to use by setting the `SslProtocols` property on the client.

**Comment by jstedfast** [comment]
Oh, n/m, I see you already did that. I misunderstood your original report to mean that you set those flags on the server.

I have no idea what the problem you are seeing is since those flags are passed verbatim to SslStream's `AuthenticateAsClient()` method.

Microsoft may have made it such that if you've added any of the TLS flags, it automatically disables SSLv3.

**Comment by Saurbaum** [comment]
Thanks for looking into it.  This gives me the perfect excuse to drop SSL 3.0 support entirely.
