### ISSUE TITLE
[Question]SASL Mechanisms

### ISSUE THREAD

**Issue by Nekeniehl** [jstedfast/MailKit#260]
Hi There, 

I'm getting an exception on the Authentication of the smtp client, I got a "5.1.1 Command not recognized".

I did my research and the problem was that I was trying to connect with the wrong SASL, I cleaned the AuthenticationMechanisms property from the SmtpClient and add again the "PLAIN" one.

I saw that you have the following mechanisms there 
    [0]: "SCRAM-SHA-1"
    [1]: "DIGEST-MD5"
    [2]: "CRAM-MD5"
    [3]: "LOGIN"
    [4]: "PLAIN"

My question is: Do you try with all of them when the previous one fail? i.e. if the SCRAM is not supported you keep trying to authenticate with the others SALS till one of them is working or just first come first served and if it fails you raise the exception.

Thanks.

**Comment by jstedfast** [comment]
MailKit tries all of the ones that the server claims that it supports in order of most secure to least secure

**Comment by Nekeniehl** [comment]
Ok, I just didn't understand why I was facing the exception, because if I clear the AuthenticationMechanisms and add just the "plain" works flawlessly. Sadly I cannot access to the server to check if really supports what it claims that it supports.

Thanks for the support.

**Comment by jstedfast** [comment]
The values in the AuthenticationMechanisms property are the mechanisms that the server claims to support in its list of capabilities.

If you want to capture a protocol log to see what exactly is being sent back and forth between the client and the server, you can follow these directions here: https://github.com/jstedfast/MailKit/blob/master/FAQ.md#ProtocolLog

**Comment by Nekeniehl** [comment]
Ok, following your FAQ, I got the following log:

Connected to smtps://smtp.mail.de:465/
S: 220 smtp.mail.de ESMTP RZmta 37.14 ready (mo49) TLS=TLSv1.2:ECDHE-RSA-AES256-SHA384
C: EHLO [192.168.1.32]
S: 250-smtp.mail.de greets XX.XXX.X.XXX
S: 250-ENHANCEDSTATUSCODES
S: 250-8BITMIME
S: 250-PIPELINING
S: 250-DELIVERBY
S: 250-SIZE 104857600
S: 250-AUTH SCRAM-SHA-1 DIGEST-MD5 CRAM-MD5 LOGIN PLAIN
S: 250 HELP
C: AUTH SCRAM-SHA-1 biwsbXXXXXXXkaWZhY3QudmVydHJpZWJAcC1wb3dlci5kZSxyPTlqZjIrY1c3TVQ1c3VNMmJQMEJDNkdoUw==
S: 334 cj05amYyK2NXN01UNXN1TTJiUXXXX05eakJDWV9hYmN0SG56bF1hY3hiKXQscz1tSElBcEVDdVN4clA3emZnLGk9NDA5Ng==
C: Yz1iaXdzLHI9OWpmMitjVzXXXXlAwQkM2R2hTTFdOXmpCQ1lfYWJjdEhuemxdYWN4Yil0LHA9dXYvaGxoQTJwYjhDRFhIaE0vbFJKc0RtaWhvPQ==
S: 334 ZT1pbnZhXXXXX29m
C: 
S: 535 5.7.8 Authentication failed: wrong user/password
C: AUTH CRAM-MD5
S: 500 5.5.1 Command unrecognized


And that is what I get in the Exception, the last one, looks like it doesn't continue with the others mechanism, Am I right?

**Comment by jstedfast** [comment]
Correct, because it will only continue if the error is "bad user/pass"

**Comment by Nekeniehl** [comment]
Ok, understood, it's what I thought, probably a problem in the server out of our hands.

Thanks again for the support.
