### ISSUE TITLE
IMAP Attachments have no unique ID

### ISSUE THREAD

**Issue by PleasantD** [jstedfast/MailKit#261]
I'm trying to scrape a bunch of metadata from IMAP, including attachments.
I make sure I'm getting `MessageSummaryItems.BodyStructure`.
I iterate through the attachments but the source I'm getting them from (Gmail) doesn't set a `ContentId` and there doesn't seem to be a way to get the `X-Attachment-Id` header value from the `BodyPartBasic`.

Without being able to uniquely identify the attachment, I can't reliably retrieve it from the body later.
Is the `X-Attachment-Id` sent from the IMAP server in the summary? Or do I have to parse the full message to get this info?

**Comment by jstedfast** [comment]
An X-Attachment-Id is not a standard header and so there is no way to get that info over IMAP without requesting the full headers of the MIME part.

You'll need to use [folder.GetBodyPart (UniqueId, BodyPart, bool, ...)](http://www.mimekit.net/docs/html/M_MailKit_Net_Imap_ImapFolder_GetBodyPart_4.htm)
