### ISSUE TITLE
Unexpected token in IMAP greeting: [atom: BYE]

### ISSUE THREAD

**Issue by nhaberl** [jstedfast/MailKit#262]
Sometimes we get this error in our unit tests when trying to connect to an self hosted exchange server.
**MailKit.Net.Imap.ImapProtocolException: Unexpected token in IMAP greeting: [atom: BYE]**

No specific time or day when that happens.

Any help appreciated,
thanks Norbert

**Comment by jstedfast** [comment]
It means that your server is sending `* BYE` as soon as you connect.

If you can get me a log, I can probably make it handle that case a bit better, but it's still going to result in an immediate disconnect (since the server is disconnecting you).

**Comment by nhaberl** [comment]
Thanks, will try to get the log.

**Comment by jstedfast** [comment]
fwiw, you can find directions on getting a log here: https://github.com/jstedfast/MailKit/blob/master/FAQ.md#ProtocolLog

**Comment by jstedfast** [comment]
never mind, I already had a FIXME in place for this case.

It now throws an ImapProtocolException with a message of "IMAP server unexpected disconnected."
