### ISSUE TITLE
The attachment name garbled

### ISSUE THREAD

**Issue by shuyuea3** [jstedfast/MailKit#264]
Hi, I added the name attachment when there will be garbled, please do I have other ways to set the attachment name.

**Comment by Yuexs** [comment]
I'm kind of curious about that, now the attachment name, and in the Chinese case, indeed gibberish.

**Comment by jstedfast** [comment]
Garbled how? I need examples.

**Comment by Yuexs** [comment]
var attachmenttxt = new MimePart("text", "plain")
            {
                ContentObject = new ContentObject(new MemoryStream(Encoding.Default.GetBytes(@"demo文本"))),
                ContentDisposition = new ContentDisposition(ContentDisposition.Attachment),
                ContentTransferEncoding = ContentEncoding.Default,
                FileName =  "测试文本.txt"
            };

This is to add attachments.
Receive a message attachment name is garbled
娴嬭瘯鏂囨湰.txt  (11字节)

**Comment by Yuexs** [comment]
Name you can set the encoding for the file, should be able to solve

**Comment by jstedfast** [comment]
This works perfectly fine for me.


Here's how the attachment filename renders in GMail:

![GMail](http://content.screencast.com/users/jeff.xamarin/folders/Jing/media/8dfdfc9a-190f-4e4e-bd62-753c1205cd69/00000010.png)

And here's how the filename renders in Thunderbird:

![Thunderbird](http://content.screencast.com/users/jeff.xamarin/folders/Jing/media/2de0e693-729d-42e3-965d-5cb75e2162d4/2015-11-21_2157.png)

And finally, here's the encoded MIME headers:

```
Content-Type: application/octet-stream; name*=utf-8''%E6%B5%8B%E8%AF%95%E6%96%87%E6%9C%AC.txt
Content-Disposition: attachment;
	filename*=utf-8''%E6%B5%8B%E8%AF%95%E6%96%87%E6%9C%AC.txt
Content-Transfer-Encoding: base64
```

All looks good to me.

**Comment by jstedfast** [comment]
I suspect the problem you are seeing is completely unrelated to MimeKit and is in fact a bug or "feature"(?) of some other mail software - either the SMTP server, the POP3 or IMAP server (whichever you are using to retrieve the message), or the recipient email client.

Good luck finding the culprit, but I'm 100% positive the problem is not MimeKit.

**Comment by Yuexs** [comment]
JavaMail is a function that sets the attachment name encoding, you test did not, I did have this happen

**Comment by Yuexs** [comment]
The character encoding to use for GB18030

**Comment by jstedfast** [comment]
I just modified your code snippet to force MimeKit to useGB18030 to encode the attachment filename and here is the encoded MIME headers produced by MimeKit:

```
Content-Type: text/plain; name*=gb18030''%B2%E2%CA%D4%CE%C4%B1%BE.txt
Content-Disposition: attachment; filename*=gb18030''%B2%E2%CA%D4%CE%C4%B1%BE.txt
Content-Transfer-Encoding: base64
```

As expected, Thunderbird and GMail both render the attachment filename correctly.

Here's the code I used to change the encoding:

```csharp
var index = attachment.Headers.IndexOf (HeaderId.ContentDisposition);
var disposition = attachment.Headers[index];

index = attachment.Headers.IndexOf (HeaderId.ContentType);
var ctype = attachment.Headers[index];
			
disposition.SetValue ("GB18030", disposition.Value);
ctype.SetValue ("GB18030", ctype.Value);
```

At this point I think we can all agree that it has been proven beyond any reasonable doubt that MimeKit correctly encodes the filename.

**Comment by Yuexs** [comment]
Thank you, it does address. thanks

**Comment by Yuexs** [comment]
Filename can be more convenient to set the encoding directly

**Comment by jstedfast** [comment]
I've added an Encoding property to MimeKit.Parameter so that this is now much easier to change.

```csharp
attachment.ContentType.Parameters.Add ("GB18030", "name", "测试文本.txt");
attachment.ContentDisposition.Parameters.Add ("GB18030", "filename", "测试文本.txt");
```

**Comment by Yuexs** [comment]
This is a very useful project so much easier, thank you.

**Comment by myesn** [comment]
@jstedfast hi，Thank you very much for your solution, but there is still a garbled problem after I tested it. Is there a solution? Thanks.

Not working on QQ Mailbox .

**code**:
```csharp
var attachmentItem = new Attachment(fileStream, attachment.Name);
var charset = "GB18030";
attachmentItem.ContentType.CharSet = charset;
//// 附件显示名称
//attachmentItem.ContentType.Name = attachment.Name;
// 附件下载名称（还是会乱码）
attachmentItem.ContentDisposition!.FileName = attachment.Name!;
attachmentItem.ContentDisposition.Parameters.Add("charset", charset);

message.Attachments.Add(attachmentItem);
```

**Debug screenshot**:
![image](https://github.com/jstedfast/MailKit/assets/18598579/e7ee0be6-3c62-4570-b6f1-e3b9cb0ffb54)

It was received by the QQ mailbox and can display Chinese normally, but it became garbled when viewing the details or downloading:
![image](https://github.com/jstedfast/MailKit/assets/18598579/f97e85ed-8960-4529-8d28-387985f29ee1)
![image](https://github.com/jstedfast/MailKit/assets/18598579/49c505c5-6799-428c-8957-fa7e20375b47)
![image](https://github.com/jstedfast/MailKit/assets/18598579/25afbabd-1666-47a6-ae9d-7bddd21f349b)

**Comment by jstedfast** [comment]
Screenshots aren't enough to figure out why that is happening, but probably a bug in QQ mail server.

All I can tell you is that this line of code is wrong:

```csharp
attachmentItem.ContentDisposition.Parameters.Add("charset", charset);
```

That line needs to be removed.
