### ISSUE TITLE
AUTH PLAIN and FormatException in the Challenge method

### ISSUE THREAD

**Issue by fenzad** [jstedfast/MailKit#268]
Hello,
I have a problem during POP3 authentication.
In attachment the protocol log.

The error happens on the response "+ go ahead" of the email server. The exception occurs in the method "Challenge" of the class "SaslMechanism". The value of the parameter "token" is "ho ahead" and fails the conversion from base 64. This value anyhow it is never considered in the "Challenge" method of the class "SaslMechanismPlain" called in this case.

This is a bug of MailKit or a misconstruction of the protocol by the email server?

[plog.log.txt](https://github.com/jstedfast/MailKit/files/44858/plog.log.txt)

**Comment by jstedfast** [comment]
Technically, I think it's a bug in the server because it shouldn't send plain text after the +, but it should be fairly trivial to work around in MailKit.

**Comment by fenzad** [comment]
Fine! Now it is ok! It is expected a release for nuget?

**Comment by jstedfast** [comment]
It'll be in the next release, but I don't know yet when that will be.

**Comment by jstedfast** [comment]
I've released MailKit 1.2.15 to NuGet with this fix.

**Comment by fenzad** [comment]
Thanks!
