### ISSUE TITLE
Authentication failed trying to connect to IMAP:4 Exchange server

### ISSUE THREAD

**Issue by MohsenMahdieh** [jstedfast/MailKit#269]
I am trying to connect to an IMAP:4 enabled hosted Exchange Server using "IMapClient" class from MailKit but I am getting the Authentication failed exception. The following is the dump of the logger:

Connected to imap://IP-ADDRESS:143/?starttls=when-available
S: * OK The Microsoft Exchange IMAP4 service is ready.
C: A00000000 CAPABILITY
S: * CAPABILITY IMAP4 IMAP4rev1 LOGINDISABLED STARTTLS UIDPLUS MOVE ID CHILDREN IDLE NAMESPACE LITERAL+
S: A00000000 OK CAPABILITY completed.
C: A00000001 STARTTLS
S: A00000001 OK Begin TLS negotiation now.
C: A00000002 CAPABILITY
S: * CAPABILITY IMAP4 IMAP4rev1 AUTH=PLAIN AUTH=NTLM AUTH=GSSAPI UIDPLUS MOVE ID CHILDREN IDLE NAMESPACE LITERAL+
S: A00000002 OK CAPABILITY completed.
C: A00000003 AUTHENTICATE NTLM
S: +
C: TlRMTVNTUAABAAAABwIIAAAAAAAgAAAAAAAAACAAAAA=
S: + TlRMTVNTUAACAAAAEAAQADgAAAAFAokCT++vHlcHakoAAAAAAAAAAKQApABIAAAABgOAJQAAAA9EAFAAVABDAEwATwBVAEQAAgAQAEQAUABUAEMATABPAFUARAABAAoAQwBBAFMAMAAyAAQAHgBkAHAAdABjAGwAbwB1AGQALgBjAG8AbQAuAGEAdQADACoAYwBhAHMAMAAyAC4AZABwAHQAYwBsAG8AdQBkAC4AYwBvAG0ALgBhAHUABQAeAGQAcAB0AGMAbABvAHUAZAAuAGMAbwBtAC4AYQB1AAcACACYJccN0ijRAQAAAAA=
C: TlRMTVNTUAADAAAAGAAYAFYAAAAYABgAbgAAAAAAAABAAAAAFgAWAEAAAAAAAAAAVgAAAAAAAACGAAAAAYIIAGUAbABlAGMAdAByAGkAYwBpAHQAeQDqlY7S6w1JqQAAAAAAAAAAAAAAAAAAAABmwpjC52AodwEn5tt4Or/Jsrx/RyHV0ew=
S: A00000003 NO AUTHENTICATE failed.
C: A00000004 AUTHENTICATE PLAIN
S: +
C: AGVsZWN0cmljaXR5AEVQYXNzd29yZDE=
S: A00000004 NO AUTHENTICATE failed.
C: A00000005 LOGIN ACCOUNT@EMAILADDRESS ACCPASSWORD
S: A00000005 NO LOGIN failed.
AUTHENTICATE failed.

I should mention that same code works when I try to connect to our on-premiss exchange server but the Capabilities are a little bit different as followed:

Connected to imap://IPADDRESS:143/?starttls=when-available
S: * OK The Microsoft Exchange IMAP4 service is ready.
C: V00000000 CAPABILITY
S: * CAPABILITY IMAP4 IMAP4rev1 AUTH=PLAIN AUTH=NTLM AUTH=GSSAPI STARTTLS UIDPLUS ID CHILDREN IDLE NAMESPACE LITERAL+
S: V00000000 OK CAPABILITY completed.
C: V00000001 STARTTLS
S: V00000001 OK Begin TLS negotiation now.
C: V00000002 CAPABILITY
S: * CAPABILITY IMAP4 IMAP4rev1 AUTH=PLAIN AUTH=NTLM AUTH=GSSAPI UIDPLUS ID CHILDREN IDLE NAMESPACE LITERAL+
S: V00000002 OK CAPABILITY completed.
C: V00000003 AUTHENTICATE NTLM
S: +
C: TlRMTVNTUAABAAAABwIIAAAAAAAgAAAAAAAAACAAAAA=
S: + TlRMTVNTUAACAAAADgAOADgAAAAFAokCPaBgQj6SzAoAAAAAAAAAAKYApgBGAAAABgOAJQAAAA9SAE8AQwBLAEUATgBEAAIADgBSAE8AQwBLAEUATgBEAAEAEgBSAE8AQwBLAC0ARQBYADAAMQAEABoAUgBvAGMAawBlAG4AZAAuAGwAbwBjAGEAbAADAC4AUgBPAEMASwAtAEUAWAAwADEALgBSAG8AYwBrAGUAbgBkAC4AbABvAGMAYQBsAAUAGgBSAG8AYwBrAGUAbgBkAC4AbABvAGMAYQBsAAcACABFCJ2wmCjRAQAAAAA=
C: TlRMTVNTUAADAAAAGAAYAFYAAAAYABgAbgAAAAAAAABAAAAAFgAWAEAAAAAAAAAAVgAAAAAAAACGAAAAAYIIAGYAaQBsAGUAUwBNAEEAUgBUADAAMQDxvOiYzHcqeQAAAAAAAAAAAAAAAAAAAABq6PWCwxas9yZzLne1nD9r+ys7XCOfPXQ=
S: V00000003 OK AUTHENTICATE completed.

Any thought on that?

**Comment by jstedfast** [comment]
Try disabling NTLM by using the following line of code before calling the Authenticate() method:

```csharp
client.AuthenticationMechanisms.Remove ("NTLM");
```

**Comment by MohsenMahdieh** [comment]
Hi There,

I gave it a try and it worked. Thanks for your help!

Regards,

**Comment by jstedfast** [comment]
With this latest patch, you might not need to disable NTLM anymore. Let me know if you try it and it still fails.

If you'd rather wait for a new nuget release, I'll try to update the status of this bug when I get around to doing that.
