### ISSUE TITLE
DKIM signature appears to fail when Date header is included

### ISSUE THREAD

**Issue by xecrets** [jstedfast/MailKit#271]
Using the following:

MimeKit.HeaderId[] headersToSign = new MimeKit.HeaderId[] { MimeKit.HeaderId.From, MimeKit.HeaderId.To, MimeKit.HeaderId.Subject, MimeKit.HeaderId.Date };

This causes the DKIM signature validation by both Google and returnpath to fail. Removing the Date header from the list of headers to sign fixes the problem. Am using 'Relaxed' canonicalization for both headers and body.

Is it a bad idea to use the 'Date' header in the signature? In general, I have found no simple source for documentation concerning any recommendations about what headers to sign, and which not to.

Since this is added to an existing project, the actual message is created as a System.Net.Mail.MailMessage and then (MimeKit.MimeMessage) cast for mimekit use, not that I see that it would make an obvious difference.

Thanks for a really useful library!

**Comment by jstedfast** [comment]
Using the Date header should be fine, just make sure you set the message.Date field before signing.

For future reference, please file MimeKit issues on the [MimeKit issue tracker](https://github.com/jstedfast/MimeKit/issues).

**Comment by jstedfast** [comment]
BTW, if explicitly setting the Date value before signing does not fix the problem, let me know. It seems to work for me, but perhaps there is some other issue.
