### ISSUE TITLE
sha algorythm

### ISSUE THREAD

**Issue by uruscode** [jstedfast/MailKit#272]
A question: is the SHA256 algorythm supported in the last version?

The fact is: a client has modified the security of a PEC server, passing from SHA1 to SHA256 and he can't connect now to it.. this is the stacktrace:
System.FormatException: Invalid length for a Base-64 char array or string.
   at System.Convert.FromBase64_Decode(Char* startInputPtr, Int32 inputLength, Byte* startDestPtr, Int32 destLength)
   at System.Convert.FromBase64CharPtr(Char* inputPtr, Int32 inputLength)
   at System.Convert.FromBase64String(String s)
   at MailKit.Net.Imap.ImapClient.<>c__DisplayClass24.<Authenticate>b__23(ImapEngine imap, ImapCommand cmd, String text)
   at MailKit.Net.Imap.ImapCommand.Step()
   at MailKit.Net.Imap.ImapEngine.Iterate()
   at MailKit.Net.Imap.ImapClient.Authenticate(ICredentials credentials, CancellationToken cancellationToken)
   at ... my classes...

Before there was 0.26 version of MailKil and I updated now with last version (adapting the code), but nothing changed.. same error!

Can you help me?

**Comment by jstedfast** [comment]
SHA256 of what? There is no SASL authentication mechanism that supports SHA256 afaik.

**Comment by jstedfast** [comment]
Can you follow these directions and get me a protocol log? https://github.com/jstedfast/MailKit/blob/master/FAQ.md#ProtocolLog

**Comment by uruscode** [comment]
How can I write this log in the same folder where log4net put others log?
Because now I catch this:
System.UnauthorizedAccessException: Accesso al percorso 'C:\Windows\SysWOW64\inetsrv\imap.log' negato.
   in System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   in System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   in System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   in MailKit.ProtocolLogger..ctor(String fileName)

in italian it's like "access denied to folder ... "

**Comment by jstedfast** [comment]
You can provide a full path.

**Comment by jstedfast** [comment]
I've added support for the SCRAM-SHA-256 authentication mechanism. Maybe that will help?

**Comment by uruscode** [comment]
Hi Jeffrey, yesterday I didn't write anymore because I left the office (I'm in Italy so many hours difference).. now I'm trying to get the customer's protocol log, and if needed I will get your updated code. I will let you know..

Anyway, is there a way to specify which authentication mechanism to use, or I don't need to?
Because before I never specify to use the SHA1.. and it worked.. maybe the pec server tells the application server which it wants and for me is transparent..?

**Comment by jstedfast** [comment]
You don't need to specify SHA256, it will just use it if it's available.

You can, however, control which auth mechanism is used by removing mechanism names from the `client.AuthenticationMechanisms` hashset property which is just a list to keep track of which auth mechanisms the server supports.

**Comment by uruscode** [comment]
Finally, it seems that only updating the library from version 0.26 to latest it was enough to resolve the issue... thanks anyway for you support!!

**Comment by jstedfast** [comment]
No problem, glad things are working for you now!
