### ISSUE TITLE
Spam folder in yahoo is not detected

### ISSUE THREAD

**Issue by apidrone** [jstedfast/MailKit#274]
The library does not detect Spam folder in yahoo email. This is sample code to list all folders and to try and open Spam folder:
```
using (var client = new ImapClient())
{
	client.Connect("imap.mail.yahoo.com", 993, SecureSocketOptions.SslOnConnect);

	// Note: since we don't have an OAuth2 token, disable
	// the XOAUTH2 authentication mechanism.
	client.AuthenticationMechanisms.Remove("XOAUTH2");

	client.Authenticate("xxxxx", "xxxxx");

	var personal = client.GetFolder(client.PersonalNamespaces[0]);
	foreach (var folder in personal.GetSubfolders(false))
		Console.WriteLine("[folder] {0}", folder.Name);

	var spamOne = client.GetFolder(SpecialFolder.Junk);
	var spamTwo = client.GetFolder("Spam")

	client.Disconnect(true);
}
```
This is always false:
```
if ((client.Capabilities & (ImapCapabilities.SpecilUse | ImapCapabilities.XList)) != 0) {
    // ...
}
```
spamOne and spamTwo are always null, and GetSubfolders() does not show the spam folder.
This is the debug log sample:
```
S: A00000000 OK AUTHENTICATE completed - Mailbox size in bytes is 7026886
C: A00000001 CAPABILITY
S: * CAPABILITY IMAP4rev1 ID NAMESPACE X-ID-ACLID UIDPLUS LITERAL+ XAPPLEPUSHSERVICE XYMHIGHESTMODSEQ
S: A00000001 OK CAPABILITY completed
C: A00000002 NAMESPACE
S: * NAMESPACE (("" "/")) NIL NIL
S: A00000002 OK NAMESPACE completed
C: A00000003 LIST "" "INBOX"
S: * LIST (\HasNoChildren) "/" "Inbox"
S: A00000003 OK LIST completed
C: A00000004 LIST "" "%"
S: * LIST (\HasNoChildren) "/" "clientFetch"
S: * LIST (\HasNoChildren) "/" "Bulk Mail"
S: * LIST (\HasNoChildren) "/" "Draft"
S: * LIST (\HasNoChildren) "/" "Inbox"
S: * LIST (\HasNoChildren) "/" "Junk E-mail"
S: * LIST (\HasNoChildren) "/" "Sent"
S: * LIST (\HasNoChildren) "/" "Trash"
S: A00000004 OK LIST completed
```

**Comment by DavidKarlas** [comment]
Quick google search indicates Yahoo is using "Bulk Mail" for "Spam" folder...

**Comment by jstedfast** [comment]
```csharp
if ((client.Capabilities & (ImapCapabilities.SpecialUse | ImapCapabilities.XList)) != 0) {
```

as well as the IMAP protocol log indicate that the server does not support those features and thus there's no way for MailKit to auto-detect them.

The only way to do it is to more-or-less what your spamTwo attempt tried to do. If you can, do a google search for the particular server you are connecting to in order to figure out what the name of their spam folder is.

Another option is to ask the user of your software what folder to use as the spam folder.

**Comment by apidrone** [comment]
I think DavidKarlas is right on this. I found an article about Spam/Bulk which is Yahoo related [here](http://superuser.com/questions/386959/yahoo-imap-spam-folder-not-recognized-by-outlook-2007)

My attempt with spamOne or spamTwo, was based on some previous libraries that i have used in the past, where basically all you do is folder.Select("Desiredname"), and they had some wrappers for most used email systems like, Gmail, Yahoo, Hotmail(Outlook) and others.

Have to check this when i am on my dev machine, but 99% is what DavidKarlas pointed out in his comment and the above [link](http://superuser.com/questions/386959/yahoo-imap-spam-folder-not-recognized-by-outlook-2007)
