### ISSUE TITLE
Windows 8 phone

### ISSUE THREAD

**Issue by shahzadthathal** [jstedfast/MailKit#275]
Hi, 
Can I use this for windows phone 8 application for reading emails?
Or please suggest me a library as I'm searching for windows mobile supported stuff for reading emails.

Thank you

**Comment by jstedfast** [comment]
No, unfortunately MailKit cannot be used for Windows Phone 8, I think it will only work on Windows Phone 8.1 or later.

I did not realized that you wanted to target WP8.

Perhaps [ImapX](https://imapx.codeplex.com/) will work? Sadly it's also not really kept up-to-date, but it's got more active development than S22.Imap.

**Comment by shahzadthathal** [comment]
okay thank you  I will try.
