### ISSUE TITLE
Why is IMAP limited to a single connection?

### ISSUE THREAD

**Issue by ben-rockliffe** [jstedfast/MailKit#278]
I am using Mailkit in an application and I would ideally like to have two IMAP connections. One read only (sat in an IDLE loop) and the other ReadWrite for downloading messages and moving them about.

Currently this isn't possible as the code uses a single ImapEngine (and thus connection) no matter how many instances of the ImapClient you create and forces you to drop the idle before performing operations.

If I can have multiple clients connected to the same IMAP account at the same time why is this limitation imposed in MailKit?

**Comment by jstedfast** [comment]
Huh? What? You can just create multiple ImapClient instances and have each of them connect to the same server.

Each ImapClient instance gets its own ImapEngine instance. I'm not sure how you came to the conclusion that there is a global ImapEngine that is shared...

**Comment by Sicos1977** [comment]
I agree with jstedfast, I just made something simular to your problem and that works fine

**Comment by ben-rockliffe** [comment]
You are indeed correct, earlier in my development I was seeing messages similar to "the imap client is busy in another thread.." I have since found and eliminated a rouge thread that was being created and it does now work as you say.

Apologies for the confusion.

**Comment by jstedfast** [comment]
No worries :)

Glad you got it working.
