### ISSUE TITLE
Unexpected token in IMAP response: ')'

### ISSUE THREAD

**Issue by zhangjiagege** [jstedfast/MailKit#279]
I got an exception when fetching Envelope.Here's the log:
S: * 33 FETCH (ENVELOPE ("Wed, 7 Aug 2013 16:44:13 +0800" "=?GBK?B?UmU6ILnY09pRVFMgSUm1xNT2x78=?=" (("=?GBK?B?1uzLs72h?=" NIL "xxx" "xxx.com")) (("=?GBK?B?1uzLs72h?=" NIL "xxx" "xxx.com")) (("=?GBK?B?1uzLs72h?=" NIL "xxx" "xxx.com")) (("=?GBK?B?emhhbmcuYm8=?=" NIL "xxx" "xxx.com")) NIL NIL "<xxx@qq.com>"))

The code is:
			if ((nstring = ReadNStringToken (engine, false, cancellationToken)) != null)
				envelope.MessageId = MimeUtils.ParseMessageId (nstring);

**Comment by jstedfast** [comment]
Your IMAP server is returning a broken ENVELOPE response.

According to the specification, the ENVELOPE value should contain:

1. Date
2. Subject
3. From
4. Sender
5. Reply-To
6. To
7. Cc
8. Bcc
9. In-Reply-To
10. Message-Id

Your server responded with:

Date = "Wed, 7 Aug 2013 16:44:13 +0800"
Subject = "=?GBK?B?UmU6ILnY09pRVFMgSUm1xNT2x78=?="
From = (("=?GBK?B?1uzLs72h?=" NIL "xxx" "xxx.com"))
Sender = (("=?GBK?B?1uzLs72h?=" NIL "xxx" "xxx.com"))
Reply-To = (("=?GBK?B?1uzLs72h?=" NIL "xxx" "xxx.com"))
To = (("=?GBK?B?emhhbmcuYm8=?=" NIL "xxx" "xxx.com"))
Cc = NIL
Bcc = NIL
In-Reply-To = "xxx@qq.com"

Where's the Message-Id??? :)

File a bug report against your IMAP server software.

**Comment by jstedfast** [comment]
FWIW, here is the exact syntax definition from rfc3501:

```
envelope        = "(" env-date SP env-subject SP env-from SP
                  env-sender SP env-reply-to SP env-to SP env-cc SP
                  env-bcc SP env-in-reply-to SP env-message-id ")"

env-bcc         = "(" 1*address ")" / nil

env-cc          = "(" 1*address ")" / nil

env-date        = nstring

env-from        = "(" 1*address ")" / nil

env-in-reply-to = nstring

env-message-id  = nstring

env-reply-to    = "(" 1*address ")" / nil

env-sender      = "(" 1*address ")" / nil

env-subject     = nstring

env-to          = "(" 1*address ")" / nil
```

**Comment by jstedfast** [comment]
As a work-around, you could request the specific headers that you want instead of requesting the `MessageSummaryItems.Envelope`.
