### ISSUE TITLE
Is MailKit a Mail Server?

### ISSUE THREAD

**Issue by b9chris** [jstedfast/MailKit#280]
Apologies for using the Issues section for this. This doesn't suit StackOverflow as it's a broad question and there doesn't appear to be a MailKit forum, so this seemed the most obvious place to ask.

Is MailKit meant to run a mail server, for example on Windows, or only a mail client?

I see a lot of things that suggest a mail server, like DKIM and all of the SMTP/IMAP functions. But digging for info on MailKit I don't see anything discussing deployment best practices, like what ports to open, how to run MailKit in a way that it's available and listening on those ports, SPF setup, that sort of thing.

So I figured I'd ask people who would know.

Sorry for the basic question.

**Comment by jstedfast** [comment]
MailKit is a mail-client library and has no server functionality.

DKIM can be done in the client or on the server. In MailKit's case, the DKIM functionality is actually part of [MimeKit](https://github.com/jstedfast/MimeKit) which is just a general purpose MIME parser/generator that can be used in either a client or server implementation.

The SMTP, POP3 and IMAP code in MailKit is client-only.

Hope that helps.
