### ISSUE TITLE
Mails with CC and BCC are not send to those

### ISSUE THREAD

**Issue by CyberGecko** [jstedfast/MailKit#281]
Hello, I am using MailKit Version 1.2.16 and it seems that mails with cc or bcc are not send to those, although the reciver sees the cc address.

this is the code i am using to create a part of the mail:
```c#
private MimeMessage SetSenderAndReceiverAddresses(MailItem mailItem, MimeMessage result)
        {
            MailboxAddress sender = new MailboxAddress(mailItem.SenderName, mailItem.SenderAddress);
            MailboxAddress receiver = new MailboxAddress(mailItem.RecipientName, mailItem.RecipientAddress);
            result.Sender = sender;
            result.From.Add(sender);
            result.To.Add(receiver);
           
            result.Bcc.Clear();
            result.Cc.Clear();
            if (!String.IsNullOrWhiteSpace(mailItem.BlindCarbonCopyAddress))
                result.Bcc.Add(new MailboxAddress(mailItem.BlindCarbonCopyName, mailItem.BlindCarbonCopyAddress));

            if (!String.IsNullOrWhiteSpace(mailItem.CarbonCopyAddress))
                result.Cc.Add(new MailboxAddress(mailItem.CarbonCopyName, mailItem.CarbonCopyAddress));
            
            return result;
        }
```
I tried the current prerelease Version, but ther is the same problem...
My sysadmin told me that the cc (or bcc) address is missing in the 'rcpt to:' part.

**Comment by CyberGecko** [comment]
Ok. I just realised that i have been a little bit stupid...

I had sent the mail with this method:
´´´c#
smtpClient.Send(message, message.Sender, message.To.OfType<MailboxAddress>().AsEnumerable());
´´´

When i use just
´´´c#
smtpClient.Send(message);
´´´
it works almost as intended. 
The strange thing here ist if i use for the recipient (To-Property) 'bpuls@domain.eu' and bastian.puls@domain.eu as carbon copy (CC-Property) I only recieve the mail only once.

**Comment by jstedfast** [comment]
That's because your server knows that one of those addresses is an alias for the other, most likely.

It's not a MailKit issue.
