### ISSUE TITLE
The IMAP server has unexpectedly disconnected

### ISSUE THREAD

**Issue by FishTailTea6** [jstedfast/MailKit#282]
I have one issue that has occurred in last few days and I would like to ask you to help me to understand what could be wrong.
I have a console application that uses MailKit to get mails from two folders (not inbox). In one folder there is sent mail and in the other is received mail. Both folders contain quite a lot of messages as it is a storage of the whole company's emails (let's say backup).
Until a few days ago I was able to get the mail without problem, but recently I'm able to read only the received folder. Each time I try to read the send folder I get the error: The IMAP server has unexpectedly disconnected. This happens when I run the code
mailFolder.Search(SearchQuery.DeliveredOn(qDate))
However the code for send and received folder is the same, and as I have stated it worked before. Could you maybe have some idea what should I check or what could be wrong?
Thank you in advance.

**Comment by FishTailTea6** [comment]
One more thing just now occurred to me. I might have used flag as seen function on some items in that folder. Is there a chance it could cause problems as it is sent mail?

**Comment by jstedfast** [comment]
Try getting a protocol log using these instructions: https://github.com/jstedfast/MailKit/blob/master/FAQ.md#ProtocolLog

Perhaps that will shed some light.

**Comment by FishTailTea6** [comment]
Thank you for the hint, however I still do not know very much. After I run the search on received folder, id's of the messages are listed. When I try the sent folder, the Id's are not listed and I only get the message on the number of all mail...
C: A00000008 UID SEARCH ON 6-DEC-2015
S: * 71210 EXPUNGE
S: * 71210 EXISTS
S: * 0 RECENT

Tomorrow I will yet try to talk to the guys who runs the service and ask them to check the folder itself if it's not somehow corrupted.

**Comment by jstedfast** [comment]
Is it actually disconnecting? I don't see anything that would cause MailKit to get disconnected (i.e. no `* BYE` response). Is the server simply dropping the connection?

THis is not really looking like a bug in MailKit, so I guess I'll close it for now until/unless you discover a reason to believe that there is a bug in MailKit.
