### ISSUE TITLE
Exception with MailKit

### ISSUE THREAD

**Issue by GuardRex** [jstedfast/MailKit#286]
Hi,

I just wired up MailKit for the first time. I'm on the latest .NET 5 runtime and packages on the dev feed (`dnx-coreclr-win-x64.1.0.0-rc2-16357` - dnxcore50 only project with `-rc2-*` packages). Out of the box, I get the following exception. Any tips?? Ideas??
```
System.MissingMethodException: Method not found: 'Void 
System.Net.Security.SslStream.AuthenticateAsClient(System.String, 
System.Security.Cryptography.X509Certificates.X509CertificateCollection, 
System.Security.Authentication.SslProtocols, Boolean)'.
 at MailKit.Net.Smtp.SmtpClient.Connect(String host, Int32 port, SecureSocketOptions options, 
CancellationToken cancellationToken)
 at MailKit.MailService.Connect(String host, Int32 port, Boolean useSsl, CancellationToken 
cancellationToken)
 at ShorehamPublic.ContactController.SendMailKitMail
```

**Comment by GuardRex** [comment]
Here's the code ...
```c#
try
{
    var message = new MimeMessage();
    message.From.Add(new MailboxAddress(visitor.Name, visitor.Email));
    message.To.Add(new MailboxAddress(destinationEmailName, destinationEmailAddress));
    message.Subject = destinationSubjectLine;
    message.Body = new TextPart("plain")
    {
        Text = $"{visitor.Message}"
    };
    using (var client = new SmtpClient())
    {
        client.Connect("smtpout.secureserver.net", 465, true);
        client.AuthenticationMechanisms.Remove("XOAUTH2");
        client.Authenticate("<FULL_EMAIL_ADDRESS_HERE>", "<MY_PASSWORD_HERE>");
        client.Send(message);
        client.Disconnect(true);
    }
}
catch (Exception ex)
{
    serverReply = "Error: " + ex.ToString();
}
```

**Comment by jstedfast** [comment]
Very strange. The method seems to exist for me...

**Comment by GuardRex** [comment]
hummmmm ... I'm going to play with the dependencies and see what's what. I'll try deleting the `project.lock.json` file, too, for a total refresh.

**Comment by jstedfast** [comment]
My guess is that it's part of System.Net.Security, so make sure you have the latest

**Comment by GuardRex** [comment]
I'm not getting anywhere. Looks like your package isn't ready for RC2 and they pulled that from `System.Net.Security`.

Here's what it's showing for your package ...
```json
"MailKit/1.3.0-beta5": {
        "type": "package",
        "dependencies": {
          "Microsoft.CSharp": "4.0.1-beta-23516",
          "MimeKit": "1.3.0-beta5",
          "Portable.BouncyCastle": "1.8.0",
          "System.Collections": "4.0.11-beta-23516",
          "System.Data.Common": "4.0.1-beta-23516",
          "System.IO.Compression": "4.1.0-beta-23516",
          "System.Linq": "4.0.1-beta-23516",
          "System.Net.NameResolution": "4.0.0-beta-23516",
          "System.Net.NetworkInformation": "4.1.0-beta-23516",
          "System.Net.Primitives": "4.0.11-beta-23516",
          "System.Net.Security": "4.0.0-beta-23516",
          "System.Net.Sockets": "4.1.0-beta-23516",
          "System.Reflection": "4.1.0-beta-23516",
          "System.Runtime": "4.0.21-beta-23516",
          "System.Runtime.Serialization.Primitives": "4.1.0-beta-23516",
          "System.Security.Cryptography.Algorithms": "4.0.0-beta-23516",
          "System.Security.Cryptography.Primitives": "4.0.0-beta-23516",
          "System.Text.Encoding": "4.0.11-beta-23516",
          "System.Text.Encoding.CodePages": "4.0.1-beta-23516",
          "System.Text.Encoding.Extensions": "4.0.11-beta-23516",
          "System.Threading": "4.0.11-beta-23516"
        },
        "compile": {
          "lib/dnxcore50/MailKit.dll": {}
        },
        "runtime": {
          "lib/dnxcore50/MailKit.dll": {}
        }
      },
```

... but the latest RC2 is `"System.Net.Security": "4.0.0-rc2-23623"`.

**Comment by GuardRex** [comment]
Yeah ... I guess I can close. I have to stay on RC2, and I'm even gearing up for the `Hosting` package changes that are imminent for availability on the dev feed.

**Comment by jstedfast** [comment]
Hmmm, I tried to dnvm upgrade but it doesn't find an rc2

**Comment by GuardRex** [comment]
You have to use the `-u` switch to grab it (or them if you're getting more than one) from the dev "nightly builds" feed. Example ...
```
dnvm install 1.0.0-rc2-16357 -a x64 -r coreclr -u
```

**Comment by jstedfast** [comment]
BTW, in my google search for rc2, I found this: https://github.com/aspnet/dnx/issues/3271

**Comment by jstedfast** [comment]
ah, thanks

**Comment by GuardRex** [comment]
Ah, I see. Yes, interesting. They changed it ... doesn't surprise me ... except that we really should be in stabilization at this point ... I mean being RC2 and all, and one would hope to stop having radical changes to the methods like this. Anywho ... whatever the case, I'll have to do something different. They're still working on my SslStream bug at https://github.com/dotnet/corefx/issues/4822, so my simple mail code is still broken on WS 2012 R2. I'll have to figure something else out. Thanks for your help.

**Comment by jstedfast** [comment]
If you find out that they are going to permanently remove that AuthenticateAsClient() method, let me know, and I'll see what I can do to update MailKit to use whatever the replacement is.

Once RC2 goes final, I'll be updating to target that instead of RC1 anyway.

That's supposed to go final in Feb, right? I was trying to google their release schedule earlier and that seemed to be the status.

**Comment by GuardRex** [comment]
Yeah, roadmap for RC2-final in Feb and the word on the street is that they might make it a big announcement for RTM at Build 2016 (March 30-April 1). That would be fun if it goes down like that.

**Comment by BeelzeBu** [comment]
I'm using dot net cli and have the same issue, is there be going any updates for rc2 this is the only feature I'm missing.

**Comment by jstedfast** [comment]
Has RC2 been released? I must have missed the announcement... if it's out, I'll make sure to do a new release this weekend.

**Comment by jstedfast** [comment]
I just checked to see what nuget packages were available and it looks like the latest updates are still the November RC1 releases.

**Comment by GuardRex** [comment]
@jstedfast No, it's not out yet. They're trying to ship RC2-final this month; however, that's a plan and not a firm commitment. The RC1-final packages are considered 'latest stable release.' They are far enough along with RC2, that folks (myself included) are doing well on RC2-nightly right now. You could probably jump-in anytime with `dotnet cli`-nightly and RC2-nightly.

**Comment by BeelzeBu** [comment]
@jstedfast That's right, rc1 is the latest stable, but many of us are using dotnet cli with rc2, this is a game changer in many ways, so I'm glad to help if needed to test this out.

**Comment by mikes-gh** [comment]
@jstedfast +1 I'm using rc2 and came across this as well.
If you need any help with rc2 stuff let me know.

**Comment by jstedfast** [comment]
Most likely I won't have time to work on this until late May. I've got a lot of stuff on my plate atm.

**Comment by mikes-gh** [comment]
RC2 will drop today or next few days.
The sync methods mentioned in this thread are gone (perhaps we could bring them back).
Apparently the vision is to have all IO methods async.
Personally I think they should be leaving the sync methods in place and not break existing API.
There are situations that may even run slower with async.  Particularly in this case where you probably want to do a load of small synchronous IO (such as setting up a new email).

Anyway you could  use the following
(pseudo code)

`string result = Task.Run(AuthenticateAsClientAsync()).Result;`

Its dirty but it might give you compatibility in RC2 for minimal time..

**Comment by jstedfast** [comment]
Thanks, I'll try to look into this over the weekend.
