### ISSUE TITLE
Support for dotnet5.x instead of just dnxcore50

### ISSUE THREAD

**Issue by Gekctek** [jstedfast/MailKit#287]
I can get this library to work using the Dnx Core 5.0 framework (dnxcore50) but am unable to target it using .Net Platform 5.x (dotnet5.x (in my case 5.5)). According the the devs, non application projects such as class libraries should be targeting dotnet5.x instead of dnxcore50 and net4x instead of dnx4x. Here is a [Link](https://github.com/aspnet/Announcements/issues/98) to it

**Comment by jstedfast** [comment]
would it make more sense to use dotnet5.0?

**Comment by jstedfast** [comment]
ok, so now that I understand the mapping a bit better, my guess would be 5.2 or 5.3 should work.

**Comment by Gekctek** [comment]
Do you want me to update my pull request or did you want to change the reference yourself.

**Comment by jstedfast** [comment]
I can update it myself. I'll need to update MimeKit as well.

**Comment by jstedfast** [comment]
FWIW, I'll likely push a new nuget by the end of this coming weekend.

**Comment by jstedfast** [comment]
The MailKit 1.3.0-beta6 nuget has this change. Thanks again for letting me know that I should be using dotnet* instead of dnxcore50 :)

**Comment by Gekctek** [comment]
Thank you
