### ISSUE TITLE
error running on 64 bit machine

### ISSUE THREAD

**Issue by Neoabacus** [jstedfast/MailKit#289]
if i compile for any CPU or 32bit CPU i get the following error

Method not found: 'Int32 System.Environment.get_CurrentManagedThreadId()'.

when executing the following 
    using (var client = new MailKit.Net.Pop3.Pop3Client()) 
    {
        <...login etc...>
        MimeKit.MimeMessage message = client.GetMessage(i);
    }

if i compile for 64 bit i get the following:
The type initializer for 'MimeKit.MimeMessage' threw an exception.

for the same line

I have searched your code, my code and i can't tell where the error is occurring.

**Comment by jstedfast** [comment]
None of my code uses Environment.CurrentManagedThreadId so I have no I'm not sure where you are getting this either.

Maybe seeing the full StackTrace of the exception would help.

What framework are you targeting? .NET 4.5? .NET 4.0? WindowsPhone8.1?

**Comment by jstedfast** [comment]
FWIW, I suspect you copied the wrong MimeKit and/or MailKit dll into your project.

**Comment by Neoabacus** [comment]
i will close this.. found out target machine did not have .NET 4.5, downgraded mailkit to 1.2.14 and mimekit to 1.2.18 and it works fine

**Comment by jstedfast** [comment]
You shouldn't need to downgrade MimeKit or MailKit, just make sure to use the .NET 4.0 assemblies.

**Comment by Neoabacus** [comment]
I tried that and got the same error... downgrading works for the purposes i need it for
