### ISSUE TITLE
Unable to authenticate GoDadday Pop server

### ISSUE THREAD

**Issue by mukeshkolhi** [jstedfast/MailKit#29]
Hi,
I'm using Mailkit library for couple of months in a pilot project. I'm facing a strange issue while authenticating with GoDaddy pop server using MailKit Pop3 Client.

Here is the code.
MailKit.Net.Pop3.Pop3Client client = new MailKit.Net.Pop3.Pop3Client();
CancellationTokenSource cancel = new CancellationTokenSource();
var credentials = new System.Net.NetworkCredential("XXX", "XXX");
var uri = new Uri("pops://pop.secureserver.net:995");
client.Connect(uri, cancel.Token);
client.Authenticate(credentials, cancel.Token);

Exception : "Unable to login. Unexpected response from server: warning: auth_error: authorization failed (authorization failed wrong password)".

Above code able the connect with godaddy pop server. But unable to authenticate the  username & password (while the same pop setting and credentials are working fine with outlook.). While reviewing the code of MailKit.Net.Pop3.Pop3Client class, i found it is checking pop server capabilities in a order of 'APop','Sasl' and  'User'. In my scenario (with GoDaddy Pop server) Pop3Client class is using 'APop' capability to authenticate with pop server. Could you help me on this or guide me to follow correct approach.
Thanks.

**Comment by yadavmukul1986** [comment]
Hi jstedfast,

I am facing the same problem at one of my clients. I have checked out latest Mailkit version (1.16). Client Email Server is APOP. Screens are attached for your reference. Command prompt displayed is from my windows application and text file is from Protocol Logger, enabled in MailKit. I have made following change for APOP - 

client.AuthenticationMechanisms.Remove("XOAUTH2");
client.AuthenticationMechanisms.Remove("APOP");

Please suggest how to do an APOP from mailkit as i am stuck now. 

![apop](https://user-images.githubusercontent.com/9866319/28167581-ad662a72-67f9-11e7-9ead-19fe31a3ed81.png)
