### ISSUE TITLE
Login to iCloud fails

### ISSUE THREAD

**Issue by ben-rockliffe** [jstedfast/MailKit#295]
Not sure if this is something you can actually handle, as the server is seemingly the one at fault, but If you try to connect to the iCloud IMAP services using mailkit the connection is dropped unless you disable PLAIN auth first:

Connected to imaps://imap.mail.me.com:993/
S: * OK [CAPABILITY mr11p00im-iscream004 15E201 XAPPLEPUSHSERVICE IMAP4 IMAP4rev1 SASL-IR AUTH=ATOKEN AUTH=PLAIN] iSCREAM ready to rumble (15E201-d02dd996912b:24762) mr11p00im-iscream004 [31:1461:18:16:40:81]
C: A00000000 AUTHENTICATE PLAIN snip
S: A00000000 NO [AUTHENTICATIONFAILED] Authentication failed
C: A00000001 LOGIN snip@icloud.com snip

Connection dropped

Connected to imaps://imap.mail.me.com:993/
S: * OK [CAPABILITY mr11p00im-iscream023 15E201 XAPPLEPUSHSERVICE IMAP4 IMAP4rev1 SASL-IR AUTH=ATOKEN AUTH=PLAIN] iSCREAM ready to rumble (15E201-d02dd996912b:14338) mr11p00im-iscream023 [28:1275:08:32:19:74]
C: A00000000 LOGIN snip@icloud.com snip
S: A00000000 OK [CAPABILITY XAPPLEPUSHSERVICE IMAP4 IMAP4rev1 ACL RIGHTS=tekx QUOTA LITERAL+ NAMESPACE UIDPLUS CHILDREN BINARY UNSELECT SORT CATENATE URLAUTH LANGUAGE ESEARCH ESORT THREAD=ORDEREDSUBJECT THREAD=REFERENCES CONDSTORE ENABLE QRESYNC CONTEXT=SEARCH CONTEXT=SORT WITHIN SASL-IR SEARCHRES METADATA ID XSENDER X-SUN-SORT ANNOTATE-EXPERIMENT-1 X-UNAUTHENTICATE X-SUN-IMAP XUM1 IDLE] User snip logged in
C: A00000001 NAMESPACE
S: * NAMESPACE (("" "/")) NIL NIL
S: A00000001 OK Completed
C: A00000002 LIST "" "INBOX"
S: * LIST (\NoInferiors) "/" INBOX
S: A00000002 OK Completed

**Comment by jstedfast** [comment]
That's something that you'll have to know and deal with yourself, unfortunately, because there's no way for MailKit to know that iCloud's PLAIN implementation is broken.

To disable PLAIN authentication, just do

```csharp
client.AuthenticationMechanisms.Remove ("PLAIN");
```

before authenticating (I'm assuming you did that already based on the second log, but figured I'd explain in case anyone else comes across this later with the same problem).

Hope that helps.
