### ISSUE TITLE
Support for calendar and contacts

### ISSUE THREAD

**Issue by blacklion9279** [jstedfast/MailKit#297]
Great work @jstedfast ! Couple of questions 
- does this library support calendar / contacts support for IMAP and POP3? If not are you planning to add that in future? 
- does this also support UWP platform ? if not any plans to add that support? 

Thanks and congratulations on awesome work! keep it up.

**Comment by jstedfast** [comment]
Well, technically POP3 and IMAP don't support calendar and contacts. All they support is email.

That said, some clients abuse the IMAP protocol to store email messages with vcard and/or ical attachments in their folders.

You can access those messages using MailKit, but I do not have a parser for them (that is a bit out of scope for this project, imho).

AFAIK, MimeKit and MailKit already support UWP.
