### ISSUE TITLE
Does not support dotnet5.4

### ISSUE THREAD

**Issue by Eaglef90** [jstedfast/MailKit#298]
When you create a ASP.Net Core 1 class library the framework name is "dotnet5.4" which does not appear to be supported by 1.3.0-beta6 as the error "The dependency MailKit 1.3.0-beta6 does not support framework .NetPlatform, Version=v5.4" is thrown.

Example project.json:

    {
        "version": "1.0.0",
        "description": "JobSight.Core Class Library",
        "authors": [ "Matthew Verstraete" ],
        "tags": [ "" ],
        "projectUrl": "",
        "licenseUrl": "",
        "frameworks": {
            "dotnet5.4": {
                "dependencies": {
                    "Microsoft.CSharp": "4.0.1-beta-23516",
                    "System.Collections": "4.0.11-beta-23516",
                    "System.Linq": "4.0.1-beta-23516",
                    "System.Runtime": "4.0.21-beta-23516",
                    "System.Threading": "4.0.11-beta-23516"
                }
            }
        },
        "dependencies":
        {
            "JobSight.DAL": "1.0.0",
            "MailKit": "1.3.0-beta6",
            "Newtonsoft.Json": "8.0.2",
            "System.Net.Http": "4.0.1-beta-23516",
            "System.Text.RegularExpressions": "4.0.11-beta-23516"
        }
    }

**Comment by jstedfast** [comment]
it's impossible to support dotnet54 in MailKit because it's missing a ton of APIs that I need.
