### ISSUE TITLE
Question: Remove Message-Id in headers? Contains my computer name.

### ISSUE THREAD

**Issue by Tauri4n** [jstedfast/MailKit#301]
Hi, I noticed that the headers contain this:
`Message-Id: <L9B5U000EXT4.1HIHP2C689LF@**MyComputerName**>`

Is there a way to remove this?

**Comment by jstedfast** [comment]
Yes.

You can set the Message-Id header manually by doing

```csharp
message.MessageId = MimeUtils.GenerateMessageId ("domain.com");
```

This will use `domain.com` instead of `**MyComputerName**`.

**Comment by Tauri4n** [comment]
So it can't be removed?

**Comment by jstedfast** [comment]
Oh, well, you can also remove the header, but the Message-Id header is a required header according to the specs, so why do you want to remove it?

```csharp
message.Headers.Remove (HeaderId.MessageId);
```

**Comment by Tauri4n** [comment]
Because it has the computer name and I'm not sending from a server. So I don't have a use for a domain.

**Comment by ysunil702** [comment]
When I set my message-id, it becomes duplicate, then the error below comes.
550 Messages should have one or no Message-ID headers, not 2.
@jstedfast

**Comment by jstedfast** [comment]
@ysunil702 how are you setting it?

You should be using `message.MessageId = "msg.id@host.com";`

**Comment by ysunil702** [comment]
yeah i am using same way message.MessageId = "msg.id@host.com"  but there is already one messageid Message-Id: <message-id@**MyComputerName**> while adding my message id its become duplicate.

**Comment by jstedfast** [comment]
Are you loading a message template or something before setting the `MessageId` property? How is it getting a second message-id?
