### ISSUE TITLE
MailKit authentication is insanely slow when incorrect credentials are given.

### ISSUE THREAD

**Issue by mareksuscak** [jstedfast/MailKit#304]
A friend of mine is "abusing" MailKit's SmtpClient for the account verification on the SMTP server that verifies accounts against LDAP (this is what we need in fact). The application doesn't have direct access to the LDAP, that's why he's doing it this way. It works as follows:

```
1. Connect to smtp.example.com on implicitly secured SSL port 465
2. Authenticate by providing login & password.
3. If authentication succeeded, the account is considered verified.
4. If authentication fails, the account doesn't exist and is considered non-verified.
```

Now, not a lot of SMTP clients have support for a low level SMTP access (connect, authenticate, send...) so he's chosen MailKit for that purpose. However we found out that it takes incredibly long time when incorrect account credentials are passed in compared to other SMTP client libraries out there (for example LumiSoft.NET) - e.g. **7.7s** vs **less than 2s**. It is definitely not caused by the speed of SMTP server's response so we suspect there's a bug in MailKit. 

Here's the code:

```csharp
try
{
  using (var client = new SmtpClient())
  {
    client.ServerCertificateValidationCallback = ValidateRemoteCertificate;
    client.Connect(host, 465, true);

    // Note: since we don't have an OAuth2 token, disable
    // the XOAUTH2 authentication mechanism.
    client.AuthenticationMechanisms.Remove("XOAUTH2");

    // Note: only needed if the SMTP server requires authentication
    client.Authenticate(login, password);
    client.Disconnect(true);
  }

  /* Account considered verified */
}
catch(Exception ex) { /* Account considered non-verified */ }
```

**Comment by jstedfast** [comment]
When you supply invalid credentials, MailKit will fall back to another mechanism and try again until it exhausts all mechanisms supported by the SMTP server.

If you want to avoid this, then you'll need to remove all but 1 mechanism from the `client.AuthenticationMechanisms` hash set.
