### ISSUE TITLE
ImapClient authenticate error

### ISSUE THREAD

**Issue by yial2** [jstedfast/MailKit#305]
I am not sure if this is an issue or not, but this is the error I keep getting when trying to authenticate.

(I copied and pasted the demo code, and only change the host and credential - latest version of mail kit, 1.2.19)

![image](https://cloud.githubusercontent.com/assets/1848530/13232586/a0bd2c46-d964-11e5-9193-5a1716f6d4b3.png)

**Comment by jstedfast** [comment]
Any chance you could get me a protocol log? I'll need to feed the IMAP's SASL challenges into the code to see where it is going wrong.

You can get a protocol log by creating the ImapClient like this:

```csharp
client = new ImapCLient (new ProtocolLog ("imap.log"))
```

**Comment by yial2** [comment]
@jstedfast 

[log.txt](https://github.com/jstedfast/MailKit/files/141462/log.txt)

THANK YOU!!

**Comment by jstedfast** [comment]
This commit should fix things for you: https://github.com/jstedfast/MailKit/commit/5bfa014eda9936d05a6db4d3f91a74e41a4ef9c7
