### ISSUE TITLE
How To Star and UnStar A Mail Use MailKit

### ISSUE THREAD

**Issue by oppoic** [jstedfast/MailKit#306]
How to get my stared mails by MailKit,I Use`SearchQuery.Flagged` and get nothing back.
And how i Star and UnStar a mail by Mailkit?

**Comment by jstedfast** [comment]
I'm assuming that you are talking about GMail.

The way to do this is to search for the GMail Label `\Starred` (as a string this would be `"\\Starred"`).

Unfortunately, I just tested this out and it didn't work so I just committed a fix, but anyway, thr way to do it would be to use `SearchQuery.HasGmailLabel ("\\Starred")``.

I'll release a new version with my fix in the next few days.

Thanks for the bug report!

**Comment by jstedfast** [comment]
In the meantime, you can use the following approach to getting the results you want (although sadly it is not as efficient as a proper Search):

```csharp
var summaries = folder.Fetch (0, -1, MessageSummaryItems.UniqueId | MessageSummaryItems.GMailLabels);
var uids = new UniqueIdSet ();
foreach (var summary in summaries) {
    if (!summary.UniqueId.IsValid) // this should never happen...
        continue;

    var starred = false;
    foreach (var label in summary.GMailLabels) {
        if (label == "\\Starred") {
            starred = true;
            break;
        }
    }

    if (starred)
        uids.Add (summary.UniqueId);
}
```

**Comment by jstedfast** [comment]
Oops, I forgot to answer the second part of your question about how to Star and Unstar messages.

```csharp
// to star a message, add the "\\Starred" label...
folder.AddLabels (uid, new string[] { "\\Starred" }, true);

// to unstar a message, remove the "\\Starred" label...
folder.RemoveLabels (uid, new string[] { "\\Starred" }, true);
```

**Comment by oppoic** [comment]
Not Gmail,Gmail is forbidden in China.I'm using qq Mails,which is China most popular mail services. `SearchQuery.Flagged` return my star mails today,but,when I use the way upstars to star my emails,got this message back:
"The IMAP server does not support the Google Mail extensions."
 any other way to star and unstar a mail?many tks :)

**Comment by oppoic** [comment]
I slove it myself,the code is:
`folder.AddFlags(uid, MessageFlags.Flagged, true);
folder.RemoveFlags(uid, MessageFlags.Flagged, true);`
and my search all star mails code is:
`var foldermodel = client.GetFolder(foldername == "Starred" ? "INBOX" : foldername);
                        foldermodel.Open(FolderAccess.ReadOnly);
                        var uids = foldermodel.Search(foldername == "Starred" ? SearchQuery.Flagged : SearchQuery.All).OrderByDescending(m => m.Id).Take(10);`
By this way,I just can get all Inbox Star mails,how can I quickly get All Star mails,which from inbox,outbox...

**Comment by jstedfast** [comment]
Does your imap server have an "All Mail" folder? If so, you could search that.

If not, you'll have to iterate through all of your folders and search for the Flagged messages in each of them.

What IMAP extensions does your server support? Perhaps it supports the MULTISEARCH extension and I could implement support for that in MailKit...

**Comment by oppoic** [comment]
Thanks for your quick answer,Jeffrey.I'm now facing another difficult question about Attachments:when user click a detail page of a mail,I send him attachments's name,in this process,I do not download any attachments,when the user click a attachment,I will download this attachments to my server,then give the url to this user for downloading,then the user download the attachments from my server,Here is my code for download the attachments to my server:

> string filePath = Server.MapPath("/Attachments");
                    foreach (MimeEntity attachment in message.Attachments)
                    {
                        var mimePart = (attachment as MimePart);
                        using (var fileStream = new FileStream(filePath + "/" + attachment.ContentDisposition.FileName, FileMode.Create, FileAccess.Write))
                        {
                            mimePart.ContentObject.DecodeTo(fileStream);
                        }
> }

but while the attachment is very big,it will cost few minutes to download it,I want to give the attachment's url to user directly without downloading to my server.How can i get the attachment's url with MailKit,tks.

**Comment by jstedfast** [comment]
I have no idea what you are asking. What url do you want? Give me an example so I know what you are talking about.

**Comment by oppoic** [comment]
Long story short:user want to download attachment in a mail ,need i download attachment to my server,then let user download it from my server?can user download the attachment directly.like:http://www.domain.com/attachment/attachment1.zip how can i get this url,the attachment url.

**Comment by oppoic** [comment]
sorry,my poor English cost your a lot of time :(

**Comment by jstedfast** [comment]
There's no way to get that url because that's not how IMAP works. Some servers may support something like that, but there's no specification for it that I'm aware of.

**Comment by oppoic** [comment]
Thanks for answer me!so,while user use my program which developed with MailKit to download his attachment,I must download attachment to my server,then user download it from my server?It may cost a lot of time.How do you deal with this program?also download the attachments to your own server?
