### ISSUE TITLE
Standalone usage on Linux w/ PHP

### ISSUE THREAD

**Issue by mstaack** [jstedfast/MailKit#310]
Hello everyone,

i was looking for a decent well made mail package and found this.
Is there any practical and smart way to use this in a PHP Context?
Could this be compiled to a native linux binary i could call from php?

Any hints or ideas?

thanks max

**Comment by jstedfast** [comment]
You can use MailKit on Linux, but not easily from PHP since MailKit is written using C# and meant for the .NET runtime (either via Microsoft's .NET runtime or the Mono runtime).

I don't even know where to begin trying to use it from PHP... sorry.
