### ISSUE TITLE
Email Priority

### ISSUE THREAD

**Issue by PaijoRX** [jstedfast/MailKit#311]
i'm using mailkit to retrive email from my server. and i want to get the priority of email (high, normal, low).
from this code always got priority: Normal
~~~
 for (int i = 0; i < pop3Client.Count; i++) {
     MimeMessage mimeMessage = pop3Client.GetMessage(i);

    System.Console.WriteLine(mimeMessage.MessageId);
    System.Console.WriteLine(mimeMessage.Priority);
    System.Console.WriteLine(mimeMessage.Importance.ToString());
    System.Console.WriteLine(mimeMessage.TextBody);
}
~~~

but from the log always got right priority.
~~~
new ProtocolLogger("log\\pop3.log")

S: X-Priority: 2 (High)
~~~

How to get the priority from email? Thanks

**Comment by jstedfast** [comment]
It looks like MimeKit's MimeMessage class does not parse the X-Priority header. It only pays attention to the `Priority` and `Importance` headers.

Also, I was unaware that there was even a value of 2. I always thought X-Priority only used 1, 3, and 5 (this is the problem with non-standard headers :-\)

**Comment by jstedfast** [comment]
I guess the way that you can get the value of the `X-Priority` header is as follows:

```csharp
var xpriority = message.Headers[HeaderId.XPriority];
if (!string.IsNullOrEmpty (xpriority)) {
    switch (int.Parse (xpriority.Split (' ', '\t'))) {
    case 1: // highest priority
    case 2: // high priority
    case 3: // normal priority
    case 4: // low priority
    case 5: // lowest priority
    }
}
```

**Comment by jstedfast** [comment]
I've added an XPriority property to MimeMessage for this:

https://github.com/jstedfast/MimeKit/commit/dbf718bbeec00e46d7441d6ea80b69ccf775fb8b

**Comment by PaijoRX** [comment]
Thank you for your quick respond.
But, have you publish this update on NuGet version ?

**Comment by PaijoRX** [comment]
i'm using thunderbird as email client. it's have 1,2,3,4,5 priority.
while waiting your NuGet version, i have try your code below:
~~~
var xpriority = message.Headers[HeaderId.XPriority];
if (!string.IsNullOrEmpty (xpriority)) {
    switch (int.Parse (xpriority.Split (' ', '\t'))) {
    case 1: // highest priority
    case 2: // high priority
    case 3: // normal priority
    case 4: // low priority
    case 5: // lowest priority
    }
}
~~~
but still can't get right value of priority. For normal priority will return null.

**Comment by jstedfast** [comment]
Yea, because the header probably doesn't exist.

And no, I have not published to NuGet. I generally only publish every 2 weeks or so and I *just* published on Sunday, so it'll be another 2 weeks or so before I publish again.

**Comment by jstedfast** [comment]
Change the code to this:

```csharp
var xpriority = message.Headers[HeaderId.XPriority];
if (!string.IsNullOrEmpty (xpriority)) {
    switch (int.Parse (xpriority.Split (' ', '\t'))) {
    case 1: // highest priority
    case 2: // high priority
    case 3: // normal priority
    case 4: // low priority
    case 5: // lowest priority
    }
} else {
    // normal priority
}
```

**Comment by PaijoRX** [comment]
Ok. Thanks :+1:

**Comment by arman-g** [comment]
> 
> 
> Change the code to this:
> 
> ```cs
> var xpriority = message.Headers[HeaderId.XPriority];
> if (!string.IsNullOrEmpty (xpriority)) {
>     switch (int.Parse (xpriority.Split (' ', '\t'))) {
>     case 1: // highest priority
>     case 2: // high priority
>     case 3: // normal priority
>     case 4: // low priority
>     case 5: // lowest priority
>     }
> } else {
>     // normal priority
> }
> ```

Hi, are priority values changed in v2.1.5.1? to

NonUrgent	0	The message has non-urgent priority.
Normal	1	The message has normal priority.
Urgent	2	The message has urgent priority. 

http://www.mimekit.net/docs/html/T_MimeKit_MessagePriority.htm
