### ISSUE TITLE
Can't connect to exchange server

### ISSUE THREAD

**Issue by orc886** [jstedfast/MailKit#313]
The error was: System.Security.Authentication.AuthenticationException: The remote certificate is invalid according to the validation procedure. 
at: MailKit.Net.Imap.ImapClient.Connect(String host, Int32 port, SecureSocketOptions options, CancellationToken cancellationToken)

We checked auth user and password, and it worked with another library (S22)
What can cause that?

**Comment by jstedfast** [comment]
That's not an authentication error involving a user name and password, that is an SSL error involving the server's certificate.

To properly handle this, you need to set a custom certificate handler like this:

```csharp
client.ServerCertificateValidationCallback = MyCustomServerCertificateValidationCallback;
```

Most likely your mail server's certificate is self-signed and thus your system does not trust it. Another possibility is that it is signed by a Certificate Authority (CA) that your system's trust store does not trust. A third option is that your virus scanner is trying to bait-and-switch the mail server's SSL certificate with its own (see [Avast!'s FAQ](https://www.avast.com/no-no/faq.php?article=AVKB91) for an example of what I'm talking about). And, of course, the last possibility is that you are the victim of a Man-In-The-Middle ([MITM](https://en.wikipedia.org/wiki/Man-in-the-middle_attack)) attack.

S22.Imap simply [accepts all certificates](https://github.com/smiley22/S22.Imap/blob/master/ImapClient.cs#L223) which is not really safe (see the MITM link above to learn why), but if that's what you want to do, MailKit will let you do that, too:

```csharp
client.ServerCertificateValidationCallback = (sender, cert, chain, error) => true;
```

Hope that helps.

**Comment by orc886** [comment]
Will try it out. Thanks!
