### ISSUE TITLE
A call to SSPI failed. The token supplied to the function is invalid

### ISSUE THREAD

**Issue by SuhovDE** [jstedfast/MailKit#314]
Hello, I receive an error when try to connect to SMTP server:

> System.Security.Authentication.AuthenticationException: A call to SSPI failed, see inner exception. ---> System.ComponentModel.Win32Exception: The token supplied to the function is invalid
>    --- End of inner exception stack trace ---
>    at System.Net.Security.SslState.StartSendAuthResetSignal(ProtocolToken message, AsyncProtocolRequest asyncRequest, Exception exception)
>    at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
>    at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
>    at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
>    at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
>    at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
>    at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
>    at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
>    at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
>    at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
>    at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
>    at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
>    at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
>    at System.Net.Security.SslState.ForceAuthentication(Boolean receiveFirst, Byte[] buffer, AsyncProtocolRequest asyncRequest)
>    at System.Net.Security.SslState.ProcessAuthentication(LazyAsyncResult lazyResult)
>    at System.Net.Security.SslStream.AuthenticateAsClient(String targetHost, X509CertificateCollection clientCertificates, SslProtocols enabledSslProtocols, Boolean checkCertificateRevocation)
>    at MailKit.Net.Smtp.SmtpClient.Connect(String host, Int32 port, SecureSocketOptions options, CancellationToken cancellationToken)
>    at SmtpClient.SmtpClient.Init(SmtpSettings settings, String sender)
>    at Pop3SmtpClient.Pop3SmtpClient.InitSend()
>    at MessengerSendReceive.Sender.Send(String clientType, String settings, IMessage message)
> System.ComponentModel.Win32Exception (0x80004005): The token supplied to the function is invalid

**Comment by jstedfast** [comment]
The problem appears to either be a bug in System.Net.Security.SslStream or a bug in your server's SSL implementation.

The token that the error is complaining about comes from the server, not from MailKit.

**Comment by SuhovDE** [comment]
Jstedfast, thank you for answer

**Comment by andresmoschini** [comment]
@jstedfast Could this problem be related to have ```SmtpClient.ClientCertificates = null```?

@SuhovDE did you find a way to fix it?

**Comment by SuhovDE** [comment]
@andresmoschini We have updated a certificate and the problem was gone.
We didn't investigated what exactly was wrong.

**Comment by andresmoschini** [comment]
Thanks @SuhovDE !
