### ISSUE TITLE
Imap Order By Issue

### ISSUE THREAD

**Issue by Radhay** [jstedfast/MailKit#315]
Hello

when i doing sorting using mailkit i am getting following error

The IMAP server does not support the SORT extension.

I am using following code

var orderBy = new[] { MailKit.Search.OrderBy.ReverseArrival };

 foreach (var uid in inbox.Search(query, orderBy))
                {
                    var message = inbox.GetMessage(uid);
                    Console.WriteLine("[match] {0}: {1}", uid, message.Subject);
                }
when i run using this code i am getting error
The IMAP server does not support the SORT extension.

Please help me i am not getting any help from anywhere

Thanks
Radhay

**Comment by jstedfast** [comment]
You are getting that error because your IMAP server does not support sorting.

Many of the IMAP features are *optional* extensions that the server may or may not implement. In order to check if the server supports them, you need to check the ImapClient.Capabilities flags for the appropriate flag.

For example:

```csharp
if (client.Capabilities.HasFlag (ImapCapabilities.Sort)) {
    var orderBy = new[] { MailKit.Search.OrderBy.ReverseArrival };
    foreach (var uid in inbox.Search(query, orderBy)) {
        var message = inbox.GetMessage(uid);
        Console.WriteLine("[match] {0}: {1}", uid, message.Subject);
    }
} else {
    // handle this in another way
}
```

**Comment by Radhay** [comment]
Hello 

I have to sort all the record by subject,Bcc,cc and date.

and i used the code which are send to me.

But in this i got all the emails in descending order.

But i want order by many way.

Please help me or tell why imap server does not support order by.

Regards,
Radhay

**Comment by jstedfast** [comment]
If you want to order by all those fields, you'll need to use:

```csharp
using System.Linq;

...

var items = client.Fetch (0, -1, MessageSummaryItems.Envelope | MessageSummaryItems.UniqueId).ToList ();
```

Once you do that, you'll need to write your own `IComparer` and then use `List.Sort()` or `Array.Sort()` to sort your values.

I don't know why your server doesn't support the SORT extension. It just doesn't. Not all servers support it.

**Comment by jstedfast** [comment]
Actually, it looks like MailKit already has some custom sorters to help you (I forgot I wrote them):

```csharp
using System.Linq;

...

var items = client.Fetch (0, -1, MessageSummaryItems.Envelope | MessageSummaryItems.UniqueId).ToList ();
MessageSorter.Sort (items, orderBy);
```

**Comment by Radhay** [comment]
Hello,

i also don't know that why it's not support.

tell me that can we add this or not.

or which mailkit version support it.

Regards,
Radhay

**Comment by jstedfast** [comment]
MailKit is the IMAP *client*, not the server. Therefor it's not possible for MailKit to support server-side sorting if the *server* does not support it.

*You* cannot add SORT support to your IMAP server and neither can I. You have to ask the vendor of your IMAP server to add support for it.

**Comment by nikita030493** [comment]
Does the search method still have an overload - inbox.Search(SearchQuery.All, new[] { OrderBy.ReverseArrival }) ? There are 4 overloads and none of them has place for the ordering argument.

**Comment by jstedfast** [comment]
No, the `Search()` methods that take a OrderBy argument were renamed to `Sort()` a few years ago :)

**Comment by nikita030493** [comment]
Thank you for the response!

While I was able to solve the problem of taking only latest n amount of emails using:
`inbox.Search(SearchQuery.All).Reverse().Take(50);`,

I guess using Sort() is more descriptive after all:
`inbox.Sort(SearchQuery.All, new[] { OrderBy.Arrival }).Take(50);`
