### ISSUE TITLE
Sent item message id

### ISSUE THREAD

**Issue by atiqi36** [jstedfast/MailKit#318]
Hi,

I don't believe this has been asked before. Is there anyway of saving the message id of a sent email message. As you know sent emails are saved if normally we connect through imap from outlook or any email client.
My scenario is that my system will send an email and if there is no reply within x number of days, it will send a reminder message with the original message attached. 
Another question is when receiving an email does InReplyTo property works perfectly? As I need to check if the email received is from any email I sent.
Thanks in advance.

**Comment by jstedfast** [comment]
> Is there anyway of saving the message id of a sent email message.

Look at the [MimeMessage.MessageId](http://www.mimekit.net/docs/html/P_MimeKit_MimeMessage_MessageId.htm) property.

Or if you are querying an IMAP server and don't want to download the full message, you can do this:

```csharp
var msgid = folder.Fetch (uid, MessageSummaryItems.Envelope).FirstOrDefault ().Envelope.MessageId;
```

Docs for Envelope: http://www.mimekit.net/docs/html/T_MailKit_Envelope.htm

> Another question is when receiving an email does InReplyTo property works perfectly?

The `InReplyTo` property isn't a calculation or based or heuristics or anything, it's just the parsed message-id that exists in the `In-Reply-To` header of the message. It's up to the client replying to the message to set that appropriately. If the client does, then it will "work perfectly". If not, then it won't.

Hope that helps.

**Comment by atiqi36** [comment]
Hi,

Thanks for the quick reply.

Sorry I am a bit confused, when I am sending a message, it goes through smtp server so how can I get the messageId of it while sending a new message?

**Comment by jvilhuber** [comment]
It depends on the service. Most services don't automatically 'link' smtp and imap (gmail does, but most others I've seen don't), so your code may beed to put a copy of the message in the imap sent folder. In either case, you'll need to go to IMAP (possibly after adding the message to sent yourself) and fetch the MessageId as Jeff outlined.

**Comment by atiqi36** [comment]
Ok so is there anyway to check if smtp and imap is linked because last thing I want to do is copy to sent folder every time and have duplicates there?

**Comment by jvilhuber** [comment]
Not that I know of. So far gmail has been the only one I've encountered
that automatically populates the Sent folder. All others don't.

Perhaps Jeff has a better answer.
jan

**Comment by jstedfast** [comment]
If you are sending the message over SMTP, then you have the MimeMessage locally before it is sent. ALl you need to do is assign it a message-id before you pass it to the `SmtpClient.Send()` method:

```csharp
var msgid = message.MessageId = MimeUtils.GenerateMessageId ();
client.Send (message);
```

Then you can stick `msgid` into your local database or wherever you are storing it for tracking.

**Comment by Samra10** [comment]
I tried another solution to get the ID of the message sent with SMTP Client, to trace any replied messages.

Before you send your message add a hidden ID property to the message headers,
![Capture](https://user-images.githubusercontent.com/10185327/60954020-8f3c5700-a2fe-11e9-9852-a53a021a1917.PNG)

Now continue and send your message,
Wait about 10 Seconds, Then you will use the **IMAP** Client to get your Sent folder and for each message in your folder,
loop over the message headers and check if anyone of them is ==`messageIdentity `, now you catch your 
sent message successfully and get any information about it you wand like ID etc...

**Comment by Hoopou** [comment]
This works with gmail and Outlook:

```c#
mimeMessage.MessageId = MimeUtils.GenerateMessageId();
mimeMessage.Headers.Add(HeaderId.MessageId, mimeMessage.MessageId);
var response = smtpClient.Send(mimeMessage);
```

And if you look at the response from the server, you should see the MessageId somewhere in the string.
