### ISSUE TITLE
Reply function

### ISSUE THREAD

**Issue by PaijoRX** [jstedfast/MailKit#319]
Hi @jstedfast ,

there is any function to reply email based on messageId ?
when i got new email, i want to auto reply it. and attach body/content/attachment of new email  on email reply.

thanks,

**Comment by jstedfast** [comment]
There is no reply function, but you can copy & paste either of the solutions mentioned in the FAQ:

https://github.com/jstedfast/MailKit/blob/master/FAQ.md#Reply
