### ISSUE TITLE
Yahoo Account email get issue

### ISSUE THREAD

**Issue by Radhay** [jstedfast/MailKit#320]
Hello,

I want to get all the email using yahoo account but i am getting the error

Too many bad login attempts.

but my all credential is okie and code is work for gmail account.

Tell me what i do

Regards,
Radhay

**Comment by jstedfast** [comment]
Get a [protocol log](https://github.com/jstedfast/MailKit/blob/master/FAQ.md#ProtocolLog) and see what authentication mechanisms are failing, then disable those like this:

```csharp
client.AuthenticationMechanisms.Remove ("XOAUTH2");
```
