### ISSUE TITLE
How can we send with attachments using smtp

### ISSUE THREAD

**Issue by haria93** [jstedfast/MailKit#321]
How can we add attachments with mail? i have tried but i cant find the attachments.add option while using mail kit in asp.net core

**Comment by jstedfast** [comment]
I would probably recommend using the `BodyBuilder` class, but I've written up an FAQ on how to do it multiple ways:

http://www.mimekit.net/docs/html/FrequentlyAskedQuestions.htm#CreateAttachments

**Comment by haria93** [comment]
thank you jsed .
