### ISSUE TITLE
Authentication failed

### ISSUE THREAD

**Issue by SuhovDE** [jstedfast/MailKit#322]
Hello,

Periodically when I connect to IMAP server I receive error:

> MailKit.Security.AuthenticationException: Authentication failed.
>    at MailKit.Net.Imap.ImapClient.Authenticate(Encoding encoding, ICredentials credentials, CancellationToken cancellationToken)
>    at MailKit.MailService.Authenticate(String userName, String password, CancellationToken cancellationToken)
 
IMAP log:

> Connected to imaps://imapserver.com:993/
> S: * OK The Microsoft Exchange IMAP4 service is ready.
> C: A00000000 CAPABILITY
> S: * CAPABILITY IMAP4 IMAP4rev1 AUTH=PLAIN AUTH=NTLM AUTH=GSSAPI UIDPLUS MOVE ID CHILDREN IDLE NAMESPACE LITERAL+
> S: A00000000 OK CAPABILITY completed.
> C: A00000001 AUTHENTICATE NTLM
> S: +
> C: TlRMTVNTUAABAAAABwIIAAAAAAAgAAAAAAAAACAAAAA=
> S: + TlRMTVNTUAACAAAACAAIADgAAAAFAokC/swBpqO/71gAAAAAAAAAAI4AjgBAAAAABgOAJQAAAA9PAEEATQBDAAIACABPAEEATQBDAAEAGABNAEMAVABFAFgAQQBSAFMAUgBWADAAMQAEABAAbwBhAG0AYwAuAGMAbwBtAAMAKgBNAEMAVABFAFgAQQBSAFMAUgBWADAAMQAuAG8AYQBtAGMALgBjAG8AbQAFABAAbwBhAG0AYwAuAGMAbwBtAAcACADS32cxyZTRAQAAAAA=
> C: TlRMTVNTUAADAAAAGAAYAFQAAAAYABgAbAAAAAAAAABAAAAAFAAUAEAAAAAAAAAAVAAAAAAAAACEAAAAAYIIAG8AbQBhAG4ALgBzAHQAYQB0AHMAou72ajqXvS4AAAAAAAAAAAAAAAAAAAAAshgyuH6SJ/S5AP65OD29I8RMy9BPLZSJ
> S: A00000001 NO AUTHENTICATE failed.
> C: A00000002 AUTHENTICATE PLAIN
> S: +
> C: AG9tYW4uc3RhdHMAMG1AbiR0QHQk
> S: A00000002 NO AUTHENTICATE failed.
> C: A00000003 LOGIN plain_username plain_password
> S: A00000003 NO Server Unavailable. 15
> S: * BYE Connection closed. 14
> C: A00000004 LOGOUT

The problem is that with Chilkat library I can authenticate stable. What can be reason?
Thank you.

**Comment by jstedfast** [comment]
Try doing this before calling `client.Authenticate (...)`:

```csharp
client.AuthenticationMechanisms.Clear ();
```

This will prevent MailKit from trying to authenticate via `NTLM` and `PLAIN` and instead just use the `LOGIN` command (which is probably what ChilKat is using).

It's possible that the server is disabling your login ability due to the failed `NTLM` and `PLAIN` attempts.

**Comment by SuhovDE** [comment]
Thank you @jstedfast, it resolved the issue.
