### ISSUE TITLE
Syntax error in untagged ESEARCH response. Unexpected token: '('

### ISSUE THREAD

**Issue by kduthoy** [jstedfast/MailKit#323]
Hi,

when i call 

    IMAPfolder.Search(MailKit.Search.SearchQuery.ChangedSince(<value>)) 

on my IMAP server, it throws an exception with message 

    "Syntax error in untagged ESEARCH response. Unexpected token: '('".

The log output is:

    C: A00000012 UID SEARCH RETURN () MODSEQ 284529
    S: * ESEARCH (TAG "A00000012") UID ALL 33866,33897,33906 (MODSEQ 284535)

Is there an error in the response parser?

Kind regards
Kristof

**Comment by jstedfast** [comment]
Looks like there's a bug in the IMAP server's response, actually.

AFAICT looking at the spec, the ()'s are not allowed around the MODSEQ part of the response. It should instead look like this:

```
S: * ESEARCH (TAG "A00000012") UID ALL 33866,33897,33906 MODSEQ 284535
```

**Comment by jstedfast** [comment]
Just tested this with GMail and it matches what I expected:

```
C: A00000008 UID SEARCH RETURN () MODSEQ 20
S: * ESEARCH (TAG "A00000008") UID ALL 343:393,395:400,402:403,410:412 MODSEQ 41506
S: A00000008 OK SEARCH completed (Success)
```

**Comment by jstedfast** [comment]
If you can build from source, give the latest code a try and see if that fixes it for you.
