### ISSUE TITLE
Can't search email subject on imap server

### ISSUE THREAD

**Issue by vnwind** [jstedfast/MailKit#324]
Hi Jeffrey
I can't figure out why this work on gmail but not on another imap server. All I want is to search for unread emails with the subject that match the name. Here is the code

var query = SearchQuery.SubjectContains(name).And(SearchQuery.NotSeen);
var matchedMsgList = inbox.Search(query);
if (matchedMsgList.Count != 0)
         // do something

I have the same unread email with the same subject "Lead me" and the name is "Lead" but only Gmail account return the match while the other imap server does not. 

I looked at what capabilities supported by this imap server and it returns 
ImapCapabilities.IMAP4rev1 
ImapCapabilities.Status 
ImapCapabilities.Idle 
ImapCapabilities.Namespace 
ImapCapabilities.Id 
ImapCapabilities.Children 
ImapCapabilities.StartTLS 
ImapCapabilities.Unselect

while GMail returns
ImapCapabilities.ListStatus 
ImapCapabilities.UTF8Accept 
ImapCapabilities.GMailExt1 
ImapCapabilities.XList 
ImapCapabilities.Move 
ImapCapabilities.IMAP4rev1 
ImapCapabilities.Status 
ImapCapabilities.Quota 
ImapCapabilities.Idle 
ImapCapabilities.Namespace 
ImapCapabilities.Id 
ImapCapabilities.Children 
ImapCapabilities.Unselect 
ImapCapabilities.UidPlus 
ImapCapabilities.CondStore 
ImapCapabilities.ESearch 
ImapCapabilities.Compress 
ImapCapabilities.Enable 
ImapCapabilities.ListExtended

So I am wondering if  ImapCapabilities.ESearch is required for the search to work or it is not related at all?
Thanks

**Comment by jstedfast** [comment]
No, ESearch is not required (ESearch just allows the client to request different return values from the SEARCH command).

So... the problem with IMAP searching is that it's up to the server to decide what matches and what doesn't :(

My guess is that GMail's implementation looks for the substring while your other IMAP server probably uses an exact-match or something silly.

You could try using this instead:

```csharp
var query = SearchQuery.HeaderContains("Subject", name).And(SearchQuery.NotSeen);
```

That might work...

**Comment by vnwind** [comment]
This is very werid, Let say the subject is "My Lead 1123" and If i search for "1123" then it return the result but if I search for "Lead" then it does not return anything. Can you think of any reason why?

**Comment by jstedfast** [comment]
Nope, that is completely bizarre.
