### ISSUE TITLE
Support for netcoreapp and dotnet cli-based aspnet webapps

### ISSUE THREAD

**Issue by PabloZaiden** [jstedfast/MailKit#325]
Hi! With the new dotnet cli (dnx + dnu + dnvm is now deprecated) the package is not working
When trying to restore packages I'm getting:

```
Package MailKit 1.3.0-beta7 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). Package MailKit 1.3.0-beta7 supports:
      - dotnet5.5 (.NETPlatform,Version=v5.5)
      - monoandroid10 (MonoAndroid,Version=v1.0)
      - net40 (.NETFramework,Version=v4.0)
      - net45 (.NETFramework,Version=v4.5)
      - net451 (.NETFramework,Version=v4.5.1)
      - win81 (Windows,Version=v8.1)
      - wpa81 (WindowsPhoneApp,Version=v8.1)
      - xamarinios10 (Xamarin.iOS,Version=v1.0)
    One or more packages are incompatible with .NETCoreApp,Version=v1.0.

```
The repo with the official sample projects is: https://github.com/aspnet/cli-samples

**Comment by jstedfast** [comment]
Libraries are not supposed to support netcoreapp, only apps use that framework.

What you want is netcorestandard which is what I plan to support as soon as they release the next beta.

**Comment by PabloZaiden** [comment]
Thanks! After reading this: https://github.com/dotnet/corefx/blob/master/Documentation/architecture/net-platform-standard.md I think you meant netstandard, not netcorestandard.
Right?

**Comment by jstedfast** [comment]
Er, yea, sorry. I meant netstandard.
