### ISSUE TITLE
Get Email in reverse order

### ISSUE THREAD

**Issue by Radhay** [jstedfast/MailKit#326]
Hello ,

can i get email list in reverse order while using custom paging.

Regards,
Radhay

**Comment by jstedfast** [comment]
Yes. How would you get items in reverse order from an array? It works exactly the same with with POP3. If you are using IMAP, you might be able to use the `ImapFolder.Search()` method to get a sorted list of messages in the order you want them, but only if the server supports the SORT extension. If it doesn't, then you'll need to do it the same way you'd do it for POP3.
