### ISSUE TITLE
obscure bug

### ISSUE THREAD

**Issue by Radzhab** [jstedfast/MailKit#329]
I have 1 message in mail box. 

```
 var inbox = client.Inbox; 
 var test = inbox.Count; // its show 0 
Console.WriteLine("Total messages: {0}", inbox.Count); // its show 1 message

```
What i make wrong?

**Comment by jstedfast** [comment]
I have no idea what you mean. Are you looking at this in the debugger and test is 0? Are you sure you stepped *over* the line and test has been initialized?

This can't happen.
