### ISSUE TITLE
NTLM with DefaultNetworkCredentials

### ISSUE THREAD

**Issue by SuhovDE** [jstedfast/MailKit#332]
Hello,

I’m trying to work out how to authenticate a sender on SMTP server using NTLM (Windows Authentication) thus avoiding the need to store any login credentials, just using  CredentialCache.DefaultNetworkCredentials. But every time when I try it, I receive  Authentication unsuccessful error. But when I call Authenticate function specifying user name and password it works, although user is the same.
What can be wrong?

For example this code fails:
```c#
Client.AuthenticationMechanisms.Clear();
Client.AuthenticationMechanisms.Add("NTLM");
var Uri = new Uri(string.Format(@"{0}://{1}:{2}", 
      Settings.SecureSocketOptions == MailKit.Security.SecureSocketOptions.None ? "smtp" :   "smtps",
      Settings.Server, 
      Settings.Port));
 ICredentials defCredentials = CredentialCache.DefaultNetworkCredentials;
 NetworkCredential credential = defCredentials.GetCredential(Uri, "NTLM");
 Client.Authenticate(credential);
```

This also:
```c#
Client.AuthenticationMechanisms.Clear();
Client.AuthenticationMechanisms.Add("NTLM");
Client.Authenticate(CredentialCache.DefaultNetworkCredentials);
```
But this works:
```c#
Client.AuthenticationMechanisms.Clear();
Client.AuthenticationMechanisms.Add("NTLM");
Client.Authenticate(new NetworkCredential(Settings.UserName, Settings.Password));
```
This also:
```c#
Client.AuthenticationMechanisms.Clear();
Client.AuthenticationMechanisms.Add("NTLM");
Client.Authenticate(Settings.UserName, Settings.Password);
```
Thank you in advance.

**Comment by SuhovDE** [comment]
It seems that the reason is that in SaslMechanismNtlm.cs you read User name, Password and Domain from provided credentials, but in DefaultNetworkCredentials they are empty.

But I still has not found solution for my issue.
Is there something like SmtpClient.UseDefaultCredentials from System.Net.Mail?

**Comment by jstedfast** [comment]
There is nothing like SmtpClient.UseDefaultCredentials.

This is the way it should work:

```csharp
Client.AuthenticationMechanisms.Clear();
Client.AuthenticationMechanisms.Add("NTLM");
Client.Authenticate(CredentialCache.DefaultNetworkCredentials);
```

If that doesn't work, then you need to figure out why it doesn't and fix that.

**Comment by jstedfast** [comment]
> but in DefaultNetworkCredentials they are empty.

Most likely this means that the default credentials were never initialized (nothing MailKit can do about that).

**Comment by SuhovDE** [comment]
As I understood CredentialCache.DefaultNetworkCredentials has empty UserName, Password and Domain by design. I just want to say, that most likely  it is not correct to use CredentialCache.DefaultNetworkCredentials to authenticate as current user.

But it does not give me answer how to use MailKit SmtpClient with current user credentials.

Could you give me please an example how to use MailKit.Net.Smtp.SmtpClient the same way as it is implemented in System.Net.Mail.SmtpClient with UseDefaultCredentials=true?

**Comment by SuhovDE** [comment]
I have examined the source code of System.Net.Mail
They also use CredentialCache.DefaultNetworkCredentials

```C#
public bool UseDefaultCredentials {
       get {
            return (transport.Credentials is SystemNetworkCredential) ? true : false;
        }
        set {
             if (InCall) {
                  throw new InvalidOperationException(SR.GetString(SR.SmtpInvalidOperationDuringSend));
             }
            transport.Credentials = value ? CredentialCache.DefaultNetworkCredentials : null;
         }
}
```

But when DefaultNetworkCredentials  are used, they prepare m_CredentialsHandle  different way without reading User name and Password directly from provided credentials 

 ```C#
//
// check if we're using DefaultCredentials
//
if (credential is SystemNetworkCredential)
{
          GlobalLog.Print("NTAuthentication#" + ValidationHelper.HashString(this) + "::.ctor(): using DefaultCredentials");
          m_CredentialsHandle = SSPIWrapper.AcquireDefaultCredential(
                                                GlobalSSPI.SSPIAuth,
                                                package,
                                                (m_IsServer? CredentialUse.Inbound: CredentialUse.Outbound));

          m_UniqueUserId = "/S"; // save off for unique connection marking ONLY used by HTTP client
}
```

**Comment by jstedfast** [comment]
I was going to suggest taking a look at the referencesource, but it looks like you did already :)

As I suspected, they are using internal API's that MailKit does not have access to.

This means you are out of luck trying to use CredentialCache.DefaultNetworkCredentials.

Sorry.

**Comment by UriHendler** [comment]
I don't know if anyone has solved this issue yet.

I managed to get it working (tested against Exchange 2010), using the [NSspi](https://github.com/antiduh/nsspi) library for the SSPI auth part.

```csharp
using NSspi;
using NSspi.Contexts;
using NSspi.Credentials;

/// <summary>
/// The NTLM Integrated Auth SASL mechanism.
/// </summary>
/// <remarks>
/// A SASL mechanism based on NTLM using the credentials of the current user 
/// via Windows Integrated Authentication (SSPI).
/// </remarks>
public class SaslMechanismNtlmIntegrated : SaslMechanism
{
    enum LoginState
    {
        Initial,
        Challenge
    }

    LoginState state;
    ClientContext sspiContext;
    
    /// <summary>
    /// Initializes a new instance of the <see cref="MailKit.Security.SaslMechanismNtlmIntegrated"/> class.
    /// </summary>
    /// <remarks>
    /// Creates a new NTLM Integrated Auth SASL context.
    /// </remarks>
    public SaslMechanismNtlmIntegrated() : base(string.Empty, string.Empty)
    {
    }

    /// <summary>
    /// Gets the name of the mechanism.
    /// </summary>
    /// <remarks>
    /// Gets the name of the mechanism.
    /// </remarks>
    /// <value>The name of the mechanism.</value>
    public override string MechanismName
    {
        get { return "NTLM"; }
    }

    /// <summary>
    /// Gets whether or not the mechanism supports an initial response (SASL-IR).
    /// </summary>
    /// <remarks>
    /// SASL mechanisms that support sending an initial client response to the server
    /// should return <value>true</value>.
    /// </remarks>
    /// <value><c>true</c> if the mechanism supports an initial response; otherwise, <c>false</c>.</value>
    public override bool SupportsInitialResponse
    {
        get { return true; }
    }

    /// <summary>
    /// Parses the server's challenge token and returns the next challenge response.
    /// </summary>
    /// <remarks>
    /// Parses the server's challenge token and returns the next challenge response.
    /// </remarks>
    /// <returns>The next challenge response.</returns>
    /// <param name="token">The server's challenge token.</param>
    /// <param name="startIndex">The index into the token specifying where the server's challenge begins.</param>
    /// <param name="length">The length of the server's challenge.</param>
    /// <exception cref="System.InvalidOperationException">
    /// The SASL mechanism is already authenticated.
    /// </exception>
    /// <exception cref="SaslException">
    /// An error has occurred while parsing the server's challenge token.
    /// </exception>
    protected override byte[] Challenge(byte[] token, int startIndex, int length)
    {
        if (IsAuthenticated)
            throw new InvalidOperationException();

        InitializeSSPIContext();

        byte[] serverResponse = null;
        SecurityStatus status;
        
        switch (state)
        {
            case LoginState.Initial:
                status = sspiContext.Init(null, out serverResponse);
                state = LoginState.Challenge;
                break;
            case LoginState.Challenge:
                status = sspiContext.Init(token, out serverResponse);
                IsAuthenticated = true;
                break;
            default:
                throw new IndexOutOfRangeException("state");
        }

        return serverResponse;
    }

    private void InitializeSSPIContext()
    {
        if (sspiContext != null)
        {
            return;
        }

        var credential = new ClientCurrentCredential(PackageNames.Ntlm);

        sspiContext = new ClientContext(
            credential,
            string.Empty,
            ContextAttrib.InitIntegrity |
            ContextAttrib.ReplayDetect |
            ContextAttrib.SequenceDetect |
            ContextAttrib.Confidentiality);
    }

    /// <summary>
    /// Resets the state of the SASL mechanism.
    /// </summary>
    /// <remarks>
    /// Resets the state of the SASL mechanism.
    /// </remarks>
    public override void Reset()
    {
        state = LoginState.Initial;
        base.Reset();
    }
}
```

Here's an example protocol log:
```
S: 220 EXCHANGE.mydomain.com Microsoft ESMTP MAIL Service ready at Tue, 19 Jun 2018 09:07:18 +0200
C: EHLO [127.0.0.1]
S: 250-EXCHANGE.mydomain.com Hello [10.10.10.2]
S: 250-SIZE
S: 250-PIPELINING
S: 250-DSN
S: 250-ENHANCEDSTATUSCODES
S: 250-STARTTLS
S: 250-X-ANONYMOUSTLS
S: 250-AUTH NTLM
S: 250-X-EXPS GSSAPI NTLM
S: 250-8BITMIME
S: 250-XEXCH50
S: 250-XRDST
S: 250 XSHADOW
C: AUTH NTLM TlRMTVNTUAABAAAA<rest of base64 removed>
S: 334 TlRMTVNTUAACAAAAFAAUA<rest of base64 removed>
C: TlRMTVNTUAADAAAAGAAYAIAAAA<rest of base64 removed>
S: 235 2.7.0 Authentication successful
C: QUIT
S: 221 2.0.0 Service closing transmission channel
```

**Comment by sorenaa65** [comment]
Hi @UriHendler 
I have tried to implement your example but can't get it working.
Could you create an example of how to authenticate using your class?
I tried:
            `SaslMechanismNtlmIntegrated sasl = new SaslMechanismNtlmIntegrated();
            SmtpClient client = new SmtpClient();
            client.Connect("smtp.office365.com", 587, SecureSocketOptions.StartTls);
            client.Authenticate(sasl);`
but it does not work..

**Comment by UriHendler** [comment]
@sorenaa65 That's how you would do it, but AFAIK, Office 365 doesn't support NTLM integrated authentication. That only works for Exchange on-premises.

See here: https://serverfault.com/questions/949471/office365-ntlm-authentication

**Comment by sorenaa65** [comment]
Hi @UriHendler 
Thank you for your answer. That actually make sense in hindsight :-)

**Comment by chucklu** [comment]
interesting topic

**Comment by beaudry** [comment]
If anyone wants it, I've created a [NuGet package](https://www.nuget.org/packages/MailKit.Security.SaslMechanismNtlmIntegrated) with the code from @UriHendler.

**Comment by rhrocha** [comment]
For NET Core platforms, the NSspi library can be replaced by System.Net.Security.NegotiateAuthentication for NTLM negotiation, here is the source code for SaslMechanism implementation:

`public sealed class SaslMechanismNtlmIntegrated : SaslMechanism, IDisposable
{
    private bool IsNegotiating { get; set; } = false;
    private NegotiateAuthentication NegotiateAuthentication { get; set; }

    public SaslMechanismNtlmIntegrated()
        : base(userName: string.Empty, password: string.Empty)
    {
    }

    public override string MechanismName => "NTLM";
    public override bool SupportsInitialResponse => true;

    protected override byte[] Challenge(byte[] token, int startIndex, int length, CancellationToken cancellationToken)
    {
        cancellationToken.ThrowIfCancellationRequested();

        if (IsAuthenticated)
            throw new InvalidOperationException();

        NegotiateAuthentication ??= new NegotiateAuthentication(new NegotiateAuthenticationClientOptions() { Package = MechanismName });

        var response = NegotiateAuthentication.GetOutgoingBlob((IsNegotiating) ? Convert.ToBase64String(token) : string.Empty, out var statusCode);

        IsAuthenticated =
            (statusCode == NegotiateAuthenticationStatusCode.Completed) ? true :
            (statusCode == NegotiateAuthenticationStatusCode.ContinueNeeded) ? false :
            throw new UserMessageException(GetStatusCodeMessage(statusCode));

        IsNegotiating = true;

        return Convert.FromBase64String(response);
    }

    public override void Reset()
    {
        IsNegotiating = false;
        base.Reset();
    }

    public static string GetStatusCodeMessage(NegotiateAuthenticationStatusCode statusCode)
    {
        return statusCode switch
        {
            NegotiateAuthenticationStatusCode.Completed => @"NTLM authentication error: Operation completed successfully.",
            NegotiateAuthenticationStatusCode.ContinueNeeded => @"NTLM authentication error: Operation completed successfully but more tokens are to be exchanged with the other party.",
            NegotiateAuthenticationStatusCode.GenericFailure => @"NTLM authentication error: Operation resulted in failure but no specific error code was given.",
            NegotiateAuthenticationStatusCode.BadBinding => @"NTLM authentication error: Channel binding mismatch between client and server.",
            NegotiateAuthenticationStatusCode.Unsupported => @"NTLM authentication error: Unsupported authentication package was requested.",
            NegotiateAuthenticationStatusCode.MessageAltered => @"NTLM authentication error: Message was altered and failed an integrity check validation.",
            NegotiateAuthenticationStatusCode.ContextExpired => @"NTLM authentication error: Referenced authentication context has expired.",
            NegotiateAuthenticationStatusCode.CredentialsExpired => @"NTLM authentication error: Authentication credentials have expired.",
            NegotiateAuthenticationStatusCode.InvalidCredentials => @"NTLM authentication error: Consistency checks performed on the credential failed.",
            NegotiateAuthenticationStatusCode.InvalidToken => @"NTLM authentication error: Checks performed on the authentication token failed.",
            NegotiateAuthenticationStatusCode.UnknownCredentials => @"NTLM authentication error: The supplied credentials were not valid for context acceptance, or the credential handle did not reference any credentials.",
            NegotiateAuthenticationStatusCode.QopNotSupported => @"NTLM authentication error: Requested protection level is not supported.",
            NegotiateAuthenticationStatusCode.OutOfSequence => @"NTLM authentication error: Authentication token was identfied as duplicate, old, or out of expected sequence.",
            NegotiateAuthenticationStatusCode.SecurityQosFailed => @"NTLM authentication error: Validation of RequiredProtectionLevel against negotiated protection level failed.",
            NegotiateAuthenticationStatusCode.TargetUnknown => @"NTLM authentication error: Validation of the target name failed.",
            NegotiateAuthenticationStatusCode.ImpersonationValidationFailed => @"NTLM authentication error: Validation of the impersonation level failed.",
            _ => $@"NTLM authentication error: Failed with unknown status code {statusCode}.",
        };
    }

    private bool disposedValue;

    private void Dispose(bool disposing)
    {
        if (!disposedValue)
        {
            if (disposing)
            {
                try
                {
                    NegotiateAuthentication?.Dispose();
                }
                catch (Exception)
                {
                    // Nothing to do
                }
                finally
                {
                    NegotiateAuthentication = null;
                }
            }

            disposedValue = true;
        }
    }

    public void Dispose()
    {
        Dispose(disposing: true);
        GC.SuppressFinalize(this);
    }
}`

**Comment by jstedfast** [comment]
@rhrocha is this still necessary even with the current MailKit NTLM implementation?

Wondering if perhaps I should just replace MailKit's NTLM mechanism with something like this for NetCore

**Comment by rhrocha** [comment]
The current NTML implementation works fine when the user and password are provided.

But it would not work with CredentialCache.DefaultCredentials, since it cannot be used to view the user name, password, or domain of the current security context (https://learn.microsoft.com/en-us/dotnet/api/system.net.credentialcache.defaultcredentials).

This constructor would not work as expected:

    #if NET48_OR_GREATER || NET5_0_OR_GREATER || NETSTANDARD2_0_OR_GREATER
    public SaslMechanismNtlm () : this (CredentialCache.DefaultNetworkCredentials)
    {
    }
    #endif

Because the Credentials.Domain, Credentials.UserName and Credentials.Password will be empty here:

    protected override byte[] Challenge (byte[] token, int startIndex, int length, CancellationToken cancellationToken)
    {
        if (IsAuthenticated)
            return null;

        string userName = Credentials.UserName;
        string domain = Credentials.Domain;
        NtlmMessageBase message = null;

        [...]

        switch (state) {
            case LoginState.Negotiate:
                message = negotiate = new NtlmNegotiateMessage (domain, Workstation, OSVersion);
                state = LoginState.Challenge;
                break;
            case LoginState.Challenge:
                var password = Credentials.Password;
                message = GetChallengeResponse (domain, userName, password, token, startIndex, length);
                IsAuthenticated = true;
                break;
        }

The NegotiateAuthentication for NTLM with DefaultNetworkCredentials works only in Windows platform, since it uses a wrapper for SSPI (I confirmed it in the dotnet runtime source code). The managed implementation of NTLM protocol in NegotiateAuthentication  (which is used in other platforms) does not support using DefaultNetworkCredentials.

Maybe the new NegotiateAuthentication class, introduced in NET 7, could be used as an additional authentication mechanism for NTLM authentication using DefaultNetworkCredentials, available only for net7.0-windows target framework.

**Comment by jstedfast** [comment]
@rhrocha Thanks for this info!

**Comment by jstedfast** [comment]
I've just added a new SaslMechanismNtlmNative class to MailKit. I'm not sure that I want to quite get rid of the existing SaslMechanismNtlm class simply because it provides support for settings that don't have an equivalent in the NegotiateAuthentication APIs.

**Comment by jstedfast** [comment]
MailKit 4.12.0 has been released with this feature.
