### ISSUE TITLE
Can I target both Universal Windows 10 and Windows Phone 8.1 at the same time?

### ISSUE THREAD

**Issue by diogorolo** [jstedfast/MailKit#336]
I have 3 projects in my solution, one targeting UWP, another targeting Windows Phone 8.1 and a common one, where I program the common logic (which uses MailKit).

Is there a way to use configure MailKit project to support both the other projects at the same time?

**Comment by jstedfast** [comment]
Well, lucky for you, this is Open Source which means you can fiddle with the PCL profiles until it fits :)
