### ISSUE TITLE
Inbox Count 0 (zero)

### ISSUE THREAD

**Issue by PaijoRX** [jstedfast/MailKit#337]
i'am using this code to get inbox:
```csharp
pop3Client.Connect(configProperty.emailHost, configProperty.emailIncomingPort, SecureSocketOptions.Auto);
pop3Client.Authenticate(configProperty.emailUsername, configProperty.emailPassword);

if (pop3Client.IsConnected)
{
    for (int i = 0; i < pop3Client.Count; i++){
       ....
    }
}
```

but, sometime i got return 0 from pop3Client.Count.
there is any wrong of my code.

Thank you....

**Comment by jstedfast** [comment]
Maybe you just don't have any messages...

You could try getting a protocol log (see the [FAQ](https://github.com/jstedfast/MailKit/blob/master/FAQ.md#ProtocolLog) for details) to check the server responses.

I suspect that the server is telling MailKit that you have 0 messages.

**Comment by PaijoRX** [comment]
from email client (thunderbird), i got 17 new email.
but from pop3Client always got 0.

**Comment by jstedfast** [comment]
I need to see a log or I can't possibly solve the problem.

**Comment by PaijoRX** [comment]
this is our log :
````
Connected to pop://x.x.x.x:110/?starttls=when-available
S: +OK IBM Notes POP3 server version Release 9.0.1FP5 ready on xxxxxx/xxxxxxx.
C: CAPA
S: +OK
S: USER
S: UIDL
S: TOP
S: .
C: USER servicedeskit@xxxxxx.xx.xx
S: +OK servicedeskit@xxxxxx.xx.xx, your papers please.
C: PASS notes
S: +OK servicedeskit@xxxxxx.xx.xx has 0 messages.
C: CAPA
S: +OK
S: USER
S: TOP
S: UIDL
S: IMPLEMENTATION Lotus_Notes_POP3_Server_2.0
S: .
C: STAT
S: +OK 0 0
C: QUIT
S: +OK IBM Notes POP3 server signing off.
````

**Comment by PaijoRX** [comment]
if a new email coming to my inbox. the pop3Client.Count() will get all email count.
let say 17(from old email on inbox) + 1 (new email) = 18.

**Comment by jstedfast** [comment]
This is a bug in your POP3 server, then.

From the logs:

```
C: STAT
S: +OK 0 0
```

MailKit asks for the number of messages and the server replies with `You've got 0 messages!`

How could MailKit possibly know that the server is lying to it?

Here's the relevant snippet of the log where MailKit finds 21 messages:

```
C: STAT
S: +OK 21 21504
```

The response to the `STAT` command has 2 pieces:

1. The total number of messages
2. The total number of bytes of all messages combined

In the first log, you can see that your server tells MailKit that there are 0 messages that take up 0 bytes.

In the second log, you can see that the server tells MailKit that there are 21 messages that take up a combined 21504 bytes.

But if you aren't convinced by that, it looks like your POP3 server provides some free-form text in the response to the `PASS` command:

```
C: PASS XXX
S: +OK servicexxx@xxxxxx.xx.xx has 0 messages.
```

There's nothing wrong or broken with MailKit.
