### ISSUE TITLE
Move message to folder but also update it subject

### ISSUE THREAD

**Issue by truane** [jstedfast/MailKit#338]
I know i can open a folder
<code> folder.Open(FolderAccess.ReadWrite); </code> 
can read a message 
<code> MimeMessage message = folder.GetMessage(messageID); </code> 
and i can move that meassage to another folder
<code> folder.MoveTo(messageID, _client.GetFolder("newFolder")); </code> 

Is there any way I can change the email subject line before I move it to the new folder?
like - folder.SetMessage(messageID,message)

**Comment by jstedfast** [comment]
The only way to do that is something like this:

```csharp
folder.Open (FolderAccess.ReadWrite);
var message = folder.GetMessage (uniqueId);
message.Subject = "Changed subject";
var newFolder = client.GetFolder ("newFolder");
newFolder.Append (message);
```

**Comment by truane** [comment]
Thank you

Can you also confirm the messagID is always the same for the same message.
i.e if a close the connection and open it a hour later and try to get same message with the id I used before it would return the same message? As long as it hasn't been deleted or moved.

**Comment by jstedfast** [comment]
Yes and no.

The UID (note: it's not a message-id, a message-id is completely different and not guaranteed to be unique) will be the same between connections IF AND ONLY IF the `folder.UidValidity` value is the same between connections (it almost always is, but if the server crashes and the disk gets corrupt and the admin has to restore from a backup or something, the UidValidity will probably change).

**Comment by truane** [comment]
One last question 
```
var newMessageID = newFolder.Append(message, MessageFlags.Seen);
if (onError && newMessageID != null) 
newFolder.AddFlags((UniqueId)newMessageID, MessageFlags.Flagged, true);

```

On some systems the newMessageID is comming back as null can i set MessageFlags.Seen and MessageFlags.Flagged on the append at same time?

**Comment by jstedfast** [comment]
Yes.

```csharp
newFolder.Append(message, MessageFlags.Seen | MessageFlags.Flagged);
```

**Comment by truane** [comment]
Thanks again I will test it now.
