### ISSUE TITLE
error on handshake with smtp.live.com

### ISSUE THREAD

**Issue by SHAliakbari** [jstedfast/MailKit#339]
Hi , 
there is problem on connect to smtp.live.com on dnxcore5 .

my code is : 

```
using (var client = new SmtpClient())
                {
                    client.Connect("smtp.live.com", 587, true);

                    client.AuthenticationMechanisms.Remove("XOAUTH2");

                    // Note: only needed if the SMTP server requires authentication
                    client.Authenticate("xxxx", "xxxx");

                    await client.SendAsync(message);
                    client.Disconnect(true);
                }
```

the error is :

> The handshake failed due to an unexpected packet format.

**Comment by SHAliakbari** [comment]
I found solution 
connect method should be : 

`client.Connect("smtp-mail.outlook.com", 587,  MailKit.Security.SecureSocketOptions.StartTls);`

**Comment by jstedfast** [comment]
Glad you figured it out. Let me know if you have any other questions.
