### ISSUE TITLE
Medium trust level

### ISSUE THREAD

**Issue by denes** [jstedfast/MailKit#340]
Do you have MailKit in Medium trust level hosting?

**Comment by jstedfast** [comment]
I'm not sure what you mean. It's hosted on GitHub. I guess if that's Medium trust level, then yes?

**Comment by denes** [comment]
When I'm running my code on the sharing host Server: 

Inheritance security rules violated while overriding member: MailKit.Net.Imap.ImapCommandException.GetObjectData(System.Runtime.Serialization.SerializationInfo, System.Runtime.Serialization.StreamingContext) . Security accessibility of the overriding method must match the security accessibility of the method being overriden.

My server hosting is configured in Medium trust level.

**Comment by jstedfast** [comment]
Try adding `[System.Security.SecurityCritical]` to the `GetObjectData()` method on `ImapCommandException` and see if that fixes it.

**Comment by denes** [comment]
Same problem in medium trust level. Is not working in version 1.2.23:

For your tests: put this in web config: <trust level="Medium"/>

**Comment by jstedfast** [comment]
Do you think you could dig into the problem and send me a patch to fix it? I have no knowledge of ASP.NET website development.

Thanks.

**Comment by jstedfast** [comment]
You can apparently fix this issue by adding the following to your web.config:

```
<system.web>
    <trust level="Full" />
<system.web>
```

**Comment by gyself** [comment]
Will not work if your hosting doesn't support full trust.
