### ISSUE TITLE
Port 0 fails to connect to IMAP

### ISSUE THREAD

**Issue by jujukid** [jstedfast/MailKit#343]
When I set port to 0 it fails to connect to IMAP.

client.Connect("imap.gmail.com", 0);

{"A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 209.85.145.108:143"}

**Comment by jstedfast** [comment]
That's because imap.gmail.com does not run a service on port 143.

You need to connect via SSL, but you are trying to connect w/o SSL.

The behavior you are seeing is the expected behavior.

**Comment by jujukid** [comment]
I selected port 0 not 143

**Comment by jstedfast** [comment]
port 0 means the default port for the type of connection you are making, which in your case is port 143 (you didn't ask to connect via SSL).
