### ISSUE TITLE
ImapClient.Connect() fails with "Could not resolve host" exception in Release build on Xamarin

### ISSUE THREAD

**Issue by TigN** [jstedfast/MailKit#344]
**[Environment]**
Visual Studio Community 2015 Update 2
Xamarin Android Player emulating Nexus 5 KitKat or real physical device: Samsung Galaxy S6.

**[Steps to reproduce]**
1. Create a trivial Xamarin for Android app. In Visual Studio use _Blank App (Xamarin.Forms.Portable)_ template.
2. Call the following code anywhere in the app:
```
using (var client = new ImapClient())
{
    try
    {
        client.Connect("imap.gmail.com", 993, SecureSocketOptions.SslOnConnect);
        Toast.MakeText(this, "Connect() is successfull", ToastLength.Short).Show();
    }
    catch (Exception e)
    {
        Console.WriteLine(e.Message);
        Toast.MakeText(this, "Connect() failed: "+e.Message, ToastLength.Short).Show();
    }
    client.Disconnect(true);
}
```
3. Build the Release configuration and deploy to emulator or real Android device.
4. Watch behavior when the code executes in Debug and Release builds.
5. `ImapClient.Connect()` throws exception in Release build.

**[Expected Behavior]**
`ImapClient.Connect()` returns successfully in both Debug and Release build.

**[Actual Behavior]**
`ImapClient.Connect()` fails with "Could not resolve host" exception in Release build. Everything works as expected in Debug build.

**[Possible Culprit]**
The culprit seems to be `Dns.GetHostAddresses()` call in `ImapClient.Connect()` implementation.

**[Attachment]**
Minimal Visual Studio project and source code for reproduction attached.
[MailkitBug.zip](https://github.com/jstedfast/MailKit/files/278936/MailkitBug.zip)

**Comment by jstedfast** [comment]
If Dns.GetHostAddresses() is failing, then what do you expect me to do about it?

**Comment by jstedfast** [comment]
Well, unfortunate,y I can't even test this because I can't get HAXM to work so the emulators refuse to start up.

I recommend submitting a bug to https://bugzilla.xamarin.com about the Dns.GetHostAddresses() bug because that's obviously not something I can fix from within MailKit.

**Comment by TigN** [comment]
I understand. I will submit to Xamarin. Thanks a lot for looking.
