### ISSUE TITLE
imap.mail.ru : Syntax error in response. Unexpected token: [atom: A00000001]

### ISSUE THREAD

**Issue by zhoqa** [jstedfast/MailKit#345]
Hi jstedfast,

My code had been working without any change for many months. Recently I ran it again and realized that Authenticate() method now throws an exception. The sample code is below. Login/password are dummy, but in my code I verified all connection parameters, they are correct. Probably mail.ru changed its response. Any idea how to repair it?

```
static void Main(string[] args)
{
    try
    {
        ImapClient imap = new ImapClient();
        imap.Connect("imap.mail.ru", 993, true);
        imap.Authenticate("someaddress@mail.ru", "<somepwd>");
    }
    catch (Exception e)
    {
        // Syntax error in response. Unexpected token: [atom: A00000001]
        Console.WriteLine(e.Message);
    }
}
```

Thanks in advance,
zhoqa

**Comment by jstedfast** [comment]
You'll need to get a protocol log to figure it out.

```csharp
 ImapClient imap = new ImapClient(new ProtocolLogger("imap.log"));
```

**Comment by zhoqa** [comment]
```
Connected to imaps://imap.mail.ru:993/
S: * OK Welcome
C: A00000000 CAPABILITY
S: * CAPABILITY IMAP4rev1 ID XLIST UIDPLUS UNSELECT MOVE LIST-STATUS AUTH=PLAIN AUTH=XOAUTH2
S: A00000000 OK CAPABILITY completed
C: A00000001 AUTHENTICATE XOAUTH2
S: + 
C: dXNlcj00MDAwOTAwMDRAbWFpbC5ydQFhdXRoPUJlYXJlciA4TDJtajNlXgEB
S: A00000001 NO [AUTHENTICATIONFAILED] Authentication failed
C: A00000002 AUTHENTICATE PLAIN
S: A00000001 NO [AUTHENTICATIONFAILED] Authentication failed

```

**Comment by jstedfast** [comment]
Do you see the problem?

```
C: A00000002 AUTHENTICATE PLAIN
S: A00000001 NO [AUTHENTICATIONFAILED] Authentication failed
```

Your server is replying to the command that is tagged `A00000002` with `A00000001` which is completely broken.

Report this to mail.ru.

**Comment by zhoqa** [comment]
Thanks a lot  for your help!!

**Comment by bambhey** [comment]
Hi jstedfast

Please help me interpret this error? and what seems to be the problem? We had the same response error but the log is different. By the way, I am authenticating a shared mailbox

Example of my IMAP:
EMAIL ADDRESS:  shared@anotherdomain.com (shared mailbox)
 IMAP SERVER: outlook.office365.com
 SMTP SERVER: smtp.office365.com
USERNAME:  user@maindomain.com\shared-mailbox  (user\shared mailbox alias)
PASSWORD: password (user's password)


Connected to imaps://outlook.office365.com:993/
S: * OK The Microsoft Exchange IMAP4 service is ready. [SABLADIAUABSADAAMgBDAEEAMAAxADgAOQAuAGEAcABjAHAAcgBkADAAMgAuAHAAcgBvAGQALgBvAHUAdABsAG8AbwBrAC4AYwBvAG0A]
C: A00000000 CAPABILITY
S: * CAPABILITY IMAP4 IMAP4rev1 AUTH=PLAIN AUTH=XOAUTH2 SASL-IR UIDPLUS MOVE ID UNSELECT CHILDREN IDLE NAMESPACE LITERAL+
S: A00000000 OK CAPABILITY completed.
C: A00000001 AUTHENTICATE XOAUTH2 dXNlcj1zdmMtYW50aGVzaXNlbWFpbEBWYXJleEltYWdpbmcub25taWNyb3NvZnQuY29tXFVTLU1CWC1Qcm9kdWN0RW52Q29tcGxpYW5jZQFhdXRoPUJlYXJlciBqKEAyRT0xODYlPSQoMlg1AQE=
S: A00000001 NO Server Unavailable. 15
C: A00000002 AUTHENTICATE PLAIN AHN2Yy1hbnRoZXNpc2VtYWlsQFZhcmV4SW1hZ2luZy5vbm1pY3Jvc29mdC5jb21cVVMtTUJYLVByb2R1Y3RFbnZDb21wbGlhbmNlAGooQDJFPTE4NiU9JCgyWDU=
S: A00000001 NO AUTHENTICATE failed.

**Comment by jstedfast** [comment]
You need to call:

```csharp
client.AuthenticationMechanisms.Remove ("XOAUTH2");
```

because you don't have an XOAUTH2 token.
