### ISSUE TITLE
Unable to access pulbic folder

### ISSUE THREAD

**Issue by truane** [jstedfast/MailKit#346]
Hi im trying to append email to a public folder but i'm unable to find it using mailkit

client.GetFolder (client.PersonalNamespaces[0]).GetSubfolders ())

 but this only returns 11 folders

{Calander}
{Contacts}
{Deleted Items}
{Drafts}
{INBOX}
{Journal}
{Junk Email}
{Notes}
{Outbox}
{Sent Items}
{Tasks}

Is there a special way of referencing them?

**Comment by jstedfast** [comment]
Exchange does not support public folders via IMAP, unfortunately. You'll need to use another library :(
