### ISSUE TITLE
Interfaces for main classes to facilitate unit testing

### ISSUE THREAD

**Issue by marspd** [jstedfast/MailKit#347]
Hi Jeffrey
Thank you for your excellent work and this is a request rather than an issue.

I have been using your code for a while now and it is brilliant. However, I'm just starting a new project and I want to use TDD and with this in mind I want to unit test my classes that use the classes from Mailkit. 

In particular I want to test a class of my own that depends on ImapClient. Unfortunately there is no interface for this class and therefore I can't Mock it out to test my class specifically.

I did see that ImapClient does inherit from IMailStore but IMailStore does not define all the properties/methods on ImapClient that I am using.

Is there a possibility that you can at some point generate interfaces for your main classes to make unit testing easier further down the line?

Thank you for your time
Paul

**Comment by jstedfast** [comment]
What methods in particular are you using that aren't already covered in IMailStore and/or IMailService?

**Comment by marspd** [comment]
If I set my dependency on IMailStore I don't get the following methods

```
                // Connect up to the IMAP server
                _client.Connect(hostname, port, ssl);
                _client.Authenticate(username, password);

                // Get full access to the inbox
                _client.Inbox.Open(FolderAccess.ReadWrite);
```

Although there are other similar methods for Connect and Authorize. Perhaps you can tell me if there is a way around these methods using the existing methods in IMailService? I can't see a similar method for the missing Inbox.

Paul

**Comment by jstedfast** [comment]
I would recommend against using `_client.Connect(hostname, port, ssl);` as I'm trying to deprecate that API (people get confused about what 'true' and 'false' mean - i.e. "does it include STARTTLS?").

Instead, I recommend using `Connect (string, int, SecureSocketOptions)`

**Comment by jstedfast** [comment]
The `IMailStore` interface already defines an `Inbox` property.

I've added the Connect and Authenticate methods that you are using to the `IMailService` interface.

**Comment by jstedfast** [comment]
Can you explain why the interfaces are needed? I don't get it...

**Comment by marspd** [comment]
Hi Jeffrey
Sorry for the confusion. 

As you mentioned the IMailStore interface does have all the methods I need if I replace the connect and authenticate as follows:

`                // Connect up to the IMAP server
                //_client.Connect(hostname, port, ssl);
                //_client.Authenticate(username, password);
                await  _client.ConnectAsync(hostname, port, MailKit.Security.SecureSocketOptions.SslOnConnect);
                await _client.AuthenticateAsync(new NetworkCredential(username, password));
`

**Comment by marspd** [comment]
Just to let you know I have made a small donation for your excellent work.

**Comment by jstedfast** [comment]
Thanks! FWIW, you don't need to use the async versions, there's also non-async versions.

**Comment by grokky1** [comment]
Sorry to revive an old issue, but I'm having similar trouble - various `SmtpClient` methods are not virtual, so I can't mock them.

These methods are used in a simple send, but they are not virtual:

- `public void Connect(string host, int port, bool useSsl, CancellationToken cancellationToken = default(CancellationToken));`
- `public void Authenticate(string userName, string password, CancellationToken cancellationToken = default(CancellationToken));`

There are others too, but not an issue for me now because I'm not mocking them.

**Comment by jstedfast** [comment]
Those methods call the virtual methods. Override the virtual methods.

**Comment by prashanth-nani** [comment]
For those who are coming here in 2020, now `Mailkit` has interfaces for `ISmtpClient`, `IImapClient`, `IPop3Client`, `IProxyClient`. Introduced in version `2.5.0`.
