### ISSUE TITLE
Imap Idle Events are not firing using Windows service

### ISSUE THREAD

**Issue by prathhi** [jstedfast/MailKit#350]
I make use of Imap idle events like CountChanged and Messages Arrived. Both are working fine  in C# Console Application  but it does not by C# Windows Service.

Can you tell me the way forward approach ASAP as its holding my current project

**Comment by jstedfast** [comment]
Does it make sense to you that it works with a console app but not in a Windows Service app? You must not be doing something right, but I can't tell you what based on what you've told me.

**Comment by prathhi** [comment]
Below is the code snippet which was working properly in console ap but not in windows service. As I said beforeMessage arrive arrived isnot firing as and when the Email arrives to the Inbox.

            using (ImapClient Client = new ImapClient())
            {
                Client.Connect(host, port, MailKit.Security.SecureSocketOptions.StartTls);
                // Note: since we don't have an OAuth2 token, disable
                // the XOAUTH2 authentication mechanism.
                Client.AuthenticationMechanisms.Remove("XOAUTH2");

                Client.Authenticate(username, password);

                // The Inbox folder is always available on all IMAP servers...
                var inbox = Client.Inbox;
                
                inbox.Open(FolderAccess.ReadWrite);
                IEnumerable<UniqueId> MessageList = inbox.Search(SearchQuery.All);

                // keep track of the messages 
 				IList<IMessageSummary> messages = null;  				
                int count = 0;


                if (Client.Inbox.Count > 0)
                {
                    messages = Client.Inbox.Fetch(0, -1, MessageSummaryItems.Full | MessageSummaryItems.UniqueId).ToList(); 
 					count = messages.Count; 
 				}


                Client.Inbox.MessagesArrived += (sender, e) =>
                {
                    var folder = (ImapFolder)sender;
                    if (folder.Count > count)
                    {
                        var Mailclient = new ImapClient();
                        Mailclient.Connect(host, port, MailKit.Security.SecureSocketOptions.Auto);
                        //Mailclient.Connect("imap.thewestpacgroup.com.au", 143, MailKit.Security.SecureSocketOptions.StartTls);
                        Mailclient.AuthenticationMechanisms.Remove("XOAUTH2");
                        Mailclient.Authenticate(username, password);
                        Mailclient.Inbox.Open(FolderAccess.ReadOnly);
                        var summaries = Mailclient.Inbox.Fetch(count, folder.Count - 1, MessageSummaryItems.Envelope | MessageSummaryItems.Body | MessageSummaryItems.All);
                        for (var i = count; i < folder.Count; i++)
                        {
                            MimeMessage msg = Mailclient.Inbox.GetMessage(count);
                            Console.WriteLine(msg.GetTextBody(MimeKit.Text.TextFormat.Text));

                                               
                        }
                        // New messages have arrived in the folder. 
                        Console.WriteLine("{0}: {1} new messages have arrived.", folder, folder.Count - count);
                        
                        // Note: your first instict may be to fetch these new messages now, but you cannot do 
                        // that in an event handler (the ImapFolder is not re-entrant).                         
                    }
                };

**Comment by jstedfast** [comment]
In your callback, you are inconsistent between using `folder` and `Mailclient.Inbox`.

You need to always use `Mailclient.Inbox` in the callback.

**Comment by prathhi** [comment]
But Client.Inbox.MessagesArrived event is tagged to main client. If I remove the whole code under MessagesArrived event also, event was not firing in windows service. Is there any work aorund for this?

**Comment by jstedfast** [comment]
You aren't making any sense.

Look here:

```csharp
for (var i = count; i < folder.Count; i++)
{
    MimeMessage msg = Mailclient.Inbox.GetMessage(count);
```

Why are you iterating over folder.Count when you are getting messages from Mailclient.Inbox?

That's what I'm talking about.

**Comment by jstedfast** [comment]
Also, as soon as you close the using block for `Client`, you will get no more events because the `Client` will be disposed.

**Comment by prathhi** [comment]
When I try to make use of below code in windows service MessagesArrived event is not firing as and when Email arrives to inbox

using (ImapClient Client = new ImapClient())
        {
            Client.Connect(host, port, MailKit.Security.SecureSocketOptions.StartTls);
            // Note: since we don't have an OAuth2 token, disable
            // the XOAUTH2 authentication mechanism.
            Client.AuthenticationMechanisms.Remove("XOAUTH2");

            Client.Authenticate(username, password);

            // The Inbox folder is always available on all IMAP servers...
            var inbox = Client.Inbox;

            inbox.Open(FolderAccess.ReadWrite);
            IEnumerable<UniqueId> MessageList = inbox.Search(SearchQuery.All);

            // keep track of the messages 
            IList<IMessageSummary> messages = null;                 
            int count = 0;


            if (Client.Inbox.Count > 0)
            {
                messages = Client.Inbox.Fetch(0, -1, MessageSummaryItems.Full | MessageSummaryItems.UniqueId).ToList(); 
                count = messages.Count; 
            }


            Client.Inbox.MessagesArrived += (sender, e) =>
            {
Logger.Log(LogOption.INFO, "Process started  under Message Arrived Event"); 

//do Something
Logger.Log(LogOption.INFO, "Process Completed under Message Arrived Event"); 
};

**Comment by jstedfast** [comment]
Use the CountChanged event instead.

**Comment by prathhi** [comment]
I have tried this Event but its not working. Do you  know any alternative way for this?

**Comment by jstedfast** [comment]
If the CountChanged event is not working, then it means that the IMAP server is not sending a status notification about the message count changing in the folder (which is the only way the IMAP server signifies that any new mail may have arrived).

It may be an IMAP server bug or it may be that the mail hasn't arrived yet, or it has been delivered to another folder, etc.

Also it should probably be noted that not all IMAP servers that support IDLE will emit events for everything that is supported in IDLE. For example, GMail does not emit events for some flag changes (I think), even though IDLE supports that.

This would be the first time I've heard of a server not notifying the client of an EXISTS change, but who knows, I suppose it could happen.

**Comment by prathhi** [comment]
Few facts about our applicaiton
1. Using console application both events (MessageArrived and CountChanged) are getting triggered when a new email arrives to Inbox folder.
2. Using Windows service,its behaving differellty as I said before when the Email arrives to Inbox.

So I think there is slight difference between windows service and console application IMAP Event Handling.

can you tell me the sequence how exactly the IMAP Server attaches the client and triggers the event Can we have any logging for IMAP Idle  event acess?

**Comment by jstedfast** [comment]
You can log the protocol using:

```csharp
var client = new ImapClient (new ProtocolLogger ("imap.log"));
```
