### ISSUE TITLE
Importing cloned project to existing WP 8.1

### ISSUE THREAD

**Issue by szkodnik25** [jstedfast/MailKit#354]
Hello,

I am having troubles with importing cloned project into my existing WP 8.1 solution.
I did:
`git clone https://github.com/jstedfast/MailKit.git`
`cd MailKit`
`git submodule update --init --recursive`

After that, I tried to import add existing project to my solution (I guess MailKit.WindowsPhone81.csproj), but I'm getting errors similar to "The type or namespace name 'MimeKit' could not be found (are you missing a using directive or an assembly reference?)". What should I inculde, import or add?

**Comment by jstedfast** [comment]
I think you actually want WindowsUniversal81

**Comment by szkodnik25** [comment]
Doesn't matter, after importing MailKit.WindowsUniversal81 I'm getting same errors:

`The type or namespace name 'MimeKit' could not be found (are you missing a using directive or an assembly reference?)`
`The type or namespace name 'ContentType' could not be found (are you missing a using directive or an assembly reference?)	`
`The type or namespace name 'Parameter' could not be found (are you missing a using directive or an assembly reference?)	`

and so on

**Comment by jstedfast** [comment]
Oh! wait, no... I'm wrong. You need to add the following projects:

Portable.Text.Encoding.WindowsUniversal81.csproj
MimeKit.WindowsUniversal81.csproj

and then finally

MailKit.WindowsPhone81.csproj
