### ISSUE TITLE
Suspicious MailboxAddress parsing

### ISSUE THREAD

**Issue by GSPP** [jstedfast/MailKit#355]
Here are some test cases where I'm not sure there should be any parse failures:

    MailboxAddress.Parse("DHL Worldwide Delivery < DHL-International@mail.com >")
    MailboxAddress.Parse("DHL Worldwide Delivery < DHL-International@mail.com >".ToLower())

Shouldn't these work? I have received mails that have such a `From` header.

<hr>

    MailboxAddress.Parse("DHL Worldwide Delivery <DHL-International@mail.com >".ToLower())

This succeeds which is surprising because if the space after "<" was not OK the space before ">" should also not be OK. Is this a bug?

My preference would be to have all of these cases succeed so that my automated receiving system can deal with as many mail styles as possible.

**Comment by jstedfast** [comment]
Yes, this was a bug. I've fixed this in [MimeKit](https://github.com/jstedfast/MimeKit).

Thanks for reporting this!

**Comment by jstedfast** [comment]
I have published a new version of MimeKit that fixes this issue to nuget.
