### ISSUE TITLE
UniqueId.Equals probably should include the Validity field

### ISSUE THREAD

**Issue by GSPP** [jstedfast/MailKit#356]
`UniqueId.Equals` only compares the `Id` field. This means that IDs from different folders or servers might compare equal. Also, it's not possible to detect a `UniqueId` change by calling `Equals`.

I propose that the equality algorithm be changed to include the validity datum.

I also propose that all equals and comparison methods throw an exception if `!IsValid`. This should be helpful to catch bugs with uninitialized variables of type `UniqueId`.

See https://github.com/jstedfast/MailKit/blob/master/MailKit/UniqueId.cs#L158

**Comment by jstedfast** [comment]
I'm not sure I agree because why would you ever compare uids from multiple folders?

Also if you compare Validity in `.Equals (UniqueId other)`, then you'd expect it to work the same as `==` which would then make other comparison operators not make any sense (how does Validity play into `>` or `<`?).

**Comment by GSPP** [comment]
How are we supposed to detect a UID change when comparing data just queried from IMAP with data previously stored in a database? Both fields must be compared. I'm glad I realized that. Otherwise I would have had a silent bug that takes a long time to manifest itself and then has grave consequences.

`>` should throw if used with differing Validities. Such a comparison does not make sense and is a bug in the caller.

All methods should take Validity into account and throw in case of API misuse. I don't see any API consistency issue with that.

**Comment by jstedfast** [comment]
You wouldn't want to store it on a per-UID basis, you'd want to store and compare the UidValidity of the folder separately.

**Comment by jstedfast** [comment]
> `>` should throw if used with differing Validities. Such a comparison does not make sense and is a bug in the caller.

The problem with comparing more values is that it will negatively impact performance by forcing another comparison into the inner-loop instead of doing it in the outer loop.
