### ISSUE TITLE
Unexpected greeting from server

### ISSUE THREAD

**Issue by Nekeniehl** [jstedfast/MailKit#357]
I really don't know if this is a bug or my bad but I've switched from my own email server (where this was working before) to gmail, and now I'm getting an "Unexpected greeting from server: * OK Gimap ready for requests from 62.220.2.230" exception.

This is how the log looks like:
```
Connected to pops://pop.gmail.com:993/
S: * OK Gimap ready for requests from 62.220.2.230
```
And this is the code I have to connect
```
Client = new Pop3Client(new ProtocolLogger("Log\\pop.log"));
Client.Connect("pop.gmail.de", 995, true);
Client.ServerCertificateValidationCallback = ValidateRemoteCertificate;
```

Thanks in advance.

EDIT I got it connected, port problem.

**Comment by jstedfast** [comment]
Yea, you are trying to connect to an IMAP server with the Pop3Client :)
