### ISSUE TITLE
imap.fetch() always returns "The IMAP server replied to the 'FETCH' command with a 'NO' response: FETCH Server error while fetching messages" for one particular message in a mailbox on imap.mail.yahoo.com

### ISSUE THREAD

**Issue by mcoyle012** [jstedfast/MailKit#358]
This is my first week using MailKit.  I've got the latest released version installed.

I was looking at some sample code here https://components.xamarin.com/gettingstarted/mailkit for my initial console application.  I'm aiming this at a mailbox on imap.mail.yahoo.com.

I found that I could not use the (0, -1, ...) invocation of fetch because I always got an ImapCommandException (below).  So I began hunting that down.  I began a binary search to find the failing index.  Turns out it was 9972.

I found that:
* retrying after catching the exception didn't do any good--persistent failure, and
* if f I changed which MessageSummaryItems I was fetching, it would no longer throw the exception.

In binary #1 I get this exception every single time on any fetch that includes message 9972.  I can retry after catching the exception and it never succeeds.

HResult=-2146233088
  Message=The IMAP server replied to the 'FETCH' command with a 'NO' response: FETCH Server error while fetching messages
  Source=MailKit
  StackTrace:
       at MailKit.Net.Imap.ImapFolder.Fetch(Int32 min, Int32 max, MessageSummaryItems items, CancellationToken cancellationToken)
       at ConsoleApplication2.Program.Main(String[] args) in C:\Users\ExtSvc-IntDev\Documents\Visual Studio 2015\Projects\ConsoleApplication2\ConsoleApplication2\Program.cs:line 63
       at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
       at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
       at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
       at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Threading.ThreadHelper.ThreadStart()
  InnerException:

In binary #2, I never get the exception thrown on message 9972.

The only difference between binary #1 and binary #2 is this:

binary #1: always fails
foreach (var summary in inbox.Fetch(i, j, MessageSummaryItems.Full | MessageSummaryItems.UniqueId))

Total messages: 23983
Recent messages: 0
Fetching 9971..9971
("text" "plain" ("charset" "iso-8859-1") NIL NIL "quoted-printable" 5245 NIL NIL NIL NIL 152): {0}
Fetching 9972..9972
Exception thrown: 'MailKit.Net.Imap.ImapCommandException' in MailKit.dll
MailKit.Net.Imap.ImapCommandException: The IMAP server replied to the 'FETCH' command with a 'NO' response: FETCH Server error while fetching messages
   at MailKit.Net.Imap.ImapFolder.Fetch(Int32 min, Int32 max, MessageSummaryItems items, CancellationToken cancellationToken)
   at ConsoleApplication2.Program.Main(String[] args) in C:\Users\ExtSvc-IntDev\documents\visual studio 2015\Projects\ConsoleApplication2\ConsoleApplication2\Program.cs:line 67: ImapCommandException: {0}
Fetching 9972..9972
Exception thrown: 'MailKit.Net.Imap.ImapCommandException' in MailKit.dll
MailKit.Net.Imap.ImapCommandException: The IMAP server replied to the 'FETCH' command with a 'NO' response: FETCH Server error while fetching messages
   at MailKit.Net.Imap.ImapFolder.Fetch(Int32 min, Int32 max, MessageSummaryItems items, CancellationToken cancellationToken)
   at ConsoleApplication2.Program.Main(String[] args) in C:\Users\ExtSvc-IntDev\documents\visual studio 2015\Projects\ConsoleApplication2\ConsoleApplication2\Program.cs:line 67: ImapCommandException: {0}
Fetching 9972..9972
Exception thrown: 'MailKit.Net.Imap.ImapCommandException' in MailKit.dll
MailKit.Net.Imap.ImapCommandException: The IMAP server replied to the 'FETCH' command with a 'NO' response: FETCH Server error while fetching messages
   at MailKit.Net.Imap.ImapFolder.Fetch(Int32 min, Int32 max, MessageSummaryItems items, CancellationToken cancellationToken)
   at ConsoleApplication2.Program.Main(String[] args) in C:\Users\ExtSvc-IntDev\documents\visual studio 2015\Projects\ConsoleApplication2\ConsoleApplication2\Program.cs:line 67: ImapCommandException: {0}
Fetching 9972..9972
Exception thrown: 'MailKit.Net.Imap.ImapCommandException' in MailKit.dll
MailKit.Net.Imap.ImapCommandException: The IMAP server replied to the 'FETCH' command with a 'NO' response: FETCH Server error while fetching messages
   at MailKit.Net.Imap.ImapFolder.Fetch(Int32 min, Int32 max, MessageSummaryItems items, CancellationToken cancellationToken)
   at ConsoleApplication2.Program.Main(String[] args) in C:\Users\ExtSvc-IntDev\documents\visual studio 2015\Projects\ConsoleApplication2\ConsoleApplication2\Program.cs:line 67: ImapCommandException: {0}

binary #2, always succeeds
foreach (var summary in inbox.Fetch(i, j, MessageSummaryItems.Fast))

Total messages: 23983
Recent messages: 0
Fetching 9971..9971
Fetching 9972..9972
Fetching 9973..9973
Fetching 9974..9974
Fetching 9975..9975
Fetching 9976..9976
Fetching 9977..9977
Fetching 9978..9978

**Comment by jstedfast** [comment]
Can you get a protocol log (see the FAQ to learn how to get one)? That'll be more useful than stack traces.

Thanks.

**Comment by mcoyle012** [comment]
You bet.  Give me 10 mins or so ...thanks!

**Comment by mcoyle012** [comment]
Here's the log, unscrubbed.  Please keep the email addresses contained in the log confidential and off the web (light or dark ;-).  Thanks in advance!
Log generated by 
                foreach (var summary in inbox.Fetch(9970, 9980, MessageSummaryItems.Full | MessageSummaryItems.UniqueId))
                {
                    var text = summary.Body as BodyPartText;
                    if (text == null)
                    {
                        var multipart = summary.Body as BodyPartMultipart;
                        if (multipart != null)
                            text = multipart.BodyParts.OfType<BodyPartText>().FirstOrDefault();
                    }
                    if (text == null)
                        continue;
                    // this will download *just* the text part
                    var part = inbox.GetBodyPart(summary.UniqueId, text);
                    System.Diagnostics.Debug.WriteLine("{0}", text.ToString()
                        );

**Comment by mcoyle012** [comment]
And here it is with a single request using inbox.Fetch (9972, 9972 ...)

**Comment by jstedfast** [comment]
Hey, just an FYI, but when you reply via email, it doesn't go to me - it goes to the issuer tracker which posts stuff publicly.

I've scrubbed the logs, but keep that in mind in the future.

I should probably add a note about that to the FAQ.

Looking at the logs, I'm not sure what can be done about the "NO" response within MailKit itself. It appears to be a bug in the IMAP server.

That said, for this *particular* issue, you might be able to work around it by subscribing to the `MessageSummaryFetched` event which gets emitted whenever the full requested data for a message is fetched. So you could do something like this:

```csharp
void OnMessageSummaryFetched (object sender, MessageSummaryFetchedEventArgs e)
{
    var text = summary.Body as BodyPartText;
    if (text == null)
    {
        var multipart = summary.Body as BodyPartMultipart;
        if (multipart != null)
            text = multipart.BodyParts.OfType<BodyPartText>().FirstOrDefault();
    }
    if (text == null)
        continue;
    // this will download *just* the text part
    var part = inbox.GetBodyPart(summary.UniqueId, text);
    System.Diagnostics.Debug.WriteLine("{0}", text.ToString());
}
```

```csharp
try {
    inbox.MessageSummaryFetched += OnMessageSummaryFetched;
    inbox.Fetch (9970, 9980, MessageSummaryItems.Full | MessageSummaryItems.UniqueId);
} catch (ImapCommandException) {
} finally {
    inbox.MessageSummaryFetched -= OnMessageSummaryFetched;
}
```

Hope that helps.

**Comment by samysilva** [comment]
I discovered the problem.

The EXPUNGE method does not work correctly on YAHOO servers.
It does not reset the sequential message counter (ID).

To solve the problem, just always work using UID

<code>var query = SearchQuery.All;
foreach (UniqueId uid in inbox.Search(query))
{
	try
	{
		var message = inbox.GetMessage(uid);
		ProcessMailMessage(message);
		inbox.AddFlags(uid, MessageFlags.Deleted, false);
	}
	catch (ImapCommandException ex)
	{
		inbox.AddFlags(uid, MessageFlags.Deleted, false);
		Global.Logger.WriteEntry("StartWork failed in GetMessage(" + uid.Id + ") and was marked as deleted: " + ex.Message,
			EventLogEntryType.Error, 3002);
	}
	catch (Exception ex)
	{
		throw ex;
	}
}</code>


Additionally, I added a try-catch in the "GetMessage" method. Because; Something eventually occurs in the UIDs that jump large ranges, leaving the previous ranges inaccessible.

Example:

Assuming the "inbox.Search (query)" return: 9001,9002,9003,1234501,1234502,1234503

The first 3 UIDs always return errors, being necessary to delete, and only work with the other UIDs.

Example of how to simulate problems in Yahoo
You can verify that there is no "ID 1"

<code>
openssl s_client -connect imap.mail.yahoo.com:993 -crlf
? LOGIN AAAAAAAAAAAAAAAAAA@yahoo.com PASSWORD
? LIST "" "*"
? SELECT INBOX
? SEARCH ALL
? FETCH 1 BODY[TEXT]
</code>

Example of how to get around problems in Yahoo

<code>
openssl s_client -connect imap.mail.yahoo.com:993 -crlf
? LOGIN AAAAAAAAAAAAAAAAAA@yahoo.com PASSWORD
? LIST "" "*"
? SELECT INBOX
? UID SEARCH ALL
? UID FETCH 101178 BODY[TEXT]
? LOGOUT
</code>

**Comment by jstedfast** [comment]
> As can be imagined this a source of a lot mistakes because if you’re looping through a list of message sequence numbers ascendingly, deleting messages as you go, you’ll end up deleting the wrong messages.

Indeed! I always recommend using UIDs if at all possible, even when not using Yahoo! IMAP. It's really just the best way to do things for any IMAP server and reduces the likelyhood of problems with both the IMAP server and your own code (we all make mistakes and so UIDs are a great way to make sure that we are referring to the message we mean to refer to).
