### ISSUE TITLE
IMailfolder.Search(SearchQuery.HeaderContains("Message-ID", messageId)) Issue

### ISSUE THREAD

**Issue by yasiduy3k** [jstedfast/MailKit#359]
Hi,
We are using the following code snippet.
SearchQuery query = SearchQuery.HeaderContains("Message-ID", messageId);
IList<UniqueId> uids = inbox.Search(query); //IMailfolder

We have noticed that when the _"Message-ID"_  is containing special characters (!&!AAAAAAAAAAAYAAAAAAAAAKD8xN0CRe1OpCsx8tRCulPCgAAAEAAAACuu7yUxk5lGo97p7X8rSSIBAAAAAA==@domain.com), IMailfolder.Search() returns an empty list instead of the related message.

**Comment by jstedfast** [comment]
That's probably the server's fault (MailKit just sends the string to the server and the server does the actual search).

But if you want me to take a look and verify, I'll need a protocol log (see the FAQ on how to get this).

**Comment by yasiduy3k** [comment]
Hi jstedfast,
I have attached the protocolog.
![protocollog](https://cloud.githubusercontent.com/assets/19964633/16105729/0a405b7a-33ab-11e6-88e7-6b4edbc3f72e.png)

**Comment by jstedfast** [comment]
Well, the search command was sent correctly and the server replied that there were no matches.

You could try doing:

```csharp
SearchQuery query = SearchQuery.HeaderContains("Message-ID", "<" + messageId + ">");
```

If that doesn't work, then I don't know what to tell you.

**Comment by yasiduy3k** [comment]
Adding "< >" does not return the UID as well.
Thanks for the help.
