### ISSUE TITLE
No way to verify anonymous smtp connection

### ISSUE THREAD

**Issue by eriknuds** [jstedfast/MailKit#363]
MailKit seem to lack a way to detect if anonymous email sending via SMTP are allowed by the server. Some servers allow anonymous smtp connections, where you can send an email without authenticating as a user first. If a server will relay anonymously is usually restricted by the network you are on or even the from address. It also may relay only internally without authentication. The anonymous authentication method is not necessarily mentioned in the AuthenticationMechanisms property. I can see no way to detect that anonymous sending is permitted without actually sending an email. If I could send RCPT to my from address and see what response I got (OK/ERR) and then abort the sending then maybe that would solve the problem, but I can find no way to send low level messages in MailKit as the SendMessage() method used internally is not available through a public interface, it seems. Maybe I could use connect with a socket to do low level communications once properly connected by MailKit, but it seems kind of sketchy and I have found no info on this.
MailKit seem to lack a way to detect if anonymous email sending via SMTP are allowed by the server. Some servers allow anonymous smtp connections, where you can send an email without authenticating as a user first. If a server will relay anonymously is usually restricted by the network you are on or even the from address. It also may relay only internally without authentication. The anonymous authentication method is not necessarily mentioned in the AuthenticationMechanisms property. I can see no way to detect that anonymous sending is permitted without actually sending an email. If I could send RCPT to my from address and see what response I got (OK/ERR) and then abort the sending then maybe that would solve the problem, but I can find no way to send low level messages in MailKit as the SendMessage() method used internally is not available through a public interface, it seems. Maybe I could use connect with a socket to do low level communications once properly connected by MailKit, but it seems kind of sketchy and I have found no info on this.

**Comment by jstedfast** [comment]
If the server allows anonymous relays, then you don't need to authenticate first.

You can try sending a message, and, if that fails with (I think) an UnauthorizedException, you know you need to authenticate first.

**Comment by eriknuds** [comment]
Yeah, thanks for the suggestion, I might have to do it that way, although I'd prefer to just issue the RCPT TO <my_own_from_address> to see if sending was allowed at all. Will the internal SendMesssage() function or some other low level access to the SMTP stream be available in the future? Or would it be ok to give a stream to MailKit and then use that stream to issue SMTP protocol commands like RCPT TO and reading the response - or would that conflict with how MailKit is using the stream? Why else is there a stream constructor for the connection? I have found no examples using it...

**Comment by jstedfast** [comment]
The stream .ctor is to allow you to connect via a proxy.

Calling `client.Send()` will work the same as you sending a RCPT TO command. There's no good reason to want to send RCPT TO manually. If the RCPT TO command fails due to authorization being needed, MailKit will throw the proper exception which you can catch to know it's needed. It would be no different from you manually sending RCPT TO and then parsing the response and branching based on what you get back.

**Comment by eriknuds** [comment]
I want to verify the SMTP server/user/pass settings when a user enters the configuration settings in the application, not maybe two weeks later when the user actually wants to send an email for the first time - and at the time of configuration I don't actually want to send a dummy email, if I can avoid it. By just issuing the RCPT TO instead of really attempting to send an actual email, I can give the user feedback immediately without unwanted external effects. Authenticate() will fail even if the server doesn't require authentication. Not sure if that reason is good enough for you, but it's good enough for me;-)

**Comment by eriknuds** [comment]
A public bool client.CanSendTo(string addr) would be nice, but if that's out of the question I'm looking for alternatives...

**Comment by jstedfast** [comment]
I'll think about this, but CanSendTo() will need a from address as well.

**Comment by eriknuds** [comment]
Yes:-)
