### ISSUE TITLE
List AppleMail Attachments as Attachments

### ISSUE THREAD

**Issue by JulianSchneider** [jstedfast/MailKit#364]
Since Apple Mail embeds their attachment pictures in E-Mails it is not possible to grab them with

`message.Attachments.OfType<MimePart>()`

is there any way to make this happen?

**Comment by jstedfast** [comment]
I don't know what you mean by "embedding". I assume you mean that they are just MIME parts like any other attachment except that perhaps they do not have a `Content-Disposition: attachment` header.

If that's the case, just use `message.BodyParts.OfType<MimePart> ()` and filter out any MIME parts that you don't want.

For example, maybe this will work for your needs:

```csharp
message.BodyParts.OfType<MimePart> ().Where (x => !string.IsNullOrEmpty (x.ContentType.Name));
```

The Attachments property does something very similar, except that it checks the `ContentDisposition` property.
