### ISSUE TITLE
Unable to use with .NET Core 1.0

### ISSUE THREAD

**Issue by Xlomi** [jstedfast/MailKit#372]
It was my understanding that version 1.4.0 should be working with .NET Core 1.0 but I keep getting the error below for both MailKit & MimeKit.
any help/instructions would be appreciated - I'm new to github so I apologize in advance if I'm not using it correctly for reporting this.
Xlomi

**Comment by Xlomi** [comment]
the error:  Unable to resolve 'MailKit (>= 1.4.0)' for '.NETCoreApp,Version=v1.0'

**Comment by jstedfast** [comment]
Somehow your project.json is broken.

.NETCoreApp imports .NETStandard1.6 which is a superset of .NETStandard1.4 which is what MimeKit and MailKit target, so .NETCoreApps can certainly use MimeKit and MailKit.

A quick google of the error you got (minus the MailKit bit) leads to: https://github.com/dotnet/cli/issues/2543

You might find that helpful.

**Comment by Xlomi** [comment]
just managed to resolve it - what wonders a good night sleep does :-)
Had to install each item separately via nuget:
"Portable.BouncyCastle": "1.8.1.1",
"System.Net.NetworkInformation": "4.1.0",
"MailKit": "1.4.0",
"MimeKit": "1.4.0"
     
Not sure why but it worked. 
Thanks for the quick response and all the good work.

**Comment by jstedfast** [comment]
Very odd... but glad you got it working :)
