### ISSUE TITLE
Which is the better Secure Socket Option?

### ISSUE THREAD

**Issue by Saurbaum** [jstedfast/MailKit#373]
I am at present using SslOnConnect for my SMTP connections.  One user though is reporting that they can only connect when using port 465 and that it fails if they attempt to use 25.  I'm trying to check but at present they are adamant that they have security running on port 25.

I know I'm not doing anything differently on the different ports and I'm pretty sure from the MailKit code that it isn't either but it has got me thinking about the SslOnConnect option.

Which is the better more secure one to use out of SslOnConnect and StartTls?

From reading the comments SslOnConnect should be the better one as it should encrypt immediately.

**Comment by jstedfast** [comment]
There isn't really a "better". SslOnConnect when used with SMTP is generally for port 465 and was historically used with SMTP servers that did not support SSL out of the box. What admins did was to wrap the SMTP port with another program that did the SSL encryption for the SMTP daemon process. This is known as "SSL-wrapping".

Later, SMTP server implementations started getting SSL support natively and this is enabled in the protocol usually as soon as the client reads the server greeting and queries the capabilities to check if the server supports the STARTTLS extension.

The greeting and list of initial capabilities are perfectly safe to allow transmission in clear text, so it doesn't matter that those bits aren't encrypted. Where you want encryption is authentication sending of the content.

The STARTTLS method is most often used with port 25 and/or 587 if the server supports it.

Note, however, that the admin can run the SMTP server on *any* port with *any* configuration (SslOnConnect or via STARTTLS or none of the above) he or she wants. The ports I mention are just a general rule of thumb.

Hope that helps.

**Comment by Saurbaum** [comment]
Thanks that's pretty much exactly what I was looking for.  By the sound of it I should use StartTLS because it's the more modern option so it's more likely that's what I'll encounter in the wild.

Does it also mean that the SslOnConnect can fail with "The handshake failed due to an unexpected packet format." if the server is not expecting encryption until it has delivered its greetings and capabilities?  If so that explains what the customer is seeing.

**Comment by jstedfast** [comment]
Yes.

SslOnConnect and StartTLS are both pretty common in the wild, so be mindful of that...
