### ISSUE TITLE
Cancellation token not always respected in IMAP Idle command; when server does not send data over SSL connection.

### ISSUE THREAD

**Issue by Mankarse** [jstedfast/MailKit#374]
I am trying to write a Windows Service that monitors email inboxes. The service must produce minimal network traffic while also having a low latency on inbox reads, so I want to use IMAP Idle when possible; however, the service must also be able to promptly shut down when requested by the Operating System/User.

This is currently not possible with MailKit, because MailKit does not always respect the cancellationToken that is provided to ImapClient.Idle.

The program below attempts to perform an IMAP Idle command over a SSL connection; it then attempts to prematurely cancel the Idle command via the `cancellationToken` parameter.

With MailKit 1.4.1; this test program below fails. `client.Idle()` blocks in the call to `Stream.Read` in [ImapStream.ReadAhead:339](https://github.com/jstedfast/MailKit/blob/1.4.1/MailKit/Net/Imap/ImapStream.cs#L339). This never unblocks until the `timeout` triggers a response from the server; which in the real code, could be up to 29 minutes after the user requested the cancellation. The call to `cancellationToken.ThrowIfCancellationRequested ()` is nice, but occurs too early to be generally useful; as the majority of the time is spent in the blocking `Stream.Read` call; rather than in the leadup to it.

I was able to resolve this issue with by replacing this problematic `Stream.Read` call with:

    var task = Stream.ReadAsync (input, start, end - start, cancellationToken);
    task.Wait (cancellationToken);
    nread = task.Result;

However, this requires dotnet >= v4.5, so will not work on all the platforms that MailKit targets. In theory this could be worked around via Stream.BeginRead; but I can't find any solid evidence that the SslStream.BeginRead/EndRead functions are non-blocking in .net4.0; and I don't have an environment that I can test .net4.0 in.

Another option would be linking the cancellationToken to the same thing that the doneToken is linked to.

    using System;
    using System.Linq;
    using System.Net;
    using System.Threading;
    using System.Threading.Tasks;
    using MailKit;
    using MailKit.Net.Imap;
    using NUnit.Framework;

    namespace DotNetEmailReceive
    {
        class Test1
        {
            static void Main(string[] args)
            {
                //Add your own test email server.
                //The server must not receive any emails during the test.
                var mailHost = "mail.example.com";
                var emailAddress = "test@example.com";
                var password = "a_password";

                //Start the client and connect to the server. No problems here.
                var client= new ImapClient();
                client.Connect(mailHost, 993, true); //Note; useSsl == true
                client.AuthenticationMechanisms.Remove("XOAUTH2");
                client.Authenticate(new NetworkCredential(emailAddress, password));
                client.Inbox.Open(FolderAccess.ReadOnly);

                //Run an Idle command, and after 5 seconds attempt to cancel it.
                var cancelTokenSource = new CancellationTokenSource();
                using (var timeout = new CancellationTokenSource(new TimeSpan(0, 0, 30))) {
                    var startTime = DateTime.UtcNow;

                    var task = Task.Run(() => client.Idle(timeout.Token, cancelTokenSource.Token));

                    Thread.Sleep(new TimeSpan(0,0,5));
                    cancelTokenSource.Cancel();
                    var ex = Assert.Throws<AggregateException>(() => task.Wait());
                    Assert.AreEqual(ex.InnerExceptions.Count, 1);
                    Assert.IsInstanceOf<OperationCanceledException>(ex.InnerExceptions.First());
                    var endTime = DateTime.UtcNow;

                    //Check that the Idle command got canceled after 5 seconds,
                    //rather than after the 30 second timeout.
                    Assert.Less(endTime, startTime.Add(new TimeSpan(0,0,10)),
                        "The cancelTokenSource cancel should have immediately interrupted the read operation; rather than only once the timeout finished..");
                }
            }
        }
    }

**Comment by Mankarse** [comment]
Note that my proposed workaround is actually silly, as if the cancellation happens during the call to `task.Wait`, the task is unceremoniously abandoned; rather than being cancelled. This is essentially equivalent to just calling `client.IdleAsync().Wait()`; which I could do anyway, without any alteration of the MailKit.

However, if I do not supply a CancellationToken to Wait(), the problem is not solved (the call to `Wait()` blocks, even if the original `ReadAsync` should have been cancelled by the supplied CancellationToken). It seems that `SslStream.ReadAsync` is not actually asynchronous.

**Comment by jstedfast** [comment]
This is, unfortunately, unfixable without rewriting SslStream. The problem is that there's no way to cancel an SslStream.Read[Async] and there's also no way to poll an SslStream.

You can poll the underlying NetworkStream, but the problem with doing that is that the remaining data you expect to read may already be data buffered on the SslStream (since it buffers data in order to decrypt it).

If you use plain network streams, everything is cancellable.

As I wrote in the documentation, one possible work-around you could try is try cancelling the `doneToken` first, and then the `cancellationToken`. That seems to work for me.

Hope that helps.

**Comment by Mankarse** [comment]
Thanks for the very fast reply. Indeed it is in the documentation (not sure how I missed it?). I have altered my code to trigger DoneToken cancel from UserCancellationToken cancel; and it now works well.

**Comment by jstedfast** [comment]
Glad that solution works for you :)
