### ISSUE TITLE
ImapClient.Idle can hang for dotnet core under docker

### ISSUE THREAD

**Issue by sh54** [jstedfast/MailKit#376]
I am finding that `ImapClient.Idle` is not always behaving as it should do when called in an app running in the docker image `microsoft/dotnet`. This may apply to other platforms but I have not tested them.

The specific issue is that `Idle` never returns if it is called with a `doneToken` that is a cancellation token from a cancellation token source that times out after 9 minutes.

This works just fine in Windows. It also works fine under docker if the timeout is just 1 minute.

The following code comes from the Main function of a bog standard app generated by `dotnet new`:

    var emailUsername = "someone@email.com";
    var emailPassword = "password";

    using (var client = new ImapClient()) {
        client.Connect("mail.messagingengine.com", 993, true);

        // Note: since we don't have an OAuth2 token, disable
        // the XOAUTH2 authentication mechanism.
        client.AuthenticationMechanisms.Remove("XOAUTH2");

        client.Authenticate(emailUsername, emailPassword);

        var someFolder = client.GetFolder("INBOX.someFolder");
        someFolder.Open(FolderAccess.ReadWrite);

        Console.WriteLine($"Entering Idle: {DateTime.Now.ToString("o")}");

        // This scenario does not work or docker but works for windows
        var idleTimeout = new CancellationTokenSource(new TimeSpan(0, 9, 0));

        // This works for docker & windows
        // var idleTimeout = new CancellationTokenSource(new TimeSpan(0, 1, 0));

        // This is just here to verify that the idle timout is getting noticed by the runtime
        idleTimeout.Token.Register(ctx => {
            // This is always getting called regardless of whether `Idle` returns or not
            Console.WriteLine("Timeout!");
        }, "context");

        try {
            // The function in question
            client.Idle(idleTimeout.Token);
        } catch (OperationCanceledException ex) { }
        // This point is never hit with a 9 minute timeout running in Docker
        Console.WriteLine($"Exiting Idle: {DateTime.Now.ToString("o")}");

        if (client.IsConnected) {
            someFolder.Close();
            client.Disconnect(true);
        }
    }

Other info:
dotnet version 1.0.0-preview2-003121 (same on docker and windows)
Docker version 1.11.2
Ubuntu 15.10 on Azure
Linux 4.2.0.42

**Comment by sh54** [comment]
When `ImapClient.Idle` hangs it eventually throws out an `IOException` after about 25 minutes with the message `Unable to read data from the transport connection: Connection timed out`.

**Comment by jstedfast** [comment]
If you log the connection to a file (see the FAQ for how to get a protocol log), does the `DONE` command get sent?

**Comment by sh54** [comment]
The DONE command does get sent.

Dump of logging:

Connected to imaps://mail.messagingengine.com:993/
S: * OK IMAP4 ready
C: A00000000 CAPABILITY
S: * CAPABILITY IMAP4 IMAP4rev1 LITERAL+ ENABLE UIDPLUS SASL-IR NAMESPACE CONDSTORE SORT LIST-EXTENDED QRESYNC MOVE SPECIAL-USE CREATE-SPECIAL-USE IDLE AUTH=PLAIN
S: A00000000 OK completed
C: A00000001 AUTHENTICATE PLAIN XYZXYZ
S: A00000001 OK [CAPABILITY IMAP4rev1 LITERAL+ ID ENABLE XAPPLEPUSHSERVICE ACL RIGHTS=kxten QUOTA MAILBOX-REFERRALS NAMESPACE UIDPLUS NO_ATOMIC_RENAME UNSELECT CHILDREN MULTIAPPEND BINARY CATENATE CONDSTORE ESEARCH SEARCH=FUZZY SORT SORT=MODSEQ SORT=DISPLAY SORT=UID THREAD=ORDEREDSUBJECT THREAD=REFERENCES THREAD=REFS ANNOTATEMORE ANNOTATE-EXPERIMENT-1 METADATA LIST-EXTENDED LIST-STATUS LIST-MYRIGHTS LIST-METADATA WITHIN QRESYNC SCAN XLIST XMOVE MOVE SPECIAL-USE CREATE-SPECIAL-USE DIGEST=SHA1 X-REPLICATION LOGINDISABLED XCONVERSATIONS COMPRESS=DEFLATE X-QUOTA=STORAGE X-QUOTA=MESSAGE X-QUOTA=X-ANNOTATION-STORAGE X-QUOTA=X-NUM-FOLDERS IDLE] User logged in SESSIONID=<XYZXYZ>
C: A00000002 NAMESPACE
S: * NAMESPACE (("INBOX." ".")) (("user." ".")) (("" "."))
S: A00000002 OK Completed
C: A00000003 LIST (SPECIAL-USE) "" "*"
S: * LIST (\HasNoChildren \Archive) "." INBOX.Archive
S: * LIST (\HasNoChildren \Drafts) "." INBOX.Drafts
S: * LIST (\HasNoChildren \Junk) "." "INBOX.Junk Mail"
S: * LIST (\HasNoChildren \XNotes) "." INBOX.Notes
S: * LIST (\HasNoChildren \Sent) "." "INBOX.Sent Items"
S: * LIST (\HasNoChildren \Trash) "." INBOX.Trash
S: A00000003 OK Completed (0.000 secs 17 calls)
C: A00000004 LIST "" INBOX.wiki
S: * LIST (\HasNoChildren) "." INBOX.wiki
S: A00000004 OK Completed (0.000 secs 1 calls)
C: A00000005 SELECT INBOX.wiki (CONDSTORE)
S: * 17 EXISTS
S: * 0 RECENT
S: * FLAGS (\Answered \Flagged \Draft \Deleted \Seen $X-ME-Annot-2 $IsMailingList $IsNotification $HasAttachment $HasTD)
S: * OK [PERMANENTFLAGS (\Answered \Flagged \Draft \Deleted \Seen $X-ME-Annot-2 $IsMailingList $IsNotification $HasAttachment $HasTD \*)] Ok
S: * OK [UIDVALIDITY xyzxyz] Ok
S: * OK [UIDNEXT xyzxyz] Ok
S: * OK [HIGHESTMODSEQ xyzxyz] Ok
S: * OK [URLMECH INTERNAL] Ok
S: * OK [ANNOTATIONS xyzxyz] Ok
S: A00000005 OK [READ-WRITE] Completed
Entering Idle: 2016-07-26T16:05:40.1840220+00:00
C: A00000006 IDLE
S: + idling
C: DONE
Timeout!

**Comment by jstedfast** [comment]
Okay, so the problem is that it's waiting for the server to send a response to the `DONE` command.

Why the server isn't sending a response is anyone's guess :(

**Comment by jstedfast** [comment]
So here's the deal... we know that the `DONE` command was sent because the logger will only log that the data was sent after it was sent successfully (and the stream was properly Flush()'d).

We also know that the timeout exception happens in the SslStream Read() implementation, which means that *either* the server is not replying to our `DONE` command *or* there is a bug in SslStream. It seems that either way this isn't a bug in MailKit afaict, so I'm at a loss as to how I can possibly "fix" this.

Any ideas?

**Comment by sh54** [comment]
Not too many ideas. When I have the time I will check with wireshark or something if the server is responding. I would imagine it is since exactly the same commands are being sent as for the working Windows version.

**Comment by jstedfast** [comment]
If you could get a wireshark log that would be awesome. I was going to suggest that, but most people I've suggested it to in the past didn't know how to use it to get logs over SSL.

**Comment by jstedfast** [comment]
Any luck getting the wireshark log?
