### ISSUE TITLE
Inheritance security rules violated while overriding member

### ISSUE THREAD

**Issue by gyself** [jstedfast/MailKit#378]
Hi,

I have made a local application using MailKit and everything works perfectly (locally).
However when I upload the application to my hosing (www.hostbasket.com), I get following error:
----------------------------------------------------------------------------------------------------------------
Server Error in '/' Application.

Inheritance security rules violated while overriding member: 'MailKit.Net.Imap.ImapCommandException.GetObjectData(System.Runtime.Serialization.SerializationInfo, System.Runtime.Serialization.StreamingContext)'. Security accessibility of the overriding method must match the security accessibility of the method being overriden.

Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

Exception Details: System.TypeLoadException: Inheritance security rules violated while overriding member: 'MailKit.Net.Imap.ImapCommandException.GetObjectData(System.Runtime.Serialization.SerializationInfo, System.Runtime.Serialization.StreamingContext)'. Security accessibility of the overriding method must match the security accessibility of the method being overriden.

Source Error: 

An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below.

Stack Trace: 

[TypeLoadException: Inheritance security rules violated while overriding member: 'MailKit.Net.Imap.ImapCommandException.GetObjectData(System.Runtime.Serialization.SerializationInfo, System.Runtime.Serialization.StreamingContext)'. Security accessibility of the overriding method must match the security accessibility of the method being overriden.]
   MailKit.Net.Imap.ImapClient.Connect(String host, Int32 port, SecureSocketOptions options, CancellationToken cancellationToken) +0
   MailKit.MailService.Connect(String host, Int32 port, Boolean useSsl, CancellationToken cancellationToken) +72
   Axius.Presentation.Website.frmAdminDossierEmail2.ToonOngelezenEmail(Boolean bBonnected) in frmAdminDossierEmail2.aspx.cs:71
   Axius.Presentation.Website.frmAdminDossierEmail2.Page_Load(Object sender, EventArgs e) in frmAdminDossierEmail2.aspx.cs:32
   System.Web.Util.CalliEventHandlerDelegateProxy.Callback(Object sender, EventArgs e) +51
   System.Web.UI.Control.OnLoad(EventArgs e) +92
   System.Web.UI.Control.LoadRecursive() +54
   System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint) +772

Version Information: Microsoft .NET Framework Version:4.0.30319; ASP.NET Version:4.0.30319.34280

----------------------------------------------------------------------------------------------------------------

The error occurs at frmAdminDossierEmail2.aspx.cs:71:
client.Connect(sMailServer, int.Parse(sMailSSL), true);

I am using VS 2010, Framework 4.0 and MailKit/MimeKit version 1.4.1.
Hosting is running on framework 4.0 / Classic pool

Any idea how to solve this error?

Thank you
Frederik

**Comment by gyself** [comment]
Btw, i already checked this topic: https://github.com/jstedfast/MailKit/issues/340

**Comment by jstedfast** [comment]
I provided a possible fix in the other issue, but I have no way of testing it so I need someone like you to test it and let me know if it fixes it :)

**Comment by gyself** [comment]
To be very honest I have no experience with github.

I have made a new branch/patch:

![capture](https://cloud.githubusercontent.com/assets/20824258/17393585/e7346d2e-5a24-11e6-87c3-ace034c06fd8.PNG)

How can I test this change?
How can I get updated dll files in my project?

Frederik

**Comment by jstedfast** [comment]
Ah, n/m, I forgot I actually committed the patch. Yes, it's in 1.4.1.

If that doesn't work, I have no idea how to make it work.

You could edit the source code and remove all of the serialization features if you won't be using them anyway. That should fix things for you.

**Comment by jstedfast** [comment]
The source code for Exception's GetObjectData() is:

```csharp
        [System.Security.SecurityCritical]  // auto-generated_required
        public virtual void GetObjectData(SerializationInfo info, StreamingContext context) 
```

If I look at Microsoft's source code for TypeUnloadedException, for example, this is what it has:

```csharp
        [System.Security.SecurityCritical]  // auto-generated_required
        public override void GetObjectData(SerializationInfo info, StreamingContext context) {
```

ImapCommandException's GetObjectData() also has the SecurityCritical attribute, so I don't see what the problem is.

**Comment by gyself** [comment]
Hi

When I install Mailkit via nuget it says I already installed 1.4.1 but when I look at the properties of the mailkit dll it says 1.4.0.
Can I ignore this?

**Comment by jstedfast** [comment]
There are 3 attributes that define the version. You can see them here: https://github.com/jstedfast/MailKit/blob/master/MailKit/Properties/AssemblyInfo.cs#L82

**Comment by jstedfast** [comment]
BTW, what happened to your patch? In your screenshot, there was a green button in the upper right that says "Compare & pull request" - that's the button you need to click and it will create a pull request that I can merge into the project.

**Comment by gyself** [comment]
In the patch I wanted to add [System.Security.SecurityCritical] but it was already there, so I removed the patch.

> You could edit the source code and remove all of the serialization features if you won't be using them anyway. That should fix things for you.

Later today I will try to remove serialization  features in 'ImapCommandException.cs'  and see if that solves my issue.
Can you confirm that to remove serialization, I need to remove below highlighted code?
![capture5](https://cloud.githubusercontent.com/assets/20824258/17402458/aceb13a0-5a53-11e6-8db4-03b119632302.PNG)
![capture6](https://cloud.githubusercontent.com/assets/20824258/17402464/b0d6a740-5a53-11e6-9b2c-f9cdb906ae33.PNG)

Yesterday I donwloaded the source code and opened MailKit.Net40.sln. This solution contains a reference to project MimeKit which can not be found. Can I just remove that project from MailKit.Net40.sln and build the Mailkit application?

Thx

**Comment by jstedfast** [comment]
About the serialization sections: yes, you have X'd out the correct sections. You could probably just edit the Project Options and remove the SERIALIZABLE define in the compiler section so that those sections do not get compiled.

MimeKit is needed in order to compile MailKit. You will need to update the submodules in your MailKit checkout.

If you are using TortoiseGit (which is what I use), you need to click this button:

![submodule-update](https://cloud.githubusercontent.com/assets/338984/17403396/87aa6952-5a25-11e6-84b2-60703dcca170.png)

**Comment by jstedfast** [comment]
You might also need to open the `submodules\MimeKit` folder in your explorer window and then right-click and select *Git Sync...* followed by clicking the *Submodule Update* button there as well (since MimeKit also uses submodules).

**Comment by gyself** [comment]
Ok, I will try in a few hours and let you know!

**Comment by gyself** [comment]
Hi,

MailKit.Net40.sln: 957 build errors :-(

947 errors related to 'nameof'. I searched the internet and it looks like this name is only compatible in VS2015.
(http://stackoverflow.com/questions/32943593/the-name-nameof-does-not-exist-in-the-current-context)

Other errors are:
![capture](https://cloud.githubusercontent.com/assets/20824258/17411900/5a1a3ce2-5a7a-11e6-9282-4c23dd60ece7.JPG)

Is there really no other way to get the mailkit/mimekit/bouncycatle DLL's without the serialization stuff?

Thx
Frederik

**Comment by jstedfast** [comment]
You could use Xamarin Studio.

Alternatively you could figure out a regex to rename `nameof (*)` with `"*"`

**Comment by jstedfast** [comment]
Actually using Xamarin Studio will not work either since it uses whatever C# compiler you have installed on your system (which is too old).

**Comment by jstedfast** [comment]
Add the following to your web.config:

```
<system.web>
    <trust level="Full" />
<system.web>
```

**Comment by jstedfast** [comment]
Question: why are you using MailKit.Net40.sln? Is your program using MailKit.dll for .NET v4.0? Or are you using the .NET v4.5 assembly?

If you are using the .NET 4.5 assembly, you should be opening the MailKit.Net45.sln instead.

**Comment by gyself** [comment]
I am using Visual Studio 2010 with Framework 4.0, so indeed i am using mailit.dll for .NET v4.0

**Comment by gyself** [comment]
I have installed VS2015 to change the code of MailKit and remove all serialization code.

When i use the new (compiled) DLLs I get following msg

![capture](https://cloud.githubusercontent.com/assets/20824258/17418056/ca83c2ca-5a96-11e6-8a37-ddd6bcb997ab.JPG)

**Comment by jstedfast** [comment]
You'll need to relax the restrictions on the runtime. MimeKit and MailKit use pointers to improve performance which apparently your runtime doesn't like.

**Comment by gyself** [comment]
What do you exactly mean with that?

**Comment by Insire** [comment]
You need to talk to your hosting provider and ask them, if they allow full trust web applications. If they do not, then you won't be able to run mailkit on your server or you can't use all features of mailkit.

**Comment by gyself** [comment]
Hosting provider will change settings to high trust in a few weeks. Will keep you updated!

**Comment by gyself** [comment]
Solved by switching from IIS7 (framework 4) to IIS8 server (framework 4.5) with full trust enabled in web.config file.

Thanks for all your help and time!

Rgds
Frederik
