### ISSUE TITLE
Search query doesn't work when additional parameters are added inside loop

### ISSUE THREAD

**Issue by gholol** [jstedfast/MailKit#379]
I have a strange issue with mailkit:

        
            string[] fromAuthors = new string[] { "@something.com", "@something2.com", "@somethingelse.net" };

            SearchQuery query = SearchQuery.FromContains(fromAuthors[0]);
            for (int i = 1; i < fromAuthors.Length; i++)
            {
                query.Or(SearchQuery.FromContains(fromAuthors[i]));
            }

This doesn't work, `inbox.Search(query)` returns results for only the first entry  (in this case "@something.com"), everything else is being ignored.

While this:

         SearchQuery query = SearchQuery.FromContains(fromAuthors[0]).Or(SearchQuery.FromContains(fromAuthors[1])) 

works fine, and results for both emails are being returned...

**Comment by DavidKarlas** [comment]
What you probably want to change is line inside for from:
```
query.Or(SearchQuery.FromContains(fromAuthors[i]));
```
to
```
query = query.Or(SearchQuery.FromContains(fromAuthors[i]));
```

**Comment by gholol** [comment]
Yeah, that worked... so it was my fault afterall.

**Comment by jstedfast** [comment]
Thanks David :)
