### ISSUE TITLE
Newlines are interpreted differently depending on mail server. Can I do something about it?

### ISSUE THREAD

**Issue by Bartmax** [jstedfast/MailKit#380]
I'm new to this mails thing so this may be a naive question, but I was wondering why is this happening and if it's something mailkit can take care of or email providers are doing something they can improve.

I didn't do a lot of test, but just sending an email like this:

```
var msg = $@"This message
spans multiple
lines

Greetings!
";

message.Body = new TextPart("plain") { Text = msg };
using (var client = new SmtpClient())
{
    await client.ConnectAsync("smtpserver", 587, SecureSocketOptions.Auto);
    await client.AuthenticateAsync("user", "pass");
    await client.SendAsync(message);
    await client.DisconnectAsync(true);
}
```

When using gmail smtp server, when I look at the email on gmail web client, I see the lines as they were sent.

I then switched to sendgrid smtp server, and at the same client (gmail web) i see the email as one liner, like this: `This message spans multiple lines Greetings!`

I found this to be inconsistent, wanted to know if you know why, if there is a setting on mailkit to make it behave always the same way, or if there's nothing I can do on my end.

Thanks!

**Comment by jstedfast** [comment]
Sounds like a Sendgrid issue to me. MailKit always converts newlines into <CR><LF> sequences when sending over SMTP because that's what the spec says to do.

Why Sendgrid removes <CR><LF> sequences is anyone's guess. Probably a bug on their side.

You can verify this by logging the transaction using something like this:

```csharp
using (var client = new SmtpClient (new ProtocolLogger ("smtp.log"))) {
    ...
}
```

Then, using a hex editor, make sure that the lines end with 0x0D 0x0A

**Comment by Bartmax** [comment]
@jstedfast thank you for the quick response! I cross referenced this issue on the sendgrid repo, I hope they can take a look at it.

**Comment by jstedfast** [comment]
Were you able to verify the newlines being sent by MailKit? I'm 99% sure it is sending &lt;CR&gt;&lt;LF&gt; but I suppose there's always the possibility that there is some edge case where it doesn't for whatever reason.

**Comment by Bartmax** [comment]
@jstedfast yup:

![image](https://cloud.githubusercontent.com/assets/3386797/17588900/0fdcc400-5fa8-11e6-8faf-ccab11b37a0c.png)

**Comment by Bartmax** [comment]
and for completeness:

![image](https://cloud.githubusercontent.com/assets/3386797/17589103/2fa71ece-5fa9-11e6-8f37-0544c3615e36.png)

**Comment by jstedfast** [comment]
awesome, thanks
