### ISSUE TITLE
engine.Uri = null in POP3 Authenticate method under NETFX_CORE

### ISSUE THREAD

**Issue by lumigabor** [jstedfast/MailKit#381]
Counterpart of Issue #192.
In an UWP app I get NullReferenceException in the Authenticate method of Pop3Client, because engine.Uri is null.
In Pop3Client.cs in Connect method there is this line between #if !NETFX_CORE and #else:
`engine.Uri = uri;`
I think it should be between #else and #endif too, just like in ImapClient.cs.

**Comment by jstedfast** [comment]
Thanks for reporting this! I also noticed that the `secure` variable was not properly initialized either. Also fixed that.

**Comment by jstedfast** [comment]
new packages have been pushed with the fix
