### ISSUE TITLE
MailKit NullReferenceException 

### ISSUE THREAD

**Issue by mc1271** [jstedfast/MailKit#382]
Hi Jeffrey,
first of all thank you for your work and effort on helping out, where Microsoft misses out, as they have not yet ported System.net.mail to .NetCore.

I'm trying to use your MailKit (1.4.1) in my Windows 10 IoT Project (.NetCore) running on my Raspberry PI 3 / ARM CPU.

I pasted your SMTP Sample, but unfortunately I get Null ReferenceException when 
setting SMTPClient.Authenticate
>Exception thrown: 'System.NullReferenceException' in MailKit.dll
>The program '[2172] backgroundTaskHost.exe' has exited with code -1 (0xffffffff).

Stack Trace:
   at MailKit.Net.Smtp.SmtpClient.IsBrokenSmtpServerThatResetsStateAfterAuthEhlo(String host)
   at MailKit.Net.Smtp.SmtpClient.Authenticate(Encoding encoding, ICredentials credentials, CancellationToken cancellationToken)
   at MailKit.MailService.Authenticate(String userName, String password, CancellationToken cancellationToken)
   at W10IoT.clseMail.SendMail(String param_strMessage)
   at W10IoT.StartupTask.Run(IBackgroundTaskInstance taskInstance)

Hope you can help.

Best wishes
       Mike

**Comment by jstedfast** [comment]
This should be fixed by the same patch that fixed issue #381 (that one was reported for Pop3Client, but I audited all of the *Clients and fixed the same issue among all of them in the WindowsUniversal81 cases).

**Comment by mc1271** [comment]
Thanks Jeffrey, for getting back so quickly.

Sorry for the stupid/newbie question, but are you going to publish the fix in a new release (Update via Nuget) ?

**Comment by jstedfast** [comment]
Yep, I'm actually working on that right now :)

**Comment by jstedfast** [comment]
pushed

**Comment by mc1271** [comment]
Hi Jeffrey,
thank you again for respoding so fast.
Just upgraded to 1.4.2. works like a charm.
Rasperry is mailing away ;)
Thank you very much
MIke
