### ISSUE TITLE
1.4.2 Gmail Inbox = null

### ISSUE THREAD

**Issue by m1dst** [jstedfast/MailKit#383]
I just upgraded to 1.4.2 and found that I was getting a null exception when requesting the inbox.

var inbox = client.Inbox;
inbox.Open(FolderAccess.ReadWrite);

I rolled back to version 1.4.1 and it works as usual.

**Comment by jstedfast** [comment]
I can't seem to reproduce this with 1.4.2 and there have been no patches that I can find that would affect this between 1.4.1 and 1.4.2.

Do you have a test case I can use to reproduce this problem?

**Comment by m1dst** [comment]
Just tried the upgrade again and confirmed it still fails.  It doesn't fail with a non Google IMAP though.

I will try to create something standalone to repro.

**Comment by m1dst** [comment]
OK, managed to repro the problem in a console app using the following code.

```
using (var client = new ImapClient())
{

    var host = "imap.gmail.com";
    var port = 993;
    var username = "";
    var password = "";

    client.Connect(host, port, true);
    client.Authenticate(username, password);

    var inbox = client.Inbox;
    inbox.Open(FolderAccess.ReadWrite);
}   
```

[MailKit42GmailNullRepro.zip](https://github.com/jstedfast/MailKit/files/419914/MailKit42GmailNullRepro.zip)

Confirmed that 1.4.2 fails and 1.4.1 works.

What I did notice is I deliberately supplied an incorrect password and the authentication section passed silently in 1.4.2 but in 1.4.1 it warned of incorrect password.

So something has definitely changed.

James

**Comment by jstedfast** [comment]
Okay, so supplying an invalid password is broken now in that it doesn't properly emit an exception.

That sounds plausible because I did change some of that logic recently. I'll take a look.

**Comment by jstedfast** [comment]
Yep! Found and fixed the issue! Thanks for reporting. I'll try to push a new nuget release soon.

**Comment by m1dst** [comment]
I confirm it fixed my issue.

Thanks
