### ISSUE TITLE
Can't Delete message from GMail

### ISSUE THREAD

**Issue by yuribb** [jstedfast/MailKit#384]
Hello. I trashed a message and tried to Expunge it. But message still is in trash folder. Code: 

```
var result = mailFolder.MoveTo(uniqueIds, trashFolder);
mailFolder.CloseAsync(true);
if (trashFolder.IsOpen) trashFolder.Close(false);
trashFolder.Open(MailKit.FolderAccess.ReadWrite);
trashFolder.SetFlags(result.Source, MailKit.MessageFlags.Deleted, true);
trashFolder.Expunge(result.Source);
trashFolder.Close(true);
```
How can i expunge the trash folder?

**Comment by ralsu091** [comment]
I think `trashFolder.Expunge(result.Source);` is not what you want.
Try `trashFolder.Expunge();`
From the docs:
> mapFolder.Expunge Method (IList<UniqueId>, CancellationToken)
Expunge the specified uids, permanently removing them from the folder.

uids refer to the messages ids.

You can refer to: http://www.mimekit.net/docs/html/M_MailKit_Net_Imap_ImapFolder_Expunge_1.htm
and http://www.mimekit.net/docs/html/M_MailKit_Net_Imap_ImapFolder_Expunge.htm

**Comment by jstedfast** [comment]
`result.Source` refers to the UIDs in the `mailFolder` and not the `trashFolder`. You want to use `result.Destination` when settings flags/expunging the `trashFolder`.

Hope that helps.

**Comment by DavidKarlas** [comment]
Also what looks kind of wrong...
`mailFolder.CloseAsync(true);` You need `await mailFolder.CloseAsync(true);` or ugly `mailFolder.CloseAsync(true).Wait();`

**Comment by yuribb** [comment]
Thank you for answer. It is really helped me.
