### ISSUE TITLE
MailKit seems to ignore mail attachments sometimes

### ISSUE THREAD

**Issue by sboldt** [jstedfast/MailKit#386]
Hello.

I have a windows service with periodically connects to a Exchange 2016 to fetch mails from 'input' folder. 
I fetch only summaries first, move mails to 'archive' folder and save the new uid in a queue.

Then later i fetch mails from this queue from 'archive' folder and inspect their attachments. If mail does not have a pdf attachment the i move it to 'malformed' folder and remove it from queue.

But sometimes there are mail in 'malformed' who do have a pdf attachment. But when i accessing attachment through Mail object (MimeMessage) it returns an empty collection.

When i later manually (in Outlook) move tthis mails back to 'input' folder then they get processed correctly and do not land in 'malformed' folder. This is a bit unfavorable because i must always watch 'malformed' folder an move the mail back.

I do following to fetch mails:

```
using (var client = this.CreateImapClient(connector))
                {
                    var queue= GetFromQueue();
                    Log.DebugFormat("Got {0} queue entries to process. ", queue.Length);

                    foreach (var queueElement in queue)
                    {                       
                        var personal = client.GetFolder(client.PersonalNamespaces[0]);

                        var archiveMailFolder = GetOrCreateSubFolder(personal, archiveFolder);

                        var malformedFolder = GetOrCreateSubFolder(personal, malformedMessagesFolder);

                        archiveMailFolder.Open(FolderAccess.ReadWrite);

                        var uniqueMailId = new UniqueId(Convert.ToUInt32(queueElement.DocumentID));

                        // no mail found .. delete database entry
                        var mail = archiveMailFolder.GetMessage(uniqueMailId);
                        if (mail == null)
                        {
                            Log.WarnFormat("Mail with id {0} was not found. Imap Log ->", uniqueMailId.Id);
                            Log.Warn(this.imapClientLog.GetLog());

                            queue.Remove(queueElement);                            
                            continue;
                        }

                        var mailBody = !string.IsNullOrEmpty(mail.TextBody)
                                           ? mail.TextBody
                                           : !string.IsNullOrEmpty(mail.HtmlBody) ? mail.HtmlBody : string.Empty;

                        var attachments = mail.Attachments.ToArray(); 

                        var firstPdfAttachment = attachments.OfType<MimePart>().FirstOrDefault(w => w.FileName.ToLowerInvariant().EndsWith("pdf")); // here ist the firstPdfAttachment sometimes null
                        if (firstPdfAttachment == null)
                        {                                                       
                            Log.Warn("Mail does not have a PDF Attachment. Send mail to " + malformedFolder);
                            Log.Warn("Mail -> " + mail);
                           
                            foreach (var attachment in attachments)
                            {
                                Log.Warn("Attachment: " + attachment);
                            }

                            Log.Warn("Imap Log ->" + this.imapClientLog.GetLog());

                            archiveMailFolder.MoveTo(uniqueMailId, malformedFolder);

                            queue.Remove(queueElement);
                            
                            continue;
                        }

                        Log.DebugFormat("Attachment with filename {0} found", firstPdfAttachment.FileName);

//processing mail attachment
}
```

I have attached mail.txt witch contains MimeMessage.ToString and protocoll of the conversation between clinet and server. 

Both files clearly shows that there is an pdf attachment, but this mail landed in 'malformed' anyway.

[mail.txt](https://github.com/jstedfast/MailKit/files/424419/mail.txt) -> Content of MailMessage.ToString() i see that there is an attachment

[protocol.txt](https://github.com/jstedfast/MailKit/files/424421/protocol.txt) -> Here i see that attachmanet ist transferred to client

Hope you can help

Best regards
Sergej

**Comment by jstedfast** [comment]
Technically it's not an attachment because it does not have a header that looks something like `Content-Disposition: attachment; filename="Rechnung 392059734.pdf"`

What you need to do is scan `message.BodyParts` for pdfs and not `message.Attachments`.

MimeKit will only treat a MIME part as an attachment if it has a `Content-Disposition` header with a value of `attachment` (ignoring any additional parameters that may or may not be set).

If a MIME part does not have the` Content-Disposition` header, mail clients are supposed to assume that the value would be `inline` which means that it is part of the message body and should be rendered as such. Obviously whether the client can render that type of attachment or not depends on the client itself, and so if it cannot display that type of content, then most mail clients will choose to fall back to treating it as an attachment instead.

Hope that helps explain why things work the way they do...

**Comment by sboldt** [comment]
Ok. So you mean i should do following to check for pdf in mail:

```
var bodyParts = mail.BodyParts.OfType<MimePart>().ToArray();
var firstPdfAttachment = bodyParts.FirstOrDefault(w => w.FileName.ToLowerInvariant().EndsWith("pdf"));
```

But why emails gets processed after i manually move them back to input folder? Any ideas?

**Comment by jstedfast** [comment]
Most likely the IMAP server is adding a `Content-Disposition` header and setting it to `attachment` when moving it.

Your code snippet is almost right, but be aware that `w.FileName` can be null, so your code snippet as is will crash.

Secondly, the `ToArray()` on the first line is not needed.

Hope that helps.

**Comment by sboldt** [comment]
Ok.

This is the final version witch will work well i think.

```
var bodyParts = mail.BodyParts.OfType<MimePart>();
var firstPdfAttachment = bodyParts.FirstOrDefault(w => w.ContentType.IsMimeType("application", "pdf") || (w.FileName != null && w.FileName.ToLowerInvariant().EndsWith("pdf")));
```

Thank you very much for your help.
