### ISSUE TITLE
Verifying TLS

### ISSUE THREAD

**Issue by smnz** [jstedfast/MailKit#387]
MailKit automatically uses TLS if STARTTLS is available but doesn't expose that information to the client.  It should be possible to determine if the current connection was made using TLS or not.

For example, an active attacker can intercept the SMTP session and remove the STARTTLS capability from the stream.  The client will then automatically continue without TLS.  This leaves connections vulnerable.  The client should be able to validate if TLS is actually in use for the current session, and ideally also get certificate information for certificate pinning purposes.

**Comment by jstedfast** [comment]
You can check the `IsSecure` property: http://www.mimekit.org/docs/html/P_MailKit_IMailService_IsSecure.htm :)

**Comment by jstedfast** [comment]
For the Certificate, you can override http://www.mimekit.org/docs/html/P_MailKit_IMailService_ServerCertificateValidationCallback.htm
