### ISSUE TITLE
Email not sent in RELEASE mode

### ISSUE THREAD

**Issue by jkalanda** [jstedfast/MailKit#388]
hey there folks - 
I have everything up and going and emails are being sent as expected in the DEBUG mode.
however, when in the RELEASE mode, emails aren't  making it to the destination.
I'm rolled back and started using the simplest mailkit example but, still... in the RELEASE mode it's not working.
Any suggestion would be much appreciated.
Here's the copy of what I'm using. 

			var message = new MimeMessage();
			message.From.Add(new MailboxAddress("EasyA Tutor", "xxxxxxxx@gmail.com"));
			message.To.Add(new MailboxAddress("Student", "yyyyyyyyy@gmail.com"));
			message.Subject = EmailProperties.Subject;
			message.Body = new TextPart("plain")
			{
				Text = @"Hey there
			};
			using (var client = new SmtpClient())
			{
				client.Connect("smtp.gmail.com", 587, false);
				// Note: since we don't have an OAuth2 token, disable
				// the XOAUTH2 authentication mechanism.
				client.AuthenticationMechanisms.Remove("XOAUTH2");

				// Note: only needed if the SMTP server requires authentication
				client.Authenticate("falseusername", "falsepassword");
				client.Send(message);
				client.Disconnect(true);
			}

**Comment by jstedfast** [comment]
I just tested this locally and it works fine when built in RELEASE mode for me. All nuget packages are built in RELEASE mode, so I know that it works for other people as well.

I really have no idea what to tell you. ¯\_(ツ)_/¯

**Comment by jkalanda** [comment]
Hey Jeff, thanks for checking.
Can you at least suggest some ideas? 
What could be the difference between DEBUG and RELEASE modes.
I don't think google smtp configuration has anything to do with it. 
If it did... it wouldn't be working in the DEBUG mode either.

**Comment by jstedfast** [comment]
I can't think of anything that would be different between debug and release modes except that one has debugging symbols and the other doesn't

**Comment by jkalanda** [comment]
Jeff, what a trooper. You were incredibly helpful. 
I learned I shall not ask anything on this thread again.
just for the folks that spent a bit of time to figure out why this was happening, here's the solution:
just add <uses-permission android:name="android.permission.INTERNET" /> in your manifest file.

**Comment by jstedfast** [comment]
I don't think I was that helpful :-\

Thanks for posting the solution, though! That might help others in your situation.

**Comment by NirajW-Infogain** [comment]
@jkalanda  I am working in UWP application. And I am facing same issue - email not sent in RELEASE mode. Could you please help me in providing more details, as to what and how do I add into manifest file? 
Thank You.
