### ISSUE TITLE
How to receive incoming email from multi emaill address other? My english is bad.

### ISSUE THREAD

**Issue by tienvd1994** [jstedfast/MailKit#392]
How to receive incoming email from multi emaill address other? My english is bad.

**Comment by jstedfast** [comment]
Create multiple Pop3Client objects or multiple ImapClient objects, one for each email address.

**Comment by tienvd1994** [comment]
Thanks for your help.

2016-08-28 18:04 GMT+07:00 Jeffrey Stedfast <notifications@github.com>:
