### ISSUE TITLE
MailKit fails to authenticate against shaw.ca mailserver

### ISSUE THREAD

**Issue by Saurbaum** [jstedfast/MailKit#393]
My apologies for the vagueness I'm waiting on some more information.

Shaw.ca (ISP in Canada) are running a mail server on mail.shaw.ca and one of my users is attempting to connect to it for their email needs.  I THINK it's running Exchange 2010 but I can't be certain.

I've managed to get an account out of them to test on but to see the problem you actually wouldn't need one.

I can connect fine

`client.Connect(this.ServerAddress, this.ServerPort, SecureSocketOptions.StartTls);`

but no matter what I send here 

`client.Authenticate(this.UserName, this.Password);`

no exception is thrown when a logon fails unless I have set the password to blank.

My code then continues having not seen an exception and attempts to send the mail which will return

`5.1.0 Authentication required`

Using the same details I threw together a test using `System.Net.Mail.SmtpClient` and that works.

**Comment by Saurbaum** [comment]
In case it helps the connection details are 
Server: mail.shaw.ca
Port: 587

**Comment by jstedfast** [comment]
Make sure that you are using MailKit 1.4.2.1 and not 1.4.2 (1.4.2 has a bug where a bad login did not throw an exception).

**Comment by Saurbaum** [comment]
I've tried with 1.4.2.1 and with 1.2.13 but they behave the same on authentication with this server.

**Comment by jstedfast** [comment]
FWIW, I'm getting an AuthenticationException locally, but it looks like the 1.4.2 issue only affected IMAP and not SMTP (like I thought in my previous comment).

**Comment by Saurbaum** [comment]
I'll try it again with a bad username in case that makes a difference.  It's definitely the strangest mail server I've had this displeasure of connecting to.

**Comment by jstedfast** [comment]
Just to make sure I'm understanding the issue correctly:

There are 2 issues here:

1. Using an invalid user/passwd combo, an exception is not being thrown
2. When the correct user/passwd are being used, it throws an exception on `Send()` saying that authentication is required

Is that correct? Or is it only the first issue?

The reason I ask is because I *think* the second issue *might* be that MailKit sends an EHLO command after authenticating (because the specs say clients should do that in case the server offers different capabilities for authenticated users) but from my own experience, *some* SMTP servers are broken and when you send EHLO after successfully authenticating, it wipes out their authenticated state variable and they think the client is no longer authenticated.

**Comment by Saurbaum** [comment]
Correct both 1 and 2 are being seen.

I've double checked and any setting I put in for the username and password, except a blank password, result in no exception.

Then in all cases on this server the send throws the exception because it is no authenticated.  It certainly sounds likely that the authenticated state is being dropped.  Is there a way for me to prove that?  More importantly is there a way for me to not send the second EHLO?  No disrespect intended to your benevolent overlords but I doubt Microsoft is going to patch Exchange 2010 any time soon.

**Comment by jstedfast** [comment]
No disrespect taken :)

Are you able to test MailKit built from source? If so, you can modify https://github.com/jstedfast/MailKit/blob/master/MailKit/Net/Smtp/SmtpClient.cs#L75 to add `"smtp.shaw.ca"` to that list and that *should* fix that issue (at least assuming the problem is the one I think it is).

As far as the invalid user/passwd not throwing an exception, that is weird. I'll have to dig some more to figure out why you aren't getting an exception and I am. This is with 1.4.2.1, right?

**Comment by Saurbaum** [comment]
Yes.  I was on 1.2.13 but I figured that you'd really only care about the latest so I've pulled that in as well.  I'll double check my build process and make sure the binaries are getting to the right place and I'm not still dealing with an old build by mistake.

**Comment by jstedfast** [comment]
ok, cool. If you are still seeing the problem after you make sure you get a fresh build, can you give me a sample invalid user/pass combo that you are trying?

I've been trying:

    client.Authenticate ("invalid", "invalid");

That's what has been giving me the exception.

**Comment by jstedfast** [comment]
I've just aded smtp.shaw.ca to that list since I'm fairly certain that will solve the second issue you are seeing.

Now we just need to figure out the invalid user/pass issue.

**Comment by Saurbaum** [comment]
I've checked it with a locally built dll and yes they are the 4th "honorable" entry into the non standard compliant club.  Now I'm deeper in the code I see I can get an exception out of it in 1.4.2.x
`The SMTP server has unexpectedly disconnected.`

Not exactly what I would have expected on an invalid password but it's something.  When the full nuget is available I'll get that and pull it in do a full build and test it again.

**Comment by jstedfast** [comment]
That's not the correct exception, you should be getting an AuthenticationException

**Comment by Saurbaum** [comment]
Note that it's mail.shaw.ca not smtp.shaw.ca that's being flagged.  It appears that they have actually setup and alias on both of them but their own support recommend using mail.shaw.ca 

Looks like the server has dropped offline at the moment so I'll have to wait for that to come back online before I investigate it further.

**Comment by jstedfast** [comment]
Oh, okay. I could probably add both aliases to the list.

**Comment by Saurbaum** [comment]
Definitely only getting the exception `The SMTP server has unexpectedly disconnected.` 

Using the built in .Net client and the same wrong credentials I get `The server committed a protocol violation The server response was: ` so I don't think this is anything we are doing

I'll raise it with the ISP and try to get my external ip address off the blacklist I seem to have been added to for failing to log on too many times.

Can you push the new version via nuget and we can close this ticket off then?

**Comment by jstedfast** [comment]
Unfortunately I am working remotely this week and so do not have access to my normal Windows/Visual Studio setup so can't publish any nugets until I get back this weekend.

**Comment by Saurbaum** [comment]
No worries I won't be rushing this fix out now I know that the mail server is at fault.  I'll be arguing this with them for a few days anyway with the timezone.

**Comment by Saurbaum** [comment]
Any chance we can make a minor change to let a user specify that a connection is against a non compliant server? Either as a property on the Smtp client or as part of the connection method?  I'm just conscious that this list will grow more and more and I'm sure you don't really want me to keep pestering you with an ever increasing list of dodgy servers.

**Comment by jstedfast** [comment]
Yea, I've been thinking of how to better solve this. I might just have to give up on doing what I'm supposed to do (i.e. sending EHLO after authenticating) and just default to not sending it.

Either that or having a bool property like "QueryCapabilitiesAfterAuth" or something.

**Comment by jstedfast** [comment]
FWIW, if shaw.ca asks you what their server implements wrong, point them to rfc2554, Page 2:

         If a security layer is negotiated through the SASL
         authentication exchange, it takes effect immediately following
         the CRLF that concludes the authentication exchange for the
         client, and the CRLF of the success reply for the server.  Upon
         a security layer's taking effect, the SMTP protocol is reset to
         the initial state (the state in SMTP after a server issues a
         220 service ready greeting).  The server MUST discard any
         knowledge obtained from the client, such as the argument to the
         EHLO command, which was not obtained from the SASL negotiation
         itself.  The client MUST discard any knowledge obtained from
         the server, such as the list of SMTP service extensions, which
         was not obtained from the SASL negotiation itself (with the
         exception that a client MAY compare the list of advertised SASL
         mechanisms before and after authentication in order to detect
         an active down-negotiation attack).  The client SHOULD send an
         EHLO command as the first command after a successful SASL
         negotiation which results in the enabling of a security layer.

What *they* are doing is resetting state *completely*, including resetting authentication state which means that when the client sends an `EHLO` command after authenticating, it then cannot send messages because the server thinks that the client is not authenticated.

**Comment by jstedfast** [comment]
as far as part 1 of this bug, what happens if you do:

    client.Authenticate ("invalid", "invalid");

Does that fail? Or does it succeed? I'm wondering if the server accepts any password as long as the username is correct?

**Comment by Saurbaum** [comment]
I fails it just reports and internal server error and drops the connection instead of an Authenticaiton exception.

**Comment by jstedfast** [comment]
I've released MailKit 1.6.0 with the mail.shaw.ca fix but still can't repro your other problem.

**Comment by uthens** [comment]
**I tested with SMTP gmail it's worked.**
**Code:**
using (var client = new SmtpClient())
            {
               await client.ConnectAsync(sSMTP, nPort, false);

                // Note: since we don't have an OAuth2 token, disable
                // the XOAUTH2 authentication mechanism.
                client.AuthenticationMechanisms.Remove("XOAUTH2");
                await client.AuthenticateAsync(sFromEmail, sAuthenPassword);

                client.Send(message);
                client.Disconnect(true);
            }

**But when i try to used with SMTP on my company, it's don't work.**
**Code:** 
 using (var client = new SmtpClient())
            {
                // For demo-purposes, accept all SSL certificates (in case the server supports STARTTLS)
                client.ServerCertificateValidationCallback = (s, c, h, e) => true;

                client.Connect(sSMTP, 587, false);

                // Note: since we don't have an OAuth2 token, disable
                // the XOAUTH2 authentication mechanism.
                client.AuthenticationMechanisms.Remove("XOAUTH2");

                // Note: only needed if the SMTP server requires authentication
                client.Authenticate(sFromEmail, sAuthenPassword);

                client.Send(message);
                client.Disconnect(true);
            }

**Error : One or more errors occurred. (5.7.0 authentication failed)**

**Comment by uthens** [comment]
**And also i tested on your sample code:** 
<img width="1214" alt="screen shot 2560-06-12 at 11 46 58 am" src="https://user-images.githubusercontent.com/10783170/27019929-e9a5d308-4f66-11e7-8c00-1d9b3da2b058.png">

**Comment by uthens** [comment]
**Im try on this :** 
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Text;
using MailKit.Net.Smtp;
using MailKit;
using MimeKit;

namespace app01console
{
    public class Program
    {
        public static void Main(string[] args)
        {
            var mailSender = new EMailSender();
            var task = mailSender.SendEmailAsync();
            Task.WaitAll(task);
        }
    }    

    public class EMailSender
    {

        public async Task SendEmailAsync() {

            var message = new MimeMessage ();
            message.From.Add (new MailboxAddress ("Joey Tribbiani", "an@email.com"));
            message.To.Add (new MailboxAddress ("Mrs. Chanandler Bong", "another@email.com"));
            message.Subject = "How you doin'?";

            message.Body = new TextPart ("plain") {
                Text = @"Hey Chandler,

I just wanted to let you know that Monica and I were going to go play some paintball, you in?

-- Joey"
            };

            using (var client = new SmtpClient())
            {
                //client.ServerCertificateValidationCallback = delegate (
                //    Object obj, X509Certificate certificate, X509Chain chain,
                //    SslPolicyErrors errors)
                //{
                //    return (true);
                //};

                await client.ConnectAsync("smtp.sendgrid.net", 587, false);
                //await client.ConnectAsync(smtpOptions.Server, smtpOptions.Port, SecureSocketOptions.StartTls);

                // Note: since we don't have an OAuth2 token, disable
                // the XOAUTH2 authentication mechanism.
                client.AuthenticationMechanisms.Remove("XOAUTH2");

                // Note: only needed if the SMTP server requires authentication
                // if(smtpOptions.RequiresAuthentication)
                // {

                // }

                await client.AuthenticateAsync("myusername", "mypassword");

                client.Send(message);
                Console.WriteLine("Mensaje enviado");

                client.Disconnect(true);
                Console.WriteLine("Cliente desconectado");

            }
        }
    }
}

I still found the same error: 
<img width="1063" alt="screen shot 2560-06-12 at 2 42 51 pm" src="https://user-images.githubusercontent.com/10783170/27023619-84bd4400-4f7d-11e7-93a9-7b0d69a7dfd7.png">

Reference from : https://github.com/jstedfast/MailKit/issues/293

**Comment by jstedfast** [comment]
What does the error in your first screenshot say? Now look at your Connect() call and tell me what's wrong.

**Comment by uthens** [comment]
I tested on code sample and it's first screenshot show me.
**CASE1: don't use user and password:**

<img width="960" alt="screen shot 2560-06-13 at 10 06 37 am" src="https://user-images.githubusercontent.com/10783170/27064425-763d89ae-5021-11e7-8948-9a34ceca8a5c.png">

**Comment by uthens** [comment]
**CASE2: I used user & password**
<img width="961" alt="screen shot 2560-06-13 at 10 10 43 am" src="https://user-images.githubusercontent.com/10783170/27064630-8da851b8-5022-11e7-840a-00a2ddc4869b.png">

**Error exception:**
+		$exception	{MailKit.Net.Smtp.SmtpCommandException: 5.7.0 authentication failed
   at MailKit.Net.Smtp.SmtpClient.Authenticate(Encoding encoding, ICredentials credentials, CancellationToken cancellationToken)
   at MailKit.MailService.Authenticate(String userName, String password, CancellationToken cancellationToken)
   at TestClient.Program.Main() in D:\Projects\OpenSource\MailKit\MyTest2\Program.cs:line 19}	MailKit.Net.Smtp.SmtpCommandException

**Comment by uthens** [comment]
I try on this : https://stackoverflow.com/questions/40236311/5-7-0-user-not-authenticated-in-asp-net-core1-with-mailkit-and-strato-server
but still don't worked!

client.QueryCapabilitiesAfterAuthenticating = false;

**Comment by jstedfast** [comment]
Update your code from git master.

**Comment by jstedfast** [comment]
Also the reason I asked you to tell me what the error was in your first screenshot was because the error said "The server does not support STARTTLS" and you were specifically requesting the code to use STARTTLS.

**Comment by uthens** [comment]
It's worked thank you so much you're still best!

**Comment by tskarman** [comment]
I had issues that sound similar and wanted to stay with the current MailKit NuGet package (1.16.1).

The code snippet below describes my workaround. I've added the server log output below.
Since you only mentioned `DIGEST-MD5` issues and that method was tried last, I might have hit on a different phenomen, though.
Or am I doing sth. else entirely wrong?

```
        private static void Authenticate(SmtpClient client, string userName, string password)
        {
            // Prefer PLAIN over secure connections.
            // This is mostly a workaround for our mail server (Kerio Connect 9.2.3),
            // that doesn't seem to like MailKit's non-PLAIN auth. and terminates the connection
            // after 3 failed auth. methods (which is before PLAIN is ordinarily attempted).
            if (client.IsSecure && client.AuthenticationMechanisms.Contains("PLAIN"))
            {
                client.AuthenticationMechanisms.Clear();
                client.AuthenticationMechanisms.Add("PLAIN");

                // We could retry the other mechanisms if this fails.
                // But no point really, since that would only ever work
                // if the mail server falsely advertised PLAIN support.
                // Better cut the attempt short.
                client.Authenticate(userName, password);
            }
            else
            {
                // Execute the default behavior.
                client.Authenticate(userName, password);
            }
        }
```

The log lines of the server were:

```
[16/Jun/2017 15:25:26] Failed SMTP login from x.x.x.x with SASL method NTLM.
[16/Jun/2017 15:25:29] Failed SMTP login from x.x.x.x with SASL method CRAM-MD5.
[16/Jun/2017 15:25:32] Failed SMTP login from x.x.x.x with SASL method DIGEST-MD5.
[16/Jun/2017 15:25:32] SMTP server connection from x.x.x.x closed after 3 bad commands
```

**Comment by jstedfast** [comment]
Well, it seems your server doesn't advertise `PLAIN` so it never hits your `Clear()`

**Comment by jstedfast** [comment]
Either that or the connection isn't secure.

**Comment by tskarman** [comment]
I was unclear:
* The above piece of code is working fine and was required to make MailKit work in my case.
* The log output is from before my change (i.e. the default behavior).
* `PLAIN` is advertised by the mailserver. Judging by the log output, it is not tried as one of the first 3 auth. methods by MailKit. (Since the method list is a set it seems unlikely that an order could be imposed anyway).

I just wanted to add that information to the discussion in case anyone else stumbles over failed auth with the MailKit NuGet packages.

**Comment by ismailmohammed** [comment]
Hi,

I am using mailKit 2.3.1.6 with ImapClient and get authentication error. below is my code FYI. Please help me anyone.

using (var client = new ImapClient(new ProtocolLogger(Console.OpenStandardOutput())))
            {
                //client.Connect("imap.gmail.com", 993, SecureSocketOptions.SslOnConnect);
                client.Connect("outlook.office365.com", 993, true);                 
                client.AuthenticationMechanisms.Remove("XOAUTH2");
                client.Authenticate("ismail@aa.net", "adsd123");
                 
                client.Inbox.Open(FolderAccess.ReadOnly);
                client.Disconnect(true);
            }

In the console, I am getting this.

Connected to imaps://outlook.office365.com:993/
S: * OK The Microsoft Exchange IMAP4 service is ready. [TQBBAFgAUABSADAAMQAwADEAQwBBADAAMAA0ADkALgBJAE4ARABQAFIARAAwADEALgBQAFIATwBEAC4ATwBVAFQATABPAE8ASwAuAEMATwBNAA==]
C: A00000000 CAPABILITY
S: * CAPABILITY IMAP4 IMAP4rev1 AUTH=PLAIN AUTH=XOAUTH2 SASL-IR UIDPLUS ID UNSELECT CHILDREN IDLE NAMESPACE LITERAL+
S: A00000000 OK CAPABILITY completed.
C: A00000001 AUTHENTICATE PLAIN AGlzbWFpbEBhdWRsaW5rLm5ldABZbm1zcUA3ODY=
S: A00000001 NO AUTHENTICATE failed.
C: A00000002 LOGIN ismail@aa.net adsd123
S: A00000002 NO LOGIN failed.

Thank you

**Comment by jstedfast** [comment]
Looks like the IMAP server is rejecting your username and password which probably means you are using the wrong username and/or password.

**Comment by ismailmohammed** [comment]
@jstedfast I have given valid credentials but still same error.

**Comment by jstedfast** [comment]
Try `client.Authentications.Remove ("PLAIN");` - I doubt it'll work, but you could try.

**Comment by ismailmohammed** [comment]
No luck same error : MailKit.Security.AuthenticationException: 'LOGIN failed.'

**Comment by Saurbaum** [comment]
You don't have 2 factor authentication switched on in outlook do you?
