### ISSUE TITLE
Getting messages from GMail is very slow

### ISSUE THREAD

**Issue by rboy1** [jstedfast/MailKit#394]
This is a weird problem so I'll try my best to explain it. I've written a custom c# client to get my emails from Gmail. I have 2 gmail accounts, I have the EXACT same code, two instance of the executable running, one of each account. Both accounts have about 10 email in the inbox folder from which I'm retrieving the emails.
One of them fetches all the emails in under 3 seconds while the other takes about 10 seconds per email.

I recently upgraded to MailKit 1.4.2.1 and MimeKit 1.4.2 if that makes any difference. Any suggestions on why one is zooming and other is crawling. They are virtually identical accounts otherwise.

**Comment by jstedfast** [comment]
Both are GMail accounts and one is slow and one is fast?

You could try clearing client.AuthenticationMechanisms except for the auth mechanism you are actually using (look at the log to see).

To get a log, just create your ImapClient like this:

    new ImapClient (new ProtocolLogger ("imap.log"))

**Comment by rboy1** [comment]
Yes that's right both GMail and almost identical size etc
The only Authentication mechanism I'm removing is XOAUTH2 and this is what I get back from GMAIL. Any pointers would be appreciated, also what's this THROTTLED?

Connected to imaps://imap.gmail.com:993/
S: * OK Gimap ready for requests from XX.XX.XX.XX 77mb97000802yxn
C: B00000000 CAPABILITY
S: * CAPABILITY IMAP4rev1 UNSELECT IDLE NAMESPACE QUOTA ID XLIST CHILDREN X-GM-EXT-1 XYZZY SASL-IR AUTH=XOAUTH2 AUTH=PLAIN AUTH=PLAIN-CLIENTTOKEN AUTH=OAUTHBEARER AUTH=XOAUTH
S: B00000000 OK Thats all she wrote! 77mb97000802yxn
C: B00000001 AUTHENTICATE PLAIN AHJib3lhcHBzQGdtYWlsLmNvbQBTYmdtcmVjMTEhIQ==
S: * CAPABILITY IMAP4rev1 UNSELECT IDLE NAMESPACE QUOTA ID XLIST CHILDREN X-GM-EXT-1 UIDPLUS COMPRESS=DEFLATE ENABLE MOVE CONDSTORE ESEARCH UTF8=ACCEPT LIST-EXTENDED LIST-STATUS LITERAL- APPENDLIMIT=35651584
S: B00000001 OK XXX@gmail.com authenticated (Success)
C: B00000002 NAMESPACE
S: * NAMESPACE (("" "/")) NIL NIL
S: B00000002 OK Success [THROTTLED]

**Comment by rboy1** [comment]
This is what I get from the account that is zooming. I think it's this THROTTLED that may be the issue. Wonder what that is and how to get rid of it:

> Connected to imaps://imap.gmail.com:993/
> S: * OK Gimap ready for requests from XX.XX.XX.XX i189mb138493950yxa
> C: A00000000 CAPABILITY
> S: * CAPABILITY IMAP4rev1 UNSELECT IDLE NAMESPACE QUOTA ID XLIST CHILDREN X-GM-EXT-1 XYZZY SASL-IR AUTH=XOAUTH2 AUTH=PLAIN AUTH=PLAIN-CLIENTTOKEN AUTH=OAUTHBEARER AUTH=XOAUTH
> S: A00000000 OK Thats all she wrote! i189mb138493950yxa
> C: A00000001 AUTHENTICATE PLAIN AG1jZWJ1ZGR5MnhAZ21haWwuY29tAFNiZ21yZWMxMSEh
> S: * CAPABILITY IMAP4rev1 UNSELECT IDLE NAMESPACE QUOTA ID XLIST CHILDREN X-GM-EXT-1 UIDPLUS COMPRESS=DEFLATE ENABLE MOVE CONDSTORE ESEARCH UTF8=ACCEPT LIST-EXTENDED LIST-STATUS LITERAL- APPENDLIMIT=35651584
> S: A00000001 OK YYYY@gmail.com authenticated (Success)
> C: A00000002 NAMESPACE
> S: * NAMESPACE (("" "/")) NIL NIL
> S: A00000002 OK Success

**Comment by jstedfast** [comment]
I guess it suggests that GMail is throttling your connection. I did a quick google search and it looks like Google will throttle your connection if you request too much data in a short period.

https://developers.google.com/gmail/api/v1/reference/quota

**Comment by rboy1** [comment]
Thanks. That is what it is. It's supposed to back off the limits after 24 hours let's see. It's possible because I was polling it every minute. But then I'm doing both accounts every minute.

One final question is there is a way to subscribe to push notifications instead of polling to reduce this overhead?

**Comment by jstedfast** [comment]
You can use `client.Idle()` or `client.IdleAsync()` - check out https://github.com/jstedfast/MailKit/tree/master/samples/ImapIdle

**Comment by rboy1** [comment]
Thanks, FYI for others here is another FAQ from google about general limits and restoration times
https://support.google.com/a/answer/1366776?hl=en

**Comment by rboy1** [comment]
One more follow up question - I'm trying to nail why it generated such a problem, one check per minute is NOT heavy load as per the limits defined in the google FAQ.

I'm trying to retrieve all emails from the inbox. Is this the "optimal" way to do it? If not what would be the "right" way to get them:

> IMailFolder inbox = Client.GetFolder("Inbox"); // Get the Inbox
>                 inbox.Open(FolderAccess.ReadWrite); // Open Inbox with read/write capability
>                 IList<UniqueId> uids = inbox.Search(SearchQuery.All);
> 
>                 foreach (UniqueId uid in uids)

**Comment by jstedfast** [comment]
That's about as optimal as you can get. The problem might be that Google didn't like you fetching that much data so quickly. I have no idea.

**Comment by rboy1** [comment]
So an update, just like that it fixed itself but I reduced the polling from 1 minute to 15 minutes for 24 hours. It's not throttled anymore.

**Comment by rboy1** [comment]
So I'm going to make a request here. Given this nature of throttling is there a way to capture this in a flag/variable for the imapclient? That way the application can look at the flag and adjust the interaction period with the Miao server to avoid it getting out of control. Let me know if you want me to open a new issue for this. Thanks

**Comment by jstedfast** [comment]
This is impossible to know in the ImapClient

**Comment by rboy1** [comment]
So I'm going to pick at this again, thanks to your help I was able to move to a more efficient structure of downloading only the body instead of the whole email. But here's an interesting issue I ran into.
If you recall one of my accounts is being throttled by GMail (even at 15 minute poll intervals).

With the earlier `inbox.search()` implementation, while it downloaded ALL the emails and was inefficient, it worked, albeit VERY slowly due to the throttling but it worked without any issues.

Now since I've moved to the newer more efficient implementation of using fetch() I get this exception:

> MailKit.Net.Imap.ImapProtocolException: The IMAP server has unexpectedly disconnected.
   at MailKit.Net.Imap.ImapStream.ReadAhead(Int32 atleast, CancellationToken cancellationToken)
   at MailKit.Net.Imap.ImapStream.ReadToken(String specials, CancellationToken cancellationToken)
   at MailKit.Net.Imap.ImapCommand.Step()
   at MailKit.Net.Imap.ImapEngine.Iterate()
   at MailKit.Net.Imap.ImapFolder.Fetch(Int32 min, Int32 max, MessageSummaryItems items, CancellationToken cancellationToken)

Can you shed some light or suggest a fix? Why would search() and GetMessage() work but fetch() die?

**Comment by jstedfast** [comment]
This exception is one of those "the network connection has mysteriously dropped" errors.

It might be that Google Mail dropped the connection or it might be something else.

Half the fun of network programming is handling random disconnects and re-connecting at every method call :(

One of the downsides to MailKit's current `Connect()` and `Authenticate()` design is that it doesn't lend itself to auto-reconnecting for the user very easily.

I originally chose this for simplicity and also because people tend to get paranoid about saving their password in memory (which I'd have to do if I were to auto-reconnect).

For auth mechanisms like OAuth2.0, I'm not sure if I can simply re-use the auth_token (which is used as a password) anyway :-\

**Comment by rboy1** [comment]
So let me understand this, the way I've designed it is that the IMAP client is created, then connected and finally authenticated as part of a static process (once and done for the scope of the program).
From then on every 15 minutes when I want to check for emails, I look at the isConnected and isAuthenticated properties, if either of them are false, I close the connection and start over (the static process).

Are you suggesting that if gMail has dropped the connection the isConnected and isAuthenticated properties won't reflect that?

**Comment by jstedfast** [comment]
Well, the `IsConnected` property won't reflect it until the client realizes that the connection is dropped, which won't happen until the client goes to read or write to the socket - at which point you get the `ImapProtocolException`.

Once you get an `ImapProtocolException`, you need to check `IsConnected`. If that is `false`, then you'll need to re-`Connect()`, `Authenticate()` and possibly re-`Open()` the folder that you had open before (if you had a folder opened).

**Comment by jstedfast** [comment]
Yea, I might be able to provide a `ReconnectCallback` method. Unfortunately this is a non-trivial problem to fix within the client itself :(

**Comment by rboy1** [comment]
Got it thanks, may I recommend that you also put that information in the documentation, critical and very helpful.

**Comment by jstedfast** [comment]
It's in the Remarks section of [ImapProtocolException](http://www.mimekit.net/docs/html/T_MailKit_Net_Imap_ImapProtocolException.htm) :)

I'm not sure where else to add it.

**Comment by rboy1** [comment]
with the isConnected and and isAuthenticated parts, especially the part about it not being synchronous, that it's more reactive in nature and real time. I.e. checking this doesn't guarantee that the connection is alive or connected or authenticated etc.

**Comment by rboy1** [comment]
http://www.mimekit.net/docs/html/P_MailKit_Net_Imap_ImapClient_IsAuthenticated.htm

and

http://www.mimekit.net/docs/html/P_MailKit_Net_Imap_ImapClient_IsConnected.htm

probably mention that it's not real time, it's only valid post an exception if I understood it correctly

**Comment by jstedfast** [comment]
done

**Comment by rboy1** [comment]
Awesome, would it make sense to note that the connection state isn't in realtime, so it may return true even if it's disconnected and appropriate time to check would be during an exception and not otherwise.

BTW noticed a few minutes ago that with this efficient way to handling mails, GMail has stopped throttling the connection also.
