### ISSUE TITLE
POP3 Authentication issue

### ISSUE THREAD

**Issue by p231970** [jstedfast/MailKit#395]
this is logged conversation between server and client using MailKit:

> Connected to pop://mail.shoppingcartelite.com:110/?starttls=when-available
> S: +OK <16184.1473445882@mail3.gohsphere.com>
> C: CAPA
> S: +OK capability list follows
> S: USER
> S: TOP
> S: UIDL
> S: .
> C: APOP System.Text.UTF8Encoding pavel@shoppingcartelite.com
> S: -ERR authorization failed
 
As you see server returns capabilities without APOP, but the MailKit try it first and server always closes the connection. Also Capabilities property contains this "Apop | Top | UIDL | User".
To resolve this I have to add a code between Connect and Authenticate:
`Client.Capabilities ^= MailKit.Net.Pop3.Pop3Capabilities.Apop;`
But I think it should to use capabilities returned by the server.

**Comment by jstedfast** [comment]
The server supports APOP (that's what that email address thingy is in the greeting before the CAPA command).

The problem is that it's sending `System.Text.UTF8Encoding` as your username because I got some arguments swapped by mistake in the code :)

**Comment by jstedfast** [comment]
I'll make a new nuget release this weekend with the fix.

Thanks for the bug report!

**Comment by jstedfast** [comment]
I've released MailKit 1.6.0 with this fix
