### ISSUE TITLE
Add possibility to pass a string IMAP query to ImapFolder.Search

### ISSUE THREAD

**Issue by cervengoc** [jstedfast/MailKit#396]
#We are in the process of testing MailKit and migrating to it from ImapX library (it was me who posted the related question on SO yesterday).

We have out own interface for reading IMAP messages to be as loosely coupled from any third-party libraries as possible.

Our interface method for searching messages in a folder receives a string IMAP query, so like this again, we don't depend on any library specifically.

I see that in MailKit there is a comfortable `SearchQuery` implementation, which is very nice, but in our case it would be better if we could simply use strings, so we wouldn't need to change our consuming codes.

Anyway this seems to be a great project and at first glance we like it very much, thank you for all the work.

**Comment by jstedfast** [comment]
Done :)

https://github.com/jstedfast/MailKit/commit/0c9f3a14c31c012d77ac24bf1597b94f529bbb5c

**Comment by cervengoc** [comment]
Wow that was really fast thank you :) Will use the latest `master` build until next release, no need to hurry.

**Comment by jstedfast** [comment]
Cool :)
