### ISSUE TITLE
HtmlPreviewVisitor

### ISSUE THREAD

**Issue by madu2003** [jstedfast/MailKit#398]
Hi,

I am trying to get inline images in emails to show in html. HtmlPreviewVisitor works fine in my local machine but when its uploaded to the server it does not seem to work. Image tend to show as cid:image

Is it something to do with ToBase64String in the server?

**Comment by jstedfast** [comment]
It sounds like you aren't replacing the src attribute in the img tags.

I would need to see your source code (and a screenshot of what you are seeing?) to provide any more usefulness.

**Comment by madu2003** [comment]
Hi,

The following is how I call the function.

uploadpath = ConfigurationManager.AppSettings["testuploadpath"].ToString();
var visitor = new Reader.HtmlPreviewVisitor(uploadpath + message.MessageId);

-----------------------------HtmlPreviewVisitor  Class------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.DirectoryServices;
using Intandem.Data;
using System.Threading;
using System.Web;
using System.Reflection;
using System.Data.SqlClient;
using System.Web.Hosting;
using System.DirectoryServices.ActiveDirectory;
using System.IO;

using MimeKit;
using MimeKit.Text;
using MimeKit.Tnef;

namespace Reader
{
	#region HtmlPreviewVisitor
	/// <summary>
	/// Visits a MimeMessage and generates HTML suitable to be rendered by a browser control.
	/// </summary>
	public class HtmlPreviewVisitor : MimeVisitor
	{
		List<MultipartRelated> stack = new List<MultipartRelated> ();
		List<MimeEntity> attachments = new List<MimeEntity> ();
		readonly string tempDir;
		string body;

		/// <summary>
		/// Creates a new HtmlPreviewVisitor.
		/// </summary>
		/// <param name="tempDirectory">A temporary directory used for storing image files.</param>
		public HtmlPreviewVisitor (string tempDirectory)
		{
			tempDir = tempDirectory;
		}

		/// <summary>
		/// The list of attachments that were in the MimeMessage.
		/// </summary>
		public IList<MimeEntity> Attachments {
			get { return attachments; }
		}

		/// <summary>
		/// The HTML string that can be set on the BrowserControl.
		/// </summary>
		public string HtmlBody {
			get { return body ?? string.Empty; }
		}

		protected override void VisitMultipartAlternative (MultipartAlternative alternative)
		{
			// walk the multipart/alternative children backwards from greatest level of faithfulness to the least faithful
			for (int i = alternative.Count - 1; i >= 0 && body == null; i--)
				alternative[i].Accept (this);
		}

		protected override void VisitMultipartRelated (MultipartRelated related)
		{
			var root = related.Root;

			// push this multipart/related onto our stack
			stack.Add (related);

			// visit the root document
			root.Accept (this);

			// pop this multipart/related off our stack
			stack.RemoveAt (stack.Count - 1);
		}

		// look up the image based on the img src url within our multipart/related stack
		bool TryGetImage (string url, out MimePart image)
		{
			UriKind kind;
			int index;
			Uri uri;

			if (Uri.IsWellFormedUriString (url, UriKind.Absolute))
				kind = UriKind.Absolute;
			else if (Uri.IsWellFormedUriString (url, UriKind.Relative))
				kind = UriKind.Relative;
			else
				kind = UriKind.RelativeOrAbsolute;

			try {
				uri = new Uri (url, kind);
			} catch {
				image = null;
				return false;
			}

			for (int i = stack.Count - 1; i >= 0; i--) {
				if ((index = stack[i].IndexOf (uri)) == -1)
					continue;

				image = stack[i][index] as MimePart;
				return image != null;
			}

			image = null;

			return false;
		}

		// Save the image to our temp directory and return a "file://" url suitable for
		// the browser control to load.
		// Note: if you'd rather embed the image data into the HTML, you can construct a
		// "data:" url instead.
        //string SaveImage (MimePart image, string url)
        //{
        //    string fileName = url.Replace (':', '_').Replace ('\\', '_').Replace ('/', '_');

        //    string path = Path.Combine (tempDir, fileName);

        //    if (!File.Exists (path)) {
        //        using (var output = File.Create (path))
        //            image.ContentObject.DecodeTo (output);
        //    }

        //    return "file://" + path.Replace ('\\', '/');
        //}

        string SaveImage(MimePart image, string url)
        {
            using (var output = new MemoryStream())
            {
                image.ContentObject.DecodeTo(output);

                var buffer = output.GetBuffer();
                int length = (int)output.Length;

                return string.Format("data:{0};base64,{1}", image.ContentType.MimeType, Convert.ToBase64String(buffer, 0, length));
            }
        }

		// Replaces <img src=...> urls that refer to images embedded within the message with
		// "file://" urls that the browser control will actually be able to load.
		void HtmlTagCallback (HtmlTagContext ctx, HtmlWriter htmlWriter)
		{
			if (ctx.TagId == HtmlTagId.Image && !ctx.IsEndTag && stack.Count > 0) {
				ctx.WriteTag (htmlWriter, false);

				// replace the src attribute with a file:// URL
				foreach (var attribute in ctx.Attributes) {
					if (attribute.Id == HtmlAttributeId.Src) {
						MimePart image;
						string url;

						if (!TryGetImage (attribute.Value, out image)) {
							htmlWriter.WriteAttribute (attribute);
							continue;
						}

						url = SaveImage (image, attribute.Value);

						htmlWriter.WriteAttributeName (attribute.Name);
						htmlWriter.WriteAttributeValue (url);
					} else {
						htmlWriter.WriteAttribute (attribute);
					}
				}
			} else if (ctx.TagId == HtmlTagId.Body && !ctx.IsEndTag) {
				ctx.WriteTag (htmlWriter, false);

				// add and/or replace oncontextmenu="return false;"
				foreach (var attribute in ctx.Attributes) {
					if (attribute.Name.ToLowerInvariant () == "oncontextmenu")
						continue;

					htmlWriter.WriteAttribute (attribute);
				}

				htmlWriter.WriteAttribute ("oncontextmenu", "return false;");
			} else {
				// pass the tag through to the output
				ctx.WriteTag (htmlWriter, true);
			}
		}

		protected override void VisitTextPart (TextPart entity)
		{
			TextConverter converter;

			if (body != null) {
				// since we've already found the body, treat this as an attachment
				attachments.Add (entity);
				return;
			}

			if (entity.IsHtml) {
				converter = new HtmlToHtml {
					HtmlTagCallback = HtmlTagCallback
				};
			} else if (entity.IsFlowed) {
				var flowed = new FlowedToHtml ();
				string delsp;

				if (entity.ContentType.Parameters.TryGetValue ("delsp", out delsp))
					flowed.DeleteSpace = delsp.ToLowerInvariant () == "yes";

				converter = flowed;
			} else {
				converter = new TextToHtml ();
			}

			string text = entity.Text;

			body = converter.Convert (entity.Text);
		}

		protected override void VisitTnefPart (TnefPart entity)
		{
			// extract any attachments in the MS-TNEF part
			attachments.AddRange (entity.ExtractAttachments ());
		}

		protected override void VisitMessagePart (MessagePart entity)
		{
			// treat message/rfc822 parts as attachments
			 attachments.Add (entity);
            // entity.Message.WriteTo(new FileStream(@"E:\stripped.eml", FileMode.CreateNew));
		}

		protected override void VisitMimePart (MimePart entity)
		{
			// realistically, if we've gotten this far, then we can treat this as an attachment
			// even if the IsAttachment property is false.
			attachments.Add (entity);
		}
	}
	#endregion


}





--------------------------------------------------------------------------------------

**Comment by jstedfast** [comment]
FWIW, your `SaveImage()` method returns a string instead of saving the image to a temp directory, so you don't actually need a temp directory for the HtmlPreviewVisitor .ctor.

Have you tried using the other (commented out) implementation of `SaveImage()` instead? Maybe whatever browser you are using can't handle embedded image data?

**Comment by madu2003** [comment]
Hi jstedfast,

Sorry to reply to a closed thread. But I am still having problems with reading embedded images. I tested the HtmlPreviewVisitor function in one of our test servers and I read emails from outlook.office365.com. It saved the images all good using the SaveImage function commented above.

But when I implemented this on a client environment it failed to read the embedded images in emails. 
The email message body shows <cid:myimagecid> like format.

How do I make sure whether it hits the SaveImage function or not? Is there a log file which writes stuff when reading emails? or is it the mail server version /type where mailkit fails to recognise embedded images?

Thanks.

**Comment by madu2003** [comment]
Ok, I think I know what basically is causing the problem. I added some logging and came across the code lines below.

In the HtmlPreviewVisitor class, the part where it checks for  -- if (entity.IsHtml) is false when the client uses outlook desktop app. When this happens it does not save the embedded images. But if the client uses outlook 360 browser app to embed images it's saving ok. Is there a way which I could read when the user embeds images in outlook desktop app? Sorry I am really struggling to get this working desperately. Thanks.

protected override void VisitTextPart (TextPart entity)
		{
			TextConverter converter;
            LogWrite("VisitTextPart");
			if (body != null) {
				// since we've already found the body, treat this as an attachment
				attachments.Add (entity);
				return;
			}

			if (entity.IsHtml) {
				converter = new HtmlToHtml {
					HtmlTagCallback = HtmlTagCallback
				};
			} else if (entity.IsFlowed) {
				var flowed = new FlowedToHtml ();
				string delsp;

				if (entity.ContentType.Parameters.TryGetValue ("delsp", out delsp))
					flowed.DeleteSpace = delsp.ToLowerInvariant () == "yes";

				converter = flowed;
			} else {
				converter = new TextToHtml ();
			}

			string text = entity.Text;

			body = converter.Convert (entity.Text);
		}

**Comment by jstedfast** [comment]
Well, what is the MIME-type of the entity? Is it RTF? MimeKit doesn't have an RTF parser so you'll have to write your own.

**Comment by madu2003** [comment]
Hi , see below. Using the ProtocolLogger it gave me the following logs. I had to delete some sensitive info. Does this look like RTF?

S: --_004_4A65F7ACB3F1F042AD0C44CC4FD7DAAF620CCEE4UKIXEEXC901ukkw_--
S:  UID 348693)
S: A00000008 OK FETCH completed.
C: A00000009 UID FETCH 348694 (BODY.PEEK[])
S: * 4045 FETCH (BODY[] {86194}
S: Received: from <deleted> ([fe80::3589:3001:1b06:e41c]) by
S:  <deleted> ([fe80::d5c:a3c9:ce62:1ff7%38]) with mapi id
S:  14.03.0301.000; Fri, 21 Oct 2016 15:04:52 +0100
S: From:  <deleted>
S: To: <deleted>
S: Subject: TEST EMAIL
S: Thread-Topic: TEST EMAIL
S: Thread-Index: AdIrpAzoBJ2OFEEeSreFhAwAXMpnyQ==
S: Date: Fri, 21 Oct 2016 15:04:51 +0100
S: Message-ID:
S:  <34CEEB1A04F1B449A7276AA0CE732652FC448217@<deleted>>
S: Accept-Language: en-GB, en-US
S: Content-Language: en-US
S: X-MS-Exchange-Organization-AuthAs: Internal
S: X-MS-Exchange-Organization-AuthMechanism: 04
S: X-MS-Exchange-Organization-AuthSource: <deleted>
S: X-MS-Has-Attach: yes
S: X-MS-Exchange-Organization-SCL: -1
S: X-MS-TNEF-Correlator:
S: x-exclaimer-md-config: b2bb2c14-5fe2-4a3d-abf2-8daa5fa7b89b
S: x-originating-ip: [10.216.182.245]
S: Content-Type: multipart/related;
S: 	boundary="_002_34CEEB1A04F1B449A7276AA0CE732652FC448217UKWATEXC901ukkw_";
S: 	type="text/plain"
S: MIME-Version: 1.0
S: 
S: --_002_34CEEB1A04F1B449A7276AA0CE732652FC448217UKWATEXC901ukkw_
S: Content-Type: text/plain; charset="us-ascii"
S: 
S: TEST EMAIL
S: 
S: 
S: [cid:image001.png@01D22BAC.7834C820]
S: 
S: --_002_34CEEB1A04F1B449A7276AA0CE732652FC448217UKWATEXC901ukkw_
S: Content-Type: image/png; name="image001.png"
S: Content-Description: image001.png
S: Content-Disposition: inline; filename="image001.png"; size=61817;
S: 	creation-date="Fri, 21 Oct 2016 14:04:51 GMT";
S: 	modification-date="Fri, 21 Oct 2016 14:04:51 GMT"
S: Content-ID: <image001.png@01D22BAC.7834C820>
S: Content-Transfer-Encoding: base64
