### ISSUE TITLE
Interesting exception when try to log in an unsecure imap server

### ISSUE THREAD

**Issue by Jonas741** [jstedfast/MailKit#399]
Hi,
My problem is: my code is just working fine on gmail and other secure servers. When I'm connecting to this unsecure imap(without ssl) server it works on my main pc(even if I use a virtual machine(different ip, directly connected to the network card(diferent mac too), it has win 8.1 and working perfectly with the unsecure server).

But when I'm try to run my code on a different computer it throw this exception:
"A call to SSPI failed, see inner exception."
Inner exception: "The Local Security Authority cannot be contacted"

Any idea what can cause this? How should I workaround this?
(Sorry for my English)

**Comment by jstedfast** [comment]
You are trying to connect with SSL. Show me your call to `client.Connect()`.

**Comment by jstedfast** [comment]
Make sure to use:

```csharp
client.Connect ("hostname", port, SecureSocketOptions.None);
```

Using this should also work unless the server has a broken STARTTLS implementation:

```csharp
client.Connect ("hostname", port, SecureSocketOptions.StartTlsWhenAvailable);
```

**Comment by Jonas741** [comment]
Thanks it looks like helps. I have used a simple bool in the client.Connect("host",port,xyz.ssl) like this.
Thanks for the quick answer, much appreciated.
