### ISSUE TITLE
Difference between MailKit and other IMAP libs?

### ISSUE THREAD

**Issue by jgboggs** [jstedfast/MailKit#401]
Hi,

I was wondering what the difference between these projects were (aenetmail, MailKit, S22.Imap, MailSystem.NET, etc) and whether maybe it would be a good idea for all of these projects to work together instead of reinventing the wheel over and over again?

I'm trying to make a decision on which one to use. At first glance, it would appear that MailKit might be the way to go (it has 1012 stars) while aenetmail has 269, S22.Imap has 117 and MailSystem.NET has 17, but I've learned the hard way that more popularity doesn't mean "best".

I plan to post this same question on each of these projects with the hope of getting thoughts of the both the developers and the users (have users used the other libraries? how did they compare? why did you choose the one you settled on?)

Any feedback would be hugely helpful in saving me a lot of time and effort!

**Comment by jstedfast** [comment]
I would argue that there's a reason MailKit has more users than any of the other IMAP libraries you listed even though they've been around far longer than MailKit.

MailKit:

1. is better quality
2. is more robust
3. is more efficient
4. is more rfc-compliant
5. has more features (i.e. implements more IMAP extensions)
6. has better documentation

I dunno, is there anything MailKit *doesn't* do better? :)

Oh, and unlike the other projects you mentioned, it's not abandoned. So there's that.

It's also the only mail library for .NET Core. Not even System.Net.Mail's SmtpClient exists on .NET Core.

**Comment by jgboggs** [comment]
Wow! That was fast! Thanks for replying!

I guess it's hard to argue with that. I didn't realize the other libraries were abandoned. I guess that makes things simple.

**Comment by jgboggs** [comment]
I haven't had time to check this myself yet (I started to try, but gave up because I don't know what I'm doing well enough), but as per the discussion at https://github.com/pmengal/MailSystem.NET/issues/6, it seems that MailKit does not pass some of MailSystem.NET's unit tests.

Maybe you could check it out?

**Comment by jstedfast** [comment]
which ones?

**Comment by jstedfast** [comment]
Turns out there were no bugs in MimeKit but there *were* some broken assumptions in MailSystem.NET's parser/unit tests.
