### ISSUE TITLE
The remote certificate is invalid according to the validation procedure

### ISSUE THREAD

**Issue by praachii** [jstedfast/MailKit#402]
Hello,

I am trying to connect imap with following code but it gives error as: 
The remote certificate is invalid according to the validation procedure.

using (var client = new ImapClient())
                {
    
                    client.Connect("imap.mail.com", 143,false);
                    client.AuthenticationMechanisms.Remove("XOAUTH2");
                    client.Authenticate(username, password);
}

When i add the followin certificate validation code. it does get connected.
//ServicePointManager.ServerCertificateValidationCallback += (o, c, ch, er) => true;

So, is it safe to use this approach or is there any better approach for this?

**Comment by jstedfast** [comment]
Depends. Do you care if the server is who it claims to be? If you do, then no.

You have a few options:

1. Import the server's certificate into your certificate database (not sure how to do this, so you'll have to use Google) and mark the certificate as trusted.
2. Write a custom callback that checks the certificate's Thumbprint against a known value.

To get the Thumbprint, you could write a custom callback that uses Console.WriteLine() or something to print out the value.
