### ISSUE TITLE
"Specified cast is not valid" on SmtpClient.Connect() method

### ISSUE THREAD

**Issue by dstep2007** [jstedfast/MailKit#403]
I'm trying to setup a simple smtp email feature using MailKit.  Here is my code:

```csharp
public void SendEmail(List<string> emails, string body, string subject)
{
        var emailMessage = new MimeMessage();

        emailMessage.From.Add(new MailboxAddress("Test", "test@gmail.com"));
        foreach(var e in emails)
        {
            emailMessage.To.Add(new MailboxAddress("", e));
        }
        emailMessage.Subject = subject;
        emailMessage.Body = new TextPart("plain") { Text = body };

        using (var client = new SmtpClient())
        {
            client.Connect("smtp.gmail.com", 587, SecureSocketOptions.StartTls);
            client.Authenticate("username", "password");
            client.Send(emailMessage);
            client.Disconnect(true);
        }
}
```

on the `client.Connect()` method, I am getting an exception thrown "Specified cast is not valid".  I'm not sure why since all of my data types line up with the method prototype as shown in the documentation [http://www.mimekit.net/docs/html/M_MailKit_Net_Smtp_SmtpClient_Connect_1.htm](url).

I've also tried this using port 465 and SecureSocketOptions.SslOnConnect with the same exception as the result.

Please let me know if I am doing something wrong, otherwise possibly there was a breaking change recently?  Thanks!

**Comment by jstedfast** [comment]
What method is throwing that exception? Can you provide me with a StackTrace of the exception?

I've never seen anyone get that, especially from such a simple message. I have unit tests that test this and they don't throw.

**Comment by jstedfast** [comment]
A protocol log might also be helpful...

```csharp
using (var client = new SmtpClient(new ProtocolLogger ("smtp.log")))
```
