### ISSUE TITLE
Disconnect all mail transports when the transport is disposed

### ISSUE THREAD

**Issue by SeanFarrow** [jstedfast/MailKit#404]
Hi,

I am using MailKit with a dependency injection framework--Autofac specifically. Looking at the source I notice that the MailService class implements IDisposable, providing the capability for other classes to implement disposable where needed.

I also notice that from what I can see no overriding class does this. I am suggesting, that the IMap, Pop3 and Smtp clients all implement the Dispose method, specifically disconnection from the server if we are connected.

I am happy to implement this, if this is something that would be wanted, as currently, any class that uses any class deriving from MailService, has to disconnect and then call dispose. This, doesn't make sense, surely, disconnecting should be part of disposable.

Kind regards
Sean.

**Comment by jstedfast** [comment]
I'm guessing you didn't actually look at the code :)

Dispose() does call Disconnect().

**Comment by SeanFarrow** [comment]
ok, where is that, I couldn’t find it!

**Comment by jstedfast** [comment]
Right here: https://github.com/jstedfast/MailKit/blob/master/MailKit/Net/Smtp/SmtpClient.cs#L2100

**Comment by SeanFarrow** [comment]
Ok, got it, strange that I didn’t see that one—sorry!

**Comment by jstedfast** [comment]
Disconnect(bool) exists because it allows for clean disconnect + reuse of the client.

**Comment by alexander-petuhov** [comment]
> Disconnect(bool) exists because it allows for clean disconnect + reuse of the client.

Hello. Does it mean that it's better to call Disconnect(true) before Dispose? For example
`using (var smptClient = .....`
{
.....
smptClient.Send..
...
smptClient.Disconnect(true);
}
or in case of manual dispose
....
smptClient.Send...
smptClient.Disconnect(true);
smptClient.Dispose();

**Comment by jstedfast** [comment]
@alexander-petuhov yes, ideally you should call Disconnect(true) before Dispose().
