### ISSUE TITLE
LocalEndPoint

### ISSUE THREAD

**Issue by shapemetrics** [jstedfast/MailKit#407]
How can you select the local IP Address (LocalEndPoint) it is located in MailService.cs. I am attempting to route traffic from specific IP addresses out the firewall for different TLDs.

**Comment by jstedfast** [comment]
Check out the docs on https://msdn.microsoft.com/en-gb/library/system.net.networkinformation.networkinterface.getallnetworkinterfaces(v=vs.110).aspx
