### ISSUE TITLE
Mail Message received Date  

### ISSUE THREAD

**Issue by truane** [jstedfast/MailKit#409]
Is it possible to get the latest date received from the email headers?

Received: from XXXXX1.com (10.10.10.1) by XXXXX1.com
 (10.10.10.1) with Microsoft SMTP Server (TLS) id 14.3.210.2; **Wed, 28 Sep
 2016 13:38:57 -0500**
Received: from XXXXX2.com (10.10.10.2) by XXXX2.com
 (10.10.10.2) with Microsoft SMTP Server id 14.3.210.2; Wed, 28 Sep 2016
 13:38:56 -0500
Received: from XXXXX3.com ([10.10.10.3]) by XXXXX3.com with
 Microsoft SMTPSVC(6.0.3790.4675);	 Wed, 28 Sep 2016 13:38:55 -0500
Received: from XXXXX4.com ([10.10.10.4]) by XXXXX4.com with
 Microsoft SMTPSVC(6.0.3790.4675);	 Wed, 28 Sep 2016 13:38:54 -0500
.....

**Comment by jstedfast** [comment]
Yes, but you'll have to at least locate the start of that date string yourself and then use MimeKit.DateUtils.TryParse() to parse it (or you can use DateTime[Offset]'s parse methods):

http://www.mimekit.net/docs/html/Overload_MimeKit_Utils_DateUtils_TryParse.htm
