### ISSUE TITLE
Bug on MailboxAddress.Parse

### ISSUE THREAD

**Issue by Sbaia** [jstedfast/MailKit#414]
I found a possible bug in MailboxAddress Parse class.
If the address has a name containing an email address, the parsing is failing.

`var str = "my_email_address@server.com <my_email_address@server.com>";

MimeKit.MailboxAddress add;
if (MimeKit.MailboxAddress.TryParse(str, out add))
{
}`

**Comment by jstedfast** [comment]
Of course that's failing, it isn't valid.

**Comment by Sbaia** [comment]
I know it's invalid, but I receive a lot of mail like this, from customers.

**Comment by jstedfast** [comment]
Have you tried submitting a bug report to the sending agent?

The problem with constantly forcing Well Written(tm) software (like MimeKit/MailKit) to have to work around Poorly Written(tm) software is that the standards for mail software just end up getting lower and lower to the point where we are obviously at now which is that any gobbledy gook is expected to work or it's blamed on the Well Written software for not accepting it.

There is no excuse for the sending agent software to be this broken.

Show me that you have submitted a bug report to them and I will look into what can be done in MimeKit to work around this issue.

MimeKit already has work-arounds for dozens of broken formatting issues that mail software sends. This is getting ridiculous. It's obviously a never-ending slew of garbage that mail software thinks it can get away with sending and the people writing this shitty software need to start being held accountable.

**Comment by Sbaia** [comment]
I did not want to debate, I understand your reasons. the System.Mail.Net.MailAddress parser accepts it, so I thought it was a mistake.
However, I will follow your advices.

**Comment by jstedfast** [comment]
I have a patch ready that I am willing to commit, but I want to start forcing people asking for workarounds to hold the authors of broken software accountable by filing bugs and demanding a fix from them as well.

**Comment by jstedfast** [comment]
A patch has been committed to MimeKit: https://github.com/jstedfast/MimeKit/commit/b4e93d9e1671af054e6de323ec18141b89be956e

Please, please, please submit a bug report to the software that is generating those broken addresses.

Help me make the world a better place.
