### ISSUE TITLE
Calling DKIM Sign 

### ISSUE THREAD

**Issue by shapemetrics** [jstedfast/MailKit#416]
I have an issue where I build the message in a function that returns a MimeMessage, Signs it in the calling function and hands it off to a function to send it.

I am not sure what is happening but if the code is in the same function the code works but in separate functions it fails.

Gmail reports:   dkim=neutral (body hash did not verify)  which also causes the Dmarc to fail. 

I have tested this multiple times and the only thing that seems to cause it are separate functions to handle sending from building the message.

**Comment by jstedfast** [comment]
I'll need to see some sample code that illustrates this problem.

**Comment by jstedfast** [comment]
I suspect the issue is on your end because I can't make this happen no matter how I split stuff up between functions.

**Comment by shapemetrics** [comment]
I have narrowed the problem down to the HTML content. Something is happening with it. When I use basic HTML with just html and body tags it is a problem. But once I utilize more complex HTML with an external image something goes wrong and the body hash is not valid.

**Comment by jstedfast** [comment]
That doesn't make any sense because the MimeMessage doesn't know anything about HTML.

**Comment by shapemetrics** [comment]
I would agree, however it may be from signing the body before wrapping the body.

**Comment by jstedfast** [comment]
Then you need to call `message.Prepare (EncodingConstraint.SevenBit)`

**Comment by shapemetrics** [comment]
That was the resolution. Thank you again!

**Comment by jstedfast** [comment]
no prob :)

**Comment by jstedfast** [comment]
What doc/docs did you read to figure out how to DKIM sign your message? I want to update the docs to make it make sure it is known to call Prepare() first.

**Comment by shapemetrics** [comment]
I found the documentation on stackoverflow and your unit tests.

Side note: I left you a little something under my wife's account on pledgie for the assistance. :)

**Comment by jstedfast** [comment]
Thanks, I was wondering if that was you :)

**Comment by jstedfast** [comment]
Looks like my StackOverflow answer did not mention the need for Prepare(), so I've just updated that. Thanks! I forgot I even had an answer on StackOverflow :)

**Comment by shapemetrics** [comment]
Maybe on the next release put that call within the signing function? It would eliminate the need for developers to make the call and less chance of errors like that.

**Comment by jstedfast** [comment]
Can't: https://github.com/jstedfast/MimeKit/issues/224

**Comment by shapemetrics** [comment]
I see. Interesting, I hadn't read through all the RFC's for it. I guess that I have some reading to do. 

It is really odd that they would not account for it. 

I had read that thread previously but did not see that it was related. :)

**Comment by jstedfast** [comment]
It's not really anything to do with RFCs, the problem is that DKIM does not understand message encodings, it operates on the final message stream after encoding has taken place.

Thus, if you change the encodings (because the SMTP server is more strict, for example), then the DKIM signature will break.

The problem described in that issue is as follows:

1. sender constructs a message
2. sender DKIM-signs the message for 8BITMIME transport
3. sender sends the signed message
4. message is delivered to intermediary transport which uses MimeKit to parse the message and then DKIM-sign it with the intermediary's key
5. intermediary sends the message along to the final recipient

If the DKIM `Sign()` method calls `Prepare (EncodingConstraint.SevenBit)`, then any MIME part with an encoding of `8bit` needs to be re-encoded to `base64` or `quoted-printable` in order to fit within the 7bit constraints and thus the signature of the original sender is broken.

**Comment by shapemetrics** [comment]
I seen that, but it would make a bit more sense for me to do research on why it was like that than to just say do it. I would have to understand the underlying rationale. It is clearly founded for a reason, just not what I thought originally.

I took my signing function and made it an extension method with the call directly in it, so I would not forget to call it before actually signing.

**Comment by jstedfast** [comment]
SMTP servers support 3 different constraints, depending on which SMTP server you use:

1. old SMTP servers only support 7bit encodings (hence the need for `base64` and `quoted-printable`)
2. newer SMTP servers support `8BITMIME` which means they support the `8bit` encoding. This means that 8bit text can be sent with a `Content-Transfer-Encoding` header with a value of `8bit`. This generally replaces the need for `quoted-printable`, but binary content must still be sent using `base64`.
3. the newest SMTP servers support `BINARYMIME` which means no encoding is needed, but this is very very rare in the wild.
