### ISSUE TITLE
Cant search in subject having "&" ampersand character.

### ISSUE THREAD

**Issue by jaysb1** [jstedfast/MailKit#419]
The search query having "&" ampersand character shows no result. Check below piece of code.
{
IMailFolder mailFolder = Client.GetFolder(Client.PersonalNamespaces[0]).GetSubfolder("[Gmail]").GetSubfolder("All Mail");
string PathSeparator = mailFolder.DirectorySeparator.ToString();
mailFolder.Open(FolderAccess.ReadOnly);
var query = SearchQuery.SubjectContains("test subject & test subject");
var uids = mailFolder.Search(query);
}

**Comment by jstedfast** [comment]
It shows no result because Google's text indexing doesn't handle the &, it has nothing to do with MailKit doing something wrong.
