### ISSUE TITLE
Reply gmail incorrect sent mail

### ISSUE THREAD

**Issue by tienvd1994** [jstedfast/MailKit#420]
http://www.mimekit.net/docs/html/FrequentlyAskedQuestions.htm#Reply

My email can't reply to email sent but it is create new email. Please help me.

**Comment by jstedfast** [comment]
That example does not handle HTML messages, it only works for plain-text emails. Quoting the body of an HTML message is a lot more complicated and depends a lot on how you decide you want to convert HTML into plain text.

**Comment by tienvd1994** [comment]
But I send plain-text email. You can suggest me parameter pass to Reply method of example http://www.mimekit.net/docs/html/FrequentlyAskedQuestions.htm#Reply

**Comment by jstedfast** [comment]
You'll have to give me an example.

**Comment by tienvd1994** [comment]
My code
public static void Reply(MimeMessage message, MailboxAddress from, bool replyToAll)
        {
            var reply = new MimeMessage();

            reply.From.Add(from);

            // reply to the sender of the message
            if (message.ReplyTo.Count > 0)
            {
                reply.To.AddRange(message.ReplyTo);
            }
            else if (message.From.Count > 0)
            {
                reply.To.AddRange(message.From);
            }
            else if (message.Sender != null)
            {
                reply.To.Add(message.Sender);
            }

            if (replyToAll)
            {
                // include all of the other original recipients (removing ourselves from the list)
                reply.To.AddRange(message.To.Mailboxes.Where(x => x.Address != from.Address));
                reply.Cc.AddRange(message.Cc.Mailboxes.Where(x => x.Address != from.Address));
            }

            // set the reply subject
            if (!message.Subject.StartsWith("Re:", StringComparison.OrdinalIgnoreCase))
                reply.Subject = "Re: " + message.Subject;
            else
                reply.Subject = message.Subject;

            // construct the In-Reply-To and References headers
            if (!string.IsNullOrEmpty(message.MessageId))
            {
                reply.InReplyTo = message.MessageId;
                foreach (var id in message.References)
                    reply.References.Add(id);
                reply.References.Add(message.MessageId);
                reply.MessageId = MimeUtils.GenerateMessageId("mail.gmail.com");
            }

            // quote the original message text
            using (var quoted = new StringWriter())
            {
                var sender = message.Sender ?? message.From.Mailboxes.FirstOrDefault();
                var name = sender != null ? (!string.IsNullOrEmpty(sender.Name) ? sender.Name : sender.Address) : "someone";

                quoted.WriteLine("On {0}, {1} wrote:", message.Date.ToString("f"), name);
                using (var reader = new StringReader(message.TextBody))
                {
                    string line;

                    while ((line = reader.ReadLine()) != null)
                    {
                        quoted.Write("> ");
                        quoted.WriteLine(line);
                    }
                }

                reply.Body = new TextPart("plain")
                {
                    Text = quoted.ToString()
                };
            }


            using (var client = new SmtpClient())
            {
                client.Connect("smtp.gmail.com", 465, SecureSocketOptions.SslOnConnect);
                client.Authenticate("tienvd1994@gmail.com", "password");
                client.Send(reply);
                client.Disconnect(true);
            }
        }
My controller pass parameter
[HttpPost]
        [ValidateAntiForgeryToken]
        public JsonResult SendReply(EmailReplyMeta emailReplyMeta)
        {
            var message = new MimeMessage();
            message.MessageId = emailReplyMeta.MessageId;
            message.ReplyTo.Add(new MailboxAddress("hoaihoai", "hoaittt3.94@gmail.com"));
            message.Subject = emailReplyMeta.Content;

            var builder = new BodyBuilder();

            builder.TextBody = "Set the html version of the message text";

            message.Body = builder.ToMessageBody();

            UtilEmail.Reply(message, new MailboxAddress("tienvd", "tienvd1994@gmail.com"), false);

            return Json(1);
        }

**Comment by jstedfast** [comment]
Works fine for me...

```csharp
using System;
using System.IO;
using System.Linq;

using MimeKit;
using MimeKit.Utils;

namespace TestCase {
	class Program
	{
		static void Main ()
		{
			var message = new MimeMessage ();
			message.MessageId = MimeUtils.GenerateMessageId ();
			message.ReplyTo.Add (new MailboxAddress ("hoaihoai", "hoaittt3.94@gmail.com"));
			message.Subject = "This is the subject.";
			
			var builder = new BodyBuilder ();
			
			builder.TextBody = "Set the html version of the message text";
			
			message.Body = builder.ToMessageBody ();

			Reply (message, new MailboxAddress ("tienvd", "tienvd1994@gmail.com"), false);
		}

		static void Reply (MimeMessage message, MailboxAddress from, bool replyToAll)
		{
			var reply = new MimeMessage ();
			
			reply.From.Add (from);
			
			// reply to the sender of the message
			if (message.ReplyTo.Count > 0)
				reply.To.AddRange (message.ReplyTo);
			else if (message.From.Count > 0)
				reply.To.AddRange (message.From);
			else if (message.Sender != null)
				reply.To.Add (message.Sender);

			if (replyToAll) {
				// include all of the other original recipients (removing ourselves from the list)
				reply.To.AddRange (message.To.Mailboxes.Where (x => x.Address != from.Address));
				reply.Cc.AddRange (message.Cc.Mailboxes.Where (x => x.Address != from.Address));
			}

			// set the reply subject
			if (!message.Subject.StartsWith ("Re:", StringComparison.OrdinalIgnoreCase))
				reply.Subject = "Re: " + message.Subject;
			else
				reply.Subject = message.Subject;

			// construct the In-Reply-To and References headers
			if (!string.IsNullOrEmpty (message.MessageId)) {
				reply.InReplyTo = message.MessageId;
				foreach (var id in message.References)
					reply.References.Add (id);
				reply.References.Add (message.MessageId);
				reply.MessageId = MimeUtils.GenerateMessageId ("mail.gmail.com");
			}

			// quote the original message text
			using (var quoted = new StringWriter ()) {
				var sender = message.Sender ?? message.From.Mailboxes.FirstOrDefault ();
				var name = sender != null ? (!string.IsNullOrEmpty (sender.Name) ? sender.Name : sender.Address) : "someone";
				
				quoted.WriteLine ("On {0}, {1} wrote:", message.Date.ToString ("f"), name);
				using (var reader = new StringReader (message.TextBody)) {
					string line;

					while ((line = reader.ReadLine()) != null) {
						quoted.Write ("> ");
						quoted.WriteLine (line);
					}
				}

				reply.Body = new TextPart ("plain") {
					Text = quoted.ToString ()
				};
			}

			reply.WriteTo (Console.OpenStandardOutput ());
		}
	}
}
```

Output:

```
From: tienvd <tienvd1994@gmail.com>
Date: Tue, 08 Nov 2016 10:25:23 -0500
Subject: Re: This is the subject.
Message-Id: <MJRJ90DIPZT4.AHXANBPWFVN71@mail.gmail.com>
To: hoaihoai <hoaittt3.94@gmail.com>
In-Reply-To: <63NF90DIPZT4.IHAE005807I63@Jeffreys-Air>
References: <63NF90DIPZT4.IHAE005807I63@Jeffreys-Air>
MIME-Version: 1.0
Content-Type: text/plain; charset=utf-8

On Tuesday, November 8, 2016 10:25 AM, someone wrote:
> Set the html version of the message text
```

**Comment by jstedfast** [comment]
What did you expect it to send?

**Comment by tienvd1994** [comment]
It is always send at status "new" email. I want email reply like of Gmail.
![image-reply](https://cloud.githubusercontent.com/assets/16608342/20106150/bca78626-a606-11e6-84cb-81f576d87885.JPG)

**Comment by jstedfast** [comment]
Can you do some research and figure out what the difference is between a reply generated by MimeKit and one generated by GMail that makes it not get added to GMail's conversation thread and report back to me? Thanks.
