### ISSUE TITLE
ASP.NET Core + Amazon SES: The remote certificate is invalid according to the validation procedure.

### ISSUE THREAD

**Issue by mdmoura** [jstedfast/MailKit#421]
Hello,

I am trying to send email using ASP.NET Core, MailKit and Amazon SES:

      using (SmtpClient client = new SmtpClient(new ProtocolLogger("smtp.log"))) {
          client.Connect("email-smtp.us-east-1.amazonaws.com", 587, SecureSocketOptions.StartTls);
          client.Authenticate("myusername", "mypassword");
          await client.SendAsync(message);
          client.Disconnect(true);
      }

I keep getting the error "The remote certificate is invalid according to the validation procedure.".

And the log file shows:

    Connected to smtp://email-smtp.us-east-1.amazonaws.com:587/?starttls=always
    S: 220 email-smtp.amazonaws.com ESMTP SimpleEmailService-1737464811 qt5bXhIgVseJaHPspjp4
    C: EHLO [127.0.0.1]
    S: 250-email-smtp.amazonaws.com
    S: 250-8BITMIME
    S: 250-SIZE 10485760
    S: 250-STARTTLS
    S: 250-AUTH PLAIN LOGIN
    S: 250 Ok
    C: STARTTLS
    S: 220 Ready to start TLS

What am I missing?

Thank You,
Miguel

**Comment by jstedfast** [comment]
You need to provide your own `client.ServerCertificateValidationCallback` method to verify the server certificate. It can be as simple as always returning true or it can check the fingerprint against a known fingerprint for the server or any number of other possibilities.

For more information, see http://www.mimekit.org/docs/html/P_MailKit_MailService_ServerCertificateValidationCallback.htm

**Comment by h3smith** [comment]
@jstedfast  didn't have to do that on our end. We are using IAM credentials (name+password) to send via AWS SES: 

```
            try
            {
                using (var client = new SmtpClient())
                {
                    client.Connect(host, port, tls);

                    //client.AuthenticationMechanisms.Remove("XOAUTH2");

                    // Note: only needed if the SMTP server requires authentication
                    client.Authenticate(username, password);

                    client.Send(message);
                    client.Disconnect(true);
                }

                return "Message Sent Succesfully";
            }
            catch (Exception e)
            {
                return @"ERROR: " + e.Message.ToString();
            }
```

Is working where TLS = StartTlsWhenAvailable

**Comment by BrettStrongEH** [comment]
Thanks @h3smith ... your solution solved my issue also.
