### ISSUE TITLE
Is it possible to get specific parts of a pop3 message using getmessageheaders??

### ISSUE THREAD

**Issue by shomarisharpe** [jstedfast/MailKit#423]
Hi,
i want my app to just get the messageid, subject, date server received mail and attachment names, sizes from a pop3client. Is this possible or do i have to revert to using GetMessage and then process the message?

**Comment by jstedfast** [comment]
If you call `GetHeaders()`, you'll get back the complete set of message headers which will include the `Message-Id`, `Subject`, `Date`, and `Received` headers.

It will not include attachment file names or the size of the message.

To get the size of the message, use the `GetMessageSize()` method.

If you need attachment file names, you'll need to use `GetMessage()`. POP3 does not support getting attachment file names without downloading the entire message.

**Comment by shomarisharpe** [comment]
Wow this means i really have to download all messages from the server again and again. Would you recommend putting messages in a sqlite database and checking message-id's against the database?

**Comment by jstedfast** [comment]
If your server supports the UIDL extension, you can safely just track the UIDs of the messages you've already downloaded (stick them in a database?).

If your server does *not* support UIDL, then yea, you'll probably have to use `GetHeaders()` to somehow figure out if you've already downloaded a message or not.

I would warn against using `Message-Id` alone as there's nothing stopping 2 messages from having an identical `Message-Id` header. Should be rare if legitimate, but does not stop someone from purposely crafting a message with an identical `Message-Id` to confuse client software.

**Comment by shomarisharpe** [comment]
I see. So how do i get these UIDL's and could i see a short example? Could it be something like the following algo:

if (pop3client.capabilities.hasflag(UIDL)
{
    var uidls = pop3client.getUIDLS();
    var messages = pop3client.getmessages(uidls)
    foreach (var message in messages) {
        //1. store the message uidl, body, subject
        //2. store the attachments
    }
} else {
     var messages = pop3client.getmessages(0);
      foreach(var message in messages) {
             //1. store the message md5(message-id + date timestamp) , body, subject
             //2. store the attachments
         }
     }
}

**Comment by jstedfast** [comment]
It could be pretty much exactly like your code snippet. The beauty of C# IDE's is that they offer code completion to make finding the proper APIs easy :)

```csharp
if (pop3client.Capabilities.HasFlag (Pop3Capabilities.Uidl))
```

```csharp
var uids = pop3client.GetMessageUids ();
```

You need to still call `GetMessage()` based on the index, but you can index into the `uids` array to get the UID string to check against your database before calling it.

**Comment by jstedfast** [comment]
http://www.mimekit.net/docs/html/M_MailKit_Net_Pop3_Pop3Client_GetMessageUids.htm even has a sample code snippet to illustrate how to use it :)

**Comment by shomarisharpe** [comment]
Thanks for the speedy responses. I'm glad i threw out my earlier implementation (not using mailkit). Good work bro.

**Comment by jstedfast** [comment]
I've written multiple email clients professionally so I know all of the ins and outs :)
