### ISSUE TITLE
saving and loading messages to disk

### ISSUE THREAD

**Issue by beppe9000** [jstedfast/MailKit#425]
I would like to have a local cache of emails so I wanted to ask if there is some method to save/load a message as eml, mbs or any other format.

**Comment by jstedfast** [comment]
Yes. See http://www.mimekit.net/docs/html/Overload_MimeKit_MimeMessage_WriteTo.htm and http://www.mimekit.net/docs/html/Overload_MimeKit_MimeMessage_Load.htm

**Comment by beppe9000** [comment]
wew thanks, i was looking for "Save" so I completely missed it ;)
