### ISSUE TITLE
Window Server 2012:Authentication Failed 

### ISSUE THREAD

**Issue by anhlee24** [jstedfast/MailKit#429]
- I have a problem on window server 2012.
- I am used Gmail, port 587. 
- Username/Password have tested on local, its working properly. But when i run on window server 2012, its always show "Authentication Failed" error.
- I have also open port 587 (Inbound, Outbound)

Do you have any suggest? Thank you.

**Comment by jstedfast** [comment]
So you are running an app on Windows Server 2012 and connecting to smtp.gmail.com:587 using MailKit.Net.Smtp.SmtpClient and you get an `AuthenticationException` when doing `client.Authenticate(username, password);`?

What does the protocol log say?

**Comment by anhlee24** [comment]
Hi,

Thanks for your reply.
I have found the solution. 
-Because i have used Gmail, its working fine on my PC becasue of i have logined Gmail on this PC. 
- On the VPS, i have to login again to let Gmail know that this is me. 
The reason is because of Gmail authentication rule.

Thanks again :)

**Comment by jstedfast** [comment]
Okay, cool.

**Comment by kshyju** [comment]
I am experiencing the same issue when i deploy the code to an azure website. Works fine when i run it locally!. I enabled "Access to Less secure apps" in my gmail security settings. Any thoughts @jstedfast ?

**Comment by anhlee24** [comment]
@kshyju 

With VPS, i can open the browser, login and verify to allow access with my VPS IP address. I think you can contact with Azure support. I have not working with Azure before so i can not suggest more idea.
