### ISSUE TITLE
.net core 1.1 ImapClient.connect() throws An unhandled exception of type 'System.ExecutionEngineException' occurred in System.Private.CoreLib.ni.dll

### ISSUE THREAD

**Issue by CodeDoctor34** [jstedfast/MailKit#431]
I recently updated my .net core 1.0 app to 1.1 and found that it is no longer working with MailKit. When I attempt client.Connect(MailServer, Port, SSL) it throws "An unhandled exception of type 'System.ExecutionEngineException' occurred in System.Private.CoreLib.ni.dll"

**Comment by jstedfast** [comment]
Sounds like a duplicate of https://github.com/dotnet/corefx/issues/13814
