### ISSUE TITLE
Fetching return wrong results when server send flags update

### ISSUE THREAD

**Issue by ChenMachluf** [jstedfast/MailKit#435]
Hi,
I used the `ImapFolder.Fetch` and realized that sometimes I get too much results.
It seems that this occurs when the imap server send flag updates , it get handled by the ImapCommand of the fetching.
Meanwhile I check on my side and remove the unwanted summaries.
Log:

> C: E00000030 UID FETCH 34274:34300 (UID FLAGS INTERNALDATE RFC822.SIZE)
S: * 9941 FETCH (UID 34274 RFC822.SIZE 60593 .................
S: * 9942 FETCH (UID 34275 RFC822.SIZE 15602 .................
S: * 9943 FETCH (UID 34276 RFC822.SIZE 93329 .................
S: * 9944 FETCH (UID 34277 RFC822.SIZE 103569 .................
S: * 9945 FETCH (UID 34278 RFC822.SIZE 14511 .................
S: * 9946 FETCH (UID 34279 RFC822.SIZE 45827 .................
S: * 9947 FETCH (UID 34280 RFC822.SIZE 11467 .................
S: * 9948 FETCH (UID 34281 RFC822.SIZE 44040 .................
S: * 9949 FETCH (UID 34282 RFC822.SIZE 7988 .................
S: * 9950 FETCH (UID 34283 RFC822.SIZE 61967 .................
S: * 9951 FETCH (UID 34284 RFC822.SIZE 23700 .................
S: * 9952 FETCH (UID 34288 RFC822.SIZE 6010 .................
S: * 9953 FETCH (UID 34289 RFC822.SIZE 77416 .................
S: * 9954 FETCH (UID 34291 RFC822.SIZE 62463 .................
S: * 9955 FETCH (UID 34292 RFC822.SIZE 7988 .................
S: * 9956 FETCH (UID 34293 RFC822.SIZE 18832 .................
S: * 9957 FETCH (UID 34297 RFC822.SIZE 10516 .................
S: * 9958 FETCH (UID 34298 RFC822.SIZE 80717 .................
S: * 9959 FETCH (UID 34299 RFC822.SIZE 12205 .................
S: * 9960 FETCH (UID 34300 RFC822.SIZE 15591 .................
S: * 13315 FETCH (UID 39553 MODSEQ (2272449) FLAGS (\Answered))
S: E00000030 OK Success

**Comment by jstedfast** [comment]
This isn't a bug, it's just the way IMAP works.

**Comment by ChenMachluf** [comment]
Yeah , i know ...
Just when the `ImapEngine` have a active `ImapCommand` , like when u do Fetch.
The `ImapCommand`  handle this imap event cuz it registered to the Fetch atom.
So , the Fetch command get "wrong results" then what we ask for ,
and the `ImapFolder` didnt get the message  , so no events raised for `MessageFlagsChanged` , `MessageLabelsChanged` and `ModSeqChanged` . 

I know its really a edge case , but maybe we can fix it.
I will be happy to try fix it in a smooth way , if u think it worth it.

**Comment by jstedfast** [comment]
The only solutions to this that I can think of would have a potentially large performance hit due to having to check if the Index or UID is in the list of requested IDs.
