### ISSUE TITLE
Attachment is followed by CRLF in some cases

### ISSUE THREAD

**Issue by ParanoikCZE** [jstedfast/MailKit#436]
Sending body with singleline attachment containing non UTF characters ends with unexpected CRLF in the end.

STR:
create txt file and insert e.g. "123", save it and attach into message => "123\r\n" is encoded

notes:
When there is any UTF character, CRLF is not added.
When there are more than single line, CRLF is not added.

**Comment by jstedfast** [comment]
Can you write me up a test case so I can be sure I know exactly what you are seeing?

**Comment by ParanoikCZE** [comment]
Just quick one .. 

        [TestCase("123", TestName = "Test7BitSingleLineAttachment")]
        [TestCase("123\r\n", TestName = "Test7BitMultiLineAttachment")]
        private void Test7BitAttachment(string filecontent)
        {
            var builder = new BodyBuilder();

            builder.Attachments.Add("filename", new MemoryStream(Encoding.UTF8.GetBytes(filecontent)));

            var body = builder.ToMessageBody();
            
            var bodyparts = body.ToString().Split(new string[] 
                { "\r\n--" + body.ContentType.Boundary, "--\r\n" }, StringSplitOptions.RemoveEmptyEntries);
            var content = bodyparts[bodyparts.Length - 1];
            
            Assert.True(content.EndsWith(filecontent));
        }

**Comment by jstedfast** [comment]
Thanks. This is fixed now. I probably won't be making a new release until Jan/Feb 2017, though, so in the meantime your best bet will be to encode the attachment using base64.
