### ISSUE TITLE
MailKit - Attachment From Stream

### ISSUE THREAD

**Issue by Shadowman4205** [jstedfast/MailKit#438]
I am using epplus with Memory stream to download excel. Now i want use this stream in attachment can i? i cannot find any example about this.
is there any working example like this
> builder.Attachments.Add(stream,"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",  "Report.xlsx" );

**Comment by jstedfast** [comment]
What you can do is something like this:

```csharp
builder.Attachments.Add ("Report.xslx", stream);
```

or (if the above code doesn't get the correct mime-type)

```csharp
builder.Attachments.Add ("Report.xslx", stream, new ContentType ("application", "vnd.openxmlformats-officedocument.spreadsheetml.sheet"));
```

Just be careful not to dispose the stream until after you have sent the message.

**Comment by Shadowman4205** [comment]
Thank you very much, it does work. i was giving the parameters in wrong way.
