### ISSUE TITLE
Disable Attachment logging from ProtocolLogger

### ISSUE THREAD

**Issue by jaggata** [jstedfast/MailKit#439]
Hi, a suggestion for a future feature : i find the ProcotolLogger availability extremely useful, but i think it would be desirable to have an on/off flag in order to enable/disable attachment logging.

I achieved the same Behavior by implementing a new ProtocolLogger based on the code of the original one, but the final solution is somewhat tricky and i guess a neat solution requires to modify all the calls to the Write methods that in turn call the LogClient method.

**Comment by jstedfast** [comment]
The ProtocolLogger is just a log of exactly what is sent across the wire and at the point where it is logged, it has no context to know if something is an attachment or not.

This is not something that can be done.
