### ISSUE TITLE
body text reading

### ISSUE THREAD

**Issue by yasartopuk** [jstedfast/MailKit#44]
hi,

How do I read mail in the body as a string..

``` csharp
using (var client = new ImapClient())
{
    var credentials = new NetworkCredential("a@a.com", "xxx");
    var uri = new Uri("imaps://imap.gmail.com");

    using (var cancel = new CancellationTokenSource())
    {
        try
        {
            client.Connect(uri, cancel.Token);
            client.Authenticate(credentials, cancel.Token);

            var sent = client.GetFolder(SpecialFolder.Sent);
            sent.Open(FolderAccess.ReadOnly, cancel.Token);

            var query = SearchQuery.DeliveredAfter(Convert.ToDateTime("01-01-2014"));

            foreach (var uid in sent.Search(query, cancel.Token))
            {
                var message = sent.GetMessage(uid, cancel.Token);

                string mailUid = uid.ToString();
                string mailTo = message.To.ToString();
                string mailCc = message.Cc.ToString();
                string mailSubject = message.Subject;
                string mailDate = message.Date.ToString("yyyy-MM-dd HH:mm:ss");
                string mailMessageId = message.MessageId;

                txtMessages.Text = message.BodyParts.ToString(); 
            }

        }
        catch (Exception)
        {
            throw;
        }

        client.Disconnect(true, cancel.Token);
    }
}
```

**Comment by kennepal** [comment]
var body = msg.BodyParts.OfType<TextPart>().FirstOrDefault(x => x.ContentType.Matches("text", "html"));

Gives error:
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1061	'ContentType' does not contain a definition for 'Matches' and no extension method 'Matches' accepting a first argument of type 'ContentType' could be found (are you missing a using directive or an assembly reference?)

**Comment by jstedfast** [comment]
The Matches() method was renamed to [IsMimeType()](http://www.mimekit.net/docs/html/M_MimeKit_ContentType_IsMimeType.htm).

**Comment by AsadGilani** [comment]
TextPart textPart = new TextPart();
textPart.Text = body; // body contains the html text.
if(textPart.IsHtml)
{
}else { } 

textPart.IsHtml is not giving me the correct result.I know my body text contains HTML but still it goes in else condition.

Then I look into this conversation but when i wrote it. It gives error on ContentType.
char does not contains the information of contentType.
var bodyii = textPart.Text.FirstOrDefault(x => x.ContentType.IsMimeType("text", "html"));
Can anyone point out what i am doing wrong ?

**Comment by jstedfast** [comment]
`textPart.IsHtml` doesn't examine the `textPart.Text` to see if it contains html tags, it examines the `textPart.ContentType` to see if it matches `text/html`. When you create a `TextPart` using the default constructor, it creates `text/plain`, not `text/html`.

You need to use: `TextPart textPart = new TextPart ("html");`

**Comment by AsadGilani** [comment]
Is there any way that could automate that the text is coming is HTML or plain text. ?
I mean I don't need to create the text part based on the content otherwise I need to pass the extra parameter that will tell it is HTML or plain and based on that I need to create the text part.

**Comment by jstedfast** [comment]
Then you need to write code to detect what it is yourself.

**Comment by AsadGilani** [comment]
@jstedfast: Thanks for your reply.

**Comment by Conscious-z-order4** [comment]
i confirmed the answer https://lnkr.fun/41117d7
