### ISSUE TITLE
Make IsAuthenticated usable in tests

### ISSUE THREAD

**Issue by SeanFarrow** [jstedfast/MailKit#440]
Hi,

I'm using MailKit quite happily, although the only thing I've noticed is that IsAuthenticated is declared on the MailService class rather than the IMailService interface, would you consider declaring it on the latter, instead? That way it could be mocked for testing. Currently I'm taking an IMailTransport in, due to the fact that I'm using DI and sending messages, so mocking the IsAuthenticated method would be super useful. I'm happy to do the work and submit a pr if this would be useful?
Cheers
Sean.
the

**Comment by jstedfast** [comment]
Thanks. I didn't realize it wasn't already on IMailService. I've just added it :)

**Comment by SeanFarrow** [comment]
Any idea when this might land on NuGet?
