### ISSUE TITLE
Exception on HtmlTagCallback ctx.WriteTag

### ISSUE THREAD

**Issue by juansh20** [jstedfast/MailKit#441]
I use HtmlPreviewVisitor.css class when messages have images, I have a exception about tag parameter name in some messages.

Class: HtmlPreviewVisitor.css

Method:
```csharp
 void HtmlTagCallback(HtmlTagContext ctx, HtmlWriter htmlWriter)
        {
            try
            {
                // pass the tag through to the output
                if (ctx.TagId == HtmlTagId.Image && !ctx.IsEndTag && stack.Count > 0)
                {
                    ctx.WriteTag(htmlWriter, false);

                    // replace the src attribute with a file:// URL
                    foreach (var attribute in ctx.Attributes)
                    {
                        if (attribute.Id == HtmlAttributeId.Src)
                        {
                            MimePart image;
                            string url;

                            if (!TryGetImage(attribute.Value, out image))
                            {
                                htmlWriter.WriteAttribute(attribute);
                                continue;
                            }

                            url = SaveImage(image, attribute.Value);

                            htmlWriter.WriteAttributeName(attribute.Name);
                            htmlWriter.WriteAttributeValue(url);
                        }
                        else
                        {
                            htmlWriter.WriteAttribute(attribute);
                        }
                    }
                }
                else if (ctx.TagId == HtmlTagId.Body && !ctx.IsEndTag)
                {
                    ctx.WriteTag(htmlWriter, false);

                    // add and/or replace oncontextmenu="return false;"
                    foreach (var attribute in ctx.Attributes)
                    {
                        if (attribute.Name.ToLowerInvariant() == "oncontextmenu")
                            continue;

                        htmlWriter.WriteAttribute(attribute);
                    }

                    htmlWriter.WriteAttribute("oncontextmenu", "return false;");
                }
                else
                {
                    ctx.WriteTag(htmlWriter, true); //Error line
                }
            }
            catch (Exception ex)
            {

            }
```

exception:
"Invalid tag name.\r\nNombre del parámetro: name"

Trace:
 en MimeKit.Text.HtmlWriter.ValidateTagName(String name)
   en MimeKit.Text.HtmlWriter.WriteStartTag(String name)
   en MimeKit.Text.HtmlTagContext.WriteTag(HtmlWriter htmlWriter, Boolean writeAttributes)
   en HtmlPreviewVisitor.HtmlTagCallback(HtmlTagContext ctx, HtmlWriter htmlWriter)

htmlWriter contains:

<style>table.customTableClassName {margin-bottom: 10px;border-collapse: collapse;display: table;}.customTableClassName td, .customTableClassName th {border: 1px solid #ddd;}</style><div id="write-custom-write" style="font-size: 14px; font-family: &#23435;&#20307;;"><p style="margin:0px;">Dear Maryuri,</p><p style="margin:0px;"><br/></p><p style="margin:0px;">Good day!<br/><br/></p><p style="margin:0px;">Sorry for my late reply!&#160;</p><p style="margin:0px;"><br/></p><p style="margin:0px;">cnee information on MBL is ok,other information should confirm by your side,thanks!</p><p style="margin:0px;"><br/></p><p style="margin:0px;">I have sent HBL to actual cnee today,but have not reply,i would try to contact tomorrow.</p><p style="margin:0px;"><br/></p><p style="margin:0px;"><br/></p><br/></div><div id="write-custom-signature"><div style="FONT-FAMILY: 'Times New Roman'; COLOR: rgb(0,0,0); FONT-SIZE: 14px">Tks &amp; Best Rgds<br/>Yuki Rao</div><div style="FONT-FAMILY: 'Times New Roman'; COLOR: rgb(0,0,0); FONT-SIZE: 14px"><span style="LINE-HEIGHT: 24px"><span style="FONT-FAMILY: ; FONT-SIZE: 10px">Branch&#160;Manager</span></span><br/>TRANS-CHINA LOGISTICS CO.,LTD.SHENZHEN BRANCH</div><div style="FONT-FAMILY: 'Times New Roman'; COLOR: rgb(0,0,0); FONT-SIZE: 14px">29E ,DAQING BUILDING ,NO.6027,SHENNAN ROAD,FUTIAN DISTRICT ,SHENZHEN<br/><span style="FONT-FAMILY: Times New Roman; COLOR: black; FONT-SIZE: 15px"><span style="FONT-FAMILY: Times New Roman; COLOR: black; FONT-SIZE: 15px"><span style="FONT-FAMILY: Times New Roman; FONT-SIZE: 14px; FONT-WEIGHT: bold">&#22320;&#22336;:&#28145;&#22323;&#24066;&#31119;&#30000;&#21306;&#28145;&#21335;&#22823;&#36947;6027&#21495;&#22823;&#24198;&#22823;&#21414;29E</span></span></span><br/>Tel:0086-755-83252302 Fax:0086-755-82974649<br/>E-mail:sz-cus10@trans-china.com</div><div style="FONT-FAMILY: 'Times New Roman'; COLOR: rgb(0,0,0); FONT-SIZE: 14px">Skype:tc-szmarket01<br/><a style="MARGIN-TOP: 0px; FONT-FAMILY: Times New Roman; MARGIN-BOTTOM: 0px; FONT-SIZE: 14px" href="http://www.trans-china.com/">http://www.trans-china.com</a></div><div style="COLOR: rgb(0,0,0)"><div style="COLOR: rgb(0,0,0); FONT-SIZE: 15px; FONT-WEIGHT: normal"><span style="COLOR: rgb(0,0,0)"><span style="FONT-WEIGHT: bold"><span style="FONT-FAMILY: ; FONT-SIZE: 10px; FONT-WEIGHT: normal">Office:Xiamen,Shanghai,Shenzhen,Qingdao,Ningbo</span></span></span></div><div style="COLOR: rgb(0,0,0); FONT-SIZE: 15px; FONT-WEIGHT: normal"><span style="COLOR: rgb(0,0,0)"><span style="FONT-FAMILY: Times New Roman"></span></span></div><div style="COLOR: rgb(0,0,0); FONT-WEIGHT: normal"><span style="COLOR: rgb(0,0,0); FONT-SIZE: 15px"><span style="FONT-SIZE: 13px; FONT-WEIGHT: normal"><div style="FONT-SIZE: 15px"><span style="COLOR: rgb(0,0,0)"><span style="FONT-FAMILY: Times New Roman"></span></span></div><div style="FONT-SIZE: 15px"><span style="COLOR: rgb(0,0,0)"><strong><span style="FONT-FAMILY: Times New Roman"><span style="COLOR: blue"><span style="FONT-FAMILY: Times New Roman; COLOR: blue; FONT-SIZE: 14px; FONT-WEIGHT: normal"><span style="FONT-FAMILY: Times New Roman; FONT-SIZE: 14px; FONT-WEIGHT: normal">Go Green.</span> </span></span><span style="COLOR: green; FONT-SIZE: 12px"><span style="FONT-FAMILY: Times New Roman; COLOR: green; FONT-SIZE: 14px; FONT-WEIGHT: normal">Don&#39;t print this e-mail unless it&#39;s really necessary.</span></span></span></strong></span></div></span></span></div></div><div style="COLOR: rgb(0,0,0)">&#160;</div><p style="margin:0px;"><br/></p></div><div style="padding:5px;padding-left:0px;border-top:solid #999 1.0pt;font-family: arial; font-size:12px;margin-bottom:20px;"><p style="margin:0px;"><strong>From:</strong> &quot;Phoebe Chen &lt;market14@trans-china.com&gt;&quot;</p><p style="margin:0px;"><strong>To:</strong> &quot;Maryuri Ramirez - EZ Ship &lt;mramirez@ezship.pe&gt;Maryuri Ramirez - EZ Ship &lt;mramirez@ezship.pe&gt;&quot;,&quot;sz-cus10@trans-china.com &lt;sz-cus10@trans-china.com&gt;&quot;</p><p style="margin:0px;"><strong>CC:</strong> &quot;Luz &#160; Solano &lt;lsolano@ezship.pe&gt;&quot;,&quot;Claudia &#160;Tipiani Delgado &lt;ctipiani@ezship.pe&gt;&quot;,&quot;MIKE &lt;sz-cus09@trans-china.com&gt;&quot;</p><p style="margin:0px;"><strong>Sent:</strong> 2016-12-20 23:11</p><p style="margin:0px;"><strong>Subject:</strong> Re:Re: NEW SHIPMENT FROM CALLAO TO HONG KONG - REF: &#160;EZ493/1116</p></div><p style="margin:0px;">Dear Yuki</p><div><br/></div><div>Kindly help check again and revert,tks.<br/><br/><br/><br/><br/><div class="sign-app-type">PHOEBE</div></div><p style="margin:0px;"><br/><br/>----- Original Message -----<br/>From:Maryuri Ramirez - EZ Ship &lt;mramirez@ezship.pe&gt;Maryuri Ramirez - EZ Ship</p>

**Comment by jstedfast** [comment]
The problem is probably that the text you are feeding it is not valid HTML.
