### ISSUE TITLE
BlackList

### ISSUE THREAD

**Issue by Bobruk** [jstedfast/MailKit#443]
How to add an email sender to blacklist using IMAP?

**Comment by jstedfast** [comment]
IMAP does not know anything about black lists.

**Comment by Bobruk** [comment]
Maybe spam-list?

**Comment by jstedfast** [comment]
IMAP is just mail storage, it doesn't know anything about spam filtering.

**Comment by Bobruk** [comment]
And POP3? Or SMTP?

**Comment by jstedfast** [comment]
Nope. They don't know anything about spam either.

Spam filtering is generally done on the client side after the message(s) have been downloaded.

**Comment by Bobruk** [comment]
Thank you :)
