### ISSUE TITLE
send attachement from array

### ISSUE THREAD

**Issue by user373721** [jstedfast/MailKit#445]
I am testing .Net Core MVC, which does not support System.Net.Mail, Mailkit, works well but can't figure out how to send attachments that I have stored in my database as binary. I used the following in MVC 5:
```
var mail = new MailMessage();
     mail.Attachments.Add(new Attachment(new MemoryStream(attachment), 
     attachmentName, attachmentType));
```
I would appreciate your suggestions. Thank you

**Comment by jstedfast** [comment]
This is probably the easiest solution:

```csharp
var message = new MimeMessage ();
var builder = new BodyBuilder ();

builder.Attachments.Add (attachmentName, attachment, ContentType.Parse (attachmentType));

message.Body = builder.ToMessageBody ();
```

This assumes that `attachmentName` and `attachmentType` are strings while `attachment` is a `byte[]`.

**Comment by user373721** [comment]
Thank you

**Comment by caocuongccc** [comment]
Thank man!
