### ISSUE TITLE
Mailkit stop working.

### ISSUE THREAD

**Issue by PoulErikDK** [jstedfast/MailKit#447]
smtp.gmail.com return an empty string after the mail is sent and my app stop showing a blank page:
you can try https://parogsingler.dk/Home/Kontakt
Stopping at https://parogsingler.dk/Home/SendEmailAsync
My code:
 using (var client = new SmtpClient())
            {
                var credentials = new NetworkCredential
                {
                    UserName = "admin@parogsingler.dk", // replace with valid value
                    Password = "xxxxxx" // replace with valid value
                };
                client.LocalDomain = "parogsingler.dk";
                // check your smtp server setting and amend accordingly:
                client.Connect("smtp.gmail.com", 587, SecureSocketOptions.Auto);
                client.AuthenticationMechanisms.Remove("XOAUTH2");
                await client.AuthenticateAsync(credentials);
                await client.SendAsync(emailMessage).ConfigureAwait(false);
                await client.DisconnectAsync(true).ConfigureAwait(false);

                RedirectToAction("Thanks");
            }
Do you have any clues about this?
Regards,
Poul Erik

**Comment by jstedfast** [comment]
You might be getting an exception. You'll need to figure out what exception that is and based on that figure out what the problem is.

I can't see what exception your ASP.NET code is getting so I can't debug it.

**Comment by PoulErikDK** [comment]
Hello,
Nope, I doesn't get any exception so I tried smtp-mail.outlook.com and get these exceptions:

MailKit.Net.Smtp.SmtpClient.ProcessMailFromResponse(MimeMessage message, MailboxAddress mailbox, SmtpResponse response)
MailKit.Net.Smtp.SmtpClient.FlushCommandQueue(MimeMessage message, MailboxAddress sender, IList<MailboxAddress> recipients, CancellationToken cancellationToken)
MailKit.Net.Smtp.SmtpClient.Send(FormatOptions options, MimeMessage message, MailboxAddress sender, IList<MailboxAddress> recipients, CancellationToken cancellationToken, ITransferProgress progress)
MailKit.Net.Smtp.SmtpClient.Send(FormatOptions options, MimeMessage message, CancellationToken cancellationToken, ITransferProgress progress)
MailKit.MailTransport.Send(MimeMessage message, CancellationToken cancellationToken, ITransferProgress progress)
MailKit.MailTransport+<>c__DisplayClass2_0.<SendAsync>b__0()
System.Threading.Tasks.Task.Execute()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
ParOgSingler.dk.Controllers.HomeController+<SendEmailAsync>d__4.MoveNext() in HomeController.cs

                    await client.SendAsync(emailMessage).ConfigureAwait(false);

System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

**Comment by jstedfast** [comment]
This is the source code for `ProcessMailFromResponse()`, which is where your StackTrace suggests the exception is being thrown from:

```csharp
void ProcessMailFromResponse (MimeMessage message, MailboxAddress mailbox, SmtpResponse response)
{
	switch (response.StatusCode) {
	case SmtpStatusCode.Ok:
		OnSenderAccepted (message, mailbox, response);
		break;
	case SmtpStatusCode.MailboxNameNotAllowed:
	case SmtpStatusCode.MailboxUnavailable:
		OnSenderNotAccepted (message, mailbox, response);
		break;
	case SmtpStatusCode.AuthenticationRequired:
		throw new ServiceNotAuthenticatedException (response.Response);
	default:
		throw new SmtpCommandException (SmtpErrorCode.UnexpectedStatusCode, response.StatusCode, response.Response);
	}
}
```

This means that you are probably getting either `ServiceNotAuthenticatedException` (which means that the SMTP server thinks you are not authenticated for some reason) -or- the SMTP server returned an unexpected error code in response to the `MAIL FROM` command.
