### ISSUE TITLE
Login with Auth2

### ISSUE THREAD

**Issue by jonathansmirnoff** [jstedfast/MailKit#448]
Hey guys,

I'm having some issues trying to authenticate into gmail with an auth2 token. Did some do this? It will be very help full some help. Or some example.

Thanks!

**Comment by jstedfast** [comment]
The FAQ explains how to do this: https://github.com/jstedfast/MailKit/blob/master/FAQ.md#GMailOAuth2

Hope that helps.

**Comment by jonathansmirnoff** [comment]
@jstedfast I appreciate your help. I tried to follow the example. It should work but I'm having is this issue:
`The method or operation is not implemented.  at System.Security.Cryptography.X509Certificates.RSACertificateExtensions.GetRSAPrivateKey (System.Security.Cryptography.X509Certificates.X509Certificate2 certificate) [0x00000] in /Users/builder/data/lanes/3969/7beaef43/source/xamarin-macios/_ios-build/Library/Frameworks/Xamarin.iOS.framework/Versions/git/src/mono/mcs/class/System.Core/System.Security.Cryptography.X509Certificates/RSACertificateExtensions.cs:36 
  at Google.Apis.Auth.OAuth2.ServiceAccountCredential+Initializer.FromCertificate (System.Security.Cryptography.X509Certificates.X509Certificate2 certificate) [0x00000] in <f651f1beb6e646a4aba6382f55c77786>:0 
  at ITBApp.iOS.EmailService+<SendMail>c__async0.MoveNext () [0x00162] in /Users/jonathan/Documents/Work/bitbucket/ITBApp/ITBApp.iOS/Implementations/EmailService.cs:56 `


The code that I have is the following:

`var certificate = new X509Certificate2(googleCertificate, "notasecret", X509KeyStorageFlags.Exportable);
				var serviceAccountEmail = "xxxx@developer.gserviceaccount.com";

				var credential = new ServiceAccountCredential(
					new ServiceAccountCredential.Initializer(serviceAccountEmail)
					{
						Scopes = new[] { "https://mail.google.com/" },
						User = "nlehmann@gmail.com"
					}.FromCertificate(certificate));

				bool result = await credential.RequestAccessTokenAsync(CancellationToken.None);`

The exception is thrown when the method FromCertificate is called.

Maybe you figure out where I'm doing something wrong.  Thanks!

**Comment by jstedfast** [comment]
Google's API doesn't work on Mono because it depends on System.Security API's that have not been implemented on Linux/Mac.

**Comment by jonathansmirnoff** [comment]
Ok, so there is no way to use google auth2 in xamarin, right?

**Comment by jstedfast** [comment]
Seems that way :(

At least not using the Google API assemblies. You could probably work around it by using an OAuth2 library based on BouncyCastle (the crypto lib that MailKit uses for the same reason).

I don't know of any that use BouncyCastle off the top of my head, though (and one might not exist).

Sorry :-\

**Comment by jonathansmirnoff** [comment]
No problem. Again I really appreciate your time. At least for now I will use, as a workaround, the gmail api rest service.

**Comment by DavidKarlas** [comment]
I think you should be able to use https://components.xamarin.com/view/xamarin.auth/ or https://github.com/Clancey/SimpleAuth to get AccessToken.

**Comment by jonathansmirnoff** [comment]
I did that, the problem was that the token doesn't work to access to gmail. It should work but it doesn't..

**Comment by DavidKarlas** [comment]
Maybe what you could do... is use Fiddler or something like that to see what is Google library communicating differently from standard OAuth lib(like SimpleAuth)
