### ISSUE TITLE
Connection timout

### ISSUE THREAD

**Issue by SuhovDE** [jstedfast/MailKit#449]
It seems, that MailKit disregards Timeout option for Connection operation. 
For read and write operations it works correctly.

**Comment by SuhovDE** [comment]
Hello, are you sure that your changes will fix this issue? I thought that the common approach to set connection timeout for Socket in .Net is to make a call of BeginConnect and after that wait until timeout happens (or not happens). Something like described here [How to configure socket connect timeout](http://stackoverflow.com/questions/1062035/how-to-configure-socket-connect-timeout)

**Comment by jstedfast** [comment]
Sounds like it won't work. I would recommend using that code yourself to connect and then passing the Socket to the Connect() method that takes a Socket argument.

I don't want to deal with the mess to support this.
