### ISSUE TITLE
The SMTP server has unexpectedly disconnected

### ISSUE THREAD

**Issue by Xioshock** [jstedfast/MailKit#450]
Hey, I'm trying out MailKit, but I'm stuck on the first example from readme. I copy pasted the SMTP example and entered gmail account, that I know works in my Go app:

`          var m = new MimeMessage ();
            m.From.Add (new MailboxAddress ("Joey Tribbiani", "joey@friends.com"));
            m.To.Add (new MailboxAddress ("Mrs. Chanandler Bong", "..."));
            m.Subject = "How you doin'?";

            m.Body = new TextPart ("plain") {
                Text = @"..." };

            using (var client = new SmtpClient ()) {
                // For demo-purposes, accept all SSL certificates (in case the server supports STARTTLS)
                client.ServerCertificateValidationCallback = (s,c,h,e) => true;

                client.Connect ("smtp.gmail.com", 465, false);

                // Note: since we don't have an OAuth2 token, disable
                // the XOAUTH2 authentication mechanism.
                client.AuthenticationMechanisms.Remove ("XOAUTH2");

                // Note: only needed if the SMTP server requires authentication
                client.Authenticate ("...", "...");

                client.Send (m);
                client.Disconnect (true);
            }
`

This throws:
`Connection id "0HL21SIP866TI": An unhandled exception was thrown by the application.
MailKit.Net.Smtp.SmtpProtocolException: The SMTP server has unexpectedly disconnected.`

after 10 seconds.

I don't know what to think about it, I tried even the async methods and the result was same.

I'm on .Net core 1.1.0, MailKit 1.10.1, Mac OS.

**Comment by jstedfast** [comment]
The exception says that your server disconnected you. It works fine for me, so I suspect you have some sort of firewall problem or something.

You could try getting a ProtocolLog (explained in the FAQ.md file) to see how far it gets before getting the exception. Maybe that will be helpful?

**Comment by Xioshock** [comment]
It only outputs 1 line from the log: Connected to smtp://smtp.gmail.com:465/

And then it throws the same exception. Maybe it has something to do with the gmail, I can't think of anything that could be wrong..

Like I said, I'm using the same exact server smtp.gmail.com:465 with the same credentials in my other app, that is build with Go.

**Comment by jstedfast** [comment]
Can you write a simple program that connects to smtp.gmail.com on port 465 using simple sockets?

**Comment by Xioshock** [comment]
I managed to connect to gmail on port 25 for now. I'll try the 465 later. Thanks for the help.
