### ISSUE TITLE
Unable to write data to the transport connection: An established connection was aborted by the software in your host machine

### ISSUE THREAD

**Issue by RonLiang** [jstedfast/MailKit#454]
I keep the SMTP connection for two days. And now I call the send method to send an message. But some errors occured. 
Error info:Unable to write data to the transport connection: An established connection was aborted by the software in your host machine.

So what is the problem? Thanks for your answer ahead.

**Comment by jstedfast** [comment]
You lost the connection. Reconnect and try again.
