### ISSUE TITLE
MailKit loading assembly in MEF based scenario with Caliburn Micro

### ISSUE THREAD

**Issue by wstaelens** [jstedfast/MailKit#455]
I'm downloading plugins from a remote location. The dll's of these plugins are downloaded in their own directory with name and version (e.g; Dllname.1.0.0.0) to make them unique.

In a next step these assemblies are loaded into an existing application with .LoadFrom:
`var myAssembly = Assembly.LoadFrom(filename). `
And also added to AssemblySource. with:
`AssemblySource.Instance.Add(myAssembly)`

This is because they need to be known by the MEF Container and Caliburn Micro to make the IoC / DI working.

However when loading MailKit, this fails because MailKit requires MimeKit. So MimeKit should be loaded first. For some reason during loading the MailKit dll, it needs something from MimeKit which makes it fail.

When I load other dll's that depend on another dll, I don't have this error, which makes me believe that there is some kind of static field or something that gets executed/initialized when loading MailKit that requires MimeKit making it fail.

In this way I can't load first MailKit and then MimeKit and after that make some calls.

(quite hard to explain, it is a complex situation but MailKit has something which does not allow it to load the assembly and make it available to MEF and Caliburn Micro without loading first MimeKit. While other assemblies make this possible.)

**Comment by jstedfast** [comment]
Could you investigate this and get back to me with a solution? I'd be happy to review your patch(es) and work with you to merge them into mainline MimeKit and/or MailKit.

You seem to know a whole lot more about this than I do.

**Comment by wstaelens** [comment]
Plugins and their dll's are downloaded and stored in their own folder. e.g.:
`FtpLib.dll`
is stored in path: "FtpLib.1.0.4185.25073". Constructed like this:
`// "" + FtpLib + "." + 1.0.4185.25073 = \FtpLib.1.0.4185.25073\`

next a foreach loop gets the filenames and loads them via:

```
foreach (var fileName in downloadedPlugins) {
  try {
    var localAssembly = Assembly.LoadFrom(fileName);

    AssemblySource.Instance.Add(localAssembly); // <--- crash is here
 } catch {}
}
```

So I have for example these **folders**:
`BouncyCastle.Crypto.1.8.15362.1
MailKit.1.10.2.0
MimeKit.1.10.1.0
`

Because I download the files in alphabetical order I first get Bouncy, next I get MailKit and next MimeKit.

Bouncy loads just fine.  but MailKit fails to load because it requires MimeKit. 
Now for some reason (and this is probably the problem) during the **AssemblySource.Instance.Add()** the MailKit assembly does/needs/inspects/... something causing it to look for MimeKit. Resulting in an exception and MailKit could not be loaded.

However if I copy/paste the dll from MimeKit to the folder of MailKit (remember their were stored in a separate folder, a bit like packages to make them unique) then MailKit can load because it finds MimeKit (or I've just been lucky all the time).

This means I always have to either load MimeKit first or add MimeKit to the same library of MailKit before loading MailKit assembly. The problem is that I can't control the order in which I receive MimeKit or MailKit.

I download and load other dll's also where I load first a dll that requires another one and lather load the other one, and that does not crash. So there must be "something" different with MailKit/MimeKit but I have no clue what exactly it is. (nor can't i create a path or spend hours on it to search for it because of limited time, but I wanted to report it so that this 'issue' is known at least. Currently I'm trying to find all dependencies first and try to sort them as a workaround).

**Comment by jstedfast** [comment]
> Now for some reason (and this is probably the problem) during the AssemblySource.Instance.Add() the MailKit assembly does/needs/inspects/... something causing it to look for MimeKit. Resulting in an exception and MailKit could not be loaded.

Makes sense... because the runtime has no idea where to find the MimeKit.dll. It's not in the GAC and it's not in the same directory (which is how the assembly loader works).

I don't see how this is a problem with my code.
