### ISSUE TITLE
Email InternalDate

### ISSUE THREAD

**Issue by lordofhammsters** [jstedfast/MailKit#456]
Hi,
1) When i fetch the message summaries 

`inbox.Fetch(uids, MessageSummaryItems.UniqueId | MessageSummaryItems.Envelope | MessageSummaryItems.InternalDate)`

InternalDate is the same Date, but i expect "received" date from headers:

```
Received: by 10.103.85.210 with SMTP id q79csp283698vsg;
        Sat, 11 Feb 2017 18:24:14 -0800 (PST)
X-Received: by 10.200.40.113 with SMTP id 46mr14303764qtr.167.1486866254026;
        Sat, 11 Feb 2017 18:24:14 -0800 (PST)
Received: from a11-99.smtp-out.amazonses.com (a11-99.smtp-out.amazonses.com. [54.240.11.99])
        by mx.google.com with ESMTPS id y36si4464679qty.52.2017.02.11.18.24.13
        for <...@gmail.com>
        (version=TLS1 cipher=ECDHE-RSA-AES128-SHA bits=128/128);
        Sat, 11 Feb 2017 18:24:13 -0800 (PST)
Date: Sun, 12 Feb 2017 02:24:13 +0000
```

2) How to get internal date ("received") when get message like `inbox.GetMessage(id)`?

**Comment by jstedfast** [comment]
What you can do is request specific header fields (such as Received) like this:

```csharp
var fields = new HashSet<string> ();
fields.Add ("Received");

inbox.Fetch (uids, MessageSummaryItems.UniqueId | MessageSummaryItems.Envelope, fields);
```

At this point you can access the `Headers` property of each message summary that is returned.

**Comment by lordofhammsters** [comment]
Thank you for answer and library!
