### ISSUE TITLE
Message-Id missing after download

### ISSUE THREAD

**Issue by Mats391** [jstedfast/MailKit#458]
I am using MailKit to download emails from a POP3 server. To remember which mail I already downloaded I use the Message-Id to identify those. For that I first only ask for the Message-Id header and if its not known, download the message.
The problem that arises is that sometimes I get a valid Message-Id when getting it from the header, but the downloaded message then has no Message-Id set. This is random bug that I cant really reproduce.

My code:
```
public IEnumberable<MimeMessage> DownloadNewMails()
{
    int startAt = -1;
    int count = _pop3Client.Count;
    for (int i = count - 1; i >= 0; i--) {
        string messageId;
        if (TryGetMessageId( i, out messageId )) { // Valid Message-Id
            if (!_downloadedMessageIds.Contains( messageId )) {
                startAt = i;
            }
            else {
                break;
            }
        }
    }

    if (startAt >= 0) {
        for (int i = startAt; i < count; i++) {
            string messageId;
            if (TryGetMessageId( i, out messageId )) { // Valid Message-Id
                yield return _pop3Client.GetMessage( i ); // Message-Id=null
            }
        }
    }
}

public bool TryGetMessageId(int id, out string messageId)
{
    messageId = string.Empty;
    var headers = _pop3Client.GetMessageHeaders( id );
    if (headers.Contains( HeaderId.MessageId )) {
        messageId = headers[HeaderId.MessageId];
        return true;
    }
    return false;
}
```
Am I doing something wrong? Is this a known issue of Pop3?

**Comment by jstedfast** [comment]
You can't rely on a Message-Id header existing. It's *supposed* to be there according to the spec, but there's no guarantee that the client that sent the message has added it. If it didn't set one, then it won't exist on the POP3 server.

It's possible that when you call GetHeaders() that the server is randomly generating a Message-Id but that when you download the entire message, it isn't. I've seen this behavior with some POP3 servers for other headers (never Message-Id that I've noticed, but I haven't tested them all obviously).

You can verify that it's not a bug in MailKit by obtaining a protocol log as suggested in the FAQ and taking a look at the raw message data that gets downloaded.

I'm 99.9% confident that if the downloaded MimeMessage doesn't have a Message-Id, then neither does the raw message.
