### ISSUE TITLE
The requested folder could not be found.

### ISSUE THREAD

**Issue by RonLiang** [jstedfast/MailKit#459]
I use method 
oSourceFolder.MoveTo(UniqueId, m_imapClient.GetFolder(sDesFolder)) 
to move a message to another folder.
But I get this err:The requested folder could not be found. The sDesFolder actually exists. What makes me confused is that this error doesn't  occurr every time.

The follow is the exception stack info:
at MailKit.Net.Imap.ImapFolder.ProcessResponseCodes(ImapCommand ic, IMailFolder folder)
at MailKit.Net.Imap.ImapFolder.MoveTo(IList`1 uids, IMailFolder destination, CancellationToken cancellationToken)
at MailKit.MailFolder.MoveTo(UniqueId uid, IMailFolder destination, CancellationToken cancellationToken)

**Comment by jstedfast** [comment]
Can you get me a protocol log? See the FAQ for how to get this information.

**Comment by RonLiang** [comment]
Hi Jeff, this is the protocol log. I find "The destination mailbox could not be found" in it. But before move, I have checked whether the destination folder exist. If it doesn't, I would create it. So it should be found. I don't know why it look like this. This is an outlook server.

C: A00000049 LIST "" Exception
S: * LIST (\HasNoChildren) "/" EXCEPTION
S: A00000049 OK LIST completed.
C: A00000050 LIST "" Exception
S: * LIST (\HasNoChildren) "/" EXCEPTION
S: A00000050 OK LIST completed.
C: A00000051 SELECT EXCEPTION
S: * 1 EXISTS
S: * 0 RECENT
S: * FLAGS (\Seen \Answered \Flagged \Deleted \Draft $MDNSent)
S: * OK [PERMANENTFLAGS (\Seen \Answered \Flagged \Deleted \Draft $MDNSent)] Permanent flags
S: * OK [UIDVALIDITY 92] UIDVALIDITY value
S: * OK [UIDNEXT 120] The next unique identifier value
S: A00000051 OK [READ-WRITE] SELECT completed.
C: A00000052 UID MOVE 119 "Exception Processed"
S: A00000052 NO [TRYCREATE] The destination mailbox could not be found.
C: A00000053 LIST "" Exception
S: * LIST (\HasNoChildren) "/" EXCEPTION
S: A00000053 OK LIST completed.
C: A00000054 LIST "" "Exception Not Processed"
S: A00000054 OK LIST completed.
C: A00000055 LIST "" "Exception Not Processed"
S: A00000055 OK LIST completed.
C: A00000056 CREATE "Exception Not Processed"
S: A00000056 OK CREATE completed.
C: A00000057 LIST "" "Exception Not Processed"
S: * LIST (\HasNoChildren) "/" "Exception Not Processed"
S: A00000057 OK LIST completed.
C: A00000058 LIST "" Exception
S: * LIST (\HasNoChildren) "/" EXCEPTION
S: A00000058 OK LIST completed.
C: A00000059 UID MOVE 119 "Exception Not Processed"
S: [COPYUID 116 119 1]
S: * 1 EXPUNGE
S: * 0 EXISTS
S: A00000059 OK MOVE completed.

**Comment by jstedfast** [comment]
How did you check that it exists? Did another client delete the folder?

**Comment by jstedfast** [comment]
Can you show the part of the log where it gets the info for the "Exception Processed" folder? It'll be a LIST command.

**Comment by RonLiang** [comment]
I check the folder in the web outlook. And it is me who delete the folder. I do that for a test.
Now I get the root cause. Before move action, the code would check whether folder exist via MailKit.IMailFolder.GetFolder method. This is the problem. This method would do nothing if it has gotten the folder last time. So a list command wouldn't be executed. It seems that this folder exist. Actually it has been deleted.


public Sub MoveEmail(ByVal sSourceFolder As String, ByVal sDesFolder As String, ByVal UniqueId As MailKit.UniqueId)

...

If Not isFolderExisted(sDesFolder) Then
    Dim root As MailKit.IMailFolder = m_imapClient.GetFolder(m_imapClient.PersonalNamespaces(0))
    root = root.Create(sDesFolder, True)
else 
	Dim oSourceFolder As MailKit.IMailFolder = m_imapClient.GetFolder(sSourceFolder)
    oSourceFolder.Open(MailKit.FolderAccess.ReadWrite)
    oSourceFolder.MoveTo(UniqueId, m_imapClient.GetFolder(sDesFolder))
    oSourceFolder.Close()			
End If

...

end function

Private Function isFolderExisted(ByVal strFolderName As String) As Boolean

...
        Try
            Dim oFolder As MailKit.IMailFolder = m_imapClient.GetFolder(strFolderName)
        Catch ex As Exception
            Return False
        End Try
        Return True
...
End Function


If I call MoveEmail twice, the first time m_imapClient.GetFolder(strFolderName) return fine. The second time it would always return fine too, thought the strFolderName folder has been deleted.

**Comment by jstedfast** [comment]
Okay, so I guess this is solved now?

**Comment by RonLiang** [comment]
yes, I change the isFolderExisted function code. 

`Dim oFolder As MailKit.IMailFolder = m_imapClient.GetFolder(strFolderName)
oFolder.Open(FolderAccess.ReadOnly)
oFolder.Close()`

Then It always return the actual status of an folder.
Thanks your help.
