### ISSUE TITLE
Authentication failed trying to connect to IMAP:4 Exchange server

### ISSUE THREAD

**Issue by sapreakshay** [jstedfast/MailKit#460]
Hi ,
I am trying to connect to Microsoft exchange client.  It is giving me Authentication failed. 
Imap Log 
Connected to imaps://outlook.office365.com:993/
S: * OK The Microsoft Exchange IMAP4 service is ready. [UwBOADEAUABSADAAMgBDAEEAMAAwADEANQAuAG4AYQBtAHAAcgBkADAAMgAuAHAAcgBvAGQALgBvAHUAdABsAG8AbwBrAC4AYwBvAG0A]
C: A00000000 CAPABILITY
S: * CAPABILITY IMAP4 IMAP4rev1 AUTH=PLAIN AUTH=XOAUTH2 SASL-IR UIDPLUS MOVE ID UNSELECT CHILDREN IDLE NAMESPACE LITERAL+
S: A00000000 OK CAPABILITY completed.
C: A00000001 AUTHENTICATE PLAIN AHN2Y19hc29wX28zNjVAaWxtbi5vbm1pY3Jvc29mdC5jb21cTUItQVNPUC1ET0MtQVRUQUNILURFVgA9Vk1FbHlrVHNPbjcz
S: A00000001 NO AUTHENTICATE failed.
C: A00000002 LOGIN "svc_asop_o365@XXX.onmicrosoft.com\\MB-XXX-DOC-ATTACH-DEV" =VMElykTsOn73
S: A00000002 NO LOGIN failed.
C: A00000003 LOGOUT
S: * BYE Microsoft Exchange Server 2016 IMAP4 server signing off.
S: A00000003 OK LOGOUT completed.

Code Snippet 
 imapClient.Connect(param.ImapServerHost, param.ImapServerPort,MailKit.Security.SecureSocketOptions.Auto);
                
                 imapClient.AuthenticationMechanisms.Remove("XOAUTH2");
                 imapClient.AuthenticationMechanisms.Remove("NTLM");
                //  imapClient.Connect(param.ImapServerHost, param.ImapServerPort);
                imapClient.Authenticate(param.ImapUsername, param.ImapPassword);
                var inbox = imapClient.GetFolder(param.ImapFolder);

Exception found 
2017-02-15 12:57:34,217 [1] FATAL XXX.AAAA.Common.EmailHelper [(null)] <(null)> - Application [XXX.ASOP.Common.Driver] LOGIN failed.

Thanks in advance

**Comment by jstedfast** [comment]
An authentication failed exception indicates that you provided the wrong credentials.

The log also shows that the server rejected your credentials.
