### ISSUE TITLE
Problem with exchange 2016 CU3 IMAP4, folder.append with multipart msg fail

### ISSUE THREAD

**Issue by XavierDa** [jstedfast/MailKit#461]
Hello,

short context here, i'm copying one msg from one server to another so i'm getting a msg with mailkit from   one part and save it to a buffer then reparsing it with :
`
using (MemoryStream stream = new MemoryStream(content.Content))
{
    var parser = new MimeParser(stream);
    msg = parser.ParseMessage();
}
`
after i do a 
`
UniqueId? id = folder.Append(msg);
`
Code works well on zimbra / roundcube servers and text mail on exchange but it seems to fail when trying to save a multipart/alternative.

Attached is the log (size is wrong seeing that i modified the file to hide some private information).

I tried to play with formatoptions / parseoptions but nothing seems to work.

My guess is that there is a problem on Exchange Side parsing the multipart...

[logimapclean.txt](https://github.com/jstedfast/MailKit/files/790250/logimapclean.txt)

**Comment by XavierDa** [comment]
Ok after looking a little more in depth it seems that i hit the max size for command (10KB) is there anyway to avoid it using mailkit ?

**Comment by jstedfast** [comment]
If you check the size of the data sent in the APPEND command w/o any editing, does it match the size specified by MailKit in the {}'s? e.g. is it 131072 bytes?

**Comment by XavierDa** [comment]
ok seems that this is the pb the binary stream that i used is filed with 0 at the end (from 88744 to 131072)

**Comment by XavierDa** [comment]
So it works.

Found for thoughts : i was using an example that was writing a mimemessage to a binary buffer, it was using MemoryStream.GetBuffer().

i changed it to "MemoryStream.ToArray()" and it resolved all.

**Comment by jstedfast** [comment]
oh, cool
