### ISSUE TITLE
Question: Does MailKit support RCPT TO when sending an e-mail with SMTP?

### ISSUE THREAD

**Issue by Sicos1977** [jstedfast/MailKit#463]
Hi,

Does MailKit support RCPT TO when sending an e-mail with SMTP and if so how is this done?
What I want to do is forward an E-mail to another mailbox with the original TO (the one where it is forwarded from) intact. 

Thanks.

Greetings,
Kees van Spelde

**Comment by Sicos1977** [comment]
Nevermind I already figured out that it is possible :-)

**Comment by jstedfast** [comment]
For anyone else that comes across this with the same question: The way to do this is to use the [SmtpClient.Send(MimeMessage message, MailboxAddress sender, IEnumerable<MailboxAddress> recipients, CancellationToken cancellationToken = null, ITransferProgress progress = null)](http://www.mimekit.net/docs/html/M_MailKit_MailTransport_Send_2.htm) method that allows you to override the addresses in the Sender, From, To, Cc, and Bcc headers.

**Comment by Sicos1977** [comment]
I decided not to use it because our Exchange server is marking my "forwarded" E-mails as SPAM. I now am going to move the messages by making a connection to both mailboxes through IMAP and then move the message from mailbox A to mailbox B

**Comment by jstedfast** [comment]
Ah, yea, that works better :)

**Comment by Sicos1977** [comment]
Yeah but only when you have the credentials for both accounts... like in my case.
