### ISSUE TITLE
ImapProtocolException. The IMAP server has unexpectedly disconnected

### ISSUE THREAD

**Issue by jacargentina** [jstedfast/MailKit#464]
I'm attaching the logs for an account i'm trying to use.

May be the login, or password, are bad. But i would like to receive that error, and not the ugly "The IMAP...", which looks as something much bad.

![mailkit-error](https://cloud.githubusercontent.com/assets/517228/23718068/e01f87ca-043e-11e7-88aa-1869e61183a7.jpg)

**Comment by jstedfast** [comment]
The problem is that the server has dropped your connection. There's no way for MailKit to know *why* the server dropped the connection.
