### ISSUE TITLE
SmtpClient client.ReplayConnect method don't working on vs 2017 

### ISSUE THREAD

**Issue by uthens** [jstedfast/MailKit#465]
SmtpClient client.ReplayConnect method don't working on vs 2017 
I try to build on unit test "SmtpClientTests.cs" and i found the problem.
My projects to used .net 4.5.2 (unit test project) and .netcoreapp 1.1 (main project)

![screen shot 2560-03-09 at 4 26 26 pm](https://cloud.githubusercontent.com/assets/10783170/23744011/4fedeb5e-04e5-11e7-9894-fe183efff1a5.png)

Best,
-Uthen

**Comment by jstedfast** [comment]
Only the MailKit UnitTests have access to that method via `InternalsVisibleTo` attribute in MailKit's AssemblyInfo.cs

In other words, you're not supposed to have access to it in your own code.

**Comment by uthens** [comment]
Thanks you so much
