### ISSUE TITLE
Attachment file size

### ISSUE THREAD

**Issue by madu2003** [jstedfast/MailKit#467]
Hi,

Is there a method to call to get the size of an attachment when reading emails in?

something like below:

foreach(var mp in message.Attachments)
{
    long byteSize = mp.attachment.Length;
}

**Comment by jstedfast** [comment]
No, there is not. But you can do this:

```csharp
foreach (var attachment in message.Attachments) {
    using (var stream = new MeasuringStream ()) {
        var rfc822 = attachment as MessagePart;
        var part = attachment as MimePart;

        if (rfc822 != null) {
            rfc822.Message.WriteTo (stream);
        } else {
            part.ContentObject.DecodeTo (stream);
        }

        Console.WriteLine ("attachment length = {0}", stream.Length);
    }
}
```

In the code snippet above I am using `DecodeTo` instead of `WriteTo` because I am assuming you want the decoded length, not the _encoded_ length. If that's not the case, just swap `DecodeTo` with `WriteTo`.

**Comment by prostakov** [comment]
I have additional question regarding this.

So in general in MailKit there are these two approaches:

1. `IMailFolder.FetchAsync` which returns `IMessageSummary`, which is a metadata on mail message.
And this metadata includes info about attachments sizes via means of `Octets` field on `BodyPartBasic` abstraction.

2. The other approach `IMailFolder.GetMessageAsync`, which does not load only metadata, but rather entire message - in abstraction `MimeMessage`, which has property `IEnumerable<MimeEntity> Attachments`.

So the question then becomes - how come this data is available in first approach and is not available in second?

As I understand - the solution with having additional measuring stream, just to estimate the size of the attachment with consume more memory.

If this data is available somewhere - would it be possible to extend the `MimeEntity` or `MimePart` with new octets property?

**Comment by jstedfast** [comment]
> So the question then becomes - how come this data is available in first approach and is not available in second?

The short answer is because MimeMessage/MimeEntity/MimePart are the parsed results of the raw message data while the `IMessageSummary` stuff returned by `Fetch`/`FetchAsync` are the parsed IMAP rsponse for the data returned by the IMAP server.

MailKit is not calculating the `Octets` value - that is metadata that is returned by the IMAP server because the IMAP protocol defines that metadata.

> As I understand - the solution with having additional measuring stream, just to estimate the size of the attachment, - will consume more memory.

That's not actually the case. The [MimeKit.IO.MeasuringStream](https://mimekit.net/docs/html/T_MimeKit_IO_MeasuringStream.htm) does not need to allocate very much memory at all in order to be able to measure the length of the MimeMessage or MimeEntity that you write to it.

In fact, this is literally how the MeasureingStream.Write() method works:

```csharp
public override void Write (byte[] buffer, int offset, int count)
{
	CheckDisposed ();

	ValidateArguments (buffer, offset, count);

	position += count;

	length = Math.Max (length, position);
}
```

All it does is count the number of bytes written to it. It does not save the content into memory at all.

> If this data is available somewhere - would it be possible to extend the MimeEntity or MimePart with new octets property?

The information isn't available at all. MimeKit would have to calculate it by creating a new MeasuringStream and writing the message or part to the measuring stream and then accessing the `stream.Length` property which you can do yourself if you want it in 3 lines of code:

```csharp
using (var stream = new MeasuringStream()) {
    message.WriteTo(stream);
    long octets = stream.Length;
}
```

**Comment by prostakov** [comment]
Thank you for getting back at me!

-----------------------------------

> MailKit is not calculating the Octets value - that is metadata that is returned by the IMAP server because the IMAP protocol defines that metadata.

This does seem like an oversight from the IMAP protocol.
At least would be nice to have an option to query the message along with metadata (`MimeMessage` + `IMessageSummary`)  in **single request**.

-----------------------------------

> That's not actually the case. The [MimeKit.IO.MeasuringStream](https://mimekit.net/docs/html/T_MimeKit_IO_MeasuringStream.htm) does not need to allocate very much memory at all in order to be able to measure the length of the MimeMessage or MimeEntity that you write to it.

Thank you very much for sharing these details.
While this is definitely a good news, this is not a complete relief, as we still need to spend CPU cycles measuring the size of attachment. 
As I speculate if I have for example 20MB PDF - this operation may take up to one second? Or even a few seconds?...
I wonder in this case - wouldn't it be quicker to just do a second request for `IMessageSummary`, and fetch size from metadata...

**Comment by jstedfast** [comment]
> As I speculate if I have for example 20MB PDF - this operation may take up to one second? Or even a few seconds?

I doubt it would take that long on any reasonably modern hardware. Keep in mind that MimeKit can parse a Gigabyte worth of email in 1 second, so measuring a 20MB attachment will take microseconds at most.

**Comment by prostakov** [comment]
I was able to run some checks this morning.

On mime message that is 30MB.

This method:

```
public static long GetSize(this MimeMessage message)
{
    using var stream = new MeasuringStream();
    message.WriteTo(stream);
    return stream.Length;
}
```

On my fancy PC: 132ms.
On my 10-year-old macbook: 230ms.

It is not seconds - as you've said.

I guess this will do...

Thanks again for your assistance 👍
