### ISSUE TITLE
Login Failed IMAP

### ISSUE THREAD

**Issue by yaseminaladi** [jstedfast/MailKit#469]
Hello,
I have 3 mail address configured in same server, same port and same password. I authenticate both of them, but I could not authenticate other one. Can you help me, please?

**Comment by jstedfast** [comment]
Try getting a [protocol log](https://github.com/jstedfast/MailKit/blob/master/FAQ.md#ProtocolLog) to see what the problem is.

**Comment by yaseminaladi** [comment]
Log is here.

Connected to imaps://exchange.aksigorta.com.tr:993/
S: * OK The Microsoft Exchange IMAP4 service is ready.
C: A00000000 CAPABILITY
S: * CAPABILITY IMAP4 IMAP4rev1 AUTH=NTLM AUTH=GSSAPI AUTH=PLAIN UIDPLUS CHILDREN IDLE NAMESPACE LITERAL+
S: A00000000 OK CAPABILITY completed.
C: A00000001 AUTHENTICATE PLAIN
S: +
C: AHRlc3RoYXNhcmV2cmFrMUBha3NpZ29ydGEuY29tLnRyAEFrczEyMzQ1
S: A00000001 NO AUTHENTICATE failed.
C: A00000002 LOGIN testhasarevrak1@aksigorta.com.tr Aks12345
S: A00000002 NO LOGIN failed.

**Comment by jstedfast** [comment]
Your server doesn't seem to like your credentials for whatever reason. Unfortunately it doesn't say why.

**Comment by yaseminaladi** [comment]
But The server has 3 mail addresses and all of them has same password.

13 Mar 2017 20:18 tarihinde "Jeffrey Stedfast" <notifications@github.com>
yazdı:

**Comment by jstedfast** [comment]
All I can tell you is that it's not a bug in MailKit based on the protocol logs.

**Comment by yaseminaladi** [comment]
And I have problem with multithreading in Mailkit. Can you provide any
example please?


13 Mar 2017 20:23 tarihinde "Jeffrey Stedfast" <notifications@github.com>
yazdı:
