### ISSUE TITLE
Unable to read data from the transport connection: A blocking operation was interrupted by a call to WSACancelBlockingCall.

### ISSUE THREAD

**Issue by yaseminaladi** [jstedfast/MailKit#470]
Hello,

I am getting the error Unable to read data from the transport connection: A blocking operation was interrupted by a call to WSACancelBlockingCall in windows service. The service is always listening three mail addresses in parallel. Generally, I am getting this error. Why it occur? Can you help me, please?

**Comment by jstedfast** [comment]
I have no idea... you haven't given me anything useful. Try googling for WSACancelBlockingCall I guess.

https://social.msdn.microsoft.com/Forums/vstudio/en-US/31866793-8064-4bce-a1e7-8bde3b793505/why-im-getting-exception-a-blocking-operation-was-interrupted-by-a-call-to-wsacancelblockingcall?forum=csharpgeneral

That might help.
