### ISSUE TITLE
MailKit it's worked on local pc only, but don't work on live server (2016) on azure.

### ISSUE THREAD

**Issue by uthens** [jstedfast/MailKit#471]
MailKit it's worked on local pc only, but don't work on live server (2016) on azure.
When i tested on windows 10 email send is correct, but when we try to deploy to production server 
on Azure we can't send email.

I don't make sure IIS on the server block the email service ? 
We tried to enable SMTP on server but it's not help.

![screen shot 2560-03-20 at 1 55 54 pm](https://cloud.githubusercontent.com/assets/10783170/24090677/f974cc46-0d74-11e7-9285-dc3857d028d7.png)

![screen shot 2560-03-20 at 2 51 11 pm](https://cloud.githubusercontent.com/assets/10783170/24091778/c5c72cd8-0d7c-11e7-86b8-ad6d03eaedfd.png)

![screen shot 2560-03-20 at 3 59 27 pm](https://cloud.githubusercontent.com/assets/10783170/24093418/4addace0-0d86-11e7-9cca-6e475713b955.png)

Best, 
Uthen

**Comment by uthens** [comment]
Sample code we used:
 
public class EMailSender
    {
        public async Task SendEmailByThread(string sSubject, string sHtmlBody, 
            string sFromEmail, string sToEmail, string sFromName, string sToName, 
            string sAuthenPassword, int nPort, string sSMTP)
        {
            var message = new MimeMessage();
            message.From.Add(new MailboxAddress(sFromName, sFromEmail));
            message.To.Add(new MailboxAddress(sToName, sToEmail));
            message.Subject = sSubject;

            var bodyBuilder = new BodyBuilder();
            bodyBuilder.HtmlBody = sHtmlBody;
            message.Body = bodyBuilder.ToMessageBody();

            using (var client = new SmtpClient())
            {
                await client.ConnectAsync(sSMTP, nPort, false);

                // Note: since we don't have an OAuth2 token, disable
                // the XOAUTH2 authentication mechanism.
                client.AuthenticationMechanisms.Remove("XOAUTH2");
                await client.AuthenticateAsync(sFromEmail, sAuthenPassword);

                client.Send(message);
                client.Disconnect(true);
            }
        }
    }

**Comment by uthens** [comment]
relate on this number or not ? https://github.com/jstedfast/MailKit/issues/393

**Comment by uthens** [comment]
I try on this but don't help.: http://stackoverflow.com/questions/35651001/gmail-smtpauthenticationerror-when-i-attempt-to-send-email-via-django

**Comment by jstedfast** [comment]
GMail blocks logins from unknown IP addresses. You need to login to your GMail account from your azure server first. Then it will work.

**Comment by uthens** [comment]
@jstedfast unbelievable it's worked wowwwwwwww and cool.
You save my day & night 👍

**Comment by jstedfast** [comment]
you're welcome!

**Comment by uthens** [comment]
It's worked good on azure, but it's not work on amazon ec2 ?

**Comment by rahulraut5067** [comment]
You need to allow access to the Gsuit Gmail account, because, google blocks the mail from different IP's.    

https://accounts.google.com/DisplayUnlockCaptcha

**Comment by glihm** [comment]
> @jstedfast unbelievable it's worked wowwwwwwww and cool.
> You save my day & night 👍

How did you logged in from Azure?
