### ISSUE TITLE
Question: Example that shows how to put an e-mail into a folder through IMAP

### ISSUE THREAD

**Issue by Sicos1977** [jstedfast/MailKit#473]
Hi,

Just a question, do you maybe have an example somewhere how to generate an e-mail with mimekit and place that generated e-mail into a folder with mailkit?

Thanks in advance.

Greetings,
Kees van Spelde

**Comment by jstedfast** [comment]
You can construct the message as normal and then, to append the message to a folder, you'd use one of the [ImapFolder.Append()](http://www.mimekit.net/docs/html/Overload_MailKit_MailFolder_Append.htm) methods.

If you specify a `MessageFlags` argument, it sets those flag(s) on the message when it appends it to the folder. You can always change the flags again later. using AdFlags/RemoveFlags/SetFlags.

If you specify a `DateTimeOffset`, it sets the `INTERNALDATE` metadata for the message on the server. Generally, the `INTERNALDATE` value is treated as the timestamp for when the message arrived in the folder and so if you don't specify this value, it just uses the current date/time value.

Hope that helps.

**Comment by Sicos1977** [comment]
Thanks for the quick response

**Comment by Sicos1977** [comment]
Hi,

Just a follow up question. I saw that there also was a possibility to cast a MailMessage to a MimeMessage. I do that now like this:

```
        /// <summary>
        /// Schrijft het opgegeven <paramref name="message"/> naar de <see cref="Folder"/> wanneer
        /// deze <see cref="MailBox"/> een <see cref="Outbox"/> is
        /// </summary>
        /// <param name="message"><see cref="MimeMessage"/></param>
        /// <returns>Het unieke id van het geschreven bericht</returns>
        /// <exception cref="MailBoxException"></exception>
        public string WriteMessage(MailMessage message)
        {
            return WriteMessage((MimeMessage) message);
        }
```
Does this also set the `INTERNALDATE `automatically or do I need to do this manually?

**Comment by jstedfast** [comment]
The `MimeMessage` (or `MailMessage`) does not contain an `INTERNALDATE`, it's just a timestamp that the IMAP server keeps as to when the message arrived in its inbox (or whatever folder).
