### ISSUE TITLE
Not able to use MailKit in Visual Studio 2017

### ISSUE THREAD

**Issue by fvandillen** [jstedfast/MailKit#474]
I am trying to retrieve IMAP messages with MailKit, however the code example that my colleague uses (which is working on his machine with the previous VS version) isn't working on mine.

The IDE reports the following error:
![mailkit](https://cloud.githubusercontent.com/assets/5518922/24298992/0675f6be-10a8-11e7-8514-215e26dd4b46.png)

Any ideas?

**Comment by mwpowellhtx** [comment]
@fvandillen One of the interfaces and/or classes involved no longer supports IDisposable.

**Comment by fvandillen** [comment]
@mwpowellhtx I'm following the official documentation for MailKit. Any ideas?

**Comment by mwpowellhtx** [comment]
@fvandillen I follow MailKit as a some-time user. My recommendations: fork and contribute a PR. Possibly you just need to include IDisposable where current (?) or up-coming (?) .NET framework distributions no longer support IDisposable. Hope that helps.

**Comment by fvandillen** [comment]
Never mind, i'm an idiot. Should have chosen a better class name on Line 7.

**Comment by mwpowellhtx** [comment]
@fvandillen That even escaped me. It happens. :+1:

**Comment by jstedfast** [comment]
Hah, I didn't notice that either :)

I was scratching my head wondering why that was happening because it still implements IDisposable.

**Comment by mwpowellhtx** [comment]
Sometimes the obvious answer is right in front of you. Not IDisposable? Because it wasn't. Anywho... Thanks for the humor for the day.
