### ISSUE TITLE
SMTP with GMAIL

### ISSUE THREAD

**Issue by santidat** [jstedfast/MailKit#475]
Dear Sir,
I have this problem :+1: 

If I use an Gmail account xxx.gmail.com  I am able to connect to gmail server.Not problem
But if I want to connect to my corpporate gmail account I am not able. I checked the "let insecure app to connect " and it is ON. The double check authentification is OFF.
The corporate account ,managed by gmail its xxx@yyy.com

This is the code I use, wrote in VB.net

       Dim smtp As New MailKit.Net.Smtp.SmtpClient

       
        smtp.AuthenticationMechanisms.Remove("XOAUTH2")

        smtp.Connect("smtp.gmail.com", 587, SecureSocketOptions.StartTls)

        smtp.Authenticate(User, Password)

        smtp.Send(mail)
        smtp.Disconnect(True)

Please could you tell me something

**Comment by jstedfast** [comment]
You might need to login via a web browser from the same machine first.

I don't know anything else beyond that. I know for a fact it's not a MailKit problem because I have connected fine to a corporate gmail account.
