### ISSUE TITLE
Unable to write data to the transport connection. An existing connection was forcibly closed by the remote host.  

### ISSUE THREAD

**Issue by maddisn** [jstedfast/MailKit#479]
Hello, 

I am running into the following network related issues even after turning my firewall off, along with windows defender. I have tried to attempt this on a different machine and the same issue surfaces. 
My process relates to parsing the email, attachments, and inline attachments in order to upload them to our ticketing system. Everything worked fine for a while, until now.

ImapProtocolException
I also get ImapProtocolException, and visual studio will try to run my program for at least 10 minutes.

![connectionclosed](https://cloud.githubusercontent.com/assets/25490236/24466136/c6ccc9c8-147d-11e7-8d40-0cbb380550f5.PNG)
![bug](https://cloud.githubusercontent.com/assets/25490236/24466141/c97968de-147d-11e7-8e7a-f357a676b302.PNG)
![screenshot 61](https://cloud.githubusercontent.com/assets/25490236/24466144/cc001224-147d-11e7-9bf1-0867e461410a.png)

Thanks.

**Comment by jstedfast** [comment]
Unfortunately there's nothing I can do about that... it means that the IMAP server closed the connection on you and there's no way to know why.

That exception gets thrown here: https://github.com/jstedfast/MailKit/blob/master/MailKit/Net/Imap/ImapStream.cs#L350

The only way for that to happen is if Stream.Read() returns 0 which means that the stream has reached the End-of-File (EOF), which, in the context of network sockets, means "the other end of the connection has closed the socket."

**Comment by jstedfast** [comment]
Since you mentioned that everything worked fine for a while, what you may be experiencing is that the IMAP server has decided you have tried to connect/disconnect too many times in a short period of time and has now temporarily banned you from further connections.
