### ISSUE TITLE
Authenticate IMAP

### ISSUE THREAD

**Issue by Ramer** [jstedfast/MailKit#480]
Hello!

I have a strange problem with imap connection (troubles with server and/or transport) and it's very hard to connect (many timeouts). BUT if connection was established, it work great and fast.
So i need to authenticate to many mailboxes (one by one) via same connection (get all mailboxes from exchange database). When I call second auth method (for next mailbox), I have an exception - already authenticated.

How can I authenticate to second mailbox (deauthenticate from first) without disconnecting from server?

You are great! Thanks.

**Comment by jstedfast** [comment]
You can't. IMAP doesn't allow this.
