### ISSUE TITLE
folder.append fail on some multipart/mixed 

### ISSUE THREAD

**Issue by XavierDa** [jstedfast/MailKit#481]
So the target is an Exchange 2016 CU3 IMAP4, 

Ok i have been trying to locate the problem here for quite some days and i will post here so i "may" find an answer or a way to track more precisely the problem.

Long story short, i'm copying mails from one server to another.

So i have a ton of error with Folder.Append when appending multipart/mixed on an exchange 2016 CU3.
 I got the "Unable to write data to the transport connection. An existing connection was forcibly closed by the remote host."

It happens everytime at the same location of the stream for one mail . The main "thing" i see in the log is that when mailkit send the line "filename=?utf-8?Q?num=C3=A9risation0001=2Ejpg?="Content-Transfer-Encoding: base64/9j/4QOARXhpZgAASUkqAAgAAAAIAA8BAgADAAAASFAAAhA....." the is no \r\n in the log just one reallllly long line. (in fact it feels like it's trying to send one really long header when in fact it's trying to send the body of the mime)

If i look at the buffers that crashed the connection nothing really strange just a bunch of base64 chars. (no zeroed buffers)

The length of the mimecontent looks "ok", but it never reaches its full length. I can send bigger files without any issues. (and usually 

If you want i can send you the logs mails (i can't put them here because they have "little sensitive data" inside them (nothing big but can't just put them one the wild)

I tried "preparing" the msg with a low column max size but it seems that nothing change.

**Comment by jstedfast** [comment]
Yes, please send me the log and preferably the original message so that I can figure out why MailKit is not properly inserting \r\n.

Thanks.

**Comment by XavierDa** [comment]
Sent them to you via mail. Thank you.

**Comment by jstedfast** [comment]
Turns out not a bug in MailKit... phew! :)
