### ISSUE TITLE
Syntax error with folder named "NIL"

### ISSUE THREAD

**Issue by breedbekkikker** [jstedfast/MailKit#482]
Hi,

MailKit returns a syntax error when parsing a folder list that contains a folder named "NIL":

> Syntax error in untagged LIST response. Unexpected token: NIL

The IMAP protocol log:

> C: C00000005 LIST "" "%"
> S: * LIST (\HasNoChildren) "/" Drafts
> S: * LIST (\HasChildren) "/" INBOX
> S: * LIST (\HasNoChildren) "/" NIL
> S: * LIST (\HasNoChildren) "/" Sent
> S: * LIST (\HasNoChildren) "/" Spam
> S: * LIST (\HasNoChildren) "/" Trash
> S: C00000005 OK LIST completed

AFAIK a folder named "NIL" is allowed according to [RFC3501](https://tools.ietf.org/html/rfc3501#section-4.5).

Thanks,

**Comment by jstedfast** [comment]
Is there a physical folder named "NIL"? Or?

Because, according to rfc3501, the syntax is:

```
mailbox         = "INBOX" / astring
                    ; INBOX is case-insensitive.  All case variants of
                    ; INBOX (e.g., "iNbOx") MUST be interpreted as INBOX
                    ; not as an astring.  An astring which consists of
                    ; the case-insensitive sequence "I" "N" "B" "O" "X"
                    ; is considered to be INBOX and not an astring.
                    ;  Refer to section 5.1 for further
                    ; semantic details of mailbox names.

mailbox-data    =  "FLAGS" SP flag-list / "LIST" SP mailbox-list /
                   "LSUB" SP mailbox-list / "SEARCH" *(SP nz-number) /
                   "STATUS" SP mailbox SP "(" [status-att-list] ")" /
                   number SP "EXISTS" / number SP "RECENT"

mailbox-list    = "(" [mbx-list-flags] ")" SP
                   (DQUOTE QUOTED-CHAR DQUOTE / nil) SP mailbox
```

The untagged LIST response is made up of `mailbox-data` (the `"LIST" SP mailbox-list`).

`mailbox-list` allows `NIL` to appear as the namespace separator, but `mailbox` is required to either be `INBOX` or an `astring`.

In order to allow `NIL` as the mailbox name token, it would have to allow `nstring`:

```
nil             = "NIL"

nstring         = string / nil
```

I guess that you could argue that `NIL` taken literally as an atom string is possible(?), but that is in the realm of "undefined behavior".

**Comment by breedbekkikker** [comment]
Yes, there is a physical folder named "NIL" (without quotes).

Since mailbox name is an astring, I guess nil is not allowed... So NIL should be taken as an atom string?

The [RFC3501 ](https://tools.ietf.org/html/rfc3501#section-4.5)defines the situation of the mailbox name NIL:

        4.5.    NIL
              
        The special form "NIL" represents the non-existence of a particular
        data item that is represented as a string or parenthesized list, as
        distinct from the empty string "" or the empty parenthesized list ().
        
        Note: NIL is never used for any data item which takes the
        form of an atom.  For example, a mailbox name of "NIL" is a
        mailbox named NIL as opposed to a non-existent mailbox
        name.  This is because mailbox uses "astring" syntax which
        is an atom or a string.  Conversely, an addr-name of NIL is
        a non-existent personal name, because addr-name uses
        "nstring" syntax which is NIL or a string, but never an
        atom.

**Comment by jstedfast** [comment]
Ah, interesting... I missed that before. Thanks.

**Comment by jstedfast** [comment]
Out of curiosity, how did you discover this? It seems strange that someone would actually have a folder named `NIL` unless they were purposely trying to break IMAP clients and/or servers?

**Comment by breedbekkikker** [comment]
Thanks for your quick response!

I came across the syntax error since a client uses "NIL" as a folder name since it is actually an abbreviation :)

**Comment by jstedfast** [comment]
hah, odd coincidence.

**Comment by jstedfast** [comment]
Hmmm, good thing I just added a unit test. I needed to update the STATUS handler as well.

**Comment by jstedfast** [comment]
MimeKit & MailKit 1.14 have been released with this fix.
