### ISSUE TITLE
IMAP NO Login Failed

### ISSUE THREAD

**Issue by JackHazelden** [jstedfast/MailKit#483]
Hi there,

I've been attempting to retrieve mail via IMAP for multiple addresses on the same server - the only difference between the accounts is their usernames and passwords. One of the accounts fails with an Authentication Exception of LOGIN Failed.

Oddly enough the same account has no issue with authenticating when sending email, albeit via the SMTP client. So at least I can confirm that the password being used is correct.

Any help with this matter would be greatly appreciated.

Here is the log file that was produced:
```
Connected to imaps://imap.hs20.net:993/
S: * OK The Microsoft Exchange IMAP4 service is ready.
C: A00000000 CAPABILITY
S: * CAPABILITY IMAP4 IMAP4rev1 AUTH=PLAIN AUTH=NTLM AUTH=GSSAPI UIDPLUS MOVE ID CHILDREN IDLE NAMESPACE LITERAL+
S: A00000000 OK CAPABILITY completed.
C: A00000001 AUTHENTICATE PLAIN
S: +
C: XXXXXXXX
S: A00000001 NO AUTHENTICATE failed.
C: A00000002 LOGIN *****@*****.com *****
S: A00000002 NO LOGIN failed.
```

**Comment by jstedfast** [comment]
It seems that the server is refusing your login credentials (twice, both via `AUTHENTICATE PLAIN` and `LOGIN`), but it doesn't say why.

Some IMAP servers will reject a user if they've connected "too many" times in a short period. Perhaps that's the reason?

You'd have to ask your admin.

**Comment by JackHazelden** [comment]
Right, I'll see if I can find out whether that's the issue. Thanks for getting back so quickly, I'll let you know if there are any developments regarding the issue.

Cheers.

**Comment by Alim-Oezdemir** [comment]
@JackHazelden, did you find out a solution? I have the exact same problem.

**Comment by Gargamine** [comment]
I have the same problem.... trying to connect to exchange
With message saying "Failed to connect to mailbox. EAGetMail.MailServerException: A0002 NO LOGIN failed."
Any solution yet ?

**Comment by jstedfast** [comment]
@Gargamine have you looked at the protocol log?

**Comment by Alim-Oezdemir** [comment]
In my case it turned out to be a change made by the Office365-admin on one of the accounts, he disabled IMAP-access. He enabled it for me again with:
Exchange Control Panel ->
mailbox features ->
IMAP.Enabled -> Enabled

**Comment by Gargamine** [comment]
Thanks @Alim-Oezdemir for your answer. Enabling the IMAP protocol in the control panel worked.
Now I am getting the error "A0003 BAD User is authenticated but not connected." which may be cause by bad credentials or 2FA security.
Have you got a similar issue in the past by any chance?

**Comment by jstedfast** [comment]
The "BAD User is authenticated but not connected." error has been reported before, but I think it was on StackOverflow.

It's a bug in Exchange that happens if the password you provided was wrong. Exchange will act like you successfully authenticated when you didn't.

**Comment by Gargamine** [comment]
Will look into it and get back to you as soon as possible.
Thanks for your fast reply and accurate answers!

**Comment by saileshchandran** [comment]
Hi All,
  I too have the same issue. As per my logs I see this.
EAGetMail.MailServerException: A002 NO LOGIN failed.
   at ?.?(? ?, String ?)
   at ?.?(?& ?)
   at ?.?()
   at ?.?()
   at ?.?()
   at ?.?()
   at ?.?(MailServer ?)
   at EAGetMail.MailClient.Connect(MailServer server)
Does anyone have a solution for this?
Thanks,
Sailesh.

**Comment by jstedfast** [comment]
@saileshchandran You are using EAGetMail, not MailKit.

**Comment by bss-haresh-makwana** [comment]
MailKit.Security.AuthenticationException
  HResult=0x80131500
  Message=LOGIN failed.
  Source=MailKit
  StackTrace:
   at MailKit.Net.Imap.ImapClient.<AuthenticateAsync>d__103.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MailKit.Net.Imap.ImapClient.Authenticate(Encoding encoding, ICredentials credentials, CancellationToken cancellationToken)
   at MailKit.MailService.Authenticate(Encoding encoding, String userName, String password, CancellationToken cancellationToken)
   at MailKit.MailService.Authenticate(String userName, String password, CancellationToken cancellationToken)
