### ISSUE TITLE
Store attachments from GetMessage(uid) locally?

### ISSUE THREAD

**Issue by maddisn** [jstedfast/MailKit#487]
I am trying to download all the attachments contained in an email locally.
Sorry for raising a ticket, I have read *https://github.com/jstedfast/MailKit/issues/303* , and saw examples on stack, but I am unable to crack the question.

Here is my code so far.

    `public void getAtttachments()
        {
            using (var client = new ImapClient())
            {
                //authenticate
                client.Connect("imap.gmail.com", 993, SecureSocketOptions.SslOnConnect);
                client.Authenticate("secret", "secret");
                
                if (client.IsConnected == true)
                {
                    FolderAccess inboxAccess = client.Inbox.Open(FolderAccess.ReadWrite);
                    IMailFolder destination = client.GetFolder("Inbox");
                    IList<UniqueId> uids = client.Inbox.Search(SearchQuery.All);
                    string saveAttachmentPath = "C:\\Users\\mimeKitAttachments\\";

                    if (destination != null)
                    {
                        foreach (var x in uids)
                        {
                            var message = destination.GetMessage(x);

                            foreach (MimeEntity attachment in message.BodyParts)
                            {
                                //TODO: store the attachments with the original filename within the email to the local disk
                            }
                        }
                    }
                }
                else
                {
                    throw new NullReferenceException();
                }
            }
        }`

Is getting the *summary of a message* better than getting the *message*.
I just need the subject, body and all the attachments.
The attachments if able to store locally with the original filename and file type will be converted to a base64String to upload into our ticketing system.
Thanks.

**Comment by jstedfast** [comment]
See the FAQ: https://github.com/jstedfast/MailKit/blob/master/FAQ.md#SaveAttachments

You can use the same foreach logic with both `message.Attachments` and `message.BodyParts` (whichever one you prefer).

Note that `BodyParts` *includes* `Attachments`.

For you, I would recommend downloading the entire message and then iterating over the `Attachments` or `BodyParts`.

The message body is typically so small in comparison with the attachments that downloading the entire message will have less overhead than downloading each attachment individually due to the added back-and-forth chatter.

**Comment by maddisn** [comment]
I have a MimeMessage object that I am getting from the emails server, but when I do something like 

`  foreach (MimePart part in message.Attachments){}`

I get a "Cannot convert from MimeEntity to MimePart"

For now, I am not downloading the messages locally.
Can you please help, I am using the IList<UniqueID> to get all the message in my inbox.

**Comment by jstedfast** [comment]
If you look at the definition of the `Attachments` property, you will discover that it is `IEnumerable<MimeEntity>`. So change your `foreach` loop or else use `System.Linq` to limit the items you iterate over to just `MimePart` like so:

```csharp
foreach (MimePart part in message.Attachments.OfType<MimePart> ())
```

**Comment by maddisn** [comment]
I am still running into some issues, I have tried to mimic the code from: 
https://github.com/jstedfast/MailKit/issues/58
and
http://stackoverflow.com/questions/36227622/mailkit-save-attachments

Do you have any resources on a full-length example that shows how to download all the attachments from a given UniqueID

**Comment by jstedfast** [comment]
What issues are you running into?

**Comment by jstedfast** [comment]
The code in issue #58 was written *before* the `Attachments` property started enumerating `MimeEntity` (it used to enumerate `MimePart`).

Obviously, you will need to change the logic from that snippet.

**Comment by maddisn** [comment]
I am currently stuck at this part, and I do not know where to go from here. 
I looked at the examples on https://github.com/jstedfast/MailKit/blob/master/FAQ.md#SaveAttachments
Still cant seem to make sense out of it.

                    `foreach (UniqueId x in uids)
                        {
                            MimeMessage message = destination.GetMessage(x);

                            foreach (MimeEntity attachment in message.Attachments)
                            {
                              //Need to save all the attachments to a local disk
                            }   
                        }`
