### ISSUE TITLE
Could not load type 'MimeKit.Cryptography.MD5' from assembly ..." in dotnet core apps

### ISSUE THREAD

**Issue by alirizaadiyahsi** [jstedfast/MailKit#489]
When I try to use mailkit in dotnetcore `(<TargetFramework>netcoreapp1.1</TargetFramework>)` apps, we get this error.

I use example code that is in project readme page like following:

```csharp
using System;

using MailKit.Net.Smtp;
using MailKit;
using MimeKit;

namespace TestClient {
	class Program
	{
		public static void Main (string[] args)
		{
			var message = new MimeMessage ();
			message.From.Add (new MailboxAddress ("Joey Tribbiani", "joey@friends.com"));
			message.To.Add (new MailboxAddress ("Mrs. Chanandler Bong", "chandler@friends.com"));
			message.Subject = "How you doin'?";

			message.Body = new TextPart ("plain") {
				Text = @"Hey Chandler,

I just wanted to let you know that Monica and I were going to go play some paintball, you in?

-- Joey"
			};

			using (var client = new SmtpClient ()) {
				// For demo-purposes, accept all SSL certificates (in case the server supports STARTTLS)
				client.ServerCertificateValidationCallback = (s,c,h,e) => true;

				client.Connect ("smtp.friends.com", 587, false);

				// Note: since we don't have an OAuth2 token, disable
				// the XOAUTH2 authentication mechanism.
				client.AuthenticationMechanisms.Remove ("XOAUTH2");

				// Note: only needed if the SMTP server requires authentication
				client.Authenticate ("joey", "password");

				client.Send (message);
				client.Disconnect (true);
			}
		}
	}
}
```

I get error in following line

    client.Authenticate ("joey", "password");

StackTrace:

    at MailKit.Security.SaslMechanismCramMd5.Challenge(Byte[] token, Int32 startIndex, Int32 length)\r\n   at MailKit.Security.SaslMechanism.Challenge(String token)\r\n   at MailKit.Net.Smtp.SmtpClient.Authenticate(Encoding encoding, ICredentials credentials, CancellationToken cancellationToken)\r\n   at MailKit.MailService.Authenticate(String userName, String password, CancellationToken cancellationToken)\r\n   at ConsoleAppMailkit.Program.Main(String[] args) in c:\\users\\aliriza\\documents\\visual studio 2017\\Projects\\ConsoleAppMailkit\\ConsoleAppMailkit\\Program.cs:line 37

**Comment by jstedfast** [comment]
You need to use MimeKit 1.14.1

**Comment by marcwmiller** [comment]
I ran into same issue, and had to explicitly add the MimeKit package. Perhaps the MailKit nuget package dependencies need updating?

From: MimeKit (>= 1.14.0)
To: MimeKit (>= 1.14.1)

**Comment by jstedfast** [comment]
@marcwmiller thanks, I thought it already depended on 1.14.1

I guess I forgot to bump it when I made the release.

**Comment by jstedfast** [comment]
I just pushed 1.16 of both MimeKit and MailKit which solves the version dependency issue.

**Comment by marcwmiller** [comment]
Sweet - thx!

**Comment by andreujuanc** [comment]
I still get this error :(

**Comment by jstedfast** [comment]
Then you probably don't have 1.16

**Comment by andreujuanc** [comment]
I do !

**Comment by jstedfast** [comment]
1.16 of both MimeKit and MailKit? what is the exact error you are getting? What platform?
