### ISSUE TITLE
Cancelling Search or GetMessage causes client to disconnect

### ISSUE THREAD

**Issue by Xerillio** [jstedfast/MailKit#493]
I don't know if it's a bug or just me not grasping the usage of the CancellationToken correctly, since I couldn't find an explanation about it. I'm trying to make a simple mail client, so to show messages in a folder using the `ImapService` I do the following:

    static CancellationTokenSource _messagesTaskCts;
    IMailFolder _sourceFolder;

    async Task<ObservableCollection<MailMessage>> GetMessages()
    {
        try { _messagesTaskCts?.Cancel(); }
        catch (ObjectDisposedException) { /* The implicated task already finished */ }
        
        using (_messagesTaskCts = new CancellationTokenSource())
        {
            var cToken = _messagesTaskCts.Token;
            var messages = new ObservableCollection<MailMessage>();

            await _sourceFolder.OpenAsync(FolderAccess.ReadOnly).ConfigureAwait(false);
            var uids = (await _sourceFolder.SearchAsync(SearchQuery.All, cToken));

            foreach (var uid in uids)
            {
                var msg = await _sourceFolder.GetMessageAsync(uid, cToken);
                messages.Add(new MailMessage(msg));
            }

            return messages;
        }
    }

However, if one folder is currently trying to retrieve its messages and I want to start retrieving messages from another folder (i.e. cancel current task and start new) I end up getting a `ServiceNotConnectedException.cs` telling me that the client has been disconnected.

I expected that cancelling the token source would simply terminate the operation (be it `_sourceFolder.SearchAsync` or `_sourceFolder.GetMessageAsync`), but maybe that's not how I'm supposed to use the token?

Using MailKit v1.14.2 from NuGet

**Comment by jstedfast** [comment]
The way that cancellation works is that if a command is already in progress, it has to drop the connection (there's no other way).

The convention for doing cancellation should probably look a bit like this from your perspective:

```csharp
try {
    client.DoSomethingAsync (..., cancellationToken);
} catch (OperationCanceledException) {
    if (!client.IsConnected) {
        Reconnect ();
    }
}
```

**Comment by Xerillio** [comment]
Thanks for the quick response, that makes sense now. It also forces me to think about how to handle retrying any task that is using the client when it loses connection.

**Comment by jstedfast** [comment]
Glad that cleared things up :)
