### ISSUE TITLE
Syntax error in MODSEQ. Unexpected token: [atom: -1]

### ISSUE THREAD

**Issue by hpandroid** [jstedfast/MailKit#495]
Hi,

While I am trying to download emails from IMAP it is giving this error can any one help me to fix this is this a bug or any error.

Syntax error in MODSEQ. Unexpected token: [atom: -1]
Thanks

**Comment by jstedfast** [comment]
Please get me a [Protocol Log](https://github.com/jstedfast/MailKit/blob/master/FAQ.md#ProtocolLog)

It's impossible to debug the problem w/o that.

Thanks.

**Comment by jstedfast** [comment]
Your server is broken.

```
   An IMAP server that supports this extension MUST associate a positive
   unsigned 64-bit value called a modification sequence (mod-sequence)
   with every IMAP message.
```

```
   mod-sequence-value  = 1*DIGIT
                          ;; Positive unsigned 64-bit integer
                          ;; (mod-sequence)
                          ;; (1 <= n < 18,446,744,073,709,551,615)
```

Your server is sending a mod-sequence-value of `-1`.
