### ISSUE TITLE
Syntax error in ENVELOPE. Unexpected token: [qstring: "HTML"]

### ISSUE THREAD

**Issue by manit77** [jstedfast/MailKit#496]
I am pulling emails from GMAIL.  All was working fine until I sent email from IIS STMP to to the gmail server. This occurs on the Fetch function.

Syntax error in ENVELOPE. Unexpected token: [qstring: "HTML"]

var uids = client.Inbox.Search(MailKit.Search.SearchQuery.NotSeen);
            if (uids.Count > 0) {
                return client.Inbox.Fetch(uids, MessageSummaryItems.All | MessageSummaryItems.UniqueId | MessageSummaryItems.Body | MessageSummaryItems.BodyStructure | MessageSummaryItems.Envelope | MessageSummaryItems.Full | MessageSummaryItems.Size).ToList();
            } else {
                return new List<IMessageSummary>();
            }

**Comment by manit77** [comment]
The error message different if I change the MessageSummaryItems

**Comment by jstedfast** [comment]
Please get me a protocol log and I'll take a look. Thanks.

**Comment by jstedfast** [comment]
Did you get a protocol log yet?

**Comment by manit77** [comment]
I'd be glad to get that information to you. I know you put a lot of work on
this project. How do I get that information?

I deleted all the mail in the folder so I don't know if I can reproduce it.
I was testing your imap library by sending and downloading thousands of
emails over night. I can try to run the job again.




- Manit

**Comment by jstedfast** [comment]
You can read up on how to get the protocol log here: https://github.com/jstedfast/MailKit/blob/master/FAQ.md#ProtocolLog
