### ISSUE TITLE
Encoding support

### ISSUE THREAD

**Issue by alexwilsh** [jstedfast/MailKit#497]
I'm sending emails (html and plain text) on English, German and Russian.
I don't have any issues with English for now. But the text on German or Russian is spoiled.
Looks like the encoding is not applied or something like that. 
However, I can see that Content-type header is set to charset=utf8.

What I'm doing wrong?

My code looks like the following:
```
private async Task SendEmailAsync(SendEmailData sendEmailData)
{
	var emailMessage = new MimeMessage();
	emailMessage.From.Add(new MailboxAddress(Encoding.UTF8, sendEmailData.FromName, sendEmailData.FromEmail));
	emailMessage.To.Add(new MailboxAddress(Encoding.UTF8, sendEmailData.ToName, sendEmailData.ToEmail));
	
	// TODO: encoding issue in Subject if it contains German
	emailMessage.Subject = sendEmailData.Subject;

	BodyBuilder bodyBuilder = new BodyBuilder();
	if (sendEmailData.IsHtml)
	{
		bodyBuilder.HtmlBody = sendEmailData.Message;
	}
	else
	{
		bodyBuilder.TextBody = sendEmailData.Message;
	}
	if (sendEmailData.Attachments != null)
	{
		foreach (var attachment in sendEmailData.Attachments)
		{
			bodyBuilder.Attachments.Add(attachment.FileName, attachment.Stream);
		}
	}
	// TODO: encoding issue in Body if it contains German
	emailMessage.Body = bodyBuilder.ToMessageBody();

	using (var client = new SmtpClient())
	{
		await
			client.ConnectAsync(_smptSettings.SmtpHost, _smptSettings.SmtpPort, SecureSocketOptions.Auto)
				.ConfigureAwait(false);

		await client.SendAsync(options, emailMessage).ConfigureAwait(false);
		await client.DisconnectAsync(true).ConfigureAwait(false);
	}
}
```

In log file I can see the correct text in Body, but Subject looks exactly the same as I see it in email itself.

Thanks in advance for the help.

**Comment by jstedfast** [comment]
What log file? What does the message look like when saved to disk? What file are you attaching? Without test cases, there's nothing I can do.

**Comment by alexwilsh** [comment]
I've sent you additional info by email. 
Btw, I found the issue with Subject. I'm using HtmlEncoder and this spoils it.
But the issue with body is still there.
Thanks in advance for the help

**Comment by jstedfast** [comment]
This turned out to be not a bug in MimeKit/MailKit, but rather a bug in the SMTP server or receiving software.

Most likely the server software (or receiving client) is configured to (wrongly) assume that the text is in iso-8859-1 when it is not.

In other words, the server is using a `TextReader` with `Encoding.GetEncoding ("iso-8859-1")` to read the message, thereby corrupting the text.

**Comment by IvanBarbaric992** [comment]
Hello @jstedfast, I am using nuget Mailkit/Mime kite and everything works perfectly except Franch language encoding where I get an email with bad encoding of é and similar letters, this is the result: 
_Quelqu'un vient de r�pondre � votre commentaire,_ 
What do you suggest how to solve this? English and Italian works perfectly.  Thank you in advance.
