### ISSUE TITLE
How can we choose or set a specific cipher to establish the connection with pop server?

### ISSUE THREAD

**Issue by hpandroid** [jstedfast/MailKit#498]
Hi,

- What were you trying to do?
Trying to connect server with a specific cipher suite 

How can we choose or set a specific cipher to establish the connection with  pop server?
If this is possible can any one please provide me the example?

Thanks,
Harry

**Comment by jstedfast** [comment]
You can't. This is negotiated by the underlying [SslStream](https://msdn.microsoft.com/en-us/library/system.net.security.sslstream(v=vs.110).aspx) and it does not appear to allow you to specify the cipher algorithm.

**Comment by jstedfast** [comment]
If you are asking about setting the SSL/TLS versions to allow, you can checkout the [SslProtocols](http://www.mimekit.net/docs/html/P_MailKit_MailService_SslProtocols.htm) property.
