### ISSUE TITLE
Is this the proper way to access folders / sub-folders?

### ISSUE THREAD

**Issue by maddisn** [jstedfast/MailKit#500]
I have a folder with 2 levels of cascading subfolders.
I found this snippet from the issues: 

```csharp
IMailFolder personal = client.GetFolder(EmailConstant.EnrollmentStudentServicesFolder);
foreach (IMailFolder folder in personal.GetSubfolders())
{
    //do Things
}
```

Is this the right way to access subfolders within folders?
I have a main folder with 5 subfolders, and these 5 subfolders again branch off into several subfolders.
Would I just use the same line of code to access all the subfolders, or is there a special recursive function of some sort within the MailKit framework?

Can you please provide me with a code snippet?
![image](https://cloud.githubusercontent.com/assets/25490236/25559388/ce192a4a-2d06-11e7-85b6-beb9f8745f53.png)

Thanks.

**Comment by maddisn** [comment]
The subfolders continue to one more level within the 5 subfolders under the "Enrollment..." folder,

**Comment by jstedfast** [comment]
You need to call GetSubfolders on each folder that can contain subfolders.

You can also take a look at the ImapClientDemo sample included in the source repo: https://github.com/jstedfast/MailKit/blob/master/samples/ImapClientDemo/ImapClientDemo/FolderTreeView.cs
