### ISSUE TITLE
Proxy Settings

### ISSUE THREAD

**Issue by jcnovoa** [jstedfast/MailKit#501]
When attempting to implement MailKit (POP/SMTP) behind a proxy, I did not find a way to set the proxy value/port (authentication where applicable).
I would think this should be an attribute/property of the URL/Host object or a parameter in an overloaded method to include a proxy object when sending/receiving messages.
Is this by design, or am I missing something?

**Comment by jstedfast** [comment]
The way to use proxies in MailKit is to use the `Connect()` overload that takes a `Socket` argument. You need to connect to your proxy yourself and then provide the socket to MailKit once you've connected.

**Comment by adam-b-maurer** [comment]
I see how you provide Proxy support via the Socket overload, but it does not appear you directly support authentication to that proxy.

Consider a scenario where your proxy *must* be setup to use TLS but the SMPT Server is setup to use SSL *and* you have no control over the Smpt server's settings.

**Comment by jstedfast** [comment]
Hmmm, I didn't consider that. I suppose I;'d have to have a Connect() method that takes a Stream instead of a socket wouldn't I?

**Comment by adam-b-maurer** [comment]
That was what I was thinking.  Honestly, it isn't much of an issue for us right now because we *should* always be using TLS I think... however, if it ever comes up it would be nice to have the option.

**Comment by fipso** [comment]
Hey,
is there any example about how to do this with a Socks5 Proxy ?
I already have a working Socket that is connected to my Proxy Server.
The Proxy Server (Socks5) is connected to the IMAP, but the IMAP closes connection.

https://gist.github.com/fipso/e98c745d8b54bdcc40d22e83cc063392

`Unhandled Exception:
MailKit.Net.Imap.ImapProtocolException: The IMAP server has unexpectedly disconnected.
  at MailKit.Net.Imap.ImapStream.ReadAhead.......
`

Thanks.
Have a nice day

**Comment by jstedfast** [comment]
@fipso you probably need to pass `SecureSocketOptions.SslOnConnect` to the Connect method.

**Comment by jstedfast** [comment]
MailKit 2.1.0 now has support for Socks4 and Socks5 proxies.
