### ISSUE TITLE
Is it OK to connect with Gmail using SMTP to send email while already connected using IMAP?

### ISSUE THREAD

**Issue by maddisn** [jstedfast/MailKit#505]
This is more of a general question, but I am parsing emails using IMAP for a C# program. I also want to send out some notification emails using SMTP while I am connected to Gmail using IMAP.
I read that IMAP is not useful for sending emails.

I was wondering if this is OK. I did try it, and it works fine, just something lingering. 

    `  using (var imapClient = new ImapClient())
       {
	      //connect with IMAP and do stuff..

	       using (SmtpClient smtpClient = new SmtpClient())
	      {
		  //while already connected with IMAP, connect again to send emails
		  smtpClient.Disconnect(true);
	      }
	         imapClient.Disconnect(true);
        }`

**Comment by jstedfast** [comment]
Yes. Of course. Why wouldn't it be?

**Comment by maddisn** [comment]
Thanks, Is there anything that can go bad if you do not disconnect from either the SMTP / IMAP client?

**Comment by jstedfast** [comment]
nope
