### ISSUE TITLE
ProtocolLogger: Shouldn't the caller decide when to dispose the log stream

### ISSUE THREAD

**Issue by axunonb** [jstedfast/MailKit#506]
Jeff
Shouldn't the caller decide when the stream used for ```ProtocolLogger``` should be disposed?
Currently, disposing ```SmtpClient``` also disposes the log stream.
Simplified code:
```csharp
var logStream = new MemoryStream();
var smtpClient = new SmtpClient(new MailKit.ProtocolLogger(logStream));

smtpClient.Connect("smtp.1and1.com", 25);
smtpClient.Dispose();

// Logic for taking care of the log is in a different part of the code
logStream.Position = 0;  // raising ObjectDisposedException
var reader = new StreamReader(logStream);
var log = reader.ReadToEnd();
```
Cheers,
Norbert

**Comment by jstedfast** [comment]
Not really, no, because the protocol logger disposes the stream when the .ctor takes a filename parameter.

I can add a leaveOpen param for the Stream .ctor, though.

How is that?

**Comment by axunonb** [comment]
That is perfect for the use case I described. 
Thanks for quick response and even implementation!

**Comment by grokky1** [comment]
@jstedfast Yeah this is exactly what I need too, but it isn't included in the latest nuget. 😢  When do you expect the next release to be?

**Comment by jstedfast** [comment]
waiting on people to get back to me with info needed to fix some reported bugs. once I get that info and fix the bugs, I'll make a release. Hoping it comes soon.

**Comment by grokky1** [comment]
How did @axunonb use this new code if it hasn't been released ❓

**Comment by jstedfast** [comment]
He probably used the source code?

**Comment by grokky1** [comment]
Oh wow then he was more desperate than me 😃 I'll wait for the nuget!
