### ISSUE TITLE
MailKit it's worked on Amazon server

### ISSUE THREAD

**Issue by uthens** [jstedfast/MailKit#507]
Hi MaiKit team, 
This issue to relate on : https://github.com/jstedfast/MailKit/issues/471

It's working good on azure, but when we tested on Amazon web server we found on this message.
![screen shot 2560-05-09 at 12 26 19 pm](https://cloud.githubusercontent.com/assets/10783170/25836748/8677eb90-34b3-11e7-96cb-9dee56c003bc.png)

I don't make sure some services on Amazon is block MailKit services ? or HTTPS issue ?

**Note: On Amazon we used HTTPS port, on Azure we only used HTTP port.**

Best, 
Uthen

**Comment by jstedfast** [comment]
NSIndexSet is an Apple Foundation Framework error which doesn't make sense to me. Are you using Mac or iOS API's somewhere?

That error doesn't appear to be related to MailKit at all.

**Comment by jstedfast** [comment]
btw, the error states that it was expecting an error code between 200 and 299 but it got 404 - 404 is an HTTP(s) error code saying the url does not exist.

**Comment by xamaringeek** [comment]
@jstedfast 
I used iOS app with EF core API thanks you for comment i will re-check on our app today.
Best

**Comment by uthens** [comment]
@jstedfast Thanks you for comment we used iOS app i will more research on this i think IIS on Amazon it's block some services.

**Comment by uthens** [comment]
Now it's fixed on IIS web server the cause of the problem from URLSCAN to block send email.
Thanks you for all suggestion.
