### ISSUE TITLE
MailboxAddress.TryParse

### ISSUE THREAD

**Issue by StMilan** [jstedfast/MailKit#508]
MailboxAddress address;
Method MailboxAddress.TryParse("-", out address) return true. Also passing ParserOptions as additional argument doesn't help either.

**Comment by jstedfast** [comment]
I would argue that this is necessary behavior because the parser needs to be forgiving in what it accepts.

**Comment by jstedfast** [comment]
What is the scenario in which you are actually feeding the parser this value expecting it not to work?
