### ISSUE TITLE
The address of the sender

### ISSUE THREAD

**Issue by bebravebaby** [jstedfast/MailKit#509]
how can I get the sender's address? (from) and compare it with the desired email

**Comment by jstedfast** [comment]
Have you checked the From property of the MimeMessage?

**Comment by bebravebaby** [comment]
I got an InternetAddress, but I can't get email form email@domen.com

**Comment by jstedfast** [comment]
InternetAddress is a base class. You need to cast to a MailboxAddress and then use the Address property
