### ISSUE TITLE
InvalidOperationException: Can not find compilation library location for package 'system.text.encoding.codepages'

### ISSUE THREAD

**Issue by cyberh0me** [jstedfast/MailKit#512]
with Visual Studio 2017 (15.2, 26430.6) as soon as i add MailKit (1.16.1) as NuGet package to a "ASP.NET Core Web Application (.NET Core)" project (ASP.NET Core 1.1) the project compiles but shows an Internal Server Error

>	An unhandled exception occurred while processing the request.
>	InvalidOperationException: Can not find compilation library location for package 'system.text.encoding.codepages'
>	Microsoft.Extensions.DependencyModel.CompilationLibrary.ResolveReferencePaths()
>	
>	Stack Query Cookies Headers 
>	
>	InvalidOperationException: Can not find compilation library location for package 'system.text.encoding.codepages'
>	Microsoft.Extensions.DependencyModel.CompilationLibrary.ResolveReferencePaths()
>	System.Linq.Enumerable+<SelectManyIterator>d__159.MoveNext()
>	Microsoft.AspNetCore.Mvc.Razor.Compilation.MetadataReferenceFeatureProvider.PopulateFeature(IEnumerable<ApplicationPart> parts, MetadataReferenceFeature feature)
>	Microsoft.AspNetCore.Mvc.ApplicationParts.ApplicationPartManager.PopulateFeature<TFeature>(TFeature feature)
>	Microsoft.AspNetCore.Mvc.Razor.Internal.RazorReferenceManager.GetCompilationReferences()
>	System.Threading.LazyInitializer.EnsureInitializedCore<T>(ref T target, ref bool initialized, ref object syncLock, Func<T> valueFactory)
>	Microsoft.AspNetCore.Mvc.Razor.Internal.RazorReferenceManager.get_CompilationReferences()
>	Microsoft.AspNetCore.Mvc.Razor.Internal.DefaultRoslynCompilationService.CreateCompilation(string compilationContent, string assemblyName)
>	Microsoft.AspNetCore.Mvc.Razor.Internal.DefaultRoslynCompilationService.Compile(RelativeFileInfo fileInfo, string compilationContent)
>	Microsoft.AspNetCore.Mvc.Razor.Internal.RazorCompilationService.Compile(RelativeFileInfo file)
>	Microsoft.AspNetCore.Mvc.Razor.Internal.CompilerCache.CreateCacheEntry(string relativePath, string normalizedPath, Func<RelativeFileInfo, CompilationResult> compile)
>	System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>	System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>	Microsoft.AspNetCore.Mvc.Razor.Internal.CompilerCache.GetOrAdd(string relativePath, Func<RelativeFileInfo, CompilationResult> compile)
>	Microsoft.AspNetCore.Mvc.Razor.Internal.DefaultRazorPageFactoryProvider.CreateFactory(string relativePath)
>	Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine.CreateCacheResult(HashSet<IChangeToken> expirationTokens, string relativePath, bool isMainPage)
>	Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine.OnCacheMiss(ViewLocationExpanderContext expanderContext, ViewLocationCacheKey cacheKey)
>	Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine.LocatePageFromViewLocations(ActionContext actionContext, string pageName, bool isMainPage)
>	Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine.FindView(ActionContext context, string viewName, bool isMainPage)
>	Microsoft.AspNetCore.Mvc.ViewEngines.CompositeViewEngine.FindView(ActionContext context, string viewName, bool isMainPage)
>	Microsoft.AspNetCore.Mvc.ViewFeatures.Internal.ViewResultExecutor.FindView(ActionContext actionContext, ViewResult viewResult)
>	Microsoft.AspNetCore.Mvc.ViewResult+<ExecuteResultAsync>d__26.MoveNext()
>	System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>	System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>	Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker+<InvokeResultAsync>d__30.MoveNext()
>	System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>	System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>	Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker+<InvokeNextResultFilterAsync>d__28.MoveNext()
>	System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>	Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ResultExecutedContext context)
>	Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
>	Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker+<InvokeNextResourceFilter>d__22.MoveNext()
>	System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>	Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ResourceExecutedContext context)
>	Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
>	Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker+<InvokeAsync>d__20.MoveNext()
>	System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>	System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>	Microsoft.AspNetCore.Builder.RouterMiddleware+<Invoke>d__4.MoveNext()
>	System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>	System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>	Microsoft.AspNetCore.Authentication.AuthenticationMiddleware+<Invoke>d__18.MoveNext()
>	System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>	Microsoft.AspNetCore.Authentication.AuthenticationMiddleware+<Invoke>d__18.MoveNext()
>	System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>	System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>	Microsoft.AspNetCore.Authentication.AuthenticationMiddleware+<Invoke>d__18.MoveNext()
>	System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>	Microsoft.AspNetCore.Authentication.AuthenticationMiddleware+<Invoke>d__18.MoveNext()
>	System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>	System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>	Microsoft.AspNetCore.Authentication.AuthenticationMiddleware+<Invoke>d__18.MoveNext()
>	System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>	Microsoft.AspNetCore.Authentication.AuthenticationMiddleware+<Invoke>d__18.MoveNext()
>	System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>	System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>	Microsoft.AspNetCore.Authentication.AuthenticationMiddleware+<Invoke>d__18.MoveNext()
>	System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>	Microsoft.AspNetCore.Authentication.AuthenticationMiddleware+<Invoke>d__18.MoveNext()
>	System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>	System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>	Microsoft.VisualStudio.Web.BrowserLink.BrowserLinkMiddleware+<ExecuteWithFilter>d__7.MoveNext()
>	System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>	System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>	Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.MigrationsEndPointMiddleware+<Invoke>d__5.MoveNext()
>	System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>	System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>	Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware+<Invoke>d__6.MoveNext()
>	System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>	Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware+<Invoke>d__6.MoveNext()
>	System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>	System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>	Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware+<Invoke>d__7.MoveNext()
>	
>	Show raw exception details 
>	System.InvalidOperationException: Can not find compilation library location for package 'system.text.encoding.codepages'
>	
>	   at Microsoft.Extensions.DependencyModel.CompilationLibrary.ResolveReferencePaths()
>	   at System.Linq.Enumerable.<SelectManyIterator>d__159`2.MoveNext()
>	   at Microsoft.AspNetCore.Mvc.Razor.Compilation.MetadataReferenceFeatureProvider.PopulateFeature(IEnumerable`1 parts, MetadataReferenceFeature feature)
>	   at Microsoft.AspNetCore.Mvc.ApplicationParts.ApplicationPartManager.PopulateFeature[TFeature](TFeature feature)
>	   at Microsoft.AspNetCore.Mvc.Razor.Internal.RazorReferenceManager.GetCompilationReferences()
>	   at System.Threading.LazyInitializer.EnsureInitializedCore[T](T& target, Boolean& initialized, Object& syncLock, Func`1 valueFactory)
>	   at Microsoft.AspNetCore.Mvc.Razor.Internal.RazorReferenceManager.get_CompilationReferences()
>	   at Microsoft.AspNetCore.Mvc.Razor.Internal.DefaultRoslynCompilationService.CreateCompilation(String compilationContent, String assemblyName)
>	   at Microsoft.AspNetCore.Mvc.Razor.Internal.DefaultRoslynCompilationService.Compile(RelativeFileInfo fileInfo, String compilationContent)
>	   at Microsoft.AspNetCore.Mvc.Razor.Internal.RazorCompilationService.Compile(RelativeFileInfo file)
>	   at Microsoft.AspNetCore.Mvc.Razor.Internal.CompilerCache.CreateCacheEntry(String relativePath, String normalizedPath, Func`2 compile)
>	--- End of stack trace from previous location where exception was thrown ---
>	   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>	   at Microsoft.AspNetCore.Mvc.Razor.Internal.CompilerCache.GetOrAdd(String relativePath, Func`2 compile)
>	   at Microsoft.AspNetCore.Mvc.Razor.Internal.DefaultRazorPageFactoryProvider.CreateFactory(String relativePath)
>	   at Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine.CreateCacheResult(HashSet`1 expirationTokens, String relativePath, Boolean isMainPage)
>	   at Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine.OnCacheMiss(ViewLocationExpanderContext expanderContext, ViewLocationCacheKey cacheKey)
>	   at Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine.LocatePageFromViewLocations(ActionContext actionContext, String pageName, Boolean isMainPage)
>	   at Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine.FindView(ActionContext context, String viewName, Boolean isMainPage)
>	   at Microsoft.AspNetCore.Mvc.ViewEngines.CompositeViewEngine.FindView(ActionContext context, String viewName, Boolean isMainPage)
>	   at Microsoft.AspNetCore.Mvc.ViewFeatures.Internal.ViewResultExecutor.FindView(ActionContext actionContext, ViewResult viewResult)
>	   at Microsoft.AspNetCore.Mvc.ViewResult.<ExecuteResultAsync>d__26.MoveNext()
>	--- End of stack trace from previous location where exception was thrown ---
>	   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>	   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeResultAsync>d__30.MoveNext()
>	--- End of stack trace from previous location where exception was thrown ---
>	   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>	   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextResultFilterAsync>d__28.MoveNext()
>	--- End of stack trace from previous location where exception was thrown ---
>	   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>	   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ResultExecutedContext context)
>	   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
>	   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
>	--- End of stack trace from previous location where exception was thrown ---
>	   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>	   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ResourceExecutedContext context)
>	   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
>	   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeAsync>d__20.MoveNext()
>	--- End of stack trace from previous location where exception was thrown ---
>	   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>	   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
>	--- End of stack trace from previous location where exception was thrown ---
>	   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>	   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
>	--- End of stack trace from previous location where exception was thrown ---
>	   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>	   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
>	--- End of stack trace from previous location where exception was thrown ---
>	   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>	   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
>	--- End of stack trace from previous location where exception was thrown ---
>	   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>	   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
>	--- End of stack trace from previous location where exception was thrown ---
>	   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>	   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
>	--- End of stack trace from previous location where exception was thrown ---
>	   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>	   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
>	--- End of stack trace from previous location where exception was thrown ---
>	   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>	   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
>	--- End of stack trace from previous location where exception was thrown ---
>	   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>	   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
>	--- End of stack trace from previous location where exception was thrown ---
>	   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>	   at Microsoft.VisualStudio.Web.BrowserLink.BrowserLinkMiddleware.<ExecuteWithFilter>d__7.MoveNext()
>	--- End of stack trace from previous location where exception was thrown ---
>	   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>	   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.MigrationsEndPointMiddleware.<Invoke>d__5.MoveNext()
>	--- End of stack trace from previous location where exception was thrown ---
>	   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>	   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.<Invoke>d__6.MoveNext()
>	--- End of stack trace from previous location where exception was thrown ---
>	   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>	   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.<Invoke>d__6.MoveNext()
>	--- End of stack trace from previous location where exception was thrown ---
>	   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>	   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()

how can i fix that ?

**Comment by jstedfast** [comment]
I have no idea. Make sure you target netstandard >= 1.3?
