### ISSUE TITLE
Multiline ContentDisposition FileName not returned correctly.

### ISSUE THREAD

**Issue by julianhall** [jstedfast/MailKit#514]
Hi - I'm trying to get the filenames of the attachments in certain emails via IMAP.
In some cases we throw errors because the filename is returned without the extension.

I've used your ImapFolder.getStream() to dump the raw email: 

```csharp
var mkw = (MailKitWrapper)ctx.getObj("object.Imap." + name);

            using (var stream = File.Create(Path.Combine(location, fileName)))
            {
                //ImapFolder.GetStream()
                var msgStream = mkw.Folder.GetStream(mkw.MsgSummary.UniqueId,0, checked((int)mkw.MsgSummary.Size));
                msgStream.CopyTo(stream);
            }
```
and looked at the output: and it seems that the file name is of this format:

```
 --=-H4RUP7w2Rhdeuacuuv1j/Q==
 Content-Type: application/octet-stream;
 	name*0="hawwers_mutual (inv 1).64-197-1846172.2017.05.19.12.02.51.653.x.pdf.";
 	name*1=xml
 Content-Disposition: attachment;
 	filename*0="hawwers_mutual (inv 1).64-197-1846172.2017.05.19.12.02.51.653.x.";
 	filename*1=pdf.xml
Content-Transfer-Encoding: base64
```

I'm unable to get the full Attachment name (IE filename*0+filename*1) when I access it this way:
```csharp
 mkw.MsgSummary= mkw.Folder.Fetch(new List<UniqueId> { mkw.OrderedUids[idx].UniqueId }, MessageSummaryItems.Full | MessageSummaryItems.BodyStructure | MessageSummaryItems.UniqueId )
                                        .FirstOrDefault();

foreach (var m in MsgSummary.Attachments) {
    var attachmentFileName = m.FileName;//Not with extension here.
}
```

Is there a work around or am I doing something wrong?

Thanks,

Julian

**Comment by jstedfast** [comment]
Well, I don't know because your query doesn't request the raw message, it requests a pre-parsed form from the imap server. For all we know right now, the bug is in the imap server.

This is why I ask for the protocol logs for new issues 😇

**Comment by julianhall** [comment]
Ah - Sorry I'll read up on adding the protocol logs.   This is contacting office 365.   I was hoping someone has seen the 'filename' split into multiple lines before :)

Can you point me in the right direction on how to request the raw message to help debug this?

thanks,

Julian

**Comment by jstedfast** [comment]
Yes, but the following code does not operate on raw messages:

 mkw.MsgSummary= mkw.Folder.Fetch(new List<UniqueId> { mkw.OrderedUids[idx].UniqueId }, MessageSummaryItems.Full | MessageSummaryItems.BodyStructure | MessageSummaryItems.UniqueId )
                                        .FirstOrDefault();

foreach (var m in MsgSummary.Attachments) {
    var attachmentFileName = m.FileName;//Not with extension here.
}

I bet that if you iterate over the MimeMessage that you get back from the GetMessage call, you'll find that you get the full file name 😇

**Comment by jstedfast** [comment]
In fact I know you will because I have unit tests for this 😇

**Comment by julianhall** [comment]
Hi - I haven't had the chance yet to try and pull the full message to see if that works properly.  (Will do today at some point.) But I was thinking about what you said:

> I bet that if you iterate over the MimeMessage that you get back from the GetMessage call, you'll find that you get the full file name

Even if that works, I don't think it will be a viable solution for me - as the inbox I'm polling has too many messages with attachments and I'd be pulling too much data.  I need to work on the summary data.

I was looking into this a bit and according to [rfc2231 ](https://tools.ietf.org/html/rfc2231) the multiline concept is specified.
 
there is a section that mentions thinks like 
```
 Content-Disposition: attachment;
 	filename*0="hawwers_mutual (inv 1).64-197-1846172.2017.05.19.12.02.51.653.x.";
 	filename*1=pdf.xml
```
   is semantically identical to
```
 Content-Disposition: attachment;
 	filename="hawwers_mutual (inv 1).64-197-1846172.2017.05.19.12.02.51.653.x.pdf.xml";
```

I probably can't read RFC's to your level - but could this be a feature that was missed in your library?
thanks again,

Julian

**Comment by jstedfast** [comment]
*sigh*

Yes. I know about rfc2231 and I'm sure that it's implemented and I'm also sure that it works. Like I said, I have unit tests for that.

This is hy I said if you download the full message using GetMessage() and then iterate over the `MimeMessage.Attachments` property, you will find that this  works as expected.

What *I'm* saying is that when you request `MessageSummaryItems.BodyStructure` in a `Fetch()` request, you do not get back the raw message or MIME part headers. What you get back are pre-parsed values in a LISP-like expression which has nothing to do with rfc2231.

This is why I absolutely need the protocol log that includes the `FETCH` response for the particular message that you are having issues with. From there, we can figure out if there is a bug in MailKit or a bug in the IMAP server.

**Comment by jstedfast** [comment]
BTW, it takes literally 2 seconds to get a protocol log: https://github.com/jstedfast/MailKit/blob/master/FAQ.md#ProtocolLog

I didn't link that to you yesterday because I was on an Amtrak train with spotty wireless using my phone to reply. A Google search of "mailkit protocol log" also returns that link in the first match.

**Comment by julianhall** [comment]
Ah - gotcha.  OK I'll go get the protocol logs ;) Sorry, lack of knowledge on my end. 

I did see that, and it looks fairly trivial.  I just need to deploy the change into a 'prod' like environment to reproduce... will update shortly.

**Comment by jstedfast** [comment]
Cool, thanks :)

**Comment by julianhall** [comment]
Here is the protocol log when attempting to get the file name from the earlier:

```c#
 mkw.MsgSummary= mkw.Folder.Fetch(new List<UniqueId> { mkw.OrderedUids[idx].UniqueId }, MessageSummaryItems.Full | MessageSummaryItems.BodyStructure | MessageSummaryItems.UniqueId )
                                        .FirstOrDefault();

foreach (var m in MsgSummary.Attachments) {
    var attachmentFileName = m.FileName;//Not with extension here.
}
```

[imap.protocol.scrubbed.txt](https://github.com/jstedfast/MailKit/files/1017312/imap.protocol.scrubbed.txt)

I've 'scrubbed' out the body and the authentication. with [** REMOVED **] sections.

Do you need me to also do this again, but downloading the full message? 

Julian

**Comment by jstedfast** [comment]
No, the log is sufficient.

```
C: A00000011 UID FETCH 161 (UID FLAGS INTERNALDATE RFC822.SIZE ENVELOPE BODYSTRUCTURE)
S: * 145 FETCH (UID 161 FLAGS () INTERNALDATE "19-May-2017 07:34:58 -0400" RFC822.SIZE 83625 ENVELOPE ("Fri, 19 May 2017 11:34:52 +0000" "Invoice from Lewis, Brisbois, Bisgaard & Smith LLP for Claim 20140457" ((NIL NIL "noreply" "cloud-trade.net")) NIL NIL ((NIL NIL "pat" "hawwersmutualnc.com")) NIL NIL NIL "<0100015c207d294d-59e75301-ef55-4dc5-8fdf-249f5e3bb7e0-000000@email.amazonses.com>") BODYSTRUCTURE ((("text" "html" ("charset" "utf-8") NIL NIL "7BIT" 3862 189 NIL NIL NIL NIL)("application" "octet-stream" ("name" "hawwers_mutual (inv 1).64-197-1846172.2017.05.19.12.02.51.653.x.pdf.") NIL NIL "base64" 6672 NIL ("attachment" ("filename" "hawwers_mutual (inv 1).64-197-1846172.2017.05.19.12.02.51.653.x.")) NIL NIL) "mixed" ("boundary" "=-H4RUP7w2Rhdeuacuuv1j/Q==") NIL NIL)("application" "octet-stream" ("name" "hawwers_mutual (inv 1).64-197-1846172.2017.05.19.12.02.51.653.x.pdf.") NIL NIL "base64" 40326 NIL ("attachment" ("filename" "hawwers_mutual (inv 1).64-197-1846172.2017.05.19.12.02.51.653.x.")) NIL NIL) "mixed" ("boundary" "=-1YNWiSlo24v6uC58NH//bA==") NIL NIL))
S: A00000011 OK FETCH completed.
C: A00000012 UID FETCH 161 (BODY.PEEK[1.1.MIME] BODY.PEEK[1.1])
S: * 145 FETCH (BODY[1.1.MIME] {251}
S: Content-Type: text/html; charset=utf-8
S: X-Microsoft-Exchange-Diagnostics:
S: 	1;BN6PR13MB1828;27:t6hAwSUElyvORHmIYTFDWck23d3Ccjy+AOqbB77GzmwHAMB+EiYN7NlfXFQ/daQKzXHrtZYe9TjDkC9en52N8S2le3xQPBHxX2GT+Al2f0j/yhTiiAozmmQtEI+DHXN61H6+EVjMirN9/QbZbpwbdA==
S: 
S:  BODY[1.1] {3862}
S: <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd"><html xmlns="http://www.w3.org/1999/xhtml" lang="en-GB" xml:lang="en-GB"><head>
S: [****BODY REMOVED****]
S: </body>
S: </html>
S: 
S:  UID 161)
S: A00000012 OK FETCH completed.
C: A00000013 UID FETCH 161 (BODY.PEEK[1.1.MIME] BODY.PEEK[1.1])
S: * 145 FETCH (BODY[1.1.MIME] {251}
S: Content-Type: text/html; charset=utf-8
S: X-Microsoft-Exchange-Diagnostics:
S: 	1;BN6PR13MB1828;27:t6hAwSUElyvORHmIYTFDWck23d3Ccjy+AOqbB77GzmwHAMB+EiYN7NlfXFQ/daQKzXHrtZYe9TjDkC9en52N8S2le3xQPBHxX2GT+Al2f0j/yhTiiAozmmQtEI+DHXN61H6+EVjMirN9/QbZbpwbdA==
S: 
S:  BODY[1.1] {3862}
S: <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd"><html xmlns="http://www.w3.org/1999/xhtml" lang="en-GB" xml:lang="en-GB"><head>
S: [****BODY REMOVED****]
S: </html>
S: 
S:  UID 161)
S: A00000013 OK FETCH completed.
C: A00000014 UID FETCH 161 (BODY.PEEK[1.1.MIME] BODY.PEEK[1.1])
S: * 145 FETCH (BODY[1.1.MIME] {251}
S: Content-Type: text/html; charset=utf-8
S: X-Microsoft-Exchange-Diagnostics:
S: 	1;BN6PR13MB1828;27:t6hAwSUElyvORHmIYTFDWck23d3Ccjy+AOqbB77GzmwHAMB+EiYN7NlfXFQ/daQKzXHrtZYe9TjDkC9en52N8S2le3xQPBHxX2GT+Al2f0j/yhTiiAozmmQtEI+DHXN61H6+EVjMirN9/QbZbpwbdA==
S: 
S:  BODY[1.1] {3862}
S: <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd"><html xmlns="http://www.w3.org/1999/xhtml" lang="en-GB" xml:lang="en-GB"><head>
S: [****BODY REMOVED****]
S: </html>
S: 
S:  UID 161)
S: A00000014 OK FETCH completed.
C: A00000015 UID FETCH 161 (BODY.PEEK[1.2.MIME] BODY.PEEK[1.2])
S: * 145 FETCH (BODY[1.2.MIME] {517}
S: Content-Type: application/octet-stream;
S: 	name*0="hawwers_mutual (inv 1).64-197-1846172.2017.05.19.12.02.51.653.x.pdf.";
S: 	name*1=xml
S: Content-Disposition: attachment;
S: 	filename*0="hawwers_mutual (inv 1).64-197-1846172.2017.05.19.12.02.51.653.x.";
S: 	filename*1=pdf.xml
S: Content-Transfer-Encoding: base64
S: X-Microsoft-Exchange-Diagnostics:
S: 	1;BN6PR13MB1828;27:t6hAwSUElyvORHmIYTFDWck23d3Ccjy+AOqbB77GzmwHAMB+EiYN7NlfXFQ/daQKzXHrtZYe9TjDkC9en52N8S2le3xQPBHxX2GT+Al2f0j/yhTiiAozmmQtEI+DHXN61H6+EVjMirN9/QbZbpwbdA==
S: 
S:  BODY[1.2] {6672}
S: PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0idXRmLTgiPz4NCjxjWE1MIHhtbDpsYW5nPSJl
S: [****BODY REMOVED****]
S: cXVlc3Q+DQogIDwvUmVxdWVzdD4NCjwvY1hNTD4=
S:  UID 161)
```

As we can see here, with UID 161, it contains the following MIME headers:

```
Content-Type: application/octet-stream;
	name*0="hawwers_mutual (inv 1).64-197-1846172.2017.05.19.12.02.51.653.x.pdf.";
	name*1=xml
Content-Disposition: attachment;
	filename*0="hawwers_mutual (inv 1).64-197-1846172.2017.05.19.12.02.51.653.x.";
	filename*1=pdf.xml
Content-Transfer-Encoding: base64
```

but the server is providing us with the following pre-parsed header values:

```
S: * 145 FETCH (UID 161 FLAGS () INTERNALDATE "19-May-2017 07:34:58 -0400" RFC822.SIZE 83625 ENVELOPE ("Fri, 19 May 2017 11:34:52 +0000" "Invoice from Lewis, Brisbois, Bisgaard & Smith LLP for Claim 20140457" ((NIL NIL "noreply" "cloud-trade.net")) NIL NIL ((NIL NIL "pat" "hawwersmutualnc.com")) NIL NIL NIL "<0100015c207d294d-59e75301-ef55-4dc5-8fdf-249f5e3bb7e0-000000@email.amazonses.com>") BODYSTRUCTURE ((("text" "html" ("charset" "utf-8") NIL NIL "7BIT" 3862 189 NIL NIL NIL NIL)("application" "octet-stream" ("name" "hawwers_mutual (inv 1).64-197-1846172.2017.05.19.12.02.51.653.x.pdf.") NIL NIL "base64" 6672 NIL ("attachment" ("filename" "hawwers_mutual (inv 1).64-197-1846172.2017.05.19.12.02.51.653.x.")) NIL NIL) "mixed" ("boundary" "=-H4RUP7w2Rhdeuacuuv1j/Q==") NIL NIL)("application" "octet-stream" ("name" "hawwers_mutual (inv 1).64-197-1846172.2017.05.19.12.02.51.653.x.pdf.") NIL NIL "base64" 40326 NIL ("attachment" ("filename" "hawwers_mutual (inv 1).64-197-1846172.2017.05.19.12.02.51.653.x.")) NIL NIL) "mixed" ("boundary" "=-1YNWiSlo24v6uC58NH//bA==") NIL NIL))
```

Take special note of the following:

```
("name" "hawwers_mutual (inv 1).64-197-1846172.2017.05.19.12.02.51.653.x.pdf.")
```

and

```
("filename" "hawwers_mutual (inv 1).64-197-1846172.2017.05.19.12.02.51.653.x.")
```

Does that look correct to you?

I think we just found the source of the problem :)

Your IMAP server is broken.

**Comment by julianhall** [comment]
Thank you.  

Great - So the Microsoft office365.com IMAP server isn't' handling this correctly? Hmm, that's a shame. 

What are my work arounds? 

(I did manage to do what you said - and getting the full message and iterating over the Attachments collection did work... but I'd like to avoid downloading the full message just to read the attachment file names .....if at all possible.)

_On another note - I'd like like to make a donation for all your time and effort - where can I do so?_

Julian

**Comment by jstedfast** [comment]
I'm not sure what you can do as a reliable workaround from the IMAP client side of things.

Do you have control over the sending client? If so, perhaps you could try shortening the file name to avoid the need for using rfc2231 encodings?

If you are using MimeKit/MailKit to *send* the message containing those pdf's, you could also optionally override the default behavior of encoding the filenames with rfc2231 by following these instructions to use the rfc2047 encoding instead: https://github.com/jstedfast/MailKit/blob/master/FAQ.md#UntitledAttachments

As far as donations, you can donate here via Paypal: https://pledgie.com/campaigns/29300

**Comment by julianhall** [comment]
I'll look into discussing the shortening of the filename from the provider of the emails.
I'll _attempt_ to raise a ticket with O365. 
Might look into a solution - to see if i can identify a message by subject - then download the full message and extract the filename from that.
Thanks again - donation sent. 

Julian

**Comment by jstedfast** [comment]
if you can add me to the bug report you file against O365, feel free to add jestedfa@microsoft.com

I'll argue with them if I have to :)

**Comment by julianhall** [comment]
Awesome.

**Comment by julianhall** [comment]
Hi Jeff - I've 'raised' a ticket with Microsoft via the support in the O365 portal... I've now had 3 call backs asking me to go over the issue again and again.  Not sure if it is being escalated every time or not.
Is there another avenue that you know of to raise bugs like these with Microsoft?

**Comment by jstedfast** [comment]
I'm pretty new at Microsoft, so unfortunately I don't :(

Feel free to let them know that I can help explain the problem. I want to help you get this fixed.

**Comment by jstedfast** [comment]
I just explained the situation to someone at Microsoft and it sounds like this is now being directed toward the EXO IMAP team and I've let them know that I will be happy to answer any questions the EXO IMAP team may have (I suspect they'll understand the problem right away).

Just wanted to give you a status update.

Don't hesitate to redirect them back to me if they ask you for any IMAP protocol details. I won't mind :)

**Comment by julianhall** [comment]
Excellent news... thanks for that.  I just got an email saying that they talked to you.
After the 6th call back, and 6th time explaining the situation... I was ready to give up!
If you do need the reference the case number it is 617052393414012.

Julian

**Comment by jstedfast** [comment]
No problem :)
