### ISSUE TITLE
SmtpClient.Connect() throws exception "The token supplied to the function is invalid (Exception from HRESULT: 0x80090308)"

### ISSUE THREAD

**Issue by zipswich** [jstedfast/MailKit#519]
Trying to send a message as following:
```
using (SmtpClient sc = new SmtpClient())
{
    sc.Connect("mail.mydomain.com", 465);
    ...
}

```
Stack trace:
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
  at MailKit.Net.Smtp.SmtpClient.Connect(String host, Int32 port, SecureSocketOptions options, CancellationToken cancellationToken)

Please let me know if this the diagnosis of exception requires the log.

**Comment by jstedfast** [comment]
Doesn't look like a bug in MailKit, it looks like a bug in some lower-level code in the core libs.

**Comment by zipswich** [comment]
Is there anything that I can do to find the culprit?  When I change "mail.mydomain.com" to "smtp.mydomain.com", the exception is replaced by something like host cannot be resolved.   I have just added smtp.mydomain.com to the MX record (not sure if this is the right thing to do).  I will see if helps.  I assume it takes some time for the new setting to propagate.

**Comment by jstedfast** [comment]
I doubt it has anything to do with the hostname.

**Comment by zipswich** [comment]
sc.Connect("smtp.google.com", 465) generates the following error:
No such host is known. (Exception from HRESULT: 0x80072AF9)

I have added a MX record for smtp.mydomain.com, and I can ping smtp.mydomain.com successfully, but sc.Connect(" smtp.mydomain.com", 465)  also throws exception "No such host is known".

**Comment by jstedfast** [comment]
Try stepping thru the debugger in this code to see what the problem is:

https://github.com/jstedfast/MailKit/blob/master/MailKit/Net/Smtp/SmtpClient.cs#L819

**Comment by zipswich** [comment]
Hallelujah! It is working finally as following:
`sc.Connect("mail.mydomain.com", 465, MailKit.Security.SecureSocketOptions.None);`

The key is MailKit.Security.SecureSocketOptions.None.

**Comment by jstedfast** [comment]
Why did you put a plaintext SMTP server on port 465? 465 is for SSL-wrapped SMTP.

**Comment by zipswich** [comment]
I vaguely remember the choice is related to spam or attack. That port is perceived to be abused less.  I could be wrong.

**Comment by jstedfast** [comment]
my point was that you chose the SSL port and decided not to enable SSL on the server. Very odd choice to make.

**Comment by zipswich** [comment]
SmarterMail calls 465 as Alternate SMTP port.   I remember vaguely that some ISPs (e.g. Xfinity) blocks the default SMTP port 25.

**Comment by jstedfast** [comment]
You don't seem to understand what I'm saying.

I'm sure they block 25, but the other standard plaintext SMTP port is not 465, it's 587. 465 is for SSL-wrapped SMTP. In other words, you *SHOULD* need `SecureSocketOptions.SslOnConnect` for port 465.

You can use google to verify what I'm saying.

**Comment by jstedfast** [comment]
http://www.jscape.com/blog/smtp-ports

**Comment by zipswich** [comment]
I feel that I understand your point only to a degree.  The main part that I  miss is the downside of using port 465 in this way.  It has been like this for about 5 years.
![smartmailports](https://user-images.githubusercontent.com/6095671/26976801-705fa67e-4cf3-11e7-8de9-51af2350f23f.png)

**Comment by jstedfast** [comment]
People expect port 465 to be SSL-enabled.

**Comment by zipswich** [comment]
OK.  I see the point.  This is an email server exclusively for the internal use of a small startup.
