### ISSUE TITLE
Skipping certificate validation altogether

### ISSUE THREAD

**Issue by dkekesi** [jstedfast/MailKit#520]
I have an application that sits behind a firewall with no internet access. When I connect to an IMAPS server that has a certificate issued by VeriSign, MailKit will go and try to retrieve certificate revocation information (CRL or OCSP), but it will obviously fail.
I use this method to ignore certificate errors:

`client.ServerCertificateValidationCallback = (sender, certificate, chain, sslPolicyErrors) =>
            {
                return true;
            };`

While this will indeed prevent exceptions caused by lack of CRL/OCSP access, there's a major issue with the approach. This callback only processes the _results_ of certificate validation, thus making me wait for the timeout while the server tries to retrieve revocation data. It is around 1 minute by default, which is a real pain to wait at every connection attempt.

Is there a way to tell MailKit to skip certificate validation altogether, without even trying to do anything (especially going online)?

**Comment by jstedfast** [comment]
Is there a way to tell SslStream to skip validation? I haven't seen one. So.... no.

**Comment by jstedfast** [comment]
Found a way.

**Comment by dkekesi** [comment]
Wow, that was fast. Thanks a million. This is **_EXACTLY_** why MailKit/MimeKit is the best. Period.

**Comment by dkekesi** [comment]
Do you plan to make a new release that contains this feature in the near future? Thanks.

**Comment by jstedfast** [comment]
Yes. I'm hoping to make a release this weekend but I'm waiting on some feedback on some patches for NTLM fixes.
