### ISSUE TITLE
Not able to send an email through office365 

### ISSUE THREAD

**Issue by kpcauchi** [jstedfast/MailKit#524]
Hi there,

I am trying to send an email through office 365 through mailkit (.net core 1.1) but it is giving me an authentication failed error.

Error: MailKit.Security.AuthenticationException: Authentication failed.
   at MailKit.Net.Smtp.SmtpClient.Authenticate(Encoding encoding, ICredentials credentials, CancellationToken cancellationToken)
   at MailKit.MailService.Authenticate(String userName, String password, CancellationToken cancellationToken)
   at ConsoleApp1.Program.Main(String[] args) in C:\Users\kcauc\OneDrive\Documents\Visual Studio 2017\Projects\ConsoleApp1\ConsoleApp1\Program.cs

Here is my code: 
`                string Subject = "Hello World - Sending email using ASP.NET Core 1.1";
                string BodyContent = "test.";

                //Smtp Server 
                string SmtpServer = "smtp.office365.com";
                //Smtp Port Number 
                int SmtpPortNumber = 587;

                var mimeMessage = new MimeMessage();
                mimeMessage.From.Add(new MailboxAddress(FromAddress));
                mimeMessage.To.Add(new MailboxAddress(ToAddress));
                mimeMessage.Subject = Subject;
                mimeMessage.Body = new TextPart("plain")
                {
                    Text = BodyContent

                };

                using (var client = new SmtpClient())
                {

                    client.Connect(SmtpServer, SmtpPortNumber, false);
                    // Note: only needed if the SMTP server requires authentication 
                    // Error 5.5.1 Authentication  
                    client.Authenticate(FromAddress, GetPassword());
                    client.Send(mimeMessage);
                    Console.WriteLine("The mail has been sent successfully !!");
                    Console.ReadLine();
                    client.Disconnect(true);

                }`

When switching to .Net Framework 4.5, using System.Net.Mail, it works fine.

Because of this, I assume the issue is coming from MailKit.

Any help?

Thanks

P.S. Yes, the credentials are ok.

**Comment by jstedfast** [comment]
Already fixed yesterday. Update your MailKit source code and try again.

**Comment by jstedfast** [comment]
Actually, might not be the same issue. The issue I fixed emitted SmtpCommandException rather than AuthenticationException due to a bug in authmech fallback.

If you want this bug to be fixed, send me a protocol log (jestedfa@microsoft.com). Without it, there's nothing I can do.

**Comment by kpcauchi** [comment]
Actually I just found out it works when I do  `client.AuthenticationMechanisms.Remove("XOAUTH2");` before the authenticate.. 

maybe that's a hint?

**Comment by jstedfast** [comment]
Yea, you need to do that on servers that support oauth2 unless you are using an oath token.
