### ISSUE TITLE
Unable to code Connect Method (Socket, String, Int32, SecureSocketOptions, CancellationToken)

### ISSUE THREAD

**Issue by Carneno** [jstedfast/MailKit#525]
Hello,

If I try to use this code to connect an Imap client:
```csharp
Socket tcpSocket = new Socket(AddressFamily.InterNetwork, SocketType.Stream, ProtocolType.Tcp);
client.ServerCertificateValidationCallback = (s, c, h, e) => true;
client.Connect(tcpSocket, mailbox.Host, mailbox.ServerPortNumber, mailbox.UseSsl);
client.AuthenticationMechanisms.Remove("XOAUTH2");
client.Authenticate(mailbox.User, mailbox.Password);
var inbox = client.Inbox;
inbox.Open(FolderAccess.ReadOnly);
```

The **tcpSocket** in the client.Connect statement, gives the error: **Argument 1: cannot convert from 'System.Net.Sockets.Socket' to 'string'**

I think I am coding this in the correct way, but I am not sure of why the intellisense will not allow me to do that.

I expected that it would be accepted since the first parameter of the Connect method is typed as a System.Net.Sockets.Socket.

Any help that you can provide to resolve this issue would be gratefully appreciated.

Thanks,
Tony

**Comment by jstedfast** [comment]
Please provide the exact exception message and the StackTrace value. Thanks

**Comment by jstedfast** [comment]
Oh, I bet the problem is that you are using a bool value for `useSsl` and there is no `Connect` method that takes a `Socket` and a `bool` for `useSsl`. You need to replace your `mailbox.UseSsl` with a `SecureSocketOptions` value.

**Comment by Carneno** [comment]
Jeffrey,

Thanks for your quick response and help.

Yes, the problem is I was using a bool value for useSsl.

It works now.

Tony
