### ISSUE TITLE
Client Timeout property

### ISSUE THREAD

**Issue by Carneno** [jstedfast/MailKit#526]
Hello,

When I use this code:
`
                    using (var client = new ImapClient())
                    {
                         client.Timeout = 5000;
                         client.ServerCertificateValidationCallback = (s, c, h, e) => true;
                         client.Connect(mailbox.Host, mailbox.ServerPortNumber, mailbox.UseSsl);
                         client.AuthenticationMechanisms.Remove("XOAUTH2");
                         client.Authenticate(mailbox.User, mailbox.Password);
                         var inbox = client.Inbox;
                         inbox.Open(FolderAccess.ReadOnly);

`

The client.Connect still takes about two minutes to error out.  I thought the Timeout property of 5000 would change that to five seconds.

Any help that you can provide to make the Timeout property work would be gratefully appreciated.

Thanks,
Tony

**Comment by jstedfast** [comment]
The timeout only affects sending and receiving of data, not the connection timeout.

If you want to set a timeout on the connection process, you need to connect your own `Socket` and then pass that into the `Connect` method.

**Comment by Carneno** [comment]
Jeffrey,

Thank for your continued support and for the excellent product that you have provided.

I did try to use a socket connection and got an error.  Do you have any examples of how to connect using a socket?

Thanks,
Tony

**Comment by jstedfast** [comment]
I'm not sure how to connect with a timeout, but you can more-or-less copy the logic in https://github.com/jstedfast/MailKit/blob/master/MailKit/Net/Imap/ImapClient.cs#L1252

```csharp
var ipAddresses = Dns.GetHostAddresses (hostName);
Socket socket = null;

for (int i = 0; i < ipAddresses.Length; i++) {
	socket = new Socket (ipAddresses[i].AddressFamily, SocketType.Stream, ProtocolType.Tcp);

	try {
		cancellationToken.ThrowIfCancellationRequested ();

		if (LocalEndPoint != null)
			socket.Bind (LocalEndPoint);

		socket.Connect (ipAddresses[i], port);
		break;
	} catch (OperationCanceledException) {
		socket.Dispose ();
		throw;
	} catch {
		socket.Dispose ();

		if (i + 1 == ipAddresses.Length)
			throw;
	}
}
```

And then of course you'd do something like this once you have a connected socket:

```csharp
client.Connect (socket, hostName, port);
```

As far as how to connect w/ a timeout, I'm not sure if `ConnectAsync` with a timed `CancellationToken` would work, but you could try that... if it works, let me know, because I might be able to add that to MailKit's `Connect()` implementation if it does.

e.g.

```csharp
using (var cancellationTokenSource = new CancellationTokenSource (new TimeSpan (0, 0, 1)) {
    await socket.ConnectAsync (ipAddresses[i], port, cancellationTokenSource.Token);
}
```

I suspect that won't work, but it might be worth trying. It would be the cleanest way to do it if it does.

**Comment by Carneno** [comment]
Jeffrey,

I'm sorry, but I don't feel that I have the knowledge of how to make this work in my environment.  I'm getting errors on cancellationToken and LocalEndPoint and I do not know enough to code where and how those objects are defined.

I appreciate very much all you have done to help me.

Thanks,
Tony
