### ISSUE TITLE
bug with enoding iso-8859-1  and ContentEncoding.SevenBit

### ISSUE THREAD

**Issue by Yambr** [jstedfast/MailKit#530]
if i call TextBody when message is not html and encoded with sevenbit

i get this https://pastebin.com/raw/AieT2JaH

but if i use this for TextPart
`if (!textPart.IsHtml && textPart.ContentTransferEncoding == ContentEncoding.SevenBit)
{    
    return textPart.GetText(Encoding.UTF8);
}`

result of decode is ok  - "Значение не равно 0 более 10 минут"

I will be glad if someday this will be fixed)

But I will use as is)

**Comment by jstedfast** [comment]
The Content-Transfer-Encoding header is ignored for decoding text content (other than base64 or quoted-printable). Only the charset parameter is used from the Content-Type header.

**Comment by jstedfast** [comment]
Sounds like this is a bug in the sending client, not MimeKit.
