### ISSUE TITLE
Question: How to get the message headers (like X-....)

### ISSUE THREAD

**Issue by Sicos1977** [jstedfast/MailKit#533]
Hi,

I now use below code to get MessageSummary items to get information about the message. I also want to retrieve the headers. Is it possible to do it somehow in the same call or do I need to use the client.Inbox.GetHeaders(result[0].Index); method on each message?

```
client.Inbox.Open(FolderAccess.ReadOnly);

const MessageSummaryItems items =
	MessageSummaryItems.UniqueId |
	MessageSummaryItems.Flags |
	MessageSummaryItems.Envelope |
	MessageSummaryItems.Body |
	MessageSummaryItems.Size;

var fields = new HashSet<HeaderId> {HeaderId.Importance};
var result = client.Inbox.Count == 0
	? new IMessageSummary[0]
	: client.Inbox.Fetch(0, -1, items, fields);

//var test = client.Inbox.GetHeaders(result[0].Index);

client.Inbox.Close();
```

**Comment by Sicos1977** [comment]
And is it also possible to check if a message has attachments without retrieving the entire message?

**Comment by jstedfast** [comment]
The `Fetch()` API is really designed to just get back a specified list of named headers and not the full header block of each message. So right now, you'll have to use `GetHeaders()` *unless* you can specify which X- headers you want:

```csharp
var fields = new HashSet<string> ({ "X-Mailer", "X-Priority", "X-Loop" });
var result = folder.Fetch (0, -1, items, fields);
```

As far as determining if a message has attachments or not, what you can do is include `MessageSummaryItems.BodyStructure` and then check the `IMessageSummary`'s `Attachments` property like so:

```csharp
if (item.Attachments.Any ())
```

**Comment by Sicos1977** [comment]
Thanks

**Comment by ravikumarjella** [comment]
HI 
i followed the same but i am getting headers as null. this is my code : 
  var headerFields = new HashSet<string> { "X-MS-Has-Attach", "X-Mailer", "X-Priority", "X-Loop" };
var result = folder.Fetch (0, -1, items, fields);
