### ISSUE TITLE
question: How can I tell whether a protocol logger is attached?

### ISSUE THREAD

**Issue by grokky1** [jstedfast/MailKit#534]
I am reusing an instance of `SmtpClient` and passing it around the app. When logging I need to know if a protocol logger is attached.

I checked the source, and figured this out:

    var loggerIsAttached = !(client.ProtocolLogger is NullProtocolLogger);

But this isn't documented, so please just let me know if I can safely depend on this behavior?

---
Also, is it possible to get the underlying stream? `ProtocolLogger ` doesn't expose it. If you're passing the client around, and you're not near the original callsite, then you won't have a reference to the `MemoryStream`. So would be nice to be able to get it from the client or logger or somewhere?

**Comment by grokky1** [comment]
Just checked the source, so I guess this is it:

    var loggerIsAttached = !(smtpClient.ProtocolLogger is NullProtocolLogger);

This isn't documented, so please just let me know if I can depend on this behavior?

**Comment by jstedfast** [comment]
Yes, that will work. It's not possible to get the stream from a ProtocolLogger, but you could implement a custom IProtocolLogger that lets you get at it. I mostly just included the default ProtocolLogger class to illustrate how to use it and for the simple debugging cases.

**Comment by lonix1** [comment]
Creating a custom ProtocolLogger just to expose (change private to public) the stream is like reinventing the wheel because the default one is already there and works nicely.

Exposing the stream is very useful for the reasons mentioned by the OP.

**Comment by jstedfast** [comment]
You don't need to reinvent the wheel, just do this:

```csharp
class MyProtocolLogger : ProtocolLogger
{
    public MyProtocolLogger (Stream stream) : base (stream)
    {
        MyStream = stream;
    }

    public Stream MyStream {
        get; private set;
    }
}
```

**Comment by lonix1** [comment]
I think that's part of what the OP was trying to say, passing in the stream means we need to keep a refrence to it in the container, or something like that (which is what I do).

Whereas if the underlying logger exposed it then we wouldn't need to, and could do

````cs
public MySmtpClient() : base(new ProtocolLogger(new MemoryStream(), leaveOpen:false)) {
````

and if we need to inspect the logs, we could do

````cs
smtpClient.ProtocolLogger.Stream
````
