### ISSUE TITLE
STATUS of NonExistent folder should reset IMailFolder properties

### ISSUE THREAD

**Issue by ekalchev** [jstedfast/MailKit#536]
I am moving this discussion from stackoverflow here
https://stackoverflow.com/questions/44853388/mailkit-foldercache-and-deleted-folder

After the response below Mailkit doesn't update cached folder UIDVALIDITY, UIDNEXT, index and etc. I believe it should. 
Jeffrey you said: 
The UID is the same as the old cached version because your server is not responding to the STATUS (UIDVALIDITY) request. This appears to be a bug in your server

However I think: 
	
This is a wild guess but I believe there is no UIDVALIDITY in the response because the folder has attribute \NonExistent. If it does not exist it shouldn't have UIDVALIDITY, UIDNEXT and etc. I am thinking... may be when Mailkit notice the presence of \NonExistent should clear the cached folder properties even if there is no response for UIDVALIDITY, UIDNEXT and etc because you can imply the these values by \NonExistent. What do you think Jeffrey? The server is Dovecot, i'll try this scenario with gmail to see the outcome.

That is Dovecot
C: A00000102 LIST "" "INBOX.spam.%" RETURN (SUBSCRIBED CHILDREN STATUS (UIDVALIDITY)) S: * LIST (\NonExistent \HasChildren) "." INBOX.spam.op S: A00000102 OK List completed (0.001 + 0.000 secs).
That is GMAIL

C: B00000057 LIST "" "INBOX/test/%" RETURN (SUBSCRIBED CHILDREN STATUS (UIDVALIDITY))
S: * LIST (\HasChildren \NonExistent \Subscribed) "/" "INBOX/test/omg"
S: B00000057 OK Success

It seems both GMail and Dovecot doesn't return UIDVALIDITY for non-existent folders. I also asked Dovecot support and they said:

[20:25] <cmouse> Emooo: also it says INBOX.spam.op is nonexistent but has children. 
[20:25] <cmouse> Emooo: there can't be UID validity for nonexistent folder. 

With that said I think the correct behavior of Mailkit should be to reset the values of UIDVALIDITY, UIDNEXT, index and etc to default values.

**Comment by jstedfast** [comment]
already implemented

**Comment by ekalchev** [comment]
Wow, that you!
