### ISSUE TITLE
question: Fake in-memory SMTP server for testing

### ISSUE THREAD

**Issue by grokky1** [jstedfast/MailKit#537]
@jstedfast Hope for advice relating to testing.

I'm doing integration tests with `SmtpClient`. I'm using the Polly library, to handle all sorts of complicated retries and fallback policies. But I need to test that when the server responds in a certain way, my code takes appropriate action.

There used to be an in-memory SMTP server called [`nDumbster`](https://github.com/EdenRidgway/nDumbster), for unit/integration testing. But it hasn't been updated in years, and doesn't support netcore, so I can't use it anymore.

It needs to be within the tests, so not an external app like papercut, smtp4dev, etc.

Do you use an in-memory tool like this, or just mock the send methods? Or maybe there's some other way I've not considered?

**Comment by jstedfast** [comment]
Best I can offer is what you'll find in my own unit tests. They use an internal ReplayConnect method, but you could modify your own fork of MailKit to make that public or add an InternalsVisibleTo for your own test harness

**Comment by lonix1** [comment]
If you folks use linux, can recommend how you test?

On Windows we used to use "papercut" or "smtp4dev" fake mail servers. Have you found a good alternative for *nix?

**Comment by lonix1** [comment]
@jstedfast Thanks for that idea, I didn't think of that.

In the meantime though I found something called ["MailHog"](https://github.com/mailhog/MailHog) which is similar to Papercut (but it's for *nix) and it's really good. Hope that helps someone.

**Comment by artur-intech** [comment]
> 

https://github.com/sj26/mailcatcher
