### ISSUE TITLE
Unable to authenticate with APOP

### ISSUE THREAD

**Issue by yadavmukul1986** [jstedfast/MailKit#539]
Hi jstedfast,

I am facing the same problem at one of my clients. I have checked out latest Mailkit version (1.16). Client Email Server is APOP. Screens are attached for your reference. Command prompt displayed is from my windows application and text file is from Protocol Logger, enabled in MailKit. I have made following change for APOP - 

client.AuthenticationMechanisms.Remove("XOAUTH2");
client.AuthenticationMechanisms.Remove("APOP");

Please suggest how to do an APOP from mailkit as i am stuck now. 

![apop](https://user-images.githubusercontent.com/9866319/28167581-ad662a72-67f9-11e7-9ead-19fe31a3ed81.png)

**Comment by jstedfast** [comment]
The latest is 1.16.2 and has an APOP fix, please upgrade and try again.

**Comment by jstedfast** [comment]
BTW, the problem is that your server is disconnecting after a failed APOP authentication attempt.

Also, as the docs explain, to disable APOP authentication, do this:

```csharp
client.Capabilities &= ~Pop3Capabilities.Apop;
```

**Comment by yadavmukul1986** [comment]
Thank you so much, that was very quick. I'l try as suggested.

**Comment by jstedfast** [comment]
Then it probably means that your POP3 server doesn't properly implement APOP support :\

**Comment by yadavmukul1986** [comment]
Ok. Thanks for the information.
