### ISSUE TITLE
Error sending email through SmtpClient to an Office 365 server

### ISSUE THREAD

**Issue by robsonfelix** [jstedfast/MailKit#541]
I keep receiving the exception bellow...

> System.NotSupportedException: No compatible authentication mechanisms found.

However I am able to successfully send the same message using System.Net.SmptClient with the same parameters. I am trying with the same contents (from, to, subject and header) and all of them are plain-text.

I already tried to understand how this is not working by reading the trace files for the socket on both cases. What I see is that when the credentials are being sent, something seems to be different. Probably due to the authentication mechanism used at first on Authenticate. I see that on both cases the "Microsoft Unified Security Protocol Provider" is chosen. I see on the bytes being send that the header is the same and rest of the bytes are the same - after the 1st LF til the end.

I **am** able to send messages to other server types (including gmail) but not Office 365. I can successfully use MailKit for reading messages with Office 365 but not SMTP.

I tried to change parameters such as StartTls, Ssl, etc, but nothing happens.

I am going nuts here trying to figure out what is going on... Thoughts?

My code snippets are:

**System.Net.SmptClient**

```csharp
RemoteCertificateValidationCallback certificateValidation = (sender, cert, chain, sslPolicyErrors) => true;

ServicePointManager.ServerCertificateValidationCallback += certificateValidation;

var client = new System.Net.Mail.SmtpClient(_host, _port);
client.Credentials = new NetworkCredential(_user, _pwd);
client.DeliveryMethod = System.Net.Mail.SmtpDeliveryMethod.Network;
client.EnableSsl = true;
client.ServicePoint.Expect100Continue = false;
client.Send(_user, _to, _subject, _body);

ServicePointManager.ServerCertificateValidationCallback -= certificateValidation;
```
**MailKit**

````csharp
RemoteCertificateValidationCallback certificateValidation = (sender, cert, chain, sslPolicyErrors) => true;

var logger = new ProtocolLogger(@"smtp.log");
var client = new MailKit.Net.Smtp.SmtpClient(logger);
client.CheckCertificateRevocation = false;
client.ServerCertificateValidationCallback += certificateValidation;
client.Connect(_host, _port, MailKit.Security.SecureSocketOptions.StartTls);
client.AuthenticationMechanisms.Remove("XOAUTH2");
client.Authenticate(Encoding.ASCII, new NetworkCredential(_user, _pwd));
client.Send(email);
client.Disconnect(true);

ServicePointManager.ServerCertificateValidationCallback -= certificateValidation;

**Comment by jstedfast** [comment]
Can you post the contents of the smtp.log?

The error suggests that the list of authentication mechanisms that your Office365 server supports are not compatible with the list of authentication mechanisms that MailKit supports.

MailKit supports only the following mechanisms:

XOAUTH2, SCRAM-SHA-256, SCRAM-SHA-1, CRAM-MD5, DIGEST-MD5, PLAIN, and LOGIN.

It does not support anything called "Microsoft Unified Security Protocol Provider".
