### ISSUE TITLE
Syntax error in response. Unexpected token: [atom: <meta]

### ISSUE THREAD

**Issue by Sicos1977** [jstedfast/MailKit#542]
When I try to move a message from mailbox A to mailbox B on a Exchange 2013 server I get the error 

`Syntax error in response. Unexpected token: [atom: <meta]`

The ********* in the log are no errors but just private information that I removed.

Any idea how to fix this?

```
Connected to imap://server:143/
S: * OK The Microsoft Exchange IMAP4 service is ready.
C: A00000000 CAPABILITY
S: * CAPABILITY IMAP4 IMAP4rev1 AUTH=PLAIN STARTTLS UIDPLUS MOVE ID CHILDREN IDLE NAMESPACE LITERAL+
S: A00000000 OK CAPABILITY completed.
...
...
C: A00000002 CAPABILITY
S: * CAPABILITY IMAP4 IMAP4rev1 AUTH=PLAIN UIDPLUS MOVE ID CHILDREN IDLE NAMESPACE LITERAL+
S: A00000002 OK CAPABILITY completed.
C: A00000003 NAMESPACE
S: * NAMESPACE (("" "/")) NIL NIL
S: A00000003 OK NAMESPACE completed.
C: A00000004 LIST "" "INBOX"
S: * LIST (\Marked \HasNoChildren) "/" INBOX
S: A00000004 OK LIST completed.
C: A00000005 SELECT INBOX
S: * 0 EXISTS
S: * 0 RECENT
S: * FLAGS (\Seen \Answered \Flagged \Deleted \Draft $MDNSent)
S: * OK [PERMANENTFLAGS (\Seen \Answered \Flagged \Deleted \Draft $MDNSent)] Permanent flags
S: * OK [UIDVALIDITY 14] UIDVALIDITY value
S: * OK [UIDNEXT 849] The next unique identifier value
S: A00000005 OK [READ-WRITE] SELECT completed.
C: A00000006 APPEND INBOX {51944+}
C: Subject: Re: We received a registration with the municipality
C: Message-Id: <L04CG97JW1U4.8J1G8D1IPZ1X1@Email2Storage.com>
C: From: *******<*********>
C: To: ********
C: Date: Thu, 20 Jul 2017 13:06:04 +0200
C: MIME-Version: 1.0
C: Content-Type: text/html; charset=utf-8
C: Content-Id: <4CWHG97JW1U4.VILM23L8W7M81@********>
C: 
C: <meta 
```

**Comment by Sicos1977** [comment]
This is how I build the message that I try to write directly into a persons mailbox

```
        internal MimeMessage ToMimeMessage(
            List<string> headersToInclude,
            string messageIdDomain = null)
        {
            var mimeMessage = new MimeMessage();

            if (!string.IsNullOrWhiteSpace(messageIdDomain))
                mimeMessage.MessageId = MimeKit.Utils.MimeUtils.GenerateMessageId(messageIdDomain);

            SetMimeMessageCustomHeaders(mimeMessage, headersToInclude);

            mimeMessage.From.Add(new MailboxAddress(FromAddress.DisplayName, FromAddress.Address));

            foreach (var to in ToAddress)
                mimeMessage.To.Add(new MailboxAddress(to.DisplayName, to.Address));

            foreach (var cc in CcAddress)
                mimeMessage.Cc.Add(new MailboxAddress(cc.DisplayName, cc.Address));

            mimeMessage.Bcc.Clear();
            //foreach (var bcc in email.BccAddress)
            //    mimeMessage.Bcc.Add(new MailboxAddress(bcc.DisplayName, bcc.Address));

            switch (Priority)
            {
                case EmailPriority.Low:
                    mimeMessage.Priority = MessagePriority.NonUrgent;
                    break;
                case EmailPriority.Normal:
                    mimeMessage.Priority = MessagePriority.Normal;
                    break;
                case EmailPriority.High:
                    mimeMessage.Priority = MessagePriority.Urgent;
                    break;
                default:
                    throw new ArgumentOutOfRangeException();
            }

            mimeMessage.Subject = Subject;
            mimeMessage.Date = SendDate;

            var bodyBuilder = new BodyBuilder();

            if (IsBodyHtml)
            {
                var body = Body;
                foreach (var attachment in Attachments)
                {
                    if (!attachment.IsInline) continue;
                    // cid toevoegen in de body die refereert naar de linked resource die we later aanmaken
                    body = body.Replace(attachment.FileName, "cid:" + attachment.FileName);
                }

                bodyBuilder.HtmlBody = Body;
            }
            else
                bodyBuilder.TextBody = Body;

            foreach (var attachment in Attachments)
            {
                if (attachment.Type == AttachmentType.Downloaded) continue;
                var attach = !attachment.IsInline
                    ? bodyBuilder.Attachments.Add(attachment.FileName, attachment.FileData)
                    : bodyBuilder.LinkedResources.Add(attachment.FileName, attachment.FileData);

                attach.ContentDisposition.Size = attachment.FileSize;
            }

            mimeMessage.Body = bodyBuilder.ToMessageBody();
            return mimeMessage;
        }
        #endregion
```

**Comment by Sicos1977** [comment]
I also wrote the mime-message to disk and have no problems in opening them with Outlook

**Comment by Sicos1977** [comment]
This is how I write the messages to a persons mailbox

```
        #region WriteMessage
        /// <summary>
        /// Schrijft het opgegeven <paramref name="message"/> naar de <see cref="SelectedFolder"/> wanneer
        /// deze <see cref="MailBox"/> een <see cref="Outbox"/> is
        /// </summary>
        /// <param name="message"><see cref="MimeMessage"/></param>
        /// <returns>Het unieke id van het geschreven bericht</returns>
        /// <exception cref="MailBoxException"></exception>
        public string WriteMessage(MimeMessage message)
        {
            using (var memoryStream = new MemoryStream())
            using (var protocolLogger = new ProtocolLogger(memoryStream))
            using (var client = new ImapClient(protocolLogger))
            {
                try
                {
                    ConnectAndAuthenticate(client);
                    var folder = client.GetFolder(SelectedFolder);
                    folder.Open(FolderAccess.ReadWrite);
                    var uniqueId = folder.Append(message);
                    client.Disconnect(true);
                    return uniqueId != null ? uniqueId.Value.ToString() : null;
                }
                catch (Exception exception)
                {
                    throw new MailBoxException(RemoveLoginInformation(memoryStream), exception);
                }
            }
        }
        #endregion
```

**Comment by jstedfast** [comment]
I have no idea. The problem can't possibly be what MailKit is sending to the server because that `<meta` text is just part of the message body and the content length that MailKit declared in the APPEND command is no where near overflowed.

The exception string you pasted looks like it is coming from MailKit, but MailKit doesn't parse what it sends to the server so that doesn't make any sense either.

Are you sure there isn't more to the log?

**Comment by Sicos1977** [comment]
Update: It seems that is has something to do with the body that I'm setting.

When I take just a portion of the my original HTML body then everything seems to work, but I still don't know why it goes wrong.

bodyBuilder.HtmlBody = body.Substring(0, 2000);

**Comment by Sicos1977** [comment]
When I use the complete body that is 41647 bytes long then it fails

**Comment by Sicos1977** [comment]
It's very strange but when I use this than it works.

`bodyBuilder.HtmlBody = body.Substring(0, 10320);`

But when I do this then it fails.

`bodyBuilder.HtmlBody = body.Substring(0, 10330);`

**Comment by jstedfast** [comment]
There's no limit the the number of bytes that can be uploaded to the IMAP server in an APPEND command that I'm aware of, and if there was, the server would respond with a `NO` response, not unexpected token.

The IMAP server shouldn't be interpreting the message either, other than possibly to parse the MIME (not the HTML) in order to cache the ENVELOPE and BODYSTRUCTURE of the message.

**Comment by Sicos1977** [comment]
I know there is no limit but for some reason it fails after 10330 chars in the body. I don't know why but when I shorten the body then everything works without any problems

**Comment by jstedfast** [comment]
very odd :(

**Comment by Sicos1977** [comment]
I did try another message that also fails. This is the log with some private informatien (*****)  removed.

S: * CAPABILITY IMAP4 IMAP4rev1 AUTH=PLAIN STARTTLS UIDPLUS MOVE ID CHILDREN IDLE NAMESPACE LITERAL+
S: A00000000 OK CAPABILITY completed.
C: A00000001 AUTHENTICATE PLAIN
S: +
C: *******
S: A00000001 OK AUTHENTICATE completed.
C: A00000002 CAPABILITY
S: * CAPABILITY IMAP4 IMAP4rev1 AUTH=PLAIN UIDPLUS MOVE ID CHILDREN IDLE NAMESPACE LITERAL+
S: A00000002 OK CAPABILITY completed.
C: A00000003 NAMESPACE
S: * NAMESPACE (("" "/")) NIL NIL
S: A00000003 OK NAMESPACE completed.
C: A00000004 LIST "" "INBOX"
S: * LIST (\Marked \HasNoChildren) "/" INBOX
S: A00000004 OK LIST completed.
C: A00000005 SELECT INBOX
S: * 0 EXISTS
S: * 0 RECENT
S: * FLAGS (\Seen \Answered \Flagged \Deleted \Draft $MDNSent)
S: * OK [PERMANENTFLAGS (\Seen \Answered \Flagged \Deleted \Draft $MDNSent)] Permanent flags
S: * OK [UIDVALIDITY 14] UIDVALIDITY value
S: * OK [UIDNEXT 973] The next unique identifier value
S: A00000005 OK [READ-WRITE] SELECT completed.
C: A00000006 APPEND INBOX {32228+}
C: From: *****
C: Date: Fri, 21 Jul 2017 15:25:52 +0200
C: Subject: *****
C: Message-Id: <BJ1RKX8SW1U4.MM50OR8M6GFB1@Email2Storage.com>
C: To: *****
C: MIME-Version: 1.0
C: Content-Type: multipart/mixed; boundary="=-MLKm4TnDi2N1X+RRy9P0TA=="
C: 
...
C: Content-Type: text/html; charset=utf-8
C: Content-Id: <BLNLHY8SW1U4.TQFH924Q8U5B2@MS303388W2K12-2>
C: 
C: <html>
C: <head>
C: <meta http-equiv="Content-Type" content="text/html; charset=utf-8"></head>
C: ***** BODY REMOVED *****
C: <body></span>di
...
C: Content-Type: application/vnd.ms-works;
C: 	name="*****.wps"
C: Content-Disposition: attachment;
C: 	filename*0="*****";
C: 	filename*1=wps; size=15360
C: Content-Transfer-Encoding: base64
C: 
C:	******* REMOVED ATTACHMENTS **** 
C:
C: --=-MLKm4TnDi2N1X+RRy9P0TA==--
C: 
S: <body><div BAD Command Error. 10
S: * BYE Connection closed.

**Comment by Sicos1977** [comment]
Not solved yet but when I do this then I can append the message. Is seems there is some kind of size limit on what can be send as one long string without <CR><LF>'s

![image](https://user-images.githubusercontent.com/6692947/28556975-0fcaf774-710a-11e7-9214-4b50d821a708.png)

**Comment by Sicos1977** [comment]
I solved my problem by adding this to my code.

```
                var output = new StringBuilder();

                foreach (var c in body)
                {
                    if (c  == '<' && c != 0)
                        output.Append(Environment.NewLine);

                    output.Append(c);
                }

                bodyBuilder.HtmlBody = output.ToString();
```

Is there something inside Mail or MimeKit that can do the same?

**Comment by Sicos1977** [comment]
I switched to HTML Tidy... it does do a better job then I can do with my workaround.

```
                    using (var memoryStream = new MemoryStream(new UTF8Encoding(false).GetBytes(body)))
                    using (var document = Document.FromStream(memoryStream))
                    {
                        document.ShowWarnings = false;
                        document.Quiet = true;
                        document.OutputXhtml = true;
                        document.CleanAndRepair();
                        bodyBuilder.HtmlBody = document.Save();
                    }
```

So far my problem is solved with this but I still find it an odd behavior for Exchange 2013.

**Comment by jstedfast** [comment]
Wait, is the problem that a single line is too long?

If so, make sure to call:

```csharp
message.Prepare (EncodingConstraint.SevenBit);
```

(Note: you can also use EncodingConstraint.EightBit).

That method also allows specifying a max line length.

**Comment by Sicos1977** [comment]
Yes it is exactly that problem. I also mentioned that in a previous message.

> Not solved yet but when I do this then I can append the message. Is seems there is some kind of size limit on what can be send as one long string without [CR][LF]'s

Nevermind, I'll try the `message.Prepare (EncodingConstraint.SevenBit);` method tomorrow (since it's already evening overhere) and see if that also fixes the problem.

**Comment by jstedfast** [comment]
It should fix the issue. I'm guessing that one of the lines is longer than 1000 bytes.
