### ISSUE TITLE
envelope.From

### ISSUE THREAD

**Issue by 30797593** [jstedfast/MailKit#546]
Hi
I found the sender's name in the message header information appears in the space is not complete。
![1k9771qywyf22 vo1 q ba1](https://user-images.githubusercontent.com/22047027/28856224-4b0f286c-7774-11e7-92ee-f07ad2673979.png)
![mo wvfw8pdq20 0 vo5m3 o](https://user-images.githubusercontent.com/22047027/28856225-4b2bb270-7774-11e7-8d39-2b857045bd63.png)

The IMAP protocol logging:
C: A00000006 SELECT INBOX
S: * 2 EXISTS
S: * 0 RECENT
S: * OK [UNSEEN 1]
S: * OK [UIDVALIDITY 1500945873] UID validity status
S: * OK [UIDNEXT 3] Predicted next UID
S: * FLAGS (\Answered \Flagged \Deleted \Draft \Seen)
S: * OK [PERMANENTFLAGS (\* \Answered \Flagged \Deleted \Draft \Seen)] Permanent flags
S: A00000006 OK [READ-WRITE] SELECT complete
C: A00000007 UID SEARCH CHARSET UTF-8 NOT TO {24}
S: * SEARCH 1 2
S: A00000007 OK UID SEARCH completed
C: A00000008 UID FETCH 1:2 (UID FLAGS ENVELOPE BODYSTRUCTURE)
S: * 1 FETCH (UID 1 FLAGS (\Seen) ENVELOPE ("Wed, 5 Apr 2017 09:50:12 +0800" "=?GBK?B?u7bTrcq508PM2tG2xvPStdPKz+Q=?=" (("=?GBK?B?zNrRtsbz0rXTys/k?=" NIL "10000" "qq.com")) (("=?GBK?B?zNrRtsbz0rXTys/k?=" NIL "10000" "qq.com")) (("=?GBK?B?zNrRtsbz0rXTys/k?=" NIL "10000" "qq.com")) NIL NIL NIL NIL) BODYSTRUCTURE ("TEXT" "HTML" ("CHARSET" "gb2312") NIL NIL NIL 5912 89 NIL NIL NIL))
S: * 2 FETCH (UID 2 FLAGS () ENVELOPE ("Wed, 2 Aug 2017 10:59:27 +0800" "=?GBK?B?IHRlc3QgbWFpbGtpdCBmcm9t?=" (("=?GBK?B?SnVzdGlu?=" NIL "bizbee" "trayoo.com")) (("=?GBK?B?SnVzdGlu?=" NIL "bizbee" "trayoo.com")) (("=?GBK?B?SnVzdGlu?=" NIL "bizbee" "trayoo.com")) (("=?GBK?B?Yml6YmVlMg==?=" NIL "bizbee2" "trayoo.com")) NIL NIL NIL "<tencent_0FE54EA32BDC33DB16703763@qq.com>") BODYSTRUCTURE (("TEXT" "PLAIN" ("charset" "utf-8") NIL NIL "BASE64" 28 2 NIL NIL NIL)("TEXT" "HTML" ("charset" "utf-8") NIL NIL "BASE64" 126 3 NIL NIL NIL) "ALTERNATIVE" ("BOUNDARY" "----=_NextPart_5981400F_097892C8_31E72749") NIL NIL))
S: A00000008 OK UID FETCH Completed

**Comment by jstedfast** [comment]
Your IMAP server is telling MailKit that the name is `=?GBK?B?SnVzdGlu?=` which decodes to `Justin`, not `Justin Turner`.

**Comment by 30797593** [comment]
Thank you for your reply Let me know that the problem lies in the server side
