### ISSUE TITLE
Exception in UniqueIdSet when Search return none

### ISSUE THREAD

**Issue by clsaad** [jstedfast/MailKit#547]
Hello,

I has write a script that cleanup some directories periodically.
I make a function to search for all messages that older than X days (in this case 30 days).

Code:

        Dim oFolder As ImapFolder = oIMAP.GetFolder("Inbox")
        oFolder.Open(FolderAccess.ReadWrite)
        Dim uIDs As UniqueIdSet
        Dim dtDataBefore as Date = CDate("2017-07-11")

       ' exception occurs if don't have any messages.
        uIDs = oFolder.Search(SearchQuery.DeliveredBefore(dtDataBefore).And(SearchQuery.NotDeleted))

error:
Exceção Sem Tratamento: System.InvalidCastException: Não é possível converter um objeto do tipo 'MailKit.UniqueId[]' no tipo 'MailKit.UniqueIdSet'.

Regards, Cleber

**Comment by jstedfast** [comment]
Well, yea, it doesn't always return a UniqueIdSet. Sometimes it returns new UniqueId[0];

The API is such that it's not specific on what type of collection of UniqueId it returns.

You need to check what type it is yourself and cast appropriately.

**Comment by clsaad** [comment]
Hello,

In this case I assume that always return a UniqueIdSet because some folders have a lot of messages. But, I guess if have an only item (or message) the UniqueIdSet need to be populated with only 1 record.

**Comment by jstedfast** [comment]
Generally it will be a UniqueIdSet unless there are 0 messages, but I do not want to make that guarantee.

Why do you care if it is a UniqueIdSet vs a List<UniqueId> vs a UniquerIdRange vs UniqueId[] ?

You should not cast it to any of those, ever. Treat it as an IList<UniqueId> like the API enforces :)
