### ISSUE TITLE
can't star in gmail account

### ISSUE THREAD

**Issue by in32bit** [jstedfast/MailKit#549]
Hello and thank you.
I tried all example from this thread also _**https://github.com/jstedfast/MailKit/issues/306**_

**My code**

```
[HttpPost, Authorize]
        public async Task<ActionResult> SetFlaggedMail(MailMessage dto)
        {
            using (var client = new ImapClient(new ProtocolLogger("C:/temp/logs/imap.txt")))
            {
                if (await Helpers.Mailer.IMAPConnectAndAuthenticate(client))
                {
                    var folder = client.GetFolder(SpecialFolder.All);
                    await folder.OpenAsync(FolderAccess.ReadWrite);
                    var uniqueId = new UniqueId(1, Convert.ToUInt32(dto.MailId));

                    if (dto.Flagged)
                    {
                        await folder.RemoveLabelsAsync(uniqueId, new string[] { "\\Starred" }, true);
                        await folder.RemoveFlagsAsync(uniqueId, MessageFlags.Flagged, true);
                    }
                    else
                    {
                        await folder.AddLabelsAsync(uniqueId, new string[] { "\\Starred" }, true);
                        await folder.AddFlagsAsync(uniqueId, MessageFlags.Flagged, true);
                    }

                    await folder.CloseAsync(true);
                    await client.DisconnectAsync(true);
                }
            }


            return SerializedContent(true);
        }

```

**the log**

Connected to imaps://imap.gmail.com:993/
S: * OK Gimap ready for requests from 89.138.156.154 j80mb475523931wmd
C: E00000000 CAPABILITY
S: * CAPABILITY IMAP4rev1 UNSELECT IDLE NAMESPACE QUOTA ID XLIST CHILDREN X-GM-EXT-1 XYZZY SASL-IR AUTH=XOAUTH2 AUTH=PLAIN AUTH=PLAIN-CLIENTTOKEN AUTH=OAUTHBEARER AUTH=XOAUTH
S: E00000000 OK Thats all she wrote! j80mb475523931wmd
C: E00000001 AUTHENTICATE PLAIN AHJveUBmYXN0LXRlY2hub2xvZ2llcy5jb20AYTY0MDM2NDAz
S: * CAPABILITY IMAP4rev1 UNSELECT IDLE NAMESPACE QUOTA ID XLIST CHILDREN X-GM-EXT-1 UIDPLUS COMPRESS=DEFLATE ENABLE MOVE CONDSTORE ESEARCH UTF8=ACCEPT LIST-EXTENDED LIST-STATUS LITERAL- SPECIAL-USE APPENDLIMIT=35651584
S: E00000001 OK roy@xxx-technologies.com authenticated (Success)
C: E00000002 NAMESPACE
S: * NAMESPACE (("" "/")) NIL NIL
S: E00000002 OK Success
C: E00000003 LIST "" "INBOX"
S: * LIST (\HasNoChildren) "/" "INBOX"
S: E00000003 OK Success
C: E00000004 LIST (SPECIAL-USE) "" "*"
S: * LIST (\All \HasNoChildren) "/" "[Gmail]/All Mail"
S: * LIST (\Drafts \HasNoChildren) "/" "[Gmail]/Drafts"
S: * LIST (\HasNoChildren \Sent) "/" "[Gmail]/Sent Mail"
S: * LIST (\HasNoChildren \Junk) "/" "[Gmail]/Spam"
S: * LIST (\Flagged \HasNoChildren) "/" "[Gmail]/Starred"
S: * LIST (\HasNoChildren \Trash) "/" "[Gmail]/Trash"
S: E00000004 OK Success
C: E00000005 LIST "" "[Gmail]"
S: * LIST (\HasChildren \Noselect) "/" "[Gmail]"
S: E00000005 OK Success
C: E00000006 SELECT "[Gmail]/All Mail" (CONDSTORE)
S: * FLAGS (\Answered \Flagged \Draft \Deleted \Seen $NotPhishing $Phishing)
S: * OK [PERMANENTFLAGS (\Answered \Flagged \Draft \Deleted \Seen $NotPhishing $Phishing \*)] Flags permitted.
S: * OK [UIDVALIDITY 11] UIDs valid.
S: * 497 EXISTS
S: * 0 RECENT
S: * OK [UIDNEXT 1446] Predicted next UID.
S: * OK [HIGHESTMODSEQ 92677]
S: E00000006 OK [READ-WRITE] [Gmail]/All Mail selected. (Success)
C: E00000007 UID STORE 501 +X-GM-LABELS.SILENT (\Starred)
S: E00000007 OK Success
C: E00000008 CLOSE
S: E00000008 OK Returned to authenticated state. (Success)
C: E00000009 LOGOUT
S: * BYE LOGOUT Requested
S: E00000009 OK 73 good day (Success)

why?

**Comment by jstedfast** [comment]
Looks like the server is accepting the \Starred label just as you wanted. Are you sure that the correct label is "\Starred"? Maybe it's just "Starred"?

**Comment by in32bit** [comment]
I Just jries "Starred" and the server is not accepting that.
Tried "\\Flagged" and he did and still not working.

**Comment by in32bit** [comment]
this is how i get the flags...

```
                    foreach (var summary in inbox.Fetch(ids, MessageSummaryItems.Envelope | MessageSummaryItems.Flags))
                    {
                        var message = new MailMessage
                        {
                            MailId = Convert.ToInt32(summary.UniqueId.Id),
                            Subject = summary.Envelope.Subject,
                            From = summary.Envelope.Sender.ToString(),
                            Date = summary.Envelope.Date,
                            To = string.Join(", ", summary.Envelope.To.ToList()).Replace("\"", string.Empty),
                            Flagged = (summary.Flags & MessageFlags.Flagged) == MessageFlags.Flagged,
                            Seen = (summary.Flags & MessageFlags.Seen) == MessageFlags.Seen
                        };

                        dto.Messages.Add(message);

                    }
```

**Comment by jstedfast** [comment]
I would recommend starring a few messages and then getting that messages flags/labels and seeing what the server uses to mark those messages as starred, then use that.

**Comment by NickSpag** [comment]
It's "\\Starred" if anyone comes across this.

**Comment by jstedfast** [comment]
Thanks, Nick!
