### ISSUE TITLE
IMessageSummary.Envelope.ReplyTo.ToString() parsing incorrectly

### ISSUE THREAD

**Issue by Rgenware** [jstedfast/MailKit#551]
IMessageSummary.Envelope.ReplyTo.ToString() leaves off the > at end of line

current result is as below:
"Google" <no-reply@accounts.google.com

**Comment by jstedfast** [comment]
I don't see how that is possible:

https://github.com/jstedfast/MimeKit/blob/master/MimeKit/MailboxAddress.cs#L526

That is the line of code that stringifies the address.

Did Google's IMAP server perhaps feed MailKit an improper address?

For example, if you check your logs, does Google's IMAP server send MailKit the following tokens?

`("Google" NIL "<no-reply" "accounts.google.com")` ?
