### ISSUE TITLE
How do you delete a message using IMAP client?

### ISSUE THREAD

**Issue by kirk-quinbar** [jstedfast/MailKit#552]
I have a need to search for a message based on a unique subject and if i find it, delete the message. How do i accomplish the delete part? searching for messages was self-explanatory. I can't seem to find a way to delete the message once i've found it.

**Comment by jstedfast** [comment]
What you need to do is to set the `MessageFlags.Deleted` flag on the message via `folder.AddFlags (uid, MessageFlags.Deleted, true);`

You may also want to purge the folder of deleted messages using `folder.Expunge ();`
