### ISSUE TITLE
Unexpected token in IMAP response: ']' from imap-mail.outlook.com

### ISSUE THREAD

**Issue by mike-nelson** [jstedfast/MailKit#555]
Hi, I am seeing an error parsing this response:

  Unexpected token in IMAP response: ']'

Snippet from protocol log:

  C: B00000011 UID MOVE 3210 Inbox
  S: * OK [COPYUID 14  ]
  S: B00000011 OK MOVE completed.

I think the space before the ] is tripping it up. 

Server is Microsoft Exchange IMAP4 at imaps://imap-mail.outlook.com:993/

I am on MailKit 1.2.12 so not sure if fixed already but doesn't look like it to me.

**Comment by mike-nelson** [comment]
I have upgraded to 1.18.0 so will see if it happens again and update this issue.

**Comment by mike-nelson** [comment]
I found in the latest version it still throws this error but it has a different description:

    Syntax error in COPYUID response code. Unexpected token: ']'

This happens consistently on Outlook.com IMAP server.

Note there are two spaces before the ]

    S: * OK [COPYUID 14  ]

**Comment by jstedfast** [comment]
The problem isn't the space, but rather the fact that the `COPYUID` is missing 2 more arguments.

The `COPYUID` *should* be followed by 3 tokens:

1. the UIDVALIDITY of the destination folder
2. the  source folder's uid-set
3. the uid-set of the corresponding messages in the destination folder

For whatever reason, your IMAP server is not providing 2 of the 3 necessary arguments :(

**Comment by jstedfast** [comment]
I could look into making MailKit ignore the syntax error, but geez, that sucks :(

**Comment by mike-nelson** [comment]
Don't call it MY mail server, it is Outlook.com, you would think those guys would know a bit about mail but ah well...

**Comment by jstedfast** [comment]
hehe :)

I'll try to look into this tomorrow morning.

**Comment by jstedfast** [comment]
Out of curiosity, is it possible that message uid 3210 did not exist in the source folder?

Here's my thinking:

If the message did not exist, then it would make sense that the src uid-set in the COPYUID resp-code would be an empty which of course would also mean that the dest uid-set would also be empty, potentially producing empty strings for both sets. If we were to represent this in some pseudo C# syntax, we'd get:

```csharp
var uidValidity = 14;
var srcSet = string.Empty;
var destSet = string.Empty;

output.WriteLine ("* OK [COPYUID {0} {1} {2}]", uidValidity, srcSet, destSet);
```

And this, of course, would produce `* OK [COPYUID 14  ]` (note the double spaces).

**Comment by mike-nelson** [comment]
Yes! You are quite right. This is what is happening. So actually that is probably a valid return from that call. You could throw a MessageNotFound exception in this case instead.

Took a while as I first thought that wasn't possible since I am fetching the mail first to see if it exists, but turns out I am fetching it in the inbox, it does exist there (because this code executes a second time and the message is already in the inbox). 

My code is doing an "undo delete" operation, and occasionally it gets run twice. It moves a message from "deleted" folder back to "inbox". I am checking first that the message exists with a fetch. BUT i am fetching always in the inbox, instead of in the "deleted" folder for this undo operation.

By the way, when a message is not found in Fetch, the method previously returned null and now throws ImapCommandException. This is very general, so I then have to check the text of the message (and I notice these messages change with versions of mailkit, so not ideal). It would be much better to have a MessageNotFound exception, which could also be thrown in this MOVE with blank returns case.

**Comment by jstedfast** [comment]
> So actually that is probably a valid return from that call.

It's actually not valid - what Outlook.com *should* be doing is just omitting the COPYUID response-code altogether.

Glad we've confirmed what is actually happening, though.

The Fetch() method should have never returned null - that was a bug I guess.

ImapCommandException is only thrown when the IMAP server responds with NO or BAD which is not easy to map to a "message not found" error, so I'm not sure that can be done.

In fact, an IMAP server should, afaik, respond with an OK even if the uid(s) requested do not exist - the response will just not contain any untagged FETCH responses.

What is (Outlook.com?) responding with? BAD? (due to UID being out of the known range?)

**Comment by mike-nelson** [comment]
Wait, so response to Fetch with UID not found could be empty list if mail server responds OK, OR exception if mail server responds NO. This might vary depending on how mail server handles not found case. Not a problem really, I just need to handle exception, null, empty list all the same. 

This exception has its own description "some of the requested messages no longer exist". Not sure if you added that text or it came from the mail server's NO response.

**Comment by jstedfast** [comment]
That sounds like it came from the IMAP server.

Technically, the IMAP server should never return NO or BAD if the message does not exist. But yea, I guess this server decided to return an error instead.

FWIW, BAD generally means syntax error while NO generally means error completing the request for some reason.

**Comment by mike-nelson** [comment]
Yet MailKit throws both NO and BAD as ImapCommandException? Maybe they should throw different exceptions? (Could cause unnecessary back compat grief though)

I think you could interpret the spec meaning that NO could be used for "can't find it".

    6.4.5.  FETCH Command

   Arguments:  sequence set
               message data item names or macro

   Responses:  untagged responses: FETCH

   Result:     OK - fetch completed
               NO - fetch error: can't fetch that data
               BAD - command unknown or arguments invalid

**Comment by jstedfast** [comment]
There's a property on ImapCommandException to check BAD vs NO (I think it's the Response property).

**Comment by mike-nelson** [comment]
That's a good idea. I don't seem to have a Response property or any property that looks like it. 

However I can check the message text which should be fairly reliable?

    exception.Message.Contains("BAD")

**Comment by jstedfast** [comment]
You're looking at the wrong exception type.

https://github.com/jstedfast/MailKit/blob/master/MailKit/Net/Imap/ImapCommandException.cs#L152

`ImapProtocolException` is only emitted in cases where there is a protocol-level error.

**Comment by mike-nelson** [comment]
Ah, great - thanks!
