### ISSUE TITLE
Right square bracket missing from folder fullname

### ISSUE THREAD

**Issue by breedbekkikker** [jstedfast/MailKit#557]
Hi,

Consider the following snippet from an IMAP4 protocol logging:

```
S: * OK [CAPABILITY IMAP4rev1 LITERAL+ SASL-IR LOGIN-REFERRALS ID ENABLE IDLE AUTH=PLAIN AUTH=LOGIN] Hello there.
[...]
C: X00000004 LIST "" "%" RETURN (SUBSCRIBED CHILDREN)
S: * LIST (\Subscribed \HasNoChildren) "." Sent
S: * LIST (\Subscribed \HasNoChildren) "." Trash
S: * LIST (\Subscribed \HasNoChildren) "." Drafts
S: * LIST (\Subscribed \HasChildren) "." [Gmail]
S: * LIST (\HasNoChildren) "." INBOX
S: X00000004 OK List completed.
```

IMailFolder.FullName returns the fullname as `[Gmail`. So the right square bracket is missing, which results in not being able to iterate through the folder structure.

Other IMAP4 servers that I've seen return `"[Gmail]"` instead of `[Gmail]` in the response to the LIST command, which does not cause any problems.

Please advise, thanks!

**Comment by breedbekkikker** [comment]
Hi, as always, thanks a lot for your prompt response and fix!

Just wondering whether you have any idea yet when the next NuGet release will be out?

**Comment by jstedfast** [comment]
Hoping to make a release this weekend

**Comment by breedbekkikker** [comment]
Thank you so much for releasing the new NuGet package!

**Comment by jstedfast** [comment]
Hey, so it turns out I needed to fix this for STATUS and QUOTA* responses as well which I just did in 1.18.1.1 (1.18.1 only contains the fix for LIST responses).

**Comment by jstedfast** [comment]
Also of note is that ']' is actually legal in mailbox names. I'm just going to document this here in case I ever come back to this...

```
mailbox         = "INBOX" / astring
                    ; INBOX is case-insensitive.  All case variants of
                    ; INBOX (e.g., "iNbOx") MUST be interpreted as INBOX
                    ; not as an astring.  An astring which consists of
                    ; the case-insensitive sequence "I" "N" "B" "O" "X"
                    ; is considered to be INBOX and not an astring.
                    ;  Refer to section 5.1 for further
                    ; semantic details of mailbox names.

astring         = 1*ASTRING-CHAR / string

ASTRING-CHAR   = ATOM-CHAR / resp-specials

ATOM-CHAR       = <any CHAR except atom-specials>

atom-specials   = "(" / ")" / "{" / SP / CTL / list-wildcards /
                  quoted-specials / resp-specials

resp-specials   = "]"
```

What originally confused me, I think, is that ']' is a `resp-special` which is explicitly disallowed in the `ATOM-CHAR` definition. However, `ASTRING-CHAR` is an `ATOM-CHAR` -or- a `resp-special`, thereby allowing ']'.

**Comment by jstedfast** [comment]
Also, hah:

```
84) Change the definition of atom to exclude "]".  Update astring to
   include "]" for compatibility with the past.  Remove resp-text-atom.
```

**Comment by breedbekkikker** [comment]
Thanks, it works :)
