### ISSUE TITLE
MailKit.Net.Pop3.Pop3ProtocolException: Pop3 server returned an incomplete response to the UIDL command.

### ISSUE THREAD

**Issue by kishoresahas** [jstedfast/MailKit#560]
To help me debug your issue, please explain:
- What were you trying to do? **Connect to a POP3 server** 
- What happened? **Got an exception while Authenticate**
- What did you expect to happen? **Connect to POP3 server and fetch mails**
- Step-by-step reproduction instructions and/or a simple test case.
                
                var incomingMailServer = GlobalVariables.EmailSettings.IncomingMailServer;
                var portNumber = GlobalVariables.EmailSettings.Pop3Port;
                var userName = GlobalVariables.EmailSettings.UserId;
                var password = GlobalVariables.EmailSettings.Password;
               using (var pop3Client = new Pop3Client())
                {
                    Status("connecting to " + incomingMailServer + "...");
                    pop3Client.Connect(incomingMailServer, portNumber, GlobalVariables.EmailSettings.EnableSsl);
                    // Note: since we don't have an OAuth2 token, disable
                    // the XOAUTH2 authentication mechanism.
                    pop3Client.AuthenticationMechanisms.Remove("XOAUTH2");
                    //Authenticate with usr / pass
                    pop3Client.Authenticate(userName, password);
                   ...
                }

**Note : The servers is not having UIDL capability.**

If you got an exception, please include the exception Message *and* StackTrace.
```
MailKit.Net.Pop3.Pop3ProtocolException: Pop3 server returned an incomplete response to the UIDL command.
   at MailKit.Net.Pop3.Pop3Client.GetMessageUid(Int32 index, CancellationToken cancellationToken)
   at MailKit.Net.Pop3.Pop3Client.ProbeCapabilities(CancellationToken cancellationToken)
   at MailKit.Net.Pop3.Pop3Client.Authenticate(Encoding encoding, ICredentials credentials, CancellationToken cancellationToken)
   at MailKit.MailService.Authenticate(String userName, String password, CancellationToken cancellationToken)
   at PAL.Vessel.TransPackets.ReadMail.Read()

```
Please also INCLUDE A PROTOCOL LOG (scrubbed of any authentication data), especially
if you got an exception such as `Syntax error in XYZ. Unexpected token: ...`.
If you do not include the protocol log, you will make me VERY UNHAPPY.

**This issue is happening in a local computer where internet is not available.  
We are using below POP3 server.
[RedPort](http://downloads.globalmarinenet.com/downloads/wxa/RedPort_Email.pdf )**

**Comment by jstedfast** [comment]
Could you attach a protocol log? Without one, all I can do is make guesses. Thanks.

**Comment by jstedfast** [comment]
If your POP3 server doesn't support the UIDL command, it should return `-ERR` and not `+OK` with missing values.

**Comment by jstedfast** [comment]
Please get me a protocol log and I'll look into a way to try and work around this server bug.
