### ISSUE TITLE
Unable to connect to imaps when setting up TLS 

### ISSUE THREAD

**Issue by truane** [jstedfast/MailKit#561]
So i'm having an issue I am trying to connect to using TLS

Server name: outlook.office365.com
Port: 993
Encryption method: TLS

so I am using this to connect to the server 
 
` _client.Connect( "outlook.office365.com", "993", SecureSocketOptions.StartTls);`

But it fails and the log only contains one line and throws an exception

> Connected to **imap:**//outlook.office365.com:993/?starttls=always

But if use below it connect successfully but need to use TLS

` _client.Connect( "outlook.office365.com", "993", SecureSocketOptions.Auto);`

> Connected to **imaps**://outlook.office365.com:993/
> S: * OK The Microsoft Exchange IMAP4 service is ready. [SABFADEAUAAxADkAMABDAEEAMAAwADEANQAuAEUAVQBSAFAAMQA5ADAALgBQAFIATwBEAC4ATwBVAFQATABPAE8ASwAuAEMATwBNAA==]
> C: C00000000 CAPABILITY
> S: * CAPABILITY IMAP4 IMAP4rev1 AUTH=PLAIN AUTH=XOAUTH2 SASL-IR UIDPLUS ID UNSELECT CHILDREN IDLE NAMESPACE LITERAL+
> S: C00000000 OK CAPABILITY completed.
> C: C00000001 AUTHENTICATE XOAUTH2  ***********************
> S: C00000001 NO AUTHENTICATE failed.
> C: C00000002 AUTHENTICATE PLAIN ***********************
> S: C00000002 OK AUTHENTICATE completed.
> C: C00000003 CAPABILITY
> S: * CAPABILITY IMAP4 IMAP4rev1 AUTH=PLAIN AUTH=XOAUTH2 SASL-IR UIDPLUS MOVE ID UNSELECT CLIENTACCESSRULES CLIENTNETWORKPRESENCELOCATION BACKENDAUTHENTICATE CHILDREN IDLE NAMESPACE LITERAL+
> S: C00000003 OK CAPABILITY completed.
> C: C00000004 NAMESPACE
> S: * NAMESPACE (("" "/")) NIL NIL
> S: C00000004 OK NAMESPACE completed.
> C: C00000005 LIST "" "INBOX"
> S: * LIST (\Marked \HasNoChildren) "/" INBOX
> S: C00000005 OK LIST completed.
> C: C00000006 SELECT INBOX
> S: * 5 EXISTS
> S: * 2 RECENT
> S: * FLAGS (\Seen \Answered \Flagged \Deleted \Draft $MDNSent)
> S: * OK [PERMANENTFLAGS (\Seen \Answered \Flagged \Deleted \Draft $MDNSent)] Permanent flags
> S: * OK [UNSEEN 4] Is the first unseen message
> S: * OK [UIDVALIDITY 14] UIDVALIDITY value
> S: * OK [UIDNEXT 626] The next unique identifier value
> S: C00000006 OK [READ-WRITE] SELECT completed.
> C: C00000007 FETCH 1:* (UID FLAGS INTERNALDATE RFC822.SIZE ENVELOPE BODY)

should the TLS be going to imaps as well?

Am I missing something any help would be useful I have removed the  ***********************

**Comment by truane** [comment]
sorry the error using 

`_client.Connect( "outlook.office365.com", "993", SecureSocketOptions.StartTls);`

is 
```
MailKit.Net.Imap.ImapProtocolException-The IMAP server has unexpectedly disconnected.
at MailKit.Net.Imap.ImapStream.ReadAhead(Int32 atleast, CancellationToken cancellationToken)
   at MailKit.Net.Imap.ImapStream.ReadToken(String specials, CancellationToken cancellationToken)
   at MailKit.Net.Imap.ImapStream.ReadToken(CancellationToken cancellationToken)
   at MailKit.Net.Imap.ImapEngine.Connect(ImapStream stream, CancellationToken cancellationToken)
   at MailKit.Net.Imap.ImapClient.Connect(String host, Int32 port, SecureSocketOptions options, CancellationToken cancellationToken)
```
I have also tried  `"imaps://outlook.office365.com:993/?starttls=always"`

```
Exception :System.Net.Sockets.SocketException-No such host is known
 at System.Net.Dns.GetAddrInfo(String name)
   at System.Net.Dns.InternalGetHostByName(String hostName, Boolean includeIPv6)
   at System.Net.Dns.GetHostAddresses(String hostNameOrAddress)
   at MailKit.Net.Imap.ImapClient.Connect(String host, Int32 port, SecureSocketOptions options, CancellationToken cancellationToken)
```

I have also used `StartTlsWhenAvailable` on all the above with same results

**Comment by jstedfast** [comment]
There's 2 ways that a IMAP/POP3/SMTP server can enable SSL/TLS for each protocol.

We'll call the first one "SSL/TLS-wrap". This is done on a "high port" (typically 465 for SMTP/S, 993 for IMAP/S and 995 for POP3/S). What happens here is that the socket is immediately wrapped in an SSL/TLS layer and so a client needs to enable SSL/TLS immediately after establishing a TCP/IP connection, before *any* commands are sent.

This mode is represented by `SecureSocketOptions.SslOnConnect`.

The second way is via the use of a `STARTTLS` command issued *after* the client connects and reads the server greeting and obtains the list of extensions supported by the server (of which `STARTTLS` is one).

`SecureSocketOptions.StartTls` tells MailKit that `STARTTLS` is a *requirement* for the client and that if the server doesn't support the `STARTTLS` extension, it should immediately bail.

`SecureSocketOptions.StartTlsWhenAvailable` is more lax. It will toggle into `STARTTLS` mode only if the server supports it, but if not, it will proceed in plain-text mode w/o error.

Hope that explanation clears things up.

**Comment by truane** [comment]
So let me get this straight even though I want to use TLS i need to set SecureSocketOptions.SslOnConnect and it will still use TLS?

can i still use  _client.SslProtocols = SslProtocols.Tls12;

**Comment by jstedfast** [comment]
Yes and yes.
