### ISSUE TITLE
Do it work with PEC email?

### ISSUE THREAD

**Issue by biapar** [jstedfast/MailKit#563]
Do it work with PEC email?

**Comment by jstedfast** [comment]
I don't know what PEC email is.

**Comment by jstedfast** [comment]
Looks like you probably mean this https://tools.ietf.org/html/rfc6109 ?

If so, yes and no. MimeKit/MailKit do not implement this specification, but they do provide you with all of the fundamental pieces to do PEC. In other words, MimeKit /MailKit support S/MIME v3 and allow you to construct messages in any way you want and add any header you want, so you should be able to fairly easily implement support for PEC using MimeKit/MailKit based on my quick overview of the specification.

**Comment by biapar** [comment]
PEC is special service email used in Italy as alternative to the registered email.

**Comment by forons** [comment]
@biapar were you able in the end to use it with PEC emails?
