### ISSUE TITLE
Issue with IMAP server has unexpectedly disconnected and yahoo

### ISSUE THREAD

**Issue by kirk-quinbar** [jstedfast/MailKit#564]
I have seen in past issues here that "IMAP server has unexpectedly disconnected" seems to indicate that the connected server dropped for some reason and mailkit doesnt really know why, but i thought i'd ask if there are known problems specifically with yahoo and connecting via IMAP.

We have a simple status test to validate our entire email system. it sends out an email every minute, then connects to various destination servers, in this case yahoo, and sits in a loop doing a search for the email for a specified amount of time. it should be a pass/fail type thing based on whether the sent email comes up in an imap search of the mailbox, but intermittently we are getting the error below. From what i can tell, it is right at the point of trying to authenticate based on my logging. 

Questions:
- in your experience, does yahoo have more issue related to this error than other email servers? 
- could it be that yahoo is occasionally is just dropping the connection because it thinks we are connecting too often?
- Anything else we can do to prevent this error? I did add some addtional logic to reconnect the imap server if this error pops up in the search loop, but this error is typically happening the very first time it connects and authenticates (before the loop).
- is there a better way than to connect and then sit in a loop constantly doing a search for a specified subject to determine if its received in a specified amount of time?

Protocol Log:
Connected to imaps://imap.mail.yahoo.com:993/  S: * OK [CAPABILITY IMAP4rev1 ID MOVE NAMESPACE X-ID-ACLID UIDPLUS LITERAL+ XYMHIGHESTMODSEQ CHILDREN SASL-IR AUTH=PLAIN AUTH=LOGIN AUTH=XYMLOGIN AUTH=XYMPKI AUTH=XYMCOOKIEB64 AUTH=XOAUTH2 AUTH=OAUTHBEARER] IMAP4rev1 Hello  C: M00000000 AUTHENTICATE PLAIN AHp5d2F2ZXN0YXR1c0B5YWhvby5jb20ARDMyNjg2MzUtODJCNS00NzIxLTg3M0QtMkY1OEVBOEUwNEY3  

Error we get:
MailKit.Net.Imap.ImapProtocolException: The IMAP server has unexpectedly disconnected.     at MailKit.Net.Imap.ImapStream.ReadAhead(Int32 atleast, CancellationToken cancellationToken)     at MailKit.Net.Imap.ImapStream.ReadToken(String specials, CancellationToken cancellationToken)     at MailKit.Net.Imap.ImapStream.ReadToken(CancellationToken cancellationToken)     at MailKit.Net.Imap.ImapEngine.ReadToken(CancellationToken cancellationToken)     at MailKit.Net.Imap.ImapCommand.Step()     at MailKit.Net.Imap.ImapEngine.Iterate()     at MailKit.Net.Imap.ImapEngine.Wait(ImapCommand ic)     at MailKit.Net.Imap.ImapClient.Authenticate(Encoding encoding, ICredentials credentials, CancellationToken cancellationToken)     at MailKit.MailService.Authenticate(String userName, String password, CancellationToken cancellationToken)     at Zywave.Status.Jobs.Mail.Providers.ImapServerProvider.CheckForMail(ImapServerInfo serverInfo, String emailSubject, Int32 sleepTime, Int32 secondsToWait) in D:\TeamCity\buildAgent\work\1fd95e8dab9a5eeb\Zywave.Status.Jobs.Mail\Providers\ImapServerProvider.cs:line 38

**Comment by jstedfast** [comment]
I don't have any specific knowledge of yahoo mail so your guess is as good as mine.

It's possible they think you are trying to connect too often. It's possible that their servers are just busy (peak usage). It's possible your network connection or their network connection is congested.

I really don't know.

Sorry :(
