### ISSUE TITLE
Problem with Outlook.com and Office365.com SMTPs

### ISSUE THREAD

**Issue by majco333** [jstedfast/MailKit#566]
Hi,

we have problem with sending emails by outlook.com (SMTP server: smtp-mail.outlook.com) and office365.com (SMTP server: outlook.office365.com). Error description:
MailKit.Security.AuthenticationException: ErrorInProcessing: 4.7.0 Temporary server error. Please try again later. PRX4 [AM5PR0701CA0008.eurprd07.prod.outlook.com]

 Our MailKit version is 1.18.1.1 (the latest). Can you help us?

Thanks

**Comment by jstedfast** [comment]
The error message comes from the SMTP server which states that it is some sort of "Temporary server error" (perhaps it is overloaded?) and to try again later.

The error really has nothing to do with MailKit or your code.

**Comment by majco333** [comment]
Sorry, but this situation isn't temporary (it takes few months). Then I use MS Outlook or Android, these SMTPs works fine (messages are sent). And I found the same problem (from 2014): https://stackoverflow.com/questions/44536155/c-sharp-mail-kit-office-365-server-issue

What can we do?

**Comment by jstedfast** [comment]
Contact your administrator? I don't know. It's nothing to do with MailKit.

**Comment by majco333** [comment]
We have a web app with a lot of users and 30 users have this problem. It's working with .NET SMTPClient. So I think MailKit has a problem with these SMTP servers. Office365 is used more and more so MailKit could respond to that...

**Comment by jstedfast** [comment]
Considering that the error occurs in authenticating, perhaps they are sending incorrect credentials?

Have you tried disabling some of the authentication mechanisms? Perhaps the server advertises an auth mechanism that it doesn't really support and it just so happens that System.Net.Mail doesn't even try to use that mechanism?

Try using the protocol logging feature to figure out which mechanism(s) it is trying to start eliminating 1 mechanism at a time until it works?

**Comment by majco333** [comment]
Credentials are correct (I tried it, I created own Outlook account - it's free and easy). The number of AuthenticationMechanisms is 0 - I tried this client.AuthenticationMechanisms.Remove("XOAUTH2").

My logs:
Connected to smtp://smtp.outlook.com:587/?starttls=when-available
S: 220 VI1P189CA0035.outlook.office365.com Microsoft ESMTP MAIL Service ready at Tue, 10 Oct 2017 08:50:10 +0000
C: EHLO [192.168.3.75]
S: 250-VI1P189CA0035.outlook.office365.com Hello [195.28.88.172]
S: 250-SIZE 157286400
S: 250-PIPELINING
S: 250-DSN
S: 250-ENHANCEDSTATUSCODES
S: 250-STARTTLS
S: 250-8BITMIME
S: 250-BINARYMIME
S: 250-CHUNKING
S: 250 SMTPUTF8
C: STARTTLS
S: 220 2.0.0 SMTP server ready
C: EHLO [192.168.3.75]
S: 250-VI1P189CA0035.outlook.office365.com Hello [195.28.88.172]
S: 250-SIZE 157286400
S: 250-PIPELINING
S: 250-DSN
S: 250-ENHANCEDSTATUSCODES
S: 250-AUTH LOGIN XOAUTH2
S: 250-8BITMIME
S: 250-BINARYMIME
S: 250-CHUNKING
S: 250 SMTPUTF8
C: AUTH XOAUTH2 dXNlcj1pa3Jvc2tyb3NAaG90bWFpbC5jb20BYXV0aD1CZWFyZXIgMjFpa3JvczEyAQE=
S: 451 4.7.0 Temporary server error. Please try again later. PRX4  [VI1P189CA0035.EURP189.PROD.OUTLOOK.COM]
C: AUTH LOGIN
S: 334 VXNlcm5hbWU6
C: aWtyb3Nrcm9zQGhvdG1haWwuY29t
S: 334 UGFzc3dvcmQ6
C: MjFpa3JvczEy
S: 451 4.7.0 Temporary server error. Please try again later. PRX4  [VI1P189CA0035.EURP189.PROD.OUTLOOK.COM]
C: QUIT
S: 221 2.0.0 Service closing transmission channel

Do you see anything?

Thanks

**Comment by jstedfast** [comment]
You need to use `client.AuthenticationMechanisms.Remove("XOAUTH2")` *after* connecting but *before* authenticating. The log shows that it tried to authenticate via XOAUTH2 and failed.

**Comment by majco333** [comment]
Super! Remove XOAUTH2 after connecting working. Sorry for my mistake...

**Comment by jstedfast** [comment]
No problem :)

**Comment by irowbin** [comment]
@jstedfast I am facing this issue `5.1.7 Invalid address [KU1PR03MB2775.apcprd03.prod.outlook.com]`

```c#
 using (var client = new SmtpClient(new ProtocolLogger(Console.OpenStandardOutput())))
            {    
                await client.ConnectAsync( smtpOptions.Server,  smtpOptions.Port, false ).ConfigureAwait(false);
                
                // Note: since we don't have an OAuth2 token, disable
                // the XOAUTH2 authentication mechanism.
                client.AuthenticationMechanisms.Remove("XOAUTH2");

                // Note: only needed if the SMTP server requires authentication
                if (smtpOptions.RequiresAuthentication)
                {
                    await client.AuthenticateAsync(
                        smtpOptions.User,
                        smtpOptions.Password).ConfigureAwait(false);
                }

                await client.SendAsync(m).ConfigureAwait(false);
                await client.DisconnectAsync(true).ConfigureAwait(false);
            }
```

**Comment by MPEV** [comment]
> You need to use client.AuthenticationMechanisms.Remove("XOAUTH2") after connecting but before authenticating. The log shows that it tried to authenticate via XOAUTH2 and failed.

 this specifically for office 365?

**Comment by jstedfast** [comment]
You don’t need to remove XOAUTH2 anymore since it is no longer on the list of auto-attempted mechanisms.
