### ISSUE TITLE
MailKit requires Nuget 2.12, that excludes VS 2012 users

### ISSUE THREAD

**Issue by lsoft** [jstedfast/MailKit#568]
I am not very competent with publishing nuget packages, but 

`
Install-Package MailKit
`

fails with 

> Install-Package : The 'MailKit 1.18.1.1' package requires NuGet client version '2.12' or above, but the current NuGet version is '2.8.60318.667'.

for the VS 2012 users.
As a VS 2012 user I can only use Mailkit 1.12. 
Can you enlight reasons why Mailkit require nuget 2.12?
Is it possible to downgrade back to nuget 2.8?

I think .Net 4.5 and VS 2012 are not too old for email-related developing.

Thanks!

**Comment by jstedfast** [comment]
The problem is that MailKit is also built for .NETStandard 1.3 which is what requires nuget 2.12

**Comment by lsoft** [comment]
As I said I am not competent with nuget publishing, so is there any way to downgrade to 2.8 and keep .NETStandard 1.3 supported? add one more package MailKit.NetFramework?

If no, I'll close this issue.

Thanks for reply!

**Comment by jstedfast** [comment]
There's no way to downgrade the required nuget version if I want to only ship just 1 nuget.

As you said, I could ship a second nuget package that had the .NETStandard versions in it, but that's more work that I really would prefer not to do unless it can be shown that there's a lot of users who need it. I don't want to burden myself with the extra work for just a few people.

You are welcome to fork this project and maintain your own MimeKit/MailKit nuspec files and publish to nuget.org that strips out the .NETStandard versions. I'd even be willing to link to them in my README if you want to do that.
