### ISSUE TITLE
Web.config support?

### ISSUE THREAD

**Issue by DianaKoenraadt** [jstedfast/MailKit#569]
Hi Jeffrey,

MailKit is a godsend. It enabled me to send a message with implicit SSL, very easily. Thank you!

Small question: I'm setting up the SMTP server, SecureSocketOptions, username, password, etc. in code now. I'd prefer doing that in Web.Config. Is this possible? 

Sorry if this is answered elsewhere, I have been searching but could not find documentation mentioning whether or not it is supported.

Thank you kindly.

Diana

**Comment by jstedfast** [comment]
You could easily write code to load these properties from your Web.config file. Web.config is just XML.

Hope that helps.
