### ISSUE TITLE
How to send custom IMAP command?

### ISSUE THREAD

**Issue by AlmightyCZ** [jstedfast/MailKit#570]
I'm trying to improve one of my projects by replacing not very reliable AE.Net.Mail library with the MailKit. However in order to use ModSeq with my IMAP server I have to "identify" as a "firendly" client using command such as ' {imap tag} x-icewarp-server iwconnector "x.x.x.yyyy" ' only then the  server includes HighestModSeq value for folders and allows me to search by it.
Is there an elegant way of doing this with the MailKit ImapClient instance? Thanks!

**Comment by jstedfast** [comment]
There's no API for doing that, but you can fork MailKit and it should be fairly straight forward to add an API to send that command if you follow the general pattern of other commands.

If you have questions, poke me and I'll answer.
