### ISSUE TITLE
Determine if server supports custom flags

### ISSUE THREAD

**Issue by mspace** [jstedfast/MailKit#571]
I'm synhronizing email messages from inbox to CRM. First I only read Unseen email messages (`MailKit.Search.SearchQuery.NotSeen`) and then marked them as readed. It turns out that some people have email account registered/added in outlook therefore they read emails which marks them as Readed and sync program doesn't transfer them to CRM (as emails were already readed by some people). 

I'm now using custom flags. This is my whole code (I removed logging for brevity and some other methods which aren't vital for the question):

```csharp
private const string TransferedToCrm = "TransferedToCrm";
private HashSet<string> UserFlags
{
  get
  {
    return new HashSet<string>() { TransferedToCrm };
  }
}

public void Synhronize()
{
  var settingService = new SettingService(this._user);
  ISettingItem item = settingService.GetSysSetting("Mail.Imap.Accounts");
  List<Models.ImapAccountModel> imapAccounts = Newtonsoft.Json.JsonConvert.DeserializeObject<List<Models.ImapAccountModel>>(item.Value);

  foreach (var imapAccount in imapAccounts)
  {
    using (var client = new ImapClient())
    {
      try
      {
        client.Connect(imapAccount.Server, imapAccount.Port, imapAccount.UseSsl);
      }
      catch (System.Security.Authentication.AuthenticationException e)
      {
        // https://github.com/dotnet/corefx/issues/1854#issuecomment-160513245
        if (e.InnerException is System.ComponentModel.Win32Exception)
        {
          // retrying
          client.Connect(imapAccount.Server, imapAccount.Port, imapAccount.UseSsl);
        }
        else
        {
          throw;
        }
      }

      client.AuthenticationMechanisms.Remove("XOAUTH2");
      client.Authenticate(imapAccount.Username, imapAccount.Password);

      // imap uses folders
      IMailFolder inbox = client.Inbox;
      
      // ReadWrite to allow setting flags for messsages
      inbox.Open(FolderAccess.ReadWrite);

      IList<MailKit.UniqueId> messageIds = inbox.Search(MailKit.Search.SearchQuery.DeliveredAfter(LastSyncDay)
        .And(MailKit.Search.SearchQuery.DoesNotHaveCustomFlag(TransferedToCrm)));
      
      foreach (MailKit.UniqueId messageId in messageIds)
      {
        MimeMessage message = inbox.GetMessage(messageId);
        EmailActivityModel model = this.CreateEmailActivity(message, imapAccount.Email);
        Logger.Info("EmailActivity created [activityId: " + model.ActivityId + "].");

        // add TransferedToCrm flag for this message
        inbox.AddFlags(messageId, MessageFlags.None, UserFlags, true);
      }

      // send Logout command
      client.Disconnect(true);
    }
  }
}
```

Is there some API to determine if imap server supports setting custom flags on messages/emails. I found only this http://www.mimekit.net/docs/html/P_MailKit_Net_Smtp_SmtpClient_Capabilities.htm.

I also found next [stackoverflow post](https://stackoverflow.com/questions/40038731/how-can-i-mark-a-message-forwarded-in-the-client-synchronize-to-the-server) where you mentioned this:

> If your server supports custom flags, your other IMAP client(s) may be using a custom flag

**Comment by jstedfast** [comment]
The IMAP protocol allows each individual folder (mailbox in IMAP parlance) to specify which flags it supports.

What you need to do is check the folder's `PermanentFlags` property for the `MessageFlags.UserDefined` bit:

```csharp
if (folder.PermanentFlags.HasFlag (MessageFlags.UserDefined)) {
    // folder supports user-defined custom flags
}
```

Hope that helps.

**Comment by mspace** [comment]
Just want to add that this solves my issue of determining whether I can set custom flag on email message to specific folder. But it should be noted that Permanent flags get their value after folder is opened `inbox.Open(FolderAccess.ReadWrite);`. 

Perhaps you meant something else by 'Hope that helps'?
