### ISSUE TITLE
How to Group SearchQuery?

### ISSUE THREAD

**Issue by JobaDiniz** [jstedfast/MailKit#573]
How to use `SearchQuery` to group conditions, for example:
`FROM (x@email.com OR y@email.com) AND TO (a@a.com OR b@b.com)`

The way I see it, there is no way, because `SearchQuery` only contains `And` and `Or` and I can't group things...

**Comment by jstedfast** [comment]
Sure you can.

```csharp
var xOrY = SearchQuery.FromContains ("x@email.com").Or (SearchQuery.FromContains ("y@email.com"));
var aOrB = SearchQuery.FromContains ("a@email.com").Or (SearchQuery.FromContains ("b@email.com"));
var query = xOrY.And (aOrB);
```

**Comment by jstedfast** [comment]
FWIW, there's also an ImapFolder.Search() method that takes a raw search query string.

You might need to cast the IMailFolder to an ImapFolder first, though, since I don't think IMailFolder exposes it.

That said, I generally recommend using the SearchQuery API because it's impossible to search for literal strings using the string API (by literal strings I mean the way IMAP defines literal strings).

**Comment by dhaval-kateliya** [comment]
> 
how can we search using FromContains if we have list or array of address, means dynamic or condition with SearchQuery

**Comment by jstedfast** [comment]
Like This:

```csharp
var query = SearchQuery.FromContains (addresses[0]);
for (int i = 1; i < addresses.Length; i++)
    query = query.Or (SearchQuery.FromContains (addresses[i]));

var uids = folder.Search (query);
```

**Comment by dhaval-kateliya** [comment]
> Like This:
> 
> ```cs
> var query = SearchQuery.FromContains (addresses[0]);
> for (int i = 1; i < addresses.Length; i++)
>     query = query.Or (SearchQuery.FromContains (addresses[i]));
> 
> var uids = folder.Search (query);
> ```

Hi, Thanks for reply 
I tried the same but gives compile time error for line` query = query.Or (SearchQuery.FromContains (addresses[i]));` as below
`Error	CS0029	Cannot implicitly convert type 'MailKit.Search.BinarySearchQuery' to 'MailKit.Search.TextSearchQuery'`

**Comment by jstedfast** [comment]
Change `var query = ...` to `SearchQuery query = ...`
