### ISSUE TITLE
How to Create draft message?

### ISSUE THREAD

**Issue by docrizwan** [jstedfast/MailKit#574]
How to create a "Draft" message (with or without attachment) and save it in email server using IMAP.

**Comment by jstedfast** [comment]
First, you need to create a normal message.

Then you need to use [ImapFolder.Append()](http://www.mimekit.net/docs/html/M_MailKit_MailFolder_Append_5.htm) like this:

```csharp
folder.Append (message, MessageFlags.Draft);
```

**Comment by docrizwan** [comment]
Do I need to "Expunge" the folder?
After what operations, the "Expunge" method calling is necessary?

**Comment by jstedfast** [comment]
You only need to Expunge if you want to purge messages (i.e. remove deleted messages).

**Comment by docrizwan** [comment]
Thank you.!
