### ISSUE TITLE
How to delete a message permanently?

### ISSUE THREAD

**Issue by docrizwan** [jstedfast/MailKit#575]
How can I delete a message permanently using IMAP. Reading articles and research about MailKit brought me two solutions.

1. Just open the folder and add "Deleted" flag with that message.
2. Mark the message as "Delete" and call "Expunge" method of the opened folder.

I am not clear about the "Expunge" method, Can you mention when to call of "Expunge" is necessary?

**Comment by jstedfast** [comment]
Adding the `MessageFlags.Deleted` to a message marks the message for deletion and most clients will stop showing the message at that point, but technically the message still exists on the server in the folder where it's always been.

To purge the message from the folder so it is no longer taking up space, you need to call the `Expunge()` method.

This is just how IMAP works. The `Expunge()` method corresponds with the IMAP `EXPUNGE` command.

You can read more about this in the specification: https://tools.ietf.org/html/rfc3501#page-49
