### ISSUE TITLE
How to Move a message to Trash folder?

### ISSUE THREAD

**Issue by docrizwan** [jstedfast/MailKit#576]
How can I move a message to trash folder/ label (not the permanent deletion)?
I have found two solutions.
1. Open the folder and mark it as "Deleted", that's it.
2. Open the folder and move the message to trash, 
    e.g. `myFolder.MoveTo( new [] { msgUid }, myClient.GetFolder(SpecialFolder.Trash));`

What's the better way?

**Comment by jstedfast** [comment]
If marking the message as "Deleted" moves it to the Trash folder, then you are probably using a non-standard IMAP server such as GMail in its default configuration.

Using MoveTo() is how you need to do it for any standard IMAP server.

For GMail, you can change its behavior by editing your GMail Settings.

![GMail POP3 and IMAP Settings](http://content.screencast.com/users/jeff.xamarin/folders/Jing/media/7d50dada-6cb0-4ab1-b117-8600fb5e07d4/00000022.png "GMail POP3 and IMAP Settings")

Step 1: Make sure the "Auto-Expunge" feature is disabled (this is standard behavior)
Step 2: Select "Immediately delete the message forever" when the EXPUNGE command is used.

You can see the exact settings you should use in the above screenshot as well.

**Comment by docrizwan** [comment]
Thank you!
