### ISSUE TITLE
Imap Inbox folder returning "sent" messages - Gmail

### ISSUE THREAD

**Issue by JobaDiniz** [jstedfast/MailKit#577]
In Gmail, I'm trying to fetch all inbox messages, but it returns messages that were **answered**. 
Is there a way to filter theses messages? I couln't find any method for that in `SearchQuery` class.

**Comment by jstedfast** [comment]
Any of these will work:

```csharp
var query = SearchQuery.Not (SearchQuery.HasFlags (MessageFlags.Answered));

// or

var query = SearchQuery.Not (SearchQuery.Answered);

// or

var query = SearchQuery.NotAnswered;
```
