### ISSUE TITLE
Details about IMAP/ POP/ SMTP capabilities?

### ISSUE THREAD

**Issue by docrizwan** [jstedfast/MailKit#579]
Where can I find the details about the client and server capabilities? Means, I can view the list in `ImapCapabilities` enum object, but I don't know the details and purposes of them, like Acl, XList, SpecialUse, Compress, etc.

Can you share me the material, so I can get an idea of them and will be able to use them intelligently?

**Comment by jstedfast** [comment]
The documentation for each Capability specifies which RFC contains the specifications for said capability and you can find the full list of specifications here: https://github.com/jstedfast/MailKit/tree/master/rfc

You can also find them online at https://tools.ietf.org/html/

As a quick hack, you can substitute the rfc #### in the following url and it will bring you to the specification: `https://tools.ietf.org/html/rfc####`

The MSDN-style documentation also links directly to the RFC *and* the section:

http://www.mimekit.net/docs/html/T_MailKit_Net_Imap_ImapCapabilities.htm
