### ISSUE TITLE
Alternative logic of Client/ Server Capabilities?

### ISSUE THREAD

**Issue by docrizwan** [jstedfast/MailKit#580]
How can I use the client and server capabilities (e.g. `ImapCapabilities`) for implementing alternative solutions?
For instance,
Gmail supports "SpecialUse/ XList" capabilities (I don't know what it is, but got this from generated exception), but a custom domain email (like my office email, %@averox.com does not support it.
What should be the alternative solution?
I used the below for just now:
```
if (client.Capabilities.HasFlag(ImapCapabilities.XList | ImapCapabilities.SpecialUse))
	drafts = client.GetFolder(SpecialFolder.Drafts);
else
	drafts = client.GetFolders(client.PersonalNamespaces[0]).FirstOrDefault(k => k.FullName.IndexOf("draft", StringComparison.InvariantCultureIgnoreCase) > -1);
```
Is it Okay? OR suggest a better way.

**Comment by jstedfast** [comment]
That's exactly how the Capabilities flags are supposed to be used.

**Comment by docrizwan** [comment]
How will I know if there is capability flag check is necessary?
1. By testing every operation of my client app on many different mail servers and getting exceptions and resolving each time?
Or specific flags checks are necessary? @jstedfast

**Comment by jstedfast** [comment]
The documentation for the various client and folder methods will typically specify what flags to check.

If you find a method that doesn't, tell me, and I'll fix the documentation.

**Comment by docrizwan** [comment]
Sorry, I didn't get, what documentation of client/ folders you're pointing to?

**Comment by jstedfast** [comment]
Well, since you asked about the Compress capability:

http://www.mimekit.net/docs/html/M_MailKit_Net_Imap_ImapClient_Compress.htm

Here's an example for the ID capability:

http://www.mimekit.net/docs/html/M_MailKit_Net_Imap_ImapClient_Identify.htm

The sample code snippet in that also shows how to use Acl and some other capabilities.

**Comment by jstedfast** [comment]
The Remarks section don't always mention the needed ImapCapability, but if you check the possible Exceptions list, any method that requires a certain capability be present will document that it can throw a NotSupportedException and in the docs for that exception, it will mention what capability is needed.

**Comment by docrizwan** [comment]
Thank you, Jeff. I had already seen that code snippet, but it's good that you reminded me.
I will try to use them. Thank you again.
