### ISSUE TITLE
How to use folder events?

### ISSUE THREAD

**Issue by docrizwan** [jstedfast/MailKit#581]
How can I use `IMailFolders` folder events to detect changes?
[Here](https://goo.gl/wCUnUr) you described, how to use `CountChanged` event but your program is waiting after assigning new event.

In my case, I recreate the clients on each transaction when the user commands any operation (like deletion, markRead, etc.). My client destroys each time, how can I use the folder events in such situation?

**Comment by jstedfast** [comment]
Well, once the client is destroyed, so are the folders, so there's no way to use their events.

The reason the sample waits is not because events have been subscribed to, but because the sample itself chose to wait until it got an event from the server.
