### ISSUE TITLE
Unexcepted disconnected when sending mails

### ISSUE THREAD

**Issue by zouwei1991** [jstedfast/MailKit#583]
I recently tried to sending emails with mailkit ,but got mistake like 'The SMTP server has unexpectedly disconnected.'  and i cann't figure out why.Belowe is my code to send email   
![image](https://user-images.githubusercontent.com/19298694/32160333-4652d522-bd8c-11e7-8188-d36c7abca127.png) .
can you give me some possible reasons that lead to the problem? By the way ,i use mailkit to send gmail emails.

**Comment by jstedfast** [comment]
If you get an unexpected disconnect, it means your computer lost the connection with the server which means either:

1. your network had a hickup
2. the server dropped your connection (maybe because it was overloaded)

The problem is not in your code and it's not in MailKit.

**Comment by jstedfast** [comment]
FWIW, TCP/IP connections get dropped all the time. You just have to reconnect and try again.
