### ISSUE TITLE
Can't authenticate with Gmail

### ISSUE THREAD

**Issue by andrewliang** [jstedfast/MailKit#585]
I'm trying to connect to Gmail using IMAP but I can't get passed authentication. I'm not sure what I'm doing wrong. When calling `client.Authenticate()`, it throws "MailKit.Security.AuthenticationException: 'Invalid credentials (Failure)'". I know for sure that I'm passing the correct username and password. I'm using my full email address as my username (eg: "some.email.address@gmail.com").

I have confirmed that IMAP is enabled for my account and I tested this by using Mozilla Firebird email client.

Here's Gmail IMAP settings: https://support.google.com/mail/answer/7126229?hl=en

Here's the code that I used to reproduce the issue. I replaced my real username and password for obvious reasons.
```
class Program
    {
        public static void Main(string[] args)
        {
            using (var client = new ImapClient(new ProtocolLogger("imap.log")))
            {
                // For demo-purposes, accept all SSL certificates
                client.ServerCertificateValidationCallback = (s, c, h, e) => true;

                client.Connect("imap.gmail.com", 993, true);

                // Note: since we don't have an OAuth2 token, disable
                // the XOAUTH2 authentication mechanism.
                client.AuthenticationMechanisms.Remove("XOAUTH2");

                client.Authenticate("some.email.address@gmail.com", "[my password]");

                // The Inbox folder is always available on all IMAP servers...
                var inbox = client.Inbox;
                inbox.Open(FolderAccess.ReadOnly);

                Console.WriteLine("Total messages: {0}", inbox.Count);
                Console.WriteLine("Recent messages: {0}", inbox.Recent);

                for (int i = 0; i < inbox.Count; i++)
                {
                    var message = inbox.GetMessage(i);
                    Console.WriteLine("Subject: {0}", message.Subject);
                }

                client.Disconnect(true);
            }
        }
    }
```
I would provide logs as instructed but it just contains my username and password that I'm not willing to share. 

If someone can tell me how I can get this code to properly authenticate with Gmail, that would be really helpful. Thank you so much!

**Comment by jstedfast** [comment]
Follow the Trouble Shooting directions on the site you linked. Did you enable “less secure apps”?

**Comment by andrewliang** [comment]
Thanks @jstedfast. I followed the troubleshooting section. I resolved this issue by creating an App password specifically for MailKit, and modifying the code to use this new App password. I find it odd that I did not have to do this for Firebird.

**Comment by jstedfast** [comment]
I don't need to do that for MailKit either... but I guess that's one way.

**Comment by jstedfast** [comment]
This is what I was driving at: https://support.google.com/accounts/answer/6010255

You only need app-specific passwords if you use 2-factor auth.

**Comment by jstedfast** [comment]
Also: Thunderbird supports OAuth 2.0 (so does MailKit, but it leaves it up to you to get the OAuth 2.0 credentials because there are so many OAuth 2.0 client libraries that I don't want to force you into a specific one).
