### ISSUE TITLE
SMTP Client does not send MAIL FROM in Pipelining-Mode

### ISSUE THREAD

**Issue by alex-becker-startp** [jstedfast/MailKit#587]
Hello,

the SMTP client does not send MAIL FROM part to the SMTP Server when the Pipelining-Mode is in use.
This seems only to occur in unencrypted sessions (e.g. plain SMTP on Port 25).

In the protocol-log the MAIL FROM line is contained, but on the mailserver only the following RCPT TO line is received.
I've checked the transmission with Wireshark. In fact the MAIL FROM line is not sent at all.

In addition, there is a massive delay until the server error is returned.
This is caused from pipelining, too. SmtpClient thinks it sent two commands, but the server did only receive one. Then the client waits for two responses, but the second one will never arrive.

As a workaround, I remove the PIPELINING capability just after an esablished connection. This works.

Best regards,
Alexander

Protocol-Log
--------------
```
Connected to smtp://mail:25/
S: 220 mail.startp.de VPOP3 ESMTP Server Ready
C: EHLO [192.168.1.114]
S: 250-mail.startp.de VPOP3 SMTP Server - Hello [192.168.1.114] (192.168.1.114), pleased to meet you
S: 250-AUTH LOGIN PLAIN CRAM-MD5
S: 250-AUTH=LOGIN PLAIN CRAM-MD5
S: 250-ENHANCEDSTATUSCODES
S: 250-SIZE 104857600
S: 250-DSN
S: 250-STARTTLS
S: 250-PIPELINING
S: 250 HELP
C: MAIL FROM:<carola.joerges@addPLM.com>
C: RCPT TO:<Alexander.Becker@addPLM.com>
S: 503 5.5.1 Need MAIL before RCPT
C: RSET
```

Corresponding log from the SMTP-Server
-------------------------------------------------
```
9/11/2017 13:53:59.214 - 00001aaf<EHLO [192.168.1.114]
9/11/2017 13:53:59.214 - 00001aaf>250-mail.startp.de VPOP3 SMTP Server - Hello [192.168.1.114] (192.168.1.114), pleased to meet you
250-AUTH LOGIN PLAIN CRAM-MD5
250-AUTH=LOGIN PLAIN CRAM-MD5
250-ENHANCEDSTATUSCODES
250-SIZE 104857600
250-DSN
250-STARTTLS
250-PIPELINING
250 HELP
9/11/2017 13:53:59.245 - 00001aaf<RCPT TO:<Alexander.Becker@addPLM.com>
9/11/2017 13:53:59.245 - 00001aaf>503 5.5.1 Need MAIL before RCPT
```

**Comment by jstedfast** [comment]
Anything that makes it to the protocol log has been written to the socket. That's how the logging client works. It does socket.Write() and then logger.Write() with the same arguments.

I don't see how this is possible.

I also have a unit test that actually tests this and it passes saying that the expected data was written.

Since this works flawlessly for me, do you think you could debug it on your end and show me where my code is going wrong?

**Comment by jstedfast** [comment]
The Send() method implementation starts here: https://github.com/jstedfast/MailKit/blob/master/MailKit/Net/Smtp/SmtpClient.cs#L1700

That's where the methods that handle sending the MAIL FROM and RCPT TO commands are invoked:

```csharp
// Note: if PIPELINING is supported, MailFrom() and RcptTo() will
// queue their commands instead of sending them immediately.
MailFrom (format, message, sender, extensions, cancellationToken);

int accepted = 0;
for (int i = 0; i < recipients.Count; i++) {
	if (RcptTo (format, message, recipients[i], cancellationToken))
		accepted++;
}

if (queued.Count > 0) {
	// Note: if PIPELINING is supported, this will flush all outstanding
	// MAIL FROM and RCPT TO commands to the server and then process all
	// of their responses.
	FlushCommandQueue (message, sender, recipients, cancellationToken);
} else if (accepted == 0) {
	OnNoRecipientsAccepted (message);
}
```

The implementation of MailFrom is here: https://github.com/jstedfast/MailKit/blob/master/MailKit/Net/Smtp/SmtpClient.cs#L1411

You'll notice that if the server supports PIPELINING, it uses `QueueCommand()` which can be found here: https://github.com/jstedfast/MailKit/blob/master/MailKit/Net/Smtp/SmtpClient.cs#L342

```csharp
void QueueCommand (SmtpCommand type, string command, CancellationToken cancellationToken)
{
	var bytes = Encoding.UTF8.GetBytes (command + "\r\n");

	// Note: queued commands will be buffered by the stream
	Stream.Write (bytes, 0, bytes.Length, cancellationToken);
	queued.Add (type);
}
```

`Stream`, here, is an `SmtpStream` which has an output buffer of 4K. When that buffer fills up, it flushes it to the socket. And that logic in `SmtpStream.Write()` is here: https://github.com/jstedfast/MailKit/blob/master/MailKit/Net/Smtp/SmtpStream.cs#L595

All writes, whether queued or not, go through this method.

Hopefully that helps you track down this bug...

**Comment by jstedfast** [comment]
Since your example only has 1 sender and 1 recipient, both commands are likely being added to that output buffer in `SmtpStream` and then that output buffer gets flushed in `SmtpStream.Flush()` which writes everything in that output buffer.

**Comment by jstedfast** [comment]
Are you *sure* that the `MAIL FROM` command appears in the log when PIPELINING is enabled?

**Comment by alex-becker-startp** [comment]
I've compiled MailKit for myself and stepped into it.
Everything is OK until Stream.Write() is called in SmtpStream.Flush().

I've added some debugging code to Flush() before the actual write:
```
var ms = new MemoryStream();
ms.Write(output, 0, outputIndex);
var arr = ms.ToArray();
var sendText = System.Text.Encoding.UTF8.GetString(arr);
```

From this I can tell that both lines (MAIL FROM and RCPT TO) is in the output buffer.

1st Flush() sendText content:
`EHLO [192.168.1.105]`

2nd Flush() sendText content:
`MAIL FROM:<A.Becker@StartP.de>`
`RCPT TO:<A.Becker@StartP.de>`

Parallel I recorded the complete network traffic with Wireshark, and there the MAIL FROM line is not contained within the SMTP data session:

```
<220 mail.startp.de VPOP3 ESMTP Server Ready
>EHLO [192.168.1.105]
<250-mail.startp.de VPOP3 SMTP Server - Hello [192.168.1.105] (192.168.1.105), pleased to meet you
<250-AUTH LOGIN PLAIN CRAM-MD5
<250-AUTH=LOGIN PLAIN CRAM-MD5
<250-ENHANCEDSTATUSCODES
<250-SIZE 104857600
<250-DSN
<250-STARTTLS
<250-PIPELINING
<250 HELP
>RCPT TO:<A.Becker@StartP.de>
<503 5.5.1 Need MAIL before RCPT
```

I am completely puzzled with this result and have no clue where to continue with debugging now.
Alex.

**Comment by jstedfast** [comment]
At least I'm not crazy :)

Sounds like possibly a bug in `System.Net.NetworkStream`? That would seem like a very odd bug in `NetworkStream`, but I'm not sure how else to explain it unless Wireshark has a bug in that maybe it's getting confused because it is expecting single-line writes from the client to the server and it is just matching the last line in the packet?

**Comment by jstedfast** [comment]
If you look at the raw packets in Wireshark instead of doing the Follow -> TCP Stream, does it show it then?

**Comment by alex-becker-startp** [comment]
The raw packets in Wireshark do not contain the MAIL FROM line, too.
I even checkt the packet sizes...
And the SMTP service log (which ever was very reliable) tells the same.
Strange.

For now the hack with disabling pipelining is OK for me.
If I have some time to do so, I'll try to step debug into the System.Net.NetworkStream class....
Should be possible according to https://msdn.microsoft.com/en-us/library/cc667410.aspx

**Comment by jstedfast** [comment]
I'm going to close this since it doesn't /seem/ like it's a bug in MailKit, but I'm very interested in what you find when you debug into NetworkStream.

Keep me posted and if there's something MailKit *is* doing wrong, let me know and hopefully armed with whatever you find, we'll be able to fix this.

Thanks!
