### ISSUE TITLE
a problem when delete emails

### ISSUE THREAD

**Issue by PanChenhao** [jstedfast/MailKit#589]
Code as Below
```
client.ServerCertificateValidationCallback = (s, c, h, e) => true;

                // client.Connect("pop.qq.com", 995, true);
                client.Connect("imap.qq.com", 993, true);
                // Note: since we don't have an OAuth2 token, disable
                // the XOAUTH2 authentication mechanism.  
                client.AuthenticationMechanisms.Remove("XOAUTH2");

                client.Authenticate("113729396@qq.com", "nathan2013");
                List<UniqueId> Uids = new List<UniqueId> { };
                request.Uids.ForEach(e=> {
                    Uids.Add(new UniqueId(e));
                });
                var inbox = client.Inbox;
                inbox.Open(FolderAccess.ReadWrite);
                inbox.AddFlags(Uids,MessageFlags.Deleted, false);
               // inbox.Expunge(Uids);
                client.Disconnect(true);

but comes out an error info:
`MailKit.Net.Imap.ImapCommandException:“The IMAP server replied to the 'STORE' command with a 'BAD' response: UID parameters!”`

Is there anyone can help me?
```

**Comment by jstedfast** [comment]
When you submitted this issue, the template should have told you to get a protocol log to diagnose problems like these. Did you get a protocol log?

**Comment by PanChenhao** [comment]
@jstedfast  below is the protocol log. what's the problem?

Connected to imaps://imap.qq.com:993/
S: * OK [CAPABILITY IMAP4 IMAP4rev1 ID AUTH=LOGIN NAMESPACE] QQMail IMAP4Server ready
C: B00000000 AUTHENTICATE LOGIN
S: + VXNlciBOYW1lAA==
C: MTEzNzI5Mzk2QHFxLmNvbQ==
S: + UGFzc3dvcmQA
C: bmF0aGFuMjAxMw==
S: B00000000 OK Success login ok
C: B00000001 CAPABILITY
S: * CAPABILITY IMAP4 IMAP4rev1 XLIST MOVE IDLE XAPPLEPUSHSERVICE NAMESPACE CHILDREN ID UIDPLUS
S: B00000001 OK CAPABILITY Completed
C: B00000002 NAMESPACE
S: * NAMESPACE (("" "/")) NIL NIL
S: B00000002 OK NAMESPACE Success
C: B00000003 LIST "" "INBOX"
S: * LIST (\HasNoChildren) "/" "INBOX"
S: B00000003 OK LIST completed
C: B00000004 XLIST "" "*"
S: * XLIST (\NoSelect \HasChildren) "/" "&UXZO1mWHTvZZOQ-"
S: * XLIST (\HasNoChildren \Inbox) "/" "INBOX"
S: * XLIST (\HasNoChildren \Sent) "/" "Sent Messages"
S: * XLIST (\HasNoChildren \Drafts) "/" "Drafts"
S: * XLIST (\HasNoChildren \Trash) "/" "Deleted Messages"
S: * XLIST (\HasNoChildren \Junk) "/" "Junk"
S: B00000004 OK XLIST completed
C: B00000005 SELECT INBOX
S: * 1811 EXISTS
S: * 0 RECENT
S: * OK [UNSEEN 94]
S: * OK [UIDVALIDITY 1338330244] UID validity status
S: * OK [UIDNEXT 7069] Predicted next UID
S: * FLAGS (\Answered \Flagged \Deleted \Draft \Seen)
S: * OK [PERMANENTFLAGS (\* \Answered \Flagged \Deleted \Draft \Seen)] Permanent flags
S: B00000005 OK [READ-WRITE] SELECT complete
C: B00000006 UID STORE 7067:7065 +FLAGS (\Deleted)
S: B00000006 BAD UID parameters!

**Comment by jstedfast** [comment]
The problem *might* be the reverse order of the UIDs?

Technically, that is supposed to be legal according to the specification, but I also know from experience that some IMAP servers do not (or at least did not) handle that very well.

Try sorting your UIDs in ascending order first. See if that fixes it.

**Comment by jstedfast** [comment]
Relevant portion of the spec:

```
seq-range       = seq-number ":" seq-number
                    ; two seq-number values and all values between
                    ; these two regardless of order.
                    ; Example: 2:4 and 4:2 are equivalent and indicate
                    ; values 2, 3, and 4.
                    ; Example: a unique identifier sequence range of
                    ; 3291:* includes the UID of the last message in
                    ; the mailbox, even if that value is less than 3291.
```

**Comment by jstedfast** [comment]
Did my suggestion help? Yes? No? Maybe so?

**Comment by PanChenhao** [comment]
I have add Uids.Sort(). There is no error message came out. but the email were not deleted.

```
 List<UniqueId> Uids = new List<UniqueId> { };
                request.Uids.ForEach(e=> {
                    Uids.Add(new UniqueId(e));
                });
                **Uids.Sort();**
                var inbox = client.Inbox;
                inbox.Open(FolderAccess.ReadWrite);
                inbox.AddFlags(Uids,MessageFlags.Deleted, true);
               // inbox.Expunge(Uids);
                client.Disconnect(true);
```

**Comment by PanChenhao** [comment]
@jstedfast  Thank you very much.   below is the protocol  log, can you find out the reason?
`Connected to imaps://imap.qq.com:993/
S: * OK [CAPABILITY IMAP4 IMAP4rev1 ID AUTH=LOGIN NAMESPACE] QQMail IMAP4Server ready
C: A00000000 AUTHENTICATE LOGIN
S: + VXNlciBOYW1lAA==
C: MTEzNzI5Mzk2QHFxLmNvbQ==
S: + UGFzc3dvcmQA
C: bmF0aGFuMjAxMw==
S: A00000000 OK Success login ok
C: A00000001 CAPABILITY
S: * CAPABILITY IMAP4 IMAP4rev1 XLIST MOVE IDLE XAPPLEPUSHSERVICE NAMESPACE CHILDREN ID UIDPLUS
S: A00000001 OK CAPABILITY Completed
C: A00000002 NAMESPACE
S: * NAMESPACE (("" "/")) NIL NIL
S: A00000002 OK NAMESPACE Success
C: A00000003 LIST "" "INBOX"
S: * LIST (\HasNoChildren) "/" "INBOX"
S: A00000003 OK LIST completed
C: A00000004 XLIST "" "*"
S: * XLIST (\NoSelect \HasChildren) "/" "&UXZO1mWHTvZZOQ-"
S: * XLIST (\HasNoChildren \Inbox) "/" "INBOX"
S: * XLIST (\HasNoChildren \Sent) "/" "Sent Messages"
S: * XLIST (\HasNoChildren \Drafts) "/" "Drafts"
S: * XLIST (\HasNoChildren \Trash) "/" "Deleted Messages"
S: * XLIST (\HasNoChildren \Junk) "/" "Junk"
S: A00000004 OK XLIST completed
C: A00000005 SELECT INBOX
S: * 1792 EXISTS
S: * 0 RECENT
S: * OK [UNSEEN 94]
S: * OK [UIDVALIDITY 1338330244] UID validity status
S: * OK [UIDNEXT 7083] Predicted next UID
S: * FLAGS (\Answered \Flagged \Deleted \Draft \Seen)
S: * OK [PERMANENTFLAGS (\* \Answered \Flagged \Deleted \Draft \Seen)] Permanent flags
S: A00000005 OK [READ-WRITE] SELECT complete
C: A00000006 UID STORE 7066:7067,7078 +FLAGS.SILENT (\Deleted)
S: A00000006 OK UID STORE Completed
C: A00000007 LOGOUT
S: * BYE LOGOUT received
S: A00000007 OK LOGOUT Completed
78 FLAGS (\Deleted \Seen))
S: F00000006 OK UID STORE Completed
C: F00000007 LOGOUT
S: * BYE LOGOUT received
S: F00000007 OK LOGOUT Completed
 BYE LOGOUT received
S: B00000007 OK LOGOUT Completed`

**Comment by jstedfast** [comment]
Looks like it worked to me:

```
S: A00000005 OK [READ-WRITE] SELECT complete
C: A00000006 UID STORE 7066:7067,7078 +FLAGS.SILENT (\Deleted)
S: A00000006 OK UID STORE Completed
```

FWIW, `AddFlags` just marks messages with the `\Deleted` flag. It doesn't remove them from the folder.

In order to remove them from the folder, you need to call the `Expunge` method.
