### ISSUE TITLE
ASP.NET FileResult as attachment

### ISSUE THREAD

**Issue by robertpmansion** [jstedfast/MailKit#590]
We have an ExcelResult based on the ASP.NET MVC FileResult. What this does is it creates an excel file based on the data we generated and the users are able to download this. However, due to some changes in requirements, we want to send this excel file to a user through email. My question is how do I convert this ExcelResult based on FileResult as an attachment or if not convert use this as an attachment?

**Comment by jstedfast** [comment]
There doesn't appear to be any way to get the actual content of the file based on what I can tell from the FileResult class.

You can get the `ContentType` and `DownloadFileName` strings tho, that's kinda nice...

Can you use this to get the contents? https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.filecontentresult.filecontents?view=aspnetcore-2.0#Microsoft_AspNetCore_Mvc_FileContentResult_FileContents

If so... you could do this:

```csharp
var contentType = ContentType.Parse (fileResult.ContentType);
var part = new MimePart (contentType);

part.FileName = fileResult.DownloadFileName;

part.ContentObject = new ContentObject (new MemoryStream (fileResult.FileContents, false));
```

or, if you would prefer to use the `BodyBuilder` class to construct your message, you could do:

```csharp
var contentType = ContentType.Parse (fileResult.ContentType);

bodyBuilder.Attachments.Add (fileResult.DownloadFileName, fileResult.FileContents, contentType);
```
