### ISSUE TITLE
Usage Question: Keep checking folder folder for message until found

### ISSUE THREAD

**Issue by Bitz** [jstedfast/MailKit#592]
I am trying to read the contents of an IMAP Inbox folder, checking every 5 seconds to see if I got a reply from a  specific user. 

The critera would obviously be as such:

`var query = SearchQuery.NotSeen.And(SearchQuery.SubjectContains(search)).And(SearchQuery.FromContains(Config.mail.to.ToLower()));`

Where `search` is the original subject- presumably it will carry a similar title- ie) if the original message was subjected "Hello", it should find "RE: Hello".

And... `Config.mail.to.ToLower()` contains a mail address such as "abc@gmail.com".

And this is how I keep "watching" the folder:

```
var inbox = client.Inbox;
inbox.Open(FolderAccess.ReadWrite);

var query = SearchQuery.NotSeen.And(SearchQuery.SubjectContains(search)).And(SearchQuery.FromContains(Config.mail.to.ToLower()));

Stopwatch st = new Stopwatch();
st.Start();
while (string.IsNullOrEmpty(result) && st.ElapsedMilliseconds < 600000) //Wait 10 minutes.
{
	foreach (UniqueId uid in inbox.Search(query))
	{
		var message = inbox.GetMessage(uid);
		result = message.TextBody.Split('\r', '\n').FirstOrDefault();
		inbox.AddFlags(uid, MessageFlags.Deleted, true);
		break;
	}
	Thread.Sleep(5000);
}
st.Stop();
```

Currently- it works sometimes and at other times it fails to find the message. What about my usage makes it finicky? What am I doing wrong?

Is this the best way to approach "waiting" for a message?

**Comment by jstedfast** [comment]
I would say that's a pretty inefficient way of waiting for the message...

Why search the entire folder for the message when you *know* it has to be a message that arrived *since* your previous query?

To be more efficient, try only querying messages with a higher UniqueId than what you've already seen.

Secondly, take a look at the `ImapIdle` sample in the samples directory of this repo. In Program.cs, you will see how to efficiently wait for new messages to arrive.

In the `CountChanged` event handler, you will want to call `done.Cancel ()` (which will require some rearranging of the code so that you have access to it inside the handler). That will kick you out of the IDLE loop. Once you are out, *then* send your search query for messages with a higher UID than what you've seen.

To get the max UID you've seen in your Search, capture the ImapFolder.NextUid property before you start idling.

Then, once new messages have arrived, you can modify your search to be:

```csharp
var range = SearchQuery.Uids (new UniqueIdRange (nextUid, UniqueId.MaxValue));
foreach (UniqueId uid in inbox.Search(range, query))
 {
    ...
}
```

**Comment by Bitz** [comment]
I'm honestly pretty new at cancellation tokens so I'm not sure about what I'm doing wrong- 
I oped for the `MessagesArrived` event handler- that one seemed a bit more appropriate. 

```
var query = SearchQuery.NotSeen
	.And(SearchQuery.SubjectContains(search))
	.And(SearchQuery.FromContains(Config.mail.to.ToLower()))
	.And(SearchQuery.Uids(new UniqueIdRange(nextUid, UniqueId.MaxValue)));

using (CancellationTokenSource done = new CancellationTokenSource())
{
	var thread = new Thread(IdleLoop);

	thread.Start(new IdleState(client, done.Token));
	client.Inbox.MessagesArrived += (sender, e) =>
	{
		C.WriteLine("You got mail!");
		done.Cancel();
		thread.Join();
	};
	Console.ReadKey();
	done.Cancel();
	thread.Join();
}


foreach (UniqueId uid in inbox.Search(query))
{
	var message = inbox.GetMessage(uid);
	result = message.TextBody.Split('\r', '\n').FirstOrDefault();
	inbox.AddFlags(uid, MessageFlags.Deleted, true);

	if (result != null && result.ToLower().ToLower() == "cancel")
	{
		C.WriteLine("We won't be proceeding with this post...");
		Environment.Exit(0);
	}
	else
	{
		C.WriteLine("We got a title!");
	}
	break;
}
```
This doesn't work- and I'm pretty sure it's because I'm misusing the cancellation tokens.

**Comment by jstedfast** [comment]
The MessagesArrived event is a hack that I'm planning to drop as it makes assumptions that aren't necessarily true.

Subscribe to the CountChanged event instead.

Try something more like this (untested):

```csharp
var query = SearchQuery.NotSeen
	.And(SearchQuery.SubjectContains(search))
	.And(SearchQuery.FromContains(Config.mail.to.ToLower()));
var nextUid = inbox.NextUid;
var done = new CancellationTokenSource();
var thread = new Thread(IdleLoop);

client.Inbox.CountChanged += (sender, e) =>
{
    C.WriteLine("You got mail!");
    done.Cancel();
};

thread.Start(new IdleState(client, done.Token));
thread.Join();
done.Dispose ();

var range = new UniqueIdRange (nextUid, UniqueId.Max);
foreach (var uid in inbox.Search (range, query))
{
	var message = inbox.GetMessage(uid);
	result = message.TextBody.Split('\r', '\n').FirstOrDefault();
	inbox.AddFlags(uid, MessageFlags.Deleted, true);

	if (result != null && result.ToLower().ToLower() == "cancel")
	{
		C.WriteLine("We won't be proceeding with this post...");
		Environment.Exit(0);
	}
	else
	{
		C.WriteLine("We got a title!");
	}
	break;
}
```
