### ISSUE TITLE
 MailKit.Net.Pop3.Pop3ProtocolException

### ISSUE THREAD

**Issue by anyasorchigozie** [jstedfast/MailKit#594]
To help me debug your issue, please explain:
- What were you trying to do?
Hi,
i am trying to establish connection to my pop3
this is my line of code 
**Pop3 = new Pop3Client();
Pop3.Connect("mymailserver", port, false);**
- What happened?
got an exception
**Additional information: Unexpected greeting from server: 220 mymailserver Microsoft ESMTP MAIL Service ready at Wed, 29 Nov 2017 10:57:08 +0100**
- What did you expect to happen?
My expectation is for it to establish the connection to enable my application proceed to authenticate the credentials i supplied. 

Your kind assistance will be appreciated.

**Comment by jstedfast** [comment]
You are connecting a Pop3Client to an SMTP server and/or port. That won’t work. You need to connect to the POP3 port (110).

**Comment by anyasorchigozie** [comment]
Hi jstedfast 
Thanks for responding.

it isi fine now.

However am getting this:

An unhandled exception of type 'System.Security.Authentication.AuthenticationException' occurred in MailKit.dll

Additional information: The remote certificate is invalid according to the validation procedure.
am working with c#

**Comment by jstedfast** [comment]
The problem seems to be that your POP3 server supports the STLS command but has an invalid SSL/TLS certificate.

You have 2 options:

1. override the ServerCertificateValidationCallback (see the README.md and/or the FAQ.md for how to do this).
2. Use the following Connect method: `pop3.Connect (hostName, port, SecureSocketOptions.None);`

**Comment by anyasorchigozie** [comment]
Wow item 2 worked for me.

But am presented with this challenge now even though am using the right details:

An unhandled exception of type 'MailKit.Security.AuthenticationException' occurred in MailKit.dll

**Additional information: Authentication failed.**

**Comment by jstedfast** [comment]
Most likely MailKit is trying to use XOAUTH2, but you are not providing OAuth2 credentials - you are providing the standard user/pass credentials which are not the same.

Disable it like this:

```csharp
pop3.AuthenticationMechanisms.Remove ("XOAUTH2");
```

**Comment by anyasorchigozie** [comment]
Hi Jstedfast

I already have that in my code as this:

 Pop3.AuthenticationMechanisms.Remove("XOAUTH2");
 Pop3.Authenticate(this.User, this.Pwd);

it fails at  **Pop3.Authenticate(this.User, this.Pwd);**

**Comment by jstedfast** [comment]
I dunno, try getting a protocol log and seeing what is being sent to the server and what the server is responding with.

See here for how to get a protocol log:
https://github.com/jstedfast/MailKit/blob/master/FAQ.md#ProtocolLog

**Comment by anyasorchigozie** [comment]
hi

what could be the reason for this error:

'Pop3.Count' threw an exception of type 'MailKit.ServiceNotAuthenticatedException'

**Comment by jstedfast** [comment]
It means you aren't authenticated.
