### ISSUE TITLE
ImapCommand untagged responses

### ISSUE THREAD

**Issue by ekalchev** [jstedfast/MailKit#595]
Hey Jeffrey,

I need your advice on this. I don't want to have logic inside IMailFolder untagged response handlers like CountChanged and Expunge but I want to fill a Queue with entries and then work with those as a Batch to avoid executing SQL queries for each event. I am planning to execute my queue right after MoveTo command which should be equal to IMAP OK response (which mark the end of imap command). However I wonder if this will work for MoveTo since in certain condition I can execute two imap commands copy + expunge and I won't be able to execute my queue after copy.

**Comment by jstedfast** [comment]
Could you explain in more detail what exactly you are trying to do? I'm kind of lost. Maybe a bit more context will help.

**Comment by ekalchev** [comment]
I am moving 10000+ email. That generates 10000 expunge and 10000 exists responses from the server. I have events handlers that hit my database for each response. I would like to optimize that by grouping expunge responses in a batch and then execute them with one query. The problem is I don't know when the command ends. My first guess was right after MoveTo call but sometimes that could be two commands (Copy + Delete depending if the server support Move imap extension).

**Comment by jstedfast** [comment]
Yes, you must evaluate untagged responses right away.

If you want to reduce Expunge commands, just use the CopyTo() method instead of MoveTo() if/when the server does not support the MOVE extension:

```csharp
if (client.Capabilities.HasFlag (ImapCapabilities.Move)) {
    folder.MoveTo (uids, targetFolder);
} else {
    folder.CopyTo (uids, targetFolder);
    folder.AddFlags (uids, MessageFlags.Deleted, false);
    folder.Expunge (uids);
}
