### ISSUE TITLE
Mailkit to  get mail

### ISSUE THREAD

**Issue by sour7230** [jstedfast/MailKit#598]
System.NotSupportedException: No data is available for encoding 51936. For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvider method.

**Comment by jstedfast** [comment]
If you are using .NET Core, you need to register encodings.

See https://github.com/jstedfast/MimeKit/issues/330

**Comment by sour7230** [comment]
issue was not resolved ,kindly check it.

[image: Inline image 1]


* Thank and regards*

*Sourabh Saini*
Software Engineer
Expert Tech Source Pvt Ltd.
333-334 A Tower,
Spaze IT Tech Park
Sector-49, Gurgaon (Harayna).

Mob. 07042507252


On Wed, Dec 13, 2017 at 11:48 PM, Jeffrey Stedfast <notifications@github.com

**Comment by jstedfast** [comment]
Can you send me a pull request to fix it properly then?

**Comment by sour7230** [comment]
ssue was not resolved ,kindly check it.

![image](https://user-images.githubusercontent.com/26112010/33957348-6067f0ca-e067-11e7-90f8-eff25f042918.png)

**Comment by jstedfast** [comment]
If you want me to fix it, you need to tell me how to reproduce the problem. Start with telling me what type of project you created and how I can duplicate that (i.e. which options did you enable?).

Then tell me how you added the MailKit nuget and which MailKit assembly is being referenced (net45? netstandard? net461? a PCL?)

**Comment by jstedfast** [comment]
Or better yet, just zip up your project and send it to me (either via email or link me to a dropbox or something).

**Comment by jstedfast** [comment]
Looks like you created a Cross Platform -> Xamarin.Forms App and selected ".NET Standard" for your code-sharing strategy based on my fiddling with creating projects.

Unfortunately for you, I don't get any exceptions when creating new MimeMessages when I go to run my compiled app.

It works perfectly fine for me.

**Comment by sour7230** [comment]
Yes,you are right .I will make email client in xamarin,more over I am new
in xamarin application.so I will send you code zip for your
better ​​​understanding.
​
 App5.rar
<https://drive.google.com/file/d/18PxdThg4aZC4ND2qwef4TGjJRbkf4OPe/view?usp=drive_web>
















On 14 Dec 2017 2:22 am, "Jeffrey Stedfast" <notifications@github.com> wrote:

Looks like you created a Cross Platform -> Xamarin.Forms App and selected
".NET Standard" for your code-sharing strategy based on my fiddling with
creating projects.

Unfortunately for you, I don't get any exceptions when creating new
MimeMessages when I go to run my compiled app.

It works perfectly fine for me.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/jstedfast/MailKit/issues/598#issuecomment-351518285>,
or mute the thread

**Comment by jstedfast** [comment]
You need to go into your Android and iOS project's Project Options and check the checkboxes for the various charset locales:

https://www.screencast.com/t/97OxahwPrg

**Comment by sour7230** [comment]
Thanks for continouisly reply.


Error is still remains same.i checked that checkbox on both project.may I
request you can send me fully compiled code over the mail or as you won't.

**Comment by jstedfast** [comment]
When I create a new Cross Platform Mobile App and select ".NET Standard" as my code-sharing option, my Android and iOS projects themselves are not ".NET Standard", but in *your* project, they are.

In *my* project, I get no exceptions when I create a new MimeMessage. In your project, you do.

I'm using the latest version of Visual Studio (15.5.2). What did you use to create your initial project from a template?

**Comment by jstedfast** [comment]
In other words, when *I* create a new project, I end up with the following 3 projects:

- App# (which is .NETStandard 2.0)
- App#.Android (which is NOT .NETStandard 2.0)
- App#.iOS (which is NOT .NETStandard 2.0)

*Your* project is like this:

- App# (which is .NETStandard 2.0)
- App#.Android (which is .NETStandard 2.0)
- App#.iOS (which is .NETStandard 2.0)

This is probably what is causing things to fail. I don't know how you got your current project, but I know that at least iOS does not support being built as netstandard2.0 yet (I'm not sure of android).

That's probably confusing the hell out of the Android and/or iOS runtimes and causing them to break.

**Comment by sour7230** [comment]
i did all the things, Moreover i used  Portable.Text.Encoding  to register
to encoding type. but position still remain same.
i need your help end this issue.

thanks for replay.



* Thank and regards*

*Sourabh Saini*
Software Engineer
Expert Tech Source Pvt Ltd.
333-334 A Tower,
Spaze IT Tech Park
Sector-49, Gurgaon (Harayna).

Mob. 07042507252

**Comment by jstedfast** [comment]
I can't help you because the problem is not with MimeKit or MailKit, it's a problem with your setup.

You need the Android and iOS projects to not be netstandard2.0. Then it will work.

**Comment by sour7230** [comment]
I was send you my complied code two days ago.can you change that code as
your understanding or send New app where you use mimekit.and send to me
that code or new app over the mail or as your convenient.
                      I did all the solution but i didnot get any
success.this issue already posted on xamarin forum by me yesterday evening.



Thanks for your better reply.i hope you well help me again.

On 16 Dec 2017 2:35 am, "Jeffrey Stedfast" <notifications@github.com> wrote:

I can't help you because the problem is not with MimeKit or MailKit, it's a
problem with your setup.

You need the Android and iOS projects to not be netstandard2.0. Then it
will work.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/jstedfast/MailKit/issues/598#issuecomment-352111639>,
or mute the thread

**Comment by sour7230** [comment]
Issue Has been Resolved.



* Thank and regards*

*Sourabh Saini*
Software Engineer
Expert Tech Source Pvt Ltd.
333-334 A Tower,
Spaze IT Tech Park
Sector-49, Gurgaon (Harayna).

Mob. 07042507252

**Comment by polterguy** [comment]
Hi Jeffrey, for weird reasons, apparently out of the blue, all of a sudden, I am experiencing this exact same error. As far as I know, there's no Chinese in my code or my data. The error occurs when I try the following.

```
MimePart retVal = new MimePart ("application/x-hyperlambda");
```

System ==> .Net Fr. 4.5.2 (Mono) + MimeKit 2.0.0 and BC 1.8.1 + Mac OSX using Xamarin Studio (Visual Studio for OSX)

The weird part is that this worked perfectly fine until just _now_ ...???

**Comment by jstedfast** [comment]
Which version of Mono? There was a Mono runtime bug causing this a few months ago but was fixed in either 5.8 or 5.10 (I forget which)

**Comment by polterguy** [comment]
I am not sure, I am using Visual Studio for OSX (Xamarin Studio) with .Net Fr. 4.5.2 ...

**Comment by polterguy** [comment]
Sorry, my bad - Just completely ignore that one (blush!)

**Comment by jstedfast** [comment]
In Xamarin Studio, if you go to the "Xamarin Studio" menu, click "About" and then in the About Dialog click the "Show Details" button in the lower right corner, it will give you a list of versions of all installed components.

Mono should be at the top. For example, this is what mine says at the top:

```
Visual Studio Enterprise 2017 for Mac (Preview)
Version 7.6 Preview (7.6 build 947)
Installation UUID: 119afeba-010d-4f09-8021-f77e92bcb3e7
Runtime:
	Mono 5.16.0.5 (2018-06/7627a5f9eeb) (64-bit)
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 4.4.0.36 (master / 0c7c49a6)
```

The other possibility is that your project is referencing the netstandard nuget, but assuming that it's the the packages.config here: phosphorusfive/plugins/extras/p5.mime/packages.config

then it looks like it references the net452 framework (which matches what you've been saying), which means it *should* be referencing the net45 assembly (MimeKit nuget packages do not include a 4.5.2 assembly).

**Comment by polterguy** [comment]
There was another bug in my code, and I set it to break on all exceptions, and an exception (which probably) was caught stopped my debugger at that point, while it actually was a completely different bug that was the cause ...

Sorry (blush!)

I should have done more research before jumping to conclusions ... :)

Thx for the recipe of figuring out .Net version though ...

**Comment by jstedfast** [comment]
Ah, ok :)
