### ISSUE TITLE
Strange TLS problem with ImapClient

### ISSUE THREAD

**Issue by alex-becker-startp** [jstedfast/MailKit#600]
Hi Jeffrey,

when I try to connect IMAP with TLS the connection procedure hangs.
I've drilled this down to the place where the data stream is encapsulated in a TLS stream:
The call tls.AuthenticateAsClient(host) does never return.

After some digging I found out that it works when the TAG (A0000000n) of the STARTTLS command does not exceed one single char.
All other commands before and after STARTTLS are okay with the 9-digit numeric tag.

So I added some lines to ImapCommand.Step() to "fix" this issue.

```csharp
	// construct and write the command tag if this is the initial state
	if (current == 0) {
		Tag = string.Format ("{0}{1:D8}", Engine.TagPrefix, Engine.Tag++);

        // change the TAG to a one-char X to fix the TLS-upgrade hang
        var partCommand = parts[current].Command;
		var partText = System.Text.Encoding.ASCII.GetString(partCommand);
		if (partText.StartsWith("STARTTLS"))
			Tag = "X";

		var buf = Encoding.ASCII.GetBytes (Tag + " ");
		Engine.Stream.Write (buf, 0, buf.Length, CancellationToken);
	}
```

Something about this is very strange.
The problem occours only if I am in the same network as the server (@work) without a router between.
When I connect via VPN or from external via portforward the connection works well.

I've checked what thunderbird does, and a wireshark shows me tb uses integer Tags which starts from 1 increasing.
So the STARTTLS command has a one-digit tag because of this approach.

Alexander

**Comment by alex-becker-startp** [comment]
Just when I posted the issue, I had a little flash of insight.
My anti virus scanner (GData) has some transparent proxy functionality for email.
When I disable the port monitoring for 143 in this proxy, the problem is all gone.
I've written a support request to GData, lets see what they tell me about this...

**Comment by jstedfast** [comment]
Glad you found the proble.
