### ISSUE TITLE
Cannot retrieve emails when running program through CLI

### ISSUE THREAD

**Issue by nismolo** [jstedfast/MailKit#604]
**Issue:**

We implemented a small email client to retrieve emails from a gmail account for an end to end test spec using .net core 2. 

When running the tests through the test explorer on Visual Studio the test works correctly and emails are retrieved from the gmail account.

The issue only happens when running the tests outside of visual studio through CLI. The below exception is thrown when opening the email inbox folder. We installed the MimeKit dependency as a direct dependency of our project which still did not resolve the issue. 

**Exception:**
Step 5: System.TypeInitializationException : The type initializer for 'MimeKit.ParserOptions' threw an exception.
                                        ---> System.TypeInitializationException : The type initializer for 'MimeKit.Utils.CharsetUtils' threw an exception.
                                                ---> System.IO.FileNotFoundException : Could not load file or assembly 'System.Text.Encoding.CodePages, Version=4.0.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
                                                        ---> System.IO.FileNotFoundException : Could not load file or assembly 'System.Text.Encoding.CodePages, Version=4.0.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
                                at MailKit.Net.Imap.ImapEngine.ParseMessage(Stream stream, Boolean persistent, CancellationToken cancellationToken)
                                at MailKit.Net.Imap.ImapFolder.ParseMessage(Stream stream, CancellationToken cancellationToken)
                                at MailKit.Net.Imap.ImapFolder.GetMessage(UniqueId uid, CancellationToken cancellationToken, ITransferProgress progress)
                                at Odin.E2E.Utils.Email.EmailClient.GetRegistrationVerificationToken(String subjectEmail, String testEmail) in C:\Git\odin.e2e.utils\src\Odin.E2E.Utils\Email\EmailClient.cs:line 49

**Log File:**
[imap.log](https://github.com/jstedfast/MailKit/files/1574872/imap.log)

**Comment by claylaut** [comment]
Adding an extra point with @nismolo:
One thing that I've noticed it is failing to load `System.Text.Encoding.CodePages` Version=4.0.2.0. But when I've checked the nuget repo the version 4.0.2.0 doesn't exist.
https://www.nuget.org/packages/System.Text.Encoding.CodePages/

**Comment by jstedfast** [comment]
Just because you don't see a nuget version on nuget.org doesn't mean it doesn't exist, it just means the publisher hid it  from view (probably because new versions were released).

That said, this isn't a problem with MailKit, it's a problem with your development environment.

I run test programs from the console all the time and don't have this problem.

MailKit also does not depend on System.Text.Encoding.CodePages, Version=4.0.2.0, it depends on 4.3.0 which *is* listed on nuget.org.

**Comment by jstedfast** [comment]
Just went through my releases of MailKit and MailKit has depended on System.Text.Encoding.CodePages 4.3.0 since MailKit 1.14.0, MailKit is now on version 1.22.0. Maybe you just need to update?

**Comment by nismolo** [comment]
We did further investigation and it seems its happening only when directly using the `dotnet xunit` command to run tests. It works just fine when using `dotnet test` command.

**Comment by nismolo** [comment]
And yes forgot to mention we are using the latest version 1.22.

**Comment by nismolo** [comment]
Please note that we have opened an issue with xunit directly.

https://github.com/xunit/xunit/issues/1595
