### ISSUE TITLE
Index & uniqueid of email changes with moving away and back to inbox => impact on pager

### ISSUE THREAD

**Issue by gyself** [jstedfast/MailKit#605]
Hi,

I am trying to show inbox content based on index by passing 2 variables to below line of code.
_Variable 1: sRange = how many emails to display on the page.
Variable 2: sPage = the page number of the inbox._

`var summaries = client.Inbox.Fetch(Math.Max(0, client.Inbox.Count - (int.Parse(sRange) * int.Parse(sPage))), client.Inbox.Count - ((int.Parse(sRange) * int.Parse(sPage)) - (int.Parse(sRange) - 1)), MessageSummaryItems.Envelope | MessageSummaryItems.UniqueId | MessageSummaryItems.Flags | MessageSummaryItems.BodyStructure);`

If the inbox has 5 messages and sRange = 2 and sPage = 1 (=show 2 messages on page 1) then outcome of above line of code would be:

`var summaries = client.Inbox.Fetch(Math.Max(0, 5 - (2 * 1)), 5 - ((2 * 1) - (2 - 1)), MessageSummaryItems.Envelope | MessageSummaryItems.UniqueId | MessageSummaryItems.Flags | MessageSummaryItems.BodyStructure);`

or 

`var summaries = client.Inbox.Fetch(3, 4, MessageSummaryItems.Envelope | MessageSummaryItems.UniqueId | MessageSummaryItems.Flags | MessageSummaryItems.BodyStructure);`

This fetches the last 2 messages in the inbox or the messages with index 3 & 4.

This is the complete inbox:
![image](https://user-images.githubusercontent.com/20824258/34223711-aa3862f8-e5c0-11e7-9e61-80a74a0bfa62.png)
(The numbers on the right side are the uniqueid and the index of the message.)

The outcome of the line of code at the start of this post is:
![image](https://user-images.githubusercontent.com/20824258/34223818-f80f6666-e5c0-11e7-9677-aa0af40201ad.png)

Now... if I move Email 2 and Email 4 to a subfolder via the webclient of the email provider, complete inbox looks as follows:
![image](https://user-images.githubusercontent.com/20824258/34223884-32949efa-e5c1-11e7-8c75-2644658b24a5.png)
_(uniqueids remains the same, indexes have changed)_

If I now move back Email 2 and Email 4 from the subfolder to the inbox (via the webclient of the emailprovider) the complete inbox looks as follows:
![image](https://user-images.githubusercontent.com/20824258/34223962-7617d584-e5c1-11e7-9581-a1be065d0382.png)

If I reapply the line of code at the start of this post is, outcome is as follows:
![image](https://user-images.githubusercontent.com/20824258/34224016-a918d1b8-e5c1-11e7-8e07-8f7e2074f12d.png)

The result doesn't show email 5 & email 4 anymore but Email 4 & Email 2 because the indexes have changed.  The moved messages get the latest index. Also the uniqueid changed.

Do you know a workaround to still show the 2 most recent messages with the metodology I use, even after moving message away and back to inbox?

Thanks a lot
Frederik

**Comment by jstedfast** [comment]
You've lost me with your description, but my suggestion is: don't use indexes.

Use only UniqueId's.

Indexes are for developers who only want to download all messages as if IMAP were just a POP3 server. If you want to do anything more complex, use UniqueIds. That's why I put so much effort into making the API's for UniqueIds so nice to use.

**Comment by gyself** [comment]
Ok,
And how can I fetch for example email 11 to 20 of the inbox by use of UniqueId's?

Thx
Frederik

**Comment by jstedfast** [comment]
UniqueId's don't change. If they change every time you open your folder, then your server is broken.

```csharp
// get all uids sorted in ascending order of arrival date
var all = folder.Search (SearchQuery.All);
var uids = new UniqueIdSet ();

// get the uids visible on the page we are trying to display
int min = Math.Max (all.Count - ((sRange * (sPage + 1)) + 1), 0);
for (int i = 0; i < sRange; i++)
    uids.Add (all[min + i]);

var summaries = folder.Fetch (uids, MessageSummaryItems.Envelope | MessageSummaryItems.UniqueId | MessageSummaryItems.Flags | MessageSummaryItems.BodyStructure);

// now just walk over the summaries in reverse order... tada! how simple is that? :)
```

My math may be a little off because I'm doing this while doing other things, but it should give you the right idea.

**Comment by gyself** [comment]
Sorry but I am not convinced.
I don't think my office365 inbox is broken.
When I move a the emails with title 'Email2' and 'Email4) to a subfolder and back to inbox, both emails gets a new UniqueId
100% of that.

![image](https://user-images.githubusercontent.com/20824258/34274678-eba08890-e699-11e7-9445-874d80fae4fc.png)


Rgds
Frederik

**Comment by jstedfast** [comment]
Well, yes, they will get a new UID because they were moved out and lost their original UIDs when that happened.

**Comment by gyself** [comment]
Yep
Any idea how I can get the inbox back, sorted on date?

**Comment by jstedfast** [comment]
Well, that all depends on what extensions the server supports. Does it support the SORT extension?

If so, use my code above, but switch out:

```csharp
var all = folder.Search (SearchQuery.All);
```

with:

```csharp
var all = folder.Sort (SearchQuery.All, new OrderBy[] { OrderBy.ReverseDate });
```

And now you can also just start indexing from the beginning of `all` rather than the end of `all`.

**Comment by jstedfast** [comment]
If the server doesn't support the SORT extension, then you will need to fetch the entire list of summaries and do sorting locally (you can use the [MessageSorter](http://www.mimekit.net/docs/html/T_MailKit_MessageSorter.htm) class).

This means that you'll want to do local caching most likely in order to reduce traffic each time you switch back to the folder so that you can concentrate on just getting the info that has changed rather than everything.

This is where you start looking to see if the server supports the QRESYNC extension, and, if so, take advantage of it by calling [EnableQuickResync](http://www.mimekit.net/docs/html/M_MailKit_Net_Imap_ImapClient_EnableQuickResync.htm) on the client right after connecting and then start using the [ImapFolder.Open](http://www.mimekit.net/docs/html/M_MailKit_Net_Imap_ImapFolder_Open_1.htm) method that takes a list of known uids, etc to help you resync faster.

**Comment by jstedfast** [comment]
Here's an illustration on how to resync a folder (w/o the use of the QRESYNC extension which simplifies this dramatically):

```csharp
class CachedMessageInfo
{
	public UniqueId UniqueId;
	public MessageFlags Flags;
	public HashSet<string> UserFlags;
	public Envelope Envelope;
	public BodyPart Body;
}

static void ResyncFolder (ImapFolder folder, List<CachedMessageInfo> cache, ref uint cachedUidValidity)
{
	IList<IMessageSummary> summaries;

	// Step 1: Open the folder.

	// Note: we only need read-only access to update our cache, but depending on
	// what you plan to do with the folder after resynchronizing, you may want
	// top open the folder in read-write mode instead.
	folder.Open (FolderAccess.ReadOnly);

	if (cache.Count > 0) {
		if (folder.UidValidity == cachedUidValidity) {
			// Step 2: Remove messages from our cache that no longer exist on the server.

			// get the full list of UIDs on the server...
			var all = folder.Search (SearchQuery.All);

			// remove any messages from our cache that no longer exist...
			for (int i = 0; i < cache.Count; i++) {
				if (!all.Contains (cache[i].UniqueId)) {
					cache.RemoveAt (i);
					i--;
				}
			}

			// Step 3: Sync any flag changes for our cached messages.

			// get a list of known uids... astute observers will note that an easy
			// optimization to make here would be to merge this loop with the above
			// loop.
			var known = new UniqueIdSet (SortOrder.Ascending);
			for (int i = 0; i < cache.Count; i++)
				known.Add (cache[i].UniqueId);

			// fetch the flags for our known messages...
			summaries = folder.Fetch (known, MessageSummaryItems.Flags);
			for (int i = 0; i < summaries.Count; i++) {
				// Note: the indexes should match up with our cache, but it wouldn't
				// hurt to add error checking to make sure. I'm not bothering to here
				// for simplicity reasons.
				cache[i].Flags = summaries[i].Flags.Value;
				cache[i].UserFlags = summaries[i].UserFlags;
			}
		} else {
			// The UIDVALIDITY of the folder has changed. This means that our entire
			// cache is obsolete. We need to clear our cache and start from scratch.
			cachedUidValidity = folder.UidValidity;
			cache.Clear ();
		}
	} else {
		// We have nothing cached, so just start from scratch.
		cachedUidValidity = folder.UidValidity;
	}

	// Step 4: Fetch the messages we don't already know about and add them to our cache.

	summaries = folder.Fetch (cache.Count, -1, MessageSummaryItems.UniqueId | MessageSummaryItems.Flags | MessageSummaryItems.Envelope | MessageSummaryItems.BodyStructure);
	for (int i = 0; i < summaries.Count; i++) {
		cache.Add (new CachedMessageInfo {
			UniqueId = summaries[i].UniqueId,
			Flags = summaries[i].Flags.Value,
			UserFlags = summaries[i].UserFlags,
			Envelope = summaries[i].Envelope,
			Body = summaries[i].Body
		});
	}

	// Tada! Now we are resynchronized with the server.
}
```

**Comment by gyself** [comment]
This works for me.
Thanks!

`                // get all uids sorted in ascending order of arrival date
                var all = client.Inbox.Sort(SearchQuery.All, new OrderBy[] { OrderBy.Date });
                var uids = new UniqueIdSet();

                // get the uids visible on the page we are trying to display

                int index_from = Math.Max(0, all.Count - (int.Parse(sRange) * int.Parse(sPage)));
                int index_to = all.Count - ((int.Parse(sRange) * int.Parse(sPage)) - (int.Parse(sRange) - 1));

                for (int i = index_from; i < index_to + 1; i++)
                {
                    uids.Add(all[i]);
                }

                var summaries = client.Inbox.Fetch(uids, MessageSummaryItems.Envelope | MessageSummaryItems.UniqueId | MessageSummaryItems.Flags | MessageSummaryItems.BodyStructure);
                `

**Comment by jstedfast** [comment]
Instead of sorting by Date and then walking the list of uids backwards, try sorting on ReverseDate and walking forwards. It'll be a bit easier :)

**Comment by jstedfast** [comment]
FWIW, the proper markup to use to do C# code is backtick-backtick-backtick-csharp. I'll edit your post to fix it and then you can click edit yourself to see what I did.

**Comment by stewartwhaley** [comment]
How do you get messages by UniqID when using POP3 and GMail. The call, "client.GetMessage(msgIndex)" seems to want an index. I want to be able to pass the uniqID of a message. What I get back from GMail [the uniqID of the message] is something like, "GmailId10c7b74dbd834255". The .GetMessage only excepts either a int or uint32. Can I pass the uniqID I'm getting ?

**Comment by jstedfast** [comment]
Where are you getting the UID from?

Here's how to do what you want:

```csharp
var uids = client.GetMessageUids ();
int index = -1;

for (int i = 0; i < uids.Count; i++) {
    if (uids[i] == uniqID) {
        index = i;
        break;
    }
}

if (index != -1)
    message = client.GetMessage (index);
```
