### ISSUE TITLE
Could not delete Message from Exchange

### ISSUE THREAD

**Issue by yadavmukul1986** [jstedfast/MailKit#607]
Hi ,

I am facing delete issue at client. Client is using Office 365. Below is the deletion login i have implemented -

imapFolder.AddFlags(u, MessageFlags.Deleted, false); -- u is unique message Id
imapFolder.Expunge();

**Error from Mailkit** - 

at *********.ImapClient_MailKit.MarkMessageForDeletion() in
 ..\ImapClient-MailKit.cs:line 176

The IMAP server replied to the 'EXPUNGE' command with a 'NO' response: EXPUNGE failed

**Mailkit Protocol Log :** Connected to imaps://outlook.office365.com:993/
S: * OK The Microsoft Exchange IMAP4 service is ready. [QgBNADEAUABSADAAMQBDAEEAMAAxADEAMgAuAEkATgBEAFAAUgBEADAAMQAuAFAAUgBPAEQALgBPAFUAVABMAE8ATwBLAC4AQwBPAE0A]
C: A00000000 CAPABILITY
S: * CAPABILITY IMAP4 IMAP4rev1 AUTH=PLAIN AUTH=XOAUTH2 SASL-IR UIDPLUS ID UNSELECT CHILDREN IDLE NAMESPACE LITERAL+
S: A00000000 OK CAPABILITY completed.
C: A00000001 AUTHENTICATE XOAUTH2 dXNlcj1PbmxpbmVAbWF4bGlmZWluc3VyYW5jZS5jb20BYXV0aD1CZWFyZXIgTGluZUAzMzIyAQE=
S: A00000001 NO AUTHENTICATE failed.
C: A00000002 AUTHENTICATE PLAIN AE9ubGluZUBtYXhsaWZlaW5zdXJhbmNlLmNvbQBMaW5lQDMzMjI=
S: A00000002 OK AUTHENTICATE completed.
C: A00000003 CAPABILITY
S: * CAPABILITY IMAP4 IMAP4rev1 AUTH=PLAIN AUTH=XOAUTH2 SASL-IR UIDPLUS MOVE ID UNSELECT CLIENTACCESSRULES CLIENTNETWORKPRESENCELOCATION BACKENDAUTHENTICATE CHILDREN IDLE NAMESPACE LITERAL+
S: A00000003 OK CAPABILITY completed.
C: A00000004 NAMESPACE
S: * NAMESPACE (("" "/")) NIL NIL
S: A00000004 OK NAMESPACE completed.
C: A00000005 LIST "" "INBOX"
S: * LIST (\Marked \HasChildren) "/" INBOX
S: A00000005 OK LIST completed.
C: A00000006 SELECT INBOX
S: * 41 EXISTS
S: * 41 RECENT
S: * FLAGS (\Seen \Answered \Flagged \Deleted \Draft $MDNSent)
S: * OK [PERMANENTFLAGS (\Seen \Answered \Flagged \Deleted \Draft $MDNSent)] Permanent flags
S: * OK [UNSEEN 1] Is the first unseen message
S: * OK [UIDVALIDITY 14] UIDVALIDITY value
S: * OK [UIDNEXT 257307] The next unique identifier value
S: A00000006 OK [READ-WRITE] SELECT completed.
C: A00000007 FETCH 1:* UID

A00000017 OK FETCH completed.
C: A00000018 UID STORE 257271 +FLAGS (\Deleted)
S: * 43 RECENT
S: * 43 EXISTS
S: * 6 FETCH (FLAGS (\Deleted \Recent))
S: A00000018 OK STORE completed.
C: A00000019 UID STORE 257267 +FLAGS (\Deleted)
S: * 2 FETCH (FLAGS (\Deleted \Recent))
S: A00000019 OK STORE completed.
C: A00000020 UID STORE 257269 +FLAGS (\Deleted)
S: * 4 FETCH (FLAGS (\Deleted \Recent))
S: A00000020 OK STORE completed.
C: A00000021 UID STORE 257274 +FLAGS (\Deleted)
S: * 9 FETCH (FLAGS (\Deleted \Recent))
S: A00000021 OK STORE completed.
C: A00000022 UID STORE 257270 +FLAGS (\Deleted)
S: * 5 FETCH (FLAGS (\Deleted \Recent))
S: A00000022 OK STORE completed.
C: A00000023 UID STORE 257268 +FLAGS (\Deleted)
S: * 3 FETCH (FLAGS (\Deleted \Recent))
S: A00000023 OK STORE completed.
C: A00000024 UID STORE 257273 +FLAGS (\Deleted)
S: * 8 FETCH (FLAGS (\Deleted \Recent))
S: A00000024 OK STORE completed.
C: A00000025 UID STORE 257275 +FLAGS (\Deleted)
S: * 10 FETCH (FLAGS (\Deleted \Recent))
S: A00000025 OK STORE completed.
C: A00000026 UID STORE 257272 +FLAGS (\Deleted)
S: * 7 FETCH (FLAGS (\Deleted \Recent))
S: A00000026 OK STORE completed.
C: A00000027 UID STORE 257266 +FLAGS (\Deleted)
S: * 1 FETCH (FLAGS (\Deleted \Recent))
S: A00000027 OK STORE completed.
C: A00000028 EXPUNGE
S: * 33 EXISTS
S: A00000028 NO EXPUNGE failed. 

It may be an issue with some rule on particular mail box. Need your confirmation for the same.

**Comment by jstedfast** [comment]
How would I have any idea? The server doesn't say why it says NO, it just says NO.

Did you re-open the folder on ReadOnly mode? If not, then I have no idea.
