### ISSUE TITLE
Auth issue

### ISSUE THREAD

**Issue by santibevi** [jstedfast/MailKit#608]
Hello, I am trying to use the imagClient but I receive "LOGIN Failed - Invalid username or password." but the user and password I write are correct.
I used por 143 and ssl = false. Also the username is my email address complete.

using (var client = new ImapClient())
                {
                    client.Connect(email.POPServer, Convert.ToInt32(email.IncomingPort), (bool)email.IsPOPssl);               
                    client.Authenticate(email.POPUsername, email.POPpassword);
                    int i = 1;
                    // get the unread messages
                    var uids = client.Inbox.Search(SearchQuery.NotSeen);
                    foreach (var uid in uids)
                    {
                        var message = client.Inbox.GetMessage(uid);
                        MailMessege obj = new MailMessege();
                        try
                        {

                            obj.UID = message.MessageId;
                            obj.subject = message.Subject;
                            obj.sender = message.From.Mailboxes.FirstOrDefault().Address;
                            obj.sendDate = message.Date.DateTime;
                            if (message.Attachments != null)
                                obj.Attachments = message.Attachments;

                            model.Inbox.Add(obj);
                            success++;
                        }
                        catch (Exception e)
                        {
                            fail++;
                        }
                        i++;
                    }

**Comment by jstedfast** [comment]
If your user name or password is wrong, how much of a donation will you contribute to the project? ;-)

Please follow the instructions that you deleted when you submitted this issue (which can also be found in the [FAQ](https://github.com/jstedfast/MailKit/blob/master/FAQ.md#ProtocolLog)) for how to get a protocol log.

Thanks.
