### ISSUE TITLE
Problem when we have user login different than user mail (for get mails). Ex: shared mailbox 

### ISSUE THREAD

**Issue by jnurit** [jstedfast/MailKit#611]
Hi

i have an issue (or a feature request) for the use of this plugin. 

the use case :  
- I have an user whith login x@mydomain.com and a mail adress y@mydomain.com
- i tried to log in with connect + authenticate
- doesn't work. 
       - i tried with multiple url (outlook.office365.com/imap/ssl/novalidate-cert/authuser=y@mydomain.com&user=x@mydomain.com)
       - i tried with different authenticate method (login with x@mydomain.com\y@mydomain.com or with x@mydomain.com\y)

I have no imap.log because i catch error and i have a timeout only.

I don't know if is an issue, a mistake in configuration or a new feature to make...

Ps: i have an exemple in PHP, it's work:

--------------------------------------------------------------------------------------------------------

/* connect */
$hostname = '{outlook.office365.com:993/imap/ssl/novalidate-cert/authuser=x@mydomain.com/user=y@mydomain.com}INBOX';
$username = 'x@mydomain.com';
$password = 'XXXXXXXXXXXX';

/* try to connect */
$inbox = imap_open($hostname,$username,$password) or die('Cannot connect to Gmail: ' . imap_last_error());

--------------------------------------------------------------------------------------------------------

Thanks in advance for yours answers.

Best regards.

**Comment by jstedfast** [comment]
Just use "x@mydomain.com" as the username when authenticating.

**Comment by jnurit** [comment]
Sorry but it doesn't work :(. with shared mailbox, i have the mails of X, but i need to get mails of Y... Z... on the same account (X@domain.com). With the sample of php, it works, but i have no solution with mailkit..

**Comment by jstedfast** [comment]
Find out what the php code is sending to the server using a tool like wire shark or something, then I’ll be able to help you.

**Comment by jnurit** [comment]
If it's help:

[wireshark capture.zip](https://github.com/jstedfast/MailKit/files/1589027/wireshark.capture.zip)

**Comment by jstedfast** [comment]
You'll need to setup your Wireshark to decrypt the SSL either that or disable SSL. There's no way that I can decrypt it on my end.

**Comment by Ceus** [comment]
I know this is a closed issue but I figured I would chime in as I am currently using a Shared Mailbox and have this working with Office 365. You are also comparing C# to PHP.

Here is my code which is confirmed to work.

```csharp
await client.ConnectAsync("outlook.office365.com", 993, SecureSocketOptions.SslOnConnect);
client.AuthenticationMechanisms.Remove("XOAUTH2");
await client.AuthenticateAsync(@"username@yourdomain.com\sharedmailbox", "userpassword");
```

**Comment by jstedfast** [comment]
@Ceus awesome, thanks for sharing! Hopefully that helps @jnurit
