### ISSUE TITLE
when cloud be support rfc 2445 

### ISSUE THREAD

**Issue by sgf** [jstedfast/MailKit#612]
To help me debug your issue, please explain:
- What were you trying to do?
- What happened?
- What did you expect to happen?
- Step-by-step reproduction instructions and/or a simple test case.

this project is very great project.
but it seems do not support rfc 2445。

was there any plan to support that ?
also there's another is  rfc 2426.

**Comment by jstedfast** [comment]
There's no plans to support iCal or vCard. Someone else can do those :)

**Comment by sgf** [comment]
@jstedfast can u tell what else can do those 
🙂

**Comment by sgf** [comment]
got the way by
Conversion of MailMessage to MimeMessage
