### ISSUE TITLE
Signal 6 error in mono android in mailkit mimekit version 2.0 

### ISSUE THREAD

**Issue by ashutoshgarg0007** [jstedfast/MailKit#614]
Whenever i update the nuget from 1.22 to 2.0 and build my mono android project it gives me fatal 6 signal error. And then i have to revert it to 1.22 .

**Comment by jstedfast** [comment]
Can you get me a simple test case?

**Comment by ashutoshgarg0007** [comment]
Do you have xamarin android setup ?

**Comment by jstedfast** [comment]
Yes, but I don't seem to be able to successfully deploy *any* Xamarin.Android app to an emulator. It just sits there with a black screen forever.

I probably didn't create the emulator correctly, so that's probably the problem.

That said, a SIGABORT (signal 6) suggests a runtime bug so you'll probably have better luck reporting the problem to Xamarin.

**Comment by jstedfast** [comment]
The crash you are experiencing may be related to this: https://bugzilla.xamarin.com/show_bug.cgi?id=60625

It should be fixed in Xamarin.Mac and Xamarin.iOS in the next release. Not sure about Android. Will try to report back as soon as I find out.

**Comment by jstedfast** [comment]
Ok, it will be in the next release of Xamarin.Android as well.

Feel free to test out the snapshot build here:

https://jenkins.mono-project.com/view/Xamarin.Android/job/xamarin-android-builds-d15-5/

**Comment by jstedfast** [comment]
This is of course assuming that the bug is the same bug as that :)

**Comment by ashutoshgarg0007** [comment]
Ok. Let's  wait  and see what happens because it has not been fixed till now. But it works pretty fine with mailkit mimekit version 1.22. May be you have updated something in the code that mono doesn't like.

**Comment by jstedfast** [comment]
No, the problem is likely that your app is now referencing .netstandard2.0 or 1.6 when it was referencing some other framework version before. (netstandard1.6 and netstandard2.0 are newly supported in MimeKit/MailKit 2.0).

**Comment by jstedfast** [comment]
MimeKit code itself changed very little between 1.22 and 2.0 (the only code that changed was S/MIME stuff). The code for CharsetUtils didn't change one iota and that is where the crash is.
