### ISSUE TITLE
i am using version 2.0.0 of mail kit so i am facing app crashed Issue 

### ISSUE THREAD

**Issue by sour7230** [jstedfast/MailKit#615]
Dear Jstedfast,
i am using version 2.0.0 of mail kit

when i go on this code app crashed  Automatically 
 **foreach (var summary in inbox.Fetch(0, -1, MessageSummaryItems.full))
                {**

                  }

this is only work with uids

**Comment by jstedfast** [comment]
It works fine in the unit tests. Can you get me a test case to illustrate the problem?

**Comment by sour7230** [comment]
i send you my working project than you will test this and  an illustrate
the problem​
 App17.rar
<https://drive.google.com/file/d/1zbz9fKPaiE5kRMcUfqjXbQGymTfget6b/view?usp=drive_web>
​


* Thank and regards*

*Sourabh Saini*
Software Engineer
Expert Tech Source Pvt Ltd.
333-334 A Tower,
Spaze IT Tech Park
Sector-49, Gurgaon (Harayna).

Mob. 07042507252

**Comment by jstedfast** [comment]
I can't open rar files. Please use zip instead. Thanks!

**Comment by sour7230** [comment]
i tested your older version it's working fine.there is no problem​
 App17.zip
<https://drive.google.com/file/d/1eP3Dm9uuexlo-SeL4KovjooriZ4R4lKO/view?usp=drive_web>
​


* Thank and regards*

*Sourabh Saini*
Software Engineer
Expert Tech Source Pvt Ltd.
333-334 A Tower,
Spaze IT Tech Park
Sector-49, Gurgaon (Harayna).

Mob. 07042507252

**Comment by jstedfast** [comment]
Why did you not include the sln file?

**Comment by sour7230** [comment]
Sry for that i miss out this file.
​
 App17 (2).zip
<https://drive.google.com/file/d/1at5zaUgfHbdcn1m4_AKINHTIvquvYHCN/view?usp=drive_web>
​


* Thank and regards*

*Sourabh Saini*
Software Engineer
Expert Tech Source Pvt Ltd.
333-334 A Tower,
Spaze IT Tech Park
Sector-49, Gurgaon (Harayna).

Mob. 07042507252

**Comment by jstedfast** [comment]
I'll need you to verify your phone on gmail so I can test your app.

**Comment by jstedfast** [comment]
type `74` on your phone

**Comment by sour7230** [comment]
process again.




* Thank and regards*

*Sourabh Saini*
Software Engineer
Expert Tech Source Pvt Ltd.
333-334 A Tower,
Spaze IT Tech Park
Sector-49, Gurgaon (Harayna).

Mob. 07042507252

**Comment by jstedfast** [comment]
ok, so the app is logging in now. How do I reproduce this error?

**Comment by sour7230** [comment]
you debug this app line by line.


* Thank and regards*

*Sourabh Saini*
Software Engineer
Expert Tech Source Pvt Ltd.
333-334 A Tower,
Spaze IT Tech Park
Sector-49, Gurgaon (Harayna).

Mob. 07042507252

**Comment by jstedfast** [comment]
No, I mean, I'm not getting a crash. It works fine for me.

**Comment by sour7230** [comment]
nopes,i am getting app crash on same code.


* Thank and regards*

*Sourabh Saini*
Software Engineer
Expert Tech Source Pvt Ltd.
333-334 A Tower,
Spaze IT Tech Park
Sector-49, Gurgaon (Harayna).

Mob. 07042507252

**Comment by jstedfast** [comment]
You're running the exact same code you sent to me? No changes at all?

MainPage.xaml.cs has this query:

```csharp
foreach (var summary in inbox.Fetch(0,100, MessageSummaryItems.Full | MessageSummaryItems.UniqueId))
```

**Comment by sour7230** [comment]
no dear. same codes i was send you.
app crash on first loop.


* Thank and regards*

*Sourabh Saini*
Software Engineer
Expert Tech Source Pvt Ltd.
333-334 A Tower,
Spaze IT Tech Park
Sector-49, Gurgaon (Harayna).

Mob. 07042507252

**Comment by jstedfast** [comment]
Well, if it doesn't crash for me... then there's no bug in MailKit 2.0.0.

**Comment by sour7230** [comment]
okk.


* Thank and regards*

*Sourabh Saini*
Software Engineer
Expert Tech Source Pvt Ltd.
333-334 A Tower,
Spaze IT Tech Park
Sector-49, Gurgaon (Harayna).

Mob. 07042507252
