### ISSUE TITLE
Unable to connect to Gmail via IMAP after upgrading to 2.00

### ISSUE THREAD

**Issue by niemyjski** [jstedfast/MailKit#616]
We are running on asp.net core 2.0 and we upgraded from v1.22 to 2.00 with the following code and we can no longer connect to google. If we revert to 1.22 it works flawlessly.

```cs
using (var client = new ImapClient()) {
            var uri = new Uri("imaps://imap.gmail.com:993");
            await client.ConnectAsync(uri, cancellationToken).AnyContext();
            await client.AuthenticateAsync(identity, apiKey, cancellationToken).AnyContext(); // api key is an oauth access token... and identity is the email address
}
```

```
{MailKit.Security.AuthenticationException: Invalid credentials (Failure)
  at MailKit.Net.Imap.ImapClient.<AuthenticateAsync>d__76.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)}
```

**Comment by jstedfast** [comment]
If you want to use OAuth2.0 authentication, you need to use:

```csharp
var oauth2 = new SaslMechanismOAuth2 (uri, identity, apiKey);
await client.AuthenticateAsync(oauth2, cancellationToken).AnyContext();
```

The reason for this is because OAuth2.0 uses different credentials than every other auth scheme and I felt that it was annoying for people to have to always disable XOAUTH2 when they weren't using it.

Hope that helps.

**Comment by niemyjski** [comment]
@jstedfast could we update the readme / faq as it currently has the old code

**Comment by niemyjski** [comment]
There doesn't seem to be an overload that takes the SaslMech

```
var oauth2 = new SaslMechanismOAuth2(uri, new NetworkCredential(identity, apiKey));
await client.AuthenticateAsync(oauth2, cancellationToken).AnyContext();
```

**Comment by jstedfast** [comment]
Weird... http://www.mimekit.net/docs/html/M_MailKit_Net_Imap_ImapClient_AuthenticateAsync.htm

**Comment by jstedfast** [comment]
And yea, I'll update the README/FAQ/etc

**Comment by jstedfast** [comment]
FWIW, I've modified SaslMechanism .ctors to no longer require a Uri argument and have obsoleted the existing .ctors that take a Uri.

The Uri will now be set (if needed) by the *Client implementations.

I made this change because most people aren't using Uri-based Connect() methods.
