### ISSUE TITLE
Display Name in From header is garbled

### ISSUE THREAD

**Issue by aYasutakaOhtake** [jstedfast/MailKit#629]
Dear

DisplayName in From header garbled when receiving the following mail with my application using MailKit (1.18.1.1).

    From: "=?iso-2022-jp?B?GyRCIVpHdkhpJVclaiVDJVclaiFIJE8kaxsoQg==?=  =?iso-2022-jp?B?GyRCJF8hSTJyNlgbKEIhIRskQiFbJW0hPCU9JXMlVSVsJUMlNyVlJVclbCVfGyhC?=  =?iso-2022-jp?B?GyRCJSIlYCVLJWUhPCU5GyhC?=" <test_mag@mail.test.jp>
    To: test@test.test
    Subject: test
    Content-Type: text/plain; charset=iso-2022-jp
    Content-Transfer-Encoding: quoted-printable
    
    test

Display Name in `Envelope.From.First().Name`.

    【薄皮プリップリ“はる  =?iso-2022-jp?B?GyRCJF8hSTJyNlgbKEIhIRskQiFbJW0hPCU9JXMlVSVsJUMlNyV

I guess that ReadQuotedStringTokenAsync in ImapStream.cs may not read the QuotedString of DisplayName only by 128 bytes (inputEnd variable).

Thanks in advance for yours answers.

Best regards,

**Comment by jstedfast** [comment]
No, if you look at the protocol log (see the FAQ.md file for how to get this), I'm betting you'll find that the Display Name above is exactly what the IMAP server provides - which is broken.

This is not a MailKit bug.
