### ISSUE TITLE
how to consume system.net settings in the web.config?

### ISSUE THREAD

**Issue by robertpmansion** [jstedfast/MailKit#630]
Hi there,

I'm using ASP.NET 4.5 MVC and would like to use the MailKit, however, how do you use the system.net in my web.config to MailKit? 

```
<system.net>
        <mailSettings>
            <smtp deliveryMethod="Network" from="system@company.com">
                <network host="localhost" />
            </smtp>
        </mailSettings>
    </system.net>
```

I would just like to use the web.config and would not like to add any literal strings configuration to my codes so that to make things simple and organised.

**Comment by jstedfast** [comment]
You'll have to write your own custom code to parse web.config to get the values.

MailKit doesn't parse web.config and never will.
