### ISSUE TITLE
Is there a way I can covert a Microsoft.Exchange.WebServices.Data.EmailMessage to MineMessage

### ISSUE THREAD

**Issue by truane** [jstedfast/MailKit#632]
I'm using multiple services and want to use MailKit to send email but I also want to include an existing email received by EWS in the format Microsoft.Exchange.WebServices.Data.EmailMessage.

Is there a way I can covert a Microsoft.Exchange.WebServices.Data.EmailMessage into MineMessage so that I can attach it.

var messagepart = new MessagePart {Message = orignalMessage};
multipart.Add(messagepart);

I can also use Microsoft.Exchange.WebServices.Data.EmailMessage.MimeContent.Content to get the mime message as Btye[] if there is a way to convert that to a MineMessage.

Regards,

**Comment by jstedfast** [comment]
If you can get the full message as a byte[], then yes:

```csharp
var messageData = exchangeEmailMessage.MimeContent.Content;
MimeMessage message;

using (var stream = new MemoryStream (messageData, false))
    message = MimeMessage.Load (stream);
```
