### ISSUE TITLE
Aws Lambda support for mail kit using netstandard 1.6.0

### ISSUE THREAD

**Issue by ashutoshgarg0007** [jstedfast/MailKit#634]
Hi jstedfast,
I want to know how can i use the mailkit/mimekit library with aws lambda .net core project using .net standard 1.6.0 because it's the only supported version by aws lambda. In my other projects your old versions of library was supported but when i try to update or use it in a new project it fails because it needs .net standard >= 1.6.1. Any help would be appreciated.

Thanks.

**Comment by jstedfast** [comment]
You could build from source and tweak the dependencies.

FWIW, it doesn't depend on .NET Standard >= 1.6.1, it depends on .NETStandard.Library >= 1.6.1 because that is the latest stable bugfix release of the core framework library.

**Comment by ashutoshgarg0007** [comment]
Yes I understand. But the limitation is on the aws lambda that support .Net
core 1.1 with max 1.6.0 .Net standard library. For the time being I have
used mailkit version 1.
