### ISSUE TITLE
ModSeq or HighestModSeq value not return

### ISSUE THREAD

**Issue by ChrisRyuGS** [jstedfast/MailKit#638]
I'm trying to read recent messages by cache with ModSeq or HighestModSeq
but the ModSeq of the item or HighestModSeq value is not returned.

inbox.Open(FolderAccess.ReadOnly, stoppingToken);
messages = inbox.Fetch(0, -1,
         MessageSummaryItems.ModSeq | MessageSummaryItems.UniqueId).ToList();
        var highestModSeq = inbox.HighestModSeq;

S: * OK The Microsoft Exchange IMAP4 service is ready.
C: A00000000 CAPABILITY
S: * CAPABILITY IMAP4 IMAP4rev1 AUTH=PLAIN AUTH=NTLM AUTH=GSSAPI UIDPLUS MOVE ID CHILDREN IDLE NAMESPACE LITERAL+
S: A00000000 OK CAPABILITY completed.
C: A00000001 AUTHENTICATE PLAIN
S: +
C: AG5tcwB3anNza2FlbzEh
S: A00000001 OK AUTHENTICATE completed.
C: A00000002 CAPABILITY
S: * CAPABILITY IMAP4 IMAP4rev1 AUTH=PLAIN AUTH=NTLM AUTH=GSSAPI UIDPLUS MOVE ID XPROXY3 CHILDREN IDLE NAMESPACE LITERAL+
S: A00000002 OK CAPABILITY completed.
C: A00000003 NAMESPACE
S: * NAMESPACE (("" "/")) NIL NIL
S: A00000003 OK NAMESPACE completed.
C: A00000004 LIST "" "INBOX"
S: * LIST (\Marked \HasNoChildren) "/" INBOX
S: A00000004 OK LIST completed.
C: A00000005 EXAMINE INBOX
S: * 42 EXISTS
S: * 42 RECENT
S: * FLAGS (\Seen \Answered \Flagged \Deleted \Draft $MDNSent)
S: * OK [PERMANENTFLAGS ()] Permanent flags
S: * OK [UNSEEN 7] Is the first unseen message
S: * OK [UIDVALIDITY 14] UIDVALIDITY value
S: * OK [UIDNEXT 51] The next unique identifier value
S: A00000005 OK [READ-ONLY] EXAMINE completed.
C: A00000006 FETCH 1:* UID
S: * 1 FETCH (UID 2)
S: * 2 FETCH (UID 3)
S: * 3 FETCH (UID 4)
S: * 4 FETCH (UID 5)
S: * 5 FETCH (UID 13)
S: * 6 FETCH (UID 14)
S: * 7 FETCH (UID 15)
S: * 8 FETCH (UID 16)
S: * 9 FETCH (UID 17)
S: * 10 FETCH (UID 18)
S: * 11 FETCH (UID 19)
S: * 12 FETCH (UID 20)
S: * 13 FETCH (UID 21)
S: * 14 FETCH (UID 22)
S: * 15 FETCH (UID 23)
S: * 16 FETCH (UID 24)
S: * 17 FETCH (UID 25)
S: * 18 FETCH (UID 26)
S: * 19 FETCH (UID 27)
S: * 20 FETCH (UID 28)
S: * 21 FETCH (UID 29)
S: * 22 FETCH (UID 30)
S: * 23 FETCH (UID 31)
S: * 24 FETCH (UID 32)
S: * 25 FETCH (UID 33)
S: * 26 FETCH (UID 34)
S: * 27 FETCH (UID 35)
S: * 28 FETCH (UID 36)
S: * 29 FETCH (UID 37)
S: * 30 FETCH (UID 38)
S: * 31 FETCH (UID 39)
S: * 32 FETCH (UID 40)
S: * 33 FETCH (UID 41)
S: * 34 FETCH (UID 42)
S: * 35 FETCH (UID 43)
S: * 36 FETCH (UID 44)
S: * 37 FETCH (UID 45)
S: * 38 FETCH (UID 46)
S: * 39 FETCH (UID 47)
S: * 40 FETCH (UID 48)
S: * 41 FETCH (UID 49)
S: * 42 FETCH (UID 50)
S: A00000006 OK FETCH completed.

**Comment by jstedfast** [comment]
Not all IMAP servers support MODSEQ and HIGHESTMODSEQ. Only IMAP servers that support the CONDSTORE extension support it (and it appears yours does not by the CAPABILITY response).
