### ISSUE TITLE
Request for POP3 'Fetch' before downloading

### ISSUE THREAD

**Issue by jernelson7** [jstedfast/MailKit#641]
I'm creating an email app that needs to support both IMAP and POP3 protocols. I have a local cache of messages that have already been downloaded. I didn't have much trouble implementing the message synchronization on the IMAP side (thanks for that!). 

For POP3, checking for messages I've already downloaded is a bit tricky. As I understand it, not all POP3 servers support message UIDs. In that case, I want to fall back to comparing metadata of the message (e.g. Date/Sender/Subject) to check if it has already been downloaded. It seems the only way to get this information is to download the whole message. It would be convenient if you could add something similar to IMailFolder.Fetch to Pop3Client so that I can get the metadata before downloading the whole message. 

You're the expert, so I'll trust your judgement if that is a reasonable request or not worth the effort. Thank you!

**Comment by jstedfast** [comment]
IMAP is a far more flexible protocol than POP3. The IMAP and POP3 API's mimic the protocol commands that are available.

That said, POP3 does have a HEAD command which gets just the message headers and the Pop3Client has a GetHeaders() method to take advantage of this.

That's what I would recommend using.

Hope that helps!

**Comment by jernelson7** [comment]
Thanks! I think that will work. I was worried about having to parse the headers but I see you have some support for that (e.g. InternetAddressList.TryParse).
