### ISSUE TITLE
Not possible to load NuGet package MailKit

### ISSUE THREAD

**Issue by EmJay71** [jstedfast/MailKit#643]
Hello,

I tried to load the NuGet package MailKit Version 2.0.1 and I get the following error:

The "MailKit 2.0.1" package could not be installed. You are trying to install this package into a project that refers to ". NETPortable, Version=v4.5, Profile=Profile259", but the package does not contain assembly references or content files that are compatible with this framework. For more information, please contact the package manufacturer.

Es wird versucht, Abhängigkeitsinformationen für das Paket "MailKit.2.0.1" bezüglich des Projekts "SePem300TestApp.Android" mit dem Ziel "MonoAndroid,Version=v7.0" zu erfassen.
Das Erfassen von Abhängigkeitsinformationen hat 5,7 sec gedauert.
Es wird versucht, Abhängigkeiten für das Paket "MailKit.2.0.1" mit dem DependencyBehavior "Lowest" aufzulösen.
Das Auflösen von Abhängigkeitsinformationen hat 0 ms gedauert.
Aktionen zum Installieren des Pakets "MailKit.2.0.1" werden aufgelöst.
Aktionen zum Installieren des Pakets "MailKit.2.0.1" wurden aufgelöst.
Das Paket "MailKit 2.0.1" wird aus "nuget.org" abgerufen.
Installationsfehler. Ein Rollback wird ausgeführt...
Das Paket "MailKit.2.0.1" ist im Projekt "SePem300TestApp" nicht vorhanden.
Das Paket "MailKit.2.0.1" ist im Ordner "D:\Entwicklung\TestApp\packages" nicht vorhanden.
Das Ausführen von NuGet-Aktionen hat 505,81 ms gedauert.
Das Paket "MailKit 2.0.1" konnte nicht installiert werden. Sie versuchen, dieses Paket in ein Projekt zu installieren, das sich auf ".NETPortable,Version=v4.5,Profile=Profile259" bezieht, das Paket enthält aber keine Assemblyverweise oder Inhaltsdateien, die mit diesem Framework kompatibel sind. Wenden Sie sich an den Paketersteller, um weitere Informationen zu erhalten.
Verstrichene Zeit: 00:00:07.0376147
========== Abgeschlossen ==========

What can I do load it correctly?

Thank you very much,

Emjay71

**Comment by jstedfast** [comment]
MailKit doesn't support PCL Profile 259.

Portable Class Libraries have been deprecated in favor of NET Standard by Microsoft, so I would recommend making the switch away from PCL as you'll find more and more nugets dropping support for PCL as time goes on.

**Comment by EmJay71** [comment]
Thank you very much for your answer ;-)
