### ISSUE TITLE
MailKit v2.0.1 crashes on Android (Xamarin)

### ISSUE THREAD

**Issue by dpankow2** [jstedfast/MailKit#645]
I have two same applications: for Windows and for Android.

Application for Windows uses latest version MailKit and everything is working perfectly here.  

Application for Android uses MailKit 1.22 - IMAP and POP works properly but for some e-mail services SMTP not works. For example mail.ru - client.Authenticate always throws exception: "435: Unable to authenticate at present" (the same account checked on Windows works properly).

I decided to update MailKit to latest version in application for Android. But now for IMAP and POP program crashes without and exception on creating client:
```csharp
using (var client = new ImapClient())
using (var client2 = new Pop3Client())
```
and for SMTP also crashes without any exception on creating message:
```csharp
var message = new MimeMessage();
```
Full device log for sending message by SMTP (using mail.ru account): http://wklej.org/id/3367253/ 

Thanks in advance for help with error on 1.22 version or crashing on 2.0.1 version.

**Comment by jstedfast** [comment]
Several people have already reported this and the crash is in the Mono runtime and not the fault of MailKit. You need to upgrade your Xamarin Android installation (I think there's already been a release, but if not, it will probably be out soon).

**Comment by jstedfast** [comment]
FWIW, there's more discussion on this bug here: https://github.com/jstedfast/MailKit/issues/617

Unfortunately, that link does not have a download for Xamarin.Android in particular, but it does suggest that updating your Xamarin.Android should resolve the issue, but you'll likely need to do a clean rebuild of your app.
