### ISSUE TITLE
Stream attachments

### ISSUE THREAD

**Issue by Niklas-Peter** [jstedfast/MailKit#646]
Are stream attachments really streamed to the SMTP server, i. e., without loading the complete stream into memory? This is important to know for me, because I send some emails concurrently (using multiple SmtpClients) each having attachments loaded from a database or the file system as a stream.

> builder.Attachments.Add("myLargeFile.pdf", File.OpenRead("myLargeFile.pdf"))

Thanks in advance!

**Comment by jstedfast** [comment]
Yes, they are streamed and the stream needs to be seekable because MailKit may need to measure the size of the message in some cases.
