### ISSUE TITLE
Custom IProtocolLogger implementation

### ISSUE THREAD

**Issue by ekalchev** [jstedfast/MailKit#648]
Is it possible to have custom implementation of IProtocolLogger which logs imap commands only, without actual mime part bodies, user, password and etc.

I would like user to be able to submit their logs for troubleshooting but mime body content makes those logs huge and it contains sensitive user info. Em Client logs are like this and I would like to come up with similar implementation using MailKit.

**Comment by jstedfast** [comment]
Yes, you can implement your own custom IProtocolLogger.

IProtocolLogger is just an interface.
