### ISSUE TITLE
SearchQuery.NotSeen returns more email count than expected

### ISSUE THREAD

**Issue by ananththecoder** [jstedfast/MailKit#651]
I am trying to fetch "Unread" Emails alone from gmail through WinForms using [SearchQuery.NotSeen](http://www.mimekit.net/docs/html/T_MailKit_Search_SearchQuery.htm). I'm expecting it to return only 15 mails but it fetches 523 messages.

I also tried New and Recent but each returns different values than 15 !!

```
using (var client = new ImapClient())
            {
                client.Connect("imap.gmail.com", 993, true);
                client.Authenticate("gmail_address", "app_specific_password");
                client.Inbox.Open(FolderAccess.ReadOnly);

                var uids = client.Inbox.Search(SearchQuery.NotSeen);
                foreach (var uid in uids)
                {
                    var message = client.Inbox.GetMessage(uid);
                    listMails.Items.Add(message.Subject);
                }
                MessageBox.Show(uids.Count.ToString());
                client.Disconnect(true);
            }
```

**Comment by jstedfast** [comment]
Why do you expect only 15?

**Comment by ananththecoder** [comment]
bro, thats because I have only 15 unread emails, and in order to reduce network congestion

**Comment by jstedfast** [comment]
Get me a [Protocol Log](https://github.com/jstedfast/MailKit/blob/master/FAQ.md#ProtocolLog) and we'll see what's up.

I guarantee that the server is returning whatever number MailKit is showing you, though :)

**Comment by ananththecoder** [comment]
@jstedfast First of all thank you and apologies for the delayed reply. After a deep manual search, I found out that Mailkit fetches up all unread messages including Social, Promotions etc. which summed up to 523. And to solve this I used **SearchQuery.DeliveredAfter(DateTime.Parse("yyyy-mm-dd")**, which yielded me comparatively lower number of email.

**Comment by jstedfast** [comment]
Ah, you are using GMail...

GMail doesn't use physical folders, it uses "virtual" folders, as in it's just a database query that matches what GMail refers to as a "label". The Inbox has an "Inbox" label and so on.

Add to that the fact that GMail's new UI splits the Inbox into multiple views (Social, Promotions, plain ol' Inbox, etc) which all fall under the "Inbox" label and so when you search the Inbox, the search will match messages in any of those views.

Not sure how, but I disabled that feature in my own personal GMail account so it's not as confusing.

It's a bit similar to Outlook's new(ish) "Focused Inbox" feature which I find confusing as hell.

**Comment by ananththecoder** [comment]
Well, that makes sense @jstedfast and thanks a lot. I wanted to have this clarification so that people who may face this issue in future might get a picture of how Mailkit views the inboxes.

> "Focused Inbox"
yes it is pretty useful to have a visually organized view for productivity but when it comes to development, it sure made me scratch my head for hours.
