### ISSUE TITLE
samples ImapClientDemo fail update folder

### ISSUE THREAD

**Issue by flamme-demon** [jstedfast/MailKit#653]
Hi,

I wanted to test your solution, to see the possibilities.
Unfortunately when I clicked on the list of files an error appeared.

Error Framework :

> Consultez la fin de ce message pour plus de détails sur l'appel du débogage
> juste-à-temps (JIT) à la place de cette boîte de dialogue.
> 
> ************** Texte de l'exception **************
> System.InvalidOperationException: The ImapClient is currently busy processing a command in another thread. Lock the SyncRoot property to properly synchronize your threads.
>    à MailKit.Net.Imap.ImapEngine.<IterateAsync>d__169.MoveNext()
> --- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
>    à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    à MailKit.Net.Imap.ImapEngine.<RunAsync>d__170.MoveNext()
> --- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
>    à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    à MailKit.Net.Imap.ImapFolder.<StatusAsync>d__54.MoveNext()
> --- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
>    à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    à System.Runtime.CompilerServices.TaskAwaiter.GetResult()
>    à ImapClientDemo.FolderTreeView.<UpdateUnreadCount>d__10.MoveNext() dans C:\Users\flamm\Downloads\Compressed\MailKit-master\samples\ImapClientDemo\ImapClientDemo\FolderTreeView.cs:ligne 145
> --- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
>    à System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
> 
> 
> ************** Assemblys chargés **************
> mscorlib
>     Version de l'assembly : 4.0.0.0
>     Version Win32 : 4.7.2633.0 built by: NET471REL1LAST_C
>     CodeBase : file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
> ----------------------------------------
> ImapClientDemo
>     Version de l'assembly : 1.0.0.0
>     Version Win32 : 1.0.0.0
>     CodeBase : file:///C:/Users/flamm/Downloads/Compressed/MailKit-master/samples/ImapClientDemo/ImapClientDemo/bin/Debug/ImapClientDemo.exe
> ----------------------------------------
> MailKit
>     Version de l'assembly : 2.0.0.0
>     Version Win32 : 2.0.1.0
>     CodeBase : file:///C:/Users/flamm/Downloads/Compressed/MailKit-master/samples/ImapClientDemo/ImapClientDemo/bin/Debug/MailKit.DLL
> ----------------------------------------
> System.Core
>     Version de l'assembly : 4.0.0.0
>     Version Win32 : 4.7.2633.0 built by: NET471REL1LAST_C
>     CodeBase : file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
> ----------------------------------------
> System
>     Version de l'assembly : 4.0.0.0
>     Version Win32 : 4.7.2556.0 built by: NET471REL1
>     CodeBase : file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
> ----------------------------------------
> MimeKit
>     Version de l'assembly : 2.0.0.0
>     Version Win32 : 2.0.1.0
>     CodeBase : file:///C:/Users/flamm/Downloads/Compressed/MailKit-master/samples/ImapClientDemo/ImapClientDemo/bin/Debug/MimeKit.DLL
> ----------------------------------------
> System.Windows.Forms
>     Version de l'assembly : 4.0.0.0
>     Version Win32 : 4.7.2556.0 built by: NET471REL1
>     CodeBase : file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
> ----------------------------------------
> System.Drawing
>     Version de l'assembly : 4.0.0.0
>     Version Win32 : 4.7.2556.0 built by: NET471REL1
>     CodeBase : file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
> ----------------------------------------
> System.Configuration
>     Version de l'assembly : 4.0.0.0
>     Version Win32 : 4.7.2556.0 built by: NET471REL1
>     CodeBase : file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
> ----------------------------------------
> System.Xml
>     Version de l'assembly : 4.0.0.0
>     Version Win32 : 4.7.2612.0 built by: NET471REL1LAST_B
>     CodeBase : file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
> ----------------------------------------
> mscorlib.resources
>     Version de l'assembly : 4.0.0.0
>     Version Win32 : 4.7.2556.0 built by: NET471REL1
>     CodeBase : file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_fr_b77a5c561934e089/mscorlib.resources.dll
> ----------------------------------------
> System.Windows.Forms.resources
>     Version de l'assembly : 4.0.0.0
>     Version Win32 : 4.7.2556.0 built by: NET471REL1
>     CodeBase : file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_fr_b77a5c561934e089/System.Windows.Forms.resources.dll
> ----------------------------------------
> 
> ************** Débogage JIT **************
> Pour activer le débogage juste-à-temps (JIT), le fichier de configuration pour cette
> application ou cet ordinateur (machine.config) doit avoir la valeur
> jitDebugging définie dans la section system.windows.forms.
> L'application doit également être compilée avec le débogage
> activé.
> 
> Par exemple :
> 
> <configuration>
>     <system.windows.forms jitDebugging="true" />
> </configuration>
> 
> Lorsque le débogage juste-à-temps est activé, les exceptions non gérées
> seront envoyées au débogueur JIT inscrit sur l'ordinateur
> plutôt que d'être gérées par cette boîte de dialogue.

File IMAP.LOG

> Connected to imaps://imap.free.fr:993/
> S: * OK IMAP4 ready
> C: A00000000 CAPABILITY
> S: * CAPABILITY IMAP4REV1 X-NETSCAPE LOGIN-REFERRALS AUTH=PLAIN
> S: A00000000 OK completed
> C: A00000001 AUTHENTICATE PLAIN
> S: + 
> C: AGdyZWdvcnlkZXZhdXgAZmxhbW1lOTEyMnNt
> S: A00000001 OK [CAPABILITY IMAP4rev1 ACL BINARY CATENATE CHILDREN CONDSTORE ENABLE ESEARCH ESORT I18NLEVEL=1 ID IDLE LIST-EXTENDED LIST-STATUS LITERAL+ LOGIN-REFERRALS MULTIAPPEND NAMESPACE QRESYNC QUOTA RIGHTS=ektx SASL-IR SEARCHRES SORT THREAD=ORDEREDSUBJECT UIDPLUS UNSELECT WITHIN XLIST] LOGIN completed
> C: A00000002 NAMESPACE
> S: * NAMESPACE (("" "/")) (("/home/" "/")) NIL
> S: A00000002 OK NAMESPACE completed
> C: A00000003 LIST "" "INBOX"
> S: * LIST (\HasChildren) "/" "INBOX"
> S: A00000003 OK LIST completed
> C: A00000004 XLIST "" "*"
> S: * XLIST (\HasChildren) "/" "2007"
> S: * XLIST (\HasNoChildren) "/" "2007/sent-mail"
> S: * XLIST (\HasNoChildren) "/" "2008"
> S: * XLIST (\HasNoChildren) "/" "2009"
> S: * XLIST (\HasNoChildren) "/" "2010"
> S: * XLIST (\HasNoChildren) "/" "2011"
> S: * XLIST (\HasNoChildren) "/" "2012"
> S: * XLIST (\HasNoChildren) "/" "Chats"
> S: * XLIST (\HasNoChildren) "/" "Commercial"
> S: * XLIST (\HasNoChildren) "/" "Contacts"
> S: * XLIST (\HasNoChildren) "/" "Deleted Items"
> S: * XLIST (\HasNoChildren \Drafts) "/" "Drafts"
> S: * XLIST (\HasNoChildren) "/" "Emailed Contacts"
> S: * XLIST (\HasChildren \Inbox) "/" "INBOX"
> S: * XLIST (\HasNoChildren) "/" "INBOX/appartement"
> S: * XLIST (\HasNoChildren) "/" "INBOX/dl.free.fr"
> S: * XLIST (\HasNoChildren) "/" "INBOX/ecole"
> S: * XLIST (\HasNoChildren) "/" "INBOX/important"
> S: * XLIST (\HasNoChildren) "/" "INBOX/job"
> S: * XLIST (\HasNoChildren) "/" "INBOX/OVH"
> S: * XLIST (\HasNoChildren) "/" "INBOX/Taff"
> S: * XLIST (\HasNoChildren) "/" "INBOX/Telephone"
> S: * XLIST (\HasChildren) "/" "INBOX/Vacance"
> S: * XLIST (\HasNoChildren) "/" "INBOX/Vacance/2016"
> S: * XLIST (\NoInferiors \Spam) "/" "Junk"
> S: * XLIST (\HasNoChildren) "/" "ReseauxSociaux"
> S: * XLIST (\HasNoChildren \Sent) "/" "Sent"
> S: * XLIST (\HasNoChildren) "/" "Sent Items"
> S: * XLIST (\HasNoChildren \Trash) "/" "Trash"
> S: A00000004 OK XLIST completed
> C: A00000005 LIST "" "%" RETURN (SUBSCRIBED CHILDREN)
> S: * LIST (\Subscribed \HasChildren) "/" "2007"
> S: * LIST (\Subscribed \HasNoChildren) "/" "2008"
> S: * LIST (\Subscribed \HasNoChildren) "/" "2009"
> S: * LIST (\Subscribed \HasNoChildren) "/" "2010"
> S: * LIST (\Subscribed \HasNoChildren) "/" "2011"
> S: * LIST (\Subscribed \HasNoChildren) "/" "2012"
> S: * LIST (\HasNoChildren) "/" "Chats"
> S: * LIST (\HasNoChildren) "/" "Commercial"
> S: * LIST (\HasNoChildren) "/" "Contacts"
> S: * LIST (\HasNoChildren) "/" "Deleted Items"
> S: * LIST (\HasNoChildren) "/" "Drafts"
> S: * LIST (\HasNoChildren) "/" "Emailed Contacts"
> S: * LIST (\Subscribed \HasChildren) "/" "INBOX"
> S: * LIST (\NoInferiors) "/" "Junk"
> S: * LIST (\HasNoChildren) "/" "ReseauxSociaux"
> S: * LIST (\HasNoChildren) "/" "Sent"
> S: * LIST (\HasNoChildren) "/" "Sent Items"
> S: * LIST (\HasNoChildren) "/" "Trash"
> S: A00000005 OK LIST completed
> C: A00000006 STATUS 2007 (UNSEEN)
> S: * STATUS "2007" (UNSEEN 0)
> S: A00000006 OK STATUS completed
> C: A00000007 STATUS 2008 (UNSEEN)
> S: * STATUS "2008" (UNSEEN 0)
> S: A00000007 OK STATUS completed
> C: A00000008 STATUS 2009 (UNSEEN)
> S: * STATUS "2009" (UNSEEN 0)
> S: A00000008 OK STATUS completed
> C: A00000009 STATUS 2010 (UNSEEN)
> S: * STATUS "2010" (UNSEEN 0)
> S: A00000009 OK STATUS completed
> C: A00000010 STATUS 2011 (UNSEEN)
> S: * STATUS "2011" (UNSEEN 0)
> S: A00000010 OK STATUS completed
> C: A00000011 STATUS 2012 (UNSEEN)
> S: * STATUS "2012" (UNSEEN 0)
> S: A00000011 OK STATUS completed
> C: A00000012 STATUS Chats (UNSEEN)
> S: * STATUS "Chats" (UNSEEN 0)
> S: A00000012 OK STATUS completed
> C: A00000013 STATUS Commercial (UNSEEN)
> S: * STATUS "Commercial" (UNSEEN 435)
> S: A00000013 OK STATUS completed
> C: A00000014 STATUS Contacts (UNSEEN)
> S: * STATUS "Contacts" (UNSEEN 0)
> S: A00000014 OK STATUS completed
> C: A00000015 STATUS "Deleted Items" (UNSEEN)
> S: * STATUS "Deleted Items" (UNSEEN 0)
> S: A00000015 OK STATUS completed
> C: A00000016 STATUS Drafts (UNSEEN)
> S: * STATUS "Drafts" (UNSEEN 0)
> S: A00000016 OK STATUS completed
> C: A00000017 STATUS "Emailed Contacts" (UNSEEN)
> S: * STATUS "Emailed Contacts" (UNSEEN 0)
> S: A00000017 OK STATUS completed
> C: A00000018 STATUS INBOX (UNSEEN)
> S: * STATUS "INBOX" (UNSEEN 5)
> S: A00000018 OK STATUS completed
> C: A00000019 STATUS Junk (UNSEEN)
> S: * STATUS "Junk" (UNSEEN 19)
> S: A00000019 OK STATUS completed
> C: A00000020 STATUS ReseauxSociaux (UNSEEN)
> S: * STATUS "ReseauxSociaux" (UNSEEN 215)
> S: A00000020 OK STATUS completed
> C: A00000021 STATUS Sent (UNSEEN)
> S: * STATUS "Sent" (UNSEEN 0)
> S: A00000021 OK STATUS completed
> C: A00000022 STATUS "Sent Items" (UNSEEN)
> S: * STATUS "Sent Items" (UNSEEN 0)
> S: A00000022 OK STATUS completed
> C: A00000023 STATUS Trash (UNSEEN)
> S: * STATUS "Trash" (UNSEEN 0)
> S: A00000023 OK STATUS completed
> C: A00000024 EXAMINE INBOX (CONDSTORE)
> S: * 13701 EXISTS
> S: * 1 RECENT
> S: * OK [UNSEEN 13667] mailbox contains unseen messages
> S: * OK [UIDVALIDITY 1] UIDs are valid for this mailbox
> S: * OK [UIDNEXT 50629] next expected UID is 50629
> S: * FLAGS (\Answered \Deleted \Draft \Flagged \Seen $Forwarded $MDNSent Forwarded $Junk $NotJunk Junk JunkRecorded NonJunk NotJunk)
> S: * OK [PERMANENTFLAGS ()] junk-related flags are not permanent
> S: * OK [HIGHESTMODSEQ 81530] modseq tracked on this mailbox
> S: A00000024 OK [READ-ONLY] EXAMINE completed

**Comment by jstedfast** [comment]
Thanks. I for got to update the code to do proper locking once I made MailKit fully async instead of using Task.Run() around the synchronous methods.

What is happening is that an IMAP command is still running when the client tries to send another command.

**Comment by rashiddear** [comment]
I also download your example and updated defined on https://github.com/jstedfast/MailKit/commit/152d0bee361eaf6c627c80e581ceb5955360d33e 
but i am still getting the error on same place await folder.StatusAsync(StatusItems.Unread); in procedure async void UpdateUnreadCount(object sender, EventArgs e).

Could you please help me for this.

Thanks
