### ISSUE TITLE
Can we attach Email Tracking?

### ISSUE THREAD

**Issue by docrizwan** [jstedfast/MailKit#654]
Hi Jeff,
Loved your library and explored it much.
Now, my personal mailbox users want the new feature.
-- Email tracking (just like other trackers do)

Can you share me some helping resource for adding email tracking in the email sent by my mailbox (which developed based on Mailkit)?

**Comment by jstedfast** [comment]
what do you mean by email tracking?

Keep in mind that a lot of the advanced functionality you find in clients like Outlook are done using proprietary protocols and are not possible to do with SMTP, POP3 and IMAP.

**Comment by docrizwan** [comment]
Got to know that.
What I mean by tracking is to monitor, when and where from email is viewed by which user.
Is it possible to do it? Any 3rd party library you want to recommend? will love it.

**Comment by jstedfast** [comment]
There's no support for that in any of the standard protocols. I don't know what to suggest to you. If you could guarantee that everyone you are communicating with uses your specific email client, then you could probably implement something like that, but otherwise, you are SOL.

**Comment by docrizwan** [comment]
Thank you for your support.
