### ISSUE TITLE
Auto responder implementation

### ISSUE THREAD

**Issue by docrizwan** [jstedfast/MailKit#655]
Yo Jeff,
Loved your library and explored it much.
Now, my personal mailbox users want the new feature.
-- Auto reponder

Can you share me some helping resource regarding auto responder implementation in mailbox (which developed based on Mailkit)?

**Comment by jstedfast** [comment]
Well, to implement an auto-responder, you just need to auto-generate MimeMessages that say "So-and-so is out of the office at this time." and send them to anyone who sends your user a new message.

There's no need to add any functionality to MailKit for this.
