### ISSUE TITLE
folder.open return "No" response in 163 email

### ISSUE THREAD

**Issue by gogood** [jstedfast/MailKit#657]
Hi Jeff,
I'm using your library and loved this...

But, Can you help me ? I really ,really  need you help.
Now, I'm facing an issue that I cannot open the inbox folder in 163 email. I can receive emails in yahoo, outlook email, but cannot receive email in 163 email. I need to say I can receive 163 email via pop protocol.so I don't think there is any error in your library. I found many information about 163 email, and 163 email prevent receiving email via imap beacause it thinks this is unsafe . But I found this: http://ask.csdn.net/questions/347764

163 email prevent receiving email via imap:

So what does that workaround do? IMAP command is usually in the format
1 CAPABILITY 
2 LOGIN USERNAME PASSWORD 
3 CAPABILITY 
4 LIST "" "" 
5 ID NIL 
6 SELECT INBOX  
but 163 required a “C” before each command, eg
C1 CAPABILITY
so the fix is… add “C”.
it's mean we need to modify the Protocol object’s writeCommand method and use a “C” prefix for 163 (also 126.com, yeah.net) imap host address.

so I think maybe you change your library code and help me to receive 163 email, or any valuable suggestions are highly appreciated.
can you understand what I mean,and my english is not very well.
Thank you so much!

**Comment by jstedfast** [comment]
You can use System.Reflection to set the ImapEngine's TagPrefix and/or TagPrefixIndex (you might need to change the TagPrefixIndex).

Use reflection to find `MailKit.Net.Imap.ImapEngine` after creating a `new ImapClient`. Then, before you call the `Connect()` method, change the `static int MailKit.Net.Imap.ImapEngine.TagPrefixIndex` value to `2`.

This will cause the `ImapEngine`'s `TagPrefix` to be `'C'` (`'A' + 2 = 'C'`).

**Comment by gogood** [comment]
Hi, Jeff, Thanks your quick answer.
I did what you said and I think I successed to change the ImapEngine's TagPrefix to be 'C'. but it doesn't work. I still cannot open folder and return "No" respsonse.

ImapClient imapClient = new ImapClient();
imapClient.ServerCertificateValidationCallback = (s, c, h, e) => true;
System.Reflection.Assembly imapClientType = typeof(ImapClient).Assembly;
Type engineType = imapClientType.GetType("MailKit.Net.Imap.ImapEngine");
  if (engineType != null)
      {
           FieldInfo fieldInfo = engineType.GetField("TagPrefixIndex",BindingFlags.NonPublic | BindingFlags.Static);
           if (fieldInfo != null)
           {
                   fieldInfo.SetValue(null, 2);
                   var TagPrefixIndex = (int)(fieldInfo.GetValue(null));
                   var changeTagPrefix = (char)('A' + (TagPrefixIndex++ % 26));
                   System.Diagnostics.Debug.WriteLine("GetEmailMessage_Droid AuthenMailBoxUser fieldInfo changeTagPrefix:" + changeTagPrefix);
                    }
              }
           imapClient.Connect(emailServer.Server, emailServer.Port, SecureSocketOptions.SslOnConnect);
           imapClient.AuthenticationMechanisms.Remove("XOAUTH2");
           imapClient.Authenticate(mailAccount, mailPassword);

Maybe the method doesn't work, I don't know and I only know 163 email does not follow the specification of IMAP.

**Comment by jstedfast** [comment]
I doubted that this "hack" would work anyway, it didn't make any sense to me.
