### ISSUE TITLE
IMapClient.connect takes a very long time

### ISSUE THREAD

**Issue by avdegt1976** [jstedfast/MailKit#659]
Hello, I have very simply code like this:

client.ServerCertificateValidationCallback = (s, c, h, e) => true;
client.Timeout = 30000;
emailServer.tokenSource = new CancellationTokenSource();
emailServer.token = tokenSource.Token;
client.Connect(connectionLine, port, true,emailServer.token);
                
.. and I also have onTimer event each of 30 seconds which checks if connect function is still running, and if yes - it sends cancellation token to Cancel() like this:

public void OnTimer(object sender, System.Timers.ElapsedEventArgs args)
        {
            if (emailServer.inReconnection)
                emailServer.tokenSource.Cancel();

However it doesn't work. Sometimes client.Connect() takes 2-3 hours (!!!!) of trying connect to IMAP.YANDEX.RU, then it shows error due to some reason, then connecting again OK. 

How I can stop the process of connection after 30 seconds of trying?

**Comment by jstedfast** [comment]
What you'll have to do is search StackOverflow.com for how to cancel a Socket.Connect() call in .NET, then implement that yourself. Then, once you have a connected Socket, you can pass it off to `client.Connect(Socket socket, string host, int port, SecureSocketOption sslOptions)`

I can't easily support cancellation of Socket.Connect() in MailKit.

**Comment by avdegt1976** [comment]
Thanks, but the problem is I have SSL connection, which means no socket available.
What if I do asynchronous mode of connection?

**Comment by jstedfast** [comment]
All connections have a socket, even SSL connections.
