### ISSUE TITLE
Memory leak after getting messages via Imap

### ISSUE THREAD

**Issue by roederm94** [jstedfast/MailKit#660]
To help me debug your issue, please explain:
- What were you trying to do? -> Getting unread messages with ImapClient out of IMailFolder
- What happened? -> I get a memeory leak after getting all messages. Disposing ImapClient and closing IMailFolder does not fix this leak.
- What did you expect to happen? -> I expect that the memory gets released after disposing the ImapClient and closing the IMailFolder.
- Step-by-step reproduction instructions and/or a simple test case. -> Sample Code:

**Members:**

private readonly ImapClient _client = new ImapClient();
private IMailFolder _inbox;

**Connecting:**

public void Login(string serverAddress, int port,
            string username, string password, bool useSsl)
        {
            _client.ServerCertificateValidationCallback = (s, c, h, e) => true;

            _client.Connect(serverAddress, port, useSsl);
            
            _client.AuthenticationMechanisms.Remove("XOAUTH2");

            _client.Authenticate(username, password);
            _inbox = _client.Inbox;
            _inbox.Open(FolderAccess.ReadWrite);
        }

**Getting the mails:**

Returning own object "ImapMessage"
In my case the ImapSearchQuery is "Unread"

        public List<ImapMessage> GetMessages(ImapSearchQuery searchQuery)
        {
            // Validation
            if (!_searchQueriesWrapper.ContainsKey(searchQuery))
                throw new ArgumentOutOfRangeException(nameof(searchQuery));

            // Get the messages
            List<ImapMessage> messages = new List<ImapMessage>();

            foreach (UniqueId uid in _inbox.Search(_searchQueriesWrapper[searchQuery]))
            {
                MimeMessage message = _inbox.GetMessage(uid);
                
                // Creates the message object with the basic informations
                ImapMessage imapMessage = new ImapMessage
                {
                    Id = uid.Id,
                    Subject = message.Subject,
                    HtmlBody = message.HtmlBody
                };

                // Adds all attachments
                foreach (MimeEntity bodyPart in message.BodyParts)
                {
                    if(bodyPart is MimePart mimePart && !String.IsNullOrEmpty(mimePart.ContentType.Name))
                        imapMessage.Attachements.Add(new ImapAttachement(mimePart));
                }

                messages.Add(imapMessage);
            }

            return messages;
        }

I call the Login() method. After that I call the GetMessages() method. I get 26 messages. Then I close the IMailFolder and dispose the ImapCleint. The used RAM stays the same after disposing the ImapClient.

I attached the log information for you.

[imap.log](https://github.com/jstedfast/MailKit/files/1777757/imap.log)

Thank you.
Regards,
Marvin

**Comment by jstedfast** [comment]
The problem is that you are holding open streams in your ImapMessage's Attachments collection.

That's where the "leak" is.

**Comment by roederm94** [comment]
Hello.
How can I close the stream?
Is the stream the bodypart of the MimeMessage?

Thank you!

**Comment by jstedfast** [comment]
Each `MimePart` has a `Content` property of type `MimeContent` which has a `Stream` property that you need to close.

**Comment by roederm94** [comment]
Hello,

I just tried that out right now. I closed and disposed all MimePart Content Streams but the RAM stays the same. It does not get released. Do you need any further information? It would be grat if I get this problem solved as it is very important for me.

Thank you very much.
Regards,
Marvin

**Comment by roederm94** [comment]
Hello,

I attached my code samples for you.
I hope that you can find the error.
I think I did everything right.

**Program.cs**
![program](https://user-images.githubusercontent.com/37024090/36948564-0372f33c-1fdd-11e8-8100-cf5ac6ba7f43.jpg)

**Disposing ImapMessage**
![imapmessagedispose](https://user-images.githubusercontent.com/37024090/36948565-08712e80-1fdd-11e8-9ddc-43214d8071a3.PNG)

**Disposing ImapAttachment (Closing and disposing ContentObject Stream**
![imapattachmentdispose](https://user-images.githubusercontent.com/37024090/36948569-0ad371f6-1fdd-11e8-9217-7f74640e417a.PNG)


Thank you for your support.
Regards
Marvin

**Comment by jstedfast** [comment]
What are you using to decide if you have a leak or not? Just RAM usage of the VM?

If so, then you're doing it wrong :)

The VM won't release memory.

**Comment by roederm94** [comment]
I am checking the RAM usage in Visual Studio 2017 Professional. If attached a screenshot of the usage before getting the mails, after getting the mails and after disposing and closing the content streams. The screenshots are based of getting 5731 mails.

**Before getting mails:**

![ramusagebefore](https://user-images.githubusercontent.com/37024090/36949419-81cbf656-1fe8-11e8-9182-eca59c47e108.PNG)

**After getting mails:**

![ramusageaftergettingmail](https://user-images.githubusercontent.com/37024090/36949425-8e034e74-1fe8-11e8-9b7c-08b3b25ba66a.PNG)

**After disposing and closing the streams:**

![ramusageafterdisposing](https://user-images.githubusercontent.com/37024090/36949432-9b7028e8-1fe8-11e8-98b2-132445a75795.PNG)


Thank you.
Regards,
Marvin

**Comment by roederm94** [comment]
If you mean "Virtual Machine" with "VM": I am not using any virtual machine. I am debugging and testing it on my local system.

Regards,
Marvin

**Comment by jstedfast** [comment]
What I meant by VM is the virtual machine *of the .NET runtime*. In other words, the .NET runtime *is* a VM :)

So did disposing the streams reduce memory usage? If so, make sure you dispose the streams of the `MimePart`s that you *aren't* storing in your Attachments list as well and that should reduce it the rest of the way. If it didn't help, then the problem isn't a "leak", it's just the way the .NET runtime works.

All this said, the streams should all be `MemoryStream`s and so don't really need to be disposed as long as you aren't keeping references to them. The GC should be smart enough to clean them up because a `MemoryStream` doesn't actually hold any native references, it just has a reference to a managed `byte[]` which is not in any way a "leak".

Anyway... there's no memory leaks in MimeKit or MailKit.

To really debug leaks, you need proper tools that actually track object lifetimes/references. You can't just assume a "leak" because your memory usage goes up.

**Comment by roederm94** [comment]
Hello,
Thank you.
Disposing them did not change anything. I am going to test this tomorrow again.

Thanks
