### ISSUE TITLE
Retrieve inbox messages in reverse order Mailkit.

### ISSUE THREAD

**Issue by arn3342** [jstedfast/MailKit#661]
Hello, i am using this code to retrieve messages(only FROM and DATE) from my gmail inbox : 

`var inbox = MailKitClient.Inbox;
    inbox.Open(FolderAccess.ReadOnly);
    for (int i = 0; i <= inbox.Count - 1; i++)
    {
        var message = inbox.GetMessage(i);
        Emails Email = new Emails;
        Email.From = message.From.ToString;
        Email.Subject = message.Date.ToString;
        InboxMails.Add(Email);
    }`

The problem is,as i am also loading the dates,i can see that the message start coming/retrieving from the last message and eventually to the first. I tried using sort : 

  `inbox.sort(Search.SearchQuery.NotDeleted,Search.OrderBy.ReverseArrival)`

But it throws an error saying IMAP SERVER DOESNT SUPPORT SORT or something like that

**Comment by ekalchev** [comment]
for (int i = inbox.Count -1; i >= 0; i--)

try this

**Comment by jstedfast** [comment]
As you have discovered, not all IMAP servers support the SORT extension.

The way to check for this in the future, is:

```csharp
if (client.Capabilitiers.HasFlag (ImapCapabilities.Sort))
{
    // the server supports the SORT command
}
```

If the server doesn't support sorting, then all you can do is sort things client-side. @ekalchev 's suggestion is the easiest, but you could also download all of the messages into a list (or an array) and sort the result using `System.Array.Sort()`.

Which you choose is up to you.

Hope that helps!

**Comment by arn3342** [comment]
why was this post closed ?

**Comment by arn3342** [comment]
for (int i = inbox.Count -1; i >= 0; i--)

This doesnt even return a single message

**Comment by jstedfast** [comment]
It was closed because it was explained that could make a loop that walks backwards to get the messages in reverse order.

**Comment by arn3342** [comment]
but that loop doesnt even return a single messge.....any help ?

**Comment by arn3342** [comment]
any help plz??

**Comment by ekalchev** [comment]
try with FolderAccess.ReadWrite
inbox.Open(FolderAccess.ReadWrite)

**Comment by arn3342** [comment]
Tried that a long ago,didnt work

**Comment by arn3342** [comment]
Hey, if i have a list)of string) populated with unique id,is it possible to get messgaes(from,date) using the UniqueIds from the list ?
