### ISSUE TITLE
Does mailkit support certificate store

### ISSUE THREAD

**Issue by jimjimbojimbob** [jstedfast/MailKit#662]
We have a mailkit based imap client for viewing email which works as expected.

When an Anti-Virus client installs it's own certificate and scans SSL connections, it presents it's own certificate and gives us the error 'Remote certificate has errors'.  As documented by yourself we have easily fixed this by referencing the thumbprint of the AV programs certificate (or simply ignoring these errors), however I was wondering is mailkit able to reference the certificate store in the same way Outlook does so we don't need to manually reference the thumbprint?

Thanks,

Jim

**Comment by jstedfast** [comment]
For SSL, MailKit uses `SslStream` which references the SSL Certificate Store in whatever way the standard way is for that system (Windows is different from Linux which is different from MacOS and might differ between Mono and CoreCLR as well).

I have no idea how Outlook accesses the certificate store(s) on your system, but I imagine it would be the same way that the standard .NET runtime does on Windows (the Mono runtime might be different, I'm not sure).

Other than the callback that MailKit provides (which is really just a hook into the callback approach that SslStream provides), there's no other way that I know of to control how certificates and/or certificate stores are used.

Probably not quite the answer you were hoping for, but I hope that helps...
