### ISSUE TITLE
ImapStream cancellation and socket disconnect

### ISSUE THREAD

**Issue by ekalchev** [jstedfast/MailKit#663]
I can see that if you cancel a imap command that leads to imapClient.disconnect which calls Socket.Dispose()

I am looking at this and it seems there is a special procedure to disconnect the socket so the both sides are aware that the connection is terminating.
https://en.wikipedia.org/wiki/Transmission_Control_Protocol#Connection_termination

I wonder if Socket.Dispose() will close the connection on the server side and won't leave the connection open on the server and eventually ran out of available connections for the current account, if cancel is used multiple times.

I see the recommended way to disconnecting a C# socket is

socket.Shutdown(SocketShutdown.Both);
socket.Dispose()

not sure if socket.Shutdown(SocketShutdown.Both) will work if the socket is still streaming data

Thought?

P.S.

I ran some tests and it seems socket.Dispose is never called on OperationCancelledException. I guess the actual disconnect happens in NetworkStream.Dispose(). This method call Socket.InternalShutdown.

My tests shows that there is no issue with left open connections on the server.

**Comment by jstedfast** [comment]
As far as I'm aware, it's not really an issue and it sounds like your testing came to the same conclusion? Or am I misunderstanding?

**Comment by ekalchev** [comment]
Yeah, my tests shows that there are no open connections on the server when you dispose the NetworkStream.

I was initially concerned by this in ImapClient.ConnectAsync

                       for (int i = 0; i < ipAddresses.Length; i++) {
				socket = new Socket (ipAddresses[i].AddressFamily, SocketType.Stream, 
                         ProtocolType.Tcp);

				try {
					cancellationToken.ThrowIfCancellationRequested ();

					if (LocalEndPoint != null)
						socket.Bind (LocalEndPoint);

					socket.Connect (ipAddresses[i], port);
					break;
				} catch (OperationCanceledException) {
					socket.Dispose ();
					throw;
				} catch {
					socket.Dispose ();

					if (i + 1 == ipAddresses.Length)
						throw;
				}
			}

Here we have socket that is not called Socket.Close and Socket.Shutdown but looking closely those exceptions can't occur before the socket is connected so it seems ok.
