### ISSUE TITLE
reconnect on disconnect?

### ISSUE THREAD

**Issue by zxed** [jstedfast/MailKit#665]
I'm using azure an azure webjob to run a continuous job that will (on launch) listen to N imap accounts via oauth.

Running locally as console app, it works fine; below is the code that starts the tasks to connect., 

```csharp
static void Main()
        {
            var host = new JobHost();
            // The following code ensures that the WebJob will be running continuously
            List<SomeEmailProc> emails = new List<SomeEmailProc>();
            using (someEntities en = new someEntities())
            {
                var mss = en.ValidatedAccounts.ToList();
                foreach (var item in mss)
                {
                    var bk = en.AccountToken.Where(o => o.AccountId == item.Id).FirstOrDefault();
                    if (bk == null || string.IsNullOrEmpty(item.RefreshToken)) continue;
                    Task.Factory.StartNew(() =>
                    {
                        try{
                            emails.Add(new SomeEmailProc(item, bk));
                        }
                        catch { }
                    });
                }
            }

            host.RunAndBlock();
        }
```

The SomeEmailProc - function basically, initializes the client where it will auth with the appropriate folders and the event listeners.

I need to figure out how to capture the protocol log when its running in the azure webjob space- the output will be truncated on azure webjobs.

Since I do not yet know if azure is putting it in "cold mode" or if the clients are timing out and not connecting - my first question is "do we need to explicitly handle a disconnect, and do a reconnect on disconnect?" or is this handled automatically by the client?

**Comment by jstedfast** [comment]
You will need to manually re-connect once you've been disconnected. It will not auto-reconnect for you (I considered trying to implement this but it would require MailKit to hold onto the auth credentials which seemed like a bad idea for security reasons).
