### ISSUE TITLE
Get summary from mailkit c#

### ISSUE THREAD

**Issue by arn3342** [jstedfast/MailKit#668]
I am trying to retrieve the emails after a specific ID using `MailKit`.I am using the below code:

   ` var range = new UniqueIdRange (new UniqueId ((uint) 2001), UniqueId.MaxValue);

    foreach (var uid in folder.Search (range, query)) {
    var message = folder.GetMessage (uid);
    }`

Now my problem is,in such a situation,i don't want to download the entire message,but just the `Summary`(IMessageSummary) because i just want the `From` and `Date` from the summary.I know i can use `message.from` bur i need `summary.From`.Any way to do that ?

One last question, i have 2 forms in my winforms app,is it possible to login using `MailKit.Net.ImapClient` from one from and use that login/connection in the second form so that in the 2nd form, i dont need to log in again ?

**Comment by jstedfast** [comment]
Instead of this:

```csharp
var range = new UniqueIdRange (new UniqueId ((uint) 2001), UniqueId.MaxValue);

foreach (var uid in folder.Search (range, query)) {
    var message = folder.GetMessage (uid);
}
```

do this:

```csharp
var range = new UniqueIdRange (new UniqueId ((uint) 2001), UniqueId.MaxValue);
var uids = folder.Search (range, query);

foreach (var summary in folder.Fetch (uids, MessageSummaryItems.Envelope)) {
    // now you can use summary.Envelope to get date or from
}
```

> One last question, i have 2 forms in my winforms app,is it possible to login using MailKit.Net.ImapClient from one from and use that login/connection in the second form so that in the 2nd form, i dont need to log in again ?

Yes, it's possible. You would do it the same way you would share an integer variable or anything else between 2 forms.

**Comment by arn3342** [comment]
can u please explain the answer to my last qs ? I am really new to c#
