### ISSUE TITLE
Get messages using email address

### ISSUE THREAD

**Issue by arn3342** [jstedfast/MailKit#673]
I retrieved the sender address using `message.From.ToStroing`. Now,for example,if i have an email address such as `abc@def.com`, is there a way to fetch all the mail summary that came from this specific address ?

**Comment by jstedfast** [comment]
Yes:

```csharp
var uids = folder.Search (SearchQuery.FromContains ("abc@def.com"));
var summaries = folder.Fetch (uids, .....);
```
