### ISSUE TITLE
FolderNotFound exception

### ISSUE THREAD

**Issue by ekalchev** [jstedfast/MailKit#674]
var personalNamespace = imapConnection.PersonalNamespaces[0];
imapConnection.GetFolder(personalNamespace);

This code throws FolderNotFound exception. I thought I am doing something wrong and tried a workaround but this

imapConnection.GetFolders(personalNamespace, StatusItems.None, false);

 also throws an FolderNotFound exception

I am using Protonmail bridge to connect to protonmail imap server.

Connected to imap://127.0.0.1:1143/?starttls=when-available
S: * OK [CAPABILITY IMAP4rev1 STARTTLS AUTH=PLAIN AUTH=LOGIN ID APPENDLIMIT] IMAP4rev1 Service Ready
C: A00000000 STARTTLS
S: A00000000 OK Begin TLS negotiation now
C: A00000001 CAPABILITY
S: * CAPABILITY IMAP4rev1 AUTH=PLAIN AUTH=LOGIN ID XSTOP APPENDLIMIT
S: * CAPABILITY IMAP4rev1 AUTH=PLAIN AUTH=LOGIN ID XSTOP APPENDLIMIT
S: A00000001 OK CAPABILITY completed
C: A00000002 AUTHENTICATE PLAIN
S: +
C: ?????????
S: A00000002 OK [CAPABILITY IMAP4rev1 IDLE MOVE SPECIAL-USE ID XSTOP QUOTA APPENDLIMIT=26214400] AUTHENTICATE completed
C: A00000003 LIST "" ""
S: * LIST (\Noselect) "/" "/"
S: A00000003 OK LIST completed
C: A00000004 LIST "" "INBOX"
S: * LIST (\Noinferiors) "/" "INBOX"
S: A00000004 OK LIST completed
C: A00000005 LIST (SPECIAL-USE) "" "*"
S: A00000005 BAD Reference name must be a string

**Comment by jstedfast** [comment]
Can you research what the correct command should be?

**Comment by ekalchev** [comment]
I can see Outlook and Em Client work correctly with protonmail.

This is what I see in em client log

21:50:23.509|012|   A5 LIST "" "%"
21:50:23.509|017|   * LIST (\Noinferiors) "/" "INBOX"
21:50:23.511|017|   * LIST (\Sent \Noinferiors) "/" "Sent"
21:50:23.511|014|   A6 SELECT "INBOX"
21:50:23.521|017|   * LIST (\Trash \Noinferiors) "/" "Trash"
21:50:23.547|017|   * LIST (\Junk \Noinferiors) "/" "Spam"
21:50:23.560|017|   * LIST (\Archive \Noinferiors) "/" "Archive"
21:50:23.570|017|   * LIST (\All \Noinferiors) "/" "All Mail"
21:50:23.590|017|   * LIST (\Noselect) "/" "Labels"
21:50:23.591|017|   * LIST (\Noselect) "/" "Folders"
21:50:23.591|017|   A5 OK LIST completed

**Comment by jstedfast** [comment]
What happens if you manually disable SPECIAL-USE support after Authenticate()?

```csharp
client.Capabilities &= ~ImapCapabilities.SpecialUse;
```

**Comment by ekalchev** [comment]
I am getting the same exceptions with client.Capabilities &= ~ImapCapabilities.SpecialUse;

**Comment by jstedfast** [comment]
What happens if you change this line: https://github.com/jstedfast/MailKit/blob/master/MailKit/Net/Imap/ImapEngine.cs#L2191

to this?

```csharp
PersonalNamespaces.Add (new FolderNamespace (list[0].DirectorySeparator, list[0].EncodedName));
```

**Comment by jstedfast** [comment]
Wait, never mind, that won't fix it...

**Comment by ekalchev** [comment]
I tried some commands from a console

tag LIST "" ""
* LIST (\Noselect) "/" "/"
tag OK LIST completed
tag LIST (SPECIAL-USE) "" "*"
tag BAD Reference name must be a string
tag LIST "" "*"
* LIST (\Noinferiors) "/" "INBOX"
* LIST (\Sent \Noinferiors) "/" "Sent"
* LIST (\Trash \Noinferiors) "/" "Trash"
* LIST (\Junk \Noinferiors) "/" "Spam"
* LIST (\Archive \Noinferiors) "/" "Archive"
* LIST (\All \Noinferiors) "/" "All Mail"
* LIST (\Noselect) "/" "Labels"
* LIST (\Noselect) "/" "Folders"
tag OK LIST completed
tag LIST "/" "*"
tag OK LIST completed
tag LIST "" "%"
* LIST (\Noinferiors) "/" "INBOX"
* LIST (\Sent \Noinferiors) "/" "Sent"
* LIST (\Trash \Noinferiors) "/" "Trash"
* LIST (\Junk \Noinferiors) "/" "Spam"
* LIST (\Archive \Noinferiors) "/" "Archive"
* LIST (\All \Noinferiors) "/" "All Mail"
* LIST (\Noselect) "/" "Labels"
* LIST (\Noselect) "/" "Folders"
tag OK LIST completed

**Comment by jstedfast** [comment]
Try changing this line: https://github.com/jstedfast/MailKit/blob/master/MailKit/Net/Imap/ImapEngine.cs#L2255

to this:

```csharp
ic = new ImapCommand (this, cancellationToken, null, "LIST (SPECIAL-USE) \"\" \"/*\"\r\n");
```

**Comment by jstedfast** [comment]
Another option might be: `LIST (SPECIAL-USE) "/" "*"`

**Comment by ekalchev** [comment]
Same 

tag LIST (SPECIAL-USE) "/" "*"
tag BAD Reference name must be a string
tag LIST (SPECIAL-USE) "" "/*"
tag BAD Reference name must be a string

**Comment by jstedfast** [comment]
Ok, pretty sure that's a bug in ProtonMail's SPECIAL-USE implementation.

The only way I can think of to work around this, then, is to ignore `BAD` responses to this command and fall back to `LIST "" "*"`?

**Comment by ekalchev** [comment]
I just tried that

tag LIST "" "*" (SPECIAL-USE)
* LIST (\Noinferiors) "/" "INBOX"
* LIST (\Sent \Noinferiors) "/" "Sent"
* LIST (\Trash \Noinferiors) "/" "Trash"
* LIST (\Junk \Noinferiors) "/" "Spam"
* LIST (\Archive \Noinferiors) "/" "Archive"
* LIST (\All \Noinferiors) "/" "All Mail"
* LIST (\Noselect) "/" "Labels"
* LIST (\Noselect) "/" "Folders"
tag OK LIST completed

**Comment by ekalchev** [comment]
nevermind, it seems with this syntax the special-use is ignored

**Comment by ekalchev** [comment]
My observation to different email client logs shows that all of them use LIST "" "%" for listing folders. This was something I couldn't achieve with mailkit

**Comment by jstedfast** [comment]
The SPECIAL-USE query is needed to initialize the special folders so that doing `client.GetFolder (SpecialFolder.Sent);` works.

**Comment by jstedfast** [comment]
I just committed a potential fix (untested). Could you check to see if it works for you?

**Comment by ekalchev** [comment]
I'll be able to test it tomorrow and I'll let you know.

**Comment by jstedfast** [comment]
ok, thanks.

**Comment by jstedfast** [comment]
Going to close this for now under the expectation that my fix works. I'll be watching for your response tho, so if it doesn't, just let me know and I'll work on it until it does.

**Comment by ekalchev** [comment]
The fix you added have some issues.

1. It seems BAD response from the log is not throwing a ImapCommandException that is why ProtonMail fallback was never executed

2. MailKit have problems with LIST "" "%". ImapCommand constructor was throwing FormatException

This code

`                       using (var builder = new MemoryStream ()) {
				int argc = 0;
				byte[] buf;
				string str;
				char c;

				for (int i = 0; i < format.Length; i++) {
					if (format[i] == '%') {
						switch (format[++i]) {
						case '%': // a literal %
							builder.WriteByte ((byte) '%');
							break;
						case 'c': // a character
							c = (char) args[argc++];
							builder.WriteByte ((byte) c);
							break;
						case 'd': // an integer
							str = ((int) args[argc++]).ToString ();
							buf = Encoding.ASCII.GetBytes (str);
							builder.Write (buf, 0, buf.Length);
							break;
						case 'u': // an unsigned integer
							str = ((uint) args[argc++]).ToString ();
							buf = Encoding.ASCII.GetBytes (str);
							builder.Write (buf, 0, buf.Length);
							break;
						case 'F': // an ImapFolder
							var utf7 = ((ImapFolder) args[argc++]).EncodedName;
							AppendString (options, true, builder, utf7);
							break;
						case 'L':
							var literal = new ImapLiteral (options, args[argc++], UpdateProgress);
							var length = literal.Length;
							var plus = string.Empty;
							bool wait = true;

							if (CanUseNonSynchronizedLiteral (literal.Length)) {
								wait = false;
								plus = "+";
							}

							totalSize += length;

							if (options.International)
								str = "UTF8 (~{" + length + plus + "}\r\n";
							else
								str = "{" + length + plus + "}\r\n";

							buf = Encoding.ASCII.GetBytes (str);
							builder.Write (buf, 0, buf.Length);

							parts.Add (new ImapCommandPart (builder.ToArray (), literal, wait));
							builder.SetLength (0);

							if (options.International)
								builder.WriteByte ((byte) ')');
							break;
						case 'S': // a string which may need to be quoted or made into a literal
							AppendString (options, true, builder, (string) args[argc++]);
							break;
						case 'Q': // similar to %S but string must be quoted at a minimum
							AppendString (options, false, builder, (string) args[argc++]);
							break;
						case 's': // a safe atom string
							buf = Encoding.ASCII.GetBytes ((string) args[argc++]);
							builder.Write (buf, 0, buf.Length);
							break;
						default:
							throw new FormatException ();
						}
					} else {
						builder.WriteByte ((byte) format[i]);
					}
				}`

With this string LIST "" "%" when you get to % character you enter in if (format[i] == '%') { and they try to switch on the next character which in this case is double-quote and there is no case '"' for double-quote that is why it falls back to FormatException

I was able to get the list of folders by editing your code to this

`if ((Capabilities & ImapCapabilities.SpecialUse) != 0) {
				ic = new ImapCommand (this, cancellationToken, null, "LIST (SPECIAL-USE) \"\" \"*\"\r\n");
				ic.RegisterUntaggedHandler ("LIST", ImapUtils.ParseFolderListAsync);
				ic.UserData = list;

				QueueCommand (ic);

                if(ic.Response == ImapCommandResponse.Bad)
                {
                    ic = new ImapCommand(this, cancellationToken, null, "LIST \"\" \"*\"\r\n");
                    ic.RegisterUntaggedHandler("LIST", ImapUtils.ParseFolderListAsync);
                    ic.UserData = list;

                    list.Clear();

                    QueueCommand(ic);

                    await RunAsync(ic, doAsync).ConfigureAwait(false);
                }

				await LookupParentFoldersAsync (list, doAsync, cancellationToken).ConfigureAwait (false);

				AssignSpecialFolders (list);
			}`

**Comment by ekalchev** [comment]
Another possible issue

imapConnection.GetFolder(imapConnection.PersonalNamespaces[0])

C: A00000003 LIST "" ""
S: * LIST (\Noselect) "/" "/"

This throws FolderNotFound Exception - I tried a workaround in my code but I wonder, if the namespace folder cannot be returned how I am supposed to rename a folder that is direct descendant of the namespace since ImapFolder.Rename is supposed accept IMailFolder as a parent. How to do that when imapConnection.GetFolder(imapConnection.PersonalNamespaces[0]) doesn't return a folder.

**Comment by jstedfast** [comment]
Try the latest fix and let me know how that works for you. It should be the commit that bases the protonmail quirks mode on the XSTOP extension.

**Comment by ekalchev** [comment]
The fix you applied appear to be working. 

this line also works and returns folder
imapConnection.GetFolder(imapConnection.PersonalNamespaces[0])

Thank you for your efforts!

**Comment by jstedfast** [comment]
Awesome. Glad that worked out. I plan to make a new nuget release this weekend.

**Comment by jstedfast** [comment]
MailKit 2.0.2 has been released with this work-around.
