### ISSUE TITLE
NullReferenceException

### ISSUE THREAD

**Issue by ekalchev** [jstedfast/MailKit#677]
![image](https://user-images.githubusercontent.com/10009149/37616439-954f846e-2bb8-11e8-9145-20e59c1d9173.png)

I am getting null reference exception randomly after exit of idle when I try to open a folder immediately after the exit of Idle.

What I do is to cancel idle and then open a folder. I see that engine.state is still idle even if I exited Idle already. Keep in mind my code runs in a single thread so no concurrency is involved and Open cannot be called if imapConnection.Idle was still blocking the thread.

**Comment by jstedfast** [comment]
I'll need a small sample app that I can use to debug this.

**Comment by jstedfast** [comment]
Add some logging to `ImapClient.IdleAsync()` in the `ContinuationHandler` delegate block and also to the `IdleComplete()` method.

The `ContinuationHandler` is where the `Engine` state gets set to `Idle` and the `IdleComplete()` method is where the `Engine` state gets set back to `Selected`.

**Comment by ekalchev** [comment]
I was able to reproduce the issue using this test code

class Program
    {
        static void Main(string[] args)
        {
            Run().Wait();
        }

        private static async Task Run()
        {
            ImapClient client = new ImapClient();
            client.Connect("<your_url>");
            client.Authenticate("<user>", "<pass>");
            var folders = client.GetFolders(client.PersonalNamespaces[0]);
            var testFolder = folders[0];

            while (true)
            {
                CancellationTokenSource source = new CancellationTokenSource();

                await Task.Run(async () =>
                {
                    await Task.Delay(100);
                    source.Cancel();
                });

                client.Inbox.Open(MailKit.FolderAccess.ReadWrite);
                client.Idle(source.Token);
                testFolder.Open(MailKit.FolderAccess.ReadWrite);
            }
        }
    }

Note that I am running this against mail server in my local network and it is very fast. I believe this is timing issue, because it happens rarely. I'll try to give you more information about that.

**Comment by ekalchev** [comment]
Added some logging 

ContinuationHandler: imap.State = ImapEngineState.Idle
IdleComplete method entered
IdleComplete: ctx.Engine.State == ImapEngineState.Idle
IdleComplete: ctx.Engine.State = ImapEngineState.Selected
IdleComplete method exited
StepAsync method entered
StepAsync method entered
StepAsync method entered
ContinuationHandler: imap.State = ImapEngineState.Idle
IdleComplete method entered
IdleComplete: ctx.Engine.State == ImapEngineState.Idle
IdleComplete: ctx.Engine.State = ImapEngineState.Selected
IdleComplete method exited
StepAsync method entered
StepAsync method entered
StepAsync method entered
ContinuationHandler: imap.State = ImapEngineState.Idle
IdleComplete method entered
IdleComplete: ctx.Engine.State == ImapEngineState.Idle
IdleComplete: ctx.Engine.State = ImapEngineState.Selected
IdleComplete method exited
StepAsync method entered
StepAsync method entered
StepAsync method entered
ContinuationHandler: imap.State = ImapEngineState.Idle
IdleComplete method entered
IdleComplete: ctx.Engine.State == ImapEngineState.Idle
IdleComplete: ctx.Engine.State = ImapEngineState.Selected
IdleComplete method exited
StepAsync method entered
StepAsync method entered
StepAsync method entered
ContinuationHandler: imap.State = ImapEngineState.Idle
IdleComplete method entered
IdleComplete: ctx.Engine.State == ImapEngineState.Idle
IdleComplete: ctx.Engine.State = ImapEngineState.Selected
IdleComplete method exited
StepAsync method entered
StepAsync method entered
StepAsync method entered
ContinuationHandler: imap.State = ImapEngineState.Idle
IdleComplete method entered
IdleComplete: ctx.Engine.State == ImapEngineState.Idle
IdleComplete: ctx.Engine.State = ImapEngineState.Selected
IdleComplete method exited
StepAsync method entered
StepAsync method entered
StepAsync method entered
ContinuationHandler: imap.State = ImapEngineState.Idle
IdleComplete method entered
IdleComplete: ctx.Engine.State == ImapEngineState.Idle
StepAsync method entered <-- Here the exception is thrown

**Comment by ekalchev** [comment]
It is very easy to reproduce if you add Thread.Sleep here

                static async void IdleComplete (object state)
		{
            Console.WriteLine("IdleComplete method entered");
			var ctx = (ImapIdleContext) state;

			if (ctx.Engine.State == ImapEngineState.Idle) {
                Console.WriteLine("IdleComplete: ctx.Engine.State == ImapEngineState.Idle");
                var buf = Encoding.ASCII.GetBytes ("DONE\r\n");

				await ctx.Engine.Stream.WriteAsync (buf, 0, buf.Length, ctx.CancellationToken).ConfigureAwait (false);
				await ctx.Engine.Stream.FlushAsync (ctx.CancellationToken).ConfigureAwait (false);

                Thread.Sleep(1000);
				ctx.Engine.State = ImapEngineState.Selected;
                Console.WriteLine("IdleComplete: ctx.Engine.State = ImapEngineState.Selected");
            }
            Console.WriteLine("IdleComplete method exited");
        }

**Comment by jstedfast** [comment]
Try moving the state change to before the writes in the IdleComplete method.

**Comment by ekalchev** [comment]
I am moved the State setter code above the awaited calls and I don't see NullReferenceException anymore. However I see this

I believe this is not related the change I did, because I saw this before the change. It think this is different issue. This issue is reproducible with the test app above.

![image](https://user-images.githubusercontent.com/10009149/37652372-f2ffb8c8-2c43-11e8-99c4-cfda9c374589.png)

**Comment by ekalchev** [comment]
Here this log

C: A00000011 SELECT INBOX.temp-inbox (CONDSTORE)
S: * OK [CLOSED] Previous mailbox closed.
S: * FLAGS (\Answered \Flagged \Deleted \Seen \Draft $Forwarded)
S: * OK [PERMANENTFLAGS (\Answered \Flagged \Deleted \Seen \Draft $Forwarded \*)] Flags permitted.
S: * 2319 EXISTS
S: * 0 RECENT
S: * OK [UNSEEN 2] First unseen.
S: * OK [UIDVALIDITY 1491228504] UIDs valid
S: * OK [UIDNEXT 9283] Predicted next UID
S: * OK [HIGHESTMODSEQ 12] Highest
S: A00000011 OK [READ-WRITE] Select completed (0.015 + 0.000 + 0.014 secs).
C: A00000012 SELECT INBOX (CONDSTORE)
S: * OK [CLOSED] Previous mailbox closed.
S: * FLAGS (\Answered \Flagged \Deleted \Seen \Draft $Forwarded)
S: * OK [PERMANENTFLAGS (\Answered \Flagged \Deleted \Seen \Draft $Forwarded \*)] Flags permitted.
S: * 92 EXISTS
S: * 0 RECENT
S: * OK [UIDVALIDITY 1491227400] UIDs valid
S: * OK [UIDNEXT 107049] Predicted next UID
S: * OK [HIGHESTMODSEQ 30678] Highest
S: A00000012 OK [READ-WRITE] Select completed (0.002 + 0.000 + 0.001 secs).
C: A00000013 IDLE
S: + idling
S: A00000013 OK Idle completed (0.002 + 0.001 + 0.001 secs).
C: DONE
C: A00000014 SELECT INBOX.temp-inbox (CONDSTORE)
S: DONE BAD Error in IMAP command : Unknown command (1127685.302 + 0.000 secs).
S: * OK [CLOSED] Previous mailbox closed.
S: * FLAGS (\Answered \Flagged \Deleted \Seen \Draft $Forwarded)
S: * OK [PERMANENTFLAGS (\Answered \Flagged \Deleted \Seen \Draft $Forwarded \*)] Flags permitted.
S: * 2319 EXISTS
S: * 0 RECENT
S: * OK [UNSEEN 2] First unseen.
S: * OK [UIDVALIDITY 1491228504] UIDs valid
S: * OK [UIDNEXT 9283] Predicted next UID
S: * OK [HIGHESTMODSEQ 12] Highest
S: A00000014 OK [READ-WRITE] Select completed (0.010 + 0.000 + 0.009 secs).

**Comment by jstedfast** [comment]
Uhm, the `DONE` command is what terminates the IDLE command... why is the server saying BAD?

**Comment by jstedfast** [comment]
I've just updated the code a bit with an alternative fix. Can you test it to see if it works for you? Maybe it'll also fix your latest issue as well?

**Comment by ekalchev** [comment]
I am running the test app for a while and i don't get any exceptions

**Comment by jstedfast** [comment]
Awewsome :)
