### ISSUE TITLE
149.xxx.xxx.xxx is _my_ address

### ISSUE THREAD

**Issue by ovavadim** [jstedfast/MailKit#678]
Good day, dear collegues!

I'm trying to send email using SMTP-server, created by my collegue. I'm using .net core 2.0 this Identity.

When I run my application at debug-mode using my own computer -- it works perfectly.
When I run the same app on hosting it throws this exception:

SmtpCommandException: 149.xxx.xxx.xxx is _my_ address
MailKit.Net.Smtp.SmtpClient.OnSenderNotAccepted(MimeMessage message, MailboxAddress mailbox, SmtpResponse response)

the hosting and the smtp-server have the same IP-address and work at the same computer.
I'm sure, that exception of form "149.xxx.xxx.xxx is _my_ address" means, that smtp-server thinks, I'm spamer, trying to use its IP to be "whitelisted" -- and this server blocks me.

I've found this:

HELO is faked interface address
Type: forgery
Some spammers put the server's interface address they connect to in their HELO, maybe asuming it is whitelisted or something.
drop condition = ${if eq{[$interface_address]}{$sender_helo_name}}
     message   = $interface_address is _my_ address

But the same hosting has many other web-applications, they don't have a problem with connection to the local server. 

```csharp

public async Task SendEmailAsync(string email, string subject, string message)
        {
            var emailMessage = new MimeMessage();
            emailMessage.From.Add(new MailboxAddress("No reply", "XX@XXXX.XXX"));
            emailMessage.To.Add(new MailboxAddress("", email));
            emailMessage.Subject = subject;
            emailMessage.Body = new TextPart(MimeKit.Text.TextFormat.Html)
            {
                Text = message
            };

            using (var client = new SmtpClient())
            {               
                await client.ConnectAsync("localhost", 25, SecureSocketOptions.None);
                await client.AuthenticateAsync("XX@XXXX.XXX", "Password");
                
                await client.SendAsync(emailMessage);                

                await client.DisconnectAsync(true);
            }
        }

```

I tried to use its address instead of "localhost". But it throws the same exception.
What should I do? How to say a smtp-server that I'm not spamer, that I'm just physically situated on its IP-address, on the same computer?

**Comment by jstedfast** [comment]
You need to set the `client.LocalDomain` string to the value you want to use in the EHLO.

The SMTP server code that youy showed me shows that there's no way for MailKit to get this to work because of *course* it is going to use the same interface address in the EHLO, because that's what is being used! :)

**Comment by eriknuds** [comment]
Actually ovavadim, I think the server is trying to prevent a mail loop. I believe that was the original intention of the ehlo/helo domain string.
