### ISSUE TITLE
cancellation token does nothing

### ISSUE THREAD

**Issue by user94857** [jstedfast/MailKit#680]
Hey there, I was testing MailKit and I noticed the cancellation token doesn't work. Nothing happens when we use a cancellation token instead of the done token. Here's the code:

`
```
            _doneIdle = new CancellationTokenSource();
            _shutdownService = new CancellationTokenSource();
```
            _imapClient.Inbox.Open(FolderAccess.ReadWrite, _shutdownService.Token);

            _imapClient.IdleAsync(_doneIdle.Token, _shutdownService.Token).ContinueWith(task =>
            {
                switch (task.Status)
                {
                    case TaskStatus.RanToCompletion:
                        Console.WriteLine("RanToCompletion");
                        break;
                    case TaskStatus.Canceled:
                        Console.WriteLine("Cancelled");
                        break;
                    default:
                        break;
                }
             }, _shutdownService.Token);           
               
             _shutdownService.Cancel(true); // client continues to idle

             lock (_imapClient.SyncRoot)
             {
               _imapClient.Disconnect(true); //error imapclient busy processing a command in another thread
             }

`

am i missing something?

**Comment by jstedfast** [comment]
See the explanation here: https://github.com/jstedfast/MailKit/issues/374#issuecomment-233595125

**Comment by user94857** [comment]
thank you kindly!
