### ISSUE TITLE
Connection pooling

### ISSUE THREAD

**Issue by Niklas-Peter** [jstedfast/MailKit#681]
Does Mailkit internally use a SMTP connection pool or is really a new connection created per connect call?

**Comment by jstedfast** [comment]
It's really a new connection created per Connect() call.

**Comment by wasabii** [comment]
@jstedfast I would like to implement pooling, if possible, and am seeking your advise on it.

So, SmtpClient owns a connection. And it can multiplex. But is it inherently thread safe? Can multiple threads invoke Send at the same time? Or can Send be invoked multiple times from the same thread, and the result awaited on in a batch? What are the limitations here?

A cursory reading makes me think it should not be used from multiple threads. But that a single thread can multiplex stuff.

So I'm thinking of an object pool indexed by connection/auth information. With a SmtpClient returned and leased. But only for a single user at a time. And then returned to the pool when finished. And said pool leasing needs to do some smart checking to make sure it's still connected, authenticated, etc.

Does this seem right to you?

**Comment by jstedfast** [comment]
You are correct, it cannot be used from multiple threads.

I'm not sure it really makes sense to implement connection pooling *inside of* MailKit. I think it probably make sense to implement it *on top of* MailKit, but I'm curious to see what you come up with.

I would say that the connection string concept would probably work and I would recommend that it take the syntax of a URI: `smtp://user@mail.host.com:587/`

Are you planning to implement connection pooling for anything other than SMTP?

**Comment by wasabii** [comment]
Nope. Smtp is all I need for now.

That said, if it does belong in MailKit in sure you'd want it extendable to the other clients.

My biggest thing to think about right now is authentication methods. Some of these aren't easy to configure in a way that makes sense to be done by the pool.

**Comment by Poltuu** [comment]
Any update on this matter ? I'm looking to implement pooling as well, I'm curious to know if there was any already implemented solution out there.

**Comment by wasabii** [comment]
No. I dropped the project last year. Got pulled onto other things.

I think the general design idea is still sound though. I would have to go back and really take a close look at the ADO.NET design again, because the way they are doing it is probably sufficient.

The complicated auth methods are still and issue that need to be sorted.
