### ISSUE TITLE
Get the top EMAIL unique id

### ISSUE THREAD

**Issue by arn3342** [jstedfast/MailKit#682]
My inbox email count is 2035, but my last(top/newest) email's  unique id is 2110..Is there a way to get the top/last/newest email's uid without retrieveing the entire folder ?

**Comment by ekalchev** [comment]
Try this

imapFolder.Fetch(imapFolder.Count, -1...
imapFolder.Fetch(imapFolder.Count - 1, -1...

**Comment by arn3342** [comment]
i tried it as follows

var summury = folder.fetch(folder.count - 1, -1, MessageSummaryItems.FUll);
    foreach (var sum in summary)
    {
    }

But it doesnt work :( It returns 0

**Comment by arn3342** [comment]
Ok i got that to work a bit but it returns 3709 whereas my last mai id is 3801 ... why ??

**Comment by arn3342** [comment]
okey fixed it :)

**Comment by jstedfast** [comment]
If all you want is the UID of the most recent message in the folder, there's a few ways to do that.

As @ekalchev illustrated, you can do that using the Fetch() method:

```csharp
var summary = folder.fetch (folder.Count - 1, folder.Count, MessageSummaryItems.UniqueId).FirstOrDefault ();
var latestUid = summary?.UniqueId;
```

Note above that you need to pass `MessageSummaryItems.UniqueId` to the Fetch() method.

Another way is to use the Search() method:

```csharp
var all = folder.Search (SearchQuery.All);
var latestUid = all[all.Count - 1];
```

If your server supports `ImapCapabilities.SearchResults`, you can use the following approach:

```csharp
var results = folder.Search (SearchOptions.Max, SearchQuery.All);
var latestUid = results.Max.Value;
```

My recommendation would be to use the Fetch() method as I think it'll be cheaper for the server to calculate *and* return a minimum amount of data over the network connection (technically, the SearchResults option is less network traffic, but fewer servers will support this feature and the ones that do might not implement it as efficiently as it could be done).
