### ISSUE TITLE
DeliverAfter returns messages that before the last sync date.

### ISSUE THREAD

**Issue by AhmedElbatt** [jstedfast/MailKit#683]
I am trying to filter out the messages by using Deliever after method like the following:

```
   if (inbox.IncomingEmailSettings.EmailProtocol == EmailProtocol.IMAP)
            {
                client = new ImapClient();
            }
         using (client)
            {
                client.Connect(inbox.IncomingEmailSettings.HostName, inbox.IncomingEmailSettings.PortNumber, inbox.IncomingEmailSettings.SslSecured);
                client.Authenticate(inbox.Email, inbox.Password);
                var folder = client.Inbox;
                folder.Open(FolderAccess.ReadOnly);
                if (inbox.LastSyncAt == null)
                {
                    uids = client.Inbox.Search(SearchQuery.All);
                }
                else
                {
                    var query = SearchQuery.DeliveredAfter(inbox.LastSyncAt.Value);
                    uids = client.Inbox.Search(query);
                }

                foreach (var item in uids)
                {
                    var message = folder.GetMessage(item);
                        messageList.Add(message);

                }

            }
```
The method returns data that is not appropriate because it is before the last sync data value ?
Any suggestions to solve this issue.

**Comment by jstedfast** [comment]
Use the DeliveredAfter search query and then manually filter out the ones before the last-sync date?

**Comment by AhmedElbatt** [comment]
Do you mean something like that ?
var query = SearchQuery.DeliveredAfter((DateTime)inbox.LastSyncAt.Value);

             foreach (var item in uids)
                {
                    var message = folder.GetMessage(item);
                    if (inbox.LastSyncAt == null)
                    {
                        messageList.Add(message);
                    }
                    else
                    {
                        if (DateTime.Compare(message.Date.DateTime, inbox.LastSyncAt.Value) > 0)
                        {
                            messageList.Add(message);
                        }
                    }
                }

**Comment by jstedfast** [comment]
Almost. `message.Date` is the Sent date, not the Received date.

The received date can be obtained via the `Fetch()` method if you pass in the `MessageSummaryItems.InternalDate` flag which will allow you to check the `InternalDate` property on the `IMessageSummary`.
