### ISSUE TITLE
E-mails do not save in the sent folder. [Question]

### ISSUE THREAD

**Issue by DawidMusialik** [jstedfast/MailKit#684]
Hello. I use MailKit in my application.
When testing using google mail, I did not have any problems.

However, in the final version I will use the linuxpl.com mail client.
The application correctly sends e-mails from linuxpl.com mail, however it does not save them to the folder sent to linuxpl.com.
```
        using (clientSMTPTwo)
                {
                    clientSMTPTwo.ServerCertificateValidationCallback = (s, c, h, e) => true;
                    await clientSMTPTwo.ConnectAsync(_emailConfigurationToClient.mailSMTPAdres, _emailConfigurationToClient.mailSMTPPort, SecureSocketOptions.SslOnConnect);
                    //clientSMTPOne.AuthenticationMechanisms.Remove("XOAUTH2");
                    await clientSMTPTwo.AuthenticateAsync(_emailConfigurationToClient.mailAdres, _emailConfigurationToClient.mailPassword);
                    await clientSMTPTwo.SendAsync(emailSendTwo);
                    await clientSMTPTwo.DisconnectAsync(true);
                }
```

Mail settings are:
SMTP Port - I tested port 465 and 587.
SMTP Address - s52.linuxpl.com

This is what the message looks like:
```
            //emailSendTwo - MimeMessage
            //emailElementsTwo - Multipart
            emailSendTwo.From.Add(new MailboxAddress(_emailConfigurationToClient.mailName, _emailConfigurationToClient.mailAdres));
            emailSendTwo.To.Add(new MailboxAddress(_emailMessageTwo.mailNameTo, _emailMessageTwo.mailAdresTo));
            emailSendTwo.Subject = _emailMessageTwo.mailSubject;
            emailSendTwo.Body = emailElementsTwo;
```

I would like to ask if the fault is on my side because I configured MailKit incorrectly (Google worked) or on the linuxcom.pl website?

Thanks!

**Comment by jstedfast** [comment]
Well, when you send a message via SMTP, it doesn't get appended to any Sent folder. That's up to you to do using the IMAP protocol.

If it works in GMail, it's a bonus feature that GMail apparently implements, but it's not a standard feature.

Hope that helps.

**Comment by DawidMusialik** [comment]
jstedfast, thanks for the answer. I solved the problem. For an amateur like me, it would be useful to write in the documentation as an example of writing an email to the posted directory.

Thanks for your work on MailKit !!!
