### ISSUE TITLE
Unable send email using corporate SMTP

### ISSUE THREAD

**Issue by abhaydhar** [jstedfast/MailKit#686]
To help me debug your issue, please explain:
- What were you trying to do? send email using MailKit in asp.net core application
- What happened? error - Client was not authenticated error code 5.7.1
- What did you expect to happen? email should be sent, but email sending behaviour is erratic, as there were a few instance earlier when we were able to send email , not able to replicate the success send operation
- Step-by-step reproduction instructions and/or a simple test case.

If you got an exception, please include the exception Message *and* StackTrace.
AuthenticationInvalidCredentials: 5.7.3 Authentication unsuccessful

at MailKit.Net.Smtp.SmtpClient.Authenticate(Encoding encoding, ICredentials credentials, CancellationToken cancellationToken) at MailKit.MailService.Authenticate(String userName, String password, CancellationToken cancellationToken) at 

Please also INCLUDE A PROTOCOL LOG (scrubbed of any authentication data), especially
if you got an exception such as `Syntax error in XYZ. Unexpected token: ...`.
If you do not include the protocol log, you will make me VERY UNHAPPY.
Connected to smtp://<IP>:25/?starttls=when-available
S: 220 <Server_REDACTED>.<DOMAIN_REDACTED>.COM Microsoft ESMTP MAIL Service ready at Tue, 27 Mar 2018 03:22:42 -0400
C: EHLO [10.207.8.74]
S: 250-<Server_REDACTED>.<DOMAIN_REDACTED>.COM Hello [10.207.8.74]
S: 250-SIZE
S: 250-PIPELINING
S: 250-DSN
S: 250-ENHANCEDSTATUSCODES
S: 250-STARTTLS
S: 250-X-ANONYMOUSTLS
S: 250-AUTH NTLM
S: 250-X-EXPS GSSAPI NTLM
S: 250-8BITMIME
S: 250-BINARYMIME
S: 250-CHUNKING
S: 250-XEXCH50
S: 250-XRDST
S: 250 XSHADOW
C: STARTTLS
S: 220 2.0.0 SMTP server ready
C: EHLO [10.207.8.74]
S: 250-<Server_REDACTED>.<DOMAIN_REDACTED>.COM Hello [10.207.8.74]
S: 250-SIZE
S: 250-PIPELINING
S: 250-DSN
S: 250-ENHANCEDSTATUSCODES
S: 250-AUTH NTLM LOGIN
S: 250-X-EXPS GSSAPI NTLM
S: 250-8BITMIME
S: 250-BINARYMIME
S: 250-CHUNKING
S: 250-XEXCH50
S: 250-XRDST
S: 250 XSHADOW
C: AUTH LOGIN
S: 334 VXNlcm5hbWU6
C: <>REDACTED==
S: 334 UGFzc3dvcmQ6
C: <REDACTED>
S: 535 5.7.3 Authentication unsuccessful
Without a protocol log, I CANNOT fix the issue. I will simply close the bug report.

To get a protocol log, follow one of the following code snippets:

```csharp
// log to a file called 'imap.log'
var client = new ImapClient (new ProtocolLogger ("imap.log"));
```

```csharp
// log to a file called 'pop3.log'
var client = new Pop3Client (new ProtocolLogger ("pop3.log"));
```

```csharp
// log to a file called 'smtp.log'
var client = new SmtpClient (new ProtocolLogger ("smtp.log"));
```

Note: if the protocol log contains sensitive information, feel free to email it to me at
jestedfa@microsoft.com instead of including it in the GitHub issue.

**Comment by XceSx6** [comment]
Dear  abhaydhar,

I am stuck at the Authenticate, as it is throwing the same AuthenticationChallenge after AUTH LOGIN.
Would you be willing to provide some sample code on how to go about this ?

I am doing:
MailClient.Connect(Server, Port, None)
MailClient.Authenticate(Username, Password)
 >> Here it throws the AuthenticationChallenge


Kind regards

**Comment by abhaydhar** [comment]
Hi XceSx6,
I am facing the issue currently , for which i have raised this issue. Nevertheless , below is the code piece

using (var client = new SmtpClient())
{
    client.Connect(EmailConfiguration.SmtpServer, EmailConfiguration.SmtpPort, EmailConfiguration.UseSsl);

    if (EmailConfiguration.RequiresAuthentication)
    {
        client.Authenticate(EmailConfiguration.Username, EmailConfiguration.Password);
    }

    //TODO: Only Send if PROD
    client.Send(message);
    client.Disconnect(true);
}

return true;
}

https://stackoverflow.com/questions/49485336/weird-issue-in-dotnet-core-website-using-mailkit-to-send-email?noredirect=1#comment85982412_49485336

**Comment by jstedfast** [comment]
Looks like you are sending an empty string as a password.

If you don't have a password, don't call Authenticate().

**Comment by abhaydhar** [comment]
No. I am sending a password , the Protocol logger log file generated contained the base64 encoded passowrd and i debugged the application and can confirm the password is passed to MailKit.

**Comment by jstedfast** [comment]
And did the password that you provided to MailKit match the base64 decoded password string?

**Comment by jstedfast** [comment]
There are 3 possibilities:

1. You used the wrong password.
2. Your server is broken, not MailKit's fault.
3. Your server is expecting the password string to be in a charset other than UTF-8 which means you need to specify that System.Text.Encoding to MailKit in the Authenticate() method (use the override that allows you to specify an Encoding).

**Comment by jstedfast** [comment]
I closed the bug because I am 100% sure that the problem is not a bug in MailKit.
