### ISSUE TITLE
Question: SMTP Exhange AuthenticationChallenge

### ISSUE THREAD

**Issue by XceSx6** [jstedfast/MailKit#687]
Dear Dev,

After MailClient.Connect(Server, Port, None) ..
At MailClient.Authenticate(Username, Password) it throws the error:
"A call to Authenticate failed with this message: AuthenticationChallange: someBase64string"

However I am not yet knowledgeable in how to go about this.
How to Handle a challenge? I have not yet come across some Example code.

Would you be so kind as to point me in the right direction?

Keep up the good work!
Kind regards

**Comment by jstedfast** [comment]
That error means that you are not sending the correct password.
