### ISSUE TITLE
Unilateral response during GetStream or GetStreams

### ISSUE THREAD

**Issue by ekalchev** [jstedfast/MailKit#688]
Is there a mechanism to capture unilateral IMAP responses during GetStream or GetStreams methods. 

P.S. Actually I can see MessageFlagChanged event is raised for unilateral responses for GetStream or GetStreams, however MessageFlagChanged is not raised when you receive unilateral response for Fetch. 

Can you confirm this is how it is supposed to work?

**Comment by jstedfast** [comment]
That is how it is supposed to work.

It's very difficult (impossible?) to determine what FETCH responses are what when you issue a FETCH request, so that data is always returned in the FETCH response.
