### ISSUE TITLE
Old SyncRoot Property documentation?

### ISSUE THREAD

**Issue by bender2k14** [jstedfast/MailKit#689]
In [this SO answer](https://stackoverflow.com/questions/29222413/thread-safe-getfolder-using-mailkit), you say
> As of the 2.0 release, the Async methods no longer do any locking for you. You will have to do it yourself.

but the documentation of [`ImapClient.SyncRoot` Property](http://www.mimekit.net/docs/html/P_MailKit_Net_Imap_ImapClient_SyncRoot.htm) says
> When using the non-Async methods from multiple threads, it is important to lock the SyncRoot object for thread safety when using the synchronous methods.

which I understand to mean that it is _not_ important to synchronize `async` method calls.

Which of these is correct?  Was the `ImapClient.SyncRoot` Property documentation not updated to match the new behavior?

**Comment by jstedfast** [comment]
The documentation was just not updated. You always need to synchronize your calls for both sync and async.

**Comment by jstedfast** [comment]
Technically, the docs are still correct in the sense that you can't lock around async calls anyway.

**Comment by bender2k14** [comment]
Thanks very much for the classification and correction.

While it is true that the body of a [lock statement](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/lock-statement) cannot be asynchronous, it is still possible to achieve this behavior in other ways.  I prefer to use [`Nito.AsyncEx.AsyncLock.LockAsync`](https://github.com/StephenCleary/AsyncEx/wiki/AsyncLock).

Excellent tools you have here with MailKit and MimeKit.  Keep up the great work! :)

**Comment by jstedfast** [comment]
I'll have to look into that Nito library, sounds really useful. Thanks for the link :)

And you're welcome :)

**Comment by bender2k14** [comment]
Glad to help.

The author of that library is Stephen Cleary ([blog](https://blog.stephencleary.com/)) who also wrote [Concurrency in C# Cookbook: Asynchronous, Parallel, and Multithreaded Programming](https://www.amazon.com/Concurrency-Cookbook-Asynchronous-Multithreaded-Programming/dp/1449367569).  In a world with too much to learn, I always take his advice about how to properly write asynchronous code.
