### ISSUE TITLE
Possible issue with .Net Standard 2.0 NuGet Package

### ISSUE THREAD

**Issue by Rgenware** [jstedfast/MailKit#691]
I've been trying to get MailKit working in a .Net Standard 2.0 library. Everything compiles but I get this error as soon as the code attempts to instantiate a new ImapClient. 

System.IO.FileNotFoundException: 'Could not load file or assembly 'MimeKit, Version=2.0.0.0, Culture=neutral, PublicKeyToken=bede1c8a46c66814' or one of its dependencies. The system cannot find the file specified.'

Just in case there was something wrong with my project, I created a new project(.Net Standard 2.0 library). I added MailKit  via NuGet and then added the below code. Then attempted to instantiate ImapClientTest. I got the same error.

Public Class ImapClientTest
    Private Imap As ImapClient
    Sub New()
        Imap = New ImapClient
    End Sub
End Class

Thanks for your help and I apologize if I've missed something simple.

**Comment by jstedfast** [comment]
I gather that you have resolved this issue?

**Comment by Rgenware** [comment]
Yes, sorry I got a head of myself, it doesn't seem to be a problem

**Comment by R2D221** [comment]
So... how did you solve it?

**Comment by jrb9249** [comment]
We resolved this issue by **installing the Mailkit nuget package on the startup project** (actually, we installed on all projects in solution). Still not sure what was causing it though.
