### ISSUE TITLE
Multimailbox ESEARCH

### ISSUE THREAD

**Issue by ekalchev** [jstedfast/MailKit#692]
I can see Mailkit support ESEARCH extensions but does it support https://tools.ietf.org/html/rfc6237?

I don't see anything in the source related to this. Are there plans to support this?

**Comment by jstedfast** [comment]
Does your server support it?

**Comment by ekalchev** [comment]
I thought all servers with ESEARCH capability support it?

**Comment by jstedfast** [comment]
Nope. Your server needs to support the MULTISEARCH extension.

```
A server that
   supports this extension includes "MULTISEARCH" in its IMAP capability
   string.
```

The `ESEARCH` extension that MailKit supports is defined by this specification: ttps://tools.ietf.org/html/rfc4731

The `MULTISEARCH` extends the `ESEARCH` extension that is defined in rfc4731, but not all servers that support `ESEARCH` support ` MULTISEARCH`. In fact, I have not found a single server that supports `MULTISEARCH` but apparently the Oracle 8.0 IMAP server supports it (and looks to be the only one that does): https://imapwiki.org/Specs

**Comment by ekalchev** [comment]
No, my server doesn't support it. I guess if it is that rare it not worth supporting that.

**Comment by jstedfast** [comment]
It would be nice if it was more widely supported, but yea, that was my thinking as well ;-)
