### ISSUE TITLE
When does IMailFolder.Append return null?

### ISSUE THREAD

**Issue by bender2k14** [jstedfast/MailKit#693]
The family of [`IMailFolder.Append` methods](https://github.com/jstedfast/MailKit/wiki/Overload_MailKit_IMailFolder_Append) have the return type `UniqueId?` (or an `IList<>` of that).  For these return values, the documentation says
> The UID of the appended message, if available; otherwise, null.

Would you mind elaborating a bit here about this "if available" business?  For what sorts of reasons would these methods return `null`?

**Comment by jstedfast** [comment]
If the IMAP server does not support the UIDPLUS extension, then the return value will always be null.

Theoretically, if the server supports UIDPLUS, then it should always return a valid UniqueId... but as we all know, theory and reality can vary greatly.

**Comment by bender2k14** [comment]
I see.  Thanks for that explanation.

Suppose we appending a single `MimeMessage`.  How would you recommend following up a call to `Append` in order to obtain the `UniqueId` of the just appended `MimeMessage`?

**Comment by jstedfast** [comment]
probably something along the lines of:

```csharp
var uids = folder.Search (SearchQuery.HeaderContains ("Message-Id", message.MessageId));
var appendedUid = uids[uids.Length - 1];
```

**Comment by xnevz** [comment]
@jstedfast, just a small thing!
`Search` method returns `IList<UniqueId>` so you should use `Count` instead of `Length`, 😉

**Comment by jstedfast** [comment]
Ah, thanks, I've updated the code in my previous comment.
