### ISSUE TITLE
A call to SSPI failed, see inner exception.

### ISSUE THREAD

**Issue by roshanghangare7** [jstedfast/MailKit#694]
I am using mailkit version 1.12.0 to get unread mail count.
Please find below code
	public int GetUnreadMailCountFromInbox()
		{
			using (var client = new ImapClient())
			{
				client.ServerCertificateValidationCallback = (s, c, h, e) => true;
				client.Connect(host, port, false);
				client.Authenticate(user, password);

				var inbox = client.Inbox;
				inbox.Open(FolderAccess.ReadOnly);
				var unreadMailcount = inbox.Unread;
				client.Disconnect(true);
				return unreadMailcount;
			}
		}

I am getting below exception during this method call,
A call to SSPI failed, see inner exception.
- System.Net.Security.SslState.StartSendAuthResetSignal(ProtocolToken message, AsyncProtocolRequest asyncRequest, Exception exception) (0, 0)
- System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest) (0, 0)
- System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest) (0, 0)
- System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest) (0, 0)
- System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest) (0, 0)
- System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest) (0, 0)
- System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest) (0, 0)
- System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest) (0, 0)
- System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest) (0, 0)
- System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest) (0, 0)
- System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest) (0, 0)
- System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest) (0, 0)
- System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest) (0, 0)
- System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest) (0, 0)
- System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest) (0, 0)
- System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest) (0, 0)
- System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest) (0, 0)
- System.Net.Security.SslState.ForceAuthentication(Boolean receiveFirst, Byte[] buffer, AsyncProtocolRequest asyncRequest) (0, 0)
- System.Net.Security.SslState.ProcessAuthentication(LazyAsyncResult lazyResult) (0, 0)
- MailKit.Net.Imap.ImapClient.Connect(String host, Int32 port, SecureSocketOptions options, CancellationToken cancellationToken) (0, 0)
- MailKit.MailService.Connect(String host, Int32 port, Boolean useSsl, CancellationToken cancellationToken) (0, 0)
- MyProject.Utils.ImapMailClient.GetUnreadMailCount() (0, 0)

The message received was unexpected or badly formatted

**Comment by jstedfast** [comment]
Use `client.Connect(host, port, SecureSocketOpotions.None);`
