### ISSUE TITLE
Not possible to install nuget package (".NETPortable,Version=v4.5,...)

### ISSUE THREAD

**Issue by EmJay1171** [jstedfast/MailKit#698]
Hello,

I am a newbie in creating apps  and I am developing an Xamarin pcl app and I have to create an app which receives and sends emails. 
Now I tried toinstall MailKit, but I allways get the following error:

Schweregrad	Code	Beschreibung	Projekt	Datei	Zeile	Unterdrückungszustand
Fehler		Das Paket "MailKit 2.0.2" konnte nicht installiert werden. Sie versuchen, dieses Paket in ein Projekt zu installieren, das sich auf ".NETPortable,Version=v4.5,Profile=Profile259" bezieht, das Paket enthält aber keine Assemblyverweise oder Inhaltsdateien, die mit diesem Framework kompatibel sind. Wenden Sie sich an den Paketersteller, um weitere Informationen zu erhalten.			0	

I am not sure what I have to change in my app to make it work .... 

Thanks for your help,

Emjay1171

**Comment by jstedfast** [comment]
I would recommend avoiding PCL and opt for .NET Core instead. PCL will be a nightmare to use if you are new to using it.

**Comment by EmJay1171** [comment]
Thanks for you help :-)
