### ISSUE TITLE
Check if mail has attachments

### ISSUE THREAD

**Issue by arn3342** [jstedfast/MailKit#703]
I am using the below code to get different parts of a message such as "To" , "CC" ...

      var message = `folder.GetMessage(LstUID);
      string` From = `message.From.ToString();

Now, i was wondering how i could check if a mail contains attachments or not ? I found the below code on StackOverFlow but i fail to combine it with my existing code :(

     var summary = inbox.Fetch(MessageId,MessageSummaryItems.Body,cancel.Token).FirstOrDefault();  
     var bodyMultiPart = summary.Body as BodyPartMultipart;
     if (bodyMultiPart != null)
     {
     foreach (var bodyPart in bodyMultiPart.BodyParts.Where(x => x is BodyPartBasic))
    {
        BodyPartBasic basicPart = bodyPart as BodyPartBasic;
        if (basicPart.ContentDisposition != null && basicPart.ContentDisposition.IsAttachment)
        {
           //add basic part as attachment
        }               
    }    
    }

**Comment by jstedfast** [comment]
If you are calling `GetMessage()`, then you could just check `message.Attachments.Any()`
