### ISSUE TITLE
Default created EHLO/HELO domain (when not using SmtpClient.LocalDomain Property) is not always valid according to protocol

### ISSUE THREAD

**Issue by eriknuds** [jstedfast/MailKit#704]
Protocol log documenting the bug:
***
Connected to smtp://smtp.somewhere.com:25/?starttls=when-available
S: 220 smtp.somewhere.com Microsoft ESMTP MAIL Service, Version: 8.0.9200.16384 ready at  Mon, 7 May 2018 13:53:31 +0200 
C: EHLO [IPv6:::ffff:10.0.4.47]
S: 501 5.5.4 Invalid Address
C: HELO [IPv6:::ffff:10.0.4.47]
S: 501 5.5.4 Invalid Address
***

I have not set the SmtpClient.LocalDomain Property, assuming MailKit will use a valid default. However the value is not a valid IPv6, IPv4 or FQDN, causing the (arguably quite strict) server to deny the transaction. This server, I guess, I configured with the -RequireEHLODomain = true:
***
Set-ReceiveConnector <Receive Connector Name> -RequireEHLODomain <$true | $false>
***

I can however not affect this server configuration, so I have to make sure the domain is valid or not sent with the EHLO (which this server accepts fine, but is not possible with mailKit as I read the code in the current version of MailKit/Net/Smtp/SmtpClient.cs).

That is, in addtion to the domain being created by default is sometimes invalid, there seem to be no way to specify that no EHLO domain should be used, which are usually allowed and valid. Setting the SmtpClient.LocalDomain Property to blank will trigger the default behavior (which is as the protocol log demonstrates not always correct).

I can implement settings for my client to specify a valid FQDN, or detect an IP address and make sure it is valid and specify this using the SmtpClient.LocalDomain Property, but I believe the default value used by mailkit should be valid, and that I have found a bug here. Also I think it is a significant enough problem that I can't optionally choose not to send a domain with the EHLO command, even though I guess that particular issue is more of a feature request than a bug report.

**Comment by eriknuds** [comment]
More info - the failing session used a proxy, and the proxy socket given to mailkit seem to use IPv6. This can however happen in other instances where the target SMTP server has an IPv6 address, it seems from the current MailKit source code. Creating the socket with AddressFamily.InterNetwork before giving it to MailKit seem to resolve he issue, but is not an IPv6 compatible work around.

**Comment by jstedfast** [comment]
Would adding this be sufficient?

```csharp
if (ip.IsIPv4MappedToIPv6)
    ip = ip.MapToIPv4 ();
```

**Comment by jstedfast** [comment]
Based on the SMTP specification, it seems to me that the IPv6 address literal that MailKit is using is correct. Am I reading or understanding something badly?

**Comment by eriknuds** [comment]
You are right, I thought at first it was invalid but it seems to be valid mixed notation IPv6. I will do some more testing to get a clearer picture of why this SMTP server will not accept this string and get back to the issue.

**Comment by jstedfast** [comment]
ok, sounds good. I also can't find anywhere in the spec that says no argument to EHLO or HELO is acceptable.

That seems like a hack for a particular SMTP server that is not universally standardized anywhere.

**Comment by eriknuds** [comment]
Hi again, I haven't had a chance to check on that particular strict server yet regarding the literal IP format, but in reply to having no argument to the HELO/EHLO command the RFC says SHOULD, not MUST, and this particular strict (Exchange) SMTP server at least confirms to this, allowing an empty EHLO which I tested earlier using telnet.

From RFC2821:

These commands are used to identify the SMTP client to the SMTP server. The argument field contains the fully-qualified domain name of the SMTP client if one is available. In situations in which the SMTP client system does not have a meaningful domain name (e.g., when its address is dynamically allocated and no reverse mapping record is available), the client SHOULD send an address literal (see section 4.1.3), optionally followed by information that will help to identify the client system. The SMTP server identifies itself to the SMTP client in the connection greeting reply and in the response to this command.

BTW, thanks for the quick responses and the help so far, as well as for creating and maintaining this excellent piece of software:-) MimeKit/MailKit is some of the most well designed, flexible, well written, well maintained, best and most stable software libraries I've ever used, free or commercial.

**Comment by eriknuds** [comment]
I've experimented with the server now, it seems it just don't like IPv6 literals. But it works fine when I bind specifically to an IPv4 socket so MailKit sends an IPv4 literal in the EHLO command. So I will do that for now. But if you add your suggested:
***
if (ip.IsIPv4MappedToIPv6)
    ip = ip.MapToIPv4 ();
***
...then it would have worked out of the box, and wouldn't have required me to only support IPv4 proxy connections, so I think this is a good idea anyway, nothing wrong with using an IPv4 literal when it is really an IPv4 socket being used, and IPv4 is definitely more universally accepted still.

This particular SMTP server is an Exchange server owned by a rather well known (at least here) SAAS and hosting company and used by one of their clients, so it's not some weird software some hobbyist built and configured haphazardly. 

Thanks for all this, and I hope you will include your clever fix in a later release:-)

**Comment by jstedfast** [comment]
Cool, glad that worked. I'll add that work-around.

**Comment by jstedfast** [comment]
Fix added. I won't be able to make another release for another 2 weeks or so, but when I get back, I will.

**Comment by eriknuds** [comment]
Thanks, I have no problem waiting:-) Excellent work and attention:-)
