### ISSUE TITLE
Automatically set the date in the WriteTo method

### ISSUE THREAD

**Issue by NZ-Jaybird** [jstedfast/MailKit#710]
Hi Jeffrey

- Situation: Save email to file using WriteTo
- Actual behaviour: File does not include Date header
- Expected behaviour: Date should be set to current timestamp and included in the output
- Steps: (1) Create new MimeMessage using CreateFromMailMessage (2) WriteTo file

Since I'm not sending the mail over a particular protocol, I guess there's nothing to log, please advise if protocol log is still required.

Note that if I manually set the timestamp before calling WriteTo then it is output.

Also, just wondering if it's possible to omit the day in the Date output as the .NET SmtpClient doesn't include the "Wed, " part when writing the date.

Thank you

Jonathan

**Comment by jstedfast** [comment]
The day string is part of the email standard.

Anyway, turns out this is only an issue with CreateFromMailMessage. Creating a new MimeMessage using MimeKit API's sets the Date header.

**Comment by NZ-Jaybird** [comment]
That makes sense. I was going to add that I since tried to send the email
with MimeKits SmtpClient and noticed the Date header was also not present
(also from the CreateFromMailMessage). Thanks for looking into it!

**Comment by jstedfast** [comment]
No problem :)
