### ISSUE TITLE
Authentication failed for  partner.outlook.cn:993   use imap

### ISSUE THREAD

**Issue by zousq19910623** [jstedfast/MailKit#711]
this is the log:

Connected to imaps://partner.outlook.cn:993/
S: * OK The Microsoft Exchange IMAP4 service is ready. [UwBIADIAUABSADAAMQBDAEEAMAAzADkALgBDAEgATgBQAFIAMAAxAC4AcAByAG8AZAAuAHAAYQByAHQAbgBlAHIALgBvAHUAdABsAG8AbwBrAC4AYwBuAA==]
C: A00000000 CAPABILITY
S: * CAPABILITY IMAP4 IMAP4rev1 AUTH=PLAIN AUTH=XOAUTH2 SASL-IR UIDPLUS ID UNSELECT CHILDREN IDLE NAMESPACE LITERAL+
S: A00000000 OK CAPABILITY completed.
C: A00000001 AUTHENTICATE PLAIN AEhSLVJlc3VtZXNAYW1yZXN0LmFzaWEAMTExMTEx
S: A00000001 NO AUTHENTICATE failed.
C: A00000002 LOGIN HR-Resumes@amrest.asia 111111
S: A00000002 NO LOGIN failed.
C: A00000003 LOGOUT
S: * BYE Microsoft Exchange Server IMAP4 server signing off.
S: A00000003 OK LOGOUT completed.
c3VtZXNAYW1yZXN0LmFzaWEAMTExMTEx
S: A00000003 NO AUTHENTICATE failed.
C: A00000004 LOGIN HR-Resumes@amrest.asia 111111
S: A00000004 NO LOGIN failed.
C: A00000005 LOGOUT
S: * BYE Microsoft Exchange Server IMAP4 server signing off.
S: A00000005 OK LOGOUT completed.

how to solve this problem??
why turn out this error??

**Comment by zousq19910623** [comment]
if anyone knows ,pls tell me ,thx.

**Comment by zousq19910623** [comment]
i already try to change the password,but still throw this exception：MailKit.Security.AuthenticationException: LOGIN failed.

**Comment by jstedfast** [comment]
It's failing because you are giving it the wrong user name or the wrong password.
