### ISSUE TITLE
Parsing MimeMessage using MailKit/MimeKit c#

### ISSUE THREAD

**Issue by arn3342** [jstedfast/MailKit#712]
I have the following code 

    MailKit.IMailFolder Folder = GetFolder(MailKit.SpecialFolder.Sent);
    var Message = Folder.GetMessage(MailKit.UniqueId.Parse(UID));
    string emlPath = myPathHere;
    Message.WriteTo(emlPath);

Now, my scenario is that, i need to remove the images from the mime-message. For this, i know that i may need to remove all < img > tags and the items/strings in between(Correct me if i am wrong). Is there a way that i can parse the message in code, get it as a string(or array of string) and run necessary operations(like regex) to remove the <img> tags and others and finally save it to disk? Any help would be appreciated :)

**Comment by arn3342** [comment]
Never mind, i solved it :)

**Comment by jstedfast** [comment]
You should just be able to walk the MIME structure of the parsed message (probably via the MimeVIsitor API) and remove them and then use the `HtmlToHtml` to fix up any of the img tags.

For an example on how to use the HtmlToHtml converter, check out the code in the HtmlPreviewVisitor at https://github.com/jstedfast/MimeKit/blob/master/FAQ.md#q-how-do-i-tell-if-a-message-has-attachments (specifically, see the HtmlTagCallback method and how it gets used).

You really don't want to use regex.

Hope that helps.

**Comment by pankajmahanta** [comment]
Can I parse a mail chain ? Means is it possible to separate each mail from a mailchain @jstedfast

**Comment by jstedfast** [comment]
@pankajmahanta I'm not sure what you mean by a mail chain.

Are you asking if it can parse an mbox-formatted mailbox file/stream with multiple messages? Yes.

**Comment by pankajmahanta** [comment]
@jstedfast Actually I am trying to retrieve all replies mail separate from previous mail, I trying with MimeMessage . I am  getting text body of replies , But if i am in CC or BCC ,then I unable to retrieve text body . I have added my code .
                        var mailFolder = client.GetFolder("Inbox", cancel.Token);
                        mailFolder.Open(FolderAccess.ReadWrite);
                        var query = SearchQuery.SubjectContains("Upcoming UAT for CL");
                        var uids = mailFolder.Search(query);
                            ArrayList messages = new ArrayList();

                            foreach (var uid in uids)
                            {
                                var msg = mailFolder.GetMessage(uid, cancel.Token, null);
                                messages.Add(msg.TextBody);
                            }
                         
                            Console.WriteLine(messages);

                            Console.ReadKey();

**Comment by jstedfast** [comment]
What's wrong with your current code? I still don't understand what you are trying to accomplish.

Your code above is getting individual message replies, just like you said you wanted. Right? How is that not what you want?
