### ISSUE TITLE
Xamarin iOS - access shared inbox

### ISSUE THREAD

**Issue by SarathyEST** [jstedfast/MailKit#714]
I am using this in my VS for MAC - to build a iOS application which needs to read a shared mailbix in an exchange or office 365 server. How can I force the code to change from default inbox to access shared inbox folder?

**Comment by jstedfast** [comment]
What you need to do is:

```csharp
await client.ConnectAsync("outlook.office365.com", 993, SecureSocketOptions.SslOnConnect);
await client.AuthenticateAsync(@"username@yourdomain.com\sharedmailbox", "userpassword");
```
