### ISSUE TITLE
AuthenticationException being thrown for non-authentication issues?

### ISSUE THREAD

**Issue by oatsoda** [jstedfast/MailKit#717]
I am using the AuthenticationException to track when I think that the credentials are wrong, assuming that it would only throw when the SMTP Response Code are `SmtpStatusCode.AuthenticationInvalidCredentials` etc. but it seems that in actual fact this exception type can be thrown for any failure - is this correct?

Looking at the code *all* errors are thrown as an AuthenticationException:
https://github.com/jstedfast/MailKit/blob/6d21ecd036da8d46eb17716c5e320737a79cc930/MailKit/Net/Smtp/SmtpClient.cs#L733-L738

The description suggests otherwise:
https://github.com/jstedfast/MailKit/blob/6d21ecd036da8d46eb17716c5e320737a79cc930/MailKit/Net/Smtp/SmtpClient.cs#L636-L638

I believe that I am getting AuthenticationExceptions with messages such as:
> ServiceNotAvailable: 4.3.2 Service not active [AM6PR03CA0003.eurprd03.prod.outlook.com]. 

Which is problematic as the AuthenticationException does not have an StatusCode which I could inspect for more details.

How should I be detecting *true* failures of credentials?

**Comment by jstedfast** [comment]
You could try digging into the InnerException property. That should have the info you are looking for.

AuthenticationException -> SaslException -> SmtpCommandException

**Comment by oatsoda** [comment]
Thanks @jstedfast. Will take a look.

**Comment by jstedfast** [comment]
If the InnerException suggestion doesn’t work, let me know and I’ll try to look into making changes to the code so you can get that info.

**Comment by jstedfast** [comment]
It looks like my suggestion won't work now that I am looking at the code.

I'll commit a fix shortly.

**Comment by jstedfast** [comment]
FWIW, the nesting goes like this: `AuthenticationException` -> `SmtpCommandException` [ -> `SaslException` ]

**Comment by oatsoda** [comment]
@jstedfast Thanks for following up on this. I had just begun to look at how to get this working. I guess I will need to take the next version with the fix in!

So ultimately I can check for password/account specific failures by: 
- Checking for AuthenticationException
- Checking it has an InnerException of type SmtpCommandException
- Checking the StatusCode on the InnerException

**Comment by jstedfast** [comment]
Probably not for a few weeks unless a major bug comes to my attention. I try to release every 4-6 weeks or so and I just made a release last week?

**Comment by oatsoda** [comment]
@jstedfast Any chance of a it being quicker? I'm fighting quite a major live issue with this :(

**Comment by RickVM** [comment]
Running into the same problem. I would like some way to figure out what went wrong if authentication fails.

InnerException is Null, Message is: "Login failed"

**Comment by jstedfast** [comment]
The text "Login failed" likely came from the IMAP, POP3 or SMTP server.

You can get a protocol log like this:

```csharp
using (var client = new SmtpClient (new ProtocolLogger ("smtp.log"))
```

Replace "Smtp" with Pop3 or Imap depending on what client you are having this issue with.
