### ISSUE TITLE
Header are always coming empty

### ISSUE THREAD

**Issue by ravikumarjella** [jstedfast/MailKit#719]
HI 
I am using mailkit and i need headers to know whether the mail has attachments or not .
this is my code 
 var headerFields = new HashSet<string> { "X-MS-Has-Attach", "X-Mailer", "X-Priority", "X-Loop" };
var mails = maillist.Fetch(maillist.Count - endIndex, maillist.Count - startIndex, MailKit.MessageSummaryItems.All, headerFields);
i also used headerId's but still headers are comming as null.

**Comment by ravikumarjella** [comment]
any one please help me

**Comment by jstedfast** [comment]
It probably means that the message(s) don't have those headers.

Try getting a [protocol log](https://github.com/jstedfast/MailKit/blob/master/FAQ.md#ProtocolLog) to see if the server actually returns them.
