### ISSUE TITLE
Being able to authenticate with PLAIN without the leading '\0' in the encoded message ?

### ISSUE THREAD

**Issue by XavierDa** [jstedfast/MailKit#721]
I was trying to login on a server that support "delegate" authentication (oracle communications suite 7) 

i needed to login using PLAIN authentication and sending "USER1\ADMIN\0Password" but Mailkit is sending "\0USER1\ADMIN\0Password" which leads to "username or pass not UTF8

i created a simple SaslMechansim that inherit of SaslMechansimPlain and in challenge i changed :

`var buffer = new byte[userName.Length + password.Length + delegateUserName.Length + 1];`

and removed the first
 
`buffer[offset++] = 0;`

and it worked. 

I don't know if it could be a feature or not (as it could change many methods) but i feel like at least posting my experience with it. (and thanks for being able to use our own Saslmechanism it helped me)

**Comment by jstedfast** [comment]
Do you mean `"USER1\0ADMIN\0Password"`?

This is the SASL PLAIN spec: https://tools.ietf.org/html/rfc4616

The only way to skip the leading nul-byte is if you have 3 components: the `authzid`, `authcid` and `passwd`.

If not, seems like this server's PLAIN implementation is buggy?

Or am I missing something in the spec?

**Comment by XavierDa** [comment]
Yes it is USER1\0ADMIN\0Password.

**Comment by jstedfast** [comment]
Okay, then this patch should fix your issue: https://github.com/jstedfast/MailKit/commit/de2857c5d8fed2bf304bff0d8ff6cc59d0f1e8e9

Create your NetworkCredential with "USER1" as your domain string, "ADMIN" as your username and your passwd string as normal.

**Comment by XavierDa** [comment]
Yes this should work. great to see this patch will become baseline 👍
