### ISSUE TITLE
An error occurred while attempting to establish an SSL or TLS connection.

### ISSUE THREAD

**Issue by MrGreger** [jstedfast/MailKit#722]
An error occurred while attempting to establish an SSL or TLS connection.

The error occurs only after publishing to the server

client.ServerCertificateValidationCallback = (s, c, h, e) => true;
await client.ConnectAsync("smtp.mail.ru", 25, false);
    
await client.AuthenticateAsync(login, password);
await client.SendAsync(mailMessage);
await client.DisconnectAsync(true);

ServerCertificateValidationCallback never called

[smtplog.txt](https://github.com/jstedfast/MailKit/files/2098351/smtplog.txt)

**Comment by jstedfast** [comment]
Use `await client.ConnectAsync("smtp.mail.ru", 25, SecureSocketOptions.None);`
