### ISSUE TITLE
Expunge(list<uniqueid>) doesnt seem to work with Gmail

### ISSUE THREAD

**Issue by kirk-quinbar** [jstedfast/MailKit#726]
I have a status test for testing our email system and realized recently that even though i was marking emails for deletion and auto-expunge was set to true that gmail was archiving them instead of moving them to trash (this is the default). per some of the other postings i saw in your issues section here, i changed gmail's auto expunge to false and set the "when message is marked as deleted" to send to trash. If i run the attached code, the emails that get found are marked for deleting with the flag but never get moved to trash when the expunge method is called. the code is getting past the check for the UidPlus, but maybe gmail has some weird issues with that anyways and i should be using just Expunge()?

I tried commenting out that expunge code and just using a MoveTo Trash (also in the code but commented out) and that seems to work. 

any thoughts on why expunge(list<uniqueid>) isnt working with gmail? I am using the 2.0.4 version of mailkit. 

[mailkit-unittest-protocollog.txt](https://github.com/jstedfast/MailKit/files/2116323/mailkit-unittest-protocollog.txt)
[mailkit-examplecode.txt](https://github.com/jstedfast/MailKit/files/2116324/mailkit-examplecode.txt)

**Comment by jstedfast** [comment]
Here's the relevant snippet from the protocol log:

```
C: A00000009 CHECK
S: * 216 EXISTS
S: A00000009 OK Success
C: A00000010 UID SEARCH RETURN () SUBJECT "Test Email <1444c1cd-82a0-4b47-ab21-4fc85ce50bd1>"
S: * ESEARCH (TAG "A00000010") UID ALL 1496508
S: A00000010 OK SEARCH completed (Success)
C: A00000011 UID STORE 1496508 +FLAGS.SILENT (\Deleted)
S: * 216 FETCH (UID 1496508 MODSEQ (125848342) FLAGS (\Deleted))
S: A00000011 OK Success
C: A00000012 UID EXPUNGE 1496508
S: * 216 EXPUNGE
S: * 215 EXISTS
S: A00000012 OK Success
```

You are marking it as `\Deleted` and then you are purging it from the folder.

If you configured GMail to move `\Deleted` messages to the Trash folder, then don't `Expunge()` at all.

GMail doesn't use real "physical" folders (where "physical" means a separate storage location per folder), GMail only has 1 big folder with labels that are used to denote "folders", so they are purely virtual.

**Comment by kirk-quinbar** [comment]
I probably didnt explain what i did correctly so here are the details
- i changed gmail's auto-expunge to Off and changed the destination of deleted emails to the Trash. You cannot set the destination of deleted emails unless auto-expunge is off. the default for deleted emails if auto-expunge is on is to archive them, NOT send them to trash.. stupid.. lol. 
- I was then using the Expunge method from mailkit to Expunge any messages i deleted because if auto-expunge is set to off, it is expected that the client has to request an Expunge.
- with this setup, all emails are still be archived, so i was letting you know that Expunge seems to not work as expected, although i dont know if that is a mailkit issue or a gmail issue.

**Comment by jstedfast** [comment]
It's a GMail issue. MailKit did exactly what you asked it to do according to the protocol log.

If you just want to move the message(s) to the Trash folder, you could just use the `MoveTo` method.

That's what I would recommend... then it would work no matter what IMAP server you used.

**Comment by kirk-quinbar** [comment]
That makes sense. If i just do a MoveTo Trash, would i still need to add the Deleted flag, or is the MoveTo enough for even non-gmail servers.

**Comment by jstedfast** [comment]
No. If the IMAP server has a `MOVE` command, then MailKit will use that (in which case no need to set the `\Deleted` flag or `Expunge`). If the IMAP server *does not* support `MOVE`, then MailKit will use a `COPY` command and then mark those messages as `Deleted` and `Expunge`.
