### ISSUE TITLE
ServerCertificateValidationCallback does not work on Linux

### ISSUE THREAD

**Issue by Kintar** [jstedfast/MailKit#727]
Running MailKit in a .Net Core 2.0 app, connecting to a server with an enterprise-signed certificate.  Loading the certificate into the machine's store does not allow connection in Windows or Linux.  Setting SmtpClient.ServerCertificateValidationCallback to a delegate that always returns true works on Windows, but not when the same binary is run on Linux (Debian latest).

**Comment by jstedfast** [comment]
I would recommend submitting a bug report to Mono then because clearly the problem is unrelated to MailKit if it works properly on Windows.

**Comment by Kintar** [comment]
Digging in to it a little farther this morning, it looks like an issue with SslStream in corefx. :/

Although I've successfully used things that rely on SslStream on Linux in other contexts, so its going to be a little weirder than that.  Whee!

**Comment by Kintar** [comment]
Yep.  Just in case anyone is googling this:

The ServerCertificateValidationCallback is not honored in (at least) Debian Linux, and .Net Core does not correctly use the machine's certificate store by default.  In order to get around this limitation, do one of the following:

- Put the server certificates in a bundle file and point the environment variable SSL_CERT_FILE at it
- Put the server certificates in individual files in a known location, and point the environment variable SSL_CERT_DIR at the directory

Both of these options worked for me using the microsoft/dotnet:2.0-runtime docker image (which is a Debian-flavored Linux container).

**Comment by jstedfast** [comment]
Thanks for digging further into this and documenting a solution :)
