### ISSUE TITLE
SMTP NTLM Support?

### ISSUE THREAD

**Issue by gregsohl** [jstedfast/MailKit#728]
This is a general question about operation of the SaslMechanism in conjunction with SmtpClient. In general, does the SmtpClient support NTLM authentication? I ask because of the AuthMechanismRank array in SaslMechanism:

`/// The supported authentication mechanisms in order of strongest to weakest.
public static readonly string[] AuthMechanismRank = {"SCRAM-SHA-256", "SCRAM-SHA-1", "CRAM-MD5", "DIGEST-MD5", "PLAIN", "LOGIN"}`

NTLM is not listed as a supported mechanism. However clearly there is an implementation for it in SaslMechanismNtlm.

Can someone the support clarify please? Thank you.

Greg

**Comment by jstedfast** [comment]
NTLM isn't listed in that list because I kept getting mixed reports about whether it works or not. It works fine for me and I have unit tests that show that it does work according to all the specs I could find (and their samples).

You can still authenticate using NTLM by doing:

```csharp
var ntlm = new SaslMechanismNtlm (user, passwd);
client.Authenticate (ntlm);
```

**Comment by gregsohl** [comment]
Thank you for the quick reply and clarification Jeff. From the reading I've been doing of the last 3 weeks (ultimately leading me to MailKit as an alternative), NTLM support seems to be challenging (perhaps not quite standardized) across various SMTP servers.

**Comment by gregsohl** [comment]
Jeff, I've spent a couple days with MailKit now - mostly SMTP side. Great work!!

Can you tell me what server you use for testing SMTP with NTLM authentication? Exchange is the only one I've found that supports it.

Thanks.

Greg

**Comment by jstedfast** [comment]
I used to have access to an Exchange server, but afaict, each Exchange version has different quirks wrt NTLM authentication or perhaps it depends on how the admin configured it?

I no longer have access to NTLM - all I have are some sample challenge/responses in my unit tests now.

**Comment by gregsohl** [comment]
Again, thank you. I'm considering setting one up in Azure using these instructions (https://docs.microsoft.com/en-us/Exchange/plan-and-deploy/deploy-new-installations/create-azure-test-environments). 

However, I'm really leaning towards getting MailKit integrated (replacing System.Net.Mail.SmtpClient) and disabling NTLM, since MailKit SmtpClient is much more flexible.

Greg
