### ISSUE TITLE
mailkit proxy problem c#

### ISSUE THREAD

**Issue by saadmr** [jstedfast/MailKit#733]
i m using mailkit to connect to my outlook account
i need to know what it take socket in this method client.connect(socket,string host, int port ....);
i need a example please if some one can write it , i need to use a proxy to open my emails

**Comment by jstedfast** [comment]
The host and port aren't really used other than for logging purposes.

Create your own Socket connection to the proxy, issue whatever commands you need to in order to redirect it to the IMAP server, then pass it to that function.

**Comment by saadmr** [comment]
can you give me a example of socket plz

**Comment by jstedfast** [comment]
Take a look at https://msdn.microsoft.com/en-us/library/system.net.sockets.socket(v=vs.110).aspx?cs-save-lang=1&cs-lang=csharp#code-snippet-2

**Comment by saadmr** [comment]
i read it and i try this  : 

      string host = "89.249.241.195";
                    Socket sock = ConnectSocket(host,3128);
                    client.Connect(sock,"imap-mail.outlook.com", 993, true); 

and still having the problem

**Comment by jstedfast** [comment]
Well, yea, because you need to send the proxy commands to the socket first.

I have no idea what those proxy commands are, but you need to do that or it won;'t work.
