### ISSUE TITLE
Attachments name issue

### ISSUE THREAD

**Issue by joekim2000** [jstedfast/MailKit#734]
When I send mail to gmail with attachments korean filename image or all of documents(actually all of files) that gmail shows attachment "noname" or "xxxx.dat".
Also, I downloaded orignal eml file from gmail and open it from thunderbird, shows attachments names part 1.2, part1.3, part 1.4, part 1.5, part 1.6 as five files but files are ok

But When I send thunderbird or other mail server that they have correct names.
what is wrong with my source code and how can I fix it
Please check my source code and I sent eml file to your mail address
                    var message = new MimeMessage();
                    message.From.Add(new MailboxAddress("", myID));
                    message.To.Add(new MailboxAddress(name, address));
                    message.Subject = SubjectBox.Text;
                    message.Body = new TextPart("plain")
                    {
                        Text = htmlEditorControl.InnerHtml
                    };
                    var builder = new BodyBuilder();
                    builder.HtmlBody = htmlEditorControl.InnerHtml;
                    builder.Attachments.Add("한글이름.xlsx");
                    message.Body = builder.ToMessageBody();

                    string filePath = "outMail.eml";
                     using (var cancel = new System.Threading.CancellationTokenSource())
                     {
                         using (var stream = File.Create("outMail.eml"))
                         {
                             message.WriteTo(stream, cancel.Token);
                         }
                     }

**Comment by jstedfast** [comment]
See the [FAQ](https://github.com/jstedfast/MailKit/blob/master/FAQ.md#UntitledAttachments)

**Comment by joekim2000** [comment]
Dear Jeffrey Stedfast
Thank you for quick response, I  ommited your kind guideline.

I changed my code as your guide like below but it's not work
                        using (var cancel = new System.Threading.CancellationTokenSource())
                        {
                            using (var stream = File.Create(filePath))
                            {
                                var options = FormatOptions.Default.Clone();
                                options.ParameterEncodingMethod = ParameterEncodingMethod.Rfc2047;
                                message.WriteTo(options, stream, cancel.Token); 

                            }
                        }

 I use .net framework 4.0 and mailkit 1.22.0 
and also tested .net 4.5 and mailkit 2.0.5

with above code
they are same problem on gmail attachments filename and outlook client also
I attached eml  and some capture file for review, please check it what is wrong.

picture 1 is outlook client that attachment name is Korean, means "nonamed attachment file 0002.txt" but body is ok to read Korean
picture 2 is gmail client that attachment name is html character code as you see
picture 3 is thunderbird client that attachment name is ok to read korean, means "Pyeongyang-style Cold Buckwheat Noodles <Pyeongyang naengmyeon>"... :)

I think something mistake to use mailkit library in my source code but I don't know what  is wrong in my source code


[eml_capture.zip](https://github.com/jstedfast/MailKit/files/2195373/eml_capture.zip)
Please review my data and check out my mistake

sincerely yours, Joe Kim
