### ISSUE TITLE
mailkit socket problem

### ISSUE THREAD

**Issue by saadmr** [jstedfast/MailKit#736]
i m using this code : 
 ipAddress = IPAddress.Parse("188.165.250.78");
                    IPEndPoint localEndp = new IPEndPoint(ipAddress,3836);
                    Socket ssocket = new Socket(ipAddress.AddressFamily,SocketType.Stream, ProtocolType.Tcp);
                    ssocket.Connect(ipAddress,3836);
                    client.Connect(ssocket, "imap-mail.outlook.com", 993, SecureSocketOptions.SslOnConnect);

but when i run the app they give this : 
Failed to authenticate because the remote site has closed the transport stream.  any help ?

**Comment by jstedfast** [comment]
I don't know, you'll have to use a debugger.
