### ISSUE TITLE
Unable to connect to mail server in client environment

### ISSUE THREAD

**Issue by Mohit05niec** [jstedfast/MailKit#737]
I have a syndication service build upon mailkit v.1.20.0.0 which fetch all the mails from Email server, and later process those email to create a case in our system.
Now suddenly for 3 different clients, we started facing following error:
"A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond"
We assumed it could be due to firewall blocking the request, but interestingly earlier release of the application built upon mailkit v1.0.1.0 is working fine in the same environment. So the possibility of firewall blocking the request is ruled out. Also Email clients are able to fetch the mail in the same environment.
As all the three client started facing similar error all of sudden, there could be possibility of windows update, which might need any kind of enhancement in Mailkit.

I am providing below all the log file generated by protocol logger, along with snaps of log generated by Shared Listener of Socket. In the trace log created by socket listner, there seems to be multiple attempt, with different error, which are attached Capture1, Capture2.....

Sample Code is below (Server is Microsoft Exchange IMAP Server, Port-993, SSL-true

                var currentDir = Directory.GetCurrentDirectory();
                var fileName = "logfile.log";
                var logFile = Path.Combine(currentDir, fileName);
                IProtocolLogger logger = new ProtocolLogger(logFile);
                var client = new MailKit.Net.Imap.ImapClient(logger);
                client.Connect(serverName, port, chkssl)

Attachment:

Trace Log:

![capture1](https://user-images.githubusercontent.com/9025073/43152354-f511709c-8f8b-11e8-820d-4e88d4146b72.JPG)
![capture2](https://user-images.githubusercontent.com/9025073/43152355-f564cdc8-8f8b-11e8-973c-af33cb0e295e.JPG)
![capture3](https://user-images.githubusercontent.com/9025073/43152356-f5b67efc-8f8b-11e8-88a8-e9c45eea4eaf.JPG)
![capture4](https://user-images.githubusercontent.com/9025073/43152357-f609010e-8f8b-11e8-8774-dd64ca35a9c3.JPG)
![capture5](https://user-images.githubusercontent.com/9025073/43152361-f63b9a6a-8f8b-11e8-9b11-23bf8c3b3f3d.JPG)

ProtocolLogge Log:

[logfile.log](https://github.com/jstedfast/MailKit/files/2224501/logfile.log)

**Comment by jstedfast** [comment]
According to the log:

```
Connected to imaps://mail.idfcbank.com:993/
S: * OK The Microsoft Echange IMAP4 service is ready.
C: A00000000 CAPABILITY
S: * BYE Connection is closed. 13
```

Looks like the server is immediately disconnecting the client (that's what the `* BYE ...` is about).

You'll probably need to look at the server logs to diagnose this. It's not a bug in MailKit as far as I can tell.

**Comment by Mohit05niec** [comment]
I am not saying its a bug in Mailkit, but could it be possible that, due to any windows update , there is some kind of compatibility issue with mailkit.
TraceRoute and Telnet, and other mail client are working pretty fine in the same environment, but when using mailkit it is disconnecting.
Sever Trace log are also attached.

**Comment by jstedfast** [comment]
How would I be able to diagnose whether or not a Windows update broke MailKit on your machine?

It works fine on my machine and I've got all of the latest updates.

The protocol log also shows that your IMAP server is immediately disconnecting your client right after it connects. That indicates that the problem is not a Windows update on your client, it's a problem with the server (either a bug in the server or the server is overloaded with connections and is therefor dropping the latest connection which happens to be the MailKit client).

**Comment by jstedfast** [comment]
This is the loop that attempts to connect a socket to the remote host:

https://github.com/jstedfast/MailKit/blob/master/MailKit/Net/Imap/ImapClient.cs#L1253

Your Socket Listener shows multiple attempts because DNS is returning multiple addresses for the server and MailKit tries each of them until it is able to connect successfully (which it does - the protocol log proves that it makes a successful connection).

At this point, the server sends the greeting message and then MailKit asks for the list of capabilities of the server. The server then responds with `* BYE ...` which means the server is dropping the connection for whatever reason that it does not specify.

You are free to step through the Connect() code in a debugger and see that I am right.

TraceRoute does not establish an IMAP connection so I have no idea why you think that proves anything.

Telnet doesn't either unless you are connecting it on port 993, but even then, are you stopping as soon as Telnet connects? Or are you issuing IMAP commands once you are connected?

**Comment by Mohit05niec** [comment]
Thanks for your quick reply.
As you said it is working fine in your machine, it is also working fine on my dev-machine (Windows-10) and .Net Framework 4.7.1
But I am getting the error only on few client environment all of them are Windows Server 2012 R2 and .Net Framework version 4.7.1.
Also these client are able to fetch the mail from Email Client (Microsoft Outlook and Mozila ThunderBird)
I would highly appreciate if you could consider it.

**Comment by jstedfast** [comment]
What do you expect me to do?

**Comment by Mohit05niec** [comment]
Can you plese just tell me  whether the problem is related to environment, or Mailkit related or is it something related with my implementation.

Implementation:
`var logFile = Path.Combine(Directory.GetCurrentDirectory(), "logfile.log");
var client = new ImapClient(new ProtocolLogger(logFile))
client.ServerCertificateValidationCallback = (s, c, h, err) => true;
client.Connect(txtServer.Text, txtPort.Text.GetInt(), chkSSL.Checked ? SecureSocketOptions.SslOnConnect : SecureSocketOptions.None);`

     
Exception with stack trace:

at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 s
ize)
   at System.Net.FixedSizeReader.ReadPacket(Byte[] buffer, Int32 offset, Int32 c
ount)
   at System.Net.Security._SslStream.StartFrameHeader(Byte[] buffer, Int32 offse
t, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security._SslStream.StartReading(Byte[] buffer, Int32 offset, I
nt32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security._SslStream.ProcessRead(Byte[] buffer, Int32 offset, In
t32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.Read(Byte[] buffer, Int32 offset, Int32 coun
t)
   at MailKit.Net.Imap.ImapStream.ReadAhead(Int32 atleast, CancellationToken can
cellationToken)
   at MailKit.Net.Imap.ImapStream.ReadToken(String specials, CancellationToken c
ancellationToken)
   at MailKit.Net.Imap.ImapStream.ReadToken(CancellationToken cancellationToken)

   at MailKit.Net.Imap.ImapEngine.ReadToken(CancellationToken cancellationToken)

   at MailKit.Net.Imap.ImapCommand.Step()
   at MailKit.Net.Imap.ImapEngine.Iterate()
   at MailKit.Net.Imap.ImapEngine.Wait(ImapCommand ic)
   at MailKit.Net.Imap.ImapEngine.QueryCapabilities(CancellationToken cancellati
onToken)
   at MailKit.Net.Imap.ImapClient.Connect(String host, Int32 port, SecureSocketO
ptions options, CancellationToken cancellationToken)
   

Unable to read data from the transport connection: An established connection was
 aborted by the software in your host machine.An established connection was abor
ted by the software in your host machine

**Comment by jstedfast** [comment]
I've already told you the problem is on the server end.

If the server drops your connection, there's absolutely nothing that MailKit can do to work around that.

And that is EXACTLY what is happening here.

**Comment by jstedfast** [comment]
Since I have no access to your specific environment where it didn't work, how do you propose I do that?

Will you give me access to your server?
