### ISSUE TITLE
Problem with ImapFolder.Thread() function?

### ISSUE THREAD

**Issue by smorks** [jstedfast/MailKit#739]
I was trying to use the ImapFolder.Thread() function, and i'm getting the following error:

`Syntax error in untagged THREAD response. Unexpected token: '('`

I've attached my [protocol log](https://github.com/jstedfast/MailKit/files/2242652/imap.log), which shows the two responses from two different folders from the server. It looks to me like it doesn't like when there are two opening parentheses in a row, i'm not sure if that's non-standard?

For more info, it's my own imap server running dovecot 2.3.2.1, with a very basic config, so I don't know if it's an issue with my server?

Any help would be greatly appreciated!

**Comment by jstedfast** [comment]
Thanks, I'll try to take a look at this soon.

Dovecot is usually pretty good about being standards compliant so off-hand, I'm going to guess that the bug is in my parser...

**Comment by smorks** [comment]
wow that was quick, thank you! and thanks for all your work on MimeKit/MailKit!
