### ISSUE TITLE
SmtpClient not throwing exception if wrong email provided in "To" parameter

### ISSUE THREAD

**Issue by NishantThakkar** [jstedfast/MailKit#745]
SmtpClient not throwing exception if wrong email provided in "To" parameter.

Please find attached smtp log for the same. I have removed some authentication data from it.

[smtp.log](https://github.com/jstedfast/MailKit/files/2302128/smtp.log)

**Comment by jstedfast** [comment]
Your SMTP server claimed it was valid, see the log here:

```
C: MAIL FROM:<noreply@aaneel.com>
C: RCPT TO:<wrongrecipient@wrongdomain.com>
S: 250 2.1.0 Sender OK
S: 250 2.1.5 Recipient OK
```

**Comment by NishantThakkar** [comment]
`RCPT TO: wrongrecipient@wrongdomain.com`

which is completely wrong email id, so i am assuming, it should throw exception instead of logging: 
`S: 250 2.1.5 Recipient OK`

**Comment by jstedfast** [comment]
How would MailKit know it's the wrong address?

**Comment by NishantThakkar** [comment]
@jstedfast sorry for late reply, but while MailKit trying to send E-Mail (via SMPT protocol), and if SMTP throws exception for wrong E-Mail Id, the same exception can be handled by MailKit and then MailKit can throw its own exception.
P.S.
I have not tried by sending SMTP above is just my assumption.

**Comment by jstedfast** [comment]
@NishantThakkar MailKit already does that.

**Comment by NishantThakkar** [comment]
@jstedfast then it should throw an exception instead of stating OK for below wrong Email Id:

```
C: RCPT TO:<wrongrecipient@wrongdomain.com>
S: 250 2.1.5 Recipient OK
```
Because its not going in my exception block for above Email Id.

**Comment by jstedfast** [comment]
@NishantThakkar That log is what the server says, not what MailKit says.

In other words, your SMTP server is telling MailKit that the recipient is "OK".

How can MailKit *possibly* know that the recipient *isn't* OK if the server says it is?

**Comment by NishantThakkar** [comment]
@jstedfast oh!!! if the SMTP is telling OK, then you are right MailKit can not say that it's wrong Email.
Thank you for your response.
You may close this issue.
