### ISSUE TITLE
Bulk fetch body of messages

### ISSUE THREAD

**Issue by stormleoxia** [jstedfast/MailKit#747]
From what I understood from documentation, if I want to get the body for a list of emails, I can:

- Given a list of UniqueId, iterate through the list and call GetMessage for each.

- Given a list of UniqueId, fetch the list of IMessageSummary and then iterate over
the summaries and call GetBodyPart.

The problems is that both of them are incurring many round trips to the IMAP server.

Is it possible to do this with a single IMAP command ? like `FETCH %u BODY.PEEK[]` ?
Could we do this with MailKit ? 
Or should I try to implement this with a new MessageSummaryItems value like BodyContent ?

**Comment by jstedfast** [comment]
Use this method: http://www.mimekit.net/docs/html/M_MailKit_Net_Imap_ImapFolder_GetStreams.htm
