### ISSUE TITLE
Idle problen when fetch messages

### ISSUE THREAD

**Issue by pfuentes1402** [jstedfast/MailKit#749]
I am running the MailKit / samples / ImapIdle / project and I added a line of code in the CountChanged event to get the messages from the mail server in this way: var uids = folder.Search (SearchQuery.NotSeen); but when he executes that line he throws the next exception
The ImapClient is currently busy processing a command in another thread. Lock the SyncRoot property to properly synchronize your threads.

try lock SyncRoot in this way:
lock (folder.SyncRoot)
{
       var uids = folder.Search (SearchQuery.NotSeen);
}

but keep throwing this exception. How can I solve that? Thanks in advance.

PS: I am using MailKit 2.0.1

**Comment by jstedfast** [comment]
You cannot query the ImapClient or an ImapFolder from within event callbacks. You have to just update your local state so that when the current command completes, you can then use that state info to decide what the next command(s) should be.

The reason for this is that MailKit emits events immediately as they are sent across the wire from the IMAP server and does not wait until the current command has finished being processed.

**Comment by Havret** [comment]
Is there any way to know when current command finish processing?

**Comment by jstedfast** [comment]
Yea, when the method returns it means it's done processing.

**Comment by Havret** [comment]
But I am thinking about event handler scenario. 

```
_client.Inbox.CountChanged += (sender, args) =>
{
    // some command is being processed in the meantime
};
```

**Comment by jstedfast** [comment]
Here's another option:

```csharp
Task task;

client.Inbox.CountChanged += (sender, args) => {
    task = task.ContinueWith (...);
};
task = client.Inbox.DoSomethingAsync ();
```

**Comment by Havret** [comment]
The problem was with coming back from idle when I received new message. Now I am doing sth like this --> 

```
_client.IdleAsync(_cancellationTokenSource.Token).ContinueWith(x =>
{
    self.Tell(new IdleStopped());
});
```

**Comment by jstedfast** [comment]
If you are just talking about breaking out of idle, you could do this:

```csharp
var done = new CancellationTokenSource (timeSpan);

client.Inbox.CountChanged += (sender, args) => { done.Cancel (); };
await client.IdleAsync (done.Token, cancel.Token);
```

**Comment by jstedfast** [comment]
Most mail client software that supports IDLE uses multiple connections.

They'll use 1 connection for IDLE and another connection to actually fetch the messages and such.

That allows them to do something like this:

```csharp
idleClient.CountChanged += (sender, args) => { otherClient.Fetch (...); };
await idleClient.IdleAsync (doneToken, cancelToken);
```

**Comment by rklec** [comment]
For future reference, see also this discussion: https://github.com/jstedfast/MailKit/discussions/1723
