### ISSUE TITLE
Send email to group email id

### ISSUE THREAD

**Issue by pethumishara** [jstedfast/MailKit#751]
I am using .net core web api .
I can send email to individual email ids.
but, sending to group email id (hr@xxx.com), it will fail.
 emailClient.ServerCertificateValidationCallback = (s, c, h, e) => true;
                    emailClient.Connect(_configuration["Email:Host"], int.Parse(_configuration["Email:Port"]), false);   //The last parameter here is to use SSL (Which you should!)
                    emailClient.AuthenticationMechanisms.Remove("XOAUTH2");//Remove any OAuth functionality as we won't be using it. 
                    emailClient.Authenticate(_configuration["Email:Email"], _configuration["Email:Password"]);

                    emailClient.Send(message);
                    emailClient.Disconnect(true);

**Comment by jstedfast** [comment]
What's the error?

**Comment by pethumishara** [comment]
Currently, i am not able to debug VS 2017 due to some issue, but when it is group email id (Which is not authentication) that email address for a group of people, email does not send to only group email, but SmtpClient.Send() wend s the mail to other email address.

**Comment by jstedfast** [comment]
Sounds like an issue with the server. Get a protocol log to see what the server is telling MailKit.

**Comment by tonyjmartinez** [comment]
Did you ever figure this out? I'm having the same problem sending to a group email id. There's no authentication for our internal SMTP.

**Comment by jstedfast** [comment]
Get me a protocol log (see the FAQ.md file in the repo for instructions) and I’ll take a look.

**Comment by ramya-m-1** [comment]
Hi
I am facing the same issue with "not able to send mail to a distribution list".
Not sure of how to get the protocol log file. Can u pls help me with this?

**Comment by jstedfast** [comment]
```csharp
var client = new SmtpClient (new ProtocolLogger ("smtp.log"))
```

**Comment by jdelgado1025** [comment]
Hello,

I am also having issues when sending emails to a distro group. Works fine when sending to an individual email.

Looking at the ProtocolLogger, it doesn't seem like there is any actual error. It says the email is queued for delivery and then just quits.
[smtp.log](https://github.com/jstedfast/MailKit/files/11885991/smtp.log)

I have attached the log file with only one request. The distro group is in both the TO and the CC.

Thanks!

**Comment by jstedfast** [comment]
If there's no error in the SMTP log, then the problem is either with the SMTP server or the mailing list software.

**Comment by jdelgado1025** [comment]
Thanks for the prompt reply. Could you elaborate? I am using the same SMTP server in a different application (Tibco) and it has no issues sending emails to a distribution list.

Would like to know what I should possibly be asking the server team to look for.

Thanks again!

**Comment by jstedfast** [comment]
I have no idea what to look for either. I can just tell based on the log that the problem isn't MimeKit (the MIME is fine) or MailKit (the SMTP protocol was executed by MailKit's SmtpClient just fine).

**Comment by jdelgado1025** [comment]
Noted. Thanks for you help!
