### ISSUE TITLE
How do I make it possible to display two or more mailboxes in the tree of the "ImClientDemo" example?

### ISSUE THREAD

**Issue by it19862** [jstedfast/MailKit#753]
How do I make it possible to display two or more mailboxes in the tree of the "ImClientDemo" example?
[link](https://github.com/jstedfast/MailKit/tree/master/samples/ImapClientDemo/ImapClientDemo)
![2018-09-16_13-47-01](https://user-images.githubusercontent.com/18245828/45595618-58840180-b9b7-11e8-82ee-67245781f4cb.png)

**Comment by jstedfast** [comment]
That's a Windows.Forms question and not a MailKit question.

But what is stopping you from doing that? Seems like it'd be easy. Just don't clear the `nodes` list in `LoadChildFoldersAsync`.

**Comment by it19862** [comment]
@jstedfast 

I am sorry.
Did I do it right?
Just commented out the line
// nodes.Clear (); 
**FolderTreeView.cs**
`async Task LoadChildFoldersAsync (IMailFolder folder, IEnumerable<IMailFolder> children)
		{
			TreeNodeCollection nodes;
			TreeNode node;

			if (map.TryGetValue (folder, out node))
            {
				nodes = node.Nodes;
				// nodes.Clear ();  <<<=  commented out the line
			}
            else
            {
				nodes = Nodes;
			}

			foreach (var child in children)
            {
				node = CreateFolderNode (child);
				map[child] = node;
				nodes.Add (node);

				child.MessageFlagsChanged += UpdateUnreadCount;
				child.CountChanged += UpdateUnreadCount;

				if (!child.Attributes.HasFlag (FolderAttributes.NonExistent) && !child.Attributes.HasFlag (FolderAttributes.NoSelect)) {
					await child.StatusAsync (StatusItems.Unread);
					UpdateFolderNode (child);
				}
			}
		}`


PS
I'm sorry, I'm starting to learn C #.
I have a few more questions about the code for the example "ImClientDemo".
I can ask these questions in jstedfast / MileKit / Issues?

Or it needs to be done elsewhere (for example stackoverflow.com)?

**Comment by jstedfast** [comment]
I would recommend asking the questions on Stackoverflow.com. I don't have the time to answer basic C# questions or explain how to do Windows Forms UI programming (I barely know anything about Windows Forms either).

I'll answer questions specific about MailKit, but MailKit probably isn't the best "learning C#" library out there ;-)

**Comment by it19862** [comment]
@jstedfast 
I see.... ))
I'm looking at the code "ImapClientDemo" and practically do not understand anything ...
I'm trying to figure it out ...

Is there an easier library for sending / receiving letters?
Requirements:
- a tree of mailboxes with folders;
- the ability to set tags for messages;

**Comment by jstedfast** [comment]
Probably not. My point was not that MailKit was a difficult "email library", just that email is a very difficult type of project to tackle when you are still learning how to program.

I would recommend taking on some simpler tasks first before you dive head-first into the deep end of the pool.
