### ISSUE TITLE
Authendication

### ISSUE THREAD

**Issue by madu2003** [jstedfast/MailKit#754]
Hi,

This is not a report for a bug but there is no place to ask this issue that I am having. Basically, I just wanted to know whether there's way of authenticating the mailbox user without a password? 

				client.Connect ("imap.friends.com", 993, true);
				client.Authenticate ("joey", "password");

My client has an email policy where the password is expired every 60 days. So this will be an inconvience since the email reader is a windows application which runs every minute. 

Thanks.
Jay.

**Comment by jstedfast** [comment]
But he still has a password, right? I don't know how he would gain access to his account if he doesn't authenticate.
