### ISSUE TITLE
ReplyTo is Difficult for me to set

### ISSUE THREAD

**Issue by DanJ210** [jstedfast/MailKit#755]
**Is your feature request related to a problem? Please describe.**
I'm just wanting to be able to set the reply to property in the MimeMessage so that emails that go out will reply to that property. I can't figure out what I would inherit or use to set this as I've been trying a few things and checking documentation for any answers on how to actually set the property.

**Describe the solution you'd like**
I can set the to addresses, from addresses, message and body, subject... I'd love to be able to set the reply to property as well or at least know how.

**Describe alternatives you've considered**
Trying to implement and change the code myself. I'm somewhat new at this so I need documentation that tells me how I would set properties like this with only a getter or at least how they were intended to be used and why I can't set them like other properties that I can set.

**Additional context**
If there's anything that helps me set this then please refer me and I would really appreciate it.

**Comment by jstedfast** [comment]
`MimeMessage.ReplyTo` does not have a setter - the way you add ReplyTo addresses is to add them to the existing `MimeMessage.ReplyTo` list. It works exactly the same way as the `From`, `To`, `Cc`, and `Bcc` properties.

Example:

```csharp
var message = new MimeMessage ();
message.ReplyTo.Add (new MailboxAddress ("My Name", "my@address.com"));
```

**Comment by DanJ210** [comment]
Oh. So yea that makes a lot of sense and is definitely a super dumb question. I don't know why I didn't realize that.

Thank you.

**Comment by chartierpw** [comment]
I just installed the latest version of Mailkit/Mimekit (3.6.0/3.6.1) and apparently we are still unable to set the reply to address.  This was supposed to be fixed 4+ years ago, no?  I need to be able to set the reply to address, not being able to do this makes Mailkit/Mimekit useless to me.  Is that change going to be made anytime soon?

R/
Prescott ....

**Comment by jstedfast** [comment]
You set the Reply-To addresses:

    message.ReplyTo.Add(new MailboxAddress("name", user@domain.com"));

**Comment by chartierpw** [comment]
Ah ... clearly I didn't look close enough.  Thanks for the reply, I was worried for a second as Xamarin was complaining that System.Net.Mail was obsolete and to switch to Mailkit/Mimekit.

R/
Prescott ....
