### ISSUE TITLE
Not able to read Inbox using IMAP client

### ISSUE THREAD

**Issue by aypdev** [jstedfast/MailKit#757]
I want to read emails & download attachments from my mailbox (a govt. provided service) using MailKit IMAP client.

- What were you trying to do?
  Read emails using IMAP client.

- What happened?
     Exception at  **inbox.Open(FolderAccess.ReadOnly);**
**(Exception: MailKit.Net.Imap.ImapCommandException: 'The IMAP server replied to the 'EXAMINE' command with a 'BAD' response: Unrecognised option condstore on Examine')**

- What did you expect to happen?
  Successfully get the Read access for the inbox.

- Step-by-step reproduction instructions and/or a simple test case.

```
using (var client = new ImapClient(new ProtocolLogger("E:\\imap.log")))
            {
                // For demo-purposes, accept all SSL certificates
                client.ServerCertificateValidationCallback = (s, c, h, e) => true;

                client.Connect("mail.gov.in", 993, true);

                client.Authenticate("XYZ@abc.gov.in", "password");
                // The Inbox folder is always available on all IMAP servers...

                var inbox = client.Inbox;
               
                **inbox.Open(FolderAccess.ReadOnly);** Crashed here

                Console.WriteLine("Total messages: {0}", inbox.Count);
                Console.WriteLine("Recent messages: {0}", inbox.Recent);

                for (int i = 0; i < 3; i++)
                {
                    var message = inbox.GetMessage(i);
                    Console.WriteLine("Subject: {0}", message.Subject);
                }

                client.Disconnect(true);
            }
```
If you got an exception, please include the exception Message *and* StackTrace.

**(Exception: MailKit.Net.Imap.ImapCommandException: 'The IMAP server replied to the 'EXAMINE' command with a 'BAD' response: Unrecognised option condstore on Examine')**

imap protocol log:

Connected to imaps://mail.gov.in:993/
S: * OK [CAPABILITY IMAP4rev1 UIDPLUS CHILDREN NAMESPACE SORT QUOTA ACL STARTTLS AUTH=PLAIN] Messaging Multiplexor (Oracle Communications Messaging Server 7.0.5.31.0 64bit (built May  5 2014))
C: A00000000 AUTHENTICATE PLAIN
S: + 
C: AGNiaW11bWJhaS5sZWdhbEBjYmkuZ292LmluAEFjYkAyMDE3
S: A00000000 OK User XYZ.gov.in logged in
C: A00000001 CAPABILITY
S: * CAPABILITY IMAP4 IMAP4rev1 ACL RIGHTS=tekx QUOTA LITERAL+ NAMESPACE UIDPLUS CHILDREN BINARY UNSELECT SORT CATENATE URLAUTH LANGUAGE ESEARCH ESORT THREAD=ORDEREDSUBJECT THREAD=REFERENCES ENABLE QRESYNC CONTEXT=SEARCH CONTEXT=SORT WITHIN SASL-IR SEARCHRES METADATA ID XSENDER X-SUN-SORT ANNOTATE-EXPERIMENT-1 X-UNAUTHENTICATE X-SUN-IMAP XUM1 IDLE
S: A00000001 OK Completed
C: A00000002 NAMESPACE
S: * NAMESPACE (("" "/")) (("Shared Folders/User/" "/")) (("Shared Folders/Public/" "/"))
S: A00000002 OK Completed
C: A00000003 LIST "" "INBOX"
S: * LIST (\NoInferiors) "/" INBOX
S: A00000003 OK Completed
C: A00000004 EXAMINE INBOX (CONDSTORE)
S: A00000004 BAD Unrecognised option condstore on Examine

Please help.

**Comment by jstedfast** [comment]
MailKit is using the `(CONDSTORE)` parameter because your IMAP server claims to support the `QRESYNC` extension.

From rfc5162:

```
   The quick resync IMAP extension is present if an IMAP4 server returns
   "QRESYNC" as one of the supported capabilities to the CAPABILITY
   command.

   Servers supporting this extension MUST implement and advertise
   support for the [ENABLE] IMAP extension.  Also, the presence of the
   "QRESYNC" capability implies support for the [CONDSTORE] IMAP
   extension even if the CONDSTORE capability isn't advertised.
```

And from rfc4551:

```
   A client supporting CONDSTORE extension indicates its willingness to
   receive mod-sequence updates in all untagged FETCH responses by
   issuing:

      -  a SELECT or EXAMINE command with the CONDSTORE parameter,
      -  a STATUS (HIGHESTMODSEQ) command,
      -  a FETCH or SEARCH command that includes the MODSEQ message data
         item,
      -  a FETCH command with the CHANGEDSINCE modifier, or
      -  a STORE command with the UNCHANGEDSINCE modifier.
```

Sigh. I wish IMAP server developers read and followed the specifications...

Here's what you can do, since you don't seem to be trying to use the features that CONDSTORE provide:

After authenticating with the IMAP server, add this bit of code:

```csharp
client.Capabilities &= ~(ImapCapabilities.QuickResync | ImapCapabilities.CondStore);
```

**Comment by aypdev** [comment]
Thank you so much.... Worked as explained.

**Comment by jstedfast** [comment]
FWIW, any capability advertised by the server can be manually disabled using that trick above.

Glad it worked for ya :)
