### ISSUE TITLE
[Question] 5.7.1 Relaying denied - using SMTP Server without username/password

### ISSUE THREAD

**Issue by mcblair** [jstedfast/MailKit#758]
I expect that it is obvious if you support sending SMTP without callling `Authenticate()` but I'm finding that an SMTP server I had no problem connecting to with Node.js NodeMailer - is giving me 5.7.1.

My flow:
```
try
{
    
    await _mailTransport.ConnectAsync(_smtpConfiguration.KerioHost, 25, SecureSocketOptions.None);
    await _mailTransport.SendAsync(mimeMessage);
    await _mailTransport.DisconnectAsync(true);
}
catch (Exception e)
{
    if (_mailTransport.IsConnected)
    {
        await _mailTransport.DisconnectAsync(true);
    }
    _logger.LogError($"SendKerio Exception: {e.Message}", e);
}
```

**Comment by jstedfast** [comment]
That will work as long as you don't need a user name and password.

You might want to try getting a protocol log to see why the server is rejecting you.

See the FAQ.md file for instructions on how to do that.

**Comment by mcblair** [comment]
Thanks, that didn't make things any clearer though. I understand we received the three Auth types CRAM-MD5, DIGEST-MD5 and NTLM from `Connect()` - does that mean one of those three is required?
```
Connected to smtp://x-inmai01.x.com:25/
S: 220 x-inmai01.x.com Kerio Connect 9.2.5 patch 3 ESMTP ready
C: EHLO [10.21.13.191]
S: 250-x-inmai01.x.com
S: 250-AUTH CRAM-MD5 DIGEST-MD5 NTLM
S: 250-SIZE 41943040
S: 250-STARTTLS
S: 250-ENHANCEDSTATUSCODES
S: 250-8BITMIME
S: 250-PIPELINING
S: 250-ETRN
S: 250-DSN
S: 250 HELP
C: MAIL FROM:<x@x.com>
C: RCPT TO:<x@x.com>
S: 250 2.1.0 Sender <x@x.com> ok
S: 550 5.7.1 Relaying to <x.x@x.com> denied (authentication required)
C: RSET
S: 250 2.0.0 Reset state```
