### ISSUE TITLE
How to make the sequence of folders in the tree mailClient coincide with the sequence of folders on the server?

### ISSUE THREAD

**Issue by it19862** [jstedfast/MailKit#759]
The "ImapClientDemo"([LINK](https://github.com/jstedfast/MailKit/tree/master/samples/ImapClientDemo)) client builds a folder tree where the folder sequence does not match the folder sequence on the IMAP server

How to make the sequence of folders in the tree mailClient coincide with the sequence of folders on the server?
![devenv_2018-09-20_23-29-27](https://user-images.githubusercontent.com/18245828/45845687-7b534480-bd2e-11e8-9da6-e65b0ebdd723.png)

**Comment by jstedfast** [comment]
How are they different? Other than the "Loading..." placeholder (which is probably a bug in the demo, it shouldn't be there once the child folders are loaded).

If you mean the order, well, you can't. All you can do is do your best to use the same sort order that the server uses and hacks to change the location of any folders that don't match up.

This is not a limitation of MailKit, this is a limitation of the IMAP protocol.

**Comment by it19862** [comment]
@jstedfast  
I put numbers according to which folders should be placed.
I correctly understood you, that these folders go in such a sequence in the source (imap) server?
Strange in the "thé bat" sequence of folders corresponds to the same sequence of folders on the server

![devenv_2018-09-20_23-29-28](https://user-images.githubusercontent.com/18245828/45847453-c754b800-bd33-11e8-97d5-ca5736c4a64f.png)

**Comment by jstedfast** [comment]
MailKit doesn't change the order of the folders returned by the IMAP server.

You can see proof of that by reading the source code here: https://github.com/jstedfast/MailKit/blob/master/MailKit/Net/Imap/ImapFolder.cs#L1410

My guess is that "thé bat" is sorting the folders alphabetically. You can do that with the results returned by MailKit as well, and in fact, that's exactly what I told you you could do in my previous comment.

If you still don't believe me, get a [Protocol Log](https://github.com/jstedfast/MailKit/blob/master/FAQ.md#ProtocolLog) and check what the server returned.

**Comment by jstedfast** [comment]
I just updated the demo to sort the folders so you can see how to do that.

**Comment by it19862** [comment]
@jstedfast 
Many thanks that have not left my question without attention
I apologize if I can not easily read some of your messages. I do not speak English well.


Thanks for the changes you made to the "ImapClientDemo" example.
Now the structure of the folders has become more like the source, but not completely ...
Although this option is also suitable ... The main thing is that the folder "incoming" is at the top

Questions.
Once again I want to clarify.
1. The structure of the folders in the "mail client" depends on the folder structure on "imap.yandex.by"?
2. Folders can be sorted alphabetically only?
3. Can not change the sequence of folders the way I want?
If I want to make the folder structure in any order.
4. Could you show how the changes made to the code to change the sorting?
I found some changes in the code, but I'm afraid to skip some little things.
5. To display the "Email" list, can I replace "messageList1" with "DataGridView"?
In the future I want to do:
- Ability to set tags to "Email";
- to make some "Email" in the "Email" list ("messageList1" or "DataGridView") be highlighted by the correct one, depending on the rule that I set;
- grouping "Email" by "Subject";
- grouping "Email" according to the criteria;
- different sorts of "Email";

Will it be difficult if I use to display the list of letters "DataGridView", and not "messageList1"?
Or for my tasks it is better to use "DataGridView"?
6. If it's easy for you, could you make a separate example where the name "Email" will be in the root of the tree?
Since it is made in "The Bat".

Thank you.

**Comment by jstedfast** [comment]
1. Yes, the folder structure depends on the structure returned by the IMAP server.
2. They can be sorted any way you want. I just sorted alphabetically as a simple case.
3. You can change the structure in any way you want - this is the world of computers, nothing is stopping you from doing anything you want to do.
4. This is all it takes: https://github.com/jstedfast/MailKit/blob/master/samples/ImapClientDemo/ImapClientDemo/FolderTreeView.cs#L138
5. Yes, you can do anything you want to do. It doesn't have to be a list. This demo is just a very simple demo to show you the simple cases. If you want to do something more complex, you can do it.
6. Do you not know how to use System.Windows.Forms? If you don't know how to use a tree view, then you are in way over your head and I can't help you.
