### ISSUE TITLE
Mailkit get mail list encoding problem

### ISSUE THREAD

**Issue by MuratGOZCU** [jstedfast/MailKit#760]
Hi,

There is no problem with the API, but there is no problem with encoding.

![image](https://user-images.githubusercontent.com/31828822/45944754-eda87b00-bff3-11e8-8260-090da175ca26.png)

![image](https://user-images.githubusercontent.com/31828822/45944834-40823280-bff4-11e8-8d3a-48f63490b118.png)

**Comment by jstedfast** [comment]
What's the problem with encoding? You aren't telling me anything useful.

**Comment by jstedfast** [comment]
Also that';s not a screenshot of anything MimeKit or MailKit produces. It looks like json which means it's a bug in your code.
