### ISSUE TITLE
SmtpStatusCode = 511

### ISSUE THREAD

**Issue by bender2k14** [jstedfast/MailKit#766]
While checking the behavior of MailKit, I sent an SMTP email with an nonexistent email address in the TO field.  MailKit threw an [`SmtpCommandException`](https://github.com/jstedfast/MailKit/blob/de2857c5d8fed2bf304bff0d8ff6cc59d0f1e8e9/MailKit/Net/Smtp/SmtpCommandException.cs#L87) with its [`StatusCode` property](https://github.com/jstedfast/MailKit/blob/de2857c5d8fed2bf304bff0d8ff6cc59d0f1e8e9/MailKit/Net/Smtp/SmtpCommandException.cs#L254) of `enum` type [`SmtpStatusCode`](https://github.com/jstedfast/MailKit/blob/de2857c5d8fed2bf304bff0d8ff6cc59d0f1e8e9/MailKit/Net/Smtp/SmtpStatusCode.cs) equal to `511`.  However, that `enum` does not have a state that corresponds to the value `511`.

Is this the expected behavior?  Would it be better if the value of this `enum` corresponded to one of its explicitly defined states?

If this is something that you care about, then I can post a MWE that exhibits this behavior.

**Comment by jstedfast** [comment]
The enum doesn't have a field for every possible status code (but it does have one for all of the [standard status code values](https://tools.ietf.org/html/rfc5321#section-4.2.3)).

To answer your more important question, though: Yes, this is (in a way) expected behavior. In general, the SmtpStatusCode will be a named value, though. So in that sense, it *is* unexpected :)

If you can c&p the segment of the log where this error is returned, maybe I can use that to try and figure out what I could add a named field to SmtpStatusCodes for this error.

**Comment by bender2k14** [comment]
Oh, actually, I think this is worse than I originally thought.  Since there is a problem with one of the recipients, I think the expected behavior is for an `SmtpCommandException` to be thrown with its [`ErrorCode` property](https://github.com/jstedfast/MailKit/blob/de2857c5d8fed2bf304bff0d8ff6cc59d0f1e8e9/MailKit/Net/Smtp/SmtpCommandException.cs#L222) equal to [`SmtpErrorCode.RecipientNotAccepted`](https://github.com/jstedfast/MailKit/blob/de2857c5d8fed2bf304bff0d8ff6cc59d0f1e8e9/MailKit/Net/Smtp/SmtpCommandException.cs#L64) and its [`Mailbox` property](https://github.com/jstedfast/MailKit/blob/de2857c5d8fed2bf304bff0d8ff6cc59d0f1e8e9/MailKit/Net/Smtp/SmtpCommandException.cs#L239) set to the problematic recipient.  Instead, the `ErrorCode` property is equal to [`SmtpErrorCode.UnexpectedStatusCode`](https://github.com/jstedfast/MailKit/blob/de2857c5d8fed2bf304bff0d8ff6cc59d0f1e8e9/MailKit/Net/Smtp/SmtpCommandException.cs#L71) and the `Mailbox` property is `null`.

I will create a test exhibiting this behavior and post it here.

**Comment by jstedfast** [comment]
Yea, I just took a look at the code and it should probably be looking at numeric ranges of the status codes rather than switch()'ing on the enum values explicitly.

I've got a patch I'm about to commit so this gets handled more properly.

**Comment by jstedfast** [comment]
This should solve it for you: https://github.com/jstedfast/MailKit/commit/df20447ec87d7cf968d0ffda518530ddd277850f

**Comment by bender2k14** [comment]
For some clarity, I will post some tests but only one test per comment.

Each test passes or fails as indicated when I use my configuration, which I have removed.  I understand that behavior can be SMTP server specific.  Just let me know if I can help by running an additional test using my configuration.  I am happy to assist.

The following test sends to a nonexistent email address from an email address with a different domain (i.e. `"thisdomainexists" != "thisdomaindoesnotexist"`).  It passes (using MailKit 2.0.6, which is the currently the latest release).  I don't think MailKit needs to make any changes based on this test.  I have just included it here for completeness.

```
[Fact] // passes
public void SmtpClient_Send_ToNonexistentFromDifferentDomain_Succeeds() {
  var host = "somesmtpserver.com";
  var port = 587;
  var secureSocketOptions = SecureSocketOptions.Auto;
  var username = "TODO";
  var password = "TODO";
  var fromEmailAddress = "exists@thisdomainexists.com";
  var toEmailAddress = "doesnotexist@thisdomaindoesnotexist.com";

  var message = new MimeMessage();
  message.From.Add(InternetAddress.Parse(fromEmailAddress));
  message.To.Add(InternetAddress.Parse(toEmailAddress));
  message.Subject = "Testing nonexistent recipient";
  message.Body = new TextPart("plain") { Text = "Some body" };
  message.MessageId = MimeUtils.GenerateMessageId();

  using (var smtpClient = new SmtpClient()) {
    try {
      smtpClient.Connect(host, port, secureSocketOptions);
      smtpClient.Authenticate(username, password);
      smtpClient.Send(message);
    } finally {
      smtpClient.Disconnect(true);
    }
  }
}
```

Shortly after running that test, the sender receives an email with the following (slightly redacted/modified) body.

> Hi. This is the qmail-send program at somesmtpserver.com.
I'm afraid I wasn't able to deliver your message to the following addresses.
This is a permanent error; I've given up. Sorry it didn't work out.
> 
> <thisemaildoesnotexist@thisdomaindoesnotexist.com>:
> Sorry, I couldn't find any host named thisdomaindoesnotexist.com. (#5.1.2)
> 
> --- Below this line is a copy of the message.
> 
> Return-Path: <exists@thisdomainexists.com>
> Received: (qmail 16035 invoked by uid 502); 9 Oct 2018 17:52:43 -0000
> Received: from unknown (HELO ?192.168.0.4?) (mailbox@halcomm.com@NNN.NNN.NNN.NNN)
>   by somesmtpserver.com with ESMTPA; 9 Oct 2018 17:52:43 -0000
> > From: exists@thisdomainexists.com
> > Date: Tue, 09 Oct 2018 12:52:36 -0500
> Subject: Testing nonexistent recipient
> Message-Id: <7HSWFVAXN5U4.1OSTYUK850FT3@EDMONDS>
> To: thisemaildoesnotexist@thisdomaindoesnotexist.com
> MIME-Version: 1.0
> Content-Type: text/plain; charset=utf-8
> 
> Some body

**Comment by bender2k14** [comment]
The difference between this test and the previous tests is that the FROM and TO email addresses used in this test share the same domain.  This test fails (using MailKit 2.0.6, which is the currently the latest release).

```
[Fact] // fails
public void SmtpClient_Send_ToNonexistentFromSameDomain_ThrowsSmtpCommandExceptionWithRecipientNotAcceptedErrorCodeAndNonNullMailbox() {
  var host = "somesmtpserver.com";
  var port = 587;
  var secureSocketOptions = SecureSocketOptions.Auto;
  var username = "TODO";
  var password = "TODO";
  var fromEmailAddress = "exists@thisdomainexists.com";
  var toEmailAddress = "doesnotexist@thisdomainexists.com";

  var message = new MimeMessage();
  message.From.Add(InternetAddress.Parse(fromEmailAddress));
  message.To.Add(InternetAddress.Parse(toEmailAddress));
  message.Subject = "Testing nonexistent recipient";
  message.Body = new TextPart("plain") { Text = "Some body" };
  message.MessageId = MimeUtils.GenerateMessageId();

  using (var smtpClient = new SmtpClient()) {
    try {
      smtpClient.Connect(host, port, secureSocketOptions);
      smtpClient.Authenticate(username, password);
      smtpClient.Send(message);
    } catch (SmtpCommandException e) {
      Assert.True(e.ErrorCode == SmtpErrorCode.RecipientNotAccepted && e.Mailbox != null); // fails: both arguments to && are false
    } finally {
      smtpClient.Disconnect(true);
    }
  }
}
```

Here is the (slightly redacted/modified) protocol log for this test.

> Connected to smtp://somesmtpserver.com:587/?starttls=when-available
> S: 220 somesmtpserver.com ESMTP
> C: EHLO [192.168.0.4]
> S: 250-somesmtpserver.com
> S: 250-STARTTLS
> S: 250-PIPELINING
> S: 250-8BITMIME
> S: 250-SIZE 0
> S: 250 AUTH LOGIN PLAIN CRAM-MD5
> C: STARTTLS
> S: 220 ready for tls
> C: EHLO [192.168.0.4]
> S: 250-somesmtpserver.com
> S: 250-PIPELINING
> S: 250-8BITMIME
> S: 250-SIZE 0
> S: 250 AUTH LOGIN PLAIN CRAM-MD5
> C: AUTH CRAM-MD5
> S: 334 xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
> C: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
> S: 235 ok, go ahead (#2.0.0)
> C: MAIL FROM:<exists@thisdomainexists.com>
> C: RCPT TO:<doesnotexist@thisdomainexists.com>
> S: 250 ok
> S: 511 sorry, no mailbox here by that name (#5.1.1 - chkuser)
> C: RSET
> S: 250 flushed
> C: QUIT
> S: 221 somesmtpserver.com

**Comment by bender2k14** [comment]
> df20447



> This should solve it for you: [df20447](https://github.com/jstedfast/MailKit/commit/df20447ec87d7cf968d0ffda518530ddd277850f)

Now I will try the previous test with this commit.

**Comment by jstedfast** [comment]
Awesome, thanks for testing this stuff out - it is a huge help!

**Comment by bender2k14** [comment]
My previous tests passes when run on your commit.  It changes the behavior to match my expectation, which is that both `e.ErrorCode == SmtpErrorCode.RecipientNotAccepted` and `e.Mailbox.ToString() == "doesnotexist@thisdomainexists.com"`.

Excellent work @jstedfast! :D

**Comment by jstedfast** [comment]
Awesome :)
