### ISSUE TITLE
Draft messages async, save and edit

### ISSUE THREAD

**Issue by juansh20** [jstedfast/MailKit#769]
Hello:

I wonder how can edit and save messages on draft folder?. 

Well, as a common client email, they have an option to save as draft. However, it works when an user clics on a button. how can I save messages like Gmail?. Its process is async, I gues it could be that. Maybe can you orientain me?  

I think to do it like this:
- When I save a message, I generate an ID using: 

mMessage.MessageId = MimeKit.Utils.MimeUtils.GenerateMessageId();
draftfolder.Append(mMessage, MessageFlags.Seen, mMessage.Date);

The message is save on the draft folder. After that, I have a doubt,When I have to save new changes of the message, do I have to delete this message and generate other id and save it again?. 

What would be the correct process in order to have an async process for draft email?

Can you help me?.

**Comment by jstedfast** [comment]
You mostly have it correct:

```csharp
mMessage.MessageId = MimeKit.Utils.MimeUtils.GenerateMessageId();
draftfolder.Append(mMessage, MessageFlags.Seen | MessageFlags.Draft);
```

The 2 changes I made to your code above are:

1. Set the \Draft flag
2. Don't set the INTERNALDATE (aka "arrived date") to the message's Date: header value, allow the IMAP server to set it to the current clock date/time value. There's no point in setting it to the message's Date: header.

> The message is save on the draft folder. After that, I have a doubt,When I have to save new changes of the message, do I have to delete this message and generate other id and save it again?

Yes. You can re-use the same message-id, though. Or you can generate a new one. It doesn't really matter.

> What would be the correct process in order to have an async process for draft email?

```csharp
mMessage.MessageId = MimeKit.Utils.MimeUtils.GenerateMessageId();
await draftfolder.AppendAsync(mMessage, MessageFlags.Seen | MessageFlags.Draft);
```

I get the feeling that's not what you are trying to ask, but I don't know what else you can mean.

Either way, I hope that helps.
