### ISSUE TITLE
DKIM

### ISSUE THREAD

**Issue by ad-mailosaur** [jstedfast/MailKit#77]
Thanks for creating this library. Will this library support DKIM signing at some point or is that outside of it's scope?

**Comment by Lone-Coder** [comment]
I was able to get DKIM.net and MailKit to work together using the following code:

        public static MimeMessage DkimSign(MimeMessage message, DkimSigner signer)
        {
            //message.BodyEncoding = signer.Encoding;
            //message.SubjectEncoding = signer.Encoding;
            //message.HeadersEncoding = signer.Encoding;


            // get email content and generate initial signature
            var email = Email.Parse(message.ToString());

            //if (!CanSign(email))
            //{
            //    throw new InvalidOperationException("Unable to Domain Key sign the message");
            //}

            var value = signer.GenerateDkimHeaderValue(email);

            // signature value get formatted so add dummy signature value then remove it
            message.Headers.Insert(0, DkimSigner.SignatureKey, value + new string('0', 70));
            email = Email.Parse(message.ToString()); //message.Parse();
            var formattedSig = email.Headers[DkimSigner.SignatureKey].Value;
            email.Headers[DkimSigner.SignatureKey].Value = formattedSig.Substring(0, formattedSig.Length - 70);

            // sign email
            var signature = signer.GenerateSignature(email);
            signature = Regex.Replace(signature, ".{70}", "$0\n\r "); // this is needed to make mimekit not butcher the signature with wierd us-ascii encoding
            value += signature;

            message.Headers.Remove(DkimSigner.SignatureKey);
            message.Headers.Add(new Header(DkimSigner.SignatureKey, value));

            return message;
        }
