### ISSUE TITLE
Why a Sender contains several addresses?

### ISSUE THREAD

**Issue by violen332** [jstedfast/MailKit#772]
I'm trying to write simple Mail Client on .NET Core as a service to my global system.

I'm little confused by the fact, that `MailKit.MessageSummary.Sender` contains `InternetAddress` which are list, because on my opinion sender should be only one.

Is it possible that message will contain several senders?
Can you give me a reference to some RFC or another document, where _several senders_ are described?'

**Comment by jstedfast** [comment]
`MailKit.MessageSummary.Sender` is an `InternetAddressList`, you mean, and yes, that is by design :)

[rfc3501, section 9 (Formal Syntax)](https://tools.ietf.org/html/rfc3501#section-9), defines the envelope as the following:

```
envelope        = "(" env-date SP env-subject SP env-from SP
                  env-sender SP env-reply-to SP env-to SP env-cc SP
                  env-bcc SP env-in-reply-to SP env-message-id ")"

env-bcc         = "(" 1*address ")" / nil

env-cc          = "(" 1*address ")" / nil

env-date        = nstring

env-from        = "(" 1*address ")" / nil

env-in-reply-to = nstring

env-message-id  = nstring

env-reply-to    = "(" 1*address ")" / nil

env-sender      = "(" 1*address ")" / nil

env-subject     = nstring

env-to          = "(" 1*address ")" / nil
```

**Comment by jstedfast** [comment]
Keep in mind this is the IMAP protocol syntax and that there *should* only be 1 address in the `Sender:` header according to [rfc5322, section 3.6.2 (Originator Fields)](https://tools.ietf.org/html/rfc5322#section-3.6.2).

You'll notice that `MimeKit.MimeMessage` is a single `MailboxAddress` and not a list.

**Comment by EvaTheHack** [comment]
On my opinion RFC is a respectable source, so if it says that Sender is non-list - it should not be a list. I can fix this, if you do not mind?

**Comment by jstedfast** [comment]
Uh... did you not see that I posted that the IMAP RFC says it is a list?

**Comment by EvaTheHack** [comment]
Sorry, your truth :)
