### ISSUE TITLE
Auth/login issue using IMAP

### ISSUE THREAD

**Issue by zeroxster** [jstedfast/MailKit#773]
The application is no longer able to authenticate against the server.
It's using the standard code:

```csharp
client.ServerCertificateValidationCallback = (s, c, h, e) => true;
client.Connect(emailClient.imap_server, (int)emailClient.imap_port, emailClient.imap_ssl);
client.Authenticate(emailClient.username, emailClient.password);
```

It was working fine up until last few days, so I assume that the issue may be with the server itself. Regardless here's the dump:

```
Connected to imap://iphere:143/?starttls=when-available
S: * OK The Microsoft Exchange IMAP4 service is ready.
C: A00000000 CAPABILITY
S: * CAPABILITY IMAP4 IMAP4rev1 LOGINDISABLED STARTTLS SASL-IR UIDPLUS MOVE ID UNSELECT CHILDREN IDLE NAMESPACE LITERAL+
S: A00000000 OK CAPABILITY completed.
C: A00000001 STARTTLS
S: A00000001 OK Begin TLS negotiation now.
C: A00000002 CAPABILITY
S: * CAPABILITY IMAP4 IMAP4rev1 AUTH=PLAIN AUTH=NTLM AUTH=GSSAPI SASL-IR UIDPLUS MOVE ID UNSELECT CHILDREN IDLE NAMESPACE LITERAL+
S: A00000002 OK CAPABILITY completed.
C: A00000003 AUTHENTICATE PLAIN AFRSRVNTT0xVVElPTlNcUFNURVNUAFBAc3N3MHJkMTIzNA==
S: A00000003 NO AUTHENTICATE failed.
C: A00000004 LOGIN "usernamehere" passwordhere
S: A00000004 NO LOGIN failed.
```

The following is problem details generated by win debug 

```
Problem signature:
  Problem Event Name:	CLR20r3
  Problem Signature 01:	ApplicationNameHere.exe
  Problem Signature 02:	1.0.0.0
  Problem Signature 03:	5be2b54a
  Problem Signature 04:	MailKit
  Problem Signature 05:	2.0.7.0
  Problem Signature 06:	5bd5fc49
  Problem Signature 07:	d76
  Problem Signature 08:	663
  Problem Signature 09:	MailKit.Security.Authentication
  OS Version:	6.3.9600.2.0.0.16.7
  Locale ID:	2057
  Additional Information 1:	5861
  Additional Information 2:	5861822e1919d7c014bbb064c64908b2
  Additional Information 3:	d2dd
  Additional Information 4:	d2ddcae25462e2b2f29684f70c88f75a

```

Attempted to remove PLAIN auth, downgrade to 2.0.1...2.0.4, upgrade to latest version etc. No avail, same error. 

Any / all help would be appreciated. :)

**Comment by jstedfast** [comment]
I presume that the `LOGIN` command in the above log had the correct username and password strings, right?

That suggests that it's a server bug (maybe your account password changed or the account was disabled or something?)

**Comment by jstedfast** [comment]
In the `LOGIN` command, are your username and password strings properly quoted/escaped? (i.e. if you have `\` in either string, is it escaped with another `\` character?)

**Comment by zeroxster** [comment]
Yes, it follows the correct format (it outputs from SQL as "HOST\\Username".

**Comment by jstedfast** [comment]
There are no other authorization methods.

I just wrote a unit test to make sure that MailKit was properly escaping `\`'s in the username and password strings in the `LOGIN` command and it is, so I have no other advice for you.

You'll need to contact your administrator and work with him (or her) to figure out the issue on the server end.

**Comment by jstedfast** [comment]
Here's the unit test: https://github.com/jstedfast/MailKit/commit/a083aef1527f00eee17e63a19fb4847ccd53c96d
