### ISSUE TITLE
Unable to create MailboxAddress for empty email address

### ISSUE THREAD

**Issue by The-Nutty** [jstedfast/MailKit#775]
**Describe the bug**
We are using MailKit/MimeKit to relay emails.
However it does not handle sending emails to from "<>", for more info about empty email addresses see [here](https://serverfault.com/questions/151955/why-an-empty-mail-from-address-can-sent-out-email), So when you try to send an email from an empty address it throws a MimeKit.ParseException exception.
**To Reproduce**
Below is my code where the first line throws a MimeKit.ParseException
``` C#
var from = new MailboxAddress("<>"); // throws MimeKit.ParseException
await client.SendAsync(email.Message, from, to);
```
Same code but using MailboxAddress.Parse
``` C#
var from = MailboxAddress.Parse("<>"); // throws MimeKit.ParseException
await client.SendAsync(email.Message, from, to);
```
Exception:
```
MimeKit.ParseException
  HResult=0x80131537
  Message=Invalid local-part at offset 0
  Source=MimeKit
  StackTrace:
   at MimeKit.InternetAddress.TryParseLocalPart(Byte[] text, Int32& index, Int32 endIndex, Boolean throwOnError, String& localpart)
   at MimeKit.InternetAddress.TryParseAddrspec(Byte[] text, Int32& index, Int32 endIndex, Byte[] sentinels, Boolean throwOnError, String& addrspec, Int32& at)
   at MimeKit.MailboxAddress.set_Address(String value)
   at Test.Program.<Main>d__0.MoveNext() in D:\other code\C#\Test\Test\Program.cs:line 39
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Test.Program.<Main>(String[] args)
```
**Expected behavior**
I can use mailKit to send emails from an empty address

**Desktop (please complete the following information):**
 - OS: Windows 10, 64 bit. As well as tested on AWS ECS (Amazon Linux i think)
- Mailkit version 2.0.7

**Comment by jstedfast** [comment]
Just do this:

```csharp
var from = new MailboxAddress (string.Empty);
```

The .ctor takes a pre-parsed address, not an un-parsed address.

**Comment by The-Nutty** [comment]
Thanks, i appreciate the quick response.

**Comment by jstedfast** [comment]
FWIW, the reason that `MailboxAddress.Parse()` doesn't work is because technically it isn't valid, even according to the SMTP address syntax.

The reason that `<>` is allowed in the `MAIL FROM` command is because `MAIL FROM` takes a `Reverse-Path` token which is *either* a mailbox address -or- `<>`.

```
   Reverse-path   = Path / "<>"

   Forward-path   = Path

   Path           = "<" [ A-d-l ":" ] Mailbox ">"

...

   Mailbox        = Local-part "@" ( Domain / address-literal )

   Local-part     = Dot-string / Quoted-string
                  ; MAY be case-sensitive


   Dot-string     = Atom *("."  Atom)

   Atom           = 1*atext

   Quoted-string  = DQUOTE *QcontentSMTP DQUOTE
```

Anyways, you should be good to go now :)

**Comment by The-Nutty** [comment]
Ahh ok, that makes sense, thanks for clearing it up.

**Comment by jstedfast** [comment]
No problem, I like to share these bits of trivia about email :)
