### ISSUE TITLE
MailKit V2.0.7: SmtpClient.OnNoRecipientsAccepted on established connection when server disconnects

### ISSUE THREAD

**Issue by Vinnietram** [jstedfast/MailKit#776]
Hi Jeffrey,

We have encountered a situation whereby on our client sites the SmtpClient.OnNoRecipientsAccepted 
(http://www.mimekit.net/docs/html/M_MailKit_Net_Smtp_SmtpClient_OnNoRecipientsAccepted.htm) is triggered when an attempt to send a message on
an already established connection that had been left hanging as the Server has disconnected, rather than the server not accepting the recipients.

We have managed to replicate the SmtpClient.OnNoRecipientsAccepted consistently with a small test app 
(https://github.com/Vinnietram/NoValidRecipientReplicate.git) with replication steps described in the README.md

Would appreciate if you can advise.

Thanks,

Vinh Tram
Glasswall Solutions Ltd.
Email: vtram@glasswallsolutions.com

**Comment by Vinnietram** [comment]
Hi Jeff,

Would you be able to provide an indication of when the next available release will be that contains this fix?

Thanks,

Vinh.

**Comment by jstedfast** [comment]
I hope to make a new release probably next weekend.

Thanksgiving is going to get in the way of this weekend and I'm working on writing a lot more unit tests as well and making a lot of improvements based on those new tests. I've also been adding some new functionality based on the IMAP4rev2 specifications that are close to being published.

Look for 2.1.0 to show up in the nuget feed when I do make the release.

**Comment by jstedfast** [comment]
Okay, MASSIVE new 2.1.0 release has been pushed. I would recommend reading the [ReleaseNotes.md](https://github.com/jstedfast/MailKit/blob/master/ReleaseNotes.md).
