### ISSUE TITLE
Shared Folder not Listed - IBM Lotus Notes

### ISSUE THREAD

**Issue by urbanswelt** [jstedfast/MailKit#786]
**Describe the bug**
Mailkit is not showing the Shared Folder.

**To Reproduce**
Connect and show content of SharedNamesspaces, only 1 Folder there.

**Expected behavior**
How can i see all the Folders like OCRNEW in my Screenshot?

**Screenshots**
This is how it looks inside -->

![image](https://user-images.githubusercontent.com/2138928/49989443-80651000-ff7a-11e8-8f0a-679030077e0b.png)

**Additional context**

It was tested with IMAPX before, and i was able to see all Folders and can work with it.
That means it is not authorisation Issue.

This is my coding in Powershell for Opening the Inbox, this is working -->

$mll = New-Object MailKit.Net.Imap.ImapClient ([MailKit.ProtocolLogger]::new("..\imap1.log"))

$ctoken = New-Object System.Threading.CancellationToken ($false)
$ssl = [MailKit.Security.SecureSocketOptions]::Auto
$mll.Connect($mailserver, 993, $ssl, $ctoken)
$mll.Authenticate(([System.Text.Encoding]::UTF8) , $username, $password , $ctoken)
$inbox = $mll.Inbox
$inbox.Open([MailKit.FolderAccess]::ReadOnly) | Out-Null
$src = $inbox.Search([MailKit.Search.SearchQuery]::All)
$msg = $src | select -Last 1
try { $id = [MailKit.UniqueId]($msg.Id) ; $inbox.GetMessage($id) }
catch { $_ }
$inbox.Close()
$mll.Disconnect($true , $ctoken)
Remove-Variable mll,inbox,msg,src,ctoken,ssl,mailserver,username,password,id

LOG INFO

S: * OK Domino IMAP4 Server Release 9.0.1FP9 ready Fri, 14 Dec 2018 08:38:25 +0100
C: D00000000 CAPABILITY
S: * CAPABILITY IMAP4rev1 AUTH=PLAIN LITERAL+ NAMESPACE QUOTA UIDPLUS
S: D00000000 OK CAPABILITY completed
C: D00000001 AUTHENTICATE PLAIN
S: + 

S: D00000001 OK AUTHENTICATE completed
C: D00000002 CAPABILITY
S: * CAPABILITY IMAP4rev1 AUTH=PLAIN LITERAL+ NAMESPACE QUOTA UIDPLUS
S: D00000002 OK CAPABILITY completed
C: D00000003 NAMESPACE
S: * NAMESPACE (("" "\\")) (("Other Users\\" "\\")) (("Public Folders\\" "\\"))
S: D00000003 OK NAMESPACE completed
C: D00000004 LIST "" "INBOX"
S: * LIST (\Noinferiors \HasNoChildren) "\\" Inbox
S: D00000004 OK LIST completed
C: D00000005 EXAMINE Inbox
S: * 1 EXISTS
S: * 0 RECENT
S: * OK [UIDVALIDITY 9] UIDs valid
S: * OK [UIDNEXT 9] Predicted next UID
S: * FLAGS (\Flagged \Seen \Answered \Deleted \Draft)
S: * OK [PERMANENTFLAGS ()] No permanent flags permitted
S: D00000005 OK [READ-ONLY] EXAMINE completed
C: D00000006 UID SEARCH ALL
S: * SEARCH 8
S: D00000006 OK SEARCH completed
C: D00000007 UID FETCH 8 (BODY.PEEK[])

Now i am lost -__

BouncyCastle.1.8.2
MailKit.2.1.0.3
MimeKit.2.1.0

**Comment by jstedfast** [comment]
Where's your code for listing the shared folders? MailKit clearly sees that the "Public Folders/" folder exists, but you never ask for the subfolders of it so how do you know it's not working?

**Comment by jstedfast** [comment]
I just realized maybe you are asking *how* to list the shared folders? If so, this is how:

```csharp
// get the "Public Folders/" folder
var shared = client.GetFolder (client.SharedNamespaces[0]); 
var subfolders = shared.GetSubfolders ();
```

GetSubfolders() will only get 1 level of folders deep, so if you want the full tree, you'll need to recursively call that method.

**Comment by urbanswelt** [comment]
Hi jstedfast,

thank you very much for your answer !
I have it tested like this but maybe i miss a step in between ? O.o

$shared = $mll.GetFolder($mll.SharedNamespaces[0])

$mll.SharedNamespaces[0] shows this -->
![image](https://user-images.githubusercontent.com/2138928/50019394-c352d200-ffd2-11e8-89b7-d50cfd31d308.png)

looks fine for me, now the second part -->
![image](https://user-images.githubusercontent.com/2138928/50019440-f8f7bb00-ffd2-11e8-95dd-1e7951b396ac.png)

I have miss something ?

**Comment by jstedfast** [comment]
I don't know what your code is doing, but it seems that you are trying to get messages or something from a child folder that is not open?

**Comment by urbanswelt** [comment]
The code does nothing at this time, only connect to the mailbox ,  has normaly to show all folders and disconnect the session at this time O.o

![image](https://user-images.githubusercontent.com/2138928/50025610-67924400-ffe6-11e8-9c0e-1ef52dcd982a.png)

**Comment by jstedfast** [comment]
I need an actual exception stack trace then, because a screenshot of an error where the text is truncated is not at all helpful.

**Comment by jstedfast** [comment]
Oh, I bet it's because of GetEnumerator (). That's not a MailKit bug, that's just you trying to expand an `ImapFolder` in your PowerShell UI thingy and it sees that `ImapFolder` is an `IEnumerable<MimeMessage>`, so it attempts to enumerate the MimeMessages within the folder.
