### ISSUE TITLE
MoveTo not copying email

### ISSUE THREAD

**Issue by MoeHamdan** [jstedfast/MailKit#787]
Hello

After upgrading to version 2.1.0.3 the MoveTo will only delete emails and CopyTo will do nothing, below is the log for MoveTo. I have downgraded to 2.0.7 to make it work again.

S: * CAPABILITY IMAP4 IMAP4rev1 CHILDREN IDLE QUOTA SORT ACL NAMESPACE RIGHTS=texk
S: B00000002 OK CAPABILITY completed
C: B00000003 NAMESPACE
S: * NAMESPACE (("" ".")) NIL (("#Public" "."))
S: B00000003 OK namespace command complete
C: B00000004 LIST "" "INBOX"
S: * LIST (\HasNoChildren) "." "INBOX"
S: B00000004 OK LIST completed
C: B00000005 SELECT INBOX
S: * 248 EXISTS
S: * 0 RECENT
S: * FLAGS (\Deleted \Seen \Draft \Answered \Flagged)
S: * OK [UIDVALIDITY 1541601851] current uidvalidity
S: * OK [UNSEEN 5] unseen messages
S: * OK [UIDNEXT 269] next uid
S: * OK [PERMANENTFLAGS (\Deleted \Seen \Draft \Answered \Flagged)] limited
S: B00000005 OK [READ-WRITE] SELECT completed
C: B00000006 LIST "" Trash
S: * LIST (\HasNoChildren) "." "Trash"
S: B00000006 OK LIST completed
C: B00000007 SEARCH UID MailKit.UniqueId[]
S: * SEARCH
S: B00000007 OK Search completed
C: B00000008 UID STORE 261 FLAGS (\Deleted)
S: * 247 FETCH (FLAGS (\Deleted) UID 261)
S: B00000008 OK UID completed
C: B00000009 EXPUNGE
S: * 247 EXPUNGE
S: B00000009 OK EXPUNGE Completed

**Comment by jstedfast** [comment]
Wow, that's embarrassing... thanks for reporting this.

Looks like I forgot to properly serialize the `IList<UniqueId>`. My unit tests used a `UniqueIdSet`, so `ToString()` on that properly serialized the list of uids, but you seem to be using `UniqueId[]`.

I've fixed this in git master and will be pushing out a new release (2.1.1) with the fix shortly.

**Comment by jstedfast** [comment]
2.1.1 has been released with this fix.
