### ISSUE TITLE
folder.Open command fails

### ISSUE THREAD

**Issue by lsamdahl** [jstedfast/MailKit#791]
I am writing a tool using MailKit to dump an email account from a hosted Exchange server to a MySQL database. I have run into an issue where I cannot access several mailboxes (folders) in the account. The curious thing about this is that all of the other folders work fine and even the problem folders will still open in Outlook. I would suspect some issue with the folders themselves if it weren't for the fact that they open in Outlook.

**Desktop (please complete the following information):**
 - OS: Windows 10

**Additional context**
Protocol Log:
S: * OK E16DN25B-S1E7 IMAP4 service is ready.
C: A00000000 CAPABILITY
S: * CAPABILITY IMAP4 IMAP4rev1 AUTH=PLAIN STARTTLS SASL-IR UIDPLUS MOVE ID UNSELECT CHILDREN IDLE NAMESPACE LITERAL+
S: A00000000 OK CAPABILITY completed.
C: A00000001 AUTHENTICATE PLAIN AGluZm9fYXJjaGl2ZTFAc3BlY3RyYNvbmljcy5uZXQAN1NxWWZOcXMjZDg=
S: A00000001 OK AUTHENTICATE completed.
C: A00000002 CAPABILITY
S: * CAPABILITY IMAP4 IMAP4rev1 AUTH=PLAIN SASL-IR UIDPLUS MOVE ID UNSELECT CLIENTNETWORKPRESENCELOCATION CHILDREN IDLE NAMESPACE LITERAL+
S: A00000002 OK CAPABILITY completed.
C: A00000003 NAMESPACE
S: * NAMESPACE (("" "/")) NIL NIL
S: A00000003 OK NAMESPACE completed.
C: A00000004 LIST "" "INBOX"
S: * LIST (\Marked \HasChildren) "/" INBOX
S: A00000004 OK LIST completed.
C: A00000005 LIST "" "%"
S: * LIST (\HasNoChildren) "/" Calendar
S: * LIST (\HasChildren) "/" Contacts
S: * LIST (\HasNoChildren \Trash) "/" "Deleted Items"
S: * LIST (\HasNoChildren \Drafts) "/" Drafts
S: * LIST (\Marked \HasChildren) "/" INBOX
S: * LIST (\HasNoChildren) "/" Journal
S: * LIST (\HasNoChildren \Junk) "/" "Junk E-mail"
S: * LIST (\HasNoChildren) "/" Notes
S: * LIST (\HasNoChildren) "/" Outbox
S: * LIST (\HasChildren \Sent) "/" "Sent Items"
S: * LIST (\HasNoChildren) "/" "Suggested Contacts"
S: * LIST (\HasChildren) "/" "Sync Issues"
S: * LIST (\HasNoChildren) "/" Tasks
S: A00000005 OK LIST completed.
Root folder: Sent Items
C: A00000006 LIST "" "Sent Items/%"
S: * LIST (\HasNoChildren) "/" "Sent Items/2006"
S: * LIST (\HasNoChildren) "/" "Sent Items/2007"
S: * LIST (\HasNoChildren) "/" "Sent Items/2008"
S: * LIST (\HasNoChildren) "/" "Sent Items/2009"
S: * LIST (\HasNoChildren) "/" "Sent Items/2010"
S: * LIST (\HasNoChildren) "/" "Sent Items/2011"
S: * LIST (\HasNoChildren) "/" "Sent Items/2012"
S: * LIST (\HasNoChildren) "/" "Sent Items/2013"
S: * LIST (\HasNoChildren) "/" "Sent Items/2014"
S: A00000006 OK LIST completed.
C: A00000007 EXAMINE "Sent Items/2008"
S: A00000007 NO Server Unavailable. 15

Exception Details:
MailKit.Net.Imap.ImapCommandException
  HResult=0x80131500
  Message=The IMAP server replied to the 'EXAMINE' command with a 'NO' response: Server Unavailable. 15
  Source=MailKit
  StackTrace:
   at MailKit.Net.Imap.ImapFolder.<OpenAsync>d__21.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MailKit.Net.Imap.ImapFolder.Open(FolderAccess access, CancellationToken cancellationToken)
   at ImapCopy2.Program.Main(String[] args) in E:\Documents\Spectrasonics\VS_projects\ImapCopy2\ImapCopy2\Program.cs:line 44

I'm pretty new to IMAP, so I greatly appreciate any help you can give me.
-Lee

**Comment by jstedfast** [comment]
```
C: A00000007 EXAMINE "Sent Items/2008"
S: A00000007 NO Server Unavailable. 15
```

Based on the log, I can't tell you why the server is refusing to open that folder, but it is saying you can't open it.

Normally if a folder is meant to be un-openable, it will have the `\Noselect` flag on it in the `LIST` response, but yours does not.

You'll need to contact your admin to ask why.

As for why Outlook works, it's probably because it isn't using IMAP but is instead using the Exchange protocol?
