### ISSUE TITLE
Custom IProtocolLogger implementation

### ISSUE THREAD

**Issue by coding786** [jstedfast/MailKit#792]
- I am implementing a custom Protocol Logger inheriting from IProtocolLogger
- What Type I should deserialize to from bytes array in LogClient & LogServer methods ? 
- I do not have any smtp server on my local machine. How can I simulate logging on my local machine ? 
- Does logging starts only after successful connection ? Right now its throwing exception when smpt 
  client  is trying to "Not - available" smtp server but no logging is done.   
- Any sample available to demonstrate Logging with smtp client ?

**Comment by jstedfast** [comment]
LogConnect() gets called after a successful connection is made. If the user uses a Connect() method that takes a pre-connected Socket or Stream, then it will get called pretty much immediately.

You can see this done here as an example: https://github.com/jstedfast/MailKit/blob/master/MailKit/Net/Smtp/SmtpClient.cs#L997

LogClient() gets called with the raw byte stream data that it just written to the underlying TCP stream.

LogServer() gets called with the raw byte stream data that was just read from the underlying TCP stream.

For an example of how to implement the IProtocolLogger interface, take a look at this implementation: https://github.com/jstedfast/MailKit/blob/master/MailKit/ProtocolLogger.cs
