### ISSUE TITLE
Contents of Buffer in LogClient & LogServer Methods

### ISSUE THREAD

**Issue by coding786** [jstedfast/MailKit#793]
I am developing a custom implementation of IProtocol Logger.

How best can we extract contents of Buffer bytes array into a C# object ? I want to log Buffer information in my custom database from LogClient & LogServer methods. Any samples ?

**Comment by jstedfast** [comment]
I don't have any samples for you, sorry. You'll have to figure that out on your own based on the type of database you are using and how you want to represent that data.
