### ISSUE TITLE
Deserialization of Buffer Byte Array in LogClient & LogServer

### ISSUE THREAD

**Issue by coding786** [jstedfast/MailKit#794]
I wanted to confirm if I can deserialize Buffer Byte Array received in LogClient & LogServer methods to some concerete C# object (MimeMessage or some other object)  ? 

The custom implementation example shown in below link converts byte array to stream to write to a file. 
My question is this the only way to extract information from buffer byte array ? 

https://github.com/jstedfast/MailKit/blob/master/MailKit/ProtocolLogger.cs

**Comment by jstedfast** [comment]
No, you can't deserialize the data into anything.

The bytes contained within the buffer are only useful for logging the raw IMAP, POP3, or SMTP commands and responses to a log file.
