### ISSUE TITLE
ProtocolLogger for applicationLogging ? 

### ISSUE THREAD

**Issue by coding786** [jstedfast/MailKit#796]
I wish to ascertain purpose of ProtocolLogger. Is this used for email server tracing purposes (like connection, mail success/failure) or it can be used for application Logging as well ? 

As LogClient & LogServer methods are called multiple times during a single mail request response cycle - should these placeholders be used for application local database logging ?

**Comment by jstedfast** [comment]
Can I ask you an honest question? What do YOU think it's for?

**Comment by coding786** [comment]
I think it is for tracing out client connection life cycle and looks for smtp commands n exceptions(m using smtp server).
I am trying to ascertain if the placeholders like LogClient & LogServer could be plugged with DAL layer so that whatever is spit out in LogClient & LogServer can be persisted in db. But as I saw a generated log file, I see that these methods are called multiple times during the whole lifecycle so it may not be a good idea to call DAL layer from these methods. I am thinking once the connection is disconnected, I can graze out the entire generated log and persist in one call to db. Any suggestions ?

**Comment by jstedfast** [comment]
Yes, the LogClient and LogServer methods are called multiple times per session (in a typical scenario, at least).

You could log to a MemoryStream using the default ProtocolLogger (make sure to pass `true` as the `leaveOpen` parameter) and then write the contents of the MemoryStream to your database once the client connection has been closed.
