### ISSUE TITLE
ProtocolLogger for applicationLogging

### ISSUE THREAD

**Issue by coding786** [jstedfast/MailKit#797]
Answering your query on closed request #796 :
I think it is for tracing out client connection life cycle and looks for smtp commands n exceptions(m using smtp server).
I am trying to ascertain if the placeholders like LogClient & LogServer could be plugged with DAL layer so that whatever is spit out in LogClient & LogServer can be persisted in db. But as I saw a generated log file, I see that these methods are called multiple times during the whole lifecycle so it may not be a good idea to call DAL layer from these methods. I am thinking once the connection is disconnected, I can graze out the entire generated log and persist in one call to db. Any suggestions ?

**Comment by jstedfast** [comment]
You don't need to open a new issue every time you respond. I still get notifications (and will still respond) to issues that have been closed.

Thanks.
