### ISSUE TITLE
IMailFolder IsSubscribed never assigned when getting folder with subscribeOnly at false ?

### ISSUE THREAD

**Issue by XavierDa** [jstedfast/MailKit#799]
Server : Exchange 2016 on-premise using IMAP

I was trying to get the subscribe status of all folders of a mailbox using iMailFolder.IsSubscribed boolean and it seems that it is always returning false if i just do ImapClient.GetFolders(namespace);

When i try to get it with ImapClient.GetFolders(namespace, true); i get true and the list of folders really subscribed but i wouls want to avoid doing two calls if possible.

**To Reproduce**
Call ImapClient.GetFolders(namespace); check that all folders have IsSubscribed At false

**Expected behavior**
Having the real state of subscription for folders

**Code**
```csharp
var client = new ImapClient(new ProtocolLogger(@"c:\Test\imap_log.txt"));
client.Connect("myawesomeserver.io");
client.Authenticate(new NetworkCredential("a@b.c", "one password"));
var listMailFoldersSubscribed2 = client.GetFolders(client.PersonalNamespaces[0]);
var listMailFoldersSubscribed = client.GetFolders(client.PersonalNamespaces[0], true);
client.Disconnect(true);
```

**logs**
```
S: * OK The Microsoft Exchange IMAP4 service is ready.
C: A00000000 CAPABILITY
S: * CAPABILITY IMAP4 IMAP4rev1 LOGINDISABLED STARTTLS SASL-IR UIDPLUS MOVE ID UNSELECT CHILDREN IDLE NAMESPACE LITERAL+
S: A00000000 OK CAPABILITY completed.
C: A00000001 STARTTLS
S: A00000001 OK Begin TLS negotiation now.
C: A00000002 CAPABILITY
S: * CAPABILITY IMAP4 IMAP4rev1 AUTH=PLAIN AUTH=NTLM AUTH=GSSAPI SASL-IR UIDPLUS MOVE ID UNSELECT CHILDREN IDLE NAMESPACE LITERAL+
S: A00000002 OK CAPABILITY completed.
C: A00000003 AUTHENTICATE PLAIN =>_<=
S: A00000003 OK AUTHENTICATE completed.
C: A00000004 CAPABILITY
S: * CAPABILITY IMAP4 IMAP4rev1 AUTH=PLAIN AUTH=NTLM AUTH=GSSAPI SASL-IR UIDPLUS MOVE ID UNSELECT XPROXY3 CLIENTNETWORKPRESENCELOCATION CHILDREN IDLE NAMESPACE LITERAL+
S: A00000004 OK CAPABILITY completed.
C: A00000005 NAMESPACE
S: * NAMESPACE (("" "/")) NIL NIL
S: A00000005 OK NAMESPACE completed.
C: A00000006 LIST "" "INBOX"
S: * LIST (\Marked \HasNoChildren) "/" INBOX
S: A00000006 OK LIST completed.
C: A00000007 LIST "" "*"
S: * LIST (\HasNoChildren) "/" Calendar
S: * LIST (\HasChildren) "/" Contacts
S: * LIST (\HasNoChildren \Trash) "/" "Deleted Items"
S: * LIST (\HasNoChildren \Drafts) "/" Drafts
S: * LIST (\HasNoChildren) "/" "&AMk-l&AOk-ments supprim&AOk-s"
S: * LIST (\Marked \HasNoChildren) "/" INBOX
S: * LIST (\HasNoChildren) "/" Journal
S: * LIST (\HasNoChildren \Junk) "/" "Junk Email"
S: * LIST (\HasNoChildren) "/" miaou
S: * LIST (\HasNoChildren) "/" Notes
S: * LIST (\HasNoChildren) "/" Outbox
S: * LIST (\HasNoChildren) "/" "RSS Feeds"
S: * LIST (\HasNoChildren \Sent) "/" "Sent Items"
S: * LIST (\HasChildren) "/" "Sync Issues"
S: * LIST (\HasNoChildren) "/" "Sync Issues/Conflicts"
S: * LIST (\HasNoChildren) "/" "Sync Issues/Local Failures"
S: * LIST (\HasNoChildren) "/" "Sync Issues/Server Failures"
S: * LIST (\HasNoChildren) "/" Tasks
S: * LIST (\HasNoChildren) "/" Trouloulou
S: A00000007 OK LIST completed.
C: A00000008 LSUB "" "*"
S: * LSUB (\HasNoChildren) "/" "&AMk-l&AOk-ments supprim&AOk-s"
S: * LSUB (\HasNoChildren) "/" Trouloulou
S: A00000008 OK LSUB completed.
C: A00000009 LOGOUT
S: * BYE Microsoft Exchange Server 2016 IMAP4 server signing off.
S: A00000009 OK LOGOUT completed.
```

**Comment by jstedfast** [comment]
You have to make 2 calls. There's no way around that, unfortunately. The base IMAP protocol does not have a way of getting the information you want in a single call.

The exception to this rule is when the IMAP server supports the LIST-EXTENDED capability in which case MailKit will request the subscribed status be returned as part of the LIST response and only 1 call is necessary.

In hindsight, the `IsSubscribed` property should have probably been a Nullable type instead of a true/false. Perhaps in a future v3.0 release, I can break this API and change it to a `Nullable<bool>`.

I could possibly add a `CheckSubscribed()` method, but the more I think about it, the more I think that it'd be a poor solution due to the fact that calling `GetFolders (namespace, true)` is a much more efficient solution.

Thoughts?

**Comment by XavierDa** [comment]
I feared that it was the answer after looking a little at the RFC...

The `Nullable<bool>` seems to be the the good answer here, `CheckSubscribed()` look like a band-aid more than anything. 

In fact it raise a question : Is `IsSubscribed` used/assigned anywhere ?

**Comment by jstedfast** [comment]
It's assigned whenever the LSUB command is used to any folder that is returned in the list.

You can check out the code that parses the LIST/LSUB responses here: https://github.com/jstedfast/MailKit/blob/master/MailKit/Net/Imap/ImapUtils.cs#L425

What it does is it tries to merge appropriate flags from previously known folder attributes (e.g. attributes that each folder had in a previous LIST or LSUB response).
