### ISSUE TITLE
SMTP Credentials "loss"

### ISSUE THREAD

**Issue by gregsohl** [jstedfast/MailKit#800]
Using MailKit for SMTP in an TLS enabled environment against a large load-balanced SMTP server farm. Occasionally we are "losing" credentials - i.e. the password sent to the server is very wrong - i.e. not what I believe has been set on the mail client and not valid base64 encoding

 - while the user sent is still correct.

I'm not finding in my code where the Credentials object passed to MailKit could get botched, though I can't rule my own error out.

- We are forcing LOGIN authentication, based on the user's configuration of our system. 
- I've not been able to reproduce in a developer environment
- I'm not sure when the issue occurs, how long the instance of the MailKit smtp client has existed.

Quick question: Is there any kind of timeout for Credentials in the SMTP client where credentials are invalidated? I'm not seeing it, but thought I would ask the expert since I'm not finding my answer.

Any ideas anyone might have would be appreciated! Thank you.

Redacted logs are attached
[SMTP Log - Fail.txt](https://github.com/jstedfast/MailKit/files/2725072/SMTP.Log.-.Fail.txt)
[SMTP Log - Success.txt](https://github.com/jstedfast/MailKit/files/2725073/SMTP.Log.-.Success.txt)

**Comment by jstedfast** [comment]
> Quick question: Is there any kind of timeout for Credentials in the SMTP client where credentials are invalidated?

Nope. MailKit doesn't even hang on to the credentials, it uses them immediately and then forgets them.

You can see where MailKit does the base64 encoding/decoding of the challenges/responses here: https://github.com/jstedfast/MailKit/blob/master/MailKit/Security/SaslMechanism.cs#L267

You can see the logic that calculates the username/password for the LOGIN mechanism here: https://github.com/jstedfast/MailKit/blob/master/MailKit/Security/SaslMechanismLogin.cs#L265

I'm not seeing anything obviously wrong with either piece of code. Perhaps you could place a breakpoint inside of the `SaslMechanismLogin.cs` code and seeing what the values in the `NetworkCredential` are?

**Comment by gregsohl** [comment]
Jeff, thanks for the help on this. Sorry for the delayed response. Still digging for an answer. If I find something interesting I'll reply back here. Done for now.
