### ISSUE TITLE
SMTP implicit SSL

### ISSUE THREAD

**Issue by ZeusZoe** [jstedfast/MailKit#801]
Hi,
I've a problem to use it with implicit SSL.
I get the 

> An error occurred while attempting to establish an SSL or TLS connection.\r\n\r\nOne possibility is that you are trying to connect to a port which does not support SSL/TLS.\r\n\r\nThe other possibility is that the SSL certificate presented by the server is not trusted by the system for one or more of the following reasons:\r\n1. The server is using a self-signed certificate which cannot be verified.\r\n2. The local system is missing a Root or Intermediate certificate needed to verify the server's certificate.\r\n3. The certificate presented by the server is expired or invalid.\r\n\r\nSee https://github.com/jstedfast/MailKit/blob/master/FAQ.md#InvalidSslCertificate for possible solutions.

 error.

This is my code:
```
            var attachment = new MimePart("text", "xml")
            {
                Content = new MimeContent(System.IO.File.OpenRead(filename)),
                ContentDisposition = new ContentDisposition(ContentDisposition.Attachment),
                ContentTransferEncoding = ContentEncoding.Base64,
                FileName = System.IO.Path.GetFileName(filename)
            };

            var multipart = new Multipart("mixed");
            // Aggiungo l'allegato
            multipart.Add(attachment);
            // Contenuto dell'email, può essere vuota
            multipart.Add(new TextPart("plain") { Text = "" });

            var message = new MimeMessage();
            message.To.Add(new MailboxAddress("xxx@xxx.xx"));
            message.From.Add(new MailboxAddress("xxxx@pec.it"));
            message.Subject = "Fattura";
            //message.Body = multipart;

            using (var client = new SmtpClient())
            {
                try
                {

                    client.Connect("smtps.pec.aruba.it", 465, MailKit.Security.SecureSocketOptions.SslOnConnect);
                    client.Authenticate("xxx@pec.it", "xxxxxxxx");

                    client.Send(message);

                    client.Disconnect(true);
                }
                catch (Exception ex) { }
            }

```
Thanks

**Comment by jstedfast** [comment]
Have you followed the directions in the exception message?
