### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by michelevirgilio** [jstedfast/MailKit#807]
I'm trying to fetch messages with pagination.
I've tried the sample in wiki:

```
// let's search for all messages received after Jan 12, 2013 with "MailKit" in the subject...
var query = SearchQuery.DeliveredAfter (DateTime.Parse ("2013-01-12"))
    .And (SearchQuery.SubjectContains ("MailKit")).And (SearchQuery.Seen);

// let's do the same search, but this time sort them in reverse arrival order
var orderBy = new [] { OrderBy.ReverseArrival };
foreach (var uid in inbox.Search (query, orderBy)) {
	var message = inbox.GetMessage (uid);
	Console.WriteLine ("[match] {0}: {1}", uid, message.Subject);
}
```
but the compiler is complaining that `inbox.Search (query, orderBy)` is not a valid method.

My idea is to get messages ordered by date desc (or uid desc) in a specific page (from 1 to 10, from 11 to 20, etc).
Any clue?
Thanks!

**Comment by jstedfast** [comment]
You need to use `Sort()` instead of `Search()`.

The wiki hasn't been updated in 2 years. I just deleted it.

Use https://www.mimekit.net/docs instead.

**Comment by delciopolanco** [comment]
Have any example? I’m currently working on it and I haven’t found any reference on the wiki.

**Comment by jstedfast** [comment]
Here's the docs on Sort: http://www.mimekit.net/docs/html/Overload_MailKit_Net_Imap_ImapFolder_Sort.htm
