### ISSUE TITLE
MailKit Pop3 DeleteMessage followed by Disconnect....

### ISSUE THREAD

**Issue by e-novative** [jstedfast/MailKit#810]
MailKit Pop3 DeleteMessage followed by Disconnect....deletes messages.  Yea.
On Exchange Server, however, it does not put the 'deleted' message into the deleted folder.
Is there a way to move it to "deleted' or to another folder?  I know, this is an IMAP function, not Pop3, but hey, I can ask?   I want to find a way to preserve the original email.  

The other option is when inbox scanned a second time, not to see previously seen email.

**Comment by jstedfast** [comment]
that's not something that can be done using POP3. You need to use IMAP.
