### ISSUE TITLE
Different authentication mechanisms & capabilities when used on a server

### ISSUE THREAD

**Issue by adiii4** [jstedfast/MailKit#813]
While using MailKit in a web service (run on an IIS web server) I got the error message `SMTP Server does not support authentication`. It was working on my local machine but now it is not working on the server.

The error appears because of the following code lines in MailKit:

```csharp

if ((capabilities & SmtpCapabilities.Authentication) == 0)
   throw new NotSupportedException ("The SMTP server does not support authentication.");
```

I figured out that when I use it **locally** I get the following properties:

**AuthMechanisms:**
`NTLM, LOGIN, GSSAPI`

**Capabilities:**
`Size, Dsn, EnhancedStatusCodes, Authentication, EightBitMime, Pipelining, BinaryMime, Chunking`

---

When I use it **on the server** I get the following properties:

**AuthMechanisms:**
*None*

**Capabilities:**
`Size, Dsn, EnhancedStatusCodes, EightBitMime, Pipelining, BinaryMime, Chunking`

**Why are the authentication mechanisms & capabilities different even though I connect the same way locally and on the server?**

**Comment by jstedfast** [comment]
Maybe your SMTP server responds different depending on which network the incoming connection is coming from?

Who knows. You need to ask your admin.

**Comment by adiii4** [comment]
Okay, that's what I thought too but I wasn't sure. Thanks for your help.
