### ISSUE TITLE
Mailkit 2.1.2 + .Net 4.5.2 Error on SmtpClient.Connect

### ISSUE THREAD

**Issue by Alexboxat** [jstedfast/MailKit#814]
**Desktop:**
 - Windows 7 SP1 x32 x64
 - Mailkit 2.1.2
 - .Net Framework 4.5.2  (there is no error with 4.6 and 4.7)

**To Reproduce**
1. Try to connect to any SMTP server:
client.Connect("smtp.gmail.com", 587, SecureSocketOptions.Auto);

I get Exception:

Specified argument was out of the range of valid values.
Parameter name: newAddress

at
SmtpClient.Connect   at System.Net.IPAddress..ctor(Int64 newAddress)
   at System.Net.IPAddress.MapToIPv4()
   at MailKit.Net.Smtp.SmtpClient.<SendEhloAsync>d__61.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MailKit.Net.Smtp.SmtpClient.<EhloAsync>d__62.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at MailKit.Net.Smtp.SmtpClient.<ConnectAsync>d__70.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MailKit.Net.Smtp.SmtpClient.Connect(String host, Int32 port, SecureSocketOptions options, CancellationToken cancellationToken)

**Comment by Alexboxat** [comment]
Hello,

I don’t know how to force VS 2017 to use 4.5 framework for debug. And I cant just delete others since VS requires 4.6

Regards,
Alex

**Comment by Alexboxat** [comment]
I’ve installed VS 2015 on Windows 7 SP1.

When I try to compile MailIt 2.1.2:

------ Build started: Project: MailKit.Net45, Configuration: Debug Any CPU ------
C:\Users\Lucky\Desktop\MailKit-2.1.2\MailKit\Net\Imap\ImapEventGroup.cs(296,37,296,43): error CS1026: ) expected
C:\Users\Lucky\Desktop\MailKit-2.1.2\MailKit\Net\Imap\ImapEventGroup.cs(296,43,296,44): error CS1002: ; expected
C:\Users\Lucky\Desktop\MailKit-2.1.2\MailKit\Net\Imap\ImapEventGroup.cs(296,43,296,44): error CS1513: } expected
C:\Users\Lucky\Desktop\MailKit-2.1.2\MailKit\Net\Imap\ImapEventGroup.cs(394,12,394,29): error CS1520: Method must have a return type
C:\Users\Lucky\Desktop\MailKit-2.1.2\MailKit\Net\Imap\ImapEventGroup.cs(675,1,675,2): error CS1022: Type or namespace definition, or end-of-file expected
C:\Users\Lucky\Desktop\MailKit-2.1.2\MailKit\Net\Imap\ImapUtils.cs(85,35,85,41): error CS1026: ) expected
C:\Users\Lucky\Desktop\MailKit-2.1.2\MailKit\Net\Imap\ImapUtils.cs(85,41,85,42): error CS1002: ; expected
C:\Users\Lucky\Desktop\MailKit-2.1.2\MailKit\Net\Imap\ImapUtils.cs(85,41,85,42): error CS1513: } expected
C:\Users\Lucky\Desktop\MailKit-2.1.2\MailKit\Net\Imap\ImapUtils.cs(526,75,526,84): error CS1003: Syntax error, ',' expected
C:\Users\Lucky\Desktop\MailKit-2.1.2\MailKit\Envelope.cs(453,57,453,61): error CS1003: Syntax error, ',' expected
========== Build: 0 succeeded, 1 failed, 1 up-to-date, 0 skipped ==========

**Comment by jstedfast** [comment]
Looks like some versions of .NET have a bug: https://stackoverflow.com/questions/23608829/why-does-ipaddress-maptoipv4-throw-argumentoutofrangeexception

Check out the accepted answer to that StackOverflow question.

What environment are you running .NET 4.5.2? Is it running on Windows? Mac? Linux? Is it using Mono or CoreCLR?

I wonder if it has all of the service packs installed?

**Comment by Alexboxat** [comment]
1. Windows 7 32 bit with Service Pack 1.

2. It has Service Pack 1 + All Important Updates Installed till now (except Optional).

**Comment by jstedfast** [comment]
Can you try building the latest revision to see if that fixes things for you?

I don't want to make a release only to find out it doesn't fix the issue.

Thanks.

**Comment by Alexboxat** [comment]
Yes. It works now.

Thank you very much.

**Comment by GraemeMorton** [comment]
@Alexboxat I was getting the above problem and your change resolved it ... however I am now getting another error but that may be unrelated :)

**Comment by GraemeMorton** [comment]
@jstedfast I was getting the above problem and your change resolved it ... however I am now getting another error but that may be unrelated :)

**Comment by jstedfast** [comment]
What problem are you getting now?

**Comment by GraemeMorton** [comment]
It was a "relay access denied" error but I think it was the wrong relay server for that specific part of the network so it is resolved now as well :)

**Comment by jstedfast** [comment]
ok

**Comment by niemyjski** [comment]
Just an update... I was able to get connected using the following code:

```cs
 await client.ConnectAsync("imap.gmail.com", 993, SecureSocketOptions.SslOnConnect, cancellationToken);
            
var oauth2 = new SaslMechanismOAuth2(username, apiKey);
await client.AuthenticateAsync(oauth2, cancellationToken);
```

**Comment by KrishnaramaGit** [comment]
Hello,

I was getting an exception in our production environment as "Method not found: '!!0[] System.Array.Empty()'." at the time of connecting,
client.Connect("smtp.gmail.com", 587, SecureSocketOptions.Auto);
While searching for the issue it is showing me to upgrade the framework version. But its working fine in the development and UAT. 

Thanks in advance.

**Comment by jstedfast** [comment]
@KrishnaramaGit you somehow managed to leave out all of the important details of the issue you are hitting :-\

1. What is the StackTrace of the exception you are hitting?
2. What version of .NET are you using in production?
3. What version of .NET are you using in development?

My guess is that you are compiling your program on a system with a newer version of .NET than your production machine has, and so even though your development machine has Array.Empty, your production machine does not.
