### ISSUE TITLE
Invalidation of passwords in memory after use

### ISSUE THREAD

**Issue by mattherman** [jstedfast/MailKit#817]
Hello,

A security review performed on the software found a few issues related to passwords and possible heap inspection. I am not a security expert, so forgive me if anything in my explanation is inaccurate.

In a few places in the library passwords are retrieved from a `NetworkCredential` instance and used either as strings or immediately converted to byte arrays. It is my understanding that this increases the possibility that an attacker with access to process memory would be able to potentially retrieve the plaintext passwords. The `NetworkCredential` type stores the passwords as a `SecureString` which takes further precautions to limit exposure of the data, but once it is read into a string variable it is less safe. Since strings are immutable and not pinned objects they may remain in memory, possibly in multiple locations, until the garbage collector happens to remove it.

One suggestion for reducing the risk of this is to store passwords in mutable data structures such as byte arrays and then "zeroizing" them immediately after use to reduce the duration of exposure.

The files + line numbers flagged by the scan were the following:

```
MailKit/Net/Pop3/Pop3Client.cs              642
MailKit/Security/Ntlm/Type3Message.cs       107
MailKit/Security/SaslMechanismCramMd5.cs    160
MailKit/Security/SaslMechanismNtlm.cs       181
MailKit/Security/SaslMechanismScramBase.cs  321
MailKit/Security/Ntlm/Type3Message.cs       107
MailKit/Net/Proxy/Socks5Client.cs           207
MailKit/Security/SaslMechanismPlain.cs      275
```

Again, I'm not a security expert. I'm working with a potentially naive understanding of these concepts, but was wondering if this is something that is potentially an issue worth fixing.

Thanks!

**Comment by jstedfast** [comment]
MailKit can't easily use SecurePassword (cross platform problems), but I've added Array.Clear() to the places where the password string is used as a byte buffer.
