### ISSUE TITLE
"The POP3 server has unexpectedly disconnected." when invoking Pop3Client.DeleteMessage on email with large attachments

### ISSUE THREAD

**Issue by polterguy** [jstedfast/MailKit#82]
Howdy, don't know if this is a Gmail pop3 issue to be honest with you, or if it's in MailKit, but I am using MailKit wrapped in my own code to fetch emails from Gmail using pop3, and the above exception is thrown on the same message every time I run my logic

I can download more than 200 messages, and successfully mark them as deleted, but when I come to this one email which has attachments worth about roughly 20 MB, the message is successfully downloaded, but when I invoke DeleteMessage afterwards, the above exception is thrown

This is not the last email in my account, I've still got about 150 more emails before it's done fetching

ps, this is on Windows using the latest NuGet package of MailKit, version 0.94.0.0

I've tried turning off about every single bell and whistle I can imagine on my system, such ass firewalls, virus killers, and everything. Still the behavior seem to remain, but as I said, only on this specific email ...

btw, I am downloading messages in batches of 5-10 messages each time. If I try to download all messages at once within one using (Pop3Client ...) session, the same exception appears earlier, on a different email, after exactly 49 messages instead of no 210 as is now ...

I'd love to send you code, but I don't think you'd understand it, since it's for the most parts written in Magix Illuminate's Hyperlisp, wrapping C# through active event handlers ...

Which would mean you'd have to download Magix to even begin to test it ...

**Comment by newexception** [comment]
I had a similar problem, solved it like this:

`client.CheckCertificateRevocation = false;  `
