### ISSUE TITLE
How get full header email after send by SMTP

### ISSUE THREAD

**Issue by Maelou04** [jstedfast/MailKit#820]
Hello, 

I trying to get full header information added by Smtp server when message have been sent inside SmtpClient_MessageSent event. When i read MimeMessage and convert it into a Raw message i can't see some importants Headers informations like DKIM-SIGNATURE or Date and all other added by smtp server. A way to do that ?

Thank.

**Comment by jstedfast** [comment]
If you Cc or Bcc yourself and then download the sent message via POP3 or IMAP, I suppose you could get that info, but otherwise, no.
