### ISSUE TITLE
text-only PDFs corrupt when being emailed

### ISSUE THREAD

**Issue by jsultana-jeal** [jstedfast/MailKit#821]
When a text-only (i.e - no image or other binary data) PDF is emailed, the PDF received shows as a blank document. 

We did a hexadecimal compare of the original and the received PDF, and wherever the original PDF had a 0A (10) byte, the original file had a 0A followed by 1D (13). It appears as though whenever there was a newline in the original PDF, the received PDF had a newline followed by a carriage return. This suggests that Mailkit is treating the PDF as text and adding extra carriage returns, when it should not. 

As a workaround, you can prevent this behaviour by adding any kind of image (even a 1x1 white pixel) to the PDF and it'll then be emailed correctly.

**Comment by jstedfast** [comment]
Make sure to send PDF's as base64 and not quoted-printable.

This is up to you to determine.
