### ISSUE TITLE
WinForms SMTP sample

### ISSUE THREAD

**Issue by gregsohl** [jstedfast/MailKit#826]
Jeff, I have a fairly robust WinForms SMTP sample that I wrote as a test bed for techniques during our adoption of MailKit, replacing existing use of .NET SMTP . Would you be interested in adding it to the samples for MailKit?

**Comment by jstedfast** [comment]
sure

**Comment by jstedfast** [comment]
Are you still interested in submitting a WinForms SMTP sample?

**Comment by gregsohl** [comment]
Yes. Should be able to get it cleaned up and code standards set to MailKit standards this week.

**Comment by jstedfast** [comment]
Ok, awesome. Just wasn't sure if you had seen my original response ;-)

I'm not much of a WinForms/WPF programmer (you can probably tell by looking at my existing samples), so I struggle a bit with writing samples.

**Comment by jstedfast** [comment]
Any update on this? Would love to have more samples.
