### ISSUE TITLE
Improve download speed

### ISSUE THREAD

**Issue by atiyka** [jstedfast/MailKit#829]
Hi,
I was searching a lot without getting answer. I'd like to ask if it's possible in MailKit to increase the fetch size, or disable the partial fetch to achieve a faster mail download? Or is there any other way to speed up the download?
I'm asking because in [JavaMail ](https://stackoverflow.com/questions/35532797/how-to-speed-up-time-when-using-java-mail-to-save-attachments) is possible to set these values.
If nothing similar exists, would it be possible to implement it?

Thanks for your answer,
Attila

**Comment by jstedfast** [comment]
If you want to change the partial fetch size, call a `GetStream()` method that takes `offset` and `count` parameters, like one of these:

http://www.mimekit.net/docs/html/M_MailKit_Net_Imap_ImapFolder_GetStream.htm
http://www.mimekit.net/docs/html/M_MailKit_MailFolder_GetStream.htm

**Comment by atiyka** [comment]
Cool, thank you very much!
