### ISSUE TITLE
Textbody return always null

### ISSUE THREAD

**Issue by mavel72** [jstedfast/MailKit#832]
Hi, I'm trying to read mail using a c# console program with mailkit.
I use this code:

```
private static MimeMessage ReceiveMails()
      {
         MimeMessage message = new MimeMessage();

         using( var client = new Pop3Client() )
         {
            client.Connect( "outlook.office365.com", 995, true );

            client.Authenticate( "xxx@yyy.com", "xxxxxxx" );

            for( int i = 0; i < client.Count; i++ )
            {
               message = client.GetMessage( i );
               Console.WriteLine( "Body: {0}", message.TextBody );
            }

            client.DeleteAllMessages();
            client.Disconnect( true );
            return message;
         }

      }
```

While mail.Subject always return the correct subject, TextBody always returns null.
I searched the internet for answers but I only found imap examples and by now I can't read my mail body. Thanks!

**Comment by jstedfast** [comment]
Are you sure that these messages *have* a `text/plain` body? Or do they have something else like a `text/html` body?

**Comment by mavel72** [comment]
I'm writing the mail from Outlook and simply writing a word in the body. I don't know if Outlook send mails with text/plain format. If it is the case, can I try HtmlBody instead? Thank you very much!

**Comment by mavel72** [comment]
Ok I tried HtmlBody and it gets the body. Thanks for your time.

**Comment by mavel72** [comment]
Anyways, how can I convert html to get only the "text" part of htmlbody?

**Comment by jstedfast** [comment]
Converting HTML into plain text is not a lossless conversion, you're going to lose formatting.

But if that's really what you want to do, you can either use the MimeKit.Text.HtmlTokenizer to parse the HTML and just extract out the character data.

for example:

```csharp
using (var reader = new StringReader (message.HtmlBody)) {
    var tokenizer = new HtmlTokenizer (reader);
    HtmlToken token;
    
    while (tokenizer.ReadNextToken (out token)) {
        switch (token.Kind) {
	case HtmlTokenKind.Data:
	    var text = (HtmlDataToken) token;
            Console.Write (text.Data);
            break;
        case HtmlTokenKind.Tag:
            var tag = (HtmlTagToken) token;
            switch (tag.Id) {
            case HtmlTagId.Br:
            case HtmlTagId.P:
                Console.WriteLine ();
                break;
            }
            break;
    }
}
```

**Comment by mavel72** [comment]
Thank you very much, I have to send body text to a telegram bot so I need ony plain text.

**Comment by jstedfast** [comment]
Just change your Outlook settings to send plain text instead of HTML

**Comment by mavel72** [comment]
Thanks!!!
