### ISSUE TITLE
SMTP Client - Capture response from successful SendAsync

### ISSUE THREAD

**Issue by tvalenta** [jstedfast/MailKit#833]
Following successful submission of a message via the SMTP client, I would like the ability to capture the server response for the specific message.

For example,  given a successful call
    `await client.SendAsync (message).ConfigureAwait(false);` , 

I would like to capture the server's response, such as
    `250 2.0.0 x2KMTNgW014937 Message accepted for delivery`

I've seen this as part of the protocol log, but it's only the delivery response that I would like to write to application logs.

**Comment by jstedfast** [comment]
You should be able to get that string now if you connect to the `MessageSent` event.

The `MessageSentEVentArgs.Response` should be the string you are looking for.

**Comment by tvalenta** [comment]
Thanks for setting me on the right path. I had tried to get this information from a result of SendAsync, and didn't catch that it had to be an event handler. The `MessageSent` event got me what I needed.
