### ISSUE TITLE
How can check if message is meeting ?

### ISSUE THREAD

**Issue by JorgelGtzGtz** [jstedfast/MailKit#837]
Hello I don't found example for check if message is meeting invitation, could you help me with a example?

**Comment by jstedfast** [comment]
A message that contains a meeting request will have a MIME part with a mime-type of `text/calendar` and typically also have a `method=REQUEST` parameter in the `Content-Type` header.

```
Content-Type: text/calendar; charset="utf-8"; method=REQUEST
```

A simple way to check for this would be something like this:

```csharp
var meeting = message.BodyParts.OfType<TextPart> (x => {
    return x.ContentType.Parameters.TryGetValue ("method", out string method) && method.Equals ("REQUEST", StringComparison.OrdinalIgnoreCase);
});
```

And then you could use whatever ical parser you choose to parse the `meeting.Text`, or, if the ical parser of your choosing prefers a Stream-based input, you could do:

```csharp
using (var stream = meeting.Content.Open ()) {
    // pass stream to the ical parser
}
```

Hope that helps.
