### ISSUE TITLE
Connection  to server through proxy is freezes

### ISSUE THREAD

**Issue by dronamiusSlIVA** [jstedfast/MailKit#840]
client.ProxyClient = new MailKit.Net.Proxy.Socks4Client(string ProxyHost,int ProxyPort));
client.Connect (string host, int port ,bool ssl);
On the connection string, execution is frozen. This happens in 10% of cases of connection.

**Comment by jstedfast** [comment]
Are you sure the problem isn't the proxy server?

**Comment by dronamiusSlIVA** [comment]
Yes. Only with proxy. I was tested many times.

**Comment by jstedfast** [comment]
I need you to step through the proxy code in a debugger and tell me which line (in Proxy4Client.cs) is hanging and what the variables are.

**Comment by dronamiusSlIVA** [comment]
http://prntscr.com/n8qbkz

I could not add the source code from the github to my project.

**Comment by dronamiusSlIVA** [comment]
I can't add the source code because of this error http://prntscr.com/n8s978

**Comment by jstedfast** [comment]
That's C# 7 syntax which I guess your VS doesn't support.

All you need to do is copy Socks4Client.cs, SocketUtils.cs and maybe ProxyClient.cs and then just re-namespace them so that they don't conflict with the MailKit classes.

**Comment by dronamiusSlIVA** [comment]
I couldn't do what you said. I think you have not set a timeout for stream

**Comment by jstedfast** [comment]
Ok, good luck.
