### ISSUE TITLE
How can get Emails in Junk E-mail folder

### ISSUE THREAD

**Issue by JorgelGtzGtz** [jstedfast/MailKit#844]
Hello first this is awesome library, I search example for get the email of the junk folder, How can get emails for the Junk E-mail folder?

**Comment by jstedfast** [comment]
If your IMAP server supports the SPECIAL-USE or XLIST extension, then you can get it like this:

```csharp
var junkFolder = client.GetFolder (SpecialFolder.Junk);
```

If not, then you'll need to know the full path of the junk folder and get it like this:

```csharp
var junkFolder = client.GetFolder (pathToJunkFolder);
```

**Comment by rakhikarampuri** [comment]
How to get full path of jun folder ?

**Comment by jstedfast** [comment]
@rakhikarampuri That depends on your IMAP server and where it decided to create it, if it even has a junk folder (not all do).

You are going to have to figure that out by yourself, unfortunately, because I do not have an answer for that.
