### ISSUE TITLE
Problem with http Proxy

### ISSUE THREAD

**Issue by biasc** [jstedfast/MailKit#847]
**Describe the bug**
I have successfully tested the mailkit imap class with 2 differents imap account (outlook and gmail) without using proxy
I am not able to connect to our http proxy in any mode, i don't have a socks proxy. 
The connection to the proxy is Ok but when i call the connect method i have the error posted below.
This is the code i have used. 
What i am doing wrong?

**To Reproduce**
```csharp
client = new ImapClient(new ProtocolLogger("imap.log"))
                {
                    ServerCertificateValidationCallback = (s, c, h, e) => true,
                    CheckCertificateRevocation = false
                };
string proxyServer = "192.168.16.19";
                int proxyPort = 8080;
                string proxyUsername = "admin";
                string proxyPassword = "password";
                string b64UserPwd = Convert.ToBase64String(System.Text.Encoding.UTF8.GetBytes(proxyUsername + ":" + proxyPassword));
                Socket mySocket = new Socket(SocketType.Stream, ProtocolType.Tcp);
                mySocket.Connect(proxyServer,proxyPort);
                string connectMsg = string.Format("CONNECT {0}:{1} HTTP/1.0\r\n" + "Proxy-Authorization: Basic {2}\r\n" + "\r\n", 
                    proxyServer, 
                    proxyPort,
                    b64UserPwd);
                byte[] msg = Encoding.UTF8.GetBytes(connectMsg);
                mySocket.Send(msg);
                string proxyConnectionResponseHeader = "";
                while (!proxyConnectionResponseHeader.Contains("\r\n\r\n"))
                {
                    byte[] buffer = new byte[1];
                    mySocket.Receive(buffer, 0, 1, 0);
                    proxyConnectionResponseHeader += Encoding.ASCII.GetString(buffer);
                }
                if (!proxyConnectionResponseHeader.Contains("200 Connection established"))
                {
                    throw new Exception("Connection to Proxy Failed: " + proxyConnectionResponseHeader);
                }

 var mode = _appModel.UseSSL ? SecureSocketOptions.SslOnConnect :                                                 SecureSocketOptions.None;
                    client.Connect(mySocket,
                        _appModel.Server,
                        _appModel.Port,
                        mode);
```
 
**Screenshots**
![image](https://user-images.githubusercontent.com/20203309/56190366-56a41e80-602a-11e9-9e55-fefca26cbf19.png)

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by jstedfast** [comment]
Is `mode = SecureSocketOptions.SslOnConnect`? And what port are you trying to connect to? Is it 993? Or 143? Looks like you are trying to connect to port 143.

SslOnConnect is for port 993 (assuming the server uses standard ports). Try specifying StartTlsWhenAvailable instead.

**Comment by biasc** [comment]
The port is 993. Without the proxy configuration it works fine

**Comment by jstedfast** [comment]
After connecting your socket, try just creating and using an SslStream on top of it like this:

```csharp
var network = new NetworkStream (mySocket, false);
var ssl = new SslStream (network, true);
ssl.AuthenticateAsClient (_appModel.Server);
```

Does that throw any exceptions?

**Comment by jstedfast** [comment]
I'm not sure how HTTP proxies work, but are you sure you're supposed to use HTTP/1.0 instead of HTTP/1.1?

**Comment by biasc** [comment]
I'have tried HTTP/1.1 and HTTP/1.0 but there are no diff.
Using

`var network = new NetworkStream (mySocket, false);
var ssl = new SslStream (network, true);
ssl.AuthenticateAsClient (_appModel.Server);`

Throws an errror
![image](https://user-images.githubusercontent.com/20203309/56213188-dbf3f700-605b-11e9-8179-34b16e35f8ec.png)

**Comment by jstedfast** [comment]
Unexpected packet format suggests to me that the port you are actually connecting to doesn't actually support SSL.

**Comment by Safirion** [comment]
I have the same problem. Is there a simple option to just use a WebProxy with MailKit ?

**Comment by jstedfast** [comment]
@Safirion I would recommend starting with what @biasc has and trying to figure out why SslStream.AUthenticateAsClient() is failing because once you figure that out, then using an HTTP proxy is solved.

The WebProxy API doesn't actually implement a way of connecting through a proxy, it only holds information about a proxy URI and the credentials it would need. In other words, it looks useless for solving your problem.

**Comment by Safirion** [comment]
@jstedfast Yes of course, but when a solution will be find for this problem, then it would be possible to implement a support of WebProxy directly in the library, no ?

**Comment by biasc** [comment]
@Safirion I have used this code
https://github.com/poma/ProxySocket/blob/master/src/Org.Mentalis.Network.ProxySocket/ProxySocket.cs
and it works.
@jstedfast maybe it can be used to create a standard implementation in mailkit?

**Comment by jstedfast** [comment]
Try the MyGet package once it's published by the build bots (next 30 minutes or so?) and use `MailKit.Net.Proxy.HttpProxyClient`.

(Note: the main MailKit github page provides download links to official NuGet release packages as well as MyGet CI builds)

**Comment by biasc** [comment]
@jstedfast I have already tested the `MailKit.Net.Proxy.HttpProxyClient` and it works!
GREAT!
This will be included in 2.1.5 ?

**Comment by jstedfast** [comment]
yes

**Comment by biasc** [comment]
Fantastic, thanks!

**Comment by biasc** [comment]
@jstedfast When is the 2.1.5 release scheduled?

**Comment by jstedfast** [comment]
Hoping to fix a few more issues first. Making releases chews up a lot of my free time, so I like to spread them out and collect as many fixes as possible before rolling the next release.
