### ISSUE TITLE
MailKit -> "Unable to parse status code returned by the server." during client connect...

### ISSUE THREAD

**Issue by dieterblocher** [jstedfast/MailKit#848]
**Describe the bug**

Using MailKit with gmail to send emails works fine. But if I use my local provider I get an exception during the connect method.

![image](https://user-images.githubusercontent.com/3775529/56207869-1eafd200-6050-11e9-94ab-40c682bf74f2.png)

Mail Log:
Connected to smtp://atria.uberspace.de:587/?starttls=when-available
S: 220 atria.uberspace.de ESMTP
C: EHLO [192.168.1.112]
S: 250-atria.uberspace.de
S: 250-STARTTLS
S: 250-PIPELINING
S: 250-8BITMIME
S: 250 AUTH LOGIN PLAIN
C: STARTTLS
S: 220 Proceed.
C: EHLO [192.168.1.112]
S: 250-atria.uberspace.de
S: 250-PIPELINING
S: 250-8BITMIME
S: 250

**Comment by jstedfast** [comment]
Which version of MailKit are you using? Always make sure to upgrade to the latest.

**Comment by dieterblocher** [comment]
Yes, it seem it works with the v2.1.4. I had the version v2.1.3. Thanks. :-)
