### ISSUE TITLE
ImapProtocolException hides the real error message from server

### ISSUE THREAD

**Issue by komanton** [jstedfast/MailKit#849]
Very often I receive such stack trace:

`MailKit.Net.Imap.ImapProtocolException: Connection closed. 14
   at MailKit.Net.Imap.ImapEngine.IterateAsync(Boolean doAsync)
   at MailKit.Net.Imap.ImapEngine.RunAsync(ImapCommand ic, Boolean doAsync)
   at MailKit.Net.Imap.ImapEngine.GetFolderAsync(String path, Boolean doAsync, CancellationToken cancellationToken)
   at MailKit.Net.Imap.ImapClient.GetFolder(String path, CancellationToken cancellationToken)`

And I can not understand the meaning of the exception only by this message: "Connection closed. 14"

To understand this exception, I enabled the ProtocolLog:

> Connected to imaps://outlook.office365.com:993/
> S: * OK The Microsoft Exchange IMAP4 service is ready. [TA********************uAEMATwBNAA==]
> C: A00000000 CAPABILITY
> S: * CAPABILITY IMAP4 IMAP4rev1 AUTH=PLAIN AUTH=XOAUTH2 SASL-IR UIDPLUS ID UNSELECT CHILDREN IDLE NAMESPACE LITERAL+
> S: A00000000 OK CAPABILITY completed.
> C: A00000001 AUTHENTICATE PLAIN AGR*******************F0V2U=
> S: A00000001 NO AUTHENTICATE failed.
> C: A00000002 ****** LOGIN INFORMATION HIDEN ****** completed.
> C: A00000003 CAPABILITY
> S: * CAPABILITY IMAP4 IMAP4rev1 AUTH=PLAIN AUTH=XOAUTH2 SASL-IR UIDPLUS MOVE ID UNSELECT CLIENTACCESSRULES CLIENTNETWORKPRESENCELOCATION BACKENDAUTHENTICATE CHILDREN IDLE NAMESPACE LITERAL+
> S: A00000003 OK CAPABILITY completed.
> C: A00000004 NAMESPACE
> S: A00000004 BAD User is authenticated but not connected.
> C: A00000005 LIST "" "INBOX"
> S: A00000005 BAD User is authenticated but not connected.
> S: * BYE Connection closed. 14
> C: A00000006 LIST "" Inbox

And I saw that there was another message:  "BAD User is authenticated but not connected. "

Another case, I saw this message "Connection closed. 14" in the stack trace, but protocol log shows: "BAD Request is throttled. Suggested Backoff Time: 93522 milliseconds":

> Connected to imaps://outlook.office365.com:993/     
> S: * OK The Microsoft Exchange IMAP4 service is ready. [T****************************==]     
> C: Z00000000 CAPABILITY     
> S: * CAPABILITY IMAP4 IMAP4rev1 AUTH=PLAIN AUTH=XOAUTH2 SASL-IR UIDPLUS ID UNSELECT CHILDREN IDLE NAMESPACE LITERAL+     
> S: Z00000000 OK CAPABILITY completed.     
> C: Z00000001 AUTHENTICATE PLAIN A***************************l     
> S: Z00000001 NO AUTHENTICATE failed.     
> C: Z00000002 ****** LOGIN INFORMATION HIDEN ****** completed.     
> C: Z00000003 CAPABILITY     
> S: * CAPABILITY IMAP4 IMAP4rev1 AUTH=PLAIN AUTH=XOAUTH2 SASL-IR UIDPLUS MOVE ID UNSELECT CLIENTACCESSRULES CLIENTNETWORKPRESENCELOCATION BACKENDAUTHENTICATE CHILDREN IDLE NAMESPACE LITERAL+     
> S: Z00000003 OK CAPABILITY completed.     
> C: Z00000004 NAMESPACE     
> S: Z00000004 BAD Request is throttled. Suggested Backoff Time: 591431 milliseconds     
> S: * BYE Connection closed. 14     
> C: Z00000005 LIST "" "INBOX"

The question is why I see the same message in the stack trace (I mean "BYE Connection closed. 14 ") for completely different errors: "not connected" and "throttled"?
Is it a bug?

I think the correct behavior in my case should be such stack trace: 
`MailKit.Net.Imap.ImapProtocolException: User is authenticated but not connected. 
   at MailKit.Net.Imap.ImapEngine.IterateAsync(Boolean doAsync)
   at MailKit.Net.Imap.ImapEngine.RunAsync(ImapCommand ic, Boolean doAsync)
   at MailKit.Net.Imap.ImapEngine.GetFolderAsync(String path, Boolean doAsync, CancellationToken cancellationToken)
   at MailKit.Net.Imap.ImapClient.GetFolder(String path, CancellationToken cancellationToken)`

Optional: By the way, do you know what does it mean: 'BAD User is authenticated but not connected. '? Should I retry connection? Because it disappears after some time for the same user.

I use version 2.1.3.

**Comment by jstedfast** [comment]
The problem is that the `* BYE` comes *after* the tagged response, so ImapClient doesn't see the `* BYE` until it goes to read the response to the *next* command, so it is impossible to do what you suggest.

Also I have no idea what "User is authenticated but not connected" means. I suppose that yes, you should reconnect and try again.

**Comment by christophgasser** [comment]
How was that solved? I have exactly the same issue.

S: B00000001 OK AUTHENTICATE completed.
C: B00000002 CAPABILITY
S: * CAPABILITY IMAP4 IMAP4rev1 AUTH=PLAIN AUTH=XOAUTH2 SASL-IR UIDPLUS MOVE ID UNSELECT CLIENTACCESSRULES CLIENTNETWORKPRESENCELOCATION BACKENDAUTHENTICATE CHILDREN IDLE NAMESPACE LITERAL+
S: B00000002 OK CAPABILITY completed.
C: B00000003 NAMESPACE
S: B00000003 BAD Request is throttled. Suggested Backoff Time: 112857 milliseconds
S: * BYE Connection closed. 14
C: B00000004 LIST "" "INBOX"

**Comment by jstedfast** [comment]
@christophgasser it's not something that I can fix because the `* BYE` response is not part of the `B00000003` command response, it is part of the `B00000004` response.

**Comment by christophgasser** [comment]
Is this an issue of the bloody O365 or the MailKit then? Thing is, my implementation has been working well, but since sime time, it is not. But I can't tell because it was because of the update to a newer MailKit release or because Microsoft chnaged something on their O365 infrastructure/implementation.

BR
C

**Comment by christophgasser** [comment]
Just for completeness: Sometimes it is working, and sometimes it is not. Same code. Same components. 
BR
C

**Comment by jstedfast** [comment]
This is an Office365 issue, not a MailKit issue.

According to the error given in the BYE response, it sounds like your client is hitting the O365 server a little too hard and so O365 is throttling your connection.

Are you connecting and disconnecting often? Is your client pegging the server with requests for message data?

**Comment by christophgasser** [comment]
No. No. Not at all. Opening the con. Keeping it open. Doing some mail movements. That's all.
And it happens when starting the application and building up the con. No load at that time. Except of the connection request.

Will have to investigate then.

BR for your qhick response.
C

**Comment by jstedfast** [comment]
Is there another program connecting to O365 from your iP address? It doesn't have to be the MailKit client that is flooding the O365 server with requests.

**Comment by christophgasser** [comment]
Not by IMAP. Just all the Outlook clients of the company. But they are not using the same account ;-)

BR
C
