### ISSUE TITLE
ArgumentOutOfRangeException in some cases

### ISSUE THREAD

**Issue by komanton** [jstedfast/MailKit#850]
Some times I receive this exception. But I can not understand what does it mean and how to handle it. Is it MailKit internal issue or my arguments are wrong?

Stack:
`System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at MailKit.Net.Imap.ImapFolder.FetchSummaryContext.OnMessageExpunged(Object sender, MessageEventArgs args)
   at MailKit.Net.Imap.ImapFolder.OnExpunge(Int32 index)
   at MailKit.Net.Imap.ImapEngine.ProcessUntaggedResponseAsync(Boolean doAsync, CancellationToken cancellationToken)
   at MailKit.Net.Imap.ImapCommand.StepAsync(Boolean doAsync)
   at MailKit.Net.Imap.ImapEngine.IterateAsync(Boolean doAsync)
   at MailKit.Net.Imap.ImapEngine.RunAsync(ImapCommand ic, Boolean doAsync)
   at MailKit.Net.Imap.ImapFolder.GetPreviewTextAsync(FetchSummaryContext sctx, Boolean doAsync, CancellationToken cancellationToken)
   at MailKit.Net.Imap.ImapFolder.FetchAsync(IList`1 uids, MessageSummaryItems items, Boolean doAsync, CancellationToken cancellationToken)`

Protocol Log:

> Connected to imaps://outlook.office365.com:993/
> S: * OK The Microsoft Exchange IMAP4 service is ready. [TA******************A==]
> C: J00000000 CAPABILITY
> S: * CAPABILITY IMAP4 IMAP4rev1 AUTH=PLAIN AUTH=XOAUTH2 SASL-IR UIDPLUS ID UNSELECT CHILDREN IDLE NAMESPACE LITERAL+
> S: J00000000 OK CAPABILITY completed.
> C: J00000001 AUTHENTICATE PLAIN A****************************************************ch
> S: J00000001 NO AUTHENTICATE failed.
> C: J00000002 ****** LOGIN INFORMATION HIDEN ****** completed.
> C: J00000003 CAPABILITY
> S: * CAPABILITY IMAP4 IMAP4rev1 AUTH=PLAIN AUTH=XOAUTH2 SASL-IR UIDPLUS MOVE ID UNSELECT CLIENTACCESSRULES CLIENTNETWORKPRESENCELOCATION BACKENDAUTHENTICATE CHILDREN IDLE NAMESPACE LITERAL+
> S: J00000003 OK CAPABILITY completed.
> C: J00000004 NAMESPACE
> S: * NAMESPACE (("" "/")) NIL NIL
> S: J00000004 OK NAMESPACE completed.
> C: J00000005 LIST "" "INBOX"
> S: * LIST (\Marked \HasNoChildren) "/" INBOX
> S: J00000005 OK LIST completed.
> C: J00000006 SELECT INBOX
> S: * 53 EXISTS
> S: * 0 RECENT
> S: * FLAGS (\Seen \Answered \Flagged \Deleted \Draft $MDNSent)
> S: * OK [PERMANENTFLAGS (\Seen \Answered \Flagged \Deleted \Draft $MDNSent)] Permanent flags
> S: * OK [UNSEEN 1] Is the first unseen message
> S: * OK [UIDVALIDITY 14] UIDVALIDITY value
> S: * OK [UIDNEXT 6999] The next unique identifier value
> S: J00000006 OK [READ-WRITE] SELECT completed.
> C: J00000007 UID FETCH 6712:6712 (UID INTERNALDATE ENVELOPE BODYSTRUCTURE BODY.PEEK[HEADER.FIELDS (REFERENCES)])
> S: * 8 FETCH (UID 6712 INTERNALDATE "18-Apr-2019 14:31:03 +0000" ENVELOPE ("Thu, 18 Apr 2019 13:57:30 +0000" "Test message(1680362844) #413 (DO NOT REPLY)" (("Development" NIL "dev" "somedomain.com")) NIL NIL (("somemailbox-qa" NIL "somemailbox-qa" "somedomain.com")) NIL NIL NIL "<SZY5QC1HA7U4.TYTPOE50MDP73@localhost.localdomain>") BODYSTRUCTURE ("text" "plain" ("charset" "utf-8") "<5862B59F9E42AD41BEC54954A257EF99@GBRP265.PROD.OUTLOOK.COM>" NIL "base64" 0 0 NIL NIL "en-US" NIL) BODY[HEADER.FIELDS (REFERENCES)] {2}
> S:
> S: )
> S: J00000007 OK FETCH completed.
> C: J00000008 UID FETCH 6712 (BODY.PEEK[TEXT]<0.256>)
> S: * 8 FETCH (BODY[TEXT]<0> {88}
> S: VGh*************************************************************QTFkp
> S: DQoNCg==
> S:  UID 6712)
> S: * 50 EXPUNGE
> S: * 52 EXISTS
> S: J00000008 OK FETCH completed.

**Comment by jstedfast** [comment]
Looks like a valid bug. Should be fixed now. You can use the MyGet nuget feed on the GitHub main page to test out the fix (package should be published in the next 30 minutes or so).
