### ISSUE TITLE
Using mimekit nuget package (via paket) in common project removes existing System.net.http.dll from other projects referencing common project

### ISSUE THREAD

**Issue by amitpanwarIndia** [jstedfast/MailKit#854]
**Describe the bug**
Mimekit used in common project is removing System.net.http used in dependent project.

**Expected behavior**
System.net.http.dll should be present in dependent project.

**Desktop (please complete the following information):**
 - OS: Window 10

**Additional context**
I had added a new reference of mimekit library (added mimekit and mailkit via paket) in common project used by several other projects.

To use mimekit I used below code:

using MimeKit; 
namespace Project.Common.Email.Interfaces 
{ public interface IMailKitBody 
{ BodyBuilder BodyBuilder 
{ get; set; } 
} }

But while building the complete solution after adding above file, System.net.http.dll is getting removed from one of the dependent projects having reference of common project and another project which actually have a reference of System.net.http.dll.

And as soon as I remove this file from Common then System.net.http.dll starts appearing in the dependent project.

Could anyone help me out how this problem be resolved?

I know Mimekit is dependent upon System.net.http.dll and it could conflict with existing one in dependent projects. I have already tried following things: 
-removing System.net.http.dll reference from common 
-Setting Copy Local property of DLL to True 
-Adding reference System.net.http.dll from package folder

**Comment by jstedfast** [comment]
1. What Framework version does your project use?
2. What version of System.Net.Http does your project use? Is it newer or older than the one MimeKit requires?

**Comment by jstedfast** [comment]
Might just be a bug in paket (I don't even know what that is).

**Comment by amitpanwarIndia** [comment]
paket is an alternative to download nuget packages.
My project is using 4.7.1 version.
Project is referencing System.Net.Http from two places, some places at C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7.1\ (version 4.0.0.0) and C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\Microsoft\Microsoft.NET.Build.Extensions\net461\lib\ (version 4.2.0.0)

Later one is the latest Dll from Microsoft . I don't find Mimekit using System.net.http version 4.3.0 anywhere.

**Comment by jstedfast** [comment]
What's your proposed solution?

**Comment by jstedfast** [comment]
You say your project is .NET v4.7, but what framework version of MimeKit is it using? Is it using the .NET v4.5 version? Or the .NETStandard 2.0 version?

Maybe if you make it use the net45 version of MimeKit it'll be fine? I don't know.

**Comment by jstedfast** [comment]
Try installing packages from:

https://www.myget.org/feed/mimekit/package/nuget/MimeKit
and
https://www.myget.org/feed/mimekit/package/nuget/MailKit

There is no longer an explicit NuGet dependency on System.Net.Http for the .NETStandard2.0 version. Maybe that will fix it?

**Comment by amitpanwarIndia** [comment]
I used net45 only and by using Core it's actually copying the required files at the place but then Mime doesn't work and gives exception as below:
"System.TypeInitializationException
  HResult=0x80131534
  Message=The type initializer for 'MimeKit.ParserOptions' threw an exception.
  Source=MimeKit
  StackTrace:
   at MimeKit.MimeMessage..ctor()
   at MailTest.Program.Main(String[] args) in C:\Users\$User$\source\repos\MailTest\MailTest\Program.cs:line 12

Inner Exception 1:
TypeInitializationException: The type initializer for 'MimeKit.Utils.CharsetUtils' threw an exception.

Inner Exception 2:
FileNotFoundException: Could not load file or assembly 'System.Text.Encoding.CodePages, Version=4.0.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.

**Comment by jstedfast** [comment]
If you are getting that exception, then you've mixed and matched net45 with netstandard2.0

**Comment by amitpanwarIndia** [comment]
I was giving a try to check if that library works for me but appropriately it's not. So currently I am targetting 4.7.1 NET framework and using net45 library where issue is popping up.

**Comment by jstedfast** [comment]
The reason I asked you to try the MyGet packages was because I removed the System.Net.Http nuget references.

But if you are referencing the net45 versions of MimeKit and MailKit (btw, you need to be consistent with those 2 libs and use the same framework version of each), then your issue is in your own project and not MimeKit or MailKit for sure.
