### ISSUE TITLE
Gracefully Handling Transient Errors

### ISSUE THREAD

**Issue by bloudraak** [jstedfast/MailKit#857]
**Is your feature request related to a problem?** 
I'm a bit frustrated that when I'm using Mailkit in a real world network, that transient network errors, or server implementations, causes it to fail. My code becomes really messy as I have to add a ton of retry logic. Not only that, but it distracts me from the problem I'm trying to solve.

**Describe the solution you'd like**
Similiar to the Azure SDK, I'd like to register a handler in the client where I implement code that would retry operations when transient errors take place. It would then be benefitial if Mailkit comes with default retry handlers (similiar to Transient Fault Handler). 

The default retry handler should deal with SocketExceptions, TimeoutExceptions and TimeoutExceptions. As we learn more about transient errors, we could submit PRs to further enhance it. 

**Describe alternatives you've considered**
I implmented my own retry handler where each method call to Mailkit is wrapped. This makes the code brittle, messy and less maintainable. 

**Additional context**
When you're using Mailkit from a slower network (for example 3G speeds), or with high latency (e.g. connecting from South Africa to the USA; or connecting via sattelite; or a server where resources hit their limits), requests can time out, DNS lookups can temporarily fail (for the same reason timeout) and the remote IMAP server could terminate connections due to load or other reasons. Typically retrying after a brief delay recovers.

**Comment by jstedfast** [comment]
How do you propose I implement these retry handlers? I don't have experience with the Azure SDK or any other library that is fault tolerant and so don't really know what this would look like. I'm interested in hearing some proposals.

As far as interoperability with server implementations, please submit those issues to me and assuming it isn't a nightmare to work around the server bug, I will add logic to MailKit to do so. I already have a few dozen workarounds for various server bugs.

**Comment by bloudraak** [comment]
Let me upfront that I did not look at the internals of MailKit; so bear with me.

First, a article folks at Microsoft wrote about the retry pattern:
https://docs.microsoft.com/en-us/azure/architecture/patterns/retry

You may want to look at the following:
- https://github.com/dotnet/corefx/blob/master/src/System.Net.Http/src/System/Net/Http/DelegatingHandler.cs
- https://github.com/dotnet/corefx/blob/master/src/System.Net.Http/src/System/Net/Http/HttpMessageHandler.cs
- https://github.com/dotnet/corefx/blob/master/src/System.Net.Http/src/System/Net/Http/HttpMessageInvoker.cs
- https://github.com/dotnet/corefx/blob/master/src/System.Net.Http/src/System/Net/Http/HttpClientHandler.cs
- https://github.com/Azure/azure-sdk-for-net/blob/master/src/SdkCommon/ClientRuntime/ClientRuntime/ServiceClient.cs

In short, HttpClientHandler wraps the low level communciations. It inherits from HttpMessageHandler. ServiceClient wraps HttpClientHandle, but notices how it supports DelegatingHandler, which allows a client to wrap the calls to HttpClientHandler to be intercepted. 

Typical uses for folks like me would be write a delegating handler to always inject a header for each HTTP call. Microsoft also implemented delegating handlers for diagnostics, retry logic etc. Here's some examples:

- https://github.com/Azure/azure-sdk-for-net/blob/master/src/SdkCommon/ClientRuntime/ClientRuntime/RetryDelegatingHandler.cs which uses code from https://github.com/Azure/azure-sdk-for-net/tree/master/src/SdkCommon/ClientRuntime/ClientRuntime/TransientFaultHandling
- https://github.com/dotnet/corefx/blob/master/src/System.Net.Http/src/System/Net/Http/DiagnosticsHandler.cs

That said, you don't have to expose this capability to clients. Instead, you could just implement it yourself too.  I would then recommend you look at https://github.com/Azure/azure-sdk-for-net/tree/master/src/SdkCommon/ClientRuntime/ClientRuntime/TransientFaultHandling and https://github.com/Azure/azure-sdk-for-net/blob/master/src/SdkCommon/ClientRuntime/ClientRuntime/RetryDelegatingHandler.cs and wrap every call to the server.

**Comment by jstedfast** [comment]
Yea.... unlike HTTP, IMAP is a stateful protocol, so this is will be orders of magnitude more complicated.

You'll need to store the user's username/password so that you can re-authenticate if the client was previously authenticated as well as which SaslMechanism was used.

I don't think I am up for implementing this, but if you'd like to give it a shot, I can help answer any questions you have about the code.

**Comment by alexander-petuhov** [comment]
> Yea.... unlike HTTP, IMAP is a stateful protocol, so this will be orders of magnitude more complicated.
> 
> You'll need to store the user's username/password so that you can re-authenticate if the client was previously authenticated as well as which SaslMechanism was used.
> 
> I don't think I am up for implementing this, but if you'd like to give it a shot, I can help answer any questions you have about the code.

I'm implementing retry logic for mailkit using some external library and just realized that it's a little bit complex to create new instance of smpclient inside retry handler like I would do in case of my own retry implementation. Can you please confirm if it's required to create new instance on retry or I can just do connect if required and authenticated if required on existing instance of mailkit smptclient inside retry handler?

**Comment by jstedfast** [comment]
You can reuse the same instance of SmtpClient and call Connect() on it when it gets disconnected.

**Comment by jstedfast** [comment]
For what it's worth, I believe that I made the Disconnected event provide the host, port, and SecureSocketOptions values that were used to Connect to make reconnecting simpler.

That said, it does not provide the authentication info.

**Comment by alexander-petuhov** [comment]
> For what it's worth, I believe that I made the Disconnected event provide the host, port, and SecureSocketOptions values that were used to Connect to make reconnecting simpler.
> 
> That said, it does not provide the authentication info.

Sounds good, but I got interesting case. I did connect successfully and client is showing as connected, but for some reasons I wasn't able to do authenticate during test debug (after rerun - it worked fine) - I did authenticate retries, did connect retries but got "Cannot access a disposed object. Object name: 'System.Net.Sockets.Socket'. mailkit" on all attempts to do authenticate.

**Comment by jstedfast** [comment]
No idea how that could happen. You might need to step through the code in a debugger and set breakpoints in the code to see how/where/why the socket is getting disposed.

**Comment by alexander-petuhov** [comment]
> No idea how that could happen. You might need to step through the code in a debugger and set breakpoints in the code to see how/where/why the socket is getting disposed.

It's interesting - I can reproduce this. I'm calling ConnectAsync. After this I'm calling AuthenticateAsync, but with some delay and because of this I'm getting "Message	"The SMTP server has unexpectedly disconnected.". (BTW smtpclient property IsConnected still "true"). After this my "retry" logic start playing - on next invoke I'm receiving another error: "An established connection was aborted by the software in your host machine.". On the next retry "{"Cannot access a disposed object.\r\nObject name: 'System.Net.Sockets.Socket'."}" - and this is final message. IsConnected - still showing true, Authenticated - failing.

**Comment by jstedfast** [comment]
You can't fully trust the `client.IsConnected` property because it only gets updated when commands are sent/responses are received. In other words, the value is just a cached state value, the property doesn't try to verify socket connection state.

Can you provide me with a demo app that illustrates this issue?

**Comment by alexander-petuhov** [comment]
> You can't fully trust the `client.IsConnected` property because it only gets updated when commands are sent/responses are received. In other words, the value is just a cached state value, the property doesn't try to verify socket connection state.
> 
> Can you provide me with a demo app that illustrates this issue?
> 
> And lets open a new issue for your bug as well, because this one is closed.

I can show demo, but it's quite easy to repro - attaching test code below. Not sure if it's issue or expected behaviour. And I can't reconnect, because "connect" is checking "isConnected" and throwing exception.
`            using var smtpClient = new SmtpClient();

            await smtpClient.ConnectAsync(Creds.Host, Creds.Port, Creds.UseSSL);

            await Task.Delay(10000);//Put any delay which will cause timeout by smtp server.
            var count = 0;
            while (count < 5)
            {
                try
                {
                    await smtpClient.AuthenticateAsync(Creds.UserName, Creds.Password);

                    break;
                }
                catch (Exception ex)
                {
                    Console.WriteLine($"###Retry {count}.");
                    Console.WriteLine($"IsConnected={smtpClient.IsConnected}");
                    Console.WriteLine(ex.ToString());
                    Console.WriteLine(ex.InnerException?.ToString());
                    Console.WriteLine("####End");
                    count++;
                }
            }

            Console.WriteLine("done");`

**Comment by jstedfast** [comment]
Okay, it looks like SmtpClient.Authenticate/Async() are the only methods that don't properly catch disconnect errors.

I'll fix those up.
