### ISSUE TITLE
MailKit Sockets cannot connect when Avast antivirus is installed

### ISSUE THREAD

**Issue by ekalchev** [jstedfast/MailKit#858]
Mailkit cannot connect to any imap or smtp server when Avast antivirus is installed, while other mail clients can.

This is not a bug in MailKit but I want to leave the workaround for someone who experience the same issue with MailKit.

When MailKit open a socket it uses Socket constructor class which auto select IPv6 or IPv4, deepening if the network and the OS support it. When both IPv6 and IPv4 are available this constructor chooses IPv6 socket with support of Dual mode, which enables IPv4 over IPv6. 

See https://docs.microsoft.com/en-us/windows/desktop/winsock/ipproto-ipv6-socket-options
DualMode = true sets IPV6_V6ONLY = false

This works fine until some bugged implementation of network software like Avast comes to play. Avast don't support well IPv4 over IPv6 and will not allow the socket to connect.

My workaround is to build from source and change SoucketUtils.cs ConnectAsync method

and change this

    var socket = new Socket (SocketType.Stream, ProtocolType.Tcp);

to this

            Socket socket = null;
            if (Socket.OSSupportsIPv4)
            {
                socket = new Socket(AddressFamily.InterNetwork, SocketType.Stream, ProtocolType.Tcp);
            }
            else
            {
                socket = new Socket(SocketType.Stream, ProtocolType.Tcp);
            }

This way if both IPv4 and IPv6 are present. IPv4 is selected instead of IPv6.

**Comment by jstedfast** [comment]
You must be using an old version? The current code shouldn't suffer from this.

**Comment by ekalchev** [comment]
I just updated and it is working with the new code. Thanks!
