### ISSUE TITLE
How to get the result of sending mail 

### ISSUE THREAD

**Issue by daoqiang** [jstedfast/MailKit#861]
I would like to know the detailed results of the email, such as the success of the email, the rejection of the email and the detailed reasons for the rejection.

**Comment by daoqiang** [comment]
OnSenderAccepted and OnSenderNotAccepted methods may be related to this issue, but are they successful or unsuccessful responses sent by SMTP servers or responses only to messages sent by the current smtpclient instance?
can you help me？
thank you

**Comment by jstedfast** [comment]
If SmtpClient.Send() throws an exception, then sending the message failed. If it doesn't throw an exception, then it succeeded.

One of OnSenderAccepted() and OnSenderNotAccepted() get called when the SMTP server accepts or rejects the `MAIL FROM` command which is called with the email address of the message sender (typically the address in the `From` header).

As far as the reason for a rejection, if you get a [SmtpCommandException](http://www.mimekit.net/docs/html/T_MailKit_Net_Smtp_SmtpCommandException.htm), you can check its properties to help you figure out the reason.

**Comment by daoqiang** [comment]
Well done, but if I send a lot of mail, the OnSenderAccepted () and OnSenderNotAccepted () methods will be invoked, but I can't tell which mail was sent correctly or not successfully. It seems meaningless to distinguish the attributes of mimemassage, because all attributes except message ID are likely to duplicate, but message ID It should be defined by the SMTP server

**Comment by daoqiang** [comment]
Hello, i can set message ID to track mail before sending it.I am currently creating a singleton class that inherits smtpclient and implements related virtual functions to connect to the SMTP server within the class. Then use another scoped class to send the mail. The mail can be sent successfully, but the OnSenderAccepted method is not called in the singleton class.

**Comment by jstedfast** [comment]
You'd have to show me your code.

**Comment by daoqiang** [comment]
ok，Singleton Smtp Subscribe class：`   public class SmtpSubscribeSingleton : SmtpClient
    {
        private readonly Logger logger=LogManager.GetCurrentClassLogger();
        private readonly OutLookConfig outLookConfig;
        private readonly SmtpClient smtpClient;
        private readonly MailCenterDbContext dbContext;
        private readonly ConnectionsConfig connections;
        private List<FileStream> fileStreams = new List<FileStream>();
        private readonly Thread KeepAliveThread;

        public SmtpSubscribeSingleton(IOptions<OutLookConfig> options,IOptions<ConnectionsConfig> connoptions)
        {
            this.outLookConfig = options.Value;
            this.connections = connoptions.Value;
            dbContext=new MailCenterDbContext( new DbContextOptionsBuilder<MailCenterDbContext>(new DbContextOptions<MailCenterDbContext>()).UseMySql(connections.Default).Options);
            smtpClient = new SmtpClient();
            smtpClient.Connect(outLookConfig.SmtpHost, outLookConfig.SmtpPort, false);
            smtpClient.Authenticate(outLookConfig.UserName, outLookConfig.Password);
            KeepAliveThread = new Thread(new ThreadStart(KeepAlive));
            KeepAliveThread.Start();
        }
        private void KeepAlive()
        {
            try
            {
                while (true)
                {
                    Thread.Sleep(2000);
                    if (!smtpClient.IsConnected)
                    {
                        smtpClient.Connect(outLookConfig.SmtpHost, outLookConfig.SmtpPort, true);
                        smtpClient.Authenticate(outLookConfig.UserName, outLookConfig.Password);
                    }
                }
            }catch(Exception ex)
            {
                logger.Warn($"Subscribe KeepAlive Exception:{ex.Message}");
            }
        }

      
        /// <summary>
        /// 成功发送会调用
        /// </summary>
        /// <param name="message"></param>
        /// <param name="mailbox"></param> 
        /// <param name="response"></param>
        protected override void OnSenderAccepted(MimeMessage message, MailboxAddress mailbox, SmtpResponse response)
        {
            logger.Warn($"OnSenderAccepted MessageId:{message.MessageId}Subject:{message.Subject}");

            Console.WriteLine($"OnSenderAccepted MessageId:{message.MessageId}Subject:{message.Subject}");
            //TODO:更新数据库
            base.OnSenderAccepted(message, mailbox, response);
        }

        /// <summary>
        /// 驳回
        /// </summary>
        /// <param name="message"></param>
        /// <param name="mailbox"></param>
        /// <param name="response"></param>
        protected override void OnSenderNotAccepted(MimeMessage message, MailboxAddress mailbox, SmtpResponse response)
        {

            logger.Warn($"OnSenderNotAccepted MessageId:{message.MessageId}Subject:{message.Subject}");
            //TODO:更新数据库
            base.OnSenderNotAccepted(message, mailbox, response);
        }`
Scoped class：`    public class SmtpClientScope
    {
        private readonly OutLookConfig outLookConfig;
        private readonly SmtpClient smtpClient;
        private readonly MailCenterDbContext dbContext;
        private List<FileStream> fileStreams = new List<FileStream>();
        public SmtpClientScope(IOptions<OutLookConfig> options, MailCenterDbContext dbContext)
        {
            this.dbContext = dbContext;
            smtpClient = new SmtpClient();
            smtpClient.Connect(outLookConfig.SmtpHost, outLookConfig.SmtpPort, true);
            smtpClient.Authenticate(outLookConfig.UserName, outLookConfig.Password);
        }

        private MimeMessage BuildBaseMessage(string messageid,string subject, string text, string html, List<AttchmentInfo> attchmentInfos)
        {
            MimeMessage message = new MimeMessage();
            message.MessageId = messageid;
            message.From.Add(new MailboxAddress(outLookConfig.NickName, outLookConfig.UserName));
            message.Subject = subject;
            var multipart = new Multipart("mixed");
            var builder = new BodyBuilder();
            //text
            if (!string.IsNullOrEmpty(text))
            {
                var plain = new TextPart(TextFormat.Plain)
                {
                    Text = text
                };
                multipart.Add(plain);
                //  builder.TextBody = text;
            }
            //html
            if (!string.IsNullOrEmpty(html))
            {
                var HTML = new TextPart(TextFormat.Html)
                {
                    Text = html
                };
                multipart.Add(HTML);
                // builder.HtmlBody = html;
            }
            var charset = "GB18030";
            foreach (var attch in attchmentInfos)
            {
                if (attch == null)
                {
                    continue;
                }
                var stream = new FileStream(attch.Path, FileMode.Open);
                var attchment = new MimePart(FileHelper.GetFileContentType(attch.Name))
                {
                    Content = new MimeContent(stream),
                    ContentDisposition = new ContentDisposition(ContentDisposition.Attachment),
                    ContentTransferEncoding = ContentEncoding.EightBit,
                };
                attchment.ContentType.Parameters.Add(charset, "name", attch.Name);
                attchment.ContentDisposition.Parameters.Add(charset, "filename", attch.Name);
                multipart.Add(attchment);
                fileStreams.Add(stream);
            }
            message.Body = multipart;
            return message;
        }
        public string SendMail(string to, string subject, string text, string html, List<AttchmentInfo> attchmentInfos)
        {
            var id = Guid.NewGuid().ToString();
            var message = BuildBaseMessage(id,subject, text, html, attchmentInfos);
            message.To.Add(new MailboxAddress(to));
            smtpClient.Send(message);
            return id;
        }

        public string SendMail(List<string> toList, string subject, string text, string html, List<AttchmentInfo> attchmentInfos)
        {
            var messageid = Guid.NewGuid().ToString();
            var message = BuildBaseMessage(messageid, subject, text, html, attchmentInfos);
            var tos = new List<MailboxAddress>();
            if (toList != null && toList.Count > 0)
            {
                foreach (var to in toList)
                {
                    tos.Add(new MailboxAddress(to));
                }
                message.To.AddRange(tos);
            }
            smtpClient.Send(message);

            return messageid;
        }

        public string ReplyMail(string oldmessageId, string subject, string text, string html, List<AttchmentInfo> attchmentInfos, bool replyToAll)
        {
            //老邮件的eml文件路径
            var messageid = Guid.NewGuid().ToString();
            var path = dbContext.MailMessageResources.Where(m => m.MessageId == oldmessageId && m.Type == TypeEnum.ResourceType.EmlFile).FirstOrDefault()?.Path;
            MimeMessage message = MimeMessage.Load(path);

            var reply = BuildBaseMessage(messageid, subject, text, html, attchmentInfos);

            // reply to the sender of the message
            if (message.ReplyTo.Count > 0)
            {
                reply.To.AddRange(message.ReplyTo);
            }
            else if (message.From.Count > 0)
            {
                reply.To.AddRange(message.From);
            }
            else if (message.Sender != null)
            {
                reply.To.Add(message.Sender);
            }

            if (replyToAll)
            {
                // include all of the other original recipients - TODO: remove ourselves from these lists
                reply.To.AddRange(message.To);
                reply.Cc.AddRange(message.Cc);
            }

            // set the reply subject

            reply.Subject = subject;

            // construct the In-Reply-To and References headers
            if (!string.IsNullOrEmpty(message.MessageId))
            {
                reply.InReplyTo = message.MessageId;
                foreach (var id in message.References)
                    reply.References.Add(id);
                reply.References.Add(message.MessageId);
            }

            smtpClient.SendAsync(reply);

            return messageid;
            // quote the original message text
        }

        public string CopySendMail(List<string> ccList, List<string> bccList, string to, string subject, string text, string html, List<AttchmentInfo> attchmentInfos)
        {
            var messageid = Guid.NewGuid().ToString();
            var message = BuildBaseMessage(messageid, subject, text, html, attchmentInfos);
            message.To.Add(new MailboxAddress(to));
            if (ccList != null && ccList.Count > 0)
            {
                var ccs = new List<MailboxAddress>();
                foreach (var cc in ccList)
                {
                    ccs.Add(new MailboxAddress(cc));
                }
                message.Cc.AddRange(ccs);
            }
            if (bccList != null && bccList.Count > 0)
            {
                var bccs = new List<MailboxAddress>();
                foreach (var bcc in bccList)
                {
                    bccs.Add(new MailboxAddress(bcc));
                }
                message.Bcc.AddRange(bccs);
            }

            smtpClient.Send(message);

            return messageid;
        }

        public string CopySendMail(List<string> ccList, List<string> bccList, List<string> toList, string subject, string text, string html, List<AttchmentInfo> attchmentInfos)
        {
            var messageid = Guid.NewGuid().ToString();
            var message = BuildBaseMessage(messageid, subject, text, html, attchmentInfos);

            if (toList != null && toList.Count > 0)
            {
                var tos = new List<MailboxAddress>();
                foreach (var to in toList)
                {
                    tos.Add(new MailboxAddress(to));
                }
                message.To.AddRange(tos);

            }
            if (ccList != null && ccList.Count > 0)
            {
                var ccs = new List<MailboxAddress>();
                foreach (var cc in ccList)
                {
                    ccs.Add(new MailboxAddress(cc));
                }
                message.Cc.AddRange(ccs);
            }
            if (bccList != null && bccList.Count > 0)
            {
                var bccs = new List<MailboxAddress>();
                foreach (var bcc in bccList)
                {
                    bccs.Add(new MailboxAddress(bcc));
                }
                message.Bcc.AddRange(bccs);
            }
            smtpClient.Send(message);
            return messageid;
        }

        ~SmtpClientScope()
        {
            if (fileStreams!=null && fileStreams.Count>0)
            {
                foreach (var stream in fileStreams)
                {
                    stream.Close();
                }
            }
        }
    }`
startup: `services.AddSingleton<SmtpSubscribeSingleton>();
            services.AddScoped<SmtpClientScope>();`
My idea is to send mail through SmtpClientScope in MVC and SmtpSubscribeSingleton to receive the results of the SMTP server.

**Comment by jstedfast** [comment]
Well, now I know why your `OnSenderAccepted()` and `OnSenderNotAccepted()` methods don't get called...

You didn't subclass correctly. Why did you make your subclass of SmtpClient create a new internal SmtpClient? What's the point of that? Sending with that internal SmtpClient is not going to invoke your SmtpSubscribeSingleton's `OnSenderAccepted()` or `OnSenderNotAccepted()` methods because it can't and even if it could, you didn't tell it to.

Also: don't use a GUID as the message-id, use `MimeKit.Utils.MimeUtils.GenerateMessageId()`

**Comment by daoqiang** [comment]
> Well, now I know why your `OnSenderAccepted()` and `OnSenderNotAccepted()` methods don't get called...
> 
> You didn't subclass correctly. Why did you make your subclass of SmtpClient create a new internal SmtpClient? What's the point of that? Sending with that internal SmtpClient is not going to invoke your SmtpSubscribeSingleton's `OnSenderAccepted()` or `OnSenderNotAccepted()` methods because it can't and even if it could, you didn't tell it to.
> 
> Also: don't use a GUID as the message-id, use `MimeKit.Utils.MimeUtils.GenerateMessageId()`
Why did you make your subclass of SmtpClient create a new internal SmtpClient? 
Because I think I need to receive messages from the SMTP server, I need to connect to the server first. Isn't that true? If I don't connect to the server, who called OnSenderAccepted () or OnSenderNotAccepted ()?
What do you mean is that I need a subclass of smtpclient to send and receive email results?
But I probably won't wait for the result after sending. The instance of this smtpclient subclass is recycled. If you think about it, sending mail can only be a singleton object.

**Comment by daoqiang** [comment]
oh, my god.I made a fatal mistake. I think I know what to do. Thank you.

**Comment by MGAjinugrh** [comment]
> oh, my god.I made a fatal mistake. I think I know what to do. Thank you.

Coul you share your solutions here by any chance, I also need to monitor if my email has been received too

**Comment by wujialiang999** [comment]
```cs
using MailKit.Net.Smtp;
using MimeKit;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading;
using System.Threading.Tasks;

namespace MailStudy
{
    public class SmtpSubscribeSingleton  : SmtpClient
    {
        private readonly Thread KeepAliveThread;
        private readonly string smtpHost;
        private readonly int smtpPort;
        private readonly bool isSsl;
        private readonly string email;
        private readonly string password;

        public SmtpSubscribeSingleton(string smtpHost,int smtpPort,bool isSsl,string email,string password)
        {
            this.smtpHost = smtpHost;
            this.smtpPort = smtpPort;
            this.isSsl = isSsl;
            this.email = email;
            this.password = password;
            Connect(smtpHost, smtpPort, isSsl);
            Authenticate(email, password);
            KeepAliveThread = new Thread(new ThreadStart(KeepAlive));
            KeepAliveThread.Start();
            Console.WriteLine("邮件监听开启");
        }

        /// <summary>
        /// 保持链接
        /// </summary>
        private void KeepAlive()
        {
            try
            {
                while (true)
                {
                    Thread.Sleep(2000);
                    if (!IsConnected)
                    {
                        Connect(smtpHost, smtpPort, isSsl);
                        Authenticate(email, password);
                    }
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Subscribe KeepAlive Exception:{ex.Message}");
            }
        }

        /// <summary>
        /// 成功发送会调用
        /// </summary>
        /// <param name="message"></param>
        /// <param name="mailbox"></param> 
        /// <param name="response"></param>
        protected override void OnSenderAccepted(MimeMessage message, MailboxAddress mailbox, SmtpResponse response)
        {
            Console.WriteLine($"OnSenderAccepted \rMessageId:{message.MessageId}\rSubject:{message.Subject}");
            //TODO:更新数据库
            base.OnSenderAccepted(message, mailbox, response);
        }

        /// <summary>
        /// 驳回
        /// </summary>
        /// <param name="message"></param>
        /// <param name="mailbox"></param>
        /// <param name="response"></param>
        protected override void OnSenderNotAccepted(MimeMessage message, MailboxAddress mailbox, SmtpResponse response)
        {
            Console.WriteLine($"OnSenderNotAccepted \rMessageId:{message.MessageId}\rSubject:{message.Subject}");
            //TODO:更新数据库
            base.OnSenderNotAccepted(message, mailbox, response);
        }
    }
}
```
use
```cs
var smtpClient = new SmtpSubscribeSingleton(smtpHost, smtpPort, isSsl, email, password);
smtpClient.Send(new MimeMessage());
```
Even if the email address is incorrect, it will prompt a successful delivery. What I need is whether the result is correct
