### ISSUE TITLE
Issue Attaching File Mailkit 2.1.5.1 .net core 2.2.5

### ISSUE THREAD

**Issue by eeaquino** [jstedfast/MailKit#864]
- What were you trying to do?
Send and email with HTML and a PDF Attachment

- What happened?
Exception on NetworkStream.Write

- What did you expect to happen?
Email to be sent.

- Step-by-step reproduction instructions and/or a simple test case.
Create an email
Add some HTML to body
Add a PDF attachment (I used small 300KB)
Connect to SMTP server
Send Email

Reverting back to 2.1.4 Fixes the issue
SMTP is an open server with no authentication using port 25
Sending an email without any attachments does not have any issues.

**Comment by jstedfast** [comment]
What was the exception? You can't honestly expect me to randomly guess the problem.

**Comment by jstedfast** [comment]
Please include the Exception.StackTrace text as well

**Comment by jstedfast** [comment]
While you are getting the exception for me, you should also get the protocol log https://github.com/jstedfast/MailKit/blob/master/FAQ.md#ProtocolLog for me as well.

**Comment by eeaquino** [comment]
Sorry I was going to get it for you, but had to do the downgrade to get the emails going out again.  
After I got everything Fixed I upgraded again to version 2.1.5.1 and everything still worked. If the issue reappears I will get the StackTrace and log.

**Comment by jstedfast** [comment]
It was probably just a temporary SMTP server issue then
