### ISSUE TITLE
Can't send email on production server.

### ISSUE THREAD

**Issue by uthens** [jstedfast/MailKit#865]
**Describe the bug**
I tested on local server and used gmail smtp.gmail.com OR company email, it's worked email send.

But when i release production to customer web server, Email not send and don't have any error exception.

**1) How i can check some service on customer web server are block send email ?** 
**2) I can check the status of the result when send email (complete / failed) ?** 

**Sample on code:** 
```
using (var client = new MailKit.Net.Smtp.SmtpClient())
            {
                await client.ConnectAsync(sSmtp, nPort, false);

                // Note: since we don't have an OAuth2 token, disable
                // the XOAUTH2 authentication mechanism.
                client.AuthenticationMechanisms.Remove("XOAUTH2");
                client.AuthenticationMechanisms.Remove("CRAM-MD5");
                client.AuthenticationMechanisms.Remove("DIGEST-MD5");
                await client.AuthenticateAsync(sTemplateEmailEmailFrom, sAuthenPassword);

                try
                {
                    client.Send(message);
                    System.IO.File.WriteAllText("C:\\Temp\\NoError.txt","Send");
                }
                catch (SmtpCommandException ex)
                {
                    Console.WriteLine("Error sending message: {0}", ex.Message);
                    Console.WriteLine("\tStatusCode: {0}", ex.StatusCode);

                    switch (ex.ErrorCode)
                    {
                        case SmtpErrorCode.RecipientNotAccepted:
                            Console.WriteLine("\tRecipient not accepted: {0}", ex.Mailbox);
                            break;
                        case SmtpErrorCode.SenderNotAccepted:
                            Console.WriteLine("\tSender not accepted: {0}", ex.Mailbox);
                            break;

                        case SmtpErrorCode.MessageNotAccepted:
                            Console.WriteLine("\tMessage not accepted.");
                            break;
                    }
                }
                catch (SmtpProtocolException ex)
                {
                    Console.WriteLine("Protocol error while sending message: {0}", ex.Message);
                }
                client.Disconnect(true);
                System.IO.File.WriteAllText("C:\\Temp\\DiscountTrue.txt", "DiscountTrue");
            }
        }
```
**Screenshots**
I checked on telnet on customer web server
![image](https://user-images.githubusercontent.com/10783170/58631509-fd0f5f00-830c-11e9-989c-009c209d4a77.png)

![image](https://user-images.githubusercontent.com/10783170/58631912-309eb900-830e-11e9-82e1-fcc97dcec81a.png)

**Other information on server:**
 - OS: Windows Server 2008 R2 Standard SP1

**Comment by jstedfast** [comment]
You could try getting a protocol log (see https://github.com/jstedfast/MailKit/blob/master/FAQ.md#ProtocolLog for details on how to do that).

FWIW, in order to send mail from your customer's web server to smtp.gmail.com, you need to authenticate via a web browser from your customer's web server FIRST.

**Comment by uthens** [comment]
This information on smtp.log 

Connected to smtp://mail.myemailcompany.com:587/?starttls=when-available
S: 220 mail.myemailcompany.com ESMTP Sendmail 8.14.4/8.14.4; Thu, 30 May 2019 12:00:36 -0400
C: EHLO [192.168.1.57]
S: 250-mail.myemailcompany.com Hello jcg-cp-http.xxx.com [206.170.126.5], pleased to meet you
S: 250-ENHANCEDSTATUSCODES
S: 250-PIPELINING
S: 250-8BITMIME
S: 250-SIZE
S: 250-DSN
S: 250-AUTH DIGEST-MD5 CRAM-MD5 LOGIN PLAIN
S: 250-STARTTLS
S: 250-DELIVERBY
S: 250 HELP
C: STARTTLS
S: 220 2.0.0 Ready to start TLS

Can you reviews on this ? Thanks you

**Comment by uthens** [comment]
FWIW, in order to send mail from your customer's web server to smtp.gmail.com, you need to authenticate via a web browser from your customer's web server FIRST

I think i'm already to do it on customer web server, but still can't send email.

**Comment by jstedfast** [comment]
You didn't include your authentication attempt which I assume fails because you need to authenticate first using a web browser from the client's web server.

**Comment by uthens** [comment]
_"you need to authenticate first using a web browser from the client's web server."_

I just login gmail account on web browser on the client's web server first time it's correct ? 
you can more explain on this, thank you.

**This is step i do:** 
1) login gmail on web browser on client web server on the first time.
2) and logout email on web browser
3) start to test send email on iOS APP and connect with web API (it's included MailKit) on client web sever
4) email don't send out

What i should to next ?  because some server it's worked but some server don't work. 
If you source code on the first comment, it's correct logic or not ?

**Comment by jstedfast** [comment]
Don't use smtp.gmail.com if you don't know how to get it working.

GMail blocks you from sending mail unless it recognizes your IP address from a previous login via a web browser.

I don't know all of the details so I can't help you. You'll have to do some google searches and figure it out.

**Comment by uthens** [comment]
Ok, i will switch to use my company email instead.
I don't understand why  "smtp.gmail.com" it's worked on azure server.

but don't working on customer server they used windows server 2008,  however i still try to fix on this problem and let you know how i fix soon.
Thanks you.

**Comment by jstedfast** [comment]
You probably need to not log out of gmail on the web browser.

**Comment by skashif18** [comment]
for me also it's not working on the production server, I am using my company mail, and the strange thing is there is no error or exception coming.
