### ISSUE TITLE
MailKit.Net.Smtp.SmtpCommandException: 5.5.2 Syntax error on production environment

### ISSUE THREAD

**Issue by alexmejiaec** [jstedfast/MailKit#866]
**Describe the bug**
This only happens in my production environment with Windows Server 2012
Working perfectly in my Dev environment

Both Environments targetting .Net framework 4.5.2
I've already tried to connect so smtp.gmail.com via telnet in both environments and both connections were sucessfull

Getting the following error when trying to send a mail via stmp.gmail.com:587: 

2019-05-30 12:19:52,831 [6] ERROR Servicio.EnvioMail.EnvioMailServicio [(null)] - MailKit.Net.Smtp.SmtpCommandException: 5.5.2 Syntax error. d79sm1362627vkd.23 - gsmtp
   en MailKit.Net.Smtp.SmtpClient.OnRecipientNotAccepted(MimeMessage message, MailboxAddress mailbox, SmtpResponse response)
   en MailKit.Net.Smtp.SmtpClient.ProcessRcptToResponse(MimeMessage message, MailboxAddress mailbox, SmtpResponse response)
   en MailKit.Net.Smtp.SmtpClient.<FlushCommandQueueAsync>d__59.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en MailKit.Net.Smtp.SmtpClient.<SendAsync>d__106.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   en MailKit.Net.Smtp.SmtpClient.<SendAsync>d__106.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en MailKit.Net.Smtp.SmtpClient.Send(FormatOptions options, MimeMessage message, CancellationToken cancellationToken, ITransferProgress progress)
   en MailKit.MailTransport.Send(MimeMessage message, CancellationToken cancellationToken, ITransferProgress progress)

Currently using the following code 
Client definition :
```
MimeKit.MimeMessage toMail;
            clsNSeguridad seguridadBL = new clsNSeguridad();
            CrearMail_MailKit(out toMail, tiCompania, tsSubject, tsAddress, tsMailMessage, tbIsBodyHtml, CCs, toAttachments, EmbeddedImage);

            if (mkClient == null)
            {                
                mkClient = new MailKit.Net.Smtp.SmtpClient(new MailKit.ProtocolLogger("smtp.log"));
                mkClient.Timeout = 5000;
                mkClient.AuthenticationMechanisms.Remove("XOAUTH2");
            }

            if (!mkClient.IsConnected)
            {
                mkClient.Connect(tiCompania.HostMail, tiCompania.ciPuertoMail ?? 25);
            }

            if (!mkClient.IsAuthenticated)
            {
                mkClient.Authenticate(tiCompania.txEmail, seguridadBL.Desencriptar(tiCompania.txContraseniaMail));
            }

            mkClient.Send(toMail);
```

For message :

`
   toMail = new MimeKit.MimeMessage();
            toMail.From.Add(new MimeKit.MailboxAddress(tiCompania.txEmail));

            foreach (var item in tsAddress.Split(';')) {
                toMail.To.Add(new MimeKit.MailboxAddress(item.Trim()));
            }

            if (CCs != null)
                foreach (var CC in CCs)
                    toMail.Cc.Add(new MimeKit.MailboxAddress(CC));

            toMail.Subject = tsSubject;

            var builder = new MimeKit.BodyBuilder();
            if (tbIsBodyHtml)
            {
                builder.HtmlBody = tsMailMessage;

                             
            }
            else
            {
                builder.TextBody = tsMailMessage;
            }

            if (toAttachments != null)
            {
                foreach (var poAtachment in toAttachments)
                {
                    var attachment = new MimeKit.MimePart(poAtachment.ContentType.MediaType)
                    {
                        Content = new MimeKit.MimeContent(poAtachment.ContentStream, MimeKit.ContentEncoding.Default),
                        ContentDisposition = new MimeKit.ContentDisposition(MimeKit.ContentDisposition.Attachment),
                        ContentTransferEncoding = MimeKit.ContentEncoding.Base64,
                        FileName = poAtachment.Name
                    };
                    builder.Attachments.Add(attachment);
                }
            }

            toMail.Body = builder.ToMessageBody();

`

**Comment by alexmejiaec** [comment]
smtp log 

C: RSET
S: 250 2.1.5 Flushed n68sm3960564vkd.0 - gsmtp
C: MAIL FROM:<cooperativaputumayo@gmail.com>
C: RCPT TO:<mercedes_1991@xxxxxxx.es>
C: RCPT TO:<>
S: 250 2.1.0 OK n68sm3960564vkd.0 - gsmtp
S: 250 2.1.5 OK n68sm3960564vkd.0 - gsmtp
S: 555 5.5.2 Syntax error. n68sm3960564vkd.0 - gsmtp
C: RSET
S: 250 2.1.5 Flushed n68sm3960564vkd.0 - gsmtp
C: MAIL FROM:<cooperativaputumayo@gmail.com>
C: RCPT TO:<l@xxxxxxx.com>
C: RCPT TO:<>
S: 250 2.1.0 OK n68sm3960564vkd.0 - gsmtp
S: 250 2.1.5 OK n68sm3960564vkd.0 - gsmtp
S: 555 5.5.2 Syntax error. n68sm3960564vkd.0 - gsmtp
C: RSET
S: 250 2.1.5 Flushed n68sm3960564vkd.0 - gsmtp
C: MAIL FROM:<cooperativaputumayo@gmail.com>
C: RCPT TO:<l@xxxxxxx.com>
C: RCPT TO:<>
S: 250 2.1.0 OK n68sm3960564vkd.0 - gsmtp
S: 250 2.1.5 OK n68sm3960564vkd.0 - gsmtp
S: 555 5.5.2 Syntax error. n68sm3960564vkd.0 - gsmtp
C: RSET
S: 250 2.1.5 Flushed n68sm3960564vkd.0 - gsmtp
C: MAIL FROM:<cooperativaputumayo@gmail.com>
C: RCPT TO:<coop@xxxxxxx.com>
C: RCPT TO:<>
S: 250 2.1.0 OK n68sm3960564vkd.0 - gsmtp
S: 250 2.1.5 OK n68sm3960564vkd.0 - gsmtp
S: 555 5.5.2 Syntax error. n68sm3960564vkd.0 - gsmtp
C: RSET
S: 250 2.1.5 Flushed n68sm3960564vkd.0 - gsmtp
C: MAIL FROM:<cooperativaputumayo@gmail.com>
C: RCPT TO:<coop@hotmal.com>
C: RCPT TO:<>
S: 250 2.1.0 OK n68sm3960564vkd.0 - gsmtp
S: 250 2.1.5 OK n68sm3960564vkd.0 - gsmtp
S: 555 5.5.2 Syntax error. n68sm3960564vkd.0 - gsmtp
C: RSET
S: 250 2.1.5 Flushed n68sm3960564vkd.0 - gsmtp
C: MAIL FROM:<cooperativaputumayo@gmail.com>
C: RCPT TO:<duniaarmijos@yahoo.com>
C: RCPT TO:<>
S: 250 2.1.0 OK n68sm3960564vkd.0 - gsmtp
S: 250 2.1.5 OK n68sm3960564vkd.0 - gsmtp
S: 555 5.5.2 Syntax error. n68sm3960564vkd.0 - gsmtp
C: RSET
S: 250 2.1.5 Flushed n68sm3960564vkd.0 - gsmtp
C: MAIL FROM:<cooperativaputumayo@gmail.com>
C: RCPT TO:<duniaarmijos@yahoo.com>
C: RCPT TO:<>
S: 250 2.1.0 OK n68sm3960564vkd.0 - gsmtp
S: 250 2.1.5 OK n68sm3960564vkd.0 - gsmtp
S: 555 5.5.2 Syntax error. n68sm3960564vkd.0 - gsmtp
C: RSET
S: 250 2.1.5 Flushed n68sm3960564vkd.0 - gsmtp
C: MAIL FROM:<cooperativaputumayo@gmail.com>
C: RCPT TO:<distribuidoraespinza@yahoo.com>
C: RCPT TO:<>
S: 250 2.1.0 OK n68sm3960564vkd.0 - gsmtp
S: 250 2.1.5 OK n68sm3960564vkd.0 - gsmtp
S: 555 5.5.2 Syntax error. n68sm3960564vkd.0 - gsmtp
C: RSET
S: 250 2.1.5 Flushed n68sm3960564vkd.0 - gsmtp
C: QUIT
S: 221 2.0.0 closing connection n68sm3960564vkd.0 - gsmtp

**Comment by jstedfast** [comment]
This is the problem: `C: RCPT TO:<>`

You are adding a MailboxAddress with an empty string as the address. That's a bug in your code.

**Comment by NismanSolutions** [comment]
Although this could be considered a bug in the Mailkit client the handling of this edge case is less than optimal. 

Here is the use case:
```
            data.ReplyToAddresses.ForEach(x =>
            {
                message.ReplyTo.Add(new MailboxAddress(x.Name, x.EmailAddress));
            });
```

Here are the shortcomings:

1. When the 'EmailAddress' passed into the 'MailboxAddress' is an Empty string (not Null) the code above produce no Exception. even though the code would 100% fail later when trying to send the message.
2. When sending this message from the 'SmtpClient' with an empty string email the Exception generated is 'The SMTP server has unexpectedly disconnected'. This has no relevant\useful information for troubleshooting.

It took 3 hours of tedious searching and leaving no other option than analyzing Smtp protocol logs to figure out the issue. The issue was simply caused by entering an empty string "" in the configuration file used to set BCC.

It would be an improvement imo to implement points 1 or 2 above.

**Comment by jstedfast** [comment]
@NismanSolutions the problem is that an empty string is technically a valid address that can be used in some situations

If you get `The SMTP server has unexpectedly disconnected`, it typically means that there is no useful info that can be provided because the server severed the connections w/o an error.

**Comment by NismanSolutions** [comment]
I see, thank you for the explanation. Perhaps the empty string could be offered as a possible root of the problem on the receiver. It may save people the headache. There is a number of 'The SMTP server has unexpectedly disconnected' threads on the web with no useful information.
