### ISSUE TITLE
How do I know when the message is sent after I receive it successfully

### ISSUE THREAD

**Issue by yZuoB** [jstedfast/MailKit#867]
How do I know when the message is sent after I receive it successfully

**Comment by jstedfast** [comment]
Well, if you've received it, then I guess it means that it was sent ;-)

**Comment by yZuoB** [comment]
Thank you, I made an obvious mistake, and there is a specific time in the file that receives the mail.



yaozuobang@163.comt
 
From: Jeffrey Stedfast
Date: 2019-06-05 19:30
To: jstedfast/MailKit
CC: yZuoB; Author
Subject: Re: [jstedfast/MailKit] How do I know when the message is sent after I receive it successfully (#867)
Well, if you've received it, then I guess it means that it was sent ;-)
―
