### ISSUE TITLE
IMAP search SearchQuery.SentAfter confiusing

### ISSUE THREAD

**Issue by VBWebprofi** [jstedfast/MailKit#868]
I'm using ``SearchQuery.SentAfter`` at an ``ImapFolder`` of your library. ``SentAfter`` I meant to specify a ``DateTime`` before the date range I'm looking for. But I saw at protocol log it's translated to "``SENTSINCE``", which is of different meaning.

In case of ``SentAfter`` I would specify ``2009-12-31T23:59:59``.
For a ``SENTSINCE`` a ``2010-01-01T00:00:00`` would be right to get all mails since 1st of January 2010 00:00:00.

This should be clearified for use with IMAP. Maybe ``SentAfter`` does what it implies on other protocols?

**Comment by jstedfast** [comment]
I've renamed the method to SentSince now.

**Comment by VBWebprofi** [comment]
Ok, don't know if done or not, place a hint to documentation of that methods ``SentSince`` and ``SentBefore`` that they only use the date from the ``DateTime`` 😉

**Comment by jstedfast** [comment]
It already does ;-)
