### ISSUE TITLE
Attachment Examples get filename causes compiler errors

### ISSUE THREAD

**Issue by DrewBuchanan** [jstedfast/MailKit#869]
To help me debug your issue, please explain:
- What were you trying to do?
I was trying to get the file name of an attachment using the syntax from AttachmentsExamples.SaveAttachments (var fileName = attachment.ContentDisposition?.FileName : (attachment.ContentType.Name ?? "attached.eml");)
- What happened?
I got 3 compiler errors.
![image](https://user-images.githubusercontent.com/12664792/59218521-11adeb80-8b86-11e9-914f-6ecaaf2c0ed1.png)
- Step-by-step reproduction instructions and/or a simple test case.
I created a new project in git, then added MailKit.Net45 and MimeKit.Net45 as submodules, then tried to recreate the example code. My project that uses MailKit and MimeKit is using .NET Framework 4.6.2 and I'm developing in Visual Studio Professional 2017.

**Comment by DrewBuchanan** [comment]
Additional context: http://www.mimekit.net/docs/html/Frequently-Asked-Questions.htm#SaveAttachments

**Comment by jstedfast** [comment]
Thanks. I've fixed the documentation.
