### ISSUE TITLE
Proxy Http Sample

### ISSUE THREAD

**Issue by WontheSD** [jstedfast/MailKit#870]
As I found in project description, Mailkit support http proxy.
But in the samples there are not any item on that. can you support it?
Thanks a lot

**Comment by jstedfast** [comment]
```csharp
using (var client = new SmtpClient ()) {
    client.ProxyClient = new HttpProxyClient ("www.myproxy.com", 8080);
    client.Connect ("smtp.host.com", 587, false);
    ...
}
```

**Comment by WontheSD** [comment]
My code is as below, but an exception was throw

System.Net.NetworkCredential objNetworkCredential = new System.Net.NetworkCredential("username", "password");
            MailKit.Net.Proxy.HttpProxyClient objHttpProxyClient = new HttpProxyClient("ip", 8080, objNetworkCredential);

            using (ImapClient objClient = new ImapClient())
            {
               
                objClient.AuthenticationMechanisms.Remove("XOAUTH2");
                objClient.ProxyClient = objHttpProxyClient;
                objClient.Connect("imapserver.host.com", 993, SecureSocketOptions.SslOnConnect);
                

                objClient.Authenticate("username", "password");
                
                
                objClient.Inbox.Open(FolderAccess.ReadOnly);
                
                DateTime dtStart = new DateTime(2019, 6, 10);
                DateTime dtEnd = new DateTime(2019, 6, 20);
                SearchQuery objQuery;
                //objQuery = SearchQuery.DeliveredAfter(dtStart).And(SearchQuery.DeliveredBefore(dtEnd));
                objQuery = SearchQuery.DeliveredAfter(dtStart);

                IList<UniqueId> uids;
                uids = objClient.Inbox.Search(objQuery);
                //uids = objClient.Inbox.Search(SearchQuery.All);


                objClient.Disconnect(true);

            }

**Comment by WontheSD** [comment]
MailKit.Security.SslHandshakeException
  HResult=0x80131500
  Message=An error occurred while attempting to establish an SSL or TLS connection.

One possibility is that you are trying to connect to a port which does not support SSL/TLS.

The other possibility is that the SSL certificate presented by the server is not trusted by the system for one or more of the following reasons:
1. The server is using a self-signed certificate which cannot be verified.
2. The local system is missing a Root or Intermediate certificate needed to verify the server's certificate.
3. The certificate presented by the server is expired or invalid.

See https://github.com/jstedfast/MailKit/blob/master/FAQ.md#InvalidSslCertificate for possible solutions.
  Source=MailKit
  StackTrace:
   at MailKit.Net.Imap.ImapClient.<ConnectAsync>d__89.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MailKit.Net.Imap.ImapClient.Connect(String host, Int32 port, SecureSocketOptions options, CancellationToken cancellationToken)
   at NetFrameworkWebAppRPA.MailKitTest.Sample1.testImap2() in D:\MikeProjects\Test\NetFrameworkWebAppWebForm\NetFrameworkWebAppRPA\MailKitTest\Sample1.aspx.cs:line 94
   at NetFrameworkWebAppRPA.MailKitTest.Sample1.Page_Load(Object sender, EventArgs e) in D:\MikeProjects\Test\NetFrameworkWebAppWebForm\NetFrameworkWebAppRPA\MailKitTest\Sample1.aspx.cs:line 25

Inner Exception 1:
AuthenticationException: The remote certificate is invalid according to the validation procedure.

**Comment by WontheSD** [comment]
Limilabs Mail work well

**Comment by jstedfast** [comment]
My guess is that your imap server's SSL certificate is a self-signed certificate.

What Limilabs does is equivalent to this:

```csharp
System.Net.NetworkCredential objNetworkCredential = new System.Net.NetworkCredential("username", "password");
MailKit.Net.Proxy.HttpProxyClient objHttpProxyClient = new HttpProxyClient("ip", 8080, objNetworkCredential);

using (ImapClient objClient = new ImapClient())
{
    objClient.ServerCertificateValidationCallback = (s,c,h,e) => true;    // add this line
    objClient.ProxyClient = objHttpProxyClient;
    objClient.Connect("imapserver.host.com", 993, SecureSocketOptions.SslOnConnect);

    objClient.Authenticate("username", "password");

    objClient.Inbox.Open(FolderAccess.ReadOnly);

    DateTime dtStart = new DateTime(2019, 6, 10);
    DateTime dtEnd = new DateTime(2019, 6, 20);
    SearchQuery objQuery;
    //objQuery = SearchQuery.DeliveredAfter(dtStart).And(SearchQuery.DeliveredBefore(dtEnd));
    objQuery = SearchQuery.DeliveredAfter(dtStart);

    IList<UniqueId> uids;
    uids = objClient.Inbox.Search(objQuery);
    //uids = objClient.Inbox.Search(SearchQuery.All);

    objClient.Disconnect(true);
}
```

Of course, the above code snippet is a hack and is a bit of a security risk (same as it would be if you used Limilabs), and what you *should* do instead is something more like this:

```csharp
bool MyServerCertificateValidationHandler (object sender, X509Certificate certificate, X509Chain chain, SslPolicyErrors sslPolicyErrors)
{
    if (sslPolicyErrors == SslPolicyErrors.None)
        return true;

    return PromptUserToTrustThisCertificate (certificate);
}

...

objClient.ServerCertificateValidationCallback = MyServerCertificateValidationHandler;
```

I'm sure you've seen SSL certificate dialogs in your favorite web browser or email client where it asks if you trust the certificate and want to always trust it or just this once kind of thing. Well, that's *exactly* what you have to do in that callback (or have a known thumbprint saved somewhere that you can use to compare).

The reason that Limilabs trusts all SSL certifcates by default is so that everything appears to work like a charm.

MailKit doesn't do it by default because it is a security risk.

That's the difference.

**Comment by jstedfast** [comment]
FWIW, if you followed the HelpLink in the exception, this is all explained there:

https://github.com/jstedfast/MailKit/blob/master/FAQ.md#InvalidSslCertificate

**Comment by jstedfast** [comment]
This may be a helpful callback implementation to help you figure out what the issue is with your server's certificate:

```csharp
static bool ServerCertificateValidationCallback (object sender, X509Certificate certificate, X509Chain chain, SslPolicyErrors sslPolicyErrors)
{
	Console.WriteLine ("sender: {0}", sender);
	Console.WriteLine ("certificate: subject={0} issuer={1}", certificate.Subject, certificate.Issuer);
	Console.WriteLine ("SSL Policy Errors: {0}", sslPolicyErrors);

	if (chain != null) {
		Console.WriteLine ("Chain:");

		foreach (var element in chain.ChainElements) {
			Console.WriteLine ("Element Certificate: subject={0} issuer={1}", element.Certificate.Subject, element.Certificate.Issuer);
			Console.Write ("Status:");
			foreach (var status in element.ChainElementStatus) {
				Console.Write (" {0}", status);
			}
			Console.WriteLine ();
		}

		Console.Write ("Chain Status:");
		foreach (var status in chain.ChainStatus) {
			Console.Write (" {0}", status);
		}
		Console.WriteLine ();
	}

	Console.WriteLine ();

	return sslPolicyErrors == SslPolicyErrors.None;
}
```
