### ISSUE TITLE
Unable to relay (Recipient is not accepted)

### ISSUE THREAD

**Issue by ROME12345** [jstedfast/MailKit#873]
What were you trying to do?
Sending a mail with Mailkit. My CC is a Mail outside my domain. (For example: text@gmx.net)

- What happened?
I get the Error "5.7.1 Unable to relay"

- What did you expect to happen?
I expect the mail to be sent to the appropriate address, even if it is not in the domain.

- Step-by-step reproduction instructions and/or a simple test case.

```
SmtpClient client = new SmtpClient();
client.Connect(test.lan, 25, false);

MimeMessage mailMessage = new MimeMessage ();
message.From.Add(new MailboxAddress("b@test.com"));
message.To.Add(new MailboxAddress("a@test.com"));
mailMessage.Cc.Add(new MailboxAddress("test@gmx.net"));
```

Maybe there is a simple setting which I forget to set so that recipients with addresses outside the domain are also possible.

**Comment by jstedfast** [comment]
That error doesn't come from MailKit, it comes from your SMTP server.

I suggest you contact your SMTP server admin and ask him what you need to do to relay mail.

You *probably* need to authenticate before you can relay mail. Did you authenticate?

**Comment by ROME12345** [comment]
I'm trying to change "System.Net.Mail" to "MailKit.Net.Smtp". With the .Net method I didn't need any authentication, only with Mailkit the error occurs.

**Comment by jstedfast** [comment]
System.Net.Mail uses your default credentials to authenticate, so I'm betting you're wrong.

**Comment by jstedfast** [comment]
https://www.kerneldatarecovery.com/blog/how-to-fix-exchange-smtp-error-550-unable-to-relay/

That FAQ says that error is caused when a user who is unauthenticated attempts to send mail. Sound familiar?
