### ISSUE TITLE
SmtpClient disconnecting after 70-90 emails with Gmail

### ISSUE THREAD

**Issue by andyfurniss4** [jstedfast/MailKit#877]
I am trying to send a large number of emails (around 500) using MailKit and connecting to Gmail's SMTP. However, the client always falls on it's face after about 70-90 emails (it varies). When running locally, I always get the following:

> The SMTP server has unexpectedly disconnected.

The one time I've run it on production, I got this error:

> 4.7.0 Temporary System Problem. Try again later (10). i4sm4226208wrr.17 - gsmtp

I have seen this following SO ticket - https://stackoverflow.com/questions/55382267/send-mail-with-gmail-smtp-using-mailkit-smtp-client-in-net-core-2-2-is-not-work - and I have ensured that I am using the most up to date version of MailKit (2.2.0). I've also tried:

- Setting SmtpClient.Timeout to longer than the default but this doesn't seem to help.
- TLS and SSL connections.

I'm unsure if this is a Gmail issue or a MailKit issue. 

Here's my code:

```
public class GmailClient : IEmailClient
{
	private readonly ILogger logger;

	public GmailClient(ILogger logger)
	{
		this.logger = logger;
	}

	public async Task SendEmailBatch(IEnumerable<MimeMessage> messages)
	{
		var credentials = await getCredentials(((MailboxAddress)messages.First().From.First()).Address);

		using (var client = new SmtpClient())
		{
			client.Timeout = (int)TimeSpan.FromSeconds(200).TotalMilliseconds;

			await client.ConnectAsync("smtp.gmail.com", 465, true);

			var oauth2 = new SaslMechanismOAuth2(credentials.User, credentials.Token.AccessToken);
			client.Authenticate(oauth2);

			foreach (var message in messages)
			{
				await this.sendEmailInternal(client, message);
			}
			
			await client.DisconnectAsync(true);
		}
	}

	private async Task sendEmailInternal(SmtpClient client, MimeMessage email)
	{
		try
		{
			await client.SendAsync(email);
			this.logger.Information($"Successfully sent email to {string.Join(", ", email.To.Select(x => ((MailboxAddress)x).Address))}");
		}
		catch (Exception ex)
		{
			this.logger.Error(ex, $"Failed to send email to {string.Join(", ", email.To.Select(x => ((MailboxAddress)x).Address))}");
			throw;
		}
	}

	private async Task<ServiceAccountCredential> getCredentials(string fromAddress)
	{
		var certificiate = new X509Certificate2("certificate.p12", "notasecret", X509KeyStorageFlags.Exportable);
		var credentials = new ServiceAccountCredential(
			new ServiceAccountCredential.Initializer("foo@bar.iam.gserviceaccount.com")
			{
				Scopes = new[] { GmailService.Scope.MailGoogleCom },
				User = fromAddress
			}.FromCertificate(certificiate));

		if (!await credentials.RequestAccessTokenAsync(new CancellationToken()))
		{
			throw new ApplicationException("Error requesting access token for Gmail authentication");
		}

		return credentials;
	}
}
```

I have an integration test that sends 100 emails messages to SendEmailBatch and as I say, I get an exception in sendEmailInternal after 70-90 emails every time.

Versions:
MailKit: 2.2.0
.Net Core: 2.1

**Comment by jstedfast** [comment]
The Timeout property likely doesn't have anything to do with this issue. Most of the time, when you get an unexpected disconnect, it's because the server has dropped your connection.

You may have idled too long (doesn't seem likely based on your code since it just sends all of these messages in a row) or perhaps GMail decided to disconnect you because of the number of emails you've sent in a short period of time (in fact, I *know* they do this, I just don't remember what the threshold is).

GMail has a number of anti-spam measures that it employs to limit bulk mail sending.

You could try getting a protocol log (`new SmtpClient (new ProtocolLogger ("smtp.log")`) and see if that provides any more useful info (likely as part of the last message your app tries to send).

**Comment by andyfurniss4** [comment]
Thanks for getting back to me @jstedfast. I had a feeling it might have been GMail but was willing it not to be true because then I can't do anything about it! I also couldn't find any limitations documented anywhere.

I will try the ProtocolLogger tomorrow and get back to you with the results.

**Comment by jstedfast** [comment]
FWIW, I found this: https://support.google.com/a/answer/176600?hl=en

It says it limits to 2000 messages per day, which is quite a bit more than the 70-90 limit you are hitting, but maybe there is also a limit per session. *shrug*

**Comment by andyfurniss4** [comment]
Just tried the `ProtocolLogger`. All it gives me is:

> 421 4.7.0 Try again later, closing connection. (MAIL) f18sm7368744wrt.43 - gsmtp

Found this error on the SMTP error reference: https://support.google.com/a/answer/3726730?hl=en. 

> 421, "4.7.0", Try again later, closing connection. This usually indicates a Denial of Service (DoS) for the SMTP relay at the HELO stage.

Sounds like you're right regarding Gmail limiting the sending. I'm not really sure what to do now!

I know this is pretty much out of scope for you now but do you have any advice/suggestions? Would using something like AWS SES help me get around this issue?

**Comment by jstedfast** [comment]
My recommendation would probably be to find another SMTP host or possibly hosting your own SMTP server.
