### ISSUE TITLE
LIST EXTENDED command return weird result

### ISSUE THREAD

**Issue by ekalchev** [jstedfast/MailKit#879]
I am executing the command below and this is the imap log below. Note that some of the folders are missing Status command (INBOX.Archive, INBOX.spam.&-BD0EOQQ9BDkEPQ-). Is this server issue or incorrect imap command formatting?

Note that those folders are valid and I can open them. Imap server is Dovecot

`imapClient.GetFolders(imapClient.PersonalNamespaces[0], StatusItems.HighestModSeq, false, shutdownToken)
`

C: B00000007 LIST "" "INBOX.*" RETURN (SUBSCRIBED CHILDREN STATUS (HIGHESTMODSEQ))
S: * LIST (\Subscribed \HasNoChildren \UnMarked) "." INBOX.gfgfee888
S: * STATUS INBOX.gfgfee888 (HIGHESTMODSEQ 1)
S: * LIST (\Subscribed \HasNoChildren \UnMarked) "." INBOX.99999999
S: * STATUS INBOX.99999999 (HIGHESTMODSEQ 3)
S: * LIST (\Subscribed \HasNoChildren \UnMarked) "." INBOX.yyyyyyyyyyyyy
S: * STATUS INBOX.yyyyyyyyyyyyy (HIGHESTMODSEQ 1)
S: * LIST (\Subscribed \HasNoChildren \UnMarked) "." INBOX.y
S: * STATUS INBOX.y (HIGHESTMODSEQ 1)
S: * LIST (\Subscribed \HasNoChildren \UnMarked) "." INBOX.fgfgfg
S: * STATUS INBOX.fgfgfg (HIGHESTMODSEQ 61)
S: * LIST (\Subscribed \HasChildren \UnMarked) "." INBOX.Mailspring
S: * STATUS INBOX.Mailspring (HIGHESTMODSEQ 1)
S: * LIST (\Subscribed \HasNoChildren \UnMarked) "." INBOX.Mailspring.Snoozed
S: * STATUS INBOX.Mailspring.Snoozed (HIGHESTMODSEQ 1)
S: * LIST (\Subscribed \HasNoChildren \UnMarked) "." INBOX.fgfgf
S: * STATUS INBOX.fgfgf (HIGHESTMODSEQ 3)
S: * LIST (\Subscribed \HasNoChildren \UnMarked) "." INBOX.gggg34
S: * STATUS INBOX.gggg34 (HIGHESTMODSEQ 5)
S: * LIST (\Subscribed \HasChildren \UnMarked) "." INBOX.gggg
S: * STATUS INBOX.gggg (HIGHESTMODSEQ 2)
S: * LIST (\Subscribed \HasNoChildren \UnMarked) "." INBOX.gggg.hhhh
S: * STATUS INBOX.gggg.hhhh (HIGHESTMODSEQ 1)
S: * LIST (\Subscribed \HasNoChildren \UnMarked) "." INBOX.mkmkm
S: * STATUS INBOX.mkmkm (HIGHESTMODSEQ 1)
S: * LIST (\Subscribed \HasChildren \UnMarked) "." INBOX.sdfsf
S: * STATUS INBOX.sdfsf (HIGHESTMODSEQ 1)
S: * LIST (\HasChildren \UnMarked) "." INBOX.sdfsf.sdfsdfsdfsd
S: * STATUS INBOX.sdfsf.sdfsdfsdfsd (HIGHESTMODSEQ 1)
S: * LIST (\HasNoChildren \UnMarked) "." INBOX.sdfsf.sdfsdfsdfsd.zzzz
S: * STATUS INBOX.sdfsf.sdfsdfsdfsd.zzzz (HIGHESTMODSEQ 2263)
S: * LIST (\Subscribed \HasChildren \UnMarked) "." INBOX.uuyy
S: * STATUS INBOX.uuyy (HIGHESTMODSEQ 1)
S: * LIST (\Subscribed \HasChildren \UnMarked) "." INBOX.uuyy.sdfsdf
S: * STATUS INBOX.uuyy.sdfsdf (HIGHESTMODSEQ 1)
S: * LIST (\Subscribed \HasChildren \UnMarked) "." "INBOX.uuyy.sdfsdf.New Folder"
S: * STATUS "INBOX.uuyy.sdfsdf.New Folder" (HIGHESTMODSEQ 1)
S: * LIST (\Subscribed \HasChildren \UnMarked) "." "INBOX.uuyy.sdfsdf.New Folder.dfgdfg"
S: * STATUS "INBOX.uuyy.sdfsdf.New Folder.dfgdfg" (HIGHESTMODSEQ 1)
S: * LIST (\Subscribed \HasChildren \UnMarked) "." "INBOX.uuyy.sdfsdf.New Folder.dfgdfg.sdfsdfsdf"
S: * STATUS "INBOX.uuyy.sdfsdf.New Folder.dfgdfg.sdfsdfsdf" (HIGHESTMODSEQ 1)
S: * LIST (\Subscribed \HasChildren \UnMarked) "." "INBOX.uuyy.sdfsdf.New Folder.dfgdfg.sdfsdfsdf.sdfsdfsfsdf"
S: * STATUS "INBOX.uuyy.sdfsdf.New Folder.dfgdfg.sdfsdfsdf.sdfsdfsfsdf" (HIGHESTMODSEQ 1)
S: * LIST (\Subscribed \HasNoChildren \UnMarked) "." "INBOX.uuyy.sdfsdf.New Folder.dfgdfg.sdfsdfsdf.sdfsdfsfsdf.asdasdasd"
S: * STATUS "INBOX.uuyy.sdfsdf.New Folder.dfgdfg.sdfsdfsdf.sdfsdfsfsdf.asdasdasd" (HIGHESTMODSEQ 1)
S: * LIST (\Subscribed \HasNoChildren \UnMarked) "." INBOX.uuyy.fdfgdfg
S: * STATUS INBOX.uuyy.fdfgdfg (HIGHESTMODSEQ 2)
S: * LIST (\Subscribed \HasNoChildren \UnMarked) "." INBOX.vvvcv
S: * STATUS INBOX.vvvcv (HIGHESTMODSEQ 2627)
S: * LIST (\Subscribed \HasNoChildren \UnMarked) "." INBOX.hallo
S: * STATUS INBOX.hallo (HIGHESTMODSEQ 96)
S: * LIST (\Subscribed \HasChildren \UnMarked) "." "INBOX.New Folder"
S: * STATUS "INBOX.New Folder" (HIGHESTMODSEQ 1)
S: * LIST (\Subscribed \HasNoChildren \UnMarked) "." "INBOX.New Folder.omgfolder"
S: * STATUS "INBOX.New Folder.omgfolder" (HIGHESTMODSEQ 1)
S: * LIST (\Subscribed \HasNoChildren \UnMarked) "." "INBOX.New Folder.testfolder"
S: * STATUS "INBOX.New Folder.testfolder" (HIGHESTMODSEQ 1)
S: * LIST (\HasNoChildren \UnMarked) "." "INBOX.New Folder.hkhk"
S: * STATUS "INBOX.New Folder.hkhk" (HIGHESTMODSEQ 1)
S: * LIST (\Subscribed \HasNoChildren \UnMarked) "." "INBOX.New Folder.zzz"
S: * STATUS "INBOX.New Folder.zzz" (HIGHESTMODSEQ 1)
S: * LIST (\Subscribed \HasNoChildren \UnMarked) "." "INBOX.New Folder.aaa"
S: * STATUS "INBOX.New Folder.aaa" (HIGHESTMODSEQ 1)
S: * LIST (\Subscribed \HasNoChildren \UnMarked) "." "INBOX.New Folder.kgkgkk"
S: * STATUS "INBOX.New Folder.kgkgkk" (HIGHESTMODSEQ 1)
S: * LIST (\Subscribed \HasNoChildren \UnMarked) "." "INBOX.New Folder.gggfff"
S: * STATUS "INBOX.New Folder.gggfff" (HIGHESTMODSEQ 1)
S: * LIST (\Subscribed \HasNoChildren \UnMarked) "." "INBOX.New Folder.New Folder"
S: * STATUS "INBOX.New Folder.New Folder" (HIGHESTMODSEQ 1)
S: * LIST (\Subscribed \HasNoChildren \UnMarked) "." "INBOX.New Folder.hhhh"
S: * STATUS "INBOX.New Folder.hhhh" (HIGHESTMODSEQ 1)
S: * LIST (\Subscribed \HasNoChildren \UnMarked) "." "INBOX.New Folder.nnnn"
S: * STATUS "INBOX.New Folder.nnnn" (HIGHESTMODSEQ 1)
S: * LIST (\Subscribed \HasChildren \UnMarked) "." INBOX.asdasd
S: * STATUS INBOX.asdasd (HIGHESTMODSEQ 23)
S: * LIST (\HasNoChildren \UnMarked) "." INBOX.asdasd.gdfgdfgdfg
S: * STATUS INBOX.asdasd.gdfgdfgdfg (HIGHESTMODSEQ 10)
S: * LIST (\Subscribed \HasChildren \UnMarked) "." INBOX.spam
S: * STATUS INBOX.spam (HIGHESTMODSEQ 44)
S: * LIST (\HasChildren \UnMarked) "." INBOX.spam.&-BD0EOQQ9BDkEPQ-
S: * LIST (\Subscribed \HasChildren \UnMarked) "." INBOX.spam.&-BD0EOQQ9BDkEPQ-.jhfhg
S: * STATUS INBOX.spam.&-BD0EOQQ9BDkEPQ-.jhfhg (HIGHESTMODSEQ 1)
S: * LIST (\Subscribed \HasNoChildren \UnMarked) "." "INBOX.spam.&-BD0EOQQ9BDkEPQ-.jhfhg.New Folder"
S: * STATUS "INBOX.spam.&-BD0EOQQ9BDkEPQ-.jhfhg.New Folder" (HIGHESTMODSEQ 1)
S: * LIST (\Subscribed \HasChildren \UnMarked) "." INBOX.spam.&-BD0EOQQ9BDkEPQ-.jhfhg.aaa
S: * STATUS INBOX.spam.&-BD0EOQQ9BDkEPQ-.jhfhg.aaa (HIGHESTMODSEQ 1)
S: * LIST (\Subscribed \HasNoChildren \UnMarked) "." INBOX.spam.&-BD0EOQQ9BDkEPQ-.jhfhg.aaa.aaa
S: * STATUS INBOX.spam.&-BD0EOQQ9BDkEPQ-.jhfhg.aaa.aaa (HIGHESTMODSEQ 1)
S: * LIST (\Subscribed \HasNoChildren \UnMarked) "." INBOX.Sent
S: * STATUS INBOX.Sent (HIGHESTMODSEQ 1353)
S: * LIST (\Subscribed \HasNoChildren \UnMarked) "." INBOX.Trash
S: * STATUS INBOX.Trash (HIGHESTMODSEQ 5823)
S: * LIST (\Subscribed \HasChildren \UnMarked) "." INBOX.Junk
S: * STATUS INBOX.Junk (HIGHESTMODSEQ 15)
S: * LIST (\Subscribed \HasChildren \UnMarked) "." INBOX.Junk.asdasd
S: * STATUS INBOX.Junk.asdasd (HIGHESTMODSEQ 1)
S: * LIST (\Subscribed \HasChildren \UnMarked) "." INBOX.Junk.asdasd.rgthfgh
S: * STATUS INBOX.Junk.asdasd.rgthfgh (HIGHESTMODSEQ 1)
S: * LIST (\Subscribed \HasNoChildren \UnMarked) "." INBOX.Junk.asdasd.rgthfgh.Mailspring
S: * STATUS INBOX.Junk.asdasd.rgthfgh.Mailspring (HIGHESTMODSEQ 28)
S: * LIST (\Subscribed \HasChildren \UnMarked) "." INBOX.Junk.asdasd.asdasdasd
S: * STATUS INBOX.Junk.asdasd.asdasdasd (HIGHESTMODSEQ 1)
S: * LIST (\Subscribed \HasNoChildren \UnMarked) "." INBOX.Junk.asdasd.asdasdasd.dfgdfg
S: * STATUS INBOX.Junk.asdasd.asdasdasd.dfgdfg (HIGHESTMODSEQ 1)
S: * LIST (\Subscribed \HasNoChildren \UnMarked) "." INBOX.Drafts
S: * STATUS INBOX.Drafts (HIGHESTMODSEQ 1091)
S: * LIST (\HasNoChildren \UnMarked) "." INBOX.Archive
S: B00000007 OK List completed (0.004 + 0.000 + 0.003 secs).

**Comment by jstedfast** [comment]
Here's some relevant text from rfc5819:

> If the server runs into unexpected problems while trying to look up
> the STATUS information, it MAY drop the corresponding STATUS reply.
> In such a situation, the LIST command would still return a tagged OK
> reply.

This suggests that it's a server issue, but might not be a bug per se. It probably depends on what the reason is, but we can't know that from the protocol logs.

**Comment by ekalchev** [comment]
What I did is to call manually status on the folders that doesn't have its HighestModSeq set to value > 0. However this works only once, after that MailKit cache HighestModSeq value and there is no way to detect if STATUS was called for a particular folder from LIST EXTENDED. 

Does this workaround make sense to be part of Mailkit library?

Is there another workaround for this issue other than removing LIST EXTENDED from ImapClient.Capabilities?

**Comment by jstedfast** [comment]
I don't think this could easily be done in MailKit because it currently doesn't track what changes were made to any folders as part of the command processing. I also don't think you'd want MailKit to zero the requested status items on every folder that didn't get a response (or, more likely the way it would need to be done is to zero everything first, then send the commands), you'd likely want it to retain the previously gotten values and just assume nothing has changed since the last time you got them.

In your case there definitely seems to be a bug in the IMAP server since it is *supposed* to send a STATUS response for every folder, but the spec also states that if it can't for some reason get that info, it *may* just drop the STATUS response for that folder.

Have these folders ever gotten any messages delivered to them? Perhaps the problem is that they haven't been "initialized". I've noticed that some IMAP servers will respond by saying that their UIDNEXT value is 0 (it should be `1` as `0` is invalid) until it gets its first message and then it will behave correctly.

**Comment by ekalchev** [comment]
Yes those folders have emails and HighestModSeq is > 1. 
I'll ask in Dovecot forum for explanation.

**Comment by jstedfast** [comment]
Let me know what you find out. I'm curious :-)

**Comment by ekalchev** [comment]
This is the response from dovecot:

https://github.com/dovecot/core/blob/master/src/imap/cmd-list.c#L195 seems to have a bug. If LIST is requesting SUBSCRIBED results, and it finds there is a folder that is not subscribed but has a child that is subscribed, then the parent isn't requested for STATUS. That matches:

S: * LIST (\HasChildren \UnMarked) "." INBOX.spam.&-BD0EOQQ9BDkEPQ-
S: * LIST (\Subscribed \HasChildren \UnMarked) "." INBOX.spam.&-BD0EOQQ9BDkEPQ-.jhfhg

But in your LIST output INBOX.Archive didn't have any children, so I'm not sure if that's the same issue or not.

**Comment by jstedfast** [comment]
Right, because INBOX.Archive is not subscribed but also has no subscribed children, yet it was returned in the LIST response.

**Comment by ekalchev** [comment]
Why MailKit asked for subscribed children when I am calling 

imapClient.GetFolders with subscribedOnly = false

**Comment by jstedfast** [comment]
It's not. It's asking for all folders and what their subscribed status is.

**Comment by jstedfast** [comment]
To get only a list of subscribed folders, the command would be:

    LSUB "" "INBOX.*"

or

    LIST "" "INBOX.*" (SUBSCRIBED) RETURN (CHILDREN STATUS (HIGHESTMODSEQ))

**Comment by ekalchev** [comment]
Got it. Thanks.

**Comment by jstedfast** [comment]
Basically, MailKit is just trying to get the full state of the folders with the LIST request.

IMHO, the plain-old simple LIST command should have returned `\Subscribed` and `\HasChildren`/`\HasNoChildren` flags from the get-go, but it does not :(

Hopefully the next major version of IMAP will remedy this :)
