### ISSUE TITLE
Move a message to a new Folder while also updating the Date.

### ISSUE THREAD

**Issue by claudiolsmonteiro** [jstedfast/MailKit#880]
- What were you trying to do?

I am currently doing a project, in which, I have to move certain emails to a new folder, but these messages need to have a new date associated when being moved because if they have been in the new folder for longer than a day, I have to move them back.

- Step-by-step reproduction instructions and/or a simple test case.

In order to achieve this I implemented the following solution:
1. Get the message.
2. Add the current date to the Date attribute of the message.
3. Append the message to the new Folder.
4. Delete the message from the previous folder. (I have to do this or else the message will be duplicated.)

```csharp
var message = await this.externalMailFolder.GetMessageAsync(messageUniqueId);
message.Date = DateTimeOffset.UtcNow;
UniqueId? finalId = await destinationMailFolder.AppendAsync(message);
await this.externalMailFolder.AddFlagsAsync(messageUniqueId, MailKit.MessageFlags.Deleted, silent:true);
await this.externalMailFolder.ExpungeAsync();
```

I was wondering if this is the best way to achieve this or is there a better solution?

**Comment by jstedfast** [comment]
I suppose that's fine, although I would recommend against modifying the Date header.

I would just use IMAP's concept of `INTERNALDATE` which represents the date that the message was added t the folder.

When you do `folder.Append (message)`, the IMAP server will set the `INTERNALDATE` to the timestamp when the message was appended to said folder which is exactly what it sounds like you want, and best of all it doesn't modify the raw message source.

To get at the `INTERNALDATE` later, you can use the `MessageSummaryItems.InternalDate` enum flag in a `folder.Fetch()` request to populate the resulting `MessageSummary.InternalDate` property.

Some of the `folder.Search` date-based queries also operate on this date value such as the `DeliveredOn`, `DeliveredBefore`, and `DeliveredAfter` search queries. I'm pretty sure that `OlderThan` and `YoungerThan` also use the `INTERNALDATE` metadata.

**Comment by claudiolsmonteiro** [comment]
Thank you for your reply.

Before following the steps I wrote in the beginning, I tried the method MoveToAsync and noticed the date was still the same. 

After your message, I have tried using the InternalDate and observed that it was also the same as the first delivery date. I then tried using the AppendAsync method that takes a DateTimeOffset as a parameter to no avail.

I thought it would be a problem related to Gmail's Imap server and decided to try in our company's Imap Server, but had the same results.

Do you think I might be missing a step?

**Comment by jstedfast** [comment]
The IMAP `COPY` and `MOVE` commands preserve the `INTERNALDATE` value when copying messages across folders, but `APPEND` should assign a new `INTERNALDATE` to the current date & time (unless you use the `Append()` method that takes a `DateTimeOffset`, in which case it should assign that value as the `INTERNALDATE` value).

How are you determining that the `INTERNALDATE` is wrong?

Here's what the IMAP RFC says:

```
2.3.3.  Internal Date Message Attribute

   The internal date and time of the message on the server.  This
   is not the date and time in the [RFC-2822] header, but rather a
   date and time which reflects when the message was received.  In
   the case of messages delivered via [SMTP], this SHOULD be the
   date and time of final delivery of the message as defined by
   [SMTP].  In the case of messages delivered by the IMAP4rev1 COPY
   command, this SHOULD be the internal date and time of the source
   message.  In the case of messages delivered by the IMAP4rev1
   APPEND command, this SHOULD be the date and time as specified in
   the APPEND command description.  All other cases are
   implementation defined.
```

**Comment by claudiolsmonteiro** [comment]
> Keep in mind that when the internal date is set on the message, it is _NOT_ set as part of the message headers, it is set as a metadata attribute in the IMAP server's message storage database, the only way in which to retrieve this information is via the `FETCH` command with `INTERNALDATE` (aka `Fetch (<range>, MessageSummaryItems.InternalDate ...);`

I have been testing with an email that was received on 17-07-2019 at 14:40.
I have also tried with both of the following Append methods:
`await destinationMailFolder.AppendAsync(message);`
_and_
`await destinationMailFolder.AppendAsync(message, MessageFlags.Seen, DateTimeOffset.UtcNow);`

The problem is that, when I run the following fetch command with the **InternalDate** flag:
`await destinationMailFolder.FetchAsync(0, -1, MessageSummaryItems.UniqueId | MessageSummaryItems.InternalDate);`

the _InternalDate_ of the _MessageSummary_ is still set as _17-07-2019 14:40_

**Comment by jstedfast** [comment]
Can you get protocol logs of the APPEND command and of the FETCH response so I can see what is going on?

**Comment by claudiolsmonteiro** [comment]
C: A00000010 APPEND InvoicesToProcess {547+}
C: MIME-Version: 1.0
C: Date: Wed, 17 Jul 2019 09:40:08 +0000
C: Message-ID: <CADPgRxcu9at7KdB6-Rj1m6W1iC7sxDBAbndBguNM-Trmb0KrLQ@mail.gmail.com>
C: Subject: teste332
C: From: Test User <testingcside@gmail.com>
C: To: Test User <testingcside@gmail.com>
C: Content-Type: multipart/alternative; boundary="000000000000f78cbb058ddd18fe"
C: 
C: --000000000000f78cbb058ddd18fe
C: Content-Type: text/plain; charset="UTF-8"
C: 
C: 
C: 
C: --000000000000f78cbb058ddd18fe
C: Content-Type: text/html; charset="UTF-8"
C: 
C: <div dir="ltr"><br></div>
C: 
C: --000000000000f78cbb058ddd18fe--
C: 
S: * 1 FETCH (UID 1360 MODSEQ (79128) FLAGS ())
S: A00000010 OK [APPENDUID 26 485] (Success)
C: A00000011 SELECT InvoicesToProcess (CONDSTORE)
S: * FLAGS (\Answered \Flagged \Draft \Deleted \Seen $NotPhishing $Phishing)
S: * OK [PERMANENTFLAGS (\Answered \Flagged \Draft \Deleted \Seen $NotPhishing $Phishing \*)] Flags permitted.
S: * OK [UIDVALIDITY 26] UIDs valid.
S: * 1 EXISTS
S: * 0 RECENT
S: * OK [UIDNEXT 486] Predicted next UID.
S: * OK [HIGHESTMODSEQ 79154]
S: A00000011 OK [READ-WRITE] InvoicesToProcess selected. (Success)
C: A00000012 FETCH 1:* (UID INTERNALDATE)
S: * 1 FETCH (UID 485 MODSEQ (79128) INTERNALDATE "17-Jul-2019 09:40:08 +0000")
S: A00000012 OK Success

Hope this helps.

**Comment by jstedfast** [comment]
I was expecting a log of the APPEND command that takes a date argument, but you gave me a log of the APPEND command without a date argument.

Can you get me the same logs but using `Append (message, MessageFlags.Seen, DateTimeOffset.UtcNow);`?

**Comment by claudiolsmonteiro** [comment]
Sorry, I only sent this one because they appeared to be the equal.
Here is the one with `Append (message, MessageFlags.Seen, DateTimeOffset.UtcNow);`

C: A00000010 APPEND InvoicesToProcess (\Seen) "23-Jul-2019 14:23:14 +0000" {547+}
C: MIME-Version: 1.0
C: Date: Wed, 17 Jul 2019 09:40:08 +0000
C: Message-ID: <CADPgRxcu9at7KdB6-Rj1m6W1iC7sxDBAbndBguNM-Trmb0KrLQ@mail.gmail.com>
C: Subject: teste332
C: From: Test User <testingcside@gmail.com>
C: To: Test User <testingcside@gmail.com>
C: Content-Type: multipart/alternative; boundary="000000000000f78cbb058ddd18fe"
C: 
C: --000000000000f78cbb058ddd18fe
C: Content-Type: text/plain; charset="UTF-8"
C: 
C: 
C: 
C: --000000000000f78cbb058ddd18fe
C: Content-Type: text/html; charset="UTF-8"
C: 
C: <div dir="ltr"><br></div>
C: 
C: --000000000000f78cbb058ddd18fe--
C: 
S: A00000010 OK [APPENDUID 26 486] (Success)
C: A00000011 SELECT InvoicesToProcess (CONDSTORE)
S: * FLAGS (\Answered \Flagged \Draft \Deleted \Seen $NotPhishing $Phishing)
S: * OK [PERMANENTFLAGS (\Answered \Flagged \Draft \Deleted \Seen $NotPhishing $Phishing \*)] Flags permitted.
S: * OK [UIDVALIDITY 26] UIDs valid.
S: * 1 EXISTS
S: * 0 RECENT
S: * OK [UIDNEXT 487] Predicted next UID.
S: * OK [HIGHESTMODSEQ 79204]
S: A00000011 OK [READ-WRITE] InvoicesToProcess selected. (Success)
C: A00000012 FETCH 1:* (UID INTERNALDATE)
S: * 1 FETCH (UID 486 MODSEQ (79201) INTERNALDATE "17-Jul-2019 09:40:08 +0000")
S: A00000012 OK Success

**Comment by jstedfast** [comment]
Ok, seems like a bug in your IMAP server.

The INTERNALDATE that the server responds with to the FETCH request should be identical to the date sent in the APPEND command. For some reason, your IMAP server is ignoring the date sent as part of the APPEND command and is overriding it with the Date header value which it should not be doing.
