### ISSUE TITLE
Index was outside the bounds of the array when using connect

### ISSUE THREAD

**Issue by abassermann** [jstedfast/MailKit#882]
When I am using the mailkit version 2.2.0 on Windows 2012 the connect fails with "Index was outside the bounds of the array". I am using the libs with Powershell and it´s a very simply snippet:

Add-Type -Path "C:\temp\BouncyCastle.1.8.5\lib\BouncyCastle.Crypto.dll"
Add-Type -Path "C:\temp\MimeKit.2.2.0\lib\net45\MimeKit.dll"
Add-Type -Path "C:\temp\MailKit.2.2.0\lib\net45\MailKit.dll"

[string]$mailserver = "mailserver"

$cnn = New-Object MailKit.Net.Imap.ImapClient
$cnn.Connect($mailserver)
$cnn.Authenticate($username,$password)

When I use the same lines on my local windows 10 it works. I also tried another Windows 2012 server instance and ran into the same exception. 

This is the revision of the Windows 2012 where it throws the exception:
Major  Minor  Build  Revision
-----  -----  -----  --------
6      2      9200   0       

Any suggestion how to troubleshoot or is there any restrictions when it comes to  Windows 2012 ?

**Comment by jstedfast** [comment]
Is it possible to get the `StackTrace` property of the exception?

**Comment by abassermann** [comment]
![grafik](https://user-images.githubusercontent.com/34915318/61641822-1e068780-aca0-11e9-8ea2-1088a469518e.png)

**Comment by jstedfast** [comment]
Looks like the exception is actually thrown by PowerShell and not MailKit.

This is probably happening because it can't figure out which `Connect` method to invoke.

In MailKit, the `Connect` method takes 3 arguments: `string host`, `int port`, and either a `bool` indicating whether or not the port is an SSL-port or a `SecureSocketOptions` argument.

If passing in 3 arguments still fails, let me know what the new exception is and I'll see if I can help you figure out how to solve that.

**Comment by abassermann** [comment]
Thanks a lot for the responds, unfortunatly it fails with three arguements with the same exception:

![grafik](https://user-images.githubusercontent.com/34915318/61687281-56e74080-ad22-11e9-91ec-9e114dfe7044.png)

Somehow it feels like a weird condition. On my local win10 system, connect works like charm with one or three arguments passed. While on two different Win2016 servers it fails with the same exception, no matter whether I passing one or three arguments.

**Comment by jstedfast** [comment]
I'm not sure how to debug that because none of those stack frames are located in MailKit :(

**Comment by abassermann** [comment]
I resolved that issue. It is really a bug in powershell 4, which got resolved in powershell 5. The powershell version were different at my local system and the server. Therefore it was woking locally, but crashing at the server. After updating powershell at the server, Mailkit worked like charm. Sorry for bothering with that question and much thanks the help.

**Comment by jstedfast** [comment]
No problem and thanks for the update explaining the fix!
