### ISSUE TITLE
(4.4.2 Message submission rate...) not properly handled in pipeline mode

### ISSUE THREAD

**Issue by agerchev** [jstedfast/MailKit#883]
I'm sending mails to an MS Exchange instance (Version 15.1) and when i hit the sending limit, the server responds with (S: 421 4.4.2 Message submission rate for this client has exceeded the configured limit) message. The problem is that the message is hidden and I get this one instead: 

> System.IO.IOException: An existing connection was forcibly closed by the remote host ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host

This is the log from ProtocolLogger (I'm not sure whether the server is implementing the protocol properly ): 

> C: MAIL FROM:<......> BODY=8BITMIME
> C: RCPT TO:<.....>
> S: 421 4.4.2 Message submission rate for this client has exceeded the configured limit

I have changed the capabilities of the smtpClient so the SmtpCapabilities.Pipelining is disabled and the proper message was thrown.
I suppose that the problem is in the SmtpClient::FlushCommandQueueAsync method: 

```
// Note: we need to read all responses from the server before we can process
				// them in case any of them have any errors so that we can RSET the state.
				for (int i = 0; i < queued.Count; i++) {
					SmtpResponse response;

					if (doAsync)
						response = await Stream.ReadResponseAsync (cancellationToken).ConfigureAwait (false);
					else
						response = Stream.ReadResponse (cancellationToken);

					responses.Add (response);
				}
```

You loop and wait to read all the responses from the server, but the server is hitting the limit and closing the connection. You read the first response, the one for the 

> MAIL FROM:

command and then waits for the next command response, but the server has closed the connection and NetworkStream throws and exception.

**Comment by jstedfast** [comment]
Thanks for the bug report!
