### ISSUE TITLE
The IMAP server has unexpectedly disconnected on Sort

### ISSUE THREAD

**Issue by juansh20** [jstedfast/MailKit#884]
Sometimes, when I use Imapfolder.Sort(query, orderBy); I get this message: "The IMAP server has unexpectedly disconnected". I notice that this Imap folder has more than 100,000 messages. 

I use these function only for getting UID lists.

Stack error:

   en MailKit.Net.Imap.ImapStream.<ReadAheadAsync>d__56.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   en MailKit.Net.Imap.ImapStream.<ReadTokenAsync>d__71.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   en MailKit.Net.Imap.ImapCommand.<StepAsync>d__82.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   en MailKit.Net.Imap.ImapEngine.<IterateAsync>d__170.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   en MailKit.Net.Imap.ImapEngine.<RunAsync>d__171.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en MailKit.Net.Imap.ImapFolder.<SortAsync>d__359.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en MailKit.Net.Imap.ImapFolder.Sort(SearchQuery query, IList`1 orderBy, CancellationToken cancellationToken)
   en EZSafe.Libraries.Shared.MailBox.CMailProcess.lstMessagesAccount(ArrayList varparametros, ArrayList AccountParam) en D:\MailBox\CMail.cs:línea 3366
   en MyCargo.Inbox.BindPagedMessage(ArrayList Parameters) en D:\Inbox.aspx.vb:línea 150

**Comment by jstedfast** [comment]
Try getting a protocol log to see what the server is saying when it disconnects you:

```csharp
var client = new ImapClient (new ProtocolLogger ("imap.log"));
```

**Comment by juansh20** [comment]
Hello,

This is the imap.log:

Connected to imaps://mail.xxxxxxx.xxx:993/
S: * OK [CAPABILITY IMAP4rev1 SASL-IR LOGIN-REFERRALS ID ENABLE IDLE NAMESPACE LITERAL+ AUTH=PLAIN AUTH=LOGIN] Dovecot ready.
C: F00000000 AUTHENTICATE PLAIN AG1yYW1pcmV6QGV6c2hpcC5wZQB5Q3ZiTVduektGQUQ=
S: F00000000 OK [CAPABILITY IMAP4rev1 SASL-IR LOGIN-REFERRALS ID ENABLE IDLE SORT SORT=DISPLAY THREAD=REFERENCES THREAD=REFS THREAD=ORDEREDSUBJECT MULTIAPPEND URL-PARTIAL CATENATE UNSELECT CHILDREN NAMESPACE UIDPLUS LIST-EXTENDED I18NLEVEL=1 CONDSTORE QRESYNC ESEARCH ESORT SEARCHRES WITHIN CONTEXT=SEARCH LIST-STATUS BINARY MOVE SNIPPET=FUZZY NAMESPACE LITERAL+ NOTIFY SPECIAL-USE COMPRESS=DEFLATE QUOTA] Logged in
C: F00000001 NAMESPACE
S: * NAMESPACE (("INBOX." ".")) NIL NIL
S: F00000001 OK Namespace completed (0.001 + 0.000 secs).
C: F00000002 LIST "" "INBOX" RETURN (SUBSCRIBED CHILDREN)
S: * LIST (\HasChildren) "." INBOX
S: F00000002 OK List completed (0.003 + 0.000 + 0.002 secs).
C: F00000003 LIST (SPECIAL-USE) "" "*" RETURN (SUBSCRIBED CHILDREN)
S: * LIST (\Subscribed \HasNoChildren \UnMarked \Junk) "." INBOX.spam
S: * LIST (\Subscribed \HasNoChildren \UnMarked \Archive) "." INBOX.Archive
S: * LIST (\Subscribed \HasNoChildren \UnMarked \Drafts) "." INBOX.Drafts
S: * LIST (\Subscribed \HasNoChildren \UnMarked \Trash) "." INBOX.Trash
S: * LIST (\Subscribed \HasNoChildren \UnMarked \Sent) "." INBOX.Sent
S: F00000003 OK List completed (0.002 + 0.000 + 0.001 secs).
C: F00000004 EXAMINE INBOX (CONDSTORE)
S: * FLAGS (\Answered \Flagged \Deleted \Seen \Draft $MDNSent $Forwarded)
S: * OK [PERMANENTFLAGS ()] Read-only mailbox.
S: * 116866 EXISTS
S: * 0 RECENT
S: * OK [UNSEEN 42247] First unseen.
S: * OK [UIDVALIDITY 1409954669] UIDs valid
S: * OK [UIDNEXT 174217] Predicted next UID
S: * OK [HIGHESTMODSEQ 354038] Highest
S: F00000004 OK [READ-ONLY] Examine completed (0.168 + 0.000 + 0.167 secs).
C: F00000005 UID SORT RETURN () (REVERSE ARRIVAL) US-ASCII ALL

after that, I have the message: "The IMAP server has unexpectedly disconnected"

**Comment by jstedfast** [comment]
Okay, so what seems to be happening is that when MailKit attempts to send the `F00000005 UID SORT RETURN () (REVERSE ARRIVAL) US-ASCII ALL` command, the server dropped the connection (or you lost your network connection) and MailKit was unable to finish sending it.

That's not something that can be fixed in MailKit.
