### ISSUE TITLE
Specify Outgoing IP in smtp client

### ISSUE THREAD

**Issue by sekmenhuseyin** [jstedfast/MailKit#885]
I saw this issue: https://github.com/jstedfast/MailKit/issues/128
We have the same exact  problem and we couldn't solve on our own. We use Azure VM. Its private IP is 10.0.0.4 and public IP is 20.188.39.114. When we send emails, mailkit uses private IP and because of that receiver servers can not find real domain name.

```
Nevertheless your message appears to be sent from !10.0.0.4!.
You may want to publish a DNS record (A type) for the hostname !10.0.0.4! or use a different hostname in your mail software.
```
https://mxtoolbox.com/deliverability/f7170504-3af2-4a46-aa5c-2069780a37a8

My Question:
**How can I configure smtp server to use real IP.**

We have tried to create a socvket and used it in smtp construct, but couldn't succeed. And your documentation didn't help either.

**Comment by jstedfast** [comment]
Is the issue that the `EHLO` command uses `10.0.0.4` instead of `20.188.39.114`?

If so, you can do this:

```csharp
client.LocalDomain = "20.188.39.114";
client.Connect ("smtp.host.com", 25, false);
```

If the issue is that MailKit is using the wrong interface, you can bind the SmtpClient to a specific `LocalEndPoint`:

```csharp
client.LocalEndPoint = ...;
client.Connect (...);
```

Does that help?

**Comment by shapeh** [comment]
> If the issue is that MailKit is using the wrong interface, you can bind the SmtpClient to a specific LocalEndPoint:

```
IPAddress.TryParse ("20.188.39.114", out IPAddress ip);
client.LocalEndPoint = new IPEndPoint (ip, 0);
client.Connect (...);
```

This above saved me. Currently, Microsoft 365 does not support adding an IPv6 address to their approved list of mail connectors, so we were forced to use IPv4. 'Somewhat' out of the blue Microsoft started prioritizing IPv6 traffic on their M365 mail connectors. It was announced but Exchanged Admin interface has not been updated accordingly.
Thanks again for a great package!
