### ISSUE TITLE
Move mails from spam to inbox

### ISSUE THREAD

**Issue by firstlord1** [jstedfast/MailKit#887]
Hi, i need to move all spam mails to inbox. Is that possible with Yahoo ?

**Comment by firstlord1** [comment]
i can set spam folder for yahoo but i dont know how can i move all mails to inbox. 

`var spamBox = client.GetFolder("Bulk Mail");`

**Comment by jstedfast** [comment]
```csharp
spamBox.MoveTo (UniqueIdRange.All, client.Inbox);
```
