### ISSUE TITLE
MailKit mail order problem

### ISSUE THREAD

**Issue by firstlord1** [jstedfast/MailKit#888]
Hi, i have project for mail receiving. But date order is important in this project. Program can receive mails but mails mixing. as in the image. i need to sort by date. Is it bug ?

[https://i.hizliresim.com/YdNlbA.png](https://i.hizliresim.com/YdNlbA.png)

**Comment by jstedfast** [comment]
I can't see the image because the web server gives me a 403.

Anyway, MailKit just shows you the messages in whatever order they are in on the mail server. If you want to sort them, you can.

If you are using IMAP and your server supports the SORT extension, then you can use the `IMailFolder.Sort()` methods to get a sorted list of UIDs.

If not, then you can use the `MessageSorter` class to sort a list of `IMessageSummary`'s.

**Comment by firstlord1** [comment]
So im trying to receive mails same with website. but program is mixing mails. there is a mails times. Starting with 5:22:45 and increasing. but after that its mixing the mail date. (sorry my english is bad)

> 
31/07/2019 05:22:45 +00:00
31/07/2019 05:23:14 +00:00
31/07/2019 05:25:11 +00:00
31/07/2019 05:25:22 +00:00
31/07/2019 05:28:40 +00:00
31/07/2019 05:30:29 +00:00
31/07/2019 05:30:38 +00:00
31/07/2019 05:31:08 +00:00
31/07/2019 05:34:53 +00:00
31/07/2019 05:38:55 +00:00
31/07/2019 05:42:02 +00:00
31/07/2019 05:42:40 +00:00
31/07/2019 05:42:40 +00:00
31/07/2019 05:44:39 +00:00
31/07/2019 05:45:15 +00:00
31/07/2019 05:46:25 +00:00
31/07/2019 05:49:58 +00:00
31/07/2019 05:50:54 +00:00
31/07/2019 05:53:53 +00:00
31/07/2019 05:55:41 +00:00
31/07/2019 05:56:57 +00:00
31/07/2019 05:57:21 +00:00
31/07/2019 05:57:50 +00:00
31/07/2019 05:57:53 +00:00
31/07/2019 05:57:55 +00:00
31/07/2019 05:58:16 +00:00
31/07/2019 05:58:26 +00:00
31/07/2019 06:03:27 +00:00
31/07/2019 06:03:50 +00:00
31/07/2019 06:04:05 +00:00
31/07/2019 06:06:37 +00:00
31/07/2019 06:07:23 +00:00
31/07/2019 06:10:41 +00:00
31/07/2019 06:12:38 +00:00
31/07/2019 06:15:22 +00:00
31/07/2019 06:17:22 +00:00
31/07/2019 06:28:11 +00:00
31/07/2019 06:32:55 +00:00
31/07/2019 06:43:18 +00:00
31/07/2019 06:54:40 +00:00
31/07/2019 06:55:01 +00:00
31/07/2019 06:55:07 +00:00
31/07/2019 05:24:38 +00:00 >>> wrong order
31/07/2019 05:34:32 +00:00
31/07/2019 05:52:00 +00:00
31/07/2019 05:52:11 +00:00
31/07/2019 05:53:28 +00:00
31/07/2019 05:57:15 +00:00
31/07/2019 05:59:29 +00:00
31/07/2019 05:59:33 +00:00

**Comment by firstlord1** [comment]
may i share my codes by PM or mail ?

**Comment by firstlord1** [comment]
i just receive mails same with website. so i dont need order mails

**Comment by firstlord1** [comment]
i tried `Sort()` command but yahoo doesnt support sort. and i tried this code 
`                    var date = new UniqueIdSet(MailKit.Search.OrderBy.Date.Order);
                    foreach (var uid in inbox.Search(SearchQuery.All))
                        date.Add(uid);
                    foreach (var uid in date)
                    {
                        var message = inbox.GetMessage(uid);
                        textBox1.Text+=uid.ToString()+ message.Subject + message.Date + "\r\n";
                    }`

but as a result mails mixing again. i need to sort by date... for example about result :

![Screenshot_2](https://user-images.githubusercontent.com/35865864/62335807-fa301680-b4d5-11e9-844f-128f4db2c166.png)
![Screenshot_3](https://user-images.githubusercontent.com/35865864/62335808-fa301680-b4d5-11e9-83f0-3807427a5906.png)

**Comment by jstedfast** [comment]
What you need to do is this:

```csharp
var list = inbox.Fetch (0, -1, MessageSummaryItems.Envelope | MessageSummaryItems.UniqueId).ToList ();
list.Sort (new OrderBy[] { OrderBy.Date });

foreach (var item in list) {
    var message = inbox.GetMessage (item.UniqueId);
    textBox1.Text+=uid.ToString()+ message.Subject + message.Date + "\r\n";
}
```

**Comment by jstedfast** [comment]
```csharp
new UniqueIdSet(MailKit.Search.OrderBy.Date.Order);
```

That just creates a UniqueIdSet that sorts UIDs in ascending or descending order, it doesn't sort by date because it doesn't *know* the date. All you have to do is look at the type of `MailKit.Search.OrderBy.Date.Order` and you'd see that it was a enum with 3 possible values: `None`, `Ascending`, `Descending`.
