### ISSUE TITLE
IMAP client.Inbox.Open: System.NullReferenceException

### ISSUE THREAD

**Issue by RiCruiser** [jstedfast/MailKit#893]
Hi,
I'm connecting to a IMAP mailserver via MailKit 2.2.0. 
client.Connect and client.Authenticate are working, the properties of both (IsConnected and IsAuthenticated) are true.

But: Calling client.Inbox.Open(FolderAccess.ReadOnly) gives me a System.NullReferenceException.

The Protocol-logger has this output:

Connected to imap://xxx/?starttls=always
S: * OK [CAPABILITY IMAP4rev1 NOLOGIN STARTTLS SPECIAL-USE] dings imap.
C: A00000000 STARTTLS
S: A00000000 OK Start negotiating
C: A00000001 CAPABILITY
S: * capability imap4rev1 starttls login special-use
S: A00000001 OK CAPABILITY completed
C: A00000002 LOGIN username password
S: A00000002 OK LOGIN completed
C: A00000003 CAPABILITY
S: * capability imap4rev1 starttls login special-use
S: A00000003 OK CAPABILITY completed
C: A00000004 LIST "" ""
S: * List (\HasNoChildren) "/" "INBOX"
S: * List (\HasNoChildren \Trash) "/" "Trash"
S: A00000004 OK List
C: A00000005 LIST "" "INBOX"
S: * List (\HasNoChildren) "/" "INBOX"
S: * List (\HasNoChildren \Trash) "/" "Trash"
S: A00000005 OK List
C: A00000006 LIST (SPECIAL-USE) "" "*"
S: * List (\HasNoChildren) "/" "INBOX"
S: * List (\HasNoChildren \Trash) "/" "Trash"
S: A00000006 OK List

My simple code:
ImapClient client = new ImapClient(new MailKit.ProtocolLogger("imap.log"));
client.Connect(imapServer, imapPort, SecureSocketOptions.StartTls);
client.Authenticate(imapUsername, imapPassword);
**client.Inbox.Open(FolderAccess.ReadOnly);**                
int cntMail = client.Inbox.Count;
client.Disconnect(true);

**Comment by jstedfast** [comment]
Can you get me the `Exception.StackTrace` value?

**Comment by RiCruiser** [comment]
Hi Jeffrey,
Type: System.NullReferenceException
Exception.StackTrace: "  at mailclient_imap.Program.receiveMails() in C:\\VisualStudioProjects\\....\\Program.cs:Zeile 182."	
Exception.Message: The object reference was not set to an object instance.

**Comment by jstedfast** [comment]
The NRE is thrown in your Program.cs file, not within MailKit.

What is on line 182 in Program.cs?

**Comment by RiCruiser** [comment]
This Code is in line 182:
client.Inbox.Open(FolderAccess.ReadOnly);

Client.Inbox is also null. It seems thats the problem.

**Comment by jstedfast** [comment]
Ah, client.Inbox is null because your server is not tagging it with `\Inbox`.

**Comment by jstedfast** [comment]
Actually, no, I see the problem... your IMAP server is not using all upper-case tokens like it's supposed to.

**Comment by jstedfast** [comment]
Meh, rfc2060 does state that these tokens are case insensitive

**Comment by RiCruiser** [comment]
Thank you very much! Inbox is now not null! You made my day :)

**Comment by jstedfast** [comment]
Awesome :-)

**Comment by shrutimistry** [comment]
@jstedfast  Hi Jeffrey, can you give an example of "IMAP server is not using all upper-case tokens", I'm facing the same problem and I'm not quite sure what you mean by that.
Thanks

**Comment by jstedfast** [comment]
Well, for example, normally an IMAP server will respond to a LIST command like this:

```
* LIST (\HasNoChildren) "/" "INBOX"
* LIST (\HasNoChildren \Trash) "/" "Trash"
A00000004 OK LIST
```

but if your server responded with this instead, MailKit would to properly handle it:

```
* LisT (\HasNoChildren) "/" "INBOX"
* list (\HasNoChildren \Trash) "/" "Trash"
A00000004 OK LiST
```

That should no longer be an issue, though, because I patched MailKit a year ago to fix this.

If you are having any problems at all with MailKit not working, the first thing to do is to get a protocol log by creating your ImapClient in the following way:

```csharp
new ImapClient (new ProtocolLogger ("imap.log"))
```

When you do this, the ImapClient will log all of the commands and responses to a file called "imap.log" which you can then read over to see what is going wrong (or send it to me and I will look at it).

Keep in mind that the log file will contain your username/password in the AUTHENTICATE (or LOGIN) command toward the beginning of the log file, so be sure to mask the command argument(s) (for the AUTHENTICATE command, the username/password will be base64 encoded blobs).

**Comment by alex-jitbit** [comment]
I'm still getting NRE at `client.Inbox.Open` for some customers using outlook.office365.com . MailKit version 2.10.1

**Comment by alex-jitbit** [comment]
After trying with another IMAP client library (LimiLabs) I see that the server actually responds with an error

```
OK CAPABILITY completed.
SELECT "INBOX"
BAD User is authenticated but not connected.
```

It would be nice if MailKit provided an actual imap response message in an exception instead of a cryptic NRE.

**Comment by alex-jitbit** [comment]
@jstedfast OK, so I downloaded the latest source willing to submit a PR that fixes this (throws a more readable exception instead of NRE) and it appears it's already been fixed in the latest sources codes.

Please let us know when's the next release planned?

**Comment by jstedfast** [comment]
Ah, I bet you hit issue #1135 ?

I can try to make a new release this weekend.
