### ISSUE TITLE
Allow replacing of the To header without updating the Rcpt To.

### ISSUE THREAD

**Issue by Vizeo** [jstedfast/MailKit#894]
I want to use your code to send emails directly to smtp servers. If their are multiple domains that this email needs to go to I don't want the recipient added to the RCPT To header if it does not apply to that server. 

Please allow a flag when adding the email, that will not send it to the server as a recipient but still list it in the TO header, or allow me to have some sort of header override the TO header either through inheritance or through some sort of replace call to that header, that won't add those emails to recipients.

**Comment by jstedfast** [comment]
Use the Send or SendAsync method that takes an explicit list of MailboxAddresses to send the message to.

**Comment by Vizeo** [comment]
Does that not also add those recipients to the TO header? I see no indication that it does not.

**Comment by jstedfast** [comment]
It does not. The SmtpClient does not add any headers to the MimeMessage.
