### ISSUE TITLE
Use BDAT when CHUNKING available

### ISSUE THREAD

**Issue by nitinag** [jstedfast/MailKit#896]
SmtpClient can avoid dot stuffing by using BDAT when the CHUNKING extension is available. For those that want to disable it in special situations for certain servers/messages, SmtpClient already offers the ability to disable the chunking capability via the Capabilities property after Connect/Auth.

Many smtp servers support CHUNKING, but not BINARYMIME for that purpose. For example, Gmail only supports CHUNKING. Postfix only supports CHUNKING: http://www.postfix.org/BDAT_README.html.

I noticed that was also on the TODO list at https://github.com/jstedfast/MailKit/blob/master/TODO.md, which can be removed when completed.

https://github.com/jstedfast/MailKit/blob/master/MailKit/Net/Smtp/SmtpClient.cs#L2103 currently reads:
```c#
if ((extensions & SmtpExtension.BinaryMime) != 0)
```
Suggestion is to change to:
```c#
if ((Capabilities & SmtpCapabilities.Chunking) != 0 || (extensions & SmtpExtension.BinaryMime) != 0)
```
The BinaryMime check seems unnecessary after this change, but I've kept it since it reminds that BinmaryMime is a special case.

**Comment by nitinag** [comment]
Additionally, would the following optimization for BdatAsync to avoid the MeasuringStream at https://github.com/jstedfast/MailKit/blob/master/MailKit/Net/Smtp/SmtpClient.cs#L1896 make sense:
	
In BdatAsync, if the Stream is a BoundStream, take the Length (since we're sure to have StartBoundary and EndBoundry). Otherwise, use MeasuringStream as currently being done. This would allow anyone to pass a BoundStream to MimeMessage.Load and allow SmtpClient to set the BDAT size without streaming the whole message again (especially beneficial for large and/or remote streams with persist MimeMessage flag). Not sure how one would set that on a new MimeMessage though or if that would even be necessary in that case (maybe they would save first to free up the memory and then load as BoundStream).
	
The same technique to check for BoundStream would also allow SmtpClient to set the SIZE estimate parameter in MAIL FROM (https://tools.ietf.org/html/rfc1870#section-6). I think there is no need for MeasuringStream there though when the stream is not a BoundStream since it's likely not worth it there otherwise.
	
Though, looking through the MimeMessage code again just now, it seems that is not possible since the only reference to streams are for MimeContent and it does not keep a reference to the original stream. Maybe it could keep an internal reference to the stream in MimeMessage for this and other purposes? Any alternative ideas to avoid the MeasuringStream in BdatAsync and possibly send the SIZE parameter in MAIL FROM without the measuring overhead if we already know the size?

**Comment by jstedfast** [comment]
I don't think we can avoid the use of a MeasuringStream because:

1. As you noted, MimeMessage has no reference itself to streams, only the MimePart's do (indirectly) via MimeContent's Stream.
2. The MIME structure being sent via SmtpClient is not necessarily unmodified after being parsed by the MimeParser, so we can't even make assumptions about stream offsets from the MimeContent's Stream anyway.
3. Even if the MimeMessage being sent is unmodified after being parsed by MimeParser, we have no assurances that the parsed stream is in the correct `<CR><LF>` encoding.

**Comment by nitinag** [comment]
You're right, my suggestion is likely not the right solution to this. Maybe there could be someway for me to tell the library I already know or force the message size to get around that for BdatAsync and MailFromAsync (set the SIZE parameter)?

Let me share our use case so you know where my thinking is coming from:

We run our own custom-built mx, submission, relay, imap, and pop servers. So, I've built a lot of email stuff on the server side over the years, but have used third-party libraries for the mime parsing and client library pieces.

We ensure all messages end with CRLF in all our use cases (except when binary content encoding, which shouldn't have it), so we always set FormatOptions.EnsureNewLine=false so that we're in control of the exact size/bytes of the message in all cases.

Let's assume our max case of 100 MB email message sizes.

We store all our messages in a central storage layer, which exposes a stream of the message. For now, we have another layer that pulls the copy and caches it locally first if not already present. Then, any library, including MimeMessage can do what it needs with the message, even multiple times in short succession, since the OS will have cached the file.

I'm trying to optimize this by removing the need to cache a local copy of the message and needing to read the whole message at all in most cases. I have several things below I'll be looking into over the next few weeks.

Since this is a remote stream and messages can be large (100+ MB), it makes sense to avoid processing the entire message whenever possible. Here is what I'm thinking:
- On initial MimeMessage.LoadAsync on our mx/submission/imap append, we'll create an index file of raw headers and all MimeEntity structure along with offsets of MimeContent (offsets which we should have access to from MimeMessage because of the BoundStream class and use of persist=true during LoadAsync). We also already track lots of other things in the index including header/body offsets, max line size seen, 8bit content seen, 0byte content seen, binary parts seen, etc., which we get ourselves by going through the raw stream.
- For all future access, always use the index file to re-create the MimeMessage object manually with HeaderList.Load and BoundStream for MimeContent pointed to the remote server stream parts rather than local cache stream. We'll use this method for all our work including our IMAP server's responses for many requests in commands such as FETCH and SEARCH. This will allow us to "Load" large MimeMessage objects without actually reading them in full each time.
- I'll be able to read the headers on mx/submission during the stream and HeaderList.Load the partial message headers, and using the DKIM signature body canonicalization type, generate and store the resulting body hash at the same time as original incoming read.
- For SmtpClient, we'll be able to re-create this "light" MimeMessage object from our index file even for 100 MB messages without reading it. SmtpClient would thus only read the 100 MB stream once (during the actual send). Obliviously, the BdatAsync MeasuringStream creates a second read right now, which is why I mentioned it. I understand why since one could have changed the MimeMessage after load. However, in our case, we do always know the exact number of bytes (size) of the message to send and always ensure FormatOptions.EnsureNewLine=false. We just don't have a way to skip the MeasuringStream there right now.

That's what I'm thinking so far, and hopefully it'll be possible based on the code I've looked through so far.

I did notice a two other specific things to mention while looking into this over the past few weeks:
- Can MimeMessage expose `MimeMessage.GetHtmlBodyAsync()` and `MimeMessage.GetTextBodyAsync()` since `MimeMessage.HtmlBody` and `MimeMessage.TextBody` read the MimeContent streams? As methods they'll also indicate to the developer that the response reference should be copied locally since it does dynamically find the right parts and accesses the stream on each call.
- Though we don't need it since we use our own custom versions of it and our index file, `MimePart.GetBestEncoding` and `MimeMessage.Prepare` probably also need Async versions since they read the streams.

Apologies for the long post, I was going to post this later and separately once I was further along with the actual prototype of the "light" load in our use case, but it came up during this issue and doesn't change our use case.

**Comment by jstedfast** [comment]
What if I add a `protected virtual uint? GetSize (MimeMessage message)` method that you could override in the SmtpClient to get the size?

*Technically* SmtpClient could be modified such that it wouldn't need the size of the message for the BDAT command since the BDAT command can be sent multiple times with subsets of the full message stream. I just haven't gotten around to implementing that and I haven't been in a rush to do it because it wasn't necessary before.

That said, a `GetSize()` method would still be needed if you wanted to send the `SIZE=###` parameter in the `MAIL FROM` command.

**Comment by nitinag** [comment]
Yes! The protected GetSize would be a good solution for both BDAT and sending MAIL FROM SIZE parameter.

There probably isn't an immediate benefit to breaking up BDAT since I doubt many, if any, mail servers have the ability to do partial BDAT rejections based on running checks on the partial data sent so far. In addition, clients are allowed to pipeline multiple BDAT, making it essentially the same from the server perspective. However, sending it in chunks does get around the need for the client to know the full size upfront, but it would still be nice to send the SIZE via MAIL FROM so the mail server can reject the message as needed in RCPT rather than after the DATA/BDAT is sent.
