### ISSUE TITLE
Attachment file size showing higher than the actual size

### ISSUE THREAD

**Issue by kbchowdary** [jstedfast/MailKit#899]
Hi,
I am trying to check the attachments size before downloading the complete message. For this I have used the MessageSummaryItems.BodyStructure while Fetching the items from inbox. As follows.

```csharp
var items = folder.Fetch (ids, MessageSummaryItems.BodyStructure | MessageSummaryItems.UniqueId);
foreach (var item in items) {
    foreach (var attachment in item.Attachments) {
        // 'octets' is just a fancy word for "number of bytes"
        var size = attachment.Octets;
	log.Info(size);
    }
}
```

But, looking at the log, it shows the file size as more than the actual file size. Log comes as follows.

Found 2 attachments with the mail (UniqueID:5533)
Individual attachment size for message:5533 is :: 3427408
Individual attachment size for message:5533 is :: 2875804
Total size of attachment for message:5533 is 6303212

But the actual file size in File Properties shows as 2504642 and 2101546 respectively.

Can you please help me understand why the size shows more than the actual size when we download it from the email? If this is an expected behavior, is there a way to get the actual file size before downloading the attachments?

My requirement is to put a limit on the email attachment size, and ignore those emails if the size is above the limit.

**Comment by jstedfast** [comment]
You're confusing attachment size with file size after decoding the attachment content. They are 2 different things.

There's no way to get what the decoded content size will be.

The best you can do is approximate it, knowing that if the ContentTransferEncoding is "base64", you can multiply it by 0.75, but that doesn't account for the MIME headers nor the fact that base64 content gets line-wrapped.

That's about the best you can do.

**Comment by kbchowdary** [comment]
Ok thank you for the response. I understood now.
