### ISSUE TITLE
Continuiously wait for new messages ImapIdle

### ISSUE THREAD

**Issue by HoesLeaguesharp** [jstedfast/MailKit#900]
Hello, this might be a rather stupid question, but i am trying to make an Idle Imap that will run on a separate thread, fetch emails as they come in and add needed data from the received message body to a list, the list will be used by Tasks running in the background.
I have used the ImapIdle.cs sample as my code base, but i am having trouble understanding how to operate with the Cancellation token.
How do i properly wait for messages to arrive, exit out of the Idle loop, handle the folder messages, and re-enter idle loop upon completion? 

I added some code to show what i have attempted so far
i pretty much just made the cancellation token global and create a task that will fetch messages.
After some tweaking, i tried to simply restart the idle thread after cancelling the token, but it i get an error saying that the thread can not be restart.

```csharp
        public void Start()
        {
            var client = new ImapClient(new ProtocolLogger(Console.OpenStandardError()))
            {
                ServerCertificateValidationCallback = (sender, certificate, chain, sslPolicyErrors) => true
            };

            
            client.Connect("redacted", 993, true);
            client.Authenticate("redacted", "redacted");

            client.Inbox.Open(FolderAccess.ReadWrite);

            CancellationTokenSource done = new CancellationTokenSource();

            var messages = client.Inbox.Fetch(0, -1, MessageSummaryItems.Full | MessageSummaryItems.UniqueId).ToList();
            client.Inbox.MessageExpunged += (sender, e) =>
            {
            };
            var thread = new Thread(IdleLoop);
            thread.Start(new IdleState(client, done.Token));
            client.Inbox.CountChanged += (sender, e) =>
            {
                done.Cancel();
            };

            thread.Join();
            foreach (var message in client.Inbox.Fetch(0, -1,
                MessageSummaryItems.Full | MessageSummaryItems.UniqueId))
                Console.WriteLine("Subject: {0}", message.Envelope.Subject);
            thread.Start(new IdleState(client, done.Token));
        }
```

Made another edit, this time i made it work, but i can already see how many flaws there are.
1. Reconnecting is made hard
2.Race conditions when it comes to the cancellation token.
How can i polish it to make it as clean as possible?

```csharp
        public void Initialise()
        {
            var client = new ImapClient(new ProtocolLogger(Console.OpenStandardError()))
            {
                ServerCertificateValidationCallback = (sender, certificate, chain, sslPolicyErrors) => true
            };

            
            client.Connect("redacted", 993, true);
            client.Authenticate("redacted", "redacted");

            client.Inbox.Open(FolderAccess.ReadWrite);

            
            CancellationTokenSource done = new CancellationTokenSource(); //getting a token
            var thread = new Thread(IdleLoop); // starting initial idle loop
            thread.Start(new IdleState(client, done.Token));
            

            client.Inbox.MessageExpunged += (sender, e) =>
            {
            };

            client.Inbox.CountChanged += (sender, e) =>
            {
                done.Cancel(); //canceling token
            };

            while (true) //this loop will wait for thread to finish, print out new messages, and create a new token + thread variable
            {
                thread.Join();
                foreach (var message in client.Inbox.Fetch(0, -1,
                    MessageSummaryItems.Full | MessageSummaryItems.UniqueId))
                {
                    Console.WriteLine("Subject: {0}", message.Envelope.Subject);
                }
                thread = new Thread(IdleLoop);
                done = new CancellationTokenSource();
                thread.Start(new IdleState(client, done.Token));
            }
        }
```

**Comment by jstedfast** [comment]
Your second implementation has a few issues. One of the things you need to keep in mind when using anonymous delegates is that the variables that you capture when creating those delegates are snapshots in time.

In other words, in your second implementation, the `done` token source is a snapshot of the first instance. It doesn't get updated when you create new CancellationTokenSources later, so your `CountChanged` event handler will continue to cancel the very first instance over and over again.

You need to make the `done` token source truly global (or, at least, global to a class that this code is all part of).

To handle reconnections, that's easy.

Just have a method that checks that the client is connected/authenticated, and if not, reconnects/re-authenticates.

```csharp
void ReconnectIfNeeded ()
{
    if (!client.IsConnected)
        client.Connect ("host", 993, true);

    if (!client.IsAuthenticated)
        client.Authenticate ("username", "password");
}
```

Then, to use it, do this:

```csharp
IList<IMessageSummary> fetched;

do {
    try {
        fetched = client.Inbox.Fetch (0, -1, MessageSummaryItems.Full | MessageSummaryItems.UniqueId);
        break;
    } catch (ImapProtocolException) {
        ReconnectIfNeeded ();
    } catch (IOException) {
        ReconnectIfNeeded ();
    }
} while (true);

foreach (var message in fetched) {
    Console.WriteLine("Subject: {0}", message.Envelope.Subject);
}
```

**Comment by jstedfast** [comment]
I rewrote the ImapIdle sample so that it handles reconnecting, etc.

It also uses the Async methods now instead of spawning threads and using the old Sync API.
