### ISSUE TITLE
MailKit 2.3.0 - client.Inbox.AddFlags leads to timeout

### ISSUE THREAD

**Issue by RiCruiser** [jstedfast/MailKit#903]
Hi,
I try to mark an IMAP-Message "Seen". At calling client.Inbox.AddFlags(uid, MessageFlags.Seen, false) an exception is thrown after a timeout of approx. 2mins.

Strack-Trace:
System.IO.IOException: A connection try has failed, as the other side hasn't responded after a certain time span or the established connection was faulty, as the connected host didn't reacted. ---> System.Net.Sockets.SocketException: A connection try has failed, as the other side hasn't responded after a certain time span or the established connection was faulty, as the connected host didn't reacted.
   bei System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   bei MailKit.Net.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   --- Ende der internen Ausnahmestapelüberwachung ---
   bei MailKit.Net.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   bei System.Net.FixedSizeReader.ReadPacket(Byte[] buffer, Int32 offset, Int32 count)
   bei System.Net.Security._SslStream.StartFrameHeader(Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
   bei System.Net.Security._SslStream.StartReading(Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
   bei System.Net.Security._SslStream.ProcessRead(Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
   bei System.Net.Security.SslStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   bei MailKit.Net.Imap.ImapStream.<ReadAheadAsync>d__59.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei MailKit.Net.Imap.ImapStream.<ReadTokenAsync>d__74.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   bei MailKit.Net.Imap.ImapCommand.<StepAsync>d__83.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei MailKit.Net.Imap.ImapEngine.<IterateAsync>d__170.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei MailKit.Net.Imap.ImapEngine.<RunAsync>d__171.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei MailKit.Net.Imap.ImapFolder.<ModifyFlagsAsync>d__298.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei MailKit.Net.Imap.ImapFolder.AddFlags(IList`1 uids, MessageFlags flags, HashSet`1 keywords, Boolean silent, CancellationToken cancellationToken)
   bei MailKit.MailFolder.AddFlags(IList`1 uids, MessageFlags flags, Boolean silent, CancellationToken cancellationToken)
   bei MailKit.MailFolder.AddFlags(UniqueId uid, MessageFlags flags, Boolean silent, CancellationToken cancellationToken)
   bei progName.ImapEngine.markAsRead(UniqueId uid) in C:\VisualStudioProjects\....\ImapEngine.cs:Zeile 302.

The Imap-Protocol has this output:
S: A00000010 OK FETCH completed.
C: A00000011 UID STORE 8209 +FLAGS (\Seen)
S: * 8209 FETCH (FLAGS (\Seen) UID 8209)
S: A00000011 OK
--> Timeout

So the server is responding with "A00000011 OK". After that the exception/timeout occurs.
Thanks for your advice!

**Comment by jstedfast** [comment]
Looks like the response never completed.

Based on the FETCH response, the server appears to send `"${TAG} OK ${COMMAND} completed.\r\n"`, but in the case of the STORE command, it only sent `"${TAG} OK"`.

Since MailKit is still trying to read from the socket, it tells me that MailKit never got the `\r\n` that ends the response and the above response pattern also suggests that the server never sent `\r\n`.

If this happens every time, I would recommend filing a bug against the server.

If this only happened once, then it may just be that the connection was lost or the server software crashed or something before it managed to fully respond.
