### ISSUE TITLE
POP3 or Imap Connect error

### ISSUE THREAD

**Issue by etwei2git** [jstedfast/MailKit#905]
Using MailKit 2.2.x or 2.3.0 in Visual Studio 2015/Xamarin always got "Method 'string.TrimEnd' not found." error from Connect().

Switching to older release Authenticate() always fail.

**Comment by jstedfast** [comment]
Make sure that you are referencing the correct assembly version. The only way for you to get that error is if you are not.

The MailKit nuget includes:

net45
Xamarin.iOS
Xamarin.Android
netstandard1.3
netstandard1.6
netstandard2.0

If you are targeting a Xamarin platform, need to make sure that your iOS app references the Xamarin.iOS assembly and that your Xamarin.Android app references the Xamarin.Android assembly.

**Comment by etwei2git** [comment]
Thank you for the quick response.

Is it ok to have net46 in my pgm env (VS2015 Community-Xamarin)?

Microsoft Visual Studio Community 2015
Version 14.0.25431.01 Update 3
Microsoft .NET Framework
Version 4.6.01038
……
Xamarin   4.9.0.753 (f0f46392f)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   4.10.96 (a702a9ceb)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin.Android SDK   8.2.0.16 (HEAD/a78295902)
Xamarin.Android Reference Assemblies and MSBuild support.

Xamarin.iOS   11.9.1.24 (f62de47)
Visual Studio extension to enable development for Xamarin.iOS.

Xamarin.iOS and Xamarin.Mac SDK   11.9.1.24 (f62de47)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

**Comment by jstedfast** [comment]
Are you writing Xamarin Android or iOS apps? If so, no. If you are writing a console app, then make sure it references the net45 assembly.

**Comment by etwei2git** [comment]
No it’s a Xamarin Android GUI (non-console) app; so net46 should be ok?

**Comment by jstedfast** [comment]
No, Xamarin.Android is not compatible with net46. This is why you are getting that error.

**Comment by etwei2git** [comment]
But the same Xamarin.Android app (built in VS Community 2015 w/ net46 and deployed to an Android phone) had been working fine until MailKit was incorporated.

**Comment by jstedfast** [comment]
Pure blind luck, then, because that isn't guaranteed to work.
