### ISSUE TITLE
Proxy and mailkit 1.10.0

### ISSUE THREAD

**Issue by NerzOff** [jstedfast/MailKit#906]
Hi, I really liked your library, but I had a problem (not because of your project). I use mailkit 1.10.0 (I can’t update, I use visual studio 2010 and nuget 2.8) and would like to connect a proxy to it, but nothing works. please tell me how to use proxies in mailkit 1.10.0?

**Comment by jstedfast** [comment]
SmtpClient, Pop3Client and ImapClient all have a Connect() method that takes a Stream.

You'll need to write code to connect to your SMTP/POP3/IMAP server via whatever proxy you have using a `System.Net.Socket` and then wrap that Socket in a `System.Net.NetworkStream` once you've connected and then pass that to the `*Client.Connect (Stream, ...)` method.

If you want to see how to write code that will do that, look at the latest source code for MailKit and check out the source files for the MailKit.Net.Proxy namespace: https://github.com/jstedfast/MailKit/tree/master/MailKit/Net/Proxy
