### ISSUE TITLE
install mailkit 2.3.0 without nuget 2.12

### ISSUE THREAD

**Issue by NerzOff** [jstedfast/MailKit#909]
hello. is it even possible to install libraries without nuget? I use VS 2010, but would like to run mailkit 2.3.0 which can only be installed if nuget 2.12 is installed, and since I'm a fool, I can't install nuget 2.12 on VS 2010. thanks for future reply

**Comment by jstedfast** [comment]
NuGet packages are really just *.zip files with the extension changed to .nupkg. You could download the packages manually, rename the files, and then unzip and look inside to find the correct assembly (`lib/net45/MailKit.dll` and `lib/net45/MimeKit.dll` from the MimeKit nuget package).
