### ISSUE TITLE
TLS/SSL handshake failing after STARTTLS when trying to send email through yahoo

### ISSUE THREAD

**Issue by Vizeo** [jstedfast/MailKit#911]
I am trying to send an email to someone at yahoo using
client.Connect("mta5.am0.yahoodns.net", 25, false); 
I am not using ports 465 or 587 because I am not trying to route the email through yahoo. 

My application is an email server of sorts. (No not a spam server, I validate my email via SPF and Dkim. But I have thousands of clients and each one needs a specific email so using a service becomes difficult, so we are trying to create our own sending system.)

Any way I have tried:
client.SslProtocols = System.Security.Authentication.SslProtocols.Tls11 |
                                    System.Security.Authentication.SslProtocols.Tls12 |
                                    System.Security.Authentication.SslProtocols.Tls |
                                    System.Security.Authentication.SslProtocols.Ssl3 |
                                    System.Security.Authentication.SslProtocols.Ssl2;

client.ServerCertificateValidationCallback = (s, c, h, e) => {
                                    return true;
                                };

client.CheckCertificateRevocation = false;

and no matter what I get the error:

MailKit.Security.SslHandshakeException: 'An error occurred while attempting to establish an SSL or TLS connection.

The SSL certificate presented by the server is not trusted by the system for one or more of the following reasons:
1. The server is using a self-signed certificate which cannot be verified.
2. The local system is missing a Root or Intermediate certificate needed to verify the server's certificate.
3. The certificate presented by the server is expired or invalid.

See https://github.com/jstedfast/MailKit/blob/master/FAQ.md#InvalidSslCertificate for possible solutions.'

With the inner exception:

MailKit.Security.SslHandshakeException: 'An error occurred while attempting to establish an SSL or TLS connection.

The SSL certificate presented by the server is not trusted by the system for one or more of the following reasons:
1. The server is using a self-signed certificate which cannot be verified.
2. The local system is missing a Root or Intermediate certificate needed to verify the server's certificate.
3. The certificate presented by the server is expired or invalid.

See https://github.com/jstedfast/MailKit/blob/master/FAQ.md#InvalidSslCertificate for possible solutions.'

The logs show:

Connected to smtp://mta5.am0.yahoodns.net.:25/?starttls=when-available
S: 220 mtaproxy107.free.mail.ne1.yahoo.com ESMTP ready
C: EHLO bradhallfuel.com
S: 250-mtaproxy107.free.mail.ne1.yahoo.com
S: 250-PIPELINING
S: 250-SIZE 41943040
S: 250-8BITMIME
S: 250 STARTTLS
C: STARTTLS
S: 220 Ready for TLS

**Comment by jstedfast** [comment]
Use:

```csharp
client.Connect("mta5.am0.yahoodns.net", 25, SecureSocketOptions.None);
```

This will avoid using `STARTTLS` which is failing because of an invalid SSL certificate from yahoo.

**Comment by Vizeo** [comment]
That did work, so thanks, but is there a way to ignore certificate errors? Again, I am already trying this:
client.ServerCertificateValidationCallback = (s, c, h, e) => {
return true;
};

**Comment by jstedfast** [comment]
I don't know why that isn't working for you. I guess System.Net.Security.SslStream doesn't like the certificate for some reason and there's no way to override it.

**Comment by dan-webnetism** [comment]
I appreciate this is an old, closed issue - but hopefully this comment may still aid someone.

We experienced this issue in a recent project when sending email to certain hosts (Yahoo were one of them). When doing MX record lookups we were getting domains returned with a . at the end. We could connect to them fine, but connection could not be maintained when using STARTTLS (issues occurred in SslStream).

The fix in our case was to ensure hosts didn't end with a "."


For example in the SMTP logs above:
Connected to smtp://mta5.am0.yahoodns.net.:25/?starttls=when-available

There is a . before the :25 port section.
