### ISSUE TITLE
SSL connection problem when Avast's MailShield in on

### ISSUE THREAD

**Issue by atiyka** [jstedfast/MailKit#912]
I'm using successfully the MailKit in my project without any problem, but when the MailShield is turned on in Avast, then I get the following exception:
`MailKit.Security.SslHandshakeException: An error occurred while attempting to establish an SSL or TLS connection.`

Checking the [link](https://github.com/jstedfast/MailKit/blob/master/FAQ.md#InvalidSslCertificate) suggested by the exception message, I found that if I add a custom ServerCertificateValidationCallback, then it works perfectly:
`client.ServerCertificateValidationCallback = (s,c,h,e) => true;`

My question is that why isn't it an acceptable solution in the production? You wrote: 

> I would strongly recommend against it in production use

And what could be a good solution for handling this issue?

**Comment by jstedfast** [comment]
It's a bad practice to ignore all SSL certificate errors. That's the quickest way to fall for a MITM attack.

What you *should* do is to verify that the certificate is correct. You've probably seen your web browser give you a warning about an SSL certificate being invalid and it asks you to verify that the certificate is legit? That's what you need to do.

**Comment by atiyka** [comment]
I don't really understand that how can I do the same in code.
So I get the certification from the google, because I'm using gmail in my app. It couldn't be untrusted. If my Avast is on, it chains the google's certificate with another one, which is generated by the avast. If this second certificate is there, then the Mailkit fails to connect to gmail and the error message is what I already posted.
So should I ask if the user trusts in the certificate of the avast as the browsers does in case of untrusted certificates or what do you mean exactly?

**Comment by jstedfast** [comment]
> I don't really understand that how can I do the same in code.

Well, instead of doing:

```csharp
client.ServerCertificateValidationCallback = (s,c,h,e) => true;
```

you would do something like this:

```csharp
bool MyCustomServerCertificateValidationCallback (object sender, X509Certificate certificate, X509Chain chain, SslPolicyErrors sslPolicyErrors)
{
	if (sslPolicyErrors == SslPolicyErrors.None)
		return true;

	// Handle error conditions here and do whatever is the most appropriate thing for your users.
	// One possibility is to prompt a user by popping up a dialog with information about the
	// certificate and asking the user if they want to proceed.
	// (e.g. MessageBox.Show() if you are using Windows.Forms?)
}
```

and then you'd hook it up like this:

```csharp
client.ServerCertificateValidationCallback = MyCustomServerCertificateValidationCallback;
```

More documentation on this topic:

- https://docs.microsoft.com/en-us/dotnet/api/system.net.security.remotecertificatevalidationcallback?view=netframework-4.8
- https://stackoverflow.com/questions/20914305/best-practices-for-using-servercertificatevalidationcallback

**Comment by atiyka** [comment]
Thank you very much for the answer!

**Comment by gticeler** [comment]
Thank You very much for your answer!!!
