### ISSUE TITLE
LinkedResource from byte[] or stream

### ISSUE THREAD

**Issue by funklet** [jstedfast/MailKit#913]
Hello,

The only overload to add a linked resource takes a file path. 

Is there a way to add a linked resource from a byte[] or stream, otherwise I would have to write the byte[] to a file just to read it back in again..

Thanks for any help you can give..

**Comment by jstedfast** [comment]
You mean like [this](http://www.mimekit.net/docs/html/M_MimeKit_AttachmentCollection_Add_3.htm) or [this](http://www.mimekit.net/docs/html/M_MimeKit_AttachmentCollection_Add_5.htm) or [this](http://www.mimekit.net/docs/html/M_MimeKit_AttachmentCollection_Add_4.htm) or [this](http://www.mimekit.net/docs/html/M_MimeKit_AttachmentCollection_Add_6.htm)
