### ISSUE TITLE
Can't get From address

### ISSUE THREAD

**Issue by andre-idrive** [jstedfast/MailKit#915]
**Describe the bug**
There doesn't seem to be a way to get the From address.

I'm connecting to a mailbox and looping though each email. For each email, I need to be able to assign the sender email address to an array variable. Attached is the code block I'm working with.

_summary_ has an envelope property that contains the "From" property but it's always null. Any help would be appreciated.

![image](https://user-images.githubusercontent.com/53438650/65347366-db343380-dbac-11e9-8519-cc9e7407854b.png)

**Comment by jstedfast** [comment]
`MessageSummaryItems` specifies which fields of the `IMessageSummary` should be populated.

If you want the `IMessageSummary.Envelope` property to be populated, you need to include `MessageSummaryItems.Envelope` in your `Fetch()` call.

Makes sense?

**Comment by andre-idrive** [comment]
It does. Thank you
