### ISSUE TITLE
Unable to fetch Text part for email when fetching from Folder other than Inbox

### ISSUE THREAD

**Issue by arunnav** [jstedfast/MailKit#916]
**Describe the bug**
Doing 
`client.Inbox.Fetch() => **Retrieves email with HtmlBody and TextBody**`

Whereas doing -
```
var mailFolder = client.GetFolder("Sent Items");
mailFolder.Open(FolderAccess.ReadOnly);
mailFolder.Fetch() => **Retrieves only HtmlBody**
```

I tried with the same email in both folders. So the email isn't the issue as far as I can see. 

When I tried downloading .eml and .msg files for the email and using another library MSGReader, I am able to read the textbody. Even when using MailKit to read .eml file, I can view the textbody. (However .eml files downloaded using MailKit did not have TextBody)

Further testing revealed that doing `client.GetFolder("Inbox").Fetch(...)` does not retrieve TextBody but by doing `client.Inbox.Fetch(....)`, TextBody is being retrieved.

**Expected behavior**
TextBody should also be retrieved when fetching from Folders other than Inbox

**Environment**
 - Windows 10, Azure app service
 - Using dotnet core 2.2 to access outlook.office365.com server using IMAP protocol

**Comment by arunnav** [comment]
I've tried using the HtmlTokenizer to parse out Html but it isn't entirely accurate and I would prefer not to use it if I can avoid it. 
Also tried traversing the Message structure, but the text/plain part is not there at all if the message was not fetched from the Inbox.

**Comment by jstedfast** [comment]
Do you think that, perhaps, the exact arguments that you are passing to the Fetch() method might be pertinent information? Or no?

**Comment by arunnav** [comment]
I tried 
- mailFolder.Fetch(0, -1, MessageSummaryItems.Body | MessageSummaryItems.BodyStructure),
- mailFolder.Fetch(0, -1, MessageSummaryItems.All)

mailFolder.GetMessage(<uid of message>) also returns MimeMessage with no TextPart
