### ISSUE TITLE
Need option to remove sender header from message.

### ISSUE THREAD

**Issue by j055** [jstedfast/MailKit#917]
**Is your feature request related to a problem? Please describe.**
When I add the sender ```MailboxAddress``` it changes the MAIL FROM in the envelope but also adds a sender header. The problem is that in some email clients and in particular, Outlook, the client displays something like "sender@domain.com on behalf of from@domain.com" or "Sender <sender@domain.com> on behalf of From <from@domain.com>". This may be correct but the recipient is often left in doubt as to who the message is really from. Typically the sender is going to be used to handle NDRs programmatically using a VERP (Variable envelope return path) scheme and the alias part of the address could be a GUID.

**Describe the solution you'd like**
I would like an option to not add the sender header, and only change the MAIL FROM in the envelope. Perhaps adding the sender to the MimeMessage should add the header but adding it in the ```MailTransport.SendAsync``` overload does not?

**Describe alternatives you've considered**
The only way I've found to get what I want so far is to extend the SmtpClient and remove the header from the ```Prepare``` method:

```
public class ExtendedSmtpClient : SmtpClient
{
	protected override void Prepare(FormatOptions options, MimeMessage message, EncodingConstraint constraint, int maxLineLength)
	{
		message.Headers.Remove(HeaderId.Sender);

		base.Prepare(options, message, constraint, maxLineLength);
	}
}
```

I haven't fully tested this but I'm wondering if there's a better way you could point out to me?

**Additional context**
Amazon SES modifies the MAIL FROM without adding the sender header so I guess this is considered acceptable practice.

Please let me know what you think.
Thanks 
Andrew

**Comment by jstedfast** [comment]
Use SmtpClient.Send (message, from, recipients);

**Comment by j055** [comment]
Doh! I think I tried every combination except the most obvious one! MimeKit and MailKit are outstanding libraries. Thank you.

**Comment by Just1n** [comment]
What is the different between SmtpClient.Send(message) and SmtpClient.Send(message, from, recipients)?

**Comment by srikarbalmuri** [comment]
Is there a sample code I can use to achieve this feature I am also trying to implement verp

**Comment by jstedfast** [comment]
@srikarbalmuri 

```csharp
client.Send (message, from, recipients);
```
