### ISSUE TITLE
Possible issue with Socket.BeginConnect

### ISSUE THREAD

**Issue by ekalchev** [jstedfast/MailKit#920]
I am using MailKit at commit SHA 26818269484b24ed3f629ce55d37f8f42528a67a

I am not 100% sure this is MailKit issue

We've noticed that our SMTP thread was stuck and the logs suggest that probably SmtlClient.ConnectAsync method was blocking the thread.

I was using synchronously SmtpClient.ConnectAsync(...).GetAwaiter().GetResult(). (This shouldn't deadlock because calling Thead has SynchronizationContext = null)

I can see ConnectAsync is calling Socket.BeginConnect. Reading the documentation I don't see any hint about timeout for this method. Is it possible BeginConnect not to have default timeout and the code to be blocked indefinitely on BeginConnect?

**Comment by jstedfast** [comment]
I don't think `Socket.BeginConnect` makes use of the `Socket.*Timeout` properties at all, if that is what you are asking.

Afaik, BeginConnect *should* return immediately as all it does is initiate an asynchronous Connect request.

**Comment by ekalchev** [comment]
I am using SmtpClient.ConnectAsync(...).GetAwaiter().GetResult(). This will unblock the thread when you actually connect. My question is - if for some reason you can't connect should you get Timeout exception? Or this call will block forever? I can't see anything for timeout in Socket.BeginConnect documentation.

**Comment by ekalchev** [comment]
Nevermind, i ran a few tests. It seems it does timeout as you might expect.

**Comment by jstedfast** [comment]
Should I close this, then? Or?

**Comment by ekalchev** [comment]
Yes. If I have more information about that i'll update it.
