### ISSUE TITLE
Attachments corrupted after downloading while they look good and usable on the yahoo.

### ISSUE THREAD

**Issue by msufyanr** [jstedfast/MailKit#924]
I have created a service that reads multiple clients some are yahoo-mail and some are gmail, while downloading attachments it get stuck or some bug is corrupting the files. 
What looks good : 
File name and size
What's not good: 
Data Corrupted and file is of no use.

So what process i used is, I have a web-app that can send e-mails using smtp and the attachments received on the clients-end(gmail) is good and not corrupted, sender client is yahoo-mail after replying to that e-mail i receive the same e-mail in yahoo-mail that gets read by my service and it must save it correctly without corrupting the data or anything.
The code i am using is carefully written after a deep search about mailkit processes, here is the code:
`
![1](https://user-images.githubusercontent.com/30657434/66102310-5d6c2100-e5cb-11e9-88db-76d0dfb84c78.PNG)
![2](https://user-images.githubusercontent.com/30657434/66102312-5d6c2100-e5cb-11e9-983e-2aeb069611e5.PNG)
![3](https://user-images.githubusercontent.com/30657434/66102313-5e04b780-e5cb-11e9-87f5-62c336440326.PNG)

`

 - OS: [ Windows]
 - Browser [ chrome]
 - Version [ latest]

**Comment by eduardk1008** [comment]
Hi msufyanr,

Which version(s) of MailKit and Mimekit are you using? We are experiencing the same type of problem with some of our mails too.

**Comment by eduardk1008** [comment]
We are using Mailkit and Mimekit v2.1.5.1, FYI.

**Comment by msufyanr** [comment]
Hi, 
I am using 2.3.1.6 the latest stable available. It's happening with some of your emails but i am facing this with most of the emails and business is getting hurt, so i need to fix it asap. 
If anyone have solution .. please point me in the direction.
Thanks & Regards,

**Comment by jstedfast** [comment]
Why are you doing:

```csharp
getBodyPart.Content.DecodeTo (stream);
getBodyPart.Content.WriteTo (stream);
```

Seems like that's why your attachments are corrupted.

Just do `getBodyPart.Content.DecodeTo (stream);`

**Comment by msufyanr** [comment]
ok .. i will change it and test again .. 
A quick question, What is the usage difference between both ??

**Comment by jstedfast** [comment]
Well, `MimePart.Content.WriteTo()` will write the base64 encoded content and `MimePart.Content.DecodeTo()` will write the *decoded* content.

You are writing both to a stream and expecting the image loader to load it but what is likely happening is that it is finding "garbage" at the end of the real image data and not knowing what to do with it, and therefor breaking.

**Comment by msufyanr** [comment]
So your answer is specific to image, but i would like to know a generic scenario as in if i have any type of file. What will the decodeto do when .pdf,.txt,.xlsx and many more ??

**Comment by msufyanr** [comment]
@jstedfast it's still corrupted data that is receiving on my end.
It is becoming quite painful, so do help me out here.

**Comment by jstedfast** [comment]
It doesn't matter *what* kind of data is in the attachment, always use `DecodeTo()`.

The `DecodeTo()` method decodes the base64 (or quoted-printable) encoded content into the original, *unuencoded*, data.

When you send an attachment, many email servers required MIME messages (including their attachments) to be 7bit ASCII text. In order to convert file attachments to 7bit ASCII, you need to base64 encode them.

Therefore, when you receive a message and want to save an attachment, you need to reverse the process. In other words, you need to *decode* the base64 data to get the original data.

**Comment by jstedfast** [comment]
Give me a sample message with an attachment that is being "corrupted" and also give me a small sample program that shows me how you are loading the message and saving the attachment(s) so that I can figure out what you are doing wrong.

**Comment by msufyanr** [comment]
Thank you so much for the help. (+1) for the awesome library.
