### ISSUE TITLE
A certificate chain processed, but terminated in a root certificate which is not trusted by the trust provider

### ISSUE THREAD

**Issue by dayanandm123** [jstedfast/MailKit#925]
MS exchange server(Linux) is connecting from windows client.

The ssl mechanism used for connection but there is client certificates(self-signed) is using for server validation .

Certificate chain info returning always "A certificate chain processed, but terminated in a root certificate which is not trusted by the trust provider.\r\n", its whether self signed certificates installed at client trusted root or not.

Thanks in advance.

**Comment by jstedfast** [comment]
You need to provide your own `client.ServerCertificateValidationCallback` function.
