### ISSUE TITLE
Yahoo Invalid login Credentials.

### ISSUE THREAD

**Issue by msufyanr** [jstedfast/MailKit#926]
**Describe the bug**
I have this service that connects multiple clients in a foreach to read emails and dump them in sql server. What happens is, it works fine on some and it crashes on some. I don't know what have i done wrong but i am tried of trying and does not seem to understand the problem, then i brain-stromed and the server was generating un-expected sign in emails to my account. I thought maybe it's because i am authenticating it with a third-party App i.e, the service. I created an AppPassword to make it more secure. It doesn't login and the error is Login Invalid Credentials, but when i log in to my web yahoo account it works good. Can't seem to resolve this problem. Help me out.

**Comment by msufyanr** [comment]
@jstedfast  please help.

**Comment by msufyanr** [comment]
@jstedfast  this is the stack trace.
   at MailKit.Net.Imap.ImapClient.<AuthenticateAsync>d__83.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MailKit.Net.Imap.ImapClient.Authenticate(Encoding encoding, ICredentials credentials, CancellationToken cancellationToken)
   at MailKit.MailService.Authenticate(Encoding encoding, String userName, String password, CancellationToken cancellationToken)
   at MailKit.MailService.Authenticate(String userName, String password, CancellationToken cancellationToken)

**Comment by jstedfast** [comment]
You're providing credentials that the Yahoo IMAP server doesn't like.

You can get a protocol log to see if that provides a clue, but probably not...

```csharp
using (var client = new ImapClient (new ProtocolLogger ("imap.log"))
```

**Comment by msufyanr** [comment]
No. I haven't changed anything from the authentication area, it connects sometime and then it throws exception sometime. I don't know why it's happening but whenever i see my service log. Most of the log events consist of invalid login credentials. When i login from the browser it works fine but after some time, it throws exception again. It might be bug living inside of the Core Authentication area. Please look into it.

Here is a stack trace:
Exception Message: 
LOGIN Invalid credentials
Stack Trace: 
   at MailKit.Net.Imap.ImapClient.<AuthenticateAsync>d__83.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MailKit.Net.Imap.ImapClient.Authenticate(Encoding encoding, ICredentials credentials, CancellationToken cancellationToken)
   at AutoErp.CustomerEmailDownloadManager.ImapEmailClientWrapper.DownloadEmail() in 
  AutoErp.CustomerEmailDownloadManager.EmailDownLoadManager.StartDownload_CustomerEmails() in 
Exception Source: 
MailKit

**Comment by jstedfast** [comment]
Do you have the IMAP protocol log that I asked you for? Without the protocol log, there's nothing for me to look into.

**Comment by jstedfast** [comment]
FWIW, I have no trouble logging in to a Yahoo! Mail IMAP account using MailKit...

**Comment by jstedfast** [comment]
Maybe you can try creating a new Yahoo! Mail account and give me the username/password for that new account so that I can debug the issue?

Does your username or password contain non-ASCII characters? How about punctuation characters?

If you want me to look into this further, you're going to have to give me *something* to investigate. "It doesn't work for me" doesn't help me at all especially when it works just fine for me.

**Comment by msufyanr** [comment]
Yes i do have a $ sign in some of the password but i don't think that could cause any issue because a character is a character, it must be parsed exactly and sent to the server.

**Comment by jstedfast** [comment]
What do you think MailKit is doing wrong if you don't think it's passing your password to the server incorrectly?

**Comment by jstedfast** [comment]
You need to go into your Yahoo! Mail settings and enable "Allow less-secure apps".

Either that or you need to start using OAuth2.
