### ISSUE TITLE
Content Id for mails set to "multipart/multipart/mixed" in email message.

### ISSUE THREAD

**Issue by eduardk1008** [jstedfast/MailKit#927]
**Describe the bug**
When creating a new mail message using the MailKit and Mimekit helpers, when creating a message from a Multipart object, the Content Id is set to "multipart/multipart/mixed" instead of the normal "multipart/mixed". This happens when creating a MimeMessage object from a Multipart object, and then sending the email.

**To Reproduce**
Create a new outgoing email message using a MimeMessage, instead of using the BodyBuilder helper class. The MimeMessage should be built from a Multipart object using the "subType" of "multipart/mixed". Adding attachments is optional. 
When sending the mail and viewing the email as an EML file, the Content Id value is set to "multipart/multipart/mixed", instead of the correct "multipart/mixed". This can cause issues with certain email servers antispam/antivirus software seeing this message as a "malformed" message. This happened in a scenario where the recipient was using MailMarshal.

**Expected behavior**
ContentId should be set to "multipart/mixed" in all scenarios.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser All
 - Version 2.1.5.1

**Additional context**
When creating a new mail message using the BodyBuilder helper class, the message's Content Id is set correctly.

**Comment by jstedfast** [comment]
> The MimeMessage should be built from a Multipart object using the "subType" of "multipart/mixed".

So... `new Multipart ("multipart/mixed");` results in `Content-Type: multipart/multipart/mixed`?

Doctor's orders: take a sip of your morning coffee and then look at that again and tell me why you are getting the result you are getting ;-)

I'm pretty sure you'll have a "ah-hah!" moment, a little light bulb will spark to life and you'll be golden.














Hint: what you want is `new Multipart ("mixed");`

**Comment by eduardk1008** [comment]
Hi there,

Thank you for letting me know!

I have updated our code to correct this.
