### ISSUE TITLE
smtp gmail (OAUTH2) not working with scope 'GmailSend'

### ISSUE THREAD

**Issue by gopalpappu** [jstedfast/MailKit#929]
I am building an application using smtp gmail OAUTH2 authentication. Below is the sample code.

UserCredential credential = GoogleWebAuthorizationBroker.AuthorizeAsync(
                        secrets,
                        new[] { GmailService.Scope.GmailSend },
                        "user",
                        CancellationToken.None).Result;
						
using (var client = new SmtpClient())
{
	client.Connect("smtp.gmail.com", 587);                
	client.AuthenticationMechanisms.Clear();
	client.AuthenticationMechanisms.Add("XOAUTH2");                
	var oauth2 = new SaslMechanismOAuth2(credential.UserId, credential.Token.AccessToken);
	client.Authenticate(oauth2);  
}

When I use 'MailGoogleCom' as scope it is authenticating and working fine. I am able to send email.

When I use 'GmailSend' as scope it is giving authenticating error.

My only requirement is to use 'GmailSend' as I want to send only email and do not want any other functionality of mail. Also 'GmailSend' has less verification requirements from Google.

Since my requirement is to send only email, 'GmailSend' should work.

**Comment by jstedfast** [comment]
That's not how GMail scopes work, though. I know it seems intuitive that it *should* work that way, and I agree, but it doesn't - GMailSend is only for the GMailSend API, not standard SMTP.

You need to use MailGoogleCom since you are logging into mail.google.com
