### ISSUE TITLE
Kerberos Support for Mailkit

### ISSUE THREAD

**Issue by lokeshb4u** [jstedfast/MailKit#931]
**Describe the bug**
I was trying to connect using GSSAPI authenticationMachanism using Mailkit API but not successful with error : Unhandled Exception: System.NotSupportedException: No compatible authentication mechanisms found.
I confirmed that mail server supports Kerberos(GSSAPI) authenticationmechanism see output for supported authenticationmechanisms.

**To Reproduce**
sample code:
```
 using (var client = new SmtpClient(new ProtocolLogger("email.log", true)))
            {
                client.Connect(host, port, isSSL);
                Console.WriteLine("Auth types supported: ");
                foreach (var str in client.AuthenticationMechanisms)
                {
                    Console.WriteLine(str);
                }
                client.ServerCertificateValidationCallback += ValidateCertificate;
                SaslMechanism authtype = null;
                switch (auth)
                {
                    case AuthTypes.NTLM:
                        authtype = new SaslMechanismNtlm(userName, password);//WinServer
                        break;
                    case AuthTypes.LOGIN:
                        authtype = new SaslMechanismLogin(userName, password);//WinServer
                        break;
                    case AuthTypes.PLAIN:
                        authtype = new SaslMechanismPlain(userName, password);//WinServer
                        break;
                    case AuthTypes.CRAM_MD5:
                        authtype = new SaslMechanismCramMd5(userName, password);//WinServer
                        break;
                    case AuthTypes.DIGEST_MD5:
                        authtype = new SaslMechanismDigestMd5(userName, password);//WinServer
                        break;
                    case AuthTypes.KERBEROS:
                        client.AuthenticationMechanisms.Add("GSSAPI");
                        authtype = null;
                        break;
                    default:
                        authtype = null;
                        break;

                }
                if(authtype != null)
                {
                    client.Authenticate(authtype);
                }
                else
                {
                    client.Authenticate(userName, password);
                }
                
                client.MessageSent += AfterEmailSent;
                
                client.Send(message);
                
                client.Disconnect(true);
            }
```

**Expected behavior**
For the authType KERBEROS, I should connect and send email notification. But I see below error
Auth types supported:
NTLM
GSSAPI

Unhandled Exception: System.NotSupportedException: No compatible authentication mechanisms found.
   at MailKit.Net.Smtp.SmtpClient.<AuthenticateAsync>d__67.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MailKit.Net.Smtp.SmtpClient.Authenticate(Encoding encoding, ICredentials credentials, CancellationToken cancellationToken)
   at MailKit.MailService.Authenticate(Encoding encoding, String userName, String password, CancellationToken cancellationToken)
   at MailKit.MailService.Authenticate(String userName, String password, CancellationToken cancellationToken)
   at NativeMethodEx.Program.SendMessages(MimeMessage message) in C:\Users\blokesh\source\repos\Examples\NativeMethodEx\Program.cs:line 253
   at NativeMethodEx.Program.Main(String[] args) in C:\Users\blokesh\source\repos\Examples\NativeMethodEx\Program.cs:line 85

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
But I confirmed with JavaMail API with sample application for Kerberos case with same mail server. It is successful.

**Comment by jstedfast** [comment]
Calling `client.AuthenticationMechanisms.Add("GSSAPI");` isn't going to magically create a GSSAPI authentication mechanism.

You need to write the code to implement GSSAPI, MailKit does not provide it and I'm not likely to implement it. That said, you could implement it and send me a patch.
