### ISSUE TITLE
An error occurred while attempting to establish an SSL or TLS connection

### ISSUE THREAD

**Issue by neobgd** [jstedfast/MailKit#934]
Hello,
I use latest verson: 2.3.2. I have to use latest because of bug [fix](https://github.com/jstedfast/MailKit/issues/919)

with this code:
using (var client = new ImapClient())
{

                    client.ServerCertificateValidationCallback = (s, c, h, e) => true;
                    client.CheckCertificateRevocation = false;

                    client.Connect(a.inc_server, 993, true);

                    client.AuthenticationMechanisms.Remove("XOAUTH2");
                    client.Authenticate(a.inc_username, a.inc_password);
}
and from this version I getting error:
An error occurred while attempting to establish an SSL or TLS connection.

One possibility is that you are trying to connect to a port which does not support SSL/TLS.

The other possibility is that the SSL certificate presented by the server is not trusted by the system for one or more of the following reasons:
1. The server is using a self-signed certificate which cannot be verified.
2. The local system is missing a Root or Intermediate certificate needed to verify the server's certificate.
3. The certificate presented by the server is expired or invalid.

See https://github.com/jstedfast/MailKit/blob/master/FAQ.md#InvalidSslCertificate for possible solutions.

Inner exception message is:
The client and server cannot communicate, because they do not possess a common algorithm
 What I check,
Exchange server has valid certificate, Our server has valid root certificate.
Also tried with numerous combination using SecureSocketOptions

Thanks in advance.

**Comment by jstedfast** [comment]
> The client and server cannot communicate, because they do not possess a common algorithm

This *probably* means that your server does not support any of the SSL/TLS protocol versions that your MailKit client supports.

You can change which versions of SSL/TLS your MailKit client will accept by setting the `client.SslProtocols` property.

For example, to enable TLSv1.0 (which is what I would recommend trying first), you can do this:

```csharp
client.SslProtocols |= SslProtocols.Tls;
```

**Comment by Vishujai** [comment]
jstedfast
                              I have prepare a bot in ui path some error See https://github.com/jstedfast/MailKit/blob/master/FAQ.md#InvalidSslCertificate for possible solutions.

**Comment by jstedfast** [comment]
@Vishujai You keep repeating that exact same phrase that doesn't make any sense. I'm beginning to think you are a bot.

**Comment by Sertan57** [comment]
Hello jstedfast,

I have exactly the same error as the neobgd.
Ive tried every option from this https://github.com/jstedfast/MailKit/blob/master/FAQ.md#SslHandshakeException site but the error remains. It is an Outlook O365 IMAP server and I use the port 993.
Below the code:

```
            imapClient.ServerCertificateValidationCallback = (s, c, h, e) => true;
            imapClient.CheckCertificateRevocation = false;
            imapClient.SslProtocols = SslProtocols.Ssl3 | SslProtocols.Ssl2 | SslProtocols.Tls | SslProtocols.Tls11 | SslProtocols.Tls12;
            imapClient.Connect(host: IMAP_SERVER, port: IMAP_PORT, options: SecureSocketOptions.SslOnConnect);
```

could you please help me?

**Comment by lafar6502** [comment]
I can confirm there is an error connecting to Exchange  / OWA server over POP3 and SMTP with Ssl or Tls enabled. Tried any combinations listed and not listed here, to no avail. the message is always 
**The client and server cannot communicate, because they do not possess a common algorithm**

.Net Framework v4.6.1

Solution was found by going back with MailKit versions.
The last version where the connection works is **MailKit v 2.3.1.6**
and the same exactly code breaks on next version **2.3.2**

Can you please verify what was changed and where the problem could come from? 
PS im not a bot.
test code:
```
using (Pop3Client cli = new Pop3Client())
            {
                cli.CheckCertificateRevocation = false;
                cli.ServerCertificateValidationCallback = (s, c, ch, e) => true;
                //cli.SslProtocols = SslProtocols.Tls | SslProtocols.Tls11 | SslProtocols.Tls12  | SslProtocols.Ssl2;
                //cli.SslProtocols = SslProtocols.Ssl2;
                //cli.Timeout = NetworkTimeoutMs;
                cli.Connect(server, popPort);
                cli.Authenticate(user, pass);
                var uids = cli.GetMessageUids();
            }
```
