### ISSUE TITLE
Pop3 client

### ISSUE THREAD

**Issue by dayanandm123** [jstedfast/MailKit#937]
What is login capability used by pop3client by default.

I would like to login by apop or pop3 as login capabilities as the user request. How can be use these in the  pop3 client for login?

**Comment by jstedfast** [comment]
You can check if the POP3 server supports APOP using the following check:

```csharp
if (client.Capabilities.HasFlag (Pop3Capabilities.Apop))
```

You can check if the POP3 server supports the USER/PASS set of login commands using the following check:

```csharp
if (client.Capabilities.HasFlag (Pop3Capabilities.User))
```

If the POP3 server supports APOP, APOP authentication will be used in the Authenticate() method.

To disable it, do this:

```csharp
client.Capabilities &= ~Pop3Capabilities.Apop;
```

If the POP3 server supports *any* SASL mechanisms that MailKit supports, then MailKit will attempt to use the SASL mechanisms *first* and only fall back to `USER`/`PASS` if they fail.

To avoid attempting to login using a SASL mechanism, disable them *after* Connect() using:

```csharp
client.AuthenticationMechanisms.Remove ("PLAIN");
client.AuthenticationMechanisms.Remove ("LOGIN");
client.AuthenticationMechanisms.Remove ("CRAM-MD5");
client.AuthenticationMechanisms.Remove ("DIGEST-MD5");
// etc...
```

-or-

```csharp
client.AuthenticationMechanisms.Clear ();
```

**Comment by dayanandm123** [comment]
How we can check pop3 capability support by server?

**Comment by jstedfast** [comment]
Use the code I provided above after connecting to the server.
