### ISSUE TITLE
IMAP Server,like QQ Mail . Search with SubjectContainer method is not work

### ISSUE THREAD

**Issue by jol5** [jstedfast/MailKit#946]
**Describe the bug**

Code:
ImapClient client = new ImapClient()
 SearchQuery sqResult = new SearchQuery();
var sqResult = sqResult.And(SearchQuery.SubjectContains(“xxxxxxxx”)).And(SearchQuery.NotSeen);;
var uids = client.Inbox.Search(sqResult);

the result only filter NotSeen ，SubjectContains not work well

**Desktop (please complete the following information):**
 - OS:  WIN10
 - NET CORE 2.2

**Comment by jstedfast** [comment]
Please provide a protocol log:

```csharp
client = new ImapClient (new ProtocolLogger ("imap.log"))
```

**Comment by jstedfast** [comment]
FWIW, you can simplify your query construction code to this:

```csharp
var query = SearchQuery.SubjectContains(“xxxxxxxx”).And(SearchQuery.NotSeen);
```

**Comment by jol5** [comment]
> Please provide a protocol log:
> 
> ```cs
> client = new ImapClient (new ProtocolLogger ("imap.log"))
> ```
IMap.log
Connected to imaps://imap.exmail.qq.com:993/
S: * OK [CAPABILITY IMAP4 IMAP4rev1 ID AUTH=LOGIN NAMESPACE] QQMail IMAP4Server ready
C: A00000000 AUTHENTICATE LOGIN
... ...
... ...
... ...
S: A00000000 OK Success login ok
C: A00000001 CAPABILITY
S: * CAPABILITY IMAP4 IMAP4rev1 XLIST MOVE IDLE XAPPLEPUSHSERVICE NAMESPACE CHILDREN ID UIDPLUS
S: A00000001 OK CAPABILITY Completed
C: A00000002 NAMESPACE
S: * NAMESPACE (("" "/")) NIL NIL
S: A00000002 OK NAMESPACE Success
C: A00000003 LIST "" "INBOX"
S: * LIST (\HasNoChildren) "/" "INBOX"
S: A00000003 OK LIST completed
C: A00000004 XLIST "" "*"
S: * XLIST (\NoSelect \HasChildren) "/" "&UXZO1mWHTvZZOQ-"
S: * XLIST (\HasNoChildren \Inbox) "/" "INBOX"
S: * XLIST (\HasNoChildren \Sent) "/" "Sent Messages"
S: * XLIST (\HasNoChildren \Drafts) "/" "Drafts"
S: * XLIST (\HasNoChildren \Trash) "/" "Deleted Messages"
S: * XLIST (\HasNoChildren \Junk) "/" "Junk"
S: A00000004 OK XLIST completed
C: A00000005 SELECT INBOX
S: * 3688 EXISTS
S: * 0 RECENT
S: * OK [UNSEEN 2343]
S: * OK [UIDVALIDITY 1545009799] UID validity status
S: * OK [UIDNEXT 3707] Predicted next UID
S: * FLAGS (\Answered \Flagged \Deleted \Draft \Seen)
S: * OK [PERMANENTFLAGS (\* \Answered \Flagged \Deleted \Draft \Seen)] Permanent flags
S: A00000005 OK [READ-WRITE] SELECT complete
C: A00000006 UID SEARCH SINCE 18-Sep-2019 SUBJECT PRE-ALERT
S: * SEARCH 2200 2201 2202 2203 2204 2205 2206  ... .... more than 1k  ... ... 
S: A00000006 OK UID SEARCH completed

**Comment by jstedfast** [comment]
Seems like MailKit is sending the SUBJECT search query. What's the bug? Is the bug that your IMAP server is returning UIDs that don't match your query?

**Comment by jol5** [comment]
> Seems like MailKit is sending the SUBJECT search query. What's the bug? Is the bug that your IMAP server is returning UIDs that don't match your query?

yes,  just match query date.

**Comment by jstedfast** [comment]
Okay, then this is a server bug. I can't work around a server bug where the server does the wrong thing. I can only work around server bugs where the syntax they return is broken in some way.
