### ISSUE TITLE
Whats special name "Archive Folder" for Yahoo IMAP Server

### ISSUE THREAD

**Issue by firstlord1** [jstedfast/MailKit#959]
Hi, i need to move all inbox messages to archive folder on Yahoo Imap Server. But I'm getting this error "The IMAP server does not support the SPECIAL-USE". I need to Yahoo Archive Folder special name. I can move all mails to spam with "Bulk Mail" folder name. How can i inbox to archive ? Do you have any idea ? Thanks...

Inbox to Spam (is working) : `inbox.MoveTo(UniqueIdRange.All, client.GetFolder("Bulk Mail"));`

Inbox to Archive (error) : `inbox.MoveTo(UniqueIdRange.All, client.GetFolder(SpecialFolder.Archive));`

**Comment by jstedfast** [comment]
`client.GetFolder(SpecialFolder.Archive)` only works if the server supports the `SPECIAL-USE` extension which is an extension where the server tells the client which folder to is the Spam/Archive/Draft/etc folders.

Without that extension, the client has to guess which folder is for each of these things.

My only suggestion for you is to look for a folder called "Archive".
