### ISSUE TITLE
Folder.MoveTo throw exception "The folder is not currently open."

### ISSUE THREAD

**Issue by vnwind** [jstedfast/MailKit#96]
Hi 
I am trying to move a message from Inbox folder to Matched folder but it throws an exception. Here is the code

var inbox = imapClient.Inbox;
inbox.Open(FolderAccess.ReadWrite);

var matchFolder = imapClient.GetFolder(FOLDER_TO_MATCHED);
matchFolder.Open(FolderAccess.ReadWrite);

if (matchFolder != null)
         inbox.MoveTo(uid, matchFolder);

Please helps
Thanks

**Comment by Gonzo345** [comment]
Hi there:

I'm trying to move a mail from inbox to another folder and I'm getting this same Exception.

My code is the following
`imap.Inbox.Open(FolderAccess.ReadWrite);

                    var uids = imap.Inbox.Search(SearchQuery.NotSeen);
                    foreach (var uid in uids)
                    {
                        var toplevel = imap.GetFolder(imap.PersonalNamespaces[0]);
                        var nombreCarpeta = toplevel.GetSubfolder("folderName");
                        if (imap.Inbox.IsOpen || nombreCarpeta != null)
                            toplevel.MoveTo(uid, nombreCarpeta, CancellationToken.None);
                    }

When it reaches inside the if, it throws the Exception. I tried to manually open the Inbox again just before, I tried to open the toplevel (???) with another Exception result, of course.

It's interesting getting the point that it could just have just one folder open at a time, so if I see Inbox is opened, why am I getting a FolderNotOpenException?

Thanks in advance and congratulations for this amazing library.
Gonzo345.

**Comment by jstedfast** [comment]
You never `Open()` the `toplevel` folder.

**Comment by Gonzo345** [comment]
Thanks for replying but... if I don't perform the imap.Inbox.Open(FolderAccess.ReadWrite); I can't even perform the search to get the uids :/

**Comment by jstedfast** [comment]
No, I mean, you get the toplevel folder but never opened it before trying to move messages out of it.

You need to open the folder that you are moving messages out of.

BTW, `toplevel` is probably not the same as `imap.Inbox`.

**Comment by jstedfast** [comment]
This is what your code *should* look like:

```csharp
imap.Inbox.Open (FolderAccess.ReadWrite);

var uids = imap.Inbox.Search (SearchQuery.NotSeen);
var toplevel = imap.GetFolder (imap.PersonalNamespaces[0]);
var nombreCarpeta = toplevel.GetSubfolder ("folderName");
if (nombreCarpeta != null)
    imap.Inbox.MoveTo (uids, nombreCarpeta);
```

**Comment by Gonzo345** [comment]
Wow, now I get it and works like a charm! Thank you so much for your unvaluable help!
