### ISSUE TITLE
 search by sender does not work

### ISSUE THREAD

**Issue by dronamiusSlIVA** [jstedfast/MailKit#961]
Hello. I find a bug
https://prnt.sc/q9417v

i tested this email

email           swp525767797@sina.com
password    shiwenping

Error stack

	MailKit.Net.Imap.ImapFolder.SearchAsync(MailKit.Search.SearchQuery, bool, bool, System.Threading.CancellationToken)
	System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
	System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
	MailKit.Net.Imap.ImapFolder.Search(MailKit.Search.SearchQuery, System.Threading.CancellationToken)

**Comment by jstedfast** [comment]
Most likely your IMAP server is buggy and does not recognize the charset parameter.

Please get a protocol log so I can look at the raw IMAP commands.

**Comment by dronamiusSlIVA** [comment]
Thanks for answer

Log file:


`Connected to imap://imap.sina.com:143/?starttls=when-available
S: * OK [CAPABILITY IMAP4rev1 ID] sina imap ready
C: A00000000 LOGIN swp525767797@sina.com shiwenping
S: A00000000 OK [CAPABILITY IMAP4rev1 ID] User swp525767797@sina.com authenticated
C: A00000001 LIST "" ""
S: * LIST () "/" "&UXZbg5CuTvY-"
S: * LIST () "/" "INBOX"
S: * LIST (\Drafts) "/" "&g0l6P1k5-"
S: * LIST (\Sent) "/" "&XfJT0ZAB-"
S: * LIST (\Trash) "/" "&XfJSIJZk-"
S: * LIST (\Junk) "/" "&V4NXPpCuTvY-"
S: * LIST () "/" "&i6KWBZCuTvY-"
S: * LIST () "/" "&Zh9oB5CuTvY-"
S: * LIST () "/" "&VUaLr0,hYG8-"
S: * LIST () "/" "&f1F62ZAad+U-"
S: A00000001 OK LIST completed
C: A00000002 LIST "" "INBOX"
S: * LIST () NIL INBOX
S: A00000002 OK LIST completed
C: A00000003 EXAMINE INBOX
S: * 7 EXISTS
S: * 2 RECENT
S: * OK [UIDVALIDITY 1] UID validity status
S: * OK [UIDNEXT 1400] Predicted next UID
S: * FLAGS (\Answered \Flagged \Deleted \Draft \Seen)
S: * OK [PERMANENTFLAGS (\* \Answered \Flagged \Deleted \Draft \Seen)] Permanent flags
S: * OK [UNSEEN 6] first unseen message in INBOX
S: A00000003 OK [READ-ONLY] EXAMINE completed
C: A00000004 UID SEARCH FROM noreply@netflix.com
S: A00000004 BAD Missing or invalid or unimplemented argument to UID SEARCH`

**Comment by jstedfast** [comment]
try this:

```csharp
((ImapFolder) client.Inbox).Search ("FROM \"noreply@netflix.com\"");
```

**Comment by jstedfast** [comment]
I forgot that, in an effort to work around bugs in other IMAP servers, if the search strings are all ASCII, MailKit omits the charset parameter.

But it looks like your IMAP server is broken in that expects a quoted string when it doesn't need to be quoted.

**Comment by dronamiusSlIVA** [comment]
Unfortunately the same error. I want to note that in the Mozilla thunderbird with the search, everything is fine.

https://prnt.sc/q9fm8m

Connected to imap://imap.sina.com:143/?starttls=when-available
S: * OK [CAPABILITY IMAP4rev1 ID] sina imap ready
C: A00000000 LOGIN swp525767797@sina.com shiwenping
S: A00000000 OK [CAPABILITY IMAP4rev1 ID] User swp525767797@sina.com authenticated
C: A00000001 LIST "" ""
S: * LIST () "/" "&UXZbg5CuTvY-"
S: * LIST () "/" "INBOX"
S: * LIST (\Drafts) "/" "&g0l6P1k5-"
S: * LIST (\Sent) "/" "&XfJT0ZAB-"
S: * LIST (\Trash) "/" "&XfJSIJZk-"
S: * LIST (\Junk) "/" "&V4NXPpCuTvY-"
S: * LIST () "/" "&i6KWBZCuTvY-"
S: * LIST () "/" "&Zh9oB5CuTvY-"
S: * LIST () "/" "&VUaLr0,hYG8-"
S: * LIST () "/" "&f1F62ZAad+U-"
S: A00000001 OK LIST completed
C: A00000002 LIST "" "INBOX"
S: * LIST () NIL INBOX
S: A00000002 OK LIST completed
C: A00000003 EXAMINE INBOX
S: * 7 EXISTS
S: * 2 RECENT
S: * OK [UIDVALIDITY 1] UID validity status
S: * OK [UIDNEXT 1400] Predicted next UID
S: * FLAGS (\Answered \Flagged \Deleted \Draft \Seen)
S: * OK [PERMANENTFLAGS (\* \Answered \Flagged \Deleted \Draft \Seen)] Permanent flags
S: * OK [UNSEEN 6] first unseen message in INBOX
S: A00000003 OK [READ-ONLY] EXAMINE completed
C: A00000004 UID SEARCH FROM "noreply@netflix.com"
S: A00000004 BAD Missing or invalid or unimplemented argument to UID SEARCH

**Comment by jstedfast** [comment]
> I want to note that in the Mozilla thunderbird with the search, everything is fine.

All that means is that Thunderbird is working around your server bug. It doesn't mean that MailKit is broken.

Here's the IMAP SEARCH syntax:

```
astring         = 1*ASTRING-CHAR / string

ASTRING-CHAR   = ATOM-CHAR / resp-specials

atom            = 1*ATOM-CHAR

ATOM-CHAR       = <any CHAR except atom-specials>

atom-specials   = "(" / ")" / "{" / SP / CTL / list-wildcards /
                  quoted-specials / resp-specials

list-wildcards  = "%" / "*"

quoted          = DQUOTE *QUOTED-CHAR DQUOTE

QUOTED-CHAR     = <any TEXT-CHAR except quoted-specials> /
                  "\" quoted-specials

quoted-specials = DQUOTE / "\"

resp-specials   = "]"

search          = "SEARCH" [SP "CHARSET" SP astring] 1*(SP search-key)
                    ; CHARSET argument to MUST be registered with IANA

search-key      = "ALL" / "ANSWERED" / "BCC" SP astring /
                  "BEFORE" SP date / "BODY" SP astring /
                  "CC" SP astring / "DELETED" / "FLAGGED" /
                  "FROM" SP astring / "KEYWORD" SP flag-keyword /
                  "NEW" / "OLD" / "ON" SP date / "RECENT" / "SEEN" /
                  "SINCE" SP date / "SUBJECT" SP astring /
                  "TEXT" SP astring / "TO" SP astring /
                  "UNANSWERED" / "UNDELETED" / "UNFLAGGED" /
                  "UNKEYWORD" SP flag-keyword / "UNSEEN" /
                    ; Above this line were in [IMAP2]
                  "DRAFT" / "HEADER" SP header-fld-name SP astring /
                  "LARGER" SP number / "NOT" SP search-key /
                  "OR" SP search-key SP search-key /
                  "SENTBEFORE" SP date / "SENTON" SP date /
                  "SENTSINCE" SP date / "SMALLER" SP number /
                  "UID" SP sequence-set / "UNDRAFT" / sequence-set /
                  "(" search-key *(SP search-key) ")"

string          = quoted / literal
```

Do you see any bugs in MailKit's SEARCH syntax? I don't.

try this:

```csharp
((ImapFolder) client.Inbox).Search ("CHARSET US-ASCII FROM \"noreply@netflix.com\"");
```

(Note: the CHARSET parameter is optional according to the spec)

**Comment by dronamiusSlIVA** [comment]
Same error =(


Connected to imap://imap.sina.com:143/?starttls=when-available
S: * OK [CAPABILITY IMAP4rev1 ID] sina imap ready
C: A00000000 LOGIN swp525767797@sina.com shiwenping
S: A00000000 OK [CAPABILITY IMAP4rev1 ID] User swp525767797@sina.com authenticated
C: A00000001 LIST "" ""
S: * LIST () "/" "&UXZbg5CuTvY-"
S: * LIST () "/" "INBOX"
S: * LIST (\Drafts) "/" "&g0l6P1k5-"
S: * LIST (\Sent) "/" "&XfJT0ZAB-"
S: * LIST (\Trash) "/" "&XfJSIJZk-"
S: * LIST (\Junk) "/" "&V4NXPpCuTvY-"
S: * LIST () "/" "&i6KWBZCuTvY-"
S: * LIST () "/" "&Zh9oB5CuTvY-"
S: * LIST () "/" "&VUaLr0,hYG8-"
S: * LIST () "/" "&f1F62ZAad+U-"
S: A00000001 OK LIST completed
C: A00000002 LIST "" "INBOX"
S: * LIST () NIL INBOX
S: A00000002 OK LIST completed
C: A00000003 EXAMINE INBOX
S: * 7 EXISTS
S: * 2 RECENT
S: * OK [UIDVALIDITY 1] UID validity status
S: * OK [UIDNEXT 1400] Predicted next UID
S: * FLAGS (\Answered \Flagged \Deleted \Draft \Seen)
S: * OK [PERMANENTFLAGS (\* \Answered \Flagged \Deleted \Draft \Seen)] Permanent flags
S: * OK [UNSEEN 6] first unseen message in INBOX
S: A00000003 OK [READ-ONLY] EXAMINE completed
C: A00000004 UID SEARCH CHARSET US-ASCII FROM "noreply@netflix.com"
S: A00000004 BAD Missing or invalid or unimplemented argument to UID SEARCH

**Comment by jstedfast** [comment]
*shrug*

Try this?

```csharp
((ImapFolder) client.Inbox).Search ("CHARSET US-ASCII HEADER FROM \"noreply@netflix.com\"");
```

If that works, try:

```csharp
client.Inbox.Search (SearchQuery.HeaderContains ("FROM", "noreply@netflix.com"));
```

**Comment by jstedfast** [comment]
If those don't work, the only thing I can suggest is to try and figure out what the SEARCH command is that Thunderbird sends.

I'm honestly beginning to think that Thunderbird probably falls back to doing a local search query of your cached messages if the IMAP server returns BAD.

**Comment by dronamiusSlIVA** [comment]
Same.

Connected to imap://imap.sina.com:143/?starttls=when-available
S: * OK [CAPABILITY IMAP4rev1 ID] sina imap ready
C: A00000000 LOGIN swp525767797@sina.com shiwenping
S: A00000000 OK [CAPABILITY IMAP4rev1 ID] User swp525767797@sina.com authenticated
C: A00000001 LIST "" ""
S: * LIST () "/" "&UXZbg5CuTvY-"
S: * LIST () "/" "INBOX"
S: * LIST (\Drafts) "/" "&g0l6P1k5-"
S: * LIST (\Sent) "/" "&XfJT0ZAB-"
S: * LIST (\Trash) "/" "&XfJSIJZk-"
S: * LIST (\Junk) "/" "&V4NXPpCuTvY-"
S: * LIST () "/" "&i6KWBZCuTvY-"
S: * LIST () "/" "&Zh9oB5CuTvY-"
S: * LIST () "/" "&VUaLr0,hYG8-"
S: * LIST () "/" "&f1F62ZAad+U-"
S: A00000001 OK LIST completed
C: A00000002 LIST "" "INBOX"
S: * LIST () NIL INBOX
S: A00000002 OK LIST completed
C: A00000003 EXAMINE INBOX
S: * 7 EXISTS
S: * 2 RECENT
S: * OK [UIDVALIDITY 1] UID validity status
S: * OK [UIDNEXT 1400] Predicted next UID
S: * FLAGS (\Answered \Flagged \Deleted \Draft \Seen)
S: * OK [PERMANENTFLAGS (\* \Answered \Flagged \Deleted \Draft \Seen)] Permanent flags
S: * OK [UNSEEN 6] first unseen message in INBOX
S: A00000003 OK [READ-ONLY] EXAMINE completed
C: A00000004 UID SEARCH CHARSET US-ASCII HEADER FROM "noreply@netflix.com"
S: A00000004 BAD Missing or invalid or unimplemented argument to UID SEARCH

- "I'm honestly beginning to think that Thunderbird probably falls back to doing a local search query of your cached messages if the IMAP server returns BAD."

Is it necessary to use wireshark? For sniffing?

**Comment by jstedfast** [comment]
There might be tools other than wireshark that you can use and/or perhaps Thunderbird has a way to log, but I don't know what that is if it exists.

**Comment by dronamiusSlIVA** [comment]
If I succeed, I'll let you know.

**Comment by dronamiusSlIVA** [comment]
I tried to catch TCP requests of Mozilla Thunderbird, I used simple tcp sniffer, but did not find SEARCH requests there. Apparently there is no such function on this domain and it works on the principle of POP3 - complete message unloading

**Comment by jstedfast** [comment]
Okay. In that case, I guess I would suggest this:

```csharp
var results = client.Inbox.Fetch (0, -1, MessageSummaryItems.UniqueId | MessageSummaryItems.Envelope);
var matches = new UniqueIdSet ();
foreach (var result in results) {
    foreach (var mailbox in result.Envelope.From.Mailboxes) {
        if (mailbox.Address.Equals ("noreply@netflix.com", StringComparison.OrdinalIgnoreCase)) {
            matches.Add (result.UniqueId);
            break;
        }
    }
}
```

**Comment by lyling** [comment]
> Okay. In that case, I guess I would suggest this:
> 
> ```cs
> var results = client.Inbox.Fetch (0, -1, MessageSummaryItems.UniqueId | MessageSummaryItems.Envelope);
> var matches = new UniqueIdSet ();
> foreach (var result in results) {
>     foreach (var mailbox in result.Envelope.From.Mailboxes) {
>         if (mailbox.Address.Equals ("noreply@netflix.com", StringComparison.OrdinalIgnoreCase)) {
>             matches.Add (result.UniqueId);
>             break;
>         }
>     }
> }
> ```

My folder over 30,000 mails. This lead to  fetch too slow. I have the same problem about Search subject of Chinese Character.
