### ISSUE TITLE
Problem downloading big message

### ISSUE THREAD

**Issue by danexis-szu** [jstedfast/MailKit#963]
I am triying to download a message with:
GetMessage(1, cancel.Token).

It already took quite a lot of time for the first message, the second message took even longer so that the CLR somehow stopped the execution and showed the following exception message:

"Managed Debugging Assistant 'ContextSwitchDeadlock' 
  Message=Managed Debugging Assistant 'ContextSwitchDeadlock' : 'Die CLR konnte 60 Sekunden lang keinen Übergang vom COM-Kontext 0x71256690 zum COM-Kontext 0x71256568 durchführen. Der Thread, der Besitzer des Zielkontexts/-apartments ist, wartet entweder, ohne Meldungen zu verschieben, oder verarbeitet eine äußerst lang dauernde Operation, ohne Windows-Meldungen zu verschieben. Eine solche Situation beeinträchtigt in der Regel die Leistung und kann sogar dazu führen, dass die Anwendung nicht mehr reagiert oder die Speicherauslastung immer weiter zunimmt. Zur Vermeidung dieses Problems sollten alle STA-Threads (Singlethread-Apartment) primitive Typen verwenden, die beim Warten Meldungen verschieben (z. B. CoWaitForMultipleHandles), und bei lange dauernden Operationen generell Meldungen verschieben.'"

This specific Mail-Account does not support IMAP, but i forwarded some messages to another account with IMAP and tried to download the messages there, it worked.

Please see the log-file: https://drive.google.com/open?id=1hUORvpARly_oFmiopckQUIf_x2DTE4JV

**Comment by jstedfast** [comment]
The exception you posted suggests that the bug is in the Managed Debugging Assistant and not MailKit afaict (I don't read German, but the exception message clearly states that there was a deadlock in the Managed Debugging Assistant).

The wav file attachment is only about 7MB which isn't that large tbh.

**Comment by danexis-szu** [comment]
Did you read the attached log-File generated from MailKit? You should see in there that one message was downloaded and it got stuck on the second message.

I don't think it's a bug in the

This is the exception in english:
The CLR has been unable to transition from COM context 0x71256690 to COM context 0x71256568 for 60 seconds. The thread that owns the destination context/apartment is most likely either doing a non pumping wait or processing a very long running operation without pumping Windows messages. This situation generally has a negative performance impact and may even lead to the application becoming non responsive or memory usage accumulating continually over time. To avoid this problem, all single threaded apartment (STA) threads should use pumping wait primitives (such as CoWaitForMultipleHandles) and routinely pump messages during long running operations.

I could disable the ContextSwitchDeadlock (https://stackoverflow.com/questions/578357/visual-studio-contextswitchdeadlock) but then i would need to wait more than 60 s to get the message downloaded which is also not what i want and i think it's either a bug in MailKit or a bug in the POP3-server.

If you want to try yourself i could give you the credentials and you could try yourself to download the messages, they are not confidential..

Von: Jeffrey Stedfast <notifications@github.com>
Gesendet: Mittwoch, 18. Dezember 2019 13:24
An: jstedfast/MailKit <MailKit@noreply.github.com>
Cc: Samuel Zürcher <Samuel.Zuercher@danexis.com>; Author <author@noreply.github.com>
Betreff: Re: [jstedfast/MailKit] Problem downloading big message (#963)


The exception you posted suggests that the bug is in the Managed Debugging Assistant and not MailKit afaict (I don't read German, but the exception message clearly states that there was a deadlock in the Managed Debugging Assistant).

The wav file attachment is only about 7MB which isn't that large tbh.

**Comment by jstedfast** [comment]
> Did you read the attached log-File generated from MailKit? You should see in there that one message was downloaded and it got stuck on the second message.

Yes, I saw. The second message (which did not finish downloading) had a 7MB wav attachment that did not completely download.

> The thread that owns the destination context/apartment is most likely either doing a non pumping wait or processing a very long running operation without pumping Windows messages. 

Are you writing a Windows.Forms or WPF app?

This error message is telling you that the problem is that you are blocking the UI thread in your Windows app (that's what they mean when they say that you are not pumping the Windows messages).

You need to fix your code to download messages in another thread.

> If you want to try yourself i could give you the credentials and you could try yourself to download the messages, they are not confidential..

I'm willing to give it a try but I am 100% confident that it'll download w/o a problem in my own test app.

**Comment by danexis-szu** [comment]
Ok,

The credentials are:

User: user\dxscan
Password: PI4Zy5je4ki(
Host: webmail.nosergroup.com
Port: 110 (Pop3Client)
SecureSocketOptions: Auto

The first message (index = 0) should work but needs about 20 Seconds, the second message should not work, and i was never able to get more than 3 messages in a row.

Thanks a lot to look at it!

Von: Jeffrey Stedfast <notifications@github.com>
Gesendet: Mittwoch, 18. Dezember 2019 14:34
An: jstedfast/MailKit <MailKit@noreply.github.com>
Cc: Samuel Zürcher <Samuel.Zuercher@danexis.com>; Author <author@noreply.github.com>
Betreff: Re: [jstedfast/MailKit] Problem downloading big message (#963)


Did you read the attached log-File generated from MailKit? You should see in there that one message was downloaded and it got stuck on the second message.

Yes, I saw. The second message (which did not finish downloading) had a 7MB wav attachment that did not completely download.

The thread that owns the destination context/apartment is most likely either doing a non pumping wait or processing a very long running operation without pumping Windows messages.

Are you writing a Windows.Forms or WPF app?

This error message is telling you that the problem is that you are blocking the UI thread in your Windows app (that's what they mean when they say that you are not pumping the Windows messages).

You need to fix your code to download messages in another thread.

If you want to try yourself i could give you the credentials and you could try yourself to download the messages, they are not confidential..

I'm willing to give it a try but I am 100% confident that it'll download w/o a problem in my own test app.

**Comment by danexis-szu** [comment]
I also forwarded the first 5 messages to other mailaccounts (gmx.net and outlook.com) and tried to download them there: it worked like a charm with POP and also with IMAP.

Therefore there might also be a problem with this specific pop-mailserver..

**Comment by jstedfast** [comment]
I can't seem to connect.

**Comment by danexis-szu** [comment]
> 
> 
> I can't seem to connect.

The connection details are also in the logfile:
Connected to pop://webmail.nosergroup.com:110/?starttls=when-available

Maybe you forgot to type in "user\" as the user?

These two lines worked for me:
Connect("webmail.nosergroup.com", 110);
Authenticate(@"user\dxscan", "PI4Zy5je4ki(");

**Comment by jstedfast** [comment]
No, the problem is not that I can't authenticate, the problem is that I can't connect.

```
telnet webmail.nosergroup.com 110
Trying 87.117.70.3...
telnet: connect to address 87.117.70.3: Operation timed out
telnet: Unable to connect to remote host
```

**Comment by danexis-szu** [comment]
> 
> 
> No, the problem is not that I can't authenticate, the problem is that I can't connect.
> 
> ```
> telnet webmail.nosergroup.com 110
> Trying 87.117.70.3...
> telnet: connect to address 87.117.70.3: Operation timed out
> telnet: Unable to connect to remote host
> ```

Are you able to login via browser: https://webmail.nosergroup.com/owa/ ?

**Comment by jstedfast** [comment]
Yes, but my guess is that your POP3 server firewalls connections from outside the network (or outside of a whitelisted set of IPs)

**Comment by danexis-szu** [comment]
> 
> 
> Yes, but my guess is that your POP3 server firewalls connections from outside the network (or outside of a whitelisted set of IPs)

One of our IT-Admins will look at it within the next hour..

**Comment by danexis-szu** [comment]
You were right, the pop server is not responding.. Since it would be a bigger task to make the pop server accessible globally i will not investigate further as it seems to work with other mailservers.

If the problem pops up at one of our clients we will look at it again.

Thanks for your support!

**Comment by jstedfast** [comment]
No problem!
