### ISSUE TITLE
LOGIN failed when connecting to Shared mail box(.net core 2.2)

### ISSUE THREAD

**Issue by evenlee** [jstedfast/MailKit#965]
**Describe the bug**
We want to get an attachment from a shared email box. and our company has 2 steps auth(rsa token) for account authentication.

after googled, the code should like :

               using (var emailClient = new ImapClient())
               {

                    emailClient.Connect("outlook.office365.com", 993, SecureSocketOptions.SslOnConnect);
                   //emailClient.Connect("outlook.office365.com", 993, true);

                    emailClient.AuthenticationMechanisms.Remove("XOAUTH2");
                    
                    //emailClient.Authenticate("name@domain.com\\sharedmailbox@@domain.com", "passwordofname");
                    emailClient.Authenticate("name@domain.com\\sharedmailalias", "passwordofname");
                    ...
               }
when authenticate(also tested the commented lines), got error:

                    {MailKit.Security.AuthenticationException: LOGIN failed.
                 at MailKit.Net.Imap.ImapClient.AuthenticateAsync(Encoding encoding, ICredentials credentials, Boolean doAsync, CancellationToken cancellationToken)
                 at MailKit.Net.Imap.ImapClient.Authenticate(Encoding encoding, ICredentials credentials, CancellationToken cancellationToken)
                 at MailKit.MailService.Authenticate(Encoding encoding, String userName, String password, CancellationToken cancellationToken)
                 at MailKit.MailService.Authenticate(String userName, String password, CancellationToken cancellationToken)

Does mailkit support imap to read office365 shared mail box? or I misused some code?

**Comment by jstedfast** [comment]
MailKit supports the full IMAP protocol. If you are getting an error for the LOGIN command saying that the username or password failed, then it means that syntax is not supported by the IMAP server.

Shared mailboxes are usually not done using a special username string. It is generally done using the shared namespace(s) which you can access using [ImapClient.SharedNamespaces](http://www.mimekit.net/docs/html/P_MailKit_Net_Imap_ImapClient_SharedNamespaces.htm).

for example:

```csharp
using (var client = new ImapClient ()) {
    client.Connect ("outlook.office365.com", 993, SecureSocketOptions.SslOnConnect);
    client.Authenticate ("name@domain.com", "password");

    if (client.SharedNamespaces.Count > 0) {
        var sharedRoot = client.GetFolder (client.SharedNamespaces[0]);
        foreach (var sharedFolder in sharedRoot.GetSubfolders ()) {
            Console.WriteLine ("Shared folder: {0}", sharedFolder.Name);
        }
    }

    client.Disconnect (true);
}
```

**Comment by evenlee** [comment]
thanks Jstedfast, I use the code above, when debug to:
     client.Authenticate ("name@domain.com", "password");
still got the login failed error, seems the reason is I cannot login, even without the shared box.
may be caused by 2 steps authentication(RSA tokent)?

**Comment by jstedfast** [comment]
Yea, generally 2-factor authentication prevents clients from logging in to SMTP, IMAP, POP3, etc. w/o using OAuth2. I don't think Office365 supports OAuth2 yet, though (but I know they are/were working on it a few months ago).

**Comment by evenlee** [comment]
thanks, seem I cannot use meet the goal to download attachment from our email box, will find other way to fill our needs. thanks again:)

**Comment by pankajmahanta** [comment]
Hi @jstedfast , we use 3 mail box , two are as shared mailbox . all settings are in dot net core appsetting.json file . but the connection code are in library which we using as nuget package library . 
some time we  are getting authentication error . Is there any way to simplifai the code for sharedfolder mailbox .

**Comment by jstedfast** [comment]
How can I possibly simplify it?

**Comment by TimKras** [comment]
>emailClient.Authenticate("name@domain.com\\sharedmailalias", "passwordofname");

It should work with a forward slash:
[https://forum.rebex.net/4684/connecting-to-an-exchange-2010-shared-mailbox-using-imap
](url)
