### ISSUE TITLE
Pop3Client seems not to delete messages on a certain server

### ISSUE THREAD

**Issue by marekpraski** [jstedfast/MailKit#971]
hi 
I use a Pop3 email server which does not support TSL authentication and uses port 110.
In this particular case the method Pop3Client.DeleteMessage(messageIndex) seems neither to delete the message from the server nor move it to trash.
In contrast on another server (requires TSL and port 995) the method works fine.
If this helps, below are the problematic server's Capabilities:
MailKit.Net.Pop3.Pop3Capabilities.Pipelining | MailKit.Net.Pop3.Pop3Capabilities.ResponseCodes | MailKit.Net.Pop3.Pop3Capabilities.Top | MailKit.Net.Pop3.Pop3Capabilities.UIDL | MailKit.Net.Pop3.Pop3Capabilities.User.

Another external email agent (Opera Mail) manages to delete emails from the problematic server, however not quite as I would hope, ie. it deletes them permanently, rather than moving them to trash.

Any idea what the problem could be?
Marek

**Comment by jstedfast** [comment]
How are you disconnecting from the server after deleting the messages?

e.g. This will delete the messages:

```csharp
using (var client = new Pop3Client ()) {
    client.Connect ("pop.host.com", 110, false);
    client.Authenticate ("username", "password");
    for (int i = 0; i < client.Count; i++)
        client.DeleteMessage (i);

    // without this Disconnect (true) call, the messages will not get deleted
    client.Disconnect (true);
}
```

But this will not delete them:

```csharp
using (var client = new Pop3Client ()) {
    client.Connect ("pop.host.com", 110, false);
    client.Authenticate ("username", "password");
    for (int i = 0; i < client.Count; i++)
        client.DeleteMessage (i);
}
```

**Comment by marekpraski** [comment]
well, I DO disconnect the client. It is the same method I use for both servers and as I said, it works for one but does not for the other.
I was not aware of the POP3 limitation with respect to "move to trash", thanks for clarifying that. Obviously the other server supports this feature.

**Comment by jstedfast** [comment]
Try getting a protocol log w/ the problematic server. Does it send a QUIT command at the end?

**Comment by marekpraski** [comment]
hi, sorry for the trouble, there was a bug in my code. After fixing it everything works fine. Thank you
