### ISSUE TITLE
"out-of-sequence" email downloaded using POP3 protocol, does not download in IMAP

### ISSUE THREAD

**Issue by marekpraski** [jstedfast/MailKit#974]
This is more a question than a bug report.
I am getting emails both using POP3 and IMAP protocols with the following
`var message = this.emailClient.GetMessage(messageIndex);`
Then I extract date and time with 
`message.Date.LocalDateTime`
My assumption is that the older the message the smaller the message index on the server. I use this assumption to get newest messages, ie with largest indexes. This basically holds true and works fine.
However sometimes there is a glitch and when I investigated I found a message which was "out of order", like below in bold
2020-01-19 18:48:33  nr on server  2900
2020-01-18 11:50:20  nr on server  2899
**2020-01-17 13:28:37  nr on server  2898**
2020-01-17 18:44:59  nr on server  2897
2020-01-17 16:57:47  nr on server  2896
What is strange, when I entered the server directly from a browser, the date for the message was 
2020-01-18 00:31.
 I tried simple DateTime and UtcDateTime but never could get this one. 
What is even stranger, when I used IMAP protocol the message did not even download! (I did not download the whole lot, just down to 2020-01-15)
Do you have any suggestions as to what could be happening here?

**Comment by jstedfast** [comment]
Is there a Resent-Date header? If not, then the date the server is showing you is the delivery date (the Date header is the sent date). There is no header that contains the delivery date (IMAP provides this date via the INTERNAL-DATE property), but often the date will be the same as the date in the most recent Received header.

As to why you can’t download via IMAP, I have no idea unless the server is CourierIMAP in which case it’s probably because the message file on the server got set to non-readable permissions.

**Comment by marekpraski** [comment]
ResentDate property yields 0001-01-01 00:00:00 for both IMAP and POP, all messages.
I do not see the InternalDate property?

**Comment by jstedfast** [comment]
There is no InternalDate property on MimeMessage, you have to get it via the `ImapFolder.Fetch()` request by using the `MessageSummaryItems.InternalDate` flag and then checking the returned `IMessageSummary.InternalDate` property.

**Comment by marekpraski** [comment]
just for the heck of it I configured Thunderbird to POP and IMAP and guess what - it also did not retrieve this email via IMAP protocol.
As far as the InternalDate issue, I cannot get it right. What I tried was 
`DateTime date = new DateTime(2020, 1, 1, 8, 30, 52); //this would include the problematic email
 var query = SearchQuery.SentSince(date);
 var uids = emailClient.Inbox.Search(query);
 var items = emailClient.Inbox.Fetch(uids, MessageSummaryItems.UniqueId);`
but it just hangs on the third line and eventually throws System.IO.IOException and SocketException.
In debug mode.

**Comment by jstedfast** [comment]
Your code looks correct except that you would need `client.Inbox.Fetch (uids, MessageSummaryItems.UniqueId | MessageSummaryItems.InternalDate);`

The IOException is likely due to the server dropping your connection during the response, but if you can get me a [protocol log](https://github.com/jstedfast/MailKit/blob/master/FAQ.md#ProtocolLog), I'll confirm.

**Comment by marekpraski** [comment]
here is the top part of the log, together with the header of the first message. The remainder of the log looks like actual emails, but there are only a few and then there is the exception
`Connected to imaps://imap.wp.pl:993/
S: * OK IMAP4 ready
C: A00000000 CAPABILITY
S: * CAPABILITY IMAP4rev1 UIDPLUS LITERAL+ CHILDREN NAMESPACE XLIST ID IDLE MOVE XAOL-MOVE AUTH=PLAIN
S: A00000000 OK completed
C: A00000001 AUTHENTICATE PLAIN
S: + 
C: AG1hcmVrcHJhc2tpAE1hcnplbmEhKSkjV1A=
S: A00000001 OK Login completed
C: A00000002 CAPABILITY
S: * CAPABILITY IMAP4rev1 UIDPLUS LITERAL+ CHILDREN NAMESPACE XLIST ID IDLE MOVE XAOL-MOVE
S: A00000002 OK CAPABILITY completed
C: A00000003 NAMESPACE
S: * NAMESPACE (("" "/")) NIL NIL
S: A00000003 OK NAMESPACE completed
C: A00000004 LIST "" "INBOX"
S: * LIST (\Noinferiors) "/" "INBOX"
S: A00000004 OK List completed
C: A00000005 XLIST "" "*"
S: * XLIST (\Noinferiors \Drafts) "/" "Drafts"
S: * XLIST (\Noinferiors) "/" "INBOX"
S: * XLIST (\Noinferiors \Archive) "/" "INBOX/Archive"
S: * XLIST (\HasNoChildren) "/" "przeczytane"
S: * XLIST (\HasChildren) "/" "Segregator"
S: * XLIST (\HasNoChildren) "/" "Segregator/Newslettery"
S: * XLIST (\HasNoChildren) "/" "Segregator/Oferty"
S: * XLIST (\HasNoChildren) "/" "Segregator/Powiadomienia"
S: * XLIST (\HasNoChildren) "/" "Segregator/Spo&AUI-eczno&AVs-ci"
S: * XLIST (\Noinferiors \Sent) "/" "Sent"
S: * XLIST (\Noinferiors \Junk) "/" "Spam"
S: * XLIST (\Noinferiors \Trash) "/" "Trash"
S: * XLIST (\HasNoChildren) "/" "Trash_2"
S: A00000005 OK List completed
C: A00000006 EXAMINE INBOX
S: * 2909 EXISTS
S: * 0 RECENT
S: * OK [UNSEEN 2285] UIDs valid
S: * OK [UIDVALIDITY 1535123333] UIDs valid
S: * OK [UIDNEXT 9668] Predicted next UID
S: * FLAGS (\Answered \Flagged \Deleted \Seen \Draft)
S: * OK [PERMANENTFLAGS ()]
S: * OK [NOMODSEQ] Sorry, this mailbox format doesn't support modsequences
S: A00000006 OK [READ-ONLY] SELECT completed
C: A00000007 FETCH 2909 (BODY.PEEK[])
S: * 2909 FETCH (BODY[] {39494}
S: Return-Path: <no-reply@sklep.visionexpress.pl>
S: Delivered-To: marekpraski@wp.pl
S: X-WP-SR: NLJ5IQGpzU5EyEgXzA91sJYKfxDfDBBYhHrnzzr8M6kTiA==
S: Received: (wp-smtpd mx.wp.pl 22476 invoked from network); 22 Jan 2020 12:23:01 +0100
S: Received: from ip-002.s2562.net.eco.atman.pl (HELO sklep.visionexpress.pl) ([77.79.227.27])
S:           (envelope-sender <no-reply@sklep.visionexpress.pl>)
S:           by mx.wp.pl (WP-SMTPD) with SMTP
S:           for <marekpraski@wp.pl>; 22 Jan 2020 12:23:01 +0100
S: Received: by sklep.visionexpress.pl (Postfix, from userid 1000)
S: 	id 755CD60084; Wed, 22 Jan 2020 12:23:01 +0100 (CET)
S: Received: from localhost (localhost [127.0.0.1])
S: 	by sklep.visionexpress.pl (Postfix) with SMTP id 64C9F60085
S: 	for <marekpraski@wp.pl>; Wed, 22 Jan 2020 12:23:01 +0100 (CET)
S: Message-ID: <a0fd073d93bf24367539cbd16f961b32@sklep.visionexpress.pl>
S: Date: Wed, 22 Jan 2020 12:22:27 +0100
S: Subject: Sklep VE: Twoje =?utf-8?Q?zam=C3=B3wienie?= nr 2534554 (19.01.2020)
S:  =?utf-8?Q?zosta=C5=82o_wys=C5=82ane?=
S: From: Sklep Vision Express <no-reply@sklep.visionexpress.pl>
S: To: marekpraski@wp.pl
S: MIME-Version: 1.0
S: Content-Type: multipart/alternative;
S:  boundary="_=_swift_v4_1579692147_ab9b710606dd2ee0280205e5aa0c0a42_=_"
S: X-Swift-Return-Path: <no-reply@sklep.visionexpress.pl>
S: X-WP-DKIM-Status: no signature (id: n/a)                                                      
S: X-WP-MailID: 9f1c1e8b273c80d8baf597d46af38e91
S: X-WP-AV: skaner antywirusowy Poczty Wirtualnej Polski
S: X-WP-SPAM: NO (U9) 0M00010 [kVO8]                          
S: 
S: 
S: --_=_swift_v4_1579692147_ab9b710606dd2ee0280205e5aa0c0a42_=_
S: Content-Type: text/plain; charset=utf-8
S: Content-Transfer-Encoding: quoted-printable`
hope this helps

**Comment by jstedfast** [comment]
I would need to see the end of the log, but based on what you're saying, it seems to confirm my suspicions that the server isn't finishing sending a response.

**Comment by marekpraski** [comment]
the last two lines
`S: A00000016 OK Fetch completed
C: A00000017 UID SEARCH SENTON 21-Jan-2020`
I am not sure it this is enough, but the lines before that seem to belong to the preceding message. If you need the whole log it's ok, but I'd rather email it, it' approx 800kB

**Comment by jstedfast** [comment]
Ok, so the server never responds to the SEARCH query. I don't need the rest of the log.

**Comment by marekpraski** [comment]
so can I do anything about it or is this a bug?
Perhaps I could fetch the uids in some other manner, just so that I could check for the InternalDate, as you suggested?

**Comment by jstedfast** [comment]
you could do:

```csharp
emailClient.Inbox.Fetch (0, -1, MessageSummaryItems.UniqueId | MessageSummaryItems.InternalDate | MessageSummaryItems.Envelope);
```

That will fetch the INTERNALDATE for all messages.

**Comment by marekpraski** [comment]
took ages but went through. I'll analyse the data and hopefully there will be some meaningful findings. I'll let you know. Thanks for your help.

**Comment by marekpraski** [comment]
Guess what, that email is not on the list. In the meantime I have identified 3 emails like that, and none of them is in the log I created. If I only used IMAP I would never know they arrived ...

**Comment by jstedfast** [comment]
I guess that answers that question, heh.
