### ISSUE TITLE
Bug in MailService.DefaultServerCertificateValidationCallback

### ISSUE THREAD

**Issue by jeglinski** [jstedfast/MailKit#977]
**Issue**

In `MailService.DefaultServerCertificateValidationCallback` the return value is always **false** when the certificate chain is checked, e.g. if only SslPolicyErrors.RemoteCertificateChainErrors is detected.

The reason is the incorrect comparison between the certificate (of type `X509Certificate`) and the certificate in certificate chain (of type `X509Certificate2`):
 https://github.com/jstedfast/MailKit/blob/0582288e13c9ac4f04cc98e47c7d4b33d32c2f81/MailKit/MailService.cs#L324-L325

I have tested this with different certificate chains, also of different length for sending an e-mail via SMTP (with `ConnectAsync(...) `and` Connect(...)`)

The searched certificate is not found in the certificate chain, although it exists.

**My suggestion for a solution**
Replace the mentioned code with the following:
```
if (!element.Certificate.GetCertHashString().Equals(certificate.GetCertHashString(), StringComparison.OrdinalIgnoreCase))
	continue;
```
The method `X509Certificate.GetCertHashString` or `X509Certificate2.Thumbprint` both return the SHA1 hash value for the X.509v3 certificate as a hexadecimal string.

For more information see : 
https://github.com/dotnet/corefx/issues/16493
https://docs.microsoft.com/dotnet/api/system.security.cryptography.x509certificates.x509certificate.getcerthashstring
https://docs.microsoft.com/dotnet/api/system.security.cryptography.x509certificates.x509certificate2.thumbprint

**Environment**
 - OS: Windows 10 x64, Windows Server 2016
 - .NET Framework 4.7.2, .NET.Core 2.2
 - Intranet SMTP server with a self signed certificate.

**Comment by jstedfast** [comment]
Thanks

**Comment by jstedfast** [comment]
Just release MailKit 2.5.1 with this fix.
