### ISSUE TITLE
Argument 1: Cannot convert from "MimeKit.MimeMessage" to "string".

### ISSUE THREAD

**Issue by NerzOff** [jstedfast/MailKit#978]
hello, I'm trying to copy part of the text from a REGEX letter , but I have a problem. produces such an error
 Argument 1: Cannot convert from "MimeKit.MimeMessage" to "string".

```csharp
 var a = inbox.GetMessage(UID); // 
                    var rsw = new Regex("(?i)<p [^>]*?>\\s*<em[^>]*?>(.*)</em");
  string capture2 = rsw.Match(a).Groups[1].Value;
```
I do not quite understand how to fix this.

if this has nothing to do with your project, then I apologize.
thanks

**Comment by jstedfast** [comment]
The problem is that you are passing a `MimeMessage` object into `rsw.Match(a)`, but the `Match()` method takes a `string` argument, not a `MimeMessage` argument.

It looks like you are trying to use regex to match some HTML of the message body?

If so, try something more like this:

```csharp
var message = inbox.GetMessage(UID);
var htmlBody = message.HtmlBody ?? string.Empty;
var rsw = new Regex("(?i)<p [^>]*?>\\s*<em[^>]*?>(.*)</em");
string capture2 = rsw.Match(htmlBody).Groups[1].Value;
```

**Comment by NerzOff** [comment]
thank you very much
