### ISSUE TITLE
Need your guidance to add ClientCertificates using Mailkit

### ISSUE THREAD

**Issue by ANANDHASTEVE** [jstedfast/MailKit#979]
This is not an issue, I m new to Mailkit and using Mailkit for the past one week.

I dont know exactly how to  add a X509Certificate2 present in Windows personal store while connecting with smtpClient in Tsl2 using SmtpClient.ClientCertificates.Add method. 
(I have already posted this in MailKit Gitter, but didn't get a response)

The server is expecting a secure connection on port 587 in TSL1.2 with the authentication of smartcard certificate present in the store and asking me to type the pincode.

Can you point me in the right direction to acheive this.

I'm using visual studio 2017. I could acheive this using built in Windows SmtpClient but as ImapClient is missing in C#, i would like to use MailKit.

Advance Thanks and regards.

**Comment by jstedfast** [comment]
How do you do it using the Windows SmtpClient? Do it the same way with MailKit.

```csharp
client.ClientCertificates = new X509Certificate2Collection ();
client.ClientCertificates.Add (certificate);
```

**Comment by ANANDHASTEVE** [comment]
Hi Jeffrey, 

Thank you very much, 
I just resolved it before few hours. 


// this line is not needed in built-in SmptClient in Windows client . ClientCertificates = new X509Certificate2Collection (); 
// i added just this line directly client . ClientCertificates . Add ( certificate ); 
I should thank you for your prompt response and your Mailkit. 
Merci again Regards. ----- Mail original -----

De: "Jeffrey Stedfast" <notifications@github.com> 
À: "jstedfast/MailKit" <MailKit@noreply.github.com> 
Cc: "ANANDHASTEVE" <steve.anandhan@free.fr>, "Author" <author@noreply.github.com> 
Envoyé: Jeudi 23 Janvier 2020 14:46:09 
Objet: Re: [jstedfast/MailKit] Need your guidance to add ClientCertificates using Mailkit (#979) 


How do you do it using the Windows SmtpClient? Do it the same way with MailKit. 
client . ClientCertificates = new X509Certificate2Collection (); client . ClientCertificates . Add ( certificate );
