### ISSUE TITLE
MailKit.Security.AuthenticationException | The LOGIN command is disabled

### ISSUE THREAD

**Issue by MisterCookie1234** [jstedfast/MailKit#980]
Hello!
Following the Examples i tried to get a Code Snipping that would allow me to fetch specific emails and extract those + attachments 
I changed the code from one of your examples to this: https://pastebin.com/5zjAvD1G and tried running it.

"Mailkit.Security.AuthenticationException"

![grafik](https://user-images.githubusercontent.com/24813669/73650951-a4564a00-4683-11ea-893e-93cb2e97d03d.png)

Client Code: `using (var client = new ImapClient(new ProtocolLogger("imap.log")))
			{
				client.Connect("mx01.xxxxxx.net", 143, SecureSocketOptions.None);

				client.Authenticate("imaptest", "password");

				client.Inbox.Open(FolderAccess.ReadOnly);`

Protocol Log: 
Connected to imap://xxxxxxxxx:143/
S: * OK The Microsoft Exchange IMAP4 service is ready.
C: A00000000 CAPABILITY
S: * CAPABILITY IMAP4 IMAP4rev1 LOGINDISABLED STARTTLS UIDPLUS MOVE ID CHILDREN IDLE NAMESPACE LITERAL+
S: A00000000 OK CAPABILITY completed.

I am 100% sure i use the correct password and username. 
help would be appreciated

**Comment by jstedfast** [comment]
According to your log, the IMAP server reports `LOGINDISABLED` in the `CAPABILITY` response which means that the `LOGIN` command has been disabled by the server.

Typically, when the IMAP admin disables the `LOGIN` command, they will enable a SASL authentication mechanism that the client can use instead, but in this case, no SASL authentication mechanisms are listed in the `CAPABILITY` response.

Another possibility is that the admin has disabled the `LOGIN` command because they want to force users to use an SSL connection instead on port 993.

Try changing your connection code to this:

```csharp
client.Connect("mx01.xxxxxx.net", 993, SecureSocketOptions.SslOnConnect);
```

**Comment by MisterCookie1234** [comment]
Hey!
We already tried this and we get an SSL Cert Error, although our Exchange Server is configured right.
I indeed even tried your IMAPClientDemo on the same Port with the same creditionals which DOES work (without SSL) so we were wondering where the login command would be disabled. We searched everywhere in our Exchange and did not find it.

**Comment by amudhauday09** [comment]
Free Cholestrol reductions

CEO
SRAMS Inc

**Comment by jstedfast** [comment]
The SSL certificate error does not necessarily mean that your server's SSL configuration or certificate is invalid, it just means that the client can't validate the server's certificate.

This often means that the client's machine does not have a copy of (or does not trust) the Root CA certificate that signed the IMAP server's certificate.

As a temporary work-around, you can do this:

```csharp
client.ServerCertificateValidationCallback = (s,c,h,e) => true;
client.Connect("mx01.xxxxxx.net", 993, SecureSocketOptions.SslOnConnect);
```

The ImapClient.ServerCertificateValidationCallback function allows you to do your own server certificate validation in cases where the client itself is unable to validate the certificate itself.

The example above sets this function to always return true that the certificate is valid.

At some point what you will need to do is either install/trust the Root CA certificate that you used to sign your IMAP server certificate -or- you'll need to write your own ServerCertificateValidationCallback function that will verify that the IMAP server's certificate provided to that function is accurate. One way to do this is to verify that the certificate's Issuer and SerialNumber match the expected values.

**Comment by MisterCookie1234** [comment]
Ahh.. Hmm i will try that, whenever i get back to work tomorrow!
If this won't solve the problem, what else could?
You said something about login command.. we own a exchange 2013 servers.. where would you enable or disable that?

**Comment by jstedfast** [comment]
I've never been an admin for any version of Exchange, so I don't know.

**Comment by MisterCookie1234** [comment]
this seems to work! Nice!
But now.. everytime i try to run it i get 

> Value cannot be null.

in this line: var body = (TextPart) client.Inbox.GetBodyPart (item.UniqueId, bodyPart);
Looking into the folder, it already created a folder with the uid, but isnt able to save the message in it.
Any Ideas why?

Greetings

**Comment by jstedfast** [comment]
Yea,

```csharp
// IMessageSummary.TextBody is a convenience property that finds the 'text/plain' body part for us
var bodyPart = item.TextBody;
```

Not all messages have a text/plain body part. In fact, in your screen shot, *none* of them have a text/plain part - they only seem to have text/html parts.

> Looking into the folder, it already created a folder with the uid.
> Any Ideas why?

Well, yea, because you created it before you tried to download the message body.

**Comment by MisterCookie1234** [comment]
Okay... And how would i implement a code that tries to fetch text/plan body parts and if those are 0, would try to fetch text/html parts?

**Comment by jstedfast** [comment]
```csharp
var bodyPart = item.TextBody ?? item.HtmlBody;

if (bodyPart != null) {
    // download part
}
```

NullReferenceException means that you are dereferencing a null object in your code - probably `part` is null.

**Comment by MisterCookie1234** [comment]
Ah yeah prob because there were no attachment.

**Comment by MisterCookie1234** [comment]
Well thank you very much! First Step done i guess..
Now i need to figure out how to get variables like "password, user, server..." etc. out of a config file and how to move the downloaded files into their correct locations (which, i asumme, might be a bit tricky since everytime you get a new email the folder is named after the uid)

**Comment by MisterCookie1234** [comment]
Okay i just got one more question:
After Downloading Emails, i would need to move them out of the inbox folder, so that they dont get fetched again when i rerun the script. How would i, for example, move every fetched message at the end from inbox to for example "test", so it wont get recognized again?

**Comment by jstedfast** [comment]
Why not just check if the UID folder exists and if it does, you know you have the info?

**Comment by jstedfast** [comment]
Look at the [MoveTo](http://www.mimekit.net/docs/html/Overload_MailKit_MailFolder_MoveTo.htm) method if you want to move messages to another folder.

**Comment by MisterCookie1234** [comment]
Because the UID Folders would/should get deleted at the end, since i need to move the Files to other locations and folders aswell, so the main download folder is just temporary.

**Comment by jstedfast** [comment]
Another approach would be to keep a file of all of the uids you've downloaded.

**Comment by MisterCookie1234** [comment]
Hmm.. Interesting Approach..
Since i would like to move all variables like username, password etc to a config file, so every user could easily change them without the need of editing the code, it might be an good approach aswell to save all uids in a file.. mhh

**Comment by MisterCookie1234** [comment]
Hmm i dont know how to get MoveTo() to work :/
Since i am a bloody beginner, its really confusing.. i figured out with
					

> var personal = client.GetFolder(client.PersonalNamespaces[0]); personal.Create("Kassendaten", true);

i could create a new Folder, if it does not exist. On the same side i figured, the best way to place the move to function would be below 

> foreach (var item in items)

since beforehand they already got fetched and a uniqueID.. but how would i now move the already fetched messages with the known uids to the new folder?

**Comment by MisterCookie1234** [comment]
Hey!
In my try of moving the emails in another folder using moveto, i came across another error.. which seems weird to me. 

I test if the folder exists, otherwise i just create it. 

` var topLevelFolder = client.GetFolder(client.PersonalNamespaces[0]);
                    var topFolders = topLevelFolder.GetSubfolders();
                    var folderKassendaten = topFolders.FirstOrDefault(folder => folder.Name == "Kassendaten");
                    if (folderKassendaten == null)
                        folderKassendaten = topLevelFolder.Create("Kassendaten", true);`

after that i gave ReadWrite Access
`					folderKassendaten.Open(FolderAccess.ReadWrite);`
til i finally move the emails to the newly created folder.. well.. i would.
`					client.Inbox.MoveTo(item.UniqueId, folderKassendaten);`

In Visual i always get the message "The folder is not currently open in read-write mode."
Where this 
![grafik](https://user-images.githubusercontent.com/24813669/73835780-4bff8380-480e-11ea-9cbe-1efe6b2d298a.png) and this 
![grafik](https://user-images.githubusercontent.com/24813669/73835808-53269180-480e-11ea-86b5-9e8a721dddef.png) show, that there actually IS Read and Write Access.. sooo
I dont know what to do
