### ISSUE TITLE
Idn-Mapped Username

### ISSUE THREAD

**Issue by lorenzwinkler1** [jstedfast/MailKit#982]
**Is your feature request related to a problem? Please describe.**
Hello, today it took me some hours to get a simple smtp connection working. 
The problem turned out to be, that my username was an email which included characters that needed to be Idn-Mapped.
So my credentials were:

```
username: "example@bücher.com" (changed the domain because of privacy reasons)
password: "<somepassword>"
```

The login just failed. After using c#'s System.Globalization.IdnMapping class i got this finally working.
My new credentials then were:
```
username: "example@xn--bcher-kva.com"
password: "<somepassword>"
```
which worked.
**Describe the solution you'd like**
I am not sure if it is common sense for people which are more familiar with smtp than i am and thus a "fix" or "enhancement" is not needed, but i would suggest converting usernames to idn-format. A code snippet for that would be:

``` c#
   int indexofat = emailaddr.LastIndexOf('@');
   string idnmappedurl = emailaddr.Substring(0, indexofat+1) + new IdnMapping().GetAscii(emailaddr.Substring(indexofat + 1));
```

**Describe alternatives you've considered**

The alternative solution would be, to just let the developer do it.

**Additional context**

I have not checked, if the problem occured on for example the host-domain, since i do not know an smtp server which has non-ascii-characters in it. But it might be the case and should be checked if possible

Fun Fact: Windows mail also fails at connecting to this domain, but also works with Idn-Mapped url.

**Comment by jstedfast** [comment]
I don't think that I can safely do this w/o risking breaking for other users who's server does *not* want them to IDN-map their account names.

I understand that this was frustrating for you, but there's no standard that calls for account names to be IDN-mapped which means that doing this will not work for all SMTP/POP3/IMAP servers.
