### ISSUE TITLE
Search does not work

### ISSUE THREAD

**Issue by pengpengker** [jstedfast/MailKit#983]
**Describe the bug**
When I use search to find messages, it doesn't work！

**To Reproduce**

**Expected behavior**
I need to search for matching strings in the body of the message

**Screenshots**
![image](https://user-images.githubusercontent.com/50614901/74129497-ac316380-4c1a-11ea-8309-3ca5bdb834c3.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] windows 10 64
 - Browser [e.g. chrome, safari]  chrome
 - Version [e.g. 22] No

**Smartphone (please complete the following information):**

**Additional context**
My email contains the title 123, and I can get the result by using the loop, as shown in the following figure。
![image](https://user-images.githubusercontent.com/50614901/74129952-d2a3ce80-4c1b-11ea-8ad6-ecc938cafb16.png)

Obviously, my title contains 123456, but the search return is indeed empty, not found。
I think there's something wrong with my code。

Code I use：
`using (var client = new ImapClient(new ProtocolLogger("imap.log")))
            {
                // For demo-purposes, accept all SSL certificates
                client.ServerCertificateValidationCallback = (s, c, h, e) => true;

                client.Connect("imap.163.com", 993, true);

                client.Authenticate("pengpengker9@163.com", "baicaishishagou2");

                Imaps imaps = new Imaps();
                if (imaps.HasImapCapabilitiesIds(client.Capabilities, ImapCapabilities.Id))
                {
                    var clientImplementation = new ImapImplementation
                    {
                        Name = "dddddd",
                        Version = "2.0"
                    };
                    var serverImplementation = client.Identify(clientImplementation);
                }
                
                var inbox = client.Inbox;
                inbox.Open(FolderAccess.ReadOnly);

                var query = SearchQuery.SubjectContains("1").Or(SearchQuery.BodyContains("1"));

                var uids = inbox.Search(query);

                Console.WriteLine("Total messages: {0}", inbox.Count);
                Console.WriteLine("Recent messages: {0}", inbox.Recent);

                for (int i = 0; i < inbox.Count; i++)
                {
                    var message = inbox.GetMessage(i);
                    Console.WriteLine("Subject: {0}", message.Subject);
                }

                client.Disconnect(true);
            }`

imap.log：
Connected to imaps://imap.163.com:993/
S: * OK Coremail System IMap Server Ready(163com[10774b260cc7a37d26d71b52404dcf5c])
C: A00000000 CAPABILITY
S: * CAPABILITY IMAP4rev1 XLIST SPECIAL-USE ID LITERAL+ STARTTLS XAPPLEPUSHSERVICE UIDPLUS X-CM-EXT-1
S: A00000000 OK CAPABILITY completed
C: A00000001 LOGIN pengpengker9@163.com baicaishishagou1
S: A00000001 OK LOGIN completed
C: A00000002 CAPABILITY
S: * CAPABILITY IMAP4rev1 XLIST SPECIAL-USE ID LITERAL+ STARTTLS XAPPLEPUSHSERVICE UIDPLUS X-CM-EXT-1
S: A00000002 OK CAPABILITY completed
C: A00000003 LIST "" ""
S: * LIST (\Noselect) "/" ""
S: A00000003 OK LIST Completed
C: A00000004 LIST "" "INBOX"
S: * LIST () "/" "INBOX"
S: A00000004 OK LIST Completed
C: A00000005 LIST (SPECIAL-USE) "" "*"
S: * LIST (\Drafts) "/" "&g0l6P3ux-"
S: * LIST (\Sent) "/" "&XfJT0ZAB-"
S: * LIST (\Trash) "/" "&XfJSIJZk-"
S: * LIST (\Junk) "/" "&V4NXPpCuTvY-"
S: A00000005 OK LIST Completed
C: A00000006 ID ("name" "dddddd" "version" "2.0")
S: * ID ("name" "Coremail Imap" "vendor" "Mailtech" "TransID" "da3BbwAneHSsCEFe")
S: A00000006 OK ID completed
C: A00000007 EXAMINE INBOX
S: * 3 EXISTS
S: * 1 RECENT
S: * OK [UIDVALIDITY 1] UIDs valid
S: * FLAGS (\Answered \Seen \Deleted \Draft \Flagged)
S: * OK [PERMANENTFLAGS (\Answered \Seen \Deleted \Draft \Flagged)] Limited
S: A00000007 OK [READ-ONLY] Examine completed
C: A00000008 UID SEARCH OR SUBJECT 1 BODY 1
S: * SEARCH
S: A00000008 OK SEARCH completed

**Comment by jstedfast** [comment]
This is the relevant piece of the log:

```
C: A00000008 UID SEARCH OR SUBJECT 1 BODY 1
S: * SEARCH
S: A00000008 OK SEARCH completed
```

This shows that MailKit is sending your query verbatim to the server (as it should), but the server replies that there are no matches.

This is a server bug.

**Comment by pengpengker** [comment]
Thank you for your help, but I'd like to ask an extra question

Now many do not support search. Is there any other way to replace search?

Thank

**Comment by jstedfast** [comment]
Well, if you can accept only searching the envelope headers (from, reply-to, to, cc, bcc, message-id, in-reply-to, subject, date, etc), then you could query for all ENVELOPEs and manually search those:

```csharp
var matched = new UniqueIdSet ();
foreach (var message in folder.Fetch (0, -1, MessageSummaryItems.UniqueId | MessageSummaryItems.Envelope)) {
    if (message.Envelope.Subject != null && message.Envelope.Subject.Contains ("1")) {
        matched.Add (message.UniqueId);
    }
}
```
