### ISSUE TITLE
How to get the uniqueID of a message？

### ISSUE THREAD

**Issue by pengpengker** [jstedfast/MailKit#984]
**Is your feature request related to a problem? Please describe.**
I have used inbox.getmessage (1) to get message information, but I can't find the one to get uniqueID。

**Describe the solution you'd like**
var message = Inbox.GetMessage(1);
string subject = message.Subject; //Subject

How to get uniqueID next？
I need to get this uniqueID for setflags。
But the uniqueID cannot be obtained by using GetMessage。

**Describe alternatives you've considered**

**Additional context**

**Comment by jstedfast** [comment]
You can actually set flags using message indexes as well, but yes, it is better to use unique id's.

To get all of the UniqueIDs in a folder, you can do this:

```csharp
var uids = inbox.Search (SearchQuery.All);
```

You can then use those UIDs to get the messages:

```csharp
foreach (var uid in uids) {
    var message = inbox.GetMessage (uid);
}
```

Another way to get the UIDs is to ask the folder for the metadata for a set of messages (or, in the example below, *all* of the messages):

```csharp
var summaries = inbox.Fetch (0, -1, MessageSummaryItems.UniqueId | MessageSummaryItems.Envelope | MessageSummaryItems.Flags);
foreach (var summary in summaries) {
    // now you can use summary.UniqueId and any other field that you requested in the Fetch()
    // request such as summary.Envelope. You can also use summary.Index which is *always* set.
   Console.WriteLine ("Message[{0}] has UID={1} and Subject=\"{2}\" and currently has the following flags set: {3}", summary.Index, summary.UniqueId, summary.Envelope.Subject, summary.Flags.Value); 
}
```

In essence, you don't get a UID from a message, you use a UID to *refer* to a message.

Hope that helps.

**Comment by pengpengker** [comment]
Thank You!
It is very Good!!!
