### ISSUE TITLE
How bad could it be not calling ImapClient.Disconnect

### ISSUE THREAD

**Issue by JuanDavidPaez** [jstedfast/MailKit#988]
I am using Mailkit in a **Web.Api** application to retrieve mails using ImapClient. I used to connect and disconnect the ImapClient on every API call. However it turns to be very slow, so I decided not to disconnect the client and keep a reference to it storing it in **MemoryCache** and use it on every API call.

On every API call I am checking if the client is connected and authenticated, if not then connect and authenticate.

```
if (!client.IsConnected)
{
	client.Connect(imapConfig.Server, imapConfig.Port, imapConfig.SSL);
}
if (!client.IsAuthenticated)
{
	client.Authenticate(imapConfig.User, imapConfig.Password);
}
````

I already test it and it works, however I am never calling **ImapClient.Disconnect**. I am thinking on calling disconnect at the very moment the user close or leave the web page, however I think it could happens that for any reason this event never fires causing that the API never calls Disconnect.
Also, **MemoryCache** could evict the client reference so that a new API call would have to create a new one stablishing a new connection, but the old reference could not be disconnected properly.

How bad could it be if my application never calls **ImapClient.Disconnect**? Could it lead to an eventual memory issues error or maybe run out of machine available sockets or connections?

Which other approach should I use instead of MemoryCache, to improve speed on IMAP operations.

Thanks

**Comment by jstedfast** [comment]
What you're doing is fine, but I would disconnect the client when the user closes or leaves the page so that you free up the socket if it's still active.

I've never written any ASP.NET web apps, so I can't help you beyond that because I'm not very familiar with how they work.
