### ISSUE TITLE
Some new Questions

### ISSUE THREAD

**Issue by MisterCookie1234** [jstedfast/MailKit#990]
Hello!
We are testing a script running with your Mailkit for quite a while now and came upon some questions following up on this Thread: https://github.com/jstedfast/MailKit/issues/980

We are currently running the Script everyday, but added that its running a batch script at the end.
We tried removing it, but weirdly enough it couldn't iterate through all the emails anymore, moved only part of them and downloaded part of them.. with the batch script at the end, it iterates through all of them, tell running the batch script with a little "successfull" message (We dont mind the batch script but its still weird)

Now we came upon some questions:
- Since the Mails incoming are quite important, it would be nice to have a warning, whenever a mail didn't arrive. So for example if we run this script at like 1 pm every day - whenever it CAN find a email and move it + download attachement = do it - whenever it CAN'T find a email, send a warning email containing a custom text to a specific email. Is that possible? If so, how? What do i have to change in the script (Referring to the other Thread)

- How can i let the script delete a folder at the end IF, big IF, the title contains for example "Taxes"? I guess on kinda the same way i run the batch script at the end? How?

- Is it possible to not only check for a specific title of the email but also for a specific sender? So it only goes for this specific email if its from spongebob@squarepants.fantasy ? How?

- Is it possible to check for the attachement ending (.xml .dat) and save it exactly like that, without changing the ending at all? How?

Greetings!

**Comment by jstedfast** [comment]
I don't understand where the batch script fits into what you are doing with MailKit. I'm so confused. Are you running a batch script from within your .NET program? Or does the batch script run your .NET program?

1. What do you mean you'd like a warning about a mail not arriving? This seems like it should be in your code, no?
2. If you are already downloading the messages, then if `message.Subject.Contains ("Taxes")`, use the `UniqueId` that you used to download the message to mark it as deleted on the server using `folder.AddFlags (uid, MessageFlags.Deleted, true)` and then call `folder.Expunge()` when you are finished processing all of your messages.
3. `if (message.From.Mailboxes.Any (mailbox => mailbox.Address.Equals ("spongebob@squarepants.fantasy", StringComparison.OrdinalIgnoreCase)))`
4. https://github.com/jstedfast/MailKit/blob/master/FAQ.md#SaveAttachments

**Comment by jstedfast** [comment]
Oh, I see, you are not downloading the full messages, you are using the Fetch() method to obtain the BodyStructure and the UniqueId.

Add `MessageSummaryItems.Envelope` to the items you want to get:

```csharp
folder.Fetch (0, -1, MessageSummaryItems.UniqueId | MessageSummaryItems.Envelope | MessageSummaryItems.BodyStructure);
```

And then you can use the `summary.Envelope` property to see the common message headers like From, To, Cc, Subject, Date, etc.

so:

```csharp
if (item.Envelope.Subject.Contains ("Taxes")) {
    folder.AddFlags (item.UniqueId, MessageFlags.Deleted, true);
}
```

But, if you can, I would recommend batching your delete requests:

```csharp
var deleteTheseUids = new UniqueIdSet ();
foreach (var item in summaries) {
    // do what you are already doing and then:
    if (item.Envelope.Subject.Contains ("Taxes") && item.Envelope.From.Mailboxes.Any (mailbox => mailbox.Address.Equals ("spongebob@...", StringComparison.OrdinalIgnoreCase))
        deleteTheseUids.Add (item.UniqueId);
}

if (deleteTheseUids.Count > 0) {
    folder.AddFlags (deleteTheseUids, MessageFlags.Deleted, true);
    folder.Expunge ();
}
```

**Comment by MisterCookie1234** [comment]
Good Morning.
This is my current Code im reffering to: https://pastebin.com/RMZY53ut
1. Sometimes Mails dont arrive on our end due to errors from our firewall or something else.
The Code is running to automate them fully and downloading everything to a specific folder on a client server. Since we cant always check if all mail arrived, it would be nice to get a warning if by any chance whenever the script runs it doesn't find any emails to move/download whatever. So we get a notification telling us, that something went wrong and we have to contact our clients, so that they send us the emails again. 

2. I think you are referring to an email folder while i was referring to a windows folder? Not sure tho.
We get an email with taxes every thursday. To start the processing of the downloaded files we need to delete an folder called "Ready" 

3. Will try that as soon as i get back to coding within the next days/week

4. Thank you

+ Forget what i was saying about the batch script.. i removed it without even knowing it and it still works 🤷‍♂

**Comment by jstedfast** [comment]
1. I don't know how it would even be possible to detect the situation you are describing.
2. Yes, I thought you meant you wanted to delete the message from the IMAP folder. To delete it from a folder on your hard drive, just use System.IO.File.Delete().

**Comment by MisterCookie1234** [comment]
Mhhh... Since the Mailkit checks for emails containing a title like "Taxes"..
what if it doesnt find atleast one email containing it? Is there no way to actually say "if you cant find title xy send email to ahhfj@rhrh.de, otherwise iterate through the message and do the normal procedure?

**Comment by jstedfast** [comment]
You should have explained that that's what you wanted from the get-go. Yes, obviously that's possible.

Just count the number of matches you find and if you find 0, then send an email.

**Comment by MisterCookie1234** [comment]
Yea sorry lmao, sometimes i can't explain what i want.

How would i implement such? Sorry for my questions but i am not that good at coding and this is my first project ever.

**Comment by jstedfast** [comment]
```csharp
var items = folder.Fetch (uids, MessageSummaryItems.UniqueId | MessageSummaryItems.Envelope | MessageSummaryItems.BodyStructure);
int matched = 0;

foreach (var item in items) {
    // do what you are already doing and then:
    if (item.Envelope.Subject.Contains ("Taxes") && item.Envelope.From.Mailboxes.Any (mailbox => mailbox.Address.Equals ("spongebob@...", StringComparison.OrdinalIgnoreCase))
        matched++;
}

if (matched == 0) {
    // send an email
    var message = new MimeMessage ();
    message.From.Add (new MailboxAddress ("Your Name", "your@email.com"));
    message.To.Add (new MailboxAddress ("Recipient Name", "recipient@email.com"));
    message.Subject = "Didn't find any messages with Taxes in the subject!";
    message.Body = new TextPart ("plain") {
        Text = "Didn't find any messages!"
    };

    using (var smtp = new SmtpClient ()) {
        smtp.Connect ("smtp.server.com", 25, SecureSocketOptions.Auto);
        smtp.Authenticate ("username", "password");
        smtp.Send (message);
        smtp.Disconnect (true);
    }
}
```

**Comment by MisterCookie1234** [comment]
I'm not sure where i would implement it.

I got this Part 	

```
// search for messages where the Subject header contains either "Kassendaten" or "Test"
				var query = SearchQuery.SubjectContains(subject).Or(SearchQuery.SubjectContains(subject2));
				var uids = client.Inbox.Search(query);

				// fetch summary information for the search results (we will want the UID and the BODYSTRUCTURE
				// of each message so that we can extract the text body and the attachments)
				var items = client.Inbox.Fetch(uids, MessageSummaryItems.UniqueId | MessageSummaryItems.BodyStructure);
```

where i search for the title. Do i need to change 

`var items = client.Inbox.Fetch(uids, MessageSummaryItems.UniqueId | MessageSummaryItems.BodyStructure); ` ```
to var items = folder.Fetch (uids, MessageSummaryItems.UniqueId | MessageSummaryItems.Envelope | MessageSummaryItems.BodyStructure);
int matched = 0;
```
or how exactly would i implement your code snippets?

Deleting the System Folder is quite Clear, but its not clear where i have to change/paste your other code snippets in - Sorry.

**Comment by jstedfast** [comment]
Yes, you would update the Fetch() request.

**Comment by MisterCookie1234** [comment]
Like this? https://pastebin.com/v5ubxGvz
Or did i do it wrong? (I tried adding your code)
im also getting 2 errors so i believe i did it wrong (one that using directive for smtpClient is missing and second that its missing a ) at line 67.. but i believe i just implemented it wrong

**Comment by jstedfast** [comment]
Add `using MailKit.Net.Smtp;` to the top.

**Comment by MisterCookie1234** [comment]
Added, but my question if i did it right or completly fucked up remains.
Would be lovely if u could take a look at the pastebin

**Comment by jstedfast** [comment]
I'll try to look when I've got some spare time. As a quick look, you need to move the sending email logic out of the loop, otherwise it's pointless.

**Comment by MisterCookie1234** [comment]
Alright.. this is my last version: https://pastebin.com/FXyWDqDv
Im still very sure i am doing it wrong because at one point i got 
`var query = SearchQuery.SubjectContains(subject).Or(SearchQuery.SubjectContains(subject2));
				var uids = client.Inbox.Search(query);`
and at the other point i got
`if (item.Envelope.Subject.Contains("Taxes") && item.Envelope.From.Mailboxes.Any(mailbox => mailbox.Address.Equals("spongebob@...", StringComparison.OrdinalIgnoreCase))
						matched++;`
but i geniunly dont know it any better.

It would be really great if, when you got some spare time, you could analyize what i do wrong and how i have to change it to get it right.

**Comment by MisterCookie1234** [comment]
Did you find some time to take a look?

**Comment by jstedfast** [comment]
Something more like this:

```csharp
using System;
using System.Collections;
using System.Collections.Generic;
using System.IO;
using MimeKit;
using MailKit;
using MailKit.Search;
using MailKit.Security;
using MailKit.Net.Imap;
using System.Linq;
using System.Configuration;
using System.Collections.Specialized;
using System.Diagnostics;
using MailKit.Net.Smtp;

namespace MailKit.Examples
{
    public static class ImapExamples
    {
        #region DownloadBodyParts
        public static void Main(string[] args)
        {
            int matched = 0;

            using (var client = new ImapClient(new ProtocolLogger("imap.log")))
            {
                // Variablen aus der Config abrufen
                var username = ConfigurationManager.AppSettings["username"];
                var password = ConfigurationManager.AppSettings["password"];
                var server = ConfigurationManager.AppSettings["server"];
                var subject = ConfigurationManager.AppSettings["subject"];
                var subject2 = ConfigurationManager.AppSettings["subject2"];
                var savedir = ConfigurationManager.AppSettings["savedir"];
                var file_extension = ConfigurationManager.AppSettings["fileext"];
                var attachement_extension = ConfigurationManager.AppSettings["fileext"];
                var outlookfolder = ConfigurationManager.AppSettings["outlookfolder"];
                var batchfilepath = ConfigurationManager.AppSettings["batchfilepath"];

                // Mit dem Server verbinden
                client.ServerCertificateValidationCallback = (s, c, h, e) => true;
                client.Connect(server, 993, SecureSocketOptions.SslOnConnect);

                client.Authenticate(username, password);

                var topLevelFolder = client.GetFolder (client.PersonalNamespaces[0]);
                var topFolders = topLevelFolder.GetSubfolders ();
                var folderKassendaten = topFolders.FirstOrDefault (folder => folder.Name == outlookfolder);
                if (folderKassendaten == null)
                    folderKassendaten = topLevelFolder.Create (outlookfolder, true);

                client.Inbox.Open(FolderAccess.ReadWrite);

                // search for messages where the Subject header contains either "Kassendaten" or "Test"
                var query = SearchQuery.SubjectContains(subject).Or(SearchQuery.SubjectContains(subject2));
                var uids = client.Inbox.Search(query);

                // fetch summary information for the search results (we will want the UID and the BODYSTRUCTURE
                // of each message so that we can extract the text body and the attachments)
                var items = client.Inbox.Fetch(uids, MessageSummaryItems.UniqueId | MessageSummaryItems.Envelope | MessageSummaryItems.BodyStructure);

                //determine baseDirectory
                string baseDirectory = savedir;
                foreach (var item in items) {
                    // determine a directory to save stuff in
                    var directory = Path.Combine (baseDirectory);

                    // create the directory
                    Directory.CreateDirectory (directory);

                    // IMessageSummary.TextBody is a convenience property that finds the 'text/plain' body part for us
                    var bodyPart = item.TextBody ?? item.HtmlBody;

                    if (bodyPart != null) {
                        // download part
                    }

                    // download the 'text/plain' body part
                    var body = (TextPart) client.Inbox.GetBodyPart (item.UniqueId, bodyPart);

                    // TextPart.Text is a convenience property that decodes the content and converts the result to
                    // a string for us
                    var text = body.Text;

                    // now iterate over all of the attachments and save them to disk
                    foreach (var attachment in item.Attachments) {
                        // download the attachment just like we did with the body
                        var entity = client.Inbox.GetBodyPart (item.UniqueId, attachment);

                        // attachments can be either message/rfc822 parts or regular MIME parts
                        if (entity is MessagePart) {
                            var rfc822 = (MessagePart) entity;

                            var path = Path.Combine (directory, attachment.PartSpecifier + attachement_extension);

                            rfc822.Message.WriteTo (path);
                        } else {
                            var part = (MimePart) entity;

                            // note: it's possible for this to be null, but most will specify a filename
                            var fileName = part.FileName;

                            var path = Path.Combine (directory, fileName);

                            // decode and save the content to a file
                            using (var stream = File.Create (path))
                                part.Content.DecodeTo (stream);
                        }

                        if (item.Envelope.Subject.Contains ("Taxes") && item.Envelope.From.Mailboxes.Any (mailbox => mailbox.Address.Equals ("spongebob@...", StringComparison.OrdinalIgnoreCase)))
                            matched++;
                    }

                    client.Inbox.MoveTo (item.UniqueId, folderKassendaten);
                }

                client.Disconnect(true);
            }

            if (matched == 0) {
                // send an email
                var message = new MimeMessage ();
                message.From.Add (new MailboxAddress ("Your Name", "your@email.com"));
                message.To.Add (new MailboxAddress ("Recipient Name", "recipient@email.com"));
                message.Subject = "Didn't find any messages with Taxes in the subject!";
                message.Body = new TextPart ("plain") {
                    Text = "Didn't find any messages!"
                };

                using (var smtp = new SmtpClient ()) {
                    smtp.Connect ("smtp.server.com", 25, SecureSocketOptions.Auto);
                    smtp.Authenticate ("username", "password");
                    smtp.Send (message);
                    smtp.Disconnect (true);
                }
            }
        }
        #endregion
    }
}
```

**Comment by MisterCookie1234** [comment]
Thank you very much. Just have to figure out how to enable smtp on our server because we get the error "Service not avaiable" but im sure its just one setting to find

**Comment by MisterCookie1234** [comment]
Okay after we managed to get smtp working i came down to a problem.
It seems like that your code isn't working properly. Even tho he does find emails containing (for Example) taxes from spongebob@email.com he would still send me the email telling me he didn't.

**Comment by MisterCookie1234** [comment]
Can i add the part where you check if the mail is from spongebob@email.com to this aswell? 

` var query = SearchQuery.SubjectContains(subject).Or(SearchQuery.SubjectContains(subject2));`

And the code isn't working properly.. Even tho he does find the emails containing the subject he is looking for, he wouldnt increase the matching number, therefore he would always assume he found 0 and send me the mail.

**Comment by jstedfast** [comment]
Yes, you can add the subject matching to the search query if that's what you want to do.

**Comment by MisterCookie1234** [comment]
Umm.. 

I would like to add a check if the mail is from xy@email.com like here
` if (item.Envelope.Subject.Contains ("Taxes") && item.Envelope.From.Mailboxes.Any (mailbox => mailbox.Address.Equals ("spongebob@...", StringComparison.OrdinalIgnoreCase)))
                            matched++;`
to 
`var query = SearchQuery.SubjectContains(subject).Or(SearchQuery.SubjectContains(subject2))`

and still.. i tried loads of different ways but i can't get your code to work properly. Like explained before even if he does find some emails with like "Taxes" from "spongebob@email.com" he wouldnt increase the matched number, so therefore always sending me the email telling me he couldnt find anything.

**Comment by jstedfast** [comment]
You can use [SearchQuery.FromContains](http://www.mimekit.net/docs/html/M_MailKit_Search_SearchQuery_FromContains.htm) - it works just like SubjectContains.

My free time is valuable and I've spent a lot of my free time responding to your questions which eats up time I could be spending on other things.

To give you an idea, I'm currently working on obtaining tools and other supplies that I will need in order to get into recreating some early American history and, unfortunately, this is a very expensive endeavor. In the end, I expect it to cost me at least $2000 and maybe as much as $3000.

A sizable donation by you would go a long way toward helping me to achieve my own goals.

Want to help me out in return for my help? I think $500 would be fair for the time I'll probably need to spend to help you figure out how to get your program working the way you want it to.

**Comment by MisterCookie1234** [comment]
Sorry to bother you.
I know your free time is very valueable. 

As far as i would love to help you out with even more than just $500, i am concerned i am not able to. I am currently working for my first year after i left school in Germany in a i vocational training, therefore i dont get much money. Its most likely just enough to pay for my car. I learned a lot through the Mailkit and with your help. So thank you very much. 

As for my problem is assume i will need to ask someone else. I dont want to take your freetime, if you are working on such valueable tasks. It can't be that hard to find a solution i guess.
