### ISSUE TITLE
Expected usage of Pop3Client

### ISSUE THREAD

**Issue by apatenotre** [jstedfast/MailKit#996]
Hi there,

I am currently implementing a mail client dedicated to Pop, and especially trying to reproduce a behavior functionally identical to the `ImapIdleExample`.

My first implementation, simplified, was as follows:

```csharp
// Connect and authenticate
await _client.ConnectAsync(_parameters.Server, _parameters.Port, false).ConfigureAwait(false);
await _client.AuthenticateAsync(_parameters.Login, _parameters.Password).ConfigureAwait(false);

// Loop until application closes
while (!_masterToken.IsCancellationRequested)
{
	var count = await _client.GetMessageCountAsync(_masterToken.Token).ConfigureAwait(false);
	var uids = await _client.GetMessageUidsAsync(_masterToken.Token).ConfigureAwait(false);
	
	for (var i = count - 1; i >= 0; i--)
	{
		//check that we haven't already downloaded this message
		// in a previous session
		if (__kownUids.Contains(uids[i]))
		{
			continue;
		}

		var message = await _client.GetMessageAsync(i, _masterToken.Token).ConfigureAwait(false);

		_knownUids.Add(uids[i]);

		// process incoming mail
	}

	// Wait 60s before checking if new messages arrived
	await Task.Delay(60000, _masterToken.Token).ConfigureAwait(false);
}

// Disconnect and leave
await _client.DisconnectAsync(true).ConfigureAwait(false);
```

However I did notice that `GetMessageCountAsync` and `GetMessageUidsAsync` always return the same count and Uids, even in case new mails arrived. I absolutely need to disconnect an connect again.

So I ended up implementing it as follows:
```csharp
 while (!_masterToken.IsCancellationRequested)
{
	// Reconnect at each loop as otherwise, for an unknown reason, server doesn't send an updated count and list of uids
	await _client.ConnectAsync(_parameters.Server, _parameters.Port, false).ConfigureAwait(false);
	await _client.AuthenticateAsync(_parameters.Login, _parameters.Password).ConfigureAwait(false);

	var count = await _client.GetMessageCountAsync(_masterToken.Token).ConfigureAwait(false);
	var uids = await _client.GetMessageUidsAsync(_masterToken.Token).ConfigureAwait(false);
	
	for (var i = count - 1; i >= 0; i--)
	{
		//check that we haven't already downloaded this message
		// in a previous session
		if (_knownUids.Contains(uids[i]))
		{
			continue;
		}

		var message = await _client.GetMessageAsync(i, _masterToken.Token).ConfigureAwait(false);

		_knownUids.Add(uids[i]);

		// process incoming mail
	}

	await _client.DisconnectAsync(true).ConfigureAwait(false);

	// Wait 60s before checking if new messages arrived
	await Task.Delay(60000, _masterToken.Token).ConfigureAwait(false);
}
```
That doesn't look optimal to me at all, so my questions are:
* which implementation is supposed to be the right one ?
* if the first one is correct from a design point of view, am I missing something ?
* I did my tests againts a single POP server. Is it possible that the issue is on server side, due to an implementation detail ?

Many thanks for your insight

**Comment by jstedfast** [comment]
Probably a bug in the server. GetMessageCountAsync() sends a `STAT` command to get the latest message count info, so the server must be returning the old value.

Typically, POP3 servers will freeze their state when a client connects to them and only show that client the current "view" of the messages at the point at which the client connected/authenticated. You have to disconnect to refresh that view.

I would need to see a protocol log in order to provide a more definitive answer.

You can check the [FAQ](https://github.com/jstedfast/MailKit/blob/master/FAQ.md) to see how to get one.

**Comment by apatenotre** [comment]
Hi Jeffrey, thanks for the feedback
Hypothesis confirmed: STAT returns always the same count until client disconnects
No choice but to keep 2nd implementation, then!
