### ISSUE TITLE
[Question] NoOp called in the same time as Send an issue?

### ISSUE THREAD

**Issue by SpiritBob** [jstedfast/MailKit#998]
I'm aware that there's no thread-safety for Send, but does that apply in-general to using the `SmtpClient`'s publicly available methods?

Meaning if one thread is calling say `Send`, `Verify`, `NoOp`, no other thread is allowed to use the object, until the previously called operation completes?

Or is it only an issue if two threads call the same public method?

**Comment by jstedfast** [comment]
It's a problem if more than 1 thread calls any method on SmtpClient that sends any sort of command to the server.
