### ISSUE TITLE
How is a correct ClientValidation?

### ISSUE THREAD

**Issue by CDrosos** [jstedfast/MailKit#999]
Hello, in the quickstart, in the SMTP client you say this

// For demo-purposes, accept all SSL certificates (in case the server supports STARTTLS)
				client.ServerCertificateValidationCallback = (s,c,h,e) => true;
How we should properly setup this function instead of always returning true?

**Comment by jstedfast** [comment]
I don't really have a solution that I can just give you - if I did, I would have just added it to MailKit and not bothered to leave it up to developers to deal with themselves.

You can see an example solution here: https://github.com/jstedfast/MailKit/blob/master/MailKit/MailService.cs#L306

I'm not recommending it as the best solution, just an example that you can use to get started working on your own custom solution that you can feel confident about.

I would also recommend considering a solution similar to what web browsers use when you visit a website with an unknown/untrusted SSL certificate. In other words, prompt the user.

Hope that helps.
